-- A-Level Politics Flashcards — AQA (7152)
-- Generated for the RAG Learning study app from the notes and question banks.
-- One INSERT per topic. card_order restarts at 1 within each topic.
--
-- SAFE TO RE-RUN: the DELETE below clears any previous Politics/AQA/alevel
-- rows first, so running this file twice does not duplicate cards.

-- ---------------------------------------------------------------
-- Schema: add 'level' column if not present (idempotent).
-- Politics is A-Level only, so every row below is level = 'alevel'.
-- ---------------------------------------------------------------
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'alevel'
  CHECK (level IN ('gcse','as','alevel'));

-- ---------------------------------------------------------------
-- Clear any existing Politics cards so this file is re-runnable.
-- ---------------------------------------------------------------
DELETE FROM flashcards
 WHERE subject = 'Politics' AND exam_board = 'AQA' AND level = 'alevel';


-- ===============================================================
-- PAPER 1 — GOVERNMENT AND POLITICS OF THE UK
-- ===============================================================

-- Topic 1.1 — The Constitution
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.1', 'The Constitution', 'What type of constitution does the UK have?', 'Uncodified, unentrenched and unitary (now quasi-federal). Not "unwritten" — most of it is written down, just scattered across several sources rather than collected in one document.', 1, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'Name the five sources of the UK constitution.', 'Statute law; common law (including the royal prerogative); conventions; works of authority (Erskine May, Bagehot); and treaties.', 2, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'State Dicey''s three elements of parliamentary sovereignty.', 'Parliament may make or unmake any law whatever; no body may override an Act of Parliament; and no Parliament may bind its successors.', 3, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'What is a constitutional convention?', 'An unwritten rule of political practice regarded as binding by those who operate the constitution, but not legally enforceable in the courts. E.g. the Salisbury Convention, royal assent, collective responsibility.', 4, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'Why is the Fixed-term Parliaments Act the best example of unentrenchment?', 'A significant constitutional change was made in 2011 and unmade in 2022 by ordinary legislation — within eleven years. In the USA this would require a double supermajority.', 5, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'What did Miller I (2017) decide?', 'Ministers could not use the royal prerogative to trigger Article 50, because it would remove rights conferred by statute — only Parliament could authorise it. It also held the Sewel Convention judicially unenforceable despite statutory recognition.', 6, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'What did Miller II (2019) decide?', 'The five-week prorogation was unlawful and void because it frustrated Parliament''s constitutional functions without reasonable justification. The key move was holding prorogation justiciable at all.', 7, 'alevel'),
  ('Politics', 'AQA', '1.1', 'The Constitution', 'Give two arguments for and two against codifying the UK constitution.', 'For: clarity and accessibility; entrenchment protecting rights from a temporary majority. Against: loss of flexibility; transferring the final word on contested political questions to unelected judges.', 8, 'alevel');

-- Topic 1.2 — Parliament
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.2', 'Parliament', 'How long can the Lords delay a non-money bill, and a money bill?', 'One year for a non-money public bill, one month for a money bill, under the Parliament Acts 1911 and 1949.', 1, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'What is the Salisbury Convention?', 'The House of Lords does not block legislation implementing a governing party''s manifesto commitments.', 2, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'List the stages of a public bill in the Commons.', 'First reading (formal); second reading (debate on principles); committee stage (clause-by-clause); report stage; third reading. Then the Lords, "ping-pong" on disagreement, and royal assent.', 3, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'What were the Wright reforms of 2010?', 'Select committee chairs became elected by secret ballot of the whole House and members by their parties'' backbenchers; the Backbench Business Committee was created, giving backbenchers control of the agenda for a set number of days.', 4, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'What is the "payroll vote"?', 'Around a hundred ministers and parliamentary private secretaries bound by collective responsibility to support the government — drawn from exactly the people best placed to scrutinise it.', 5, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'What is "elective dictatorship"?', 'Lord Hailsham''s 1976 term for a system in which a government commanding a disciplined Commons majority faces few effective constitutional limits between elections, because Parliament is sovereign and no court may strike its legislation down.', 6, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'Why has the Lords become more assertive since 1999?', 'The House of Lords Act removed all but 92 hereditary peers (the rest went in April 2026 under the House of Lords (Hereditary Peers) Act 2026), increasing perceived legitimacy, and no single party has held a Lords majority since. Government defeats there are now routine.', 7, 'alevel'),
  ('Politics', 'AQA', '1.2', 'Parliament', 'Why did the 2012 Lords reform bill collapse?', 'Largely over Commons primacy — an elected second chamber would claim a rival democratic mandate, threatening the supremacy the Parliament Acts established and risking gridlock.', 8, 'alevel');

-- Topic 1.3 — Prime Minister and Cabinet
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'Define collective ministerial responsibility.', 'All members of the government are bound by cabinet decisions: they must publicly support government policy or resign, and cabinet discussions remain confidential.', 1, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'When has collective responsibility been formally suspended?', 'During the 1975 and 2016 EU referendums, when ministers were free to campaign on either side — because the issue cut across party lines so sharply that enforcing unity would have split the government.', 2, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'Why has individual ministerial responsibility weakened?', 'The policy/operational distinction since the Next Steps agencies (1988); the scale of modern departments; and the fact that survival now depends on whether the PM will spend political capital defending a minister.', 3, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'What is the single biggest determinant of prime ministerial power?', 'The size of the Commons majority. Blair after 1997 and Johnson after 2019 could ignore rebels; May after 2017 suffered the largest defeat in modern history and could not pass her central policy.', 4, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'Give three pieces of evidence for the presidentialisation thesis.', 'Personalised mandates and televised leaders'' debates since 2010; "sofa government" and bilateral decision-making (criticised in the Butler Review); and the growth of the PM''s Office, Cabinet Office and special advisers.', 5, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'What is the strongest argument AGAINST presidentialisation?', 'Tenure is conditional. A PM holds office only while commanding party and cabinet support and can be removed within days — Thatcher, May, Johnson and Truss all left without losing a general election. No president faces this.', 6, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'How did cabinet constrain Thatcher and Johnson?', 'Thatcher resigned in 1990 after canvassing her cabinet individually; Johnson resigned in 2022 after more than fifty government resignations in two days.', 7, 'alevel'),
  ('Politics', 'AQA', '1.3', 'Prime Minister and Cabinet', 'What is a special adviser (SpAd)?', 'A temporary political appointee chosen personally by a minister, exempt from the civil service requirement of political impartiality, whose appointment ends when the appointing minister leaves office.', 8, 'alevel');

-- Topic 1.4 — The Judiciary
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'Why can the UK Supreme Court not strike down an Act of Parliament?', 'Parliamentary sovereignty means no court may override primary legislation, and because the constitution is uncodified and unentrenched there is no higher constitutional law against which statute can be measured.', 1, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'What does a declaration of incompatibility do?', 'Under HRA s.4, a senior court states that a statute cannot be read compatibly with Convention rights. The statute REMAINS VALID and in force; only Parliament can amend it.', 2, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'Name four protections of judicial independence in the UK.', 'Security of tenure (removal only by address from both Houses); salaries charged on the Consolidated Fund; independent appointment via the Judicial Appointments Commission; and the sub judice rule.', 3, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'What did the Constitutional Reform Act 2005 do?', 'Created the UK Supreme Court; removed the Law Lords from the legislature; stripped the Lord Chancellor of headship of the judiciary; and established the Judicial Appointments Commission.', 4, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'What are the grounds for judicial review?', 'Illegality (ultra vires); irrationality (Wednesbury unreasonableness); procedural impropriety; and incompatibility with Convention rights under the HRA.', 5, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'Why has judicial review expanded since 1997?', 'The Human Rights Act created new grounds and allowed claims domestically; devolution created competence questions; executive and agency decision-making grew; and a more rights-conscious legal culture developed.', 6, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'What was the Belmarsh case (2004)?', 'A declaration of incompatibility over the indefinite detention of foreign terror suspects. The government amended the law in response — showing s.4''s political force exceeds its legal force.', 7, 'alevel'),
  ('Politics', 'AQA', '1.4', 'The Judiciary', 'What did the Judicial Review and Courts Act 2022 do, and why does it matter?', 'It narrowed the remedies available in judicial review. Its existence is evidence both that review had become a genuine constraint, and that Parliament retains the final word over the courts.', 8, 'alevel');

-- Topic 1.5 — Devolution
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.5', 'Devolution', 'What is the difference between devolution and federalism?', 'Devolved powers are DELEGATED by a sovereign Parliament that legally retains the right to reclaim them. Federal powers are constitutionally DIVIDED and entrenched, so the centre cannot remove them.', 1, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'Which electoral systems do the three devolved legislatures use?', 'Scottish Parliament: Additional Member System. Senedd: closed-list PR since 2026 (AMS before). Northern Ireland Assembly: Single Transferable Vote, chosen to guarantee both communities representation.', 2, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'What is the Sewel Convention, and what did Miller I say about it?', 'Westminster will not NORMALLY legislate on devolved matters without consent. Miller I (2017) held it remained a political convention the courts would not enforce — despite being written into statute in 2016–17.', 3, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'Give two examples of Westminster legislating without devolved consent.', 'The EU Withdrawal legislation and the UK Internal Market Act 2020, both passed over the objections of the Scottish Parliament and the Senedd.', 4, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'What is the Barnett formula and why is it contested?', 'The Treasury mechanism adjusting devolved block grants in proportion to changes in comparable English spending, weighted by population. Contested because it allocates by POPULATION rather than assessed NEED.', 5, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'Why is the Northern Ireland Assembly structurally fragile?', 'Mandatory power-sharing links the First and deputy First Minister offices, so either community''s largest party can collapse the institutions by withdrawing. Suspensions followed in 2017–2020 (RHI) and 2022–2024 (the Protocol).', 6, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'Give three examples of devolved policy divergence.', 'Tuition fees abolished for Scottish students in Scotland; prescription charges abolished in Scotland, Wales and NI but retained in England; minimum unit alcohol pricing in Scotland and Wales.', 7, 'alevel'),
  ('Politics', 'AQA', '1.5', 'Devolution', 'What was EVEL and what happened to it?', 'English Votes for English Laws (2015) gave English MPs a veto stage over England-only legislation, answering the West Lothian question. It was abandoned as unworkable in 2021.', 8, 'alevel');

-- Topic 1.6 — Democracy and Participation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Define "democratic deficit".', 'A perceived shortfall in the accountability, legitimacy or participatory quality of a political system — e.g. FPTP disproportionality, the unelected Lords, and the royal prerogative.', 1, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Give two pieces of evidence FOR a UK participation crisis.', 'Turnout fell to 59.4% in 2001, the lowest since 1918; party membership collapsed from millions in the 1950s to a small fraction.', 2, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Give two pieces of evidence AGAINST a UK participation crisis.', 'Turnout reached ~85% in the 2014 Scottish referendum and ~72% in 2016; pressure group membership (National Trust, RSPB) far exceeds that of all political parties combined.', 3, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'What is "hapathy"?', 'Disillusionment with the available choices rather than indifference to politics — the argument that low turnout reflects a judgment that a vote will not change anything, not apathy.', 4, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Name three franchise milestones.', 'Great Reform Act 1832 (some middle-class men); Representation of the People Act 1918 (all men 21+, women 30+ with property); Equal Franchise Act 1928 (women on the same terms, at 21); 1969 (voting age 18).', 5, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Give two arguments for votes at 16.', 'At 16 a person may work and pay tax, consent to medical treatment and join the armed forces with consent; and voting is habit-forming, with the 2014 Scottish referendum showing strong engagement.', 6, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Which four statutes protect rights in the UK?', 'Human Rights Act 1998; Equality Act 2010; Freedom of Information Act 2000; Data Protection Act 2018. None is entrenched.', 7, 'alevel'),
  ('Politics', 'AQA', '1.6', 'Democracy and Participation', 'Why would a British Bill of Rights not necessarily strengthen rights?', 'Unless entrenched, it would be as repealable as the HRA — changing the CONTENT of protected rights without strengthening their SECURITY. Entrenchment is incompatible with parliamentary sovereignty as traditionally understood.', 8, 'alevel');

-- Topic 1.7 — Elections and Referendums
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'How does First Past the Post work?', '650 single-member constituencies; one vote each; the candidate with the MOST votes wins — a plurality, not necessarily a majority. No second round, no transfers.', 1, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'Give the 2015 statistic that best illustrates FPTP''s disproportionality.', 'UKIP won ~3.9 million votes and ONE seat; the SNP won ~1.5 million votes and 56 seats. FPTP rewards concentrated support and penalises dispersed support.', 2, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'Give three advantages of FPTP.', 'Usually delivers decisive single-party government able to implement a manifesto; clear accountability, since voters know whom to blame; and a single identifiable constituency MP.', 3, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'How does the Additional Member System work?', 'Two votes: one for a constituency member elected by FPTP, one for a regional party list. List seats are allocated correctively, accounting for constituency seats already won, to improve proportionality.', 4, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'Where is STV used in the UK, and why there?', 'Northern Ireland Assembly and local elections, and Scottish local elections. Chosen for NI specifically to guarantee both communities representation.', 5, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'What happened in the 2011 AV referendum?', 'Roughly 68% voted No on ~42% turnout. AV is not proportional, so reformers were divided — which removed electoral reform from the agenda for a generation.', 6, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'Why is a UK referendum result "advisory but binding"?', 'Parliament is sovereign, so the result has no legal force — but it carries such political authority that ignoring it is practically impossible, creating a clash between popular and parliamentary sovereignty.', 7, 'alevel'),
  ('Politics', 'AQA', '1.7', 'Elections and Referendums', 'Why has electoral reform stalled despite criticism of FPTP?', 'The parties with the power to legislate are precisely those FPTP advantages. Neither main party has an incentive to abolish the system delivering it majorities on a minority of the vote.', 8, 'alevel');

-- Topic 1.8 — Political Parties
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.8', 'Political Parties', 'When was the Labour Party founded, and out of what?', '1900, out of the trade union movement and socialist societies, to secure parliamentary representation for working people.', 1, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'What was the Clause IV revision of 1995?', 'Blair replaced Labour''s commitment to common ownership of the means of production with an endorsement of a dynamic market economy — symbolically decisive in signalling New Labour''s acceptance of the market.', 2, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'Contrast One Nation conservatism with the New Right.', 'One Nation: paternalism, social obligation, acceptance of state intervention and welfare to preserve stability. New Right: neo-liberal free markets, privatisation and deregulation PLUS neo-conservative social authority.', 3, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'When and how were the Liberal Democrats formed?', 'In 1988, by the merger of the Liberal Party and the Social Democratic Party (itself a 1981 breakaway from Labour).', 4, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'What happened to the Liberal Democrats after the 2010 coalition?', 'The tuition fees reversal was electorally catastrophic — the party fell from 57 seats to 8 in 2015. A case study in what FPTP and coalition do to the third party.', 5, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'Give two arguments for and two against state funding of parties.', 'For: reduces dependence on large donors; fairer competition. Against: taxpayers funding parties they oppose; entrenching existing parties and removing the incentive to build mass membership.', 6, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'Why is the UK party system hard to categorise?', 'Two-party by Westminster SEATS; multi-party by VOTES; genuinely multi-party in the devolved nations under proportional systems; and dominant-party in particular periods (1979–97, 2010–24).', 7, 'alevel'),
  ('Politics', 'AQA', '1.8', 'Political Parties', 'What is the tension in member-led leadership selection?', 'Members are far more ideologically committed than the general electorate, so it enhances internal democracy while risking leaders who command neither their parliamentary party nor broad public support — Corbyn 2015, Truss 2022.', 8, 'alevel');

-- Topic 1.9 — Pressure Groups
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'Distinguish sectional from promotional pressure groups.', 'Sectional (interest) groups represent a particular section of society with restricted membership (BMA, NFU). Promotional (cause) groups campaign for a cause with open membership (Greenpeace, Liberty).', 1, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'Distinguish insider from outsider pressure groups.', 'Insiders have regular privileged access and are routinely consulted (BMA, NFU). Outsiders lack it and rely on demonstrations, direct action and media campaigns (Extinction Rebellion).', 2, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'What is the trade-off involved in insider status?', 'Privileged access normally requires moderating demands and accepting confidentiality, which limits the group''s ability to campaign publicly or mobilise supporters.', 3, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'What most reliably predicts a pressure group''s success?', 'Whether its aims ALIGN WITH THE GOVERNMENT''S OWN AGENDA. Trade unions had substantial influence under 1970s Labour governments and almost none under Thatcher, with membership largely unchanged.', 4, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'Why is membership size a poor predictor of success?', 'The Countryside Alliance mobilised huge marches and lost on hunting; small, well-connected professional bodies routinely win. Influence tracks access and alignment, not numbers.', 5, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'What is "structural power"?', 'Influence arising from government''s dependence on business investment, employment and tax revenue — so the anticipated reaction of business constrains policy even without any active lobbying.', 6, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'Why is the Lobbying Act 2014 regarded as ineffective?', 'Its register covers only CONSULTANT lobbyists, excluding the in-house lobbyists who conduct most lobbying, while its spending restrictions chiefly burdened charities and campaigners.', 7, 'alevel'),
  ('Politics', 'AQA', '1.9', 'Pressure Groups', 'Contrast pluralism and elitism.', 'Pluralism: power is dispersed among many competing groups and government arbitrates. Elitism: influence tracks resources and access rather than numbers, so business consistently outweighs diffuse public interests.', 8, 'alevel');

-- Topic 1.10 — The European Union
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '1.10', 'The European Union', 'When did the UK join the EEC, and when did it leave the EU?', 'Joined 1973; a confirmatory referendum in 1975 (~67% Yes). Voted to leave in 2016 (52/48); formally left 31 January 2020; transition ended 31 December 2020.', 1, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'What are the four freedoms of the EU single market?', 'Free movement of goods, services, capital and people — plus a customs union with a common external tariff.', 2, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'Why was Factortame (1991) constitutionally significant?', 'UK courts disapplied part of the Merchant Shipping Act 1988 because it conflicted with EU law — the first time a UK court had set aside primary legislation.', 3, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'Distinguish the ECJ from the ECtHR.', 'The European Court of Justice is an EU institution interpreting EU law — the UK left its jurisdiction. The European Court of Human Rights is a Council of Europe body enforcing the ECHR — the UK remains subject to it. Brexit did not change this.', 4, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'Was UK sovereignty surrendered or delegated to the EU?', 'Delegated, on the strongest reading: supremacy rested on the European Communities Act 1972, an ordinary statute Parliament passed and in 2018 repealed. Critics reply that a sovereignty exercisable only by leaving the entire legal order is of limited practical value.', 5, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'Name three reasons the UK voted to leave in 2016.', 'Sovereignty and "take back control"; immigration and free movement, on which membership meant no government could act; and long-term economic and political discontent in post-industrial areas.', 6, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'What did the EU (Withdrawal) Act 2018 do?', 'Repealed the European Communities Act 1972, ending EU law supremacy and ECJ jurisdiction, while converting existing EU law into RETAINED EU LAW to avoid legal gaps.', 7, 'alevel'),
  ('Politics', 'AQA', '1.10', 'The European Union', 'How did Brexit strain the devolution settlement?', 'Returning competences in devolved fields raised whether they should pass to the devolved bodies or be held centrally. The UK Internal Market Act 2020 was passed over withheld consent, exposing Sewel''s lack of legal force.', 8, 'alevel');

-- ===============================================================
-- PAPER 2 — GOVERNMENT AND POLITICS OF THE USA AND COMPARATIVE POLITICS
-- ===============================================================

-- Topic 2.1 — The US Constitution and Federalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'When was the US Constitution drafted, and how many amendments has it had?', 'Drafted 1787 at the Philadelphia Convention, in force from 1789. 27 amendments — the first ten (the Bill of Rights) ratified together in 1791.', 1, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'State the US constitutional amendment process.', 'Proposal by two-thirds of BOTH houses of Congress (or a national convention called by two-thirds of states, never used); ratification by three-quarters of state legislatures or conventions.', 2, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'What is the difference between separation of powers and checks and balances?', 'Separation of powers puts legislative, executive and judicial functions in separate institutions with separate personnel. Checks and balances deliberately OVERLAP them, giving each branch specific powers to limit the others.', 3, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'Define enumerated, implied and reserved powers.', 'Enumerated: expressly granted to the federal government. Implied: inferred via the necessary and proper (elastic) clause. Reserved: under the Tenth Amendment, everything not delegated federally nor prohibited to the states.', 4, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'How did the commerce clause expand federal power?', 'From the New Deal the Court accepted Congress could regulate almost any activity substantially affecting interstate commerce — underpinning federal regulation of wages, agriculture, civil rights and the environment. Partially reversed in US v Lopez (1995).', 5, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'What is fiscal federalism and why does it matter?', 'Federal income tax gave Washington revenues states could not match, and CONDITIONAL GRANTS let it direct state policy where it cannot legislate directly — e.g. the national minimum drinking age via highway funding. It circumvents the constitutional division entirely.', 6, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'Contrast dual and cooperative federalism.', 'Dual ("layer cake", founding–1930s): federal and state governments in largely distinct spheres. Cooperative ("marble cake", New Deal onwards): shared functions, with federal grants funding state-administered programmes.', 7, 'alevel'),
  ('Politics', 'AQA', '2.1', 'The US Constitution and Federalism', 'Why does entrenchment transfer constitutional authorship to the Supreme Court?', 'Because formal amendment is practically unattainable, constitutional change happens through judicial INTERPRETATION instead — which is why appointments are fought over so fiercely.', 8, 'alevel');

-- Topic 2.2 — Congress
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.2', 'Congress', 'Give the size and term length of each chamber of Congress.', 'House: 435 voting members, two-year terms, entire chamber re-elected each cycle. Senate: 100 (two per state), six-year terms, one-third elected every two years.', 1, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'Name the Senate''s exclusive powers.', 'Confirming presidential appointments (simple majority); ratifying treaties (two-thirds); trying impeachments (conviction needs two-thirds).', 2, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'Name the House''s exclusive powers.', 'Initiating revenue bills; bringing impeachment charges (simple majority); electing the President if no Electoral College majority.', 3, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'What is the filibuster and how is it ended?', 'Use of the Senate''s unlimited debate to delay or block a vote. Ended by cloture, normally requiring 60 of 100 senators — so it functions as a de facto supermajority requirement for most legislation.', 4, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'When was the filibuster removed, and for what?', 'For lower federal court nominations in 2013 and for Supreme Court nominations in 2017. It remains for legislation.', 5, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'Why do congressional incumbents almost always win?', 'Name recognition, franked mail, staff and casework; superior fundraising, since donors back likely winners; and safe districts from gerrymandering and geographic sorting. House re-election exceeds 90%.', 6, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'Why do safe districts drive polarisation?', 'Where the general election is a formality, the only real threat is a PRIMARY challenge from the ideological flank — so members are rewarded for purity and punished for compromise.', 7, 'alevel'),
  ('Politics', 'AQA', '2.2', 'Congress', 'Why does congressional oversight vary in vigour?', 'It tracks PARTISAN ADVANTAGE, not constitutional duty. Under divided government committees investigate aggressively; under unified government the same powers go largely unused.', 8, 'alevel');

-- Topic 2.3 — The Presidency
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.3', 'The Presidency', 'Name four formal powers of the US President.', 'The veto (overridable by two-thirds of both chambers); Commander-in-Chief; nominating judges and senior officials (subject to Senate confirmation); negotiating treaties (subject to two-thirds ratification); the federal pardon power.', 1, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'What is Neustadt''s central argument about presidential power?', 'The formal powers are largely NEGATIVE — they let a President prevent outcomes, not produce them. Effective presidents therefore build bargaining advantage: "the power of the presidency is the power to persuade".', 2, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'What is an executive order, and what is its weakness?', 'A directive to the federal executive branch with the force of law, requiring no congressional approval. Weakness: a successor can revoke it immediately, and courts can strike it down — so policy oscillates rather than settles.', 3, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'Why do presidents prefer executive agreements to treaties?', 'They avoid the two-thirds Senate ratification threshold. The cost is impermanence — a successor can withdraw unilaterally, as with the Iran nuclear agreement and the Paris accord.', 4, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'What does EXOP consist of, and why does it matter?', 'The White House Office, the National Security Council and the Office of Management and Budget. Its staff mostly need no Senate confirmation, so power has shifted from the cabinet to a circle of personally loyal advisers.', 5, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'Why is the War Powers Resolution 1973 largely ineffective?', 'Presidents dispute its constitutionality and have acted without explicit authorisation, while Congress has proved politically unwilling to cut off funding for deployed troops. There has been no declaration of war since 1942.', 6, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'State the imperial presidency thesis and the counter-thesis.', 'Imperial (Schlesinger, 1973): presidents have accumulated power beyond constitutional limits, especially over war and secrecy. Imperilled: they routinely fail to pass priorities, lose midterms, see orders reversed, and have been impeached.', 7, 'alevel'),
  ('Politics', 'AQA', '2.3', 'The Presidency', 'Why does presidential power vary within a single term?', 'The formal powers are constant; POLITICAL CAPITAL varies — the honeymoon period, midterm losses, lame duck status, approval ratings and events. Major achievements are heavily front-loaded.', 8, 'alevel');

-- Topic 2.4 — The Supreme Court and the Judicial Branch
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'How many Supreme Court justices are there, and for how long do they serve?', 'Nine, appointed for life during good behaviour.', 1, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'What did Marbury v Madison (1803) establish?', 'Judicial review — the power to declare Acts of Congress, executive actions and state laws unconstitutional. It is NOT granted by the Constitution; the Court asserted it.', 2, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'What is the writ of certiorari?', 'The order by which the Supreme Court agrees to review a lower court decision. It grants review in only a small fraction of petitions, which is a significant agenda-setting power. The "rule of four": four justices must agree.', 3, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'Why are Supreme Court appointments so politicised?', 'Life tenure means one appointment can shape constitutional interpretation for thirty years or more, and because amendment is near-impossible the Court effectively decides the most contested questions.', 4, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'What was the Garland/Barrett episode?', 'The Senate refused to consider the Garland nomination in 2016 on election-year grounds, then rapidly confirmed Barrett weeks before the 2020 election — the same argument applied and abandoned within four years.', 5, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'Contrast originalism with the living Constitution approach.', 'Originalism: interpret according to the text''s meaning when adopted (Dobbs, Second Amendment cases). Living Constitution: apply in light of contemporary values (Brown, Roe, Obergefell). Neither removes judicial discretion as fully as it claims.', 6, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'Name four limits on the Supreme Court.', 'No enforcement machinery; it is reactive and cannot initiate cases; Congress controls appellate jurisdiction and the number of justices; and rulings can be reversed by the Court itself or by amendment.', 7, 'alevel'),
  ('Politics', 'AQA', '2.4', 'The Supreme Court and the Judicial Branch', 'Why is the Court''s political character arguably structural rather than a failing?', 'An entrenched constitution that is nearly impossible to amend NECESSARILY transfers political authorship to whoever interprets it. The Court''s power follows from the amendment thresholds, not from judicial ambition.', 8, 'alevel');

-- Topic 2.5 — Elections and Direct Democracy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'How does the Electoral College work?', 'Each state has electors equal to its House members plus two senators; DC has three, giving 538. 270 are needed to win. Almost all states allocate winner-take-all; Maine and Nebraska allocate partly by district.', 1, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'How many times has a President lost the popular vote but won?', 'Five times in total, twice since 2000 — in 2000 and 2016.', 2, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'Give two defences of the Electoral College.', 'It preserves the federal character of the union and requires geographically broad support; and it produces a clear result while localising disputes — a recount concerns one state, not 150 million ballots.', 3, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'Contrast a primary with a caucus.', 'A primary is a state-run secret-ballot election. A caucus is a party-run meeting where supporters gather and publicly declare preference — demanding far more time, so turnout is low and participants are committed activists.', 4, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'What is the invisible primary?', 'The period before formal voting, during which candidates build funding, endorsements and name recognition. It screens out those who cannot raise money — though Trump in 2016 showed media attention can substitute.', 5, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'Distinguish a PAC from a Super PAC.', 'A PAC donates directly to candidates within strict limits. A Super PAC may raise and spend UNLIMITED sums on independent advocacy but may not donate to or coordinate with a campaign.', 6, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'What did Citizens United v FEC (2010) decide, and why can Congress not simply reverse it?', 'Independent political spending by corporations, unions and associations is protected First Amendment speech. Because spending restrictions are treated as SPEECH restrictions, reform requires an amendment or the Court reversing itself.', 7, 'alevel'),
  ('Politics', 'AQA', '2.5', 'Elections and Direct Democracy', 'Name the three forms of US direct democracy — and where they do NOT exist.', 'Initiative, referendum and recall, all at STATE level only. There is no provision for a national referendum.', 8, 'alevel');

-- Topic 2.6 — US Political Parties
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'Why does the USA have a two-party system?', 'Winner-take-all single-member districts and the Electoral College mean dispersed support wins nothing (Duverger''s law); plus ballot access rules, debate thresholds, and major parties absorbing third-party issues.', 1, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'What happened to Ross Perot in 1992?', 'He won around 19% of the popular vote and ZERO electoral votes — the starkest illustration of what winner-take-all rules do to dispersed support.', 2, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'What is ideological sorting?', 'Until the 1960s both parties contained conservative southern Democrats and liberal northern Republicans. The civil rights realignment eliminated that overlap, so polarisation is partly parties becoming CONSISTENT rather than anyone becoming more extreme.', 3, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'Name three consequences of polarisation for US government.', 'Legislative gridlock (the filibuster requires bipartisan majorities that no longer exist); displacement of policy-making to the executive and courts; and erosion of institutional norms.', 4, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'Give two pieces of evidence that US parties have been RENEWED.', 'Party-line voting in Congress is at historic highs; partisan identification predicts vote choice more reliably than in decades, and split-ticket voting has collapsed.', 5, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'Give the strongest evidence that US parties remain WEAK.', 'They cannot control who runs under their label — primaries let voters nominate candidates the leadership opposes (Trump 2016), and candidates fund and organise independently. There is no deselection power.', 6, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'How should the decline/renewal debate be resolved?', 'Parties have become STRONGER as ideological identities and WEAKER as organisations — the two describe different dimensions rather than contradicting each other.', 7, 'alevel'),
  ('Politics', 'AQA', '2.6', 'US Political Parties', 'What is the spoiler effect?', 'A third-party candidate splitting a major party''s vote and changing which major party wins — Nader in Florida in 2000 is the standard example.', 8, 'alevel');

-- Topic 2.7 — US Pressure Groups
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'Why are pressure groups more powerful in the USA than the UK?', 'Many access points from separation of powers and federalism; weak party discipline making individual legislators persuadable; expensive candidate-centred elections; and entrenched rights making litigation a route to permanent change.', 1, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'What is the crucial qualification to US group power?', 'Many access points are also many VETO points — US groups are better at BLOCKING than achieving. A UK group that persuades a government with a secure majority sees its aim legislated in full.', 2, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'What is an iron triangle?', 'A stable, mutually beneficial relationship between a congressional committee, a federal agency and an interest group — each supplying what the others need, insulating a policy area from wider scrutiny.', 3, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'What is an issue network, and how does it differ?', 'A looser, more open and competitive set of actors in a contested policy area such as healthcare or the environment — far less closed than the classic iron triangle.', 4, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'Why was the NRA historically so effective?', 'Less through total spending than through a large, intensely motivated single-issue membership that would vote on that issue alone in primaries — combined with scorecards, making opposition electorally dangerous.', 5, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'Why do US groups litigate so heavily?', 'Because the Constitution is entrenched, a ruling that a law is unconstitutional applies nationwide and is reversible only by the Court or an unattainable amendment. The NAACP''s strategy culminating in Brown is the model.', 6, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'What is the revolving door?', 'Movement of personnel between government office and lobbying firms or the industries they regulated — giving firms privileged access and creating incentives for officials to favour future employers.', 7, 'alevel'),
  ('Politics', 'AQA', '2.7', 'US Pressure Groups', 'Summarise the pluralist/elitist debate on US groups.', 'Pluralism (Dahl): any interest can organise and compete, so power is dispersed. Elitism (Mills): influence tracks money and access, not numbers. Common resolution: pluralist in FORM, elitist in EFFECT.', 8, 'alevel');

-- Topic 2.8 — Civil Rights
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'What do the Thirteenth, Fourteenth and Fifteenth Amendments do?', '13th (1865) abolished slavery; 14th (1868) guaranteed citizenship, due process and EQUAL PROTECTION binding on the states; 15th (1870) prohibited denial of the vote on grounds of race.', 1, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'What did Plessy v Ferguson (1896) and Brown v Board (1954) each decide?', 'Plessy upheld "separate but equal", legitimising Jim Crow. Brown held segregated public schooling inherently unequal and unconstitutional, overturning Plessy — under the SAME amendment.', 2, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'What did the Civil Rights Act 1964 and Voting Rights Act 1965 do?', 'The CRA prohibited discrimination in employment, education and public accommodation with federal enforcement. The VRA outlawed literacy tests and introduced PRE-CLEARANCE for jurisdictions with a history of discrimination.', 3, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'What did Shelby County v Holder (2013) do?', 'Struck down the VRA coverage formula, rendering pre-clearance inoperative. Several formerly covered states then introduced voter ID, reduced early voting, closed polling places and purged rolls.', 4, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'Why did the civil rights movement need litigation, direct action AND legislation?', 'Litigation established that segregation was unconstitutional; direct action created the political pressure that made federal action possible; legislation supplied enforcement machinery and reached PRIVATE discrimination.', 5, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'Trace the affirmative action cases.', 'Bakke (1978): quotas unconstitutional, but race may be one factor. Grutter (2003): upheld race-conscious admissions on diversity grounds. SFFA v Harvard (2023): race-conscious admissions held unconstitutional.', 6, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'What did Dobbs v Jackson (2022) do?', 'Overturned Roe v Wade, removing the federal constitutional right to abortion and returning regulation to the states — producing sharply divergent state laws.', 7, 'alevel'),
  ('Politics', 'AQA', '2.8', 'Civil Rights', 'Why does the route by which a right was won matter?', 'Amendment is most secure but unattainable; judicial interpretation is fastest but reversible by a changed Court (Dobbs); legislation reaches private discrimination but can be weakened without repeal (Shelby County).', 8, 'alevel');

-- Topic 2.9 — Comparative — Constitutional Arrangements
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Name the three comparative approaches.', 'STRUCTURAL (institutions and constitutional rules); RATIONAL (individuals making calculated choices to advance their own interests); CULTURAL (shared ideas, values, beliefs and historical experience).', 1, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Give the four key constitutional differences between the UK and USA.', 'Codified vs uncodified; entrenched vs unentrenched; popular sovereignty via the Constitution vs parliamentary sovereignty; separation vs fusion of powers. Plus federal vs unitary-with-devolution.', 2, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Give three genuine similarities between the two constitutions.', 'Both are liberal democracies with the rule of law and an independent judiciary; both disperse power territorially; both have become more rights-focused, with courts more assertive since the late twentieth century.', 3, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Give the structural explanation for why the US constitution changes less.', 'The double supermajority lets a minority of states block any amendment, and separation of powers, bicameralism, federalism and the filibuster multiply veto points. The UK has almost none.', 4, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Give the cultural explanation for the difference between the two constitutions.', 'The USA was created by revolution against arbitrary power, producing distrust expressed in a written limiting text. The UK evolved gradually with no founding moment at which a comprehensive text could be written.', 5, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Give the rational explanation for why UK governments resist codification.', 'It would bind the governing party''s own freedom of action and transfer power to judges. No party in office has an incentive to surrender flexibility it currently enjoys.', 6, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'How should the three approaches be related to each other?', 'They are complementary: CULTURE explains why the institutions were adopted; STRUCTURE explains the constraints they impose; RATIONAL CHOICE explains how actors behave within them.', 7, 'alevel'),
  ('Politics', 'AQA', '2.9', 'Comparative — Constitutional Arrangements', 'Is the UK converging on the US model?', 'Partly — devolution, the HRA, a separate Supreme Court and referendums all move in that direction. But parliamentary sovereignty survives, so the UK has adopted US-style institutions WITHOUT the feature that defines the US model: entrenchment.', 8, 'alevel');

-- Topic 2.10 — Comparative — The Executives
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Give three differences between the UK PM and the US President.', 'Selection (party leader with a Commons majority vs separately elected); tenure (removable by their party at any time vs a fixed four-year term); powers (no veto and not head of state vs both).', 1, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Name four UK PMs since 1990 forced out by their own party without losing a general election.', 'Thatcher (1990), May (2019), Johnson (2022) and Truss (2022) — a constraint with no US parallel.', 2, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Why does a US President struggle to legislate where a PM does not?', 'Separation of powers means no guaranteed majority and frequent divided government; multiple veto points including the filibuster; and weak party discipline. A PM commands a Commons majority BY DEFINITION.', 3, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Why is the presidential veto arguably evidence of WEAKNESS?', 'A PM needs no veto because a PM who opposes a bill simply prevents its introduction. The President needs one precisely because Congress can legislate without them.', 4, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Contrast the UK and US cabinets.', 'The UK cabinet is a COLLECTIVE body of parliamentarians bound by collective responsibility whose withdrawal of support ends a premiership. US secretaries are INDIVIDUAL advisers who cannot remove a President.', 5, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Give the rational explanation for the discipline gap.', 'UK MPs depend on the party for nomination, the label and promotion, so rebellion is costly. US legislators win primaries, fund their own campaigns and cannot be deselected, so independence is costless.', 6, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'Name two functional similarities between the executives.', 'Both can act unilaterally without new legislation — executive orders and the royal prerogative — and both have had those powers constrained by courts (Miller I/II; Youngstown). Both face weakest checks in foreign policy.', 7, 'alevel'),
  ('Politics', 'AQA', '2.10', 'Comparative — The Executives', 'How should "who is more powerful" be answered?', 'Each is more powerful in DIFFERENT DIMENSIONS: the PM over legislation when commanding a majority, the President in tenure security and unilateral action. The PM''s power is entirely conditional.', 8, 'alevel');

-- Topic 2.11 — Comparative — The Judiciaries
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'Give the single structural variable explaining the difference in the two courts'' power.', 'ENTRENCHMENT. It gives the US Court a higher law to enforce and makes its rulings effectively final; the UK has neither, so its Court can only interpret or declare incompatibility.', 1, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'Contrast how the two supreme courts are appointed.', 'US: nominated by the President, confirmed by a Senate voting on near-party lines, since 2017 by simple majority. UK: selected on merit by an independent Judicial Appointments Commission.', 2, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'Give the rational explanation for why US appointments are politicised and UK ones are not.', 'A US justice can strike down legislation and serves for life, so one appointment can determine policy for decades — heavy investment is rational. A UK justice cannot invalidate statute and faces a retirement age, so the return is too low.', 3, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'Give three similarities between the two judiciaries.', 'Both review executive action and have rejected claims it is beyond judicial reach (Miller I/II; US v Nixon); both are significant rights actors; both have faced political backlash and proposals to curb their power.', 4, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'How does UK judicial influence exceed its formal powers?', 'HRA s.3 allows courts to shape statutory meaning substantially; declarations of incompatibility are almost always acted upon; and judicial review of executive action is unqualified, reaching most of what government does.', 5, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'How can any UK court ruling be reversed?', 'By an ordinary Act of Parliament — e.g. the Judicial Review and Courts Act 2022 reversed the Cart (2011) ruling, and the Safety of Rwanda (Asylum and Immigration) Act 2024 legislated to override the Supreme Court''s 2023 finding that Rwanda was unsafe. A US constitutional ruling can realistically be reversed only by the Court itself.', 6, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'Why does the "too political" charge have more force in the USA?', 'There, appointments are openly partisan and precedent has been reversed following changes in composition (Dobbs). In the UK the criticism concerns RULINGS on executive power, not the process that produced the judges.', 7, 'alevel'),
  ('Politics', 'AQA', '2.11', 'Comparative — The Judiciaries', 'Give the cultural explanation for the difference in judicial prominence.', 'American political argument frames contested moral questions as constitutional rights claims, making the Court the arena for national moral conflict. The British tradition seeks remedy through Parliament.', 8, 'alevel');

-- Topic 2.12 — Comparative — Electoral and Party Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'What do the UK and USA share electorally, and what follows from it?', 'Both use single-member plurality for their main legislative chamber, and both have two dominant parties — Duverger''s law operating despite very different political cultures.', 1, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Why does the UK sustain third parties at Westminster and the USA not?', 'Geography. FPTP rewards CONCENTRATED support: the SNP won 56 seats on ~1.5m votes in 2015 while UKIP won one on ~3.9m. US third-party support is dispersed nationally.', 2, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Give the three resources that explain the party discipline gap.', 'Nomination (UK parties control it and can deselect; US primaries mean they cannot), campaign funding, and promotion. Discipline is strong where the party controls all three and weak where it controls none.', 3, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Contrast UK and US campaign finance.', 'UK: statutory spending limits, no paid political TV advertising, weeks-long campaigns. USA: effectively unlimited independent expenditure after Citizens United, TV advertising dominant, campaigns over a year long.', 4, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Why can the USA not legislate campaign finance reform?', 'Because the Court treats spending restrictions as SPEECH restrictions, reform requires an amendment or the Court reversing itself. The UK regulates by ordinary statute whenever it chooses.', 5, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Why is polarisation more pronounced in the USA?', 'Ideological sorting removed the cross-party overlap; safe districts make primaries the real contest; separation of powers turns polarisation into gridlock; and a deregulated partisan media has no UK equivalent.', 6, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Why did UK polarisation over Brexit have different effects?', 'It cut ACROSS parties rather than aligning with them, producing internal party crises rather than inter-party deadlock.', 7, 'alevel'),
  ('Politics', 'AQA', '2.12', 'Comparative — Electoral and Party Systems', 'Are the two party systems converging?', 'The TRENDS converge — dealignment, polarisation, insurgent challenges, wider leadership selection. The INSTITUTIONS do not — no UK primaries, capped spending, and parliamentary sovereignty.', 8, 'alevel');

-- Topic 2.13 — Comparative — Pressure Groups
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'Give the structural reason US pressure groups are more powerful.', 'Separation of powers and federalism create many access points — a bill must pass the House, the Senate, the filibuster, the President and judicial review, and fifty states exist besides. A group needs to win at only ONE point to block.', 1, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'Why do UK groups target ministers and US groups target legislators?', 'The UK executive controls the legislative agenda and commands a disciplined majority, so ministers are the decisive target. US legislators vote independently, so persuading or funding one can change an outcome.', 2, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'What lever do US groups have that UK groups structurally cannot?', 'Primary funding — the ability to threaten a legislator''s RENOMINATION. The UK has no primaries, so no equivalent exists.', 3, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'Contrast the value of litigation for UK and US groups.', 'US groups can have LEGISLATION struck down permanently. UK groups can only challenge the legality of EXECUTIVE action, and Parliament can reverse any ruling by ordinary statute.', 4, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'Give three similarities in group activity across the two countries.', 'Both rely on supplying specialist expertise; in both, success depends mainly on alignment with the governing agenda; both have lobbying registers criticised as inadequate and face the revolving door.', 5, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'How has UK group activity moved towards the US pattern?', 'Devolution created additional access points; the HRA and expanded judicial review made courts a serious arena; and commercial lobbying and a revolving door have developed.', 6, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'What are the three structural barriers to full convergence?', 'No primaries; statutory campaign spending limits; and parliamentary sovereignty meaning courts cannot strike down statute.', 7, 'alevel'),
  ('Politics', 'AQA', '2.13', 'Comparative — Pressure Groups', 'Do elitist critiques apply to both systems?', 'Yes — in both, influence tracks resources rather than numbers, and business enjoys STRUCTURAL power because governments depend on investment and employment. Both are pluralist in form, elitist in effect.', 8, 'alevel');

-- Topic 2.14 — Comparative — Civil Rights
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Contrast the legal basis of rights in the UK and USA.', 'US rights are entrenched in the Constitution, beyond legislative repeal. UK rights rest on ordinary statute — the HRA 1998 and Equality Act 2010 — repealable by a simple Commons majority.', 1, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Contrast the judicial remedies available in each country.', 'US courts can STRIKE DOWN rights-violating legislation, making it void. UK courts can only issue a declaration of incompatibility, which leaves the statute valid and in force.', 2, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Why are UK rights more uniform than US rights?', 'Equality law is reserved for Scotland and Wales (Equality Act 2010 covers Great Britain; NI has its own equality law) and the HRA applies UK-wide and is protected from devolved amendment. US federalism reserves elections, policing, education and (since Dobbs) abortion to the states, so entitlements vary by residence.', 3, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Explain the paradox of rights security in the two systems.', 'US rights are legally secure but vulnerable to REINTERPRETATION (Dobbs reversed a fifty-year precedent). UK rights are legally fragile but practically stable — no government has actually repealed them.', 4, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Why did the US judiciary drive rights change where the UK judiciary did not?', 'Entrenched enforceable rights let US courts bypass hostile majorities and deliver permanent nationwide change (Brown). With no such power, UK advances came through LEGISLATION — the Race Relations Acts, the Equality Act 2010.', 5, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Name two stabilisers protecting UK rights despite the absence of entrenchment.', 'Continuing ECHR membership means repeal of the HRA would not remove the underlying obligations; and Convention rights are written into the devolution settlements.', 6, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'Give three similarities in how rights advanced in both countries.', 'Both combined litigation, legislation and social movement campaigning; in both the judiciary became a more significant rights actor from the late twentieth century; in both, rights have been restricted by counter-terrorism legislation.', 7, 'alevel'),
  ('Politics', 'AQA', '2.14', 'Comparative — Civil Rights', 'How should "which system protects rights better" be answered?', 'The USA protects rights better against LEGISLATURES; the UK protects them better against COURTS. Which matters more depends on which institution is currently more hostile to the right in question.', 8, 'alevel');

-- ===============================================================
-- PAPER 3 — POLITICAL IDEAS
-- ===============================================================

-- Topic 3.1 — Liberalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.1', 'Liberalism', 'Name the five AQA key thinkers for liberalism.', 'John Locke, Mary Wollstonecraft, John Stuart Mill, John Rawls and Betty Friedan.', 1, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'Distinguish negative from positive freedom.', 'Negative: the absence of external constraint — a person is free if no one prevents them acting (classical). Positive: the actual capacity to act and develop, so poverty and ignorance are themselves constraints (Green, modern).', 2, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'What is Locke''s "fiduciary power"?', 'Government holds authority IN TRUST for the people. If that trust is broken they may withdraw it — which grounds a right of rebellion.', 3, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'State Mill''s harm principle.', 'The only legitimate ground for restricting an individual''s liberty is to prevent harm to OTHERS. A person''s own good is never sufficient warrant — ruling out state paternalism and the legal enforcement of morality.', 4, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'Explain Rawls''s veil of ignorance and difference principle.', 'Principles of justice are chosen from an original position where no one knows their own class, talents, gender or race. Rational choosers would pick equal basic liberties plus the difference principle: inequalities are justified only if they benefit the LEAST ADVANTAGED.', 5, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'Why is Wollstonecraft''s argument important for liberalism?', 'She did not attack liberalism — she convicted it of INCONSISTENCY WITH ITSELF. If rights derive from rationality and women are equally rational, denying them rights contradicts liberalism''s own foundations.', 6, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'Why is Mill described as the bridge between classical and modern liberalism?', 'His defence of negative freedom and the harm principle is classical, but his emphasis on individuality and self-development pointed towards the developmental arguments modern liberals used to justify an enabling state.', 7, 'alevel'),
  ('Politics', 'AQA', '3.1', 'Liberalism', 'What is Berlin''s warning about positive freedom?', 'It permits others to define what a person''s "real" interests are and to coerce them accordingly, in the name of their own liberty. (Nozick''s case against redistribution rests on a different ground: self-ownership and his entitlement theory.)', 8, 'alevel');

-- Topic 3.2 — Conservatism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.2', 'Conservatism', 'Name the five AQA key thinkers for conservatism.', 'Thomas Hobbes, Edmund Burke, Michael Oakeshott, Ayn Rand and Robert Nozick.', 1, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'Explain the conservative view of human imperfection.', 'Threefold: PSYCHOLOGICAL (needy, restless, requiring security and order); MORAL (capable of selfishness and cruelty, so law and authority are necessary); INTELLECTUAL (reason is limited and society too complex to redesign).', 2, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'Why do conservatives value tradition?', 'It embodies ACCUMULATED PRACTICAL WISDOM — institutions that survived have been tested by generations of experience, which is more reliable than any single generation''s reasoning. Burke: a partnership between the living, the dead and those yet to be born.', 3, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'What does Burke mean by "change in order to conserve"?', 'A state without the means of some change is without the means of its conservation. Reform is the CONDITION of preservation — but it must grow out of existing practice rather than from an abstract blueprint.', 4, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'Why did Burke sympathise with the American colonists but oppose the French Revolution?', 'His test was not whether change occurred but whether it GREW FROM existing practice. The Americans defended established rights against Crown innovation; the French destroyed an inheritance to build from theory.', 5, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'Summarise Oakeshott''s critique of rationalism.', 'Abstract theory cannot capture the complexity of social practice. Rationalists recognise only TECHNICAL knowledge (writable as rules) and discard PRACTICAL knowledge (acquired through experience) — the very wisdom that makes governing possible.', 6, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'What is Nozick''s entitlement theory?', 'A distribution is just if holdings were justly acquired and justly transferred, REGARDLESS of the resulting pattern. Redistributive taxation violates self-ownership by treating a person''s labour as a resource for others — a direct attack on Rawls.', 7, 'alevel'),
  ('Politics', 'AQA', '3.2', 'Conservatism', 'Why do Rand and Nozick sit uneasily within conservatism?', 'They ground politics in abstract rational individualism — precisely what Burke and Oakeshott identify as the error that produced the French Revolution — and their programme would dismantle established institutions rather than conserve them.', 8, 'alevel');

-- Topic 3.3 — Socialism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.3', 'Socialism', 'Name the AQA key thinkers for socialism.', 'Karl Marx and Friedrich Engels (counted together), Rosa Luxemburg, Beatrice Webb, Anthony Crosland and Anthony Giddens.', 1, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'Explain the socialist view of human nature.', 'MALLEABLE, not fixed. Competitive and acquisitive behaviour is a PRODUCT of capitalist social relations rather than inherent, and human beings have a natural capacity for cooperation that different institutions would allow to flourish.', 2, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'What is surplus value?', 'Workers produce more value than they receive in wages; the difference is appropriated by the capitalist as profit. Exploitation is therefore STRUCTURAL, not the fault of individual employers — which is why Marx held it cannot be reformed away.', 3, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'What is alienation?', 'Under capitalism workers are estranged from the product of their labour, from the act of production, from their own human potential, and from one another — work becomes a means of survival rather than an expression of creativity.', 4, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'What did Luxemburg argue against Bernstein AND against Lenin?', 'Against Bernstein: reforms improve conditions but can never abolish exploitation, since ownership is untouched. Against Lenin: a vanguard party substituting itself for the class would end in the dictatorship of a few over the proletariat.', 5, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'What did the Fabian "inevitability of gradualness" (Sidney Webb''s 1923 phrase, a view Beatrice Webb shared) mean?', 'Socialism would arrive through incremental reform within existing democratic institutions, as the electorate came to recognise its merits — with the state treated as a NEUTRAL instrument capturable through elections.', 6, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'What did Crosland argue in The Future of Socialism (1956)?', 'Managerial capitalism had separated ownership from control, so nationalisation was unnecessary. Socialism should be redefined around EQUALITY, achieved by taxing the proceeds of growth and funding welfare and comprehensive education.', 7, 'alevel'),
  ('Politics', 'AQA', '3.3', 'Socialism', 'What is the crucial distinction between Crosland and Giddens?', 'Crosland changed the INSTRUMENT but kept the goal (a substantial reduction in outcome inequality — "democratic equality", not absolute equality). Giddens narrowed the GOAL itself to equality of opportunity — which is why the Third Way''s socialist credentials are genuinely contested.', 8, 'alevel');

-- Topic 3.4 — Nationalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.4', 'Nationalism', 'Name the AQA key thinkers for nationalism.', 'Jean-Jacques Rousseau, Johann Herder, Giuseppe Mazzini, Marcus Garvey and Charles Maurras.', 1, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'Distinguish civic from ethnic nationalism.', 'Civic defines the nation by shared political values and citizenship — membership is voluntary and inclusive. Ethnic defines it by common descent and inherited culture — membership is inherited and exclusive.', 2, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'What is Herder''s Volksgeist?', 'The unique spirit or character of a people, expressed in its language, folklore, customs and history. Herder celebrated the distinctiveness of ALL cultures, implying their equal worth — he was not a chauvinist.', 3, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'What is Rousseau''s general will, and why does it matter for nationalism?', 'The collective will of a people directed at the common good. He predates nationalism, but the idea that a PEOPLE is the source of authority provided the foundation for the claim that nations should rule themselves.', 4, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'Summarise Mazzini''s liberal nationalism.', 'Every nation has an EQUAL right to self-determination; nations are like individuals, each entitled to freedom. A world of free self-governing nations would cooperate peacefully — so nationalism and internationalism are compatible.', 5, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'Summarise Maurras''s integral nationalism.', 'The nation is an organic whole to which the individual is entirely subordinate. Authoritarian, anti-democratic, hostile to liberalism, and exclusive — defining the nation by descent and treating outsiders as alien.', 6, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'What was Marcus Garvey''s contribution?', 'Black nationalism and pan-Africanism — racial pride and self-reliance in response to slavery, colonialism and racial oppression, showing nationalism functioning as a vehicle of LIBERATION for a dispersed people.', 7, 'alevel'),
  ('Politics', 'AQA', '3.4', 'Nationalism', 'Why is nationalism called a "cross-cutting" ideology?', 'It attaches to others rather than standing alone. With liberalism it produces Mazzini; with reactionary conservatism, Maurras; with socialism, anti-colonial movements. The premise that peoples should govern themselves does not determine WHO COUNTS as the people.', 8, 'alevel');

-- Topic 3.5 — Feminism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.5', 'Feminism', 'Name the AQA key thinkers for feminism.', 'Charlotte Perkins Gilman, Simone de Beauvoir, Kate Millett, Sheila Rowbotham and bell hooks.', 1, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'Distinguish sex from gender, and explain why it matters.', 'Sex is biological difference; gender is the socially constructed roles and expectations attached to it. It matters because it undermines the claim that women''s subordinate position is natural and therefore inevitable.', 2, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'Define patriarchy.', 'A system of social structures, practices and beliefs through which men as a group dominate women as a group — identifying subordination as SYSTEMIC rather than the product of individual prejudice.', 3, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'Explain de Beauvoir''s two central claims.', '"One is not born, but rather becomes, a woman" — femininity is socially constructed. And woman as "the OTHER" — defined in relation to man as the norm, and therefore as deviation rather than as an autonomous subject.', 4, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'What does "the personal is political" mean, and what did it achieve?', 'Private-sphere relationships are structured by power and are properly political. It made domestic violence, marital rape, unpaid domestic labour and reproductive rights into political questions requiring public remedy.', 5, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'Summarise Gilman''s argument.', 'Women''s subordination is rooted in ECONOMIC DEPENDENCE on men, reinforced by confinement to the domestic sphere. Her solution was socialising domestic labour — communal kitchens, laundries and childcare.', 6, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'Summarise socialist feminism (Rowbotham).', 'Women''s oppression is bound up with capitalism: unpaid domestic labour reproduces the workforce at no cost to employers, and women act as a cheap RESERVE ARMY OF LABOUR. Women have been "hidden from history".', 7, 'alevel'),
  ('Politics', 'AQA', '3.5', 'Feminism', 'What is intersectionality, and what did hooks criticise?', 'Race, class and gender oppression INTERLOCK rather than adding up. hooks argued mainstream feminism presented white middle-class experience as universal — Friedan''s frustrated housewife did not describe black women who had always worked from necessity.', 8, 'alevel');

-- Topic 3.6 — Multiculturalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'Name the AQA key thinkers for multiculturalism.', 'Isaiah Berlin, Charles Taylor, Bhikhu Parekh, Will Kymlicka and Tariq Modood.', 1, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'Distinguish multiculturalism from assimilation.', 'Assimilation requires minorities to abandon distinctive practices and adopt majority culture, treating diversity as a temporary problem. Multiculturalism positively endorses diversity as a permanent and VALUABLE feature of society.', 2, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'What is Berlin''s value pluralism?', 'There are many genuine human goods that conflict irreducibly and cannot be ranked on a single scale — so no one culture has a monopoly on the good life. Not relativism: some things remain simply wrong.', 3, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'What is Taylor''s politics of recognition?', 'Identity is dialogical, formed through interaction, so MISRECOGNITION inflicts real harm. Liberal neutrality is illusory, since a supposedly neutral public sphere reflects majority culture — genuine equality requires positive recognition.', 4, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'Summarise Kymlicka''s liberal defence of minority rights.', 'He begins from INDIVIDUAL AUTONOMY, not group value. Culture supplies the "context of choice" within which options have meaning, so protecting minority cultures serves liberalism. Majorities enjoy this security automatically; minority rights correct an inequality.', 5, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'Explain Kymlicka''s external protections / internal restrictions distinction.', 'External protections shield a minority from the wider society — he DEFENDS these. Internal restrictions are constraints a group imposes on its own dissenting members — he REJECTS these, because they violate the autonomy that justified the protections.', 6, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'What is Parekh''s "community of communities"?', 'Distinct cultural communities coexisting within a shared political framework, with common values NEGOTIATED through intercultural dialogue rather than inherited from the majority. No culture is complete, so each can learn from others.', 7, 'alevel'),
  ('Politics', 'AQA', '3.6', 'Multiculturalism', 'State the gender critique of multiculturalism.', 'Associated with Susan Moller Okin: group rights may shield practices that subordinate women from scrutiny in the name of cultural respect, so protecting the group comes at the expense of its most vulnerable members.', 8, 'alevel');

-- Topic 3.7 — Anarchism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.7', 'Anarchism', 'Name the AQA key thinkers for anarchism.', 'Max Stirner, Pierre-Joseph Proudhon, Mikhail Bakunin, Peter Kropotkin and Emma Goldman.', 1, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'Give the four anarchist objections to the state.', 'It is COERCIVE (rests on force); SOVEREIGN (claims illegitimate supreme authority); CORRUPTING (power corrupts those who hold it, so it cannot be captured); and UNNECESSARY (people can cooperate voluntarily).', 2, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'Contrast collectivist and individualist anarchism.', 'Collectivist derives from SOCIALISM — sociable human nature, common ownership, communes and unions (Bakunin, Kropotkin, Goldman). Individualist: the sovereign individual. Stirner''s egoism recognises no rights at all, including property, only what the ego can take and hold. Anarcho-capitalism is based on private property and voluntary contract.', 3, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'What did Proudhon mean by "property is theft"?', 'Property is theft WHERE it permits an owner to live off others'' labour — but he defended POSSESSION by those who work the land or tools. His mutualism envisaged independent producers exchanging at fair value with credit from people''s banks.', 4, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'What was Bakunin''s dispute with Marx?', 'Marx held a dictatorship of the proletariat would be needed, after which the state would wither away. Bakunin argued ANY state, including a workers'' state, would develop its own interests and become a NEW apparatus of domination.', 5, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'What is Kropotkin''s mutual aid, and why does it matter?', 'Voluntary reciprocal cooperation is widespread in nature and human society and is a major factor in evolutionary success. It provides the EMPIRICAL foundation for anarchist optimism — if cooperation is natural, order needs no coercive state.', 6, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'What was Goldman''s distinctive contribution?', 'She extended anti-authoritarianism to PERSONAL LIFE — marriage, sexual morality and gender expectations are forms of authority. She argued the vote alone could not emancipate women, since economic dependence and internalised constraint remain.', 7, 'alevel'),
  ('Politics', 'AQA', '3.7', 'Anarchism', 'Why do classical anarchists reject anarcho-capitalism?', 'Concentrated PRIVATE economic power is itself a form of domination, and private protection agencies with a territorial monopoly of force would resemble states in all but name — abolishing public authority while preserving hierarchy.', 8, 'alevel');

-- Topic 3.8 — Ecologism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'AQA', '3.8', 'Ecologism', 'Name the AQA key thinkers for ecologism.', 'Aldo Leopold, Rachel Carson, E.F. Schumacher, Carolyn Merchant and Murray Bookchin.', 1, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'Distinguish ecologism from environmentalism.', 'Environmentalism is ANTHROPOCENTRIC and reformist — protecting nature for human welfare within existing structures. Ecologism is ECOCENTRIC and radical — nature has intrinsic value, and industrialism itself is the problem.', 2, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'What is holism?', 'The whole is more than the sum of its parts, and entities can only be understood through their relationships within a wider system. It challenges both liberal individualism and the mechanistic view of nature as separable parts.', 3, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'What is Leopold''s land ethic?', 'The moral community should extend to soils, waters, plants and animals — the land as a whole. An action is right when it preserves the integrity, stability and beauty of the biotic community. Note it is HOLISTIC, not individualistic like animal rights.', 4, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'What did Rachel Carson''s Silent Spring (1962) demonstrate?', 'That DDT accumulated through food chains, devastating bird populations — showing concretely that intervening at one point in an ecosystem produces unpredictable effects throughout it. Widely credited with launching the modern environmental movement.', 5, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'Summarise Schumacher''s economic critique.', 'Conventional economics treats natural resources as INCOME rather than irreplaceable CAPITAL, so depleting a forest registers as profit rather than as liquidating an asset. He advocated human-scale, decentralised production and intermediate technology.', 6, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'What is Merchant''s argument in The Death of Nature?', 'Before the Scientific Revolution nature was conceived as a living, nurturing organism, carrying implicit ethical restraints. The MECHANISTIC worldview recast it as inert matter, legitimising exploitation — and the same period saw women''s position deteriorate.', 7, 'alevel'),
  ('Politics', 'AQA', '3.8', 'Ecologism', 'What is Bookchin''s social ecology, and what does he say against deep ecology?', 'Ecological crisis originates in HIERARCHICAL social structures — dominating nature extends humans dominating humans. He attacks deep ecology for blaming humanity in general, which obscures who profits and who suffers, and offers no political programme.', 8, 'alevel');

-- ---------------------------------------------------------------
-- VERIFY (read-only). Expect 32 rows, 256 cards in total.
-- ---------------------------------------------------------------
SELECT topic_id, topic_name, count(*) AS cards
  FROM flashcards
 WHERE subject = 'Politics' AND exam_board = 'AQA' AND level = 'alevel'
 GROUP BY topic_id, topic_name
 ORDER BY split_part(topic_id, '.', 1)::int, split_part(topic_id, '.', 2)::int;
