-- A-Level Business Flashcards — Edexcel (9BS0)
-- Generated for the RAG Learning study app from the specification and question banks.
-- One INSERT per topic. card_order restarts at 1 within each topic.
--
-- SAFE TO RE-RUN: the DELETE below clears any previous Business Studies/Edexcel/alevel
-- rows first, so running this file twice does not duplicate cards.
--
-- WHAT IS HERE: 20 topics x 8 cards = 160. All four themes are loaded.
-- Every 9BS0 topic is compulsory (no optional routes), so every student
-- sees all 20 topics.
--
-- TOPIC IDS match topics-config.js and the question banks exactly. They are
-- the join key, so do not renumber them here without renumbering everywhere.

-- ---------------------------------------------------------------
-- Schema: add 'level' column if not present (idempotent).
-- Every row below is level = 'alevel'.
-- ---------------------------------------------------------------
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'alevel'
  CHECK (level IN ('gcse','as','alevel'));

-- ---------------------------------------------------------------
-- Clear any existing Business Studies/Edexcel A-Level cards so this file is
-- re-runnable. Note this touches ONLY exam_board = 'Edexcel' at level
-- 'alevel'; any other board or level of Business Studies is untouched.
-- ---------------------------------------------------------------
DELETE FROM flashcards
 WHERE subject = 'Business Studies' AND exam_board = 'Edexcel' AND level = 'alevel';


-- ===============================================================
-- THEME 1 — MARKETING AND PEOPLE (PAPERS 1 AND 3)
-- ===============================================================

-- Topic 1.1 — Meeting Customer Needs
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'Distinguish a mass market from a niche market.', 'Mass market: a large market with broadly similar needs, served with standardised products at high volume and low margins, gaining economies of scale — e.g. Coca-Cola. Niche market: a small, specialised segment served with tailored products at higher prices and margins. Niches face less direct competition but are vulnerable to shifts in demand and to entry by larger firms.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'How are market share and market growth calculated?', 'Market share = (firm''s sales ÷ total market sales) × 100. Market growth = (change in market size ÷ original market size) × 100. E.g. £30m sales in a £200m market = 15% share; a market rising from £200m to £220m has grown 10%.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'Distinguish risk from uncertainty.', 'Risk: the outcome is unknown but the probability of it can be estimated, so it can be planned for, priced or insured. Uncertainty: the future cannot be measured and no reliable probability can be assigned — e.g. the first months of the Covid-19 pandemic.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'Contrast product orientation with market orientation.', 'Product-oriented firms focus on developing the best product and then look for buyers (e.g. Dyson''s engineering-led approach). Market-oriented firms research customer needs first and design to meet them. Evaluation: market orientation reduces the risk of failure, but product orientation can create markets customers could not have described in advance.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'Distinguish primary from secondary research, and quantitative from qualitative data.', 'Primary: new data gathered first-hand for a specific purpose (surveys, focus groups, test marketing) — tailored but costly and slow. Secondary: existing data collected by others (Mintel, ONS, company reports) — cheap and quick but may be outdated or not specific. Quantitative data is numerical (how many?); qualitative data explores opinions and motives (why?).', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'What limits the reliability of market research?', 'Sample size — small samples may not represent the population, while larger ones raise cost and time. Bias — in who is sampled, how questions are worded and how interviewers behave. Secondary data may be out of date. Findings describe past or stated behaviour, which may not match what customers actually do. ICT (websites, social media analytics, databases) cuts cost but samples only online users.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'What is market segmentation and how is it done?', 'Dividing a market into groups of customers with similar characteristics, so the marketing mix can be targeted. Common bases: demographic (age, gender, income), geographic (region, urban/rural), psychographic (lifestyle, values) and behavioural (usage, loyalty). It improves the fit of the offer but can raise costs and miss customers outside the target.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '1.1', 'Meeting Customer Needs', 'What is a market map, and how does it link to competitive advantage?', 'A diagram positioning products or brands against two variables customers care about — e.g. price (low–high) and quality (basic–premium). It reveals gaps and clusters of competition. Competitive advantage comes from differentiating the product and adding value (branding, design, service, USP) so customers pay more than the cost of inputs. A gap may exist because there is no demand there.', 8, 'alevel');

-- Topic 1.2 — The Market
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'Distinguish a movement along a demand curve from a shift in demand.', 'A change in the product''s OWN price causes a movement along the curve (extension or contraction). A change in any other factor shifts the whole curve: prices of substitutes and complements, consumer incomes, fashions and tastes, advertising and branding, demographics, external shocks and seasonality.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'How do substitutes and complements affect demand?', 'Substitutes: a rise in the price of one (e.g. Pepsi) increases demand for the other (Coca-Cola). Complements are bought together: a rise in the price of one (games consoles) reduces demand for the other (games).', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'What factors shift the supply curve?', 'Changes in the costs of production (wages, raw materials, energy), new technology, indirect taxes, government subsidies and external shocks. Lower costs, new technology or subsidies shift supply RIGHT; higher costs or new indirect taxes shift it LEFT.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'What happens to equilibrium price and quantity when demand increases?', 'At the original price there is excess demand, so price is bid up until the market clears again. The new equilibrium has a HIGHER price and a HIGHER quantity. (If supply increases instead, price falls and quantity rises.)', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'State the formula for price elasticity of demand (PED) and give a worked example.', 'PED = % change in quantity demanded ÷ % change in price. E.g. price rises 10%, quantity demanded falls 25%: PED = −25 ÷ 10 = −2.5, so demand is price ELASTIC (ignore the sign when interpreting: greater than 1 = elastic, less than 1 = inelastic).', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'What factors influence PED?', 'Number and closeness of substitutes, whether the product is a necessity or a luxury, the proportion of income spent on it, brand loyalty and habit, and the time period (demand becomes more elastic in the long run). Strong branding reduces PED, which is why brands can charge premium prices.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'How does PED affect the pricing decision and total revenue?', 'Inelastic (PED < 1): a price RISE increases total revenue. Elastic (PED > 1): a price CUT increases total revenue. E.g. PED = −0.4, price +10% → quantity −4%; revenue ≈ 1.10 × 0.96 = 1.056, a rise of about 5.6%. Watch the effect on profit, not just revenue.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '1.2', 'The Market', 'State the formula for income elasticity of demand (YED) and interpret its values.', 'YED = % change in quantity demanded ÷ % change in income. E.g. incomes +5%, demand +10%: YED = +2 (a luxury). Positive = normal good; above +1 = luxury (income elastic); negative = inferior good (e.g. value own-brand ranges). Firms use YED to predict how sales will respond to recession or growth.', 8, 'alevel');

-- Topic 1.3 — Marketing Mix & Strategy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'What is the design mix, and how has it changed to reflect social trends?', 'The balance of function (does it work reliably?), aesthetics (look, feel, appeal) and cost (can it be made economically?). Priorities vary by product. Social trends have added designing for waste minimisation, re-use and recycling, and ethical sourcing of materials — which can add value but raise costs.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'What are the benefits of strong branding?', 'Added value, the ability to charge premium prices, and reduced price elasticity of demand because loyal customers see fewer close substitutes. Types include manufacturer (producer) brands and own-label (retailer) brands.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'How can a business build a brand, and how has promotion changed with social trends?', 'Through USPs and differentiation, advertising, sponsorship and social media. Social trends have brought viral marketing (content shared by consumers at little cost), social media campaigns and influencers, and emotional branding (linking the brand to feelings and identity). Viral reach is cheap but hard to control.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'How is a cost-plus price calculated?', 'Price = unit cost + mark-up (a percentage of unit cost). E.g. unit cost £8 with a 25% mark-up: £8 × 1.25 = £10. Simple and covers costs, but it ignores competitors'' prices and PED.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'Distinguish skimming, penetration, predatory, competitive and psychological pricing.', 'Skimming: high launch price for an innovative product, lowered later (new games consoles). Penetration: low launch price to win share quickly. Predatory: pricing below cost to drive rivals out — illegal under competition law. Competitive: pricing at or near rivals. Psychological: prices that appear lower, e.g. £9.99. The right choice depends on USPs, PED, competition, brand strength, PLC stage and costs.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'What are distribution channels, and how has distribution changed?', 'The route from producer to consumer: direct; via a retailer; via wholesaler and retailer; or via an agent. Trends: online distribution (direct-to-consumer websites, marketplaces such as Amazon) and a move from product to service (e.g. streaming music with Spotify instead of selling CDs). Online sales and price comparison sites also push prices down.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'Outline the product life cycle and extension strategies.', 'Stages: development, introduction, growth, maturity, decline. Extension strategies at maturity aim to delay decline — PRODUCT (new version, flavour, size, packaging) or PROMOTION (new campaign, new target market, new uses). They cost money and only delay the inevitable if the product itself is outdated.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '1.3', 'Marketing Mix & Strategy', 'Explain the Boston Matrix.', 'Classifies products by market share and market growth. Stars: high share, high growth. Cash cows: high share, low growth — generate cash. Question marks (problem children): low share, high growth — need investment. Dogs: low share, low growth. Aim: a balanced portfolio, using cash cows to fund stars and question marks. Limitation: a snapshot that ignores profitability.', 8, 'alevel');

-- Topic 1.4 — Managing People
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Distinguish staff as an asset from staff as a cost, and explain a flexible workforce.', 'Asset: staff are a source of skills and ideas worth investing in through training. Cost: staff are an expense to be minimised. A flexible workforce uses multi-skilling, part-time and temporary contracts, flexible hours, home working and outsourcing so labour can match demand. It cuts costs but may reduce loyalty and motivation.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Distinguish dismissal from redundancy, and individual from collective bargaining.', 'Dismissal: employment ends because of the EMPLOYEE — misconduct or incapability. Redundancy: the JOB no longer exists, and the employee may be entitled to redundancy pay. Individual approach: each employee agrees terms with the employer. Collective bargaining: a trade union negotiates pay and conditions on behalf of the workforce.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Compare internal and external recruitment, and name the three types of training.', 'Internal: cheaper, quicker, candidate known and motivating for staff, but brings no new ideas and leaves a vacancy. External: wider pool and fresh ideas, but costly, slower and riskier. Training: induction (new starters), on-the-job (learning while working — cheap but may pass on bad habits) and off-the-job (courses away from the workplace — higher quality but costly and staff may leave).', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Distinguish tall and flat structures, and define span of control.', 'Span of control: the number of subordinates reporting directly to one manager. Tall: many layers, narrow spans, long chain of command — close control but slow communication. Flat: few layers, wide spans — faster decisions and more delegation but managers may be overstretched. Matrix: staff report to a functional manager AND a project manager. Decentralisation pushes decisions down the hierarchy.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Contrast Taylor''s and Mayo''s theories of motivation.', 'Taylor (scientific management): workers are motivated by money; break jobs into simple tasks, find the one best way, and pay by piece rate. Mayo (human relations, Hawthorne studies): workers are motivated by social needs, teamwork and management interest in them. Taylor suits routine output; Mayo underpins team working and consultation.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Summarise Maslow and Herzberg.', 'Maslow: a hierarchy of needs — physiological, safety, love and belonging, esteem, self-actualisation; a satisfied need no longer motivates. Herzberg: hygiene factors (pay, conditions, supervision) cause dissatisfaction if absent but do not motivate; motivators (achievement, recognition, responsibility, the work itself) motivate. Herzberg led to job enrichment.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Distinguish financial incentives from non-financial techniques.', 'Financial: piecework, commission, bonus, profit share, performance-related pay. Non-financial: delegation, consultation, empowerment, team working, flexible working, job enrichment (more responsibility — vertical), job enlargement (more tasks at the same level — horizontal) and job rotation (moving between tasks). Herzberg suggests pay only prevents dissatisfaction.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '1.4', 'Managing People', 'Distinguish management from leadership, and name the four leadership styles.', 'Management: planning, organising and controlling resources to meet objectives. Leadership: setting direction and inspiring people to follow it. Styles: autocratic (leader decides alone — fast, suits crises), paternalistic (leader decides in staff''s best interests), democratic (staff take part in decisions — motivating but slower), laissez-faire (staff left to decide — suits experts).', 8, 'alevel');

-- Topic 1.5 — Entrepreneurs & Leaders
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'What is the role of an entrepreneur, and what is intrapreneurship?', 'An entrepreneur creates and sets up a business, runs it and expands it, taking risks and organising resources in the face of uncertainty. Intrapreneurship: entrepreneurial innovation by employees INSIDE an existing business — e.g. new products developed by internal teams — without the employee bearing the personal financial risk.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'What characteristics do entrepreneurs need, and what are the barriers to entrepreneurship?', 'Characteristics: willingness to take risks, initiative, resilience, creativity, self-confidence, and skills in planning, communication and finance. Barriers: lack of finance, lack of business knowledge and skills, fear of failure, legal and regulatory requirements, and strong established competitors.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'Distinguish profit maximisation from profit satisficing, and name non-financial motives.', 'Profit maximisation: making the largest possible profit. Profit satisficing: making enough profit to meet the owner''s needs, trading off further profit for other goals such as leisure time. Non-financial motives: an ethical stance, social entrepreneurship, independence and home working.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'What objectives might a business pursue besides profit maximisation?', 'Survival (especially new businesses), sales maximisation, market share, cost efficiency, employee welfare, customer satisfaction and social objectives. Objectives change as the business moves from start-up to growth.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'Contrast sole traders and partnerships with limited companies, and say why a firm might float.', 'Sole traders and ordinary partnerships have UNLIMITED liability — owners are personally liable for business debts. A private limited company (Ltd) has LIMITED liability and a separate legal identity, but shares cannot be sold to the public. Flotation as a PLC on the stock market raises large amounts of share capital, but costs a lot and risks loss of control and takeover.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'What are franchising, social enterprises and lifestyle businesses?', 'Franchising: the franchisee buys the right to trade under an established brand and format (e.g. McDonald''s, Subway) for a fee and royalties — lower risk, less independence. Social enterprise: trades for a social or environmental purpose, reinvesting most profit (e.g. The Big Issue). Lifestyle business: set up to give the owner an income and a way of life, not growth.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'What is opportunity cost?', 'The value of the next best alternative forgone when a choice is made. E.g. spending £50,000 on a new van means that money cannot fund a marketing campaign. Every business decision involves a trade-off between competing uses of limited money, time and resources.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '1.5', 'Entrepreneurs & Leaders', 'Why is it difficult to move from entrepreneur to leader?', 'As the business grows the founder must delegate, build a management structure and let others make decisions. Entrepreneurs often struggle to give up control, lack formal management skills and may prefer creating to running. Many firms bring in professional managers at this stage.', 8, 'alevel');

-- ===============================================================
-- THEME 2 — MANAGING BUSINESS ACTIVITIES (PAPERS 2 AND 3)
-- ===============================================================

-- Topic 2.1 — Raising Finance
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'What are the sources of internal finance?', 'Owner''s capital (personal savings), retained profit and the sale of assets. No interest to pay and no loss of control — but retained profit is unavailable to a new or loss-making firm, and selling assets can reduce capacity (sale and leaseback avoids this).', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'List the sources of external finance.', 'Family and friends, banks, peer-to-peer funding (lending between individuals via online platforms), business angels (wealthy individuals investing for equity and giving advice), crowdfunding (many small investors online, e.g. Crowdcube) and other businesses.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'Distinguish loans from share capital.', 'Loans: borrowed for a fixed period, repaid with interest; no loss of ownership, but interest must be paid even when profits fall. Share capital: money from selling part-ownership; never repaid and no interest, but dilutes control and shareholders expect dividends. Only limited companies can raise share capital.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'What is venture capital?', 'Finance provided to small, high-risk, high-potential businesses by specialist firms in return for an equity stake (and often a board seat). Large sums plus expertise, but the owners give up a share of control and investors expect a high return and an exit, usually within 5–7 years.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'Outline overdrafts, leasing, trade credit and grants.', 'Overdraft: flexible short-term bank borrowing up to a limit; high interest, can be withdrawn. Leasing: renting an asset rather than buying it; no large outlay, but costs more overall. Trade credit: buying now and paying suppliers later (e.g. 30–60 days). Grants: money from government or charities that does not have to be repaid, but conditions apply.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'Why does liability affect the finance a business can raise?', 'Unlimited liability businesses (sole traders, partnerships) cannot sell shares and rely on owner''s capital, loans, overdrafts and family and friends — the owner''s personal assets are at risk. Limited companies can sell shares and attract venture capital because investors can only lose what they put in.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'Why does a business plan matter when raising finance?', 'It sets out the business idea, market research, marketing plan, cash-flow and profit forecasts and the finance required. Lenders and investors use it to judge risk and ability to repay. Limitation: its forecasts are only as good as their assumptions.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '2.1', 'Raising Finance', 'How is a cash-flow forecast calculated, and what are its limitations?', 'Net cash flow = cash inflows − cash outflows. Closing balance = opening balance + net cash flow, and becomes next month''s opening balance. E.g. opening £5,000, inflows £12,000, outflows £15,000: net −£3,000, closing £2,000. Use: spots shortfalls in advance. Limitations: based on estimates; external change can make it wrong.', 8, 'alevel');

-- Topic 2.2 — Financial Planning
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'What is the purpose of a sales forecast, and what affects its accuracy?', 'It predicts future sales so the business can plan production, staffing, cash flow and budgets. Factors: consumer trends, economic variables (incomes, interest rates, inflation) and actions of competitors. Difficulties: the future is uncertain, past trends may not continue, and new products have no data.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'How are sales revenue and total costs calculated?', 'Sales revenue = selling price × sales volume. Total costs = fixed costs + variable costs, where total variable costs = variable cost per unit × output. E.g. 1,000 units at £15 = £15,000 revenue; fixed costs £6,000 + (1,000 × £5) = £11,000 total costs.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'Distinguish fixed from variable costs.', 'Fixed costs do not change with output in the short run (rent, salaries, insurance). Variable costs change directly with output (raw materials, packaging, piece-rate wages). Some costs are semi-variable, e.g. a phone bill with a fixed line rental plus call charges.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'Define contribution.', 'Contribution per unit = selling price − variable cost per unit. Total contribution = contribution per unit × output (or total revenue − total variable costs). It is the amount each unit contributes towards fixed costs and then profit. Profit = total contribution − fixed costs.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'How is the break-even point calculated?', 'Break-even output = fixed costs ÷ contribution per unit. E.g. fixed costs £20,000, price £15, variable cost £5: contribution £10, break-even = 20,000 ÷ 10 = 2,000 units. At this point total revenue = total costs (fixed costs + total variable costs).', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'Define margin of safety.', 'Actual (or planned) output − break-even output. E.g. sales of 2,600 units with break-even at 2,000 gives a margin of safety of 600 units — sales could fall by 600 before the firm makes a loss. On a break-even chart it is the distance between the break-even point and actual output.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'What are the limitations of break-even analysis?', 'It assumes all output is sold, a single selling price, and that costs and revenue are straight lines — in reality firms offer discounts and gain bulk-buying savings. It is hard to use for multi-product firms, is only as good as its data, and is static — it does not show changing conditions.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '2.2', 'Financial Planning', 'Distinguish historical from zero-based budgets, and explain variance analysis.', 'Historical: based on last year''s figures, adjusted — quick but carries forward inefficiency. Zero-based: every item starts at zero and must be justified — thorough but time-consuming. Variance = actual − budgeted. Favourable: better than budget (cost below, revenue above). Adverse: worse than budget. E.g. costs budgeted £40,000, actual £45,000 = £5,000 adverse.', 8, 'alevel');

-- Topic 2.3 — Managing Finance
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'How are gross profit, operating profit and profit for the year calculated?', 'Gross profit = revenue − cost of sales. Operating profit = gross profit − other operating expenses. Profit for the year (net profit) = operating profit − interest (and tax). E.g. revenue £500k, cost of sales £300k → gross profit £200k; expenses £120k → operating profit £80k; interest £10k → profit for the year £70k.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'State the formula for gross profit margin and give an example.', 'Gross profit margin = (gross profit ÷ revenue) × 100. E.g. £200k ÷ £500k × 100 = 40%. It shows how well the firm controls its direct costs and prices its products.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'State the operating and net profit margin formulas, and say what the gap between margins shows.', 'Operating profit margin = (operating profit ÷ revenue) × 100. Profit for the year margin = (profit for the year ÷ revenue) × 100. E.g. £80k ÷ £500k = 16%. A healthy gross margin but a low operating margin points to high overheads rather than high direct costs.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'How can a business improve profitability?', 'Raise prices (best if demand is price inelastic), cut variable costs (cheaper suppliers, less waste), cut overheads, or increase efficiency and productivity. Each has risks — higher prices can lose customers, cheaper inputs can hurt quality, and overhead cuts can damage service or morale.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'Why is profit not the same as cash?', 'Profit = revenue − costs over a period, recorded when a sale is made. Cash is money actually received and paid. A profitable firm can run out of cash if customers pay late on credit, if it holds too much inventory, or if it spends heavily on assets. Cash shortage — not lack of profit — is the most common immediate cause of failure.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'State the current ratio and acid test ratio formulas with examples.', 'Current ratio = current assets ÷ current liabilities. E.g. £150k ÷ £100k = 1.5:1 (roughly 1.5–2 is often seen as comfortable). Acid test = (current assets − inventory) ÷ current liabilities. E.g. (£150k − £70k) ÷ £100k = 0.8:1 — below 1, so the firm relies on selling stock to pay its short-term debts. Supermarkets often run low ratios safely.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'What is working capital, and how can liquidity be improved?', 'Working capital = current assets − current liabilities — the cash available for day-to-day running. Improve liquidity by: reducing inventory, chasing debtors or offering early-payment discounts, negotiating longer credit from suppliers, sale and leaseback, or an injection of share capital. Many of these carry costs, e.g. strained supplier relations.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '2.3', 'Managing Finance', 'What are the internal and external causes of business failure?', 'Internal financial: poor cash-flow management, overtrading, too much debt. Internal non-financial: poor management, weak marketing, failure to adapt. External: recession, rising interest rates, new competitors, changing tastes, new legislation. E.g. Wilko entered administration in 2023 after years of losses and rising costs.', 8, 'alevel');

-- Topic 2.4 — Resource Management
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'Distinguish job, batch, flow and cell production.', 'Job: one-off products made to customer specification (a wedding dress) — high value, high unit cost. Batch: groups of identical items made together (bakery). Flow: continuous mass production on a production line (cars, soft drinks) — low unit cost, inflexible. Cell: production split into self-contained teams (cells), each making a complete unit — improves motivation and quality.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'Define labour productivity and state what influences it.', 'Output per unit of input per time period. Labour productivity = output ÷ number of workers. E.g. 12,000 units ÷ 40 workers = 300 units per worker per month. Influences: training, motivation, technology and equipment, working methods. Higher productivity lowers unit costs, improving competitiveness.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'What is efficiency, and how does labour-intensive differ from capital-intensive production?', 'Efficiency: producing at the minimum average (unit) cost. Labour-intensive: relies mostly on people (hairdressing, handmade goods) — flexible but higher unit costs at scale. Capital-intensive: relies mostly on machinery (car plants, Amazon warehouses) — low unit costs at high volume but high fixed costs and less flexibility.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'State the capacity utilisation formula and interpret it.', 'Capacity utilisation = (current output ÷ maximum possible output) × 100. E.g. 8,000 ÷ 10,000 × 100 = 80%. Under-utilisation: fixed costs spread over fewer units, raising unit cost. Over-utilisation (near 100%): no spare room for new orders or maintenance, and staff are stressed.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'How can a business improve capacity utilisation?', 'Increase output: raise demand through marketing, take on subcontracted work. Reduce capacity: sell or lease out space, cut shifts, rationalise sites. If over-utilised: subcontract work, invest in extra capacity, or run extra shifts.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'Interpret a stock control diagram.', 'It shows inventory falling as it is used and rising when a delivery arrives. Key features: maximum stock level, reorder level (the point at which an order is placed), lead time (time between ordering and delivery), and buffer stock (minimum held to cover unexpected demand or delays). Poor control risks stock-outs, or high holding costs and wastage.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'What is just in time (JIT) and lean production?', 'JIT: stock arrives exactly when needed, so almost no buffer stock is held. Lean production aims to minimise all waste — stock, time, defects, space. Benefits: lower holding costs, less waste, frees cash and space. Risks: depends on reliable suppliers — a single delay halts production, as seen in the 2021 semiconductor shortage in car manufacturing.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '2.4', 'Resource Management', 'Distinguish quality control, quality assurance, quality circles, TQM and Kaizen.', 'Quality control: inspecting products at the end to find defects. Quality assurance: building quality into every stage of the process to prevent defects. Quality circles: groups of workers meeting to solve quality problems. TQM: every employee is responsible for quality. Kaizen: continuous improvement through many small changes. Quality can be a source of competitive advantage.', 8, 'alevel');

-- Topic 2.5 — External Influences
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'How does inflation affect businesses?', 'Inflation is the rate of increase in the general price level, measured in the UK by the Consumer Prices Index (CPI); the Bank of England''s target is 2%. High inflation raises costs (materials, wage demands), reduces consumers'' real incomes, makes UK exports less price competitive and makes planning harder. Firms with strong brands can pass on rises more easily.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'How does an exchange rate change affect exporters and importers?', 'An appreciation of the pound makes UK exports dearer abroad and imports cheaper (SPICED: Strong Pound, Imports Cheap, Exports Dear). E.g. if £1 moves from $1.25 to $1.50, a £20 product rises from $25 to $30 in the USA. A depreciation does the opposite. Impact depends on the PED of the goods and how much the firm imports its inputs.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'How do changes in interest rates affect businesses?', 'Higher interest rates raise the cost of loans and overdrafts, cut consumer spending on credit-financed and luxury goods, and may push up the pound. Firms with high gearing are hit hardest; investment tends to be delayed. Lower rates have the opposite effects.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'How do taxation and government spending affect businesses?', 'Higher income tax or VAT cuts consumer spending; higher corporation tax (main rate 25% since April 2023) cuts retained profit for investment; higher employer National Insurance raises labour costs. Government spending creates demand directly (construction, defence, NHS suppliers).', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'Describe the business cycle and the effect of economic uncertainty.', 'Phases: boom (high demand, capacity constraints), downturn, recession (two consecutive quarters of negative growth — falling sales, rising unemployment), and recovery. Uncertainty makes firms delay investment and hiring, hold more cash and cut stock, because future demand and costs are hard to forecast.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'Outline consumer protection, employee protection and health and safety law.', 'Consumer protection (e.g. Consumer Rights Act 2015): goods must be of satisfactory quality, fit for purpose and as described. Employee protection: National Minimum and Living Wage, the Equality Act 2010, unfair dismissal rights. Health and safety law requires a safe workplace and risk assessments. Compliance raises costs but protects reputation.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'What is competition policy, and how does environmental protection affect business?', 'Competition policy stops firms abusing market power: the Competition and Markets Authority (CMA) investigates mergers, cartels and abuse of dominance, and can fine firms up to 10% of global turnover. Environmental protection law limits emissions, pollution and waste, raising costs but potentially creating a competitive advantage for greener firms.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '2.5', 'External Influences', 'How does the level of competition and market size affect a business?', 'In a highly competitive market with many firms, businesses have little control over price and must compete on cost, quality or differentiation. In a market dominated by a few large firms, those firms have more price-setting power. A growing market allows firms to gain sales without taking share from rivals; a shrinking market intensifies competition.', 8, 'alevel');

-- ===============================================================
-- THEME 3 — BUSINESS DECISIONS AND STRATEGY (PAPERS 2 AND 3)
-- ===============================================================

-- Topic 3.1 — Business Objectives & Strategy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'How are corporate objectives developed from a mission statement?', 'Mission statement (the purpose and values) → corporate aims → corporate objectives (measurable targets, ideally SMART) → strategy (the long-term plan to meet them) → tactics (short-term actions). Objectives then cascade into functional objectives for marketing, finance, operations and HR.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'What are the criticisms of mission statements?', 'They are often vague, generic and similar across firms; they may be public-relations exercises that do not guide real decisions; staff may be unaware of them. They are useful only if they are specific, communicated, and genuinely shape objectives and culture.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'Explain Ansoff''s Matrix.', 'Four growth strategies by product and market. Market penetration: existing products, existing markets — lowest risk. Product development: new products, existing markets. Market development: existing products, new markets. Diversification: new products, new markets — highest risk. Risk rises as the firm moves away from what it knows.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'Explain Porter''s Strategic Matrix (generic strategies).', 'Competitive advantage comes from either lower cost or differentiation, applied to a broad or narrow (focus) market. Cost leadership: lowest costs in the industry (Ryanair, Aldi). Differentiation: unique features that justify a premium (Apple). Focus: cost or differentiation in a niche. Firms that pursue neither are stuck in the middle.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'What is the aim of portfolio analysis, and what are distinctive capabilities?', 'Portfolio analysis (e.g. the Boston Matrix) reviews the balance of products or business units to decide where to invest, hold or divest. Distinctive capabilities (Kay) are hard-to-copy sources of competitive advantage: architecture (relationships inside and outside the firm), reputation and innovation.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'Distinguish strategic from tactical decisions.', 'Strategic: long-term, high-risk, made by senior managers, affect the whole business (entering a new market). Tactical: short-term, lower-risk, made by middle managers to carry out strategy (running a price promotion). Strategic decisions have major effects on human, physical and financial resources — hiring, new sites, large investment.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'What does a SWOT analysis contain?', 'Internal: Strengths and Weaknesses (brand, finance, staff skills, costs). External: Opportunities and Threats (market growth, new technology, competitors, regulation). It helps match strategy to strengths and opportunities. Limitation: a static, subjective list — it does not rank factors or tell managers what to do.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '3.1', 'Business Objectives & Strategy', 'Explain PESTLE and Porter''s Five Forces.', 'PESTLE analyses the external environment: Political, Economic, Social, Technological, Legal, Environmental. Porter''s Five Forces analyses industry competitiveness and potential profitability: threat of new entrants, bargaining power of suppliers, bargaining power of buyers, threat of substitutes, and rivalry among existing competitors. The stronger the forces, the lower industry profits.', 8, 'alevel');

-- Topic 3.2 — Business Growth
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'Why do businesses seek to grow?', 'To achieve economies of scale, gain market power over customers and suppliers, increase market share and brand recognition, and increase profitability. Growth can also spread risk across more products and markets.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'Distinguish internal from external economies of scale.', 'Internal economies arise from the firm''s own growth and lower its average cost: technical (bigger, better machinery), purchasing (bulk-buying discounts), financial (cheaper borrowing), managerial (specialist managers) and marketing (spreading advertising over more output). External economies arise from the growth of the industry in an area — skilled labour pools, specialist suppliers, better infrastructure.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'What are diseconomies of scale?', 'Rising average costs as a firm grows too large. Causes: communication problems through long chains of command, coordination and control difficulties, and demotivated staff who feel distant from decision-makers. Internal communication worsens as more layers are added.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'What is overtrading?', 'Expanding too quickly without enough working capital to finance it: the firm pays for more stock and staff before customers pay, so it runs out of cash despite rising sales and profit. Solutions: arrange long-term finance before expanding, grow more slowly, and control credit terms.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'Distinguish a merger from a takeover, and give the risks and rewards.', 'Merger: two firms agree to join as a new single business. Takeover (acquisition): one firm buys a controlling interest (over 50% of the shares) in another, possibly hostile — e.g. Kraft''s takeover of Cadbury in 2010. Rewards: rapid growth, economies of scale, market share. Risks: overpaying, debt, culture clash, and failure to achieve synergies.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'Distinguish horizontal from vertical integration.', 'Horizontal: joining firms at the same stage of production in the same industry — e.g. Vodafone and Three UK (completed 2025). Vertical backward: towards suppliers (a brewer buying a hop farm) — secures supply and cost. Vertical forward: towards customers (a manufacturer buying retailers) — controls distribution. Horizontal integration may be investigated by the CMA.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'Distinguish organic from inorganic growth.', 'Organic (internal) growth: expanding from within — new products, new stores, new markets, franchising. Advantages: lower risk, keeps control and culture, financed by retained profit. Disadvantages: slow, and may miss opportunities. Inorganic (external) growth: mergers and takeovers — fast but risky.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '3.2', 'Business Growth', 'How can small businesses survive in competitive markets?', 'By product differentiation and USPs, flexibility in responding to customer needs, personal customer service, and e-commerce to reach customers beyond the local area at low cost. Some owners stay small deliberately to keep control, avoid risk or keep a lifestyle.', 8, 'alevel');

-- Topic 3.3 — Decision-Making Techniques
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'How is a three-period moving average calculated?', 'Add three consecutive periods'' figures and divide by three, then plot the result against the middle period. E.g. sales of 20, 26 and 29: (20 + 26 + 29) ÷ 3 = 25, plotted against period 2. Moving averages smooth out fluctuations to reveal the underlying trend. A four-quarter moving average also needs centring.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'What are the limitations of quantitative sales forecasting?', 'Extrapolation (extending a line of best fit on a scatter graph) assumes past trends continue. It ignores sudden changes — new competitors, economic shocks, changes in taste — and correlation does not prove causation. It works best in stable markets and over short time periods.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'How is payback calculated?', 'The time taken for net cash inflows to repay the initial investment. E.g. cost £50,000, net inflows £20,000 a year: after 2 years £40,000 is recovered; £10,000 ÷ £20,000 = 0.5 year, so payback = 2.5 years (2 years 6 months). Simple and stresses liquidity, but ignores cash after payback and the time value of money.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'How is the average (accounting) rate of return calculated?', 'ARR = (average annual profit ÷ initial investment) × 100. Average annual profit = (total net inflows − cost) ÷ number of years. E.g. £80,000 over 4 years for a £50,000 investment: profit £30,000 ÷ 4 = £7,500; £7,500 ÷ £50,000 × 100 = 15%. Compare with interest rates and targets; ignores timing of cash flows.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'How is net present value (NPV) calculated?', 'Multiply each year''s net cash flow by its discount factor, add them, and subtract the initial cost. E.g. cost £10,000; £6,000 a year for 2 years at 10% (factors 0.909, 0.826): £5,454 + £4,956 = £10,410; NPV = +£410, so the project is worthwhile. It accounts for the time value of money, but the discount rate chosen is a judgement.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'Give the main limitation of each investment appraisal method.', 'Payback ignores cash flows after payback and profitability. ARR ignores the timing of cash flows. NPV depends on the discount rate chosen and is harder to explain. All rely on forecast cash flows and ignore qualitative factors such as staff morale, ethics and strategic fit.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'How is expected value calculated in a decision tree?', 'Expected value = sum of (probability × financial outcome) at each chance node; then subtract the cost of the decision. E.g. launch costs £30k: 0.6 × £100k + 0.4 × (−£20k) = £52k; net £22k. Compare with other options. Limitations: probabilities and outcomes are estimates, and qualitative factors are ignored.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '3.3', 'Decision-Making Techniques', 'How is total float calculated in critical path analysis?', 'Total float = latest finish time (LFT) − duration − earliest start time (EST). E.g. LFT 12, duration 4, EST 5: float = 3 days, so the activity can be delayed 3 days without delaying the project. Critical activities have zero float and form the critical path. Limitations: duration estimates may be wrong; it does not guarantee resources.', 8, 'alevel');

-- Topic 3.4 — Influences on Business Decisions
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'Distinguish short-termism from long-termism.', 'Short-termism: focusing on immediate results — this quarter''s profit or share price — at the expense of long-term investment in R&D, training or the brand. Long-termism: accepting lower profit now to build future performance. Pressure from shareholders and bonus schemes linked to annual results can drive short-termism.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'Distinguish evidence-based from subjective decision-making.', 'Evidence-based: using data and quantitative techniques (market research, investment appraisal, decision trees) — reduces bias and is easier to justify. Subjective: based on managers'' judgement, experience and intuition — faster and useful when data is unavailable or the situation is new. Most decisions combine both.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'What is the difference between a strong and a weak culture, and how is culture formed?', 'Culture: the shared values, attitudes and norms of an organisation — ''the way we do things around here''. Strong culture: widely shared values that guide behaviour. Weak culture: little agreement, so behaviour varies. Culture is formed by founders and leaders, history, recruitment, rewards and structure.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'Name and describe Handy''s four types of culture.', 'Power: control from one central figure (small entrepreneurial firms). Role: rules, procedures and hierarchy (civil service, large bureaucracies). Task: teams formed to complete projects, valuing expertise (consultancies). Person: the organisation exists to serve talented individuals (barristers'' chambers, partnerships).', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'Why is it difficult to change an established culture?', 'Staff hold values built over years, fear the unknown, may lose status or security, and informal groups resist. Change takes time, strong leadership and consistent changes to recruitment, rewards and structure — e.g. Satya Nadella''s shift at Microsoft from a ''know-it-all'' to a ''learn-it-all'' culture.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'Distinguish internal from external stakeholders, and give their objectives.', 'Internal: employees (pay, security), managers (career, bonuses), owners or shareholders (profit, dividends). External: customers (quality, price), suppliers (regular orders, prompt payment), the local community (jobs, low pollution), government (taxes, legal compliance), lenders (repayment).', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'Contrast the shareholder and stakeholder approaches.', 'Shareholder approach: the business should focus purely on shareholder returns — increasing share price and dividends. Stakeholder approach: the business should consider all stakeholders in its decisions. Conflict arises between profit-based and wider objectives, e.g. cutting jobs raises profit but harms employees and the community.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '3.4', 'Influences on Business Decisions', 'What is CSR, and why may ethics conflict with profit?', 'Corporate social responsibility: a business voluntarily taking account of the impact of its activities on society and the environment. Ethical decisions (fair supplier prices, higher wages, lower emissions) often raise costs — a trade-off between profit and ethics. Executive pay far above average pay is a key ethical issue. CSR can also build reputation and attract customers and staff.', 8, 'alevel');

-- Topic 3.5 — Assessing Competitiveness
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'What does the statement of comprehensive income show, and who is interested?', 'The income statement (profit and loss account) shows revenue, cost of sales, gross profit, operating expenses, operating profit, interest and profit for the year over a period. Shareholders look at profit and dividends; managers at cost control; employees at pay prospects; government at tax.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'What does the statement of financial position show, and who is interested?', 'The balance sheet shows, at a point in time, non-current assets, current assets, current liabilities, non-current liabilities, net assets and total equity (share capital + retained profit). Lenders and suppliers look at liquidity and debt; shareholders at the value of the business.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'How is the gearing ratio calculated?', 'Gearing = (non-current liabilities ÷ capital employed) × 100, where capital employed = non-current liabilities + total equity. E.g. £40m ÷ (£40m + £60m) × 100 = 40%. Above 50% is usually seen as highly geared — vulnerable to rising interest rates, but debt is cheaper than equity when profits are rising.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'How is return on capital employed (ROCE) calculated?', 'ROCE = (operating profit ÷ capital employed) × 100. E.g. £15m ÷ £100m × 100 = 15%. It measures how efficiently the business uses its long-term finance to make profit. Compare with previous years, competitors and the interest rate on savings.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'What are the limitations of ratio analysis?', 'Ratios use historical data; comparisons are only valid across similar firms and periods; accounts can be window-dressed; they ignore qualitative factors (staff morale, brand, the economy); and a single ratio says little — trends and context are needed.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'How are labour productivity and labour turnover calculated?', 'Labour productivity = output ÷ number of employees. E.g. 60,000 units ÷ 150 staff = 400 units per employee. Labour turnover = (number of staff leaving ÷ average number of staff employed) × 100. E.g. 12 leavers ÷ 150 average staff × 100 = 8%. High turnover raises recruitment and training costs.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'How are the retention rate and absenteeism rate calculated?', 'Retention rate = (number of staff with a year''s service or more ÷ number employed a year ago) × 100 — a high rate shows loyalty. Absenteeism rate = (days lost to absence ÷ total possible working days) × 100. E.g. 500 days lost ÷ 25,000 possible days × 100 = 2%.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '3.5', 'Assessing Competitiveness', 'What HR strategies can raise productivity and retention and reduce absenteeism?', 'Financial rewards (pay, bonuses), employee share ownership (gives staff a stake in success — e.g. John Lewis Partnership), consultation strategies (involving staff in decisions) and empowerment strategies (giving staff authority to make decisions). Evaluation: the cost of each must be weighed against savings from lower turnover.', 8, 'alevel');

-- Topic 3.6 — Managing Change
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'What causes change in a business?', 'Changes in organisational size (growth or retrenchment), poor business performance, new ownership (e.g. after a takeover), transformational leadership, and the market and other external factors (PESTLE).', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'What is transformational leadership, and why does it cause change?', 'A leader who sets a new vision and inspires staff to change the organisation''s direction and culture, rather than managing existing systems. New CEOs often trigger major restructuring or a new strategy. Its success depends on staff buy-in.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'What effects can change have on a business?', 'Effects on competitiveness (new products, lower costs), productivity (new technology, disruption during transition), financial performance (short-term costs of restructuring, longer-term gains) and stakeholders (job losses or new jobs, changed supplier relationships, customer reactions).', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'How do culture and size affect the management of change?', 'A strong culture can resist change unless the change fits its values; a task culture adapts more easily than a role culture. Large organisations have more layers, slower communication and more people affected, so change is harder to coordinate. Small firms can change quickly but may lack resources.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'Why does the speed of change matter?', 'Incremental change is gradual — easier to manage, less resistance, but may be too slow in a fast-moving market. Rapid (disruptive) change may be forced by a crisis or new technology and increases uncertainty and resistance. The more time available, the more consultation is possible.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'Why do staff resist change, and how can resistance be managed?', 'Reasons: fear of the unknown, job insecurity, loss of status or skills, habit and self-interest. Approaches: education and communication, participation and involvement, facilitation and support (training), negotiation and agreement, and — as a last resort — coercion. Consultation early usually reduces resistance.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'What is scenario planning and risk assessment?', 'Scenario planning: identifying possible future situations and planning responses. Risk assessment: identifying key risks, estimating their likelihood and impact, and prioritising. Key risks in the specification: natural disasters, IT systems failure (e.g. cyber-attacks such as the 2025 attack on Marks & Spencer) and loss of key staff.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '3.6', 'Managing Change', 'Distinguish business continuity planning from succession planning.', 'Business continuity: planning to keep critical functions running during a disruption — backup systems, alternative sites, recovery plans. Succession planning: identifying and developing people to replace key staff, especially senior leaders, so their departure does not damage the business.', 8, 'alevel');

-- ===============================================================
-- THEME 4 — GLOBAL BUSINESS (PAPERS 1 AND 3)
-- ===============================================================

-- Topic 4.1 — Globalisation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'Define globalisation and list the factors that have increased it.', 'The growing integration and interdependence of the world''s economies. Factors: reduction of trade barriers (trade liberalisation), political change (e.g. China opening its economy), reduced costs of transport and communication, the increasing significance of global companies, increased FDI, migration, growth of the global labour force, and structural change.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'How does UK growth compare with emerging economies, and what does it mean for business?', 'The UK typically grows around 1–2% a year, while emerging economies such as India (about 6–7%) and much of Asia and Africa grow faster. This creates trade opportunities — a rising middle class buying consumer goods — and changes employment patterns as manufacturing moves to lower-cost economies.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'Name the indicators of growth and development.', 'GDP per capita (output per person — the main income measure), literacy rates, health (e.g. life expectancy, infant mortality) and the Human Development Index (HDI), which combines income, education and life expectancy into a score between 0 and 1.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'How does specialisation link to competitive advantage and trade?', 'Countries and businesses specialise in what they produce most efficiently, gaining economies of scale and expertise, and trade for the rest. Exports are goods and services sold abroad (bringing money in); imports are those bought from abroad. Specialisation creates competitive advantage but increases dependence on other countries.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'What is foreign direct investment (FDI) and how does it link to business growth?', 'FDI is investment by a company in productive assets in another country — building a factory, setting up a subsidiary, or buying a controlling stake in a foreign firm. It allows a business to grow by entering new markets, accessing cheaper inputs and avoiding trade barriers — e.g. Nissan''s Sunderland plant.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'What is a tariff, and how does it affect business?', 'A tax on imported goods. E.g. a 20% tariff on a £50 import raises its price to £60, making domestic goods more price competitive. It protects domestic producers but raises costs for firms using imported inputs and invites retaliation — e.g. the 10% baseline US tariff on most UK goods in 2025.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'What are quotas and other trade barriers?', 'Import quota: a physical limit on the quantity of a good that can be imported. Other barriers: government legislation (product standards, safety rules and paperwork that make importing harder) and domestic subsidies (government payments to domestic producers, lowering their costs relative to foreign rivals).', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '4.1', 'Globalisation', 'What are trading blocs and how do they affect business?', 'Groups of countries that reduce or remove trade barriers between members — e.g. the EU single market (free movement of goods, services, capital and people), ASEAN, and NAFTA (replaced by the USMCA in 2020). Members gain a larger tariff-free market and economies of scale; outsiders face the external barriers, encouraging them to invest inside the bloc.', 8, 'alevel');

-- Topic 4.2 — Global Markets & Business Expansion
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'Distinguish push factors from pull factors for trading internationally.', 'Push factors drive a firm out of its home market: saturated markets and intense domestic competition. Pull factors attract it to overseas markets: economies of scale from larger output, and risk spreading across several economies.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'Distinguish offshoring from outsourcing.', 'Offshoring: moving a business activity to another country, either within the firm (its own overseas factory) or to a foreign supplier. Outsourcing: contracting an activity to another business, which may be at home or abroad. Benefits: lower costs, access to skills. Risks: quality control, longer supply chains and reputational damage.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'How can selling in multiple markets extend the product life cycle?', 'A product in maturity or decline at home may be in introduction or growth in another country. Launching it abroad extends its life without the cost of developing a new product — as UK firms have done in fast-growing Asian markets.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'What factors should a firm consider when assessing a country as a MARKET?', 'Levels and growth of disposable income, ease of doing business (regulation, bureaucracy — World Bank-style indicators), infrastructure (transport, communications, retail), political stability, and the exchange rate. Market research and cultural fit also matter.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'What factors should a firm consider when assessing a country as a PRODUCTION LOCATION?', 'Costs of production, skills and availability of labour, infrastructure, location within a trade bloc, government incentives, ease of doing business, political stability, natural resources and the likely return on investment.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'Why do businesses form global mergers or joint ventures?', 'To spread risk over different countries and regions, enter new markets and trade blocs, acquire national or international brand names and patents, secure resources and supplies, and maintain or increase global competitiveness. A joint venture shares risk and local knowledge but can cause conflict between partners.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'How do exchange rate movements affect international competitiveness?', 'A stronger pound makes UK exports dearer and imported inputs cheaper; a weaker pound makes exports cheaper and imports dearer. E.g. £1 falling from €1.20 to €1.10 cuts the euro price of a £100 export from €120 to €110. The overall effect depends on PED and the import content of production.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '4.2', 'Global Markets & Business Expansion', 'How can firms gain global competitive advantage, and how do skill shortages matter?', 'Through cost competitiveness (lower unit costs than rivals, allowing lower prices or higher margins) or differentiation (features, brand or quality that justify a premium). Skill shortages raise wage costs, delay projects and limit innovation, reducing a country''s international competitiveness.', 8, 'alevel');

-- Topic 4.3 — Global Marketing
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'Distinguish a global marketing strategy from glocalisation.', 'Global strategy: the same marketing mix worldwide, gaining economies of scale and a consistent brand. Glocalisation: a global brand adapted to local tastes and cultures — e.g. McDonald''s in India offers no beef and sells the McAloo Tikki. Glocalisation raises sales but costs more.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'Distinguish ethnocentric, polycentric and geocentric approaches.', 'Ethnocentric (domestic): uses the home-market mix abroad unchanged — cheap, but may not suit local needs. Polycentric (international): creates a separate mix for each country — suits local tastes but costly. Geocentric (mixed): a global strategy with local adaptation where needed — a balance of the two.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'How might the 4Ps be adapted for global markets?', 'Product: change size, ingredients, features or packaging for local tastes and regulations. Price: reflect local incomes, competition and exchange rates. Promotion: adapt language, imagery and media to local culture. Place: use local distributors or online channels suited to local infrastructure.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'How is Ansoff''s Matrix applied to global markets?', 'Selling existing products in a new country is market development — medium risk because the firm lacks local knowledge. Launching new products designed for a foreign market is diversification — the highest risk. Firms often reduce risk through joint ventures or acquisitions of local businesses.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'What are global niche markets?', 'Small, specialised segments that exist across many countries — groups of people across the globe share interests and values despite cultural diversity (e.g. luxury watches, specialist sports equipment). Features: customers with specific needs, less price sensitivity, and a small share of each national market but a viable total.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'How is the marketing mix adapted to suit global niches?', 'Product: highly specialised, premium quality. Price: premium, as demand is less price sensitive. Promotion: targeted — specialist media, social media communities, events. Place: selective distribution, often online direct-to-consumer to reach dispersed customers.', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'What cultural and social factors must businesses consider in global markets?', 'Cultural differences (values, religion, customs), different tastes, language, unintended meanings of names or slogans, inappropriate or inaccurate translations, and inappropriate branding and promotion. Getting these wrong wastes marketing spend and damages the brand.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '4.3', 'Global Marketing', 'Give an example of an inaccurate translation damaging a brand.', 'HSBC''s slogan ''Assume Nothing'' was translated in several countries as ''Do Nothing'', forcing a costly global rebrand to ''The world''s local bank'' in 2009. Firms reduce this risk by using local agencies and testing campaigns with local consumers.', 8, 'alevel');

-- Topic 4.4 — Global Industries & Companies (MNCs)
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'What is a multinational corporation, and how can it affect local labour?', 'An MNC has its headquarters in one country and operations (production or services) in others. Local effects: job creation and often higher wages than local firms, but possible low pay, poor working conditions and job losses if it relocates.', 1, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'How can MNCs affect local businesses, the community and the environment?', 'Local businesses: gain from supply contracts and spending by MNC workers, but may be forced out by competition. Community and environment: new infrastructure and investment, but also pollution, congestion and pressure on resources.', 2, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'How can MNCs affect the national economy through FDI and the balance of payments?', 'FDI inflows add to investment and output. The balance of payments benefits when the MNC exports from the host country, but suffers when profits are sent back to the home country and inputs are imported.', 3, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'How do MNCs affect technology, skills, consumers and business culture?', 'Technology and skills transfer — local staff learn new methods and managers gain expertise. Consumers gain choice and lower prices. Business culture can change as MNCs bring new working practices and management approaches, which may clash with local norms.', 4, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'What is transfer pricing?', 'Setting the prices charged between subsidiaries of the same MNC so that profits appear in low-tax countries. E.g. a UK subsidiary pays a large brand royalty to a sister company in a lower-tax country, cutting UK profit taxed at 25%. It reduces host-country tax revenue; the OECD 15% global minimum tax, applied from 2024, aims to limit this.', 5, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'What are the main ethical issues for MNCs?', 'Stakeholder conflicts (shareholders'' profits versus workers'' pay), pay and working conditions, environmental considerations (emissions and waste disposal), and marketing considerations (misleading product labelling and inappropriate promotional activities).', 6, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'What are the supply chain ethical issues for MNCs?', 'Exploitation of labour (very low pay, excessive hours, unsafe factories) and child labour at suppliers. E.g. the 2013 Rana Plaza collapse in Bangladesh killed over 1,100 garment workers producing for Western brands. MNCs respond with supplier audits and codes of conduct, but monitoring long supply chains is difficult.', 7, 'alevel'),
  ('Business Studies', 'Edexcel', '4.4', 'Global Industries & Companies (MNCs)', 'How can MNCs be controlled?', 'Political influence (governments negotiating with or pressuring MNCs), legal control (national laws and international agreements on tax, labour and the environment), pressure groups (campaigns and boycotts) and social media (rapid spread of criticism that damages reputation). Limitation: large MNCs can relocate or lobby, reducing the power of any single government.', 8, 'alevel');
