/* ═══════════════════════════════════════════════════════════════════
   FLASHCARDS TOPIC MAP — shared across flashcards.html, flashcards/subject.html
   and flashcards/study.html.

   Keys use the same "Subject|Board" (+ optional "|alevel" / "|gcse" variant)
   format as NOTES_AVAILABLE in notes.html. Content is a topic list only —
   card contents live in Supabase (flashcards table), not here.
═══════════════════════════════════════════════════════════════════ */
(function () {
  const FLASHCARDS_TOPICS = {
    // ── Computer Science ────────────────────────────────────────────
    'Computer Science|OCR': [
      { num: '1.1', name: 'Systems Architecture' },
      { num: '1.2', name: 'Memory and Storage' },
      { num: '1.3', name: 'Networks & Protocols' },
      { num: '1.4', name: 'Network Security' },
      { num: '1.5', name: 'Systems Software' },
      { num: '1.6', name: 'Ethical & Legal Impacts' },
      { num: '2.1', name: 'Algorithms' },
      { num: '2.2', name: 'Programming Fundamentals' },
      { num: '2.3', name: 'Producing Robust Programs' },
      { num: '2.4', name: 'Boolean Logic' },
      { num: '2.5', name: 'Languages and IDEs' },
    ],
    'Computer Science|OCR|alevel': [
      { num: '1.1', name: 'Characteristics of Processors, I/O & Storage' },
      { num: '1.2', name: 'Software and Software Development' },
      { num: '1.3', name: 'Exchanging Data' },
      { num: '1.4', name: 'Data Types, Structures & Algorithms' },
      { num: '1.5', name: 'Legal, Moral, Cultural & Ethical' },
      { num: '2.1', name: 'Elements of Computational Thinking' },
      { num: '2.2', name: 'Problem Solving and Programming' },
      { num: '2.3', name: 'Algorithms' },
    ],
    'Computer Science|AQA|alevel': [
      { num: '4.1', name: 'Fundamentals of Programming' },
      { num: '4.2', name: 'Fundamentals of Data Structures' },
      { num: '4.3', name: 'Fundamentals of Algorithms' },
      { num: '4.4', name: 'Theory of Computation' },
      { num: '4.5', name: 'Fundamentals of Data Representation' },
      { num: '4.6', name: 'Fundamentals of Computer Systems' },
      { num: '4.7', name: 'Computer Organisation & Architecture' },
      { num: '4.8', name: 'Consequences of Uses of Computing' },
      { num: '4.9', name: 'Communication & Networking' },
      { num: '4.10', name: 'Fundamentals of Databases' },
    ],
    'Computer Science|AQA|gcse': [
      { num: '3.1', name: 'Fundamentals of Algorithms' },
      { num: '3.2', name: 'Programming' },
      { num: '3.3', name: 'Fundamentals of Data Representation' },
      { num: '3.4', name: 'Computer Systems' },
      { num: '3.5', name: 'Fundamentals of Computer Networks' },
      { num: '3.6', name: 'Cyber Security' },
      { num: '3.7', name: 'Relational Databases and SQL' },
      { num: '3.8', name: 'Ethical, Legal and Environmental Impacts' },
    ],

    // ── Physics ─────────────────────────────────────────────────────
    'Physics|Edexcel': [
      { num: 'T1', name: 'Working as a Physicist' },
      { num: 'T2', name: 'Mechanics' },
      { num: 'T3', name: 'Electric Circuits' },
      { num: 'T4', name: 'Materials' },
      { num: 'T5', name: 'Waves & Particle Nature of Light' },
      { num: 'T6', name: 'Further Mechanics' },
      { num: 'T7', name: 'Electric & Magnetic Fields' },
      { num: 'T8', name: 'Nuclear & Particle Physics' },
      { num: 'T9', name: 'Thermodynamics' },
      { num: 'T10', name: 'Space' },
      { num: 'T11', name: 'Nuclear Radiation' },
      { num: 'T12', name: 'Gravitational Fields' },
      { num: 'T13', name: 'Oscillations' },
    ],
    'Physics|AQA': [
      { num: '3.1', name: 'Measurements and Their Errors' },
      { num: '3.2', name: 'Particles and Radiation' },
      { num: '3.3', name: 'Waves' },
      { num: '3.4', name: 'Mechanics and Materials' },
      { num: '3.5', name: 'Electricity' },
      { num: '3.6', name: 'Further Mechanics and Thermal Physics' },
      { num: '3.7', name: 'Fields and Their Consequences' },
      { num: '3.8', name: 'Nuclear Physics' },
    ],
    'Physics|AQA|gcse': [
      { num: '4.1', name: 'Energy' },
      { num: '4.2', name: 'Electricity' },
      { num: '4.3', name: 'Particle Model of Matter' },
      { num: '4.4', name: 'Atomic Structure' },
      { num: '4.5', name: 'Forces' },
      { num: '4.6', name: 'Waves' },
      { num: '4.7', name: 'Magnetism and Electromagnetism' },
      { num: '4.8', name: 'Space Physics' },
    ],
    'Physics|OCR A': [
      { num: 'M1', name: 'Development of Practical Skills' },
      { num: 'M2', name: 'Foundations of Physics' },
      { num: 'M3', name: 'Forces and Motion' },
      { num: 'M4', name: 'Electrons, Waves and Photons' },
      { num: 'M5', name: 'Newtonian World and Astrophysics' },
      { num: 'M6', name: 'Particles and Medical Physics' },
    ],
    'Physics|OCR A|gcse': [
      { num: 'P1', name: 'Matter' },
      { num: 'P2', name: 'Forces' },
      { num: 'P3', name: 'Electricity and Magnetism' },
      { num: 'P4', name: 'Waves and Radioactivity' },
      { num: 'P5', name: 'Energy' },
      { num: 'P6', name: 'Global Challenges' },
    ],
    'Physics|OCR B': [
      { num: 'B1', name: 'Development of Practical Skills' },
      { num: 'B2', name: 'Fundamental Data Analysis' },
      { num: 'B3', name: 'Physics in Action' },
      { num: 'B4', name: 'Understanding Processes' },
      { num: 'B5', name: 'Rise and Fall of the Clockwork Universe' },
      { num: 'B6', name: 'Field and Particle Physics' },
    ],

    // ── Economics ───────────────────────────────────────────────────
    'Economics|AQA': [
      { num: '3.1.1', name: 'Economic Problem & Methodology' },
      { num: '3.1.2', name: 'Price Determination' },
      { num: '3.1.3', name: 'Production Costs & Revenue' },
      { num: '3.1.4', name: 'Competitive & Concentrated Markets' },
      { num: '3.1.5', name: 'Market Failure & Government Intervention' },
      { num: '3.2.1', name: 'Measurement of Macroeconomic Performance' },
      { num: '3.2.2', name: 'How the Macroeconomy Works' },
      { num: '3.2.3', name: 'Economic Performance' },
      { num: '3.2.4', name: 'Financial Markets & Monetary Policy' },
      { num: '3.2.5', name: 'Fiscal & Supply-Side Policies' },
    ],
    'Economics|Edexcel A': [
      { num: '1.1', name: 'Nature of Economics & Markets' },
      { num: '1.2', name: 'Market Failure & Government Intervention' },
      { num: '2.1', name: 'Economic Performance & AD' },
      { num: '2.2', name: 'AS, National Income & Macro Policy' },
      { num: '3.1', name: 'Business Growth & Objectives' },
      { num: '3.2', name: 'Market Structures & Labour' },
      { num: '4.1', name: 'International Economics & Trade' },
      { num: '4.2', name: 'Poverty, Inequality & Development' },
    ],
    'Economics|Edexcel B': [
      { num: '1.1', name: 'How Markets Work & Surplus' },
      { num: '1.2', name: 'Market Failure & Government Intervention' },
      { num: '2.1', name: 'National Economic Performance' },
      { num: '2.2', name: 'Macroeconomic Policy' },
      { num: '3.1', name: 'Business Economics' },
      { num: '3.2', name: 'Market Structures & Competition' },
      { num: '4.1', name: 'International Economics & Globalisation' },
      { num: '4.2', name: 'Development & Inequality' },
    ],
    'Economics|OCR': [
      { num: '1.1', name: 'Economic Problem & Market Systems' },
      { num: '1.2', name: 'Market Failure & Government Intervention' },
      { num: '1.3', name: 'Firm Objectives, Costs & Revenue' },
      { num: '1.4', name: 'Market Structures' },
      { num: '2.1', name: 'National & International Economy' },
      { num: '2.2', name: 'AD/AS & Equilibrium' },
      { num: '2.3', name: 'Economic Policy' },
      { num: '2.4', name: 'International Economics & Development' },
    ],

    // ── Chemistry ───────────────────────────────────────────────────
    'Chemistry|AQA': [
      { num: 'P1', name: 'Physical Chemistry I' },
      { num: 'P2', name: 'Physical Chemistry II' },
      { num: 'I1', name: 'Inorganic Chemistry I' },
      { num: 'I2', name: 'Inorganic Chemistry II' },
      { num: 'O1', name: 'Organic Chemistry I' },
      { num: 'O2', name: 'Organic Chemistry II' },
    ],
    'Chemistry|Edexcel': [
      { num: 'T1', name: 'Atomic Structure, Bonding and Energetics' },
      { num: 'T2', name: 'Kinetics, Equilibrium and Redox' },
      { num: 'T3', name: 'Inorganic Chemistry' },
      { num: 'T4', name: 'Organic Chemistry I' },
      { num: 'T5', name: 'Thermodynamics, Acids & Bases' },
      { num: 'T6', name: 'Advanced Organic & Analysis' },
    ],
    'Chemistry|OCR A': [
      { num: 'M1', name: 'Development of Practical Skills' },
      { num: 'M2', name: 'Foundations in Chemistry' },
      { num: 'M3', name: 'Periodic Table and Energy' },
      { num: 'M4', name: 'Core Organic Chemistry' },
      { num: 'M5', name: 'Physical Chemistry & Transition Elements' },
      { num: 'M6', name: 'Organic Chemistry & Analysis' },
    ],
    'Chemistry|OCR B': [
      { num: 'S1', name: 'Foundations of Chemistry' },
      { num: 'S2', name: 'Energetics and Kinetics' },
      { num: 'S3', name: 'Equilibrium and Acid-Base' },
      { num: 'S4', name: 'Organic Chemistry' },
      { num: 'S5', name: 'Redox & Transition Metals' },
      { num: 'S6', name: 'Advanced Organic & Analysis' },
    ],

    // ── Biology ─────────────────────────────────────────────────────
    'Biology|AQA': [
      { num: 'T1', name: 'Biological Molecules' },
      { num: 'T2', name: 'Cells' },
      { num: 'T3', name: 'Organisms Exchange Substances' },
      { num: 'T4', name: 'Genetic Information & Variation' },
      { num: 'T5', name: 'Energy Transfers' },
      { num: 'T6', name: 'Organisms Respond to Changes' },
      { num: 'T7', name: 'Genetics, Populations & Evolution' },
      { num: 'T8', name: 'Control of Gene Expression' },
    ],
    'Biology|Edexcel A': [
      { num: 'T1', name: 'Molecules, Transport and Health' },
      { num: 'T2', name: 'Cells, Development and Biodiversity' },
      { num: 'T3', name: 'Exchange, Transport and Reproduction' },
      { num: 'T4', name: 'Energy, Environment and Microbiology' },
      { num: 'T5', name: 'Genetics and Evolution' },
      { num: 'T6', name: 'Immunity, Infection and Forensics' },
      { num: 'T7', name: 'Homeostasis and Response' },
      { num: 'T8', name: 'Gene Expression and Biotechnology' },
    ],
    'Biology|Edexcel B': [
      { num: 'S1', name: 'Lifestyle, Health and Risk' },
      { num: 'S2', name: 'Genes and Health' },
      { num: 'S3', name: 'Voice of the Genome' },
      { num: 'S4', name: 'Biodiversity and Natural Resources' },
      { num: 'S5', name: 'On the Wild Side' },
      { num: 'S6', name: 'Immunity, Infection and Forensics' },
      { num: 'S7', name: 'Run for Your Life' },
      { num: 'S8', name: 'Grey Matter' },
    ],
    'Biology|OCR A': [
      { num: 'M1', name: 'Development of Practical Skills' },
      { num: 'M2', name: 'Foundations in Biology' },
      { num: 'M3', name: 'Exchange and Transport' },
      { num: 'M4', name: 'Biodiversity, Evolution and Disease' },
      { num: 'M5', name: 'Communication, Homeostasis and Energy' },
      { num: 'M6', name: 'Genetics, Evolution and Ecosystems' },
    ],
    'Biology|OCR B': [
      { num: 'B1', name: 'Development of Practical Skills' },
      { num: 'B2', name: 'Cells, Chemicals and Transport' },
      { num: 'B3', name: 'Cell Division, Development and Disease' },
      { num: 'B4', name: 'Energy, Reproduction and Populations' },
      { num: 'B5', name: 'Genetics, Control and Homeostasis' },
      { num: 'B6', name: 'Biotechnology, Ecosystems and Human Impact' },
    ],

    // ── Geography ───────────────────────────────────────────────────
    'Geography|AQA': [
      { num: '1.1', name: 'Water & Carbon Cycles' },
      { num: '1.2', name: 'Coastal Systems & Landscapes' },
      { num: '1.3', name: 'Hazards' },
      { num: '2.1', name: 'Changing Places' },
      { num: '2.2', name: 'Contemporary Urban Environments' },
      { num: '2.3', name: 'Population & the Environment' },
      { num: '2.4', name: 'Resource Security' },
      { num: '3.1', name: 'Fieldwork & Investigation' },
    ],
    'Geography|Edexcel': [
      { num: 'T1', name: 'Tectonic Processes & Hazards' },
      { num: 'T2', name: 'Landscape Systems' },
      { num: 'T3', name: 'Water Cycle & Water Insecurity' },
      { num: 'T4', name: 'Carbon Cycle & Energy Security' },
      { num: 'T5', name: 'Globalisation' },
      { num: 'T6', name: 'Diverse Places' },
      { num: 'T7', name: 'Superpowers' },
      { num: 'T8', name: 'Health, Human Rights & Intervention' },
    ],
    'Geography|OCR': [
      { num: '1.1', name: 'Landscape Systems' },
      { num: '1.2', name: "Earth's Life Support Systems" },
      { num: '1.3', name: 'Hazardous Earth' },
      { num: '2.1', name: 'Changing Spaces, Making Places' },
      { num: '2.2', name: 'Trade in the Contemporary World' },
      { num: '2.3', name: 'Global Migration' },
      { num: '2.4', name: 'Human Rights' },
      { num: '2.5', name: 'Power & Borders' },
    ],
    'Geography|Eduqas|alevel': [
      { num: '1.1', name: 'Coastal Landscapes' },
      { num: '1.2', name: 'Glaciated Landscapes' },
      { num: '1.3', name: 'Changing Places' },
      { num: '2.1', name: 'Water Cycle & Water Insecurity' },
      { num: '2.2', name: 'Carbon Cycle & Energy Security' },
      { num: '2.3', name: 'Global Migration' },
      { num: '2.4', name: 'Global Governance of Oceans' },
      { num: '2.5', name: '21st Century Challenges' },
      { num: '3.1', name: 'Tectonic Hazards' },
      { num: '3.2', name: 'Ecosystems' },
    ],
    'Geography|Eduqas|gcse': [
      { num: '1.1', name: 'Coastal Landscapes' },
      { num: '1.2', name: 'River Landscapes' },
      { num: '1.3', name: 'Glaciated Landscapes' },
      { num: '1.4', name: 'Weather & Climate' },
      { num: '1.5', name: 'Tropical Rainforests' },
      { num: '1.6', name: 'Hot Deserts' },
      { num: '2.1', name: 'Urbanisation & Urban Change' },
      { num: '2.2', name: 'UK Cities' },
      { num: '2.3', name: 'Global Development' },
      { num: '3.1', name: 'Tectonic Hazards' },
      { num: '3.2', name: 'Climate Change' },
      { num: '3.3', name: 'Water Management' },
    ],

    // ── Mathematics ─────────────────────────────────────────────────
    'Mathematics|OCR|alevel': [
      { num: '1.1', name: 'Proof' },
      { num: '1.2', name: 'Algebra & Functions' },
      { num: '1.3', name: 'Coordinate Geometry' },
      { num: '1.4', name: 'Sequences & Series' },
      { num: '1.5', name: 'Trigonometry' },
      { num: '1.6', name: 'Exponentials & Logarithms' },
      { num: '1.7', name: 'Differentiation' },
      { num: '1.8', name: 'Integration' },
      { num: '1.9', name: 'Numerical Methods' },
      { num: '1.10', name: 'Vectors' },
      { num: '2.1', name: 'Statistics' },
      { num: '2.2', name: 'Mechanics' },
    ],
    'Mathematics|OCR|gcse': [
      { num: '1.1', name: 'Number: Arithmetic & Place Value' },
      { num: '1.2', name: 'Fractions, Decimals & Percentages' },
      { num: '1.3', name: 'Accuracy, Rounding & Estimation' },
      { num: '1.4', name: 'Powers, Roots & Standard Form' },
      { num: '2.1', name: 'Algebraic Expressions' },
      { num: '2.2', name: 'Equations & Inequalities' },
      { num: '2.3', name: 'Sequences' },
      { num: '2.4', name: 'Graphs' },
      { num: '3.1', name: 'Ratio & Proportion' },
      { num: '3.2', name: 'Rates of Change & Compound Measures' },
      { num: '4.1', name: 'Properties of Shapes & Angles' },
      { num: '4.2', name: 'Mensuration: Area, Perimeter & Volume' },
      { num: '4.3', name: 'Transformations' },
      { num: '4.4', name: "Pythagoras' Theorem & Trigonometry" },
      { num: '4.5', name: 'Circles & Constructions' },
      { num: '4.6', name: 'Vectors' },
      { num: '5.1', name: 'Probability' },
      { num: '6.1', name: 'Statistical Diagrams & Measures' },
      { num: '6.2', name: 'Cumulative Frequency, Histograms & Box Plots' },
    ],
    'Mathematics|AQA': [
      { num: '1.1', name: 'Proof' },
      { num: '1.2', name: 'Algebra & Functions' },
      { num: '1.3', name: 'Coordinate Geometry' },
      { num: '1.4', name: 'Sequences & Series' },
      { num: '1.5', name: 'Trigonometry' },
      { num: '1.6', name: 'Exponentials & Logarithms' },
      { num: '1.7', name: 'Differentiation' },
      { num: '1.8', name: 'Integration' },
      { num: '1.9', name: 'Numerical Methods' },
      { num: '1.10', name: 'Vectors' },
      { num: '2.1', name: 'Statistics' },
      { num: '2.2', name: 'Mechanics' },
    ],
    'Mathematics|Edexcel': [
      { num: 'P1',  name: 'Algebraic Expressions' },
      { num: 'P2',  name: 'Quadratics' },
      { num: 'P3',  name: 'Equations & Inequalities' },
      { num: 'P4',  name: 'Graphs & Transformations' },
      { num: 'P5',  name: 'Straight Lines & Circles' },
      { num: 'P6',  name: 'Trigonometric Ratios' },
      { num: 'P7',  name: 'Trig Identities & Equations' },
      { num: 'P8',  name: 'Exponentials & Logarithms' },
      { num: 'P9',  name: 'Differentiation (Year 1)' },
      { num: 'P10', name: 'Integration (Year 1)' },
      { num: 'P11', name: 'Vectors (Year 1)' },
      { num: 'P12', name: 'Algebraic Methods' },
      { num: 'P13', name: 'Functions & Graphs' },
      { num: 'P14', name: 'Sequences & Series' },
      { num: 'P15', name: 'Radians' },
      { num: 'P16', name: 'Trigonometric Functions' },
      { num: 'P17', name: 'Parametric Equations' },
      { num: 'P18', name: 'Differentiation (Year 2)' },
      { num: 'P19', name: 'Numerical Methods' },
      { num: 'P20', name: 'Integration (Year 2)' },
      { num: 'P21', name: 'Vectors (3D)' },
      { num: 'S1',  name: 'Statistical Sampling' },
      { num: 'S2',  name: 'Data Presentation & Measures' },
      { num: 'S3',  name: 'Probability' },
      { num: 'S4',  name: 'Binomial Distribution' },
      { num: 'S5',  name: 'Hypothesis Testing — Binomial' },
      { num: 'S6',  name: 'Regression & Correlation' },
      { num: 'S7',  name: 'Conditional Probability' },
      { num: 'S8',  name: 'Normal Distribution' },
      { num: 'M1',  name: 'Modelling in Mechanics' },
      { num: 'M2',  name: 'Kinematics (SUVAT)' },
      { num: 'M3',  name: "Forces & Newton's Laws" },
      { num: 'M4',  name: 'Moments' },
      { num: 'M5',  name: 'Variable Acceleration' },
      { num: 'M6',  name: 'Projectiles' },
      { num: 'M7',  name: 'Further Forces' },
    ],

    // ── Further Mathematics ─────────────────────────────────────────
    'Further Mathematics|AQA': [
      { num: '1.1', name: 'Complex Numbers' },
      { num: '1.2', name: 'Matrices' },
      { num: '1.3', name: 'Further Algebra & Functions' },
      { num: '1.4', name: 'Series' },
      { num: '1.5', name: 'Further Calculus' },
      { num: '1.6', name: 'Further Vectors' },
      { num: '1.7', name: 'Polar Coordinates' },
      { num: '1.8', name: 'Hyperbolic Functions' },
      { num: '1.9', name: 'Differential Equations' },
    ],
    'Further Mathematics|Edexcel': [
      { num: 'CP1.1', name: 'Complex Numbers' },
      { num: 'CP1.2', name: 'Argand Diagrams' },
      { num: 'CP1.3', name: 'Series' },
      { num: 'CP1.4', name: 'Roots of Polynomials' },
      { num: 'CP1.5', name: 'Volumes of Revolution' },
      { num: 'CP1.6', name: 'Matrices' },
      { num: 'CP1.7', name: 'Linear Transformations' },
      { num: 'CP1.8', name: 'Proof by Induction' },
      { num: 'CP1.9', name: 'Vectors' },
      { num: 'CP2.1', name: 'Complex Numbers (Further)' },
      { num: 'CP2.2', name: 'Series: Maclaurin & Taylor' },
      { num: 'CP2.3', name: 'Methods in Calculus' },
      { num: 'CP2.4', name: 'Volumes of Revolution (Further)' },
      { num: 'CP2.5', name: 'Polar Coordinates' },
      { num: 'CP2.6', name: 'Hyperbolic Functions' },
      { num: 'CP2.7', name: 'Methods in Differential Equations' },
      { num: 'CP2.8', name: 'Modelling with Differential Equations' },
    ],
    'Further Mathematics|OCR A': [
      { num: '1.1', name: 'Complex Numbers' },
      { num: '1.2', name: 'Matrices' },
      { num: '1.3', name: 'Further Algebra & Functions' },
      { num: '1.4', name: 'Further Calculus' },
      { num: '1.5', name: 'Further Vectors' },
      { num: '1.6', name: 'Polar Coordinates' },
      { num: '1.7', name: 'Hyperbolic Functions' },
      { num: '1.8', name: 'Differential Equations' },
      { num: '1.9', name: 'Numerical Methods' },
      { num: '1.10', name: 'Proof by Induction' },
      { num: 'D1.1', name: 'Graph Theory' },
      { num: 'D1.2', name: 'Networks & Algorithms' },
      { num: 'D1.3', name: 'Linear Programming' },
      { num: 'D1.4', name: 'Game Theory' },
      { num: 'D1.5', name: 'Recurrence Relations' },
      { num: 'M1.1', name: 'Dimensional Analysis' },
      { num: 'M1.2', name: 'Work, Energy & Power' },
      { num: 'M1.3', name: 'Impulse & Momentum' },
      { num: 'M1.4', name: 'Circular Motion' },
      { num: 'M1.5', name: 'Simple Harmonic Motion' },
      { num: 'S1.1', name: 'Discrete Random Variables' },
      { num: 'S1.2', name: 'Continuous Random Variables' },
      { num: 'S1.3', name: 'Statistical Inference' },
      { num: 'S1.4', name: 'Chi-Squared Tests' },
      { num: 'S1.5', name: 'Probability Generating Functions' },
    ],
    'Further Mathematics|OCR B': [
      { num: '1.1', name: 'Proof' },
      { num: '1.2', name: 'Complex Numbers' },
      { num: '1.3', name: 'Matrices' },
      { num: '1.4', name: 'Vectors' },
      { num: '1.5', name: 'Series' },
      { num: '1.6', name: 'Roots of Polynomials' },
      { num: '1.7', name: 'Polar Coordinates' },
      { num: '1.8', name: 'Hyperbolic Functions' },
      { num: '1.9', name: 'Further Calculus' },
      { num: '1.10', name: 'Differential Equations' },
      { num: 'A1.1', name: 'Graphs & Networks' },
      { num: 'A1.2', name: 'Network Algorithms' },
      { num: 'A1.3', name: 'Linear Programming' },
      { num: 'A1.4', name: 'Critical Path Analysis' },
      { num: 'A1.5', name: 'Simulation' },
      { num: 'M1.1', name: 'Dimensional Analysis' },
      { num: 'M1.2', name: 'Work, Energy & Power' },
      { num: 'M1.3', name: 'Impulse & Momentum' },
      { num: 'M1.4', name: 'Circular Motion' },
      { num: 'M1.5', name: 'Centres of Mass' },
      { num: 'S1.1', name: 'Discrete Random Variables' },
      { num: 'S1.2', name: 'Poisson Distribution' },
      { num: 'S1.3', name: 'Bivariate Data' },
      { num: 'S1.4', name: 'Chi-Squared Tests' },
      { num: 'S1.5', name: 'Non-Parametric Tests' },
    ],

    // ── English Language ────────────────────────────────────────────
    'English Language|AQA': [
      { num: '1.1', name: 'Methods of Language Analysis' },
      { num: '1.2', name: 'Textual Variations and Representations' },
      { num: '1.3', name: "Children's Spoken Language Development" },
      { num: '1.4', name: "Children's Written Language Development" },
      { num: '2.1', name: 'Language Diversity (Regional & Social)' },
      { num: '2.2', name: 'Language and Gender' },
      { num: '2.3', name: 'Language and Ethnicity / World Englishes' },
      { num: '2.4', name: 'Language Change' },
      { num: '2.5', name: 'Language Discourses' },
      { num: '3.1', name: 'Language Investigation (NEA)' },
      { num: '3.2', name: 'Original Writing & Commentary (NEA)' },
    ],
    'English Language|Edexcel': [
      { num: '1.1', name: 'Individual and Social Variation' },
      { num: '1.2', name: 'Historical Language Change' },
      { num: '1.3', name: 'Global and Regional Variation' },
      { num: '2.1', name: "Children's Spoken Language Development" },
      { num: '2.2', name: "Children's Written Language Development" },
      { num: '3.1', name: 'Global English (Paper 3 pathway)' },
      { num: '3.2', name: 'Language and Gender Identity (Paper 3 pathway)' },
      { num: '3.3', name: 'Language of Journalism (Paper 3 pathway)' },
      { num: '3.4', name: 'Language and Power (Paper 3 pathway)' },
      { num: '3.5', name: 'Language and Regional Variation (Paper 3 pathway)' },
      { num: '4.1', name: 'Crafting Language (NEA)' },
    ],
  };

  // Helpers — mirror notes.html's lookup semantics
  function currentLevelSuffix() {
    const l = (localStorage.getItem('cached_level') || 'gcse').toLowerCase();
    return (l === 'a-level' || l === 'as') ? 'alevel' : 'gcse';
  }

  function topicsFor(subject, board) {
    const base = `${subject}|${board}`;
    const key = `${base}|${currentLevelSuffix()}`;
    return FLASHCARDS_TOPICS[key] || FLASHCARDS_TOPICS[base] || null;
  }

  // Card background palette (white + user's 4 picks)
  const CARD_PALETTE = [
    { name: 'White',   hex: '#FFFFFF' },
    { name: 'Blush',   hex: '#ECA1A6' },
    { name: 'Mauve',   hex: '#D6CBD3' },
    { name: 'Sage',    hex: '#BDCEBE' },
    { name: 'Cream',   hex: '#FEFBD8' },
  ];

  window.FLASHCARDS_TOPICS  = FLASHCARDS_TOPICS;
  window.FLASHCARDS_TOPICS_FOR = topicsFor;
  window.FLASHCARDS_PALETTE = CARD_PALETTE;
})();
