-- A-Level Politics Flashcards — Edexcel (9PL0)
-- Generated for the RAG Learning study app from the notes and question banks.
-- One INSERT per topic. card_order restarts at 1 within each topic.
--
-- SAFE TO RE-RUN: the DELETE below clears any previous Politics/Edexcel/alevel
-- rows first, so running this file twice does not duplicate cards.
--
-- WHAT IS HERE: 28 topics x 8 cards = 224. All 28 are loaded, including BOTH
-- Component 3 routes (3A USA and 3B Global). A student sits only one route,
-- and the flashcards page filters by the topics a student has, so loading
-- both costs nothing and lets a student who switches route keep working.
--
-- TOPIC IDS match topics-config.js and the question banks exactly. They are
-- the join key, so do not renumber them here without renumbering everywhere.

-- ---------------------------------------------------------------
-- Schema: add 'level' column if not present (idempotent).
-- Politics is A-Level only, so every row below is level = 'alevel'.
-- ---------------------------------------------------------------
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'alevel'
  CHECK (level IN ('gcse','as','alevel'));

-- ---------------------------------------------------------------
-- Clear any existing Politics/Edexcel cards so this file is re-runnable.
-- Note this touches ONLY exam_board = 'Edexcel'; the AQA Politics cards
-- loaded by flashcards-politics-alevel-content.sql are untouched.
-- ---------------------------------------------------------------
DELETE FROM flashcards
 WHERE subject = 'Politics' AND exam_board = 'Edexcel' AND level = 'alevel';


-- ===============================================================
-- COMPONENT 1 — UK POLITICS (SECTION A)
-- ===============================================================

-- Topic 1.1 — Democracy and Participation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'Define legitimacy.', 'The rightful use of power in accordance with pre-set criteria or widely-held agreements — for example a government''s right to rule following an election.', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'Distinguish direct from representative democracy.', 'Direct: citizens decide policy questions themselves, as in a referendum. Representative: citizens elect representatives who deliberate and decide on their behalf. The UK is representative with increasing direct elements since 1997.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'What is a democratic deficit?', 'A flaw in the democratic process where decisions are taken by bodies lacking sufficient accountability to the electorate — most often applied in the UK to FPTP''s disproportionality and to the unelected House of Lords.', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'Give the turnout and result of the 2014 Scottish independence referendum.', '84.6% turnout; 55.3% No. The highest turnout of any modern UK-wide vote, and the first to use votes at 16.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'Distinguish sectional from promotional pressure groups.', 'Sectional (interest) groups represent a specific group and membership is usually restricted — BMA, Unite. Promotional (cause) groups campaign on an issue and are open to anyone — Greenpeace, Liberty.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'What determines whether a pressure group succeeds?', 'Alignment with government priorities, access to decision-makers, resources, expertise the government needs, and public sympathy — not the group''s type. Compare the Snowdrop Campaign''s success with the Countryside Alliance''s failure.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'State the key limitation of the Human Rights Act 1998.', 'It is an ordinary statute, so a government with a Commons majority can amend or repeal it. A s.4 declaration of incompatibility does not invalidate the offending provision — Parliament decides whether to respond.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.1', 'Democracy and Participation', 'Is there a participation crisis in the UK?', 'Turnout and party membership have fallen, but pressure group and campaign activity has risen — a change in the FORM of participation. The newer forms are more episodic and more unequally spread by class, age and education, so the crisis is one of EQUALITY rather than quantity.', 8, 'alevel');

-- Topic 1.2 — Political Parties
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'Define the doctrine of the mandate.', 'A governing party has the authority and the obligation to implement the programme on which it was elected. It underpins the Salisbury Convention, under which the Lords does not block manifesto commitments.', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'What did the Political Parties, Elections and Referendums Act 2000 do?', 'Created the Electoral Commission, required reporting of donations above a threshold, banned foreign donations and capped national campaign spending. It followed the Neill Report of 1998.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'What is Short money?', 'Public funding for opposition parties in the Commons to support their parliamentary work. Cranborne money is the Lords equivalent — so partial state funding of parties already exists.', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'Contrast One Nation conservatism with the New Right.', 'One Nation (Disraeli): the privileged owe obligations to the less fortunate, and social cohesion may require state provision. New Right: such provision breeds dependency; combines neo-liberal economics with neo-conservative social policy.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'When and why was Clause IV rewritten?', 'In 1995, under Blair. The original 1918 clause committed Labour to common ownership of the means of production; the revision symbolised acceptance of the market economy and the Third Way.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'Give the 2015 figures showing FPTP''s effect on minor parties.', 'UKIP: 12.6% of the vote, 1 seat. SNP: 4.7% of the vote, 56 seats. Concentration of support beats size of support under FPTP.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'Is the UK still a two-party system?', 'Multi-party competition at the level of VOTES and two-party dominance at the level of SEATS. The gap is produced by the electoral system, which is a more precise answer than choosing one label.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.2', 'Political Parties', 'When did UK parties converge, and when did they diverge?', 'Convergence roughly 1994–2008, as both accepted the market economy and competed for the median voter. Divergence returned after 2015 over austerity, public ownership and Brexit. Both are driven by the same thing — the pursuit of a winning coalition.', 8, 'alevel');

-- Topic 1.3 — Electoral Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'Name the four electoral systems on the Edexcel specification and where each is used.', 'FPTP — Westminster, English and Welsh locals, mayors and PCCs May 2023–May 2026. AMS — Scottish Parliament, London Assembly (and the Senedd until 2026; closed-list PR from 2026). STV — Northern Ireland Assembly and locals, Scottish locals. SV — mayors and PCCs until 2023, restored from June 2026.', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'How does the Additional Member System work?', 'Two votes: one for a constituency member elected by FPTP, one for a regional party list. List seats top up each party''s representation to reflect its regional vote share more closely. Scotland: 73 constituency + 56 regional.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'State the Droop quota formula used in STV.', 'quota = (total valid votes ÷ (seats + 1)) + 1. Surpluses above the quota transfer at reduced value; lowest-placed candidates are eliminated and their votes transferred.', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'Give two elections where the party with more votes won fewer seats.', '1951 (Labour led on votes, Conservatives on seats) and February 1974 (Conservatives led on votes, Labour on seats). FPTP can reverse the order of the two largest parties entirely.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'What was the result of the 2011 AV referendum?', 'Rejected 67.9% to 32.1% on 42.2% turnout. Conceded by the Conservatives as the price of coalition; AV is not itself proportional; the result has been treated as settling electoral reform for a generation.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'Which UK referendum used a turnout threshold, and what happened?', 'The 1979 Scottish devolution referendum required 40% of the electorate to vote Yes. Scotland voted Yes but fell below the threshold, so the result was voided. It is the only threshold ever used.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'Why is STV used in Northern Ireland?', 'Multi-member constituencies and transferable preferences ensure both communities are represented everywhere, so no single bloc can govern alone — which makes the Good Friday Agreement''s power-sharing executive consistent with the electoral outcome.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.3', 'Electoral Systems', 'What is the strongest judgement on FPTP reform?', 'It turns on what elections are FOR. If they exist to choose and remove a government, FPTP performs well; if to represent the distribution of opinion, badly. The two purposes genuinely conflict.', 8, 'alevel');

-- Topic 1.4 — Voting Behaviour and the Media
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'Distinguish class dealignment from partisan dealignment.', 'Class dealignment: the weakening link between social class and party support. Partisan dealignment: the weakening of voters'' habitual attachment to a party. The two are connected and both accelerated from the 1970s.', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'Define valence voting.', 'Choosing on the basis of which party is judged more COMPETENT to deliver goals voters broadly share, rather than on disagreement about what the goals should be. It explains why economic reputation tracks electoral fortune so closely.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'Give the 1979 result and its significance.', 'Conservative 339 seats on 43.9%; majority of 43; turnout 76.0%. Followed the Winter of Discontent. Significant for the C2 swing — early evidence of class dealignment — and for ending the post-war consensus.', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'Give the 1997 result and its significance.', 'Labour 418 seats on 43.2%; majority of 179 (177 on the stricter count that treats the Speaker as Labour — both figures are in circulation), the largest since 1935. The clearest case of valence voting: New Labour had accepted the market economy, so the contest turned on competence and the exhaustion of the incumbent.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'Give the 2019 result and its significance.', 'Conservative 365 seats on 43.6%; majority of 80. A realignment rather than a swing — leave-voting Labour seats in the Midlands and North moved Conservative. Largely reversed by 2024.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'What is agenda-setting?', 'The media''s capacity to shape which issues are treated as important, and so the ground an election is fought on — rather than telling people what to think. Better supported than direct conversion effects.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'What does reinforcement theory claim about the media?', 'That coverage mainly confirms existing preferences, because readers select outlets that already agree with them. Combined with reverse causation — proprietors back likely winners — it explains why media influence is hard to demonstrate.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.4', 'Voting Behaviour and the Media', 'Have long-term factors stopped explaining UK voting behaviour?', 'No — the RELEVANT long-term factors have changed. Age, education and housing tenure now predict party support at least as strongly as occupational class once did. The real change is that these divides cut ACROSS the party system rather than aligning with it.', 8, 'alevel');

-- ===============================================================
-- COMPONENT 1 — CORE POLITICAL IDEAS (SECTION B)
-- ===============================================================

-- Topic 1.5 — Conservatism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'State the three dimensions of human imperfection.', 'Moral (prone to selfishness and vice, so order and law are necessary); psychological (insecure, drawn to the familiar, which grounds tradition); intellectual (reality is too complex to grasp, which grounds pragmatism and the rejection of utopianism).', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'What does ''change to conserve'' mean?', 'Society should adapt to changing circumstances precisely in order to preserve what is valuable. Burke: a state without the means of some change is without the means of its own conservation.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'Give Burke''s definition of society.', 'A partnership between the living, the dead and those yet to be born. It establishes the organic view, justifies tradition, and explains why the present generation cannot simply override inherited institutions.', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'Name the five Edexcel conservative thinkers.', 'Thomas Hobbes, Edmund Burke, Michael Oakeshott, Ayn Rand, Robert Nozick.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'Summarise Hobbes''s position and why it sits awkwardly in the tradition.', 'Without a sovereign, life would be ''solitary, poor, nasty, brutish, and short''; order must precede liberty and the sovereign must be absolute. Awkward because he reaches this by a RATIONAL CONTRACT between calculating individuals — the method of early liberalism.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'Summarise Nozick''s entitlement theory.', 'A distribution is just if each holding was justly acquired and justly transferred, whatever pattern results. Redistributive taxation violates self-ownership by treating some people''s talents and earnings as a resource for others.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'What is Oakeshott''s account of conservatism?', 'A disposition rather than a doctrine: a preference ''for the familiar to the unknown, for the tried to the untried''. Politics is a practical activity, not the application of theory.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.5', 'Conservatism', 'State the internal tension within the New Right.', 'It fuses neo-liberal free markets with neo-conservative social order — but free markets dissolve the settled communities its social conservatism wants preserved. This is why the New Right is contested as conservatism at all.', 8, 'alevel');

-- Topic 1.6 — Liberalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Distinguish negative from positive freedom.', 'Negative: the absence of external constraint and non-interference in the private sphere (classical). Positive: the capacity for self-realisation, which may require removing social obstacles (modern). This single disagreement generates every other split in liberalism.', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Distinguish foundational, formal and opportunity equality.', 'Foundational: rights held by all by virtue of being born. Formal: the same legal and political rights. Opportunity: equal chances to rise and fall. Liberals hold all three and reject equality of OUTCOME.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Name the five Edexcel liberal thinkers.', 'John Locke, Mary Wollstonecraft, John Stuart Mill, John Rawls, Betty Friedan. Note: FIVE, not six — T. H. Green is an AQA thinker and is NOT on the Edexcel specification.', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'State Mill''s harm principle.', 'The only purpose for which power can rightfully be exercised over any member of a civilised community, against their will, is to prevent harm to others. Conduct affecting only the individual is not a legitimate object of coercion.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Explain Rawls''s veil of ignorance and difference principle.', 'Choose principles of justice without knowing your own class, talents or circumstances. You would choose equal basic liberties first, then permit inequalities only where they work to the greatest benefit of the least advantaged.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Why is Mill described as a bridge between classical and modern liberalism?', 'He defends negative freedom through the harm principle while treating liberty as the condition for individual DEVELOPMENT — the developmental argument later liberals used to justify the enabling state.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Why have liberals been ambivalent about democracy?', 'Fear of the tyranny of the majority. Mill proposed plural voting weighted towards the educated; early liberals restricted the franchise to property owners. The resolution is LIBERAL democracy — majority rule constrained by entrenched rights.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.6', 'Liberalism', 'Summarise Wollstonecraft''s argument.', 'Women are rational beings and therefore entitled to the same natural rights and education as men; their apparent frivolity is produced by an education designed to produce it. This EXTENDS liberalism rather than departing from it.', 8, 'alevel');

-- Topic 1.7 — Socialism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'What do socialists mean by malleable human nature?', 'Human nature is shaped substantially by social and economic conditions rather than fixed. The selfishness others treat as natural is produced by a system that rewards it. This is the premise that makes socialism achievable rather than utopian.', 1, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'Name the five Edexcel socialist thinkers.', 'Karl Marx and Friedrich Engels (counted together), Beatrice Webb, Rosa Luxemburg, Anthony Crosland, Anthony Giddens.', 2, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'State the four elements of the socialist critique of capitalism.', 'Exploitation (owners appropriate the surplus labour creates); alienation (labour as a commodity separates workers from their work and potential); inequality (wealth concentrates and reproduces); instability and waste (crises, unemployment, misdirected resources).', 3, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'Explain historical materialism.', 'Marx''s claim that the economic base shapes the social, legal and political superstructure, and that history advances through class conflict driven by contradictions within each mode of production.', 4, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'What was the Fabian ''inevitability of gradualism''?', 'Sidney Webb''s 1923 phrase for the Fabian view, shared with Beatrice Webb, that extending the franchise made a democratic majority for socialism certain, so the task was to PERMEATE existing institutions with socialist ideas and expertise rather than to overthrow them.', 5, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'Why did Luxemburg reject both Bernstein and Lenin?', 'Bernstein''s reformism leaves ownership relations intact and may stabilise capitalism; Lenin''s vanguard party would substitute itself for the class and end by ruling over it. Both objections rest on one commitment: revolution must be the DEMOCRATIC act of the working class.', 6, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'Distinguish Crosland from Giddens.', 'Crosland kept EQUALITY OF OUTCOME as the goal and dropped nationalisation as the means. Giddens dropped equality of outcome too, substituting opportunity. That is why Crosland sits within socialism and the Third Way is contested.', 7, 'alevel'),
  ('Politics', 'Edexcel', '1.7', 'Socialism', 'State the socialist objection to meritocracy.', 'The talents and circumstances that determine merit are themselves unequally distributed and largely unearned, so a meritocracy LEGITIMISES inequality by presenting it as deserved rather than removing it.', 8, 'alevel');

-- ===============================================================
-- COMPONENT 2 — UK GOVERNMENT (SECTION A)
-- ===============================================================

-- Topic 2.1 — The Constitution
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'Describe the UK constitution in three words, and define each.', 'Uncodified (not collected in a single document — not ''unwritten''); unentrenched (changeable by ordinary Act of Parliament); unitary (sovereignty held centrally, with regional power devolved from the centre).', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'Name the five sources of the UK constitution.', 'Statute law; common law (including the royal prerogative); conventions; works of authority (Erskine May, Bagehot, the Cabinet Manual); treaties.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'State Dicey''s twin pillars and the tension between them.', 'Parliamentary sovereignty and the rule of law. The tension: if Parliament may legislate on anything, it may legislate contrary to the rule of law, and no court may stop it.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'List the main constitutional reforms since 1997.', 'Devolution (1998 onwards); Human Rights Act 1998; House of Lords Act 1999; Freedom of Information Act 2000; Constitutional Reform Act 2005; Fixed-term Parliaments Act 2011 (repealed 2022).', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'What pattern do the post-1997 reforms show?', 'Power was dispersed OUTWARDS (devolution), UPWARDS (rights law) and SIDEWAYS (a separate Supreme Court) — while the centre was left untouched. Executive dominance of the Commons is essentially as it was.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'Why is UK devolution described as quasi-federal?', 'Repealing devolution remains legally possible and politically near-unthinkable, so the powers behave as though entrenched without being so. Miller (2017) held the Sewel Convention judicially unenforceable.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'Give the strongest argument against codification.', 'It is circular and practical: the settlement would have to be agreed by the institutions whose own position it would determine, and the UK has no convention mechanism for producing one — which is why it has been discussed for decades without progressing.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.1', 'The Constitution', 'Does parliamentary sovereignty still describe the UK?', 'It is accurate as a description of LEGAL authority — Brexit proved even the deepest constraint was reversible — and increasingly misleading as a description of how the constitution OPERATES, since the constraints are now political, real but unenforceable.', 8, 'alevel');

-- Topic 2.2 — Parliament
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'State the composition of the two Houses.', 'Commons: 650 MPs, directly elected in single-member constituencies, terms up to five years. Lords: appointed life peers and 26 Lords Spiritual, serving for life, with no cap on size; the 92 remaining hereditary peers were removed in 2026.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'What did the Parliament Acts 1911 and 1949 establish?', 'That the Lords may delay most public bills for around a year but cannot ultimately block them. Used rarely — the War Crimes Act 1991, the European Parliamentary Elections Act 1999 and the Hunting Act 2004.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'Distinguish a public bill committee from a select committee.', 'Public bill committee: temporary, appointed for one bill, membership reflects the party balance so the government controls it. Select committee: permanent, scrutinises a department, chairs and members ELECTED by the House since 2010.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'What were the Wright reforms and why do they matter?', '2010 reforms introducing election of select committee chairs and members and creating the Backbench Business Committee. They removed the whips from the process and created a parliamentary career path independent of ministerial patronage.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'Define the payroll vote.', 'Around 140 ministers and parliamentary private secretaries bound by collective responsibility to support the government. It guarantees a large block of reliable votes before any argument is made.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'List the stages of a bill.', 'First reading (formal); second reading (debate on principle); committee stage (line by line); report stage (whole House considers amendments); third reading; the other House; ping-pong; royal assent.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'State the Lords paradox.', 'The chamber is useful BECAUSE its members are not elected — that is what supplies the expertise, independence and long view — and it lacks legitimacy for the same reason. Every reform that fixes the legitimacy problem removes what makes it valuable.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.2', 'Parliament', 'What determines how effectively Parliament scrutinises the executive?', 'Parliamentary ARITHMETIC rather than parliamentary design. Parliament is strongest when a government is weak and weakest when it is strong — the opposite of what a constitutional check should do.', 8, 'alevel');

-- Topic 2.3 — Prime Minister and Executive
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'What comprises the UK executive?', 'The Prime Minister, the Cabinet, junior ministers and government departments — supported by the civil service and by politically appointed special advisers.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'Define the royal prerogative and give three examples.', 'Powers formally belonging to the Crown but exercised by ministers, deriving from common law rather than statute. Examples: negotiating treaties, deploying the armed forces, appointments, honours, pardons.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'Distinguish individual from collective ministerial responsibility.', 'Individual: a minister is accountable for their own conduct and their department. Collective: ministers must publicly support government decisions or resign. Collective is enforced far more reliably, because it serves the PM''s interest.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'Why does individual responsibility rarely produce resignations?', 'The policy–operations distinction lets blame fall on officials or agencies; accountability has been separated from culpability; and a PM protects a minister unless the political cost of retention exceeds the cost of losing them.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'When has collective responsibility been formally suspended?', 'The 1975 EEC referendum and the 2016 EU referendum, when ministers were released to campaign on either side. Both concerned referendums on questions cutting across party lines.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'Name the four models of executive power.', 'Cabinet government; prime ministerial government; presidentialisation; the core executive. The core executive model treats power as distributed across a network whose members depend on one another for resources.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'What most determines a Prime Minister''s power?', 'The size and unity of the parliamentary majority, plus standing in the party and the country, circumstances, and personal skill. These are CONTINGENT resources rather than formal powers, which is why authority varies so sharply between holders.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.3', 'Prime Minister and Executive', 'Give the strongest evidence against the presidentialisation thesis.', 'Four of the last seven Prime Ministers were removed by their own parties without any general election — Thatcher 1990, May 2019, Johnson and Truss 2022. No president faces this.', 8, 'alevel');

-- Topic 2.4 — Relations Between the Branches
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'What did the Constitutional Reform Act 2005 do?', 'Created the UK Supreme Court, removed the Law Lords from the legislature, reformed the Lord Chancellor''s role and established the Judicial Appointments Commission — the only genuine separation of powers the UK has achieved.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'What can and cannot the UK Supreme Court do about incompatible legislation?', 'It CAN interpret legislation compatibly with Convention rights where possible (HRA s.3) and issue a declaration of incompatibility (s.4). It CANNOT strike down or invalidate an Act — Parliament decides whether to respond.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'Summarise Miller (2017).', 'The government could not trigger Article 50 using the prerogative, because withdrawal would remove rights conferred by statute. Only an Act of Parliament could authorise it.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'Summarise Miller/Cherry (2019).', 'The advice to prorogue Parliament for five weeks was unlawful and void, because a prorogation frustrating Parliament''s constitutional functions without reasonable justification exceeds the limits of the power. Prerogative is reviewable.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'How should the two Miller cases be characterised?', 'As the Court defending PARLIAMENT against the EXECUTIVE, not displacing Parliament — which is what makes the charge of judicial overreach contestable rather than obvious.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'Define elective dictatorship.', 'Lord Hailsham''s term for a system in which a government with a Commons majority faces few effective constraints between elections, because the executive is drawn from and controls the legislature and Parliament is sovereign.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'Where does sovereignty lie in the UK?', 'LEGAL sovereignty with Parliament, undivided — Brexit demonstrated this. POLITICAL sovereignty is shared between the electorate, the executive and the devolved institutions. The gap between the two has widened considerably since 1997.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.4', 'Relations Between the Branches', 'Does the UK have a separation of powers?', 'It separates the JUDICIARY (CRA 2005) and fuses the POLITICAL branches by design. Compared with the US, it concentrates power and delivers decisive government at the cost of weak legislative restraint — the same two goods traded in opposite proportions.', 8, 'alevel');

-- ===============================================================
-- COMPONENT 2 — NON-CORE POLITICAL IDEAS (SECTION B) — STUDENT SITS ONE
-- ===============================================================

-- Topic 2.5 — Anarchism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'Define anarchism and state what distinguishes it from liberalism.', 'Rejection of the state and of all compulsory authority. Liberals accept a limited state as the guarantor of liberty; anarchists regard even a minimal state as its violation — a difference of kind, not degree.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'Why do anarchists reject representative democracy?', 'Electing a representative transfers one''s will to another and recreates authority over oneself; participating in the state legitimises it. Anarchists object to democratic states, not only authoritarian ones.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'Name the five Edexcel anarchist thinkers.', 'Max Stirner, Pierre-Joseph Proudhon, Mikhail Bakunin, Peter Kropotkin, Emma Goldman.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'Explain Proudhon''s position on property.', '''Property is theft'' — but the target is property resting on exploitation, not POSSESSION based on use, which he defends. His mutualism proposes voluntary exchange between independent producers on fair terms.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'What was Bakunin''s warning to Marx?', 'That a workers'' state would become a new ruling class — in effect a dictatorship over the proletariat rather than of it — because any group holding state power acquires an interest in keeping it. The twentieth century is usually treated as vindicating him.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'Explain Kropotkin''s mutual aid.', 'Drawing on observation as a naturalist, he argued that CO-OPERATION is a factor in evolution and survival alongside competition, so human sociability is natural rather than imposed. It grounds anarcho-communism.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'State the central tension within anarchism.', 'Whether freedom is realised through co-operative common ownership (Kropotkin, Bakunin) or through the sovereignty of the individual against every collective claim (Stirner). They share an enemy and hold opposite views of what replaces it.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.5', 'Anarchism', 'Give the strongest objection to anarchism.', 'It has no answer to the RE-EMERGENCE of power. The objection is internal: anarchism''s own analysis — that power corrupts and those holding it acquire an interest in keeping it — applies to whatever arises after the state is gone.', 8, 'alevel');

-- Topic 2.6 — Ecologism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'Distinguish ecocentrism from anthropocentrism.', 'Ecocentrism places the ecosystem at the centre of moral concern and holds nature to have intrinsic value. Anthropocentrism treats nature as valuable chiefly as a resource serving human purposes. The distinction separates deep from shallow ecology.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'Define holism as ecologists use it.', 'The whole system is more than the sum of its parts and must be understood as a whole, because the parts are interdependent — so an intervention in one part produces consequences elsewhere that studying the part alone cannot predict.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'Name the five Edexcel ecologist thinkers.', 'Aldo Leopold, Rachel Carson, E. F. Schumacher, Murray Bookchin, Carolyn Merchant.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'State Leopold''s land ethic.', 'The boundaries of the moral community should be enlarged to include soils, waters, plants and animals — collectively, the land. Humanity changes from conqueror of the land-community to plain member and citizen of it.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'Give Schumacher''s central economic argument.', 'Natural resources are CAPITAL, not income. An economy consuming them without replacement is liquidating a stock while recording it as production. Hence ''small is beautiful'' and human-scale, appropriate technology.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'Summarise Bookchin''s social ecology and his criticism of deep ecology.', 'Ecological breakdown originates in HIERARCHY within human society. He attacked deep ecology for blaming humanity in general, which identifies nobody who benefits from destruction and nobody who could change it — and slides towards misanthropy.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'What is Merchant''s ecofeminist argument?', 'The Scientific Revolution replaced an organic conception of nature as a nurturing mother with a mechanistic one in which nature is inert matter to be mastered — and the same dualistic thinking that set culture above nature set men above women.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.6', 'Ecologism', 'Is ecologism a distinct ideology?', 'It supplies a complete worldview and breaks with the anthropocentrism every other ideology shares — but most strands attach to a prior analysis of domination (capital, hierarchy, patriarchy). Only deep ecology stands alone, and it has the least developed programme. Like nationalism, it is cross-cutting rather than free-standing.', 8, 'alevel');

-- Topic 2.7 — Feminism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'Distinguish sex from gender and explain why it matters.', 'Sex is biological; gender is the socially constructed roles and expectations attached to it. If subordination follows from gender it is social and can be changed — which is the foundational move of the whole ideology. De Beauvoir: ''one is not born, but rather becomes, a woman''.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'Define patriarchy.', 'Literally rule by the father; used to describe a society in which power and authority are systematically held by men, across both public institutions and private life. It identifies subordination as STRUCTURAL rather than as individual prejudice.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'Explain ''the personal is political''.', 'Relations within the private sphere — family, marriage, sexuality, domestic labour — are structured by power and are properly political. It brought domestic violence, marital rape (criminalised 1991) and unpaid work into political debate.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'Name the five Edexcel feminist thinkers.', 'Charlotte Perkins Gilman, Simone de Beauvoir, Kate Millett, Sheila Rowbotham, bell hooks.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'Summarise Gilman''s argument and remedy.', 'Women''s subordination is rooted in ECONOMIC DEPENDENCE created by the sexual division of labour in the home. Her remedy is structural: socialise domestic work through communal kitchens, laundries and childcare so women can enter paid employment.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'What does de Beauvoir mean by woman as ''the Other''?', 'Man is treated as the human norm and woman is defined in relation to him, which denies her status as a subject in her own right. Liberation requires transcendence — economic independence, work, and rejecting assigned roles.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'Summarise hooks''s intersectional critique.', 'Second-wave feminism generalised from white, middle-class, educated women. Friedan''s account of confinement to domesticity described a condition working-class and Black women, long required to work outside the home, did not share.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.7', 'Feminism', 'What does the pattern of feminism''s successes and failures show?', 'Where the constraint was LEGAL exclusion, legal remedy worked quickly. Where it is the distribution of unpaid work and the expectations attaching to it, decades of legal equality have produced little movement — vindicating the liberal strategy AND the radical diagnosis of what remains.', 8, 'alevel');

-- Topic 2.8 — Multiculturalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'Define multiculturalism and distinguish it from assimilation.', 'Positive endorsement of cultural and religious diversity, holding that minorities should maintain their identities while participating fully in public life. Assimilation expects minorities to abandon their culture and adopt the majority''s.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'Why do multiculturalists argue formal equality is insufficient?', 'Neutral rules are not neutral in effect — institutions are built around majority assumptions (the working week, public holidays, dress codes, curricula), so applying identical rules imposes costs on minorities that the majority does not bear.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'Name the five Edexcel multiculturalist thinkers.', 'Isaiah Berlin, Charles Taylor, Bhikhu Parekh, Tariq Modood, Will Kymlicka.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'Explain Berlin''s value pluralism and distinguish it from relativism.', 'There are several genuine human goods which may conflict and cannot all be realised together, with no single correct ranking. It is NOT relativism: judgement remains possible and some ways of life are worse than others.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'Explain Taylor''s politics of recognition.', 'Identity is formed dialogically, through interaction with others, so how others regard us partly constitutes who we are. Misrecognition is therefore a form of HARM, capable of inflicting a damaged self-image on a group across generations.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'State Kymlicka''s justification for minority rights and his key distinction.', 'Culture provides the CONTEXT OF CHOICE within which autonomy is exercised, and majority culture is sustained automatically by state institutions — so minority rights correct an asymmetry. External protections (shielding a minority) are justified; internal restrictions (constraining its own members) are not.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'What is Modood''s argument about religious identity?', 'Secular multiculturalism accommodates ETHNIC difference but not RELIGIOUS difference, recognising religious minorities only as ethnic groups and missing what matters most to them. He calls for moderate secularism and an inclusive remaking of national identity.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.8', 'Multiculturalism', 'Name the four main criticisms of multiculturalism.', 'Relativism (no ground for criticising any practice); harm to individuals within groups; essentialism (treating communities as bounded units with authentic representatives); and undermining social cohesion.', 8, 'alevel');

-- Topic 2.9 — Nationalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Distinguish a nation from a state.', 'A nation is a community bound by shared culture, language, history or identity — a sociological entity. A state is a political and legal entity with territory, population, government and sovereignty. Nationalism holds that the two should coincide.', 1, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Distinguish civic from ethnic nationalism.', 'Civic: the nation defined by shared political values, institutions and citizenship — open in principle to anyone. Ethnic: defined by common descent, culture and ancestry — inherited, not chosen. In practice a spectrum rather than a clean division.', 2, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Name the five Edexcel nationalist thinkers.', 'Jean-Jacques Rousseau, Johann Gottfried Herder, Giuseppe Mazzini, Marcus Garvey, Charles Maurras.', 3, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'What did Rousseau contribute to nationalism?', 'The general will — sovereignty belongs to the people as a collective body with a common interest. He supplied nationalism''s foundation of POPULAR SOVEREIGNTY: legitimate authority flows from the people rather than from a dynasty.', 4, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Explain Herder''s Volksgeist.', 'Each nation possesses a distinctive spirit expressed through its language, customs, folklore and history, which should be cherished. His nationalism is CULTURAL and pluralist — every culture has value and none is superior — and does not necessarily demand a state.', 5, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Summarise Mazzini and Maurras, and why both are on the specification.', 'Mazzini: liberal nationalism — nations should achieve independence then co-operate as free equals. Maurras: integral nationalism — the individual wholly subordinate to the nation, authoritarian and anti-democratic. They span the doctrine''s range, which is the point.', 6, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Explain Anderson''s ''imagined communities''.', 'Members will never meet most fellow nationals, so belonging must be imagined — as in any community beyond the face-to-face. Print capitalism, standardised languages and mass education made it possible. This explains nationalism''s force rather than dismissing it.', 7, 'alevel'),
  ('Politics', 'Edexcel', '2.9', 'Nationalism', 'Why have nationalism''s political consequences been so varied?', 'It supplies no principle for determining which groups COUNT as nations, so every nationalism must at some point deny to others the claim it makes for itself. That is structural, not a misuse — which is why it has been both the most liberating and the most destructive force of the modern era.', 8, 'alevel');

-- ===============================================================
-- COMPONENT 3A — COMPARATIVE POLITICS: USA (ROUTE 3A)
-- ===============================================================

-- Topic 3A.1 — US Constitution and Federalism
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'Describe the US Constitution in three words and define each.', 'Codified (collected in a single document — seven articles plus 27 amendments); entrenched (amendable only by a demanding special procedure); vague (broad language leaving meaning to interpretation, which gives the Supreme Court a continuing role).', 1, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'State the amendment process.', 'Proposal by a two-thirds vote in both houses of Congress, or a convention called by two-thirds of state legislatures (never used). Ratification by three-quarters of state legislatures, or state conventions (used once, for the 21st Amendment).', 2, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'Distinguish enumerated from implied powers.', 'Enumerated: explicitly listed as federal, mainly in Article I Section 8. Implied: inferred as necessary to carry out the enumerated ones, deriving from the necessary and proper clause. McCulloch v Maryland (1819) established them.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'What does the Tenth Amendment provide?', 'Powers not delegated to the federal government nor prohibited to the states are reserved to the states or the people — the constitutional basis of state authority.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'Give four examples of checks and balances.', 'Presidential veto and congressional override by two-thirds; Senate confirmation of appointments; Senate ratification of treaties by two-thirds; judicial review of statutes and executive action; congressional impeachment; the power of the purse.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'Trace the phases of US federalism.', 'Dual federalism (to the 1930s, separate spheres — ''layer cake''); co-operative federalism (1930s–60s, overlapping, grant-driven — ''marble cake''); New Federalism (1970s–90s, block grants returning discretion); contemporary sharp policy divergence between states.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'Why has federal power expanded?', 'Fiscal capacity; conditions attached to categorical grants; broad readings of the commerce clause from the 1930s; implied powers. Crucially the change came through INTERPRETATION rather than amendment, which is why the states could not block it.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3A.1', 'US Constitution and Federalism', 'What does the difficulty of amendment actually produce?', 'It does not prevent constitutional change — it determines WHO makes it. Because Article V is effectively unusable, the Supreme Court has become the de facto amending body, which is why confirmations carry such stakes.', 8, 'alevel');

-- Topic 3A.2 — US Congress
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'State the size, terms and constituencies of the two chambers.', 'House: 435 voting members, two-year terms, single districts apportioned by population. Senate: 100 members, six-year staggered terms, two per state regardless of population.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'List the exclusive powers of each chamber.', 'House: initiate revenue bills; impeach; elect the President if the Electoral College deadlocks. Senate: ratify treaties (two-thirds); confirm appointments; try impeachments (two-thirds to convict); elect the Vice President in deadlock.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'Why are congressional committees so powerful?', 'They control whether a bill advances — a chair who declines to schedule hearings can kill it without any vote — and they build lasting expertise, conduct oversight with subpoena power, and mark up the text that reaches the floor.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'Explain the filibuster and cloture.', 'A filibuster blocks a Senate measure by extending debate; cloture ends debate and currently needs 60 votes, so most legislation requires a supermajority and 41 senators can block. Removed for nominations in 2013 and for Supreme Court nominations in 2017.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'Define gerrymandering and state its effects.', 'Drawing district boundaries to advantage a party. It reduces competitive seats, weakens the link between statewide vote share and seats won, and makes members answerable to PRIMARY electorates rather than the whole constituency — reinforcing polarisation.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'Give the Senate malapportionment figures.', 'Wyoming''s roughly 580,000 residents and California''s nearly 40 million each elect two senators. Article V protects equal state suffrage from amendment without the consent of every state affected — the one genuinely unamendable provision.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'How has polarisation changed Congress?', 'Realignment removed the cross-party ideological overlap that supplied the coalitions supermajority thresholds require. Result: less legislation, more governing by omnibus and executive action, and oversight that tracks party control rather than institutional interest.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3A.2', 'US Congress', 'Is Congress subordinate to the presidency?', 'Its checks operate only when the opposing party holds a chamber, so they function as PARTISAN instruments rather than institutional ones. The separation of powers has been substantially displaced by the separation of parties.', 8, 'alevel');

-- Topic 3A.3 — US Presidency
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'List the formal powers in Article II.', 'Veto (overridable by two-thirds of both chambers); Commander-in-Chief; nomination of Cabinet, ambassadors and judges (Senate confirmation); treaty negotiation (Senate ratification by two-thirds); pardon for federal offences; the take care clause; recommending measures.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'What can the President NOT do?', 'Introduce legislation, dissolve Congress, or compel it to act. Every significant formal power is shared — which is why Article II is so short and the office depends on informal sources.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'List the informal sources of presidential power.', 'Executive orders; executive agreements; signing statements; the electoral mandate; the bully pulpit; party leadership; the Executive Office of the President.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'State the three limits on executive orders.', 'A successor may revoke them; the courts may strike them down; Congress may legislate contrary to them or withhold funds. They represent power WITHOUT DURABILITY.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'Summarise Neustadt''s argument.', 'Presidential power is the power to PERSUADE. The formal powers are too sparse to govern by command, so power consists in bargaining. A President reduced to issuing commands has already failed, because commanding shows persuasion was unavailable.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'What does the 22nd Amendment provide?', 'A President is limited to two elected terms. Authority ebbs towards lame-duck status as a second term proceeds.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'Why is impeachment a weak check?', 'Conviction requires two-thirds of the Senate, which polarisation makes unreachable unless the President''s own party defects. No President has ever been removed; Nixon resigned before a vote he would probably have lost, his party''s support having collapsed.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3A.3', 'US Presidency', 'Assess the imperial presidency thesis.', 'Power has expanded UNEVENLY — close to unchecked in war, national security and emergency; wholly dependent on party control of Congress in domestic policy. And the instruments gained are weaker than legislation, so the office is more powerful at any moment and less able to achieve anything lasting.', 8, 'alevel');

-- Topic 3A.4 — US Supreme Court and Civil Rights
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'State the Court''s size, tenure and case selection.', 'Nine justices, appointed for life during good behaviour. It hears roughly 60–80 cases a year from thousands of petitions, selected under the ''rule of four'' — four justices must agree to hear a case.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'What did Marbury v Madison (1803) establish, and why is that striking?', 'Judicial review — the power to declare acts unconstitutional. Striking because the power appears NOWHERE in the constitutional text; Marshall asserted it, and the other branches have accepted it for two centuries.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'Describe the appointment process.', 'A vacancy arises by death, retirement or removal; the President nominates; the Senate Judiciary Committee holds hearings and votes to report; the full Senate confirms by simple majority since the filibuster was removed in 2017.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'Why have confirmations become so contested?', 'Life tenure means one appointment fixes policy for a generation; the Court decides the most divisive questions; the filibuster''s removal ended the incentive to nominate a consensus candidate; and norm erosion (Garland 2016, Barrett 2020) showed the process runs on power.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'Distinguish judicial activism from judicial restraint.', 'Activism: willingness to strike down law, revisit precedent and give effect to broad principle. Restraint: deference to the elected branches, narrow rulings, close adherence to precedent. Note the labels are often applied to rulings the speaker dislikes.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'Name the key civil rights cases.', 'Dred Scott (1857); Plessy v Ferguson (1896); Brown v Board of Education (1954); Gideon v Wainwright (1963); Loving v Virginia (1967); Roe v Wade (1973); Citizens United (2010); Shelby County (2013); Obergefell (2015); Dobbs (2022); Students for Fair Admissions (2023).', 6, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'What is incorporation?', 'The application of the Bill of Rights against the STATES through the Fourteenth Amendment''s due process clause — progressively extending protections that originally bound only the federal government.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3A.4', 'US Supreme Court and Civil Rights', 'Why do Court rulings not always change practice?', 'It has neither an army nor a budget and depends on the executive, states and lower courts to implement. Brown met massive resistance and advanced decisively only once Congress passed the Civil Rights Act 1964 and the executive enforced it.', 8, 'alevel');

-- Topic 3A.5 — US Democracy and Participation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'Explain the Electoral College.', '538 electors — each state has its congressional representation, two senators plus House members; DC has three. 270 needed to win. All states except Maine and Nebraska allocate winner-takes-all. If no one reaches 270 the House elects, voting by state delegation.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'Give two elections where the popular-vote loser won.', '2000 and 2016. Winner-takes-all allocation, not the College itself, produces this — and also the concentration of campaigning on swing states.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'Distinguish a primary from a caucus, and closed from open.', 'Primary: a state-run election by secret ballot. Caucus: a party-run meeting where preferences are declared publicly, with much lower turnout. Closed: only registered party members may vote. Open: any registered voter.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'What is the invisible primary?', 'The period before voting begins, spent building funding, endorsements and name recognition. It screens the field before any voter participates, which is a central part of how money shapes American elections.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'What did Citizens United v FEC (2010) hold?', 'That independent political spending by corporations and unions is protected speech. Following Buckley v Valeo (1976), which held that spending is speech, it permitted unlimited independent expenditure and gave rise to Super PACs.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'Distinguish a PAC from a Super PAC.', 'A PAC may contribute directly to campaigns, subject to limits. A Super PAC may raise and spend UNLIMITED sums but may not contribute directly or coordinate with a campaign — a restriction widely regarded as weakly enforced.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'Define an iron triangle.', 'A stable, mutually beneficial relationship between a congressional committee, a federal agency and an interest group in the same policy area — which insulates that field from the President, the wider Congress and the public.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3A.5', 'US Democracy and Participation', 'Why do third parties fail in the US?', 'Single-member plurality districts and winner-takes-all allocation convert dispersed support into no offices — Perot won 18.9% in 1992 and no electoral votes. Ballot access costs, co-option by the major parties, and the primary route to capturing a party instead.', 8, 'alevel');

-- Topic 3A.6 — Comparative Approaches
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'Name the three comparative approaches and what each emphasises.', 'Rational — individuals calculating their own interests. Cultural — shared ideas, values and group attachments. Structural — the institutions, rules and processes that shape and constrain action. They are complementary rather than rival.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'Give a rational explanation of the difference in party discipline.', 'In the UK the party controls candidate selection, so loyalty is a precondition of a career and a confidence defeat threatens every seat. In the US primary voters control selection, members raise their own funds and face no confidence vote — so defying the leadership costs little.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'Give a structural explanation of the two judiciaries'' different power.', 'A codified entrenched constitution gives the US Court a HIGHER LAW to enforce against Congress; parliamentary sovereignty leaves the UK Court interpreting statute it cannot override. The cultural account risks circularity.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'State the key limitation of the cultural approach.', 'It risks circularity — attitudes may be CONSEQUENCES of institutional arrangements rather than their causes — and it struggles to explain change within a single country over time.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'Compare the UK and US executives in one sentence.', 'The PM is more powerful DOMESTICALLY and less secure IN OFFICE; the President is less able to legislate and cannot be removed by their party.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'What single structural cause explains that comparison?', 'Fusion concentrates power and makes the leader dependent on the party; separation disperses power and makes the leader independent of it.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'Why do US pressure groups have more access points?', 'Federalism creates fifty state governments as well as the federal; the separation of powers makes executive, both chambers and the courts independent routes; judicial review makes litigation effective; weak party discipline makes individual legislators worth lobbying.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3A.6', 'Comparative Approaches', 'Are the UK and US systems converging?', 'Convergence is real at the level of PRACTICE — a separate Supreme Court, a rights instrument, quasi-federalism, referendums, leader-focused campaigns — and absent at the level of STRUCTURE, since fusion versus separation is untouched.', 8, 'alevel');

-- ===============================================================
-- COMPONENT 3B — GLOBAL POLITICS (ROUTE 3B)
-- ===============================================================

-- Topic 3B.1 — The State and Globalisation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'Distinguish internal from external sovereignty.', 'Internal: supreme authority over everything within the borders, including a monopoly of legitimate force. External: independence from outside interference and formal equality with other states regardless of power. A failed state retains the second while losing the first.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'What did the Westphalian settlement of 1648 establish?', 'Sovereign territorial states, formally equal, with non-intervention as the cardinal rule — now reflected in Article 2(7) of the UN Charter.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'Name the three dimensions of globalisation.', 'Economic (trade, investment, capital flows, production networks); political (international organisations and rules taking decisions once made by states); cultural (flows of ideas, images, media and consumer practices).', 3, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'Summarise the hyperglobalist, sceptical and transformationalist views.', 'Hyperglobalist: the nation state is becoming obsolete. Sceptical: globalisation is exaggerated — pre-1914 integration was comparable and states retain capacity. Transformationalist: real, but it transforms the state rather than ending it, and states largely CHOSE integration.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'How has globalisation constrained state autonomy?', 'Capital mobility narrows tax and regulatory choices; treaty obligations bind; transnational problems cross borders; multinationals shift production and profits; financial markets discipline fiscal policy directly, as the UK found in 2022.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'Why is that constraint described as uneven?', 'Large states with deep markets SHAPE the rules others are constrained by, so globalisation has REDISTRIBUTED autonomy as much as reduced it.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'What is pooled sovereignty?', 'States exercising certain powers jointly through a shared institution to achieve outcomes none could reach alone — the EU being the developed case. Whether this exercises or surrenders sovereignty is the contested question.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3B.1', 'The State and Globalisation', 'State the scale mismatch argument.', 'The problems that matter most now operate globally while democratic accountability remains national. That gap is the strongest structural explanation for the populist backlash — a response to a real loss of correspondence rather than a misperception.', 8, 'alevel');

-- Topic 3B.2 — Global Governance: Political and Economic
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'Name the principal organs of the UN and one weakness of each.', 'Security Council (the P5 veto paralyses it); General Assembly (resolutions non-binding); ECOSOC (limited authority over the agencies); ICJ (jurisdiction requires consent); Secretariat (depends on member funding).', 1, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'State the case for and against the Security Council veto.', 'Against: one member can block action however broad the support — Syria, Ukraine. For: without it the major powers would not have joined or remained; the League''s failure is the warning. Charter amendment needs P5 consent, so reform is structurally near-impossible.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'What is NATO''s Article 5, and how often has it been invoked?', 'An armed attack on one member is an attack on all. Invoked ONCE — after 11 September 2001, by the United States, for an alliance designed to protect Europe.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'Distinguish the roles of the IMF, World Bank and WTO.', 'IMF: monetary stability and short-term lending in balance of payments crises. World Bank: long-term development finance. WTO: administers trade rules and adjudicates disputes.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'Name four criticisms of the IMF and World Bank.', 'Weighted voting proportional to contribution; conditionality and structural adjustment; social consequences falling on health, education and subsidies; ideological uniformity (the Washington Consensus); and accountability to contributors rather than affected populations.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'What has happened to the WTO''s dispute settlement?', 'The Appellate Body ceased to function when the United States blocked appointments from 2019, so appeals cannot be heard. It is the strongest single piece of evidence for realism — the most legalised part of global governance was disabled by ONE state withdrawing consent.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'Distinguish the G7 from the G20.', 'G7: advanced economies, informal coordination. G20: includes major emerging economies and coordinated the 2008 crisis response. Neither has binding authority.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3B.2', 'Global Governance: Political and Economic', 'What is dependency theory?', 'That underdevelopment is caused by the structural position of poorer states in a global economy organised around the interests of the wealthy core — the periphery supplying raw materials and cheap labour.', 8, 'alevel');

-- Topic 3B.3 — Global Governance: Human Rights and Environmental
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'Trace the development of the international human rights regime.', 'UDHR 1948 (adopted with no dissenting vote, not binding); ICCPR and ICESCR 1966 (binding covenants); ECHR 1950 with the strongest enforcement record; ICC 2002 under the Rome Statute; ICTY and ICTR as the ad hoc precedents.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'Distinguish the ICJ from the ICC.', 'ICJ: settles disputes between STATES and gives advisory opinions; jurisdiction requires consent. ICC: prosecutes INDIVIDUALS for genocide, war crimes, crimes against humanity and aggression, on the principle of complementarity.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'What is complementarity?', 'The ICC acts only where a national jurisdiction is unwilling or unable genuinely to prosecute — so it supplements rather than replaces domestic justice.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'State the three pillars of R2P.', 'The state''s responsibility to protect its population; the international community''s responsibility to assist; and its responsibility to respond, through peaceful means first and Security Council-authorised collective action if necessary. Endorsed at the 2005 World Summit.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'Why does the Libya–Syria sequence matter for R2P?', 'Resolution 1973 authorised civilian protection in Libya in 2011 and was widely seen as stretched into regime change, which hardened Russian and Chinese resistance to later authorisations. An intervention undertaken to save lives may have reduced the capacity to save lives afterwards.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'What is jus cogens, and give three examples.', 'Peremptory norms binding on all states regardless of consent. Prohibitions on torture, slavery and genocide — the strongest evidence against the relativist objection to universal human rights.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'Distinguish the UNFCCC from the IPCC.', 'UNFCCC (1992): the treaty framework under which climate negotiation takes place, producing Kyoto and Paris through its annual COP. IPCC: assesses and synthesises the science for policymakers and sets no targets.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3B.3', 'Global Governance: Human Rights and Environmental', 'Compare Kyoto and Paris.', 'Kyoto (1997) imposed binding targets on developed states only; the US never ratified and Canada withdrew. Paris (2015) uses nationally determined contributions with transparency and review — trading bindingness for near-universal participation.', 8, 'alevel');

-- Topic 3B.4 — Power and Developments
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'Distinguish hard, soft, smart and structural power.', 'Hard: military or economic coercion. Soft (Nye): obtaining outcomes through attraction, resting on culture, values and perceived legitimacy. Smart: combining both coherently. Structural: shaping the frameworks others operate within — rules, standards, the reserve currency.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'State the key limitation of soft power.', 'It cannot be directed at will, works slowly, rarely shifts vital interests, and is easily destroyed by conduct. Its effect appears as an ABSENCE OF RESISTANCE rather than a visible outcome, which makes it real but very hard to measure.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'Define the three forms of polarity.', 'Unipolar: one preponderant state (the US after 1991). Bipolar: two dominant blocs (the Cold War) — realists often argue this is most stable. Multipolar: several comparable powers (Europe before 1914).', 3, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'Is the international system now multipolar?', 'Power is distributed unevenly ACROSS DIMENSIONS — economically multipolar, militarily closer to unipolar, institutionally between the two. No single label fits, and saying so is a better answer than choosing one.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'What do BRICS states do that is significant?', 'They build PARALLEL institutions — the Asian Infrastructure Investment Bank, the New Development Bank — rather than attacking existing ones, pressing for greater voice within the order they have benefited from.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'How does democratic decline now happen?', 'Rarely through coups. Elected leaders weaken courts, curtail media independence, alter electoral rules and hollow out institutions WHILE RETAINING elections — which makes the process gradual, deniable and difficult to resist.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'What is the HDI?', 'The Human Development Index — a composite measure of life expectancy, education and income, used to assess development beyond GDP per capita.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3B.4', 'Power and Developments', 'Why has power become harder to measure?', 'It is spread unevenly across dimensions; new domains (cyber, supply chains, standard-setting, information) do not reduce to conventional metrics; and power is RELATIONAL, so capacity for one objective does not transfer — military superiority did not deliver US objectives in Afghanistan.', 8, 'alevel');

-- Topic 3B.5 — Regionalism and the EU
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'Name the three forms of regionalism, and say which spreads most easily.', 'Economic, security and political. Economic spreads most widely because trade liberalisation offers measurable mutual gains WITHOUT requiring states to surrender authority over identity, security or law.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'List the stages of economic integration.', 'Free trade area (no internal tariffs); customs union (adds a common external tariff); single market (free movement of goods, services, capital and people, with harmonised regulation); monetary union (shared currency and central bank); political union.', 2, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'Distinguish supranationalism from intergovernmentalism.', 'Supranational: institutions can take decisions binding on members, including against an individual member''s wishes — qualified majority voting, directly effective law. Intergovernmental: states retain ultimate control, typically through unanimity.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'Name the EU institutions and what each represents.', 'Commission (the Union interest; sole right of initiative); Council of the EU (member governments); European Council (heads of government; direction); Parliament (citizens, directly elected); Court of Justice (EU law); ECB (eurozone monetary policy).', 4, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'What made the EU legal order genuinely supranational?', 'The Court''s doctrines of DIRECT EFFECT and SUPREMACY — EU law became enforceable in national courts at the suit of individuals, converting treaty obligations into rights citizens could claim. No other regional body has this.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'State the structural flaw exposed by the eurozone crisis.', 'Monetary union WITHOUT fiscal union. Members shared a currency and central bank but retained separate national budgets, so there was no transfer mechanism, and indebted members could not devalue — leaving only internal devaluation through austerity.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'What are the key EU treaty milestones?', 'ECSC 1951 and Treaty of Rome 1957; Single European Act 1986 (the single market programme); Maastricht 1992 (created the EU, path to monetary union); enlargement 2004–07; Lisbon 2009; UK withdrawal 31 January 2020, transition ending 31 December 2020.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3B.5', 'Regionalism and the EU', 'What does Brexit show about regionalism?', 'Integration is REVERSIBLE, correcting neofunctionalist ratchet accounts; national politics can override the economic logic of membership; but exit is costly, and the Brussels effect means leaving recovers formal sovereignty while leaving much practical constraint in place.', 8, 'alevel');

-- Topic 3B.6 — Comparative Theories
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'State the core assumptions of realism.', 'Anarchy — no authority above states; states are the primary actors, rational and unitary; survival is fundamental; self-help; relative gains matter more than absolute; order rests on the balance of power, not on law or institutions.', 1, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'Name the three variants of realism.', 'Classical (conflict originates in human nature); structural or neorealism, Waltz (in the system''s structure); offensive realism, Mearsheimer (states maximise power because it is the surest route to security).', 2, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'Explain the security dilemma.', 'Measures one state takes for its own security appear threatening to others, who respond in kind, leaving everyone less secure. It arises because no authority guarantees protection and intentions can change, so states must respond to CAPABILITIES rather than declarations.', 3, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'State the core assumptions of liberalism in international relations.', 'Anarchy is real but not fatal; multiple actors matter; institutions reduce uncertainty and make defection costly; interdependence raises the cost of conflict; absolute gains permit co-operation; the domestic character of states matters.', 4, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'State democratic peace theory and one qualification.', 'Established liberal democracies very rarely fight one another, though they fight non-democracies readily. Qualification: DEMOCRATISING states appear more conflict-prone than either stable democracies or autocracies, which weakens the policy conclusion.', 5, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'What does constructivism add?', 'It asks where interests COME FROM, arguing they are socially constructed through interaction and shared norms. Wendt: ''anarchy is what states make of it''. British and North Korean nuclear weapons present very different threats to Washington despite comparable material facts.', 6, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'Give the strongest evidence for realism and for liberalism.', 'Realism: the WTO Appellate Body disabled by one state withdrawing consent, and the Security Council''s paralysis on Syria and Ukraine. Liberalism: the EU, the trade regime''s durability, and the sheer density of routine compliance with international law.', 7, 'alevel'),
  ('Politics', 'Edexcel', '3B.6', 'Comparative Theories', 'What is the strongest judgement on the two theories?', 'They explain different DOMAINS rather than competing to explain the same one — realism the hard cases where vital interests conflict, liberalism the dense co-operation where they align. A system containing both nuclear deterrence and the European single market will not reduce to one logic.', 8, 'alevel');
