/*
 * OCR B A-Level Biology — Multiple Choice Question Bank
 * B1: 25 questions (10 green / 10 amber / 5 red) — smaller topic
 * B2–B6: 50 questions each (20 green / 20 amber / 10 red)
 * answer: 0-based index of correct option.
 */

const BIOLOGY_OCR_B_QUESTIONS = {

  /* ─────────────────────────────────────────────────────────── B1 */
  'B1': {
    name: 'Development of Practical Skills',
    green: [
      { q: 'What is the independent variable in an experiment?', options: ['The variable that is measured','The variable that is deliberately changed','The variable that is kept constant','The variable that cannot be controlled'], answer: 1 },
      { q: 'What is the dependent variable?', options: ['The variable deliberately changed by the experimenter','The variable kept the same throughout','The variable that is measured as the outcome','A variable that has no effect'], answer: 2 },
      { q: 'What are control variables?', options: ['Variables that are measured','Variables deliberately changed','Variables kept constant to ensure a fair test','Variables that increase over time'], answer: 2 },
      { q: 'Which piece of equipment is most appropriate for measuring the volume of a liquid to the nearest 0.1 cm³?', options: ['Measuring cylinder','Beaker','Burette','Volumetric flask'], answer: 2 },
      { q: 'What is a hypothesis?', options: ['A conclusion drawn after an experiment','A testable prediction about the outcome of an experiment','A list of apparatus needed','A type of graph'], answer: 1 },
      { q: 'What does "accuracy" mean in practical work?', options: ['How close a measured value is to the true value','How close repeated measurements are to each other','How many decimal places are used','How quickly results are obtained'], answer: 0 },
      { q: 'What does "precision" mean in practical work?', options: ['How close the result is to the true value','How close repeated measurements are to each other','The number of significant figures used','The range of measurements'], answer: 1 },
      { q: 'What is the purpose of repeating an experiment?', options: ['To use more chemicals','To identify anomalous results and improve reliability','To make the experiment take longer','To change the independent variable'], answer: 1 },
      { q: 'What type of error gives readings consistently too high or too low?', options: ['Random error','Systematic error','Zero error','Human error'], answer: 1 },
      { q: 'Which graph type is used for continuous data?', options: ['Bar chart','Pie chart','Line graph','Tally chart'], answer: 2 },
    ],
    amber: [
      { q: 'A student measures enzyme activity at different temperatures but fails to control pH. What type of variable is pH in this scenario?', options: ['Independent variable','Dependent variable','Confounding variable','Categoric variable'], answer: 2 },
      { q: 'Why is a water bath used rather than a Bunsen burner when investigating the effect of temperature on enzyme activity?', options: ['It heats faster','It provides a more uniform and controllable temperature','It is cheaper','It produces steam for the reaction'], answer: 1 },
      { q: 'A student obtains five readings: 3.2, 3.1, 3.3, 5.8, 3.2. Which value is anomalous?', options: ['3.1','3.2','3.3','5.8'], answer: 3 },
      { q: 'What is the correct procedure when calculating a mean with an anomalous result?', options: ['Include it in the mean','Exclude it and calculate mean from remaining values','Double it','Replace it with zero'], answer: 1 },
      { q: 'Why is a colorimeter more reliable than visual comparison for measuring colour change?', options: ['It is cheaper','It provides objective, quantitative measurements reducing human bias','It uses less solution','It measures temperature'], answer: 1 },
      { q: 'What is the resolution of a piece of measuring equipment?', options: ['Its maximum reading','The smallest change it can detect','Its accuracy','Its brand name'], answer: 1 },
      { q: 'In a serial dilution, each step dilutes by a factor of 10. Starting with 1 mol/dm³, what is the concentration after 3 dilutions?', options: ['0.1 mol/dm³','0.01 mol/dm³','0.001 mol/dm³','0.0001 mol/dm³'], answer: 2 },
      { q: 'What is the purpose of a control group in an experiment?', options: ['To provide a baseline for comparison','To increase the number of results','To test two variables at once','To measure the independent variable'], answer: 0 },
      { q: 'A microscope eyepiece graticule must be calibrated using which item?', options: ['A ruler','A stage micrometer','A protractor','A thermometer'], answer: 1 },
      { q: 'Why should a student draw a line of best fit rather than joining all points on a scatter graph?', options: ['It looks neater','It shows the general trend and reduces impact of random errors','It makes the graph bigger','It connects anomalous results'], answer: 1 },
    ],
    red: [
      { q: 'A student claims their results are "accurate because they are precise." Evaluate this statement.', options: ['Correct — repeats always give accurate results','Incorrect — results can be precise but not accurate if there is a systematic error','Incorrect — precision is not measurable','Correct — precision and accuracy mean the same thing'], answer: 1 },
      { q: 'An experiment shows a strong positive correlation between two variables. Can causation be concluded?', options: ['Yes — correlation always means causation','No — correlation does not prove causation','Yes — if the correlation is strong','No — correlation is meaningless'], answer: 1 },
      { q: 'A student uses a 10 cm³ measuring cylinder (±0.5 cm³) to measure 5 cm³. What is the percentage uncertainty?', options: ['5%','0.5%','1%','10%'], answer: 3 },
      { q: 'Why might increasing sample size improve the validity of an ecological investigation?', options: ['It makes the experiment quicker','A larger sample is more representative of the population','It removes all systematic errors','It controls confounding variables'], answer: 1 },
      { q: 'Evaluate the use of a potometer in measuring transpiration rate. What does it actually measure?', options: ['Water loss from leaves directly','Water uptake by the cut shoot, which approximates transpiration','Photosynthesis rate','Glucose production'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B2 */
  'B2': {
    name: 'Cells, Chemicals and Transport',
    green: [
      { q: 'What is the basic unit of life?', options: ['Tissue','Organ','Cell','Organism'], answer: 2 },
      { q: 'Which organelle is the site of aerobic respiration?', options: ['Nucleus','Ribosome','Mitochondrion','Chloroplast'], answer: 2 },
      { q: 'What is the function of ribosomes?', options: ['Photosynthesis','Protein synthesis','Lipid storage','DNA replication'], answer: 1 },
      { q: 'Which structure controls what enters and leaves a cell?', options: ['Cell wall','Nucleus','Cell membrane','Cytoplasm'], answer: 2 },
      { q: 'What is the role of the nucleus?', options: ['Energy production','Contains DNA and controls cell activities','Protein synthesis','Storage of water'], answer: 1 },
      { q: 'Which organelle is found in plant cells but not animal cells?', options: ['Mitochondria','Ribosomes','Chloroplasts','Cell membrane'], answer: 2 },
      { q: 'What is the function of the rough endoplasmic reticulum?', options: ['Lipid synthesis','Transport of proteins made by attached ribosomes','DNA replication','Photosynthesis'], answer: 1 },
      { q: 'What is osmosis?', options: ['Movement of solute from high to low concentration','Net movement of water across a partially permeable membrane from high to low water potential','Active transport of water','Diffusion of gas molecules'], answer: 1 },
      { q: 'What is diffusion?', options: ['Movement of water through a membrane','Net movement of particles from an area of high concentration to low concentration','Movement requiring ATP','Movement against a concentration gradient'], answer: 1 },
      { q: 'What is active transport?', options: ['Movement of molecules down a concentration gradient','Movement of molecules against a concentration gradient using energy from ATP','Osmosis of ions','Diffusion of large molecules'], answer: 1 },
      { q: 'What is the approximate diameter of a typical animal cell?', options: ['1 µm','10–30 µm','1 mm','0.1 nm'], answer: 1 },
      { q: 'What is the monomer of proteins?', options: ['Glucose','Fatty acid','Amino acid','Nucleotide'], answer: 2 },
      { q: 'What type of bond joins amino acids together?', options: ['Glycosidic bond','Peptide bond','Hydrogen bond','Ester bond'], answer: 1 },
      { q: 'What is the monomer of starch and glycogen?', options: ['Amino acid','Glucose','Fatty acid','Nucleotide'], answer: 1 },
      { q: 'What is an enzyme?', options: ['A type of lipid','A biological catalyst made of protein','A nucleic acid','A carbohydrate'], answer: 1 },
      { q: 'What does the "lock and key" model describe?', options: ['DNA replication','Enzyme-substrate specificity','Osmosis','Cell division'], answer: 1 },
      { q: 'What is the fluid mosaic model?', options: ['A description of the cell wall','A model of membrane structure with phospholipids and proteins that can move','A model of DNA','A description of cytoplasm'], answer: 1 },
      { q: 'Which molecule forms the bilayer of the cell membrane?', options: ['Protein','Cholesterol','Phospholipid','Glycoprotein'], answer: 2 },
      { q: 'What is a prokaryotic cell?', options: ['A cell with a nucleus','A cell without a membrane-bound nucleus','A cell with chloroplasts','A multicellular organism'], answer: 1 },
      { q: 'What magnification does an electron microscope provide compared to a light microscope?', options: ['Lower magnification','Similar magnification','Much higher magnification and resolution','Only higher resolution, not magnification'], answer: 2 },
    ],
    amber: [
      { q: 'What is the role of cholesterol in cell membranes?', options: ['It provides energy','It regulates membrane fluidity and stability','It catalyses reactions','It stores genetic information'], answer: 1 },
      { q: 'How does temperature affect enzyme activity above the optimum?', options: ['Rate increases indefinitely','The enzyme denatures — active site changes shape and substrate cannot bind','The enzyme freezes','Substrate concentration increases'], answer: 1 },
      { q: 'What is the difference between competitive and non-competitive inhibition?', options: ['Competitive inhibitors bind the active site; non-competitive bind an allosteric site','Both bind the active site','Competitive inhibitors are permanent; non-competitive are temporary','Non-competitive inhibitors increase reaction rate'], answer: 0 },
      { q: 'What is the induced fit model of enzyme action?', options: ['The substrate changes shape to fit the enzyme','The active site changes shape slightly on substrate binding to form a better fit','The enzyme permanently changes shape','The substrate is destroyed before binding'], answer: 1 },
      { q: 'What is water potential (ψ)?', options: ['The concentration of solute','A measure of the tendency of water molecules to move — pure water has ψ = 0 kPa','The pressure inside a cell','The rate of osmosis'], answer: 1 },
      { q: 'What happens to an animal cell placed in a hypotonic solution?', options: ['It becomes crenated','It swells and may burst (lysis)','Nothing happens','It becomes plasmolysed'], answer: 1 },
      { q: 'What happens to a plant cell in a hypertonic solution?', options: ['It bursts','The cell membrane pulls away from the cell wall (plasmolysis)','It becomes turgid','Nothing happens'], answer: 1 },
      { q: 'What is the difference between the smooth and rough endoplasmic reticulum?', options: ['Smooth ER has ribosomes; rough ER does not','Rough ER has ribosomes for protein transport; smooth ER synthesises lipids','They are identical','Smooth ER is in plants only'], answer: 1 },
      { q: 'What is the primary structure of a protein?', options: ['The 3D folded shape','The sequence of amino acids in the polypeptide chain','Alpha helices and beta sheets','Multiple polypeptide subunits'], answer: 1 },
      { q: 'What bonds maintain the tertiary structure of a protein?', options: ['Only peptide bonds','Hydrogen bonds, ionic bonds, disulfide bridges, and hydrophobic interactions','Only hydrogen bonds','Only covalent bonds'], answer: 1 },
      { q: 'What is the test for reducing sugars?', options: ['Iodine test','Biuret test','Benedict\'s test — produces a brick-red precipitate on heating','Emulsion test'], answer: 2 },
      { q: 'How does surface area to volume ratio affect the rate of diffusion into a cell?', options: ['No effect','A larger SA:V ratio increases rate of exchange as more membrane is available per unit volume','A smaller SA:V ratio is better','Only volume matters'], answer: 1 },
      { q: 'Why do phospholipids form a bilayer in water?', options: ['They are all hydrophobic','The hydrophilic heads face outward to water; hydrophobic tails face inward away from water','They are charged throughout','They dissolve in water completely'], answer: 1 },
      { q: 'What is meant by Vmax in enzyme kinetics?', options: ['The minimum rate of reaction','The maximum rate when all active sites are saturated with substrate','The temperature optimum','The pH optimum'], answer: 1 },
      { q: 'What is the Km of an enzyme?', options: ['Maximum velocity','The substrate concentration at which the reaction rate is half Vmax — indicates enzyme-substrate affinity','The optimum temperature','The inhibitor concentration'], answer: 1 },
      { q: 'How do channel proteins differ from carrier proteins?', options: ['They are identical','Channel proteins form a pore for passive movement; carrier proteins change shape to transport molecules','Channel proteins use ATP; carrier proteins do not','Carrier proteins only move water'], answer: 1 },
      { q: 'What is co-transport?', options: ['Two molecules moving in opposite directions','The movement of one substance coupled with another down its concentration gradient, e.g., sodium-glucose co-transport','Active transport without ATP','Osmosis and diffusion together'], answer: 1 },
      { q: 'What is the role of ATP in active transport?', options: ['It provides energy to change the shape of carrier proteins to move substances against their concentration gradient','It provides oxygen','It breaks down the membrane','It acts as an enzyme'], answer: 0 },
      { q: 'Which microscopy technique allows observation of living cells?', options: ['Transmission electron microscopy','Scanning electron microscopy','Light microscopy','All of the above'], answer: 2 },
      { q: 'What is cell fractionation used for?', options: ['Counting cells','Separating cell organelles by spinning at increasing speeds (differential centrifugation)','Staining cells','Measuring cell size'], answer: 1 },
    ],
    red: [
      { q: 'A cell is placed in a solution with ψ = -500 kPa. The cell has ψ = -300 kPa. What will happen?', options: ['Water moves out of the cell by osmosis (from higher to lower','No net movement','Water moves into the cell','The cell bursts'], answer: 0 },
      { q: 'Why does a competitive inhibitor increase the apparent Km but not Vmax?', options: ['It competes for the active site so more substrate is needed','It binds permanently','It destroys the enzyme','It increases enzyme concentration'], answer: 0 },
      { q: 'Evaluate the fluid mosaic model. Why is the membrane described as a "mosaic"?', options: ['Because it is solid and uniform','Because it is symmetric','Because it contains a variety of proteins, glycoproteins','Because it only contains phospholipids'], answer: 2 },
      { q: 'Explain why the rate of facilitated diffusion reaches a plateau at high solute concentrations.', options: ['ATP runs out','All carrier/channel proteins are occupied (saturated)','The solute is destroyed','The membrane dissolves'], answer: 1 },
      { q: 'Why can electron microscopes not be used to observe living specimens?', options: ['They are too expensive','Specimens must be fixed, dehydrated, and placed in a vacuum','They use visible light','They are too small'], answer: 1 },
      { q: 'How does the quaternary structure of haemoglobin relate to its function?', options: ['It has one polypeptide chain','Four polypeptide subunits each with a haem group allow','It is a carbohydrate','It has no tertiary structure'], answer: 1 },
      { q: 'A non-competitive inhibitor binds to an enzyme. Explain the effect on Vmax and Km.', options: ['Both increase','Vmax decreases (fewer functional enzymes) but Km stays the','Km increases but Vmax stays the same','Both decrease'], answer: 1 },
      { q: 'Why do very small organisms not need a specialised transport system?', options: ['They do not respire','Their large surface area to volume ratio means diffusion','They have no cells','They live in water only'], answer: 1 },
      { q: 'Compare and contrast endocytosis and exocytosis.', options: ['Endocytosis brings substances into the cell via vesicle','Both move substances into the cell','They occur only in prokaryotes','They are passive processes'], answer: 0 },
      { q: 'Explain how the structure of cellulose makes it suitable for its function in plant cell walls.', options: ['It is soluble and provides energy','It is a protein','Long straight chains of β-glucose form hydrogen bonds','It is branched like glycogen'], answer: 2 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B3 */
  'B3': {
    name: 'Cell Division, Development and Disease',
    green: [
      { q: 'What is mitosis?', options: ['Division producing four haploid cells','Division producing two genetically identical diploid cells','Fusion of gametes','Crossing over of chromosomes'], answer: 1 },
      { q: 'What is meiosis?', options: ['Division producing two identical cells','Division producing four genetically different haploid cells','Cell growth','DNA repair'], answer: 1 },
      { q: 'What is a chromosome?', options: ['A type of protein','A coiled structure of DNA and histone proteins','A carbohydrate','An organelle'], answer: 1 },
      { q: 'How many chromosomes do human body cells have?', options: ['23','46','92','12'], answer: 1 },
      { q: 'What is a tumour?', options: ['A type of virus','A mass of cells resulting from uncontrolled cell division','A bacterial infection','A genetic mutation that is always harmless'], answer: 1 },
      { q: 'What is the difference between benign and malignant tumours?', options: ['There is no difference','Benign tumours do not spread (metastasise); malignant tumours can invade other tissues','Benign tumours are always larger','Malignant tumours are not dangerous'], answer: 1 },
      { q: 'What is a stem cell?', options: ['A fully differentiated cell','An undifferentiated cell that can divide and differentiate into specialised cells','A dead cell','A cancer cell'], answer: 1 },
      { q: 'What is differentiation?', options: ['Cell death','The process by which a cell becomes specialised for a particular function','Cell division','Mutation'], answer: 1 },
      { q: 'What is the cell cycle?', options: ['Only mitosis','The series of stages a cell goes through including interphase, mitosis, and cytokinesis','Only meiosis','DNA transcription'], answer: 1 },
      { q: 'What happens during interphase?', options: ['The cell divides','The cell grows, organelles replicate, and DNA is copied','Chromosomes line up','Cytokinesis occurs'], answer: 1 },
      { q: 'What is apoptosis?', options: ['Uncontrolled cell division','Programmed cell death','Cell growth','DNA replication'], answer: 1 },
      { q: 'What is a pathogen?', options: ['A white blood cell','A microorganism that causes disease','An antibody','A vaccine'], answer: 1 },
      { q: 'Name two types of pathogen.', options: ['Red blood cells and platelets','Bacteria and viruses','Enzymes and hormones','Mitochondria and ribosomes'], answer: 1 },
      { q: 'What is an antigen?', options: ['A type of white blood cell','A molecule on the surface of a cell that can trigger an immune response','An antibiotic','A type of vaccine'], answer: 1 },
      { q: 'What do antibodies do?', options: ['They are pathogens','They are proteins produced by B lymphocytes that bind to specific antigens','They cause disease','They are enzymes that digest food'], answer: 1 },
      { q: 'What is a mutation?', options: ['Normal cell division','A change in the base sequence of DNA','A type of protein','An immune response'], answer: 1 },
      { q: 'What is cancer caused by?', options: ['Only viruses','Mutations in genes controlling the cell cycle (oncogenes and tumour suppressor genes)','Excess vitamins','Low temperature'], answer: 1 },
      { q: 'What phase of mitosis involves chromosomes lining up at the cell equator?', options: ['Prophase','Metaphase','Anaphase','Telophase'], answer: 1 },
      { q: 'During which phase of mitosis do sister chromatids separate?', options: ['Prophase','Metaphase','Anaphase','Telophase'], answer: 2 },
      { q: 'What is cytokinesis?', options: ['DNA replication','Division of the cytoplasm to form two separate cells','Chromosome condensation','Spindle formation'], answer: 1 },
    ],
    amber: [
      { q: 'What is the role of tumour suppressor genes?', options: ['They promote cell division','They slow or stop the cell cycle, and their inactivation can lead to cancer','They produce antibodies','They cause mutations'], answer: 1 },
      { q: 'What is an oncogene?', options: ['A gene that prevents cancer','A mutated proto-oncogene that promotes uncontrolled cell division','A viral gene only','A gene for apoptosis'], answer: 1 },
      { q: 'How does meiosis produce genetic variation?', options: ['By producing identical cells','Through independent assortment of chromosomes and crossing over during prophase I','By skipping DNA replication','Through mitosis'], answer: 1 },
      { q: 'What is crossing over in meiosis?', options: ['Chromosomes failing to separate','Exchange of genetic material between homologous chromosomes during prophase I','DNA replication errors','Formation of the spindle'], answer: 1 },
      { q: 'What is independent assortment?', options: ['All maternal chromosomes go to one cell','Homologous pairs line up randomly at metaphase I, so each gamete gets a different combination','Chromosomes do not separate','Cytokinesis fails'], answer: 1 },
      { q: 'How do totipotent stem cells differ from pluripotent stem cells?', options: ['They are identical','Totipotent cells can form any cell type including extraembryonic tissue; pluripotent can form any body cell but not placenta','Pluripotent can form more types','Totipotent cannot differentiate'], answer: 1 },
      { q: 'What is the innate immune system?', options: ['The adaptive response involving antibodies','Non-specific defences present from birth, including barriers, phagocytes, and inflammation','Vaccination','Memory cells'], answer: 1 },
      { q: 'How do phagocytes destroy pathogens?', options: ['By producing antibodies','By engulfing (phagocytosis) and digesting pathogens using lysosomes','By producing antigens','By undergoing apoptosis'], answer: 1 },
      { q: 'What is the role of T helper cells in the immune response?', options: ['They engulf pathogens','They release cytokines that activate B cells and cytotoxic T cells','They produce antibodies','They form the skin barrier'], answer: 1 },
      { q: 'What is clonal selection?', options: ['Random destruction of lymphocytes','The process by which a lymphocyte with a receptor matching a specific antigen is activated and proliferates','Production of all antibody types','Phagocytosis'], answer: 1 },
      { q: 'What is the primary immune response?', options: ['The fastest response','The first encounter with an antigen — it is slow because few specific lymphocytes exist initially','A response to self-antigens','Inflammation only'], answer: 1 },
      { q: 'What is the secondary immune response?', options: ['A slower response','A faster and stronger response on re-exposure to the same antigen due to memory cells','The first response to a pathogen','An allergic reaction'], answer: 1 },
      { q: 'How do vaccines work?', options: ['They kill all pathogens immediately','They contain weakened/dead pathogens or antigens that stimulate an immune response and memory cell production without causing disease','They are antibiotics','They replace white blood cells'], answer: 1 },
      { q: 'What is metastasis?', options: ['Cell growth during interphase','The spread of cancer cells from the primary tumour to other parts of the body via blood or lymph','Apoptosis','Immune response'], answer: 1 },
      { q: 'What is the role of checkpoints in the cell cycle?', options: ['They speed up division','They are control points where the cell checks conditions (e.g., DNA integrity) before proceeding to the next phase','They cause cancer','They produce ATP'], answer: 1 },
      { q: 'What happens if DNA is damaged and the G1 checkpoint fails?', options: ['The cell repairs perfectly','The cell may proceed with damaged DNA, potentially leading to mutations and cancer','The cell always dies','Nothing happens'], answer: 1 },
      { q: 'What is the difference between humoral and cell-mediated immunity?', options: ['They are the same','Humoral involves B cells producing antibodies in body fluids; cell-mediated involves T cells directly attacking infected cells','Humoral uses T cells; cell-mediated uses B cells','Neither involves lymphocytes'], answer: 1 },
      { q: 'How do cytotoxic T cells kill infected cells?', options: ['By producing antibodies','By releasing perforin which creates pores in the target cell membrane, and granzymes which trigger apoptosis','By phagocytosis','By releasing histamine'], answer: 1 },
      { q: 'What is an autoimmune disease?', options: ['A disease caused by bacteria','A condition where the immune system attacks the body\'s own cells, mistaking self-antigens as foreign','A viral infection','A type of cancer'], answer: 1 },
      { q: 'What is herd immunity?', options: ['Immunity in farm animals only','When a high proportion of a population is vaccinated, reducing transmission and protecting unvaccinated individuals','Personal immunity from infection','Antibiotic resistance'], answer: 1 },
    ],
    red: [
      { q: 'Explain why cancer is considered a multistep process requiring multiple mutations.', options: ['One mutation always causes cancer immediately','A single mutation is always repaired','Multiple mutations in oncogenes and tumour suppressor genes are','Cancer is caused only by viruses'], answer: 2 },
      { q: 'Evaluate the use of embryonic stem cells in medicine. Consider both benefits and ethical concerns.', options: ['They can potentially treat many diseases by replacing damaged cells','There are no ethical issues','They always cause cancer','They are only used for research'], answer: 0 },
      { q: 'Compare and contrast the structure and replication of bacteria and viruses as pathogens.', options: ['They are both cells','Bacteria are prokaryotic cells that reproduce independently','Viruses are larger than bacteria','Both contain membrane-bound organelles'], answer: 1 },
      { q: 'Explain why antibiotics are effective against bacteria but not viruses.', options: ['Antibiotics kill everything','Antibiotics target bacterial structures/processes (e.g.','Viruses are too large','Antibiotics are the same as antivirals'], answer: 1 },
      { q: 'A patient has a malignant tumour. Explain why surgery alone may not cure the cancer.', options: ['Cancer cells may have already metastasised via blood/lymph','Surgery is never attempted','Surgery always cures cancer','The tumour always regrows in the same place'], answer: 0 },
      { q: 'Explain the significance of non-disjunction during meiosis.', options: ['It produces identical cells','Chromosomes fail to separate properly, resulting in gametes','It always causes cell death','It is a normal part of meiosis'], answer: 1 },
      { q: 'Why might immunosuppressant drugs be necessary after an organ transplant, and what risks do they carry?', options: ['They speed up healing only','They strengthen the immune system','They are never needed','They prevent the recipient\'s immune system from rejecting'], answer: 3 },
      { q: 'Discuss why antigenic variation in pathogens like influenza makes it difficult to achieve long-term immunity.', options: ['The virus never changes','The virus frequently mutates its surface antigens','Antibodies last forever','Only bacteria show antigenic variation'], answer: 1 },
      { q: 'Evaluate the claim: "All mutations are harmful." Is this correct?', options: ['Yes — all mutations cause disease','No — most mutations are neutral (in non-coding DNA or synonymous)','Yes — mutations always cause cancer','No — all mutations are beneficial'], answer: 1 },
      { q: 'Explain how the regulation of the cell cycle by cyclins and CDKs relates to cancer development.', options: ['CDKs prevent all division','Cyclins bind CDKs to drive progression through cell cycle checkpoints','Cyclins only function in meiosis','Cyclins have no role in cancer'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B4 */
  'B4': {
    name: 'Energy, Reproduction and Populations',
    green: [
      { q: 'What is photosynthesis?', options: ['Breaking down glucose for energy','Converting light energy into chemical energy (glucose) using CO₂ and water','Releasing CO₂','Decomposing organic matter'], answer: 1 },
      { q: 'Where does the light-dependent reaction of photosynthesis occur?', options: ['Stroma','Thylakoid membranes of chloroplasts','Cytoplasm','Mitochondrial matrix'], answer: 1 },
      { q: 'Where does the Calvin cycle take place?', options: ['Thylakoid membrane','Stroma of the chloroplast','Mitochondria','Nucleus'], answer: 1 },
      { q: 'What is the equation for aerobic respiration?', options: ['CO₂ + H₂O → glucose + O₂','Glucose + O₂ → CO₂ + H₂O + ATP','Glucose → ethanol + CO₂','Glucose → lactate'], answer: 1 },
      { q: 'Where does glycolysis occur?', options: ['Mitochondrial matrix','Cytoplasm','Nucleus','Thylakoid'], answer: 1 },
      { q: 'Where does the Krebs cycle occur?', options: ['Cytoplasm','Mitochondrial matrix','Inner mitochondrial membrane','Stroma'], answer: 1 },
      { q: 'What is ATP?', options: ['A protein','Adenosine triphosphate — the universal energy currency of cells','A lipid','A carbohydrate'], answer: 1 },
      { q: 'What is anaerobic respiration in animals?', options: ['Respiration using oxygen','Respiration without oxygen, producing lactate','Photosynthesis','Fermentation producing ethanol'], answer: 1 },
      { q: 'What is the net gain of ATP from glycolysis?', options: ['0','2','4','38'], answer: 1 },
      { q: 'What is a limiting factor in photosynthesis?', options: ['A factor that has no effect','A factor that limits the rate of photosynthesis when in short supply','A factor that always increases the rate','Temperature only'], answer: 1 },
      { q: 'What is a population?', options: ['All organisms in an area','All organisms of one species in a particular area at a given time','A single organism','A community'], answer: 1 },
      { q: 'What is a community?', options: ['One species in an area','All the populations of different species living in the same area','A single organism','An ecosystem'], answer: 1 },
      { q: 'What is an ecosystem?', options: ['Only the living organisms','A community of organisms and their abiotic environment interacting together','Only the physical environment','A single habitat'], answer: 1 },
      { q: 'What is a niche?', options: ['The place where an organism lives','The role of an organism within its ecosystem, including how it uses resources','A type of habitat','A food source'], answer: 1 },
      { q: 'What is meant by carrying capacity?', options: ['The maximum speed of an organism','The maximum population size an environment can sustain indefinitely','The minimum population size','The birth rate'], answer: 1 },
      { q: 'What is the link reaction?', options: ['Glucose to pyruvate','Pyruvate is converted to acetyl CoA, releasing CO₂ and reducing NAD','Oxidative phosphorylation','The Calvin cycle'], answer: 1 },
      { q: 'What are the products of the light-dependent reaction?', options: ['Glucose and O₂','ATP, reduced NADP (NADPH), and O₂','CO₂ and water','Pyruvate and ATP'], answer: 1 },
      { q: 'What is the role of NADP in photosynthesis?', options: ['It is an enzyme','It is a hydrogen/electron carrier — reduced NADP carries H to the Calvin cycle','It is a pigment','It absorbs light'], answer: 1 },
      { q: 'What is oxidative phosphorylation?', options: ['Glycolysis','The production of ATP using energy from the electron transport chain on the inner mitochondrial membrane','The Calvin cycle','Fermentation'], answer: 1 },
      { q: 'What is meant by birth rate?', options: ['Number of deaths per year','Number of live births per 1000 individuals per year','Total population size','Number of immigrants'], answer: 1 },
    ],
    amber: [
      { q: 'Explain the role of chemiosmosis in ATP production during oxidative phosphorylation.', options: ['Protons move randomly','Protons (H⁺) accumulate in the intermembrane space creating a gradient; they flow back through ATP synthase, driving ATP synthesis','Oxygen is split','Glucose is phosphorylated'], answer: 1 },
      { q: 'What is the role of oxygen in aerobic respiration?', options: ['It is a waste product','It is the final electron acceptor in the electron transport chain, combining with H⁺ to form water','It breaks down glucose directly','It enters the Krebs cycle'], answer: 1 },
      { q: 'How does RuBisCO function in the Calvin cycle?', options: ['It splits water','It catalyses the fixation of CO₂ by combining it with RuBP (5C) to form two molecules of GP (3C)','It produces ATP','It absorbs light'], answer: 1 },
      { q: 'What is photorespiration and why is it a problem?', options: ['Normal photosynthesis','RuBisCO fixes O₂ instead of CO₂, producing a toxic 2C compound and wasting energy — it reduces photosynthetic efficiency','Respiration in the dark','A beneficial process'], answer: 1 },
      { q: 'Explain how NAD and FAD function in respiration.', options: ['They are enzymes','They are coenzymes that act as hydrogen/electron carriers — they are reduced (gain H) during glycolysis and the Krebs cycle and pass electrons to the ETC','They are substrates','They produce oxygen'], answer: 1 },
      { q: 'What is substrate-level phosphorylation?', options: ['ATP production via the ETC','Direct transfer of a phosphate group from a substrate to ADP to form ATP, without the electron transport chain','Photophosphorylation','Oxidation of NADH'], answer: 1 },
      { q: 'What is a respiratory substrate and how does the RQ differ for fats vs carbohydrates?', options: ['Only glucose can be respired','Any organic molecule broken down in respiration; RQ for carbohydrates ≈ 1.0, for fats ≈ 0.7 (fats need more O₂ per CO₂ produced)','RQ is always 1','Fats cannot be respired'], answer: 1 },
      { q: 'Explain the concept of net primary productivity (NPP).', options: ['Total energy fixed','NPP = GPP − plant respiration; it is the energy available to primary consumers','Total energy in the ecosystem','Energy lost as heat'], answer: 1 },
      { q: 'What is density-dependent population regulation?', options: ['Factors unrelated to population size','Factors whose effects increase with population density, e.g., competition, disease, predation','Only abiotic factors','Genetic drift'], answer: 1 },
      { q: 'How does the sigmoid (S-shaped) population growth curve relate to carrying capacity?', options: ['Population grows indefinitely','Growth is exponential at first, then slows as resources become limiting, and stabilises around the carrying capacity','Population always declines','Carrying capacity has no effect'], answer: 1 },
      { q: 'What is the role of photosystem II in the light-dependent reaction?', options: ['It fixes CO₂','It absorbs light energy, causing photoionisation of chlorophyll, and splits water (photolysis) to replace lost electrons, releasing O₂ and H⁺','It produces glucose','It reduces NADP'], answer: 1 },
      { q: 'Explain cyclic photophosphorylation.', options: ['Non-cyclic electron flow','Electrons from PSI are passed back to PSI via electron carriers, generating ATP but no NADPH or O₂ — used when NADP is limiting','It involves PSII only','It splits water'], answer: 1 },
      { q: 'Why does the Krebs cycle turn twice for each glucose molecule?', options: ['Glucose enters the Krebs cycle directly','Each glucose produces two pyruvate molecules (in glycolysis), each converted to one acetyl CoA, so the cycle turns twice per glucose','It only turns once','The cycle requires two enzymes'], answer: 1 },
      { q: 'What is decarboxylation in respiration?', options: ['Addition of CO₂','Removal of a carboxyl group as CO₂ from a substrate, e.g., pyruvate → acetyl CoA and in the Krebs cycle','Reduction of NAD','Phosphorylation of ADP'], answer: 1 },
      { q: 'What factors affect the rate of decomposition?', options: ['Only temperature','Temperature, moisture, oxygen availability, and pH — these affect enzyme activity in decomposers','Only light intensity','Only the type of organism'], answer: 1 },
      { q: 'What is interspecific competition?', options: ['Competition within the same species','Competition between individuals of different species for the same resources','Predation','Mutualism'], answer: 1 },
      { q: 'What is intraspecific competition?', options: ['Competition between different species','Competition between individuals of the same species for the same resources','Predation','Parasitism'], answer: 1 },
      { q: 'Explain how mark-release-recapture is used to estimate population size.', options: ['Count all organisms directly','Capture and mark a sample, release them, recapture later; estimate N = (first capture × second capture) / number recaptured','Measure biomass','Use a transect'], answer: 1 },
      { q: 'What assumptions must be met for mark-release-recapture to be valid?', options: ['No assumptions needed','No births/deaths/migration between samples, marks do not affect survival or behaviour, marked individuals mix randomly','Only that marks are visible','The population must be small'], answer: 1 },
      { q: 'Explain why only about 10% of energy is transferred between trophic levels.', options: ['All energy is transferred','Energy is lost as heat from respiration, in excretion/egestion, and not all organisms are consumed — only ~10% is incorporated into biomass of the next level','50% is transferred','Energy is created at each level'], answer: 1 },
    ],
    red: [
      { q: 'Explain the chemiosmotic theory of ATP synthesis and why cyanide is lethal.', options: ['Cyanide blocks the Krebs cycle only','Cyanide is harmless','Cyanide blocks glycolysis','Cyanide inhibits cytochrome c oxidase (complex IV) in the ETC'], answer: 3 },
      { q: 'Compare C3 and C4 photosynthesis in terms of carbon fixation efficiency.', options: ['They are identical','C4 plants spatially separate initial CO₂ fixation (PEP','C3 is always more efficient','C4 plants do not use RuBisCO'], answer: 1 },
      { q: 'Evaluate the use of respirometers in measuring metabolic rate.', options: ['Respirometers measure O₂ uptake or CO₂ release as a proxy','They measure photosynthesis','They are perfectly accurate','They directly measure ATP'], answer: 0 },
      { q: 'Explain the ecological significance of the second law of thermodynamics for energy flow in ecosystems.', options: ['Energy is created at each level','At each transfer, some energy is converted to heat','Energy flow is circular','The law does not apply to biology'], answer: 1 },
      { q: 'Discuss the factors that cause a population to overshoot its carrying capacity and the consequences.', options: ['Time lags in the effect of density-dependent factors can','Carrying capacity is fixed forever','Populations never overshoot','Overshoot has no consequences'], answer: 0 },
      { q: 'Explain why the theoretical maximum ATP yield from one glucose molecule (36-38) is rarely achieved in vivo.', options: ['It is always achieved exactly','Proton leakage across the membrane, use of the proton','Only 2 ATP are produced','Glycolysis is 100% efficient'], answer: 1 },
      { q: 'Analyse how global warming might affect the distribution of C3 and C4 plant species.', options: ['No effect','Rising temperatures increase photorespiration in C3 plants','C4 plants will disappear','Only rainfall matters'], answer: 1 },
      { q: 'Evaluate the competitive exclusion principle and explain when coexistence is possible.', options: ['Competition never affects populations','The principle states that two species competing for identical resources cannot coexist','The principle has been disproven','Two species can always coexist on identical resources'], answer: 1 },
      { q: 'Explain how the light compensation point relates to plant ecology in shaded environments.', options: ['It only applies in full sunlight','At the light compensation point, photosynthesis equals','It is irrelevant','All plants have the same compensation point'], answer: 1 },
      { q: 'Discuss the evidence for and limitations of the endosymbiotic theory regarding the origin of mitochondria and chloroplasts.', options: ['The theory has been completely disproven','Evidence includes double membranes, own circular DNA, 70S ribosomes','There is no evidence','It applies only to chloroplasts'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B5 */
  'B5': {
    name: 'Genetics, Control and Homeostasis',
    green: [
      { q: 'What is a gene?', options: ['A whole chromosome','A section of DNA that codes for a specific polypeptide/protein','A type of RNA','An amino acid'], answer: 1 },
      { q: 'What is an allele?', options: ['A chromosome pair','A different version of a gene','A type of mutation','A codon'], answer: 1 },
      { q: 'What does homozygous mean?', options: ['Two different alleles for a gene','Two identical alleles for a gene','No alleles','One allele only'], answer: 1 },
      { q: 'What does heterozygous mean?', options: ['Two identical alleles','Two different alleles for a gene','Only one allele present','No alleles at all'], answer: 1 },
      { q: 'What is the genotype?', options: ['Physical appearance','The genetic makeup of an organism (alleles present)','The environment','A type of mutation'], answer: 1 },
      { q: 'What is the phenotype?', options: ['The alleles present','The observable characteristics resulting from genotype and environment','Only genetic factors','A DNA sequence'], answer: 1 },
      { q: 'What is a dominant allele?', options: ['An allele that is always harmful','An allele that is expressed in both homozygous and heterozygous conditions','An allele only expressed when homozygous','A recessive allele'], answer: 1 },
      { q: 'What is a recessive allele?', options: ['An allele always expressed','An allele only expressed in the homozygous condition','A dominant allele','A codominant allele'], answer: 1 },
      { q: 'What is homeostasis?', options: ['Growth of an organism','The maintenance of a constant internal environment despite external changes','Cell division','DNA replication'], answer: 1 },
      { q: 'What is negative feedback?', options: ['A response that amplifies a change','A response that counteracts a deviation from the norm, returning conditions to the set point','No response to change','Positive reinforcement'], answer: 1 },
      { q: 'What is a hormone?', options: ['A nerve impulse','A chemical messenger transported in the blood that acts on target cells with specific receptors','A type of enzyme','A nutrient'], answer: 1 },
      { q: 'What is the central dogma of molecular biology?', options: ['Protein → RNA → DNA','DNA → RNA → protein (transcription then translation)','RNA → DNA → protein','Protein → DNA → RNA'], answer: 1 },
      { q: 'What is transcription?', options: ['DNA replication','The synthesis of mRNA from a DNA template','Translation of mRNA into protein','Reverse transcription'], answer: 1 },
      { q: 'What is translation?', options: ['DNA to mRNA','The synthesis of a polypeptide from an mRNA template at the ribosome','RNA splicing','DNA replication'], answer: 1 },
      { q: 'What is a codon?', options: ['A single nucleotide','A triplet of bases on mRNA that codes for one amino acid','A gene','An anticodon'], answer: 1 },
      { q: 'What organ regulates blood glucose concentration?', options: ['Liver only','Pancreas (produces insulin and glucagon)','Brain','Kidneys'], answer: 1 },
      { q: 'What does insulin do?', options: ['Increases blood glucose','Lowers blood glucose by stimulating cells to take up glucose and liver to store glycogen','Has no effect on glucose','Breaks down glycogen'], answer: 1 },
      { q: 'What does glucagon do?', options: ['Lowers blood glucose','Raises blood glucose by stimulating glycogen breakdown in the liver','Stores glucose as glycogen','Is the same as insulin'], answer: 1 },
      { q: 'What is a reflex arc?', options: ['A voluntary response','The pathway of a rapid, automatic nervous response: receptor → sensory neurone → relay neurone → motor neurone → effector','A hormone pathway','A feedback loop'], answer: 1 },
      { q: 'What is a synapse?', options: ['A type of receptor','The junction between two neurones where neurotransmitters transmit the signal','A nerve cell body','An axon'], answer: 1 },
    ],
    amber: [
      { q: 'What is codominance?', options: ['One allele masks the other','Both alleles are expressed equally in the phenotype of a heterozygote','One allele is always recessive','Neither allele is expressed'], answer: 1 },
      { q: 'What is epistasis?', options: ['One gene on two chromosomes','The interaction where one gene masks or modifies the expression of another gene at a different locus','Codominance','Linked genes'], answer: 1 },
      { q: 'How does the Hardy-Weinberg equation relate to allele frequencies?', options: ['It predicts mutations','p² + 2pq + q² = 1 predicts genotype frequencies in a non-evolving population (no selection, mutation, drift, migration, or non-random mating)','It measures fitness','It calculates mutation rates'], answer: 1 },
      { q: 'What is the role of mRNA splicing in eukaryotic gene expression?', options: ['It removes exons','Introns (non-coding regions) are removed and exons are joined together before translation — alternative splicing allows one gene to produce different proteins','It adds introns','It occurs in prokaryotes'], answer: 1 },
      { q: 'Explain how a nerve impulse is transmitted along an axon (action potential).', options: ['Continuous flow of electrons','Depolarisation occurs as Na⁺ channels open (Na⁺ rushes in), followed by repolarisation as K⁺ channels open (K⁺ moves out) — the impulse propagates along the axon','Hormones travel along the axon','Ca²⁺ flows continuously'], answer: 1 },
      { q: 'What is the role of the myelin sheath?', options: ['It slows nerve impulses','It insulates the axon and enables saltatory conduction (impulse jumps between nodes of Ranvier), increasing speed','It produces neurotransmitters','It connects neurones'], answer: 1 },
      { q: 'What is the difference between Type 1 and Type 2 diabetes?', options: ['They are identical','Type 1: autoimmune destruction of β-cells, no insulin produced; Type 2: cells become resistant to insulin or insufficient insulin is produced, often linked to lifestyle','Type 1 is lifestyle-related','Type 2 involves no insulin'], answer: 1 },
      { q: 'Explain the role of the hypothalamus in thermoregulation.', options: ['It directly warms the body','It acts as the thermoregulatory centre, detecting blood temperature and sending nerve impulses to effectors (e.g., sweat glands, muscles for shivering)','It produces insulin','It is only active during fever'], answer: 1 },
      { q: 'What is the role of ADH in osmoregulation?', options: ['It increases urine volume','ADH (from the posterior pituitary) increases water reabsorption in the collecting duct by inserting aquaporins, producing more concentrated urine','It lowers blood pressure','It increases salt excretion'], answer: 1 },
      { q: 'What is genetic drift?', options: ['Natural selection','Random changes in allele frequency due to chance, most significant in small populations','Mutation','Gene flow'], answer: 1 },
      { q: 'What is epigenetics?', options: ['Changes to DNA sequence','Heritable changes in gene expression without altering the DNA sequence, e.g., DNA methylation and histone modification','A type of mutation','Gene therapy'], answer: 1 },
      { q: 'What is a dihybrid cross?', options: ['A cross involving one gene','A cross involving two genes on different chromosomes, producing a 9:3:3:1 ratio in F2 if unlinked and both parents heterozygous','A cross with linked genes only','A test cross'], answer: 1 },
      { q: 'What is the chi-squared test used for in genetics?', options: ['Measuring DNA length','Testing whether observed ratios differ significantly from expected ratios — if χ² exceeds the critical value at p=0.05, the difference is significant','Measuring allele frequency','Sequencing DNA'], answer: 1 },
      { q: 'What is the role of tRNA in translation?', options: ['It carries the genetic code','Each tRNA carries a specific amino acid and has an anticodon that base-pairs with the complementary mRNA codon at the ribosome','It makes the ribosome','It splices introns'], answer: 1 },
      { q: 'What is the difference between the sympathetic and parasympathetic nervous systems?', options: ['They are identical','Sympathetic prepares the body for "fight or flight" (increases heart rate); parasympathetic promotes "rest and digest" (decreases heart rate) — they have antagonistic effects','Sympathetic slows the heart','Parasympathetic causes stress'], answer: 1 },
      { q: 'What is gene linkage?', options: ['Genes on different chromosomes','Genes on the same chromosome that tend to be inherited together, deviating from expected Mendelian ratios','Genes that are always dominant','Epistasis'], answer: 1 },
      { q: 'Explain how gibberellins promote seed germination.', options: ['They inhibit germination','Gibberellins stimulate the production of amylase in the aleurone layer, which breaks down starch into maltose for the embryo to use for growth','They are auxins','They prevent enzyme synthesis'], answer: 1 },
      { q: 'What is the role of the medulla oblongata in controlling heart rate?', options: ['It produces hormones','It contains the cardiovascular centre which adjusts heart rate via sympathetic (accelerator) and parasympathetic (vagus) nerves in response to input from baroreceptors and chemoreceptors','It pumps blood','It controls breathing only'], answer: 1 },
      { q: 'What is a polymerase chain reaction (PCR)?', options: ['Protein synthesis in vivo','A technique to amplify specific DNA fragments using repeated cycles of denaturation (95°C), annealing (50-65°C), and extension (72°C) with DNA polymerase','RNA transcription','Gel electrophoresis'], answer: 1 },
      { q: 'What is the role of restriction enzymes in genetic engineering?', options: ['They join DNA','They cut DNA at specific recognition sequences, often producing sticky ends that allow fragments from different sources to be joined','They replicate DNA','They transcribe RNA'], answer: 1 },
    ],
    red: [
      { q: 'Explain how a change in one base in DNA (point mutation) can lead to a non-functional protein, using sickle cell anaemia as an example.', options: ['Point mutations never matter','A single base substitution in the β-globin gene changes the','All mutations cause sickle cell','The mutation affects α-globin'], answer: 1 },
      { q: 'Evaluate the concept of "nature vs nurture" in determining phenotype, using a specific example.', options: ['Only genes matter','Phenotype results from the interaction of genotype and environment','Only environment matters','They never interact'], answer: 1 },
      { q: 'Explain why the kidney is considered an organ of both excretion and osmoregulation.', options: ['It only excretes urea','It excretes metabolic waste (urea, excess salts) AND','It only regulates water','It produces hormones only'], answer: 1 },
      { q: 'Discuss the advantages and limitations of using the Hardy-Weinberg model in real populations.', options: ['Advantages: estimates allele/genotype frequencies and detects evolution','It only works for dominant alleles','It cannot estimate frequencies','It is perfectly accurate for all populations'], answer: 0 },
      { q: 'Explain how negative feedback in blood glucose regulation can fail in Type 2 diabetes.', options: ['Negative feedback always works perfectly','Target cells become resistant to insulin (receptor','Only the liver is affected','Glucagon is the problem'], answer: 1 },
      { q: 'Compare the speed, duration, and specificity of nervous and hormonal communication.', options: ['They are identical','Hormones are faster','Nerves act on all cells','Nervous: fast transmission (electrical impulses), short-lived'], answer: 3 },
      { q: 'Explain how gene expression is regulated at the transcriptional level in eukaryotes, including the role of transcription factors.', options: ['Only one gene is active per cell','Regulation only occurs post-translationally','All genes are always active','Transcription factors bind to promoter/enhancer regions'], answer: 3 },
      { q: 'Discuss how natural selection can lead to changes in allele frequency over time, using antibiotic resistance as an example.', options: ['Natural selection does not change allele frequency','Random mutations produce resistance alleles','Antibiotics cause mutations','Resistance is always present'], answer: 1 },
      { q: 'Evaluate the use of gene therapy for cystic fibrosis, including challenges.', options: ['Gene therapy is fully successful for CF','Aim: deliver functional CFTR gene to lung epithelial cells','It cures all patients permanently','Only somatic therapy is possible'], answer: 1 },
      { q: 'Explain how the structure of a nephron relates to its function in producing urine.', options: ['Bowman\'s capsule filters blood (ultrafiltration)','All parts have identical function','The loop of Henle produces urine directly','The nephron only filters'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B6 */
  'B6': {
    name: 'Biotechnology, Ecosystems and Human Impact',
    green: [
      { q: 'What is biodiversity?', options: ['The number of individuals in a population','The variety of living organisms at all levels (genetic, species, ecosystem)','Only species richness','The size of a habitat'], answer: 1 },
      { q: 'What is a food chain?', options: ['A list of organisms in an ecosystem','A linear sequence showing the transfer of energy from one trophic level to the next','A type of nutrient cycle','A food web'], answer: 1 },
      { q: 'What is a trophic level?', options: ['A type of habitat','A feeding level in a food chain or web','A measure of biodiversity','An abiotic factor'], answer: 1 },
      { q: 'What is the carbon cycle?', options: ['Recycling of nitrogen','The biogeochemical cycle by which carbon moves through the atmosphere, biosphere, oceans, and geosphere','Photosynthesis only','Respiration only'], answer: 1 },
      { q: 'What is the nitrogen cycle?', options: ['Movement of carbon','The process by which nitrogen is converted between its various chemical forms as it circulates through the atmosphere, soil, and organisms','Only fixation','Only denitrification'], answer: 1 },
      { q: 'What is nitrogen fixation?', options: ['Plants absorbing nitrate','Conversion of atmospheric N₂ into ammonia/ammonium by nitrogen-fixing bacteria (e.g., Rhizobium)','Denitrification','Decomposition'], answer: 1 },
      { q: 'What is eutrophication?', options: ['Lack of nutrients in water','Excessive nutrient enrichment of water (often nitrates/phosphates) causing algal blooms, oxygen depletion, and death of aquatic organisms','Normal nutrient levels','Acid rain effects'], answer: 1 },
      { q: 'What is deforestation?', options: ['Planting new forests','The large-scale removal of trees/forest habitat','Natural tree death','Forest fires only'], answer: 1 },
      { q: 'What is the greenhouse effect?', options: ['Ozone depletion','The trapping of heat by greenhouse gases (CO₂, methane, water vapour) in the atmosphere, warming the Earth','Acid rain','UV radiation damage'], answer: 1 },
      { q: 'What is genetic engineering?', options: ['Selective breeding','The deliberate modification of an organism\'s genome by inserting, deleting, or altering genes using biotechnology','Natural mutation','Evolution'], answer: 1 },
      { q: 'What is a GMO?', options: ['A naturally evolved organism','A genetically modified organism whose DNA has been altered using genetic engineering techniques','A selectively bred organism','A cloned organism'], answer: 1 },
      { q: 'What is succession?', options: ['Population decline','The gradual change in community structure over time in an area, from colonisation to climax community','Extinction','Migration'], answer: 1 },
      { q: 'What is a climax community?', options: ['The first community to colonise','The final, stable community in a succession that is in dynamic equilibrium with its environment','A community after a disaster','A pioneer species'], answer: 1 },
      { q: 'What is selective breeding?', options: ['Genetic engineering','Humans choosing organisms with desirable traits to breed together over many generations','Natural selection','Random mating'], answer: 1 },
      { q: 'What is cloning?', options: ['Sexual reproduction','Producing genetically identical copies of an organism or cell','Mutation','Cross-breeding'], answer: 1 },
      { q: 'What is a biofuel?', options: ['A fossil fuel','A fuel derived from biological material (biomass), e.g., bioethanol from fermentation of crops','Nuclear energy','Solar energy'], answer: 1 },
      { q: 'What is the role of decomposers in nutrient cycling?', options: ['They photosynthesise','They break down dead organic matter, releasing nutrients back into the soil for uptake by plants','They are primary consumers','They fix nitrogen'], answer: 1 },
      { q: 'What is a pioneer species?', options: ['The dominant species in a climax community','The first species to colonise a bare/disturbed area, beginning primary succession','A predator','An endangered species'], answer: 1 },
      { q: 'What is conservation?', options: ['Exploiting resources without limit','The management and protection of biodiversity and natural resources for sustainable use','Only preserving rare species','Deforestation'], answer: 1 },
      { q: 'What is a plasmid?', options: ['Part of a chromosome','A small, circular DNA molecule found in bacteria, often used as a vector in genetic engineering','A type of RNA','An organelle'], answer: 1 },
    ],
    amber: [
      { q: 'How is recombinant DNA produced?', options: ['By crossing two organisms','By cutting DNA with restriction enzymes and joining fragments from different sources using DNA ligase','By PCR alone','By gel electrophoresis'], answer: 1 },
      { q: 'What is the role of DNA ligase in genetic engineering?', options: ['It cuts DNA','It joins (ligates) DNA fragments by forming phosphodiester bonds between the sugar-phosphate backbones','It amplifies DNA','It separates DNA'], answer: 1 },
      { q: 'What are sticky ends and why are they useful?', options: ['Blunt cut ends','Short single-stranded overhangs produced by restriction enzymes; they allow complementary base pairing between DNA fragments from different sources, facilitating ligation','They prevent ligation','They are produced by ligase'], answer: 1 },
      { q: 'Explain how gel electrophoresis separates DNA fragments.', options: ['By colour','DNA fragments (negatively charged) migrate through an agarose gel toward the positive electrode; smaller fragments move faster/further, separating by size','By weight in solution','By temperature'], answer: 1 },
      { q: 'What is DNA profiling (genetic fingerprinting) based on?', options: ['Coding DNA sequences','Differences in the number of short tandem repeats (STRs/VNTRs) at specific loci — these vary between individuals','Protein sequences','RNA analysis'], answer: 1 },
      { q: 'Explain how microorganisms are used in bioremediation.', options: ['They cause pollution','Microorganisms are used to break down or neutralise pollutants (e.g., oil spills, heavy metals) using their metabolic pathways','They only produce toxins','They absorb radiation'], answer: 1 },
      { q: 'What is the role of nitrifying bacteria in the nitrogen cycle?', options: ['They fix N₂ from the atmosphere','They oxidise ammonia to nitrite and then nitrite to nitrate (nitrification) — making nitrogen available to plants','They denitrify nitrate','They decompose proteins'], answer: 1 },
      { q: 'What is the role of denitrifying bacteria?', options: ['They fix nitrogen','They convert nitrate back to N₂ gas, returning nitrogen to the atmosphere — they are anaerobic','They produce ammonia','They nitrify ammonium'], answer: 1 },
      { q: 'Explain how deforestation contributes to increased atmospheric CO₂.', options: ['It has no effect','Fewer trees means less CO₂ absorbed by photosynthesis; burning/decomposition of felled trees releases stored carbon as CO₂; soil carbon may also be released','It decreases CO₂','It only affects O₂'], answer: 1 },
      { q: 'What is the difference between primary and secondary succession?', options: ['They are identical','Primary succession begins on bare, previously uncolonised substrate (e.g., bare rock); secondary succession occurs on previously colonised land after disturbance (soil already present)','Primary is faster','Secondary starts on bare rock'], answer: 1 },
      { q: 'What is Simpson\'s Index of Diversity?', options: ['A count of species','D = 1 − Σ(n/N)²; it accounts for both species richness and evenness — a higher value indicates greater diversity','Only species richness','A measure of population size'], answer: 1 },
      { q: 'Explain how insulin is produced using genetically modified bacteria.', options: ['Bacteria naturally produce insulin','The human insulin gene is identified, isolated (using reverse transcriptase from mRNA or restriction enzymes), inserted into a plasmid vector, transformed into E. coli, which then expresses and secretes human insulin','Insulin is extracted from pigs only','Bacteria cannot make insulin'], answer: 1 },
      { q: 'What are the advantages of using microorganisms in biotechnology (e.g., fermenters)?', options: ['They grow slowly','Fast reproduction, simple nutritional needs, can be grown in controlled conditions, produce useful products (antibiotics, enzymes, insulin), and some can use waste as substrate','They require sunlight','They cannot be genetically modified'], answer: 1 },
      { q: 'Explain the concept of sustainability in resource management.', options: ['Using all resources now','Using resources at a rate that meets present needs without compromising the ability of future generations to meet their needs — maintaining biodiversity and ecosystem function','Never using any resources','Only using fossil fuels'], answer: 1 },
      { q: 'What is CRISPR-Cas9 and how does it work?', options: ['A type of PCR','A gene editing tool: a guide RNA directs the Cas9 nuclease to a specific DNA sequence, which is then cut; the cell\'s repair mechanisms can delete or insert sequences at the cut site','A cloning method','A sequencing technique'], answer: 1 },
      { q: 'How does biological control differ from chemical pest control?', options: ['They are the same','Biological control uses natural predators/parasites/pathogens to reduce pest populations; chemical control uses pesticides — biological is more sustainable but slower and less predictable','Biological uses chemicals','Chemical control uses predators'], answer: 1 },
      { q: 'Explain how intensive farming increases productivity but can reduce biodiversity.', options: ['It always increases biodiversity','Monocultures, pesticides, and removal of hedgerows maximise yield but destroy habitats, reduce species diversity, and can cause pollution (eutrophication from fertiliser runoff)','It has no environmental impact','It only affects soil'], answer: 1 },
      { q: 'What is the role of saprotrophic fungi in decomposition?', options: ['They photosynthesise','They secrete extracellular enzymes onto dead organic matter, digesting it externally, then absorb the soluble products — recycling nutrients back into the ecosystem','They are parasites only','They fix nitrogen'], answer: 1 },
      { q: 'Explain how the greenhouse effect is enhanced by human activities.', options: ['Humans have no effect','Burning fossil fuels and deforestation increase CO₂; agriculture increases methane and N₂O; these additional greenhouse gases trap more infrared radiation, increasing global temperatures beyond natural levels','Only natural processes matter','CO₂ is not a greenhouse gas'], answer: 1 },
      { q: 'What is a marker gene used for in genetic engineering?', options: ['To cut DNA','To identify which cells have successfully taken up the recombinant plasmid — e.g., antibiotic resistance gene allows selection on antibiotic-containing agar','To join DNA fragments','To amplify DNA'], answer: 1 },
    ],
    red: [
      { q: 'Evaluate the ethical, social, and environmental arguments for and against the use of GMOs in agriculture.', options: ['Only economic arguments exist','GMOs are always harmful','For: increased yield, pest resistance, reduced pesticide use','There are no arguments against'], answer: 2 },
      { q: 'Discuss how climate change acts as a selection pressure and may drive evolution in affected populations.', options: ['Changed conditions (temperature, rainfall','Climate change has no evolutionary effect','Only genetic drift matters','Evolution stops during climate change'], answer: 0 },
      { q: 'Explain why maintaining genetic diversity within crop species is important for food security.', options: ['All crops should be identical','Only yield matters','Genetic diversity is irrelevant to crops','Genetic diversity provides a pool of alleles that may confer'], answer: 3 },
      { q: 'Analyse the impact of ocean acidification (from increased CO₂) on marine ecosystems.', options: ['CO₂ does not dissolve in water','Increased dissolved CO₂ lowers ocean pH; this reduces','Only temperature matters','Acidification benefits all marine life'], answer: 1 },
      { q: 'Evaluate the effectiveness of ex-situ vs in-situ conservation strategies.', options: ['Only one approach is needed','In-situ (nature reserves, protected areas) conserves species','Ex-situ is always better','In-situ has no limitations'], answer: 1 },
      { q: 'Explain why the loss of keystone species can have disproportionate effects on ecosystem stability.', options: ['Keystone species are unimportant','Keystone species have a disproportionately large effect','All species are equally important','Only producers are keystone'], answer: 1 },
      { q: 'Discuss the potential ecological risks of releasing genetically modified organisms into the environment.', options: ['Only benefits exist','GM organisms cannot survive in the wild','Risks include: gene flow to wild relatives creating "superweeds"','There are no risks'], answer: 2 },
      { q: 'Evaluate the role of international agreements (e.g., Paris Agreement) in addressing climate change.', options: ['They have no effect whatsoever','They set targets for emission reduction and promote cooperation','Only individual action matters','They are completely effective'], answer: 1 },
      { q: 'Explain why antibiotic resistance is considered one of the greatest threats to global health, linking evolution and biotechnology.', options: ['Overuse/misuse of antibiotics creates selection pressure','New antibiotics always solve the problem','Only hospitals are affected','Resistance is not a problem'], answer: 0 },
      { q: 'Discuss how the use of biological indicators and abiotic measurements together provide a more complete assessment of environmental quality.', options: ['Only one method is needed','Biological indicators are unreliable','Biological indicators (e.g., lichen diversity for air quality','Abiotic measurements are useless'], answer: 2 },
    ],
  },

};

if (typeof module !== 'undefined') module.exports = BIOLOGY_OCR_B_QUESTIONS;
