-- Lists every topic in flashcards-config.js with fewer than 30 cards (no rows = all done).
WITH cfg(subject, exam_board, level, topic_id) AS (VALUES
  ('Business Studies', 'Edexcel', 'alevel', '1.1'),
  ('Business Studies', 'Edexcel', 'alevel', '1.2'),
  ('Business Studies', 'Edexcel', 'alevel', '1.3'),
  ('Business Studies', 'Edexcel', 'alevel', '1.4'),
  ('Business Studies', 'Edexcel', 'alevel', '1.5'),
  ('Business Studies', 'Edexcel', 'alevel', '2.1'),
  ('Business Studies', 'Edexcel', 'alevel', '2.2'),
  ('Business Studies', 'Edexcel', 'alevel', '2.3'),
  ('Business Studies', 'Edexcel', 'alevel', '2.4'),
  ('Business Studies', 'Edexcel', 'alevel', '2.5'),
  ('Business Studies', 'Edexcel', 'alevel', '3.1'),
  ('Business Studies', 'Edexcel', 'alevel', '3.2'),
  ('Business Studies', 'Edexcel', 'alevel', '3.3'),
  ('Business Studies', 'Edexcel', 'alevel', '3.4'),
  ('Business Studies', 'Edexcel', 'alevel', '3.5'),
  ('Business Studies', 'Edexcel', 'alevel', '3.6'),
  ('Business Studies', 'Edexcel', 'alevel', '4.1'),
  ('Business Studies', 'Edexcel', 'alevel', '4.2'),
  ('Business Studies', 'Edexcel', 'alevel', '4.3'),
  ('Business Studies', 'Edexcel', 'alevel', '4.4'),
  ('Politics', 'Edexcel', 'alevel', '1.1'),
  ('Politics', 'Edexcel', 'alevel', '1.2'),
  ('Politics', 'Edexcel', 'alevel', '1.3'),
  ('Politics', 'Edexcel', 'alevel', '1.4'),
  ('Politics', 'Edexcel', 'alevel', '1.5'),
  ('Politics', 'Edexcel', 'alevel', '1.6'),
  ('Politics', 'Edexcel', 'alevel', '1.7'),
  ('Politics', 'Edexcel', 'alevel', '2.1'),
  ('Politics', 'Edexcel', 'alevel', '2.2'),
  ('Politics', 'Edexcel', 'alevel', '2.3'),
  ('Politics', 'Edexcel', 'alevel', '2.4'),
  ('Politics', 'Edexcel', 'alevel', '2.5'),
  ('Politics', 'Edexcel', 'alevel', '2.6'),
  ('Politics', 'Edexcel', 'alevel', '2.7'),
  ('Politics', 'Edexcel', 'alevel', '2.8'),
  ('Politics', 'Edexcel', 'alevel', '2.9'),
  ('Politics', 'Edexcel', 'alevel', '3A.1'),
  ('Politics', 'Edexcel', 'alevel', '3A.2'),
  ('Politics', 'Edexcel', 'alevel', '3A.3'),
  ('Politics', 'Edexcel', 'alevel', '3A.4'),
  ('Politics', 'Edexcel', 'alevel', '3A.5'),
  ('Politics', 'Edexcel', 'alevel', '3A.6'),
  ('Politics', 'Edexcel', 'alevel', '3B.1'),
  ('Politics', 'Edexcel', 'alevel', '3B.2'),
  ('Politics', 'Edexcel', 'alevel', '3B.3'),
  ('Politics', 'Edexcel', 'alevel', '3B.4'),
  ('Politics', 'Edexcel', 'alevel', '3B.5'),
  ('Politics', 'Edexcel', 'alevel', '3B.6'),
  ('Politics', 'AQA', 'alevel', '1.1'),
  ('Politics', 'AQA', 'alevel', '1.2'),
  ('Politics', 'AQA', 'alevel', '1.3'),
  ('Politics', 'AQA', 'alevel', '1.4'),
  ('Politics', 'AQA', 'alevel', '1.5'),
  ('Politics', 'AQA', 'alevel', '1.6'),
  ('Politics', 'AQA', 'alevel', '1.7'),
  ('Politics', 'AQA', 'alevel', '1.8'),
  ('Politics', 'AQA', 'alevel', '1.9'),
  ('Politics', 'AQA', 'alevel', '1.10'),
  ('Politics', 'AQA', 'alevel', '2.1'),
  ('Politics', 'AQA', 'alevel', '2.2'),
  ('Politics', 'AQA', 'alevel', '2.3'),
  ('Politics', 'AQA', 'alevel', '2.4'),
  ('Politics', 'AQA', 'alevel', '2.5'),
  ('Politics', 'AQA', 'alevel', '2.6'),
  ('Politics', 'AQA', 'alevel', '2.7'),
  ('Politics', 'AQA', 'alevel', '2.8'),
  ('Politics', 'AQA', 'alevel', '2.9'),
  ('Politics', 'AQA', 'alevel', '2.10'),
  ('Politics', 'AQA', 'alevel', '2.11'),
  ('Politics', 'AQA', 'alevel', '2.12'),
  ('Politics', 'AQA', 'alevel', '2.13'),
  ('Politics', 'AQA', 'alevel', '2.14'),
  ('Politics', 'AQA', 'alevel', '3.1'),
  ('Politics', 'AQA', 'alevel', '3.2'),
  ('Politics', 'AQA', 'alevel', '3.3'),
  ('Politics', 'AQA', 'alevel', '3.4'),
  ('Politics', 'AQA', 'alevel', '3.5'),
  ('Politics', 'AQA', 'alevel', '3.6'),
  ('Politics', 'AQA', 'alevel', '3.7'),
  ('Politics', 'AQA', 'alevel', '3.8'),
  ('Computer Science', 'OCR', 'gcse', '1.1'),
  ('Computer Science', 'OCR', 'gcse', '1.2'),
  ('Computer Science', 'OCR', 'gcse', '1.3'),
  ('Computer Science', 'OCR', 'gcse', '1.4'),
  ('Computer Science', 'OCR', 'gcse', '1.5'),
  ('Computer Science', 'OCR', 'gcse', '1.6'),
  ('Computer Science', 'OCR', 'gcse', '2.1'),
  ('Computer Science', 'OCR', 'gcse', '2.2'),
  ('Computer Science', 'OCR', 'gcse', '2.3'),
  ('Computer Science', 'OCR', 'gcse', '2.4'),
  ('Computer Science', 'OCR', 'gcse', '2.5'),
  ('Computer Science', 'OCR', 'alevel', '1.1'),
  ('Computer Science', 'OCR', 'alevel', '1.2'),
  ('Computer Science', 'OCR', 'alevel', '1.3'),
  ('Computer Science', 'OCR', 'alevel', '1.4'),
  ('Computer Science', 'OCR', 'alevel', '1.5'),
  ('Computer Science', 'OCR', 'alevel', '2.1'),
  ('Computer Science', 'OCR', 'alevel', '2.2'),
  ('Computer Science', 'OCR', 'alevel', '2.3'),
  ('Computer Science', 'AQA', 'alevel', '4.1'),
  ('Computer Science', 'AQA', 'alevel', '4.2'),
  ('Computer Science', 'AQA', 'alevel', '4.3'),
  ('Computer Science', 'AQA', 'alevel', '4.4'),
  ('Computer Science', 'AQA', 'alevel', '4.5'),
  ('Computer Science', 'AQA', 'alevel', '4.6'),
  ('Computer Science', 'AQA', 'alevel', '4.7'),
  ('Computer Science', 'AQA', 'alevel', '4.8'),
  ('Computer Science', 'AQA', 'alevel', '4.9'),
  ('Computer Science', 'AQA', 'alevel', '4.10'),
  ('Computer Science', 'AQA', 'gcse', '3.1'),
  ('Computer Science', 'AQA', 'gcse', '3.2'),
  ('Computer Science', 'AQA', 'gcse', '3.3'),
  ('Computer Science', 'AQA', 'gcse', '3.4'),
  ('Computer Science', 'AQA', 'gcse', '3.5'),
  ('Computer Science', 'AQA', 'gcse', '3.6'),
  ('Computer Science', 'AQA', 'gcse', '3.7'),
  ('Computer Science', 'AQA', 'gcse', '3.8'),
  ('Physics', 'Edexcel', 'alevel', 'T1'),
  ('Physics', 'Edexcel', 'alevel', 'T2'),
  ('Physics', 'Edexcel', 'alevel', 'T3'),
  ('Physics', 'Edexcel', 'alevel', 'T4'),
  ('Physics', 'Edexcel', 'alevel', 'T5'),
  ('Physics', 'Edexcel', 'alevel', 'T6'),
  ('Physics', 'Edexcel', 'alevel', 'T7'),
  ('Physics', 'Edexcel', 'alevel', 'T8'),
  ('Physics', 'Edexcel', 'alevel', 'T9'),
  ('Physics', 'Edexcel', 'alevel', 'T10'),
  ('Physics', 'Edexcel', 'alevel', 'T11'),
  ('Physics', 'Edexcel', 'alevel', 'T12'),
  ('Physics', 'Edexcel', 'alevel', 'T13'),
  ('Physics', 'AQA', 'alevel', '3.1'),
  ('Physics', 'AQA', 'alevel', '3.2'),
  ('Physics', 'AQA', 'alevel', '3.3'),
  ('Physics', 'AQA', 'alevel', '3.4'),
  ('Physics', 'AQA', 'alevel', '3.5'),
  ('Physics', 'AQA', 'alevel', '3.6'),
  ('Physics', 'AQA', 'alevel', '3.7'),
  ('Physics', 'AQA', 'alevel', '3.8'),
  ('Physics', 'AQA', 'gcse', '4.1'),
  ('Physics', 'AQA', 'gcse', '4.2'),
  ('Physics', 'AQA', 'gcse', '4.3'),
  ('Physics', 'AQA', 'gcse', '4.4'),
  ('Physics', 'AQA', 'gcse', '4.5'),
  ('Physics', 'AQA', 'gcse', '4.6'),
  ('Physics', 'AQA', 'gcse', '4.7'),
  ('Physics', 'AQA', 'gcse', '4.8'),
  ('Physics', 'Edexcel', 'gcse', '1'),
  ('Physics', 'Edexcel', 'gcse', '2'),
  ('Physics', 'Edexcel', 'gcse', '3'),
  ('Physics', 'Edexcel', 'gcse', '4'),
  ('Physics', 'Edexcel', 'gcse', '5'),
  ('Physics', 'Edexcel', 'gcse', '6'),
  ('Physics', 'Edexcel', 'gcse', '7'),
  ('Physics', 'Edexcel', 'gcse', '8'),
  ('Physics', 'Edexcel', 'gcse', '9'),
  ('Physics', 'Edexcel', 'gcse', '10'),
  ('Physics', 'Edexcel', 'gcse', '11'),
  ('Physics', 'Edexcel', 'gcse', '12'),
  ('Physics', 'Edexcel', 'gcse', '13'),
  ('Physics', 'Edexcel', 'gcse', '14'),
  ('Physics', 'Edexcel', 'gcse', '15'),
  ('Physics', 'OCR A', 'alevel', 'M1'),
  ('Physics', 'OCR A', 'alevel', 'M2'),
  ('Physics', 'OCR A', 'alevel', 'M3'),
  ('Physics', 'OCR A', 'alevel', 'M4'),
  ('Physics', 'OCR A', 'alevel', 'M5'),
  ('Physics', 'OCR A', 'alevel', 'M6'),
  ('Physics', 'OCR A', 'gcse', 'P1'),
  ('Physics', 'OCR A', 'gcse', 'P2'),
  ('Physics', 'OCR A', 'gcse', 'P3'),
  ('Physics', 'OCR A', 'gcse', 'P4'),
  ('Physics', 'OCR A', 'gcse', 'P5'),
  ('Physics', 'OCR A', 'gcse', 'P6'),
  ('Physics', 'OCR B', 'alevel', 'B1'),
  ('Physics', 'OCR B', 'alevel', 'B2'),
  ('Physics', 'OCR B', 'alevel', 'B3'),
  ('Physics', 'OCR B', 'alevel', 'B4'),
  ('Physics', 'OCR B', 'alevel', 'B5'),
  ('Physics', 'OCR B', 'alevel', 'B6'),
  ('Physics', 'OCR B', 'gcse', 'P1'),
  ('Physics', 'OCR B', 'gcse', 'P2'),
  ('Physics', 'OCR B', 'gcse', 'P3'),
  ('Physics', 'OCR B', 'gcse', 'P4'),
  ('Physics', 'OCR B', 'gcse', 'P5'),
  ('Physics', 'OCR B', 'gcse', 'P6'),
  ('Economics', 'AQA', 'alevel', '3.1.1'),
  ('Economics', 'AQA', 'alevel', '3.1.2'),
  ('Economics', 'AQA', 'alevel', '3.1.3'),
  ('Economics', 'AQA', 'alevel', '3.1.4'),
  ('Economics', 'AQA', 'alevel', '3.1.5'),
  ('Economics', 'AQA', 'alevel', '3.1.6'),
  ('Economics', 'AQA', 'alevel', '3.1.7'),
  ('Economics', 'AQA', 'alevel', '3.1.8'),
  ('Economics', 'AQA', 'alevel', '3.2.1'),
  ('Economics', 'AQA', 'alevel', '3.2.2'),
  ('Economics', 'AQA', 'alevel', '3.2.3'),
  ('Economics', 'AQA', 'alevel', '3.2.4'),
  ('Economics', 'AQA', 'alevel', '3.2.5'),
  ('Economics', 'AQA', 'alevel', '3.2.6'),
  ('Economics', 'Edexcel A', 'alevel', '1.1'),
  ('Economics', 'Edexcel A', 'alevel', '1.2'),
  ('Economics', 'Edexcel A', 'alevel', '2.1'),
  ('Economics', 'Edexcel A', 'alevel', '2.2'),
  ('Economics', 'Edexcel A', 'alevel', '3.1'),
  ('Economics', 'Edexcel A', 'alevel', '3.2'),
  ('Economics', 'Edexcel A', 'alevel', '4.1'),
  ('Economics', 'Edexcel A', 'alevel', '4.2'),
  ('Economics', 'Edexcel B', 'alevel', '1.1'),
  ('Economics', 'Edexcel B', 'alevel', '1.2'),
  ('Economics', 'Edexcel B', 'alevel', '2.1'),
  ('Economics', 'Edexcel B', 'alevel', '2.2'),
  ('Economics', 'Edexcel B', 'alevel', '3.1'),
  ('Economics', 'Edexcel B', 'alevel', '3.2'),
  ('Economics', 'Edexcel B', 'alevel', '4.1'),
  ('Economics', 'Edexcel B', 'alevel', '4.2'),
  ('Economics', 'OCR', 'alevel', '1.1'),
  ('Economics', 'OCR', 'alevel', '1.2'),
  ('Economics', 'OCR', 'alevel', '1.3'),
  ('Economics', 'OCR', 'alevel', '1.4'),
  ('Economics', 'OCR', 'alevel', '2.1'),
  ('Economics', 'OCR', 'alevel', '2.2'),
  ('Economics', 'OCR', 'alevel', '2.3'),
  ('Economics', 'OCR', 'alevel', '2.4'),
  ('Chemistry', 'AQA', 'alevel', 'P1'),
  ('Chemistry', 'AQA', 'alevel', 'P2'),
  ('Chemistry', 'AQA', 'alevel', 'I1'),
  ('Chemistry', 'AQA', 'alevel', 'I2'),
  ('Chemistry', 'AQA', 'alevel', 'O1'),
  ('Chemistry', 'AQA', 'alevel', 'O2'),
  ('Chemistry', 'Edexcel', 'alevel', 'T1'),
  ('Chemistry', 'Edexcel', 'alevel', 'T2'),
  ('Chemistry', 'Edexcel', 'alevel', 'T3'),
  ('Chemistry', 'Edexcel', 'alevel', 'T4'),
  ('Chemistry', 'Edexcel', 'alevel', 'T5'),
  ('Chemistry', 'Edexcel', 'alevel', 'T6'),
  ('Chemistry', 'OCR A', 'alevel', 'M1'),
  ('Chemistry', 'OCR A', 'alevel', 'M2'),
  ('Chemistry', 'OCR A', 'alevel', 'M3'),
  ('Chemistry', 'OCR A', 'alevel', 'M4'),
  ('Chemistry', 'OCR A', 'alevel', 'M5'),
  ('Chemistry', 'OCR A', 'alevel', 'M6'),
  ('Chemistry', 'OCR B', 'alevel', 'EL'),
  ('Chemistry', 'OCR B', 'alevel', 'DF'),
  ('Chemistry', 'OCR B', 'alevel', 'ES'),
  ('Chemistry', 'OCR B', 'alevel', 'OZ'),
  ('Chemistry', 'OCR B', 'alevel', 'WM'),
  ('Chemistry', 'OCR B', 'alevel', 'CI'),
  ('Chemistry', 'OCR B', 'alevel', 'PL'),
  ('Chemistry', 'OCR B', 'alevel', 'O'),
  ('Chemistry', 'OCR B', 'alevel', 'DM'),
  ('Chemistry', 'OCR B', 'alevel', 'CD'),
  ('Biology', 'AQA', 'alevel', 'T1'),
  ('Biology', 'AQA', 'alevel', 'T2'),
  ('Biology', 'AQA', 'alevel', 'T3'),
  ('Biology', 'AQA', 'alevel', 'T4'),
  ('Biology', 'AQA', 'alevel', 'T5'),
  ('Biology', 'AQA', 'alevel', 'T6'),
  ('Biology', 'AQA', 'alevel', 'T7'),
  ('Biology', 'AQA', 'alevel', 'T8'),
  ('Biology', 'Edexcel A', 'alevel', 'S1'),
  ('Biology', 'Edexcel A', 'alevel', 'S2'),
  ('Biology', 'Edexcel A', 'alevel', 'S3'),
  ('Biology', 'Edexcel A', 'alevel', 'S4'),
  ('Biology', 'Edexcel A', 'alevel', 'S5'),
  ('Biology', 'Edexcel A', 'alevel', 'S6'),
  ('Biology', 'Edexcel A', 'alevel', 'S7'),
  ('Biology', 'Edexcel A', 'alevel', 'S8'),
  ('Biology', 'Edexcel B', 'alevel', '1'),
  ('Biology', 'Edexcel B', 'alevel', '2'),
  ('Biology', 'Edexcel B', 'alevel', '3'),
  ('Biology', 'Edexcel B', 'alevel', '4'),
  ('Biology', 'Edexcel B', 'alevel', '5'),
  ('Biology', 'Edexcel B', 'alevel', '6'),
  ('Biology', 'Edexcel B', 'alevel', '7'),
  ('Biology', 'Edexcel B', 'alevel', '8'),
  ('Biology', 'Edexcel B', 'alevel', '9'),
  ('Biology', 'Edexcel B', 'alevel', '10'),
  ('Biology', 'OCR A', 'alevel', 'M1'),
  ('Biology', 'OCR A', 'alevel', 'M2'),
  ('Biology', 'OCR A', 'alevel', 'M3'),
  ('Biology', 'OCR A', 'alevel', 'M4'),
  ('Biology', 'OCR A', 'alevel', 'M5'),
  ('Biology', 'OCR A', 'alevel', 'M6'),
  ('Biology', 'OCR B', 'alevel', 'B1'),
  ('Biology', 'OCR B', 'alevel', 'B2'),
  ('Biology', 'OCR B', 'alevel', 'B3'),
  ('Biology', 'OCR B', 'alevel', 'B4'),
  ('Biology', 'OCR B', 'alevel', 'B5'),
  ('Biology', 'OCR B', 'alevel', 'B6'),
  ('Geography', 'AQA', 'alevel', '1.1'),
  ('Geography', 'AQA', 'alevel', '1.2'),
  ('Geography', 'AQA', 'alevel', '1.3'),
  ('Geography', 'AQA', 'alevel', '2.1'),
  ('Geography', 'AQA', 'alevel', '2.2'),
  ('Geography', 'AQA', 'alevel', '2.3'),
  ('Geography', 'AQA', 'alevel', '2.4'),
  ('Geography', 'AQA', 'alevel', '2.5'),
  ('Geography', 'AQA', 'alevel', '3.1'),
  ('Geography', 'Edexcel', 'alevel', 'T1'),
  ('Geography', 'Edexcel', 'alevel', 'T2'),
  ('Geography', 'Edexcel', 'alevel', 'T3'),
  ('Geography', 'Edexcel', 'alevel', 'T4'),
  ('Geography', 'Edexcel', 'alevel', 'T5'),
  ('Geography', 'Edexcel', 'alevel', 'T6'),
  ('Geography', 'Edexcel', 'alevel', 'T7'),
  ('Geography', 'Edexcel', 'alevel', 'T8'),
  ('Geography', 'OCR', 'alevel', '1.1'),
  ('Geography', 'OCR', 'alevel', '1.2'),
  ('Geography', 'OCR', 'alevel', '1.3'),
  ('Geography', 'OCR', 'alevel', '2.1'),
  ('Geography', 'OCR', 'alevel', '2.2'),
  ('Geography', 'OCR', 'alevel', '2.3'),
  ('Geography', 'OCR', 'alevel', '2.4'),
  ('Geography', 'OCR', 'alevel', '2.5'),
  ('Geography', 'Eduqas', 'alevel', '1.1'),
  ('Geography', 'Eduqas', 'alevel', '1.2'),
  ('Geography', 'Eduqas', 'alevel', '1.3'),
  ('Geography', 'Eduqas', 'alevel', '2.1'),
  ('Geography', 'Eduqas', 'alevel', '2.2'),
  ('Geography', 'Eduqas', 'alevel', '2.3'),
  ('Geography', 'Eduqas', 'alevel', '2.4'),
  ('Geography', 'Eduqas', 'alevel', '2.5'),
  ('Geography', 'Eduqas', 'alevel', '3.1'),
  ('Geography', 'Eduqas', 'alevel', '3.2'),
  ('Geography', 'Eduqas', 'gcse', '1.1'),
  ('Geography', 'Eduqas', 'gcse', '1.2'),
  ('Geography', 'Eduqas', 'gcse', '1.3'),
  ('Geography', 'Eduqas', 'gcse', '1.4'),
  ('Geography', 'Eduqas', 'gcse', '1.5'),
  ('Geography', 'Eduqas', 'gcse', '1.6'),
  ('Geography', 'Eduqas', 'gcse', '2.1'),
  ('Geography', 'Eduqas', 'gcse', '2.2'),
  ('Geography', 'Eduqas', 'gcse', '2.3'),
  ('Geography', 'Eduqas', 'gcse', '3.1'),
  ('Geography', 'Eduqas', 'gcse', '3.2'),
  ('Geography', 'Eduqas', 'gcse', '3.3'),
  ('Mathematics', 'OCR', 'alevel', '1.1'),
  ('Mathematics', 'OCR', 'alevel', '1.2'),
  ('Mathematics', 'OCR', 'alevel', '1.3'),
  ('Mathematics', 'OCR', 'alevel', '1.4'),
  ('Mathematics', 'OCR', 'alevel', '1.5'),
  ('Mathematics', 'OCR', 'alevel', '1.6'),
  ('Mathematics', 'OCR', 'alevel', '1.7'),
  ('Mathematics', 'OCR', 'alevel', '1.8'),
  ('Mathematics', 'OCR', 'alevel', '1.9'),
  ('Mathematics', 'OCR', 'alevel', '1.10'),
  ('Mathematics', 'OCR', 'alevel', '2.1'),
  ('Mathematics', 'OCR', 'alevel', '2.2'),
  ('Mathematics', 'OCR B', 'alevel', '1.1'),
  ('Mathematics', 'OCR B', 'alevel', '1.2'),
  ('Mathematics', 'OCR B', 'alevel', '1.3'),
  ('Mathematics', 'OCR B', 'alevel', '1.4'),
  ('Mathematics', 'OCR B', 'alevel', '1.5'),
  ('Mathematics', 'OCR B', 'alevel', '1.6'),
  ('Mathematics', 'OCR B', 'alevel', '1.7'),
  ('Mathematics', 'OCR B', 'alevel', '1.8'),
  ('Mathematics', 'OCR B', 'alevel', '1.9'),
  ('Mathematics', 'OCR B', 'alevel', '1.10'),
  ('Mathematics', 'OCR B', 'alevel', '1.11'),
  ('Mathematics', 'OCR B', 'alevel', '1.12'),
  ('Mathematics', 'OCR B', 'alevel', '1.13'),
  ('Mathematics', 'OCR B', 'alevel', '2.1'),
  ('Mathematics', 'OCR B', 'alevel', '2.2'),
  ('Mathematics', 'OCR B', 'alevel', '2.3'),
  ('Mathematics', 'OCR B', 'alevel', '2.4'),
  ('Mathematics', 'OCR B', 'alevel', '2.5'),
  ('Mathematics', 'OCR B', 'alevel', '3.1'),
  ('Mathematics', 'OCR B', 'alevel', '3.2'),
  ('Mathematics', 'OCR B', 'alevel', '3.3'),
  ('Mathematics', 'OCR B', 'alevel', '3.4'),
  ('Mathematics', 'OCR B', 'alevel', '3.5'),
  ('Mathematics', 'OCR B', 'alevel', '3.6'),
  ('Mathematics', 'OCR B', 'alevel', '3.7'),
  ('Mathematics', 'OCR', 'gcse', '1.1'),
  ('Mathematics', 'OCR', 'gcse', '1.2'),
  ('Mathematics', 'OCR', 'gcse', '1.3'),
  ('Mathematics', 'OCR', 'gcse', '1.4'),
  ('Mathematics', 'OCR', 'gcse', '2.1'),
  ('Mathematics', 'OCR', 'gcse', '2.2'),
  ('Mathematics', 'OCR', 'gcse', '2.3'),
  ('Mathematics', 'OCR', 'gcse', '2.4'),
  ('Mathematics', 'OCR', 'gcse', '3.1'),
  ('Mathematics', 'OCR', 'gcse', '3.2'),
  ('Mathematics', 'OCR', 'gcse', '4.1'),
  ('Mathematics', 'OCR', 'gcse', '4.2'),
  ('Mathematics', 'OCR', 'gcse', '4.3'),
  ('Mathematics', 'OCR', 'gcse', '4.4'),
  ('Mathematics', 'OCR', 'gcse', '4.5'),
  ('Mathematics', 'OCR', 'gcse', '4.6'),
  ('Mathematics', 'OCR', 'gcse', '5.1'),
  ('Mathematics', 'OCR', 'gcse', '6.1'),
  ('Mathematics', 'OCR', 'gcse', '6.2'),
  ('Mathematics', 'AQA', 'alevel', '1.1'),
  ('Mathematics', 'AQA', 'alevel', '1.2'),
  ('Mathematics', 'AQA', 'alevel', '1.3'),
  ('Mathematics', 'AQA', 'alevel', '1.4'),
  ('Mathematics', 'AQA', 'alevel', '1.5'),
  ('Mathematics', 'AQA', 'alevel', '1.6'),
  ('Mathematics', 'AQA', 'alevel', '1.7'),
  ('Mathematics', 'AQA', 'alevel', '1.8'),
  ('Mathematics', 'AQA', 'alevel', '1.9'),
  ('Mathematics', 'AQA', 'alevel', '1.10'),
  ('Mathematics', 'AQA', 'alevel', '2.1'),
  ('Mathematics', 'AQA', 'alevel', '2.2'),
  ('Mathematics', 'Edexcel', 'alevel', 'P1'),
  ('Mathematics', 'Edexcel', 'alevel', 'P2'),
  ('Mathematics', 'Edexcel', 'alevel', 'P3'),
  ('Mathematics', 'Edexcel', 'alevel', 'P4'),
  ('Mathematics', 'Edexcel', 'alevel', 'P5'),
  ('Mathematics', 'Edexcel', 'alevel', 'P6'),
  ('Mathematics', 'Edexcel', 'alevel', 'P7'),
  ('Mathematics', 'Edexcel', 'alevel', 'P8'),
  ('Mathematics', 'Edexcel', 'alevel', 'P9'),
  ('Mathematics', 'Edexcel', 'alevel', 'P10'),
  ('Mathematics', 'Edexcel', 'alevel', 'P11'),
  ('Mathematics', 'Edexcel', 'alevel', 'P12'),
  ('Mathematics', 'Edexcel', 'alevel', 'P13'),
  ('Mathematics', 'Edexcel', 'alevel', 'P14'),
  ('Mathematics', 'Edexcel', 'alevel', 'P15'),
  ('Mathematics', 'Edexcel', 'alevel', 'P16'),
  ('Mathematics', 'Edexcel', 'alevel', 'P17'),
  ('Mathematics', 'Edexcel', 'alevel', 'P18'),
  ('Mathematics', 'Edexcel', 'alevel', 'P19'),
  ('Mathematics', 'Edexcel', 'alevel', 'P20'),
  ('Mathematics', 'Edexcel', 'alevel', 'P21'),
  ('Mathematics', 'Edexcel', 'alevel', 'S1'),
  ('Mathematics', 'Edexcel', 'alevel', 'S2'),
  ('Mathematics', 'Edexcel', 'alevel', 'S3'),
  ('Mathematics', 'Edexcel', 'alevel', 'S4'),
  ('Mathematics', 'Edexcel', 'alevel', 'S5'),
  ('Mathematics', 'Edexcel', 'alevel', 'S6'),
  ('Mathematics', 'Edexcel', 'alevel', 'S7'),
  ('Mathematics', 'Edexcel', 'alevel', 'S8'),
  ('Mathematics', 'Edexcel', 'alevel', 'M1'),
  ('Mathematics', 'Edexcel', 'alevel', 'M2'),
  ('Mathematics', 'Edexcel', 'alevel', 'M3'),
  ('Mathematics', 'Edexcel', 'alevel', 'M4'),
  ('Mathematics', 'Edexcel', 'alevel', 'M5'),
  ('Mathematics', 'Edexcel', 'alevel', 'M6'),
  ('Mathematics', 'Edexcel', 'alevel', 'M7'),
  ('Further Mathematics', 'AQA', 'alevel', '1.1'),
  ('Further Mathematics', 'AQA', 'alevel', '1.2'),
  ('Further Mathematics', 'AQA', 'alevel', '1.3'),
  ('Further Mathematics', 'AQA', 'alevel', '1.4'),
  ('Further Mathematics', 'AQA', 'alevel', '1.5'),
  ('Further Mathematics', 'AQA', 'alevel', '1.6'),
  ('Further Mathematics', 'AQA', 'alevel', '1.7'),
  ('Further Mathematics', 'AQA', 'alevel', '1.8'),
  ('Further Mathematics', 'AQA', 'alevel', '1.9'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.1'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.2'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.3'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.4'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.5'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.6'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.7'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.8'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP1.9'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.1'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.2'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.3'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.4'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.5'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.6'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.7'),
  ('Further Mathematics', 'Edexcel', 'alevel', 'CP2.8'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.1'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.2'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.3'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.4'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.5'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.6'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.7'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.8'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.9'),
  ('Further Mathematics', 'OCR A', 'alevel', '1.10'),
  ('Further Mathematics', 'OCR A', 'alevel', 'D1.1'),
  ('Further Mathematics', 'OCR A', 'alevel', 'D1.2'),
  ('Further Mathematics', 'OCR A', 'alevel', 'D1.3'),
  ('Further Mathematics', 'OCR A', 'alevel', 'D1.4'),
  ('Further Mathematics', 'OCR A', 'alevel', 'D1.5'),
  ('Further Mathematics', 'OCR A', 'alevel', 'M1.1'),
  ('Further Mathematics', 'OCR A', 'alevel', 'M1.2'),
  ('Further Mathematics', 'OCR A', 'alevel', 'M1.3'),
  ('Further Mathematics', 'OCR A', 'alevel', 'M1.4'),
  ('Further Mathematics', 'OCR A', 'alevel', 'M1.5'),
  ('Further Mathematics', 'OCR A', 'alevel', 'S1.1'),
  ('Further Mathematics', 'OCR A', 'alevel', 'S1.2'),
  ('Further Mathematics', 'OCR A', 'alevel', 'S1.3'),
  ('Further Mathematics', 'OCR A', 'alevel', 'S1.4'),
  ('Further Mathematics', 'OCR A', 'alevel', 'S1.5'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.1'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.2'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.3'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.4'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.5'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.6'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.7'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.8'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.9'),
  ('Further Mathematics', 'OCR B', 'alevel', '1.10'),
  ('Further Mathematics', 'OCR B', 'alevel', 'A1.1'),
  ('Further Mathematics', 'OCR B', 'alevel', 'A1.2'),
  ('Further Mathematics', 'OCR B', 'alevel', 'A1.3'),
  ('Further Mathematics', 'OCR B', 'alevel', 'A1.4'),
  ('Further Mathematics', 'OCR B', 'alevel', 'A1.5'),
  ('Further Mathematics', 'OCR B', 'alevel', 'M1.1'),
  ('Further Mathematics', 'OCR B', 'alevel', 'M1.2'),
  ('Further Mathematics', 'OCR B', 'alevel', 'M1.3'),
  ('Further Mathematics', 'OCR B', 'alevel', 'M1.4'),
  ('Further Mathematics', 'OCR B', 'alevel', 'M1.5'),
  ('Further Mathematics', 'OCR B', 'alevel', 'S1.1'),
  ('Further Mathematics', 'OCR B', 'alevel', 'S1.2'),
  ('Further Mathematics', 'OCR B', 'alevel', 'S1.3'),
  ('Further Mathematics', 'OCR B', 'alevel', 'S1.4'),
  ('Further Mathematics', 'OCR B', 'alevel', 'S1.5'),
  ('English Language', 'AQA', 'alevel', '1.1'),
  ('English Language', 'AQA', 'alevel', '1.2'),
  ('English Language', 'AQA', 'alevel', '1.3'),
  ('English Language', 'AQA', 'alevel', '1.4'),
  ('English Language', 'AQA', 'alevel', '2.1'),
  ('English Language', 'AQA', 'alevel', '2.2'),
  ('English Language', 'AQA', 'alevel', '2.3'),
  ('English Language', 'AQA', 'alevel', '2.4'),
  ('English Language', 'AQA', 'alevel', '2.5'),
  ('English Language', 'AQA', 'alevel', '3.1'),
  ('English Language', 'AQA', 'alevel', '3.2'),
  ('English Language', 'Edexcel', 'alevel', '1.1'),
  ('English Language', 'Edexcel', 'alevel', '1.2'),
  ('English Language', 'Edexcel', 'alevel', '1.3'),
  ('English Language', 'Edexcel', 'alevel', '2.1'),
  ('English Language', 'Edexcel', 'alevel', '2.2'),
  ('English Language', 'Edexcel', 'alevel', '3.1'),
  ('English Language', 'Edexcel', 'alevel', '3.2'),
  ('English Language', 'Edexcel', 'alevel', '3.3'),
  ('English Language', 'Edexcel', 'alevel', '3.4'),
  ('English Language', 'Edexcel', 'alevel', '3.5'),
  ('English Language', 'Edexcel', 'alevel', '4.1')
)
SELECT cfg.*, count(f.id) AS cards
FROM cfg
LEFT JOIN flashcards f USING (subject, exam_board, level, topic_id)
GROUP BY 1, 2, 3, 4
HAVING count(f.id) < 30
ORDER BY 1, 2, 3, 4;
