-- A-Level Biology Flashcards
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.

-- ===============================================================
-- EDEXCEL B A-LEVEL (9BI0)
-- ===============================================================

-- 1 — Biological Molecules
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'What happens in a condensation reaction and in a hydrolysis reaction?', 'Condensation joins two molecules with a new covalent bond and releases a molecule of water. Hydrolysis breaks a covalent bond by adding a molecule of water. Glycosidic, ester, peptide and phosphodiester bonds are all made by condensation and broken by hydrolysis.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How do α-glucose and β-glucose differ?', 'Both are hexoses with the formula C₆H₁₂O₆. The only difference is at carbon 1: in α-glucose the –OH points below the ring; in β-glucose it points above the ring. α-glucose builds starch and glycogen; β-glucose builds cellulose.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'Which monosaccharides make maltose, sucrose and lactose?', 'Maltose: glucose + glucose (α-1,4 glycosidic bond). Sucrose: glucose + fructose. Lactose: galactose + glucose. Each is formed by one condensation reaction that releases one water molecule.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'Compare starch and glycogen.', 'Both are insoluble α-glucose polymers with α-1,4 and α-1,6 glycosidic bonds, used as compact energy stores that do not affect water potential. Starch (amylose + amylopectin) is the plant store; glycogen is the animal store and is more highly branched, with more chain ends, so glucose can be released faster.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How does the structure of cellulose give it high tensile strength?', 'Straight, unbranched β-glucose chains (alternate units inverted) lie parallel. Their –OH groups form many hydrogen bonds between neighbouring chains, which group into microfibrils and fibres. The huge number of hydrogen bonds makes the cell wall strong.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How is a triglyceride formed?', 'One glycerol and three fatty acids join in three condensation reactions between glycerol –OH groups and fatty acid carboxyl groups. Three water molecules are released and three ester bonds form.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'Why are triglycerides a good energy store?', 'Their long hydrocarbon chains have many C–H bonds, so they release about twice as much energy per gram as carbohydrate. They are insoluble, so they do not affect water potential, and they are stored without water, making a light, compact store.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How are phospholipids suited to forming cell membranes?', 'The charged phosphate head is hydrophilic and the two fatty acid tails are hydrophobic. In water they form a bilayer with heads facing outwards and a hydrophobic core that blocks ions and polar molecules, making the membrane partially permeable. The molecules can move sideways, so the membrane is fluid.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'What bonds hold the tertiary structure of a protein?', 'Hydrogen bonds (weak but numerous, between polar R groups), ionic bonds (between oppositely charged R groups, sensitive to pH) and disulfide bonds (strong covalent S–S bonds between cysteine R groups). Hydrophobic R groups also cluster together away from water.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How is the structure of collagen related to its function?', 'Three polypeptide chains form a triple helix held by many hydrogen bonds. Glycine at every third position lets the chains pack tightly. Covalent cross-links join staggered molecules into fibrils and fibres with no weak points, giving high tensile strength in tendons, skin and artery walls.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How is the structure of haemoglobin related to its function?', 'A globular protein of four chains (two α, two β), each with a haem group containing Fe²⁺ that binds one O₂. Hydrophilic R groups face outwards, making it soluble. Binding of one O₂ changes the shape so more bind easily (cooperative binding).', 11, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'Describe semi-conservative DNA replication.', 'DNA helicase breaks the hydrogen bonds between bases and the strands separate. Free nucleotides pair with complementary bases on each template. DNA polymerase joins them with phosphodiester bonds; DNA ligase joins short sections. Each new molecule has one old and one new strand.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How do mRNA and tRNA differ in structure?', 'mRNA is a single, largely linear strand carrying codons from the nucleus to the ribosome. tRNA is a short single strand folded into a clover-leaf shape held by hydrogen bonds between bases in the same strand, with an anticodon at one end and an amino acid attachment site at the other.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'What are the main features of the genetic code?', 'Triplet: three bases (a codon) code for one amino acid, giving 64 codons. Start codon AUG; stop codons UAA, UAG and UGA. Degenerate: most amino acids have more than one codon. Non-overlapping: each base is read in only one triplet. Much of the genome does not code for proteins.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'How does a single substitution cause sickle cell anaemia?', 'In the β-globin gene, GAG becomes GTG (mRNA GUG), so glutamic acid at position 6 becomes valine. Valine''s non-polar R group forms a hydrophobic patch, so at low oxygen haemoglobin molecules stick into fibres, making red blood cells rigid and sickle-shaped.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'What is the induced fit hypothesis?', 'The active site is not a rigid, exact match for the substrate. When a complementary substrate binds, the active site changes shape slightly to mould around it, straining substrate bonds and lowering the activation energy. After the products are released, the active site returns to its original shape.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'Compare competitive and non-competitive inhibition.', 'Competitive: inhibitor resembles the substrate and binds the active site; more substrate reduces the inhibition. Non-competitive: inhibitor binds an allosteric site and changes the active site''s shape; more substrate has no effect and the maximum rate is lowered.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '1', 'Biological Molecules', 'Why do plants need nitrate, calcium, magnesium and phosphate ions?', 'Nitrate: nitrogen to make amino acids and the bases of DNA. Calcium: calcium pectate in the middle lamella that holds cells together. Magnesium: to make chlorophyll. Phosphate: to make ADP and ATP.', 18, 'alevel');

-- 2 — Cells, Viruses and Reproduction of Living Things
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'What does cell theory state?', 'All living organisms are made of one or more cells; the cell is the basic unit of structure, function and organisation; new cells arise only by division of existing cells. Viruses are not cells, so they sit outside cell theory.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'List the main structures of a prokaryotic cell.', 'Peptidoglycan cell wall, cell surface membrane, cytoplasm with 70S ribosomes, circular DNA in a nucleoid (no membrane, no histones) and plasmids. Some species also have a capsule, flagella and pili. There are no membrane-bound organelles.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'How does the Gram stain distinguish bacteria?', 'Crystal violet and iodine form a complex; alcohol washes it out of Gram negative cells (thin peptidoglycan plus outer membrane), which then take up red safranin and look pink. Gram positive cells keep the complex in their thick peptidoglycan and look purple.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Why is penicillin less effective against Gram negative bacteria?', 'Penicillin stops peptidoglycan cross-links forming, so growing cells burst by osmotic lysis. In Gram negative bacteria the outer membrane (with lipopolysaccharide) keeps penicillin away from the thin peptidoglycan layer.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Give the functions of the nucleolus, RER, SER and Golgi apparatus.', 'Nucleolus: makes rRNA and assembles ribosome subunits. RER: proteins made on its ribosomes are folded and transported. SER: makes lipids, including phospholipids and steroids. Golgi: modifies proteins (e.g. adds carbohydrate), packages them into vesicles, makes lysosomes.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Give the functions of lysosomes, centrioles and the tonoplast.', 'Lysosomes: single-membrane vesicles of hydrolytic enzymes that digest engulfed material and worn-out organelles. Centrioles: organise spindle fibres in animal cells. Tonoplast: partially permeable membrane controlling movement into and out of the vacuole.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Magnification and resolution: definitions and formula', 'Magnification = image size ÷ actual size. Resolution = the smallest distance between two points that can still be seen as separate. Light microscope resolution is about 200 nm; TEM about 0.5 nm, because electrons have a much shorter wavelength than light. 1 mm = 1000 μm; 1 μm = 1000 nm.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'How is an eyepiece graticule calibrated?', 'Line up the graticule with a stage micrometer of known divisions (e.g. 10 μm). Find how many eyepiece divisions match a known length, then divide. Example: 25 divisions = 100 μm, so 1 division = 4 μm. Recalibrate for every objective lens.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Name the nucleic acid and structure of the four example viruses.', 'λ phage: dsDNA, head and tail, infects E. coli. Tobacco mosaic virus: ssRNA, helical rod, no envelope. Ebola: ssRNA, filamentous, enveloped. HIV: ssRNA retrovirus with reverse transcriptase, enveloped, infects helper T cells.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Lytic cycle vs latency', 'Lytic: attachment to receptors, entry of nucleic acid, host machinery copies the genome and makes viral proteins, assembly, then lysis releases new viruses. Latency: the viral genome stays in the host (prophage in λ, provirus in HIV) with no new viruses made, until a trigger starts the lytic cycle.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Why can antibiotics not treat viruses, and how do antivirals work?', 'Viruses are not cells: no cell wall, no 70S ribosomes and no metabolism for antibiotics to target. Antivirals must inhibit replication by blocking a step unique to the virus, e.g. reverse transcriptase or protease inhibitors for HIV.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'How was the spread of Ebola controlled in 2014?', 'Isolation of patients and quarantine of contacts; contact tracing for the 21-day incubation period; protective equipment and decontamination for health workers; safe burial teams; public education and screening of travellers. Prevention was the focus because in 2014 no licensed drug or vaccine existed; the Ervebo vaccine was licensed in 2019 and monoclonal antibody treatments in 2020.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Stages of the cell cycle and what happens to DNA', 'Interphase: G1 (growth), S (DNA replicated, each chromosome becomes two sister chromatids), G2 (growth, preparation). Then mitosis and cytokinesis. DNA content doubles in S phase and is halved again by mitosis; chromosome number stays 2n.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Stages of mitosis', 'Prophase: chromosomes condense, nuclear envelope breaks down, spindle forms. Metaphase: chromosomes line up singly at the equator. Anaphase: centromeres divide, chromatids pulled to poles. Telophase: nuclear envelopes reform. Cytokinesis: cleavage furrow (animals) or cell plate (plants).', 14, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'How does meiosis produce genetic variation?', 'Crossing over in prophase I: non-sister chromatids exchange sections at chiasmata, giving new allele combinations. Independent assortment in metaphase I: homologous pairs orient randomly, giving 2ⁿ combinations (2²³ ≈ 8.4 million in humans). Random fertilisation adds more.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Non-disjunction: Down''s and Turner''s syndromes', 'Non-disjunction is failure of homologous chromosomes (anaphase I) or sister chromatids (anaphase II) to separate, giving n + 1 and n − 1 gametes. Down''s syndrome: trisomy 21 (47 chromosomes, polysomy). Turner''s syndrome: 45,X (monosomy).', 16, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Events of fertilisation in mammals, in order', 'Capacitation; sperm passes follicle cells; binds zona pellucida; acrosome reaction releases enzymes that digest the zona; sperm and oocyte membranes fuse; cortical reaction hardens the zona to stop polyspermy; oocyte completes meiosis II; haploid nuclei fuse to form a diploid zygote.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '2', 'Cells, Viruses and Reproduction of Living Things', 'Pollen tube growth and double fertilisation', 'Pollen germinates on the stigma; the tube grows down the style, secreting digestive enzymes, controlled by the tube nucleus. The generative nucleus divides by mitosis into two male nuclei. One fuses with the egg (diploid zygote); the other fuses with two polar nuclei (triploid endosperm).', 18, 'alevel');

-- 3 — Classification and Biodiversity
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What are the eight taxonomic ranks, from largest to smallest?', 'Domain, kingdom, phylum, class, order, family, genus, species. Each rank is nested inside the one above; moving down, groups contain fewer organisms that share more features and a more recent common ancestor.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'How is a binomial name written?', 'Genus name with a capital letter, then specific name in lower case, e.g. Homo sapiens. Italicised when printed, underlined when handwritten. Everyone worldwide uses the same name for the same species.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What is the biological definition of a species?', 'A group of organisms with similar features that can interbreed in natural conditions to produce fertile offspring. Horses and donkeys are separate species because their offspring (mules) are almost always sterile.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What are the main limitations of the biological species definition?', 'It cannot be applied to asexual organisms or fossils; geographically separated populations never meet, so interbreeding cannot be tested; some separate species form fertile hybrids (e.g. wolves and coyotes); ring species have no clear dividing line; ''similar features'' is vague.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'Why is it often hard to assign organisms to a species?', 'Speciation is gradual; variation within a species; cryptic species look alike but are genetically distinct (e.g. savanna and forest elephants); convergent evolution makes unrelated organisms look similar; few specimens; most microbes cannot be cultured; taxonomists disagree.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'How does gel electrophoresis separate DNA fragments?', 'DNA is cut with restriction enzymes and loaded into wells in agarose gel. A voltage is applied; the negatively charged phosphate groups make DNA move towards the anode (+). Smaller fragments move further. A ladder estimates sizes; stain or dye shows the bands.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'How can electrophoresis banding patterns show relationships?', 'Samples sharing more bands are likely to be more closely related; an unknown with the same bands as a known species is probably that species. Limitation: it compares fragment lengths only, so same-length fragments may differ in sequence.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'How do DNA sequencing and bioinformatics show evolutionary relationships?', 'The same gene is sequenced in each species; software aligns sequences and counts base differences. Mutations build up over time, so fewer differences means a more recent common ancestor. Results give phylogenetic trees and, with a constant rate, a molecular clock.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'Why use rRNA genes for distant groups but mitochondrial genes for close species?', 'rRNA genes are in every cellular organism and change slowly, so they suit very distant comparisons. Mitochondrial genes such as cytochrome oxidase I change faster, so they separate closely related species (DNA barcoding).', 9, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What do journals, peer review and conferences do for new evidence?', 'Journals publish methods and data so others can reproduce the work. Peer review: other experts check validity, conclusions and originality before publication (reduces flawed work, cannot prove conclusions true). Conferences: findings are presented, questioned and discussed.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What evidence supports the three-domain model?', 'Woese''s rRNA comparisons: archaea differ from bacteria as much as either does from eukaryotes. Archaea have branched ether-linked membrane lipids, no peptidoglycan, histones, eukaryote-like RNA polymerase, and are not inhibited by streptomycin.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What are the three domains and the five kingdoms?', 'Domains: Bacteria, Archaea, Eukarya. Kingdoms: Prokaryotae, Protoctista, Fungi, Plantae, Animalia. The five-kingdom model put all prokaryotes in one kingdom, which hides the large differences between bacteria and archaea.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'Outline how natural selection causes evolution.', 'Variation exists, partly genetic (new alleles by mutation). More offspring are produced than survive, so there is competition and selection pressure. Individuals with advantageous alleles survive and reproduce more, passing them on, so allele frequency increases over generations.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'What is a niche, and what are the three types of adaptation?', 'Niche: the role of a species in its habitat (food, predators, activity times, tolerated conditions). Anatomical: structure (marram grass rolled leaves). Physiological: body processes (kangaroo rat concentrated urine). Behavioural: actions (nocturnal activity).', 14, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'Compare allopatric and sympatric speciation.', 'Both need reproductive isolation so gene flow stops, then mutations, selection and drift change allele frequencies separately. Allopatric: geographical barrier (Galápagos finches). Sympatric: same area, e.g. polyploidy (Spartina anglica), ecological isolation (apple maggot flies), behaviour or timing.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'Why is there an evolutionary race between pathogens and medicines?', 'Each drug is a selection pressure. Resistant mutants already present survive and multiply, so resistance allele frequency rises (plasmids spread it between bacteria). Examples: MRSA, multidrug-resistant TB, HIV, chloroquine-resistant Plasmodium. New drugs must keep being developed.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'How is the index of diversity calculated and interpreted?', 'D = N(N − 1) / Σn(n − 1), where N = total organisms of all species and n = organisms of one species. Minimum 1 (one species); higher D means greater diversity. It accounts for both species richness and evenness. Genetic diversity = variety of alleles in the gene pool.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '3', 'Classification and Biodiversity', 'Compare zoos, seed banks and protected habitats.', 'Zoos (ex situ): captive breeding, studbooks, reintroduction; but small gene pools, lost wild skills. Seed banks (ex situ): dried, about −20 °C, cheap and compact; but some seeds cannot be stored and do not evolve. Protected habitats (in situ): whole ecosystem, natural behaviour; but hard to police, fragmented.', 18, 'alevel');

-- 4 — Exchange and Transport
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Why do larger organisms need specialised exchange surfaces and a mass transport system?', 'As size increases, volume rises faster than surface area, so SA:V falls. The body surface cannot supply enough O₂ for the volume of respiring tissue, and distances to inner cells are too long for diffusion. Exchange surfaces give a large area and short distance; mass transport carries substances in bulk between them and the tissues, keeping gradients steep.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Describe the fluid mosaic model of the cell surface membrane.', 'A phospholipid bilayer: hydrophilic heads face outwards, hydrophobic tails inwards. Fluid: phospholipids and many proteins move sideways. Mosaic: proteins scattered through it, including channel and carrier proteins that span the bilayer and extrinsic proteins on one surface. Glycoproteins and glycolipids act as receptors and recognition sites; cholesterol regulates fluidity.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Compare diffusion, facilitated diffusion, osmosis and active transport.', 'Diffusion: passive, down a concentration gradient, through the bilayer (small non-polar molecules). Facilitated diffusion: passive, down a gradient, through channel or carrier proteins (ions, glucose). Osmosis: passive net movement of water from higher to lower water potential through a partially permeable membrane. Active transport: against a gradient, via carrier proteins, using ATP.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'How do size, solubility and charge affect how a molecule crosses a membrane?', 'Small, non-polar or lipid-soluble (O₂, CO₂, steroids): simple diffusion through the bilayer. Small polar (water): slowly through the bilayer, fast through aquaporins. Ions: repelled by the hydrophobic core, so need channels or carriers. Larger polar molecules (glucose, amino acids): carrier proteins. Very large molecules and particles: vesicles (endocytosis, exocytosis).', 4, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'What is the equation for water potential, and how is it used?', 'ψ = P + π. Turgor pressure (P) is usually positive in a turgid plant cell and zero in a flaccid one; osmotic potential (π) is zero for pure water and negative for solutions. Example: P = 250 kPa, π = −600 kPa gives ψ = −350 kPa. Water moves from the higher (less negative) to the lower water potential.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Explain the role of ATP in active transport.', 'The ion or molecule binds to a carrier protein. ATP is hydrolysed to ADP + Pi, releasing energy; the phosphate attaches to the carrier, which changes shape and releases the substance on the other side, against its gradient. Energy is needed to phosphorylate ADP back to ATP, using energy from respiration. Example: the Na⁺/K⁺ pump moves 3 Na⁺ out and 2 K⁺ in per ATP.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'How are fish gills adapted for gas exchange?', 'Many gill filaments covered in lamellae give a large surface area. Thin lamella epithelium and dense capillaries give a short diffusion distance. Water is pumped over the gills in one direction. Countercurrent flow: blood flows opposite to the water, so it always meets water with more O₂ and a gradient is kept along the whole lamella (up to about 80% of O₂ extracted).', 7, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'How is the insect tracheal system adapted for gas exchange?', 'Air enters through spiracles, which can close to reduce water loss. Tracheae, held open by chitin rings, branch into fine tracheoles that reach individual respiring cells, so O₂ diffuses straight in and no blood transport is needed. In intense activity, lactate draws fluid out of the tracheole ends by osmosis, so air reaches further. Larger insects ventilate by abdominal pumping.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'How does gas exchange happen in a flowering plant leaf and stem?', 'Gases diffuse through stomata (opened when guard cells take up K⁺ and water and become turgid) into air spaces in the spongy mesophyll, dissolving in the water on moist cell walls. In light, photosynthesis uses CO₂ faster than respiration makes it, so CO₂ enters and O₂ leaves; in the dark this reverses. Lenticels in bark let gases reach living tissue beneath the cork.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Describe the cardiac cycle and the valve movements.', 'Atrial systole: atria contract, pushing blood through the open AV valves. Ventricular systole: ventricular pressure exceeds atrial pressure, so AV valves close; when it exceeds arterial pressure, semilunar valves open and blood is ejected. Diastole: ventricles relax; semilunar valves close when ventricular pressure falls below arterial pressure, AV valves open when it falls below atrial pressure.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'How is the heartbeat initiated and coordinated?', 'Cardiac muscle is myogenic. The SAN in the right atrium sends out a wave of excitation across the atria (atrial systole). Non-conducting tissue blocks direct spread; the AVN delays the wave by about 0.1 s so the atria empty first. It passes down the bundle of His to the apex, then up the Purkinje fibres, so the ventricles contract from the apex upwards.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'What do the parts of a normal ECG show, and how is heart rate found?', 'P wave: atrial depolarisation. QRS complex: ventricular depolarisation (large because the ventricles have more muscle). T wave: ventricular repolarisation. Heart rate = 60 / R–R interval in seconds; an interval of 0.8 s gives 75 beats per minute.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Describe the sequence of events in blood clotting.', 'Damage exposes collagen; platelets stick to it and each other, forming a plug. Platelets and damaged tissue release clotting factors, including thromboplastin. Thromboplastin (with Ca²⁺) converts prothrombin into thrombin. Thrombin converts soluble fibrinogen into insoluble fibrin, which forms a mesh that traps platelets and red blood cells to form a clot.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Outline the stages of atherosclerosis and its effects on health.', 'Endothelium damaged (e.g. high blood pressure, smoking) → inflammatory response; white cells enter the wall → cholesterol from LDLs builds up beneath the endothelium → calcium salts and fibrous tissue form a hard plaque that narrows the lumen and reduces elasticity. Plaques can trigger a thrombus, causing angina, myocardial infarction, stroke or aneurysm.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Explain the shape of the oxygen dissociation curve and the Bohr effect.', 'Sigmoid because binding is cooperative: once the first O₂ binds, haemoglobin changes shape and more O₂ binds easily. Flat at high pO₂ (lungs, full loading); steep at the pO₂ of tissues, so a small fall releases a lot of O₂. Bohr effect: more CO₂ forms H⁺, which lowers affinity and shifts the curve right, so more O₂ is unloaded in active tissues.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Compare haemoglobin, myoglobin and fetal haemoglobin.', 'Haemoglobin: four chains and four haem groups, cooperative binding, sigmoid curve, Bohr effect; transports O₂ in red blood cells. Myoglobin: one chain and one haem, hyperbolic curve far to the left; stores O₂ in muscle and releases it at very low pO₂. Fetal haemoglobin: higher affinity than adult (curve to the left), so it loads O₂ at the low pO₂ of the placenta.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'How is tissue fluid formed, reabsorbed and drained?', 'Arterial end: hydrostatic pressure > oncotic pressure, so water and small solutes are forced out through gaps in the capillary wall (proteins stay in). Hydrostatic pressure falls along the capillary. Venous end: oncotic pressure > hydrostatic pressure, so water returns by osmosis. Excess fluid drains into lymph capillaries as lymph and returns to the blood in veins near the heart.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '4', 'Exchange and Transport', 'Compare the structure of xylem vessels and phloem sieve tubes.', 'Xylem: dead, no cytoplasm, no end walls (continuous tube), lignified walls with pits; carries water and ions upwards, passively. Phloem: living sieve tube elements with little cytoplasm and no nucleus, sieve plates, cellulose walls, and companion cells rich in mitochondria for active loading; carries sucrose and amino acids from sources to sinks, up or down.', 18, 'alevel');

-- 5 — Energy for Biological Processes
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Why does respiration release heat as well as producing ATP?', 'Respiration is not fully efficient: only part of the chemical energy in the respiratory substrate is transferred to ATP. The rest is released as heat, which endotherms use to keep their body temperature high and stable.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'List the four stages of aerobic respiration and where each happens.', 'Glycolysis: cytoplasm. Link reaction: mitochondrial matrix. Krebs cycle: mitochondrial matrix. Oxidative phosphorylation: inner mitochondrial membrane (cristae).', 2, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Summarise glycolysis.', 'Hexose is phosphorylated by 2 ATP, then split into two triose phosphates. Each is oxidised (NAD → reduced NAD) and converted to GP, then to pyruvate. 4 ATP made by substrate-level phosphorylation, so net 2 ATP, 2 reduced NAD and 2 pyruvate per glucose.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'What happens in the link reaction?', 'In the matrix, pyruvate (3C) is decarboxylated (CO₂ released) and oxidised (NAD reduced). The 2C acetyl group joins coenzyme A to form acetyl CoA. No ATP is made. It happens twice per glucose.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'What does one turn of the Krebs cycle produce?', 'The acetyl group (2C) joins a 4C compound to make 6C, which is broken back down to 4C. Per turn: 2 CO₂, 3 reduced NAD, 1 reduced FAD and 1 ATP (substrate-level). Two turns per glucose.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Explain chemiosmosis in mitochondria.', 'Electrons from reduced NAD/FAD pass along carriers in the inner membrane, releasing energy that pumps H⁺ from the matrix into the intermembrane space. H⁺ diffuses back through ATP synthase, which makes ATP from ADP + Pi.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'What is the role of oxygen in aerobic respiration?', 'Oxygen is the terminal electron acceptor. It combines with electrons and protons to form water (½O₂ + 2H⁺ + 2e⁻ → H₂O). Without it the chain stops, NAD is not regenerated, and the link reaction and Krebs cycle stop too.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'How do mitochondrial membranes help ATP synthesis?', 'Inner membrane is impermeable to H⁺ except via ATP synthase, so a gradient can form. Cristae give a large area for ETCs and ATP synthase. Small intermembrane space gives a steep gradient quickly. Inner membrane also has carrier proteins that move pyruvate, ADP and ATP between the cytoplasm side and the matrix.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Compare the ATP yield of aerobic and anaerobic respiration.', 'Aerobic: about 30 to 32 ATP per hexose (38 often quoted as a theoretical maximum). Anaerobic: net 2 ATP, from glycolysis only. Anaerobically, pyruvate is not oxidised further, so most energy stays in lactate or ethanol.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'How does lactate affect muscle contraction?', 'Pyruvate + reduced NAD → lactate + NAD lets glycolysis continue. Lactate and H⁺ lower the pH, affecting enzymes for respiration and contraction, so force falls and fatigue sets in. Lactate is later converted back to pyruvate in the liver.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'How is ethanol formed in plant cells without oxygen?', 'Pyruvate → ethanal + CO₂ (decarboxylation). Ethanal + reduced NAD → ethanol + NAD. Ethanal is the hydrogen acceptor, NAD is regenerated for glycolysis, and the pathway is irreversible because CO₂ is lost.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'CP9: how does a respirometer measure respiration rate?', 'Organisms are sealed with soda lime, which absorbs CO₂, so O₂ uptake moves a liquid along a capillary. Volume = πr²l; divide by time (and mass). A control of glass beads corrects for temperature and pressure changes. Handle animals humanely.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Absorption spectrum vs action spectrum', 'Absorption spectrum: light absorbed by pigment(s) at each wavelength. Action spectrum: rate of photosynthesis at each wavelength. They match closely, showing that absorbed light drives photosynthesis. Peaks are in blue-violet and red; the trough is in green.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Why do plants have several photosynthetic pigments?', 'Chlorophyll a (reaction centre), chlorophyll b, carotene and xanthophylls each absorb different wavelengths. Together they absorb a wider range and pass energy to chlorophyll a, raising the rate in low or filtered light. Carotenoids also protect against excess light.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'CP11: how is an Rf value calculated?', 'Rf = distance moved by pigment spot ÷ distance moved by solvent front, both measured from the pencil origin line to the spot centre. It has no units and lies between 0 and 1. Carotene usually moves furthest; chlorophyll b least.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Describe the structure of a chloroplast.', 'Envelope: double membrane. Stroma: fluid with Calvin cycle enzymes (RUBISCO), starch grains, DNA and ribosomes. Thylakoids: membrane sacs stacked into grana. Lamellae: thylakoid membranes linking grana.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Cyclic vs non-cyclic photophosphorylation', 'Non-cyclic: PSII and PSI; electrons from water (photolysis) end on NADP; makes ATP, reduced NADP and O₂. Cyclic: PSI only; electrons return to PSI; makes ATP only. Both use electron carriers and chemiosmosis.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '5', 'Energy for Biological Processes', 'Outline the Calvin cycle and the uses of GALP.', 'In the stroma, RUBISCO fixes CO₂ with RuBP (5C) to give 2 GP (3C). GP is reduced to GALP using reduced NADP and ATP. 5 of every 6 GALP regenerate RuBP (using ATP). GALP makes hexoses, lipids, amino acids (with nitrate) and more.', 18, 'alevel');

-- 6 — Microbiology and Pathogens
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'What is aseptic technique, and what are its two purposes?', 'Working practices that prevent unwanted microorganisms contaminating a culture, and prevent the cultured microorganisms escaping to infect the worker or the environment. Examples: disinfect the bench, work near a Bunsen flame, sterilise media in an autoclave, flame the loop and bottle necks, open lids as little as possible.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Total count versus viable count: which growth-measuring methods give each?', 'Total count (live and dead cells): haemocytometer cell count, mass (biomass), and turbidity measured with a colorimeter. Viable count (living cells only): dilution plating, where each colony is assumed to grow from one living cell.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'How is a viable count calculated from a dilution plate?', 'Cells per cm³ of original culture = number of colonies × dilution factor ÷ volume plated (cm³). Use a plate with about 30–300 separate colonies. Example: 47 colonies from 0.1 cm³ of the 10⁻⁵ dilution gives 47 × 10⁵ ÷ 0.1 = 4.7 × 10⁷ cells cm⁻³.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'What causes each phase of a bacterial growth curve?', 'Lag: cells adjust and synthesise enzymes, little division. Log: plentiful nutrients, low waste, cells double at a constant rate. Stationary: nutrients running low and waste building up, so division rate equals death rate. Death: nutrients exhausted and waste toxic, so deaths exceed new cells.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'How is the mean growth rate constant, k, calculated?', 'k = (log₁₀Nₜ − log₁₀N₀) ÷ (0.301 × t), using two points on the straight log phase. N₀ and Nₜ are cell numbers at the start and end, t is the time interval, 0.301 = log₁₀2. Units: generations per hour (h⁻¹). Mean generation time = 1 ÷ k. After n generations, N = N₀ × 2ⁿ.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'How does streak plating produce a pure culture?', 'Streak the mixed culture over one area of agar, flame and cool the loop, then drag from that area into a fresh one. Repeating this carries fewer cells each time, until cells in the last area grow into separate colonies. One colony, grown from a single cell, is transferred to fresh medium to give a pure culture.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Exotoxins versus endotoxins', 'Exotoxins: usually proteins, secreted by living bacteria, often specific and potent, usually destroyed by heat (e.g. Staphylococcus). Endotoxins: lipopolysaccharides in the outer membrane of Gram-negative bacteria, released mainly when the cells die, cause general effects such as fever, inflammation and shock, relatively heat-stable (e.g. Salmonella).', 7, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'How does Mycobacterium tuberculosis cause disease?', 'By invasion of host tissue. It is inhaled in droplets and engulfed by alveolar macrophages, but its thick waxy wall resists digestion, so it multiplies inside them. Infected areas are walled off in tubercles and may stay dormant. If immunity weakens (e.g. HIV, malnutrition) it destroys lung tissue, causing cavities, a cough, weight loss and fever.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Penicillin versus tetracycline', 'Penicillin is bactericidal: it inhibits the enzymes that cross-link peptidoglycan, so new wall is weak, water enters by osmosis and the growing cell bursts. Tetracycline is bacteriostatic: it binds the 30S subunit of 70S ribosomes, stopping tRNA binding and protein synthesis, so growth and division stop and the immune system clears the bacteria.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'How does antibiotic resistance spread in a bacterial population?', 'A random mutation (present before treatment) gives some cells resistance, e.g. a β-lactamase that breaks down penicillin. The antibiotic kills susceptible cells; resistant cells survive, divide and pass on the allele, so its frequency rises. Resistance genes on plasmids also pass between species by conjugation (horizontal transfer).', 10, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Stem rust (Puccinia graminis) on wheat: transmission, infection, effect', 'Transmission: wind-borne spores from pustules (also rain splash, clothing, machinery). Infection: on a wet surface a spore germinates and a hypha enters through a stoma; haustoria absorb sugars from cells. Effect: sugars diverted from grain, epidermis ruptured (more water loss), less photosynthesis, stems collapse, shrivelled grain.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Influenza virus: transmission, infection, effect', 'Transmission: droplets, aerosols, contaminated surfaces. Infection: haemagglutinin binds receptors on airway epithelial cells; the virus replicates inside and new particles bud out, released by neuraminidase. Effect: infected cells die, ciliated epithelium is lost so secondary bacterial pneumonia can follow; cytokines cause fever and aches.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Malaria (Plasmodium): transmission, infection, effect', 'Transmission: female Anopheles mosquito (the vector) injects parasites in saliva during a blood meal; also infected blood and mother to fetus. Infection: parasites multiply in liver cells, then in red blood cells, which burst. Effect: repeated fever and shivering, anaemia; with P. falciparum, blocked small vessels cause cerebral malaria and organ failure.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Outline the humoral immune response.', 'A macrophage presents antigen on MHC proteins. A T helper cell with a complementary receptor is activated and releases cytokines. A B cell with a complementary receptor is selected (clonal selection) and divides by mitosis (clonal expansion). Most clone cells become plasma cells that secrete specific antibodies; some become B memory cells.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Outline the cell-mediated immune response.', 'Infected body cells and antigen-presenting macrophages display antigen on MHC proteins. Activated T helper cells release cytokines that stimulate matching T killer cells to divide. T killer cells bind infected cells showing the antigen and release perforins, which make pores; enzymes enter and trigger apoptosis. Some T cells become memory cells.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Why is the secondary immune response faster and larger than the primary?', 'The primary response leaves many long-lived B and T memory cells, already specific to the antigen. On re-exposure there is no need to select from a few matching lymphocytes: memory B cells rapidly become plasma cells and memory T cells rapidly form T helper and T killer cells. Antibody concentration rises faster, higher and for longer.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'Natural/artificial, active/passive immunity: one example of each', 'Natural active: recovering from an infection. Artificial active: vaccination. Natural passive: antibodies crossing the placenta or in breast milk (colostrum). Artificial passive: injected antibodies, e.g. antitoxin after a snake bite. Active immunity is slow to develop but long-lasting (memory cells); passive is immediate but short-lived.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '6', 'Microbiology and Pathogens', 'What is herd immunity, and how is the threshold estimated?', 'When enough of a population is immune, an infected person is unlikely to meet a susceptible one, so transmission chains die out, protecting those who cannot be vaccinated. Threshold ≈ 1 − 1/R₀. Measles (R₀ about 12–18) needs about 92–94% immune, so about 95% vaccine coverage is the target; R₀ = 2 needs about 50%.', 18, 'alevel');

-- 7 — Modern Genetics
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'What is the genome?', 'All of the DNA in a cell or organism, including non-coding DNA such as introns, regulatory sequences and repeats. In humans only about 1–2% of the roughly 3.1 × 10⁹ base pairs codes for proteins.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'What happens at each stage of a PCR cycle?', 'Denaturation (about 95 °C): hydrogen bonds break and the strands separate. Annealing (about 50–65 °C): primers bind to either end of the target region. Extension (about 72 °C): Taq polymerase adds nucleotides to the primers. The number of copies ideally doubles each cycle: copies = starting copies × 2ⁿ.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'Why is Taq polymerase used in PCR?', 'It comes from Thermus aquaticus, a bacterium from hot springs, so it is heat-stable. It is not denatured at 95 °C and does not need to be added again each cycle.', 3, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How can gene sequencing link a mutation to a genetic condition?', 'The gene is amplified by PCR and sequenced, then compared with the reference sequence. Reading codons from the start codon predicts the amino acid sequence, showing how a mutation changes the protein, e.g. glutamic acid replaced by valine in sickle cell disease.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'What are short tandem repeats (STRs) and why are they used in DNA profiling?', 'Non-coding regions where a short sequence (often 2–5 bases) is repeated one after another. The number of repeats at each locus varies greatly between people, and each person has two alleles per locus, one from each parent.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How is a paternity test interpreted?', 'Match each band in the child to a band in the mother first. Every remaining band must be present in the biological father. A man lacking any remaining band is excluded; a man with all of them at many loci is very likely to be the father.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How do transcription factors regulate gene expression?', 'They are proteins that bind specific DNA sequences in promoters or enhancers. Activators help RNA polymerase bind, increasing transcription; repressors block it, decreasing transcription. Example: oestrogen binds a receptor and the complex acts as a transcription factor.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'What is alternative splicing?', 'Pre-mRNA is processed in different ways so different combinations of exons are kept in the mature mRNA. The mRNAs are translated into different polypeptides, so one gene can code for more than one protein. It happens in the nucleus, after transcription.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How do DNA methylation and histone acetylation affect transcription?', 'DNA methylation: methyl groups added to cytosine (often at CpG sites in promoters) usually silence the gene. Histone acetylation: reduces the histones'' positive charge so they hold DNA less tightly, chromatin loosens and transcription increases. Neither changes the base sequence.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How does non-coding RNA change gene expression?', 'miRNA and siRNA bind complementary sequences in target mRNA, causing it to be broken down or blocking translation. Long non-coding RNAs such as Xist coat one X chromosome in female mammals, making it condense and become inactive.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'Why is epigenetic modification important in differentiation?', 'All body cells have the same genes. Genes needed by a cell type stay accessible, while others are silenced by DNA methylation and histone deacetylation. The marks are copied during mitosis, so daughter cells stay the same cell type.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'Totipotent, pluripotent and multipotent: what is the difference?', 'Totipotent: any cell type including placenta; the zygote and early embryo cells. Pluripotent: any body cell but not placenta; inner cell mass of the blastocyst and iPS cells. Multipotent: a limited range of related cells, e.g. bone marrow stem cells forming blood cells.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How are iPS cells made, and why may they be less problematic than embryonic stem cells?', 'Genes for the transcription factors Oct4, Sox2, Klf4 and c-Myc are introduced into fibroblasts, reprogramming them to a pluripotent state. No embryo is destroyed, the donor can consent, and cells from the patient are not rejected. Risks remain: tumours, low efficiency.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'What roles do restriction endonucleases and DNA ligase play in making recombinant DNA?', 'Restriction endonucleases cut DNA at specific recognition sequences, often leaving sticky ends; the gene and vector are cut with the same enzyme so the ends are complementary. DNA ligase forms phosphodiester bonds to seal the sugar–phosphate backbones.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'Name four ways of getting recombinant DNA into cells.', 'Plasmids taken up by bacteria (transformation, e.g. calcium ions and heat shock). Modified viruses, e.g. bacteriophages or retroviruses. Agrobacterium tumefaciens and its Ti plasmid for dicot plants such as soya. Gene guns firing DNA-coated gold or tungsten particles, e.g. into cereals.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How does replica plating identify recombinant bacteria?', 'The plasmid has ampicillin and tetracycline resistance genes; the gene is inserted into the tetracycline gene, inactivating it. Grow on ampicillin, press a velvet pad on and transfer to tetracycline. Colonies missing from the tetracycline plate are recombinant; take them from the master plate.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'What is a knockout mouse and why is it a useful model?', 'A mouse with a specific gene made non-functional, compared with wild-type mice to reveal the gene''s role. Mice are mammals with similar genes, breed quickly and inbred strains are near-identical. Limits: results may not apply to humans, and some knockouts are lethal to embryos.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '7', 'Modern Genetics', 'How has soya been genetically modified?', 'Herbicide-tolerant soya has a bacterial EPSPS gene not inhibited by glyphosate, so weeds can be sprayed without harming the crop. High-oleic soya has FAD2 silenced, so its oil has more monounsaturated and less polyunsaturated fat; fewer C=C bonds means less oxidation and no need for hydrogenation.', 18, 'alevel');

-- 8 — Origins of Genetic Variation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'What is the only process that produces new alleles?', 'Mutation: a change in the base sequence of DNA. Meiosis and fertilisation only reshuffle alleles that already exist. Only mutations in cells that give rise to gametes are inherited.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'How does crossing over produce genetic variation?', 'In prophase I, homologous chromosomes pair as bivalents. Non-sister chromatids break and rejoin at chiasmata, exchanging equivalent sections. This produces recombinant chromatids with new combinations of alleles on the same chromosome.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'How does independent assortment produce genetic variation?', 'At metaphase I each bivalent lines up with a random orientation, independent of the others, so gametes get a random mix of maternal and paternal chromosomes. With n pairs there are 2ⁿ combinations (2²³ ≈ 8.4 million in humans).', 3, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'How does random fertilisation add to genetic variation?', 'Any male gamete can fuse with any female gamete, so which alleles combine in a zygote is a matter of chance. The number of possible zygotes is the product of the gamete types from each parent, so every individual (apart from identical twins) is unique.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Genotype and phenotype', 'Genotype: the alleles an organism carries for the gene(s) considered, e.g. Tt. Phenotype: the characteristics it shows, which result from its genotype interacting with its environment, e.g. a tall pea plant.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Explain codominance using the ABO blood groups.', 'Iᴬ and Iᴮ are codominant: both are expressed in IᴬIᴮ, giving group AB with A and B antigens. Both are dominant to Iᴼ. Group A = IᴬIᴬ or IᴬIᴼ; group B = IᴮIᴮ or IᴮIᴼ; group O = IᴼIᴼ.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'What are multiple alleles?', 'A gene with three or more alleles in a population, e.g. Iᴬ, Iᴮ and Iᴼ for the ABO gene. Each diploid individual still carries only two of them.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'What is a test cross and what does it show?', 'Crossing an individual with the dominant phenotype with a homozygous recessive. All dominant offspring means the parent was homozygous (TT); 1 : 1 dominant : recessive means it was heterozygous (Tt).', 8, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Ratios for two unlinked, non-interacting genes', 'AaBb × AaBb gives 9 : 3 : 3 : 1 (the two 3 : 1 ratios multiplied). AaBb × aabb (test cross) gives 1 : 1 : 1 : 1. Each gamete carries one allele of each gene, e.g. AB, Ab, aB, ab.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'What is autosomal linkage?', 'Two genes whose loci are on the same autosome. Their alleles tend to be inherited together, so they do not assort independently. A test cross gives two large parental classes and two small recombinant classes, from crossing over between the loci.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'How is recombination frequency calculated and interpreted?', 'Recombination frequency = recombinant offspring ÷ total offspring × 100. Below 50% shows the genes are linked; unlinked genes give 50%. The further apart the loci, the higher the frequency. E.g. Drosophila body colour and wing length: 391 ÷ 2300 × 100 = 17%.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Explain the sex linkage of haemophilia.', 'The recessive allele (Xʰ) is on the X chromosome, with no matching locus on the Y. Males (XY) are hemizygous, so XʰY is affected. Females need XʰXʰ; XᴴXʰ females are carriers. Sons get their X from their mother, so affected fathers cannot pass it to sons.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Carrier mother × unaffected father (XᴴXʰ × XᴴY): outcomes', 'Offspring: XᴴXᴴ, XᴴXʰ (carrier), XᴴY, XʰY (affected) in equal proportions. Probability a child is an affected son = 1/4. Probability a son is affected = 1/2. No daughters are affected; half are carriers.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Steps of a chi squared test on a genetic cross', '1) Null hypothesis: no significant difference between observed and expected. 2) Calculate expected numbers from the ratio. 3) χ² = Σ(O − E)² ÷ E using raw counts. 4) Degrees of freedom = categories − 1. 5) Compare with the critical value at p = 0.05: below it, accept the null hypothesis; equal to or above it, reject.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Stabilising versus disruptive selection', 'Stabilising: phenotypes near the mean favoured, extremes selected against; mean unchanged, spread (standard deviation) reduced; maintains continuity in a stable environment. Disruptive: both extremes favoured over intermediates; distribution becomes bimodal; can lead to reproductive isolation and speciation.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'What is genetic drift?', 'A change in allele frequencies caused by chance, not by an allele giving an advantage. The alleles passed on each generation are a random sample of the gene pool. It is strongest in small populations, can lose or fix alleles, and does not make a population better adapted.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'Population bottleneck versus founder effect', 'Both are forms of genetic drift that reduce genetic diversity by chance. Bottleneck: most of an existing population dies, e.g. hunting of the northern elephant seal. Founder effect: a few individuals start a new isolated population, e.g. high frequency of Ellis–van Creveld syndrome in the Old Order Amish.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '8', 'Origins of Genetic Variation', 'State the Hardy–Weinberg equations and conditions.', 'p + q = 1 (allele frequencies). p² + 2pq + q² = 1 (AA, Aa and aa genotype frequencies). Conditions: very large population, random mating, no selection, no mutation, no migration. A change in allele frequencies over time shows the population is evolving.', 18, 'alevel');

-- 9 — Control Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'What is homeostasis, and why is it described as a dynamic equilibrium?', 'Homeostasis is keeping the internal environment (e.g. temperature, pH, water potential) within narrow limits. It is dynamic because the variables are constantly disturbed and fluctuate slightly around a set point, with corrective mechanisms continually pulling them back.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Negative feedback vs positive feedback', 'Negative feedback: a change from the set point triggers a response that reverses it, so the stimulus and the response then decrease (e.g. ADH and plasma concentration). Positive feedback: the response amplifies the change until an outside event ends it (e.g. oxytocin in childbirth; Na⁺ entry opening more Na⁺ channels in an action potential).', 2, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Two modes of hormone action', 'Adrenaline (water-soluble) binds a surface receptor → adenylyl cyclase activated → ATP to cAMP (second messenger) → protein kinase A activates enzymes; fast and amplified. Oestrogen (lipid-soluble steroid) diffuses into the cell and binds a receptor that is a transcription factor → changes gene transcription; slower (hours).', 3, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Effects of auxin', 'Cell elongation in shoots (proton pumps lower wall pH, expansins loosen cellulose, cell stretches as it takes in water); apical dominance (suppresses lateral buds); promotes root formation, e.g. in cuttings. Roots are more sensitive: high concentrations that promote shoot growth inhibit root elongation.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How do auxin and cytokinin control lateral buds?', 'They act antagonistically. Auxin from the apical bud inhibits lateral buds; cytokinin from the roots (in the xylem) stimulates cell division and bud growth. The auxin:cytokinin ratio decides: high near the apex, so buds stay dormant; removing the apex shifts the balance to cytokinin, so buds grow.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How does gibberellin trigger starch breakdown in a germinating cereal grain?', 'The grain absorbs water and the embryo releases gibberellin. It diffuses to the aleurone layer, where it causes DELLA proteins to be broken down, so the amylase gene is transcribed. Amylase is secreted into the endosperm and hydrolyses starch to maltose for the embryo. CP14 measures this with clear zones on starch agar.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Phytochrome: the two forms and how they interconvert', 'Pr absorbs red light (about 660 nm) and becomes Pfr. Pfr absorbs far-red light (about 730 nm) and becomes Pr; in the dark Pfr slowly reverts to Pr. Daylight has more red than far-red, so Pfr builds up by day and falls at night. Pfr is the active form and alters gene expression.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Short-day vs long-day plants', 'Plants measure the uninterrupted dark period. Short-day plants flower when nights exceed a critical length: Pfr inhibits their flowering, so Pfr must fall low. Long-day plants flower when nights are short: Pfr promotes their flowering. A red flash mid-night prevents short-day flowering; far-red straight after cancels it.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How does an endotherm respond when its core temperature falls?', 'Thermoreceptors in the hypothalamus (and skin) detect the change; the heat gain centre acts via the autonomic nervous system. Skin arterioles constrict, so less blood flows near the surface; little sweat; hair erector muscles contract to trap air; shivering releases heat from respiration; metabolic rate rises. Behaviour: shelter, huddling, curling up.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Functions of the medulla oblongata, cerebellum, cerebrum and hypothalamus', 'Medulla oblongata: controls breathing and heart rate. Cerebellum: balance and coordination of movement. Cerebrum: initiates voluntary movement (also thought, memory, language). Hypothalamus: temperature regulation and osmoregulation.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How is the resting potential of about −70 mV set up?', 'Na⁺/K⁺ pumps move 3 Na⁺ out for every 2 K⁺ in, using ATP. At rest K⁺ channels are open and most Na⁺ channels closed, so K⁺ diffuses out, making the inside negative, until the electrical pull inward balances the concentration gradient. Large negative proteins stay inside.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Stages of an action potential', 'Stimulus opens voltage-gated Na⁺ channels; at threshold (about −55 mV) many more open (positive feedback) and the inside reaches about +40 mV. Na⁺ channels close and K⁺ channels open: repolarisation. K⁺ channels close slowly: hyperpolarisation. Pumps restore −70 mV. The refractory period makes impulses discrete and one-way.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Why is conduction faster in myelinated axons?', 'Myelin (from Schwann cells) insulates the axon, so depolarisation can occur only at the nodes of Ranvier, where Na⁺ channels are concentrated. Local currents flow from node to node and the action potential jumps between them (saltatory conduction). Fewer ions move, so less ATP is needed. Wider axons also conduct faster.', 13, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'Events at a cholinergic synapse', 'Action potential arrives → voltage-gated Ca²⁺ channels open, Ca²⁺ enters the knob → vesicles fuse and release ACh by exocytosis → ACh diffuses across the cleft and binds receptors → Na⁺ channels open, postsynaptic membrane depolarises (EPSP) → acetylcholinesterase hydrolyses ACh to choline and ethanoic acid, which are recycled.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How do nicotine, lidocaine and cobra venom act?', 'Nicotine mimics ACh: binds and opens ACh receptors and is not broken down by acetylcholinesterase, so stimulation lasts longer. Lidocaine blocks voltage-gated Na⁺ channels, so no action potentials form: local anaesthesia. Cobra venom blocks ACh receptors, so muscles cannot be stimulated: paralysis.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How does light on a rod lead to an impulse in the optic nerve?', 'Retinal changes from cis to trans and rhodopsin breaks down into opsin and retinal (bleaching). Na⁺ channels close, so the rod hyperpolarises and stops releasing glutamate, which was inhibiting the bipolar neurone. The bipolar neurone depolarises and triggers action potentials in a ganglion cell.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How is heart rate adjusted by the autonomic nervous system?', 'Baroreceptors (pressure) and chemoreceptors (CO₂, pH) in the aorta and carotid arteries send impulses to the cardiac centre in the medulla oblongata. Sympathetic nerve → noradrenaline at the SAN → faster. Parasympathetic (vagus) nerve → acetylcholine at the SAN → slower. Adrenaline from the adrenal medulla also raises heart rate.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '9', 'Control Systems', 'How does the loop of Henle act as a counter-current multiplier?', 'The ascending limb actively pumps Na⁺ and Cl⁻ into the medulla but is impermeable to water. The descending limb is permeable to water, which leaves by osmosis. Flow in opposite directions multiplies the effect, building a steep solute gradient. Water then leaves the collecting duct by osmosis (more when ADH is present). Longer loops, as in kangaroo rats, give steeper gradients.', 18, 'alevel');

-- 10 — Ecosystems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'What is an ecosystem, and how large can one be?', 'The community of organisms in an area together with its abiotic conditions and the interactions between them. Ecosystems range in size from a rock pool or rotting log to a lake, a forest or the whole biosphere; the boundaries are chosen by the investigator.', 1, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'What is a trophic level? Give the first four.', 'The feeding position of an organism, counted in energy-transfer steps from the producers. 1: producers; 2: primary consumers (herbivores); 3: secondary consumers; 4: tertiary consumers. An omnivore can occupy more than one level.', 2, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Pyramid of numbers: one advantage and one disadvantage.', 'Advantage: quick and easy to obtain by counting, with no organisms killed. Disadvantage: ignores size, so it can be inverted or distorted (one oak tree supporting thousands of caterpillars, or parasites).', 3, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Pyramid of dry biomass: advantages and disadvantages.', 'Advantages: allows for organism size; drying removes variable water content. Disadvantages: organisms must be killed and dried; shows standing crop at one time only; can be inverted (fast-reproducing phytoplankton); equal masses of tissue don''t contain equal energy.', 4, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Pyramid of energy: advantages and disadvantages.', 'Advantages: includes time and energy content of tissues; never inverted; allows fair comparison of ecosystems and transfer efficiencies. Disadvantages: hard to collect (a year''s biomass plus calorimetry); omnivores are hard to allocate to one level. Units: kJ m⁻² yr⁻¹.', 5, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Types of quadrat and what each is best for.', 'Frame quadrat: counts or cover in a square frame. Gridded quadrat: 100 squares, count those at least half covered for % cover. Point quadrat: row of pins lowered in turn, recording every plant touched; most objective for low, dense vegetation.', 6, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Line transect vs belt transect.', 'Both are used along an environmental gradient. Line transect: records organisms touching a tape (presence and position only). Belt transect: quadrats placed along the tape, continuously or at intervals, so abundance is recorded too; results can be drawn as a kite diagram.', 7, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Measures of abundance: when to use each.', 'Individual counts: organisms easy to tell apart (daisies, limpets). Percentage cover: grasses, mosses, where individuals can''t be separated. Frequency: % of quadrats containing the species. ACFOR (Abundant, Common, Frequent, Occasional, Rare): rapid but subjective surveys.', 8, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Formulae for estimating population size.', 'Quadrats: mean per quadrat × (site area ÷ quadrat area). Mark-release-recapture (Lincoln index): N = (M × n) ÷ m, where M = number marked, n = total in second sample, m = marked in second sample. Assumes marks are harmless, full mixing and no births, deaths or migration.', 9, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'When do you use a t-test, Spearman''s rank or chi-squared?', 't-test: compare the means of two samples of continuous, roughly normal data (df = n₁ + n₂ − 2). Spearman''s rank: test for correlation between two variables on the same samples (at least 5 pairs). Chi-squared: compare observed with expected frequencies in categories. Reject the null hypothesis if the value ≥ critical value at p = 0.05.', 10, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Spearman''s rank formula and how to interpret rs.', 'rs = 1 − (6Σd²) ÷ (n(n² − 1)). Rank both variables the same way, find d for each pair, square and sum. rs ranges from +1 (perfect positive) to −1 (perfect negative). A significant correlation does not show causation.', 11, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Define GPP and NPP.', 'GPP: rate at which producers convert light energy into chemical energy by photosynthesis, per unit area per unit time. NPP: rate at which energy is stored in new producer biomass after producer respiration is subtracted. NPP = GPP − R. NPP is the energy available to consumers and decomposers.', 12, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'How do you calculate the efficiency of energy transfer, and why is it low?', 'Efficiency (%) = energy transferred to higher level ÷ energy available at lower level × 100. Low because parts are not eaten, indigestible material is egested, energy is lost in urine, and much is released in respiration and lost as heat (especially in endotherms).', 13, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Stages of the nitrogen cycle and the bacteria involved.', 'Fixation: N₂ → NH₄⁺ (Rhizobium in legume nodules, Azotobacter), using nitrogenase. Ammonification: proteins and urea → NH₄⁺ (saprobionts). Nitrification: NH₄⁺ → NO₂⁻ (Nitrosomonas) → NO₃⁻ (Nitrobacter), needs oxygen. Denitrification: NO₃⁻ → N₂ in anaerobic, waterlogged soil.', 14, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Describe primary succession from bare rock.', 'Pioneers (lichens, mosses) colonise and weather rock; when they die, humus forms a thin soil. Grasses and ferns establish and outcompete them; soil deepens and holds more water and ions. Shrubs, then birch, then slower-growing trees follow. Climax: e.g. oak woodland in lowland Britain.', 15, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Climatic climax vs plagioclimax.', 'Climatic climax: set mainly by temperature and rainfall, e.g. tropical rainforest, temperate deciduous woodland, boreal forest, tundra. Plagioclimax: human activity stops succession early, e.g. grazing keeps chalk downland, burning keeps heather moorland. If management stops, succession resumes.', 16, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'Biotic and abiotic factors affecting population size.', 'Abiotic: temperature (enzyme activity), light (photosynthesis), water, soil pH and mineral ions, oxygen, wind, salinity. Biotic: intraspecific and interspecific competition, predation, disease, parasitism, food supply. Density-dependent factors (competition, predation, disease) have more effect as density rises; frost, flood and drought are density-independent.', 17, 'alevel'),
  ('Biology', 'Edexcel B', '10', 'Ecosystems', 'What is CITES, and what are its limitations?', 'An international agreement (1973, in force 1975) controlling cross-border trade in wild species. Appendix I: commercial trade banned; II: export permit needed; III: permits from the listing country. Limitations: controls only international trade, not habitat loss or local hunting; depends on national enforcement; illegal trade continues.', 18, 'alevel');

-- CP — Core Practicals
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP1: investigate a factor affecting the initial rate of an enzyme-controlled reaction.', 'E.g. temperature with amylase: amylase and 1% starch in separate tubes in a water bath (20-60°C), equilibrate 5 min. Mix, start the stopwatch; every 30 s put a drop on iodine on a spotting tile until it stays yellow-brown (no starch). 3 repeats. IV: temperature (or pH, enzyme, substrate or inhibitor concentration); DV: time to end-point; control volumes, concentrations, pH (buffer). Safety: iodine irritant and stains, gloves; care with hot water baths. Analysis: rate = 1/t (a mean rate estimating initial rate); bell-shaped curve, optimum ~37°C, denaturation above; Q₁₀ ≈ 2 below the optimum.', 1, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP2: use a light microscope with stage and eyepiece micrometers, and draw cells from a specialised tissue.', 'Fit the eyepiece graticule; focus on the stage micrometer; line up the scales. Length of 1 eyepiece unit = stage distance ÷ number of eyepiece units; calibrate for each objective. Replace with a specialised tissue slide (e.g. palisade mesophyll), focus on low power then high. Measure several cells in eyepiece units and convert to μm; draw 3-5 cells. Safety: handle slides carefully; never use direct sunlight. Analysis: actual size = units x calibrated value; magnification = image size ÷ actual size (1 mm = 1000 μm); mean size. Drawings: sharp pencil, no shading, ruled labels, title and magnification.', 2, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP3: prepare a temporary squash of a root tip to show the stages of mitosis.', 'Cut 5 mm garlic or onion root tips; 1 mol dm⁻³ HCl at 55-60°C for ~5 min (breaks down the middle lamella and stops division). Rinse, blot, keep only the terminal 1-2 mm (meristem). Add toluidine blue or acetic orcein, macerate, wait 2 min. Coverslip, filter paper, press firmly and vertically to give a single layer. Find the meristem on low power, identify stages on high power, count cells in each stage over several fields. Safety: HCl irritant, eye protection; stains, gloves. Analysis: mitotic index = cells in mitosis ÷ total cells; proportion in each stage reflects its relative duration.', 3, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP4: investigate the effect of sucrose concentration on pollen tube growth or germination.', 'Put a drop of each sucrose solution (e.g. 0-20%) in a labelled cavity slide. Brush pollen from ripe anthers thinly onto each drop; coverslip; keep in a humid chamber at constant temperature (e.g. 25°C). After 30-60 min count grains with a tube (50+ per slide) and measure tube lengths with a calibrated eyepiece graticule. IV: sucrose concentration; DV: % germination, tube length; control time, temperature. Safety: pollen allergies, avoid inhaling, wash hands. Analysis: % germination = grains with tube ÷ total x 100; best at intermediate concentration (respiratory substrate and water potential).', 4, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP5: investigate the effect of temperature on beetroot membrane permeability.', 'Cut uniform beetroot discs with a cork borer; rinse thoroughly until water runs clear. Place one disc per tube in 5 cm³ distilled water; incubate 20 min at each temperature (20-70°C). Remove beetroot; measure absorbance of the solution with a colorimeter; 3 repeats, means. IV: temperature; DV: absorbance; control disc size, water volume, time, beetroot source. Safety: cut on a tile away from the body; tongs for hot tubes. Analysis: plot mean absorbance vs temperature; sharp rise above ~40°C as membrane proteins denature and the phospholipid bilayer loses integrity, letting betacyanin diffuse out.', 5, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP6: determine the water potential of plant cells.', 'Cut equal potato cylinders with a cork borer from the same potato; blot and weigh each. Place one in each sucrose solution (0-1.0 mol dm⁻³) for 30-60 min; remove, blot the same way, reweigh. 3 repeats per concentration. IV: sucrose concentration; DV: % change in mass. Safety: sharp tools, cut on a white tile. Analysis: % change = (final − initial) ÷ initial x 100; plot against concentration; where the line crosses 0% is the isotonic point. Convert that concentration to water potential (kPa) using a table or graph. Use % change so different starting masses are comparable.', 6, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP7: dissect an insect to show the structure of the gas exchange system.', 'Use a humanely killed locust or cockroach from a supplier. Find spiracles along the thorax and abdomen with a hand lens. Pin dorsal side up; cut along the dorsal midline of the abdomen with scissor points up; pin back the body wall and cover with water or saline so air-filled tracheae show as silvery tubes. Trace tracheae inwards; mount a piece to see chitin rings and tracheoles under the microscope. Safety and ethics: sharp tools, count pins; locust allergies (gloves); fewest specimens, treat with respect. Analysis: draw and label; O₂ path spiracle to trachea to tracheole to cells by diffusion.', 7, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP8: investigate factors affecting water uptake by plant shoots using a potometer.', 'Cut the shoot underwater and assemble the potometer underwater to avoid air locks; seal joints with Vaseline; equilibrate 5 min. Introduce an air bubble and record distance moved per minute. Test conditions such as fan (wind), plastic bag (humidity), bright light, darkness; reset the bubble with the reservoir; 3 repeats. IV: environmental factor; DV: rate of bubble movement; control shoot, temperature and other factors. Safety: sharp tools; keep electrics away from water. Analysis: volume = πr² x distance; rate = volume ÷ time. Measures uptake, taken as approximately equal to transpiration.', 8, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP9: investigate factors affecting the rate of aerobic or anaerobic respiration using a respirometer.', 'Respirometer with germinating seeds and soda lime (separated by cotton wool); control with glass beads. Seal, water bath, equilibrate 5 min; record movement of a coloured fluid drop per minute for 10 min, at different temperatures. Anaerobic: yeast in glucose, no soda lime, collect CO₂ in a gas syringe. IV: temperature; DV: rate of drop movement. Safety: soda lime is corrosive, gloves and eye protection. Analysis: soda lime absorbs CO₂ so movement is O₂ uptake; rate = distance ÷ time; roughly doubles per 10°C up to an optimum; beads control for pressure changes.', 9, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP10: investigate the effects of different wavelengths of light on the rate of photosynthesis.', 'Pondweed (e.g. Elodea), cut end up, in NaHCO₃ solution; acclimatise. Place a coloured filter (red, blue, green) between the lamp and tube, with a heat shield. Check intensity with a light meter and adjust distance to equalise it. Collect gas over a fixed time in a photosynthometer and measure volume; 3 repeats; dark control. IV: wavelength (colour); DV: rate of gas production; control intensity, temperature, CO₂. Safety: keep lamps and cables away from water; lamps get hot. Analysis: highest in blue and red, lowest in green; compare with chlorophyll absorption spectra (action vs absorption spectrum).', 10, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP11: investigate the presence of different chloroplast pigments using chromatography.', 'Grind leaves with sand and a little propanone. Draw a pencil origin 1.5 cm from the bottom of the paper or TLC plate. Build up a small concentrated spot with a capillary tube, drying between applications. Stand in solvent, origin above the solvent level; close the container. Remove when the front nears the top, mark it immediately; measure each spot''s distance from the origin. Safety: propanone and solvents are highly flammable, no flames, ventilate. Analysis: Rf = spot distance ÷ solvent front distance; carotene moves furthest, then xanthophyll, chlorophyll a, chlorophyll b least.', 11, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP12: investigate the rate of growth of bacteria in liquid culture.', 'Aseptically add a fixed volume of non-pathogenic bacteria to sterile nutrient broth at constant temperature (e.g. 25°C). Sample aseptically every 30-60 min. Measure turbidity in a colorimeter (zeroed with sterile broth), or serially dilute, spread on agar, incubate and count plates with 30-300 colonies. Safety: aseptic technique, do not open plates after incubation, autoclave before disposal. Analysis: cells = colonies x dilution factor; plot log₁₀ cells vs time (lag, log, stationary, death); k = (log₁₀Nt − log₁₀N₀) ÷ (0.301 x t). Turbidity also counts dead cells.', 12, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP13: isolate individual species from a mixed culture of bacteria using streak plating.', 'Disinfect bench, work near a Bunsen. Flame the loop red hot and cool; flame the bottle neck, take a loopful of mixed culture (e.g. Micrococcus luteus and E. coli K-12). Streak across one edge (area 1); flame and cool the loop, turn 90°, drag from area 1 into area 2; repeat for areas 3 and 4. Tape lid with two strips, invert, incubate at 25°C for 48 h. Subculture one separate colony onto a fresh plate for a pure culture. Safety: aseptic technique, do not open after incubation, autoclave. Analysis: describe colonies; each isolated colony grew from one cell so is one species.', 13, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP14: investigate the effect of gibberellin on the production of amylase in germinating cereals using a starch agar assay.', 'Cut barley grains in half; keep the halves without the embryo (the natural source of gibberellin). Surface-sterilise in dilute bleach, rinse in sterile water. Soak in a range of gibberellic acid concentrations, or water (control). Place cut face down on starch agar with sterile forceps; tape, incubate at ~25°C for 24-48 h. Remove grains, flood with iodine, measure clear zones. IV: gibberellin concentration; DV: zone area. Safety: bleach irritant, eye protection; autoclave plates. Analysis: area = πr²; bigger zone = more amylase; gibberellin switches on amylase gene transcription in the aleurone layer.', 14, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP15: investigate the effect of different sampling methods on estimates of the size of a population.', 'Mark a study area (e.g. 10 m x 10 m) with two tapes at right angles; pick an easily counted species (e.g. daisies). Place quadrats at random coordinates and count individuals. Repeat varying quadrat size, number of quadrats, or random vs systematic placement; use a running mean for sample size; do a full count if possible. Mobile animals: mark-release-recapture. Safety and ethics: fieldwork risk assessment; harmless marks, return animals, avoid trampling. Analysis: estimate = mean per quadrat x (site area ÷ quadrat area); N = (M x n) ÷ m; compare with the true count and SD to judge accuracy and precision.', 15, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Outline CP16: investigate the effect of one abiotic factor on the distribution or morphology of one species.', 'Lay a transect across a gradient (e.g. stream bank to drier ground, canopy to open). Place quadrats at regular intervals (e.g. every 2 m); record abundance of the chosen species (percentage cover or count); measure the abiotic factor (e.g. soil moisture, light, pH, temperature) at each point, at the same time of day. Morphology version: measure a feature (e.g. leaf area of ivy) where the factor differs. Safety: fieldwork risk assessment, wash hands after soil. Analysis: kite diagram or bar chart; Spearman''s rank; the correlation is significant if rs exceeds the critical value at p ≤ 0.05.', 16, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Practical skills: how is an eyepiece graticule calibrated, and how is magnification calculated?', 'Line up the eyepiece graticule with a stage micrometer of known divisions (e.g. 10 μm). Count the eyepiece units that match a known stage distance; 1 eyepiece unit = stage distance ÷ number of units. The graticule has no units until calibrated, and must be recalibrated for each objective lens. Actual size = eyepiece units x calibrated value. Magnification = image size ÷ actual size, with both in the same units (1 mm = 1000 μm). Used in CP2 and CP4.', 17, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Practical skills: what is the difference between accuracy and precision, and what does standard deviation show?', 'Accuracy is how close a result is to the true value (e.g. a population estimate compared with a full count in CP15). Precision is how close repeat results are to each other. Standard deviation measures the spread of repeat values around the mean: a small SD means more precise data; overlapping mean ± SD ranges suggest a difference may not be significant. Improve both by random sampling, enough repeats (use a running mean to decide) and identical methods for every repeat.', 18, 'alevel'),
  ('Biology', 'Edexcel B', 'CP', 'Core Practicals', 'Practical skills: when is Spearman''s rank correlation used, and how is the result interpreted?', 'Use it to test for a correlation between two variables where one or both are ordinal or not normally distributed, e.g. species abundance vs an abiotic factor along a transect (CP16). Rank each data set, calculate rs, and compare with the critical value for the number of pairs at p ≤ 0.05. If rs exceeds the critical value, the correlation is significant (reject the null hypothesis of no correlation). rs near +1 or −1 is a strong positive or negative correlation. Correlation does not show cause.', 19, 'alevel');

