-- A-Level Biology Flashcards (AQA, Edexcel A, Edexcel B, OCR A, OCR B)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- EDEXCEL A (Salters-Nuffield) A-LEVEL
-- ===============================================================

-- T1 — Molecules, Transport and Health
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Describe how a condensation reaction forms a glycosidic bond.', 'OH groups on adjacent monosaccharides react; one H and one OH are lost as water (H2O). The resulting glycosidic bond is named by the carbon atoms it links, e.g. alpha-1,4 in maltose. Hydrolysis reverses it using water.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Compare the structure and function of starch and glycogen.', 'Both are alpha-glucose polymers; both are coiled, branched (1,4 and 1,6), insoluble (no osmotic effect), and compact storage molecules. Glycogen is more highly branched than starch -> faster hydrolysis to meet animal energy demands.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'How does the structure of cellulose adapt it for plant cell walls?', 'Beta-glucose polymers; alternating monomer orientation gives unbranched chains. Many H-bonds between chains form microfibrils, which assemble into macrofibrils. High tensile strength resists cell turgor pressure.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Distinguish saturated, monounsaturated and polyunsaturated fatty acids.', 'Saturated: no C=C double bonds, straight chain, solid at room T (animal fats). Monounsaturated: one C=C; polyunsaturated: 2+ C=C, kinked chains pack less well, so liquid (oils). Cis/trans isomerism affects packing and health implications.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Compare HDL and LDL.', 'LDL: low-density lipoprotein, transports cholesterol from liver to body tissues; high LDL deposits cholesterol in artery walls (atheromas). HDL: high-density lipoprotein, removes excess cholesterol from tissues to liver. High HDL : LDL ratio reduces CVD risk.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Describe the formation of an ester bond between glycerol and a fatty acid.', 'COOH of the fatty acid reacts with OH of glycerol. A condensation reaction releases water, forming an ester bond -O-CO-. Three condensations form a triglyceride (3 H2O). Hydrolysis (lipase) reverses this.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Describe the lock-and-key vs induced-fit models of enzyme action.', 'Lock-and-key: rigid active site complementary to substrate. Induced-fit: enzyme changes shape on binding, gripping the substrate and straining bonds, lowering Ea. Induced fit better explains how a single enzyme accommodates similar substrates and catalysis.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Describe the fluid-mosaic model of the cell membrane.', 'A bilayer of phospholipids (fluid) studded with proteins (mosaic): channel and carrier proteins, glycoproteins / glycolipids for cell signalling and recognition, cholesterol regulating fluidity. Hydrophilic heads outwards, hydrophobic tails inwards.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Compare diffusion, facilitated diffusion, osmosis and active transport.', 'Diffusion: passive, down a gradient, no protein. Facilitated diffusion: passive, via channel/carrier proteins. Osmosis: passive movement of water down a water-potential gradient. Active transport: ATP-driven against the gradient via carrier proteins.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Describe the cardiac cycle (~0.8 s).', 'Atrial systole: atria contract, AV valves open, ventricles fill (0.1 s). Ventricular systole: AV valves close (lub), ventricles contract, SL valves open, blood ejected (0.3 s). Diastole: SL valves close (dub), all chambers relax, atria refill (0.4 s).', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Outline the formation of an atheroma and its consequences.', 'Damage to endothelium (e.g. by high BP) -> inflammation, white blood cells and lipids accumulate in the artery wall, forming a plaque (atheroma). Narrows lumen, reduces elasticity, raises BP further; rupture causes thrombosis -> heart attack or stroke.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Describe the role of haemoglobin in O2 transport.', 'Quaternary protein with 4 haem groups, each binds one O2. Cooperative binding gives a sigmoidal dissociation curve. High pO2 in lungs -> loads; low pO2 in tissues -> unloads. Bohr shift: high CO2/H+ shifts curve right -> more O2 released.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Compare ventilation in fish and mammals.', 'Fish: water enters mouth, passes over gills (counter-current flow with blood) and out via operculum. Mammals: tidal ventilation by negative pressure (diaphragm and external intercostals contract for inhalation; passive recoil for exhalation).', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'Give the reagents and positive results for biochemical tests for biological molecules.', 'Reducing sugar: Benedict''s, blue -> brick red on heating. Non-reducing: hydrolyse first with HCl. Starch: iodine, yellow -> blue-black. Lipid: emulsion test, white emulsion. Protein: biuret reagent, blue -> purple.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T1', 'Molecules, Transport and Health', 'How can quantitative biochemical tests be performed?', 'Use a colorimeter and a calibration curve. Make a serial dilution of standard solutions, react with the test reagent, measure absorbance at the appropriate wavelength. Plot absorbance against concentration, then read unknown concentration from its absorbance.', 15, 'alevel');

-- T2 — Cells, Development and Biodiversity
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Describe the ultrastructure of a eukaryotic cell.', 'Plasma membrane, nucleus (envelope, pore, nucleolus, chromatin), mitochondria (cristae, matrix), RER (with ribosomes), SER, Golgi apparatus (cis/trans), lysosomes, ribosomes (80S), centrioles. Plant cells additionally have chloroplasts, large permanent vacuole, cell wall (cellulose).', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'How are proteins for export packaged and secreted?', 'mRNA is translated on RER ribosomes -> protein enters RER lumen, folded -> vesicles bud off RER -> Golgi modifies (e.g. glycosylation) -> packaged into secretory vesicles -> fuse with plasma membrane (exocytosis).', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Describe the stages of the cell cycle.', 'G1 (cell growth, organelle synthesis) -> S (DNA replication) -> G2 (further growth, error check) -> M (mitosis: PMAT) -> cytokinesis. Checkpoints (e.g. p53) prevent damaged cells progressing.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'List the differences between mitosis and meiosis.', 'Mitosis: 1 division, 2 diploid daughter cells, identical to parent, used for growth/repair. Meiosis: 2 divisions, 4 haploid daughter cells, genetically distinct (independent assortment, crossing over), used for gamete production.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Define a stem cell and outline the levels of potency.', 'A stem cell is undifferentiated and can divide repeatedly, giving rise to specialised cells. Totipotent: any cell type incl. extra-embryonic; pluripotent: any body cell; multipotent: limited types (e.g. blood); unipotent: one type.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'How does cell differentiation occur?', 'Cells differentiate by selective gene expression — only certain genes are transcribed and translated, depending on the cell''s position and signals. Transcription factors and epigenetic modifications control which genes are switched on.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Define biodiversity at three levels.', 'Habitat diversity: number of habitats in an area. Species diversity: richness (no. of species) and evenness (relative abundance). Genetic diversity: variety of alleles within a population.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Calculate Simpson''s index of diversity (D).', 'D = 1 - sum (n / N)^2, where n = no. of individuals of each species, N = total number. Higher D (close to 1) = more diverse and stable; lower D (close to 0) = a few dominant species.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Describe the eight taxonomic ranks and three domains.', 'Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species. Three domains: Bacteria, Archaea, Eukarya — based on molecular evidence (rRNA sequences, membrane lipids).', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'How does DNA / amino acid evidence improve classification?', 'Closely related species share more similar DNA / protein sequences. Direct sequence comparison gives quantitative phylogenetic data, distinguishes convergent evolution, and reveals relationships hidden by morphology.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'State Darwin''s theory of evolution by natural selection.', '1) Variation exists within a population. 2) More offspring are produced than survive (struggle for existence). 3) Individuals with advantageous alleles are more likely to survive and reproduce. 4) These alleles are passed on, increasing in frequency over generations.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Give two examples of natural selection in action.', 'Antibiotic resistance: random mutation -> survival of resistant bacteria -> fast spread (e.g. MRSA). Peppered moth: dark variants favoured during industrial pollution; light forms favoured after Clean Air Act.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Describe seed banks as a conservation strategy.', 'Seeds are stored at low temperature and humidity (e.g. Millennium Seed Bank), preserving genetic diversity ex situ. Cheaper than habitat conservation; allows re-introduction; useful for crop wild relatives. Limitations: only seed-bearing plants, viability declines over time, requires germination testing.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'Compare in situ and ex situ conservation.', 'In situ: protecting in original habitat (national parks, marine reserves) — preserves ecosystem interactions but vulnerable to disasters. Ex situ: away from the habitat (zoos, seed banks) — controlled, but smaller gene pool and risk of inbreeding.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T2', 'Cells, Development and Biodiversity', 'How are random samples used to assess biodiversity?', 'Use random number coordinates with quadrats / transects to avoid bias. Calculate species frequency, percentage cover and density. Sufficient sample size needed for representative results; combine with statistical tests to compare habitats.', 15, 'alevel');

-- T3 — Exchange, Transport and Reproduction
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Why do larger animals need specialised exchange surfaces?', 'Surface area : volume falls with size, so simple diffusion cannot meet metabolic needs. Specialised surfaces are large, thin, moist, well-supplied with blood, and ventilated to maintain steep gradients (Fick''s law).', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe gas exchange in mammalian alveoli.', 'Many small alveoli (large total SA ~70 m^2), squamous epithelium one cell thick (short diffusion path), surrounded by capillaries (steep gradient maintained by ventilation and circulation), thin film of fluid for dissolved gases, surfactant lowers surface tension.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe transpiration and the cohesion-tension theory.', 'Water evaporates from spongy mesophyll into the air spaces and out through stomata. This creates tension in the xylem; cohesion (H-bonds) keeps water as a continuous column, drawn upwards. Adhesion to xylem walls aids capillary action.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe xylem and phloem structure.', 'Xylem: dead, hollow, lignified tubes (vessels and tracheids); end walls perforated -> continuous tube; pits allow lateral water movement. Phloem: living sieve tube elements (no nucleus, sieve plates) and companion cells (mitochondria, ribosomes -> support sieve tubes via plasmodesmata).', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe how a potometer is used to investigate transpiration.', 'Cut shoot underwater, attach to a capillary tube full of water (no air bubble), seal joints with petroleum jelly. Allow to equilibrate, then measure rate of bubble movement (or mass loss) under varying T, light, humidity, wind.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Outline the mass-flow hypothesis of translocation.', 'Sucrose loaded into sieve tubes at the source by H+/sucrose co-transport (active). Water enters by osmosis, raising hydrostatic pressure. Sap flows down the pressure gradient to the sink, where sucrose is unloaded and used or stored.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Compare arteries, veins and capillaries.', 'Arteries: thick muscular and elastic walls, narrow lumen, carry blood at high pressure away from the heart. Veins: thin walls, wide lumen, valves prevent backflow at low pressure. Capillaries: one-cell-thick endothelium, very narrow, large total SA, sites of exchange.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe formation of tissue fluid.', 'At the arteriole end, hydrostatic pressure > oncotic pressure -> fluid (without proteins) is forced out. At the venule end, hydrostatic pressure has dropped while oncotic pressure (proteins remain) draws water back in. Excess returns via lymph.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Compare sexual and asexual reproduction.', 'Sexual: gametes fuse, offspring genetically variable (meiosis, fertilisation), beneficial in changing environments. Asexual: one parent, offspring identical, fast and energy-efficient, beneficial in stable environments. Many plants use both (vegetative propagation + flowers).', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe gametogenesis in mammals.', 'Spermatogenesis: in seminiferous tubules; spermatogonia divide by mitosis -> primary spermatocytes -> meiosis -> spermatids -> mature sperm. Oogenesis: oogonia in fetal ovary -> primary oocytes (meiosis I arrested at birth) -> resume per cycle, completing meiosis II only at fertilisation.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe fertilisation in mammals.', 'Acrosome reaction: enzymes from sperm head digest zona pellucida. Sperm membrane fuses with oocyte. Cortical reaction prevents polyspermy. Sperm nucleus enters; meiosis II completes; fusion of male and female pronuclei -> diploid zygote.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe the structure and function of the placenta.', 'Chorionic villi increase SA for exchange between maternal and fetal blood (which never mix). Glucose, amino acids, O2, antibodies cross to the fetus; CO2, urea, hormones cross from fetus to mother. The placenta also secretes hCG, oestrogen and progesterone.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Outline pollination and double fertilisation in flowering plants.', 'Pollen lands on stigma -> pollen tube grows down style. Two male nuclei pass down: one fuses with the egg -> diploid zygote (embryo); the other fuses with two polar nuclei -> triploid endosperm (food store). This is double fertilisation.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'Describe seed dispersal mechanisms.', 'Wind (e.g. dandelion, sycamore wings), water (coconut), animal (sticky burrs, edible fruits with hard seed coat), explosive (peas, geranium). Dispersal reduces competition with parent plant and colonises new habitats.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T3', 'Exchange, Transport and Reproduction', 'How does a xerophyte minimise water loss?', 'Thick waxy cuticle, sunken / hairy stomata (still air, raises humidity), rolled leaves, reduced leaf SA (spines), fewer stomata, deep roots, CAM photosynthesis (open stomata at night).', 15, 'alevel');

-- T4 — Energy, Environment and Microbiology
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Write the overall photosynthesis equation and identify oxidation/reduction.', '6CO2 + 6H2O -> C6H12O6 + 6O2. CO2 is reduced to glucose (gain of H, electrons); H2O is oxidised to O2. Light energy supplied via chlorophyll.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Outline the light-dependent reactions.', 'Photolysis at PSII: 2H2O -> 4H+ + 4e- + O2. Excited e- pass down ETC, pumping H+ into thylakoid lumen. Chemiosmosis: H+ drives ATP synthase. NADP+ + H+ + 2e- -> NADPH. Cyclic photophosphorylation produces only ATP.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Describe the Calvin cycle.', 'CO2 + RuBP (5C) -> 2 GP (3C) (catalysed by RuBisCO). GP reduced to TP using ATP and NADPH. Some TP forms glucose; most regenerates RuBP using ATP. Six turns yield one glucose.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'How do varying CO2, light and temperature affect photosynthesis?', 'Each acts as a limiting factor when in shortest supply. Low light: rate is light-limited. High light, low CO2: rate plateaus, CO2 limits. Below optimum T: enzymes slow. Above optimum: enzymes denature; rate drops sharply.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'List the four stages of aerobic respiration and their locations.', 'Glycolysis (cytoplasm), link reaction (mitochondrial matrix), Krebs cycle (matrix), oxidative phosphorylation / ETC (inner mitochondrial membrane).', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Describe the link reaction and Krebs cycle.', 'Link: pyruvate -> acetyl (2C) + CO2 + NADH; combined with CoA. Krebs: acetyl-CoA + 4C -> 6C; decarboxylation/dehydrogenation give 2 CO2, 3 NADH, 1 FADH2 and 1 ATP per turn (x2 per glucose).', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Explain how chemiosmosis generates ATP.', 'NADH/FADH2 deliver e- to the ETC, pumping H+ into the intermembrane space. The H+ gradient (proton motive force) drives H+ back into matrix through ATP synthase, phosphorylating ADP -> ATP. O2 is final e- acceptor (-> H2O).', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Compare anaerobic respiration in animals and yeast.', 'Animals: pyruvate + NADH -> lactate + NAD+. Reversible; lactate cleared in liver (oxygen debt). Yeast: pyruvate -> ethanal + CO2 -> ethanol + NAD+. Both regenerate NAD+ to allow glycolysis to continue without O2.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Define an ecosystem and describe energy flow in a food chain.', 'Ecosystem: biotic community + abiotic environment, interconnected by energy and nutrient cycles. Energy enters as light, captured by producers (NPP), then passes to herbivores and carnivores. Loss at each trophic level: respiration, heat, faeces -> typically ~10% transfer.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Define succession and describe primary succession.', 'Directional change in community over time. Primary: bare rock -> pioneer species (lichens) -> mosses -> herbs -> shrubs -> woodland (climax). Each stage modifies abiotic environment (soil, light) for the next.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Outline the carbon cycle.', 'Photosynthesis fixes CO2 into organic compounds. Respiration, combustion and decomposition return CO2 to the atmosphere. Carbon is stored in living biomass, soil, fossil fuels and oceans (HCO3-). Anthropogenic burning of fossil fuels increases atmospheric CO2.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Describe the role of saprobionts in decomposition.', 'Saprobionts (e.g. fungi, bacteria) secrete extracellular enzymes onto dead matter (extracellular digestion). Soluble products are absorbed. They release ammonium ions, beginning the nitrogen cycle, and CO2 by respiration.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Describe aseptic technique for culturing microorganisms.', 'Sterilise loop in a Bunsen flame, work near the flame to create an updraft, lift agar lid only briefly. Inoculate, replace lid, tape lightly (allow O2). Incubate at <25 °C in schools, sealed, to prevent pathogens. Autoclave waste.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'Compare batch and continuous fermentation.', 'Batch: nutrients added once, products accumulate; reactor cleaned between runs. Useful for secondary metabolites (penicillin). Continuous: nutrients added and product removed throughout; ideal for primary metabolites (e.g. enzymes), more efficient.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T4', 'Energy, Environment and Microbiology', 'How is bacterial growth measured and described mathematically?', 'Optical density (turbidity) or viable counts (serial dilution + colony count) per ml. Phases: lag, log (exponential), stationary, decline. Log: N = N0 x 2^n, where n is number of generations.', 15, 'alevel');

-- T5 — Genetics and Evolution
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe semi-conservative DNA replication.', 'Helicase unwinds the helix; H-bonds break. Free DNA nucleotides align with their complement on each parental template. DNA polymerase joins them by phosphodiester bonds (5''-3''). Each daughter molecule has one parental and one new strand. Meselson-Stahl confirmed this.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Outline transcription and post-transcriptional modification.', 'Gene unwinds; RNA polymerase joins free RNA nucleotides to a template strand (U replaces T). Pre-mRNA undergoes splicing in the nucleus: introns are removed; exons are joined. A 5'' cap and poly-A tail are added before mRNA leaves through nuclear pores.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe translation step by step.', 'mRNA binds the small ribosomal subunit; tRNA carrying methionine binds the start codon AUG. Next tRNA (anticodon complementary to next codon) binds; peptide bond forms. Ribosome translocates one codon along; first tRNA leaves. Continues to a stop codon.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Define silent, missense, nonsense, frameshift and large-scale mutations.', 'Silent: same amino acid (degenerate code). Missense: different amino acid. Nonsense: codon -> STOP, truncated protein. Frameshift: insertion/deletion shifts reading frame. Large-scale: duplication, inversion, translocation of chromosome regions.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe a monohybrid and a dihybrid cross.', 'Mono: Aa x Aa -> 3:1 dominant:recessive. Di: AaBb x AaBb -> 9:3:3:1 (assuming no linkage). Use Punnett squares to predict ratios; chi-squared tests if observed differs significantly from expected.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Explain codominance and incompatible blood groups.', 'In the ABO system: I^A and I^B alleles are codominant (both expressed in heterozygotes -> AB blood). I^O is recessive. Genotypes: I^A I^A or I^A I^O = A; I^B I^B or I^B I^O = B; I^A I^B = AB; I^O I^O = O.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe sex linkage with haemophilia.', 'Allele on X chromosome (X^h, recessive). Females need two X^h to be affected; one X^h makes a carrier. Males are hemizygous (X^h Y) -> affected. Hence haemophilia much more common in males.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Explain epistasis with Labrador coat colour.', 'B (black) is dominant to b (brown). Locus E controls deposition: E_ allows pigment, ee blocks it -> yellow regardless of B. Recessive epistasis: ee masks the B locus.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'State and apply the Hardy-Weinberg equations.', 'Allele frequencies p + q = 1 (where p = dominant, q = recessive). Genotype frequencies p^2 + 2pq + q^2 = 1. Assumes large population, random mating, no migration/mutation/selection. e.g. if q^2 = 0.04, q = 0.2, p = 0.8.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe directional, stabilising and disruptive selection.', 'Directional: extreme phenotype favoured (e.g. peppered moths in soot). Stabilising: intermediate favoured (e.g. human birth weight). Disruptive: both extremes favoured, often the precursor to speciation.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Compare allopatric and sympatric speciation.', 'Allopatric: geographical isolation -> different selection pressures and mutations -> reproductive isolation. Sympatric: arises in the same area (polyploidy in plants, behavioural / temporal isolation), without a physical barrier.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe the role of isolation mechanisms in speciation.', 'Pre-zygotic: behavioural, mechanical, temporal, gametic. Post-zygotic: hybrid inviability, hybrid sterility (e.g. mules). Once gene flow stops, allele frequencies diverge until interbreeding is no longer possible.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'How is artificial selection (selective breeding) applied?', 'Choose individuals with desired traits, breed them, select again from offspring; repeat over generations. Examples: high milk yield in dairy cattle, disease-resistant crops. Reduces genetic diversity -> vulnerable to disease and environmental change.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'Describe the use of statistical tests in genetics (chi-squared).', 'Used to compare observed and expected ratios in genetic crosses. chi^2 = sum ((O - E)^2 / E). Compare to critical value at appropriate degrees of freedom (categories - 1) at p = 0.05. If chi^2 > critical, deviation is significant.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T5', 'Genetics and Evolution', 'How do humans drive evolution (e.g. antibiotic resistance)?', 'Overuse / underuse of antibiotics imposes selection pressure on bacteria. Resistant mutants survive and reproduce, spreading resistance genes (sometimes via plasmids, horizontal transfer). Result: emergence of MRSA, multi-drug-resistant TB.', 15, 'alevel');

-- T6 — Immunity, Infection and Forensics
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Compare bacterial, viral, fungal and protoctist diseases with examples.', 'Bacterial: TB (M. tuberculosis). Viral: HIV. Fungal: athlete''s foot (Tinea pedis); plant — black sigatoka. Protoctist: malaria (Plasmodium). Each kills cells, releases toxins, or hijacks host machinery.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Outline non-specific (innate) defences.', 'Skin barrier; mucous membranes trap pathogens; lysozyme in tears/saliva; stomach acid; ciliated epithelia move mucus. Phagocytosis by neutrophils/macrophages. Inflammation: histamine -> vasodilation, increased permeability. Fever raises body T to inhibit pathogens.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Describe phagocytosis.', 'Phagocyte chemotaxes towards pathogen, recognises by receptors, engulfs by endocytosis -> phagosome. Lysosomes fuse with phagosome -> phagolysosome; hydrolytic enzymes (lysozyme) digest the pathogen. Antigens may be displayed on surface (APC).', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Compare T helper, T killer and B cells.', 'T helper: bind to antigens on APCs, release cytokines that stimulate B cells, T killer cells, and macrophages. T killer: directly kill infected/cancerous cells via perforin and granzymes. B cells: clonally selected, divide into plasma cells (antibodies) and memory cells.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Describe antibody structure and function.', 'Y-shape; two heavy + two light chains, constant and variable regions, two antigen-binding sites. Functions: agglutinate pathogens, opsonise (mark for phagocytosis), neutralise toxins, activate complement.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Compare primary and secondary immune responses.', 'Primary: slow lag (~5-10 days), low antibody peak; person may show symptoms; produces memory cells. Secondary: faster, larger antibody peak, may not cause symptoms — basis of long-term immunity.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Distinguish active, passive, natural and artificial immunity.', 'Active: own antibodies, memory long-lasting. Passive: given antibodies, no memory, short-term. Natural: through normal life (infection / mother''s milk). Artificial: vaccines (active) or antibody injection (passive, e.g. anti-tetanus).', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Outline how vaccines work and herd immunity.', 'Vaccines contain weakened/dead pathogens or antigens, triggering primary response and producing memory cells. On future infection, secondary response is rapid. Herd immunity: when enough of the population is vaccinated, pathogen cannot spread, protecting unvaccinated individuals.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'How does antibiotic resistance evolve?', 'Mutations giving resistance (e.g. modified target, beta-lactamase) arise randomly. Antibiotics select for resistant bacteria. Resistant mutants reproduce; resistance genes spread vertically and horizontally (plasmid conjugation). Misuse and incomplete courses accelerate this.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Describe how time of death is estimated.', 'Body temperature: ~1.5 °C drop per hour for 12 hours (algor mortis). Rigor mortis: stiffening from ~2 h, peaks at 12 h, fades by 36 h (Ca2+ accumulates, no ATP). Hypostasis (livor mortis): blood pooling, fixed by ~12 h. Insect succession on body. Stomach contents.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'How is time since death estimated using insects (forensic entomology)?', 'Different insect species colonise a body in succession (blowflies first, then beetles). Egg/larval/pupal stages have known development times at given temperatures, allowing investigators to estimate post-mortem interval.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Outline DNA profiling using STRs.', 'Extract DNA, amplify short tandem repeat (STR) regions by PCR, separate fragments by gel/capillary electrophoresis. Each individual has a near-unique combination of repeat lengths -> banding pattern. Used in identification, paternity testing, forensics.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Describe gel electrophoresis principles.', 'DNA fragments are loaded into wells in agarose; an electric field pulls negatively charged DNA towards the anode. Smaller fragments move further. Bands are visualised with UV after staining (e.g. ethidium bromide). Compared to a marker / reference ladder.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'Outline polymerase chain reaction (PCR).', 'Cycles of 95 °C (denature), ~55 °C (anneal primers), 72 °C (extend with Taq polymerase). Each cycle doubles the DNA: after n cycles, 2^n copies. Used in DNA profiling, diagnostics and gene cloning.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T6', 'Immunity, Infection and Forensics', 'How does HIV cause AIDS?', 'HIV is a retrovirus binding CD4 on T helper cells; reverse transcriptase makes DNA copy of viral RNA, integrating into host genome. After latency, virus replicates and destroys T helpers. Loss of immunity -> opportunistic infections (TB, pneumonia) and Kaposi''s sarcoma -> AIDS.', 15, 'alevel');

-- T7 — Homeostasis and Response
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Define homeostasis and explain why it is essential.', 'The maintenance of a stable internal environment within tolerance limits despite external change. Stable T, pH, blood glucose and water potential keep enzymes active and cells functional, allowing optimum metabolism.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe negative feedback with an example.', 'A change away from set point triggers a response that reverses it. e.g. blood glucose rises -> beta cells secrete insulin -> liver/muscle take up glucose, blood glucose falls. Distinct from positive feedback (amplifies change, e.g. oxytocin in childbirth).', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Distinguish CNS and PNS, somatic and autonomic.', 'CNS = brain + spinal cord. PNS = sensory + motor neurones outside CNS. Somatic = voluntary control of skeletal muscle. Autonomic = involuntary control of smooth muscle, cardiac muscle and glands; subdivided into sympathetic (fight/flight) and parasympathetic (rest/digest).', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Explain a resting potential.', 'Na+/K+ pump moves 3 Na+ out and 2 K+ in per ATP. K+ leak channels allow K+ to diffuse out, leaving the inside ~-70 mV relative to outside. Maintained by ATP and selective membrane permeability.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Sketch and label an action potential.', 'Stimulus opens voltage-gated Na+ channels (depolarisation, -70 -> +40 mV). Na+ channels close, K+ channels open (repolarisation). Hyperpolarisation as K+ overshoots; Na+/K+ pump restores resting potential. Refractory period prevents overlap.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe synaptic transmission at a cholinergic synapse.', 'AP arrives -> depolarisation opens Ca2+ channels in presynaptic membrane -> Ca2+ enters -> vesicles fuse with membrane and release ACh. ACh binds receptors on postsynaptic membrane, opening Na+ channels -> EPSP. Acetylcholinesterase removes ACh.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Compare temporal and spatial summation.', 'Temporal: one presynaptic neurone fires repeatedly so neurotransmitter accumulates -> threshold reached. Spatial: several presynaptic neurones release simultaneously -> threshold reached at a single postsynaptic neurone.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe how insulin reduces blood glucose.', 'Beta cells in islets of Langerhans detect rising blood glucose; insulin released. Activates tyrosine kinase receptors on liver/muscle/adipose cells -> more GLUT4 vesicles inserted -> increased glucose uptake; glycogenesis activated; lipogenesis stimulated.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Explain the second-messenger model of glucagon.', 'Alpha cells release glucagon when blood glucose falls. Glucagon binds receptor on liver -> activates G-protein -> adenylyl cyclase -> cAMP (second messenger) -> PKA -> phosphorylates glycogen phosphorylase -> glycogenolysis -> glucose released to blood.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Compare type 1 and type 2 diabetes.', 'Type 1: autoimmune destruction of beta cells (no insulin) -> insulin injections needed. Type 2: insulin resistance / reduced secretion; managed with diet, exercise, metformin. Type 2 risk factors: obesity, age, family history, inactivity.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe thermoregulation in mammals.', 'Hypothalamus monitors blood T. Too cold: vasoconstriction, shivering, hair erected (insulating layer), thyroxine release. Too hot: vasodilation, sweating, hair flattens. Behavioural responses (seek shade, change posture) supplement physiological control.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe ultrafiltration in the nephron.', 'Glomerulus: high BP forces small molecules through fenestrated capillaries, basement membrane (selective barrier) and slits between podocytes into Bowman''s capsule. Blood cells and large proteins remain in the blood.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe selective reabsorption in the proximal convoluted tubule.', 'Microvilli give large SA. Na+ pumped out into blood by Na+/K+ pumps; Na+ re-enters with glucose / amino acids by co-transport. Glucose then enters blood by facilitated diffusion. Water follows osmotically.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Explain the loop of Henle and counter-current multiplier.', 'Descending limb: permeable to water but not ions; water leaves into the medulla (which has low water potential). Ascending limb: impermeable to water; Na+/Cl- actively pumped out. Creates a salt gradient in the medulla allowing water reabsorption from the collecting duct.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Outline ADH control of water balance.', 'High blood solute concentration -> osmoreceptors in hypothalamus stimulate posterior pituitary to release ADH -> binds collecting duct receptors -> aquaporins inserted -> more water reabsorbed -> small volume of concentrated urine.', 15, 'alevel'),
  ('Biology', 'Edexcel A', 'T7', 'Homeostasis and Response', 'Describe the sliding filament theory of muscle contraction.', 'AP arrives at neuromuscular junction -> Ca2+ released from sarcoplasmic reticulum binds troponin, moving tropomyosin to expose binding sites on actin. Myosin heads bind actin -> power stroke (ADP/Pi released). New ATP binds, head detaches; ATP -> ADP+Pi resets head.', 16, 'alevel');

-- T8 — Gene Expression and Biotechnology
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Outline how transcription factors control gene expression.', 'TFs bind specific promoter / enhancer sequences and either recruit (activators) or block (repressors) RNA polymerase. They are made in response to internal/external signals, ensuring only relevant genes are transcribed in a given cell type.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Explain how oestrogen activates transcription.', 'Lipid-soluble oestrogen diffuses through the plasma membrane and binds an intracellular receptor (TF). The complex enters the nucleus, binds hormone response elements on DNA, and stimulates transcription of target genes.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Distinguish DNA methylation and histone modification (epigenetics).', 'DNA methylation: -CH3 added to cytosine (usually CpG islands), typically silences transcription. Histone acetylation: loosens DNA-histone binding -> easier transcription. Methylation of histones can either activate or silence depending on residue. Reversible and inheritable.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'How do siRNAs and miRNAs regulate gene expression?', 'Short non-coding RNAs base-pair with complementary mRNA. siRNA usually triggers cleavage by RISC; miRNA usually inhibits translation. Reduce protein production from a specific gene.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe how restriction enzymes cut DNA.', 'Restriction endonucleases recognise specific palindromic sequences (e.g. EcoRI: GAATTC) and cut, leaving sticky or blunt ends. Sticky ends are complementary single-stranded overhangs which allow fragments from different sources to be joined.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Outline gene cloning using a bacterial plasmid.', 'Cut gene and plasmid with the same restriction enzyme -> complementary sticky ends. DNA ligase joins gene into plasmid -> recombinant DNA. Plasmid taken up by host bacterium (CaCl2 + heat shock). Marker genes identify successful uptake.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe the polymerase chain reaction (PCR).', 'Cycles: 95 °C denature, ~55 °C anneal primers, 72 °C extend with Taq polymerase. Each cycle doubles DNA: 2^n copies after n cycles. Used in cloning, sequencing and DNA profiling.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe how to make recombinant insulin.', 'Reverse transcriptase converts insulin mRNA from human pancreas to cDNA. Sticky ends added (RE) and ligated into a plasmid vector. E. coli host transformed; selected with antibiotic-resistance markers. Bacteria cultured; insulin extracted and purified.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Compare somatic and germline gene therapy.', 'Somatic: alters body cells of an individual (e.g. CFTR delivered to lung cells in CF) — not heritable. Germline: alters egg/sperm/embryo so the change is passed on; banned in humans for ethical reasons.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Outline CRISPR-Cas9 gene editing.', 'A guide RNA matches the target DNA sequence; Cas9 nuclease cuts both strands. The cell repairs the break, either by error-prone NHEJ (knock-out) or by homology-directed repair using a donor template (precise edit).', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe DNA sequencing by Sanger / dideoxy method.', 'Mix template DNA, primer, polymerase, dNTPs and small amounts of fluorescently labelled ddNTPs. Each ddNTP terminates extension. Capillary electrophoresis separates fragments by size and detects the colour of the terminator -> read off the sequence.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Outline the use of GMOs in agriculture (Bt crops, golden rice).', 'Bt crops: contain a gene from Bacillus thuringiensis encoding an insecticidal toxin -> reduces pesticide use. Golden rice: engineered with vitamin A precursor (beta-carotene) genes to combat deficiency in developing countries.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe how a fermenter can be optimised for a microbial product.', 'Maintain optimum T (water jacket), pH (buffers), O2 (sparger), nutrient concentration. Stir to keep contents uniform. Sterilise to prevent contamination. Continuous flow for primary metabolites; batch for secondary metabolites.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe immobilised enzymes and one advantage.', 'Enzyme is bound to or trapped within a solid support (alginate beads, gel, membrane). Reusable, easier product separation, more stable to T/pH. Used in industrial processes (glucose isomerase, lactose-free milk).', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'T8', 'Gene Expression and Biotechnology', 'Describe the use of DNA microarrays in genomics.', 'Thousands of single-stranded DNA probes are fixed to a slide. Sample DNA / cDNA is fluorescently labelled and hybridises to complementary probes. A scanner detects which probes light up -> shows which genes are present or expressed.', 15, 'alevel');

-- CP — Edexcel A Core Practicals
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe CP1: effect of caffeine on Daphnia heart rate.', 'Place a Daphnia in a cavity slide with pond water; locate heart under low power. Count beats over 10 s. Repeat in pond water with varied [caffeine]; allow acclimation. Plot rate vs concentration. Ethics: minimise time out of water; avoid lethal concentrations.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP2: vitamin C content by DCPIP titration.', 'DCPIP is decolourised by ascorbic acid. Titrate vitamin C standard into a fixed DCPIP volume to find volume needed to decolourise -> calibration. Repeat with juice. Compare volumes inversely (less juice needed = higher [vitamin C]).', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe CP3: membrane permeability of beetroot at varied temperatures.', 'Cut equal beetroot cylinders, rinse to remove leaked pigment. Place in tubes of distilled water at varying T (5-80 °C). After fixed time, remove, measure absorbance of red leakage at ~470 nm using a colorimeter. Higher absorbance -> more disrupted membrane.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP4: enzyme activity vs substrate concentration.', 'Use catalase (yeast or liver) with varied [H2O2]. Measure O2 produced (gas syringe) per unit time. Plot rate vs [H2O2]: rate rises and plateaus when active sites are saturated (Vmax). Control: T, pH, [enzyme].', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe CP6: rate of water uptake using a potometer.', 'Cut shoot underwater (avoid air bubbles) and seal in capillary tube of water with petroleum jelly. Time the bubble moving a set distance. Vary humidity, T, light, wind. Reset bubble using reservoir tap. Repeat for reliable means.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP7: zones of inhibition with antimicrobials.', 'Spread bacteria on agar plate (aseptic technique near a Bunsen). Place paper discs soaked in different antimicrobials. Incubate <25 °C. Measure clear zones of inhibition (diameter or area). Larger zone = greater antimicrobial activity. Control: solvent only disc.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe CP8: investigating photosynthesis with Cabomba / Elodea.', 'Submerge pondweed in NaHCO3 solution (CO2 source). Vary light intensity (lamp distance) or wavelength (filters). Count bubbles per minute or use a gas syringe. Plot rate vs intensity (1/d^2 follows inverse square law). Control T, [CO2], pH.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP9: respiration rate using a respirometer.', 'Place germinating peas in a sealed tube with KOH (absorbs CO2); manometer fluid level moves as O2 is consumed. Use thermostatically controlled bath. Control: glass beads (no respiration). Calculate volume of O2 used per unit time per gram.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe CP13: DNA extraction from a plant (e.g. onion).', 'Mash onion in salt + detergent buffer (detergent dissolves membranes, salt clumps DNA). Filter, then add cold ethanol gently to top of solution -> DNA precipitates as a white "candy floss" at the interface. Pick out with a glass rod.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP14: effect of temperature on enzyme rate.', 'Use catalase + H2O2 (or amylase + starch). Set up water baths at 0-80 °C. Mix enzyme and substrate at temperature; measure rate (gas/colour change). Plot rate vs T: optimum then sharp drop above due to denaturation.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe CP15: estimating populations using sampling techniques.', 'Random sampling: random coordinates with quadrats -> mean density. Systematic: line/belt transect across an environmental gradient. Mark-release-recapture for mobile organisms: N = (n1 x n2) / m. Calculate Simpson''s index for diversity.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP16: phototropism / gravitropism investigation.', 'Grow seedlings (e.g. cress) in different light conditions: unilateral light, no light, all-around light. Measure curvature; observe positive phototropism in shoots and negative phototropism in roots. Control: T, water, support.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'How is a calibration curve created and used?', 'Make standards of known concentration; measure their response (absorbance / intensity). Plot calibration curve. Measure unknown sample under the same conditions and read its concentration off the line. Always include a blank for zeroing.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Distinguish between continuous and discontinuous data and choose a graph.', 'Continuous: any value within a range (height) -> line graph / scatter. Discontinuous: distinct categories or whole numbers (eye colour, counts) -> bar chart. Histograms used for continuous data grouped into classes.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Describe how to calculate the standard deviation and why use it.', 'sigma = sqrt(sum((x - mean)^2) / (n - 1)). Quantifies the spread of data around the mean. Smaller sigma -> data more reproducible. Used with t-tests to assess whether sample means differ significantly.', 15, 'alevel');


