-- A-Level Biology Flashcards (AQA, Edexcel A, Edexcel B, OCR A, OCR B)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- AQA A-LEVEL
-- ===============================================================

-- T1 — Biological Molecules
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Why is water described as a polar molecule, and how does this give rise to its properties?', 'Oxygen is more electronegative than hydrogen, so the O end is delta-negative and the H ends are delta-positive. Water molecules form hydrogen bonds, giving high specific heat capacity, high latent heat of vaporisation, cohesion/adhesion (transpiration stream), and excellent solvent properties for polar/ionic substances.', 1, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Compare alpha and beta glucose and explain how this affects polysaccharide structure.', 'Alpha-glucose has the OH on C1 below the ring, beta-glucose has it above. Alpha-glucose forms starch and glycogen (coiled, branched stores). Beta-glucose monomers must alternate orientation (every other one flipped 180°) to form straight, unbranched cellulose chains held by H-bonds into microfibrils.', 2, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'How does the structure of starch suit its function?', 'Amylose: helical, compact for storage. Amylopectin: branched (1,4 and 1,6 glycosidic bonds), giving many free ends for rapid hydrolysis by amylase. Insoluble (no osmotic effect) and large (cannot leave cells).', 3, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Describe the structure of a triglyceride and an ester bond.', 'One glycerol and three fatty acids joined by three ester bonds in condensation reactions (3 H2O released). Hydrocarbon tails are non-polar, making triglycerides hydrophobic and energy-dense.', 4, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'How do phospholipids form a bilayer in membranes?', 'The hydrophilic phosphate head faces aqueous environments while the hydrophobic fatty acid tails face inwards, away from water. This creates a partially permeable barrier. <svg viewBox="0 0 220 90" width="200" height="80" style="display:block;margin:6px auto"><g><circle cx="20" cy="20" r="6" fill="#0B1E3F"/><line x1="20" y1="26" x2="16" y2="45" stroke="#0B1E3F" stroke-width="1.5"/><line x1="20" y1="26" x2="24" y2="45" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="50" cy="20" r="6" fill="#0B1E3F"/><line x1="50" y1="26" x2="46" y2="45" stroke="#0B1E3F" stroke-width="1.5"/><line x1="50" y1="26" x2="54" y2="45" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="80" cy="20" r="6" fill="#0B1E3F"/><line x1="80" y1="26" x2="76" y2="45" stroke="#0B1E3F" stroke-width="1.5"/><line x1="80" y1="26" x2="84" y2="45" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="110" cy="20" r="6" fill="#0B1E3F"/><line x1="110" y1="26" x2="106" y2="45" stroke="#0B1E3F" stroke-width="1.5"/><line x1="110" y1="26" x2="114" y2="45" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="20" cy="70" r="6" fill="#0B1E3F"/><line x1="20" y1="64" x2="16" y2="50" stroke="#0B1E3F" stroke-width="1.5"/><line x1="20" y1="64" x2="24" y2="50" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="50" cy="70" r="6" fill="#0B1E3F"/><line x1="50" y1="64" x2="46" y2="50" stroke="#0B1E3F" stroke-width="1.5"/><line x1="50" y1="64" x2="54" y2="50" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="80" cy="70" r="6" fill="#0B1E3F"/><line x1="80" y1="64" x2="76" y2="50" stroke="#0B1E3F" stroke-width="1.5"/><line x1="80" y1="64" x2="84" y2="50" stroke="#0B1E3F" stroke-width="1.5"/></g><g><circle cx="110" cy="70" r="6" fill="#0B1E3F"/><line x1="110" y1="64" x2="106" y2="50" stroke="#0B1E3F" stroke-width="1.5"/><line x1="110" y1="64" x2="114" y2="50" stroke="#0B1E3F" stroke-width="1.5"/></g><text x="135" y="22" font-size="9" fill="#0B1E3F">hydrophilic head</text><text x="135" y="55" font-size="9" fill="#0B1E3F">hydrophobic tails</text><text x="135" y="74" font-size="9" fill="#0B1E3F">hydrophilic head</text></svg>', 5, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Describe the four levels of protein structure.', 'Primary: amino acid sequence (peptide bonds). Secondary: alpha helix or beta pleated sheet held by H-bonds between C=O and N-H. Tertiary: 3D fold, stabilised by H-bonds, ionic bonds, disulfide bridges, and hydrophobic interactions. Quaternary: 2+ polypeptide subunits (e.g. haemoglobin: 4 chains + 4 haem groups).', 6, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Explain the induced-fit model of enzyme action.', 'Substrate binds the active site, causing the enzyme to subtly change shape so the active site moulds tightly around the substrate. This places strain on bonds in the substrate, lowering activation energy. Enzyme returns to original shape after products leave.', 7, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'How does a competitive inhibitor differ from a non-competitive inhibitor?', 'Competitive: similar shape to substrate, binds active site, effect overcome by raising [substrate]. Non-competitive: binds an allosteric site, distorting the active site so substrate cannot bind; effect not overcome by [substrate].', 8, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Describe the structure of a DNA nucleotide and how a polynucleotide forms.', 'A deoxyribose sugar joined to a phosphate group and a nitrogenous base (A, T, C or G). Nucleotides join by phosphodiester bonds (condensation) between the 5'' phosphate of one and 3'' OH of the next, forming a sugar-phosphate backbone.', 9, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'State the base-pairing rules and the type of bonds between bases.', 'A pairs with T (2 H-bonds); C pairs with G (3 H-bonds). Strands run antiparallel (5''-3'' and 3''-5''). The two strands wind into a right-handed double helix.', 10, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Outline the role of ATP and how it is hydrolysed.', 'ATP -> ADP + Pi releases ~30.6 kJ mol^-1, catalysed by ATP hydrolase. The Pi can phosphorylate other molecules to make them more reactive. ATP is the universal energy currency of cells.', 11, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Give the reagents, observations and positive results for tests for sugars, starch, lipids, and protein.', 'Reducing sugar: Benedict''s, heat, blue -> brick red. Non-reducing sugar: hydrolyse with HCl, neutralise, then Benedict''s. Starch: iodine in KI, yellow -> blue-black. Lipids: emulsion test, ethanol then water, white emulsion. Protein: biuret, blue -> purple.', 12, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Why is water a good transport medium in plants and animals?', 'It is a polar solvent for ions/glucose/amino acids; cohesion (H-bonds) creates surface tension and continuous columns in xylem; high specific heat capacity buffers temperature; high latent heat of vaporisation makes evaporative cooling efficient.', 13, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'State the role of inorganic ions: H+, Fe2+, Na+, PO4^3-.', 'H+: pH determination, affects enzyme activity and transport. Fe2+: in haem of haemoglobin, binds O2. Na+: co-transport of glucose/amino acids in the ileum, generates membrane potentials. PO4^3-: in DNA/RNA backbones, ATP, phospholipids.', 14, 'alevel'),
  ('Biology', 'AQA', 'T1', 'Biological Molecules', 'Compare DNA and RNA.', 'DNA: deoxyribose, double-stranded, A-T-C-G, very long, stores genetic info. RNA: ribose, single-stranded, A-U-C-G, shorter, three types (mRNA, tRNA, rRNA) involved in protein synthesis.', 15, 'alevel');

-- T2 — Cells
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T2', 'Cells', 'List the main organelles of a eukaryotic animal cell and one function of each.', 'Nucleus: stores DNA, transcription. Mitochondrion: aerobic respiration (ATP). Ribosome (80S): protein synthesis. RER: folds/transports proteins. SER: lipid/steroid synthesis. Golgi: modifies, packages, sorts proteins/glycoproteins. Lysosome: hydrolytic enzymes for digestion. Centrioles: spindle formation in mitosis.', 1, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'How does a prokaryote differ from a eukaryote?', 'Prokaryotes are smaller (~1-5 µm), have no nucleus (circular naked DNA in cytoplasm), 70S ribosomes, no membrane-bound organelles, a peptidoglycan cell wall, and may have plasmids, capsule, flagella and pili.', 2, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Compare TEM and SEM electron microscopes.', 'TEM: thin specimen, electrons pass through, very high resolution (~0.2 nm), 2D image of internal structure. SEM: surface scanned by electrons, lower resolution but 3D surface image. Both need vacuum and dead specimens, expensive, prone to artefacts.', 3, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Explain magnification vs resolution.', 'Magnification = how many times larger the image is than the object (image size / actual size). Resolution = minimum distance two points can be apart and still be distinguished. Light microscopes: ~200 nm; TEM: ~0.2 nm.', 4, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Outline cell fractionation and the order of organelle pellets.', 'Homogenise tissue in cold (slows enzymes), isotonic (prevents osmotic damage), buffered (stable pH) solution. Filter, then centrifuge in increasing speeds. Pellet order: nuclei -> chloroplasts (plants) -> mitochondria -> lysosomes -> ER -> ribosomes.', 5, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Describe the fluid-mosaic model of the plasma membrane.', 'A phospholipid bilayer (fluid) with proteins (mosaic) embedded. Includes channel/carrier proteins, glycoproteins/glycolipids (cell recognition), cholesterol (regulates fluidity). Partially permeable.', 6, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Compare facilitated diffusion and active transport.', 'Facilitated diffusion: passive, down a gradient, via channel/carrier proteins, no ATP. Active transport: uses ATP, against the gradient, via carrier proteins which change shape. Both saturate at high substrate concentrations.', 7, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Explain co-transport of glucose into ileum epithelial cells.', 'Na+/K+ pump on basal membrane uses ATP to pump Na+ out, lowering Na+ inside the cell. Na+ then re-enters with glucose via a co-transporter on the apical surface (down its gradient). Glucose then leaves into blood by facilitated diffusion.', 8, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Define water potential and describe how cells respond to hypotonic and hypertonic solutions.', 'Water potential = pressure exerted by water molecules; pure water = 0 kPa, solutions are negative. Animal cells: lyse in hypotonic, crenate in hypertonic. Plant cells: turgid in hypotonic (cell wall resists), plasmolysed in hypertonic.', 9, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Outline the stages of mitosis and the role in life cycles.', 'Prophase (chromosomes condense, nuclear envelope breaks down) -> Metaphase (chromosomes align on equator) -> Anaphase (sister chromatids pulled apart by spindle) -> Telophase (nuclear envelopes reform). Cytokinesis follows. Used for growth, repair, asexual reproduction; produces genetically identical diploid cells.', 10, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Sketch a typical mitotic index calculation.', 'Mitotic index = (cells in mitosis / total cells) x 100. Used to compare proliferation rates; high values may indicate cancerous tissue.', 11, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'How do cancer drugs target the cell cycle?', 'Some prevent DNA synthesis in S phase (e.g. methotrexate inhibits enzymes). Others prevent spindle formation in metaphase (e.g. vincristine). Side effects affect rapidly dividing healthy tissue (bone marrow, hair, gut).', 12, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Distinguish between the primary and secondary immune responses.', 'Primary: slow, low antibody peak, occurs on first exposure, person may show symptoms. Memory cells produced. Secondary: faster, larger antibody peak (memory B cells differentiate into plasma cells), often no symptoms — basis of immunity.', 13, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Outline the role of T helper, T killer and B cells.', 'T helper: bind antigen-presenting cells, release cytokines that stimulate B cells, T killer cells, and macrophages. T killer: kill infected cells via perforin. B cells: clonally selected by antigen, divide into plasma cells (secrete antibodies) and memory cells.', 14, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Describe the structure and action of an antibody.', 'A Y-shaped quaternary protein with two heavy and two light chains; constant and variable regions. Variable regions form two antigen-binding sites complementary to a specific antigen, causing agglutination and marking pathogens for phagocytosis.', 15, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'Distinguish active, passive, natural and artificial immunity.', 'Active: own antibodies made (memory). Passive: given antibodies (no memory). Natural: through normal life (e.g. infection / breast milk). Artificial: vaccines (active) / antibody injection (passive).', 16, 'alevel'),
  ('Biology', 'AQA', 'T2', 'Cells', 'How does HIV replicate and lead to AIDS?', 'HIV is a retrovirus that binds CD4 on T helper cells, RNA + reverse transcriptase enter, viral DNA integrates into the host genome. Eventually destroys T helpers, weakening immunity; AIDS = opportunistic infections take hold.', 17, 'alevel');

-- T3 — Organisms Exchange Substances
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Why do larger organisms need specialised exchange surfaces?', 'As size increases, surface area : volume ratio decreases, so diffusion alone cannot meet metabolic demands. Specialised surfaces (lungs, gills, villi) provide a large SA, are thin, moist, well-supplied with blood, and ventilated to maintain gradients.', 1, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe gas exchange in fish gills (counter-current flow).', 'Water flows over gill lamellae in the opposite direction to blood. This maintains a concentration gradient along the entire length of the lamella, so ~80% of O2 is absorbed (vs ~50% with parallel flow).', 2, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe insect tracheal system gas exchange.', 'Air enters spiracles -> tracheae -> tracheoles -> tissues. Diffusion is supplemented by ventilation (abdominal pumping) and by water moving out of fluid-filled tracheole tips during activity, increasing surface area for gaseous diffusion.', 3, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe an alveolus and label features that aid exchange.', 'Many alveoli (~300 million) give a large SA (~70 m^2). Walls are squamous epithelium (one cell thick). Surrounded by capillaries (one cell thick). Lined by surfactant. Maintained gradients by breathing and circulation. <svg viewBox="0 0 200 120" width="180" height="110" style="display:block;margin:6px auto"><circle cx="80" cy="60" r="42" fill="#FFFFFF" stroke="#0B1E3F" stroke-width="2"/><circle cx="80" cy="60" r="36" fill="none" stroke="#0B1E3F" stroke-width="0.6"/><path d="M125,60 Q160,30 175,60 Q160,90 125,60" fill="none" stroke="#A33" stroke-width="1.5"/><circle cx="155" cy="60" r="3" fill="#A33"/><text x="60" y="62" font-size="10" fill="#0B1E3F">alveolus</text><text x="115" y="35" font-size="9" fill="#A33">capillary</text><line x1="80" y1="20" x2="115" y2="10" stroke="#0B1E3F" stroke-width="0.8"/><text x="115" y="12" font-size="9" fill="#0B1E3F">surfactant</text></svg>', 4, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'How does the structure of a plant leaf adapt for gas exchange?', 'Many stomata on the lower epidermis allow CO2 in / O2 out; spongy mesophyll has air spaces giving large internal SA; thin (short diffusion distance); guard cells regulate stomatal opening to balance gas exchange and water loss.', 5, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe the adaptations of a xerophyte.', 'Sunken/hairy stomata, thick waxy cuticle, rolled leaves, reduced leaf area (spines), CAM photosynthesis (stomata open at night). All reduce transpiration in dry/hot environments.', 6, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'How are starch, proteins and lipids digested and absorbed?', 'Starch: amylase -> maltose -> maltase -> alpha-glucose. Proteins: endopeptidases (trypsin) cut middle, exopeptidases (carboxy/aminopeptidase) cut ends, dipeptidases finish. Lipids: emulsified by bile salts, lipase -> fatty acids + monoglycerides, absorbed via micelles into ileum cells, reformed and exported as chylomicrons via lacteals.', 7, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe the structure of a villus.', 'Finger-like projections on the ileum wall (large SA). One-cell-thick epithelium with microvilli increasing SA further. Rich blood supply (capillary network) maintains gradients. Lacteal absorbs lipids. Membrane has carriers for active transport / co-transport.', 8, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe a single complete cardiac cycle.', 'Atrial systole: atria contract, AV valves open, ventricles fill. Ventricular systole: ventricles contract, AV valves close (1st heart sound), SL valves open, blood ejected. Diastole: ventricles relax, SL valves close (2nd heart sound), atria fill from veins. Cycle ~0.8 s.', 9, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Sketch and explain the oxyhaemoglobin dissociation curve.', 'A sigmoidal curve: low affinity at low pO2, then cooperative binding causes a steep rise as further O2 binds more easily. The Bohr shift moves the curve right when CO2/H+ rises (active tissues), unloading more O2. <svg viewBox="0 0 200 130" width="180" height="120" style="display:block;margin:6px auto"><line x1="25" y1="110" x2="190" y2="110" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="110" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M25,108 Q60,105 80,80 Q105,40 150,25 L185,22" fill="none" stroke="#0B1E3F" stroke-width="2"/><path d="M25,109 Q70,107 95,90 Q120,55 160,35 L185,30" fill="none" stroke="#A33" stroke-width="1.5" stroke-dasharray="3,2"/><text x="2" y="60" font-size="9" fill="#0B1E3F">% sat</text><text x="80" y="125" font-size="9" fill="#0B1E3F">pO2 / kPa</text><text x="120" y="60" font-size="8" fill="#A33">+ CO2 (Bohr)</text></svg>', 10, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Compare arteries, veins and capillaries.', 'Arteries: thick muscular wall, narrow lumen, elastic, high pressure, no valves. Veins: thin wall, wide lumen, low pressure, valves prevent backflow. Capillaries: one cell thick, narrow (~5-10 µm), large total SA for exchange.', 11, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Explain tissue fluid formation and lymph.', 'At the arterial end of a capillary, hydrostatic pressure > oncotic (solute) pressure, forcing fluid out. At the venous end, hydrostatic pressure has dropped while oncotic pressure (proteins remain) draws fluid back in. Excess fluid (lymph) is returned via lymphatic vessels.', 12, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe the cohesion-tension theory of water transport in xylem.', 'Water evaporates from spongy mesophyll cells -> stomata (transpiration). This creates a tension/negative pressure in xylem, drawing water up. Water molecules cohere by H-bonds (continuous column) and adhere to xylem walls (capillary action).', 13, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Outline the mass-flow hypothesis for translocation in phloem.', 'At the source (e.g. leaf), sucrose is loaded into sieve tubes by active transport (H+/sucrose co-transport), lowering water potential. Water enters from xylem by osmosis, raising hydrostatic pressure. Sucrose flows down a pressure gradient to the sink (e.g. root) where it is unloaded and used or stored.', 14, 'alevel'),
  ('Biology', 'AQA', 'T3', 'Organisms Exchange Substances', 'Describe how a potometer is used.', 'Cut shoot underwater, attach to capillary tube full of water, ensure airtight. Record distance the air bubble moves over time -> rate of water uptake (proxy for transpiration). Vary temperature/humidity/wind/light to investigate effects.', 15, 'alevel');

-- T4 — Genetic Information, Variation & Relationships
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Distinguish gene, allele, locus, genome and proteome.', 'Gene: a section of DNA coding for a polypeptide / functional RNA. Allele: a variant of a gene. Locus: the position of a gene on a chromosome. Genome: all the genetic material in an organism. Proteome: all the proteins it can make.', 1, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Describe the genetic code.', 'Triplet (3 bases code 1 amino acid), non-overlapping, degenerate (multiple codons per amino acid), universal (same in nearly all organisms), and contains start (AUG) and stop codons.', 2, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Compare prokaryotic and eukaryotic genes.', 'Prokaryotic genes are continuous (no introns) and DNA is circular and naked. Eukaryotic genes have introns (non-coding) and exons (coding); DNA is linear and bound to histones forming chromatin.', 3, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Explain semi-conservative DNA replication.', 'DNA helicase unwinds the helix, breaking H-bonds between bases. Free DNA nucleotides align with their complement on each parental strand. DNA polymerase forms phosphodiester bonds. Each new molecule has one parental and one new strand.', 4, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Describe transcription.', 'In the nucleus, RNA polymerase binds the promoter; the gene is unwound; complementary RNA nucleotides (U for A) align on the template strand and are joined to form pre-mRNA. After splicing (introns removed), mature mRNA leaves via a nuclear pore.', 5, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Describe translation.', 'mRNA binds a ribosome; the start codon AUG attracts a tRNA carrying methionine. The next tRNA with the complementary anticodon binds; a peptide bond forms between the amino acids; the ribosome moves one codon along. Continues until a stop codon is reached.', 6, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Describe four types of gene mutation and a possible effect of each.', 'Substitution: usually limited (degenerate code) or missense/nonsense. Insertion/Deletion: cause frameshift -> all subsequent amino acids changed. Duplication: extends frame, often disruptive. Inversion: amino acid sequence reversed in section. Mutations may be silent, beneficial, or harmful.', 7, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Outline meiosis and how it produces genetic variation.', 'Two divisions produce 4 haploid daughter cells. Sources of variation: independent assortment of homologous chromosomes (metaphase I) and sister chromatids (metaphase II), plus crossing-over between non-sister chromatids in prophase I. Random fertilisation adds further variation.', 8, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Define genetic diversity and three sources of variation.', 'Genetic diversity = number of different alleles in a population. Sources: mutation, meiosis (independent assortment, crossing over), random fertilisation. Higher diversity = more raw material for natural selection.', 9, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Describe directional, stabilising and disruptive selection.', 'Directional: extreme phenotype favoured (e.g. antibiotic resistance), shifts mean. Stabilising: intermediate phenotype favoured (e.g. human birth weight), reduces variance. Disruptive: both extremes favoured, may lead to speciation.', 10, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Define species using two criteria.', 'Phylogenetic: sharing an evolutionary lineage. Biological: members can interbreed to produce fertile offspring. Mules (horse x donkey) are infertile -> different species.', 11, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Describe the binomial naming system and the eight taxonomic ranks.', 'Genus + species (italicised), e.g. Homo sapiens. Ranks: domain, kingdom, phylum, class, order, family, genus, species. Three domains: Bacteria, Archaea, Eukarya.', 12, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Why do molecular methods (DNA sequencing, immunology) improve classification?', 'Direct comparison of DNA / protein sequences gives quantitative data; closer relatives have fewer differences. They reveal evolutionary relationships hidden by convergent morphology and confirm phylogenies independently of physical traits.', 13, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'Define species richness and an index of diversity.', 'Species richness = number of species in a community. Simpson''s index D = 1 - sum(n/N)^2 (n = number of organisms of a species, N = total). Higher D = more diverse and more stable community.', 14, 'alevel'),
  ('Biology', 'AQA', 'T4', 'Genetic Information, Variation & Relationships', 'How does intensive farming reduce biodiversity, and how can this be mitigated?', 'Monoculture, hedgerow removal, pesticides, fertilisers and drainage reduce habitats and species. Mitigations: maintain hedgerows, intercropping, organic methods, conservation headlands, agri-environment schemes.', 15, 'alevel');

-- T5 — Energy Transfers in and Between Organisms
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Write the overall equation for photosynthesis and state its two stages.', '6CO2 + 6H2O -> C6H12O6 + 6O2 (light required). Stage 1: light-dependent reactions in thylakoids. Stage 2: light-independent (Calvin cycle) in stroma.', 1, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Outline the light-dependent reactions.', 'Photolysis of water at PSII: 2H2O -> 4H+ + 4e- + O2. Excited electrons travel down ETC (PSII -> PSI), pumping H+ into the thylakoid lumen. Chemiosmosis: H+ flow back through ATP synthase makes ATP. NADP+ + H+ + 2e- -> NADPH.', 2, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Describe the Calvin cycle.', 'CO2 + RuBP (5C) -> 2 GP (3C) catalysed by RuBisCO. GP reduced to TP using ATP and NADPH. Some TP forms glucose; most regenerates RuBP using ATP. Six turns produce one glucose.', 3, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'How do light, CO2 and temperature limit photosynthesis?', 'Light: rate increases with intensity until light-saturation. CO2: rate increases until other factor limiting (~0.4% CO2). Temperature: rate rises with T to ~25-30 °C, then enzymes denature. The lowest factor at any time is the limiting factor.', 4, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'List the four stages of aerobic respiration and their locations.', 'Glycolysis (cytoplasm), link reaction (matrix), Krebs cycle (matrix), oxidative phosphorylation (inner mitochondrial membrane).', 5, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Outline glycolysis.', 'Glucose phosphorylated using 2 ATP -> hexose bisphosphate -> 2 triose phosphate. Each TP oxidised to pyruvate, generating 4 ATP and 2 NADH. Net: 2 ATP and 2 NADH per glucose. Anaerobic and occurs in cytoplasm.', 6, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Describe the link reaction and Krebs cycle (per glucose).', 'Link: 2 pyruvate -> 2 acetyl-CoA, releasing 2 CO2 and 2 NADH. Krebs (x2): each acetyl-CoA + 4C -> 6C; decarboxylation/dehydrogenation give 2 CO2, 3 NADH, 1 FADH2 and 1 ATP. Per glucose: 4 CO2, 6 NADH, 2 FADH2, 2 ATP.', 7, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Explain oxidative phosphorylation by chemiosmosis.', 'NADH/FADH2 deliver electrons to the ETC on the inner mitochondrial membrane. As electrons pass, H+ is pumped to the intermembrane space. H+ flows back through ATP synthase to the matrix, driving ATP synthesis. Final electron acceptor: O2 -> H2O.', 8, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Compare lactate and ethanol fermentation.', 'In animals: pyruvate + NADH -> lactate + NAD+ (reversible; lactate -> liver). In yeast/plants: pyruvate -> ethanal + CO2 -> ethanol (irreversible, NAD+ regenerated). Both regenerate NAD+ so glycolysis can continue without O2.', 9, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Explain why fats yield more ATP per gram than carbohydrates.', 'Fats have many more C-H bonds per molecule than carbohydrates, so beta-oxidation produces more acetyl-CoA -> more NADH and FADH2 entering the ETC -> ~2x ATP yield per gram (~37 vs ~17 kJ/g).', 10, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Define GPP, NPP and write the relationship.', 'GPP = total chemical energy in plant biomass per unit area per unit time. NPP = GPP - respiratory loss. NPP available to next trophic level. Units: kJ m^-2 yr^-1.', 11, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Why is energy transfer between trophic levels inefficient?', 'Not all the previous level is eaten or digested; energy lost as heat from respiration, in faeces, urine and undigested parts. Typical transfer ~10% (plants -> herbivores) up to ~20% (carnivores).', 12, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Describe the nitrogen cycle and the four key types of bacteria.', 'Saprobionts decompose proteins to ammonium (ammonification). Nitrifying bacteria (Nitrosomonas, Nitrobacter) oxidise NH4+ -> NO2- -> NO3-. Nitrogen-fixing bacteria (Rhizobium, Azotobacter) fix N2 -> NH3. Denitrifying bacteria reduce NO3- -> N2 in anaerobic soils.', 13, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'Describe the phosphorus cycle.', 'Rocks weather, releasing PO4^3- ions into soil/water. Plants take up PO4^3- by active transport; passes along food chains. Decomposers and animal waste return PO4^3- to soil. Guano and fertilisers add PO4^3- to crops; runoff causes eutrophication.', 14, 'alevel'),
  ('Biology', 'AQA', 'T5', 'Energy Transfers', 'How does eutrophication arise?', 'Nitrate/phosphate runoff -> rapid algal growth (algal bloom) -> blocks light to plants below -> plants die -> saprobionts decompose them, depleting O2 -> aerobic organisms (e.g. fish) die.', 15, 'alevel');

-- T6 — Organisms Respond to Changes in Their Environment
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Define a tropism and contrast positive and negative phototropism.', 'A tropism is a directional growth response. Positive phototropism: shoots grow towards light (auxin (IAA) accumulates on shaded side, elongates cells). Negative phototropism: roots grow away from light, as IAA inhibits root cell elongation.', 1, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Describe a simple reflex arc.', 'Stimulus -> receptor -> sensory neurone -> relay neurone (in spinal cord) -> motor neurone -> effector (muscle/gland) -> response. Bypasses the brain (faster, protective).', 2, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Explain how a Pacinian corpuscle generates a generator potential.', 'Pressure deforms the lamellae and stretches the membrane. Stretch-mediated Na+ channels open; Na+ enters, depolarising the membrane. If above threshold, an action potential is triggered in the sensory neurone.', 3, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Compare rod and cone cells.', 'Rods: high sensitivity (many rods per bipolar cell -> retinal convergence), monochromatic, used in low light, contain rhodopsin. Cones: low sensitivity (1:1 with bipolar), high acuity, three types (red/green/blue) for colour vision, contain iodopsin, concentrated in fovea.', 4, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Describe how the heart rate is controlled by the SAN, AVN and Purkyne fibres.', 'SAN (right atrium) sets pace; wave of depolarisation spreads across atria -> contraction. Annulus fibrosus delays signal; AVN passes the impulse to the Bundle of His. Purkyne fibres carry it down the septum to the apex, ventricles contract from the bottom up.', 5, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'How is heart rate adjusted by the medulla and baroreceptors?', 'Pressoreceptors in aortic arch/carotid sinus signal to medulla. High BP -> parasympathetic (vagus) -> decrease rate. Low BP / high CO2 -> sympathetic (accelerator nerve) -> increase rate. Chemoreceptors detect blood CO2/pH.', 6, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Sketch and label an action potential.', 'Resting potential (-70 mV) -> stimulus depolarises to threshold (-55 mV). Voltage-gated Na+ channels open: rapid rise to +40 mV. Na+ channels close, K+ channels open: repolarisation. Hyperpolarisation as K+ overshoots, then Na+/K+ pump restores resting potential. <svg viewBox="0 0 200 130" width="180" height="120" style="display:block;margin:6px auto"><line x1="20" y1="80" x2="190" y2="80" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="3,2"/><line x1="20" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="20" y1="115" x2="20" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M20,90 L60,90 L80,20 L100,90 L120,105 L160,90 L190,90" fill="none" stroke="#0B1E3F" stroke-width="2"/><text x="2" y="22" font-size="9" fill="#0B1E3F">+40</text><text x="2" y="93" font-size="9" fill="#0B1E3F">-70</text><text x="80" y="128" font-size="9" fill="#0B1E3F">time / ms</text><text x="60" y="55" font-size="8" fill="#0B1E3F">depol</text><text x="100" y="55" font-size="8" fill="#0B1E3F">repol</text></svg>', 7, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Explain the all-or-nothing principle and frequency coding.', 'Once threshold is reached, an action potential of a fixed amplitude is fired; sub-threshold stimuli give nothing. Stimulus strength is encoded by frequency of action potentials and the number of neurones firing.', 8, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'How does a myelin sheath increase conduction speed?', 'Myelin (Schwann cells) is electrically insulating. Action potentials only occur at the unmyelinated nodes of Ranvier, so the impulse "jumps" from node to node (saltatory conduction), much faster than continuous conduction.', 9, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Describe synaptic transmission at a cholinergic synapse.', 'AP arrives at presynaptic knob -> Ca2+ channels open -> Ca2+ enters -> vesicles fuse with membrane and release ACh. ACh diffuses across the cleft, binds receptors on postsynaptic membrane, opening Na+ channels. Acetylcholinesterase breaks ACh into choline + acetate, taken back into the presynaptic neurone.', 10, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Compare temporal and spatial summation.', 'Temporal: one presynaptic neurone fires repeatedly in quick succession; combined NT release exceeds threshold. Spatial: several presynaptic neurones release NT at the same postsynaptic neurone simultaneously to reach threshold.', 11, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Describe sliding filament theory.', 'Ca2+ released from sarcoplasmic reticulum binds troponin, moving tropomyosin so myosin heads bind actin. ATP hydrolysis powers the power stroke, sliding actin past myosin, shortening the sarcomere. New ATP binds, myosin detaches, cycle repeats.', 12, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Compare slow- and fast-twitch muscle fibres.', 'Slow-twitch: aerobic, many mitochondria, lots of myoglobin, fatigue-resistant (e.g. postural muscles). Fast-twitch: anaerobic glycolysis, few mitochondria, large stores of glycogen and phosphocreatine, fatigue quickly (e.g. sprinting).', 13, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Define homeostasis and explain why it is essential.', 'Maintenance of a constant internal environment within tolerance limits. Stable enzyme activity (T, pH), normal cell water potential, and constant blood glucose ensure cells function efficiently despite external changes.', 14, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Explain the second-messenger model of glucagon action.', 'Glucagon binds a receptor on liver cells -> activates G-protein -> adenylyl cyclase -> ATP -> cAMP (second messenger) -> protein kinase A -> phosphorylates enzymes -> glycogenolysis, releasing glucose into blood.', 15, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Describe how insulin reduces blood glucose.', 'Binds tyrosine kinase receptors on liver/muscle/fat cells -> more GLUT4 transporters inserted, increased glucose uptake. Activates glycogen synthase -> glycogenesis. Inhibits gluconeogenesis. Promotes lipogenesis.', 16, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Compare type 1 and type 2 diabetes.', 'Type 1: autoimmune destruction of beta-cells; insulin not produced; treated with insulin injections. Type 2: cells become insulin-resistant; managed with diet, exercise and metformin. Risk factors: obesity, age, genetics.', 17, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Outline ultrafiltration and selective reabsorption in the nephron.', 'Glomerulus: high BP forces small molecules (water, glucose, urea, ions) through fenestrated capillary, basement membrane and podocytes into Bowman''s capsule. Proximal convoluted tubule: glucose and amino acids are completely reabsorbed by Na+ co-transport; water follows osmotically.', 18, 'alevel'),
  ('Biology', 'AQA', 'T6', 'Organisms Respond to Changes', 'Explain the role of ADH in osmoregulation.', 'When blood is too concentrated, osmoreceptors in the hypothalamus stimulate the posterior pituitary to release ADH. ADH increases collecting duct permeability to water (more aquaporins inserted), so more water is reabsorbed; small volume of concentrated urine is produced.', 19, 'alevel');

-- T7 — Genetics, Populations, Evolution & Ecosystems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Define genotype, phenotype, homozygous and heterozygous.', 'Genotype: alleles an organism has. Phenotype: observable characteristics. Homozygous: two identical alleles (e.g. AA, aa). Heterozygous: two different alleles (Aa).', 1, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Explain a monohybrid cross with a 3:1 ratio.', 'Aa x Aa offspring: AA : Aa : Aa : aa = 3 dominant : 1 recessive phenotype. Each parent gives one allele at random.', 2, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Describe a dihybrid cross and the 9:3:3:1 ratio.', 'Two unlinked genes; AaBb x AaBb gives 9 A_B_ : 3 A_bb : 3 aaB_ : 1 aabb. Confirms independent assortment of unlinked genes (Mendel''s second law).', 3, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Define autosomal linkage and how it affects ratios.', 'Two genes on the same autosome are inherited together unless crossing over occurs. Offspring ratios deviate from expected 9:3:3:1, with parental phenotypes in excess and recombinants reduced.', 4, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Explain sex linkage using haemophilia.', 'Allele on X chromosome (X^h). Females need two X^h to be affected (X^H X^h are carriers); males with one X^h Y are affected. Hence haemophilia is more common in males.', 5, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Define epistasis and give an example.', 'One gene masks/modifies the expression of another. E.g. coat colour in Labradors: BB or Bb gives black, bb gives brown — but ee at a separate locus blocks pigment, giving yellow regardless of B allele.', 6, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Use chi-squared (chi^2) to test goodness of fit.', 'chi^2 = sum((O - E)^2 / E). Compare with critical value at degrees of freedom = (categories - 1), p = 0.05. If chi^2 > critical, reject null hypothesis (deviation significant).', 7, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'State the Hardy-Weinberg principle and equations.', 'Allele frequencies stay constant if: large population, no mutation, no migration, no selection, random mating. p + q = 1; p^2 + 2pq + q^2 = 1.', 8, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Distinguish stabilising, directional and disruptive selection with curve sketches.', 'Stabilising: peak narrows around the same mean. Directional: peak shifts to one extreme. Disruptive: bimodal — extremes favoured.', 9, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Define allopatric vs sympatric speciation.', 'Allopatric: a geographical barrier separates populations; different selection pressures and mutations cause divergence; eventually reproductive isolation. Sympatric: reproductive isolation arises in the same area (e.g. polyploidy in plants, behavioural isolation).', 10, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Compare carrying capacity and limiting factors.', 'Carrying capacity = maximum population an environment can sustain. Limiting factors are density-dependent (food, predators, disease) or density-independent (drought, fire, climate).', 11, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Sketch predator-prey cycles.', 'Prey rises -> predators have more food, increase -> prey decreases -> predators starve, decrease -> prey recovers. Out-of-phase oscillations; predator peaks lag prey peaks.', 12, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Describe primary succession from bare rock to climax community.', 'Pioneer species (e.g. lichens) colonise rock, releasing organic matter as they die -> mosses, then small plants, grasses, shrubs, woodland. Each stage modifies the abiotic environment (soil, light) until a climax community is reached.', 13, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Outline how to estimate population size with mark-release-recapture.', 'Catch a sample, mark, release, allow to mix, recapture. Population N = (n1 x n2) / m, where n1 = first sample size, n2 = second sample size, m = marked recaptures. Assumes no births/deaths/migration and that marking does not affect survival.', 14, 'alevel'),
  ('Biology', 'AQA', 'T7', 'Genetics, Populations, Evolution & Ecosystems', 'Why is conservation often based on managed succession?', 'Allowing a single climax community reduces biodiversity. By cutting/grazing, succession is held at an earlier seral stage that supports a wider range of species (e.g. heathland, chalk grassland).', 15, 'alevel');

-- T8 — Control of Gene Expression
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'How is gene expression regulated by transcription factors?', 'Transcription factors bind specific promoter sequences and either recruit or block RNA polymerase. They are produced in response to internal or external signals (e.g. hormones), allowing only relevant genes to be transcribed in a given cell type.', 1, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Explain how oestrogen activates gene transcription.', 'Lipid-soluble oestrogen diffuses through the membrane and binds an intracellular receptor (TF). The complex enters the nucleus, binds DNA at hormone response elements, and stimulates transcription of target genes.', 2, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Distinguish DNA methylation and histone acetylation.', 'DNA methylation (adding -CH3 to cytosine of CpG islands) typically silences a gene. Histone acetylation loosens DNA-histone binding, making the gene easier to transcribe. Both are reversible epigenetic modifications.', 3, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'How do siRNA / miRNA regulate gene expression?', 'Short RNA molecules base-pair with complementary mRNA. siRNA usually leads to mRNA cleavage by the RISC complex; miRNA usually inhibits translation. Both reduce protein synthesis from a specific gene.', 4, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Define totipotent, pluripotent, multipotent and unipotent stem cells.', 'Totipotent: form any cell type incl. extra-embryonic (zygote, early morula). Pluripotent: any cell type of the body (embryonic SC). Multipotent: limited range (haematopoietic SC). Unipotent: one cell type (cardiac muscle progenitors).', 5, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Outline how iPS cells are made and an advantage over ES cells.', 'Adult somatic cells are reprogrammed by transcription factors (e.g. Oct4, Sox2, Klf4, c-Myc) to a pluripotent state. Avoid ethical issues of embryos and rejection (patient-specific).', 6, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Describe how oncogenes and tumour suppressor genes lead to cancer.', 'Proto-oncogenes regulate cell division; mutation makes them constitutively active oncogenes -> uncontrolled division. Tumour suppressor genes (e.g. p53) normally pause the cycle; loss-of-function mutations remove the brake. Both contribute to malignant tumours.', 7, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Explain how methylation of BRCA1 can lead to cancer.', 'Hypermethylation of the BRCA1 promoter silences this tumour suppressor gene. DNA repair is impaired, so further mutations accumulate -> increased risk of breast/ovarian cancer.', 8, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Describe how DNA fragments can be made for cloning.', 'Three methods: reverse transcriptase from mRNA -> cDNA; restriction endonucleases cut at specific palindromic sequences leaving sticky ends; gene synthesis using known sequences (oligonucleotides).', 9, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Outline the polymerase chain reaction (PCR).', 'Cycles of: denature (95 °C) to separate strands -> anneal (~55 °C) primers to target sequence -> extend (72 °C) by Taq DNA polymerase. Each cycle doubles the DNA -> 2^n copies after n cycles.', 10, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Outline gel electrophoresis of DNA.', 'DNA fragments are loaded into agarose gel wells; an electric field drives the negatively charged DNA towards the anode. Smaller fragments move further. Stains (e.g. ethidium bromide) reveal bands under UV. Used in DNA profiling and PCR analysis.', 11, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Describe how a gene is inserted into a bacterial plasmid.', 'Same restriction enzyme cuts gene and plasmid, creating complementary sticky ends. DNA ligase joins them by phosphodiester bonds. Plasmid (vector) is taken up by host bacterium (transformation), often with help of CaCl2 and heat shock.', 12, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'How are successfully transformed bacteria identified using marker genes?', 'Replica plating onto antibiotic-containing media; only bacteria carrying the plasmid survive. Insertional inactivation (e.g. lacZ disrupted -> white colonies) or fluorescent markers (GFP) confirm the gene of interest has been successfully inserted.', 13, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Define DNA probes and a Southern blot.', 'A DNA probe is a single-stranded labelled DNA sequence complementary to a target. In Southern blotting, fragments are separated by gel electrophoresis, transferred to a membrane, and the probe binds the target -> visualised by radioactivity or fluorescence.', 14, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Outline DNA profiling and one application.', 'PCR amplifies regions containing variable number tandem repeats (VNTRs). Fragments are separated by gel electrophoresis, giving a banding pattern unique to the individual (except identical twins). Used in paternity, forensics, and identifying genetic relationships.', 15, 'alevel'),
  ('Biology', 'AQA', 'T8', 'Control of Gene Expression', 'Compare somatic and germline gene therapy.', 'Somatic: target cells of an individual (e.g. lung cells in CF). Effects not heritable. Germline: alters egg/sperm/embryo so changes are passed on; banned in humans for ethical reasons.', 16, 'alevel');

-- RP — Required Practicals & Practical Skills
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Define independent, dependent and control variables, and give an example.', 'IV: variable manipulated by the experimenter (e.g. temperature). DV: variable measured (e.g. rate of O2 production). Controls: variables held constant (pH, [enzyme], [substrate]). Without controls, changes in DV cannot be attributed to the IV.', 1, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Distinguish accuracy, precision, reliability and validity.', 'Accuracy: closeness to true value. Precision: small spread between repeats. Reliability: same results on repetition. Validity: investigation answers the original question and only the IV affected the DV.', 2, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Describe RP1: investigating the effect of pH on amylase activity.', 'Set up buffers at different pH; mix equal volumes of amylase and starch in each. At intervals, sample with iodine on a tile; record time for the iodine to stop turning blue-black (starch fully digested). Rate = 1/time. Optimum ~ pH 7.', 3, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Outline RP2: preparing and observing a root tip squash for mitosis.', 'Cut tip (~5 mm) from a growing root (e.g. garlic), warm in 1 mol/dm^3 HCl to break cell walls, rinse, place on slide and stain with toluidine blue / acetic orcein. Squash with cover slip to spread cells. Calculate mitotic index = (cells in mitosis / total cells) x 100.', 4, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Describe RP3: dilution series and a calibration curve using a colorimeter.', 'Make a serial dilution of a standard (e.g. glucose) and react with Benedict''s. Filter precipitate; measure absorbance with red filter. Plot absorbance vs concentration to give a calibration curve. Use to find unknown [glucose] from its absorbance.', 5, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'How is RP4 (beetroot membrane permeability) carried out?', 'Cut equal-sized beetroot cylinders, rinse off cell-content pigment. Place in water at varied temperatures (or [ethanol]) for fixed time. Measure absorbance of red leaked betacyanin in colorimeter (~470 nm). Higher absorbance -> more leaked -> more disrupted membrane.', 6, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Describe RP6: aseptic technique with antimicrobial substances.', 'Sterilise inoculating loop in flame, work near a Bunsen, lift agar lid at angle. Spread bacterial culture, place paper discs soaked in antimicrobials. Incubate <25 °C (UK schools). Measure clear zone of inhibition (mm); larger zone = greater antimicrobial activity.', 7, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Outline RP7: chromatography of leaf pigments.', 'Grind leaves with sand and propanone to extract pigments. Spot solvent front on chromatography paper, spot pigment carefully, place in solvent. Calculate Rf = distance moved by spot / distance moved by solvent. Compare Rf to known pigments (chlorophyll a, b, carotene, xanthophyll).', 8, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Describe RP8: respirometer method.', 'Use a respirometer with KOH (absorbs CO2) and a manometer. Measure how far the coloured fluid moves over time -> volume of O2 used by germinating seeds / maggots. Calculate rate; control with glass beads (no respiration). <svg viewBox="0 0 220 90" width="200" height="80" style="display:block;margin:6px auto"><rect x="20" y="25" width="60" height="40" fill="none" stroke="#0B1E3F" stroke-width="1.5"/><text x="36" y="48" font-size="9" fill="#0B1E3F">seeds</text><text x="32" y="60" font-size="8" fill="#0B1E3F">+ KOH</text><line x1="80" y1="45" x2="200" y2="45" stroke="#0B1E3F" stroke-width="1.5"/><circle cx="120" cy="45" r="3" fill="#A33"/><text x="100" y="35" font-size="9" fill="#0B1E3F">manometer</text><text x="115" y="60" font-size="9" fill="#A33">droplet</text></svg>', 9, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Describe RP10: estimating distribution and abundance with quadrats and transects.', 'Random sampling: generate random coordinates with a tape and place quadrats. Systematic: place quadrats at fixed intervals along a line/belt transect (used when an environmental gradient exists). Calculate frequency, percentage cover, and density to compare habitats.', 10, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'How is a serial dilution prepared accurately?', 'Pipette equal volumes (e.g. 1 cm^3) of stock into test tubes. Add equal volumes of solvent (e.g. 9 cm^3 distilled water) to each tube and mix between transfers. This creates a 10-fold (1 in 10) dilution series. Use a fresh pipette tip each time to prevent cross-contamination.', 11, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'Why are repeats and means used, and how is anomalous data treated?', 'Repeats reduce the impact of random errors and reveal precision (range). Means smooth small variations. Identify anomalies (clearly outside the range) by inspection; ignore them when calculating the mean but record them honestly.', 12, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'How is a t-test used in biology?', 'Compares the means of two normally-distributed samples. Calculate t, look up the critical value at (n1 + n2 - 2) degrees of freedom, p = 0.05. If t > critical, reject H0 -> the difference between means is statistically significant.', 13, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'How does a haemocytometer work?', 'A haemocytometer is a calibrated counting chamber. Fill with diluted cell suspension under a coverslip; count cells in a known volume of grid squares. Cells / cm^3 = (mean count per square) / (square volume) x dilution factor.', 14, 'alevel'),
  ('Biology', 'AQA', 'RP', 'Required Practicals & Practical Skills', 'List the safety / ethics considerations for handling microorganisms.', 'Use aseptic technique near a Bunsen, sterilise tools, work on a disinfected bench, avoid lifting agar lids fully, incubate sealed plates at <25 °C, autoclave waste. Ethics: only work with non-pathogenic organisms approved for school use.', 15, 'alevel');


