-- A-Level Biology Flashcards (AQA, Edexcel A, Edexcel B, OCR A, OCR B)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- OCR A A-LEVEL
-- ===============================================================

-- M1 — Development of Practical Skills
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Distinguish independent, dependent and control variables.', 'IV: variable manipulated by the experimenter. DV: variable measured. Controls: variables held constant to ensure only the IV affects the DV. Without controls, observed changes can''t be attributed to the IV alone.', 1, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Distinguish accuracy, precision, reliability and validity.', 'Accuracy: closeness to true value. Precision: small spread of repeats. Reliability: results reproduce on repetition. Validity: investigation answers the original question and only the IV affected the DV.', 2, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Define random and systematic errors.', 'Random errors cause scatter (read by repeating and averaging). Systematic errors cause a consistent shift away from the true value (e.g. zero error on a balance) and cannot be reduced by repetition.', 3, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'How is uncertainty estimated for a single reading?', 'For analogue: half the smallest scale division. For digital: ±1 in the last digit. For repeated readings: half the range. Express as absolute and percentage uncertainty.', 4, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Describe how to choose a sample size and sampling method.', 'Larger samples reduce random error. Random sampling: random coordinates / individuals. Systematic: regular intervals (transects). Stratified: groups sampled proportionally. Method depends on whether a gradient or subgroup structure is present.', 5, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Outline how to use a t-test.', 'Used to compare two means of approximately normally distributed samples. Calculate t, find critical value at (n1 + n2 - 2) df, p = 0.05. If t > critical, reject H0 -> significant difference.', 6, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Describe Spearman''s rank correlation.', 'Used to check whether two ranked variables are correlated. r_s = 1 - (6 sum d^2 / n(n^2 - 1)) where d is rank difference. Compare with critical value at n - 2 df. r_s near +1 / -1 = strong positive / negative correlation.', 7, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Describe chi-squared (chi^2) test of goodness of fit.', 'chi^2 = sum ((O - E)^2 / E). Compare to critical value at (categories - 1) df, p = 0.05. If chi^2 > critical, reject H0 -> deviation from expected ratio is significant. Used in genetics, ecology.', 8, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'How is a calibration curve created and used?', 'Make standards of known concentration; measure response (e.g. absorbance). Plot calibration curve. Measure unknown sample under same conditions and read off concentration. Always include a blank for zeroing.', 9, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Outline good aseptic technique.', 'Sterilise loop in flame, work near a Bunsen, lift agar lid only briefly, replace and tape lightly. Incubate <25 °C in schools, sealed. Autoclave waste. Disinfect bench and hands before and after.', 10, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Compare line, bar and histogram graphs.', 'Line graph: continuous IV and DV; show trends over time / concentration. Bar chart: discontinuous (categorical) data; bars don''t touch. Histogram: continuous data grouped into classes; bars touch and area = frequency.', 11, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Describe ethical considerations in biological investigations.', 'Animal research: 3Rs (replacement, reduction, refinement); avoid undue suffering. Human studies: informed consent, anonymity, right to withdraw, ethical approval. Field studies: avoid habitat damage, follow protected-species laws.', 12, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'How are anomalous results identified and treated?', 'Plot data and inspect; values clearly outside the expected range are anomalies. Repeat to check. Exclude from mean calculations but record honestly with reasons. Investigate the source (procedural error, contamination).', 13, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'Describe the use and calculation of standard deviation.', 'sigma = sqrt(sum((x - mean)^2) / (n - 1)). Quantifies spread of data around mean. Smaller sigma -> more precise. Plotted as error bars on bar charts/scatter plots; non-overlapping error bars suggest a real difference.', 14, 'alevel'),
  ('Biology', 'OCR A', 'M1', 'Development of Practical Skills', 'List safety practices for biology practicals.', 'Wear lab coat, safety goggles and gloves where appropriate. Risk-assess procedures (HSE, CLEAPSS). No mouth-pipetting. Sterilise where microorganisms are involved. Use COSHH for hazardous chemicals. Dispose of biological/chemical waste correctly.', 15, 'alevel');

-- M2 — Foundations in Biology
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'List eukaryotic organelles and their functions.', 'Nucleus: stores DNA, transcription. Mitochondrion: aerobic respiration. RER: protein synthesis/folding. SER: lipid synthesis. Golgi: modifies/packages proteins. Lysosomes: hydrolytic enzymes. Ribosomes (80S): translation. Centrioles: spindle in mitosis. Plant cells additionally have chloroplasts, large vacuole, cellulose cell wall.', 1, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Compare prokaryotes and eukaryotes.', 'Prokaryotes are smaller (~1-5 µm), no nucleus (circular naked DNA), 70S ribosomes, no membrane-bound organelles, peptidoglycan cell wall, may have plasmids, capsule, flagella.', 2, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Compare TEM and SEM electron microscopes.', 'TEM: thin specimen, electrons pass through, very high resolution (~0.2 nm), 2D internal structure. SEM: surface scanned, lower resolution, 3D surface image. Both: vacuum, dead specimens, expensive, prone to artefacts.', 3, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Define magnification, resolution and how an eyepiece graticule is calibrated.', 'Magnification = image / actual; resolution = smallest distance between two distinguishable points. Calibrate using a stage micrometer: 1 division on the eyepiece = how many µm on the stage scale at that objective.', 4, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Why is water described as a polar molecule?', 'Oxygen is more electronegative than hydrogen; the O end is delta-negative and H ends are delta-positive. Water molecules form hydrogen bonds, giving high specific heat capacity, latent heat of vaporisation, cohesion, and excellent solvent properties.', 5, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Describe condensation and hydrolysis reactions.', 'Condensation: two monomers join with the loss of one water molecule (forming glycosidic, peptide or ester bond). Hydrolysis: water is added to break a bond, splitting a polymer into smaller units.', 6, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Describe the four levels of protein structure.', 'Primary: amino acid sequence (peptide bonds). Secondary: alpha helix / beta pleated sheet (H-bonds between C=O and N-H). Tertiary: 3D fold (H-bonds, ionic, disulfide, hydrophobic). Quaternary: 2+ subunits (e.g. haemoglobin: 4 chains + haem).', 7, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Describe a DNA nucleotide and the formation of a polynucleotide.', 'A nucleotide = phosphate + deoxyribose + base (A/T/C/G). Nucleotides join 5'' to 3'' by phosphodiester bonds (condensation), forming a sugar-phosphate backbone. Two antiparallel strands wind into a right-handed double helix held by H-bonds.', 8, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Explain induced-fit enzyme catalysis.', 'Substrate binds the active site; the enzyme subtly changes shape so the active site moulds tightly around the substrate. This places strain on bonds, lowering Ea. Enzyme returns to original shape after products leave.', 9, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'How do competitive and non-competitive inhibitors differ?', 'Competitive: similar shape to substrate, binds active site; effect overcome by raising [substrate]. Non-competitive: binds an allosteric site, distorts the active site so substrate cannot bind; effect not overcome by raising [substrate].', 10, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Describe the fluid-mosaic model.', 'A phospholipid bilayer with proteins (channels, carriers, receptors) embedded in the fluid. Glycoproteins/glycolipids for cell signalling and recognition. Cholesterol regulates fluidity. Hydrophilic heads outwards, hydrophobic tails inwards.', 11, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Compare diffusion, facilitated diffusion, osmosis and active transport.', 'Diffusion: passive, no protein. Facilitated diffusion: passive, via channel/carrier proteins. Osmosis: passive, water down a water-potential gradient. Active transport: ATP-driven, against gradient via carrier proteins.', 12, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Describe the cell cycle stages.', 'G1 (growth, organelle replication) -> S (DNA replication) -> G2 (further growth, error check) -> M (mitosis: PMAT) -> cytokinesis. Checkpoints (G1/S, G2/M, spindle) prevent damaged cells progressing.', 13, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Outline the four stages of mitosis.', 'Prophase: chromosomes condense, nuclear envelope breaks down, centrioles move to poles. Metaphase: chromosomes align on equator. Anaphase: spindle pulls sister chromatids to poles. Telophase: nuclear envelopes reform.', 14, 'alevel'),
  ('Biology', 'OCR A', 'M2', 'Foundations in Biology', 'Compare mitosis and meiosis.', 'Mitosis: 1 division, 2 diploid identical daughter cells, growth/repair. Meiosis: 2 divisions, 4 haploid genetically distinct gametes, with independent assortment and crossing over -> source of genetic variation.', 15, 'alevel');

-- M3 — Exchange and Transport
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Why do larger organisms need specialised exchange surfaces?', 'Surface area : volume falls with size, so simple diffusion cannot meet metabolic demand. Specialised exchange surfaces are large, thin, moist, well-supplied with blood, and ventilated to maintain gradients (Fick''s law).', 1, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe gas exchange in mammalian alveoli.', 'Many alveoli (large total SA ~70 m^2), squamous epithelium one cell thick (short diffusion path), surrounded by capillaries (gradient maintained), thin film of fluid for dissolved gases, surfactant lowers surface tension.', 2, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe the counter-current exchange in fish gills.', 'Water flows over lamellae in the opposite direction to blood. This maintains a concentration gradient along the entire length of the lamella, so ~80% of dissolved O2 is absorbed (vs ~50% with parallel flow).', 3, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe insect tracheal system.', 'Air enters through spiracles -> tracheae -> tracheoles -> tissues directly. Diffusion is supplemented by ventilation (abdominal pumping) and water moving out of tracheole tips during activity, increasing surface area for diffusion.', 4, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe the human breathing mechanism.', 'Inspiration: diaphragm contracts (flattens), external intercostals contract -> volume up, pressure down -> air flows in. Expiration: muscles relax, elastic recoil -> volume down, pressure up -> air flows out. Forced expiration uses internal intercostals + abdominals.', 5, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe the cardiac cycle.', 'Atrial systole: atria contract, AV valves open, ventricles fill (~0.1 s). Ventricular systole: AV valves close (lub), ventricles contract, SL valves open, blood ejected (~0.3 s). Diastole: SL valves close (dub), all chambers relax, atria refill (~0.4 s).', 6, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe how heart rate is controlled.', 'SAN sets pace -> wave of depolarisation across atria -> AVN delays -> Bundle of His -> Purkyne fibres -> ventricles contract from apex up. Medulla regulates rate via sympathetic and parasympathetic nerves; baro/chemoreceptors feed back.', 7, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Compare arteries, veins and capillaries.', 'Arteries: thick wall, narrow lumen, high pressure, no valves (except SL). Veins: thin wall, wide lumen, low pressure, valves prevent backflow. Capillaries: one cell thick, narrow, large total SA -> exchange.', 8, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe formation of tissue fluid.', 'At the arterial end of a capillary, hydrostatic pressure > oncotic pressure -> fluid forced out. At the venous end, hydrostatic pressure has dropped while oncotic pressure (proteins) draws fluid back in. Excess returns via lymph.', 9, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe the structure and function of haemoglobin.', 'Quaternary protein: 4 polypeptide subunits (2 alpha, 2 beta), each with a haem group containing Fe2+ that binds one O2. Cooperative binding gives a sigmoidal dissociation curve.', 10, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Explain the Bohr effect.', 'Increased CO2 / H+ in active tissue lowers pH, reducing haemoglobin''s affinity for O2; the dissociation curve shifts right. More O2 unloaded where it is most needed. Fetal Hb has higher O2 affinity (curve left of adult).', 11, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'How is CO2 transported in the blood?', '~5% dissolved in plasma; ~10% bound to haemoglobin (carbaminohaemoglobin); ~85% as HCO3- (chloride shift). In RBCs: CO2 + H2O -> H2CO3 -> H+ + HCO3- (catalysed by carbonic anhydrase). H+ binds Hb (buffer).', 12, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Describe xylem and phloem structure.', 'Xylem: dead, lignified, hollow tubes (vessels and tracheids); end walls perforated -> continuous tube. Phloem: living sieve tube elements (no nucleus, sieve plates) and companion cells (mitochondria, ribosomes -> support sieve tubes via plasmodesmata).', 13, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Outline the cohesion-tension theory of water transport.', 'Water evaporates from spongy mesophyll into air spaces and out via stomata (transpiration). Tension in xylem; H-bonds keep water as a continuous column. Adhesion to xylem walls aids capillary action. Roots also push water by root pressure (active uptake of ions).', 14, 'alevel'),
  ('Biology', 'OCR A', 'M3', 'Exchange and Transport', 'Outline the mass-flow hypothesis of translocation.', 'Sucrose loaded into sieve tubes at source by H+/sucrose co-transport -> low water potential. Water enters by osmosis -> high hydrostatic pressure. Sap flows down pressure gradient to sink, where sucrose is unloaded and used or stored.', 15, 'alevel');

-- M4 — Biodiversity, Evolution and Disease
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'List four types of pathogens with examples in plants and animals.', 'Bacteria: TB (M. tuberculosis); ring rot (Clavibacter, plants). Virus: HIV; tobacco mosaic virus (TMV). Fungi: athlete''s foot; black sigatoka (banana). Protoctist: malaria (Plasmodium); potato late blight (Phytophthora).', 1, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'How are pathogens transmitted?', 'Direct: contact, droplet, faecal-oral, sexual. Indirect: vectors (mosquitos, animals), fomites (objects), water, food, soil, vertical (mother to fetus). Plants: wind, water, vectors, soil contact, contaminated tools.', 2, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Describe non-specific (innate) defences in animals.', 'Skin barrier; mucous membranes; lysozyme; gastric acid; ciliated epithelia; phagocytosis (neutrophils, macrophages); inflammation (histamine, vasodilation); fever. Fast but non-specific.', 3, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Outline plant defences.', 'Physical: bark, waxy cuticle, lignified cell walls, callose deposition. Chemical: tannins, alkaloids, terpenoids, antimicrobial proteins, salicylates. Hypersensitive response: localised cell death to limit pathogen spread.', 4, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Describe phagocytosis.', 'Phagocyte chemotaxes towards pathogen, recognises by surface receptors, engulfs by endocytosis -> phagosome. Lysosomes fuse, hydrolytic enzymes (lysozyme) digest the pathogen. Antigens presented on MHC II for T-cell activation.', 5, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Describe roles of T helper, T killer, B and memory cells.', 'T helper: bind APCs, release cytokines that stimulate B cells, T killer cells, macrophages. T killer: kill infected cells (perforin, granzymes). B cells -> plasma cells (antibodies) and memory B cells. Memory T cells maintain long-term immunity.', 6, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Compare primary and secondary immune responses.', 'Primary: slow lag, low antibody peak, may show symptoms; produces memory cells. Secondary: rapid, high antibody peak, often asymptomatic. Forms the basis of long-term immunity.', 7, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Distinguish active, passive, natural and artificial immunity.', 'Active: own antibodies, memory long-term. Passive: given antibodies, no memory, short-term. Natural: through normal life. Artificial: vaccines (active) or antibody injection (passive). e.g. anti-tetanus = artificial passive.', 8, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Describe how vaccines work and herd immunity.', 'Vaccines contain weakened/dead pathogens or antigens, triggering primary response and memory cells without disease. If high enough proportion vaccinated, pathogen cannot spread, protecting unvaccinated (herd immunity). Threshold depends on R0.', 9, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Describe biodiversity at three levels.', 'Habitat: number of habitats. Species: richness (count) + evenness (proportion). Genetic: variety of alleles within a population. All three matter for ecosystem stability and resilience.', 10, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Calculate Simpson''s index of diversity.', 'D = 1 - sum (n / N)^2 where n = number of organisms of each species and N = total. Higher D (close to 1) = more diverse and stable; lower D (close to 0) = a few dominant species.', 11, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Describe the eight taxonomic ranks and three domains.', 'Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species. Three domains (Woese): Bacteria, Archaea, Eukarya — based on rRNA sequences and membrane chemistry.', 12, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Outline Darwin''s theory of natural selection.', '1) Variation within populations. 2) More offspring produced than survive. 3) Individuals with advantageous alleles more likely to survive and reproduce. 4) These alleles become more common over generations -> evolution.', 13, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Give two examples of natural selection.', 'Antibiotic resistance in bacteria: random mutations in resistance genes; antibiotic selection -> resistant strains spread (e.g. MRSA). Peppered moth: dark variants favoured during industrial pollution; light variants favoured after the Clean Air Act.', 14, 'alevel'),
  ('Biology', 'OCR A', 'M4', 'Biodiversity, Evolution and Disease', 'Compare in situ and ex situ conservation.', 'In situ: protect species in natural habitat (national parks). Preserves ecosystem interactions but vulnerable to disasters. Ex situ: zoos, seed banks, botanical gardens. Controlled but smaller gene pool, risk of inbreeding.', 15, 'alevel');

-- M5 — Communication, Homeostasis and Energy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Explain the resting potential.', 'Na+/K+ pump moves 3 Na+ out / 2 K+ in per ATP. K+ leak channels allow K+ to diffuse out, leaving inside ~-70 mV relative to outside. Maintained by ATP and selective membrane permeability.', 1, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Sketch and label an action potential.', 'Stimulus opens voltage-gated Na+ channels (depolarisation, -70 -> +40 mV). Na+ channels close, K+ channels open (repolarisation). Hyperpolarisation as K+ overshoots; Na+/K+ pump restores resting potential. Refractory period prevents overlap.', 2, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Why does myelination speed transmission?', 'Myelin (Schwann cells / oligodendrocytes) is electrically insulating. Action potentials only occur at unmyelinated nodes of Ranvier; the impulse "jumps" between nodes (saltatory conduction), much faster than continuous conduction.', 3, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Describe synaptic transmission at a cholinergic synapse.', 'AP arrives -> Ca2+ channels open in presynaptic membrane -> Ca2+ enters -> vesicles fuse with membrane and release ACh. ACh binds postsynaptic receptors, opening Na+ channels. Acetylcholinesterase hydrolyses ACh; choline recycled.', 4, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Compare temporal and spatial summation.', 'Temporal: one presynaptic neurone fires repeatedly so neurotransmitter accumulates -> threshold reached. Spatial: several presynaptic neurones release simultaneously -> threshold reached at a single postsynaptic neurone.', 5, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Define homeostasis and explain why it matters.', 'Maintenance of stable internal environment within tolerance limits. Stable T, pH, blood glucose and water potential keep enzymes active and cells functional. Negative feedback returns conditions to set point; positive feedback amplifies (e.g. childbirth).', 6, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Describe how insulin and glucagon regulate blood glucose.', 'Beta cells release insulin: more GLUT4 transporters -> increased glucose uptake; activates glycogen synthase -> glycogenesis. Alpha cells release glucagon: cAMP second messenger -> phosphorylates glycogen phosphorylase -> glycogenolysis -> glucose released.', 7, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Compare type 1 and type 2 diabetes.', 'Type 1: autoimmune destruction of beta cells -> insulin injections needed. Type 2: insulin resistance / reduced secretion; managed with diet, exercise, metformin. Type 2 risk factors: obesity, age, family history, inactivity.', 8, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Describe ultrafiltration in the nephron.', 'Glomerulus: high BP forces small molecules (water, glucose, ions, urea) through fenestrated capillary, basement membrane (selective barrier) and slits between podocytes into Bowman''s capsule. Blood cells and large proteins remain in blood.', 9, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Describe selective reabsorption in the proximal convoluted tubule.', 'Microvilli give large SA. Na+ pumped into blood by Na+/K+ pumps; Na+ re-enters with glucose / amino acids by co-transport. Glucose then enters blood by facilitated diffusion. Water follows osmotically. ~85% of filtrate reabsorbed here.', 10, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Outline ADH control of water balance.', 'High blood solute concentration -> osmoreceptors in hypothalamus stimulate posterior pituitary to release ADH -> binds collecting duct receptors -> aquaporins inserted -> more water reabsorbed -> small volume of concentrated urine.', 11, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Outline the light-dependent reactions of photosynthesis.', 'Photolysis at PSII: 2H2O -> 4H+ + 4e- + O2. Excited e- pass down ETC, pumping H+ into thylakoid lumen. Chemiosmosis: H+ flows back through ATP synthase -> ATP. NADP+ + H+ + 2e- -> NADPH. Cyclic photophosphorylation produces only ATP.', 12, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Describe the Calvin cycle.', 'CO2 + RuBP (5C) -> 2 GP (3C) (catalysed by RuBisCO). GP reduced to TP using ATP and NADPH. Some TP forms hexose; most regenerates RuBP using ATP. Six turns yield one glucose.', 13, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Describe glycolysis, link reaction and Krebs cycle.', 'Glycolysis (cytoplasm): glucose -> 2 pyruvate, net 2 ATP and 2 NADH. Link (matrix): 2 pyruvate -> 2 acetyl-CoA + 2 CO2 + 2 NADH. Krebs (matrix, x2): 2 CO2, 3 NADH, 1 FADH2, 1 ATP per turn. Per glucose: 4 CO2, 6 NADH, 2 FADH2, 2 ATP.', 14, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Explain oxidative phosphorylation by chemiosmosis.', 'NADH/FADH2 deliver e- to ETC on inner mitochondrial membrane. As electrons pass, H+ pumped to intermembrane space. H+ flows back through ATP synthase -> ATP. O2 final acceptor: O2 + 4H+ + 4e- -> 2H2O. Theoretical yield ~32 ATP per glucose.', 15, 'alevel'),
  ('Biology', 'OCR A', 'M5', 'Communication, Homeostasis and Energy', 'Compare lactate and ethanol fermentation.', 'Animals: pyruvate + NADH -> lactate + NAD+; reversible (lactate cleared in liver -> oxygen debt). Yeast/plants: pyruvate -> ethanal + CO2 -> ethanol + NAD+; irreversible. Both regenerate NAD+ for glycolysis to continue without O2.', 16, 'alevel');

-- M6 — Genetics, Evolution and Ecosystems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'How is gene expression regulated?', 'Transcription factors (activators / repressors) bind specific promoter sequences and either recruit or block RNA polymerase. siRNA / miRNA destroy mRNA or inhibit translation. Epigenetic modifications (DNA methylation, histone acetylation) control accessibility.', 1, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Outline the lac operon as a prokaryotic example.', 'In E. coli, lacI gene constitutively makes a repressor that binds the operator, blocking RNA polymerase. When lactose is present, allolactose binds the repressor, releasing it from the operator -> RNA polymerase transcribes lacZYA -> beta-galactosidase produced.', 2, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Describe a monohybrid and a dihybrid cross.', 'Mono: Aa x Aa -> 3:1 dominant:recessive. Di: AaBb x AaBb -> 9:3:3:1 (assuming no linkage). Use Punnett squares to predict ratios; chi-squared tests if observed differs significantly from expected.', 3, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Explain codominance and the ABO blood system.', 'I^A and I^B alleles are codominant (both expressed in heterozygotes -> AB blood). I^O is recessive. Genotypes: I^A I^A or I^A I^O = A; I^B I^B or I^B I^O = B; I^A I^B = AB; I^O I^O = O.', 4, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Describe sex linkage with haemophilia.', 'Allele on X chromosome (X^h, recessive). Females need two X^h to be affected; one X^h makes a carrier. Males with X^h Y are hemizygous and affected. Hence haemophilia much more common in males.', 5, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Define epistasis with an example.', 'One gene masks another. Recessive epistasis: ee blocks pigment in Labradors -> yellow regardless of B locus. Dominant epistasis: e.g. Bombay phenotype masks ABO. Distorted ratios (12:3:1, 9:3:4 etc.) reveal epistasis.', 6, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'State the Hardy-Weinberg equations and assumptions.', 'p + q = 1; p^2 + 2pq + q^2 = 1. Assumes large population, random mating, no migration / mutation / selection. Useful for estimating carrier frequencies (e.g. cystic fibrosis).', 7, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Describe directional, stabilising and disruptive selection.', 'Directional: extreme phenotype favoured (e.g. peppered moth). Stabilising: intermediate favoured (e.g. human birth weight). Disruptive: both extremes favoured (often precursor to speciation).', 8, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Compare allopatric and sympatric speciation.', 'Allopatric: geographical isolation -> divergent selection / drift -> reproductive isolation. Sympatric: arises within a population without a physical barrier (polyploidy in plants, behavioural / temporal isolation).', 9, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Describe how restriction enzymes and ligase build recombinant DNA.', 'Restriction endonucleases cut DNA at palindromic sequences, leaving sticky ends. Same enzyme used on the gene and the vector creates complementary ends. DNA ligase forms phosphodiester bonds between them, producing recombinant DNA.', 10, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Outline polymerase chain reaction (PCR).', 'Cycles: 95 °C denature, ~55 °C anneal primers, 72 °C extend with Taq polymerase. Each cycle doubles DNA -> 2^n copies after n cycles. Used in cloning, sequencing and DNA profiling.', 11, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Outline DNA profiling using STRs.', 'Extract DNA, amplify short tandem repeat (STR) regions by PCR, separate fragments by gel/capillary electrophoresis. Each individual has a near-unique STR profile -> banding pattern. Used in identification, paternity, forensics.', 12, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Compare natural and artificial cloning of plants and animals.', 'Plants: vegetative propagation (runners), tissue culture (totipotent cells -> callus -> plantlets). Animals: identical twins (natural); artificial: nuclear transfer (Dolly, somatic cell nuclear transfer); embryo splitting in livestock.', 13, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Describe primary succession from bare rock.', 'Pioneer species (lichens) colonise bare rock, weather it and add organic matter. Mosses follow, then small plants, grasses, shrubs and finally woodland (climax). Each stage modifies the abiotic conditions for the next.', 14, 'alevel'),
  ('Biology', 'OCR A', 'M6', 'Genetics, Evolution and Ecosystems', 'Outline the nitrogen cycle and four key bacteria.', 'Saprobionts decompose proteins -> ammonium (ammonification). Nitrifying bacteria (Nitrosomonas, Nitrobacter) oxidise NH4+ -> NO2- -> NO3-. Nitrogen-fixing bacteria (Rhizobium, Azotobacter) fix N2 -> NH3. Denitrifying bacteria reduce NO3- -> N2 in anaerobic soil.', 15, 'alevel');

-- PAG — Practical Activity Groups
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG1: microscopy and use of an eyepiece graticule.', 'Calibrate eyepiece graticule against a stage micrometer at each magnification: 1 division = ? µm. Mount specimen, focus low power first, refine at high power. Measure cells using calibrated graticule. Calculate magnification and actual size.', 1, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG2: dissection (e.g. heart).', 'Pin out external features, identify chambers and vessels. Cut along septum; observe atria (thinner walls), ventricles (thicker, especially LV), AV and SL valves, papillary muscles and chordae tendineae. Use sharps disposal; wear gloves.', 2, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG3: sampling techniques.', 'Random sampling: random coordinates with quadrats. Systematic: line/belt transect across an environmental gradient. Calculate species frequency, percentage cover, density. Mark-release-recapture: N = (n1 x n2) / m for mobile organisms.', 3, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Outline PAG4: rates of enzyme reactions.', 'Use catalase + H2O2 (gas syringe collects O2) or amylase + starch (iodine end-point on tile). Vary T, pH or [substrate]. Plot rate vs IV. Control: [enzyme], buffers, mixing time.', 4, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG5: colorimetry.', 'Make a serial dilution of standards; react with reagent; measure absorbance with appropriate filter (complement of solution colour). Plot calibration curve. Read unknown concentrations from absorbance. Always include a blank to zero.', 5, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Outline PAG6: chromatography of plant pigments.', 'Grind leaves with sand and propanone. Spot solvent front on chromatography paper, spot pigments, place in solvent. Calculate Rf = distance moved by spot / distance moved by solvent. Compare Rf to known pigments (chlorophyll a, b, carotene, xanthophyll).', 6, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG7: aseptic technique with antimicrobials.', 'Sterilise loop in flame, work near a Bunsen, lift agar lid only briefly. Spread bacterial culture, place soaked discs of antimicrobials. Incubate <25 °C, sealed. Measure clear zones of inhibition (diameter or area). Larger zone = greater activity.', 7, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Outline PAG8: transport in and out of cells.', 'Osmosis: cut equal-mass potato cylinders; place in solutions of varied [sucrose]; measure % mass change. Where mass change = 0, water potential of potato = solution. Membrane permeability: beetroot cylinders at varied T -> measure leaked betacyanin in colorimeter.', 8, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG9: biochemical tests for biological molecules.', 'Reducing sugar: Benedict''s, blue -> brick red. Non-reducing sugar: hydrolyse with HCl, neutralise, then Benedict''s. Starch: iodine, blue-black. Lipids: emulsion test, white emulsion. Protein: biuret, blue -> purple. Always heat for Benedict''s.', 9, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Outline PAG10: investigation using a data logger.', 'Use sensors (e.g. T probe, pH probe, light sensor, O2 sensor) connected to a data logger. Set sample interval and duration. Advantages: high precision, large data sets, real-time monitoring, no observer bias. Output to spreadsheet for graphing.', 10, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG11: factors affecting respiration rate (respirometer).', 'Place germinating peas with KOH (CO2 absorber) in sealed tube; manometer fluid moves as O2 consumed. Use thermostatically controlled bath. Control: glass beads (no respiration). Calculate volume of O2 used per unit time per gram of organism.', 11, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe PAG12: factors affecting photosynthesis.', 'Submerge pondweed (Cabomba/Elodea) in NaHCO3 solution (CO2 source). Vary light intensity (lamp distance) or wavelength (filters). Count bubbles per minute or use a gas syringe. Plot rate vs intensity. Control T, [CO2], pH.', 12, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'How is a serial dilution prepared accurately?', 'Pipette equal volumes (e.g. 1 cm^3) of stock into test tubes. Add equal volumes of solvent (e.g. 9 cm^3 distilled water) to each. Mix between transfers. This creates a 10-fold dilution series. Use a fresh pipette tip each time to prevent cross-contamination.', 13, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'Describe how to use a haemocytometer.', 'A haemocytometer is a calibrated counting chamber. Fill with diluted cell suspension under a coverslip; count cells in a known volume of grid squares. Cells / cm^3 = (mean count per square) / (square volume) x dilution factor.', 14, 'alevel'),
  ('Biology', 'OCR A', 'PAG', 'Practical Activity Groups', 'How is data analysed and a conclusion drawn?', 'Plot graph (line / scatter / bar / histogram); identify pattern. Calculate gradient / rate / mean / SD. Apply statistical test (t-test, chi^2, Spearman) to assess significance at p = 0.05. Conclusion: link data back to hypothesis; consider limitations and improvements.', 15, 'alevel');


