-- A-Level Biology Flashcards
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.

-- ===============================================================
-- EDEXCEL A A-LEVEL (Salters-Nuffield, 9BN0)
-- ===============================================================

-- S1 — Lifestyle, Health and Risk
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Compare single, double and closed circulatory systems.', 'Single (e.g. fish): blood passes through the heart once per circuit; gill -> body. Double (mammals): twice per circuit (pulmonary + systemic), maintaining higher pressures. Closed: blood remains within vessels (mammals); open (insects): haemolymph bathes tissues.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Describe a single cardiac cycle.', 'Atrial systole: atria contract, AV valves open, ventricles fill. Ventricular systole: AV valves close (lub), ventricles contract, SL valves open, blood ejected. Diastole: SL valves close (dub), all chambers relax, atria refill. Cycle ~0.8 s at 75 bpm.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Compare arteries, veins and capillaries.', 'Arteries: thick muscular wall, narrow lumen, elastic, carry oxygenated blood (except pulmonary) at high pressure. Veins: thin wall, wide lumen, valves prevent backflow at low pressure. Capillaries: one cell thick endothelium, narrow, large total SA -> exchange.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Why is water described as a polar molecule?', 'O is more electronegative than H, creating a partial negative charge on O and partial positives on H. Water molecules form hydrogen bonds, giving high specific heat capacity, latent heat of vaporisation, cohesion, and excellent solvent properties.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Distinguish saturated, monounsaturated and polyunsaturated fatty acids.', 'Saturated: no C=C, straight chain, solid (animal fats). Monounsaturated: one C=C; polyunsaturated: 2+ C=C, kinked chains -> oils, liquid. cis/trans isomerism affects health: trans fats raise LDL.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Compare HDL and LDL.', 'LDL (low-density): transports cholesterol from liver to tissues; high LDL contributes to atheromas. HDL (high-density): returns cholesterol from tissues to liver. A high HDL : LDL ratio is associated with reduced cardiovascular disease risk.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Describe the formation of an atheroma and its consequences.', 'Damage to endothelium -> inflammation; LDL and white blood cells accumulate in the artery wall, forming a fibrous plaque (atheroma). Lumen narrows; elasticity falls; BP rises; plaque rupture -> thrombosis -> heart attack or stroke.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'List CVD risk factors and how each contributes.', 'Genetics, age, gender. Modifiable: high BP, high LDL, smoking (CO reduces O2 capacity, nicotine raises BP), diet (saturated/trans fats, salt), inactivity, obesity, diabetes. Each damages endothelium or alters blood lipids.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Define correlation vs causation, and identify confounding variables.', 'Correlation: two variables vary together. Causation: one variable directly produces the change in the other. Confounding variables: a third factor that affects both (e.g. age, smoking). Studies must control these to identify true causation.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Compare cohort and case-control studies.', 'Cohort: a group is followed forward in time, recording outcomes (lung cancer in smokers vs non-smokers). Case-control: starts with cases (lung cancer patients) and controls, looks back at exposures (smoking). Cohort is stronger evidence but slower.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Describe how cholesterol-lowering treatments work.', 'Statins inhibit HMG-CoA reductase, the liver enzyme that makes cholesterol. Liver cells then take up more LDL from the blood, lowering blood LDL and total cholesterol. Benefit: reduced CVD risk. Risks: side effects such as muscle pain and liver damage, and the need to take them long-term. Plant stanols/sterols reduce absorption of cholesterol from the gut. (The other 9BN0 CVD treatments act differently: antihypertensives lower blood pressure; anticoagulants such as warfarin and platelet inhibitors such as aspirin reduce clotting.)', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Define risk and probability and calculate from data.', 'Risk = probability of an event = number of events / total. Relative risk = exposure group risk / unexposed risk. e.g. if smokers'' risk = 0.2, non-smokers'' = 0.05, RR = 4 -> 4-fold higher risk.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S1', 'Lifestyle, Health and Risk', 'Outline how lifestyle interventions reduce CVD risk.', 'Stop smoking, reduce saturated/trans fats and salt, increase fruit/veg/fibre, exercise regularly, maintain healthy BMI, moderate alcohol. These lower BP and LDL, improve insulin sensitivity, and reduce inflammation.', 13, 'alevel');

-- S2 — Genes and Health
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe the structure of haemoglobin and oxygen binding.', 'Haemoglobin is a globular protein with quaternary structure: four polypeptide chains (2 alpha, 2 beta), each folded around a haem group containing Fe2+ that binds one O2, so each molecule carries up to 4 O2. The chains fold with hydrophilic R groups on the outside, making it soluble in plasma. Compare collagen, a fibrous protein: three insoluble chains wound into a rope-like triple helix, giving tensile strength.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe the structure of DNA.', 'A nucleotide = phosphate + deoxyribose + base (A, T, C or G). Polynucleotide strands joined by phosphodiester bonds. Two antiparallel strands held by H-bonds: A=T (2), G≡C (3). Twisted into a right-handed double helix.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Outline the genetic code.', 'Triplet, non-overlapping, degenerate, (almost) universal. Start codon AUG; three stop codons (UAA, UAG, UGA). With 4 possible bases at each of 3 positions there are 4^3 = 64 codons for 20 amino acids. Because of this redundancy (degeneracy), some base substitutions are silent.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe transcription and post-transcriptional modification.', 'RNA polymerase joins free RNA nucleotides to a template strand (U replaces T) -> pre-mRNA. Splicing removes introns; exons rejoin. 5'' cap and poly-A tail added. Mature mRNA exits via nuclear pore.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe translation in detail.', 'Small ribosomal subunit binds mRNA; tRNA carrying methionine binds AUG; large subunit completes ribosome. Next tRNA binds complementary codon; peptide bond forms. Ribosome translocates one codon. Continues until a stop codon -> polypeptide released.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe types of gene mutations and outcomes.', 'Substitution: silent (same amino acid), missense (different amino acid) or nonsense (stop codon -> truncated protein). Insertion or deletion of bases not in a multiple of 3: frameshift -> every downstream codon changed, usually a non-functional protein. The effect depends on how the change alters the protein''s structure and function. Examples: sickle-cell anaemia (substitution, Glu -> Val in beta-globin); CF delta F508 (deletion of 3 nucleotides removing one amino acid, phenylalanine 508, with no frameshift, so CFTR misfolds and is degraded).', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Outline cystic fibrosis at the molecular level.', 'Mutation in the CFTR gene (chr 7) — most commonly delta F508. CFTR is a chloride channel. Faulty channel -> thick mucus in airways, gut, reproductive system. Treatments target symptoms (physiotherapy, mucolytics) and the cause (CFTR modulators, gene therapy).', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe how cystic fibrosis is inherited.', 'Autosomal recessive: two cf alleles needed (one from each parent). Carriers (Cc) show no symptoms. Two carriers x: 1/4 affected, 1/2 carriers, 1/4 unaffected. Genetic counselling and prenatal testing available.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe phospholipid bilayer structure.', 'Two layers of phospholipids: hydrophilic phosphate heads point outward (towards aqueous); hydrophobic fatty acid tails point inward. The membrane is fluid; cholesterol regulates fluidity; proteins are embedded as channels, carriers and receptors.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Compare diffusion, facilitated diffusion, osmosis and active transport.', 'Diffusion: passive, lipid-soluble or gases, no protein. Facilitated diffusion: passive via channel/carrier proteins. Osmosis: passive water movement down water-potential gradient. Active transport: against gradient, ATP-driven by carrier proteins.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe how Na+ and Cl- normally cross airway epithelium and how CF disrupts this.', 'Normal: Cl- ions move out through CFTR channels into mucus; Na+ follows; water follows osmotically -> thin watery mucus. CF: faulty CFTR -> Cl- cannot leave; Na+ moves into cell instead; water leaves mucus -> thick sticky mucus.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe the structure of the lungs and gas exchange.', 'Trachea -> bronchi -> bronchioles -> alveoli (~300 million; ~70 m^2). Alveoli: thin squamous epithelium, surrounded by capillaries (also one cell thick), surfactant lining, ventilated by breathing -> O2 diffuses to blood, CO2 diffuses out.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Outline the role of cilia and goblet cells.', 'Goblet cells secrete mucus that traps pathogens and dust. Ciliated epithelial cells beat to move mucus up to the throat where it is swallowed (mucociliary escalator). Smoking paralyses cilia -> chronic cough.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Describe pre-natal genetic testing for CF (CVS and amniocentesis).', 'CVS (10-13 weeks): biopsy of chorionic villi, faster, slightly higher miscarriage risk (~1%). Amniocentesis (15-20 weeks): sample of amniotic fluid containing fetal cells; lower miscarriage risk (~0.5%) but later. PCR / genetic analysis of CFTR gene.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'S2', 'Genes and Health', 'Outline ethical considerations of genetic testing.', 'Benefits: informed reproductive choices, treatment planning. Issues: psychological impact, insurance discrimination, privacy, potential for selective termination, parental disagreements, mis-diagnosis. Pre-test counselling is essential.', 15, 'alevel');

-- S3 — Voice of the Genome
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Compare DNA in eukaryotes vs prokaryotes.', 'Eukaryotic DNA: linear, in nucleus, wound around histones, has introns and exons. Prokaryotic DNA: circular, in cytoplasm (nucleoid), no histones, no introns. Plasmids may also be present.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Describe the eukaryotic cell cycle.', 'G1: cell growth, organelle replication. S: DNA replication. G2: further growth, error check. M: mitosis (PMAT). Cytokinesis. Checkpoints (G1/S, G2/M, spindle) prevent damaged cells progressing.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Outline the four stages of mitosis.', 'Prophase: chromosomes condense (sister chromatids visible), nuclear envelope breaks down, centrosomes move to poles. Metaphase: chromosomes line up on equator. Anaphase: spindle pulls sister chromatids to poles. Telophase: nuclear envelopes reform.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Compare mitosis and meiosis.', 'Mitosis: 1 division, 2 diploid identical daughter cells, growth/repair. Meiosis: 2 divisions, 4 haploid genetically distinct gametes, with independent assortment and crossing over. Source of variation -> evolution.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Describe two sources of genetic variation in meiosis.', 'Independent assortment: homologous chromosomes line up randomly in metaphase I (and sister chromatids in metaphase II). Crossing over: in prophase I, non-sister chromatids exchange DNA at chiasmata, forming new allele combinations.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Define totipotent, pluripotent, multipotent and unipotent.', 'Totipotent: any cell type incl. extra-embryonic (e.g. zygote). Pluripotent: any embryonic cell type (e.g. embryonic stem cells). Multipotent: limited types (e.g. haematopoietic stem cells). Unipotent: one type (e.g. cardiac muscle progenitor).', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Outline how stem cells differentiate.', 'Differentiation results from selective gene expression. Specific TFs activate cell-type-specific genes; epigenetic changes (DNA methylation, histone modification) silence others. Position-dependent signals (morphogens) and the cells'' microenvironment guide specialisation.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Outline benefits and ethical issues of using human embryonic stem cells.', 'Benefits: pluripotent -> potential regenerative therapies (Parkinson''s, spinal injury). Ethics: destruction of embryos; iPS cells offer an alternative with fewer concerns. Strict regulation (HFEA in the UK).', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Describe how genes and environment interact.', 'Genotype sets potential; phenotype is the result of gene expression + environment. e.g. height (genetic potential limited by nutrition); MZ twins'' methylomes drift over time; many traits are polygenic and multifactorial.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Compare continuous and discontinuous variation.', 'Continuous: range of values (height, mass), polygenic and influenced by environment, normal distribution. Discontinuous: distinct categories (blood group), usually one or few genes, environment little effect; bar chart distribution.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Describe cell signalling and gene expression.', 'Signal molecule (e.g. hormone) binds a receptor -> transduction (often a phosphorylation cascade) -> activates TFs that bind DNA, switching specific genes on/off. Allows tissue-specific responses.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'Outline mammalian fertilisation.', 'Sperm acrosome reaction: enzymes digest zona pellucida. Sperm membrane fuses with oocyte. Cortical reaction prevents polyspermy. Sperm nucleus enters; meiosis II completes; haploid pronuclei fuse -> diploid zygote. Cleavage starts.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S3', 'Voice of the Genome', 'How are chromosomes packaged in the nucleus?', 'DNA wraps around 8 histone proteins to form a nucleosome (~146 bp). Nucleosomes coil into a 30 nm fibre and fold into chromatin. Heterochromatin (densely packed) silences genes; euchromatin (open) is transcribed.', 13, 'alevel');

-- S4 — Biodiversity and Natural Resources
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Outline the eight taxonomic ranks and three domains.', 'Domain, Kingdom, Phylum, Class, Order, Family, Genus, Species. Three domains (Woese): Bacteria, Archaea, Eukarya — based on rRNA sequences, membrane lipids, and genome organisation.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Define a species and describe two ways to define it.', 'Phylogenetic: shared evolutionary lineage on a tree of life. Biological: members can interbreed to produce fertile offspring. Issues: hybrid sterility (mules), asexual species, ring species. Modern molecular comparisons supplement morphology.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'How are molecular methods used to classify organisms?', 'Direct DNA / amino acid sequence comparison gives quantitative similarity. Closer relatives share more conserved sequences. Confirms or revises classifications based on morphology and reveals evolutionary relationships hidden by convergent evolution.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Define biodiversity at three levels.', 'Habitat: number of habitats in an area. Species: richness (count) and evenness (relative abundance). Genetic: variety of alleles within a population. All three vary independently and matter for ecosystem stability.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Calculate the index of diversity (9BN0).', '9BN0 index of diversity: D = N(N - 1) / sum of n(n - 1), where N = total number of organisms of all species and n = number of individuals of each species. D = 1 if only one species is present; the higher the value, the more diverse the habitat. It takes into account both species richness and the evenness of abundance, so habitats can be compared.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Define endemism and give an example.', 'A species found only in a single restricted area. e.g. lemurs (Madagascar), Galapagos finches. Endemic species are vulnerable to extinction because their entire range can be affected by a single disturbance.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Describe the structure of plant cell walls.', 'Cellulose microfibrils (beta-1,4 glucose) crosslinked by hemicellulose and embedded in pectin. Lignin adds strength to xylem and sclerenchyma. Plasmodesmata link cells. The wall provides support, shape and tensile strength against turgor pressure.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Compare xylem and phloem.', 'Xylem: dead, lignified tubes carrying water/minerals from root to leaves; mass flow driven by transpiration tension. Phloem: living sieve tubes with companion cells, transports assimilates (sucrose) from sources to sinks by mass flow.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'How are plants used in medicine? (Drug discovery)', 'Examples: aspirin from willow bark salicylates, taxol from yew (cancer), digitalis from foxglove (heart). Bioprospecting screens biodiverse regions; loss of biodiversity means losing potential drugs.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Describe testing of new drugs (William Withering / clinical trials).', 'Withering used systematic patient observation to determine the correct dose of digitalis. Modern trials: pre-clinical (cells, animals), Phase I (safety in healthy volunteers), II (efficacy), III (large randomised trial vs placebo or current treatment), IV (post-market surveillance).', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Compare in situ and ex situ conservation.', 'In situ: protect species in natural habitat (national parks, reserves) — preserves ecological interactions but vulnerable to disasters. Ex situ: zoos, seed banks, botanical gardens — controlled but smaller gene pool, risk of inbreeding.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Describe a seed bank.', 'Stores dried, low-T seeds (e.g. Millennium Seed Bank, Kew) ex situ. Long-term storage preserves genetic diversity, crop wild relatives, and species at risk of extinction. Limitations: only seed-bearing plants, viability declines, periodic germination tests required.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'Outline how zoos contribute to species conservation.', 'Captive breeding programmes (e.g. Arabian oryx, giant panda); coordinated international stud books prevent inbreeding; reintroduction projects; education and research. Critics raise concerns about welfare and habitat loss being the root problem.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'S4', 'Biodiversity and Natural Resources', 'State Hardy-Weinberg principle and equations.', 'Allele frequencies stay constant across generations if: large population, no migration, no mutation, no selection, random mating. p + q = 1; p^2 + 2pq + q^2 = 1.', 14, 'alevel');

-- S5 — On the Wild Side
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Write the photosynthesis equation and identify oxidation/reduction.', '6CO2 + 6H2O -> C6H12O6 + 6O2 (sunlight). CO2 is reduced (gains H/electrons) to glucose. H2O is oxidised to O2 in photolysis at PSII.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Outline the light-dependent reactions.', 'Photolysis at PSII: 2H2O -> 4H+ + 4e- + O2. Excited e- pass down ETC, pumping H+ into thylakoid lumen -> ATP via chemiosmosis. NADP+ + H+ + 2e- -> NADPH. Cyclic photophosphorylation produces only ATP.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Describe the Calvin cycle.', 'CO2 + RuBP -> 2 GP (catalysed by RuBisCO). GP reduced to TP using ATP and NADPH. Some TP forms hexose; most regenerates RuBP using ATP. Six turns yield one glucose.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Describe how light, CO2 and temperature affect photosynthesis.', 'Each can be the limiting factor when it is in shortest supply. Low light: the light-dependent reactions are limited, so little ATP and reduced NADP is supplied to the Calvin cycle. Low CO2: carbon fixation by RuBisCO in the Calvin cycle is limited. Temperature: below the optimum, enzyme-controlled reactions (e.g. RuBisCO) slow. Above the optimum, the rate falls as stomata close to reduce water loss (less CO2 uptake) and enzymes lose activity, denaturing at high temperatures (around 40 degrees C and above).', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Define an ecosystem and give an example food chain.', 'Ecosystem = a community of organisms interacting with each other and with their abiotic environment. Example food chain: grass -> rabbit -> fox (producer -> primary consumer -> secondary consumer). Energy enters when producers fix light energy by photosynthesis (GPP); the energy remaining after plant respiration (NPP = GPP - R) is available to primary consumers. Typically only about 10% of energy passes from one trophic level to the next.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Define and calculate net primary productivity (NPP).', 'GPP = total chemical energy fixed by producers per area per time. NPP = GPP - R (respiration). Units: kJ m^-2 yr^-1. NPP is energy available to next trophic level.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Describe the carbon cycle.', 'Photosynthesis fixes CO2 into organic compounds; respiration, combustion and decomposition return CO2. Carbon stored in biomass, soil, oceans (HCO3-), fossil fuels. Anthropogenic CO2 (fossil fuel burning, deforestation) increases atmospheric levels.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'List evidence for climate change.', 'Direct: ice core CO2 / temperature records, atmospheric CO2 measurements (Mauna Loa), satellite data, sea-level rise, glacier retreat. Indirect: dendrochronology, pollen analysis, isotope ratios in foraminifera. Multiple independent lines converge on warming.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Explain how rising temperatures affect species distribution.', 'Species shift poleward and upward in altitude as temperatures rise; phenological mismatches (flowering vs pollinators) occur; range contractions if no migration possible (e.g. mountain-top species). Loss of habitat and mismatched timing reduce reproductive success.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Describe primary succession from bare rock.', 'Pioneer species (e.g. lichens) colonise bare rock, weather it and add organic matter. Mosses follow, then small plants, grasses, shrubs and finally woodland (climax). Each stage modifies the abiotic conditions for the next.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Compare deflected and secondary succession.', 'Secondary: starts on existing soil after disturbance (e.g. fire); succession proceeds as for primary but faster. Deflected: human activity (mowing, grazing) holds the community at an earlier seral stage (heathland, chalk grassland) — often biodiverse.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Describe natural selection in peppered moths and antibiotic resistance.', 'Peppered moth: dark form favoured during industrial pollution (camouflage on sooty trees); light form returns after Clean Air Act. Antibiotic resistance: random mutations in bacteria; resistant variants survive antibiotic treatment and reproduce.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'Compare allopatric and sympatric speciation.', 'Allopatric: geographical isolation -> divergent selection / drift -> reproductive isolation. Sympatric: arises within a population without a physical barrier (polyploidy in plants, behavioural / temporal isolation).', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'S5', 'On the Wild Side', 'How can we mitigate climate change biologically?', 'Reduce CO2 emissions (fossil fuel substitution, energy efficiency); reforestation and afforestation; rewetting peatlands; protect oceans (blue carbon); reduce deforestation; carbon capture and storage; soil management. Both supply-side and demand-side action needed.', 14, 'alevel');

-- S6 — Immunity, Infection and Forensics
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Compare types of pathogens and give one example each.', 'Bacteria: prokaryote, peptidoglycan wall (e.g. TB Mycobacterium tuberculosis). Virus: nucleic acid + capsid, hijacks host (HIV). Fungi: eukaryote, hyphae (athlete''s foot Trichophyton). Protoctist: eukaryote (Plasmodium - malaria).', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Describe non-specific (innate) defences.', 'Skin barrier; mucous membranes; lysozyme in tears/saliva; gastric acid; ciliated epithelia; phagocytosis (neutrophils, macrophages); inflammation (histamine, vasodilation); fever (raised T inhibits pathogens). Fast but non-specific.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Describe phagocytosis step-by-step.', 'Phagocyte chemotaxes towards pathogen, recognises by surface receptors, engulfs by endocytosis -> phagosome. Lysosomes fuse with phagosome -> phagolysosome; lysozyme digests pathogen. Antigens displayed on MHC for T-cell activation.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Compare T helper, T killer and B cells.', 'T helper: bind APCs, release cytokines that activate other cells. T killer: directly kill infected/cancer cells (perforin, granzymes). B cells: differentiate into plasma cells (antibodies) or memory cells once selected by their specific antigen.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Describe antibody structure and four functions.', 'Y-shape, two heavy + two light chains, constant + variable regions, two antigen-binding sites. Functions: agglutination, opsonisation (mark for phagocytosis), neutralisation of toxins, activation of complement.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Compare primary and secondary immune responses.', 'Primary: long lag (about 1-2 weeks to peak) while the few B and T cells specific to the antigen are selected and cloned; low antibody peak; symptoms often develop. Memory B and T cells form. Secondary: memory cells respond quickly, so antibody levels rise within a few days and reach a much higher, longer-lasting peak; the pathogen is usually destroyed before symptoms appear. Forms the basis of long-term immunity.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Describe vaccination and herd immunity.', 'Vaccines contain weakened/inactivated pathogens or antigens, triggering primary response and memory cells without disease. If many in a population are immune, the pathogen cannot spread (herd immunity), protecting unvaccinated individuals.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Distinguish active, passive, natural and artificial immunity.', 'Active: own antibodies / memory (long-term). Passive: received antibodies (short-term). Natural: through life (infection / breast milk). Artificial: vaccines (active) or antibody injection (passive, e.g. anti-tetanus).', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'How do antibiotics work?', 'Bactericidal: kill bacteria (penicillin disrupts peptidoglycan synthesis -> weak walls -> lysis). Bacteriostatic: prevent growth (tetracyclines block 70S ribosomes -> halt protein synthesis). Selective toxicity: target features absent in human cells.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'How does antibiotic resistance evolve?', 'Random mutation gives resistance (e.g. beta-lactamase, modified penicillin-binding proteins). Antibiotics select for resistant strains; resistance genes spread via plasmid conjugation (horizontal transfer). Misuse and incomplete courses accelerate this.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Describe how time of death is estimated.', 'Algor mortis: ~1.5 °C drop per hour (first 12 h). Rigor mortis: stiffness from ~2 h, peak at 12 h, fades by 36 h. Hypostasis (livor): blood pooling, fixed by ~12 h. Insect succession (entomology). Stomach contents.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Outline DNA profiling using STRs.', 'Extract DNA, amplify short tandem repeat (STR) regions by PCR, separate fragments by gel/capillary electrophoresis. Each individual has a near-unique STR profile -> banding pattern. Used in identification, paternity, forensics.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Outline polymerase chain reaction (PCR).', 'Cycles: 95 °C denature -> ~55 °C anneal primers -> 72 °C extend with Taq polymerase. Each cycle doubles DNA -> 2^n copies after n cycles. Used in cloning, sequencing and DNA profiling.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'S6', 'Immunity, Infection and Forensics', 'Describe how decomposers contribute to nutrient cycling.', 'Saprobionts (fungi, bacteria) secrete extracellular enzymes onto dead matter; soluble products absorbed by diffusion. Detritivores fragment material. Resulting NH4+ enters the nitrogen cycle; CO2 returns to atmosphere via respiration.', 14, 'alevel');

-- S7 — Run for Your Life
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'List the four stages of aerobic respiration with location.', 'Glycolysis (cytoplasm), link reaction (matrix), Krebs cycle (matrix), oxidative phosphorylation (inner mitochondrial membrane / cristae).', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Outline glycolysis.', 'Glucose phosphorylated using 2 ATP -> hexose bisphosphate -> 2 triose phosphate. Each TP oxidised to pyruvate; net 2 ATP and 2 NADH per glucose. Anaerobic; in cytoplasm.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Describe the link reaction and Krebs cycle.', 'Link: 2 pyruvate -> 2 acetyl-CoA, 2 NADH and 2 CO2. Krebs (x2): each acetyl-CoA + 4C -> 6C; decarboxylation/dehydrogenation give 2 CO2, 3 NADH, 1 FADH2 and 1 ATP per turn (per glucose: 4 CO2, 6 NADH, 2 FADH2, 2 ATP).', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Explain oxidative phosphorylation by chemiosmosis.', 'NADH/FADH2 deliver e- to ETC on inner membrane. Electrons pass between carriers, pumping H+ into intermembrane space. H+ flows back through ATP synthase -> ATP. O2 final acceptor: O2 + 4H+ + 4e- -> 2H2O.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Compare lactate and ethanol fermentation.', 'Animals: pyruvate + NADH -> lactate + NAD+; reversible (lactate cleared in liver -> oxygen debt). Yeast/plants: pyruvate -> ethanal + CO2 -> ethanol + NAD+; irreversible. Both regenerate NAD+ to allow glycolysis to continue.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Compare slow- and fast-twitch muscle fibres.', 'Slow-twitch (Type I): aerobic, many mitochondria, lots of myoglobin, fatigue-resistant (postural muscles, marathon). Fast-twitch (Type II): anaerobic glycolysis, large glycogen and phosphocreatine stores, fatigue quickly (sprinting, weightlifting).', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Describe the structure of a sarcomere.', 'Region between two Z-lines. Contains overlapping thin actin and thick myosin filaments. I-band: actin only. A-band: full length of myosin. H-zone: myosin only (no actin). M-line: middle of sarcomere. Sarcomere shortens during contraction.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Outline the sliding filament theory.', 'AP arrives at NMJ -> Ca2+ released from sarcoplasmic reticulum -> Ca2+ binds troponin, moving tropomyosin to expose actin binding sites. Myosin heads bind actin -> power stroke (ADP/Pi released). New ATP binds, head detaches; ATP -> ADP+Pi resets.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Describe how heart rate is controlled.', 'SAN sets pace -> wave of depolarisation across atria -> AVN delays -> Bundle of His -> Purkyne fibres -> ventricles contract from apex up. Medulla regulates rate via sympathetic (accelerator) and parasympathetic (vagus) nerves; baroreceptors and chemoreceptors feed back.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'How does exercise affect ventilation?', 'CO2 produced in respiration lowers blood pH; chemoreceptors in aortic / carotid bodies detect this and signal medulla -> increases breathing rate and depth. Stretch receptors in lungs prevent over-inflation. After exercise, debt repaid by elevated breathing.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Define VO2 max and how it adapts to training.', 'Maximum rate of O2 uptake during intense exercise (mL kg^-1 min^-1). Reflects cardiovascular and respiratory efficiency. Aerobic training raises VO2 max via increased stroke volume, capillary density, mitochondria and myoglobin in muscle.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Outline thermoregulation during exercise.', 'Increased respiration produces heat. Hypothalamus detects rise; vasodilation of skin arterioles, sweating (evaporative cooling), reduced metabolic heat. After exercise: shivering or vasoconstriction may follow if body T overshoots.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Describe how performance-enhancing drugs work and ethical issues.', 'Anabolic steroids: mimic testosterone -> increased muscle synthesis; risks include heart damage and infertility. EPO: boosts red blood cells -> O2 carriage; risk of clots. Stimulants: mask fatigue. Ethics: unfair advantage, health risk, role-model effect, legality.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'S7', 'Run for Your Life', 'Describe the keyhole / arthroscopic surgery for sports injury.', 'A small incision allows a fibre-optic camera and instruments into a joint. Cartilage tears are trimmed or repaired; ACL reconstruction uses graft tissue. Less tissue trauma -> faster recovery than open surgery, though possible complications (infection, stiffness).', 14, 'alevel');

-- S8 — Grey Matter
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Describe the structure of a typical neurone.', 'Cell body (with nucleus), dendrites (receive signals), axon (conducts AP), and axon terminals (release neurotransmitter). Axon may be myelinated by Schwann cells (PNS) or oligodendrocytes (CNS), with nodes of Ranvier.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Distinguish CNS and PNS, somatic and autonomic, sympathetic and parasympathetic.', 'CNS = brain + spinal cord. PNS: sensory + motor neurones. Somatic: voluntary skeletal muscle. Autonomic: involuntary smooth/cardiac muscle/glands. Sympathetic: fight/flight; parasympathetic: rest/digest.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Explain the resting potential.', 'Na+/K+ pump moves 3 Na+ out / 2 K+ in per ATP. K+ leaks out via leak channels, leaving inside ~-70 mV relative to outside. Maintained by ATP and selective membrane permeability.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Sketch and label an action potential.', 'Stimulus -> threshold (-55 mV) -> voltage-gated Na+ channels open (depolarisation to +40 mV). Na+ channels close, K+ channels open (repolarisation). Hyperpolarisation; Na+/K+ pump restores resting potential.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Why does myelination speed transmission?', 'Myelin (Schwann/oligodendrocyte) is electrically insulating. Action potentials only occur at unmyelinated nodes of Ranvier; the impulse "jumps" between nodes (saltatory conduction), much faster than continuous conduction.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Describe synaptic transmission at a cholinergic synapse.', 'AP arrives -> Ca2+ channels open, Ca2+ enters -> vesicles fuse with membrane and release ACh. ACh diffuses across cleft, binds postsynaptic receptors, opens Na+ channels. Acetylcholinesterase hydrolyses ACh; choline recycled.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Describe excitatory and inhibitory postsynaptic potentials.', 'EPSP: depolarising (Na+ entry) — moves potential towards threshold. IPSP: hyperpolarising (Cl- entry or K+ exit) — moves it away. Summation of EPSPs and IPSPs determines whether the postsynaptic neurone fires.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Describe the major regions of the human brain and their functions.', 'Cerebrum: voluntary action, learning, memory. Cerebellum: balance, coordination. Hypothalamus: homeostasis, thermoregulation. Pituitary: hormones. Medulla: heart and breathing centres.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Outline how the eye detects light.', 'Light is refracted mainly by the cornea, with fine focusing by the lens, and is focused on the retina. In a rod, light breaks rhodopsin into retinal and opsin; this closes cation (Na+) channels, so the rod hyperpolarises and stops releasing the neurotransmitter that inhibits the bipolar cell. The bipolar cell then depolarises and stimulates a ganglion cell, which fires action potentials along the optic nerve (optic neurones) to the visual cortex. Cones (3 types, concentrated in the fovea) work in a similar way and give colour vision.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Compare rods and cones.', 'Rods: high sensitivity (many to one bipolar -> retinal convergence); monochromatic; rhodopsin; concentrated outside fovea. Cones: low sensitivity, high acuity (1:1 to bipolar); iodopsin (3 colour types); concentrated in fovea.', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Outline learning and types of memory.', 'Sensory -> short-term -> long-term (consolidation). Habituation: decreased response to a repeated harmless stimulus (sea-slug Aplysia). Classical and operant conditioning. Memories stored across synapses; LTP strengthens connections.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Describe how drugs affect synapses (e.g. nicotine, MDMA, L-DOPA).', 'Nicotine: agonist of nicotinic ACh receptors -> stimulation; reward via dopamine. MDMA: floods synapses with serotonin (release + reuptake inhibition). L-DOPA: precursor of dopamine, crosses BBB to relieve Parkinson''s symptoms.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Describe the symptoms and cause of Parkinson''s disease.', 'Loss of dopaminergic neurones in the substantia nigra. Symptoms: tremor, rigidity, bradykinesia, postural instability. Treatments: L-DOPA, dopamine agonists, MAO-B inhibitors, deep brain stimulation. Causes: idiopathic, genetic factors, environmental.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Outline the imaging techniques: CT, MRI, fMRI, PET.', 'CT: X-ray slices -> structural images. MRI: magnetic field aligns nuclei -> high-resolution structural images, no ionising radiation. fMRI: detects blood-O2 changes (BOLD signal) -> activity. PET: radiolabelled tracers -> functional metabolism.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'S8', 'Grey Matter', 'Compare nature and nurture in shaping the brain.', 'Genes provide the basic neural framework (e.g. innate reflexes). Environment shapes synaptic connections, particularly in critical periods (e.g. visual deprivation in kittens). Both interact: brain plasticity allows learning throughout life.', 15, 'alevel');

-- CP — Core Practicals
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP1: investigate the effect of caffeine on heart rate in Daphnia.', 'Daphnia on a cavity slide under cotton wool strands, low power. Acclimatise 2 min; count beats in 20 s (x3 = bpm), three counts, mean. Add caffeine drops, wait 2 min, recount. Fresh Daphnia per concentration. IV: caffeine concentration (e.g. 0-0.5%); DV: heart rate (bpm); control temperature (LED light), acclimatisation time, volume added, Daphnia size. Ethics: fewest organisms, sub-lethal doses, minimal time on slide, return to pond water. Analysis: plot mean bpm vs concentration (positive correlation); Spearman''s rank. Caffeine inhibits phosphodiesterase, so cAMP stays high.', 1, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP2: investigate the vitamin C content of food and drink.', 'Pipette 1 cm³ DCPIP (blue) into a tube; add juice drop by drop from a burette or graduated pipette, swirling, against a white tile, until it turns colourless. Record volume; 3 repeats. Repeat with known ascorbic acid concentrations to make a calibration curve. IV: juice type or treatment (fresh, pasteurised, boiled); DV: volume to decolourise; control DCPIP volume and concentration, temperature, rate of addition. Safety: DCPIP stains, so gloves and eye protection. Analysis: less juice needed = more vitamin C; read concentration off the calibration curve by interpolation.', 2, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP3: investigate membrane permeability (effect of temperature or alcohol concentration).', 'Cut equal beetroot cylinders with a cork borer, trim to 1 cm; rinse in distilled water until clear. One per tube with 5 cm³ distilled water, 20 min in water baths at 20-70°C (or in 0-50% ethanol at one temperature). Remove beetroot, shake, read absorbance with a blue-green filter (~530 nm), zeroed with water. IV: temperature or ethanol %; DV: absorbance; control cylinder size, water volume, time. Safety: cut away from the body on a tile; tongs for hot tubes. Analysis: absorbance low to ~40°C then rises sharply as proteins denature and the bilayer becomes more fluid; ethanol disrupts the bilayer.', 3, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP4: investigate the effect of enzyme and substrate concentrations on the initial rate of reaction.', 'Catalase (equal-mass potato discs or fixed volume of liver homogenate) in a flask at 25°C. Add pre-warmed H₂O₂, bung at once, record O₂ in a gas syringe every 30 s for 5 min; 3 repeats. Vary H₂O₂ concentration (0.5-8%), or vary enzyme amount with substrate fixed. Control temperature, volumes, enzyme mass. Safety: H₂O₂ irritant, eye protection and gloves; no naked flames. Analysis: initial rate = gradient of tangent at t = 0. Rate vs [substrate] rises then plateaus at Vmax (active sites saturated); rate vs [enzyme] is proportional while substrate is in excess.', 4, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP5: prepare and stain a root tip squash to observe the stages of mitosis.', 'Cut 5 mm garlic or onion root tips; 1 mol dm⁻³ HCl at 55-60°C for ~5 min (stops division and breaks down the middle lamella). Rinse, keep only the terminal 1-2 mm (meristem). Add toluidine blue or acetic orcein, macerate, wait 2 min. Coverslip, filter paper, press firmly and vertically (no twisting) to give one cell layer. Find small square cells on low power; count cells in each stage on high power. Safety: HCl irritant, eye protection. Analysis: mitotic index = cells in mitosis ÷ total cells; time in a stage = proportion of cells x cycle time.', 5, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP6: identify sclerenchyma fibres, phloem sieve tubes and xylem vessels and their location in stems.', 'Cut very thin transverse sections of celery petiole or sunflower stem with a razor blade on a tile; keep in water. Stain in toluidine blue ~1 min, rinse, mount in water. Low power: draw a plan (tissue outlines only). High power: identify tissues. Xylem: towards the centre of each bundle, large empty lignified cells (blue-green). Phloem: outside the xylem, small thin-walled cells, no lignin (purple). Sclerenchyma: cap outside the phloem, very thick lignified walls, narrow lumen (blue-green). Safety: razor blades, cut away from fingers; stain gloves. Measure cells with a calibrated eyepiece graticule.', 6, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP7: investigate plant mineral deficiencies.', 'Grow equal numbers of similar duckweed plants (or seedlings) in equal volumes of culture solutions: complete, lacking nitrate, lacking magnesium, lacking calcium, plus distilled water. Cover containers, wrap in foil, same light and temperature; at least 3 replicates. Count fronds and note colour every few days for 2-3 weeks; weigh at the end. IV: solution; DV: frond number, colour, mass. Safety: low hazard, wash hands; keep light banks away from water. Analysis: complete solution grows most; no nitrate or Mg²⁺ gives yellow (chlorotic) fronds and less growth; compare means with a t-test.', 7, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP8: determine the tensile strength of plant fibres.', 'Extract single fibres (e.g. celery strings) carefully. Measure diameter at several points (calibrated graticule or callipers); A = πr². Clamp one end, hang a hook, add masses in 10 g steps, waiting ~10 s each, until it breaks. Test at least 10 fibres per type. Safety: tray or cushion under the masses; eye protection in case the fibre snaps and recoils. Analysis: force F = m (kg) x 9.81; tensile stress = F ÷ A (Pa or MPa). Compare species or plant parts; relate strength to cellulose microfibrils, secondary wall thickening and lignin. Report SD and range.', 8, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP9: investigate the antimicrobial properties of plants, including aseptic technique.', 'Grind equal masses of plants (e.g. garlic, mint) with equal volumes of ethanol; filter. Aseptically spread a non-pathogenic bacterium (e.g. Bacillus subtilis) as a lawn on nutrient agar. Soak sterile paper discs in each extract, let the ethanol evaporate, place on the agar with an ethanol-only control disc. Tape lid with two strips, incubate upside down at 25°C for 48 h. IV: plant extract; DV: area of clear zone. Safety: ethanol is highly flammable, keep away from the Bunsen; never open plates after incubation; autoclave before disposal. Analysis: area = πr²; compare means; the control should show no zone.', 9, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP10: ecology of a habitat using quadrats and transects, including abiotic factors.', 'Random sampling: two tapes at right angles make a grid; random coordinates; record count, percentage cover or ACFOR in each quadrat (10-30 quadrats). Transect along a gradient: quadrats at regular intervals (e.g. every 2 m); at each point measure light, temperature, soil moisture, pH at the same time of day; repeat 3 parallel transects. Safety: fieldwork risk assessment (terrain, water, weather), wash hands. Analysis: kite diagram of abundance with abiotic readings; Spearman''s rank to test for correlation; index of diversity D = N(N−1) ÷ Σn(n−1).', 10, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP11: investigate photosynthesis using isolated chloroplasts (the Hill reaction).', 'Blend spinach in ice-cold, isotonic, buffered isolation medium; filter through muslin; centrifuge at low then higher speed to pellet chloroplasts; resuspend and keep on ice in dim light. Mix equal volumes of chloroplast suspension and DCPIP; place at different distances from a lamp. Time loss of blue colour (or read absorbance with a red filter). Controls: tube in foil (dark); DCPIP with no chloroplasts. Control temperature (heat shield). Safety: DCPIP harmful, eye protection; balance the centrifuge. Analysis: rate = 1/time vs light intensity (∝ 1/d²); DCPIP replaces NADP as electron acceptor.', 11, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP12: investigate the effect of temperature on the initial rate of an enzyme-catalysed reaction, including Q₁₀.', 'Amylase and 1% starch in separate tubes in a water bath (20-60°C) for 5 min to equilibrate. Mix, start the stopwatch; every 30 s put a drop on iodine on a spotting tile. End-point: iodine stays yellow-brown (no starch). 3 repeats per temperature. IV: temperature; DV: time to end-point; control volumes, concentrations, pH. Safety: tongs for hot water baths; iodine stains, gloves. Analysis: rate = 1/t; bell-shaped curve with an optimum; above it the enzyme denatures. Q₁₀ = rate at (T + 10)°C ÷ rate at T°C, about 2 below the optimum.', 12, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP13: investigate the effect of temperature on the development of organisms.', 'Brine shrimp: equal volumes of artificial sea water at a range of temperatures (e.g. 10-30°C); add the same mass of cysts (e.g. 0.05 g), same light. Every 12-24 h stir gently, remove a fixed volume, count hatched larvae, return them. Continue 2-3 days; 3 repeats. Alternative: mean seedling shoot growth per day. IV: temperature; DV: number hatched (or growth rate); control cyst mass, salt concentration, light. Ethics and safety: treat shrimp with respect, small numbers; keep electrics away from water. Analysis: rate rises to an optimum then falls; Q₁₀; discuss links to climate change and limits of lab data.', 13, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP14: use gel electrophoresis to separate DNA fragments of different length.', 'Agarose gel in a tank with wells at the negative (cathode) end, covered in buffer. Mix restriction-digested DNA with loading dye and micropipette a fixed volume into each well without piercing it; include a DNA ladder. Lid on, run at low voltage until the dye front is near the end. Switch off, stain (e.g. methylene blue), measure well-to-band distances. Safety: only switch on with the lid on, disconnect before touching; gloves. Analysis: DNA is negative (phosphate) so moves to the anode; shorter fragments move further; size unknowns from a ladder calibration curve.', 14, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP15: investigate the effect of different antibiotics on bacteria.', 'Aseptically spread a non-pathogenic bacterium (e.g. E. coli K-12) evenly as a lawn on nutrient agar. With flamed forceps press antibiotic discs (or a multidisc) onto the agar, at least 25 mm apart. Tape lid with two strips (not sealed), label the base, incubate upside down at 25°C or below for 24-48 h. Measure zone diameters through the base without opening. IV: antibiotic; DV: area of zone of inhibition. Safety: never open plates after incubation; autoclave before disposal. Analysis: area = πr²; bigger zone = more effective (or better diffusion); cannot tell bactericidal from bacteriostatic.', 15, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP16: investigate rate of respiration.', 'Respirometer: soda lime at the bottom of each tube, cotton wool above, then germinating seeds; control tube with an equal volume of glass beads. Connect to a capillary with a coloured fluid drop; water bath, equilibrate 5 min. Record drop position every minute for 10-15 min; repeat at different temperatures. IV: temperature; DV: distance moved per minute. Safety: soda lime is corrosive, gloves and eye protection; keep it away from organisms. Analysis: soda lime absorbs CO₂, so movement shows O₂ uptake; volume = πr² x distance; subtract control; rate rises with temperature (Q₁₀ ≈ 2) until enzymes denature.', 16, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP17: investigate the effects of exercise on tidal volume, breathing rate, minute ventilation and O₂ consumption using spirometer traces.', 'Screen participants and get consent. With a nose clip and clean mouthpiece, record a spirometer trace at rest (spirometer filled with medical-grade O₂, fresh soda lime). Do standard exercise (e.g. step-ups to a metronome for 5 min); record immediately after and every minute in recovery. From the trace: tidal volume = trough-to-peak height; breathing rate = peaks per minute; minute ventilation = tidal volume x breathing rate; O₂ consumption = fall in trace volume per minute (soda lime removes CO₂). Safety: stop if dizzy or unwell. Analysis: all increase after exercise, as chemoreceptors detect raised CO₂.', 17, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Outline CP18: investigate habituation to a stimulus.', 'Snail on a damp surface, left until tentacles are fully out. Touch gently between the upper tentacles with a damp cotton bud; start the stopwatch; time until tentacles fully re-emerge. Repeat at the same place and pressure 10-15 times; repeat with other snails. IV: number of touches; DV: re-emergence time; control touch strength and position, interval, temperature, light, noise. Ethics: gentle touch, keep snails moist, fewest snails, return them. Analysis: plot mean time vs touch number; time falls; Spearman''s rank. Habituation: fewer Ca²⁺ channels open presynaptically, less neurotransmitter released.', 18, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Practical skills: how is a calibration curve made and used?', 'Measure the same quantity for a series of solutions of known concentration (e.g. volume of ascorbic acid standard needed to decolourise 1 cm³ DCPIP in CP2, or a DNA ladder''s band distances in CP14). Plot the known values and draw a line or curve of best fit. Measure the unknown sample in exactly the same way, then read its value off the curve by interpolation. Keep conditions (volumes, temperature, filter, gel and run time) the same for standards and unknowns. Only read values within the range of the standards.', 19, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Practical skills: why calculate standard deviation, and which statistical test fits which data?', 'Standard deviation measures the spread of repeat readings around the mean; a small SD means the data are more consistent (precise), and overlapping mean ± SD suggests a difference may not be significant. Report it with means (e.g. heart rates in CP1, fibre strength in CP8). Tests: Spearman''s rank for a correlation between two variables (CP1, CP10, CP18); a t-test to compare two means of normally distributed data (CP7); Mann-Whitney U to compare two groups otherwise. Compare the calculated value with the critical value at p = 0.05.', 20, 'alevel'),
  ('Biology', 'Edexcel A', 'CP', 'Core Practicals', 'Practical skills: how is an eyepiece graticule calibrated and used to measure cells?', 'Put a stage micrometer (known divisions, e.g. 10 μm) on the stage and line its scale up with the eyepiece graticule. Count how many eyepiece units match a known stage distance; length of 1 eyepiece unit = stage distance ÷ number of units. Recalibrate for every objective lens. Replace with the specimen, measure in eyepiece units and multiply by the calibrated value (e.g. xylem and sclerenchyma diameter in CP6, fibre diameter in CP8). Measure several cells and take a mean.', 21, 'alevel');

