-- A-Level Biology Flashcards (AQA, Edexcel A, Edexcel B, OCR A, OCR B)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- OCR B (Salters-Nuffield) A-LEVEL
-- ===============================================================

-- B1 — Development of Practical Skills
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Define independent, dependent and control variables.', 'IV: variable manipulated by the experimenter. DV: variable measured. Controls: variables held constant to ensure only the IV affects the DV. Without controls, observed changes can''t be attributed to the IV alone.', 1, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Distinguish accuracy, precision, reliability, validity.', 'Accuracy: closeness to true value. Precision: small spread between repeats. Reliability: same results on repetition. Validity: investigation answers the original question and only the IV affected the DV.', 2, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'How are random and systematic errors managed?', 'Random errors: repeat readings and average; use more precise instruments. Systematic errors: zero / calibrate the instrument; use different equipment or method. Repetition cannot reduce systematic errors.', 3, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Describe how to plan a controlled investigation.', 'Identify IV, DV and controls. Choose a measurable, sensitive method. Decide range and number of values; sample size; repeats. Risk assess (CLEAPSS, COSHH). Plan data table and graph. Pre-test or pilot to refine the method.', 4, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'How is uncertainty estimated for a single reading?', 'For analogue: half the smallest scale division. For digital: ±1 in the last digit. For repeated readings: half the range. Express as both absolute and percentage uncertainty.', 5, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Describe how percentage uncertainties combine.', 'Multiplied/divided quantities: add the percentage uncertainties. Powers: multiply by the index. Use to identify which measurement contributes most error and how to improve.', 6, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Outline how to use a t-test.', 'Compares two means of approximately normally distributed samples. Calculate t, find critical value at (n1 + n2 - 2) df, p = 0.05. If t > critical, reject H0 -> means significantly different.', 7, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Describe Spearman''s rank correlation.', 'Used to test whether two ranked variables are correlated. r_s = 1 - (6 sum d^2 / n(n^2 - 1)) where d = rank difference. Compare with critical value at n - 2 df. Values close to +1 / -1 = strong correlation.', 8, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Describe chi-squared (chi^2) goodness of fit.', 'chi^2 = sum ((O - E)^2 / E). Compare to critical value at (categories - 1) df, p = 0.05. If chi^2 > critical, reject H0 -> deviation from expected ratio is significant. Used in genetics, ecology.', 9, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Describe how to calculate and use standard deviation.', 'sigma = sqrt(sum((x - mean)^2) / (n - 1)). Quantifies the spread around the mean. Smaller sigma -> more precise data. Plotted as error bars on bar charts/scatter plots; non-overlapping error bars suggest a real difference.', 10, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'How are anomalous results identified and treated?', 'Plot data and inspect; values clearly outside the expected range are anomalies. Repeat to check. Exclude from mean calculations but record honestly. Investigate the source (procedural error, contamination, instrument issue).', 11, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Describe how a calibration curve is created and used.', 'Make standards of known concentration; measure response (e.g. absorbance). Plot calibration curve. Measure unknown sample under same conditions; read concentration off the line. Always include a blank for zeroing.', 12, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'How are scientific results communicated and referenced?', 'Use SI units, clear axis labels, key, error bars, statistical tests. Reference using Harvard or Vancouver style: cite primary literature. Distinguish your own data from cited claims. Include limitations and improvements.', 13, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'Outline ethical considerations in biological investigations.', 'Animal research: 3Rs (replace, reduce, refine), avoid suffering. Human studies: informed consent, anonymity, right to withdraw, ethical approval. Field studies: avoid habitat damage, follow protected-species laws.', 14, 'alevel'),
  ('Biology', 'OCR B', 'B1', 'Development of Practical Skills', 'List safety practices for biology practicals.', 'Wear lab coat, goggles, gloves where appropriate. Risk assess (HSE, CLEAPSS, COSHH). Aseptic technique near a Bunsen for microorganisms. No mouth-pipetting. Sharps disposal. Autoclave biological waste.', 15, 'alevel');

-- B2 — Cells, Chemicals and Transport
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Compare prokaryotic and eukaryotic cells.', 'Prokaryotes: smaller (~1-5 µm), no nucleus, circular naked DNA, 70S ribosomes, no membrane-bound organelles, peptidoglycan wall, may have plasmids/capsule/flagella. Eukaryotes: larger (~10-100 µm), nucleus, linear DNA + histones, 80S ribosomes, membrane-bound organelles.', 1, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Describe the role of the major eukaryotic organelles.', 'Nucleus: stores DNA, transcription. Mitochondrion: aerobic respiration. Chloroplast: photosynthesis. RER: protein synthesis. SER: lipid synthesis. Golgi: modifies/packages proteins. Lysosomes: digestion. Ribosomes (80S): translation.', 2, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Compare TEM and SEM.', 'TEM: thin specimen, electrons pass through, very high resolution (~0.2 nm), 2D internal structure. SEM: surface scanned, lower resolution, 3D surface image. Both: vacuum, dead specimens, prone to artefacts.', 3, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Why is water described as a polar molecule, and how does this give rise to its properties?', 'Oxygen is more electronegative than hydrogen, so the O end is delta-negative and the H ends are delta-positive. Water molecules form hydrogen bonds, giving high specific heat capacity, latent heat of vaporisation, cohesion, and excellent solvent properties.', 4, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Describe how a glycosidic bond forms between two monosaccharides.', 'Two -OH groups react; one H and one OH are removed as water (condensation). The bond is named by the carbon atoms it links, e.g. alpha-1,4 glycosidic in maltose. Hydrolysis (water added) breaks the bond.', 5, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Compare starch, glycogen and cellulose.', 'Starch (alpha-1,4 + 1,6, plant store): amylose helical, amylopectin branched -> compact. Glycogen (alpha, animal store): more highly branched -> rapid hydrolysis. Cellulose (beta-1,4, alternating orientation): straight chains, H-bonded into microfibrils -> tensile strength.', 6, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Describe the four levels of protein structure.', 'Primary: amino acid sequence (peptide bonds). Secondary: alpha helix / beta pleated sheet (H-bonds between C=O and N-H). Tertiary: 3D fold (H-bonds, ionic, disulfide, hydrophobic). Quaternary: 2+ subunits (e.g. haemoglobin: 4 chains + haem).', 7, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Describe the structure of a DNA nucleotide and the formation of a polynucleotide.', 'Nucleotide = phosphate + deoxyribose + base (A/T/C/G). Nucleotides join 5'' to 3'' by phosphodiester bonds (condensation). Two antiparallel strands wind into a double helix held by H-bonds (A=T, G≡C).', 8, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Explain induced-fit enzyme catalysis.', 'Substrate binds the active site; enzyme subtly changes shape so the active site moulds tightly around the substrate. This places strain on bonds in the substrate, lowering Ea. Enzyme returns to original shape after products leave.', 9, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Compare competitive and non-competitive inhibitors.', 'Competitive: similar shape to substrate, binds active site; effect overcome by raising [substrate]. Non-competitive: binds an allosteric site, distorts the active site so substrate cannot bind; effect not overcome by raising [substrate].', 10, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Describe the fluid-mosaic model.', 'A phospholipid bilayer with proteins (channels, carriers, receptors) embedded in the fluid. Glycoproteins/glycolipids for cell signalling and recognition. Cholesterol regulates fluidity. Hydrophilic heads outwards, hydrophobic tails inwards.', 11, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Compare diffusion, facilitated diffusion, osmosis and active transport.', 'Diffusion: passive, no protein. Facilitated diffusion: passive, via channel/carrier proteins. Osmosis: passive, water down a water-potential gradient. Active transport: ATP-driven, against gradient via carrier proteins.', 12, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Define water potential and predict cell behaviour.', 'Water potential = pressure exerted by water molecules; pure water = 0 kPa, solutions are negative. Animal cells: lyse in hypotonic solution, crenate in hypertonic. Plant cells: turgid in hypotonic (cell wall resists), plasmolysed in hypertonic.', 13, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Explain co-transport of glucose into ileum epithelial cells.', 'Na+/K+ pump on basal membrane uses ATP to pump Na+ out, lowering Na+ in cell. Na+ then re-enters with glucose via a co-transporter on the apical surface (down its gradient). Glucose then leaves into the blood by facilitated diffusion.', 14, 'alevel'),
  ('Biology', 'OCR B', 'B2', 'Cells, Chemicals and Transport', 'Describe gas exchange in mammalian alveoli.', 'Many alveoli (large total SA ~70 m^2), squamous epithelium one cell thick (short diffusion path), surrounded by capillaries (gradient maintained by ventilation and circulation), thin film of fluid for dissolved gases, surfactant lowers surface tension.', 15, 'alevel');

-- B3 — Cell Division, Development and Disease
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Describe the eukaryotic cell cycle.', 'G1: cell growth, organelle replication. S: DNA replication. G2: further growth, error check. M: mitosis (PMAT). Cytokinesis. Checkpoints (G1/S, G2/M, spindle) prevent damaged cells progressing.', 1, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Outline the four stages of mitosis.', 'Prophase: chromosomes condense, nuclear envelope breaks down, centrioles move to poles. Metaphase: chromosomes align on equator. Anaphase: spindle pulls sister chromatids to poles. Telophase: nuclear envelopes reform.', 2, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Compare mitosis and meiosis.', 'Mitosis: 1 division, 2 diploid identical daughter cells, growth/repair. Meiosis: 2 divisions, 4 haploid genetically distinct gametes, with independent assortment and crossing over. Source of genetic variation -> evolution.', 3, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Describe two sources of genetic variation in meiosis.', 'Independent assortment of homologous chromosomes (metaphase I) and sister chromatids (metaphase II). Crossing over: in prophase I, non-sister chromatids exchange DNA at chiasmata, producing new allele combinations.', 4, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Define totipotent, pluripotent, multipotent, unipotent.', 'Totipotent: any cell type incl. extra-embryonic. Pluripotent: any embryonic cell type. Multipotent: limited types (e.g. haematopoietic). Unipotent: one type (e.g. cardiac muscle progenitor).', 5, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Outline how stem cells differentiate.', 'Differentiation results from selective gene expression. Specific transcription factors activate cell-type-specific genes; epigenetic changes (DNA methylation, histone modification) silence others. Position-dependent signals (morphogens) and microenvironment guide specialisation.', 6, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Outline the benefits and ethical issues of using human embryonic stem cells.', 'Benefits: pluripotent -> potential regenerative therapies (Parkinson''s, spinal injury). Ethics: destruction of embryos; iPS cells offer an alternative with fewer concerns. Strict regulation by HFEA in the UK.', 7, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Describe how oncogenes and tumour suppressor genes lead to cancer.', 'Proto-oncogenes regulate cell division; mutation makes them constitutively active oncogenes -> uncontrolled division. Tumour suppressor genes (e.g. p53) normally pause the cycle; loss-of-function mutations remove this brake. Both contribute to malignant tumours.', 8, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Compare benign and malignant tumours.', 'Benign: slow-growing, encapsulated, do not metastasise (e.g. lipoma). Malignant: rapid, invade tissues, metastasise via blood or lymph. Multiple gene mutations needed; many cancers also show altered DNA methylation patterns (epigenetic).', 9, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Compare innate (non-specific) and specific immune responses.', 'Innate: skin, mucus, lysozyme, phagocytosis, inflammation, fever. Fast but non-specific. Specific: B cells (antibodies), T helpers, T killers, memory cells. Slower at first exposure but produces immunological memory.', 10, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Describe phagocytosis.', 'Phagocyte chemotaxes towards pathogen, recognises by receptors, engulfs by endocytosis -> phagosome. Lysosomes fuse with phagosome -> phagolysosome; lysozyme digests pathogen. Antigens displayed on MHC II for T-cell activation.', 11, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Outline vaccination and herd immunity.', 'Vaccines contain weakened/inactivated pathogens or antigens, triggering primary response and memory cells. If high enough proportion vaccinated, pathogen cannot spread, protecting unvaccinated (herd immunity). Threshold depends on R0.', 12, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Compare bacterial, viral, fungal and protoctist diseases with examples.', 'Bacterial: TB (M. tuberculosis). Viral: HIV. Fungal: athlete''s foot (Tinea); plant — black sigatoka. Protoctist: malaria (Plasmodium); potato late blight.', 13, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'How do antibiotics work and how does resistance arise?', 'Bactericidal (penicillin: weakens peptidoglycan -> lysis) or bacteriostatic (tetracyclines: block 70S ribosomes). Resistance: random mutations -> resistant variants survive and reproduce; resistance genes spread by plasmid conjugation. Misuse accelerates this.', 14, 'alevel'),
  ('Biology', 'OCR B', 'B3', 'Cell Division, Development and Disease', 'Describe how malaria is transmitted and prevented.', 'Plasmodium parasites transmitted by female Anopheles mosquito biting. Inside the host, multiplies in liver then RBCs, causing fever cycles. Prevention: insecticide-treated nets, indoor spraying, antimalarials, drainage of standing water, vaccines (RTS,S).', 15, 'alevel');

-- B4 — Energy, Reproduction and Populations
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Write the photosynthesis equation and identify oxidation/reduction.', '6CO2 + 6H2O -> C6H12O6 + 6O2 (sunlight, chlorophyll). CO2 is reduced (gains H/electrons) to glucose; H2O is oxidised to O2 in photolysis at PSII.', 1, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Outline the light-dependent reactions.', 'Photolysis at PSII: 2H2O -> 4H+ + 4e- + O2. Excited e- pass down ETC, pumping H+ into thylakoid lumen. Chemiosmosis: H+ flow back through ATP synthase -> ATP. NADP+ + H+ + 2e- -> NADPH. Cyclic photophosphorylation produces only ATP.', 2, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Describe the Calvin cycle.', 'CO2 + RuBP (5C) -> 2 GP (3C) (catalysed by RuBisCO). GP reduced to TP using ATP and NADPH. Some TP forms hexose; most regenerates RuBP using ATP. Six turns yield one glucose.', 3, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'How do CO2, light and temperature affect photosynthesis?', 'Each can be a limiting factor when in shortest supply. Low light: rate limited by photolysis. Low CO2: rate limited by Calvin cycle. Below optimum T: enzymes slow; above ~30 °C: RuBisCO denatures, stomata close.', 4, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'List the four stages of aerobic respiration with location.', 'Glycolysis (cytoplasm), link reaction (matrix), Krebs cycle (matrix), oxidative phosphorylation / ETC (inner mitochondrial membrane / cristae).', 5, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Outline glycolysis.', 'Glucose phosphorylated using 2 ATP -> hexose bisphosphate -> 2 triose phosphate. Each TP oxidised to pyruvate; net 2 ATP and 2 NADH per glucose. Anaerobic; in cytoplasm.', 6, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Describe the link reaction and Krebs cycle.', 'Link: 2 pyruvate -> 2 acetyl-CoA + 2 CO2 + 2 NADH. Krebs (x2): each acetyl-CoA + 4C -> 6C; decarboxylation/dehydrogenation give 2 CO2, 3 NADH, 1 FADH2 and 1 ATP per turn (per glucose: 4 CO2, 6 NADH, 2 FADH2, 2 ATP).', 7, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Explain oxidative phosphorylation by chemiosmosis.', 'NADH/FADH2 deliver e- to ETC on inner membrane. As electrons pass between carriers, H+ is pumped to the intermembrane space. H+ flows back through ATP synthase -> ATP. O2 is final acceptor: O2 + 4H+ + 4e- -> 2H2O. Theoretical yield ~32 ATP per glucose.', 8, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Compare lactate and ethanol fermentation.', 'Animals: pyruvate + NADH -> lactate + NAD+; reversible (lactate cleared in liver -> oxygen debt). Yeast/plants: pyruvate -> ethanal + CO2 -> ethanol + NAD+; irreversible. Both regenerate NAD+ for glycolysis to continue without O2.', 9, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Define an ecosystem and describe energy flow.', 'Ecosystem = community + abiotic environment. Energy enters as light, captured by producers (NPP), passes to herbivores and carnivores. Loss at each level: respiration, heat, faeces, excretion. ~10% transfer typical -> short food chains.', 10, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Define GPP, NPP and their relationship.', 'GPP = total chemical energy fixed by producers per area per time. NPP = GPP - R (respiratory loss). Units: kJ m^-2 yr^-1. NPP is energy available to next trophic level.', 11, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Outline the carbon and nitrogen cycles.', 'Carbon: photosynthesis fixes CO2; respiration, combustion and decomposition return it. Nitrogen: saprobionts -> NH4+; nitrifiers -> NO2- -> NO3-; nitrogen-fixing bacteria N2 -> NH3; denitrifiers reduce NO3- -> N2 in anaerobic soils.', 12, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Compare carrying capacity and density-dependent / -independent factors.', 'Carrying capacity: maximum population an environment can sustain. Density-dependent: food, predation, disease (act more strongly as density rises). Density-independent: drought, fire, flooding (act regardless of density).', 13, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Describe primary succession from bare rock to climax community.', 'Pioneer species (lichens) colonise bare rock, weather it and add organic matter. Mosses follow, then small plants, grasses, shrubs and finally woodland (climax). Each stage modifies the abiotic conditions for the next.', 14, 'alevel'),
  ('Biology', 'OCR B', 'B4', 'Energy, Reproduction and Populations', 'Outline Darwin''s theory of natural selection.', '1) Variation within a population. 2) More offspring produced than survive. 3) Individuals with advantageous alleles more likely to survive and reproduce. 4) These alleles increase in frequency over generations -> evolution.', 15, 'alevel');

-- B5 — Genetics, Control and Homeostasis
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe semi-conservative DNA replication.', 'Helicase unwinds the helix; H-bonds break. Free DNA nucleotides align with their complement on each parental template. DNA polymerase joins them by phosphodiester bonds (5''-3''). Each daughter molecule has one parental and one new strand.', 1, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Outline transcription and post-transcriptional modification.', 'Gene unwinds; RNA polymerase joins free RNA nucleotides to a template strand (U replaces T) -> pre-mRNA. Splicing removes introns; exons rejoin. 5'' cap and poly-A tail added. Mature mRNA exits via nuclear pore.', 2, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe translation step by step.', 'mRNA binds the small ribosomal subunit; tRNA carrying methionine binds AUG. Next tRNA (anticodon complementary to next codon) binds; peptide bond forms. Ribosome translocates one codon. Continues until a stop codon -> polypeptide released.', 3, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe how transcription factors regulate gene expression.', 'Transcription factors bind specific promoter sequences and either recruit (activators) or block (repressors) RNA polymerase. They are produced in response to internal/external signals, ensuring only relevant genes are transcribed in a given cell type.', 4, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Distinguish DNA methylation and histone modification (epigenetics).', 'DNA methylation: -CH3 added to cytosine, typically silences transcription. Histone acetylation: loosens DNA-histone binding -> easier transcription. Histone methylation can either activate or silence depending on residue. Reversible and inheritable.', 5, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe a monohybrid and a dihybrid cross.', 'Mono: Aa x Aa -> 3:1 dominant:recessive. Di: AaBb x AaBb -> 9:3:3:1 (assuming no linkage). Use Punnett squares to predict ratios; chi-squared tests if observed differs significantly from expected.', 6, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Explain codominance and the ABO blood system.', 'I^A and I^B alleles are codominant (both expressed in heterozygotes -> AB blood). I^O is recessive. Genotypes: I^A I^A or I^A I^O = A; I^B I^B or I^B I^O = B; I^A I^B = AB; I^O I^O = O.', 7, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe sex linkage with haemophilia.', 'Allele on X chromosome (X^h, recessive). Females need two X^h to be affected; one X^h makes a carrier. Males with X^h Y are hemizygous and affected. Hence haemophilia much more common in males.', 8, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'State the Hardy-Weinberg equations and assumptions.', 'p + q = 1; p^2 + 2pq + q^2 = 1. Assumes large population, random mating, no migration / mutation / selection. Useful for estimating carrier frequencies (e.g. cystic fibrosis).', 9, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Explain the resting potential and an action potential.', 'Resting: Na+/K+ pump (3 Na+ out / 2 K+ in) plus K+ leak channels -> -70 mV. AP: stimulus -> Na+ channels open (depolarisation to +40 mV) -> Na+ close, K+ open (repolarisation) -> hyperpolarisation -> Na+/K+ pump restores resting.', 10, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe synaptic transmission at a cholinergic synapse.', 'AP arrives -> Ca2+ channels open -> Ca2+ enters -> vesicles fuse with membrane and release ACh. ACh binds postsynaptic receptors, opens Na+ channels. Acetylcholinesterase hydrolyses ACh; choline recycled.', 11, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe how insulin and glucagon regulate blood glucose.', 'Beta cells release insulin: more GLUT4 transporters -> glucose uptake; activates glycogen synthase -> glycogenesis. Alpha cells release glucagon: cAMP second messenger -> phosphorylates glycogen phosphorylase -> glycogenolysis -> glucose released to blood.', 12, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe ultrafiltration and selective reabsorption in the nephron.', 'Glomerulus: high BP forces small molecules through fenestrated capillaries, basement membrane, and podocyte slits into Bowman''s capsule. PCT: Na+ pumped out into blood; Na+ re-enters with glucose / amino acids by co-transport; water follows osmotically.', 13, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Outline ADH control of water balance.', 'High blood solute concentration -> osmoreceptors in hypothalamus stimulate posterior pituitary to release ADH -> binds collecting duct receptors -> aquaporins inserted -> more water reabsorbed -> small volume of concentrated urine.', 14, 'alevel'),
  ('Biology', 'OCR B', 'B5', 'Genetics, Control and Homeostasis', 'Describe thermoregulation in mammals.', 'Hypothalamus monitors blood T. Too cold: vasoconstriction, shivering, hair erected, thyroxine release. Too hot: vasodilation, sweating, hair flattens. Behavioural responses (seek shade, change posture) supplement physiological control.', 15, 'alevel');

-- B6 — Biotechnology, Ecosystems and Human Impact
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Describe how restriction enzymes and ligase build recombinant DNA.', 'Restriction endonucleases cut DNA at palindromic sequences leaving sticky ends. The same enzyme used on the gene and the vector creates complementary ends. DNA ligase forms phosphodiester bonds between them, producing recombinant DNA.', 1, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Outline gene cloning using a bacterial plasmid.', 'Cut gene and plasmid with the same restriction enzyme -> complementary sticky ends. DNA ligase joins gene into plasmid -> recombinant DNA. Plasmid taken up by host bacterium (CaCl2 + heat shock). Marker genes identify successful uptake.', 2, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Outline polymerase chain reaction (PCR).', 'Cycles: 95 °C denature, ~55 °C anneal primers, 72 °C extend with Taq polymerase. Each cycle doubles DNA -> 2^n copies after n cycles. Used in cloning, sequencing and DNA profiling.', 3, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Outline DNA profiling using STRs.', 'Extract DNA, amplify short tandem repeat (STR) regions by PCR, separate fragments by gel/capillary electrophoresis. Each individual has a near-unique STR profile -> banding pattern. Used in identification, paternity, forensics.', 4, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Describe gel electrophoresis principles.', 'DNA fragments are loaded into wells in agarose; an electric field pulls negatively charged DNA towards the anode. Smaller fragments move further. Bands are visualised with UV after staining (e.g. ethidium bromide). Compared to a marker / reference ladder.', 5, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Outline how to make recombinant insulin.', 'Reverse transcriptase converts insulin mRNA from human pancreas to cDNA. Sticky ends added (RE) and ligated into a plasmid vector. E. coli host transformed; selected with antibiotic-resistance markers. Bacteria cultured; insulin extracted and purified.', 6, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Compare somatic and germline gene therapy.', 'Somatic: alters body cells of an individual (e.g. CFTR delivered to lung cells in CF) — not heritable. Germline: alters egg/sperm/embryo so changes are passed on; banned in humans for ethical reasons.', 7, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Outline CRISPR-Cas9 gene editing.', 'A guide RNA matches the target DNA sequence; Cas9 nuclease cuts both strands. The cell repairs the break, either by error-prone NHEJ (knock-out) or by homology-directed repair using a donor template (precise edit).', 8, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Compare natural and artificial cloning of plants and animals.', 'Plants: vegetative propagation (runners), tissue culture (totipotent cells -> callus -> plantlets). Animals: identical twins (natural); artificial: nuclear transfer (Dolly, somatic cell nuclear transfer); embryo splitting in livestock.', 9, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Compare batch and continuous fermentation.', 'Batch: nutrients added once, products accumulate; reactor cleaned between runs. Useful for secondary metabolites (penicillin). Continuous: nutrients added and product removed throughout; ideal for primary metabolites (e.g. enzymes); more efficient.', 10, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Describe immobilised enzymes and one advantage.', 'Enzymes bound to or trapped within a solid support (alginate beads, gel, membrane). Reusable, easier product separation, more stable to T/pH. Used in industrial processes (glucose isomerase, lactose-free milk).', 11, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Describe the carbon cycle and human impact.', 'Photosynthesis fixes CO2; respiration, combustion and decomposition return it. Carbon stored in biomass, soil, oceans, fossil fuels. Human burning of fossil fuels and deforestation increases atmospheric CO2 -> enhanced greenhouse effect -> global warming.', 12, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'List evidence for climate change.', 'Direct: ice core CO2 / temperature, atmospheric CO2 (Mauna Loa), satellite data, sea-level rise, glacier retreat. Indirect: dendrochronology, pollen analysis, isotope ratios. Multiple independent lines converge on warming.', 13, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Describe how rising temperatures affect species distribution.', 'Species shift poleward and upward in altitude as temperatures rise; phenological mismatches occur (flowering vs pollinators); range contractions if no migration possible (e.g. mountain-top species). Loss of habitat and mismatched timing reduce reproductive success.', 14, 'alevel'),
  ('Biology', 'OCR B', 'B6', 'Biotechnology, Ecosystems and Human Impact', 'Compare in situ and ex situ conservation.', 'In situ: protect species in natural habitat (national parks). Preserves ecological interactions but vulnerable to disasters. Ex situ: zoos, seed banks, botanical gardens. Controlled but smaller gene pool, risk of inbreeding.', 15, 'alevel');

-- PA — OCR B Practical Activities
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 1: microscopy and measuring cells.', 'Calibrate eyepiece graticule against a stage micrometer at each magnification. Mount specimen, focus low power first. Measure cells in graticule divisions, then convert using calibration. Calculate magnification (image / actual).', 1, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 2: dissection of an organ (e.g. heart).', 'Pin out external features, identify chambers and vessels. Cut along septum; observe atria (thinner walls), ventricles (thicker, especially LV), AV and SL valves, papillary muscles and chordae tendineae. Sharps disposal; gloves.', 2, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 3: sampling organisms in a habitat.', 'Random sampling: random coordinates with quadrats. Systematic: line/belt transect across an environmental gradient. Calculate species frequency, percentage cover and density. Mark-release-recapture for mobile organisms: N = (n1 x n2) / m.', 3, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 4: chromatography of plant pigments.', 'Grind leaves with sand and propanone. Spot solvent front on chromatography paper, spot pigments, place in solvent. Calculate Rf = distance moved by spot / distance moved by solvent. Compare Rf to known pigments (chlorophyll a, b, carotene, xanthophyll).', 4, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 5: investigating enzyme activity.', 'Use catalase + H2O2 (gas syringe collects O2) or amylase + starch (iodine end-point on tile). Vary T, pH or [substrate]. Plot rate vs IV. Control: [enzyme], buffers, mixing time. Determine optimum and explain via active-site shape.', 5, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 6: investigating osmosis.', 'Cut equal-mass potato cylinders. Place in solutions of varied [sucrose]. After fixed time, blot and reweigh. Plot % change in mass vs [sucrose]. Where mass change = 0, water potential of potato = solution. Control T, time, surface area.', 6, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 7: investigating photosynthesis.', 'Submerge pondweed (Cabomba/Elodea) in NaHCO3 solution (CO2 source). Vary light intensity (lamp distance) or wavelength (filters). Count bubbles per minute or use a gas syringe. Plot rate vs intensity. Control T, [CO2], pH.', 7, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 8: investigating respiration.', 'Place germinating peas with KOH (CO2 absorber) in sealed tube; manometer fluid moves as O2 consumed. Use thermostatically controlled bath. Control: glass beads (no respiration). Calculate volume of O2 used per unit time per gram of organism. <svg viewBox="0 0 220 90" width="200" height="80" style="display:block;margin:6px auto"><rect x="20" y="25" width="60" height="40" fill="none" stroke="#0B1E3F" stroke-width="1.5"/><text x="36" y="48" font-size="9" fill="#0B1E3F">seeds</text><text x="32" y="60" font-size="8" fill="#0B1E3F">+ KOH</text><line x1="80" y1="45" x2="200" y2="45" stroke="#0B1E3F" stroke-width="1.5"/><circle cx="120" cy="45" r="3" fill="#A33"/><text x="100" y="35" font-size="9" fill="#0B1E3F">manometer</text><text x="115" y="60" font-size="9" fill="#A33">droplet</text></svg>', 8, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 9: aseptic microbiology techniques.', 'Sterilise loop in flame, work near a Bunsen, lift agar lid only briefly. Spread bacterial culture, place soaked discs of antimicrobials. Incubate <25 °C. Measure zones of inhibition (diameter or area). Larger zone = greater antimicrobial activity.', 9, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Outline Practical 10: gel electrophoresis.', 'Prepare agarose gel; load DNA samples + loading dye into wells. Apply voltage; DNA migrates towards anode (negatively charged). Smaller fragments move further. Stain (e.g. ethidium bromide) and visualise under UV. Compare to ladder for sizing.', 10, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 11: heart rate and ventilation during exercise.', 'Record resting heart rate and breathing rate. Subject exercises (steady cycle / step) for 3-5 min; record during recovery. Plot rate vs time. Use a pulse oximeter / spirometer. Control fitness level, pre-test rest period.', 11, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'Describe Practical 12: plant tropisms.', 'Grow seedlings (e.g. cress) in different light conditions: unilateral light, dark, all-around light. Measure curvature of stems and roots. Positive phototropism in shoots; negative phototropism in roots. Control: T, water, type of seed.', 12, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'How is a serial dilution prepared accurately?', 'Pipette equal volumes (e.g. 1 cm^3) of stock into test tubes. Add equal volumes of solvent (e.g. 9 cm^3 distilled water) to each. Mix between transfers. This creates a 10-fold dilution series. Use a fresh pipette tip each time to prevent cross-contamination.', 13, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'How is a colorimeter used in biology?', 'Choose a filter complementary to the solution colour (e.g. red for blue solution). Zero with a blank. Make standards of known concentration; plot calibration curve of absorbance vs [conc]. Read unknown concentration off curve from its absorbance.', 14, 'alevel'),
  ('Biology', 'OCR B', 'PA', 'Practical Activities', 'How is data analysed and a conclusion drawn?', 'Plot graph (line / scatter / bar / histogram); identify pattern. Calculate gradient / rate / mean / SD. Apply statistical test (t-test, chi^2, Spearman) at p = 0.05. Conclusion: link to hypothesis; consider limitations and improvements.', 15, 'alevel');
