-- A-Level Computer Science Flashcards (OCR + AQA)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.

-- ---------------------------------------------------------------
-- Schema migration: add 'level' column if not present (idempotent)
-- ---------------------------------------------------------------
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'alevel'
  CHECK (level IN ('gcse','as','alevel'));


-- ===============================================================
-- OCR A-LEVEL
-- ===============================================================

-- Topic 1.1 — Characteristics of Processors, I/O & Storage
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What is the Von Neumann architecture?', 'A CPU design where program instructions and data are stored in the same memory and accessed via a single shared bus, executed sequentially using the stored-program concept.', 1, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'How does Harvard architecture differ from Von Neumann?', 'Harvard uses physically separate memories and buses for instructions and data, allowing simultaneous fetch of an instruction and data. Common in microcontrollers and DSPs.', 2, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What is the Von Neumann bottleneck?', 'Because instructions and data share one bus, only one can be transferred at a time, limiting CPU throughput.', 3, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What does the ALU do?', 'The Arithmetic Logic Unit performs arithmetic (ADD, SUB, MUL, shifts) and logical (AND, OR, NOT, XOR) operations and sets status register flags.', 4, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What is the difference between MAR and MDR?', 'MAR (Memory Address Register) holds the address being placed on the address bus. MDR (Memory Data Register) buffers the data/instruction travelling on the data bus.', 5, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'List the three steps of the Fetch phase using register transfer notation.', 'MAR <- [PC]; PC <- [PC] + 1; MDR <- [Memory[MAR]]; CIR <- [MDR].', 6, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What does the address bus width determine?', 'It determines the maximum addressable memory: an n-bit address bus can address 2^n locations.', 7, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'How does pipelining improve performance?', 'It overlaps the fetch, decode and execute stages of consecutive instructions so that one instruction completes per clock cycle once the pipeline is full, increasing throughput.', 8, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'Name three types of pipeline hazard.', 'Data hazards (instruction needs an unfinished result), control hazards (branch outcome unknown), and structural hazards (two instructions need the same hardware).', 9, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'Compare CISC and RISC instruction sets.', 'CISC has many complex variable-length instructions (e.g. x86) suited to dense code; RISC has few simple fixed-length instructions executing in one cycle (e.g. ARM), suited to deep pipelining and lower power.', 10, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What is locality of reference?', 'The empirical observation that programs tend to re-use the same memory locations (temporal) or nearby ones (spatial), which is exploited by caches.', 11, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'Why are GPUs effective for machine learning?', 'GPUs have thousands of simple SIMD cores that execute the same instruction on different data simultaneously, perfectly matching the large matrix multiplications in neural-network training.', 12, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'How does an SSD store data?', 'In NAND flash memory, where trapped charge in floating-gate transistors represents bits. A controller manages reads, writes and wear-levelling.', 13, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'Why does a computer need both RAM and ROM?', 'ROM is non-volatile and holds boot firmware needed at power-on. RAM is fast and rewritable, providing volatile working memory for the OS and applications once running.', 14, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'What is virtual storage (in OCR 1.1.3)?', 'Storage that appears local but is provided by remote/distributed servers (e.g. Google Drive, Dropbox), abstracted behind a uniform interface and accessed over a network.', 15, 'alevel'),
  ('Computer Science', 'OCR', '1.1', 'Characteristics of Processors, I/O & Storage', 'Distinguish throughput from latency.', 'Throughput is the number of operations completed per unit time. Latency is the time taken for one operation to complete from start to finish.', 16, 'alevel');

-- Topic 1.2 — Software and Software Development
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What three umbrella purposes does an operating system serve?', 'Abstraction (hide hardware complexity), resource management (arbitrate CPU/memory/I/O), and security & user management (authentication, isolation, permissions).', 1, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What is the kernel?', 'The privileged core of the OS that manages processes, memory, interrupts and I/O. It runs in kernel mode; all other OS components rely on it.', 2, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'Define paging.', 'A memory-management technique that divides RAM into fixed-size frames and each process''s virtual address space into equally sized pages, mapped by a per-process page table.', 3, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What is virtual memory?', 'A technique that uses secondary storage (a swap/page file) to extend apparent RAM. A page fault occurs when an accessed page is on disk and must be paged in.', 4, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What is an interrupt?', 'A signal to the CPU from hardware or software that an event needs attention. The CPU saves state, runs an Interrupt Service Routine, then resumes the original task.', 5, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'How does Round Robin scheduling work?', 'Each ready process runs for a fixed time quantum in turn, then is preempted. It is fair and gives good response time but performance depends on quantum size.', 6, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What is a real-time operating system (RTOS)?', 'An OS that guarantees a response within strict time limits; correctness depends on when as well as what. Used in ABS controllers, pacemakers and industrial robots.', 7, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What is intermediate code (bytecode)?', 'Platform-neutral code produced by a compiler and executed by a process VM (e.g. JVM, .NET CLR). It can be interpreted or JIT-compiled to native code at runtime.', 8, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'Compare a compiler with an interpreter.', 'A compiler translates the entire program once into machine code; the result runs fast. An interpreter translates and executes line by line each run, slower but with quicker debugging and portability.', 9, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'List the four stages of compilation in order.', 'Lexical analysis (tokens), syntax analysis (AST), semantic analysis (intermediate representation/type checking), and code generation with optimisation.', 10, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What does a linker do?', 'Combines object files and library code into a single executable, resolving symbolic references between modules. Static linking embeds libraries; dynamic linking resolves them at load/run time.', 11, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'When is the Waterfall methodology most suitable?', 'For projects with fixed, well-understood requirements such as safety-critical, regulated or government systems, where each stage can be signed off before the next begins.', 12, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'What characterises Agile development?', 'Iterative development in short sprints producing working software, with continuous customer collaboration and the ability to embrace changing requirements.', 13, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'Distinguish alpha and beta testing.', 'Alpha testing is internal, performed by the development organisation. Beta testing is external, performed by selected end-users on real hardware to find issues that emerge at scale.', 14, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'Describe indirect addressing mode.', 'The operand is the address of a memory location whose contents are themselves the address of the actual data — two memory hops to retrieve the value.', 15, 'alevel'),
  ('Computer Science', 'OCR', '1.2', 'Software and Software Development', 'Name the four pillars of object-oriented programming.', 'Encapsulation, inheritance, polymorphism and abstraction.', 16, 'alevel');

-- Topic 1.3 — Exchanging Data
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'When should you choose lossless over lossy compression?', 'When every bit must be preserved — e.g. text, source code, executables, spreadsheets and databases. Lossy is only acceptable where small perceptual errors are tolerable (images, audio, video).', 1, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'How does Run-Length Encoding (RLE) work?', 'It replaces consecutive runs of the same value with a (value, count) pair. Effective when long repeated runs exist (bitmaps, fax images), poor on natural-language text.', 2, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'Outline how Huffman coding builds its tree.', 'Place each symbol in a priority queue ordered by frequency. Repeatedly merge the two lowest-frequency nodes under a parent (sum of frequencies) until one root remains. Left edges = 0, right = 1; the path from root to a leaf gives the code.', 3, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'Compare symmetric and asymmetric encryption.', 'Symmetric uses one shared key for encrypt and decrypt — fast but suffers from key distribution. Asymmetric uses a public/private key pair: anyone can encrypt with the public key but only the private key decrypts. Slow but solves key distribution.', 4, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'What three guarantees does a digital signature provide?', 'Authenticity (only the sender''s private key could sign it), integrity (any change alters the hash) and non-repudiation (the sender cannot deny signing).', 5, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'Why are passwords stored as salted hashes rather than encrypted?', 'Hashing is one-way, so a database leak does not reveal the originals. A unique salt per user ensures identical passwords produce different hashes, defeating rainbow-table attacks.', 6, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'What is a primary key?', 'A field (or combination) that uniquely identifies each record in a table. It must be unique and not NULL.', 7, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'State the requirement for Third Normal Form (3NF).', 'The database is in 2NF and contains no transitive dependencies — every non-key attribute depends only on the primary key, not on another non-key attribute.', 8, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'List the four ACID properties of a transaction.', 'Atomicity (all-or-nothing), Consistency (valid state to valid state), Isolation (concurrent transactions appear serialised) and Durability (committed effects survive crashes).', 9, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'What is referential integrity?', 'The guarantee that a foreign-key value always matches an existing primary-key value in the referenced table (or is NULL), preventing orphan references.', 10, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'What does DNS do?', 'The Domain Name System maps human-readable domain names to IP addresses using a hierarchical, distributed database of name servers (root, TLD, authoritative).', 11, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'Compare TCP and UDP.', 'TCP is reliable, connection-oriented and ordered (used for files, web pages); UDP is connectionless and fire-and-forget with low overhead (used for DNS, VoIP, live video and gaming).', 12, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'What is packet switching?', 'A method where messages are split into packets routed independently across a network and reassembled at the destination. It is robust, efficient and scalable — the basis of the Internet.', 13, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'Why is client-side validation insufficient?', 'Because users can disable or modify JavaScript in the browser. Server-side validation is mandatory for security; client-side validation is only a usability feature.', 14, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'Describe PageRank in one sentence.', 'A page is important if many important pages link to it; rank is computed iteratively from incoming links weighted by their source pages'' rank, damped by a factor (~0.85).', 15, 'alevel'),
  ('Computer Science', 'OCR', '1.3', 'Exchanging Data', 'What is the role of a stateful firewall?', 'It filters traffic between networks by tracking active connections, so it can recognise inbound packets that are legitimate replies to outbound requests, blocking unsolicited traffic.', 16, 'alevel');

-- Topic 1.4 — Data Types, Structures & Algorithms
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'Convert 173 (denary) to 8-bit binary.', '10101101 (128 + 32 + 8 + 4 + 1 = 173).', 1, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'How do you convert a positive denary number to two''s complement (negative)?', 'Convert the magnitude to binary, flip every bit (one''s complement), then add 1.', 2, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'What is the range of an 8-bit two''s complement integer?', '−128 to +127.', 3, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'How is overflow detected in two''s complement addition?', 'When the carry into the sign bit differs from the carry out of the sign bit — equivalently, two positives sum to a negative or two negatives sum to a positive.', 4, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'Why is hexadecimal used in computing?', 'Each hex digit maps to exactly four binary bits (one nibble), making it a compact, less error-prone shorthand for binary in addresses, machine code, MAC addresses and colour codes.', 5, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'In floating-point, what determines range vs precision?', 'The exponent determines range (the magnitudes representable); the mantissa determines precision (the number of significant figures).', 6, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'What is normalisation in floating-point?', 'Adjusting the mantissa and exponent so the leading bit gives the maximum precision: for two''s complement form, the first mantissa bit after the point must differ from the sign bit.', 7, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'How does Unicode differ from ASCII?', 'ASCII is a 7-bit code with 128 characters; Unicode covers over 150,000 code points across all human scripts. UTF-8 is a variable 1–4 byte encoding of Unicode that is ASCII-compatible.', 8, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'Describe a stack ADT.', 'A LIFO (Last-In, First-Out) structure with push (add to top), pop (remove from top) and peek operations. Used for function calls, undo, expression evaluation and DFS.', 9, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'Why use a circular queue instead of a linear queue?', 'In a linear queue, after dequeues the front advances and slots at the start are wasted. A circular queue uses modular arithmetic so pointers wrap, reusing all slots until truly full.', 10, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'State the BST ordering invariant.', 'For every node N, all keys in N''s left subtree are less than N''s key, and all keys in N''s right subtree are greater.', 11, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'Compare adjacency matrix and adjacency list representations of a graph.', 'A matrix uses O(V^2) space and gives O(1) edge-existence checks; a list uses O(V+E) space and is better for sparse graphs but edge checks are O(degree).', 12, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'What is a hash collision and how is it resolved?', 'When two distinct keys hash to the same bucket. Resolved by separate chaining (a linked list at each bucket) or open addressing (probing the next slot).', 13, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'State De Morgan''s laws.', 'NOT(A AND B) = (NOT A) OR (NOT B); NOT(A OR B) = (NOT A) AND (NOT B).', 14, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'What does a D-type flip-flop do?', 'Stores one bit. On a clock edge, the value at input D is latched and appears on output Q; the value is held until the next clock edge — the basis of registers and memory.', 15, 'alevel'),
  ('Computer Science', 'OCR', '1.4', 'Data Types, Structures & Algorithms', 'Give an advantage of a static data structure over a dynamic one.', 'Predictable, contiguous memory usage and O(1) random access by index, plus better cache locality.', 16, 'alevel');

-- Topic 1.5 — Legal, Moral, Cultural & Ethical
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'Distinguish "legal" from "ethical".', 'Legal means required or forbidden by law and enforceable by courts. Ethical means a shared (often professional) set of principles for what is right in practice — codified by a group but not necessarily law.', 1, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What does the Data Protection Act 2018 regulate?', 'How personal data (any information about an identified or identifiable living person) is collected, stored, processed and shared in the UK, implementing the UK GDPR.', 2, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'List four of the GDPR data-protection principles.', 'Lawfulness/fairness/transparency, purpose limitation, data minimisation, accuracy, storage limitation, integrity & confidentiality, and accountability.', 3, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'Who is the data controller in GDPR?', 'The entity that determines the purposes and means of processing personal data and is legally accountable for compliance — e.g. the company running an online shop.', 4, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What is the maximum higher-tier GDPR fine?', '£17.5 million or 4% of global annual turnover, whichever is higher.', 5, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What does the Computer Misuse Act 1990 criminalise?', 'Unauthorised access to computer material, unauthorised access with intent to commit further offences, unauthorised acts impairing computer operation, and supplying tools for these offences.', 6, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What does the Copyright, Designs and Patents Act 1988 protect?', 'Original literary (including source code), dramatic, musical and artistic works, automatically on creation. Software is treated as a literary work; protection lasts the author''s life plus 70 years.', 7, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'Compare copyright and patents.', 'Copyright protects the expression of an idea (e.g. source code) automatically; a patent protects novel, non-obvious inventions and requires application, examination and renewal — lasting up to 20 years.', 8, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What does the Regulation of Investigatory Powers Act 2000 govern?', 'Lawful interception of communications, directed surveillance and acquisition of communications data by UK public authorities (police, intelligence services, HMRC).', 9, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What is the digital divide?', 'The gap between those who have ready access to digital technology, fast internet and the skills to use them, and those who do not — created by income, geography, age or disability.', 10, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'Give two environmental impacts of computing.', 'Energy consumption of data centres and cryptocurrency mining; e-waste from short device lifecycles and rare-earth mining for components.', 11, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What is algorithmic bias?', 'When an automated system produces systematically unfair outcomes for some groups, often because the training data reflects existing societal bias or excludes some populations.', 12, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What is the BCS Code of Conduct?', 'A professional code published by the British Computer Society requiring members to act with integrity, in the public interest, with professional competence and due care for relevant authority and duty.', 13, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'How does automation affect the workforce?', 'It can displace routine jobs, create new specialised roles, raise productivity and wages for some workers but increase inequality for those without retraining opportunities.', 14, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'What rights does the Freedom of Information Act 2000 give?', 'Any person has a right of access to recorded information held by UK public authorities (government, NHS, schools, councils), with a response required within 20 working days.', 15, 'alevel'),
  ('Computer Science', 'OCR', '1.5', 'Legal, Moral, Cultural & Ethical', 'Why is "many eyes" sometimes claimed to make open-source software more secure?', 'Because anyone can read and audit the source, security flaws can be spotted and fixed by a global community rather than relying on a single vendor — though bugs are also visible to attackers.', 16, 'alevel');

-- Topic 2.1 — Elements of Computational Thinking
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is abstraction?', 'The process of removing or hiding unnecessary detail to focus on the essential features of a problem, making it easier to reason about and solve.', 1, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Distinguish representational and procedural abstraction.', 'Representational abstraction strips detail from real-world objects (e.g. the Tube map). Procedural abstraction hides how a procedure works behind a name and parameters.', 2, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is decomposition?', 'Breaking a large problem into smaller, independently solvable sub-problems that can be tackled separately and then combined.', 3, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Compare top-down and bottom-up design.', 'Top-down (stepwise refinement) starts from the whole and breaks it into parts. Bottom-up starts from small reliable components and combines them into larger systems.', 4, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is "thinking ahead"?', 'Anticipating future inputs, outputs, edge cases and reuse opportunities at design time so they don''t cause problems later — including caching, preconditions and exception handling.', 5, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is a precondition?', 'A condition that must be true before a procedure runs for it to behave correctly — e.g. "input list must be non-empty" before calling find_max.', 6, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is caching and why is it useful?', 'Storing the result of a slow computation so future requests for the same input return immediately, reducing repeated work and latency.', 7, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is "thinking logically"?', 'Identifying decision points and using Boolean conditions to model how the program''s flow branches based on inputs and intermediate state.', 8, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Distinguish concurrency from parallelism.', 'Concurrency is dealing with multiple tasks "in progress" (possibly time-sliced on one core). Parallelism is literally executing tasks at the same instant on multiple cores or processors.', 9, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'State Amdahl''s Law.', 'The maximum speed-up from parallelisation is limited by the sequential portion of the program: if 20% is inherently sequential, max speed-up is 1/0.2 = 5×.', 10, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is an "embarrassingly parallel" task?', 'A task that decomposes into many independent sub-tasks with little or no communication between them — e.g. applying the same image filter to thousands of images.', 11, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Give two challenges of concurrent programming.', 'Race conditions (where outcome depends on thread scheduling), deadlocks (threads waiting on each other''s locks), and synchronisation overhead.', 12, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'What is "thinking procedurally"?', 'Designing a sequence of clear, ordered steps to solve a problem and breaking those steps into reusable sub-procedures.', 13, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Why use levels of abstraction?', 'They let designers focus on one detail level at a time (hardware, OS, application, business logic) without being overwhelmed by every layer simultaneously.', 14, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Distinguish data parallelism from task parallelism.', 'Data parallelism applies the same operation to many data items simultaneously (SIMD). Task parallelism runs different tasks concurrently on different cores.', 15, 'alevel'),
  ('Computer Science', 'OCR', '2.1', 'Elements of Computational Thinking', 'Why is identifying inputs and outputs an early-design activity?', 'Because it determines the function''s contract, what data must be validated, what data structures are needed and how the rest of the system communicates with it.', 16, 'alevel');

-- Topic 2.2 — Problem Solving and Programming
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'Name the three basic programming constructs.', 'Sequence (statements executed one after another), selection (if/case branching) and iteration (while/for repetition).', 1, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is the difference between a procedure and a function?', 'A procedure performs an action and may not return a value; a function computes and returns a value. Functions ideally have no side effects.', 2, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'Compare pass-by-value and pass-by-reference.', 'Pass-by-value copies the argument''s value into the parameter; changes don''t affect the caller. Pass-by-reference passes a pointer/alias; the callee can modify the caller''s variable.', 3, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is variable scope?', 'The region of a program in which a variable is accessible. Local variables exist only within their procedure; global variables are accessible anywhere.', 4, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is recursion?', 'A subroutine that calls itself with smaller input, with one or more base cases that stop the recursion. Each call creates a new stack frame.', 5, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What causes a stack overflow?', 'Too many nested subroutine calls (often unbounded recursion) consuming all the call-stack memory.', 6, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'Give the recursive definition of factorial.', 'factorial(0) = 1; factorial(n) = n * factorial(n-1) for n > 0.', 7, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is encapsulation in OOP?', 'Bundling data (attributes) with the methods that act on them, and restricting direct access to attributes via private visibility and getters/setters to protect invariants.', 8, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is polymorphism?', 'The same method name behaves differently depending on the object''s class (overriding) or argument types (overloading). Lets the same code handle different concrete types.', 9, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is backtracking?', 'A problem-solving technique that builds candidates incrementally and abandons (backs up) any partial candidate that cannot lead to a valid solution. Used in maze solving and N-Queens.', 10, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is a heuristic?', 'A practical, approximate rule that quickly produces a "good enough" solution where finding the exact optimum is too expensive — e.g. a greedy choice or an estimated distance in A*.', 11, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is divide and conquer?', 'A strategy that recursively splits a problem into smaller independent sub-problems, solves them, then combines results — the basis of merge sort and binary search.', 12, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is data mining?', 'The process of discovering patterns, correlations and anomalies in large data sets using techniques like clustering, classification and association rules to inform decisions.', 13, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'Compare iteration and recursion.', 'Iteration uses loops and constant stack space, generally fast; recursion mirrors recursive problem structure (trees, divide-and-conquer) more naturally but uses stack memory per call.', 14, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'Name three common IDE features that aid development.', 'Syntax highlighting/auto-complete, integrated debugger with breakpoints and watch variables, and built-in compiler/run + version-control integration.', 15, 'alevel'),
  ('Computer Science', 'OCR', '2.2', 'Problem Solving and Programming', 'What is performance modelling?', 'Estimating how an algorithm or system will behave at scale (time, memory, network) using profiling, complexity analysis and simulation, before committing to an implementation.', 16, 'alevel');

-- Topic 2.3 — Algorithms
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'What does Big-O notation describe?', 'The asymptotic upper bound on an algorithm''s running time or space as input size grows, ignoring constants and lower-order terms.', 1, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'State the time complexity of linear search.', 'O(n) in the worst and average case — every element may need to be checked.', 2, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'State the time complexity of binary search and its precondition.', 'O(log n). The list must be sorted; binary search halves the search range each step.', 3, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'How does bubble sort work?', 'Repeatedly compares adjacent pairs and swaps them if out of order; after each pass the largest unsorted element bubbles to the end. O(n^2) average and worst case.', 4, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'How does insertion sort work?', 'Iterates through the list, taking each element and inserting it into its correct position in the already-sorted left portion. O(n^2) worst case but O(n) on already-sorted input.', 5, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'Outline merge sort.', 'A divide-and-conquer algorithm: recursively split the list in half, sort each half, then merge two sorted halves into one. O(n log n) time, O(n) extra space.', 6, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'Outline quick sort.', 'Pick a pivot, partition the list into elements less than and greater than the pivot, then recursively sort each partition. O(n log n) average; O(n^2) worst case (poor pivot).', 7, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'What is the time complexity of searching a balanced BST?', 'O(log n) on average. In a fully unbalanced BST it degrades to O(n).', 8, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'What is Dijkstra''s algorithm?', 'A shortest-path algorithm for weighted graphs with non-negative edges. It uses a priority queue, repeatedly extracting the closest unvisited vertex and relaxing its neighbours.', 9, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'Why does Dijkstra fail with negative edge weights?', 'Once a vertex is finalised it isn''t reconsidered, but a later negative edge could provide a shorter path — invalidating the assumption Dijkstra relies on.', 10, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'How does A* improve on Dijkstra?', 'It adds a heuristic h(n) estimating the distance from each node to the goal, prioritising nodes with the smallest f(n) = g(n) + h(n) and reaching the target faster while remaining optimal if h is admissible.', 11, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'What is an admissible heuristic?', 'One that never overestimates the true cost to the goal. With an admissible heuristic, A* is guaranteed to find the optimal path.', 12, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'Distinguish best, average and worst case.', 'Best case: minimum running time on the most favourable input. Worst case: maximum running time. Average case: expected running time over typical input distributions — usually most informative.', 13, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'What is space complexity?', 'The amount of additional memory an algorithm needs as a function of input size, expressed in Big-O notation just like time complexity.', 14, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'How many comparisons does binary search make on a list of 1024 items in the worst case?', 'log2(1024) = 10 comparisons.', 15, 'alevel'),
  ('Computer Science', 'OCR', '2.3', 'Algorithms', 'When would you choose insertion sort over merge sort?', 'For very small or nearly-sorted lists: insertion sort has lower overhead and is O(n) on already-sorted data, whereas merge sort always does O(n log n) work.', 16, 'alevel');


-- ===============================================================
-- AQA A-LEVEL
-- ===============================================================

-- Topic 4.1 — Fundamentals of Programming
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'List five primitive data types AQA examines.', 'Integer, real/float, character, string and Boolean.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'Distinguish type coercion from type casting.', 'Coercion is implicit conversion done by the language (e.g. int auto-promoted to float in mixed arithmetic). Casting is explicit conversion requested by the programmer.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is a user-defined data type?', 'A type defined by the programmer (records, enumerations, sets, classes) that combines or restricts existing primitives to model domain concepts.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is a constant?', 'A named value that cannot change after declaration, improving readability and protecting against accidental modification (e.g. PI = 3.14159).', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'Why prefer local variables over globals?', 'Locals limit scope and lifetime, reducing unintended side effects, name collisions and tight coupling between subroutines, making code easier to test and maintain.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is a stack frame?', 'A region pushed onto the call stack for each subroutine call, containing the return address, parameters, local variables and saved registers.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'Define recursion and state its requirement.', 'A subroutine that calls itself with smaller input. It must have one or more base cases that terminate the recursion to avoid stack overflow.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is shadowing?', 'When a local variable has the same name as a variable in an enclosing or global scope, the local "shadows" the outer one within its scope.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What does encapsulation achieve?', 'It binds data and behaviour together inside a class and hides internal state behind methods, so invariants are protected and implementation can change without breaking callers.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'Distinguish overriding from overloading.', 'Overriding redefines an inherited method in a subclass with the same signature. Overloading provides multiple methods with the same name but different parameter lists in the same class.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is inheritance?', 'A subclass automatically reuses and may extend or override the attributes and methods of a parent class, modelling an "is-a" relationship.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is the purpose of try/except/finally?', 'try contains code that might raise an exception; except handles specific exception types; finally runs cleanup code (file close, lock release) whether or not an exception occurred.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'Why are exceptions preferred to return codes?', 'They separate error-handling code from the main logic, cannot be silently ignored, and propagate automatically up the call stack until handled.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What does structured programming forbid?', 'Unconstrained jumps (goto). Programs must be built from sequence, selection and iteration, with each block having one entry and ideally one exit.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'What is a side effect?', 'Any change a subroutine makes outside its return value — modifying parameters, globals, files or screen output. Pure functions avoid side effects.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.1', 'Fundamentals of Programming', 'Why use meaningful identifier names?', 'They make code self-documenting, reducing the need for comments and making bugs easier to spot during review and debugging.', 16, 'alevel');

-- Topic 4.2 — Fundamentals of Data Structures
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'Distinguish an Abstract Data Type from its implementation.', 'An ADT specifies only the operations and behaviour (e.g. stack: push/pop/peek). The implementation is the concrete data structure that realises it (e.g. array or linked list).', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'Describe row-major order for 2D arrays.', 'Elements are stored in memory row by row: arr[0][0], arr[0][1], ..., arr[1][0], .... Used by most languages including C, C++, Python lists.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What is a record?', 'A heterogeneous, fixed structure of named fields each with its own type — the basis of file records and rows in a database.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What does a queue ADT support?', 'enqueue (add to rear), dequeue (remove from front), peek/front, isEmpty and isFull. It is FIFO — first in, first out.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'How does a circular queue work?', 'It uses an array with front and rear indices that wrap modulo the array size: rear = (rear + 1) mod size, so all slots are reused.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What does a stack ADT support?', 'push (add to top), pop (remove from top), peek/top, isEmpty. It is LIFO — last in, first out.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'How is Reverse Polish Notation evaluated with a stack?', 'Read tokens left to right: push numbers; on an operator, pop the top two operands, apply the operator, push the result. The final value remaining on the stack is the answer.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'When should you use an adjacency matrix over a list?', 'For dense graphs and when fast O(1) edge-existence checks are needed. Adjacency lists are better for sparse graphs because they use only O(V+E) space.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'Define a binary search tree.', 'A binary tree where every node N satisfies: all keys in N''s left subtree are less than N''s key, and all keys in N''s right subtree are greater.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What does an in-order traversal of a BST produce?', 'The keys visited in ascending sorted order. In-order = (visit left subtree, visit node, visit right subtree).', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'List two properties of a good hash function.', 'Deterministic and uniform (spreads keys evenly across buckets) and fast to compute. It should also minimise collisions for the expected key distribution.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What is open addressing with linear probing?', 'On a collision, search the next slot (index + 1, +2, ...) until an empty slot is found. Simple but suffers from clustering as occupied runs grow.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What is the load factor of a hash table?', 'The ratio of stored items to total buckets. When it exceeds a threshold (~0.7), the table is rehashed into a larger array to maintain O(1) performance.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What is a dictionary?', 'An ADT that maps unique keys to values, supporting insert, lookup and delete. Typically implemented as a hash table or balanced BST.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'Give an advantage of a linked-list implementation of a stack over an array implementation.', 'It can grow dynamically without overflowing a fixed size and without copying when resizing — push and pop remain O(1).', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.2', 'Fundamentals of Data Structures', 'What is a priority queue?', 'A queue where each item carries a priority; dequeue returns the highest-priority item rather than the longest-waiting one. Used in OS scheduling and Dijkstra''s algorithm.', 16, 'alevel');

-- Topic 4.3 — Fundamentals of Algorithms
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Compare DFS and BFS.', 'DFS goes as deep as possible before backtracking, using a stack (or recursion); BFS visits all neighbours at the current depth first, using a queue. BFS finds shortest unweighted paths.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'What data structure does iterative DFS use?', 'A stack (push neighbours, pop the next vertex to visit).', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'What data structure does BFS use?', 'A queue (enqueue neighbours, dequeue the next vertex to visit).', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Name the three depth-first tree traversals.', 'Pre-order (node, left, right), in-order (left, node, right) and post-order (left, right, node).', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'How do you evaluate a Reverse Polish expression?', 'Push numbers onto a stack; on each operator pop the top two values, apply the operator, push the result. The remaining top-of-stack is the answer.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'What is the shunting-yard algorithm used for?', 'Converting infix expressions (e.g. 3 + 4 * 5) into postfix (RPN) using an operator stack and an output queue, respecting precedence and associativity.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'State the time complexity of binary search.', 'O(log n). The list must be sorted; each comparison halves the remaining search range.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Why is merge sort stable?', 'When merging, equal elements from the left half are taken before equal elements from the right half, preserving their original relative order.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'State the time complexity of merge sort.', 'O(n log n) in best, average and worst cases. Uses O(n) extra space for the merge buffer.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'How does bubble sort work?', 'Repeatedly compares each adjacent pair and swaps if out of order; after pass i the i-th largest element is in place. O(n^2) average and worst case.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Outline Dijkstra''s shortest-path algorithm.', 'Maintain tentative distances; using a priority queue, repeatedly extract the closest unvisited node and relax its neighbours (update if a shorter path is found). Stops when all nodes are visited.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'What is the time complexity of Dijkstra''s algorithm with a binary heap?', 'O((V + E) log V), where V is vertices and E is edges.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Why does Dijkstra require non-negative edge weights?', 'Once a vertex is finalised it is never reconsidered. A negative edge could later offer a shorter path, invalidating the greedy choice.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Order the common complexity classes from fastest to slowest growing.', 'O(1) < O(log n) < O(n) < O(n log n) < O(n^2) < O(2^n) < O(n!).', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'How does A* extend Dijkstra?', 'A* adds a heuristic estimate h(n) of the distance to the goal and explores nodes by smallest f(n) = g(n) + h(n), reaching the goal faster while remaining optimal if h is admissible.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.3', 'Fundamentals of Algorithms', 'Why are constants dropped in Big-O?', 'Big-O describes asymptotic growth: as n grows large, constants and lower-order terms become insignificant compared to the dominant term.', 16, 'alevel');

-- Topic 4.4 — Theory of Computation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'Define abstraction.', 'The process of removing or hiding unnecessary detail to focus on the essential features of a problem. It allows complex systems to be reasoned about at multiple levels.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'Distinguish procedural and functional abstraction.', 'Procedural abstraction hides how a procedure is implemented behind its name and parameters. Functional abstraction emphasises the mathematical mapping from inputs to outputs without state.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is information hiding?', 'Concealing the internal data and implementation of a module so callers can only interact via its public interface, reducing coupling.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is a finite state machine (FSM)?', 'A computational model with a finite set of states, an input alphabet, transitions between states triggered by input symbols, a start state and one or more accepting states.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'Distinguish a Mealy from a Moore machine.', 'A Mealy machine''s output depends on the current state AND the input. A Moore machine''s output depends only on the current state.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is a Turing machine?', 'An abstract model with an infinite tape, a read/write head, a finite state register and a transition function. It captures the formal notion of computation.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'State the Church–Turing thesis.', 'Any function that can be effectively computed by an algorithm can be computed by a Turing machine. It defines the limits of mechanical computation.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is a Universal Turing Machine?', 'A Turing machine that, given a description of any other Turing machine and its input on its tape, simulates that machine — the theoretical basis for stored-program computers.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What language describes regular expressions?', 'Regular expressions describe regular languages, which are exactly the set of languages recognised by deterministic or non-deterministic finite automata (DFA/NFA).', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is Backus–Naur Form (BNF)?', 'A meta-syntax that defines context-free grammars using rules like <expr> ::= <term> "+" <expr>. Used to specify programming-language syntax.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'Why does BNF describe more languages than regular expressions?', 'BNF can express recursive, nested structures (matched brackets, balanced expressions) which regular expressions cannot, because regex corresponds only to regular languages.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'Distinguish tractable from intractable problems.', 'Tractable problems can be solved in polynomial time (P). Intractable ones have no known polynomial-time algorithm — they are infeasible for large inputs.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is the class P?', 'The set of decision problems solvable in polynomial time by a deterministic Turing machine. Considered the class of "efficiently solvable" problems.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is an NP-complete problem?', 'A problem in NP to which every other NP problem can be polynomially reduced. If any NP-complete problem has a polynomial solution, then P = NP. Examples: SAT, Travelling Salesman (decision form).', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'State the Halting Problem.', 'Given an arbitrary program and an input, decide whether the program eventually halts. Turing proved no algorithm can solve this for all programs and inputs.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.4', 'Theory of Computation', 'What is decomposition?', 'Breaking a complex problem or system into smaller independent sub-problems that can be solved separately and then combined.', 16, 'alevel');

-- Topic 4.5 — Fundamentals of Data Representation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'How many bytes is a kibibyte (KiB) versus a kilobyte (KB)?', '1 KiB = 1024 bytes (binary, IEC). 1 KB = 1000 bytes (decimal, SI).', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Convert 218 (decimal) to hexadecimal.', '218 = 11011010 binary = DA hex.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'What is the range of an n-bit two''s complement integer?', '−2^(n−1) to +2^(n−1)−1. For 8 bits: −128 to +127.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Why is two''s complement preferred over sign-and-magnitude?', 'It has only one representation of zero, and ordinary binary addition hardware works for both signed addition and subtraction without modification.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'What do logical and arithmetic right shifts differ in?', 'Logical right shift fills new MSBs with 0. Arithmetic right shift preserves the sign by replicating the original MSB, so it works for signed numbers as a divide-by-2.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Describe IEEE 754 single precision.', '32 bits: 1 sign bit, 8 exponent bits (with bias 127) and 23 mantissa bits. Value = (-1)^s × 1.mantissa × 2^(exponent − 127).', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'How does ASCII differ from Unicode?', 'ASCII is 7-bit (128 characters, mostly English). Unicode covers all human scripts (>150,000 code points) and is encoded as UTF-8, UTF-16 or UTF-32.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'What does UTF-8 encoding give you?', 'A variable 1–4 byte encoding of Unicode that is fully ASCII-compatible (U+0000–U+007F encode in one byte) and dominant on the web.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Define a bitmap image.', 'A grid of pixels where each pixel''s colour is stored as a number. Quality depends on resolution (pixel count) and colour depth (bits per pixel).', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Compare bitmap and vector graphics.', 'Bitmaps store pixels and pixelate when scaled up. Vectors store mathematical descriptions of shapes (lines, curves) and rescale cleanly at any size.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'What is the Nyquist sampling theorem?', 'To capture a signal accurately, the sampling rate must be at least twice the highest frequency present. CD audio at 44.1 kHz captures up to ~22 kHz — beyond human hearing.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'How does Run-Length Encoding compress data?', 'It replaces runs of identical values with a (value, count) pair. Effective on data with long uniform runs (simple bitmaps, fax) and lossless.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Describe Huffman coding briefly.', 'A lossless variable-length code where frequent symbols get shorter codes. Built from a binary tree merging the two lowest-frequency nodes repeatedly. Codes have the prefix property.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'What is a Vernam cipher?', 'A symmetric cipher that XORs the plaintext with a truly random key as long as the message, used once. It is the only theoretically unbreakable cipher (one-time pad).', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'What is a hash function?', 'A one-way function mapping arbitrary-length input to a fixed-length output (digest). Cryptographic hashes are infeasible to reverse and exhibit avalanche behaviour.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.5', 'Fundamentals of Data Representation', 'Distinguish overflow from underflow in floating-point.', 'Overflow: the exponent is too large to store (number too big in magnitude). Underflow: the exponent is too small/negative (number too close to zero to represent).', 16, 'alevel');

-- Topic 4.6 — Fundamentals of Computer Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Distinguish system software from application software.', 'System software (OS, drivers, utilities) manages and supports the computer itself. Application software (browser, word processor) helps the user perform tasks.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Compare bespoke and off-the-shelf software.', 'Bespoke is custom-built for one client — fits exact needs but is expensive and slow to develop. Off-the-shelf is mass-produced — cheap and immediate but a generic compromise.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Compare a compiler and an interpreter.', 'A compiler translates the entire program once to machine code that runs fast. An interpreter translates and executes line by line each run, slower but more portable and easier to debug.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What does an assembler do?', 'Translates assembly language (one mnemonic per machine instruction) into the corresponding machine code with a near 1:1 mapping.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Why is NAND a "universal" gate?', 'Any Boolean function can be implemented using only NAND gates (or only NOR gates). NAND is also cheap and fast to manufacture in CMOS.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'State De Morgan''s first law.', 'NOT(A AND B) = (NOT A) OR (NOT B). The negation of a conjunction is the disjunction of the negations.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What is a Karnaugh map used for?', 'Visually simplifying Boolean expressions by grouping adjacent 1s in powers of two, producing a minimal sum-of-products form.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What is a half-adder?', 'A circuit with two inputs (A, B) producing Sum = A XOR B and Carry = A AND B. It cannot accept a carry-in.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'How does a full adder differ from a half-adder?', 'A full adder accepts a carry-in alongside A and B, producing Sum = A XOR B XOR Cin and Cout = (A AND B) OR (Cin AND (A XOR B)). Cascade n full adders for n-bit addition.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What does a D-type flip-flop do?', 'On a clock edge it latches the value at input D onto output Q and holds it until the next clock edge. It is the basic 1-bit memory cell used in registers.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What is the role of the kernel?', 'The privileged core of the OS. Manages processes, memory, interrupts and I/O. Runs in kernel mode with full hardware access.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What is virtual memory?', 'A technique where the OS uses part of secondary storage (a page file) as if it were extra RAM. When a needed page isn''t in RAM, a page fault triggers it to be loaded.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Distinguish kernel mode from user mode.', 'Kernel mode allows full access to hardware and privileged instructions. User mode restricts applications to safe operations; system calls trap into the kernel for privileged work.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Compare Round Robin and Shortest Job First scheduling.', 'Round Robin gives each ready process a fixed time quantum in turn — fair and good for interactivity. SJF picks the ready process with the shortest expected burst — minimum average wait but can starve long jobs.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'What is XOR equal to in terms of NAND gates?', 'XOR can be built from four NAND gates: A XOR B = ((A NAND (A NAND B)) NAND (B NAND (A NAND B))).', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.6', 'Fundamentals of Computer Systems', 'Why is a 4-bit ripple-carry adder slow for wide values?', 'Each full adder must wait for the carry-out of the previous bit. The carry "ripples" through, so addition latency grows linearly with bit width.', 16, 'alevel');

-- Topic 4.7 — Computer Organisation & Architecture
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'What is the stored-program concept?', 'The principle that instructions and data are stored together in memory and the CPU fetches and executes instructions sequentially — the basis of Von Neumann architecture.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'Name the three system buses and what they carry.', 'Address bus (memory addresses, CPU → memory), data bus (data and instructions, bidirectional), control bus (READ/WRITE, IRQ, clock and other control signals).', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'What is the role of the Program Counter (PC)?', 'Holds the address of the next instruction to be fetched. It is incremented after each fetch and overwritten by branch instructions.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'What does the CIR (Current Instruction Register) hold?', 'The instruction currently being decoded and executed. The Control Unit splits its contents into opcode and operand.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'Describe the Fetch phase of the FDE cycle in RTN.', 'MAR <- [PC]; PC <- [PC] + 1; MDR <- [Memory[MAR]]; CIR <- [MDR].', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'How does pipelining boost throughput?', 'It overlaps consecutive instructions across fetch/decode/execute stages so one instruction completes per clock cycle once the pipeline is full.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'What is branch prediction?', 'A technique where the CPU guesses the outcome of a conditional branch and speculatively fetches from the predicted target, reducing pipeline stalls. Wrong predictions cause a flush.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'Describe immediate addressing mode.', 'The operand is the literal value itself, encoded directly in the instruction (e.g. MOV R1, #5 puts 5 into R1).', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'Describe indexed addressing mode.', 'The effective address is base + the contents of an index register. It is how arrays are accessed: arr[i] becomes base + i × element_size.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'How does cache improve performance?', 'It exploits locality of reference by keeping copies of recently used instructions/data in fast SRAM, drastically reducing average memory access time.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'What is word length and why does it matter?', 'The natural unit of data the CPU operates on (e.g. 64 bits). It dictates register size, the size of operands processed in one cycle, and (often) data-bus width.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'Compare RISC and CISC.', 'RISC has a small set of simple, fixed-length instructions executing in one cycle (ARM); CISC has many complex variable-length instructions doing more per instruction (x86). RISC pipelines easily and uses less power.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'Why are GPUs effective for machine learning?', 'They contain thousands of simple SIMD cores running the same instruction on different data simultaneously, perfectly suited to the large matrix multiplications in neural networks.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'How does an HDD store data?', 'As magnetic patterns on spinning platters. A read/write head floats above each platter; tracks are subdivided into sectors. Access requires seek time + rotational latency.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'How does an SSD store data?', 'In NAND flash memory cells (floating-gate transistors holding charge). It has no moving parts, near-instant access (<0.1 ms) but limited write endurance per cell.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.7', 'Computer Organisation & Architecture', 'What is virtual storage?', 'Storage abstracted over a network or pool so multiple physical devices appear as one logical volume — e.g. cloud storage, SAN. Distinct from virtual memory.', 16, 'alevel');

-- Topic 4.8 — Consequences of Uses of Computing
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'Distinguish moral, ethical and legal issues.', 'Moral = personal beliefs about right/wrong. Ethical = shared/professional principles. Legal = required or forbidden by law and enforceable by courts.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'Name two ethical frameworks for reasoning about technology.', 'Utilitarianism (greatest good for the greatest number), deontology (duties and rules — Kant), virtue ethics (what would a virtuous person do?), and rights-based ethics.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What does the UK GDPR / Data Protection Act 2018 regulate?', 'How personal data about identifiable individuals is collected, stored, processed and shared, requiring lawful basis, transparency, minimisation and security.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What does the Computer Misuse Act 1990 criminalise?', 'Unauthorised access to computer material, unauthorised access with intent to commit further offences, unauthorised modification, and the supply of hacking tools.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What does the Copyright, Designs and Patents Act 1988 protect?', 'Original literary works (including source code), dramatic, musical and artistic works automatically on creation. Protection lasts the author''s life plus 70 years.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'Give two privacy concerns of corporate surveillance.', 'Tracking users across sites for ad profiling without meaningful consent; selling data to third parties; and inferring sensitive attributes (health, politics) from behavioural data.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What is the digital divide?', 'The gap between those who have access to digital technology, fast internet and the skills to use them, and those who do not — caused by income, geography, age or disability.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'Give two environmental impacts of computing.', 'Energy consumption of data centres and crypto mining; e-waste from short device lifetimes; rare-earth and conflict-mineral mining for components.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'Why is accountability hard for AI decisions?', 'AI models (especially deep neural networks) can be opaque "black boxes"; responsibility is split between developer, dataset curator, deployer and user, making blame hard to assign when harm occurs.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What is algorithmic bias?', 'When an automated system produces systematically unfair outcomes for some groups, often because the training data reflects existing societal bias or excludes some populations.', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'Name two professional codes of conduct relevant to computing.', 'The BCS Code of Conduct (UK) and the ACM Code of Ethics (international). Both require integrity, public interest, competence and respect for privacy.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What is the trolley problem in autonomous vehicles?', 'A thought experiment about how a self-driving car should choose between unavoidable harms (e.g. swerving to hit one person to save five), forcing programmers to encode moral choices.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What does a PEEC paragraph contain?', 'Point, Evidence, Explanation, Counterargument — a structure for extended-response answers that earns marks for balanced reasoning.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'How can computing reduce its environmental footprint?', 'Energy-efficient hardware (ARM, low-power chips), workload scheduling on renewables, server consolidation/virtualisation, longer device lifetimes, and recycling/right-to-repair.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'What is misinformation versus disinformation?', 'Misinformation is false information shared without intent to deceive; disinformation is deliberately false information spread to mislead — both amplified by social-media algorithms.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.8', 'Consequences of Uses of Computing', 'How does automation affect employment?', 'It can displace routine and manual jobs, raise productivity and create new specialised roles, but risks worsening inequality if displaced workers lack retraining opportunities.', 16, 'alevel');

-- Topic 4.9 — Communication & Networking
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Compare serial and parallel transmission.', 'Serial sends one bit at a time over a single wire — cheap, reliable over long distances. Parallel sends multiple bits simultaneously over many wires — fast over short distances but suffers skew at high frequencies.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Distinguish baud rate from bit rate.', 'Baud rate is the number of signal changes per second. Bit rate is the number of bits transmitted per second. They are equal only when each signal change carries one bit.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'How does a parity bit detect errors?', 'An extra bit is appended so that the total number of 1s is even (even parity) or odd (odd parity). A single bit-flip changes the parity, signalling corruption.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Compare circuit switching and packet switching.', 'Circuit switching reserves a dedicated end-to-end path for the call (telephone). Packet switching breaks data into packets routed independently (Internet) — robust, efficient, scalable.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Compare LAN and WAN.', 'A LAN spans a single site (home, office) with high speed and locally owned infrastructure. A WAN spans cities/countries (e.g. the Internet) using leased or shared infrastructure.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Describe star topology.', 'All devices connect to a central switch or hub. Failure of one cable affects only that device, but the central node is a single point of failure. Common in modern Ethernet LANs.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'What does DNS do?', 'The Domain Name System resolves human-friendly domain names (e.g. www.aqa.org.uk) to IP addresses through a hierarchy of root, TLD and authoritative name servers.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Why use CIDR notation like 192.168.1.0/24?', 'It specifies the network prefix length: /24 means the first 24 bits are the network and the last 8 are host addresses, giving 256 addresses (254 usable).', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'What is NAT?', 'Network Address Translation lets many private LAN devices share a single public IPv4 address. The router rewrites source IP and port for outbound traffic and tracks replies in a table.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'List the four layers of the TCP/IP model.', 'Application (HTTP, DNS), Transport (TCP, UDP), Internet (IP, ICMP) and Network Access/Link (Ethernet, Wi-Fi).', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Compare TCP and UDP.', 'TCP is reliable, connection-oriented and ordered (web pages, file transfer); UDP is connectionless and fire-and-forget with low overhead (DNS, VoIP, gaming, live video).', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Outline the TCP three-way handshake.', 'Client sends SYN; server replies SYN-ACK; client replies ACK. Sequence numbers are synchronised and the connection is established before data flows.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'What does encapsulation mean in the network stack?', 'As data descends the stack, each layer adds its own header (and possibly trailer) to the unit from above. The receiver strips each header in reverse on the way up.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'What is a MAC address?', 'A 48-bit hardware identifier burned into a network interface, used at the Data Link layer to address frames within a local segment. Format: six hex pairs.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'Compare symmetric and asymmetric cryptography.', 'Symmetric uses one shared key — fast but key distribution is hard. Asymmetric uses a public/private key pair — slower but solves key distribution. TLS combines both.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.9', 'Communication & Networking', 'What is a digital certificate?', 'An electronic document binding a public key to an identity, signed by a trusted Certificate Authority (CA). Browsers verify the chain to authenticate HTTPS sites.', 16, 'alevel');

-- Topic 4.10 — Fundamentals of Databases
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What is an entity in ER modelling?', 'A real-world thing about which data is stored (Student, Order, Product). Each entity normally becomes a table in the relational model.', 1, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What is a primary key?', 'An attribute (or combination) that uniquely identifies each record in a table. It must be unique and not NULL.', 2, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What is a foreign key?', 'An attribute in one table that references the primary key of another table, enforcing a link between them and preserving referential integrity.', 3, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'How is a many-to-many relationship implemented relationally?', 'By introducing a linking (junction) table containing foreign keys to both sides, decomposing the M:N into two 1:M relationships.', 4, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'State the requirement for First Normal Form (1NF).', 'Each field contains only an atomic value (no lists or repeating groups), every record has a primary key, and entries in a column are all of the same type.', 5, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'State the requirement for Third Normal Form (3NF).', 'The database is in 2NF and has no transitive dependencies — every non-key attribute depends only on the primary key, not on another non-key attribute.', 6, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What is the difference between WHERE and HAVING in SQL?', 'WHERE filters rows before grouping; HAVING filters groups produced by GROUP BY. WHERE cannot reference aggregate functions; HAVING can.', 7, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What does an INNER JOIN return?', 'Only the rows where the ON condition matches in both tables. Non-matching rows from either side are excluded.', 8, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What does a LEFT (OUTER) JOIN return?', 'All rows from the left table plus matching rows from the right. Where there is no match, columns from the right side are filled with NULL.', 9, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'List the four ACID properties.', 'Atomicity (all-or-nothing), Consistency (valid state to valid state), Isolation (concurrent transactions appear serialised), Durability (committed effects survive crashes).', 10, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What is a deadlock and how is it resolved?', 'Two transactions each holding a lock the other needs, waiting forever. The DBMS detects the cycle and aborts (rolls back) one transaction so the other can proceed.', 11, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What is SQL injection?', 'An attack where malicious SQL is inserted into a query via unsanitised user input, potentially exposing or destroying data. Defended by parameterised queries / prepared statements.', 12, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'Name the five Vs of big data.', 'Volume, Velocity, Variety, Veracity and Value. They describe why traditional relational databases struggle with internet-scale data.', 13, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'Name four families of NoSQL database.', 'Key-value (Redis), document (MongoDB), column-family (Cassandra) and graph (Neo4j). Each trades some ACID guarantees for scale or flexibility.', 14, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What does MapReduce do?', 'A programming model for processing huge datasets in parallel: a Map function emits key-value pairs from input, then Reduce aggregates pairs sharing the same key. Underpins Hadoop.', 15, 'alevel'),
  ('Computer Science', 'AQA', '4.10', 'Fundamentals of Databases', 'What do GRANT and REVOKE do in SQL?', 'GRANT gives users specific privileges on a database object (SELECT, INSERT, UPDATE on a table). REVOKE removes them. Together they implement role-based access control.', 16, 'alevel');
