-- A-Level Economics Flashcards (Edexcel A)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.

-- ===============================================================
-- EDEXCEL A A-LEVEL
-- ===============================================================

-- Topic 1.1 — Nature of Economics and Markets
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'What is economics as a social science?', 'The study of how individuals, firms and governments allocate scarce resources to satisfy unlimited wants. Uses positive and normative analysis, modelling and ceteris paribus.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Define opportunity cost with an example.', 'The next-best alternative forgone. A government spending £10bn on the NHS forgoes £10bn that could have been spent on schools or tax cuts.', 2, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Why does a PPF curve outwards (concave)?', 'Resources are not equally productive in all uses, so reallocating them yields increasing opportunity cost — the absolute slope steepens as we move along the curve. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><path d="M30 25 Q70 32 130 75 T200 130" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Good X</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">Good Y</text><text x="135" y="105" font-size="9" fill="#0B1E3F">PPF</text></svg>', 3, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'State the law of demand.', 'Ceteris paribus, as the price of a good rises, quantity demanded falls. Demand curves slope downwards because of the substitution and income effects and diminishing marginal utility.', 4, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Name five non-price determinants of demand (PIRATE).', 'Population, income, related goods (substitutes/complements), advertising/tastes, expectations. (Also fashion, season.) A change in any of these shifts the demand curve.', 5, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Define PED and explain three determinants.', 'PED = % change in Qd / % change in P. Determinants: substitutes (more = elastic), share of income, necessity vs luxury, time period (more elastic in long run), addiction.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'How does PED affect total revenue?', 'If demand is elastic (|PED|>1), price cuts raise total revenue. If inelastic (|PED|<1), price rises raise total revenue. At unitary elasticity, revenue is maximised.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Define YED and interpret three values.', 'YED = % change in Qd / % change in income. >1: luxury (income elastic). 0<YED<1: necessity. Negative: inferior good.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Define XED and interpret its sign.', 'XED = % change in Qd of A / % change in P of B. Positive: substitutes (Coke and Pepsi). Negative: complements (printers and cartridges). Magnitude shows closeness.', 9, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Name three determinants of PES.', 'Spare capacity, ease of stockholding, factor mobility, time period (longer is more elastic), barriers to entry. Also depends on production lags (agriculture is inelastic).', 10, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'How is market equilibrium determined?', 'At the price where Qd = Qs. A surplus pushes price down; a shortage pushes price up. The price mechanism rations, signals and incentivises (Adam Smith''s ''invisible hand''). <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="78" x2="120" y2="78" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="120" y1="78" x2="120" y2="130" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="81" font-size="9" fill="#0B1E3F" text-anchor="end">P*</text><text x="120" y="145" font-size="9" fill="#0B1E3F" text-anchor="middle">Q*</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 11, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Define consumer surplus and producer surplus.', 'Consumer surplus: amount consumers are willing to pay above the actual price. Producer surplus: amount producers receive above the minimum acceptable price. Together = welfare.', 12, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Distinguish indirect and direct taxes with examples.', 'Indirect taxes are paid through spending (VAT, fuel duty); they shift supply leftward. Direct taxes are paid on income or wealth (income tax, NI); they affect AD via disposable income.', 13, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'How does demand elasticity affect tax incidence?', 'When demand is more inelastic than supply, consumers bear the larger share of an indirect tax. When demand is more elastic, producers bear the larger share.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'Explain the rationality assumption in classical economics.', 'Consumers are assumed to maximise utility and firms to maximise profit. Behavioural economics challenges this: people use heuristics, exhibit bounded rationality, herding, anchoring and loss aversion.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '1.1', 'Nature of Economics and Markets', 'What is a positive and a normative statement?', 'Positive: testable factual claim (UK CPI inflation was 4% in March). Normative: value judgement (the government should cut taxes). Mixing them up is a common evaluation pitfall.', 16, 'alevel');

-- Topic 1.2 — Market Failure and Government Intervention
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Define market failure.', 'Where a free market fails to allocate resources efficiently, leading to a misallocation and welfare loss. Includes externalities, public goods, information failure, monopoly power and inequality.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Distinguish complete from partial market failure.', 'Complete: a missing market — the good is not provided at all (pure public goods). Partial: the market exists but produces the wrong quantity (externalities, merit/demerit goods).', 2, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Define a negative externality of consumption.', 'A spillover cost on third parties from consumption. Marginal Social Benefit lies below Marginal Private Benefit. Examples: cigarettes, alcohol, fast food. Free market overconsumes.', 3, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Define a positive externality of production.', 'A spillover benefit on third parties from production. MSC lies below MPC. Examples: bee-keeping near orchards, R&D spillovers. Free market underproduces.', 4, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Identify the welfare loss triangle on an externality diagram.', 'The triangle bounded by the MSC and MSB curves between the free-market quantity and the socially optimal quantity, representing welfare lost from over- or under-consumption. <svg viewBox="0 0 240 150" width="240" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="225" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="200" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="200" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="65" y1="125" x2="220" y2="22" stroke="#0B1E3F" stroke-width="1.5" stroke-dasharray="3 2"/><polygon points="115,75 145,55 145,90" fill="#B00020" fill-opacity="0.3"/><text x="203" y="125" font-size="9" fill="#0B1E3F">D=MPB</text><text x="203" y="30" font-size="9" fill="#0B1E3F">MPC</text><text x="223" y="20" font-size="9" fill="#0B1E3F" text-anchor="end">MSC</text><text x="118" y="80" font-size="8" fill="#B00020">DWL</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="225" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 5, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'State the two characteristics of a public good.', 'Non-rival (one person''s use does not diminish another''s) and non-excludable (cannot prevent non-payers from using). Lighthouses, defence, street lighting.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'What is the free-rider problem?', 'For non-excludable goods, individuals can consume without paying. Profit-maximising firms cannot recoup costs, so the good is under- or non-provided — justifying state provision via taxation.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'How does information failure cause market failure?', 'Asymmetric information (Akerlof''s lemons), misinformation or ignorance leads to suboptimal choices. Used-car buyers under-pay for good cars; consumers under-buy pensions or savings.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Evaluate using a Pigouvian (indirect) tax.', 'Strengths: internalises external cost, raises revenue, signals harm. Weaknesses: hard to set at exact MEC, regressive, evasion/black markets, inelastic demand limits effect.', 9, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Evaluate using a subsidy on a positive externality.', 'Strengths: lowers price to consumers, increases output to social optimum, encourages innovation. Weaknesses: opportunity cost, fiscal cost, risks dependency, hard to set at MEB, may favour wealthy producers.', 10, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'How does cap-and-trade (tradeable permits) work?', 'Government caps total emissions; firms trade permits. Polluters that cut emissions cheaply sell permits to those who can''t. EU ETS. Sets a price on carbon and falls in the cap tighten over time.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'When is a maximum price effective?', 'When set below the equilibrium and demand is responsive enough to fall to the new lower output. Side effects: shortage, queueing, black markets and informal rationing — e.g. UK rent controls of the 1970s. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="105" x2="205" y2="105" stroke="#B00020" stroke-width="1.2" stroke-dasharray="4 2"/><line x1="80" y1="105" x2="160" y2="105" stroke="#B00020" stroke-width="2"/><text x="120" y="120" font-size="8" fill="#B00020" text-anchor="middle">shortage</text><text x="208" y="107" font-size="9" fill="#B00020">P max</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 12, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'When is a minimum price effective?', 'When set above equilibrium with the surplus bought up by government — e.g. EU CAP for farm products, UK national living wage. Aim: support producers'' incomes or floor wages. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="50" x2="205" y2="50" stroke="#B00020" stroke-width="1.2" stroke-dasharray="4 2"/><line x1="65" y1="50" x2="170" y2="50" stroke="#B00020" stroke-width="2"/><text x="120" y="42" font-size="8" fill="#B00020" text-anchor="middle">surplus</text><text x="208" y="52" font-size="9" fill="#B00020">P min</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 13, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Distinguish state provision and direct regulation.', 'State provision: the public sector funds and supplies a good (NHS, BBC). Regulation: rules that constrain private behaviour (smoking ban, vehicle emissions standards).', 14, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Why is a behavioural ''nudge'' often used instead of bans?', 'It exploits cognitive biases at low cost: e.g. default opt-in pension enrolment, organ-donation choice architecture, calorie labelling. Preserves choice (libertarian paternalism, Thaler & Sunstein).', 15, 'alevel'),
  ('Economics', 'Edexcel A', '1.2', 'Market Failure and Government Intervention', 'Define government failure with one cause.', 'When intervention produces a worse allocation than the failed market. Causes: imperfect information, unintended consequences, regulatory capture, administrative cost, political short-termism, distortion of incentives.', 16, 'alevel');

-- Topic 2.1 — Economic Performance and Aggregate Demand
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'List the four main macroeconomic objectives.', 'Sustainable economic growth, low and stable inflation (~2% CPI), low unemployment, current account balance. Also: redistribution, balanced budget, environmental sustainability.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Distinguish nominal and real GDP.', 'Nominal: output at current prices. Real: output at constant (base-year) prices, stripping out inflation. Real GDP captures actual changes in output.', 2, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Why use GDP per capita and PPP?', 'Per capita corrects for population. PPP corrects for differences in cost of living between countries. Both make cross-country welfare comparisons more meaningful (Big Mac index).', 3, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Give three limitations of GDP as a welfare measure.', 'Ignores distribution; excludes informal/black economy and household production; ignores environmental costs; says nothing about leisure, health or political freedom.', 4, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Outline how CPI is calculated.', 'A weighted average of prices for a representative basket of goods consumed by households (Living Costs and Food Survey). Weights updated annually; CPI is the BoE target measure.', 5, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'List three limitations of CPI.', 'Excludes some housing costs; basket lags taste changes; represents the average household, not yours; quality changes hard to capture.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'How is unemployment measured (UK)?', 'Claimant count (administrative — those on Jobseeker''s Allowance/Universal Credit) and the Labour Force Survey/ILO measure (anyone willing/able to work who hasn''t worked in the last week).', 7, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Distinguish four types of unemployment.', 'Cyclical (demand-deficient), frictional (between jobs), structural (mismatched skills/regions), seasonal. Plus real-wage and classical/voluntary.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Write the AD equation and label its components.', 'AD = C + I + G + (X − M). Consumption (~60%), investment (~15%), government spending (~20%), and net exports (residual). All measured at constant prices.', 9, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Why does AD slope downwards?', 'Real-balance effect (lower P raises real wealth), interest-rate effect (lower P -> lower r -> more I and C), international trade effect (lower P boosts X, deters M).', 10, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Name three determinants of consumption.', 'Disposable income, interest rates, wealth (housing/financial), confidence, expectations of inflation, availability of credit, taxes/benefits.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Define gross and net investment.', 'Gross investment: total spending on new capital goods. Net = gross − depreciation. Net investment expands the capital stock and productive potential.', 12, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'List four determinants of investment.', 'Expected returns/animal spirits, interest rates, business confidence, corporate tax rates, technological change, retained profits, the accelerator.', 13, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'How does an exchange rate affect net exports?', 'A depreciation makes exports cheaper abroad and imports dearer, raising X − M (subject to the Marshall-Lerner condition and J-curve). Appreciation has the opposite effect.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'List four causes of an increase in AD.', 'Lower interest rates, lower income tax, weaker exchange rate, higher house prices, higher G, faster world growth, rising consumer confidence.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '2.1', 'Economic Performance and Aggregate Demand', 'Distinguish a movement along AD from a shift.', 'A movement is caused by a change in the price level. A shift is caused by a change in any non-price determinant of AD (income tax, interest rates, government spending, world demand).', 16, 'alevel');

-- Topic 2.2 — AS, National Income and Macroeconomic Policy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Distinguish SRAS and LRAS.', 'SRAS: upward-sloping; in the short run, sticky wages mean higher P raises profit margins and output. LRAS: vertical at full-employment Yfe (classical) or Keynesian (kinked) shape.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'List four determinants of SRAS.', 'Wages, raw material costs, business taxes/subsidies, exchange rate (import-cost channel), productivity, supply shocks (oil prices), regulation.', 2, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'List four determinants of LRAS.', 'Quantity/quality of labour, capital stock, technology and innovation, enterprise/incentives, education and skills, infrastructure, openness to trade.', 3, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Compare classical and Keynesian LRAS.', 'Classical: vertical at Yfe; AD changes only affect P. Keynesian: horizontal at low output (large spare capacity), upward sloping then vertical near Yfe; AD matters at low output. <svg viewBox="0 0 460 160" width="460" height="160" style="display:block;margin:6px auto"><g><line x1="30" y1="135" x2="200" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="140" y1="135" x2="140" y2="25" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="30" x2="180" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="200" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="143" y="20" font-size="9" fill="#0B1E3F">LRAS</text><text x="183" y="125" font-size="9" fill="#0B1E3F">AD</text><text x="115" y="155" font-size="9" fill="#0B1E3F" text-anchor="middle">Classical</text></g><g><line x1="260" y1="135" x2="440" y2="135" stroke="#0B1E3F"/><line x1="260" y1="135" x2="260" y2="20" stroke="#0B1E3F"/><path d="M260 110 L320 110 Q360 100 380 60 L380 25" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="270" y1="35" x2="420" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="440" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text><text x="258" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="383" y="22" font-size="9" fill="#0B1E3F">LRAS</text><text x="423" y="125" font-size="9" fill="#0B1E3F">AD</text><text x="350" y="155" font-size="9" fill="#0B1E3F" text-anchor="middle">Keynesian</text></g></svg>', 4, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Define the multiplier and give a formula.', 'Ratio of final ΔY to initial Δ injection. k = 1/(1−MPC) = 1/MPS in a closed, no-tax economy. With taxes and imports: k = 1/(MPS+MPT+MPM).', 5, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'List injections and withdrawals from the circular flow.', 'Injections: I, G, X. Withdrawals: S, T, M. Equilibrium when I + G + X = S + T + M; otherwise national income changes via the multiplier.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'List three benefits of economic growth.', 'Higher living standards, higher tax revenue, lower unemployment, easier redistribution, higher business investment, lower public-sector borrowing.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'List three costs of economic growth.', 'Demand-pull inflation, deteriorating current account, environmental damage, resource depletion, possible inequality, work-life imbalance.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Define monetary policy.', 'The use of interest rates and the money supply by the central bank to influence AD and meet the inflation target. UK: Bank Rate and QE, set by MPC, target 2% CPI.', 9, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Through which four channels does Bank Rate affect inflation?', 'Market rates (mortgages, savings), asset prices (housing, shares), confidence, exchange rate. Each affects AD with lags of 12-24 months.', 10, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'What is quantitative easing?', 'A central bank creates new electronic money to buy government bonds and other assets, raising bond prices, lowering long-term yields, raising bank reserves and asset prices, and stimulating AD.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Define fiscal policy.', 'The use of government spending (G) and taxation (T) to influence AD and the supply side. Set by HM Treasury in the annual Budget; subject to fiscal rules and the OBR.', 12, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Distinguish progressive, proportional and regressive taxes.', 'Progressive: average rate rises with income (income tax). Proportional: same % at every income (flat tax). Regressive: average rate falls (VAT, council tax).', 13, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'What are automatic stabilisers?', 'Built-in features of the tax/benefits system that smooth the cycle: tax revenues fall and benefit payments rise in a recession; both reverse in a boom — without explicit policy change.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Distinguish demand-side and supply-side policies.', 'Demand-side (monetary, fiscal) shifts AD to manage cycles. Supply-side raises LRAS (productive potential) over the long run via market reform, education, R&D and infrastructure.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '2.2', 'AS, National Income and Macro Policy', 'Give three examples of supply-side policies.', 'Income/corporation tax cuts, deregulation, privatisation, education and training, R&D subsidies, infrastructure investment, weakening of trade unions, immigration.', 16, 'alevel');

-- Topic 3.1 — Business Growth and Objectives
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Why do firms grow?', 'To exploit economies of scale, gain market power, diversify risk, increase profits/owners'' rewards, and meet managerial objectives (size, status). Constraints: regulators, finance, organisational complexity.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Distinguish organic and inorganic growth.', 'Organic: internal expansion (more sales, new products, new markets). Inorganic: mergers and acquisitions. Inorganic is faster but riskier and may run into regulatory/cultural challenges.', 2, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Distinguish horizontal, vertical and conglomerate integration.', 'Horizontal: same stage of same industry (Disney + Pixar). Vertical: different stages (PepsiCo + bottlers). Conglomerate: unrelated industries (Berkshire Hathaway).', 3, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Why do some firms remain small?', 'Niche markets, owner''s preference for control, low minimum efficient scale, personal service, finance constraints, government support of SMEs (small business rates relief).', 4, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Distinguish public sector and private sector.', 'Public sector: organisations funded and run by government (NHS, BBC, state schools). Private sector: privately owned firms aiming to make profit. Mixed economies have both.', 5, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'List four business objectives beyond profit max.', 'Revenue maximisation (Baumol — MR=0), sales maximisation (output max where AC=AR), satisficing (Simon — meet target rather than max), market share, social/ethical, survival.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Explain the principal-agent problem.', 'Owners (principals) and managers (agents) have different objectives and information. Without monitoring or incentives, managers may pursue empire-building or perks at the expense of profit.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Distinguish fixed, variable and total costs.', 'Fixed: do not change with output (rent). Variable: change with output (wages, raw materials). Total = FC + VC. Marginal cost = ΔTC/ΔQ.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'State the law of diminishing marginal returns.', 'In the short run, adding more of a variable input to a fixed input eventually causes the marginal product of that input to fall — driving rising MC.', 9, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'List four internal economies of scale.', 'Technical, purchasing (bulk discounts), managerial (specialist managers), financial (cheaper borrowing), marketing, risk-bearing. They lower long-run AC as output grows.', 10, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Distinguish economies and diseconomies of scale.', 'Economies: long-run AC falls as output rises. Diseconomies: AC rises beyond the minimum efficient scale, due to coordination, motivation and communication problems in large firms.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'What is minimum efficient scale (MES)?', 'The lowest output at which a firm''s long-run AC reaches its minimum. Industries with high MES tend to have few large firms and significant entry barriers.', 12, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Define total revenue, average revenue and marginal revenue.', 'TR = P×Q. AR = TR/Q = price (the demand curve). MR = ΔTR/ΔQ. For a price-taker AR = MR; for a price-maker MR < AR and slopes more steeply.', 13, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'State the profit-maximisation rule.', 'Produce the output at which MC = MR with MC rising. At this output, total profit (TR − TC) is largest.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Distinguish normal and supernormal profit.', 'Normal: minimum return needed to keep resources in their current use; counted as a cost. Supernormal: profit above normal — attracts entry in competitive markets, sustained only behind barriers.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '3.1', 'Business Growth and Objectives', 'Explain the divorce of ownership from control.', 'In large firms, owners (shareholders) are usually distinct from managers. Without effective monitoring, managers may pursue different objectives (revenue, status, perks) — the principal-agent problem.', 16, 'alevel');

-- Topic 3.2 — Market Structures and Labour
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Define an oligopoly with two examples.', 'A market dominated by a few large interdependent firms with significant entry barriers. Examples: UK supermarkets, big six energy suppliers, smartphone manufacturers, oil majors.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'How is concentration measured?', 'The n-firm concentration ratio (CR4 = combined market share of the top four firms). High CR4 (>50%) suggests an oligopolistic structure. Herfindahl-Hirschman Index (HHI) is also used.', 2, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Explain the kinked demand curve.', 'In oligopoly, rivals match price cuts (so demand below the kink is inelastic) but ignore price rises (so demand above is elastic). Result: price stickiness and a vertical gap in MR. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="35" x2="115" y2="75" stroke="#0B1E3F" stroke-width="1.5"/><line x1="115" y1="75" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="55" x2="115" y2="95" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><line x1="115" y1="115" x2="170" y2="125" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><line x1="115" y1="95" x2="115" y2="115" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><circle cx="115" cy="75" r="2.5" fill="#0B1E3F"/><text x="115" y="68" font-size="8" fill="#0B1E3F" text-anchor="middle">kink</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="170" y="135" font-size="9" fill="#0B1E3F">MR</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 3, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Distinguish collusive and non-collusive oligopoly.', 'Collusive: explicit (cartel — illegal in UK/EU) or tacit (price leadership). Non-collusive: independent rivalry, often through non-price competition or price wars.', 4, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Use a payoff matrix to explain the prisoner''s dilemma.', 'Two firms decide low/high price. Each has an individual incentive to undercut, even though both would profit more by colluding at high prices. Cartels are unstable without enforcement.', 5, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Define monopolistic competition with examples.', 'Many small firms with slightly differentiated products, low entry barriers — hairdressers, restaurants, plumbers. Each has a downward-sloping demand curve, but supernormal profit is competed away in the long run.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Define a pure monopoly and a working monopoly.', 'Pure: a single seller. Working/legal: a firm with ≥25% market share under the UK Competition Act 1998. Both have significant market power.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Outline three barriers to entry.', 'Economies of scale (large MES), high sunk costs, brand loyalty, predatory pricing, control of essential inputs, patents/copyrights, network effects, government licences.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Compare price and output of monopoly with perfect competition.', 'Monopoly: higher price, lower output, supernormal profit, allocative inefficiency (P > MC), often X-inefficient. Perfect competition: P = MC = minimum AC, normal profit only in long run. <svg viewBox="0 0 240 160" width="240" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="225" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="40" y1="35" x2="195" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="35" x2="120" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><path d="M40 90 Q90 130 130 95 T200 60" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><path d="M40 110 Q100 130 140 105 T210 75" stroke="#0B1E3F" stroke-width="1" fill="none" stroke-dasharray="3 2"/><line x1="30" y1="60" x2="100" y2="60" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="30" y1="92" x2="100" y2="92" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="100" y1="60" x2="100" y2="135" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><rect x="30" y="60" width="70" height="32" fill="#0B1E3F" fill-opacity="0.12"/><text x="198" y="130" font-size="9" fill="#0B1E3F">D=AR</text><text x="123" y="135" font-size="9" fill="#0B1E3F">MR</text><text x="200" y="62" font-size="9" fill="#0B1E3F">MC</text><text x="210" y="78" font-size="9" fill="#0B1E3F">AC</text><text x="28" y="63" font-size="9" fill="#0B1E3F" text-anchor="end">Pm</text><text x="100" y="148" font-size="9" fill="#0B1E3F" text-anchor="middle">Qm</text><text x="60" y="80" font-size="8" fill="#0B1E3F">profit</text></svg>', 9, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Outline three conditions needed for price discrimination.', 'Market power (price-maker), ability to identify groups with different PEDs, ability to prevent resale (no arbitrage). Examples: rail peak/off-peak, student/adult cinema, airline tickets.', 10, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Define the contestable-markets theory (Baumol).', 'A market is contestable if entry and exit are costless. Under threat of hit-and-run entry, even monopolists set price near AC. Implication: structure matters less than entry conditions.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Define the marginal revenue product of labour (MRPL).', 'The extra revenue from employing one more worker. MRPL = MPL × MR. Profit-maximising firms hire labour up to where MRPL = wage.', 12, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Name three determinants of demand for labour.', 'Wage rate, MRPL, the price of capital substitutes, demand for the final good, productivity, employment regulation. Demand for labour is derived from demand for the product.', 13, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'Define a monopsony in the labour market.', 'A single buyer of labour (e.g. NHS for nurses). The firm can set a wage below the competitive level and employs fewer workers, creating a deadweight loss.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'How can a trade union raise wages?', 'By collective bargaining backed by the threat of strikes. In a monopsony it can raise both wages and employment by counterbalancing the employer''s wage-setting power.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '3.2', 'Market Structures and Labour', 'List three causes of wage discrimination.', 'Imperfect information about productivity, monopsony power, prejudice/discrimination, occupational segregation, gaps in education or experience, the gender pay gap''s motherhood penalty.', 16, 'alevel');

-- Topic 4.1 — International Economics and Trade
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'State Ricardo''s law of comparative advantage.', 'Countries should specialise in goods they produce at the lowest opportunity cost and trade for the rest. Total output rises even if one country is absolutely better at everything.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Distinguish absolute and comparative advantage.', 'Absolute: producing more output per unit of input. Comparative: lower opportunity cost. Specialisation by comparative advantage maximises total world output.', 2, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Give two limitations of comparative advantage.', 'Assumes no transport costs, full employment, perfect mobility, constant returns. Ignores externalities, infant industries and the welfare cost of structural change.', 3, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'List four protectionist tools.', 'Tariffs, quotas, subsidies to domestic firms, non-tariff barriers (regulation, technical standards), exchange-rate intervention, embargoes.', 4, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Show the welfare effect of a tariff diagrammatically.', 'On supply/demand: domestic price rises by tariff. Producer surplus rises; consumer surplus falls more; government gets tariff revenue; deadweight loss appears as two triangles (production + consumption). <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="245" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="40" y1="30" x2="220" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="130" x2="220" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="100" x2="245" y2="100" stroke="#0B1E3F" stroke-width="1"/><line x1="30" y1="78" x2="245" y2="78" stroke="#0B1E3F" stroke-width="1"/><polygon points="80,100 100,78 100,100" fill="#B00020" fill-opacity="0.35"/><polygon points="180,100 160,78 180,78" fill="#B00020" fill-opacity="0.35"/><rect x="100" y="78" width="60" height="22" fill="#0B1E3F" fill-opacity="0.18"/><text x="225" y="125" font-size="9" fill="#0B1E3F">D</text><text x="225" y="35" font-size="9" fill="#0B1E3F">S</text><text x="248" y="103" font-size="9" fill="#0B1E3F">Pw</text><text x="248" y="80" font-size="9" fill="#0B1E3F">Pw+t</text><text x="125" y="93" font-size="8" fill="#0B1E3F" text-anchor="middle">tariff revenue</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="245" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 5, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Give three arguments for protectionism.', 'Infant industry, sunset industry, defence, anti-dumping, addressing externalities, balance-of-payments stabilisation, retaliation, jobs in vulnerable regions.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Outline the four stages of economic integration.', 'Free trade area (no tariffs), customs union (common external tariff), single/common market (free movement of factors), economic and monetary union (common currency). EU progressed through all four.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'What is the WTO''s main role?', 'Promotes liberal world trade by negotiating multilateral agreements, enforcing the Most-Favoured-Nation principle and arbitrating disputes between members. Successor to GATT (1995).', 8, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'List the four parts of the current account.', 'Trade in goods, trade in services, primary income (interest, profits, dividends), secondary income (transfers — remittances, EU/UN payments, foreign aid).', 9, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Distinguish causes of a current-account deficit.', 'Strong domestic demand, overvalued exchange rate, low productivity/competitiveness, deindustrialisation, slow trading-partner growth, high domestic inflation, structural shifts.', 10, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'State the Marshall-Lerner condition.', 'A depreciation improves the current account only if |PEDx| + |PEDm| > 1. In the short run elasticities are low — the J-curve — so the deficit may worsen before improving.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Distinguish floating and fixed exchange-rate regimes.', 'Floating: market sets the rate (US dollar, UK pound). Fixed: government pegs to another currency, defended via intervention or capital controls (Bretton Woods, HK dollar).', 12, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Effects of a depreciation on the macroeconomy?', 'Exports cheaper, imports dearer: improves current account (Marshall-Lerner), raises AD, but raises imported inflation. Helps domestic producers; hurts consumers/exporters dependent on imports.', 13, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'Define international competitiveness.', 'A country''s ability to sell its goods/services abroad relative to others. Measured by unit labour costs, real exchange rate, productivity. Weakens when costs rise faster than rivals''.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'List three benefits and two costs of globalisation.', 'Benefits: comparative advantage, FDI, tech transfer, lower prices. Costs: structural unemployment in losing sectors, environmental damage, race to the bottom in standards, MNC tax avoidance.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '4.1', 'International Economics and Trade', 'What is foreign direct investment (FDI)?', 'Investment by a firm in productive assets in another country (factories, subsidiaries). Brings capital, jobs, technology and managerial know-how but can crowd out domestic firms or repatriate profits.', 16, 'alevel');

-- Topic 4.2 — Poverty, Inequality and Development
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Distinguish absolute and relative poverty.', 'Absolute: income too low for basic needs (World Bank: $2.15/day, 2017 PPP). Relative: income below a societal benchmark (UK: 60% of median income). Relative measures inequality more than survival.', 1, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'How does the Lorenz curve work?', 'Plots cumulative % of population (x) against cumulative % of income (y). Perfect equality is the 45° line; the further the curve bows below, the more unequal the distribution. <svg viewBox="0 0 220 160" width="220" height="160" style="display:block;margin:6px auto"><line x1="30" y1="140" x2="200" y2="140" stroke="#0B1E3F"/><line x1="30" y1="140" x2="30" y2="20" stroke="#0B1E3F"/><line x1="30" y1="140" x2="190" y2="20" stroke="#0B1E3F" stroke-width="1.2" stroke-dasharray="3 2"/><path d="M30 140 Q120 140 190 20" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><text x="200" y="155" font-size="9" fill="#0B1E3F" text-anchor="end">% population</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">% income</text><text x="100" y="80" font-size="8" fill="#0B1E3F">equality</text><text x="120" y="125" font-size="8" fill="#0B1E3F">Lorenz</text></svg>', 2, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Define the Gini coefficient.', 'A summary inequality measure derived from the Lorenz curve: 0 = perfect equality, 1 = perfect inequality. UK around 0.35; Nordic countries below 0.30.', 3, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'List four causes of inequality.', 'Differences in skills/education, inheritance, discrimination, capital ownership, regressive tax/benefit changes, technological change favouring high skills, globalisation.', 4, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Distinguish economic growth and economic development.', 'Growth: rise in real GDP. Development: broader improvement in welfare — health, education, gender equality, freedom (Sen). HDI captures more than GDP.', 5, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'List the three components of HDI.', 'Life expectancy at birth (health), mean and expected years of schooling (education), GNI per capita PPP (income). Combined into a 0-1 index.', 6, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'List three barriers to development.', 'Primary product dependence, low savings/investment, capital flight, brain drain, corruption, civil war, debt overhang, demographic pressure, climate vulnerability.', 7, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Outline the Harrod-Domar model.', 'Growth depends on the savings rate divided by the capital-output ratio. Developing countries save little, so domestic investment is too low — case for foreign aid or FDI to plug the gap.', 8, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Define the Lewis dual-sector model.', 'A developing economy has a low-productivity rural/subsistence sector and a higher-productivity modern sector. Growth is driven by transferring surplus labour into the modern sector — drives urbanisation.', 9, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'What is the Prebisch-Singer hypothesis?', 'The terms of trade for primary products tend to deteriorate over time relative to manufactures, hurting commodity-dependent developing countries.', 10, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Distinguish bilateral and multilateral aid.', 'Bilateral: country-to-country (UK Foreign, Commonwealth and Development Office). Multilateral: through international institutions (World Bank, IMF, UN). Tied aid imposes conditions; untied does not.', 11, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Give two arguments for and against foreign aid.', 'For: relieves poverty, builds capacity, addresses humanitarian crises. Against: dependency, corruption, distorts incentives, ''Dutch disease'' from aid inflows, conditionality may impose poor policy.', 12, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Outline microfinance.', 'Small loans to low-income borrowers without collateral, often via group lending (Grameen Bank). Aims to fund small business; criticised for high interest, debt traps and limited macro impact.', 13, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Define fair trade.', 'A movement guaranteeing producers a minimum price plus a social premium, especially for primary commodities (coffee, cocoa). Trade-off: protected producers may overproduce, lowering wider market price.', 14, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Distinguish IMF and World Bank.', 'IMF: short-term BoP support, monetary stability, structural adjustment. World Bank: long-term project lending and poverty reduction (IBRD, IDA). Both Bretton Woods 1944, based in Washington DC.', 15, 'alevel'),
  ('Economics', 'Edexcel A', '4.2', 'Poverty, Inequality and Development', 'Define the trickle-down hypothesis.', 'The claim that policies enriching top earners (tax cuts, deregulation) eventually filter down through investment and jobs. Empirical evidence is contested and depends on the policy mix.', 16, 'alevel');
