-- A-Level Economics Flashcards (AQA, Edexcel A, Edexcel B, OCR)
-- Generated for the RAG Learning study app from existing notes HTML files
-- (notes-economics-{board}-alevel/). One INSERT per topic; card_order
-- restarts at 1 within each topic. Inline SVG diagrams are used only on
-- the cards where the diagram IS the answer (supply/demand shifts,
-- AD/AS, monopoly DWL, externality wedge, PPF, Lorenz, etc.) — not on
-- definition or evaluation cards.

-- ---------------------------------------------------------------
-- Schema migration: add 'level' column if not present (idempotent)
-- ---------------------------------------------------------------
ALTER TABLE flashcards ADD COLUMN IF NOT EXISTS level TEXT DEFAULT 'alevel'
  CHECK (level IN ('gcse','as','alevel'));

-- ===============================================================
-- AQA A-LEVEL
-- ===============================================================

-- Topic 3.1.1 — Economic Problem & Methodology
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Define the economic problem.', 'The fundamental challenge of scarcity: human wants are infinite but resources are finite, so choices and trade-offs must be made about how to allocate them.', 1, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'List the three fundamental economic questions every society must answer.', 'What to produce? How to produce it? For whom to produce it? Different economic systems answer these in different ways.', 2, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Define opportunity cost and give one example.', 'The value of the next best alternative foregone when a choice is made. E.g. the opportunity cost of attending university for three years includes the salary that could have been earned working full-time.', 3, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Sketch a PPF and label efficient, inefficient and unattainable points.', 'A concave (bowed-out) curve. Points ON the curve are productively efficient; INSIDE are inefficient (unemployed resources); OUTSIDE are currently unattainable. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M25,30 Q170,30 185,115" fill="none" stroke="#1a73e8" stroke-width="2"/><circle cx="70" cy="55" r="3" fill="#16a34a"/><text x="76" y="52" font-size="8" fill="#16a34a">A</text><circle cx="70" cy="100" r="3" fill="#f59e0b"/><text x="76" y="102" font-size="8" fill="#f59e0b">B</text><circle cx="160" cy="50" r="3" fill="#dc2626"/><text x="166" y="48" font-size="8" fill="#dc2626">C</text><text x="80" y="132" font-size="9" fill="#0B1E3F">Consumer goods</text><text x="2" y="65" font-size="9" fill="#0B1E3F" transform="rotate(-90,2,65)">Capital</text></svg>', 4, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Why is the PPF concave (bowed outwards)?', 'Because of the law of increasing opportunity cost: resources are not perfectly adaptable, so producing more of one good means giving up increasing amounts of the other.', 5, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Give two causes of an outward shift of the PPF.', 'More or better-quality factors of production (e.g. immigration, increased capital investment) and technological progress that raises productivity.', 6, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Name the four factors of production and their rewards.', 'Land (rent), labour (wages), capital (interest), enterprise (profit).', 7, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Distinguish capital goods from consumer goods.', 'Capital goods are man-made resources used to produce other goods (machinery, factories). Consumer goods are bought for direct satisfaction (food, smartphones). More capital today means a larger PPF tomorrow.', 8, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Distinguish positive and normative statements with one example each.', 'Positive: objective and testable (e.g. "UK unemployment is 4.2%"). Normative: subjective value judgement (e.g. "Unemployment is too high"). Look for words like should, ought to, fair, unfair.', 9, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'What is meant by ceteris paribus?', 'Latin for "all other things being equal" — an assumption that all other relevant variables are held constant while examining the effect of one variable. Essential for isolating relationships in economic models.', 10, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Compare a free-market and a command economy.', 'Free market: private ownership, prices set by supply and demand, profit motive (e.g. Hong Kong). Command: state ownership, central planning, social-welfare motive (e.g. North Korea). Most real economies are mixed.', 11, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'State the three functions of the price mechanism.', 'Signalling (prices convey information about scarcity), incentive (high prices encourage supply and discourage demand), and rationing (allocating scarce goods to those willing and able to pay).', 12, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'Outline two advantages of specialisation and division of labour.', 'Higher productivity through repetition and skill development, and lower average costs from economies of scale and use of specialist machinery (Adam Smith''s pin factory example).', 13, 'alevel'),
  ('Economics', 'AQA', '3.1.1', 'Economic Problem & Methodology', 'What is Hayek''s knowledge problem?', 'Friedrich Hayek argued that the information needed to allocate resources is dispersed across millions of individuals. Only the price mechanism can aggregate it; central planners cannot — a key critique of command economies.', 14, 'alevel');

-- Topic 3.1.2 — Price Determination
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Define demand and state the law of demand.', 'Demand is the quantity consumers are willing and able to buy at a given price. The law of demand: as price rises, quantity demanded falls (inverse relationship), ceteris paribus.', 1, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Give three reasons why the demand curve slopes downward.', 'Income effect (higher price reduces real purchasing power), substitution effect (consumers switch to cheaper alternatives), and diminishing marginal utility (each extra unit gives less satisfaction).', 2, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Distinguish a movement along from a shift of the demand curve.', 'A movement along (extension/contraction) is caused by a change in the good''s own price. A shift (increase/decrease in demand) is caused by a non-price factor like income, tastes, or prices of related goods.', 3, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Sketch market equilibrium with consumer and producer surplus shaded.', 'D and S intersect at (Pe, Qe). Consumer surplus is the triangle below D and above Pe; producer surplus is above S and below Pe. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="35" y1="25" x2="180" y2="110" stroke="#dc2626" stroke-width="2"/><text x="183" y="113" font-size="9" fill="#dc2626">D</text><line x1="35" y1="110" x2="180" y2="25" stroke="#1a73e8" stroke-width="2"/><text x="183" y="28" font-size="9" fill="#1a73e8">S</text><polygon points="35,25 107,67 25,67" fill="#16a34a" fill-opacity="0.15"/><polygon points="35,110 107,67 25,67" fill="#1a73e8" fill-opacity="0.15"/><circle cx="107" cy="67" r="2.5" fill="#0B1E3F"/><line x1="25" y1="67" x2="107" y2="67" stroke="#64748b" stroke-width="0.8" stroke-dasharray="2,2"/><line x1="107" y1="67" x2="107" y2="115" stroke="#64748b" stroke-width="0.8" stroke-dasharray="2,2"/><text x="10" y="70" font-size="9" fill="#0B1E3F">Pe</text><text x="103" y="128" font-size="9" fill="#0B1E3F">Qe</text><text x="80" y="130" font-size="9" fill="#0B1E3F">Q</text></svg>', 4, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'How does the market eliminate excess supply?', 'When P > Pe, quantity supplied exceeds quantity demanded, so producers cut prices and reduce output. As price falls, Qd rises and Qs falls until equilibrium is restored.', 5, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Show on a diagram what happens when D shifts right while S is fixed.', 'New equilibrium has both higher price and higher quantity. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="35" y1="35" x2="160" y2="110" stroke="#dc2626" stroke-width="2"/><text x="163" y="113" font-size="9" fill="#dc2626">D1</text><line x1="65" y1="25" x2="190" y2="100" stroke="#dc2626" stroke-width="2" stroke-dasharray="4,3"/><text x="172" y="98" font-size="9" fill="#dc2626">D2</text><line x1="35" y1="110" x2="180" y2="25" stroke="#1a73e8" stroke-width="2"/><text x="183" y="28" font-size="9" fill="#1a73e8">S</text><circle cx="92" cy="72" r="2.5" fill="#0B1E3F"/><circle cx="118" cy="57" r="2.5" fill="#0B1E3F"/><line x1="92" y1="72" x2="118" y2="57" stroke="#64748b" stroke-width="0.8"/><text x="105" y="50" font-size="8" fill="#0B1E3F">→</text><text x="80" y="130" font-size="9" fill="#0B1E3F">Q</text></svg>', 6, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Define consumer surplus.', 'The difference between the maximum price a consumer is willing to pay and the price they actually pay. On a diagram, the triangle below the demand curve and above the market price.', 7, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'State the formula for PED and what it measures.', 'PED = % change in quantity demanded ÷ % change in price. It measures the responsiveness of quantity demanded to a change in the good''s own price; always negative.', 8, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Sketch and contrast price-elastic and price-inelastic demand.', 'Elastic: relatively flat (|PED| > 1). Inelastic: relatively steep (|PED| < 1). <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="35" y1="50" x2="180" y2="80" stroke="#16a34a" stroke-width="2"/><text x="160" y="45" font-size="8" fill="#16a34a">elastic</text><line x1="95" y1="20" x2="125" y2="115" stroke="#dc2626" stroke-width="2"/><text x="128" y="40" font-size="8" fill="#dc2626">inelastic</text><text x="10" y="65" font-size="9" fill="#0B1E3F">P</text><text x="100" y="130" font-size="9" fill="#0B1E3F">Q</text></svg>', 9, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Give four determinants of PED.', 'Availability of substitutes, whether the good is a necessity or luxury, proportion of income spent on it, time period (PED is more elastic in the long run), and degree of habit/addiction.', 10, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'If demand is price-inelastic, what should a firm do to raise revenue?', 'Raise the price. With inelastic demand, the price rise outweighs the small fall in Qd, so total revenue (P x Q) increases. Firms with elastic demand should cut prices instead.', 11, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Distinguish a normal good from an inferior good using YED.', 'YED = %ΔQd ÷ %ΔY. Normal goods have positive YED (demand rises with income); inferior goods have negative YED (demand falls as income rises, e.g. supermarket value brands, bus travel).', 12, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'What does cross elasticity of demand (XED) tell you?', 'The relationship between two goods. Positive XED = substitutes (e.g. Coke and Pepsi). Negative XED = complements (e.g. printers and ink). The size shows the strength of the relationship.', 13, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'List three determinants of price elasticity of supply (PES).', 'Spare capacity, ability to store stocks, time period (longer = more elastic), factor mobility, and barriers to entry.', 14, 'alevel'),
  ('Economics', 'AQA', '3.1.2', 'Price Determination', 'Why are agricultural prices very volatile?', 'Both demand (food is a necessity) and short-run supply (fixed growing seasons) are price-inelastic, so a small supply shock — like the 2021 Brazilian frost that hit coffee — causes a large price swing.', 15, 'alevel');

-- Topic 3.1.3 — Production Costs & Revenue
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Define productivity and give the formula for labour productivity.', 'Productivity is output per unit of input in a given time period. Labour productivity = total output ÷ number of workers (or labour hours). Higher productivity is the main driver of long-run living standards.', 1, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Distinguish the short run from the long run.', 'Short run: at least one factor of production is fixed (usually capital). Long run: all factors are variable and the firm can change its entire scale of production.', 2, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'State the law of diminishing marginal returns.', 'As successive units of a variable factor (e.g. labour) are added to a fixed factor (e.g. capital), the marginal product eventually falls. A short-run concept only.', 3, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Distinguish fixed costs and variable costs with examples.', 'Fixed costs do not vary with output (rent, insurance, business rates) and exist even at zero output. Variable costs do vary with output (raw materials, hourly wages, energy).', 4, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Sketch the short-run cost curves (AFC, AVC, AC, MC).', 'AFC falls continuously; AVC and AC are U-shaped; MC cuts both AVC and AC at their minimums. The vertical gap between AC and AVC equals AFC. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M40,30 Q70,80 110,95 Q150,105 185,108" fill="none" stroke="#f59e0b" stroke-width="1.5" stroke-dasharray="4,2"/><text x="170" y="103" font-size="8" fill="#f59e0b">AFC</text><path d="M40,80 Q80,55 110,55 Q150,65 180,90" fill="none" stroke="#16a34a" stroke-width="1.5"/><text x="172" y="86" font-size="8" fill="#16a34a">AVC</text><path d="M40,55 Q80,35 115,40 Q150,50 180,75" fill="none" stroke="#1a73e8" stroke-width="1.5"/><text x="172" y="71" font-size="8" fill="#1a73e8">AC</text><path d="M40,95 Q70,90 90,75 Q115,40 145,20" fill="none" stroke="#dc2626" stroke-width="1.5"/><text x="148" y="22" font-size="8" fill="#dc2626">MC</text><text x="100" y="130" font-size="9" fill="#0B1E3F">Q</text></svg>', 5, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Why does MC cross AC at the minimum point of AC?', 'When MC < AC, the next unit pulls the average down. When MC > AC, it pulls the average up. Therefore AC is at its minimum exactly where MC = AC — the same logic as exam grades.', 6, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Define economies of scale.', 'Cost advantages a firm gains as it increases its scale of production in the long run; long-run average cost falls. Causes the downward-sloping section of the LRAC curve.', 7, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Name four types of internal economies of scale.', 'Technical (specialised machinery), managerial (specialist managers), purchasing (bulk buying), financial (cheaper borrowing), marketing (advertising spread over more units), risk-bearing (diversification).', 8, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Sketch the LRAC curve and label MES.', 'A U-shape: economies of scale (falling), then constant returns, then diseconomies (rising). MES is the lowest output where LRAC reaches its minimum. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M35,40 Q75,80 110,80 Q145,80 180,55" fill="none" stroke="#1a73e8" stroke-width="2"/><text x="160" y="50" font-size="9" fill="#1a73e8">LRAC</text><line x1="110" y1="80" x2="110" y2="115" stroke="#64748b" stroke-width="0.8" stroke-dasharray="2,2"/><text x="100" y="128" font-size="8" fill="#0B1E3F">MES</text><text x="40" y="105" font-size="7" fill="#16a34a">EoS</text><text x="140" y="40" font-size="7" fill="#dc2626">DoS</text><text x="100" y="138" font-size="9" fill="#0B1E3F">Q</text></svg>', 9, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Distinguish diminishing marginal returns from decreasing returns to scale.', 'Diminishing returns: SHORT RUN, one factor fixed, explains U-shaped SR cost curves. Decreasing returns to scale: LONG RUN, all factors increase together, explains rising LRAC. Confusing them is heavily penalised.', 10, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Define normal and supernormal profit.', 'Normal profit: minimum return needed to keep a firm in the industry (TR = TC, included as a cost). Supernormal profit: profit above normal (TR > TC), which signals new firms to enter.', 11, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'State the profit-maximising rule.', 'A firm maximises profit by producing the output where MC = MR (with MC rising through MR). At any unit where MR > MC, profit rises by producing it; where MR < MC, profit falls.', 12, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'For a firm with market power, why does MR lie below AR?', 'To sell one extra unit it must lower the price on ALL units (not just the extra one). The marginal revenue from the next sale is therefore less than its price. For a linear demand curve, MR is twice as steep as AR.', 13, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'When should a loss-making firm shut down in the short run?', 'When AR < AVC. If revenue covers variable costs and contributes to fixed costs, the firm loses less by continuing. If AR < AVC it should shut down immediately.', 14, 'alevel'),
  ('Economics', 'AQA', '3.1.3', 'Production Costs & Revenue', 'Give two alternative objectives to profit maximisation.', 'Revenue maximisation (MR = 0) — managers'' bonuses linked to sales. Sales maximisation (AC = AR, normal-profit constraint) — building market share, e.g. Amazon. Also satisficing and survival.', 15, 'alevel');

-- Topic 3.1.4 — Competitive & Concentrated Markets
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'List the four main market structures from most to least competitive.', 'Perfect competition, monopolistic competition, oligopoly, monopoly. They differ in number of firms, barriers to entry, product differentiation, and price-setting power.', 1, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'State the assumptions of perfect competition.', 'Many small buyers and sellers, homogeneous product, perfect information, no barriers to entry/exit, firms are price takers, perfectly mobile factors, no externalities. Largely a theoretical benchmark.', 2, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Why are perfectly competitive firms price takers with horizontal demand curves?', 'Each firm is too small to influence the market price, and consumers can switch costlessly to identical products. So AR = MR = P, shown as a horizontal line at the market price.', 3, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Why does perfect competition deliver only normal profit in the long run?', 'No barriers to entry mean any supernormal profit attracts new firms. Market supply shifts right, price falls until P = AC (minimum) and supernormal profit is competed away.', 4, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'In long-run perfect-competition equilibrium, which efficiencies are achieved?', 'Both: allocative efficiency (P = MC, value to consumers equals cost of last unit) and productive efficiency (output at minimum AC). Firms earn only normal profit.', 5, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'In UK competition law, what market share defines monopoly power?', 'A firm is classified as having monopoly power if it holds 25% or more of the market, the working definition used by the CMA. Pure (single-firm) monopoly is rare in practice.', 6, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Give four sources of monopoly power (barriers to entry).', 'Economies of scale / natural monopoly, patents and licences, brand loyalty and advertising, control of essential resources, network effects, sunk costs, predatory pricing.', 7, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Sketch the monopoly profit-max diagram with supernormal profit and DWL.', 'Profit max at MC=MR; price Pm read off AR=D above this output. Supernormal profit = (Pm - AC) x Qm; DWL is the triangle between Qm and the allocatively efficient Qc. <svg viewBox="0 0 200 150" width="180" height="135" style="display:block;margin:6px auto"><line x1="25" y1="125" x2="190" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="125" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="35" y1="25" x2="180" y2="120" stroke="#16a34a" stroke-width="1.5"/><text x="183" y="123" font-size="8" fill="#16a34a">AR=D</text><line x1="35" y1="25" x2="107" y2="120" stroke="#f59e0b" stroke-width="1.5"/><text x="110" y="118" font-size="8" fill="#f59e0b">MR</text><path d="M35,100 Q70,90 100,75 Q130,55 165,30" fill="none" stroke="#dc2626" stroke-width="1.5"/><text x="167" y="32" font-size="8" fill="#dc2626">MC</text><path d="M35,80 Q80,55 110,52 Q150,60 175,80" fill="none" stroke="#1a73e8" stroke-width="1.5"/><text x="178" y="84" font-size="8" fill="#1a73e8">AC</text><circle cx="80" cy="78" r="2" fill="#0B1E3F"/><line x1="80" y1="78" x2="80" y2="125" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="25" y1="55" x2="80" y2="55" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="11" y="58" font-size="8" fill="#0B1E3F">Pm</text><text x="74" y="138" font-size="8" fill="#0B1E3F">Qm</text><rect x="35" y="55" width="45" height="13" fill="#16a34a" fill-opacity="0.2"/><polygon points="80,55 80,78 115,72" fill="#dc2626" fill-opacity="0.2"/></svg>', 8, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Compared to perfect competition, what does a monopolist do?', 'Charges a higher price (Pm > Pc) and produces less output (Qm < Qc). This causes allocative inefficiency (P > MC) and a deadweight welfare loss; consumer surplus is transferred to producer surplus.', 9, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Give one Schumpeterian argument FOR monopoly.', 'Supernormal profits fund R&D and innovation, driving "creative destruction." Without the prospect of monopoly profits — especially via patents — firms would have less incentive to develop new products.', 10, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Define a natural monopoly.', 'A market where LRAC is still falling at the level of total market demand, so one firm can supply the whole market more cheaply than two. Examples: water, electricity transmission, railways. Usually regulated by Ofwat/Ofgem.', 11, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Define oligopoly and its key feature.', 'A market dominated by a few large interdependent firms (e.g. UK supermarkets, mobile networks). Key feature is INTERDEPENDENCE — each firm''s decisions depend on rivals'' likely reactions, leading to game-theory style strategy.', 12, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Distinguish collusive and non-collusive oligopoly.', 'Collusive: firms cooperate to fix prices/output (cartel) — illegal under UK/EU law. Non-collusive: firms compete strategically. Tacit collusion (price leadership) is legal but suspicious.', 13, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'What is the kinked demand curve theory?', 'Sweezy''s model: rivals match price cuts (so demand below P is inelastic) but ignore price rises (demand above P is elastic). A kink at the prevailing price explains why oligopoly prices are sticky.', 14, 'alevel'),
  ('Economics', 'AQA', '3.1.4', 'Competitive & Concentrated Markets', 'Give two examples of non-price competition in oligopoly.', 'Advertising and branding, product differentiation, loyalty schemes, customer service, packaging, R&D and innovation. Used because price wars are mutually destructive.', 15, 'alevel');

-- Topic 3.1.5 — Market Failure & Government Intervention
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Define market failure.', 'When the free market fails to allocate resources efficiently, leading to a net welfare loss. The market equilibrium does not match the socially optimal outcome where MSB = MSC.', 1, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'List four main causes of market failure.', 'Externalities, public goods, merit/demerit goods (information failure), monopoly power, factor immobility, and inequality.', 2, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'State the formulae for MSC and MSB.', 'MSC = MPC + MEC (marginal private cost + marginal external cost). MSB = MPB + MEB. Social optimum is where MSC = MSB.', 3, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Sketch a negative production externality with welfare loss.', 'MSC lies above MPC. Market produces at Qm (where MPC=MPB) but social optimum is Q* (where MSC=MSB). Triangle between Q* and Qm is the welfare loss from overproduction. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="35" y1="100" x2="180" y2="35" stroke="#1a73e8" stroke-width="1.8"/><text x="160" y="32" font-size="8" fill="#1a73e8">MPC</text><line x1="35" y1="80" x2="180" y2="20" stroke="#dc2626" stroke-width="1.8"/><text x="160" y="18" font-size="8" fill="#dc2626">MSC</text><line x1="35" y1="30" x2="180" y2="100" stroke="#16a34a" stroke-width="1.8"/><text x="160" y="105" font-size="8" fill="#16a34a">MSB</text><circle cx="115" cy="68" r="2" fill="#1a73e8"/><circle cx="100" cy="60" r="2" fill="#dc2626"/><line x1="115" y1="68" x2="115" y2="115" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="100" y1="60" x2="100" y2="115" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="110" y="128" font-size="8" fill="#1a73e8">Qm</text><text x="92" y="128" font-size="8" fill="#dc2626">Q*</text><polygon points="100,60 115,68 115,52" fill="#dc2626" fill-opacity="0.2"/></svg>', 4, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Give one example of a positive consumption externality.', 'Vaccination — the individual is protected (private benefit) but also can''t infect others, contributing to herd immunity. MSB > MPB, so the free market under-consumes; the NHS therefore provides vaccines free.', 5, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'State the two characteristics of a pure public good.', 'Non-excludable (cannot prevent non-payers using it) and non-rivalrous (one person''s use doesn''t reduce availability for others). Examples: defence, street lighting, lighthouses.', 6, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'What is the free-rider problem and why does it matter?', 'Because public goods are non-excludable, individuals can enjoy them without paying. Private firms cannot make a profit, so the good is not provided at all. Solved by compulsory taxation funding state provision.', 7, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Distinguish merit goods from public goods.', 'Merit goods are excludable and rivalrous — markets CAN provide them but provide too little (e.g. education, healthcare). Public goods CANNOT be provided by markets at all due to free riding. Different failures.', 8, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Distinguish adverse selection from moral hazard.', 'Adverse selection occurs BEFORE a transaction (hidden info, e.g. used-car "lemons"). Moral hazard occurs AFTER (changed behaviour, e.g. insured drivers being careless, banks taking risks if too-big-to-fail).', 9, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'How does an indirect tax correct a negative externality?', 'A specific or ad valorem tax raises producers'' costs, shifting MPC up to MSC. Output falls to the socially optimal Q*. Ideally the tax equals the marginal external cost — internalising the externality (Pigouvian tax).', 10, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Sketch the incidence of an indirect tax with inelastic demand.', 'Tax shifts S left to S+tax. Most of the tax is passed to consumers as higher prices because demand is inelastic. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="95" y1="20" x2="125" y2="115" stroke="#dc2626" stroke-width="1.8"/><text x="128" y="40" font-size="8" fill="#dc2626">D</text><line x1="35" y1="105" x2="180" y2="40" stroke="#1a73e8" stroke-width="1.8"/><text x="160" y="35" font-size="8" fill="#1a73e8">S</text><line x1="35" y1="85" x2="180" y2="20" stroke="#1a73e8" stroke-width="1.8" stroke-dasharray="4,3"/><text x="156" y="18" font-size="8" fill="#1a73e8">S+tax</text><circle cx="110" cy="68" r="2" fill="#0B1E3F"/><circle cx="105" cy="48" r="2" fill="#0B1E3F"/><line x1="25" y1="68" x2="110" y2="68" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="25" y1="48" x2="105" y2="48" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="10" y="71" font-size="8" fill="#0B1E3F">P1</text><text x="10" y="51" font-size="8" fill="#0B1E3F">P2</text></svg>', 11, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'How does the UK Soft Drinks Industry Levy correct demerit-good consumption?', 'The 2018 sugar tax raises the cost of sugary drinks (a demerit good), shifting supply left and reducing consumption. Over half of manufacturers reformulated drinks to fall below the threshold; revenue funds school sports.', 12, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Sketch a price ceiling (max price) below equilibrium and its consequence.', 'Price capped below Pe creates excess demand (shortage), as Qd > Qs. Used to protect consumers (e.g. rent controls). <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="35" y1="25" x2="180" y2="110" stroke="#dc2626" stroke-width="1.8"/><text x="183" y="113" font-size="8" fill="#dc2626">D</text><line x1="35" y1="110" x2="180" y2="25" stroke="#1a73e8" stroke-width="1.8"/><text x="183" y="28" font-size="8" fill="#1a73e8">S</text><line x1="25" y1="85" x2="180" y2="85" stroke="#f59e0b" stroke-width="1.5" stroke-dasharray="4,3"/><text x="160" y="82" font-size="8" fill="#f59e0b">Pmax</text><circle cx="65" cy="85" r="2" fill="#1a73e8"/><circle cx="143" cy="85" r="2" fill="#dc2626"/><text x="60" y="100" font-size="7" fill="#1a73e8">Qs</text><text x="138" y="100" font-size="7" fill="#dc2626">Qd</text><text x="80" y="78" font-size="8" fill="#0B1E3F">shortage</text></svg>', 13, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'Explain how tradable pollution permits work.', 'Government caps total emissions and issues permits for that amount. Firms trade them — clean firms sell, dirty firms buy. Price reflects the cost of pollution and incentivises cleaner technology. The EU ETS is the largest example.', 14, 'alevel'),
  ('Economics', 'AQA', '3.1.5', 'Market Failure & Government Intervention', 'What is government failure?', 'When government intervention to correct market failure makes outcomes worse — through unintended consequences, regulatory capture, information gaps, political short-termism, or excessive bureaucracy. The cure can be worse than the disease.', 15, 'alevel');

-- Topic 3.2.1 — Measurement of Macroeconomic Performance
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'List the four main UK macroeconomic objectives.', 'Sustained economic growth (~2-2.5%), low and stable inflation (CPI 2% target), low unemployment, and a satisfactory balance of payments. Plus equity, sustainable public finances, and environmental goals.', 1, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Give two conflicts between macroeconomic objectives.', 'Growth vs inflation (rapid growth causes demand-pull inflation); growth vs current account (imports rise with income); low unemployment vs inflation (Phillips curve trade-off).', 2, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Define GDP and write the expenditure formula.', 'GDP is the total monetary value of all final goods and services produced within a country in a period. GDP = C + I + G + (X - M).', 3, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Distinguish nominal from real GDP.', 'Nominal GDP is measured at current prices and rises with inflation alone. Real GDP is adjusted for inflation (constant base-year prices) and reflects the true change in output. Real GDP is the meaningful measure of growth.', 4, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Sketch the economic cycle around trend GDP.', 'Actual GDP fluctuates around the rising trend line through boom (peak), recession (contraction), trough (slump), and recovery. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="100" x2="185" y2="35" stroke="#64748b" stroke-width="1.5" stroke-dasharray="4,3"/><text x="160" y="30" font-size="8" fill="#64748b">trend</text><path d="M30,95 Q55,55 80,75 Q105,100 130,70 Q155,40 185,55" fill="none" stroke="#1a73e8" stroke-width="1.8"/><text x="55" y="55" font-size="7" fill="#16a34a">boom</text><text x="92" y="100" font-size="7" fill="#dc2626">recession</text><text x="100" y="130" font-size="9" fill="#0B1E3F">Time</text></svg>', 5, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Define a recession technically.', 'Two consecutive quarters of negative real GDP growth. Typically associated with rising unemployment, falling investment, and lower confidence — e.g. UK GDP fell 9.7% in 2020.', 6, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Give three limitations of GDP as a measure of living standards.', 'Hides income inequality; excludes shadow/non-marketed work (housework, voluntary); ignores environmental damage; doesn''t capture quality, leisure, or composition of output; PPP needed for international comparison.', 7, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'What does HDI measure beyond GDP?', 'The Human Development Index combines life expectancy, mean and expected years of schooling, and GNI per capita (PPP). Captures health and education outcomes, not just output.', 8, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Define inflation, deflation and disinflation.', 'Inflation: sustained rise in the average price level. Deflation: sustained fall. Disinflation: a fall in the rate of inflation (prices still rising, but more slowly, e.g. 10% to 5%).', 9, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Outline how CPI is calculated.', 'A representative basket of ~700 goods is selected and weighted by household spending shares. ONS collects ~180,000 prices monthly. The weighted average is expressed as an index relative to a base year of 100.', 10, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Give two reasons CPI may be a poor measure for individual households.', 'It is a national average, hiding different inflation rates for pensioners, students, families etc. It excludes mortgage interest, may have substitution bias, and quality adjustments are imprecise.', 11, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Distinguish the Claimant Count from the ILO/LFS unemployment measure.', 'Claimant Count: those claiming unemployment-related benefits (admin records, monthly). ILO/LFS: those without a job who actively sought work in the last 4 weeks and can start within 2 (survey, internationally comparable).', 12, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'List four types of unemployment.', 'Frictional (between jobs), structural (mismatch of skills/location), cyclical / demand-deficient (recession), seasonal, real-wage (classical, wage above market-clearing).', 13, 'alevel'),
  ('Economics', 'AQA', '3.2.1', 'Measurement of Macroeconomic Performance', 'Define the current account of the balance of payments.', 'Records international trade in goods and services, primary income (wages, investment income) and secondary income (transfers). The UK typically runs a current account deficit, financed by capital and financial inflows.', 14, 'alevel');

-- Topic 3.2.2 — How the Macroeconomy Works
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'List the injections and withdrawals in the circular flow.', 'Injections (J): Investment, Government spending, eXports. Withdrawals (W): Savings, Taxation, iMports. Equilibrium when J = W; if J > W, national income rises.', 1, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Write the AD formula and the largest component in the UK.', 'AD = C + I + G + (X - M). Consumption (C) is the largest, around 60% of UK AD.', 2, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Give three reasons the AD curve slopes downward.', 'Real-balance (wealth) effect — higher PL erodes savings; interest-rate effect — higher PL raises money demand and rates, cutting C and I; international competitiveness — higher PL hits net exports.', 3, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Sketch AD/AS equilibrium with an outward AD shift.', 'AD shifts right along upward-sloping SRAS, raising both real output and price level. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M35,100 Q90,75 150,40" fill="none" stroke="#1a73e8" stroke-width="2"/><text x="153" y="38" font-size="8" fill="#1a73e8">SRAS</text><line x1="40" y1="30" x2="160" y2="110" stroke="#dc2626" stroke-width="1.8"/><text x="163" y="113" font-size="8" fill="#dc2626">AD1</text><line x1="70" y1="25" x2="185" y2="105" stroke="#dc2626" stroke-width="1.8" stroke-dasharray="4,3"/><text x="178" y="100" font-size="8" fill="#dc2626">AD2</text><circle cx="86" cy="80" r="2" fill="#0B1E3F"/><circle cx="115" cy="60" r="2" fill="#0B1E3F"/><text x="100" y="130" font-size="9" fill="#0B1E3F">Y</text><text x="10" y="65" font-size="9" fill="#0B1E3F">PL</text></svg>', 4, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Define MPC and MPS and state the relationship.', 'MPC = ΔC/ΔY (fraction of extra income spent). MPS = ΔS/ΔY (fraction saved). In a simple closed economy with no tax, MPC + MPS = 1.', 5, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'List three factors that increase consumption.', 'Lower interest rates, rising consumer confidence, rising house and asset prices (wealth effect), tax cuts, easier credit availability.', 6, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'What is the accelerator effect?', 'A change in the rate of growth of demand causes a magnified change in investment. Rising consumer demand encourages firms to invest in new capacity; falling demand causes them to cut investment sharply.', 7, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Why is the SRAS curve upward-sloping?', 'In the short run, wages and other input costs are sticky. A higher price level raises profit margins, incentivising firms to expand output.', 8, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Give three causes of an SRAS shift left.', 'Rising wages, rising raw material/commodity/energy prices, exchange rate depreciation (imported inputs more expensive), higher indirect taxes, supply shocks (war, pandemic).', 9, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Sketch the Classical (vertical) LRAS curve.', 'LRAS is vertical at the full-employment output Yfe — long-run output is determined by productive capacity, not the price level. Shifts in AD only change PL. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="120" y1="20" x2="120" y2="115" stroke="#16a34a" stroke-width="2"/><text x="123" y="22" font-size="9" fill="#16a34a">LRAS</text><line x1="40" y1="30" x2="160" y2="110" stroke="#dc2626" stroke-width="1.8"/><text x="163" y="113" font-size="8" fill="#dc2626">AD</text><text x="115" y="128" font-size="8" fill="#0B1E3F">Yfe</text><text x="10" y="65" font-size="9" fill="#0B1E3F">PL</text></svg>', 10, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'Contrast Keynesian and Classical views of LRAS.', 'Classical: vertical LRAS — economy self-corrects to full employment via flexible wages/prices. Keynesian: LRAS has horizontal section (spare capacity), upward-sloping middle, then vertical at full capacity — wages and prices are sticky downward.', 11, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'List three causes of an LRAS shift right.', 'More/better factors of production (immigration, capital investment, education), technological progress, improved productivity, supply-side reforms, falling natural rate of unemployment.', 12, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'State the multiplier formula and what it represents.', 'k = 1/(1 - MPC) or k = 1/MPW. An initial injection (e.g. £1bn G) leads to a final increase in GDP of k x £1bn as spending circulates. A larger MPC = larger multiplier.', 13, 'alevel'),
  ('Economics', 'AQA', '3.2.2', 'How the Macroeconomy Works', 'If MPC = 0.8, what is the multiplier?', 'k = 1/(1 - 0.8) = 1/0.2 = 5. A £10bn injection raises real GDP by £50bn in equilibrium (assuming spare capacity).', 14, 'alevel');

-- Topic 3.2.3 — Economic Performance
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Distinguish actual from potential growth.', 'Actual growth: increase in real GDP (movement towards/along the PPF, AD shifts right). Potential growth: increase in productive capacity (PPF or LRAS shifts right). Sustainable growth requires both.', 1, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Define the output gap.', 'The difference between actual and potential GDP. Positive output gap: actual > potential (overheating, inflation pressure). Negative output gap: spare capacity, low inflation/deflation pressure.', 2, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Give three benefits of economic growth.', 'Higher living standards (more real income per head), lower unemployment (derived demand for labour), higher tax revenue (fiscal dividend), reduced poverty, higher business confidence.', 3, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Give three costs of economic growth.', 'Environmental degradation (pollution, resource depletion), demand-pull inflation if AD outpaces capacity, rising inequality, current account deterioration (more imports), longer working hours.', 4, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Sketch demand-pull inflation on AD/AS.', 'AD shifts right near full capacity; mainly the price level rises with little extra output. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M35,105 Q90,80 130,45 Q150,25 165,18" fill="none" stroke="#1a73e8" stroke-width="2"/><text x="167" y="20" font-size="8" fill="#1a73e8">SRAS</text><line x1="40" y1="35" x2="160" y2="110" stroke="#dc2626" stroke-width="1.8"/><text x="163" y="113" font-size="8" fill="#dc2626">AD1</text><line x1="65" y1="25" x2="185" y2="100" stroke="#dc2626" stroke-width="1.8" stroke-dasharray="4,3"/><text x="178" y="98" font-size="8" fill="#dc2626">AD2</text><circle cx="100" cy="75" r="2" fill="#0B1E3F"/><circle cx="125" cy="50" r="2" fill="#0B1E3F"/><line x1="25" y1="75" x2="100" y2="75" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="25" y1="50" x2="125" y2="50" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="8" y="78" font-size="8" fill="#0B1E3F">PL1</text><text x="8" y="53" font-size="8" fill="#0B1E3F">PL2</text></svg>', 5, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'What causes cost-push inflation? Sketch the diagram.', 'A leftward shift in SRAS (e.g. from 2022 gas prices) raises the price level while reducing output — stagflation. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M35,105 Q90,80 130,45 Q155,20 170,15" fill="none" stroke="#1a73e8" stroke-width="2"/><text x="172" y="17" font-size="8" fill="#1a73e8">SRAS1</text><path d="M35,90 Q80,60 115,30 Q135,15 145,10" fill="none" stroke="#1a73e8" stroke-width="2" stroke-dasharray="4,3"/><text x="100" y="22" font-size="8" fill="#1a73e8">SRAS2</text><line x1="40" y1="30" x2="160" y2="110" stroke="#dc2626" stroke-width="1.8"/><text x="163" y="113" font-size="8" fill="#dc2626">AD</text><circle cx="115" cy="65" r="2" fill="#0B1E3F"/><circle cx="93" cy="50" r="2" fill="#0B1E3F"/><line x1="25" y1="65" x2="115" y2="65" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="25" y1="50" x2="93" y2="50" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/></svg>', 6, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Define stagflation.', 'Simultaneously high inflation AND stagnant or falling output (low growth, often rising unemployment). Caused by adverse supply shocks shifting SRAS left — e.g. UK 2022, world economy in the 1970s oil crisis.', 7, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Give three consequences of high inflation.', 'Erodes real purchasing power (worst for those on fixed incomes), menu and shoe-leather costs, reduced international competitiveness, redistributes from savers to borrowers, fiscal drag, possible wage-price spiral.', 8, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Why do central banks fear deflation?', 'Consumers postpone spending (waiting for lower prices) → AD falls further. The real value of debt rises → defaults. Nominal rates hit zero (liquidity trap) so monetary policy is impotent. Japan''s "lost decades" illustrate this.', 9, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Sketch the short- and long-run Phillips curves.', 'SRPC slopes down (trade-off between unemployment and inflation). LRPC is vertical at the natural rate of unemployment (NRU). <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M35,30 Q70,55 110,90 Q140,108 180,112" fill="none" stroke="#1a73e8" stroke-width="2"/><text x="160" y="105" font-size="8" fill="#1a73e8">SRPC</text><line x1="115" y1="20" x2="115" y2="115" stroke="#dc2626" stroke-width="2"/><text x="118" y="22" font-size="8" fill="#dc2626">LRPC</text><text x="105" y="128" font-size="8" fill="#dc2626">NRU</text><text x="100" y="138" font-size="9" fill="#0B1E3F">U%</text><text x="6" y="65" font-size="9" fill="#0B1E3F">π%</text></svg>', 10, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Why is the long-run Phillips curve vertical?', 'Friedman/Phelps: any short-run trade-off depends on expectations. As workers learn that policy has raised inflation, they demand higher wages — SRPC shifts up. In the long run, unemployment returns to the NRU regardless of inflation.', 11, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Define the natural rate of unemployment (NRU).', 'The unemployment that exists when the labour market is in equilibrium — the sum of frictional and structural unemployment. Cyclical unemployment is zero. Cannot be reduced by demand-side policy alone.', 12, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'Give three consequences of unemployment.', 'Lost output (economy inside PPF), lost tax revenue and higher benefit spending (fiscal cost), deskilling (hysteresis), poverty and inequality, social/health problems, lower aggregate demand.', 13, 'alevel'),
  ('Economics', 'AQA', '3.2.3', 'Economic Performance', 'What is hysteresis in labour markets?', 'The tendency for unemployment to persist after the original cause has passed. Long-term unemployed workers lose skills, motivation, and networks — raising the NRU. Justifies aggressive demand-side action in deep recessions.', 14, 'alevel');

-- Topic 3.2.4 — Financial Markets & Monetary Policy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'List four key functions of financial markets.', 'Facilitating saving, channelling funds from savers to borrowers (intermediation), providing liquidity, pricing risk, enabling firms to raise capital (shares/bonds), and facilitating international trade via FX.', 1, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Distinguish money markets from capital markets.', 'Money markets trade short-term debt (under 1 year) — Treasury bills, interbank loans. Capital markets trade long-term debt (bonds) and equity (shares). Primary = new issues; secondary = existing securities.', 2, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'State the four functions of money.', 'Medium of exchange (eliminates barter), store of value (holds purchasing power over time), unit of account (common measure of value), and standard of deferred payment (enables credit/contracts).', 3, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'How do commercial banks create money?', 'When a bank makes a loan it credits a new deposit in the borrower''s account. As that money is spent and re-deposited, the cycle repeats — most money in the economy is bank deposits, not central-bank cash.', 4, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Sketch the money market with an increase in money supply.', 'MS is vertical (set by the BoE). MD slopes down (liquidity preference). MS shifts right → equilibrium interest rate falls. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="90" y1="20" x2="90" y2="115" stroke="#1a73e8" stroke-width="2"/><text x="80" y="18" font-size="8" fill="#1a73e8">MS1</text><line x1="135" y1="20" x2="135" y2="115" stroke="#1a73e8" stroke-width="2" stroke-dasharray="4,3"/><text x="138" y="18" font-size="8" fill="#1a73e8">MS2</text><line x1="35" y1="30" x2="180" y2="105" stroke="#dc2626" stroke-width="1.8"/><text x="183" y="108" font-size="8" fill="#dc2626">MD</text><circle cx="90" cy="58" r="2" fill="#0B1E3F"/><circle cx="135" cy="81" r="2" fill="#0B1E3F"/><line x1="25" y1="58" x2="90" y2="58" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="25" y1="81" x2="135" y2="81" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="10" y="61" font-size="8" fill="#0B1E3F">r1</text><text x="10" y="84" font-size="8" fill="#0B1E3F">r2</text></svg>', 5, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'State Keynes'' three motives for holding money.', 'Transactions (everyday spending — depends on income), precautionary (buffer for emergencies — depends on income/uncertainty), speculative (anticipating bond price changes — inversely related to the interest rate).', 6, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'What is the liquidity trap?', 'When interest rates are at or near zero, MD becomes perfectly elastic — extra money is hoarded rather than spent or used to buy bonds. Conventional monetary policy becomes ineffective; QE may be needed.', 7, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Why was the Bank of England granted independence in 1997?', 'To remove political short-termism (the political business cycle), improve credibility and anchor inflation expectations, and align with international norms. The MPC sets Bank Rate to meet the 2% CPI target.', 8, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Outline the transmission mechanism of a Bank Rate cut.', 'Lower Bank Rate → cheaper borrowing and lower returns on saving → C and I rise; weaker pound → exports rise, imports fall; asset prices rise (wealth effect). All increase AD and the price level.', 9, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Define quantitative easing (QE).', 'Unconventional monetary policy where the central bank creates electronic reserves to buy government bonds and other assets. This raises bond prices, lowers long-term yields, and boosts liquidity, lending and AD.', 10, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Give two side effects of prolonged QE.', 'Inflated asset prices (housing, equities) which worsens wealth inequality; risks of asset bubbles; difficulty unwinding (quantitative tightening); some loss of central-bank independence credibility.', 11, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'What is the relationship between bond prices and interest rates?', 'Inverse. When market rates rise, existing bonds with lower coupons become less attractive, so their price falls. When rates fall, existing bonds become more attractive and their price rises.', 12, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Explain why banks failed during the 2008 financial crisis.', 'Excessive risk-taking, sub-prime mortgage lending, complex derivatives (CDOs) hiding risk, high leverage, moral hazard ("too big to fail"), and inadequate regulation. The UK government spent ~£137bn rescuing banks.', 13, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'Give three post-2008 financial regulations.', 'Higher capital requirements (Basel III), separation of retail and investment banking (UK ring-fencing under Vickers), stress testing by the BoE, the FPC for macroprudential oversight, and the PRA for bank supervision.', 14, 'alevel'),
  ('Economics', 'AQA', '3.2.4', 'Financial Markets & Monetary Policy', 'What does the Bank of England do as "lender of last resort"?', 'Provides emergency liquidity to solvent commercial banks facing temporary cash shortages, preventing bank runs and systemic collapse. Critical during the 2007-08 Northern Rock crisis.', 15, 'alevel');

-- Topic 3.2.5 — Fiscal & Supply-Side Policies
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Define fiscal policy and name its two main instruments.', 'The use of government spending (G) and taxation (T) to influence AD and macroeconomic objectives. Set by the Chancellor in the Budget; affects AD directly (G) and indirectly via C and I (T).', 1, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Distinguish current spending, capital spending, and transfer payments.', 'Current: day-to-day costs (NHS wages, school running costs). Capital: long-lived assets (hospitals, HS2). Transfers: payments without goods/services in return (pensions, Universal Credit) — not in GDP but boost C.', 2, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Distinguish progressive, regressive and proportional taxes.', 'Progressive: % paid rises with income (UK income tax). Regressive: % paid falls as income rises (VAT — flat rate but lower earners spend a higher share). Proportional: constant % regardless of income.', 3, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'List Adam Smith''s four canons of taxation.', 'Equity (fairness, ability to pay), economy (low collection costs), convenience (easy to pay), certainty (clear rules). Modern additions: flexibility and efficiency (low distortion).', 4, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Distinguish a budget deficit from the national debt.', 'Budget deficit: a flow — government spending exceeds tax in a year (G > T). National debt: a stock — total accumulated past borrowing. UK debt exceeded 100% of GDP after COVID.', 5, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Distinguish cyclical from structural deficits.', 'Cyclical: caused by the economic cycle — disappears when growth returns. Structural: persists even at full employment, requiring deliberate cuts or tax rises. Cutting cyclical deficits in a recession can deepen it.', 6, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Sketch expansionary fiscal policy on AD/AS.', 'Increase in G or cut in T shifts AD right; real GDP rises and PL increases. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><path d="M35,105 Q90,80 130,45 Q150,25 165,18" fill="none" stroke="#1a73e8" stroke-width="2"/><text x="167" y="20" font-size="8" fill="#1a73e8">SRAS</text><line x1="40" y1="30" x2="160" y2="110" stroke="#dc2626" stroke-width="1.8"/><text x="163" y="113" font-size="8" fill="#dc2626">AD1</text><line x1="70" y1="25" x2="185" y2="100" stroke="#dc2626" stroke-width="1.8" stroke-dasharray="4,3"/><text x="178" y="98" font-size="8" fill="#dc2626">AD2</text><circle cx="100" cy="75" r="2" fill="#0B1E3F"/><circle cx="125" cy="50" r="2" fill="#0B1E3F"/><line x1="25" y1="75" x2="100" y2="75" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="100" y1="75" x2="100" y2="115" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="125" y1="50" x2="125" y2="115" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="95" y="128" font-size="7" fill="#0B1E3F">Y1</text><text x="120" y="128" font-size="7" fill="#0B1E3F">Y2</text></svg>', 7, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Give two examples of automatic stabilisers.', 'Progressive income tax (takes more in booms, less in recessions) and means-tested welfare benefits (rise in recessions as unemployment increases, fall in booms). They dampen the cycle without explicit policy decisions.', 8, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Distinguish demand-side from supply-side policies.', 'Demand-side: shift AD (fiscal and monetary policy). Supply-side: shift LRAS by raising productive potential (education, training, deregulation, infrastructure, tax incentives).', 9, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'List four supply-side policies.', 'Investment in education and training, infrastructure (HS2, broadband), reducing income tax to incentivise work, cutting corporation tax to encourage investment, deregulating labour/product markets, privatisation.', 10, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Distinguish interventionist from market-based supply-side policies.', 'Interventionist: government action to fix market failures (state spending on training, infrastructure, R&D grants). Market-based: reducing state involvement (tax cuts, deregulation, privatisation, weaker trade unions).', 11, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Sketch a successful supply-side policy on AD/AS.', 'LRAS shifts right; output rises and the price level falls — non-inflationary growth. <svg viewBox="0 0 200 140" width="180" height="125" style="display:block;margin:6px auto"><line x1="25" y1="115" x2="190" y2="115" stroke="#0B1E3F" stroke-width="1.5"/><line x1="25" y1="115" x2="25" y2="15" stroke="#0B1E3F" stroke-width="1.5"/><line x1="100" y1="20" x2="100" y2="115" stroke="#16a34a" stroke-width="2"/><text x="78" y="22" font-size="8" fill="#16a34a">LRAS1</text><line x1="135" y1="20" x2="135" y2="115" stroke="#16a34a" stroke-width="2" stroke-dasharray="4,3"/><text x="138" y="22" font-size="8" fill="#16a34a">LRAS2</text><line x1="40" y1="30" x2="170" y2="115" stroke="#dc2626" stroke-width="1.8"/><text x="173" y="113" font-size="8" fill="#dc2626">AD</text><circle cx="100" cy="75" r="2" fill="#0B1E3F"/><circle cx="135" cy="98" r="2" fill="#0B1E3F"/><line x1="25" y1="75" x2="100" y2="75" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><line x1="25" y1="98" x2="135" y2="98" stroke="#64748b" stroke-width="0.7" stroke-dasharray="2,2"/><text x="8" y="78" font-size="8" fill="#0B1E3F">PL1</text><text x="8" y="101" font-size="8" fill="#0B1E3F">PL2</text></svg>', 12, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Give two evaluation points on supply-side policies.', 'Long time lags (education takes years to feed through), high opportunity cost, may worsen inequality (e.g. tax cuts for high earners), success uncertain — many supply-side reforms (UK 1980s) had mixed results.', 13, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Define crowding out.', 'When increased government borrowing pushes up interest rates, reducing private investment and consumption. Most likely when the economy is near full capacity; less of a concern in deep recessions with spare savings.', 14, 'alevel'),
  ('Economics', 'AQA', '3.2.5', 'Fiscal & Supply-Side Policies', 'Compare the UK''s 2010-15 austerity with the 2020-21 COVID stimulus.', 'Austerity: contractionary — VAT rose to 20%, public-sector pay frozen, welfare cuts; deficit fell but recovery was slow. COVID stimulus: expansionary — £70bn furlough, business grants, Eat Out to Help Out; debt rose past 100% of GDP but mass unemployment was avoided.', 15, 'alevel');
