-- A-Level Economics Flashcards (OCR)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.

-- ===============================================================
-- OCR A-LEVEL
-- ===============================================================

-- Topic 1.1 — The Economic Problem and Market Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'What is the central economic problem?', 'Scarcity: human wants are unlimited but the resources (factors of production) available to satisfy them are finite, so choices must be made about what to produce, how, and for whom.', 1, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'List the four factors of production with their respective rewards.', 'Land (rent), labour (wages), capital (interest), enterprise (profit). Enterprise organises the others and bears the residual risk.', 2, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define opportunity cost.', 'The value of the next-best alternative forgone when a choice is made. Applies to consumers (spending), firms (factor use) and governments (budget allocation).', 3, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'What does a Production Possibility Frontier (PPF) show?', 'The maximum combinations of two goods an economy can produce when all resources are fully and efficiently employed, given the current state of technology. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><path d="M30 25 Q70 32 130 75 T200 130" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Good X</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">Good Y</text><text x="135" y="105" font-size="9" fill="#0B1E3F">PPF</text></svg>', 4, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Why is a PPF typically concave to the origin?', 'Because resources are not equally productive in all uses; reallocating them yields increasing opportunity costs as factors better suited to the other good must be transferred.', 5, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Distinguish positive and normative statements.', 'Positive: testable factual claim (UK CPI inflation was 4% in March). Normative: value judgement (the government should cut taxes). Mixing them up is a common evaluation pitfall.', 6, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Distinguish a free market, command and mixed economy.', 'Free market: resources allocated by price signals and private ownership. Command: state plans and owns resources. Mixed: combines private market with public sector and regulation — most real economies.', 7, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'State the law of demand.', 'Ceteris paribus, as price falls, quantity demanded rises. Demand curves slope downwards because of substitution effect, income effect and diminishing marginal utility.', 8, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'State the law of supply.', 'Ceteris paribus, as price rises, quantity supplied rises. Supply curves slope upwards because higher prices cover higher marginal costs and incentivise producers to expand output.', 9, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'How is market equilibrium determined?', 'At the price where Qd = Qs. Surpluses push price down; shortages push it up. The price mechanism rations, signals and incentivises (Adam Smith''s ''invisible hand''). <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="78" x2="120" y2="78" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="120" y1="78" x2="120" y2="130" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="81" font-size="9" fill="#0B1E3F" text-anchor="end">P*</text><text x="120" y="145" font-size="9" fill="#0B1E3F" text-anchor="middle">Q*</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 10, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define PED and three determinants.', 'PED = % ΔQd / % ΔP. Determinants: substitutes (more = elastic), share of income, necessity vs luxury, time period (longer = more elastic), addiction.', 11, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define YED and interpret three values.', 'YED = % ΔQd / % Δincome. >1: luxury (income elastic). 0<YED<1: necessity. Negative: inferior good — demand falls as income rises.', 12, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define XED and interpret its sign.', 'XED = % ΔQd of A / % ΔP of B. Positive: substitutes. Negative: complements. Magnitude shows closeness of relationship.', 13, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define PES and three determinants.', 'PES = % ΔQs / % ΔP. Determinants: spare capacity, ease of stockholding, factor mobility, time period (longer is more elastic), barriers to entry.', 14, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define consumer and producer surplus.', 'Consumer surplus: amount consumers were willing to pay above actual price. Producer surplus: amount producers receive above their minimum acceptable price. Both contribute to total welfare.', 15, 'alevel'),
  ('Economics', 'OCR', '1.1', 'The Economic Problem and Market Systems', 'Define specialisation and the division of labour.', 'Specialisation: workers/firms/countries focus on what they do best. Division of labour: production split into specialised tasks (Smith''s pin factory) — raises productivity but risks monotony.', 16, 'alevel');

-- Topic 1.2 — Market Failure and Government Intervention
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Define market failure.', 'When the free market fails to allocate resources efficiently, leading to a welfare loss. Forms: externalities, public goods, information failure, monopoly power, inequality.', 1, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Distinguish private, external and social cost.', 'Private cost: borne by producer/consumer. External cost: spillover on third parties (pollution). Social cost = private + external. Markets ignore externals -> overproduction.', 2, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'How do you identify a negative production externality on a diagram?', 'MSC lies above MPC. Free-market output where MPB = MPC exceeds the social optimum where MSB = MSC, creating a deadweight welfare loss triangle. <svg viewBox="0 0 240 150" width="240" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="225" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="200" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="200" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="65" y1="125" x2="220" y2="22" stroke="#0B1E3F" stroke-width="1.5" stroke-dasharray="3 2"/><polygon points="115,75 145,55 145,90" fill="#B00020" fill-opacity="0.3"/><text x="203" y="125" font-size="9" fill="#0B1E3F">D=MPB</text><text x="203" y="30" font-size="9" fill="#0B1E3F">MPC</text><text x="223" y="20" font-size="9" fill="#0B1E3F" text-anchor="end">MSC</text><text x="118" y="80" font-size="8" fill="#B00020">DWL</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="225" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 3, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Distinguish merit and demerit goods.', 'Merit goods: undervalued, underconsumed (education, healthcare). Demerit goods: overvalued, overconsumed (cigarettes, alcohol). Reflect information failure and externalities.', 4, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'State the two characteristics of a public good.', 'Non-rival (one person''s use does not reduce another''s) and non-excludable (no one can be prevented from using). Examples: street lighting, national defence.', 5, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'What is the free-rider problem?', 'Because public goods are non-excludable, individuals can benefit without paying. Profit-maximising firms cannot recoup costs, so the market under-provides — justifying state provision.', 6, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'How does asymmetric information cause market failure?', 'When one party has more information than the other. Examples: used cars (Akerlof''s lemons), insurance (moral hazard, adverse selection), pensions (consumer ignorance).', 7, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Evaluate using an indirect (Pigouvian) tax.', 'Strengths: internalises external cost, raises revenue, signals harm. Weaknesses: hard to set at exact MEC, regressive, evasion/black markets, inelastic demand limits effect.', 8, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Evaluate using a subsidy on a positive externality.', 'Strengths: lowers price, raises output to social optimum, encourages innovation. Weaknesses: opportunity cost, dependency, hard to set at MEB, may favour wealthy producers.', 9, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'How does cap-and-trade (tradeable permits) work?', 'Government caps total emissions; firms hold permits they may trade. Polluters cutting emissions cheaply sell permits to those who can''t. Sets a market price on carbon — EU ETS.', 10, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'When is a maximum price effective?', 'Set below equilibrium with elastic demand. Side effects: shortages, queueing, black markets, poor quality. UK rent controls in the 1970s reduced housing supply. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="105" x2="205" y2="105" stroke="#B00020" stroke-width="1.2" stroke-dasharray="4 2"/><line x1="80" y1="105" x2="160" y2="105" stroke="#B00020" stroke-width="2"/><text x="120" y="120" font-size="8" fill="#B00020" text-anchor="middle">shortage</text><text x="208" y="107" font-size="9" fill="#B00020">P max</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 11, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'When is a minimum price effective?', 'Set above equilibrium with surplus bought up by government — EU CAP, UK national living wage. Aim: support producer incomes or floor wages. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="50" x2="205" y2="50" stroke="#B00020" stroke-width="1.2" stroke-dasharray="4 2"/><line x1="65" y1="50" x2="170" y2="50" stroke="#B00020" stroke-width="2"/><text x="120" y="42" font-size="8" fill="#B00020" text-anchor="middle">surplus</text><text x="208" y="52" font-size="9" fill="#B00020">P min</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 12, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Distinguish state provision and direct regulation.', 'State provision: public sector funds and supplies the good (NHS). Regulation: rules constrain private behaviour (smoking ban, vehicle emissions standards).', 13, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Define government failure with one cause.', 'When intervention produces a worse allocation than the failed market. Causes: imperfect information, unintended consequences, regulatory capture, administrative cost, political short-termism.', 14, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'What is regulatory capture?', 'When the regulator comes to act in the interests of the industry it regulates rather than consumers, due to lobbying, revolving doors of personnel, or asymmetric information.', 15, 'alevel'),
  ('Economics', 'OCR', '1.2', 'Market Failure and Government Intervention', 'Give an example of unintended consequences.', 'Rent controls reducing housing supply and quality; cigarette taxes funding smuggling; subsidies for biofuels raising food prices; minimum alcohol pricing hitting low-income moderate drinkers.', 16, 'alevel');

-- Topic 1.3 — Firm Objectives, Costs and Revenue
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Distinguish production from productivity.', 'Production = total quantity of output produced. Productivity = output per unit of input (e.g. labour productivity = output per worker per hour). Productivity drives long-run living standards.', 1, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'State the law of diminishing marginal returns.', 'In the short run, as more variable input is added to a fixed input, the marginal product of the variable input eventually falls. Causes the short-run MC curve to slope upward.', 2, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Distinguish fixed and variable costs.', 'Fixed costs do not vary with output (rent, insurance, salaried staff). Variable costs change with output (raw materials, hourly wages). FC + VC = TC.', 3, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Define average cost and marginal cost.', 'AC = TC/Q (cost per unit). MC = ΔTC/ΔQ (cost of producing one more unit). MC cuts AC at its minimum because adding a unit cheaper than average pulls average down.', 4, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Why is the short-run AC curve U-shaped?', 'Initially, spreading FC over more units lowers AFC and AC; eventually diminishing returns raise AVC and pull AC back up. The minimum is the productively efficient level of output. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><path d="M40 50 Q90 110 130 80 T200 35" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><path d="M40 90 Q100 120 140 95 T200 50" stroke="#0B1E3F" stroke-width="1.5" fill="none" stroke-dasharray="3 2"/><circle cx="125" cy="92" r="2.5" fill="#0B1E3F"/><text x="198" y="35" font-size="9" fill="#0B1E3F">MC</text><text x="198" y="55" font-size="9" fill="#0B1E3F">AC</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">£</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 5, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Define returns to scale.', 'Long-run response of output to a proportional change in all inputs. Increasing returns: output rises more than proportionally. Constant: same. Decreasing: less than proportional.', 6, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'List four internal economies of scale.', 'Technical (specialised capital), purchasing (bulk-buy discounts), managerial (specialist managers), financial (cheaper borrowing), marketing, risk-bearing. Lower long-run AC as output grows.', 7, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'What are diseconomies of scale?', 'Rises in long-run AC as a firm grows past its minimum efficient scale, due to coordination problems, communication breakdown, motivational issues and X-inefficiency from weak supervision.', 8, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Distinguish internal and external economies of scale.', 'Internal: arise within the firm as it grows. External: arise within the industry as a whole (skilled labour pool, specialist suppliers, infrastructure clustering — e.g. Silicon Valley).', 9, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Define total, average and marginal revenue.', 'TR = P×Q. AR = TR/Q = price (the demand curve). MR = ΔTR/ΔQ. For a price-taker AR = MR; for a price-maker MR < AR and slopes more steeply.', 10, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'State the profit-maximisation rule.', 'Produce where MC = MR (and MC is rising). At this output, total profit (TR − TC) is largest.', 11, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Distinguish normal and supernormal profit.', 'Normal: minimum return needed to keep resources in their current use; counted as a cost in economics. Supernormal: profit above normal — attracts entry in competitive markets.', 12, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'State the short-run shut-down rule.', 'A firm continues operating in the short run as long as P >= AVC, since variable costs are covered. If P < AVC, shut down to limit losses to fixed costs.', 13, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Distinguish productive and allocative efficiency.', 'Productive efficiency: producing at minimum AC (no waste of resources). Allocative efficiency: producing the goods consumers value most, where P = MC, maximising welfare.', 14, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Why might a firm have other objectives than profit-maximisation?', 'Imperfect information, principal-agent problems, satisficing (Simon), revenue maximisation (Baumol — MR=0), sales maximisation (output max where AC=AR), market-share targets, social/ethical aims.', 15, 'alevel'),
  ('Economics', 'OCR', '1.3', 'Firm Objectives, Costs and Revenue', 'Distinguish horizontal, vertical and conglomerate integration.', 'Horizontal: same stage of same industry (Disney + Pixar). Vertical: different stages (PepsiCo + bottlers). Conglomerate: unrelated industries (Berkshire Hathaway).', 16, 'alevel');

-- Topic 1.4 — Market Structures
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '1.4', 'Market Structures', 'List the four assumptions of perfect competition.', 'Many small buyers and sellers (price takers); identical (homogeneous) products; perfect information; free entry and exit (no barriers).', 1, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Why does a perfectly competitive firm face a horizontal demand curve?', 'It is a price taker — its output is too small to influence market price. AR = MR = market price; charging more loses all customers.', 2, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'What happens to supernormal profits in perfect competition long run?', 'New firms are attracted by the profit, supply rises, market price falls until each firm earns only normal profit. Long-run equilibrium: P = AC = MC = MR.', 3, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Why is perfect competition both productively and allocatively efficient long run?', 'P = minimum AC (productive efficiency) and P = MC (allocative efficiency). Consumers get goods at the lowest possible cost equal to their valuation.', 4, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Define monopolistic competition with examples.', 'Many small firms with slightly differentiated products and low entry barriers — hairdressers, restaurants, plumbers. Each has a downward-sloping demand curve from product differentiation.', 5, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'List four characteristics of an oligopoly.', 'Few large firms dominate, high concentration ratio, interdependent decisions, significant entry barriers, products differentiated or homogeneous, non-price competition important.', 6, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'How is concentration measured?', 'n-firm concentration ratio (CR4 = combined market share of top four firms). High CR4 (>50%) indicates oligopoly. Herfindahl-Hirschman Index (HHI) sums squared market shares.', 7, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Explain the kinked demand curve.', 'In oligopoly, rivals match price cuts (so demand below the kink is inelastic) but ignore price rises (so demand above is elastic). MR has a vertical gap — explains observed price stability. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="35" x2="115" y2="75" stroke="#0B1E3F" stroke-width="1.5"/><line x1="115" y1="75" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="55" x2="115" y2="95" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><line x1="115" y1="115" x2="170" y2="125" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><line x1="115" y1="95" x2="115" y2="115" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><circle cx="115" cy="75" r="2.5" fill="#0B1E3F"/><text x="115" y="68" font-size="8" fill="#0B1E3F" text-anchor="middle">kink</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="170" y="135" font-size="9" fill="#0B1E3F">MR</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 8, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Distinguish collusive and non-collusive oligopoly.', 'Collusive: explicit (cartel — illegal in UK/EU) or tacit (price leadership). Non-collusive: independent rivalry, often through non-price competition or price wars.', 9, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Use a payoff matrix to explain the prisoner''s dilemma.', 'Two firms decide low/high price. Each has an individual incentive to undercut, even though both would profit more colluding at high prices. Cartels are unstable without enforcement.', 10, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'List three forms of non-price competition.', 'Advertising and branding, product differentiation/quality, after-sales service, loyalty schemes, packaging, location. Used to gain market share without triggering price wars.', 11, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Define a pure monopoly and a working monopoly.', 'Pure: a single firm is the only seller. Working/legal: a firm with at least 25% market share (UK Competition Act 1998). Both have significant market power.', 12, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'How does a profit-maximising monopoly set price and output?', 'Output where MC = MR; price read off the AR (demand) curve at that quantity. Result: higher P, lower Q than competition, supernormal profit sustained by entry barriers. <svg viewBox="0 0 240 160" width="240" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="225" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="40" y1="35" x2="195" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="35" x2="120" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><path d="M40 90 Q90 130 130 95 T200 60" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><path d="M40 110 Q100 130 140 105 T210 75" stroke="#0B1E3F" stroke-width="1" fill="none" stroke-dasharray="3 2"/><line x1="30" y1="60" x2="100" y2="60" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="30" y1="92" x2="100" y2="92" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="100" y1="60" x2="100" y2="135" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><rect x="30" y="60" width="70" height="32" fill="#0B1E3F" fill-opacity="0.12"/><text x="198" y="130" font-size="9" fill="#0B1E3F">D=AR</text><text x="123" y="135" font-size="9" fill="#0B1E3F">MR</text><text x="200" y="62" font-size="9" fill="#0B1E3F">MC</text><text x="210" y="78" font-size="9" fill="#0B1E3F">AC</text><text x="28" y="63" font-size="9" fill="#0B1E3F" text-anchor="end">Pm</text><text x="100" y="148" font-size="9" fill="#0B1E3F" text-anchor="middle">Qm</text><text x="60" y="80" font-size="8" fill="#0B1E3F">profit</text></svg>', 13, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Define a natural monopoly.', 'An industry where long-run AC keeps falling over the entire range of market demand — one firm can supply the market more cheaply than several. Examples: water, electricity grid, rail networks. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><path d="M40 35 C90 90 140 110 200 120" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="40" y1="40" x2="200" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="200" y="35" font-size="9" fill="#0B1E3F" text-anchor="end">LRAC</text><text x="200" y="138" font-size="9" fill="#0B1E3F" text-anchor="end">D</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">£</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 14, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'What three conditions are needed for price discrimination?', 'Market power (price-maker), ability to identify groups with different PEDs, ability to prevent resale (no arbitrage). Examples: peak/off-peak rail, student/adult cinema, airline.', 15, 'alevel'),
  ('Economics', 'OCR', '1.4', 'Market Structures', 'Define the contestable-markets theory (Baumol).', 'A market is contestable if entry and exit are costless. Under threat of hit-and-run entry, even monopolists set price near AC. Implication: structure matters less than entry conditions.', 16, 'alevel');

-- Topic 2.1 — The National and International Economy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'List the four main macroeconomic objectives.', 'Sustainable economic growth, low and stable inflation (~2% CPI), low unemployment (full employment), satisfactory balance of payments. Plus: balanced budget, fairer distribution, environmental sustainability.', 1, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Distinguish nominal and real GDP.', 'Nominal: output at current prices. Real: at constant base-year prices, removing inflation. Real GDP captures the actual change in output.', 2, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Why use GDP per capita and PPP?', 'Per capita corrects for population. PPP corrects for differences in cost of living. Both make cross-country welfare comparisons more meaningful (Big Mac index).', 3, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Give three limitations of GDP as a welfare measure.', 'Ignores income distribution; misses informal/black economy and household production; ignores environmental damage; says nothing about leisure, health or political freedom.', 4, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Outline how CPI is calculated.', 'A weighted average of prices for a representative basket of goods consumed by households, weights from the Living Costs and Food Survey. Bank of England target measure (2% CPI).', 5, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Distinguish demand-pull and cost-push inflation.', 'Demand-pull: AD rises faster than AS — ''too much money chasing too few goods''. Cost-push: rising costs (wages, oil, taxes, weak pound) shift SRAS leftward, raising P and lowering Y (stagflation possible).', 6, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'List four costs of inflation.', 'Erodes purchasing power; menu and shoe-leather costs; uncertainty deters investment; loss of competitiveness; redistribution from creditors to debtors; fiscal drag.', 7, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Distinguish four types of unemployment.', 'Cyclical (demand-deficient), frictional (between jobs), structural (mismatched skills/regions), seasonal. Plus real-wage and classical/voluntary.', 8, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Give three costs of unemployment.', 'Lost output (operating inside PPF), lower tax/higher benefit spend, hysteresis (skills atrophy), social costs (mental health, crime), inequality.', 9, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'How is unemployment measured (UK)?', 'Claimant count (those receiving JSA/Universal Credit) — narrow and quick. ILO/Labour Force Survey (anyone willing/able to work who hasn''t worked in the last week) — broader, internationally comparable.', 10, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'What does the balance of payments record?', 'All economic transactions between residents of the UK and the rest of the world over a period. Made up of current account, capital account and financial account; sum equals zero with errors and omissions.', 11, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'List the four parts of the current account.', 'Trade in goods, trade in services, primary income (wages/interest/profits/dividends from abroad), secondary income (transfers — remittances, EU/UN payments, foreign aid).', 12, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Define the activity (participation) rate.', 'The economically active population (employed + unemployed) as a percentage of the working-age population. Rises if more women, students or older people enter the labour force.', 13, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Distinguish actual and trend (potential) growth.', 'Actual growth = year-on-year change in real GDP. Trend growth = the long-run sustainable growth rate without rising inflation, set by the supply-side fundamentals.', 14, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'List the four phases of the business cycle.', 'Recovery, boom (peak), slowdown, recession (trough). A recession is two consecutive quarters of negative real GDP growth.', 15, 'alevel'),
  ('Economics', 'OCR', '2.1', 'The National and International Economy', 'Define the output gap.', 'The difference between actual and potential GDP. Negative output gap implies spare capacity (recession); positive gap implies overheating (inflationary pressure).', 16, 'alevel');

-- Topic 2.2 — AD/AS and Equilibrium
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Write the AD equation and label its components.', 'AD = C + I + G + (X − M). Consumption (~60%), investment (~15%), government spending (~20%), and net exports (residual). All measured at constant prices.', 1, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Why does AD slope downwards?', 'Real-balance effect (lower P raises real wealth and C), interest-rate effect (lower P -> lower r -> more I), international trade effect (lower P boosts X, deters M).', 2, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Name three determinants of consumption.', 'Disposable income, interest rates, wealth (housing/financial), confidence, expectations of inflation, availability of credit, taxes/benefits.', 3, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Distinguish gross and net investment.', 'Gross investment = total spending on new capital goods. Net = gross − depreciation. Net investment expands capital stock and productive potential.', 4, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'List three determinants of investment.', 'Expected returns/animal spirits, interest rates, business confidence, taxation/allowances, technology, retained profits, the accelerator effect.', 5, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'List four causes of an increase in AD.', 'Cuts in income tax, lower interest rates, weaker pound, rising house prices, rising consumer/business confidence, higher G, faster world growth.', 6, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Distinguish SRAS and LRAS.', 'SRAS: upward-sloping; in the short run, sticky wages mean higher P raises profit margins and output. LRAS: vertical at full-employment Yfe (classical) or with horizontal/upward/vertical sections (Keynesian).', 7, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'List three factors that shift LRAS.', 'Quantity/quality of labour (immigration, education), capital stock and investment, technology and productivity, enterprise/incentives, government supply-side policy (deregulation, infrastructure).', 8, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Compare classical and Keynesian LRAS curves.', 'Classical: vertical at Yfe — output cannot exceed potential, so AD changes only affect P. Keynesian: horizontal at low output, upward-sloping with spare capacity, vertical near Yfe — AD matters at low output. <svg viewBox="0 0 460 160" width="460" height="160" style="display:block;margin:6px auto"><g><line x1="30" y1="135" x2="200" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="140" y1="135" x2="140" y2="25" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="30" x2="180" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="200" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="143" y="20" font-size="9" fill="#0B1E3F">LRAS</text><text x="183" y="125" font-size="9" fill="#0B1E3F">AD</text><text x="115" y="155" font-size="9" fill="#0B1E3F" text-anchor="middle">Classical</text></g><g><line x1="260" y1="135" x2="440" y2="135" stroke="#0B1E3F"/><line x1="260" y1="135" x2="260" y2="20" stroke="#0B1E3F"/><path d="M260 110 L320 110 Q360 100 380 60 L380 25" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="270" y1="35" x2="420" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="440" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text><text x="258" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="383" y="22" font-size="9" fill="#0B1E3F">LRAS</text><text x="423" y="125" font-size="9" fill="#0B1E3F">AD</text><text x="350" y="155" font-size="9" fill="#0B1E3F" text-anchor="middle">Keynesian</text></g></svg>', 9, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'Define the multiplier and give a formula.', 'Ratio of final ΔY to initial Δ injection. k = 1/(1 − MPC) = 1/MPS in a closed economy with no government; in an open economy k = 1/(MPS + MPT + MPM).', 10, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'List injections and withdrawals from the circular flow.', 'Injections: investment (I), government spending (G), exports (X). Withdrawals: saving (S), taxation (T), imports (M). Equilibrium: I + G + X = S + T + M.', 11, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'What is the accelerator effect?', 'The relationship by which a change in the rate of growth of output causes a much larger proportional change in investment, since firms only invest when expected demand growth justifies new capacity.', 12, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'How does an outward shift of AD affect P and Y on a Keynesian AS curve?', 'On the horizontal section: Y rises with P unchanged. On the upward-sloping section: P and Y both rise. On the vertical section: P rises with Y unchanged (pure inflation).', 13, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'List three benefits of economic growth.', 'Higher living standards, higher tax revenue, lower unemployment, easier to redistribute, more government spending on public services, fiscal dividend.', 14, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'List three costs of rapid economic growth.', 'Demand-pull inflation, current-account deficit (rising imports), environmental damage, widening inequality, resource depletion, work-life imbalance.', 15, 'alevel'),
  ('Economics', 'OCR', '2.2', 'AD, AS and Equilibrium', 'What is hysteresis in the labour market?', 'The persistence of unemployment after the original shock has passed, because the long-term unemployed lose skills, motivation and employability — raising the natural rate.', 16, 'alevel');

-- Topic 2.3 — Economic Policy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Define monetary policy and the MPC.', 'The use of interest rates and the money supply by the central bank to influence AD and meet the inflation target. UK: BoE Monetary Policy Committee (9 members), 2% CPI target.', 1, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Through which four channels does Bank Rate affect inflation?', 'Market interest rates (mortgages, savings), asset prices (housing, shares), confidence/expectations, exchange rate. Each affects AD with lags of 12-24 months.', 2, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'What is quantitative easing (QE)?', 'A central bank creates new electronic money to buy government bonds (and other assets), pushing up bond prices, lowering long-term yields, raising asset prices and bank reserves to stimulate AD.', 3, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Give two limitations of monetary policy.', 'Liquidity trap (rates near zero cannot fall further); time lags; uncertain transmission via banks; if banks won''t lend or households deleverage, low rates have little effect; widens inequality.', 4, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Define fiscal policy.', 'The use of government spending (G) and taxation (T) to influence AD, redistribute income and provide public goods. Set in the Budget by HM Treasury.', 5, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Distinguish direct and indirect taxes.', 'Direct: levied on income/wealth (income tax, NI, corporation tax). Indirect: levied on spending (VAT, excise duties, fuel duty); incidence can shift between buyer and seller.', 6, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Distinguish progressive, proportional and regressive taxes.', 'Progressive: average tax rate rises with income (UK income tax). Proportional: same percentage at every income (flat tax). Regressive: average rate falls (VAT, council tax).', 7, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'List the four canons of taxation (Adam Smith).', 'Equity (ability to pay), certainty (clear amount/timing), convenience (easy to pay), economy (low collection cost). Modern additions: efficiency, flexibility, transparency.', 8, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'What is the difference between budget deficit and national debt?', 'Deficit: gap between G and T in a single year (a flow). National debt: cumulative total of past borrowing (a stock). Each year''s deficit adds to the debt.', 9, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Distinguish cyclical and structural budget deficits.', 'Cyclical: arises automatically when output is below trend (lower tax, higher benefits). Structural: persists at full employment, signalling fiscal policy is unsustainable.', 10, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Define automatic stabilisers.', 'Built-in features of the tax/benefit system that smooth the cycle without explicit policy change: tax revenue falls and benefits rise in a recession; both reverse in a boom.', 11, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'What is crowding out?', 'When higher government borrowing pushes up interest rates and absorbs available savings, reducing private investment and consumption. Most relevant near full employment.', 12, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Define supply-side policies.', 'Policies designed to raise the productive capacity (LRAS) and improve long-run growth by improving the quantity or quality of factors of production and the efficiency of markets.', 13, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Distinguish market-based and interventionist supply-side policies.', 'Market-based: free up markets — cut income/corporation tax, deregulation, privatisation, weaker trade unions. Interventionist: government action — infrastructure, education, R&D subsidies, training.', 14, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'What is the Laffer curve?', 'A graph showing tax revenue against tax rate. Revenue rises then falls as the rate rises beyond an optimum, because high rates discourage work, encourage avoidance and shrink the tax base.', 15, 'alevel'),
  ('Economics', 'OCR', '2.3', 'Economic Policy', 'Why might monetary and fiscal policy need to be coordinated?', 'They influence AD jointly. Loose fiscal with tight monetary (or vice versa) creates conflicting signals, raising long-term rates and worsening the policy mix; coordination improves outcomes.', 16, 'alevel');

-- Topic 2.4 — International Economics and Development
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'State Ricardo''s law of comparative advantage.', 'Countries should specialise in goods they produce at the lowest opportunity cost and trade for the rest. Total world output rises even if one country is absolutely better at all goods.', 1, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Distinguish absolute and comparative advantage.', 'Absolute: producing more output per unit of input. Comparative: lower opportunity cost. Specialisation by comparative advantage maximises total world output.', 2, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Give two limitations of comparative advantage.', 'Assumes no transport costs, full employment, perfect mobility, constant returns. Ignores externalities, infant industries and the welfare cost of structural change.', 3, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'List four protectionist tools.', 'Tariffs, quotas, subsidies to domestic firms, non-tariff barriers (regulation, technical standards), exchange-rate intervention, embargoes, voluntary export restraints.', 4, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Show the welfare effect of a tariff diagrammatically.', 'On supply/demand: domestic price rises by tariff. Producer surplus rises; consumer surplus falls more; government gets tariff revenue; deadweight loss appears as two triangles (production + consumption). <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="245" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="40" y1="30" x2="220" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="130" x2="220" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="100" x2="245" y2="100" stroke="#0B1E3F" stroke-width="1"/><line x1="30" y1="78" x2="245" y2="78" stroke="#0B1E3F" stroke-width="1"/><polygon points="80,100 100,78 100,100" fill="#B00020" fill-opacity="0.35"/><polygon points="180,100 160,78 180,78" fill="#B00020" fill-opacity="0.35"/><rect x="100" y="78" width="60" height="22" fill="#0B1E3F" fill-opacity="0.18"/><text x="225" y="125" font-size="9" fill="#0B1E3F">D</text><text x="225" y="35" font-size="9" fill="#0B1E3F">S</text><text x="248" y="103" font-size="9" fill="#0B1E3F">Pw</text><text x="248" y="80" font-size="9" fill="#0B1E3F">Pw+t</text><text x="125" y="93" font-size="8" fill="#0B1E3F" text-anchor="middle">tariff revenue</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="245" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 5, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Outline the four stages of economic integration.', 'Free trade area (no tariffs), customs union (common external tariff), single/common market (free factor movement), economic and monetary union (common currency). EU progressed through all four.', 6, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'What is the WTO''s main role?', 'Promotes liberal world trade by negotiating multilateral agreements, enforcing the Most-Favoured-Nation principle and arbitrating disputes between members. Successor to GATT (1995).', 7, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Distinguish floating and fixed exchange-rate regimes.', 'Floating: market sets the rate (USD, GBP). Fixed: government pegs to another currency, defended via intervention or capital controls (HK dollar, Bretton Woods era).', 8, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Effects of a depreciation on the macroeconomy?', 'Exports cheaper, imports dearer: improves current account (Marshall-Lerner), raises AD, but raises imported inflation. Helps domestic producers; hurts consumers/exporters dependent on imports.', 9, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'State the Marshall-Lerner condition and the J-curve.', 'A depreciation improves the current account only if |PEDx| + |PEDm| > 1. Short-run elasticities are low — the J-curve — so the deficit may worsen before improving. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="80" x2="205" y2="80" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><path d="M30 80 Q70 130 110 95 T200 25" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="50" y1="78" x2="50" y2="82" stroke="#0B1E3F"/><text x="50" y="95" font-size="8" fill="#0B1E3F" text-anchor="middle">depreciation</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">CA balance</text><text x="205" y="78" font-size="9" fill="#0B1E3F" text-anchor="end">time</text></svg>', 10, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Distinguish economic growth and economic development.', 'Growth: rise in real GDP. Development: broader improvement in welfare — health, education, gender equality, freedom (Sen). HDI captures more than GDP.', 11, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'List the three components of HDI.', 'Life expectancy at birth (health), mean and expected years of schooling (education), GNI per capita PPP (income). Combined into a 0-1 index.', 12, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'List three barriers to development.', 'Primary product dependence, low savings/investment, capital flight, brain drain, corruption, civil war, debt overhang, demographic pressure, climate vulnerability.', 13, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Distinguish bilateral and multilateral aid.', 'Bilateral: country-to-country (UK FCDO). Multilateral: through institutions (World Bank, IMF, UN). Tied aid imposes conditions; untied does not.', 14, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Distinguish IMF and World Bank.', 'IMF: short-term BoP support, monetary stability, structural adjustment. World Bank: long-term project lending and poverty reduction (IBRD, IDA). Both Bretton Woods 1944, Washington DC.', 15, 'alevel'),
  ('Economics', 'OCR', '2.4', 'International Economics and Development', 'Distinguish absolute and relative poverty.', 'Absolute: income too low for basic essentials (World Bank: $2.15/day, 2017 PPP). Relative: income below a threshold (UK: 60% of median income). Relative measures inequality more than survival.', 16, 'alevel');
