-- A-Level Economics Flashcards (Edexcel B)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.

-- ===============================================================
-- EDEXCEL B A-LEVEL
-- ===============================================================

-- Topic 1.1 — How Markets Work and Surplus
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'What is the central economic problem?', 'Scarcity: human wants are unlimited but resources are finite, so choices must be made about what, how and for whom to produce. All choices have an opportunity cost.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'List the four factors of production and their rewards.', 'Land (rent), labour (wages), capital (interest), enterprise (profit). Enterprise organises the others and bears risk.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'What does a PPF show and a point inside it indicate?', 'Maximum combinations of two goods producible with all resources fully and efficiently employed. A point inside the PPF indicates productive inefficiency or unemployed resources.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'State the law of demand.', 'Ceteris paribus, as price falls quantity demanded rises. Downward-sloping due to substitution effect, income effect and diminishing marginal utility.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Distinguish movement along and shift of demand.', 'Movement caused by a change in the good''s own price. A shift caused by a change in any other determinant: income, related-good prices, tastes, expectations, population.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define PED and give three determinants.', 'PED = % ΔQd / % ΔP. Determinants: substitutes (more = elastic), share of income, necessity vs luxury, time period (longer = more elastic), addiction.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'How does PED affect total revenue?', 'If demand is elastic, a price cut raises revenue. If inelastic, a price rise raises revenue. Maximum revenue at unitary elasticity.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define YED and interpret three values.', 'YED = % ΔQd / % Δincome. >1: luxury. 0<YED<1: necessity. Negative: inferior good. Helps firms forecast and plan.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define XED and interpret its sign.', 'XED = % ΔQd of A / % ΔP of B. Positive: substitutes. Negative: complements. Magnitude shows closeness of relationship.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'State the law of supply and three shift factors.', 'Ceteris paribus, higher price -> higher Qs. Shifters: costs of production, technology, taxes/subsidies, number of firms, expectations, weather/agriculture.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define PES and three determinants.', 'PES = % ΔQs / % ΔP. Determinants: spare capacity, ease of stockholding, factor mobility, time period (longer is more elastic).', 11, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'How is market equilibrium determined?', 'At the price where Qd = Qs. Surplus -> price falls. Shortage -> price rises. The price mechanism rations, signals and incentivises.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define consumer surplus and producer surplus.', 'Consumer surplus: amount willing to pay above actual price. Producer surplus: amount received above minimum acceptable price. Both contribute to welfare.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Explain rational economic decision-making.', 'Consumers maximise utility, firms maximise profit, governments maximise welfare. Behavioural economics challenges this with bounded rationality, anchoring, herding and loss aversion.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define specialisation and division of labour with one advantage and one disadvantage.', 'Specialisation: focus on tasks/goods one is best at. Division of labour: tasks split between workers (Smith''s pin factory). Advantage: higher productivity. Disadvantage: monotony lowers morale.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'List four functions of money.', 'Medium of exchange (replaces barter), store of value (preserves purchasing power), unit of account (common measure of value), standard of deferred payment (debt contracts).', 16, 'alevel');

-- Topic 1.2 — Market Failure and Government Intervention
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Define market failure.', 'When the free market fails to allocate resources efficiently, leading to a welfare loss. Forms: externalities, public goods, information failure, monopoly power, inequality.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Distinguish private, external and social cost.', 'Private cost: borne by producer/consumer. External cost: spillover on third parties (pollution). Social cost = private + external. Markets ignore externals -> overproduction.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Show a negative production externality on a diagram.', 'MSC lies above MPC. Free-market output where MPB = MPC exceeds the social optimum where MSB = MSC. The triangle between is the deadweight welfare loss.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Distinguish merit and demerit goods.', 'Merit goods are undervalued and underconsumed (education, healthcare, vaccines). Demerit goods are overvalued and overconsumed (cigarettes, alcohol). Tied to information failure and externalities.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'State the two characteristics of a public good.', 'Non-rival (one person''s use does not reduce another''s) and non-excludable (cannot prevent non-payers). Examples: street lighting, lighthouses, defence.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'What is the free-rider problem?', 'Because public goods are non-excludable, individuals can consume without paying. Profit-maximising firms cannot recoup costs, so the market under-provides — justifying state provision.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'How does asymmetric information cause market failure?', 'When one party knows more than another. Examples: used cars (Akerlof''s lemons), insurance (moral hazard, adverse selection), pensions (consumer ignorance).', 7, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Evaluate using an indirect (Pigouvian) tax.', 'Strengths: internalises external cost, raises revenue, signals harm. Weaknesses: hard to set at exact MEC, regressive, may shift activity to black markets, inelastic demand limits effect.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Evaluate using a subsidy on a positive externality.', 'Strengths: lowers price, raises output to social optimum, encourages innovation. Weaknesses: opportunity cost, dependency, hard to set at MEB, may favour wealthy producers.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'How does cap-and-trade (tradeable permits) work?', 'Government caps total emissions; firms hold permits they may trade. Polluters cutting emissions cheaply sell permits to those who can''t. Sets a market price on carbon — EU ETS.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'When is a maximum price effective?', 'Set below equilibrium with elastic demand. Side effects: shortages, queueing, black markets, poor quality. UK rent controls in the 1970s reduced housing supply.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'When is a minimum price effective?', 'Set above equilibrium with surplus bought up by government — EU CAP, UK national living wage. Aim: support producer incomes or floor wages.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Distinguish state provision and direct regulation.', 'State provision: public sector funds and supplies the good (NHS). Regulation: rules constrain private behaviour (smoking ban, vehicle emissions standards).', 13, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Why is a behavioural ''nudge'' often used instead of bans?', 'It exploits cognitive biases at low cost (default opt-in pension enrolment, organ donation) while preserving choice — libertarian paternalism (Thaler & Sunstein).', 14, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Define government failure.', 'Where intervention to correct market failure leads to a worse allocation. Causes: imperfect information, unintended consequences, regulatory capture, admin costs, political short-termism.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Why is competition policy needed?', 'To prevent abuse of monopoly power — anti-competitive mergers, predatory pricing, cartels — and protect consumers. Enforced by the CMA in the UK.', 16, 'alevel');

-- Topic 2.1 — National Economic Performance
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List the four main macroeconomic objectives.', 'Sustainable growth, low and stable inflation (~2% CPI), low unemployment (full employment), satisfactory current account. Plus: balanced budget, fairer distribution, environmental sustainability.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Distinguish nominal and real GDP.', 'Nominal: output at current prices. Real: at constant base-year prices, removing inflation. Real GDP captures actual output change.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Why use GDP per capita and PPP?', 'Per capita corrects for population. PPP corrects for differences in cost of living. Both make cross-country welfare comparisons more meaningful.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Give three limitations of GDP as a welfare measure.', 'Ignores distribution; misses informal/black economy and household production; ignores environmental damage; says nothing about leisure, health, freedom.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Outline how CPI is calculated.', 'Weighted average price of a representative basket from the Living Costs and Food Survey. Updated annually. Geometric mean used. Bank of England target measure.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List three limitations of CPI.', 'Quality changes hard to capture; basket lags behind taste shifts; excludes some housing costs; reflects average household, not individual budgets.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Distinguish demand-pull and cost-push inflation.', 'Demand-pull: AD rises faster than AS, pulling up prices. Cost-push: rising costs (wages, oil, weak pound) shift SRAS leftward, pushing prices up while output falls — stagflation possible.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List four costs of inflation.', 'Erodes purchasing power; menu and shoe-leather costs; uncertainty deters investment; loss of competitiveness; redistribution from creditors to debtors; fiscal drag.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Why is deflation a problem?', 'Consumers delay purchases; debt burden rises (Fisher debt-deflation); banks face credit losses; central bank loses traction at the zero lower bound. Hard to escape (Japan 1990s).', 9, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Distinguish four types of unemployment.', 'Cyclical (demand-deficient), frictional (between jobs), structural (mismatched skills/regions), seasonal. Plus real-wage and classical/voluntary.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Give three costs of unemployment.', 'Lost output (inside PPF), lower tax/higher benefit spend, hysteresis (skills atrophy), social costs (mental health, crime), inequality.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'How is unemployment measured (UK)?', 'Claimant count (those receiving JSA/Universal Credit) — narrow and quick. ILO/Labour Force Survey (anyone willing/able and not employed last week) — internationally comparable.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List the four parts of the current account.', 'Trade in goods, trade in services, primary income (interest, profits, dividends), secondary income (transfers — remittances, EU/UN payments, aid).', 13, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List two causes of a current-account deficit.', 'Strong domestic demand (sucks in imports), overvalued exchange rate, low productivity/competitiveness, deindustrialisation, slow trading-partner growth, high domestic inflation.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List four phases of the business cycle.', 'Recovery, boom (peak), slowdown, recession (trough). A recession is technically two consecutive quarters of negative real GDP growth.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Define the output gap.', 'The difference between actual and potential GDP. A negative output gap implies spare capacity (recession); a positive gap implies overheating (inflationary pressure).', 16, 'alevel');

-- Topic 2.2 — Macroeconomic Policy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Write the AD equation.', 'AD = C + I + G + (X − M). Consumption (~60%), investment (~15%), government spending (~20%), and net exports.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Why does AD slope downwards?', 'Real-balance effect (lower P raises real wealth and C); interest-rate effect (lower P -> lower r -> more I); international trade effect (lower P boosts X).', 2, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Distinguish SRAS and LRAS.', 'SRAS: upward sloping; sticky wages let higher P raise output. LRAS: vertical at full employment (classical) or with horizontal/upward/vertical sections (Keynesian).', 3, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'List four determinants of LRAS.', 'Quantity/quality of labour, capital stock, technology and innovation, education and skills, infrastructure, openness to trade.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define the multiplier and give its formula.', 'k = ΔY / Δinjection. Closed economy with no government: k = 1/(1−MPC) = 1/MPS. Open economy with taxes: k = 1/(MPS+MPT+MPM).', 5, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'List injections and withdrawals from the circular flow.', 'Injections: investment (I), government spending (G), exports (X). Withdrawals: saving (S), taxation (T), imports (M). Equilibrium: I + G + X = S + T + M.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define monetary policy and the MPC.', 'Use of interest rates and money supply by the central bank to influence AD and meet the inflation target. UK: BoE Monetary Policy Committee (9 members) targeting 2% CPI.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Through which four channels does Bank Rate affect inflation?', 'Market interest rates (mortgages, savings), asset prices (housing, shares), confidence/expectations, exchange rate. Each affects AD with lags of 12-24 months.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'What is quantitative easing?', 'Central bank creates new electronic money to buy government bonds (and other assets), lowering long-term yields, raising bank reserves and asset prices, stimulating AD when Bank Rate is near zero.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define fiscal policy.', 'Use of government spending (G) and taxation (T) to influence AD and the supply side. Set in the Budget by HM Treasury; subject to fiscal rules and OBR forecasts.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Distinguish progressive, proportional and regressive taxes.', 'Progressive: average rate rises with income (UK income tax). Proportional: same percentage at all incomes. Regressive: average rate falls (VAT, council tax).', 11, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'What is the difference between budget deficit and national debt?', 'Deficit is the annual gap between G and T (a flow). National debt is the cumulative total of past borrowing (a stock). Each year''s deficit adds to the debt.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define automatic stabilisers.', 'Built-in tax/benefit responses that smooth the cycle without explicit policy: tax revenues fall and benefits rise in recession; reverse in boom.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Distinguish demand-side and supply-side policies.', 'Demand-side: monetary and fiscal — manage AD over the cycle. Supply-side: raise LRAS over the long run via market reform, education, R&D, infrastructure.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Give three examples of supply-side policies.', 'Income/corporation tax cuts, deregulation, privatisation, education and training, R&D subsidies, infrastructure investment, weakening of trade unions, immigration.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Why must monetary and fiscal policy be coordinated?', 'They both affect AD. A loose fiscal stance with tight monetary policy creates conflict, raising long-term rates. Coordination — ''policy mix'' — improves outcomes.', 16, 'alevel');

-- Topic 3.1 — Business Economics
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Why do firms grow?', 'To exploit economies of scale, gain market power, diversify risk, increase profits, and meet managerial objectives. Constraints: regulation, finance, organisational complexity.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Distinguish organic and inorganic growth.', 'Organic: internal expansion through more sales or new markets. Inorganic: mergers and acquisitions. Inorganic is faster but riskier, with cultural/regulatory hurdles.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Distinguish horizontal, vertical and conglomerate integration.', 'Horizontal: same stage of same industry. Vertical: different stages of the same industry. Conglomerate: unrelated industries (Berkshire Hathaway).', 3, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Why do some firms remain small?', 'Niche markets, owner''s preference for control, low minimum efficient scale, personal service, finance constraints, government support of SMEs.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'List four business objectives beyond profit max.', 'Revenue maximisation (Baumol — MR=0), sales maximisation (output max where AC=AR), satisficing (Simon), market share, social/ethical, survival.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Distinguish fixed, variable and total costs.', 'Fixed: do not change with output (rent, insurance). Variable: change with output (wages, raw materials). TC = FC + VC. MC = ΔTC/ΔQ.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'State the law of diminishing marginal returns.', 'In the short run, adding more variable input to a fixed input eventually causes the marginal product of the variable input to fall, raising MC.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'List four internal economies of scale.', 'Technical, purchasing (bulk discounts), managerial, financial (cheaper borrowing), marketing, risk-bearing. They lower long-run AC as output grows.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Define minimum efficient scale (MES).', 'The smallest output at which a firm''s long-run AC reaches its minimum. Industries with high MES tend to have few large firms and significant entry barriers.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Define total, average and marginal revenue.', 'TR = P × Q. AR = TR/Q = price (the demand curve). MR = ΔTR/ΔQ. For a price-taker AR = MR; for a price-maker MR < AR and slopes more steeply.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'State the profit-maximisation rule.', 'Produce the output where MC = MR with MC rising. At this output the gap between TR and TC is largest.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Distinguish normal and supernormal profit.', 'Normal: minimum return needed to keep resources in current use; counted as a cost. Supernormal: profit above normal — attracts entry in competitive markets.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'State the short-run shut-down rule.', 'A firm continues operating in the short run as long as P >= AVC (covers variable costs). If P < AVC, shut down to limit losses to fixed costs.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Distinguish productive and allocative efficiency.', 'Productive: producing at minimum AC (no resource waste). Allocative: producing the goods consumers value most, where P = MC, maximising welfare.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Explain X-inefficiency.', 'A failure to minimise costs because firms lack competitive pressure — managerial slack, generous perks, bloated workforces. Common in monopolies and state monopolies.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Business Economics', 'Explain the principal-agent problem.', 'Owners (principals) and managers (agents) have different objectives and information. Managers may pursue empire-building or perks at the expense of profit unless monitored or incentivised.', 16, 'alevel');

-- Topic 3.2 — Market Structures and Competition
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'List the four assumptions of perfect competition.', 'Many small buyers and sellers (price takers); homogeneous products; perfect information; free entry and exit (no barriers).', 1, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Why does a perfectly competitive firm face a horizontal demand curve?', 'It is a price taker — output too small to influence market price. AR = MR = market price; charging more loses all customers.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'What happens to supernormal profits in perfect competition long run?', 'New firms enter, supply rises, market price falls until each firm earns only normal profit. Long-run equilibrium: P = AC = MC = MR.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Why is perfect competition both productively and allocatively efficient long run?', 'P = minimum AC (productive) and P = MC (allocative). Consumers get goods at lowest possible cost, and society values them at exactly their marginal cost.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Define monopolistic competition with examples.', 'Many small firms with slightly differentiated products and low entry barriers — hairdressers, restaurants, plumbers. Each has a downward-sloping demand curve; long-run supernormal profit competes away.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'List four characteristics of an oligopoly.', 'Few large firms, high concentration, interdependent decisions, significant entry barriers, products differentiated or homogeneous, non-price competition important.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'How is concentration measured?', 'n-firm concentration ratio (CR4 = combined share of top four firms). High CR4 (>50%) indicates oligopoly. Herfindahl-Hirschman Index (HHI) sums the squared shares.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Explain the kinked demand curve.', 'In oligopoly, rivals match price cuts (inelastic below the kink) but ignore price rises (elastic above). MR has a vertical gap — explains observed price stability.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Use a payoff matrix to explain the prisoner''s dilemma.', 'Two firms decide low/high price. Each has a unilateral incentive to undercut, even though both would profit more colluding at high prices. Cartels are unstable.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'List three forms of non-price competition.', 'Advertising/branding, product differentiation/quality, after-sales service, loyalty schemes, packaging, location. Used to gain market share without triggering price wars.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Define a pure monopoly and a working monopoly.', 'Pure: single seller. Working/legal: a firm with at least 25% market share under the UK Competition Act 1998. Both have significant market power.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'How does a profit-maximising monopoly set price and output?', 'Output where MC = MR; price read off the demand (AR) curve at that quantity. Result: higher P, lower Q than competition, supernormal profit sustained by barriers.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'List three barriers to entry.', 'Economies of scale (high MES), high sunk costs, brand loyalty, predatory pricing, control of essential inputs, patents/copyrights, network effects, government licences.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Give two costs and two benefits of monopoly.', 'Costs: higher prices, lower output, allocative inefficiency, X-inefficiency. Benefits: economies of scale, supernormal profits fund R&D and dynamic efficiency, may be a natural monopoly.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Outline three conditions needed for price discrimination.', 'Market power (price-maker), ability to identify groups with different PEDs, ability to prevent resale (no arbitrage). Examples: rail peak/off-peak, cinema, airline.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Market Structures and Competition', 'Define the contestable-markets theory (Baumol).', 'A market is contestable if entry and exit are costless. Even monopolists set price near AC under threat of hit-and-run entry. Implication: structure matters less than entry conditions.', 16, 'alevel');

-- Topic 4.1 — International Economics and Globalisation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Define globalisation.', 'The growing integration of national economies through international trade, capital flows, migration, technology transfer and cultural exchange. Driven by transport costs, ICT and trade liberalisation.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'List three causes of globalisation.', 'Falling transport/communication costs, trade liberalisation (WTO), ICT advances, deregulation of capital markets, end of the Cold War, growth of multinationals, rising consumer incomes.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'State Ricardo''s law of comparative advantage.', 'Countries should specialise in goods they produce at the lowest opportunity cost and trade for the rest. Total world output rises even if one country is absolutely better at all goods.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Distinguish absolute and comparative advantage.', 'Absolute: producing more output per unit of input. Comparative: lower opportunity cost. Specialisation by comparative advantage maximises total output.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Give three benefits of trade.', 'Greater consumer choice, lower prices through competition and economies of scale, access to inputs/technology, faster growth, transfer of best practice.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'List four protectionist tools.', 'Tariffs, quotas, subsidies to domestic firms, non-tariff barriers (standards, regulation), exchange-rate intervention, embargoes, voluntary export restraints.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Show the welfare effect of a tariff diagrammatically.', 'On supply/demand: domestic price rises by the tariff. Producer surplus rises; consumer surplus falls more; government gains tariff revenue; deadweight loss = production + consumption triangles.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Give three arguments for protectionism.', 'Infant industry, sunset industry, defence, anti-dumping, addressing externalities, BoP stabilisation, retaliation, jobs in vulnerable regions.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Outline the four stages of economic integration.', 'Free trade area (no tariffs), customs union (common external tariff), single/common market (free factor movement), economic and monetary union (common currency). EU progressed through all four.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'What is the WTO''s main role?', 'Promotes liberal world trade by negotiating multilateral agreements, enforcing the Most-Favoured-Nation principle and arbitrating disputes. Successor to GATT (1995).', 10, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Distinguish floating and fixed exchange-rate regimes.', 'Floating: market sets the rate (USD, GBP). Fixed: government pegs to another currency, defended via intervention or capital controls (HK dollar, Bretton Woods era).', 11, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Effects of a depreciation on the macroeconomy?', 'Exports cheaper, imports dearer: improves current account (Marshall-Lerner), raises AD, but raises imported inflation. Helps domestic producers; hurts consumers/exporters dependent on imports.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'State the Marshall-Lerner condition.', 'A depreciation improves the current account only if |PEDx| + |PEDm| > 1. Short-run elasticities are low — the J-curve — so deficit may worsen before improving.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Define international competitiveness.', 'A country''s ability to sell its goods/services abroad relative to others. Measured by unit labour costs, real exchange rate, productivity. Weakens if domestic costs rise faster than rivals''.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'What is foreign direct investment (FDI)?', 'Investment by a firm in productive assets in another country (factories, subsidiaries). Brings capital, jobs, technology and know-how but can crowd out domestic firms or repatriate profits.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'International Economics and Globalisation', 'Give two benefits and two costs of MNCs to host countries.', 'Benefits: jobs, investment, tax revenue, technology transfer. Costs: profit repatriation, tax avoidance, exploitation of weak labour/environmental standards, loss of cultural identity.', 16, 'alevel');

-- Topic 4.2 — Development and Inequality
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Distinguish economic growth and economic development.', 'Growth: rise in real GDP. Development: broader improvement in welfare — health, education, gender equality, freedom (Sen). HDI captures more than GDP.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'List the three components of HDI.', 'Life expectancy at birth (health), mean and expected years of schooling (education), GNI per capita PPP (income). Combined into a 0-1 index.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Distinguish absolute and relative poverty.', 'Absolute: income too low for basic needs (World Bank: $2.15/day, 2017 PPP). Relative: income below societal benchmark (UK: 60% of median income). Relative measures inequality more than survival.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'How does the Lorenz curve work?', 'Plots cumulative % of population (x) against cumulative % of income (y). Perfect equality is the 45° diagonal; the further the curve bows below, the more unequal the distribution.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Define the Gini coefficient.', 'A summary inequality measure derived from the Lorenz curve: 0 = perfect equality, 1 = perfect inequality. UK around 0.35; Nordic countries below 0.30.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'List four causes of inequality.', 'Skills/education differences, inheritance, discrimination, capital ownership, regressive tax/benefit changes, technology favouring high skills, globalisation.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'List three barriers to development.', 'Primary product dependence, low savings/investment, capital flight, brain drain, corruption, civil war, debt overhang, demographic pressure, climate vulnerability.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Outline the Harrod-Domar model.', 'Growth depends on the savings rate divided by the capital-output ratio. Developing countries save little, so domestic investment is too low — case for foreign aid or FDI.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Define the Lewis dual-sector model.', 'A developing economy has a low-productivity rural/subsistence sector and a higher-productivity modern sector. Growth comes from transferring surplus labour to the modern sector — drives urbanisation.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'What is the Prebisch-Singer hypothesis?', 'Terms of trade for primary products tend to deteriorate over time relative to manufactures, hurting commodity-dependent developing countries.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Distinguish bilateral and multilateral aid.', 'Bilateral: country-to-country (UK FCDO). Multilateral: through institutions (World Bank, IMF, UN). Tied aid imposes conditions; untied does not.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Give two arguments for and against foreign aid.', 'For: relieves poverty, builds capacity, addresses crises. Against: dependency, corruption, distorts incentives, ''Dutch disease'', conditionality may impose poor policy.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Outline microfinance.', 'Small loans to low-income borrowers without collateral, often via group lending (Grameen Bank). Aims to fund small business; criticised for high interest, debt traps and limited macro impact.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Define fair trade.', 'A movement guaranteeing producers a minimum price plus a social premium, especially for primary commodities (coffee, cocoa). Trade-off: protected producers may overproduce, lowering market price.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Distinguish IMF and World Bank.', 'IMF: short-term BoP support, monetary stability, structural adjustment. World Bank: long-term project lending and poverty reduction (IBRD, IDA). Both Bretton Woods 1944.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Development and Inequality', 'Define the trickle-down hypothesis.', 'The claim that policies enriching top earners (tax cuts, deregulation) eventually filter down through investment and jobs. Empirical evidence is contested and depends on policy mix.', 16, 'alevel');
