-- A-Level Economics Flashcards (Edexcel B)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.

-- ===============================================================
-- EDEXCEL B A-LEVEL
-- ===============================================================

-- Topic 1.1 — How Markets Work and Surplus
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'What is the central economic problem?', 'Scarcity: human wants are unlimited but resources are finite, so choices must be made about what, how and for whom to produce. All choices have an opportunity cost.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'List the four factors of production and their rewards.', 'Land (rent), labour (wages), capital (interest), enterprise (profit). Enterprise organises the others and bears risk.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'What does a PPF show and a point inside it indicate?', 'Maximum combinations of two goods producible with all resources fully and efficiently employed. A point inside the PPF indicates productive inefficiency or unemployed resources. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><path d="M30 25 Q70 32 130 75 T200 130" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><circle cx="80" cy="105" r="3" fill="#B00020"/><text x="86" y="108" font-size="8" fill="#B00020">A (inside)</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Good X</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">Good Y</text><text x="135" y="105" font-size="9" fill="#0B1E3F">PPF</text></svg>', 3, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'State the law of demand.', 'Ceteris paribus, as price falls quantity demanded rises. Downward-sloping due to substitution effect, income effect and diminishing marginal utility.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Distinguish movement along and shift of demand.', 'Movement caused by a change in the good''s own price. A shift caused by a change in any other determinant: income, related-good prices, tastes, expectations, population.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define PED and give three determinants.', 'PED = % ΔQd / % ΔP. Determinants: substitutes (more = elastic), share of income, necessity vs luxury, time period (longer = more elastic), addiction.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'How does PED affect total revenue?', 'If demand is elastic, a price cut raises revenue. If inelastic, a price rise raises revenue. Maximum revenue at unitary elasticity.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define YED and interpret three values.', 'YED = % ΔQd / % Δincome. >1: luxury. 0<YED<1: necessity. Negative: inferior good. Helps firms forecast and plan.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define XED and interpret its sign.', 'XED = % ΔQd of A / % ΔP of B. Positive: substitutes. Negative: complements. Magnitude shows closeness of relationship.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'State the law of supply and three shift factors.', 'Ceteris paribus, higher price -> higher Qs. Shifters: costs of production, technology, taxes/subsidies, number of firms, expectations, weather/agriculture.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define PES and three determinants.', 'PES = % ΔQs / % ΔP. Determinants: spare capacity, ease of stockholding, factor mobility, time period (longer is more elastic).', 11, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'How is market equilibrium determined?', 'At the price where Qd = Qs. Surplus -> price falls. Shortage -> price rises. The price mechanism rations, signals and incentivises. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="78" x2="120" y2="78" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="120" y1="78" x2="120" y2="130" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="81" font-size="9" fill="#0B1E3F" text-anchor="end">P*</text><text x="120" y="145" font-size="9" fill="#0B1E3F" text-anchor="middle">Q*</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 12, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define consumer surplus and producer surplus.', 'Consumer surplus: amount willing to pay above actual price. Producer surplus: amount received above minimum acceptable price. Both contribute to welfare.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Explain rational economic decision-making.', 'Consumers maximise utility, firms maximise profit, governments maximise welfare. Behavioural economics challenges this with bounded rationality, anchoring, herding and loss aversion.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'Define specialisation and division of labour with one advantage and one disadvantage.', 'Specialisation: focus on tasks/goods one is best at. Division of labour: tasks split between workers (Smith''s pin factory). Advantage: higher productivity. Disadvantage: monotony lowers morale.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '1.1', 'How Markets Work and Surplus', 'List four functions of money.', 'Medium of exchange (replaces barter), store of value (preserves purchasing power), unit of account (common measure of value), standard of deferred payment (debt contracts).', 16, 'alevel');

-- Topic 1.2 — Market Failure and Government Intervention
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Define market failure.', 'When the free market fails to allocate resources efficiently, leading to a welfare loss. Forms: externalities, public goods, information failure, monopoly power, inequality.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Distinguish private, external and social cost.', 'Private cost: borne by producer/consumer. External cost: spillover on third parties (pollution). Social cost = private + external. Markets ignore externals -> overproduction.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Show a negative production externality on a diagram.', 'MSC lies above MPC. Free-market output where MPB = MPC exceeds the social optimum where MSB = MSC. The triangle between is the deadweight welfare loss. <svg viewBox="0 0 240 150" width="240" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="225" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="200" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="200" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="65" y1="125" x2="220" y2="22" stroke="#0B1E3F" stroke-width="1.5" stroke-dasharray="3 2"/><polygon points="115,75 145,55 145,90" fill="#B00020" fill-opacity="0.3"/><text x="203" y="125" font-size="9" fill="#0B1E3F">D=MPB</text><text x="203" y="30" font-size="9" fill="#0B1E3F">MPC</text><text x="223" y="20" font-size="9" fill="#0B1E3F" text-anchor="end">MSC</text><text x="118" y="80" font-size="8" fill="#B00020">DWL</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="225" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 3, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Distinguish merit and demerit goods.', 'Merit goods are undervalued and underconsumed (education, healthcare, vaccines). Demerit goods are overvalued and overconsumed (cigarettes, alcohol). Tied to information failure and externalities.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'State the two characteristics of a public good.', 'Non-rival (one person''s use does not reduce another''s) and non-excludable (cannot prevent non-payers). Examples: street lighting, lighthouses, defence.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'What is the free-rider problem?', 'Because public goods are non-excludable, individuals can consume without paying. Profit-maximising firms cannot recoup costs, so the market under-provides — justifying state provision.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'How does asymmetric information cause market failure?', 'When one party knows more than another. Examples: used cars (Akerlof''s lemons), insurance (moral hazard, adverse selection), pensions (consumer ignorance).', 7, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Evaluate using an indirect (Pigouvian) tax.', 'Strengths: internalises external cost, raises revenue, signals harm. Weaknesses: hard to set at exact MEC, regressive, may shift activity to black markets, inelastic demand limits effect.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Evaluate using a subsidy on a positive externality.', 'Strengths: lowers price, raises output to social optimum, encourages innovation. Weaknesses: opportunity cost, dependency, hard to set at MEB, may favour wealthy producers.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'How does cap-and-trade (tradeable permits) work?', 'Government caps total emissions; firms hold permits they may trade. Polluters cutting emissions cheaply sell permits to those who can''t. Sets a market price on carbon — the EU ETS, and the UK ETS since 2021.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'When is a maximum price effective?', 'Set below equilibrium with elastic demand. Side effects: shortages, queueing, black markets, poor quality. UK rent controls in the 1970s reduced housing supply. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="105" x2="205" y2="105" stroke="#B00020" stroke-width="1.2" stroke-dasharray="4 2"/><line x1="80" y1="105" x2="160" y2="105" stroke="#B00020" stroke-width="2"/><text x="120" y="120" font-size="8" fill="#B00020" text-anchor="middle">shortage</text><text x="208" y="107" font-size="9" fill="#B00020">P max</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 11, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'When is a minimum price effective?', 'Set above equilibrium with surplus bought up by government — EU CAP, UK national living wage. Aim: support producer incomes or floor wages. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="195" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="50" x2="205" y2="50" stroke="#B00020" stroke-width="1.2" stroke-dasharray="4 2"/><line x1="65" y1="50" x2="170" y2="50" stroke="#B00020" stroke-width="2"/><text x="120" y="42" font-size="8" fill="#B00020" text-anchor="middle">surplus</text><text x="208" y="52" font-size="9" fill="#B00020">P min</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="198" y="30" font-size="9" fill="#0B1E3F">S</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 12, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Distinguish state provision and direct regulation.', 'State provision: public sector funds and supplies the good (NHS). Regulation: rules constrain private behaviour (smoking ban, vehicle emissions standards).', 13, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Why is a behavioural ''nudge'' often used instead of bans?', 'It exploits cognitive biases at low cost (default opt-in pension enrolment, organ donation) while preserving choice — libertarian paternalism (Thaler & Sunstein).', 14, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Define government failure.', 'Where intervention to correct market failure leads to a worse allocation. Causes: imperfect information, unintended consequences, regulatory capture, admin costs, political short-termism.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '1.2', 'Market Failure and Government Intervention', 'Why is competition policy needed?', 'To prevent abuse of monopoly power — anti-competitive mergers, predatory pricing, cartels — and protect consumers. Enforced by the CMA in the UK.', 16, 'alevel');

-- Topic 2.1 — National Economic Performance
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List the four main macroeconomic objectives.', 'Sustainable growth, low and stable inflation (~2% CPI), low unemployment (full employment), satisfactory current account. Plus: balanced budget, fairer distribution, environmental sustainability.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Distinguish nominal and real GDP.', 'Nominal: output at current prices. Real: at constant base-year prices, removing inflation. Real GDP captures actual output change.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Why use GDP per capita and PPP?', 'Per capita corrects for population. PPP corrects for differences in cost of living. Both make cross-country welfare comparisons more meaningful.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Give three limitations of GDP as a welfare measure.', 'Ignores distribution; misses informal/black economy and household production; ignores environmental damage; says nothing about leisure, health, freedom.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Outline how CPI is calculated.', 'Weighted average price of a representative basket from the Living Costs and Food Survey. Updated annually. Geometric mean used. Bank of England target measure.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List three limitations of CPI.', 'Quality changes hard to capture; basket lags behind taste shifts; excludes some housing costs; reflects average household, not individual budgets.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Distinguish demand-pull and cost-push inflation.', 'Demand-pull: AD rises faster than AS, pulling up prices. Cost-push: rising costs (wages, oil, weak pound) shift SRAS leftward, pushing prices up while output falls — stagflation possible.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List four costs of inflation.', 'Erodes purchasing power; menu and shoe-leather costs; uncertainty deters investment; loss of competitiveness; redistribution from creditors to debtors; fiscal drag.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Why is deflation a problem?', 'Consumers delay purchases; debt burden rises (Fisher debt-deflation); banks face credit losses; central bank loses traction at the zero lower bound. Hard to escape (Japan 1990s).', 9, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Distinguish four types of unemployment.', 'Cyclical (demand-deficient), frictional (between jobs), structural (mismatched skills/regions), seasonal. Plus real-wage and classical/voluntary.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Give three costs of unemployment.', 'Lost output (inside PPF), lower tax/higher benefit spend, hysteresis (skills atrophy), social costs (mental health, crime), inequality.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'How is unemployment measured (UK)?', 'Claimant count (those receiving JSA/Universal Credit) — narrow and quick. ILO/Labour Force Survey (out of work, actively sought work in the last four weeks and available to start within two weeks) — internationally comparable.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List the four parts of the current account.', 'Trade in goods, trade in services, primary income (interest, profits, dividends), secondary income (transfers — remittances, EU/UN payments, aid).', 13, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List two causes of a current-account deficit.', 'Strong domestic demand (sucks in imports), overvalued exchange rate, low productivity/competitiveness, deindustrialisation, slow trading-partner growth, high domestic inflation.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'List four phases of the business cycle.', 'Recovery, boom (peak), slowdown, recession (trough). A recession is technically two consecutive quarters of negative real GDP growth. <svg viewBox="0 0 260 150" width="260" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="245" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="30" y1="80" x2="245" y2="50" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><path d="M30 90 Q70 30 110 80 T190 90 T245 60" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><text x="80" y="40" font-size="8" fill="#0B1E3F" text-anchor="middle">peak</text><text x="155" y="105" font-size="8" fill="#0B1E3F" text-anchor="middle">trough</text><text x="245" y="48" font-size="8" fill="#0B1E3F" text-anchor="end">trend</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">Real GDP</text><text x="245" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">time</text></svg>', 15, 'alevel'),
  ('Economics', 'Edexcel B', '2.1', 'National Economic Performance', 'Define the output gap.', 'The difference between actual and potential GDP. A negative output gap implies spare capacity (recession); a positive gap implies overheating (inflationary pressure).', 16, 'alevel');

-- Topic 2.2 — Macroeconomic Policy
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Write the AD equation.', 'AD = C + I + G + (X − M). Consumption (~60%), investment (~15%), government spending (~20%), and net exports.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Why does AD slope downwards?', 'Real-balance effect (lower P raises real wealth and C); interest-rate effect (lower P -> lower r -> more I); international trade effect (lower P boosts X).', 2, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Distinguish SRAS and LRAS.', 'SRAS: upward sloping; sticky wages let higher P raise output. LRAS: vertical at full employment (classical) or with horizontal/upward/vertical sections (Keynesian). <svg viewBox="0 0 460 160" width="460" height="160" style="display:block;margin:6px auto"><g><line x1="30" y1="135" x2="200" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="140" y1="135" x2="140" y2="25" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="30" x2="180" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="200" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="143" y="20" font-size="9" fill="#0B1E3F">LRAS</text><text x="183" y="125" font-size="9" fill="#0B1E3F">AD</text><text x="115" y="155" font-size="9" fill="#0B1E3F" text-anchor="middle">Classical</text></g><g><line x1="260" y1="135" x2="440" y2="135" stroke="#0B1E3F"/><line x1="260" y1="135" x2="260" y2="20" stroke="#0B1E3F"/><path d="M260 110 L320 110 Q360 100 380 60 L380 25" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="270" y1="35" x2="420" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><text x="440" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text><text x="258" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="383" y="22" font-size="9" fill="#0B1E3F">LRAS</text><text x="423" y="125" font-size="9" fill="#0B1E3F">AD</text><text x="350" y="155" font-size="9" fill="#0B1E3F" text-anchor="middle">Keynesian</text></g></svg>', 3, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'List four determinants of LRAS.', 'Quantity/quality of labour, capital stock, technology and innovation, education and skills, infrastructure, openness to trade.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define the multiplier and give its formula.', 'k = ΔY / Δinjection. Closed economy with no government: k = 1/(1−MPC) = 1/MPS. Open economy with taxes: k = 1/(MPS+MPT+MPM).', 5, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'List injections and withdrawals from the circular flow.', 'Injections: investment (I), government spending (G), exports (X). Withdrawals: saving (S), taxation (T), imports (M). Equilibrium: I + G + X = S + T + M.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define monetary policy and the MPC.', 'Use of interest rates and money supply by the central bank to influence AD and meet the inflation target. UK: BoE Monetary Policy Committee (9 members) targeting 2% CPI.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Through which four channels does Bank Rate affect inflation?', 'Market interest rates (mortgages, savings), asset prices (housing, shares), confidence/expectations, exchange rate. Each affects AD with lags of 12-24 months.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'What is quantitative easing?', 'Central bank creates new electronic money to buy government bonds (and other assets), lowering long-term yields, raising bank reserves and asset prices, stimulating AD when Bank Rate is near zero.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define fiscal policy.', 'Use of government spending (G) and taxation (T) to influence AD and the supply side. Set in the Budget by HM Treasury; subject to fiscal rules and OBR forecasts.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Distinguish progressive, proportional and regressive taxes.', 'Progressive: average rate rises with income (UK income tax). Proportional: same percentage at all incomes. Regressive: average rate falls (VAT, council tax).', 11, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'What is the difference between budget deficit and national debt?', 'Deficit is the annual gap between G and T (a flow). National debt is the cumulative total of past borrowing (a stock). Each year''s deficit adds to the debt.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Define automatic stabilisers.', 'Built-in tax/benefit responses that smooth the cycle without explicit policy: tax revenues fall and benefits rise in recession; reverse in boom.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Distinguish demand-side and supply-side policies.', 'Demand-side: monetary and fiscal — manage AD over the cycle. Supply-side: raise LRAS over the long run via market reform, education, R&D, infrastructure.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Give three examples of supply-side policies.', 'Income/corporation tax cuts, deregulation, privatisation, education and training, R&D subsidies, infrastructure investment, weakening of trade unions, immigration.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '2.2', 'Macroeconomic Policy', 'Why must monetary and fiscal policy be coordinated?', 'They both affect AD. A loose fiscal stance with tight monetary policy creates conflict, raising long-term rates. Coordination — ''policy mix'' — improves outcomes.', 16, 'alevel');

-- Topic 3.1 — Globalisation, Trade and Global Business
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Define globalisation and give two ways it is measured.', 'The growing integration and interdependence of national economies through trade in goods and services, capital flows, migration, technology transfer and cultural exchange. Measured by trade as a share of world GDP, FDI flows, migrant stocks (304 million international migrants in 2024, UN DESA) and cross-border capital and data flows.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'List four causes of globalisation.', 'Containerisation and falling transport costs; ICT and the internet cutting communication costs to near zero; trade liberalisation through GATT/WTO and regional blocs; deregulation of capital markets; the growth of MNCs and fragmented global supply chains; the opening of China and the former Soviet bloc.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Give two benefits and two costs of globalisation for a national economy.', 'Benefits: lower prices and wider choice, inflows of FDI and technology, economies of scale from larger markets, faster growth and higher tax revenue. Costs: structural unemployment in uncompetitive sectors and regions, wider income inequality, greater exposure to external shocks, environmental damage, and erosion of the tax base through profit-shifting.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'State the law of comparative advantage and distinguish it from absolute advantage.', 'Absolute advantage is producing more output from the same inputs. Comparative advantage (Ricardo) is producing at a lower opportunity cost. Countries gain by specialising where their opportunity cost is lowest and trading for the rest, so total world output rises even if one country is absolutely better at everything. The gains show up as lower prices, more choice and consumption beyond the domestic PPF.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'List four assumptions or limitations of comparative advantage theory.', 'It assumes no transport costs, constant returns to scale, perfect factor mobility within countries, only two countries and two goods, free trade and perfect information. In practice transport costs, trade barriers, immobile factors, economies of scale and the risk of over-specialising in a volatile commodity all weaken the conclusion.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'List four protectionist tools.', 'Tariffs (a tax on imports), quotas (a quantity limit), subsidies to domestic producers, non-tariff barriers such as standards, licensing and paperwork, embargoes, voluntary export restraints, and exchange-rate manipulation.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Show the welfare effect of a tariff diagrammatically.', 'The domestic price rises from the world price by the size of the tariff. Producer surplus rises and government gains tariff revenue, but consumer surplus falls by more than the two gains combined; the difference is the deadweight loss shown by the production and consumption triangles. <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="245" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="40" y1="30" x2="220" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="130" x2="220" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="30" y1="100" x2="245" y2="100" stroke="#0B1E3F" stroke-width="1"/><line x1="30" y1="78" x2="245" y2="78" stroke="#0B1E3F" stroke-width="1"/><polygon points="80,100 100,78 100,100" fill="#B00020" fill-opacity="0.35"/><polygon points="180,100 160,78 180,78" fill="#B00020" fill-opacity="0.35"/><rect x="100" y="78" width="60" height="22" fill="#0B1E3F" fill-opacity="0.18"/><text x="225" y="125" font-size="9" fill="#0B1E3F">D</text><text x="225" y="35" font-size="9" fill="#0B1E3F">S</text><text x="248" y="103" font-size="9" fill="#0B1E3F">Pw</text><text x="248" y="80" font-size="9" fill="#0B1E3F">Pw+t</text><text x="125" y="93" font-size="8" fill="#0B1E3F" text-anchor="middle">tariff revenue</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="245" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 7, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Give three arguments for protectionism and two against.', 'For: the infant industry argument, managing decline in a sunset industry, national security and strategic supply, anti-dumping, correcting externalities from imported goods, and protecting jobs in vulnerable regions. Against: it raises prices and cuts consumer surplus, it shelters inefficiency and removes the incentive to cut costs, it invites retaliation, and it forfeits the gains from comparative advantage.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Outline the stages of economic integration, and distinguish trade creation from trade diversion.', 'Free trade area (no internal tariffs), customs union (plus a common external tariff), single market (free movement of goods, services, capital and labour), economic and monetary union (shared currency and macro policy). Trade creation: cheaper bloc suppliers replace dearer domestic production, so welfare rises. Trade diversion: bloc suppliers replace cheaper non-member suppliers because of the common external tariff, so welfare falls.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'What is the WTO and what does it do?', 'The World Trade Organization (founded 1995, successor to GATT) negotiates multilateral trade liberalisation, applies the Most-Favoured-Nation principle so a concession to one member goes to all, and settles disputes between members. Criticised for slow rounds (the Doha round stalled), for a dispute Appellate Body that has been unable to hear new appeals since 2019, and for terms that favour developed-country interests.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Distinguish floating, fixed and managed exchange-rate regimes.', 'Floating: the rate is set by the supply of and demand for the currency (sterling, the US dollar) and adjusts automatically to shocks, but is volatile. Fixed: the rate is pegged to another currency and defended with reserves, interest rates and capital controls (the Hong Kong dollar) — certainty for traders, but policy independence is lost. Managed or dirty float: broadly market-determined with occasional central-bank intervention.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'What are the effects of a depreciation, and what is the Marshall-Lerner condition?', 'Exports become cheaper abroad and imports dearer at home, so net exports and AD rise and domestic producers gain — but imported inputs, fuel and food push up cost-push inflation and squeeze firms that import. The current account improves only if |PEDx| + |PEDm| > 1. Short-run elasticities are low because contracts and habits take time to change, so the deficit often worsens before improving — the J-curve.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Define international competitiveness and name three determinants.', 'The ability of a country''s firms to sell in world markets relative to their rivals. Determinants: relative unit labour costs, productivity, the real exchange rate, relative inflation rates, skills and education, infrastructure, regulation and business taxation, and non-price factors such as quality, design and reliability.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'What is foreign direct investment, and why do firms undertake it?', 'FDI is cross-border investment giving a lasting interest in productive assets abroad — greenfield plants, joint ventures, or acquiring at least 10% of a foreign firm. Motives: access to large or fast-growing markets, lower labour or resource costs, jumping tariff and regulatory barriers, securing raw materials, favourable tax and subsidy regimes, and locating close to customers in the supply chain. It appears on the financial account of the balance of payments.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Why do firms expand overseas, and how do global supply chains work?', 'A saturated home market, larger overseas demand, economies of scale, lower unit costs, access to inputs and skills, and spreading risk across markets. Production is fragmented across countries — design in one, components from several, assembly in another — coordinated by an MNC. Risks: long chains are fragile (Covid-19 disruption, the 2021 Suez blockage), and transfer pricing between subsidiaries shifts profit to low-tax jurisdictions, which the OECD global minimum corporation tax rate of 15% is designed to limit.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '3.1', 'Globalisation, Trade and Global Business', 'Give three benefits and three costs of MNC activity to a host economy.', 'Benefits: employment, often at above-local wages; a capital inflow on the financial account; corporation tax revenue; transfer of technology, training and management practice, with spillovers to local suppliers; more competition and choice for consumers. Costs: profits repatriated to the parent country; transfer pricing shrinking the host tax take; local firms crowded out of product and capital markets; capital-intensive methods creating few jobs; pressure to keep labour and environmental standards weak; and footloose plants that can close at short notice.', 16, 'alevel');

-- Topic 3.2 — Global Labour Markets, Inequality and Redistribution
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What causes international migration of labour?', 'Pull factors: higher wages and living standards, unfilled vacancies and skills shortages, better public services and security, established diaspora networks, and freedom-of-movement agreements. Push factors: unemployment, low pay, conflict and persecution, climate change and natural disaster, and weak public services. Flows are also limited by visa policy, language, recognition of qualifications and the financial cost of moving.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What are the effects of inward migration on a host economy?', 'The labour supply rises, so LRAS and productive capacity shift right; skills shortages and low-paid vacancies are filled; migrants are mostly of working age, which improves the dependency ratio and the net fiscal position. AD also rises as migrants consume and pay rent. Costs: possible downward pressure on wages at the bottom of the distribution, and pressure on housing, schools and health services, often concentrated in particular regions. UK net migration fell to 171,000 in the year to December 2025 (ONS), down from 331,000 a year earlier.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What are the effects of emigration on a source economy?', 'Remittances are a major inflow — roughly $700 billion a year to low- and middle-income countries in the mid-2020s, several times the size of official aid — funding consumption, schooling and housing and showing up in secondary income on the current account. Unemployment pressure eases. But brain drain removes doctors, nurses, engineers and teachers whose training the state paid for, the dependency ratio worsens as working-age adults leave, and the loss of human capital slows long-run growth.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What does interdependence of labour markets mean, and how does the global supply of skilled and unskilled labour differ?', 'Wages and employment in one country now depend on labour conditions elsewhere, because firms can relocate production and workers can move to jobs. The global supply of unskilled and routine labour is very large and elastic, which holds down pay for routine work in advanced economies. Skilled labour is scarcer and far less mobile — licensing, language and visa rules get in the way — so skilled wages and the skill premium are higher and rising.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'Distinguish outsourcing and offshoring, and give one benefit and one cost of each.', 'Outsourcing: contracting an activity out to another firm, at home or abroad. Offshoring: moving the activity to another country, whether kept in-house or not. Benefits: lower unit labour costs, access to specialist expertise, and the freedom to concentrate on core competences. Costs: structural unemployment in the home economy, loss of control over quality and delivery, reputational risk from supplier labour standards, and longer, more fragile supply chains.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'How does MNC demand for labour affect wages and working conditions?', 'MNCs raise the demand for labour where they invest and typically pay above local rates, offering training and more stable employment, which lifts living standards. But they exercise monopsony power over their suppliers, squeezing pay and conditions further down the chain; they may choose locations where regulation and union power are weakest; and demand can be withdrawn quickly if costs rise. The evidence is mixed, which is why supply-chain reporting rules such as the UK Modern Slavery Act 2015 exist.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What is labour market flexibility, and give two arguments for and against it?', 'Flexibility means wages, hours, contracts and location adjust easily to changing conditions — weak employment protection, limited union power, part-time, temporary and zero-hours contracts, and flexible pay. For: lower structural unemployment, faster adjustment to shocks, and a more attractive location for FDI. Against: job and income insecurity, in-work poverty, weaker bargaining power, and less firm investment in training because staff turnover is high. Regulation differs sharply — the US is far more flexible than most of continental Europe, with the UK in between.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What is a skills shortage and how can it be reduced?', 'Excess demand for workers with a particular skill at the going wage, shown by hard-to-fill vacancies, rising wage premia and reliance on migrant labour — in the UK, engineering, construction, health and digital roles. Remedies: apprenticeships and vocational training, more places in shortage subjects, employer training incentives, and targeted skilled-worker visas. Occupational immobility is why shortages can persist at the same time as unemployment elsewhere in the economy.', 8, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'Distinguish absolute and relative poverty.', 'Absolute poverty: income too low to afford basic necessities. The World Bank line is $3.00 a day at 2021 PPP, raised from $2.15 in June 2025, which put the 2022 headcount at roughly 838 million people. Relative poverty: income below a benchmark set by the society concerned — the UK uses 60% of median household income, covering around 16% of people before housing costs and about 20% after them (DWP Households Below Average Income, 2024/25). Relative poverty can persist even when everyone is becoming better off.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What causes poverty, and what is the poverty trap?', 'Causes: unemployment, low pay and insecure hours, poor health and disability, low skills, caring responsibilities, discrimination, and high housing costs. The poverty trap is where earning more triggers the withdrawal of means-tested benefits at the same time as income tax and National Insurance become payable, so the effective marginal deduction rate is very high and there is little gain from working extra hours. Universal Credit''s single taper — 55p of benefit withdrawn per extra £1 earned since 2021 — was designed to soften it.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'Distinguish income and wealth inequality, and list four causes.', 'Income is a flow received over a period — wages, interest, rent, profit and benefits. Wealth is a stock of assets held at a point in time — property, pensions, shares and savings. Wealth is far more unequally distributed than income in the UK. Causes: differences in skills and education, inheritance, ownership of capital, discrimination, regional divides, technology raising the return to high skills, globalisation holding down routine pay, and the design of the tax and benefit system.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'How does the Lorenz curve work?', 'It plots the cumulative percentage of the population, ranked poorest first, on the horizontal axis against the cumulative percentage of income they receive on the vertical axis. Perfect equality is the 45-degree diagonal; the further the curve sags below it, the more unequal the distribution. Curves for different countries or years can be compared directly, but two curves that cross cannot be ranked. <svg viewBox="0 0 220 160" width="220" height="160" style="display:block;margin:6px auto"><line x1="30" y1="140" x2="200" y2="140" stroke="#0B1E3F"/><line x1="30" y1="140" x2="30" y2="20" stroke="#0B1E3F"/><line x1="30" y1="140" x2="190" y2="20" stroke="#0B1E3F" stroke-width="1.2" stroke-dasharray="3 2"/><path d="M30 140 Q120 140 190 20" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><text x="200" y="155" font-size="9" fill="#0B1E3F" text-anchor="end">% population</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">% income</text><text x="100" y="80" font-size="8" fill="#0B1E3F">equality</text><text x="120" y="125" font-size="8" fill="#0B1E3F">Lorenz</text></svg>', 12, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'Define the Gini coefficient and give three limitations.', 'The area between the Lorenz curve and the line of perfect equality, divided by the whole area beneath that line: 0 means perfect equality, 1 means one household has everything. For the UK in the financial year ending 2025 it was 33% before housing costs and 37% after them, so housing costs add several points to measured inequality. Limitations: a single number hides where in the distribution the inequality lies, two very different distributions can share the same Gini, it ignores wealth, informal income and benefits in kind, and it says nothing about absolute living standards.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'What does the Kuznets curve claim, and why is it disputed?', 'Kuznets argued that inequality follows an inverted U as a country develops: it widens as workers move from agriculture into higher-paid industry, then narrows as education spreads, labour becomes scarcer and redistribution grows. Disputed because inequality rose again in many advanced economies after 1980, the original evidence was a small cross-section of countries, and the path clearly depends on policy choices rather than being an automatic law of development.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'How can government redistribute income, and what is the equity-efficiency trade-off?', 'Progressive taxation — UK income tax at 20%, 40% and 45%, with the personal allowance tapered away above £100,000. Transfer payments — Universal Credit, the State Pension, disability benefits. A wage floor — the National Living Wage is £12.71 an hour for workers aged 21 and over from April 2026, a 4.1% rise on £12.21. Free or subsidised public services — the NHS and state education are benefits in kind that cut measured inequality sharply. Trade-off: high marginal rates and generous withdrawal can blunt incentives to work, save and take risks, so greater equity may be bought at the cost of efficiency.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '3.2', 'Global Labour Markets, Inequality and Redistribution', 'How do international aid and NGOs improve welfare?', 'Bilateral aid runs government to government (the UK''s FCDO); multilateral aid flows through institutions such as the World Bank and UN agencies; tied aid obliges the recipient to buy donor goods, untied does not. Aid can fund health, schooling, infrastructure, vaccination and emergency relief, raising living standards directly. NGOs such as Oxfam and Medecins Sans Frontieres deliver relief on the ground, often faster and closer to need than governments, and campaign on debt and trade policy. Criticisms: dependency, corruption and leakage, distorted local markets, and volatility — the UK cut its ODA target from 0.7% of GNI to 0.5% in 2021 and will cut it again to 0.3%, about £9.2bn, from 2027.', 16, 'alevel');

-- Topic 4.1 — Competition and Market Power
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Why do firms grow, and what constrains growth?', 'Motives: to exploit economies of scale and cut unit costs, to gain market power and raise prices, to diversify and spread risk, to increase profit, and to satisfy managerial objectives such as status and salary. Constraints: the size of the market, access to finance, diseconomies of scale and organisational complexity, regulatory blocks on mergers from the CMA, and owners who prefer to keep control. Some firms demerge when the parts are worth more apart than together.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Distinguish organic and inorganic growth, and the three types of integration.', 'Organic: internal expansion through extra output, new products or new markets — slower but lower risk. Inorganic: mergers and takeovers — faster, but risks overpayment, culture clash and regulatory scrutiny. Horizontal integration joins firms at the same stage of the same industry and raises market share directly. Vertical integration moves backwards towards suppliers or forwards towards distribution, securing inputs or outlets and potentially foreclosing rivals. Conglomerate integration combines unrelated markets to spread risk.', 2, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'How do economies of scale create market power?', 'Internal economies — technical, purchasing, managerial, financial, marketing and risk-bearing — cut long-run average cost as output rises. The minimum efficient scale (MES) is the smallest output at which LRAC reaches its minimum. Where MES is large relative to total market demand, only a few firms can reach competitive costs, incumbents hold a cost advantage over any entrant, and high concentration plus a natural barrier to entry follow. Past a point, diseconomies of scale — coordination, communication and motivation problems — push LRAC back up.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'State the assumptions of perfect competition and its long-run outcome.', 'Many small buyers and sellers, a homogeneous product, perfect information, and free entry and exit with no sunk costs. Each firm is a price taker facing a horizontal demand curve, so AR = MR = the market price. Short-run supernormal profit attracts entry, market supply rises and price falls until only normal profit remains. Long-run equilibrium: P = AR = MR = MC = minimum AC.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Is perfect competition efficient?', 'Statically, yes: output is at minimum average cost, so it is productively efficient, and P = MC, so it is allocatively efficient — society values the last unit at exactly what it cost to make. Dynamically, no: only normal profit is earned in the long run, so there is no surplus to fund research and development, and an identical product gives no reward for innovating. Schumpeter argued the prospect of monopoly profit is precisely what drives innovation.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Describe monopolistic competition.', 'Many small firms, differentiated products, and low barriers to entry — hairdressers, restaurants, plumbers, coffee shops. Each faces a downward-sloping but highly elastic demand curve, so it has a little price-setting power through branding and quality. In the short run supernormal profit is possible; in the long run entry competes it away to normal profit at a price above MC and above minimum AC, so the firm is neither allocatively nor productively efficient — but consumers gain variety and choice.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'List the characteristics of oligopoly and explain how concentration is measured.', 'A few large firms dominate; barriers to entry are high; firms are interdependent, so each must anticipate its rivals'' reactions; products may be differentiated or homogeneous; non-price competition matters more than price cutting. The n-firm concentration ratio measures the combined market share of the largest firms, and a CR4 above roughly 50% indicates an oligopoly. The Herfindahl-Hirschman Index sums the squared market shares, so it weights larger firms more heavily and is used in merger screening.', 7, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Explain the kinked demand curve.', 'In oligopoly, rivals are assumed to match a price cut but ignore a price rise. Demand is therefore inelastic below the current price (a cut wins little extra share but cuts revenue) and elastic above it (a rise loses customers to rivals who hold their price). The kink creates a vertical discontinuity in MR, so marginal cost can move within that gap without changing the profit-maximising price — a model of observed price stability, though it explains why prices stay put rather than how they were set. <svg viewBox="0 0 220 150" width="220" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="205" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="35" x2="115" y2="75" stroke="#0B1E3F" stroke-width="1.5"/><line x1="115" y1="75" x2="195" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="55" x2="115" y2="95" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><line x1="115" y1="115" x2="170" y2="125" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><line x1="115" y1="95" x2="115" y2="115" stroke="#0B1E3F" stroke-width="1" stroke-dasharray="3 2"/><circle cx="115" cy="75" r="2.5" fill="#0B1E3F"/><text x="115" y="68" font-size="8" fill="#0B1E3F" text-anchor="middle">kink</text><text x="198" y="125" font-size="9" fill="#0B1E3F">D</text><text x="170" y="135" font-size="9" fill="#0B1E3F">MR</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="205" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 8, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'What is collusion, and what does the prisoner''s dilemma show about it?', 'Collusion is firms agreeing to behave as a joint monopoly — fixing prices, sharing out markets or rigging bids. Overt collusion through a cartel is illegal in the UK under the Competition Act 1998; tacit collusion such as price leadership is far harder to prove. The prisoner''s dilemma shows why cartels are unstable: whatever the rival does, each firm''s dominant strategy is to undercut, so both end up at the low-price Nash equilibrium even though both would earn more by holding the high price. Leniency programmes exploit this by rewarding the first cartel member to confess.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'List the main non-price competition and pricing strategies used by firms with market power.', 'Non-price: advertising and branding, product quality and design, loyalty schemes, after-sales service, location and convenience — all of which build brand loyalty and raise entry barriers without triggering a price war. Pricing: limit pricing, setting price below a potential entrant''s average cost to deter entry; predatory pricing, pricing below cost to drive a rival out, which is illegal; penetration pricing to win share in a new market; price skimming on new technology; and price wars, which cut prices for consumers in the short run but can leave a more concentrated market.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Distinguish a pure from a working monopoly, and list the sources of monopoly power.', 'Pure monopoly: a single seller supplying the whole market. Working or legal monopoly: a firm with at least 25% market share — the share-of-supply threshold used in UK merger control under the Enterprise Act 2002; abuse of a dominant position is dealt with under the Competition Act 1998. Sources, which are also the barriers to entry: economies of scale and a high MES, large sunk costs, patents and copyright, control of an essential input or distribution network, brand loyalty built by advertising, network effects, and government licences or statutory protection.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'How does a profit-maximising monopoly set price and output?', 'It produces where MC = MR and then reads the price off the demand (AR) curve above that quantity, so price exceeds marginal revenue and marginal cost. Compared with perfect competition the result is a higher price and lower output, with supernormal profit — the shaded rectangle between AR and AC — sustained into the long run by barriers to entry. <svg viewBox="0 0 240 160" width="240" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="225" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><line x1="40" y1="35" x2="195" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><line x1="40" y1="35" x2="120" y2="130" stroke="#0B1E3F" stroke-width="1.5"/><path d="M40 90 Q90 130 130 95 T200 60" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><path d="M40 110 Q100 130 140 105 T210 75" stroke="#0B1E3F" stroke-width="1" fill="none" stroke-dasharray="3 2"/><line x1="30" y1="60" x2="100" y2="60" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="30" y1="92" x2="100" y2="92" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><line x1="100" y1="60" x2="100" y2="135" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><rect x="30" y="60" width="70" height="32" fill="#0B1E3F" fill-opacity="0.12"/><text x="198" y="130" font-size="9" fill="#0B1E3F">D=AR</text><text x="123" y="135" font-size="9" fill="#0B1E3F">MR</text><text x="200" y="62" font-size="9" fill="#0B1E3F">MC</text><text x="210" y="78" font-size="9" fill="#0B1E3F">AC</text><text x="28" y="63" font-size="9" fill="#0B1E3F" text-anchor="end">Pm</text><text x="100" y="148" font-size="9" fill="#0B1E3F" text-anchor="middle">Qm</text><text x="60" y="80" font-size="8" fill="#0B1E3F">profit</text></svg>', 12, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'Give the costs and benefits of monopoly, and define natural monopoly.', 'Costs: a higher price and lower output than under competition, allocative inefficiency and a deadweight welfare loss, X-inefficiency because weak competitive pressure allows costs to drift above the minimum, less choice, and the exploitation of suppliers. Benefits: economies of scale can push costs below the competitive level so price may still fall, supernormal profit can fund R&D and dynamic efficiency, and cross-subsidy can keep unprofitable services running. A natural monopoly has fixed costs so large relative to demand — water pipes, the rail network, the electricity grid — that one firm supplies at lower cost than several, so it is regulated by price caps of the RPI-X type (Ofwat, Ofgem, the ORR) rather than broken up.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'State the conditions for price discrimination and its welfare effects.', 'Three conditions: the firm must be a price maker with market power; it must be able to identify and separate groups with different price elasticities of demand; and it must be able to prevent resale between them. Third-degree examples: peak and off-peak rail fares, student and senior cinema tickets, airline seats sold by booking date. Effects: producer surplus rises as consumer surplus is transferred to the firm; those in the elastic segment pay less and total output may rise, funding services that would otherwise be unprofitable, but those in the inelastic segment pay more.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'What is monopsony power and what are its effects?', 'A monopsonist is a dominant buyer rather than a dominant seller — a single large employer in a local labour market, a supermarket group buying from farmers, or the NHS buying medicines. Because it faces an upward-sloping supply curve of the input, the marginal cost of buying one more unit exceeds the average, so it maximises profit by buying less at a lower price than a competitive buyer would. Effects: lower wages and employment, or squeezed supplier margins and investment; but lower input costs may be passed on as lower consumer prices. The Groceries Supply Code of Practice, enforced by the Groceries Code Adjudicator, restrains supermarket buyer power in the UK.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '4.1', 'Competition and Market Power', 'What is a contestable market, and what does UK competition policy do?', 'Baumol''s theory: a market is contestable when entry and exit are free and sunk costs are low, so even a single incumbent must price close to average cost or face hit-and-run entry. The implication is that entry conditions matter more than the number of firms, so policy should target barriers rather than structure. UK competition policy is enforced by the Competition and Markets Authority, which reviews mergers, prosecutes cartels, investigates abuse of a dominant position, and — under the Digital Markets, Competition and Consumers Act 2024 — can impose tailored conduct requirements on firms designated as having Strategic Market Status.', 16, 'alevel');

-- Topic 4.2 — Market Failure, Policy Impact and Financial Risk
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Define a public good and explain the free-rider problem.', 'A public good is non-rival — one person''s consumption does not reduce the amount available to anyone else — and non-excludable, so non-payers cannot be kept out. Examples: street lighting, flood defences, national defence, policing. Because of non-excludability everyone has an incentive to free-ride and let others pay, so revealed demand falls far short of true demand and no profit-seeking firm can cover its costs. The market therefore supplies none or far too little, and the state funds provision out of general taxation. Quasi-public goods such as roads, beaches and broadcasting are only partly non-rival or non-excludable.', 1, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Show an economy-wide negative externality and its welfare loss.', 'External costs mean marginal social cost lies above marginal private cost. The free market produces where MPB = MPC, beyond the social optimum where MSB = MSC, so output is too high and the shaded triangle is the deadweight welfare loss. Economy-wide examples: carbon emissions, road congestion, air pollution and antimicrobial resistance. Positive externalities reverse the argument — with vaccination, education and R&D spillovers MSB exceeds MPB, so the market under-produces. <svg viewBox="0 0 240 150" width="240" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="225" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><line x1="45" y1="30" x2="200" y2="125" stroke="#0B1E3F" stroke-width="1.5"/><line x1="45" y1="125" x2="200" y2="30" stroke="#0B1E3F" stroke-width="1.5"/><line x1="65" y1="125" x2="220" y2="22" stroke="#0B1E3F" stroke-width="1.5" stroke-dasharray="3 2"/><polygon points="115,75 145,55 145,90" fill="#B00020" fill-opacity="0.3"/><text x="203" y="125" font-size="9" fill="#0B1E3F">D=MPB</text><text x="203" y="30" font-size="9" fill="#0B1E3F">MPC</text><text x="223" y="20" font-size="9" fill="#0B1E3F" text-anchor="end">MSC</text><text x="118" y="80" font-size="8" fill="#B00020">DWL</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="225" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">Q</text></svg>', 2, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Distinguish merit and demerit goods.', 'Merit goods are under-consumed relative to what is socially desirable, because consumers undervalue the private benefit through information failure and because positive externalities are ignored — education, healthcare, vaccination, pension saving. Demerit goods are over-consumed for the mirror reasons — tobacco, alcohol, gambling, high-sugar food. Both rest on a value judgement about what people ought to consume, which is why intervention here is contested. Policy: subsidy, state provision, information campaigns and nudges for merit goods; indirect tax, regulation, advertising bans and minimum unit pricing for demerit goods. The Soft Drinks Industry Levy is the clearest UK example — 20.8p per litre in the standard band and 27.8p in the higher band from 1 April 2026, with the sugar threshold falling from 5g to 4.5g per 100ml and the milk-based exemptions removed from 1 January 2028.', 3, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'How do imperfect and asymmetric information cause market failure?', 'Imperfect information: neither party knows the full costs, benefits or alternatives, so the choices made are not welfare-maximising. Asymmetric information: one party knows more than the other. This gives adverse selection — Akerlof''s market for lemons, where only poor-quality used cars remain on sale, and insurance markets where the highest risks are keenest to buy cover — and moral hazard, where behaviour becomes riskier once a party is insured or protected. Remedies: compulsory disclosure and labelling, warranties, professional licensing, regulation, and standardised price comparison.', 4, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Explain factor immobility and inequity as market failures.', 'Geographical immobility: workers cannot move to where the jobs are because of housing costs, family ties and the expense of moving. Occupational immobility: their skills do not transfer, so structural unemployment persists alongside unfilled vacancies and labour is not allocated to its most productive use. Capital and land are immobile too. Inequity: the market rewards people according to the value of what they own and can sell, which can leave an outcome society judges unacceptably unequal even when it is efficient — a normative judgement rather than a Pareto one. Remedies: training and retraining, relocation and housing policy, transport investment, and redistribution through tax and benefits.', 5, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Define government failure and give four causes.', 'Government failure occurs where intervention intended to correct a market failure leaves a worse allocation of resources and a net welfare loss. Causes: information failure by policymakers who cannot value externalities precisely; unintended consequences and distorted incentives, such as rent controls cutting housing supply or landfill tax encouraging fly-tipping; administrative and compliance costs that absorb the benefit; regulatory capture, where the regulator comes to serve the industry; conflicting objectives between departments; political short-termism ahead of elections; and time lags between diagnosis, action and effect.', 6, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'List the components of AD and explain full capacity output.', 'AD = C + I + G + (X − M). In the UK consumption is roughly 60% of GDP, investment about 18%, government spending about 20%, with net trade usually negative. Full capacity output is where all factors are fully employed — the vertical section of the AS curve. With spare capacity below it, a rise in AD mostly raises real output and employment with little inflation; at or beyond full capacity the same rise feeds almost entirely into the price level. <svg viewBox="0 0 240 160" width="240" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="225" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><path d="M30 110 L110 110 Q160 100 180 55 L180 25" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="45" y1="45" x2="175" y2="128" stroke="#0B1E3F" stroke-width="1.5"/><line x1="80" y1="35" x2="210" y2="118" stroke="#0B1E3F" stroke-width="1.5" stroke-dasharray="3 2"/><line x1="180" y1="135" x2="180" y2="25" stroke="#0B1E3F" stroke-width="0.5" stroke-dasharray="2 2"/><text x="183" y="22" font-size="9" fill="#0B1E3F">AS</text><text x="178" y="130" font-size="9" fill="#0B1E3F">AD</text><text x="212" y="116" font-size="9" fill="#0B1E3F">AD1</text><text x="180" y="150" font-size="8" fill="#B00020" text-anchor="middle">full capacity</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">P</text><text x="225" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">Y</text></svg>', 7, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Define the multiplier and show how it is calculated.', 'An initial injection raises incomes, part of which is spent again, raising incomes further — so the eventual change in GDP exceeds the injection. k = ΔY / Δinjection = 1 / (1 − MPC) = 1 / MPW, where MPW = MPS + MPT + MPM. If MPC = 0.6 then k = 2.5, so £10bn of extra government investment raises GDP by £25bn. The multiplier is larger where there is spare capacity and a high MPC, and smaller in an open, heavily taxed economy or at full capacity, where the effect is absorbed by prices. It works in reverse for a withdrawal — the negative multiplier. <svg viewBox="0 0 260 150" width="260" height="150" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="245" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><rect x="50" y="85" width="34" height="45" fill="#0B1E3F" fill-opacity="0.35"/><rect x="96" y="103" width="34" height="27" fill="#0B1E3F" fill-opacity="0.25"/><rect x="142" y="114" width="34" height="16" fill="#0B1E3F" fill-opacity="0.18"/><rect x="188" y="120" width="34" height="10" fill="#0B1E3F" fill-opacity="0.12"/><text x="67" y="80" font-size="8" fill="#0B1E3F" text-anchor="middle">£10bn</text><text x="113" y="98" font-size="8" fill="#0B1E3F" text-anchor="middle">£6bn</text><text x="159" y="109" font-size="8" fill="#0B1E3F" text-anchor="middle">£3.6bn</text><text x="205" y="115" font-size="8" fill="#0B1E3F" text-anchor="middle">£2.2bn</text><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">ΔY</text><text x="245" y="145" font-size="9" fill="#0B1E3F" text-anchor="end">rounds of spending</text></svg>', 8, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'How does fiscal policy affect firms and individuals?', 'Expansionary fiscal policy — higher government spending or lower taxes — raises AD, sales and capacity utilisation, so firms invest and hire, and the accelerator amplifies the effect. A lower corporation tax rate (the UK main rate has been 25% since April 2023) leaves more retained profit for investment; lower income tax raises disposable income and consumption, helping firms selling income-elastic goods. Against that, higher employer National Insurance (15% since April 2025, up from 13.8%) and business rates raise unit costs and shift SRAS left. For individuals, tax thresholds and benefit rates determine real disposable income, and frozen thresholds pull people into higher bands through fiscal drag. Constraints: a larger deficit, debt interest, crowding out and long time lags.', 9, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'How does monetary policy affect firms and individuals?', 'The Bank of England''s Monetary Policy Committee sets Bank Rate to meet the 2% CPI target; it was held at 3.75% at the September 2026 meeting, the rate having been cut to that level in December 2025. A rise raises the cost of borrowing and of servicing variable-rate debt, so firms postpone investment as fewer projects clear the required return, stock-holding becomes dearer, and highly geared firms are hit hardest. Individuals face higher mortgage payments and better returns on saving, so consumption falls, especially of credit-financed durables and housing. A higher rate also attracts hot money and appreciates sterling — bad for exporters, good for importers of inputs. Effects work with lags of 12 to 24 months.', 10, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'How do supply-side policies affect firms and individuals?', 'Market-based: tax cuts, deregulation, privatisation, reduced union power, and welfare reform to sharpen work incentives. Interventionist: education and training, infrastructure, R&D tax credits, and regional or industrial policy. For firms these lower unit costs, widen the pool of available labour, and raise productivity, shifting LRAS to the right and allowing growth without inflation. For individuals they mean higher real wages and employment over time, but possibly less job security and wider inequality in the short run. Supply-side policy is slow and costly up front, yet it is the only route to raising the long-run trend rate of growth.', 11, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Give four macroeconomic policy conflicts.', 'Growth versus inflation — stimulating AD near full capacity pushes up prices, the short-run Phillips curve trade-off between unemployment and inflation. Growth versus the current account — faster growth sucks in imports and widens the deficit. Growth versus the environment — higher output raises emissions unless growth is decoupled from energy use. Equity versus efficiency — redistribution narrows the income gap but can blunt incentives. Deficit reduction versus growth — austerity cuts AD in the short run. Short-run demand management versus long-run supply-side reform, which needs spending now for gains much later.', 12, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Distinguish risk from uncertainty.', 'Risk, in Knight''s sense: the outcome is unknown but the range of possible outcomes and their probabilities are known or can be estimated from past data, so it can be priced, insured, diversified or hedged — for example an expected default rate on a loan book. Uncertainty: the probabilities, and sometimes the possible outcomes themselves, are unknowable — a pandemic, a war, a technological break. Uncertainty cannot be insured, so firms and households respond with precautionary saving, liquidity buffers and diversification, and investment falls when confidence, or what Keynes called animal spirits, weakens.', 13, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'List the roles of the financial sector.', 'Channelling savings into investment — banks and capital markets move funds from surplus units to deficit units, transforming maturity, size and risk. Providing the means of exchange — payment and settlement systems that let goods and services be traded. Providing forward markets in currencies and commodities, so firms can hedge a future price and plan with certainty. Providing a market for equities — the primary market raises new capital for firms, and the secondary market gives investors liquidity and prices companies continuously. Alongside these it lends to individuals and firms, and it pools and insures risk.', 14, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'Explain systemic risk, moral hazard and speculation.', 'Systemic risk: the failure of one institution cascades through the whole system because banks lend to each other and hold similar assets, producing contagion, fire sales and a credit crunch — as in 2007-08, when the failure of the interbank market froze lending to the real economy. Moral hazard: institutions that expect to be rescued because they are too big to fail take more risk than they otherwise would; the same applies to insured households and bailed-out borrowers. Speculation: buying an asset purely for capital gain rather than its yield, which adds liquidity but can inflate bubbles — dot-com shares, housing, crypto-assets — that burst and spill into output and employment. Market rigging such as the LIBOR scandal is a further conduct failure.', 15, 'alevel'),
  ('Economics', 'Edexcel B', '4.2', 'Market Failure, Policy Impact and Financial Risk', 'How are UK financial markets regulated?', 'Three bodies share the work. The Bank of England''s Financial Policy Committee is the macroprudential regulator, watching risk across the system as a whole and setting tools such as the countercyclical capital buffer and limits on mortgage loan-to-income ratios. The Prudential Regulation Authority, part of the Bank, supervises the safety and soundness of individual banks, insurers and major investment firms through capital and liquidity requirements and annual stress tests. The Financial Conduct Authority regulates conduct across all financial firms, enforcing the Consumer Duty, market integrity and competition, and it has a secondary objective to support growth and competitiveness. Post-crisis reform also ring-fenced retail from investment banking (in force since 2019) and created resolution regimes so a failing bank''s losses fall on shareholders and bondholders rather than taxpayers.', 16, 'alevel');
