-- A-Level Geography Flashcards (OCR)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- OCR A-LEVEL
-- ===============================================================

-- Topic 1.1 — Landscape Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Define a system in physical geography.', 'A set of interrelated stores and flows. Open: exchanges both energy and matter with surroundings (drainage basin, coastline). Closed: exchanges only energy (Earth''s overall water and carbon cycles).', 1, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Define a sediment cell.', 'A largely self-contained coastal section with sources, transfers and sinks of sediment between fixed boundaries (usually headlands). England and Wales are divided into 11 cells.', 2, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Distinguish constructive and destructive waves.', 'Constructive: low height, long wavelength, low frequency, strong swash, weak backwash, builds beaches. Destructive: tall, short wavelength, frequent, weak swash, strong backwash, removes sediment.', 3, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Name four wave-driven erosional processes.', 'Hydraulic action (waves compress air in cracks), abrasion (sediment scours), attrition (rocks knock together, become rounder), corrosion/solution (chemical dissolving — limestone, chalk).', 4, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Describe longshore drift.', 'Sediment is moved along a coast in a zigzag pattern: swash carries material up the beach in the prevailing wind direction; backwash returns it perpendicular to shoreline. Net result: lateral transport. <svg viewBox="0 0 260 130" width="260" height="130" style="display:block;margin:6px auto"><rect x="0" y="60" width="260" height="70" fill="#F2D9A5"/><line x1="0" y1="60" x2="260" y2="60" stroke="#0B1E3F" stroke-width="1.2"/><path d="M20 100 L60 70" stroke="#0B1E3F" marker-end="url(#d1)"/><path d="M60 70 L80 100" stroke="#0B1E3F" marker-end="url(#d1)" stroke-dasharray="2 2"/><path d="M80 100 L120 70" stroke="#0B1E3F" marker-end="url(#d1)"/><path d="M120 70 L140 100" stroke="#0B1E3F" marker-end="url(#d1)" stroke-dasharray="2 2"/><path d="M140 100 L180 70" stroke="#0B1E3F" marker-end="url(#d1)"/><path d="M40 30 L80 30" stroke="#B00020" marker-end="url(#d2)"/><text x="60" y="22" font-size="8" fill="#B00020" text-anchor="middle">prevailing wind</text><defs><marker id="d1" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker><marker id="d2" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#B00020"/></marker></defs></svg>', 5, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline the headland-bay-arch-stack sequence.', 'Differential erosion of soft and hard rock creates headlands and bays. Headlands attacked from sides: cracks → caves → caves meet (arch) → arch collapses (stack) → stack erodes (stump). Old Harry Rocks, Dorset.', 6, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline the formation of a wave-cut platform.', 'Waves erode a notch at the high-water mark; cliff above is undercut and collapses; cliff retreats inland leaving a flat rocky platform at low tide. Continued retreat creates wider platforms.', 7, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline the formation of a spit.', 'Longshore drift transports sediment past a change in coastline orientation; sediment accumulates in deeper water; secondary winds curve the end (recurve). Sheltered area behind develops salt marsh. Examples: Spurn Head, Hurst Castle.', 8, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Distinguish concordant and discordant coasts.', 'Concordant: rock layers parallel to coast (Lulworth Cove, Dorset). Discordant: layers perpendicular, headlands and bays form (Swanage, Dorset). Reflects geology and erosional differentials.', 9, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Distinguish eustatic and isostatic sea-level change.', 'Eustatic: global change in volume of seawater (ice melt, thermal expansion). Isostatic: local change in land level (glacial rebound, subsidence). Together produce relative sea-level change.', 10, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'List four hard-engineering coastal defences and one drawback each.', 'Sea wall (expensive, ugly), groynes (starve down-drift coast), rock armour/rip-rap (visual impact), revetment (costly maintenance), gabions (rust over time). Defer rather than solve.', 11, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'List four soft-engineering coastal defences.', 'Beach nourishment, dune regeneration (planting marram grass), managed retreat/coastal realignment, salt-marsh restoration, planning controls. Cheaper, more sustainable, but slower-acting.', 12, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Define Shoreline Management Plans (SMPs).', 'UK strategic plans for coastal stretches: hold the line, advance the line, managed retreat, or no active intervention. Reviewed every 5-10 years and balance economic, social and environmental factors.', 13, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline glacial systems and key processes.', 'Open systems with inputs (snowfall, avalanches), stores (ice, meltwater) and outputs (meltwater discharge, calving). Processes: plucking (ice freezes onto bedrock, plucks blocks), abrasion (rock fragments scour bedrock), freeze-thaw weathering.', 14, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Distinguish polar and temperate glaciers.', 'Polar (cold-based): below freezing, frozen to bedrock, slow movement, little erosion (Antarctic). Temperate (warm-based): meltwater at base, faster basal sliding, more erosion (Alpine, NZ Southern Alps).', 15, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline the formation of a corrie.', 'Snow accumulates in a north-facing hollow, compresses to firn then ice. Plucking and abrasion deepen the hollow; rotational movement scoops it into an armchair shape. After deglaciation, a tarn (lake) often fills it.', 16, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline the formation of a U-shaped valley.', 'A pre-existing V-shaped river valley is widened, deepened and straightened by glacier ice. Truncated spurs replace interlocking ones. After deglaciation: misfit stream, sometimes ribbon lakes (Wastwater).', 17, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Distinguish drumlin, esker and erratic.', 'Drumlin: streamlined hill of glacial till. Esker: sinuous ridge of fluvio-glacial sand and gravel (deposited by sub-glacial stream). Erratic: large rock transported far from origin (Norber erratics, Yorkshire).', 18, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'Outline pressures on a glacial environment.', 'Climate change accelerates ice loss (Alpine glaciers retreating ~50 m/yr); tourism leaves footprint; mineral exploration in Antarctica suspended by Treaty (1961); Madrid Protocol (1991) extended environmental protections.', 19, 'alevel'),
  ('Geography', 'OCR', '1.1', 'Landscape Systems', 'How is climate change altering coasts and glaciers?', 'Sea-level rise drowns low-lying coasts; storms intensify erosion; ocean acidification damages coral; warmer oceans bleach reefs. Glaciers retreat, threatening dry-season meltwater for downstream cities (Andes, Himalaya).', 20, 'alevel');

-- Topic 1.2 — Earth''s Life Support Systems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Define a system, store, flow.', 'System: set of interrelated stores and flows. Store: where matter/energy is held (oceans, atmosphere, vegetation). Flow: transfer between stores (precipitation, evaporation, photosynthesis).', 1, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'List the four major stores of the global water cycle.', 'Oceans (~97%), cryosphere/ice (~2%), groundwater (~0.7%), surface water and atmosphere (<0.1%). Lithosphere holds tiny amounts in rocks.', 2, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Sketch the global water cycle.', 'Solar energy drives evaporation from oceans, vegetation transpires, vapour rises and condenses, precipitates over land/oceans; runoff and groundwater return to sea. <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><rect x="0" y="120" width="260" height="40" fill="#9CC3E5"/><polygon points="120,120 200,120 220,80 130,80" fill="#A8D08D"/><circle cx="60" cy="35" r="12" fill="#E7E6E6"/><circle cx="180" cy="30" r="14" fill="#E7E6E6"/><path d="M40 110 Q40 80 60 50" stroke="#0B1E3F" fill="none" marker-end="url(#d3)"/><path d="M150 90 Q150 70 170 45" stroke="#0B1E3F" fill="none" marker-end="url(#d3)"/><path d="M210 50 Q220 80 220 110" stroke="#0B1E3F" fill="none" marker-end="url(#d3)"/><defs><marker id="d3" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs><text x="20" y="80" font-size="8" fill="#0B1E3F">evap</text><text x="125" y="65" font-size="8" fill="#0B1E3F">transp</text><text x="220" y="80" font-size="8" fill="#0B1E3F">precip</text></svg>', 3, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Define a drainage basin.', 'Area of land drained by a river and its tributaries. Watershed: high-ground boundary. Source: where the river begins. Mouth: where it enters the sea. Confluence: junction of two streams.', 4, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Sketch the drainage basin (inputs, stores, flows, outputs).', 'Input: precipitation. Stores: interception, surface, soil moisture, groundwater, channel. Flows: surface runoff, throughflow, infiltration, percolation, baseflow. Outputs: evaporation, transpiration, channel discharge.', 5, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Define a storm hydrograph.', 'A graph of river discharge against time after a storm. Lag time: gap between peak rainfall and peak discharge. Steeper rising limb / shorter lag indicate flashier basin (urbanised, impermeable, steep, saturated).', 6, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Distinguish physical and human factors that increase flood risk.', 'Physical: heavy/prolonged rainfall, snowmelt, impermeable rock, steep relief, antecedent saturation. Human: urbanisation (impermeable surfaces, drains), deforestation, channel modification, climate change.', 7, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'List the four major stores of the global carbon cycle.', 'Lithosphere (sedimentary rocks, fossil fuels — by far largest), oceans (dissolved CO2, biological), terrestrial biosphere (vegetation, soils), atmosphere (CO2, CH4 — smallest but climate-critical).', 8, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Distinguish fast and slow carbon cycles.', 'Fast: photosynthesis, respiration, decomposition, ocean exchange — operates over days to centuries. Slow: weathering of silicates, sedimentation, volcanism — operates over millions of years.', 9, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Sketch the global carbon cycle.', 'Atmosphere ↔ photosynthesis (vegetation) and respiration; vegetation → soil via decomposition; oceans absorb/release CO2; weathering removes; volcanism returns; fossil fuel combustion releases stored. <svg viewBox="0 0 280 160" width="280" height="160" style="display:block;margin:6px auto"><rect x="20" y="20" width="240" height="30" fill="#E7E6E6"/><text x="140" y="38" font-size="9" fill="#0B1E3F" text-anchor="middle">Atmosphere (CO2)</text><rect x="20" y="80" width="100" height="30" fill="#A8D08D"/><text x="70" y="98" font-size="9" fill="#0B1E3F" text-anchor="middle">Vegetation</text><rect x="160" y="80" width="100" height="30" fill="#9CC3E5"/><text x="210" y="98" font-size="9" fill="#0B1E3F" text-anchor="middle">Oceans</text><rect x="160" y="125" width="100" height="20" fill="#454545"/><text x="210" y="139" font-size="9" fill="white" text-anchor="middle">Fossil fuels</text><line x1="50" y1="50" x2="50" y2="78" stroke="#0B1E3F" marker-end="url(#d4)"/><line x1="90" y1="78" x2="90" y2="52" stroke="#0B1E3F" marker-end="url(#d4)"/><line x1="200" y1="123" x2="200" y2="55" stroke="#B00020" stroke-width="1.2" marker-end="url(#d5)"/><defs><marker id="d4" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker><marker id="d5" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#B00020"/></marker></defs></svg>', 10, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Outline the ocean carbon pumps.', 'Physical (solubility) pump: cold polar water dissolves CO2, sinks, locks C in deep ocean for centuries. Biological pump: phytoplankton photosynthesise; dead matter sinks (''marine snow'') sequestering C in sediments.', 11, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Why does the Amazon matter for both cycles?', 'Stores ~150-200 Pg C in biomass and soils; transpires huge water vapour into the atmosphere driving regional rainfall. Deforestation reduces both the carbon sink and the moisture flux, risking ''dieback'' tipping points.', 12, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'How are land-use change and farming affecting the carbon cycle?', 'Deforestation releases stored C and reduces sinks. Ploughing exposes/oxidises soil organic matter. Drainage of peatlands releases CO2. Livestock and rice paddies emit methane (~25× CO2 GWP).', 13, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'List four positive feedbacks accelerating climate change.', 'Ice-albedo (less ice -> more absorbed solar), permafrost thaw releasing CH4, forest dieback releasing C, ocean warming reducing CO2 solubility, slowed thermohaline circulation.', 14, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Define dynamic equilibrium and tipping point.', 'Dynamic equilibrium: stores fluctuate around a long-term average as inputs balance outputs. Tipping point: critical threshold where small change causes a shift to a new state, often irreversible.', 15, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'List four climate change impacts.', 'Sea-level rise (~3.4 mm/yr), Arctic ice loss, more extreme weather, ocean acidification (pH ~8.2 → 8.1), shifts in species ranges, glacier retreat, permafrost thaw, agricultural disruption.', 16, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Outline mitigation strategies for climate change.', 'Cut emissions: renewables, EVs, energy efficiency, low-carbon heating, food system change. Carbon capture and storage. Afforestation. Reduce deforestation (REDD+). International agreements (Paris 2015 - 1.5°C target).', 17, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Outline adaptation strategies.', 'Sea defences and coastal realignment, drought-resistant crops, water resource planning, urban cooling (green roofs, white surfaces), early warning systems, shifting agricultural zones, redesigned infrastructure.', 18, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'Define the Paris Agreement.', 'A UNFCCC treaty (2015) signed by ~196 parties. Aims to limit warming to ''well below 2°C'' above pre-industrial, pursuing 1.5°C. Each country sets Nationally Determined Contributions (NDCs), reviewed every 5 years.', 19, 'alevel'),
  ('Geography', 'OCR', '1.2', 'Earth''s Life Support Systems', 'How does deforestation affect the water and carbon cycles?', 'Reduces interception and transpiration -> overland flow rises, regional rainfall falls (Amazon ''flying rivers''). Releases stored C, reduces sink capacity, raises local temperatures via reduced cooling.', 20, 'alevel');

-- Topic 1.3 — Hazardous Earth
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Define hazard, risk, vulnerability and resilience.', 'Hazard: potential damaging event. Risk: probability × consequence. Vulnerability: degree to which a community is susceptible. Resilience: ability to absorb, adapt and recover. R = (H × V) / Capacity.', 1, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Outline the structure of the Earth.', 'Inner core (solid Fe/Ni, ~5500°C), outer core (liquid Fe/Ni, generates magnetic field), mantle (semi-molten silicates, convection cells), crust: oceanic (5-10 km, basalt) and continental (30-70 km, granite).', 2, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Explain plate motion via mantle convection, ridge push, slab pull.', 'Heat from radioactive decay drives mantle cells. Hot rock rises at ridges, pushes plates apart (ridge push). Cold dense oceanic lithosphere subducts, dragging the rest of the plate (slab pull — dominant force).', 3, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Sketch the three plate-boundary types.', 'Constructive (divergent): plates move apart, mid-ocean ridges/rifts. Destructive (convergent): denser oceanic subducts beneath continental, trench/volcanic arc. Conservative (transform): plates slide past, earthquakes only. <svg viewBox="0 0 280 150" width="280" height="150" style="display:block;margin:6px auto"><g><rect x="10" y="40" width="40" height="40" fill="#A0A0A0"/><rect x="60" y="40" width="40" height="40" fill="#A0A0A0"/><polygon points="50,40 60,40 55,20" fill="#B00020"/><line x1="20" y1="60" x2="0" y2="60" stroke="#0B1E3F" marker-end="url(#d6)"/><line x1="90" y1="60" x2="110" y2="60" stroke="#0B1E3F" marker-end="url(#d6)"/><text x="55" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Constructive</text></g><g><rect x="120" y="40" width="50" height="40" fill="#A0A0A0"/><polygon points="170,40 215,80 215,40" fill="#A0A0A0"/><polygon points="180,40 200,40 190,25" fill="#B00020"/><text x="170" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Destructive</text></g><g><rect x="225" y="40" width="50" height="40" fill="#A0A0A0"/><line x1="250" y1="40" x2="250" y2="80" stroke="white" stroke-width="2"/><line x1="240" y1="50" x2="260" y2="50" stroke="#0B1E3F" stroke-dasharray="2 2"/><text x="250" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Conservative</text></g><defs><marker id="d6" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs></svg>', 4, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Define a hot spot.', 'Mantle plumes that pierce moving plates and form volcanic chains as the plate moves over them (e.g. Hawaiian-Emperor seamount chain, Yellowstone caldera). Independent of plate boundaries.', 5, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Distinguish primary and secondary effects of a volcanic eruption.', 'Primary: lava, pyroclastic flows, ashfall, gases. Secondary: lahars (mud flows), tsunamis, climate impact (Pinatubo 1991 cooled global T by 0.5°C), economic disruption, displacement.', 6, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Compare a shield with a composite (stratovolcano).', 'Shield: low-viscosity basaltic lava, gentle slopes, frequent effusive eruptions (Mauna Loa). Composite: high-viscosity andesitic lava, steep alternating ash/lava layers, infrequent explosive eruptions (Mt St Helens, Vesuvius).', 7, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Define VEI.', 'Volcanic Explosivity Index — logarithmic 0-8 based on ejecta volume and column height. VEI 0-2: effusive, frequent. VEI 5+: highly explosive (Mt St Helens 1980 = 5; Pinatubo 1991 = 6; Tambora 1815 = 7).', 8, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'How are earthquakes measured?', 'Magnitude (energy): Moment Magnitude Scale (Mw, replaced Richter above ~M5; logarithmic). Intensity (effects): Modified Mercalli (I-XII). Depth: shallow (<70 km) most damaging.', 9, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Describe seismic waves: P, S and surface.', 'P (primary) waves: longitudinal compression, fastest, travel through solids and liquids. S (secondary): transverse, slower, only solids. Surface (Rayleigh, Love): slowest, largest amplitude, cause most damage.', 10, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'List four secondary effects of earthquakes.', 'Tsunami (Tohoku 2011), liquefaction (saturated sandy soils losing strength), landslides, fires (gas mains), disease, building collapse aftershocks. Often cause more deaths than primary shaking.', 11, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Explain how a tsunami forms.', 'Sudden vertical displacement of seabed (megathrust earthquake at subduction zone) lifts the entire water column. Long-wavelength waves travel ~700 km/h in deep ocean, slow and steepen on the shelf, surge inland.', 12, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Outline tropical storm formation conditions.', 'Forms over oceans >26.5°C, depth >50 m, latitude 5-30° (Coriolis required), low wind shear. Warm core driven by latent heat release. Coriolis spins the storm cyclonically (anticlockwise N hemisphere).', 13, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'List four hazards of a tropical storm.', 'High winds, torrential rain, storm surge, flooding, landslides. Storm surge typically causes most deaths in low-lying areas (Bangladesh 1970 cyclone — 300,000+ deaths).', 14, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Outline Park''s response curve.', 'Quality of life trace through pre-disaster, disruption, search-and-rescue, relief, rehabilitation, reconstruction. Recovery may exceed (more resilient), match, or fall below pre-disaster level depending on aid and management.', 15, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Outline the PAR (Pressure and Release) model.', 'Disasters arise from the intersection of natural hazard and social vulnerability. Root causes (poverty, governance) -> dynamic pressures (rapid urbanisation, deforestation) -> unsafe conditions (slums on hillsides). Releases pressure by addressing causes.', 16, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Compare HIC and LIC earthquake responses.', 'Tohoku, Japan 2011 (Mw9.1): ~20,000 deaths, $235bn damage, advanced warning, building codes, swift recovery. Haiti 2010 (Mw7.0): ~230,000 deaths, weak buildings, slow recovery, lasting cholera outbreak.', 17, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'List four disaster mitigation strategies.', 'Hazard mapping/zoning, building codes (base isolation), early warning systems (Japan 1-min alert), education and drills, retrofitting, insurance, emergency stockpiles, community awareness.', 18, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Define a multi-hazard zone.', 'Region exposed to several hazards (e.g. Philippines: typhoons, earthquakes, volcanism, tsunamis, landslides). Compound risk: one event can trigger another. Increases vulnerability and complicates planning.', 19, 'alevel'),
  ('Geography', 'OCR', '1.3', 'Hazardous Earth', 'Why does hazard impact differ between countries?', 'Wealth funds prevention/response. Strong governance enforces codes, manages aid. LICs lack early warning, hospitals, finance — so similar magnitudes cause higher death tolls. Cultural perception shapes preparedness.', 20, 'alevel');

-- Topic 2.1 — Changing Spaces, Making Places
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Distinguish space, place and locale.', 'Space: an area defined by coordinates. Place: space invested with meaning by people (Tuan). Locale: setting in which everyday life happens (Agnew). Place is therefore relational and dynamic.', 1, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define endogenous and exogenous factors.', 'Endogenous (internal): physical geography, demography, land use, economy, built environment, history. Exogenous (external): connections to other places, migration, capital flows, government policy, globalisation.', 2, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define topophilia and topophobia.', 'Topophilia (Tuan, 1974): the affective bond between people and place — love of place. Topophobia: fear or dislike of place — common in places associated with crime, decay, traumatic memory.', 3, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Distinguish insider and outsider perspectives.', 'Insider: born or long-resident, share traditions, language, networks; place-attached. Outsider: temporary or unfamiliar; may romanticise or stereotype. Status fluid — gentrifiers can shift between.', 4, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'How does the IMD measure deprivation?', 'UK Index of Multiple Deprivation combines seven domains: income, employment, education, health, crime, housing, living environment. Areas ranked into deciles. Allows place-by-place comparison of need.', 5, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Outline gentrification with one named example.', 'In-migration of higher-income residents into a previously low-income area, refurbishing housing and changing local amenities. Displaces original residents through rising rents. Examples: Notting Hill, Brixton, Hackney, Brooklyn.', 6, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Outline an urban regeneration scheme (London Docklands).', '1981 LDDC established. £8.7bn investment by 1998. Canary Wharf, DLR, City Airport. 80,000+ jobs. Critique: original communities largely excluded; gentrification displaced low-income residents.', 7, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Outline a rural rebranding strategy with example.', 'Cornwall: Eden Project (£2bn local economic impact since 2001), Hall for Cornwall, food/drink tourism, surf tourism, films like Doc Martin. Trade-offs: housing affordability for locals.', 8, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define rural-urban continuum.', 'Spectrum from deep countryside through accessible rural, suburb, inner suburb, inner city. Pace of life, density, services, demographic profile vary along it. Boundaries blur as commuter belts extend.', 9, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Outline counter-urbanisation drivers.', 'Improved transport/IT (commute, remote work), perception of better quality of life (lower crime, cleaner air, schools), housing affordability, retirement. Covid-19 accelerated UK ''race for space'' (London out-migration ~80,000 in 2020-21).', 10, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define ethnic enclave.', 'A neighbourhood with high concentration of one ethnic group. Reasons: chain migration, mutual support, language/cultural amenities, discrimination in housing markets. Examples: Tower Hamlets (Bangladeshi), Brixton (Caribbean).', 11, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'List four ways place is represented.', 'Statistics (census, IMD), films, novels, paintings, photographs, music, postcards, tourist boards, news media, social media (#hashtags create new place identities).', 12, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define lived experience and methods to access it.', 'Everyday meanings of a place to its residents. Accessed through ethnography, interviews, oral histories, participant observation, mental maps, photo elicitation — qualitative methods that surface what statistics cannot.', 13, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'How does globalisation affect place identity?', 'Increases similarity (clone towns, McDonaldisation), but also enables cultural hybridity (London curry, Liverpool Chinatown). Some places resist (CittaSlow, fair-trade towns); others rebrand to compete.', 14, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define resilience of place.', 'A place''s ability to absorb shocks (flooding, deindustrialisation, pandemics) and adapt. Drivers: economic diversity, social capital, governance, infrastructure. Detroit struggled; Pittsburgh transitioned to ''eds and meds''.', 15, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define social, ethnic and economic diversity in a place.', 'Social: variation in age, household type, religion. Ethnic: variation in cultural/national identities (London ~40% non-white British). Economic: range of income levels, occupations, deprivation indicators.', 16, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Outline how power shapes place.', 'Local authorities, developers and capital decide which places get investment. Power asymmetries displace less powerful (low-income, ethnic minorities). Resistance: campaigns (Save Latin Village), community land trusts, rent controls.', 17, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Define place-meaning and place-identity.', 'Place-meaning: subjective values and emotions attached to place by individuals/groups. Place-identity: sense of self constructed through belonging to place (national, regional, neighbourhood).', 18, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Outline community-led place-making.', 'Local residents shape their place through neighbourhood plans, community land trusts, public art, festivals, restoration projects. Examples: Hackney Wick, Granby Four Streets (Liverpool, Turner Prize 2015).', 19, 'alevel'),
  ('Geography', 'OCR', '2.1', 'Changing Spaces, Making Places', 'Compare a contrasting place study.', 'Choose two places (e.g. local urban + rural Cornwall), compare endogenous and exogenous factors, demographic and economic profiles, representations, lived experiences and management strategies — OCR core skill.', 20, 'alevel');

-- Topic 2.2 — Trade in the Contemporary World
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define globalisation.', 'Growing integration of national economies through international trade, capital flows, migration, technology transfer and cultural exchange. Driven by transport costs, ICT and trade liberalisation.', 1, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'List four causes of globalisation.', 'Falling transport/communication costs, trade liberalisation (WTO/GATT), ICT advances, deregulation of capital markets, end of Cold War, growth of multinationals (TNCs), rising consumer incomes.', 2, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'State Ricardo''s law of comparative advantage.', 'Countries should specialise in goods they produce at the lowest opportunity cost and trade for the rest. Total world output rises even if one country is absolutely better at all goods.', 3, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define a TNC and explain its role in globalisation.', 'Transnational Corporation: a firm operating in multiple countries (Apple, Toyota, Unilever). Drives globalisation by offshoring production, FDI, supplying global markets, transferring technology — but accused of tax avoidance, exploitation.', 4, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define a Special Economic Zone (SEZ).', 'A geographic region with relaxed regulation/taxes to attract FDI. Shenzhen, China''s first SEZ (1980), grew from 30,000 to 12 million people. Catalysed China''s manufacturing boom; 4500+ SEZs globally.', 5, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'List the four stages of economic integration.', 'Free trade area (no tariffs), customs union (common external tariff), single/common market (free factor movement), economic and monetary union (common currency). EU progressed through all four.', 6, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Outline the WTO''s main role.', 'Promotes liberal world trade by negotiating multilateral agreements, enforcing the Most-Favoured-Nation principle and arbitrating disputes. Successor to GATT (1995). 164 members; struggles with stalled Doha round.', 7, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'List four protectionist tools.', 'Tariffs, quotas, subsidies to domestic firms, non-tariff barriers (regulation, technical standards), exchange-rate intervention, embargoes, voluntary export restraints.', 8, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Outline the global shift in manufacturing.', 'Movement of manufacturing from HICs to NEEs since 1970s, driven by cheaper labour, weaker regulation. China rose to ~28% of global manufacturing. Now Vietnam, Bangladesh capture textile from China as wages rise.', 9, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Outline winners and losers of globalisation.', 'Winners: emerging economies (China, India), TNCs and shareholders, skilled labour in HICs, consumers (cheaper goods). Losers: low-skilled labour in HICs (deindustrialisation), workers in sweatshops, environment.', 10, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define switched-on and switched-off places.', 'Switched-on: well-connected to global flows of capital, people, goods (London, NYC, Shanghai). Switched-off: poor connections, peripheral economies (Sahel, Central Asia interior). Inequality reinforced by global system.', 11, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'List four economic impacts of globalisation in HICs.', 'Deindustrialisation (UK manufacturing share fell from ~30% in 1970 to ~9% by 2020), service-sector growth, regional inequality (north-south UK), wage stagnation for low-skilled, rising inequality.', 12, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'List four economic impacts of globalisation in NEEs.', 'Rapid industrialisation (China factory of the world), urbanisation, rising incomes (China''s GDP/cap rose ~40× since 1980), inequality, environmental degradation, financial volatility (1997 Asian crisis).', 13, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define cultural homogenisation and hybridisation.', 'Homogenisation: dominant cultures (often US/Western) spread, eroding local distinctiveness (McDonaldisation, Hollywood). Hybridisation: cultures mix to produce new forms (London curry, K-pop in West, Bollywood-Hollywood crossover).', 14, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Outline ethical/local responses to globalisation.', 'Fair trade (Fairtrade Foundation 1992), local sourcing, transition towns, ethical investment, anti-globalisation movements (Seattle 1999), CittaSlow (slow cities), buy local campaigns.', 15, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define re-shoring and explain why it occurs.', 'Returning production to home country. Drivers: rising wages abroad, automation reducing labour-cost advantage, supply chain risks (Covid, Ukraine), tariffs (Trump 2018, 2024), national security (semiconductors).', 16, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Outline the de-globalisation trend (post-2008).', 'Slowdown in trade growth, more protectionism (US-China tariffs), Brexit, Covid-disrupted supply chains, semiconductor decoupling, Russia sanctions. Trade share of GDP fell from peak ~61% (2008) to ~57% (2020s).', 17, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Define foreign direct investment (FDI).', 'Investment by a firm in productive assets in another country (factories, subsidiaries). Brings capital, jobs, technology and know-how but can crowd out domestic firms or repatriate profits.', 18, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'Outline the Belt and Road Initiative.', 'China''s ~$1tn (since 2013) infrastructure programme (ports, rail, energy) across ~150 countries. Aims to revive Silk Road trade, expand Chinese influence, secure resources. Critics: ''debt trap diplomacy''.', 19, 'alevel'),
  ('Geography', 'OCR', '2.2', 'Trade in the Contemporary World', 'List four environmental impacts of globalisation.', 'Higher emissions from transport (~14% of global), deforestation for plantations (palm oil), e-waste (~50 Mt/yr), ocean plastic, biodiversity loss, water and air pollution near production hubs.', 20, 'alevel');

-- Topic 2.3 — Global Migration
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define migration push and pull factors.', 'Push: war, poverty, drought, persecution, lack of opportunity. Pull: jobs, family reunification, peace, education, healthcare, freedom. Lee''s model adds intervening obstacles (cost, border controls).', 1, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Distinguish economic, forced and asylum migration.', 'Economic: voluntary for work/quality of life. Forced: displaced by conflict, disaster, persecution. Asylum: legal claim by refugees seeking protection. UNHCR oversees ~110 million displaced (2024).', 2, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define remittances.', 'Money sent home by migrants. Globally ~$650bn/yr (2022) — exceeds FDI to LICs. Major source of income for Philippines (~10% GDP), Tonga (~40%), Tajikistan. Vulnerable to host-country recessions.', 3, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define brain drain.', 'Emigration of skilled workers from LICs/MICs to HICs (doctors, engineers, scientists). Drains source country of investment and capability. Sub-Saharan Africa''s health worker emigration to UK, US is widely studied.', 4, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define a refugee, asylum-seeker, IDP.', 'Refugee: forced to flee country (recognised under 1951 Refugee Convention). Asylum-seeker: claiming refugee status, awaiting decision. IDP (Internally Displaced Person): forced to flee within own country.', 5, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline the European migration crisis (2015-).', 'Over 1 million migrants reached Europe by sea in 2015 (Syrians, Afghans, Iraqis). Triggered EU disagreements: Schengen suspended, Dublin Regulation strained. Greece-Turkey agreement (2016) reduced flows.', 6, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline US-Mexico border migration.', '~200,000 migrants/month at southern border (2024). Push: Central American violence/poverty. Pull: US wages. Trump 2017+ wall, Biden moderation, Trump 2024 deportation plans. Drivers continue despite enforcement.', 7, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define the Schengen Area.', '29 European countries (2024) without border controls between them. Enables free movement of goods, services, capital and labour. Migration crisis (2015) and Covid temporarily reintroduced borders.', 8, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline benefits and costs of migration to host countries.', 'Benefits: filling labour shortages (NHS), demographic balance for ageing societies, cultural enrichment, entrepreneurship. Costs: pressure on services, integration challenges, perceived wage suppression, political backlash.', 9, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline impacts of emigration on source countries.', 'Loss of skilled labour (brain drain), but remittances fund development; return migrants bring skills and capital; demographic changes (sex imbalance, ageing); diaspora networks for trade and investment.', 10, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define environmental migration (climate refugees).', 'Movement triggered by environmental change (drought, sea-level rise, salinisation). Lacks legal recognition. Bangladesh, Pacific atolls especially vulnerable. By 2050, IOM estimates 200 million-1 billion environmental migrants.', 11, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define Gulf migration (kafala system).', 'Gulf states (UAE, Saudi, Qatar) host ~30 million migrant workers — majority of population in some. Kafala (sponsorship) ties workers to employer. Criticised as modern slavery; reforms after Qatar World Cup 2022.', 12, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline Brexit and UK migration.', '2020 ended freedom of movement with EU. Points-based system from 2021 favours skilled workers (>£26,200/yr). Net migration rose to ~700,000 (2023) due to non-EU. Reduced Polish, Romanian; rose Indian, Nigerian.', 13, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define a chain migration.', 'When migrants follow earlier migrants from the same place, drawing on networks for jobs, housing, language support. Creates ethnic clusters. Italian migration to USA in 1880-1910s; Polish to UK post-2004.', 14, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'List four roles of IGOs in migration management.', 'UNHCR (refugees), IOM (migration governance), ILO (worker rights), EU Frontex (border control), UN Compacts on Migration (2018). Coordinate, set standards, provide humanitarian assistance.', 15, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline rural-urban migration in NEEs.', 'Major flows: China''s ''floating population'' ~290 million; India''s urban migrants for construction/services. Drivers: agricultural mechanisation, urban wages, services. Outcomes: megacity growth, slums, remittance flows.', 16, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define second-generation identity.', 'Children of migrants born/raised in destination country. Negotiate dual identities (heritage culture + host country). May experience discrimination, hyphenated identities. Visible in UK British-Asian, French-Maghrebi, US Latino.', 17, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Outline diaspora networks.', 'Migrants and descendants maintaining links to homeland through remittances, return visits, investment, political engagement. Indian (~32 million), Chinese (~50 million), African (~30 million). Soft-power resource for source countries.', 18, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'Define multicultural and assimilationist integration.', 'Multicultural (UK, Canada, Australia): respects/encourages cultural diversity. Assimilationist (France): emphasises adoption of national values, language. Both face debates over identity, cohesion, equality.', 19, 'alevel'),
  ('Geography', 'OCR', '2.3', 'Global Migration', 'List four causes of forced migration.', 'War (Syria, Ukraine, Sudan), persecution (Rohingya in Myanmar), natural disasters, environmental degradation/climate change, economic collapse (Venezuela), political instability.', 20, 'alevel');

-- Topic 2.4 — Human Rights
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define human rights.', 'Universal entitlements regardless of citizenship — life, liberty, freedom from torture, freedom of religion, education, work. Universal Declaration of Human Rights (UDHR, 1948) — non-binding but foundational.', 1, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Distinguish ICCPR and ICESCR.', 'International Covenant on Civil and Political Rights (1966): right to life, fair trial, free expression, vote. International Covenant on Economic, Social and Cultural Rights (1966): work, education, health, adequate standard of living. Both binding on signatories.', 2, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define the ECHR and its role.', 'European Convention on Human Rights (1950). 46 member states. European Court of Human Rights (Strasbourg) hears individual complaints. Influences UK law via Human Rights Act 1998. Subject to political debate.', 3, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define democracy and the Democracy Index.', 'Government by the people via free elections, rule of law, civil liberties. Democracy Index (Economist Intelligence Unit) ranks ~165 countries: full democracy, flawed democracy, hybrid, authoritarian. Trend: democratic recession 2010s-20s.', 4, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define corruption and how it is measured.', 'Abuse of public office for private gain. Transparency International''s Corruption Perceptions Index (CPI) ranks ~180 countries. Weakens institutions, deters investment, distorts public spending — strong negative correlation with HDI.', 5, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define gender inequality and three measures.', 'Systemic disadvantage of one gender. Measures: GII (UN — reproductive health, empowerment, labour market), GGGI (WEF — gender gap index), maternal mortality ratio, female labour force participation.', 6, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline gender-based violence and global patterns.', '~1 in 3 women globally experience physical/sexual violence (WHO). Concentrated where laws are weak, education low, gender norms patriarchal. Femicide, FGM, child marriage, dowry deaths. SDG 5.2 targets elimination by 2030.', 7, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define LGBTQ+ rights and global variation.', 'Rights vary: 30+ countries recognise same-sex marriage; ~70 criminalise same-sex acts (some with death penalty — Iran, Saudi). UDHR Article 2 forbids discrimination. Backlash in Russia, Hungary, Uganda 2023 anti-LGBTQ+ laws.', 8, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define indigenous rights.', 'Rights of original inhabitants (~370 million globally, ~5% population). UN Declaration on the Rights of Indigenous Peoples (UNDRIP, 2007) — self-determination, lands, culture. Threats: extractive industries, deforestation, assimilation.', 9, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define R2P (Responsibility to Protect).', 'A 2005 UN principle: states have responsibility to protect populations from genocide, war crimes, ethnic cleansing, crimes against humanity. International community may intervene if state fails. Invoked in Libya 2011.', 10, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define geopolitical intervention.', 'A state or IGO acting in another state''s affairs — diplomatic pressure, sanctions, peacekeeping, military force. Legitimacy contested: UN Security Council authorisation provides cover but P5 vetoes block action.', 11, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'List four types of international aid.', 'Bilateral (country to country), multilateral (via World Bank, UN), humanitarian/emergency (Red Cross, MSF), tied (conditional on buying donor goods/services), concessional loans, debt relief.', 12, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline strengths and weaknesses of foreign aid.', 'For: relieves poverty, builds capacity, addresses humanitarian crises. Against: dependency, corruption, distorts incentives, ''Dutch disease'' from aid inflows, conditionality may impose poor policy.', 13, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline a successful aid intervention.', 'Bangladesh: BRAC (largest NGO globally), Grameen Bank microfinance, oral rehydration therapy, vaccination — under-5 mortality fell from 240 (1970) to 28 (2024) per 1000 live births.', 14, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline a military humanitarian intervention.', 'Libya 2011: UN Resolution 1973 authorised no-fly zone after Gaddafi threatened civilians. NATO airstrikes helped overthrow regime. Aftermath: state collapse, civil war, migration crisis. Mixed legacy of R2P.', 15, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline UN peacekeeping.', '~75,000 personnel from 120+ countries (2024) deployed to ~12 missions (DRC, S Sudan, Mali). Authorised by Security Council. Limited mandate; struggle with civilian protection in active conflicts (Srebrenica 1995 failure).', 16, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define modern slavery.', 'Exploitation through coercion: bonded labour, human trafficking, forced marriage. ~50 million people globally (ILO 2022). UK Modern Slavery Act 2015 requires large firms to publish supply-chain statements. Most prevalent in fishing, agriculture, garments.', 17, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline post-conflict development challenges.', 'Rebuilding infrastructure, reconciling ethnic divisions, demobilising combatants, restoring rule of law, economic recovery, refugee return, dealing with trauma, addressing root causes (ethnicity, resources).', 18, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Define the SDGs and their relevance to human rights.', '17 Sustainable Development Goals (2015-2030): no poverty, gender equality, peace and justice, reduced inequalities. Anchor human rights in development. Universal — applies to all countries. Progress monitored by UN.', 19, 'alevel'),
  ('Geography', 'OCR', '2.4', 'Human Rights', 'Outline a contrasting human rights case study.', 'Rwanda 1994: genocide ~800,000 Tutsi killed. UN inaction criticised. Now developing country with stable governance but limited political space. Compare with Syria 2011-: 500,000 deaths, R2P invoked but Russian/Chinese vetoes blocked UN action.', 20, 'alevel');

-- Topic 2.5 — Power and Borders
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define a sovereign state.', 'A political entity with a defined territory, permanent population, government and capacity to enter international relations (Montevideo Convention 1933). ~193 UN members; some unrecognised states (Taiwan, Kosovo, Palestine).', 1, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define a nation and a nation-state.', 'Nation: a community sharing identity (culture, language, history). Nation-state: where one nation has its own state. Often blurred — most states are multi-national (UK, India, Nigeria); some nations stateless (Kurds, Palestinians).', 2, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Distinguish hard, soft and smart power (Nye).', 'Hard: coercive — military, economic sanctions. Soft: attractive — culture, ideology, diplomacy (Hollywood, BBC, English language). Smart: blends both. China''s Belt and Road combines investment with strategic positioning.', 3, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define a superpower.', 'A state with ability to project influence globally — military, economic, cultural, political. Currently the US is the sole hyperpower; China is a rising challenger; EU and Russia have regional reach.', 4, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define unipolar, bipolar and multipolar world.', 'Unipolar: one dominant power (post-1989 USA). Bipolar: two rivals (USA-USSR Cold War). Multipolar: several great powers competing (pre-WWI Europe, today USA-China-EU-Russia-India).', 5, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Outline the rise of China.', '~1.4bn population, world''s 2nd largest economy by GDP, largest by PPP. Strategy: export-led growth, manufacturing base, infrastructure (BRI), military modernisation, tech rivalry, S China Sea claims.', 6, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define the BRICS+ group.', 'Brazil, Russia, India, China, South Africa formed in 2009; expanded 2024 with Iran, UAE, Egypt, Ethiopia. Counter-balance to G7 economic governance. Goal: influence in IMF/World Bank, alternative payments, dedollarisation.', 7, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define IGOs and list four examples.', 'Intergovernmental Organisations: UN, NATO, IMF, World Bank, WTO, WHO, OECD, OPEC. Pool sovereignty for collective action; superpowers often dominate (US in IMF, China in BRICS-affiliated NDB).', 8, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Outline the Belt and Road Initiative.', 'China''s ~$1tn (since 2013) infrastructure programme (ports, rail, energy) across ~150 countries. Aims to revive Silk Road trade, expand Chinese influence, secure resources. Critics: ''debt trap diplomacy''.', 9, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Why is the South China Sea geopolitically significant?', '~$3.4tn trade passes annually. Rich fisheries, oil/gas. China claims Nine-Dash Line; rejected by 2016 PCA ruling. US ''freedom of navigation'' patrols; ASEAN states (Vietnam, Philippines) push back.', 10, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Outline the Russia-Ukraine war.', '2022 invasion broke European post-1945 order. NATO unity strengthened (Finland, Sweden joined 2023-24). Energy weaponised. Sanctions on Russia. China-Russia ''no-limits'' partnership but China cautious. War remains stalemated.', 11, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define a contested border with example.', 'Disputed territorial boundary. Kashmir (India-Pakistan since 1947, three wars), Western Sahara (Morocco-Polisario), Crimea (Russia-Ukraine 2014, 2022), Israel-Palestine, Taiwan Strait, Korean DMZ.', 12, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define secessionism with example.', 'Movement to break away from a state. Catalonia (Spain — 2017 independence referendum declared unconstitutional), Scotland (UK — 2014 referendum 55% No), South Sudan (succeeded 2011, separated from Sudan).', 13, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Outline the Arctic geopolitical contest.', 'Melting sea ice opens shipping routes (NSR through Russia) and resource access (oil, gas). 8 Arctic Council states. Russia militarising; NATO members (US, Canada, Norway) responding. Climate change driving competition.', 14, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define neo-colonialism.', 'When former colonial powers (or new powers) maintain economic/political dominance over former colonies through trade, aid conditionality, FDI, military bases. France in francophone Africa; China in resource-extraction in DRC.', 15, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Outline the Israel-Palestine conflict.', 'Disputed territory since 1948. 1967 War — Israeli occupation of West Bank, Gaza, East Jerusalem. Two-state solution stalled. October 2023 Hamas attack and Gaza war intensified humanitarian crisis. ICJ genocide hearing 2024.', 16, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'List three challenges to US hegemony.', 'Rise of China, Russia revisionism, fragmenting alliance system, debt and political polarisation, populism, climate change, technology rivalry (AI, semiconductors), de-dollarisation moves.', 17, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Outline India as an emerging power.', '~1.4bn population, 5th-largest economy by GDP. ''Demographic dividend'' (median age 28). Tech and services hub; nuclear-armed; neutral-ish in Russia-Ukraine. Member of QUAD (with US, Japan, Australia) — strategic counter to China.', 18, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define climate diplomacy.', 'Use of climate negotiations as foreign policy. UNFCCC/COP process; small island states (AOSIS) press for 1.5°C; superpowers trade emissions cuts for technology transfers. China-US bilateral track key to Paris Agreement (2015).', 19, 'alevel'),
  ('Geography', 'OCR', '2.5', 'Power and Borders', 'Define geopolitical fragmentation.', 'Decline in international cooperation, rise of regional/national blocs. Trade decoupling, technology rivalry, security alliances (QUAD, AUKUS), challenges to UN Security Council legitimacy. Threatens collective action on global issues.', 20, 'alevel');
