-- A-Level Geography Flashcards (Eduqas)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- EDUQAS A-LEVEL
-- ===============================================================

-- Topic 1.1 — Coastal Landscapes
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Define a sediment cell.', 'A largely self-contained coastal section with sources, transfers and sinks of sediment between fixed boundaries (usually headlands). England and Wales are divided into 11 cells.', 1, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Distinguish constructive and destructive waves.', 'Constructive: low height, long wavelength, low frequency (6-8/min), strong swash, weak backwash, builds beaches. Destructive: tall, short wavelength, frequent (10-14/min), weak swash, strong backwash, removes sediment.', 2, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Name four wave-driven erosional processes.', 'Hydraulic action (waves compress air in cracks), abrasion (sediment scours), attrition (rocks knock together, become rounder), corrosion/solution (chemical dissolving — limestone, chalk).', 3, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Describe longshore drift.', 'Sediment is moved along a coast in a zigzag pattern: swash carries material up the beach in the prevailing wind direction; backwash returns it perpendicular to shoreline. Net result: lateral transport. <svg viewBox="0 0 260 130" width="260" height="130" style="display:block;margin:6px auto"><rect x="0" y="60" width="260" height="70" fill="#F2D9A5"/><line x1="0" y1="60" x2="260" y2="60" stroke="#0B1E3F" stroke-width="1.2"/><path d="M20 100 L60 70" stroke="#0B1E3F" marker-end="url(#c1)"/><path d="M60 70 L80 100" stroke="#0B1E3F" marker-end="url(#c1)" stroke-dasharray="2 2"/><path d="M80 100 L120 70" stroke="#0B1E3F" marker-end="url(#c1)"/><path d="M120 70 L140 100" stroke="#0B1E3F" marker-end="url(#c1)" stroke-dasharray="2 2"/><path d="M140 100 L180 70" stroke="#0B1E3F" marker-end="url(#c1)"/><path d="M40 30 L80 30" stroke="#B00020" marker-end="url(#c2)"/><text x="60" y="22" font-size="8" fill="#B00020" text-anchor="middle">prevailing wind</text><defs><marker id="c1" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker><marker id="c2" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#B00020"/></marker></defs></svg>', 4, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Outline the formation of a wave-cut platform.', 'Waves erode a notch at the high-water mark; cliff above is undercut and collapses; cliff retreats inland leaving a flat rocky platform at low tide. Continued retreat creates wider platforms.', 5, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Outline the headland-bay-cave-arch-stack sequence.', 'Differential erosion of soft and hard rock creates headlands and bays. Headlands attacked from sides: cracks → caves → caves meet (arch) → arch collapses (stack) → stack erodes (stump). Old Harry Rocks, Dorset.', 6, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'How do beaches form and what controls their profile?', 'Beaches form where constructive waves deposit sediment in sheltered bays/lower-energy stretches. Profile depends on sediment size (steeper for shingle, gentler for sand), wave energy, and tidal range.', 7, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Outline the formation of a spit and a bar.', 'Spit: longshore drift transports sediment past a change in coastline orientation; sediment accumulates and may recurve. Bar: spit grows across a bay enclosing a lagoon. Examples: Spurn Head spit; Slapton Sands bar (Devon).', 8, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Distinguish concordant and discordant coasts.', 'Concordant: rock layers parallel to coast (Lulworth Cove, Dorset). Discordant: layers perpendicular, headlands and bays form (Swanage, Dorset). Reflects geology and erosional differentials.', 9, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Distinguish eustatic and isostatic sea-level change.', 'Eustatic: global change in volume of seawater (ice melt, thermal expansion). Isostatic: local change in land level (glacial rebound, subsidence). Together produce relative sea-level change.', 10, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Distinguish emergent and submergent landforms.', 'Emergent (sea fell or land rose): raised beaches, fossil cliffs. Submergent (sea rose or land fell): rias (drowned river valleys), fjords (drowned glacial valleys), Dalmatian coasts.', 11, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'List four hard-engineering coastal defences and one drawback each.', 'Sea wall (expensive, ugly), groynes (starve down-drift coast), rock armour/rip-rap (visual impact), revetment (costly maintenance), gabions (rust over time). Defer rather than solve.', 12, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'List four soft-engineering coastal defences.', 'Beach nourishment, dune regeneration (planting marram grass), managed retreat/coastal realignment, salt-marsh restoration, planning controls. Cheaper, more sustainable, but slower-acting.', 13, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Define Shoreline Management Plans (SMPs).', 'UK strategic plans for coastal stretches: hold the line, advance the line, managed retreat, or no active intervention. Reviewed every 5-10 years and balance economic, social and environmental factors.', 14, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Outline the Holderness coastline.', 'East Yorkshire — fastest eroding coast in Europe (~1.8 m/yr). Boulder clay cliffs, North Sea fetch, longshore drift south. Mappleton groynes (1991) protected village but accelerated erosion at Cowden.', 15, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'How is climate change altering coasts?', 'Sea-level rise (eustatic + thermal expansion) drowns low-lying coasts; more storms increase erosion; ocean acidification damages coral; warmer oceans bleach reefs; permafrost thaw weakens Arctic coasts.', 16, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Outline the formation of sand dunes.', 'Onshore winds blow dry beach sand inland; embryo dunes form around obstacles; pioneer species stabilise (sea couch, marram); succession continues to fixed dunes; finally heath/woodland on dune slack. Studland, Dorset.', 17, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Define a salt marsh and its formation.', 'Vegetated tidal mudflat in sheltered low-energy environments (estuaries, behind spits). Forms by deposition of fine sediments stabilised by halophytes (Spartina, Salicornia). Stores carbon; buffers storms; nurses fish.', 18, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Why are mangroves important?', 'Salt-tolerant trees in tropical/sub-tropical inter-tidal zones. Stilt roots absorb wave energy (~70% reduction). Sequester ~3-5x more carbon per hectare than tropical forest. Threatened by aquaculture and coastal development.', 19, 'alevel'),
  ('Geography', 'Eduqas', '1.1', 'Coastal Landscapes', 'Outline a coral reef as a tropical coastal ecosystem under threat.', 'Great Barrier Reef: warming triggers mass bleaching events (1998, 2002, 2016, 2017, 2020, 2022), acidification slows calcification, agricultural runoff causes COTS outbreaks. Resilience falls; recovery slows.', 20, 'alevel');

-- Topic 1.2 — Glaciated Landscapes
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define glacial systems and key processes.', 'Open systems with inputs (snowfall, avalanches), stores (ice, meltwater) and outputs (meltwater discharge, calving). Processes: plucking (ice freezes onto bedrock and plucks blocks), abrasion (rock fragments scour bedrock), freeze-thaw weathering.', 1, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Distinguish polar and temperate glaciers.', 'Polar (cold-based): below freezing, frozen to bedrock, slow movement, little erosion (Antarctic). Temperate (warm-based): meltwater at base, faster basal sliding, more erosion (Alpine, NZ Southern Alps).', 2, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define the glacier mass balance.', 'Difference between accumulation (snow gain in winter, above firn line) and ablation (melt loss in summer, below firn line). Positive: glacier advances; negative: retreats. Most glaciers globally have negative balance from climate change.', 3, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline freeze-thaw weathering.', 'Water enters cracks in rock; freezing expands by ~9%, widening cracks; repeated cycles fracture rock into angular fragments. Most active where temperatures oscillate around 0°C (frost-shattered scree slopes).', 4, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline the formation of a corrie.', 'Snow accumulates in a north-facing hollow, compresses to firn then ice. Plucking and abrasion deepen the hollow; rotational movement scoops it into an armchair shape. After deglaciation, a tarn (lake) often fills it.', 5, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Distinguish arête and pyramidal peak.', 'Arête: knife-edged ridge between two corries (Striding Edge, Lake District). Pyramidal peak: where three or more corries erode back-to-back (Matterhorn, Snowdon).', 6, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline the formation of a U-shaped (glacial trough) valley.', 'A pre-existing V-shaped river valley is widened, deepened and straightened by glacier ice. Truncated spurs replace interlocking ones. After deglaciation: misfit stream, sometimes ribbon lakes (Wastwater).', 7, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define a hanging valley with example.', 'A small tributary glacier valley left high above the main trough after deglaciation. Streams drop over the lip as waterfalls (Yosemite Bridalveil Falls, Tieve Bulliagh in Lake District).', 8, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Distinguish drumlin, esker and erratic.', 'Drumlin: streamlined hill of glacial till. Esker: sinuous ridge of fluvio-glacial sand and gravel (deposited by sub-glacial stream). Erratic: large rock transported far from origin (Norber erratics, Yorkshire).', 9, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define a moraine and list types.', 'Glacially transported and deposited debris. Lateral (along glacier sides), medial (where two glaciers meet), terminal (at glacier snout, marks furthest extent), recessional (during retreat pauses), ground (under ice).', 10, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define periglacial environments.', 'Cold non-glaciated regions (~25% of Earth''s land surface) with permafrost and active-layer freeze-thaw. Found in tundra, sub-Arctic. Distinct from glaciated by absence of ice cover.', 11, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define permafrost and active layer.', 'Permafrost: ground at 0°C or below for >2 consecutive years. Active layer: surface that thaws each summer. Continuous: ~80%+ frozen ground. Discontinuous: 50-80%. Sporadic: <50%. Climate change is thawing both.', 12, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline three periglacial landforms.', 'Patterned ground (frost sorting forms polygons/circles), pingos (ice-cored hills, e.g. Tuktoyaktuk Canada), solifluction lobes (downslope flow of saturated active layer), thermokarst (subsidence as ice thaws).', 13, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline pressures on a glaciated environment (Alps).', 'Tourism (~120 million annual visits to Alps), winter sports (ski lifts, pistes), hydroelectricity, climate change (Aletsch glacier retreating ~50 m/yr), threats from glacial lake outburst floods (GLOFs).', 14, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline pressures on a glaciated environment (Antarctica).', 'Climate change accelerates ice loss; tourism (~70,000 cruise visitors/yr) leaves footprint; mineral exploration interest. Antarctic Treaty (1961) suspends territorial claims and bans mining; Madrid Protocol (1991) extended.', 15, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'List four impacts of glacier retreat.', 'Sea-level rise, water security in dry-season meltwater (Andean cities, South Asian rivers), GLOFs threatening downstream villages, biodiversity loss, regional economic disruption (skiing).', 16, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define a tipping point in cryosphere.', 'A threshold beyond which change becomes self-reinforcing and irreversible on human timescales. Examples: Greenland ice sheet melt (~1.5°C trigger?), West Antarctic Ice Sheet collapse, permafrost CH4 release.', 17, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Why is the Arctic warming faster than the global average?', 'Polar amplification: ice-albedo feedback (less ice -> more absorbed solar -> more melt). Atmospheric circulation. Heat transported by ocean currents. Arctic warming ~3-4× global rate.', 18, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Outline glacial period climate evidence.', 'Pleistocene cycles ~100,000 yr. Evidence: ice cores (CO2 trapped bubbles), oxygen isotope ratios in foraminifera, pollen records, glacial erratics, dendrochronology, U-shaped valleys far from current ice.', 19, 'alevel'),
  ('Geography', 'Eduqas', '1.2', 'Glaciated Landscapes', 'Define Milankovitch cycles.', 'Variations in Earth''s orbit influencing solar input over tens to hundreds of thousands of years. Eccentricity (100,000 yr), obliquity (41,000 yr), precession (26,000 yr). Drives Pleistocene glacial-interglacial cycles.', 20, 'alevel');

-- Topic 1.3 — Changing Places
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Distinguish space, place and locale.', 'Space: an area defined by coordinates. Place: space invested with meaning by people (Tuan). Locale: setting in which everyday life happens (Agnew). Place is therefore relational and dynamic.', 1, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define endogenous and exogenous factors.', 'Endogenous (internal): physical geography, demography, land use, economy, built environment, history. Exogenous (external): connections to other places, migration, capital flows, government policy, globalisation.', 2, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define topophilia and topophobia.', 'Topophilia (Tuan, 1974): the affective bond between people and place — love of place. Topophobia: fear or dislike of place — common in places associated with crime, decay, traumatic memory.', 3, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Distinguish insider and outsider perspectives.', 'Insider: born or long-resident, share traditions, language, networks; place-attached. Outsider: temporary or unfamiliar; may romanticise or stereotype. Status fluid.', 4, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'How does the IMD measure deprivation?', 'UK Index of Multiple Deprivation combines seven domains: income, employment, education, health, crime, housing, living environment. Areas ranked into deciles. Allows place-by-place comparison of need.', 5, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Outline gentrification with one named example.', 'In-migration of higher-income residents into a previously low-income area, refurbishing housing and changing local amenities. Displaces original residents through rising rents. Examples: Notting Hill, Brixton, Hackney, Brooklyn.', 6, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Outline an urban regeneration scheme (London Docklands).', '1981 LDDC established. £8.7bn investment by 1998. Canary Wharf, DLR, City Airport. 80,000+ jobs. Critique: original communities largely excluded; gentrification displaced low-income residents.', 7, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Outline a rural rebranding strategy with example.', 'Rebranding aims to attract visitors/investors. Cornwall: Eden Project (£2bn local economic impact since 2001), Hall for Cornwall, food/drink tourism. Trade-offs: housing affordability for locals.', 8, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define rural-urban continuum.', 'Spectrum from deep countryside through accessible rural, suburb, inner suburb, inner city. Pace of life, density, services, demographic profile vary along it. Boundaries blur as commuter belts extend.', 9, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Outline counter-urbanisation drivers.', 'Improved transport/IT (commute, remote work), perception of better quality of life (lower crime, cleaner air, schools), housing affordability, retirement. Covid-19 accelerated UK ''race for space''.', 10, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define ethnic enclave.', 'A neighbourhood with high concentration of one ethnic group. Reasons: chain migration, mutual support, language/cultural amenities, discrimination in housing markets. Examples: Tower Hamlets (Bangladeshi), Brixton (Caribbean).', 11, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'List four ways place is represented.', 'Statistics (census, IMD), films, novels, paintings, photographs, music, postcards, tourist boards, news media, social media (#hashtags create new place identities).', 12, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define lived experience and methods to access it.', 'Everyday meanings of a place to its residents. Accessed through ethnography, interviews, oral histories, participant observation, mental maps, photo elicitation — qualitative methods that surface what statistics cannot.', 13, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'How does globalisation affect place identity?', 'Increases similarity (clone towns, McDonaldisation), but also enables cultural hybridity. Some places resist (CittaSlow, fair-trade towns); others rebrand to compete in global tourism/investment markets.', 14, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define resilience of place.', 'A place''s ability to absorb shocks (flooding, deindustrialisation, pandemics) and adapt. Drivers: economic diversity, social capital, governance, infrastructure. Detroit struggled; Pittsburgh transitioned to ''eds and meds''.', 15, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Outline how power shapes place.', 'Local authorities, developers and capital decide which places get investment. Power asymmetries displace less powerful (low-income, ethnic minorities). Resistance: campaigns (Save Latin Village, Tottenham), community land trusts, rent controls.', 16, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define place-meaning and place-identity.', 'Place-meaning: subjective values and emotions attached to place by individuals/groups. Place-identity: sense of self constructed through belonging to place (national, regional, neighbourhood).', 17, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Outline community-led place-making.', 'Local residents shape their place through neighbourhood plans, community land trusts, public art, festivals, restoration projects. Examples: Hackney Wick, Granby Four Streets (Liverpool, Turner Prize 2015).', 18, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Define ''place is socially constructed''.', 'Place meaning is created through human practice, language and representation rather than fixed by physical geography. The same physical site can be ''heritage,'' ''slum,'' ''opportunity'' or ''problem'' depending on who narrates it.', 19, 'alevel'),
  ('Geography', 'Eduqas', '1.3', 'Changing Places', 'Compare a contrasting place study.', 'Choose two places (e.g. local urban + rural area), compare endogenous and exogenous factors, demographic and economic profiles, representations, lived experiences and management strategies — Eduqas core skill.', 20, 'alevel');

-- Topic 2.1 — Water Cycle and Water Insecurity
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'List the four major stores of the global water cycle.', 'Oceans (~97%), cryosphere/ice (~2%), groundwater (~0.7%), surface water and atmosphere (<0.1%). Lithosphere holds tiny amounts in rocks.', 1, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Sketch the global water cycle.', 'Solar energy drives evaporation from oceans, vegetation transpires, vapour rises and condenses, precipitates over land/oceans; runoff and groundwater return to sea. <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><rect x="0" y="120" width="260" height="40" fill="#9CC3E5"/><polygon points="120,120 200,120 220,80 130,80" fill="#A8D08D"/><circle cx="60" cy="35" r="12" fill="#E7E6E6"/><circle cx="180" cy="30" r="14" fill="#E7E6E6"/><path d="M40 110 Q40 80 60 50" stroke="#0B1E3F" fill="none" marker-end="url(#c3)"/><path d="M150 90 Q150 70 170 45" stroke="#0B1E3F" fill="none" marker-end="url(#c3)"/><path d="M210 50 Q220 80 220 110" stroke="#0B1E3F" fill="none" marker-end="url(#c3)"/><defs><marker id="c3" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs><text x="20" y="80" font-size="8" fill="#0B1E3F">evap</text><text x="125" y="65" font-size="8" fill="#0B1E3F">transp</text><text x="220" y="80" font-size="8" fill="#0B1E3F">precip</text></svg>', 2, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Define a drainage basin.', 'Area of land drained by a river and its tributaries. Watershed: high-ground boundary. Source: where the river begins. Mouth: where it enters the sea. Confluence: junction of two streams.', 3, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Sketch the drainage basin (inputs, stores, flows, outputs).', 'Input: precipitation. Stores: interception, surface, soil moisture, groundwater, channel. Flows: surface runoff, throughflow, infiltration, percolation, baseflow. Outputs: evaporation, transpiration, channel discharge.', 4, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Define a storm hydrograph.', 'A graph of river discharge against time after a storm. Lag time: gap between peak rainfall and peak discharge. Steeper rising limb / shorter lag indicate flashier basin (urbanised, impermeable, steep, saturated).', 5, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Define the water budget.', 'Balance of precipitation and potential evapotranspiration. Surplus (P > PET) recharges soil. Deficit (PET > P) uses up soil moisture, plants stressed. Recharge in autumn, deficit through summer.', 6, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Define water scarcity and water stress.', 'Water stress: <1700 m3 per person per year. Water scarcity: <1000 m3. Absolute scarcity: <500 m3. Causes: physical (low rainfall) or economic (lack of infrastructure). Affects ~2 billion people.', 7, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Distinguish blue, green and grey water.', 'Blue: liquid surface and groundwater. Green: rainwater stored in soil, used by plants. Grey: wastewater volume needed to dilute pollution to safe levels.', 8, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'How does climate change affect the water cycle?', 'Warmer air holds more moisture (~7%/°C, Clausius-Clapeyron); intensifies extreme rainfall and droughts; expands subtropical dry zones; shifts seasonal precipitation; shrinks glaciers, threatening dry-season flow.', 9, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'How does deforestation affect the water cycle?', 'Reduces interception and transpiration. Increases overland flow and erosion. Lowers regional rainfall (Amazon ''flying rivers''). Raises temperatures locally through reduced evapotranspiration cooling.', 10, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Outline the Aral Sea disaster.', 'Soviet 1960s diversion of Amu/Syr Darya for cotton irrigation; Aral lost ~90% volume by 2010. Consequences: collapse of fisheries, salinised soils, dust storms, public health crisis, lost climate-moderating effect.', 11, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Define a transboundary water resource.', 'A water source crossing borders, requiring cooperation. Examples: Nile (Egypt-Sudan-Ethiopia GERD dispute), Mekong (six countries), Indus Waters Treaty (India-Pakistan, 1960 — survived three wars).', 12, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'List four hard-engineering water management strategies.', 'Mega-dams (Three Gorges, China), reservoirs, water transfer schemes (South-North China), desalination plants (Israel, Saudi Arabia). Capital-intensive; environmental and social impacts.', 13, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'List four sustainable water strategies.', 'Drip irrigation, recycling/reuse (Singapore NEWater), rainwater harvesting, demand management/metering, restoring wetlands, integrated catchment management, dual-flush toilets.', 14, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Define an aquifer and its importance.', 'A permeable rock layer (often porous sandstone or jointed limestone/chalk) saturated with groundwater. Recharged slowly by percolation. Over-abstraction lowers water tables and risks salinisation in coastal areas.', 15, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'List four physical and four human factors affecting flood risk.', 'Physical: heavy/prolonged rainfall, snowmelt, impermeable rock, steep relief, antecedent saturation. Human: urbanisation, deforestation, channel modification, climate change.', 16, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Outline integrated drainage basin management.', 'Coordinated stewardship across all catchment users (farms, cities, ecology). UK Catchment-Based Approach. Targets quality (WFD), supply, flooding, biodiversity. Requires governance and stakeholder buy-in.', 17, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'How does water pricing affect demand?', 'Pricing reflects scarcity, encouraging efficiency. Tiered tariffs make large users pay more. Risks: regressive impact on low-income users; need for safety net (essential allocation, social tariffs).', 18, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'Explain how a Mediterranean climate creates seasonal water stress.', 'Hot dry summer (subtropical high) coincides with peak demand (irrigation, tourism, AC). Wet mild winter recharges aquifers. Causes summer droughts; high abstraction risks salinisation in coastal aquifers (Spain, California).', 19, 'alevel'),
  ('Geography', 'Eduqas', '2.1', 'Water Cycle and Water Insecurity', 'How does water scarcity link to conflict?', 'Disputes over shared resources can escalate (Israel-Palestine West Bank aquifer; Tigris-Euphrates between Turkey, Syria, Iraq). Often water sits within wider political tensions; cooperation is more common than ''water wars''.', 20, 'alevel');

-- Topic 2.2 — Carbon Cycle and Energy Security
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'List the four major stores of the global carbon cycle.', 'Lithosphere (sedimentary rocks, fossil fuels — by far largest), oceans (dissolved CO2, biological), terrestrial biosphere (vegetation, soils), atmosphere (CO2, CH4 — smallest but climate-critical).', 1, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Distinguish fast and slow carbon cycles.', 'Fast: photosynthesis, respiration, decomposition, ocean exchange — operates over days to centuries. Slow: weathering of silicates, sedimentation, volcanism — operates over millions of years.', 2, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline the ocean carbon pumps.', 'Physical (solubility) pump: cold polar water dissolves CO2, sinks, locks C in deep ocean for centuries. Biological pump: phytoplankton photosynthesise; dead matter sinks (''marine snow'') sequestering C in sediments.', 3, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'How are land-use change and farming affecting the carbon cycle?', 'Deforestation releases stored C and reduces sinks. Ploughing exposes/oxidises soil organic matter. Drainage of peatlands releases CO2. Livestock and rice paddies emit methane.', 4, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Define energy security.', 'Reliable access to energy at affordable prices. Components: availability, accessibility, affordability, acceptability (low environmental and social cost). Threatened by import dependence, conflict, depletion.', 5, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'List the components of the energy mix.', 'Coal, oil, natural gas (fossil), nuclear, hydro, wind, solar, biomass/biofuel, geothermal, tidal/wave. Mix varies by country: France ~70% nuclear, Norway ~95% hydro, Saudi Arabia oil-dominant.', 6, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Define peak oil and Hubbert''s curve.', 'Peak oil: point of maximum extraction, after which production declines. Hubbert''s 1956 prediction of US peak in ~1970 was broadly correct (until shale revolution from 2008 reopened US production).', 7, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Distinguish unconventional and conventional fossil fuels.', 'Conventional: vertically drilled, naturally pooled, easily extracted. Unconventional: shale gas/oil (fracking), tar sands, deep-water, Arctic — higher cost, more environmental impact.', 8, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline the renewable energy transition.', 'Global renewable share rose from ~20% (2010) to ~30% (2024) of electricity. Solar PV cost ~90% lower since 2010. Wind, solar dominate new capacity. Challenges: intermittency, storage, grid upgrades, mineral demand.', 9, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline the geopolitics of energy in Russia/Ukraine.', 'Russia supplied ~40% of EU gas pre-2022. Invasion of Ukraine triggered EU diversification (Norwegian gas, US LNG, accelerated renewables, restart of coal). Energy weaponised; Nord Stream sabotaged.', 10, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline OPEC and its role.', 'Organization of Petroleum Exporting Countries (1960). Coordinates oil production policy among 13 members; OPEC+ adds Russia and others. Aims to stabilise prices and revenue. Production cuts in 2023-24 supported prices.', 11, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'List four impacts of fossil fuel extraction.', 'Air pollution and emissions, water contamination (fracking), oil spills, habitat destruction, induced seismicity, geopolitical conflict, methane leakage, social disruption.', 12, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'List four climate change impacts.', 'Sea-level rise (~3.4 mm/yr), Arctic ice loss, more extreme weather, ocean acidification (pH ~8.2 → 8.1), shifts in species ranges, glacier retreat, permafrost thaw, agricultural disruption.', 13, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'List four positive feedbacks accelerating climate change.', 'Ice-albedo (less ice -> more absorbed solar), permafrost thaw releasing CH4, forest dieback releasing C, ocean warming reducing CO2 solubility, slowed thermohaline circulation.', 14, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline mitigation strategies for climate change.', 'Cut emissions: renewables, EVs, energy efficiency, low-carbon heating, food system change. Carbon capture and storage. Afforestation. Reduce deforestation (REDD+). International agreements (Paris 2015).', 15, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline adaptation strategies for climate change.', 'Sea defences and coastal realignment, drought-resistant crops, water resource planning, urban cooling (green roofs, white surfaces), early warning systems, shifting agricultural zones, redesigned infrastructure.', 16, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Define the Paris Agreement (2015).', 'A UNFCCC treaty signed by ~196 parties. Aims to limit warming to ''well below 2°C'' above pre-industrial, pursuing 1.5°C. Each country sets Nationally Determined Contributions (NDCs), reviewed every 5 years.', 17, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Why is the Amazon a critical carbon sink?', 'Stores ~150-200 Pg C in biomass and soils. Transpires huge water vapour driving regional rainfall. Deforestation reduces both the carbon sink and the moisture flux, risking ''dieback'' tipping points.', 18, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Define the carbon budget.', 'Cumulative CO2 emissions consistent with limiting warming to a temperature target (e.g. 1.5°C). IPCC AR6: remaining budget ~400 Gt CO2 from 2020 for 50% chance of 1.5°C — at current rates ~10 years.', 19, 'alevel'),
  ('Geography', 'Eduqas', '2.2', 'Carbon Cycle and Energy Security', 'Outline carbon capture and storage (CCS).', 'Capture CO2 at industrial sources or directly from air, transport via pipeline, inject into geological formations (depleted oil fields, saline aquifers). Sleipner Norway storing ~1 Mt/yr since 1996. Cost remains high.', 20, 'alevel');

-- Topic 2.3 — Global Migration
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define migration push and pull factors.', 'Push: war, poverty, drought, persecution, lack of opportunity. Pull: jobs, family reunification, peace, education, healthcare, freedom. Lee''s model adds intervening obstacles (cost, border controls).', 1, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Distinguish economic, forced and asylum migration.', 'Economic: voluntary for work/quality of life. Forced: displaced by conflict, disaster, persecution. Asylum: legal claim by refugees seeking protection. UNHCR oversees ~110 million displaced (2024).', 2, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define remittances and importance.', 'Money sent home by migrants. Globally ~$650bn/yr (2022) — exceeds FDI to LICs. Major source of income for Philippines (~10% GDP), Tonga (~40%), Tajikistan. Vulnerable to host-country recessions.', 3, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define brain drain.', 'Emigration of skilled workers from LICs/MICs to HICs (doctors, engineers, scientists). Drains source country of investment and capability. Sub-Saharan Africa''s health worker emigration to UK, US is widely studied.', 4, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'List four causes of forced migration.', 'War (Syria, Ukraine, Sudan), persecution (Rohingya in Myanmar), natural disasters, environmental degradation/climate change, economic collapse (Venezuela), political instability.', 5, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define a refugee, asylum-seeker, IDP.', 'Refugee: forced to flee country (recognised under 1951 Refugee Convention). Asylum-seeker: claiming refugee status, awaiting decision. IDP (Internally Displaced Person): forced to flee within own country.', 6, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline the European migration crisis (2015-).', 'Over 1 million migrants reached Europe by sea in 2015 (Syrians, Afghans, Iraqis). Triggered EU disagreements: Schengen suspended, Dublin Regulation strained. Greece-Turkey agreement (2016) reduced flows.', 7, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline US-Mexico border migration.', '~200,000 migrants/month at southern border (2024). Push: Central American violence/poverty. Pull: US wages. Trump 2017+ wall, Biden moderation, Trump 2024 deportation plans. Drivers continue despite enforcement.', 8, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define the Schengen Area.', '29 European countries (2024) without border controls between them. Enables free movement of goods, services, capital and labour. Migration crisis (2015) and Covid temporarily reintroduced borders.', 9, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline benefits and costs of migration to host countries.', 'Benefits: filling labour shortages (NHS), demographic balance for ageing societies, cultural enrichment, entrepreneurship. Costs: pressure on services, integration challenges, perceived wage suppression, political backlash.', 10, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline impacts of emigration on source countries.', 'Loss of skilled labour (brain drain), but remittances fund development; return migrants bring skills and capital; demographic changes (sex imbalance, ageing); diaspora networks for trade and investment.', 11, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define environmental migration (climate refugees).', 'Movement triggered by environmental change (drought, sea-level rise, salinisation). Lacks legal recognition. Bangladesh, Pacific atolls especially vulnerable. By 2050, IOM estimates 200 million-1 billion environmental migrants.', 12, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define Gulf migration (kafala system).', 'Gulf states (UAE, Saudi, Qatar) host ~30 million migrant workers — majority of population in some. Kafala (sponsorship) ties workers to employer. Criticised as modern slavery; reforms after Qatar World Cup 2022.', 13, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline Brexit and UK migration.', '2020 ended freedom of movement with EU. Points-based system from 2021 favours skilled workers (>£26,200/yr). Net migration rose to ~700,000 (2023) due to non-EU. Reduced Polish, Romanian; rose Indian, Nigerian.', 14, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define a chain migration.', 'When migrants follow earlier migrants from the same place, drawing on networks for jobs, housing, language support. Creates ethnic clusters. Italian migration to USA in 1880-1910s; Polish to UK post-2004.', 15, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'List four roles of IGOs in migration management.', 'UNHCR (refugees), IOM (migration governance), ILO (worker rights), EU Frontex (border control), UN Compacts on Migration (2018). Coordinate, set standards, provide humanitarian assistance.', 16, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline rural-urban migration in NEEs.', 'Major flows: China''s ''floating population'' ~290 million; India''s urban migrants for construction/services. Drivers: agricultural mechanisation, urban wages, services. Outcomes: megacity growth, slums, remittance flows.', 17, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define second-generation identity.', 'Children of migrants born/raised in destination country. Negotiate dual identities (heritage culture + host country). May experience discrimination, hyphenated identities. Visible in UK British-Asian, French-Maghrebi, US Latino communities.', 18, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Outline diaspora networks.', 'Migrants and descendants maintaining links to homeland through remittances, return visits, investment, political engagement. Indian (~32 million), Chinese (~50 million), African (~30 million). Soft-power resource for source countries.', 19, 'alevel'),
  ('Geography', 'Eduqas', '2.3', 'Global Migration', 'Define multicultural and assimilationist integration models.', 'Multicultural (UK, Canada, Australia): respects/encourages cultural diversity. Assimilationist (France): emphasises adoption of national values, language. Both face debates over identity, cohesion, equality.', 20, 'alevel');

-- Topic 2.4 — Global Governance of Oceans
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Why are oceans considered global commons?', '~71% of Earth''s surface, beyond any single state''s jurisdiction. International waters and the high seas covered by UNCLOS. ''Commons'' need international governance; risk of free-rider tragedy.', 1, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define UNCLOS.', 'United Nations Convention on the Law of the Sea (1982, in force 1994). Defines maritime zones: territorial waters (12 nm), EEZ (200 nm), continental shelf, high seas. 168 parties; US has not ratified.', 2, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define an Exclusive Economic Zone (EEZ).', 'Sea zone extending 200 nautical miles from a state''s baseline, in which the coastal state has exclusive rights to natural resources (fisheries, minerals). Beyond the EEZ is the high seas (international waters).', 3, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline the ocean conveyor (thermohaline circulation).', 'Global ocean circulation driven by temperature and salinity differences. Cold dense water sinks at North Atlantic and Antarctic (deepwater formation), flows along the seabed, upwells in Indian/Pacific. Distributes heat globally.', 4, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'List four ecosystem services of the oceans.', 'Climate regulation (heat and CO2 absorption), oxygen production (~50% from phytoplankton), food (fisheries), transport (~80% global trade by volume), recreation, biodiversity, cultural value.', 5, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'List four ocean threats.', 'Overfishing (~34% of stocks unsustainable), plastic pollution (~8 Mt/yr enters), ocean acidification, deoxygenation/dead zones, coral bleaching, oil spills, eutrophication, invasive species.', 6, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define overfishing.', 'Catching fish faster than stocks can reproduce. ~34% of marine stocks fished beyond sustainable yield (FAO). Causes: subsidies, IUU fishing, technology efficiency. Solutions: quotas (ITQs), MPAs, monitoring (Global Fishing Watch).', 7, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline the EU Common Fisheries Policy (CFP).', 'Manages EU fishing through Total Allowable Catches (TACs) and quotas, technical measures, fleet capacity limits. Reformed 2013 to reduce discards. Brexit removed UK from CFP; new annual UK-EU negotiations.', 8, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define a Marine Protected Area (MPA).', 'Sea area designated for conservation. Ranges from no-take zones (full protection) to multi-use. ~8% of ocean is MPA; UN aims for 30% by 2030 (30x30). Examples: Great Barrier Reef Marine Park.', 9, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline ocean plastic pollution.', '~8 Mt enters ocean annually. ~80% from land-based sources. Microplastics in marine food chains, including human seafood. Great Pacific Garbage Patch ~1.6 million km2. Treaty negotiations for binding global plastics agreement (2024-).', 10, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define ocean acidification.', 'Decline in seawater pH (~8.2 pre-industrial → 8.1 today, ~30% more acidic) as oceans absorb CO2. Reduces calcium carbonate availability — harms shellfish, coral, plankton. Threatens marine food webs.', 11, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline coral reef threats and the Great Barrier Reef.', 'Threats: warming -> bleaching (1998, 2016, 2017, 2020, 2022), acidification, runoff (nitrogen, sediment), crown-of-thorns starfish outbreaks, unsustainable tourism. Australia funds Reef 2050 Plan.', 12, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define a dead zone.', 'Hypoxic ocean area where dissolved oxygen is too low to sustain most marine life. Caused by nutrient runoff (fertiliser, sewage) -> algal blooms -> decomposition. Gulf of Mexico, Baltic Sea, Arabian Sea among largest.', 13, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline the South China Sea dispute.', '~$3.4tn trade passes annually. China''s Nine-Dash Line claim disputed by Philippines, Vietnam, Malaysia, Brunei. 2016 PCA ruling against China — ignored. Artificial island building; militarisation; US ''freedom of navigation'' patrols.', 14, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline Arctic Ocean governance.', 'Arctic Council (1996) — 8 states + observers. Search and rescue, science cooperation, indigenous peoples. As ice melts, new shipping routes (NSR, NWP) and resource access (oil, gas, minerals). Russian militarisation a concern.', 15, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline the High Seas Treaty (BBNJ Agreement, 2023).', 'UN treaty for biodiversity beyond national jurisdiction. Allows MPAs in high seas, environmental impact assessments, sharing benefits of marine genetic resources. Crucial for 30x30 target. Needs 60 ratifications to enter force.', 16, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define the Antarctic Treaty System.', '1959 treaty (in force 1961, 56 parties). Suspends territorial claims, prohibits military activity, demilitarises continent, ensures freedom of scientific research. Madrid Protocol (1991, 50 yr) banned mining; review 2048.', 17, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'List four sustainable fisheries strategies.', 'Catch quotas (ITQs), MPAs, MSC certification (consumer choice), technical measures (mesh size, closed seasons), reducing subsidies, aquaculture (with caveats), monitoring (satellite, observer programmes).', 18, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Define ocean acidification feedback to global warming.', 'Acidified oceans absorb less CO2 (positive feedback amplifying warming). Warmer oceans hold less dissolved gas (Henry''s law). Reduced phytoplankton (biological pump weakened). Threatens climate regulation services.', 19, 'alevel'),
  ('Geography', 'Eduqas', '2.4', 'Global Governance of Oceans', 'Outline deep-sea mining controversy.', 'Polymetallic nodules contain Ni, Co, Mn, Cu — useful for renewables. International Seabed Authority regulates. Environmental groups oppose: irreversible damage to poorly known ecosystems. Some companies waiting for ISA to finalise rules.', 20, 'alevel');

-- Topic 2.5 — 21st Century Challenges
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'List the 17 UN Sustainable Development Goals.', 'No poverty, zero hunger, good health, quality education, gender equality, clean water, affordable energy, decent work, industry/innovation, reduced inequalities, sustainable cities, responsible consumption, climate action, life below water, life on land, peace/justice, partnerships.', 1, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define the Anthropocene.', 'Proposed geological epoch where humans are the dominant influence on Earth''s systems — climate, biogeochemical cycles, biosphere, lithosphere. Began c. 1950 (Great Acceleration) for some; awaiting formal IUGS recognition.', 2, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define planetary boundaries.', 'Nine processes regulating Earth-system stability (Rockstrom 2009): climate, biodiversity, biogeochemical flows, land use, freshwater, ocean acidification, ozone, aerosols, novel entities. Six already crossed.', 3, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline four climate change impacts.', 'Sea-level rise, extreme weather (heatwaves, floods, droughts), agricultural disruption, biodiversity loss, climate refugees, ocean acidification, glacier retreat, permafrost thaw, vector-borne disease shifts.', 4, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define the Paris Agreement.', 'A UNFCCC treaty (2015) signed by ~196 parties. Aims to limit warming to ''well below 2°C'' above pre-industrial, pursuing 1.5°C. Each country sets Nationally Determined Contributions (NDCs), reviewed every 5 years.', 5, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline COP processes (Conference of Parties).', 'Annual UN climate negotiations under UNFCCC. COP21 Paris (2015), COP26 Glasgow (2021 — Glasgow Climate Pact, methane reduction, deforestation), COP28 Dubai (2023 — first explicit ''transitioning away from fossil fuels'').', 6, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define net zero.', 'A balance between greenhouse gas emissions and removals (sinks, CCS). UK target 2050; EU 2050; China 2060; India 2070. Achieved through emissions cuts + carbon offsets/removals. Critics: relies on speculative tech.', 7, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'List four causes of biodiversity loss.', 'Habitat destruction (deforestation, agriculture), invasive species, pollution, overexploitation (fishing, hunting), climate change. WWF Living Planet: 69% decline in monitored vertebrate populations 1970-2018.', 8, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define the Convention on Biological Diversity (CBD).', '1992 UN treaty for biodiversity conservation, sustainable use, fair benefit sharing. Targets at COP15 Montreal (2022): 30% protected area by 2030 (30x30), $30bn/yr conservation funding, halt species extinction.', 9, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define food security.', 'When all people have physical and economic access to sufficient, safe, nutritious food. Pillars: availability, access, utilisation, stability. ~735 million undernourished (2024). Threatened by conflict, climate, prices.', 10, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'List four food security threats.', 'Climate change/extreme weather, soil degradation, water scarcity, conflict (Russia-Ukraine grain), market shocks, supply chain breakdowns (Covid), trade restrictions, food waste (~30% globally).', 11, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline strategies to improve food security.', 'Boost productivity (HYV, irrigation, GM), reduce waste, diversify diets, store buffer stocks, improve roads/infrastructure, fair-trade, climate-smart agriculture, land reform, vertical farming, alternative proteins.', 12, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define water security.', 'Reliable access to acceptable quantity and quality of water for all uses. Threatened by scarcity (~2 billion lack safe drinking water), pollution, climate change, transboundary disputes.', 13, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define energy security.', 'Reliable access to energy at affordable prices. Threatened by import dependence, conflict, depletion, transition risks. UK reduced Russian fossil dependency post-2022 via diversification and accelerated renewables.', 14, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline AI and technology challenges.', 'Job displacement (estimates 14-50% of jobs at risk by 2030, OECD), inequality, surveillance, misinformation. Geographic concentration of AI development (US, China). Energy/water demand of data centres.', 15, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define geopolitical fragmentation.', 'Decline in international cooperation, rise of regional/national blocs. Trade decoupling, technology rivalry, security alliances (QUAD, AUKUS), challenges to UN Security Council legitimacy. Threatens collective action on global issues.', 16, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline pandemic preparedness post-Covid.', 'Covid revealed gaps: weak surveillance, vaccine inequality, supply chain fragility. WHO Pandemic Treaty negotiations 2024-25. Lessons: One Health (human/animal/environment), invest in primary care, equitable access.', 17, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Define inequality and three measures.', 'Unequal distribution of income, wealth, opportunity. Gini coefficient (0-1), Palma ratio (top 10% vs bottom 40%), wealth percentiles (Credit Suisse Global Wealth Report). Within-country inequality has risen in many HICs since 1980s.', 18, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline the circular economy.', 'Designed-out waste, regenerative model. Reduce, reuse, refurbish, recycle. EU Circular Economy Action Plan 2020. Examples: Patagonia clothing repair, Renault remanufacturing. Decouples growth from resource use.', 19, 'alevel'),
  ('Geography', 'Eduqas', '2.5', '21st Century Challenges', 'Outline degrowth and post-growth thinking.', 'Critique of GDP growth as policy goal. Argues HICs should prioritise wellbeing over output (Doughnut Economics, Raworth). Critics: incompatible with poverty reduction, employment. Influencing climate policy debate.', 20, 'alevel');

-- Topic 3.1 — Tectonic Hazards
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Define hazard, risk, vulnerability and resilience.', 'Hazard: potential damaging event. Risk: probability × consequence. Vulnerability: degree to which a community is susceptible. Resilience: ability to absorb, adapt and recover. R = (H × V) / Capacity.', 1, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Outline the structure of the Earth.', 'Inner core (solid Fe/Ni, ~5500°C), outer core (liquid Fe/Ni, generates magnetic field), mantle (semi-molten silicates, convection cells), crust: oceanic (5-10 km, basalt) and continental (30-70 km, granite).', 2, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Sketch the three plate-boundary types.', 'Constructive (divergent): plates move apart, magma rises, mid-ocean ridges/rifts. Destructive (convergent): denser oceanic subducts beneath continental, trench/volcanic arc. Conservative (transform): plates slide past, earthquakes only. <svg viewBox="0 0 280 150" width="280" height="150" style="display:block;margin:6px auto"><g><rect x="10" y="40" width="40" height="40" fill="#A0A0A0"/><rect x="60" y="40" width="40" height="40" fill="#A0A0A0"/><polygon points="50,40 60,40 55,20" fill="#B00020"/><line x1="20" y1="60" x2="0" y2="60" stroke="#0B1E3F" marker-end="url(#c4)"/><line x1="90" y1="60" x2="110" y2="60" stroke="#0B1E3F" marker-end="url(#c4)"/><text x="55" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Constructive</text></g><g><rect x="120" y="40" width="50" height="40" fill="#A0A0A0"/><polygon points="170,40 215,80 215,40" fill="#A0A0A0"/><polygon points="180,40 200,40 190,25" fill="#B00020"/><text x="170" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Destructive</text></g><g><rect x="225" y="40" width="50" height="40" fill="#A0A0A0"/><line x1="250" y1="40" x2="250" y2="80" stroke="white" stroke-width="2"/><line x1="240" y1="50" x2="260" y2="50" stroke="#0B1E3F" stroke-dasharray="2 2"/><text x="250" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Conservative</text></g><defs><marker id="c4" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs></svg>', 3, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Define a hot spot.', 'Mantle plumes that pierce moving plates and form volcanic chains as the plate moves over them (e.g. Hawaiian-Emperor seamount chain, Yellowstone caldera). Independent of plate boundaries.', 4, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Distinguish primary and secondary effects of a volcanic eruption.', 'Primary: lava, pyroclastic flows, ashfall, gases. Secondary: lahars (mud flows), tsunamis, climate impact (Pinatubo 1991 cooled global T by 0.5°C), economic disruption, displacement.', 5, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Compare a shield with a composite (stratovolcano).', 'Shield: low-viscosity basaltic lava, gentle slopes, frequent effusive eruptions (Mauna Loa). Composite: high-viscosity andesitic lava, steep alternating ash/lava layers, infrequent explosive eruptions (Mt St Helens, Vesuvius).', 6, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Define VEI.', 'Volcanic Explosivity Index — logarithmic 0-8 based on ejecta volume and column height. VEI 0-2: effusive, frequent. VEI 5+: highly explosive (Mt St Helens 1980 = 5; Pinatubo 1991 = 6; Tambora 1815 = 7).', 7, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'How are earthquakes measured?', 'Magnitude (energy): Moment Magnitude Scale (Mw, replaced Richter above ~M5; logarithmic). Intensity (effects): Modified Mercalli (I-XII). Depth: shallow (<70 km) most damaging.', 8, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'List four secondary effects of earthquakes.', 'Tsunami (Tohoku 2011), liquefaction (saturated sandy soils losing strength), landslides, fires (gas mains), disease, building collapse aftershocks. Often cause more deaths than primary shaking.', 9, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Explain how a tsunami forms.', 'Sudden vertical displacement of seabed (megathrust earthquake at subduction zone) lifts the entire water column. Long-wavelength waves travel at ~700 km/h in deep ocean, slow and steepen on the shelf, surge inland.', 10, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Outline tropical storm conditions.', 'Forms over oceans >26.5°C, depth >50 m, latitude 5-30° (Coriolis required), low wind shear. Warm core driven by latent heat release. Coriolis spins the storm cyclonically (anticlockwise N hemisphere).', 11, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Outline Park''s response curve.', 'Quality of life trace through pre-disaster, disruption, search-and-rescue, relief, rehabilitation, reconstruction. Recovery may exceed (more resilient), match, or fall below pre-disaster level depending on aid and management.', 12, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Outline the PAR (Pressure and Release) model.', 'Disasters arise from the intersection of natural hazard and social vulnerability. Root causes (poverty, governance) -> dynamic pressures (rapid urbanisation, deforestation) -> unsafe conditions (slums on hillsides). Releases pressure by addressing causes.', 13, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Compare HIC and LIC earthquake responses.', 'Tohoku, Japan 2011 (Mw9.1): ~20,000 deaths, $235bn damage, advanced warning, building codes, swift recovery. Haiti 2010 (Mw7.0): ~230,000 deaths, weak buildings, slow recovery, lasting cholera outbreak.', 14, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'List four disaster mitigation strategies.', 'Hazard mapping/zoning, building codes (base isolation), early warning systems (Japan 1-min alert), education and drills, retrofitting, insurance, emergency stockpiles, community awareness.', 15, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Define a multi-hazard zone.', 'Region exposed to several hazards (e.g. Philippines: typhoons, earthquakes, volcanism, tsunamis, landslides). Compound risk: one event can trigger another. Increases vulnerability and complicates planning.', 16, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Why does hazard impact differ between countries?', 'Wealth funds prevention/response. Strong governance enforces codes, manages aid. LICs lack early warning, hospitals, finance — so similar magnitudes cause higher death tolls. Cultural perception shapes preparedness.', 17, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Outline a contrasting volcanic event case study.', 'Eyjafjallajökull, Iceland 2010: VEI 4, low casualties, ash disrupted European aviation 6-8 days, $1.7bn losses. Mt Merapi, Indonesia 2010: VEI 4, 350+ deaths, 350,000 displaced, evacuated villages destroyed.', 18, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Outline factors that affect hazard perception.', 'Wealth, education, religion, past experience, media coverage, role of government. Higher education and recent experience -> active mitigation. Fatalistic ''Acts of God'' acceptance -> passive response. Influences vulnerability.', 19, 'alevel'),
  ('Geography', 'Eduqas', '3.1', 'Tectonic Hazards', 'Define hazard adjustment with examples.', 'Adjustments are deliberate actions to reduce loss. Examples: zoning (no building on floodplains), retrofitting buildings, planting mangroves to absorb surges, community drills, micro-insurance for farmers.', 20, 'alevel');

-- Topic 3.2 — Ecosystems
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define ecosystem, biome and biosphere.', 'Ecosystem: community of living organisms (biotic) interacting with their physical environment (abiotic). Biome: large-scale ecosystem (tropical rainforest, tundra). Biosphere: sum of all life on Earth.', 1, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Distinguish open and closed ecosystems.', 'Open: exchange both energy and matter with surroundings (most ecosystems). Closed: only energy crosses (rare — sealed jar terrarium experiments). Earth''s biosphere is essentially closed except for solar input and meteorites.', 2, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define primary productivity.', 'Rate at which producers (plants) fix solar energy as biomass through photosynthesis. Gross primary productivity (GPP): total. Net primary productivity (NPP): GPP minus plant respiration — available to consumers.', 3, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline four major nutrient cycles.', 'Carbon (photosynthesis/respiration/combustion), nitrogen (fixation/nitrification/denitrification), phosphorus (weathering, no atmospheric phase), water. Decomposers recycle nutrients from dead matter back to producers.', 4, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define ecological succession.', 'Predictable sequence of community change. Primary succession: bare rock -> lichen -> moss -> grasses -> shrubs -> woodland (climax). Secondary: starts after disturbance with soil already present (faster).', 5, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Describe a psammosere succession (sand dunes).', 'Embryo dunes (sea couch) -> foredune (marram) -> yellow dune -> grey dune -> dune slack -> heath/woodland. Each stage modifies abiotic conditions (organic matter, moisture) enabling the next.', 6, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Describe a hydrosere succession.', 'Open water -> floating plants -> reedswamp -> fen/marsh -> carr (alder, willow) -> climax woodland. Sediment and dead matter gradually fill the water body. Common in lake margins.', 7, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Describe a lithosere succession.', 'Bare rock -> lichens (chemical weathering) -> moss -> grass -> herbaceous plants -> shrubs -> climax woodland. Each stage adds soil and organic matter for the next. Slow on hard rock.', 8, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define plagioclimax.', 'A community that has reached an apparent climax but is maintained by human intervention (grazing, fire, mowing). Heather moorland in UK uplands; meadow grasslands. Removing intervention triggers succession.', 9, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline the tropical rainforest ecosystem.', 'High rainfall (>2000 mm/yr), warm (24-28°C), high biodiversity, layered structure (emergents, canopy, understory, forest floor), nutrients cycled rapidly, thin soils with most nutrients in biomass.', 10, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'List threats to tropical rainforests.', 'Deforestation for cattle, soya, palm oil; logging; mining; roads; climate change; fire (Amazon 2019, Indonesia 2015 peatlands). Brazilian Amazon deforestation rate fell 2023 under Lula but threats remain.', 11, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline the tundra ecosystem.', 'Cold (mean <0°C), low precipitation (~200 mm/yr), permafrost beneath active layer, low biodiversity, slow decomposition, treeless, dwarf shrubs and lichens. Vulnerable to climate change (permafrost thaw, vegetation change).', 12, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline the savanna grassland ecosystem.', 'Tropical wet-dry climate (~500-1500 mm/yr seasonal). Grass-dominated with scattered trees (acacia). Grazers (zebra, wildebeest), predators (lion). Maintained by fire, drought, grazing. Threatened by overgrazing, agricultural expansion.', 13, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define biodiversity and four types.', 'Variety of life: genetic (within species), species (number/variety), ecosystem (range of habitats), functional (range of ecological roles). Hotspots: Amazon, SE Asia, Congo, biodiversity hotspots (Myers, 25 globally).', 14, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'List four causes of biodiversity loss.', 'Habitat destruction, invasive species, pollution, overexploitation, climate change. WWF Living Planet Index: 69% decline in monitored vertebrate populations 1970-2018. The ''sixth mass extinction'' debate.', 15, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline conservation strategies.', 'Protected areas (~17% land, ~8% ocean as MPAs), Convention on Biological Diversity 30x30 target, species recovery (red kite UK), ecosystem restoration (rewilding), ex-situ conservation (zoos, seed banks), community-based conservation.', 16, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define a Marine Protected Area.', 'Sea area designated for conservation. Ranges from no-take zones (full protection) to multi-use. Currently ~8% of ocean is MPA; UN aims for 30% by 2030. Examples: Great Barrier Reef Marine Park, Ross Sea (Antarctica).', 17, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Define rewilding.', 'Restoration of ecological processes by reintroducing species and reducing human management. Yellowstone wolves (1995) restored trophic cascade. UK: Knepp Estate (free-roaming herbivores), beaver reintroduction (Devon, Scotland).', 18, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline ecosystem services and four examples.', 'Nature''s benefits to humans. Provisioning (food, water, timber), regulating (climate, flood, pollination), supporting (nutrient cycling, soil), cultural (recreation, spiritual). Valued in trillions globally (Costanza 1997).', 19, 'alevel'),
  ('Geography', 'Eduqas', '3.2', 'Ecosystems', 'Outline a UK ecosystem case study.', 'UK upland moorland (e.g. North York Moors): heather plagioclimax, sheep grazing, grouse moors. Threats: peat erosion, climate change, wildfires. Restoration: peatland rewetting (Yorkshire Dales), forest expansion, sustainable agriculture.', 20, 'alevel');
