-- A-Level Geography Flashcards (AQA)
-- Generated for the RAG Learning study app from existing notes HTML files.
-- One INSERT per topic. card_order restarts at 1 within each topic.
-- The 'level' column is assumed to already exist on the flashcards table.
-- Inline SVGs are used for diagrams where they materially aid understanding.

-- ===============================================================
-- AQA A-LEVEL
-- ===============================================================

-- Topic 1.1 — Water and Carbon Cycles
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Define a system in physical geography and distinguish open from closed.', 'A set of interrelated stores and flows. Open: exchanges both energy and matter with surroundings (drainage basin). Closed: exchanges only energy (the global water cycle and global carbon cycle on Earth).', 1, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'List the four major stores of the global water cycle and approximate %.', 'Oceans (~97%), cryosphere/ice (~2%), groundwater (~0.7%), surface water and atmosphere (<0.1%). Lithosphere holds tiny amounts in rocks.', 2, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Sketch the global water cycle.', 'Solar energy drives evaporation from oceans, vegetation transpires, vapour rises, condenses, precipitates over land and oceans; runoff and groundwater return to the sea. <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><rect x="0" y="120" width="260" height="40" fill="#9CC3E5"/><polygon points="120,120 200,120 220,80 130,80" fill="#A8D08D"/><circle cx="60" cy="35" r="12" fill="#E7E6E6"/><circle cx="80" cy="40" r="14" fill="#E7E6E6"/><circle cx="180" cy="30" r="14" fill="#E7E6E6"/><circle cx="200" cy="35" r="12" fill="#E7E6E6"/><path d="M40 110 Q40 80 60 50" stroke="#0B1E3F" fill="none" stroke-width="1.2" marker-end="url(#a1)"/><path d="M150 90 Q150 70 170 45" stroke="#0B1E3F" fill="none" stroke-width="1.2" marker-end="url(#a1)"/><path d="M210 50 Q220 80 220 110" stroke="#0B1E3F" fill="none" stroke-width="1.2" marker-end="url(#a1)"/><path d="M180 120 L150 130" stroke="#0B1E3F" fill="none" stroke-width="1.2" marker-end="url(#a1)"/><defs><marker id="a1" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs><text x="20" y="80" font-size="8" fill="#0B1E3F">evap</text><text x="125" y="65" font-size="8" fill="#0B1E3F">transp</text><text x="220" y="80" font-size="8" fill="#0B1E3F">precip</text><text x="160" y="135" font-size="8" fill="#0B1E3F">runoff</text></svg>', 3, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Define a drainage basin and key terms (watershed, source, mouth, confluence).', 'Drainage basin: area of land drained by a river and its tributaries. Watershed: high-ground boundary. Source: where the river begins. Mouth: where it enters the sea. Confluence: junction of two streams.', 4, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Sketch the drainage basin hydrological system (inputs, stores, flows, outputs).', 'Input: precipitation. Stores: interception, surface, soil moisture, groundwater, channel. Flows: surface runoff, throughflow, infiltration, percolation, baseflow. Outputs: evaporation, transpiration, channel discharge. <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><rect x="20" y="20" width="220" height="120" fill="none" stroke="#0B1E3F" stroke-dasharray="3 2"/><line x1="60" y1="20" x2="60" y2="40" stroke="#0B1E3F" stroke-width="1.2" marker-end="url(#a2)"/><text x="62" y="32" font-size="8" fill="#0B1E3F">precip</text><rect x="40" y="50" width="60" height="14" fill="#9CC3E5"/><text x="42" y="61" font-size="8" fill="#0B1E3F">surface</text><rect x="40" y="74" width="60" height="14" fill="#A8D08D"/><text x="42" y="85" font-size="8" fill="#0B1E3F">soil</text><rect x="40" y="98" width="60" height="14" fill="#C9C9C9"/><text x="42" y="109" font-size="8" fill="#0B1E3F">groundwater</text><rect x="160" y="60" width="50" height="14" fill="#9CC3E5"/><text x="163" y="71" font-size="8" fill="#0B1E3F">channel</text><line x1="100" y1="57" x2="160" y2="67" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a2)"/><text x="115" y="55" font-size="7" fill="#0B1E3F">runoff</text><line x1="100" y1="81" x2="160" y2="69" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a2)"/><text x="118" y="78" font-size="7" fill="#0B1E3F">throughflow</text><line x1="100" y1="105" x2="160" y2="73" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a2)"/><text x="120" y="100" font-size="7" fill="#0B1E3F">baseflow</text><line x1="210" y1="67" x2="240" y2="67" stroke="#0B1E3F" stroke-width="1.2" marker-end="url(#a2)"/><text x="215" y="60" font-size="8" fill="#0B1E3F">discharge</text><defs><marker id="a2" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs></svg>', 5, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'What is a storm hydrograph and what do its key features mean?', 'A graph of river discharge against time after a storm. Lag time: gap between peak rainfall and peak discharge. Steeper rising limb / shorter lag indicate flashier basin (urbanised, impermeable, steep, saturated). <svg viewBox="0 0 260 160" width="260" height="160" style="display:block;margin:6px auto"><line x1="30" y1="130" x2="245" y2="130" stroke="#0B1E3F"/><line x1="30" y1="130" x2="30" y2="20" stroke="#0B1E3F"/><rect x="60" y="100" width="40" height="20" fill="#9CC3E5"/><text x="80" y="95" font-size="8" fill="#0B1E3F" text-anchor="middle">storm</text><path d="M30 125 Q90 125 130 50 Q170 30 210 90 Q230 110 245 120" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="80" y1="100" x2="80" y2="130" stroke="#B00020" stroke-dasharray="2 2"/><line x1="150" y1="38" x2="150" y2="130" stroke="#B00020" stroke-dasharray="2 2"/><line x1="80" y1="140" x2="150" y2="140" stroke="#B00020" stroke-width="1.2" marker-end="url(#a3)"/><text x="115" y="152" font-size="8" fill="#B00020" text-anchor="middle">lag time</text><defs><marker id="a3" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#B00020"/></marker></defs><text x="28" y="18" font-size="9" fill="#0B1E3F" text-anchor="end">Discharge</text><text x="245" y="148" font-size="9" fill="#0B1E3F" text-anchor="end">time</text></svg>', 6, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Distinguish physical and human factors that increase flood risk.', 'Physical: heavy/prolonged rainfall, snowmelt, impermeable rock, steep relief, antecedent saturation. Human: urbanisation (impermeable surfaces, drains), deforestation, channel modification, climate change.', 7, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'List the four major stores of the global carbon cycle.', 'Lithosphere (sedimentary rocks, fossil fuels — by far the largest), oceans (dissolved CO2, biological carbon), terrestrial biosphere (vegetation, soils), atmosphere (CO2, CH4 — smallest but climate-critical).', 8, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Distinguish fast and slow carbon cycles.', 'Fast: photosynthesis, respiration, decomposition, ocean exchange — operates over days to centuries. Slow: weathering of silicate rocks, sedimentation, volcanism — operates over millions of years.', 9, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Sketch the global carbon cycle (key stores and flows).', 'Atmosphere ↔ photosynthesis (vegetation) and respiration; vegetation → soil via decomposition; oceans absorb/release CO2; weathering removes C; volcanism returns C; fossil fuel combustion releases stored C. <svg viewBox="0 0 280 160" width="280" height="160" style="display:block;margin:6px auto"><rect x="20" y="20" width="240" height="30" fill="#E7E6E6"/><text x="140" y="38" font-size="9" fill="#0B1E3F" text-anchor="middle">Atmosphere (CO2)</text><rect x="20" y="80" width="100" height="30" fill="#A8D08D"/><text x="70" y="98" font-size="9" fill="#0B1E3F" text-anchor="middle">Vegetation</text><rect x="160" y="80" width="100" height="30" fill="#9CC3E5"/><text x="210" y="98" font-size="9" fill="#0B1E3F" text-anchor="middle">Oceans</text><rect x="20" y="125" width="100" height="20" fill="#8B6F47"/><text x="70" y="139" font-size="9" fill="white" text-anchor="middle">Soil/Litho</text><rect x="160" y="125" width="100" height="20" fill="#454545"/><text x="210" y="139" font-size="9" fill="white" text-anchor="middle">Fossil fuels</text><line x1="50" y1="50" x2="50" y2="78" stroke="#0B1E3F" marker-end="url(#a4)"/><text x="35" y="68" font-size="7" fill="#0B1E3F">photo</text><line x1="90" y1="78" x2="90" y2="52" stroke="#0B1E3F" marker-end="url(#a4)"/><text x="92" y="68" font-size="7" fill="#0B1E3F">resp</text><line x1="190" y1="50" x2="190" y2="78" stroke="#0B1E3F" marker-end="url(#a4)"/><line x1="220" y1="78" x2="220" y2="52" stroke="#0B1E3F" marker-end="url(#a4)"/><line x1="70" y1="110" x2="70" y2="123" stroke="#0B1E3F" marker-end="url(#a4)"/><line x1="200" y1="123" x2="200" y2="55" stroke="#B00020" stroke-width="1.2" marker-end="url(#a5)"/><text x="205" y="80" font-size="7" fill="#B00020">combust</text><defs><marker id="a4" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker><marker id="a5" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#B00020"/></marker></defs></svg>', 10, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'How are land-use change and farming affecting the carbon cycle?', 'Deforestation releases stored carbon and reduces sinks. Ploughing exposes and oxidises soil organic matter. Drainage of peatlands releases CO2. Livestock and rice paddies emit methane.', 11, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Define the water and carbon budgets and explain why they are linked.', 'Water budget = inputs − outputs of water in a system; carbon budget = sources − sinks of C. They are linked because plant productivity (carbon uptake) requires water, and the warming hydrological cycle alters carbon storage (drought, soil moisture).', 12, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Why does the Amazon rainforest matter for both cycles?', 'Stores ~150-200 Pg C in biomass and soils; transpires huge water vapour into the atmosphere driving regional rainfall. Deforestation reduces both the carbon sink and the moisture flux, risking ''dieback'' tipping points.', 13, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Compare positive and negative feedbacks in the climate system.', 'Positive amplifies the original change: ice-albedo (less ice -> more absorbed solar -> more melt), permafrost thaw -> CH4 release. Negative dampens: more CO2 -> more plant growth -> CO2 uptake (limited).', 14, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Define dynamic equilibrium and tipping point.', 'Dynamic equilibrium: stores fluctuate around a long-term average as inputs balance outputs. Tipping point: critical threshold where small change causes a shift to a new state, often irreversible (e.g. Atlantic ocean circulation collapse).', 15, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Outline mitigation and adaptation strategies for the carbon cycle.', 'Mitigation: cut emissions (renewables, EVs), carbon capture and storage, afforestation, reduce deforestation (REDD+). Adaptation: flood defences, drought-resistant crops, coastal managed retreat, water resource planning.', 16, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Define an aquifer and explain its importance.', 'A permeable rock layer (often porous sandstone or jointed limestone/chalk) saturated with groundwater. Recharged slowly by percolation. The London Basin chalk aquifer has been over-abstracted and is recovering (~3 m/yr) since 1990s.', 17, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'How does the cryosphere influence the global water cycle?', 'Stores ~2% of global water; reflects ~80% of incident solar (high albedo). Melt redistributes water to oceans (sea-level rise) and changes ocean salinity, affecting thermohaline circulation. Permafrost stores frozen organic matter.', 18, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Define the soil moisture budget.', 'Balance of water inputs (precipitation) and outputs (evapotranspiration, drainage) in soil over time. Field capacity reached after rain; deficit develops in summer; recharge in autumn. Critical for agriculture and runoff timing.', 19, 'alevel'),
  ('Geography', 'AQA', '1.1', 'Water and Carbon Cycles', 'Explain the ocean biological and physical carbon pumps.', 'Physical (solubility) pump: cold polar water dissolves CO2, sinks, locks C in deep ocean for centuries. Biological pump: phytoplankton photosynthesise; dead matter sinks (''marine snow'') sequestering C in sediments. Slowing as oceans warm.', 20, 'alevel');

-- Topic 1.2 — Coastal Systems and Landscapes
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Define a sediment cell.', 'A largely self-contained coastal section with sources, transfers and sinks of sediment between fixed boundaries (usually headlands). England and Wales are divided into 11 cells — useful for integrated coastal management.', 1, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Distinguish constructive and destructive waves.', 'Constructive: low height, long wavelength, low frequency (6-8/min), strong swash, weak backwash, builds berms. Destructive: tall, short wavelength, frequent (10-14/min), weak swash, strong backwash, removes sediment. <svg viewBox="0 0 260 140" width="260" height="140" style="display:block;margin:6px auto"><g><line x1="10" y1="100" x2="125" y2="100" stroke="#0B1E3F"/><path d="M10 100 Q30 80 50 100 T90 100 T130 100" stroke="#0B1E3F" fill="none"/><text x="65" y="120" font-size="9" fill="#0B1E3F" text-anchor="middle">Constructive</text></g><g><line x1="135" y1="100" x2="250" y2="100" stroke="#0B1E3F"/><path d="M135 100 Q150 70 165 100 T195 100 T225 100 T255 100" stroke="#0B1E3F" fill="none"/><text x="195" y="120" font-size="9" fill="#0B1E3F" text-anchor="middle">Destructive</text></g></svg>', 2, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Name four wave-driven erosional processes.', 'Hydraulic action (waves compress air in cracks), abrasion/corrasion (sediment scours), attrition (rocks knock together, become rounder), corrosion/solution (chemical dissolving — limestone, chalk).', 3, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Describe longshore drift.', 'Sediment is moved along a coast in a zigzag pattern: swash carries material up the beach in the prevailing wind direction; backwash returns it perpendicular to the shoreline. Net result: lateral transport. <svg viewBox="0 0 260 130" width="260" height="130" style="display:block;margin:6px auto"><rect x="0" y="60" width="260" height="70" fill="#F2D9A5"/><line x1="0" y1="60" x2="260" y2="60" stroke="#0B1E3F" stroke-width="1.2"/><path d="M20 100 L60 70" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)"/><path d="M60 70 L80 100" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)" stroke-dasharray="2 2"/><path d="M80 100 L120 70" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)"/><path d="M120 70 L140 100" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)" stroke-dasharray="2 2"/><path d="M140 100 L180 70" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)"/><path d="M180 70 L200 100" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)" stroke-dasharray="2 2"/><path d="M200 100 L240 70" stroke="#0B1E3F" stroke-width="1" marker-end="url(#a6)"/><path d="M40 30 L80 30" stroke="#B00020" marker-end="url(#a7)"/><text x="60" y="22" font-size="8" fill="#B00020" text-anchor="middle">prevailing wind</text><text x="20" y="125" font-size="8" fill="#0B1E3F">swash → solid; backwash → dashed</text><defs><marker id="a6" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker><marker id="a7" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#B00020"/></marker></defs></svg>', 4, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Outline how a wave-cut platform forms.', 'Waves erode a notch at the high-water mark; the cliff above is undercut and collapses; the cliff retreats inland leaving a flat rocky platform exposed at low tide. Continued retreat builds a wider platform.', 5, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Describe the headland-bay-stack-arch sequence.', 'Differential erosion of soft and hard rock creates headlands and bays. Headlands are attacked from sides: cracks → caves → caves meet to form an arch → arch collapses leaving a stack → stack erodes to a stump. <svg viewBox="0 0 280 140" width="280" height="140" style="display:block;margin:6px auto"><polygon points="0,140 0,80 40,80 50,90 80,90 90,80 130,80 130,140" fill="#A0A0A0"/><polygon points="170,140 170,80 200,80 210,95 230,95 240,80 270,80 270,140" fill="#A0A0A0"/><circle cx="220" cy="92" r="8" fill="white"/><polygon points="148,140 148,90 158,90 158,140" fill="#A0A0A0"/><rect x="0" y="100" width="280" height="40" fill="#9CC3E5" fill-opacity="0.6"/><text x="65" y="115" font-size="8" fill="#0B1E3F">headland</text><text x="220" y="80" font-size="8" fill="#0B1E3F" text-anchor="middle">arch</text><text x="153" y="78" font-size="8" fill="#0B1E3F" text-anchor="middle">stack</text></svg>', 6, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'How do beaches form and what controls their profile?', 'Beaches form where constructive waves deposit sediment in sheltered bays and lower-energy stretches. Profile depends on sediment size (steeper for shingle, gentler for sand), wave energy, and tidal range.', 7, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Outline the formation of a spit.', 'Longshore drift transports sediment past a change in coastline orientation; sediment accumulates in deeper water; secondary winds curve the end (recurve). Sheltered area behind develops salt marsh. Examples: Spurn Head, Hurst Castle.', 8, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Distinguish eustatic and isostatic sea-level change.', 'Eustatic: global change in volume of seawater (melting ice, thermal expansion). Isostatic: local change in land level (rebound after deglaciation, subsidence). Together produce relative sea-level change.', 9, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Distinguish emergent and submergent landforms.', 'Emergent (sea fell or land rose): raised beaches, fossil cliffs. Submergent (sea rose or land fell): rias (drowned river valleys), fjords (drowned glacial valleys), Dalmatian coasts.', 10, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'List four hard-engineering coastal defences with one drawback each.', 'Sea wall (expensive, ugly), groynes (starve down-drift coast), rock armour/rip-rap (visual impact), revetment (costly maintenance), gabions (rust over time). All defer the problem rather than solve it.', 11, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'List four soft-engineering coastal defences.', 'Beach nourishment (replenish sand), dune regeneration (planting marram grass), managed retreat/coastal realignment, salt-marsh restoration. Cheaper, more sustainable, but slower-acting.', 12, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Define Shoreline Management Plans (SMPs).', 'UK strategic plans for coastal stretches that select one of four policies for each section: hold the line, advance the line, managed retreat, or no active intervention. Reviewed every 5-10 years.', 13, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Outline the Holderness coastline as a case study.', 'East Yorkshire — fastest eroding coast in Europe (~1.8 m/yr). Boulder clay cliffs, North Sea fetch, longshore drift south. Mappleton groynes (1991) protected village but accelerated erosion at Cowden. Politically contentious.', 14, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'How is climate change altering coasts?', 'Sea-level rise (eustatic + thermal expansion) drowns low-lying coasts; more storms increase erosion; ocean acidification damages coral; warmer oceans bleach reefs; permafrost thaw weakens Arctic coasts.', 15, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'How can a coral reef be a case study of a tropical coastal ecosystem under threat?', 'Great Barrier Reef: warming triggers mass bleaching events (1998, 2002, 2016, 2017, 2020, 2022), acidification slows calcification, agricultural runoff causes COTS outbreaks. Resilience falls; recovery slows; AUS plans restoration.', 16, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Outline the formation of sand dunes.', 'Onshore winds blow dry beach sand inland; embryo dunes form around obstacles (driftwood, marram); pioneer species stabilise (sea couch, sand-lyme); succession continues to fixed dunes; finally heath/woodland on dune slack. Saltney, Studland are UK examples.', 17, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Define a salt marsh and where it forms.', 'Vegetated tidal mudflat in sheltered low-energy environments (estuaries, behind spits). Forms by deposition of fine sediments stabilised by halophytes (Spartina, Salicornia). Stores carbon; buffers storms; nursery for fish.', 18, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Why are mangroves important coastal ecosystems?', 'Mangroves are salt-tolerant trees in tropical/sub-tropical inter-tidal zones. Stilt roots absorb wave energy (~70% reduction). Sequester ~3-5x more carbon per hectare than tropical forest. Threatened by aquaculture and coastal development.', 19, 'alevel'),
  ('Geography', 'AQA', '1.2', 'Coastal Systems and Landscapes', 'Outline the formation of an offshore bar and tombolo.', 'Offshore bar: deposition where waves break on shallow seabed, creating a sandbank. Tombolo: depositional ridge linking an island to the mainland (Chesil Beach to Portland; St. Ninian''s Isle, Shetland).', 20, 'alevel');

-- Topic 1.3 — Hazards
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '1.3', 'Hazards', 'Define hazard, risk, vulnerability and resilience.', 'Hazard: potential damaging event. Risk: probability × consequence. Vulnerability: degree to which a community is susceptible. Resilience: ability to absorb, adapt and recover. The disaster equation: R = (Hazard × Vulnerability) / Capacity.', 1, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Outline Park''s hazard response (disaster) curve.', 'Quality of life trace through pre-disaster, disruption, search-and-rescue, relief, rehabilitation, reconstruction. Recovery may exceed (more resilient), match, or fall below pre-disaster level depending on aid and management.', 2, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Sketch the three plate boundary types.', 'Constructive (divergent): plates move apart, magma rises, mid-ocean ridges/rifts. Destructive (convergent): denser oceanic subducts beneath continental, trench/volcanic arc. Conservative (transform): plates slide past, earthquakes only. <svg viewBox="0 0 280 150" width="280" height="150" style="display:block;margin:6px auto"><g><rect x="10" y="40" width="40" height="40" fill="#A0A0A0"/><rect x="60" y="40" width="40" height="40" fill="#A0A0A0"/><polygon points="50,40 60,40 55,20" fill="#B00020"/><line x1="20" y1="60" x2="0" y2="60" stroke="#0B1E3F" marker-end="url(#a8)"/><line x1="90" y1="60" x2="110" y2="60" stroke="#0B1E3F" marker-end="url(#a8)"/><text x="55" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Constructive</text></g><g><rect x="120" y="40" width="50" height="40" fill="#A0A0A0"/><polygon points="170,40 215,80 215,40" fill="#A0A0A0"/><polygon points="195,40 175,40 175,55" fill="#9CC3E5"/><polygon points="180,40 200,40 190,25" fill="#B00020"/><line x1="155" y1="60" x2="180" y2="60" stroke="#0B1E3F" marker-end="url(#a8)"/><line x1="200" y1="60" x2="180" y2="60" stroke="#0B1E3F" marker-end="url(#a8)"/><text x="170" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Destructive</text></g><g><rect x="225" y="40" width="50" height="40" fill="#A0A0A0"/><line x1="250" y1="40" x2="250" y2="80" stroke="white" stroke-width="2"/><line x1="240" y1="50" x2="260" y2="50" stroke="#0B1E3F" stroke-dasharray="2 2"/><line x1="230" y1="35" x2="245" y2="35" stroke="#0B1E3F" marker-end="url(#a8)"/><line x1="270" y1="85" x2="255" y2="85" stroke="#0B1E3F" marker-end="url(#a8)"/><text x="250" y="100" font-size="8" fill="#0B1E3F" text-anchor="middle">Conservative</text></g><defs><marker id="a8" viewBox="0 0 6 6" refX="5" refY="3" markerWidth="6" markerHeight="6" orient="auto"><path d="M0,0 L6,3 L0,6 z" fill="#0B1E3F"/></marker></defs></svg>', 3, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'What drives plate movement? Explain mantle convection and ridge push/slab pull.', 'Heat from radioactive decay drives mantle convection cells. Hot rock rises at ridges (ridge push), cools and sinks; old, cold, dense oceanic lithosphere subducts and pulls the rest of the plate (slab pull). Slab pull dominates.', 4, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Distinguish primary and secondary effects of a volcanic eruption.', 'Primary: lava, pyroclastic flows, ashfall, gases. Secondary: lahars (mud flows), tsunamis, climate impact (Pinatubo 1991 cooled global T by 0.5°C), economic disruption, displacement.', 5, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Compare a shield with a composite (stratovolcano).', 'Shield: low-viscosity basaltic lava, gentle slopes, frequent effusive eruptions (Mauna Loa). Composite: high-viscosity andesitic lava, steep alternating ash/lava layers, infrequent explosive eruptions (Mt. St. Helens, Vesuvius).', 6, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'How are earthquakes measured?', 'Magnitude (energy): Richter scale (logarithmic, replaced by Moment Magnitude Mw above ~M5). Intensity (effects): Modified Mercalli (I-XII). Depth: shallow (<70 km) most damaging.', 7, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Distinguish primary and secondary effects of an earthquake.', 'Primary: ground shaking, surface rupture, building collapse. Secondary: tsunami, liquefaction, landslides, fires (gas mains), disease, economic loss. Secondary often kill more people than primary.', 8, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Explain how a tsunami forms.', 'Sudden vertical displacement of seabed (megathrust earthquake at subduction zone) lifts the entire water column. Long-wavelength waves travel at jet speed in deep ocean (~700 km/h), slow and steepen on the shelf, surge inland.', 9, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Outline a tropical storm and its formation conditions.', 'A rotating low-pressure system with sustained winds >119 km/h. Forms over oceans >26.5°C, depth >50 m, between 5° and 30° latitude (Coriolis effect needed), in low wind shear. Warm core driven by latent heat release.', 10, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'List the main hazards of a tropical storm.', 'High winds, torrential rain, storm surge, flooding, landslides. Storm surge typically causes most deaths in low-lying areas (Bangladesh 1970 cyclone — 300,000+ deaths).', 11, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Outline a wildfire as a hazard, including conditions favouring ignition.', 'Uncontrolled vegetation fire. Conditions: dry fuel (drought), high temperature, low humidity, strong wind, ignition source (lightning, human). Climate change is lengthening fire seasons (Australia 2019-20, California, Mediterranean).', 12, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Outline a contrasting case study of two earthquakes (HIC vs LIC).', 'Tohoku, Japan 2011 (Mw9.1): ~20,000 deaths mostly from tsunami, $235bn damage; advanced warning, building codes, swift recovery. Haiti 2010 (Mw7.0): ~230,000 deaths, weak buildings, slow recovery, lasting cholera outbreak.', 13, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Describe modification of vulnerability strategies.', 'Education, hazard mapping, prediction (seismic monitoring, weather forecasting), warning systems (Japan''s 1-min earthquake alert), insurance, building codes (base isolation, cross-bracing), drills, evacuation routes.', 14, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Explain why hazard impact varies between countries (development, governance).', 'Wealth funds prevention/response. Strong governance enforces codes, manages aid. Cultural factors influence perception. LICs lack early warning, hospitals, and reconstruction finance — so similar magnitudes cause higher death tolls.', 15, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Define hazard adjustment and provide three examples.', 'Adjustments are deliberate actions to reduce loss. Examples: zoning (no building on floodplains), retrofitting buildings, planting mangroves to absorb surges, community drills, micro-insurance for farmers.', 16, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Define VEI (Volcanic Explosivity Index).', 'A logarithmic 0-8 scale based on volume of ejecta and column height. VEI 0-2: effusive, frequent. VEI 5+: highly explosive, regional impact (Mt St Helens 1980 = 5; Pinatubo 1991 = 6; Tambora 1815 = 7).', 17, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Outline a multi-hazard zone.', 'Region exposed to several hazards (e.g. Philippines: typhoons, earthquakes, volcanism, tsunamis, landslides). Compound risk: one event can trigger another (typhoon -> landslide on volcanic slope). Increases vulnerability and complicates planning.', 18, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'Outline factors that affect hazard perception (Dregg, prevailing fatalism).', 'Wealth, education, religion, past experience, media coverage, role of government. Higher education and recent experience -> active mitigation. Fatalistic ''Acts of God'' acceptance -> passive response. Influences vulnerability.', 19, 'alevel'),
  ('Geography', 'AQA', '1.3', 'Hazards', 'What is a supervolcano and where are they?', 'A volcano with VEI 8 — over 1000 km3 of ejecta, capable of triggering global cooling (volcanic winter). Yellowstone (USA), Toba (Indonesia, last erupted 74,000 yrs ago, ''Toba bottleneck''), Taupo (NZ). Dormant but monitored.', 20, 'alevel');

-- Topic 2.1 — Changing Places
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Distinguish space, place and locale.', 'Space: an area defined by coordinates. Place: space invested with meaning by people (Tuan). Locale: setting in which everyday life happens (Agnew). Place is therefore relational and dynamic.', 1, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Distinguish near and far places.', 'Near: places experienced directly through everyday life. Far: places known only through media, education or imagination. Globalisation blurs the distinction (instant communications can make distant events feel proximate).', 2, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Distinguish experienced and media places.', 'Experienced: known first-hand through visits and routines. Media: known via film, news, social media, books. Media representations may distort reality (e.g. ''sink-estate'' stereotypes).', 3, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Define endogenous and exogenous factors that shape place.', 'Endogenous (internal): physical geography, demography, land use, economy, built environment, history. Exogenous (external): connections to other places, migration, capital flows, government policy, globalisation.', 4, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Define topophilia and topophobia.', 'Topophilia (Tuan, 1974): the affective bond between people and place — love of place. Topophobia: fear or dislike of place — common in places associated with crime, decay, traumatic memory.', 5, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Distinguish insider and outsider perspectives.', 'Insider: born or long-resident, share traditions, language, networks; place-attached. Outsider: temporary or unfamiliar; may romanticise or stereotype. Status fluid — gentrifiers can shift between.', 6, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'How does globalisation affect place identity?', 'Increases similarity (clone towns, McDonaldisation), but also enables cultural hybridity (London curry, Liverpool Chinatown). Some places resist (CittaSlow, fair-trade towns); others rebrand to compete.', 7, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Define place-meaning and place-identity.', 'Place-meaning: subjective values and emotions attached to place by individuals/groups. Place-identity: sense of self constructed through belonging to place (national, regional, neighbourhood).', 8, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Outline gentrification with one named example.', 'In-migration of higher-income residents into a previously low-income area, refurbishing housing and changing local amenities. Displaces original residents through rising rents. Examples: Notting Hill, Brixton, Hackney, Brooklyn.', 9, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Outline a rural rebranding strategy with an example.', 'Rebranding aims to attract visitors/investors. Cornwall: Eden Project (£2bn local economic impact since 2001), Hall for Cornwall, food/drink tourism, surf tourism, films like Doc Martin. Trade-offs: housing affordability for locals.', 10, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Outline an urban rebranding strategy with an example.', 'Liverpool One (2008) — £1bn shopping district. Capital of Culture 2008 boosted tourism. Albert Dock heritage waterfront. Tate Liverpool. But persistent inequality in Anfield/Everton wards.', 11, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'List four ways place is represented.', 'Statistics (census, IMD), films, novels, paintings, photographs, music, postcards, tourist boards, news media, social media (#hashtags create new place identities).', 12, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'How does the IMD measure deprivation?', 'UK Index of Multiple Deprivation combines seven domains: income, employment, education, health, crime, housing, living environment. Areas ranked into deciles. Allows place-by-place comparison of need.', 13, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Define lived experience and how a researcher accesses it.', 'The everyday meanings of a place to its residents. Accessed through ethnography, interviews, oral histories, participant observation, mental maps, photo elicitation — qualitative methods that surface what statistics cannot.', 14, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Explain the role of TNCs in changing places.', 'TNCs alter place economies by opening/closing branches, sourcing globally, and homogenising the high street (clone towns). Detroit''s decline tracked GM/Ford restructuring; Bangalore''s rise tracked IT outsourcing.', 15, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Compare a contrasting place study (your own + a contrasting one).', 'Choose two places (e.g. local urban + rural Cornwall), compare endogenous and exogenous factors, demographic and economic profiles, representations, lived experiences and management strategies — the ''Changing Places'' core skill.', 16, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Outline how power shapes place (gentrification politics).', 'Local authorities, developers and capital decide which places get investment. Power asymmetries displace less powerful (low-income, ethnic minorities). Resistance: campaigns (Save Latin Village, Tottenham), community land trusts, rent controls.', 17, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Define resilience of place.', 'A place''s ability to absorb shocks (flooding, deindustrialisation, pandemics) and adapt. Drivers: economic diversity, social capital, governance, infrastructure. Detroit struggled; Pittsburgh transitioned to medicine/education ''eds and meds''.', 18, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'How does diaspora shape place identity?', 'Migrants reshape places of origin (remittances, return migration) and destination (cultural quarters, transnational networks). London Bangladeshi diaspora invests in Sylhet; Brick Lane''s curry mile reflects east London Bangladeshi identity.', 19, 'alevel'),
  ('Geography', 'AQA', '2.1', 'Changing Places', 'Define ''place is socially constructed''.', 'Place meaning is created through human practice, language and representation rather than fixed by physical geography. The same physical site can be ''heritage,'' ''slum,'' ''opportunity'' or ''problem'' depending on who narrates it.', 20, 'alevel');

-- Topic 2.2 — Contemporary Urban Environments
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Define urbanisation, suburbanisation, counter-urbanisation, re-urbanisation.', 'Urbanisation: rising % living in cities. Suburbanisation: outward growth from city centres. Counter-urbanisation: net movement to rural areas (1970s UK, accelerated by Covid). Re-urbanisation: return to inner cities (e.g. Docklands).', 1, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Sketch the Burgess concentric model.', 'CBD core, then transition zone, working-class housing, middle-class housing, commuter zone — based on 1920s Chicago. Assumes uniform land surface and a single centre. <svg viewBox="0 0 200 160" width="200" height="160" style="display:block;margin:6px auto"><circle cx="100" cy="80" r="70" fill="#9CC3E5" fill-opacity="0.3" stroke="#0B1E3F"/><circle cx="100" cy="80" r="55" fill="#9CC3E5" fill-opacity="0.4" stroke="#0B1E3F"/><circle cx="100" cy="80" r="40" fill="#9CC3E5" fill-opacity="0.5" stroke="#0B1E3F"/><circle cx="100" cy="80" r="25" fill="#9CC3E5" fill-opacity="0.6" stroke="#0B1E3F"/><circle cx="100" cy="80" r="12" fill="#0B1E3F"/><text x="100" y="84" font-size="9" fill="white" text-anchor="middle">CBD</text><text x="100" y="65" font-size="7" fill="#0B1E3F" text-anchor="middle">transition</text><text x="100" y="48" font-size="7" fill="#0B1E3F" text-anchor="middle">working-class</text><text x="100" y="32" font-size="7" fill="#0B1E3F" text-anchor="middle">middle-class</text><text x="100" y="18" font-size="7" fill="#0B1E3F" text-anchor="middle">commuter</text></svg>', 2, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'How does Hoyt''s sector model differ from Burgess?', 'Hoyt (1939): sectors radiate from CBD along transport routes. Higher-income corridors keep their character outwards; industry follows transport. Better fits cities shaped by railways/roads.', 3, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Outline the multiple nuclei (Harris-Ullman) model.', 'Cities grow around several nodes (CBD, ports, universities, airports), not just one centre. Better captures large modern cities (Los Angeles, Greater London) than Burgess or Hoyt.', 4, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Define megacity, world city and global city.', 'Megacity: >10 million inhabitants (Tokyo, Delhi, Shanghai). World city: significant global political/economic influence (Friedmann). Global city: command-and-control nodes for finance and producer services (Sassen — NYC, London, Tokyo).', 5, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'List the main causes of the urban heat island effect.', 'Albedo of dark surfaces, anthropogenic heat (cars, AC, industry), reduced evapotranspiration, urban canyon multiple reflections, less wind, air pollution that traps long-wave radiation.', 6, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Explain photochemical smog formation.', 'Vehicle NOx and VOCs react in sunlight to form ground-level ozone and PAN. Worst in still, hot, sunny weather over cities (Los Angeles, Beijing, Mexico City). Damages respiratory health and crops.', 7, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'How does urbanisation alter the water cycle?', 'Impermeable surfaces increase runoff; storm drains concentrate it. Result: faster lag times, higher peak discharge — flashier hydrographs and flash flooding. SUDS (rain gardens, swales, permeable paving) try to mitigate.', 8, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Define the multiplier effect in an urban economy.', 'Initial investment (TNC HQ, university, regeneration) creates direct jobs and demand for local services, generating further indirect/induced jobs. The reverse — the negative multiplier — drives spirals of decline.', 9, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Outline causes and consequences of urban deprivation.', 'Deindustrialisation, structural unemployment, poor housing, low investment, weak schools. Consequences: cycles of poverty, spatial inequality, mental and physical ill-health, social unrest. Measured by IMD.', 10, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Outline an urban regeneration scheme (London Docklands).', '1981 LDDC established. £8.7bn investment by 1998. Canary Wharf, DLR, City Airport. 80,000+ jobs. Critique: original communities largely excluded; gentrification displaced low-income residents.', 11, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'List four sustainable urban strategies.', 'Compact city design, public transport (BRT, metro, cycle networks), renewable energy, green roofs and parks, mixed-use development, district heating, water recycling, community engagement (Curitiba, Freiburg, Copenhagen).', 12, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'How does Curitiba (Brazil) illustrate sustainable transport?', 'Bus Rapid Transit launched 1974; >2 million daily passengers; tube-stations speed boarding; integrated land-use planning along five axes; 70% commuters use BRT. Replicated in Bogota (TransMilenio).', 13, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Define ecological footprint and how cities increase it.', 'Land/water area needed to provide resources and absorb waste. Cities concentrate consumption — London''s footprint is ~125x its area; rich cities outsource emissions to producing regions.', 14, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Define ethnic enclave and outline reasons for clustering.', 'A neighbourhood with high concentration of one ethnic group. Reasons: chain migration, mutual support, language/cultural amenities, discrimination in housing markets. Examples: Tower Hamlets (Bangladeshi), Brixton (Caribbean).', 15, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Compare a UK city with a megacity in the developing world.', 'London (~9 million, planned, formal housing, declining inner-city deprivation) vs Mumbai (~22 million, Dharavi slum hosts ~1 million, informal economy >50%, intense pollution, coastal flood risk).', 16, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'List four challenges of urban waste management.', 'Volume (UK ~26 Mt municipal/yr), composition (plastics, e-waste, food), illegal dumping, landfill capacity, methane emissions. Strategies: reduce/reuse/recycle, anaerobic digestion, energy-from-waste, EPR schemes, deposit return.', 17, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'Define a smart city.', 'A city that uses ICT, sensors and big data to manage assets, energy, traffic and services efficiently. Examples: Singapore, Songdo (Korea), Barcelona''s sensors for parking, lighting, waste. Critics: privacy, equity gap.', 18, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'List three drivers of counter-urbanisation.', 'Improved transport/IT (commute, remote work), perception of better quality of life (lower crime, cleaner air, schools), housing affordability, retirement. Covid-19 accelerated UK ''race for space'' (London out-migration ~80,000 in 2020-21).', 19, 'alevel'),
  ('Geography', 'AQA', '2.2', 'Contemporary Urban Environments', 'How does urban form influence energy use?', 'Compact, mixed-use cities (Barcelona, Hong Kong) have lower per-capita transport energy than sprawled, car-dependent ones (Atlanta, Houston). Density permits mass transit, district heating, shorter trips.', 20, 'alevel');

-- Topic 2.3 — Population and the Environment
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Explain the Demographic Transition Model (DTM) stages.', 'Stage 1 high BR/DR, low NIR (pre-industrial). Stage 2 DR falls, BR high, rapid growth. Stage 3 BR falls. Stage 4 low BR/DR. Stage 5 (added) DR>BR, decline (Japan, Italy). <svg viewBox="0 0 280 160" width="280" height="160" style="display:block;margin:6px auto"><line x1="30" y1="135" x2="270" y2="135" stroke="#0B1E3F"/><line x1="30" y1="135" x2="30" y2="20" stroke="#0B1E3F"/><path d="M30 35 Q60 35 90 70 Q130 110 180 120 Q220 120 270 125" stroke="#B00020" stroke-width="1.5" fill="none"/><path d="M30 35 Q60 35 100 50 Q140 80 200 110 Q235 115 270 115" stroke="#0B1E3F" stroke-width="1.5" fill="none"/><line x1="80" y1="20" x2="80" y2="140" stroke="#0B1E3F" stroke-dasharray="2 2" stroke-width="0.5"/><line x1="130" y1="20" x2="130" y2="140" stroke="#0B1E3F" stroke-dasharray="2 2" stroke-width="0.5"/><line x1="190" y1="20" x2="190" y2="140" stroke="#0B1E3F" stroke-dasharray="2 2" stroke-width="0.5"/><line x1="230" y1="20" x2="230" y2="140" stroke="#0B1E3F" stroke-dasharray="2 2" stroke-width="0.5"/><text x="55" y="150" font-size="8" fill="#0B1E3F" text-anchor="middle">1</text><text x="105" y="150" font-size="8" fill="#0B1E3F" text-anchor="middle">2</text><text x="160" y="150" font-size="8" fill="#0B1E3F" text-anchor="middle">3</text><text x="210" y="150" font-size="8" fill="#0B1E3F" text-anchor="middle">4</text><text x="250" y="150" font-size="8" fill="#0B1E3F" text-anchor="middle">5</text><text x="265" y="32" font-size="8" fill="#B00020" text-anchor="end">BR</text><text x="265" y="112" font-size="8" fill="#0B1E3F" text-anchor="end">DR</text></svg>', 1, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Read a population pyramid: youthful vs ageing.', 'Youthful pyramid (LIC): wide base, narrow top — high BR, short life expectancy (Niger). Ageing pyramid (HIC): narrow base, wide top — low BR, long life expectancy (Japan, Germany). Indicates dependency ratio.', 2, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Define dependency ratio and give the formula.', 'DR = (under 15 + over 64) / (15-64) × 100. Higher DR means working population supports more dependants — strain on welfare and pensions in HICs, on schools and food in LICs.', 3, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Compare neo-Malthusian and Boserupian views.', 'Malthus/neo-Malthus: population grows geometrically while food grows arithmetically -> famine. Boserup: population pressure drives agricultural innovation. Real history fits both (Green Revolution, but soil exhaustion).', 4, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'List four physical influences on population distribution.', 'Climate (temperature, rainfall), relief, soil fertility, water availability, vegetation, drainage, latitude/altitude. People cluster in fertile lowlands, river valleys and coasts.', 5, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Define carrying capacity and overpopulation.', 'Carrying capacity (K): the maximum population a region can support sustainably. Overpopulation: population exceeds K, causing resource depletion and environmental degradation.', 6, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'List four push and pull factors of migration.', 'Push: war, poverty, drought, persecution, lack of jobs/education. Pull: jobs, family reunification, peace, education, healthcare, freedom. Lee''s model adds intervening obstacles (cost, border controls).', 7, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Outline the demographic dividend.', 'When the working-age population is much larger than dependants, savings and investment can rise — boosting growth (East Asia 1960-90). Requires education, jobs and gender equality to be realised.', 8, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Define epidemiological transition (Omran).', 'Disease patterns shift as a society develops: from infectious diseases (TB, cholera) and famine, to chronic diseases (heart disease, cancer), to ''emerging'' diseases (Covid-19, antibiotic-resistant infections).', 9, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Outline a contrasting health case study.', 'UK NHS: universal healthcare, ageing population, NCDs dominate, life expectancy ~81. Sub-Saharan Africa: HIV/AIDS, malaria, malnutrition; life expectancy 60-65 but rising as ART scaled up.', 10, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Outline anti- and pro-natalist policies with examples.', 'Anti-natalist: China''s One-Child Policy (1979-2015) — enforced quotas, social pressures; created sex imbalance, ageing. Pro-natalist: France''s family allowance, Singapore''s ''Have Three or More'' (1987), Hungary tax breaks.', 11, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'How does climate influence agriculture?', 'Temperature determines growing season; rainfall controls choice of crops (irrigation in arid zones); extreme events (drought, frost, hail, floods) reduce yields; climate change shifts viable areas (vine UK, decline in Iberia).', 12, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'List four agricultural strategies to feed a growing population.', 'Green Revolution (HYV crops, irrigation, fertiliser), GM crops, vertical farming, precision agriculture, irrigation, soil conservation, fair-trade, dietary shift to less meat.', 13, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Compare population dynamics of two contrasting countries.', 'Niger: TFR ~6.7, median age 15, rapidly growing youthful population, food security under pressure. Japan: TFR ~1.3, median age 49, shrinking labour force, rising old-age dependency.', 14, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Outline forecast effects of climate change on global population.', 'Disruption to food/water in vulnerable regions (Sahel, South Asia), migration pressures (climate refugees), heat-related mortality, expanded vector-borne disease. IPCC: hundreds of millions at risk by 2050.', 15, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Define resource pressure and one strategy to relieve it.', 'Demand for water, food, energy and land beyond what local environments can supply sustainably. Strategies: efficiency, recycling, demand management, shifting consumption patterns, technological innovation, international trade.', 16, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Outline how vector-borne disease distribution is influenced by climate.', 'Mosquitoes (malaria, dengue) require warmth and standing water. Climate change is shifting ranges polewards and to higher altitudes (highland malaria in Kenya). Tsetse fly limits African livestock to certain zones.', 17, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Why is globalisation linked to pandemics?', 'Air travel moves pathogens across continents in hours (SARS 2003, H1N1 2009, Covid-19 2020). Urbanisation concentrates susceptible populations. Habitat encroachment increases zoonotic spillover (Ebola, Nipah, Covid-19).', 18, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Define soil degradation and its impact on food security.', 'Decline in soil fertility through erosion, salinisation, compaction or contamination. Affects ~33% of global land. Reduces yields, increases fertiliser dependence, releases stored carbon. Worst in semi-arid Africa, South Asia.', 19, 'alevel'),
  ('Geography', 'AQA', '2.3', 'Population and the Environment', 'Define a food desert.', 'An urban area with poor access to affordable, nutritious food (low income, no supermarkets within walking distance, reliance on convenience stores). Linked to obesity and diet-related diseases. Common in deprived inner-city UK and US neighbourhoods.', 20, 'alevel');

-- Topic 2.4 — Resource Security
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Define resource and resource security.', 'Resource: anything natural that humans use to sustain life or generate wealth. Resource security: assured access to a resource (water, food, energy) at affordable cost, in adequate amount, reliably.', 1, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Distinguish stock, flow and renewable resources.', 'Stock (non-renewable): fixed amount, depleted by use (fossil fuels, minerals). Flow (renewable): continuously replenished (solar, wind, water). Critical: renewable in principle but fragile under stress (forests, fisheries).', 2, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'List the components of the energy mix.', 'Coal, oil, natural gas (fossil), nuclear, hydro, wind, solar, biomass/biofuel, geothermal, tidal/wave. Mix varies by country: France ~70% nuclear, Norway ~95% hydro, Saudi Arabia ~oil-dominant.', 3, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Describe the global pattern of energy supply and demand.', 'Supply concentrated in oil/gas-rich states (Middle East, Russia, USA). Demand greatest in HICs and rapidly industrialising NEEs (China, India). Transit chokepoints (Strait of Hormuz, Malacca, Bab el-Mandeb) create geopolitical risk.', 4, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Define peak oil and Hubbert''s curve.', 'Peak oil: the point of maximum extraction, after which production declines. Hubbert''s 1956 prediction of US peak in ~1970 was broadly correct (until shale revolution from 2008 reopened US production).', 5, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Distinguish unconventional and conventional fossil fuel sources.', 'Conventional: vertically drilled, naturally pooled, easily extracted. Unconventional: shale gas/oil (fracking), tar sands, deep-water, Arctic — higher cost, more environmental impact (water use, emissions, induced seismicity).', 6, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline two sources of mineral resource demand growth.', 'Renewables: lithium for batteries, rare earths for wind turbines and EVs, copper for grids. Urbanisation: steel, cement, aluminium for construction. Both increasing pressure on reserves and fuelling new geopolitics.', 7, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Distinguish blue, green and grey water.', 'Blue: liquid surface and groundwater. Green: rainwater stored in soil and used by plants. Grey: wastewater volume needed to dilute pollution to safe levels. Useful for agricultural water footprint analysis.', 8, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Define water scarcity and water stress.', 'Water stress: <1700 m3 per person per year. Water scarcity: <1000 m3. Absolute scarcity: <500 m3. Causes: physical (low rainfall) or economic (lack of infrastructure). Affects ~2 billion people.', 9, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline causes and consequences of water scarcity (Aral Sea).', 'Soviet 1960s diversion of Amu/Syr Darya for cotton irrigation; Aral lost ~90% volume by 2010. Consequences: collapse of fisheries, salinised soils, dust storms, public health crisis, climate change (loss of moderating effect).', 10, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'List four food security threats.', 'Climate change/extreme weather, soil degradation, water scarcity, pests/disease, conflict, market shocks, supply chain breakdowns (Covid), trade restrictions, wastage (~30% globally).', 11, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline strategies to improve food security.', 'Boost productivity (HYV, irrigation, mechanisation, GM), reduce waste, diversify diets, store buffer stocks, improve roads/infrastructure, fair-trade, subsidies, climate-smart agriculture, land reform.', 12, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Define a transboundary resource and give an example.', 'A resource (river, aquifer, fishery) that crosses political borders, requiring cooperation. Examples: Nile (Egypt-Sudan-Ethiopia GERD dispute), Mekong, Indus Waters Treaty (India-Pakistan, 1960).', 13, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline the geopolitics of energy in Russia/Ukraine.', 'Russia supplied ~40% of EU gas pre-2022. Invasion of Ukraine triggered EU diversification (Norwegian gas, US LNG, accelerated renewables, restart of coal). Energy weaponised; Nord Stream sabotaged.', 14, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline a sustainable resource management approach.', 'Reduce, reuse, recycle. Circular economy. Resource efficiency (water-saving, energy-efficient buildings). Local sourcing. Restoration (rewetting peatlands). Consumer education. Carbon pricing. Polluter-pays principle.', 15, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Why is the energy transition geographically uneven?', 'Wealth funds capital-heavy technologies (LICs lag); natural endowment (sun, wind) varies; fossil fuel rents resist change; politics influences ambition (China''s solar dominance vs Saudi Arabia''s oil dependency).', 16, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Why are rare earth elements geopolitically significant?', '17 metals essential for magnets, EVs, wind turbines, smartphones, defence. China controls ~60% of global production and ~85% of refining (2024). Concentrated supply -> strategic vulnerability. EU and US developing domestic mines and recycling.', 17, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline the renewable energy transition.', 'Global renewable share rose from ~20% (2010) to ~30% (2024) of electricity. Cost falls — solar PV ~90% cheaper since 2010. Wind, solar dominate new capacity. Challenges: intermittency, storage, grid upgrades, land use, mineral demand.', 18, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Outline conflict over a transboundary water resource.', 'Nile: Ethiopia''s Grand Ethiopian Renaissance Dam (filling since 2020) reduces flow to Egypt and Sudan. Egypt, dependent on Nile for ~95% of water, claims it as an existential threat. Negotiations ongoing under AU mediation.', 19, 'alevel'),
  ('Geography', 'AQA', '2.4', 'Resource Security', 'Define the resource curse.', 'When countries rich in natural resources experience worse development outcomes than resource-poor peers. Causes: rent-seeking, corruption, currency overvaluation (''Dutch disease''), conflict (DRC, Nigeria''s Niger Delta), authoritarianism (Venezuela).', 20, 'alevel');

-- Topic 3.1 — Fieldwork and Investigation
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level) VALUES
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Define the geography NEA (Non-Examined Assessment).', 'A 3,000-4,000 word independent investigation worth 20% of A-Level. Student-chosen geographical question/hypothesis, four days minimum fieldwork (one outside class), uses primary and secondary data.', 1, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'List the six stages of an NEA investigation.', '1) Question/hypothesis. 2) Plan and methodology. 3) Data collection. 4) Data presentation. 5) Analysis and interpretation. 6) Conclusion and evaluation. All must show geographical reasoning.', 2, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Distinguish primary and secondary data.', 'Primary: collected by you in the field (questionnaires, measurements, photographs). Secondary: from existing sources (census, ONS, IMD, Met Office). Mix of both gives validity and triangulation.', 3, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Distinguish quantitative and qualitative data.', 'Quantitative: numerical and measurable (footfall, beach gradient, pH). Qualitative: descriptive and contextual (interviews, photographs, mental maps, environmental impact assessments).', 4, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'List four sampling techniques.', 'Random (using random number tables), systematic (every nth), stratified (subgroups proportional to population), opportunistic/convenience (where access permits). Choice depends on question, time and access.', 5, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Define accuracy, reliability and validity.', 'Accuracy: closeness to true value. Reliability: same result if repeated. Validity: data measures what you intend. NEA evaluation must address all three with specific examples from your method.', 6, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'List four ways to mitigate fieldwork risk.', 'Risk assessment, group working, weather monitoring, mobile phones, first-aid kit, hi-viz clothing, supervisor contact, awareness of tides/cliffs/traffic. Required by examination board.', 7, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Name four data presentation techniques.', 'Choropleth maps, isoline maps, dot maps, proportional symbols, line graphs, bar charts, scatter graphs with line of best fit, pie charts, kite diagrams, radar charts, GIS overlays.', 8, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'When use Spearman''s rank correlation coefficient?', 'When you want to test whether two ranked variables (e.g. distance from CBD vs pedestrian count) correlate. Result lies between −1 and +1; strength compared against critical values for significance.', 9, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'When use a chi-squared test?', 'When you want to compare observed frequencies (e.g. land-use type counts) with expected frequencies. Tests whether differences are statistically significant against critical values for given degrees of freedom.', 10, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Define standard deviation and what it tells you.', 'A measure of spread around the mean. Small SD: data clustered (consistent). Large SD: data dispersed. Used to compare variability between two samples (e.g. sediment size at two beaches).', 11, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'List four ways to measure river velocity.', 'Float method (orange/cork over fixed distance), flowmeter, dye tracing, calculated from cross-section + discharge. Repeat at multiple cross-sections; average for accuracy.', 12, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Outline how to investigate a coastal hypothesis.', 'Hypothesis e.g. ''Beach gradient steepens away from the dominant wave direction''. Methods: profile every 50 m using clinometer, measure pebble size with calipers, photograph features, secondary wind-direction data.', 13, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Outline how to investigate an urban question.', 'Question e.g. ''How does environmental quality vary along a transect from CBD to suburb?''. Use environmental quality survey, pedestrian count, land-use mapping, IMD secondary data, photographs at evenly spaced sites.', 14, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'How should you reference and avoid plagiarism in NEA?', 'Cite all secondary sources with author, date and title; use Harvard or footnotes consistently; quote directly with quotation marks; submit declaration of authenticity. AQA cross-checks with Turnitin.', 15, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Outline what an evaluation should cover.', 'Strengths and limitations of method; sample size and representativeness; equipment accuracy; alternative approaches; how findings link to wider geographical theory; suggestions for further research.', 16, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Why is a pilot study useful?', 'A small-scale trial run of your method that highlights problems before main data collection: ambiguous questions, equipment issues, time required, sampling site suitability. Saves time and improves reliability.', 17, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'How can GIS be used in fieldwork?', 'Pre-fieldwork: identify sample sites, layer secondary data (IMD, flood risk, OS maps). During: GPS tagging photographs and measurements. After: choropleth maps, hot-spot analysis, buffer zones, network analysis. Software: ArcGIS, QGIS (free).', 18, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'List four ethical considerations in fieldwork.', 'Informed consent for interviews; anonymising data (no real names without permission); respect for cultural sensitivities; avoid disturbing protected sites/wildlife; consider safeguarding when working with under-18s; honest reporting (no fabrication).', 19, 'alevel'),
  ('Geography', 'AQA', '3.1', 'Fieldwork and Investigation', 'Define triangulation of methods.', 'Using multiple data sources or methods to investigate the same question and cross-check findings (e.g. environmental quality survey + photograph + interview + secondary IMD data). Increases validity and confidence in conclusions.', 20, 'alevel');
