-- Flashcard top-up: Chemistry|Edexcel|alevel — brings each topic up to 30 cards.
-- Generated by scripts/build-flashcard-topup.js from flashcards/topup/src/chemistry-edexcel-alevel.txt
-- Safe to re-run: skips fronts already present and never takes a topic past 30.
WITH v(subject, exam_board, level, topic_id, topic_name, front, back, ord) AS (VALUES
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'Define relative atomic mass.', 'The weighted mean mass of an atom of an element relative to 1/12 of the mass of a carbon-12 atom.', 1),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'What is an orbital?', 'A region around the nucleus that can hold up to two electrons with opposite spins.', 2),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'Give the electron configurations of Cr and Cu.', 'Cr: [Ar] 3d5 4s1; Cu: [Ar] 3d10 4s1 (a half-filled or filled 3d sub-shell is more stable).', 3),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'Why does ionisation energy decrease from N to O?', 'In O, two electrons share a 2p orbital; the extra repulsion makes one easier to remove.', 4),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'What is the difference between ionic and covalent bonding?', 'Ionic: electrostatic attraction between oppositely charged ions. Covalent: a shared pair of electrons attracted to both nuclei.', 5),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'How does polarisation of an anion produce covalent character in ionic bonds?', 'A small, highly charged cation distorts the electron cloud of a large anion, pulling electron density between the ions.', 6),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'What is a σ bond and a π bond?', 'σ: head-on overlap of orbitals along the internuclear axis. π: sideways overlap of p orbitals above and below the axis.', 7),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'What are London forces?', 'Temporary induced dipole–dipole attractions caused by fluctuating electron distributions. They are stronger for molecules with more electrons.', 8),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'What conditions are needed for hydrogen bonding?', 'H bonded to N, O or F, and a lone pair on an N, O or F atom in another molecule.', 9),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'How does the shape of an XeF4 molecule arise?', '4 bonding pairs and 2 lone pairs around Xe give a square planar shape (90°).', 10),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'Why do metals conduct electricity and heat?', 'Delocalised electrons can move through the structure carrying charge and energy.', 11),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'Define standard enthalpy of neutralisation.', 'The enthalpy change when 1 mole of water is formed from the reaction of an acid and an alkali under standard conditions.', 12),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'How is the enthalpy change of a reaction found from bond enthalpies?', 'ΔH = Σ(bonds broken) − Σ(bonds formed).', 13),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'What is meant by exothermic and endothermic in terms of ΔH?', 'Exothermic: ΔH negative (heat released to the surroundings). Endothermic: ΔH positive (heat absorbed).', 14),
  ('Chemistry', 'Edexcel', 'alevel', 'T1', 'Atomic Structure, Bonding and Energetics', 'How do you calculate moles of gas at room temperature from volume?', 'Moles = volume (dm^3) ÷ 24.0 dm^3 mol^-1 at RTP.', 15),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is the collision theory explanation for the effect of temperature on rate?', 'Particles have more kinetic energy, so a much greater proportion of collisions have energy at least Ea, and collisions are more frequent.', 1),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is a heterogeneous catalyst?', 'A catalyst in a different phase from the reactants, e.g. iron in the Haber process; the reaction takes place at active sites on its surface.', 2),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'How do catalysts increase rate?', 'They provide an alternative reaction pathway with a lower activation energy.', 3),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'Give the units of the rate constant for a second-order reaction.', 'dm^3 mol^-1 s^-1.', 4),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is the initial-rates method?', 'Measuring the rate at the start of several experiments with different starting concentrations to find the order with respect to each reactant.', 5),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'How does a clock reaction measure rate?', 'The time for a set amount of product to form (e.g. a sudden colour change) is measured; rate ∝ 1/t.', 6),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'Why does increasing pressure shift the equilibrium N2 + 3H2 ⇌ 2NH3 to the right?', 'The right-hand side has fewer moles of gas, so the equilibrium shifts to reduce the pressure.', 7),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is the effect of adding a catalyst on equilibrium?', 'Equilibrium is reached faster, but its position and K are unchanged.', 8),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'Define oxidation and reduction in terms of electrons.', 'Oxidation is loss of electrons; reduction is gain of electrons (OIL RIG).', 9),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is a disproportionation reaction?', 'A reaction in which the same element is both oxidised and reduced.', 10),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'How is the oxidation state of an element in a compound determined?', 'Oxidation states add up to the overall charge. Fixed values: O is −2 (except in peroxides), H is +1 (except in metal hydrides), F is −1.', 11),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is a salt bridge and why is it needed in a cell?', 'A strip of filter paper soaked in saturated KNO3 that completes the circuit by allowing ions to move, without the solutions mixing.', 12),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'How are cell diagrams written?', 'Pt | Fe2+, Fe3+ || Ag+ | Ag: the oxidation half-cell on the left, the reduction on the right, with a double line for the salt bridge.', 13),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is the relationship between E°cell and ΔG?', 'ΔG = −nFE°cell; a positive E°cell gives a negative ΔG (feasible).', 14),
  ('Chemistry', 'Edexcel', 'alevel', 'T2', 'Kinetics, Equilibrium and Redox', 'What is a fuel cell?', 'A cell that converts the chemical energy of a fuel (e.g. hydrogen) and oxygen directly into electrical energy, producing water.', 15),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Give the equation for sodium reacting with oxygen.', '4Na + O2 → 2Na2O.', 1),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Why does the reactivity of Group 1 metals increase down the group?', 'The outer electron is further from the nucleus and more shielded, so it is lost more easily.', 2),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Give the equation for the thermal decomposition of lithium nitrate.', '4LiNO3 → 2Li2O + 4NO2 + O2 (Li behaves like Group 2, unlike other Group 1 nitrates).', 3),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Give the equation for thermal decomposition of sodium nitrate.', '2NaNO3 → 2NaNO2 + O2.', 4),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Why are Group 2 carbonates more thermally stable down the group?', 'Larger cations with the same charge have lower charge density, so they polarise the carbonate ion less.', 5),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'What are the flame test colours for Group 2?', 'Ca: brick red; Sr: crimson; Ba: apple green; Mg: no colour.', 6),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'What is the trend in reactivity of the halogens, and how is it shown?', 'Reactivity decreases down the group. A more reactive halogen displaces a less reactive halide from solution.', 7),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Give the colours of Cl2, Br2 and I2 in water and in cyclohexane.', 'Cl2: pale green in both. Br2: orange in water, orange/red in cyclohexane. I2: brown in water, purple in cyclohexane.', 8),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Give the equation for iodine reacting with thiosulfate in a titration.', 'I2 + 2S2O3^2− → 2I− + S4O6^2−. Starch is added near the endpoint; blue-black turns colourless.', 9),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Why is Cr2O7^2− orange and CrO4^2− yellow?', 'They are different chromium(VI) species in equilibrium. Adding acid gives orange dichromate; adding alkali gives yellow chromate.', 10),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Give the colours of V in its four oxidation states.', 'VO2+ (+5): yellow; VO2+ (+4): blue; V3+ (+3): green; V2+ (+2): violet.', 11),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'How is vanadium reduced from +5 to +2?', 'Zinc and acid: the colour changes yellow → blue → green → violet.', 12),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'Describe the reaction of [Cr(H2O)6]3+ with excess NaOH.', 'A grey-green precipitate of Cr(OH)3(H2O)3 forms, which dissolves in excess to give dark green [Cr(OH)6]3−.', 13),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'What is the shape of a [CuCl4]2− ion?', 'Tetrahedral (Cl− ligands are large, so only four fit).', 14),
  ('Chemistry', 'Edexcel', 'alevel', 'T3', 'Inorganic Chemistry', 'What is the test for sulfate ions?', 'Add acidified BaCl2 solution; a white precipitate of BaSO4 forms.', 15),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is a structural formula?', 'A formula showing the arrangement of atoms in a molecule without all the bonds, e.g. CH3CH2OH.', 1),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is a skeletal formula?', 'A formula showing the carbon skeleton as lines, with functional groups shown and H atoms on carbons omitted.', 2),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is geometric (E/Z) isomerism?', 'Stereoisomerism caused by restricted rotation about a C=C bond, where each carbon has two different groups.', 3),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'How are E and Z assigned using CIP rules?', 'Find the higher-priority group (higher atomic number) on each carbon of the C=C. Z: both on the same side. E: on opposite sides.', 4),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'Why are alkanes unreactive?', 'C–C and C–H bonds are strong and non-polar.', 5),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What are the three stages of free-radical substitution?', 'Initiation (UV splits Cl2 into radicals), propagation (radicals react with molecules and are regenerated), termination (two radicals combine).', 6),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What are the problems with free-radical substitution for synthesis?', 'It gives a mixture of products, including further substitution and isomers.', 7),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is formed when an alkene reacts with hydrogen?', 'An alkane, with a nickel catalyst at 150 °C (hydrogenation).', 8),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is formed when an alkene is oxidised by acidified KMnO4?', 'A diol; the purple solution turns colourless.', 9),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'Describe addition polymerisation.', 'Many alkene monomers join by breaking their C=C π bonds to form a long saturated polymer chain.', 10),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What are the environmental problems with polymers and the solutions?', 'They are non-biodegradable and fill landfill. Solutions: recycling, incinerating for energy, and biodegradable polymers.', 11),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is the mechanism for OH− with a primary halogenoalkane?', 'SN2: OH− attacks the δ+ carbon as the halide leaves in one step.', 12),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'How are halogenoalkanes compared using silver nitrate in ethanol?', 'The precipitate forms fastest for iodo, then bromo, then chloro, because the C–I bond is weakest.', 13),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'What is the product of heating an alcohol with PCl5?', 'A chloroalkane, POCl3 and HCl (steamy fumes; also a test for –OH).', 14),
  ('Chemistry', 'Edexcel', 'alevel', 'T4', 'Organic Chemistry I', 'How is a secondary alcohol oxidised, and what is observed?', 'Acidified K2Cr2O7, heated under reflux, gives a ketone; the colour turns from orange to green.', 15),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'What is the Born–Haber cycle used for?', 'Calculating a lattice energy from other measurable enthalpy changes using Hess''s law.', 1),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Define first electron affinity.', 'The enthalpy change when 1 mole of gaseous atoms each gains one electron to form 1 mole of gaseous 1− ions.', 2),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Why is the second electron affinity of oxygen endothermic?', 'The electron is added to a negative ion, so energy is needed to overcome the repulsion.', 3),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Define enthalpy change of atomisation.', 'The enthalpy change when 1 mole of gaseous atoms is formed from an element in its standard state.', 4),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'What does entropy measure?', 'The number of ways particles and their energy can be arranged (disorder).', 5),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Give the equation for the total entropy change.', 'ΔS_total = ΔS_system + ΔS_surroundings, where ΔS_surroundings = −ΔH/T.', 6),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'State the relationship between ΔG and K.', 'ΔG = −RT ln K.', 7),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Define a Brønsted–Lowry acid and base.', 'Acid: proton donor. Base: proton acceptor.', 8),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'What is a conjugate acid–base pair?', 'Two species differing by one proton, e.g. CH3COOH and CH3COO−.', 9),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Calculate the pH of 0.020 mol dm^-3 HCl.', 'pH = −log(0.020) = 1.70.', 10),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Why is pure water neutral at all temperatures even though pH changes?', '[H+] always equals [OH−], even though Kw (and so pH) changes with temperature.', 11),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'How is Ka found from a half-neutralisation point?', 'At half-neutralisation [HA] = [A−], so pH = pKa.', 12),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Give two uses of buffers.', 'Maintaining blood pH (carbonic acid/hydrogencarbonate) and shampoos, food and biological experiments.', 13),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'Why is phenolphthalein unsuitable for a weak base–strong acid titration?', 'Its colour change range (pH 8.3–10) is not within the steep vertical section, which is in the acidic region.', 14),
  ('Chemistry', 'Edexcel', 'alevel', 'T5', 'Thermodynamics, Acids & Bases', 'How does temperature affect the pH of pure water?', 'Ionisation is endothermic, so higher temperatures increase Kw and lower the pH, although the water stays neutral.', 15),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'What is the delocalised model of benzene?', 'A planar ring of 6 carbons, each sp2, with a ring of 6 delocalised π electrons above and below the plane; all C–C bonds are equal length.', 1),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'Give evidence against the Kekulé structure.', 'All C–C bonds are the same length, the enthalpy of hydrogenation is less exothermic than predicted, and benzene resists addition reactions.', 2),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'Describe Friedel–Crafts alkylation.', 'A halogenoalkane with an AlCl3 catalyst forms a carbocation electrophile, which substitutes onto the benzene ring.', 3),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'Give the reaction of phenol with bromine water.', 'White precipitate of 2,4,6-tribromophenol at room temperature, without a catalyst; bromine water is decolourised.', 4),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How are aldehydes and ketones reduced?', 'With LiAlH4 in dry ether (or NaBH4): aldehydes give primary alcohols and ketones give secondary alcohols.', 5),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'Give the test for methyl ketones.', 'The iodoform test: warm with iodine in alkali; a pale yellow precipitate of CHI3 forms.', 6),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How do carboxylic acids react with carbonates?', 'They form a salt, water and CO2 (effervescence).', 7),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How are acyl chlorides hydrolysed?', 'They react vigorously with cold water to form a carboxylic acid and steamy fumes of HCl.', 8),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'Give the mechanism type for acyl chloride reactions.', 'Nucleophilic addition–elimination.', 9),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How is an amide formed from an acyl chloride?', 'React with ammonia (primary amide) or an amine (N-substituted amide).', 10),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'What is the difference between primary, secondary and tertiary amines?', 'One, two or three hydrogen atoms of ammonia replaced by alkyl or aryl groups.', 11),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How are amino acids separated and identified?', 'By TLC or paper chromatography, using ninhydrin to show spots and comparing Rf values with known samples.', 12),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How do you plan a multi-step synthesis?', 'Identify the functional groups in the starting material and product, then use known reactions (e.g. substitution, oxidation, reduction) to link them, adding a carbon with KCN if needed.', 13),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'What is the purpose of recrystallisation?', 'To purify a solid: dissolve it in the minimum hot solvent, filter hot, cool to crystallise, then filter and dry.', 14),
  ('Chemistry', 'Edexcel', 'alevel', 'T6', 'Advanced Organic & Analysis', 'How is melting point used to check purity?', 'A pure substance melts sharply at its known melting point; impurities lower it and broaden the range.', 15)
),
fresh AS (
  SELECT v.* FROM v
  WHERE NOT EXISTS (
    SELECT 1 FROM flashcards f
    WHERE f.subject = v.subject AND f.exam_board = v.exam_board AND f.level = v.level
      AND f.topic_id = v.topic_id AND f.front = v.front)
),
cur AS (
  SELECT subject, exam_board, level, topic_id, count(*) AS n, max(card_order) AS mx
  FROM flashcards
  WHERE subject = 'Chemistry' AND exam_board = 'Edexcel' AND level = 'alevel'
  GROUP BY 1, 2, 3, 4
),
ranked AS (
  SELECT fr.*, coalesce(c.n, 0) AS n, coalesce(c.mx, 0) AS mx,
         row_number() OVER (PARTITION BY fr.topic_id ORDER BY fr.ord) AS rn
  FROM fresh fr
  LEFT JOIN cur c USING (subject, exam_board, level, topic_id)
)
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level)
SELECT subject, exam_board, topic_id, topic_name, front, back, mx + rn, level
FROM ranked
WHERE n + rn <= 30;
