-- Flashcard top-up: Geography|Eduqas|alevel — brings each topic up to 30 cards.
-- Generated by scripts/build-flashcard-topup.js from flashcards/topup/src/geography-eduqas-alevel.txt
-- Safe to re-run: skips fronts already present and never takes a topic past 30.
WITH v(subject, exam_board, level, topic_id, topic_name, front, back, ord) AS (VALUES
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is a tidal range?', 'The vertical difference between high and low tide.', 1),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is swash and backwash?', 'Swash is the movement of water up a beach after a wave breaks; backwash is the water returning down the beach.', 2),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is solution (corrosion) at the coast?', 'Chemical erosion where seawater dissolves soluble rocks such as limestone and chalk.', 3),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is traction and saltation?', 'Traction: large sediment rolled along the seabed. Saltation: smaller sediment bouncing along the seabed.', 4),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is a cliff profile influenced by?', 'Rock type, rock structure (dip, joints and faults), wave energy and sub-aerial processes.', 5),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is a cuspate foreland?', 'A triangular depositional landform formed where longshore drift from two directions meets, e.g. Dungeness.', 6),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is a barrier beach?', 'A ridge of sand or shingle parallel to the coast, separated from it by a lagoon.', 7),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is beach nourishment?', 'Adding sand or shingle to a beach to make it wider and higher, absorbing wave energy.', 8),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is a groyne?', 'A wooden or rock barrier built at right angles to the beach to trap sediment moved by longshore drift.', 9),
  ('Geography', 'Eduqas', 'alevel', '1.1', 'Coastal Landscapes', 'What is a rock armour (rip-rap)?', 'Large boulders placed at the foot of a cliff or along a beach to absorb wave energy.', 10),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is basal sliding?', 'The movement of a warm-based glacier over its bed, lubricated by meltwater.', 1),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is internal deformation?', 'Ice crystals deforming and sliding past each other under pressure, causing a glacier to flow.', 2),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is a warm-based glacier?', 'A glacier with its base at the pressure melting point, so meltwater allows basal sliding; found in temperate areas.', 3),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is a cold-based glacier?', 'A glacier frozen to its bed, moving mainly by internal deformation; found in polar areas.', 4),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is a ribbon lake?', 'A long, narrow lake in a glacial trough, formed where the glacier overdeepened a section of the valley floor.', 5),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is a terminal moraine?', 'A ridge of till deposited at the furthest point reached by a glacier.', 6),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is a kame?', 'A mound of sorted sand and gravel deposited by meltwater at the edge of or on a glacier.', 7),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is an outwash plain (sandur)?', 'A flat area of sorted sediment deposited by meltwater streams in front of a glacier.', 8),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is a pingo?', 'A periglacial ice-cored hill formed when groundwater freezes and expands, pushing the ground upwards.', 9),
  ('Geography', 'Eduqas', 'alevel', '1.2', 'Glaciated Landscapes', 'What is patterned ground?', 'Circles, polygons or stripes of stones formed by frost heave and sorting in periglacial areas.', 10),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is a place''s identity?', 'The distinctive characteristics that make a place unique, shaped by its people, history, economy and landscape.', 1),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is the role of economic restructuring in changing places?', 'Shifts from primary and secondary to tertiary and quaternary industries change employment and the built environment.', 2),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is the quaternary sector?', 'Knowledge-based industries such as research and development, IT and consultancy.', 3),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is a post-industrial economy?', 'An economy dominated by services and knowledge-based industries rather than manufacturing.', 4),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is deprivation?', 'A lack of access to income, jobs, housing, healthcare, education and services compared with others.', 5),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is social inequality?', 'Unequal access to resources, opportunities and outcomes between different groups.', 6),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is spatial inequality?', 'Differences in wealth, services and opportunities between areas.', 7),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is a cycle of deprivation?', 'Low income leads to poor housing, health and education, which in turn keeps people in poverty.', 8),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is regeneration?', 'Improving an area economically, socially and environmentally to reverse decline.', 9),
  ('Geography', 'Eduqas', 'alevel', '1.3', 'Changing Places', 'What is the role of heritage in rebranding places?', 'Promoting historical and cultural assets to attract tourism and investment.', 10),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is the global hydrological cycle?', 'A closed system of water moving between the oceans, atmosphere, land and ice.', 1),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is saturated overland flow?', 'Surface runoff that occurs when the soil is already saturated and can absorb no more water.', 2),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is infiltration-excess overland flow?', 'Surface runoff that occurs when rainfall intensity exceeds the infiltration capacity of the soil.', 3),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is baseflow?', 'The part of river discharge supplied by groundwater, which maintains flow during dry periods.', 4),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is a flashy hydrograph?', 'A hydrograph with a short lag time and high peak discharge, indicating rapid runoff.', 5),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is a water footprint?', 'The total volume of fresh water used to produce the goods and services consumed by an individual or country.', 6),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is virtual water?', 'The water embedded in the production of goods, e.g. food and clothing, traded between countries.', 7),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is groundwater depletion?', 'Extracting groundwater faster than it is recharged, lowering water tables.', 8),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is water conservation?', 'Reducing water use through efficient appliances, metering, recycling and education.', 9),
  ('Geography', 'Eduqas', 'alevel', '2.1', 'Water Cycle & Water Insecurity', 'What is a transboundary water conflict?', 'Disputes between countries sharing rivers or aquifers, e.g. the Nile or Mekong.', 10),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is a carbon sink?', 'A store that absorbs more carbon than it releases, e.g. oceans, forests and soils.', 1),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is a carbon source?', 'A store that releases more carbon than it absorbs, e.g. burning fossil fuels or deforestation.', 2),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is the enhanced greenhouse effect?', 'The increase in the natural greenhouse effect caused by human emissions of greenhouse gases, leading to global warming.', 3),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is energy mix?', 'The combination of different energy sources used by a country.', 4),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is energy intensity?', 'The amount of energy used per unit of GDP.', 5),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is nuclear power''s advantage and disadvantage?', 'Advantage: low-carbon, reliable electricity. Disadvantage: radioactive waste, high costs, and risk of accidents.', 6),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is the role of wind power in energy security?', 'It provides renewable, low-carbon electricity, reducing dependence on imports, but is intermittent.', 7),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is shale gas?', 'Natural gas trapped in shale rock, extracted by fracking.', 8),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is energy poverty?', 'Lack of access to modern energy services, or inability to afford adequate heating and power.', 9),
  ('Geography', 'Eduqas', 'alevel', '2.2', 'Carbon Cycle & Energy Security', 'What is a carbon tax?', 'A tax on the carbon content of fossil fuels to reduce emissions.', 10),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is voluntary migration?', 'Migration by choice, usually for economic, social or lifestyle reasons.', 1),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is forced migration?', 'Migration caused by conflict, persecution, disasters or development projects.', 2),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is an internally displaced person?', 'Someone forced to leave their home but who remains within their own country.', 3),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is the UNHCR?', 'The UN Refugee Agency, which protects and supports refugees and displaced people.', 4),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is a migrant stock?', 'The total number of international migrants living in a country at a given time.', 5),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is circular migration?', 'Repeated movement between source and host countries, often for seasonal work.', 6),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is a gravity model of migration?', 'A model predicting that migration between two places is proportional to their population sizes and inversely proportional to the distance between them.', 7),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is the Mediterranean migration route?', 'Routes across the Mediterranean from North Africa and the Middle East to Europe, often dangerous and irregular.', 8),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is xenophobia?', 'Fear or hatred of foreigners, which can lead to discrimination against migrants.', 9),
  ('Geography', 'Eduqas', 'alevel', '2.3', 'Global Migration', 'What is multiculturalism?', 'The coexistence of different cultures within a society, with each maintaining its identity.', 10),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is the continental shelf?', 'The shallow submerged edge of a continent; states have rights to its seabed resources under UNCLOS.', 1),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is territorial waters?', 'The sea within 12 nautical miles of a coast, over which a state has full sovereignty.', 2),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is an EEZ''s extent?', 'Up to 200 nautical miles from the coast, where a state has rights to exploit marine resources.', 3),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is the high seas?', 'Ocean areas beyond national jurisdiction, open to all states.', 4),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is illegal, unreported and unregulated (IUU) fishing?', 'Fishing that breaks laws, isn''t reported, or occurs in unregulated areas, undermining sustainable management.', 5),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is bycatch?', 'Unwanted fish and other marine species caught unintentionally during fishing.', 6),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is marine plastic pollution''s impact?', 'Wildlife entanglement and ingestion, microplastics entering food chains, and habitat damage.', 7),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is eutrophication in oceans?', 'Excess nutrients from farming runoff cause algal blooms and oxygen depletion, creating dead zones.', 8),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is the International Maritime Organization?', 'The UN agency regulating shipping safety, security and marine pollution.', 9),
  ('Geography', 'Eduqas', 'alevel', '2.4', 'Global Governance of Oceans', 'What is sustainable fishing?', 'Fishing at levels that allow fish stocks to regenerate, using quotas and protected areas.', 10),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is sustainable development?', 'Development that meets the needs of the present without compromising the ability of future generations to meet their own needs.', 1),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is the Brundtland Report?', 'The 1987 UN report that defined sustainable development.', 2),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is climate justice?', 'The idea that the impacts and responsibilities of climate change should be shared fairly, as the poorest often suffer most but contribute least.', 3),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is loss and damage?', 'Funding to help vulnerable countries cope with climate impacts they cannot adapt to, agreed at COP27.', 4),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is the circular economy?', 'An economic model that minimises waste by reusing, repairing and recycling materials.', 5),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is the digital divide?', 'Inequality in access to digital technology and the internet between and within countries.', 6),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is urbanisation''s challenge in the 21st century?', 'Providing housing, services, infrastructure and jobs for rapidly growing urban populations, especially in developing countries.', 7),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is antimicrobial resistance?', 'Microorganisms becoming resistant to antibiotics, a major global health threat.', 8),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is global governance?', 'Cooperation between states, international organisations and NGOs to address global issues.', 9),
  ('Geography', 'Eduqas', 'alevel', '2.5', '21st Century Challenges', 'What is the role of the IPCC?', 'The Intergovernmental Panel on Climate Change assesses scientific evidence on climate change and informs policy.', 10),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is a volcanic hazard?', 'A threat from volcanic activity, such as lava flows, ash fall, pyroclastic flows, lahars and gases.', 1),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is a tephra?', 'Fragments of rock and ash ejected into the air during an eruption.', 2),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is a primary effect of an earthquake?', 'An effect caused directly by ground shaking, e.g. buildings collapsing.', 3),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is a secondary effect of an earthquake?', 'An effect caused indirectly, e.g. fires, tsunamis, landslides and disease.', 4),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is the Modified Mercalli scale?', 'A scale measuring earthquake intensity by observed effects, from I to XII.', 5),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is a tsunami warning system?', 'A network of seismometers and ocean buoys that detects tsunamis and issues warnings.', 6),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is the role of education in hazard preparedness?', 'It teaches people what to do in a hazard event, e.g. earthquake drills, reducing casualties.', 7),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is the difference between a hazard and a disaster?', 'A hazard is a potential threat; a disaster occurs when a hazard seriously disrupts a community.', 8),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is the role of social factors in vulnerability?', 'Poverty, age, gender, education and poor housing increase vulnerability to hazards.', 9),
  ('Geography', 'Eduqas', 'alevel', '3.1', 'Tectonic Hazards', 'What is resilience?', 'The ability of a community to withstand, recover from and adapt to hazards.', 10),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is a food chain?', 'A sequence showing how energy is transferred from producers to consumers through feeding.', 1),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is a trophic level?', 'A position in a food chain: producer, primary consumer, secondary consumer and so on.', 2),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is net primary productivity?', 'The rate at which plants store energy as biomass, after respiration losses.', 3),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is the nutrient cycle?', 'The movement of nutrients between biomass, litter and soil.', 4),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is a climatic climax community?', 'The final stable community in succession, determined by the climate.', 5),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is an arrested succession?', 'When succession is prevented from reaching the climax by a factor such as grazing or burning.', 6),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is the role of fire in savanna ecosystems?', 'Fire maintains grassland by preventing tree growth and recycling nutrients.', 7),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is desertification?', 'Land degradation in dry areas caused by climate change and human activities such as overgrazing.', 8),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is the biodiversity hotspot concept?', 'Areas with very high numbers of endemic species that are under threat, prioritised for conservation.', 9),
  ('Geography', 'Eduqas', 'alevel', '3.2', 'Ecosystems', 'What is ecotourism?', 'Responsible tourism that conserves the environment and benefits local communities.', 10)
),
fresh AS (
  SELECT v.* FROM v
  WHERE NOT EXISTS (
    SELECT 1 FROM flashcards f
    WHERE f.subject = v.subject AND f.exam_board = v.exam_board AND f.level = v.level
      AND f.topic_id = v.topic_id AND f.front = v.front)
),
cur AS (
  SELECT subject, exam_board, level, topic_id, count(*) AS n, max(card_order) AS mx
  FROM flashcards
  WHERE subject = 'Geography' AND exam_board = 'Eduqas' AND level = 'alevel'
  GROUP BY 1, 2, 3, 4
),
ranked AS (
  SELECT fr.*, coalesce(c.n, 0) AS n, coalesce(c.mx, 0) AS mx,
         row_number() OVER (PARTITION BY fr.topic_id ORDER BY fr.ord) AS rn
  FROM fresh fr
  LEFT JOIN cur c USING (subject, exam_board, level, topic_id)
)
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level)
SELECT subject, exam_board, topic_id, topic_name, front, back, mx + rn, level
FROM ranked
WHERE n + rn <= 30;
