-- Flashcard top-up: Physics|OCR B|alevel — brings each topic up to 30 cards.
-- Generated by scripts/build-flashcard-topup.js from flashcards/topup/src/physics-ocr-b-alevel.txt
-- Safe to re-run: skips fronts already present and never takes a topic past 30.
WITH v(subject, exam_board, level, topic_id, topic_name, front, back, ord) AS (VALUES
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is resolution of an instrument?', 'The smallest change in the measured quantity that the instrument can detect.', 1),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is meant by the "spread" of a set of readings?', 'The range of the readings; half the spread (±) is used as an estimate of the uncertainty in the mean.', 2),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'How are uncertainties shown on a graph?', 'With error bars extending ± the uncertainty from each plotted point.', 3),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is systematic error and how can it be detected?', 'An error that shifts all readings by the same amount. It can be detected by a non-zero intercept on a graph expected to pass through the origin.', 4),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is the difference between sensitivity and resolution of a sensor?', 'Sensitivity is the change in output per unit change in input; resolution is the smallest input change that gives a detectable output change.', 5),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is response time of an instrument?', 'The time taken for the instrument to respond to a change in the quantity it is measuring.', 6),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What does a "zero error" mean?', 'The instrument does not read zero when the measured quantity is zero. It gives a systematic error, corrected by subtracting it.', 7),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'Why should the dependent variable be plotted on the y-axis?', 'By convention, so the gradient and intercept can be interpreted directly and relationships are easy to read.', 8),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is the purpose of repeating measurements?', 'To identify anomalies and to reduce the effect of random error by averaging.', 9),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is meant by a "fair test"?', 'Only the independent variable changes; all other variables that could affect the outcome are kept constant.', 10),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'How should you choose the range of an independent variable?', 'As wide as practical and safe, with evenly spaced values, so the whole relationship can be seen.', 11),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'How can the precision of a timing measurement be improved?', 'Use electronic timing (light gates or data loggers) and time multiple events.', 12),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What is a calibration curve?', 'A graph of instrument output against known values of the input, used to convert readings into measured values.', 13),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'Why is it important to state the uncertainty of a result?', 'It shows the range within which the true value is likely to lie, so results can be compared with accepted values or other experiments.', 14),
  ('Physics', 'OCR B', 'alevel', 'B1', 'Development of Practical Skills', 'What makes a conclusion valid?', 'It is supported by data from a fair, well-controlled experiment that measures what it claims to measure.', 15),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'How do you linearise T = 2π√(m/k) to find k?', 'Plot T^2 against m: gradient = 4π^2/k, so k = 4π^2/gradient.', 1),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'How can a straight-line graph through the origin show direct proportion?', 'If y ∝ x, the graph of y against x is a straight line that passes through the origin.', 2),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'What is the "worst acceptable line"?', 'The steepest or shallowest straight line that still passes through all the error bars, used to estimate the uncertainty in the gradient.', 3),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'How is percentage uncertainty in a gradient calculated?', '(|best gradient − worst gradient| ÷ best gradient) × 100%.', 4),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'Why take logs of both sides of y = kx^n?', 'log y = n log x + log k is the equation of a straight line, so plotting log y against log x gives gradient n and intercept log k.', 5),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'For N = N0 e^(−λt), what graph gives a straight line?', 'ln N against t: the gradient is −λ and the intercept is ln N0.', 6),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'What does the gradient of a distance–time graph represent?', 'Speed.', 7),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'What is the relationship between successive values in an exponential decay?', 'The ratio of successive values over equal time intervals is constant.', 8),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'How do you use a constant-ratio test to check for exponential behaviour?', 'Take readings at equal time intervals and divide each by the previous one. If the ratios are equal, the change is exponential.', 9),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'What does it mean if points on a graph show a curve when a straight line was predicted?', 'The proposed relationship is incorrect, or a systematic effect such as heating or friction becomes significant at extreme values.', 10),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'How is the mean of a set of values calculated, and what is its uncertainty?', 'The sum divided by the number of values; the uncertainty is roughly half the range.', 11),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'Why use a spreadsheet to model data?', 'It lets you calculate derived quantities quickly, test different models and plot graphs to compare with experimental results.', 12),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'What is an order-of-magnitude calculation?', 'An estimate to the nearest power of ten, used to check whether results or predictions are reasonable.', 13),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'How is the percentage difference between an experimental value and an accepted value calculated?', '(|experimental − accepted| ÷ accepted) × 100%.', 14),
  ('Physics', 'OCR B', 'alevel', 'B2', 'Fundamental Data Analysis', 'When should a result be quoted to fewer significant figures?', 'When the uncertainty is large, the number of significant figures should reflect the uncertainty (e.g. 9.8 ± 0.3 m s^-2, not 9.8127).', 15),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is signal-to-noise ratio?', 'The ratio of the strength of the wanted signal to the unwanted noise. A higher ratio gives a clearer signal.', 1),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is the minimum sampling rate for a signal?', 'At least twice the highest frequency present in the signal (the Nyquist condition).', 2),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is bandwidth?', 'The range of frequencies a signal occupies or a channel can transmit. A higher bandwidth allows a higher bit rate.', 3),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'State the relationship between bit rate, samples per second and bits per sample.', 'Bit rate = samples per second × bits per sample.', 4),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'How much information is carried by an image of N pixels, each with b bits?', 'Total information = N × b bits.', 5),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is the magnification of a lens?', 'Image size ÷ object size, which also equals image distance ÷ object distance (v/u).', 6),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'State the lens equation using the Cartesian convention.', '1/v = 1/u + 1/f, with distances measured from the lens (u is negative for a real object).', 7),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'Define the power of a lens.', 'Power = 1/f, with f in metres; unit dioptre (D).', 8),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'How does a potential divider make a sensing circuit?', 'A sensor such as a thermistor or LDR is paired with a fixed resistor. As the sensor''s resistance changes, the output pd changes.', 9),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is conductance, and how does it combine?', 'G = 1/R, with unit siemens (S). Conductances in parallel add: G = G1 + G2.', 10),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is the relationship between EMF, terminal pd and internal resistance?', 'V = ε − Ir.', 11),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is the difference between a strong and a stiff material?', 'Strong: high breaking stress. Stiff: high Young modulus (small strain for a given stress).', 12),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'How does a metal deform plastically at the microscopic level?', 'Dislocations in the crystal lattice move under stress, allowing planes of atoms to slip past each other.', 13),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'Why are composite materials such as reinforced concrete useful?', 'They combine the properties of materials: concrete is strong in compression, steel is strong in tension.', 14),
  ('Physics', 'OCR B', 'alevel', 'B3', 'Physics in Action', 'What is noise in an image, and how can it be reduced?', 'Random variation in pixel values. It can be reduced by replacing each pixel with the median of its neighbours (median filter).', 15),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What is a phasor?', 'A rotating arrow whose length is the amplitude and whose angle is the phase, used to add waves with different phases.', 1),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'How do you find the resultant amplitude from phasors?', 'Add the phasors tip to tail; the resultant from start to end gives the amplitude and phase of the combined wave.', 2),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What is the condition for a maximum in a two-slit pattern using phasors?', 'The phasors from each slit line up (path difference = nλ), giving a large resultant.', 3),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What is the condition for a minimum using path difference?', 'Path difference = (n + ½)λ, so the phasors point in opposite directions and cancel.', 4),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'State the fringe-spacing equation for a double slit.', 'λ = xd/L, where x is fringe spacing, d slit separation and L the distance to the screen.', 5),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What is the photon energy of green light of wavelength 500 nm?', 'E = hc/λ = (6.63 × 10^-34 × 3.00 × 10^8)/(500 × 10^-9) ≈ 4.0 × 10^-19 J (about 2.5 eV).', 6),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What evidence shows electrons behave as waves?', 'Electron diffraction: electrons passed through thin graphite produce rings, a diffraction pattern.', 7),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'How does the quantum "explore all paths" idea explain light travelling in straight lines?', 'Phasors for paths far from the straight line curl up and cancel. Only paths near the straight (least-time) route add, so light appears to travel in a straight line.', 8),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What is the difference between speed and velocity?', 'Speed is a scalar (rate of change of distance); velocity is a vector (rate of change of displacement).', 9),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'How do you add two perpendicular velocities?', 'Magnitude = √(v1^2 + v2^2); direction θ = tan^-1(v2/v1).', 10),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'How is the motion of a projectile analysed?', 'Horizontal velocity is constant; vertical motion has constant acceleration g. They are treated independently and linked by time.', 11),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'Define work done by a force.', 'Work = force × displacement in the direction of the force: W = Fs cos θ.', 12),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'State the principle of conservation of momentum.', 'The total momentum of a system is constant unless an external resultant force acts.', 13),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'How can iterative (step-by-step) modelling predict motion?', 'Using small time steps: new v = v + aΔt and new s = s + vΔt, with a recalculated each step from the forces.', 14),
  ('Physics', 'OCR B', 'alevel', 'B4', 'Understanding Processes', 'What is the relationship between power and velocity for a constant force?', 'P = Fv.', 15),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What does the Boltzmann factor e^(−E/kT) represent?', 'The ratio of the number of particles in a state of energy E to those in the ground state; it estimates the fraction of particles with at least energy E.', 1),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'Why does a small rise in temperature greatly increase a reaction rate?', 'The Boltzmann factor depends exponentially on 1/T, so the fraction of particles with enough activation energy rises sharply.', 2),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'How is capacitor discharge modelled iteratively?', 'ΔQ = −(Q/RC)Δt: the change in charge each small time step is proportional to the charge remaining.', 3),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'State the capacitor discharge equation.', 'Q = Q0 e^(−t/RC).', 4),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What is the time constant and what fraction remains after one time constant?', 'τ = RC; after one time constant about 37% (1/e) of the charge remains.', 5),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What is the radioactive decay equation in terms of activity?', 'A = A0 e^(−λt), and A = λN.', 6),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'Compare the models for radioactive decay and capacitor discharge.', 'Both are exponential: the rate of decrease is proportional to the amount remaining (dN/dt = −λN; dQ/dt = −Q/RC).', 7),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What is the gravitational potential energy of two masses?', 'E = −GMm/r (zero at infinity).', 8),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'State Kepler''s third law for circular orbits.', 'T^2 = (4π^2/GM)r^3: T^2 is proportional to r^3.', 9),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What is cosmological redshift and how is it calculated?', 'The stretching of light from distant galaxies by the expansion of space: z = Δλ/λ ≈ v/c.', 10),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'State Hubble''s law.', 'v = H0 d: the recession speed of a galaxy is proportional to its distance.', 11),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What evidence supports the Big Bang?', 'The redshift of distant galaxies (expansion) and the cosmic microwave background radiation.', 12),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'What is the cosmic microwave background?', 'Radiation left from the early hot universe, now redshifted to microwave wavelengths, corresponding to about 2.7 K.', 13),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'Why does an ideal gas obey pV = NkT?', 'Molecules move randomly with negligible volume and no intermolecular forces except in collisions, so pressure comes only from collisions with the walls.', 14),
  ('Physics', 'OCR B', 'alevel', 'B5', 'Rise and Fall of the Clockwork Universe', 'State the relationship between mean molecular kinetic energy and temperature.', '(1/2)m(c_rms)^2 = (3/2)kT.', 15),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is the relationship between field strength and potential gradient?', 'E = −dV/dr: field strength is minus the potential gradient.', 1),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What are equipotential surfaces?', 'Surfaces joining points of equal potential. They are perpendicular to field lines, and no work is done moving along them.', 2),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'Describe the motion of an electron in a uniform electric field between plates.', 'It accelerates towards the positive plate; if it enters at right angles to the field it follows a parabolic path.', 3),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is the electronvolt?', 'The energy gained by one electron accelerated through 1 V: 1.6 × 10^-19 J.', 4),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is flux linkage and how is induced EMF related to it?', 'Flux linkage = NΦ. The induced EMF = −d(NΦ)/dt.', 5),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'How do eddy currents reduce transformer efficiency, and how are they reduced?', 'Induced currents in the iron core heat it, wasting energy. Laminating the core reduces them.', 6),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is magnetic flux density?', 'B = F/(IL): the force per unit current per unit length on a wire at right angles to the field, measured in tesla.', 7),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What did Rutherford scattering show?', 'The atom has a small, dense, positively charged nucleus, since a few α particles were scattered through large angles.', 8),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'Why do high-energy electrons probe nuclear structure?', 'Their de Broglie wavelength is comparable to nuclear size (about 10^-15 m), and they are unaffected by the strong force.', 9),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is the de Broglie wavelength of a particle with kinetic energy E?', 'λ = h/p, where p = √(2mE) at non-relativistic speeds.', 10),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'Why are particle accelerators so large?', 'Particles need very high energies for small wavelengths and to create massive particles (E = mc^2), which needs long accelerating distances or large rings.', 11),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is the relativistic factor γ?', 'γ = 1/√(1 − v^2/c^2). Total energy E = γmc^2 increases without limit as v approaches c.', 12),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'Describe pair production and annihilation.', 'Pair production: a photon of at least 2mc^2 creates a particle and its antiparticle. Annihilation: a particle and its antiparticle meet and turn into photons.', 13),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'What is absorbed dose and its unit?', 'Energy absorbed per unit mass of tissue, measured in gray (Gy = J kg^-1).', 14),
  ('Physics', 'OCR B', 'alevel', 'B6', 'Field and Particle Physics', 'How is effective dose calculated?', 'Effective dose (Sv) = absorbed dose × radiation weighting factor (quality factor), accounting for the harm caused by different radiations.', 15)
),
fresh AS (
  SELECT v.* FROM v
  WHERE NOT EXISTS (
    SELECT 1 FROM flashcards f
    WHERE f.subject = v.subject AND f.exam_board = v.exam_board AND f.level = v.level
      AND f.topic_id = v.topic_id AND f.front = v.front)
),
cur AS (
  SELECT subject, exam_board, level, topic_id, count(*) AS n, max(card_order) AS mx
  FROM flashcards
  WHERE subject = 'Physics' AND exam_board = 'OCR B' AND level = 'alevel'
  GROUP BY 1, 2, 3, 4
),
ranked AS (
  SELECT fr.*, coalesce(c.n, 0) AS n, coalesce(c.mx, 0) AS mx,
         row_number() OVER (PARTITION BY fr.topic_id ORDER BY fr.ord) AS rn
  FROM fresh fr
  LEFT JOIN cur c USING (subject, exam_board, level, topic_id)
)
INSERT INTO flashcards (subject, exam_board, topic_id, topic_name, front, back, card_order, level)
SELECT subject, exam_board, topic_id, topic_name, front, back, mx + rn, level
FROM ranked
WHERE n + rn <= 30;
