/*
 * OCR A-Level Physics A (H556) — MCQ Diagnostic Question Bank
 * 50 questions per topic: 20 green (recall/basic), 20 amber (application), 10 red (analysis/evaluate)
 * M1 (Practical Skills): 25 questions: 10 green, 10 amber, 5 red
 * Diagnostic picks 2 green + 2 amber + 1 red = 5 questions at random.
 * answer: 0-based index of correct option.
 */

const PHYSICS_OCR_A_QUESTIONS = {

  /* ─────────────────────────────────────────────────────────── M1 */
  'M1': {
    name: 'Practical Skills in Physics',
    green: [
      { q: 'What is the independent variable in an experiment?', options: ['The variable that is measured','The variable that is deliberately changed','The variable that is kept constant','The variable that cannot be controlled'], answer: 1 },
      { q: 'What is a dependent variable?', options: ['The variable deliberately changed by the experimenter','A variable kept constant throughout','The variable that is measured as a result of changes to the independent variable','A variable that has no effect on the experiment'], answer: 2 },
      { q: 'What are control variables?', options: ['Variables that are measured','Variables deliberately changed','Variables kept constant to ensure a fair test','Variables that are plotted on a graph'], answer: 2 },
      { q: 'What does the gradient of a straight-line graph represent?', options: ['The y-intercept','The ratio of change in y to change in x','The area under the graph','The mean of the data'], answer: 1 },
      { q: 'How many significant figures should a final answer typically be given to?', options: ['More than the raw data','The same as the least precise measurement used','Always 1 significant figure','Always 5 significant figures'], answer: 1 },
      { q: 'What is meant by the resolution of a measuring instrument?', options: ['Its accuracy','The smallest change it can detect','Its range','Its precision'], answer: 1 },
      { q: 'What is a systematic error?', options: ['A random fluctuation in readings','An error that varies unpredictably','A consistent error in the same direction in every reading','An error caused by human reaction time only'], answer: 2 },
      { q: 'What is a random error?', options: ['An error that affects all readings equally','An unpredictable variation between measurements','An error caused by a faulty instrument','An error that can be eliminated by calibration'], answer: 1 },
      { q: 'What does a line of best fit on a graph show?', options: ['The exact data points','The general trend of the data','Only the outliers','The random errors'], answer: 1 },
      { q: 'What is the purpose of repeating measurements?', options: ['To introduce systematic errors','To identify and reduce the effect of random errors','To change the independent variable','To increase the range of data'], answer: 1 },
    ],
    amber: [
      { q: 'A student measures the diameter of a wire as 0.52 mm using a micrometer with a resolution of 0.01 mm. What is the percentage uncertainty in this measurement?', options: ['0.01%','0.96%','1.92%','5.2%'], answer: 2 },
      { q: 'The percentage uncertainty in a length is 2% and in a time is 3%. What is the percentage uncertainty in speed (length/time)?', options: ['1%','5%','6%','9%'], answer: 1 },
      { q: 'A graph of extension (y-axis) against force (x-axis) gives a straight line through the origin. What does the gradient represent?', options: ['The spring constant k','1/k (the compliance)','The elastic potential energy','The force constant squared'], answer: 1 },
      { q: 'Which of the following best reduces systematic error?', options: ['Taking more repeat readings','Calibrating the instrument against a known standard','Plotting a graph','Using a larger range of values'], answer: 1 },
      { q: 'A student plots ln(V) against time t and obtains a straight line with gradient -0.05 s⁻¹. If V = V₀e^(-t/RC), what is the time constant RC?', options: ['0.05 s','20 s','-0.05 s','50 s'], answer: 1 },
      { q: 'When multiplying two quantities, how are percentage uncertainties combined?', options: ['Subtract the percentage uncertainties','Add the percentage uncertainties','Square the percentage uncertainties','Take the mean of the percentage uncertainties'], answer: 1 },
      { q: 'A student raises a quantity with uncertainty to a power n. How does the percentage uncertainty change?', options: ['It stays the same','It is multiplied by n','It is divided by n','It is raised to the power n'], answer: 1 },
      { q: 'On a graph, error bars on a data point represent:', options: ['The range of the independent variable','The absolute uncertainty in the measurement','The percentage uncertainty only','The systematic error'], answer: 1 },
      { q: 'To determine the uncertainty in the gradient of a graph, a student should draw:', options: ['Only the line of best fit','The steepest and shallowest lines that pass through the error bars','A horizontal line','A curved line through all points'], answer: 1 },
      { q: 'A student needs to verify that T² is proportional to l for a pendulum. Which graph should they plot?', options: ['T against l','T² against l','T against l²','ln T against ln l'], answer: 1 },
    ],
    red: [
      { q: 'A student measures g using a pendulum. Their result is 9.72 ± 0.15 m s⁻². The accepted value is 9.81 m s⁻². Which statement is correct?', options: ['The uncertainty is too large to draw any conclusion','The experiment is inaccurate because 9.81 is outside the uncertainty range','The experiment has high precision but is definitely inaccurate','The experiment is accurate because 9.81 falls within the uncertainty range 9.57–9.87'], answer: 3 },
      { q: 'A log-log graph of y against x gives a straight line with gradient 2 and y-intercept ln(3). What is the relationship?', options: ['y = 2x + 3','y = 3x²','y = 3e^(2x)','y = 2 ln(x) + 3'], answer: 1 },
      { q: 'An experiment to measure the speed of sound gives results: 338, 342, 340, 339, 341 m s⁻¹. The true value is 343 m s⁻¹. What can be said about the data?', options: ['High accuracy, low precision','Low accuracy, high precision','High accuracy, high precision','Low accuracy, low precision'], answer: 1 },
      { q: 'In an experiment, the percentage uncertainty in radius r is 3%. If the quantity being calculated is V = (4/3)πr³, what is the percentage uncertainty in V?', options: ['9%','27%','3%','6%'], answer: 0 },
      { q: 'A student evaluates an experiment and finds the percentage difference from the accepted value is 1.5%, but the total percentage uncertainty is 5%. What should they conclude?', options: ['The random error is 5%','The experiment is invalid','The systematic error is 1.5%','The result is consistent with the accepted value since the'], answer: 3 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── M2 */
  'M2': {
    name: 'Foundations of Physics',
    green: [
      { q: 'Which of the following is an SI base unit?', options: ['Newton','Joule','Kilogram','Watt'], answer: 2 },
      { q: 'What are the SI base units for mass, length, and time?', options: ['g, cm, s','kg, m, s','kg, km, min','lb, ft, s'], answer: 1 },
      { q: 'What is the SI base unit of electric current?', options: ['Coulomb','Volt','Ampere','Ohm'], answer: 2 },
      { q: 'What is the SI base unit of temperature?', options: ['Celsius','Fahrenheit','Kelvin','Joule'], answer: 2 },
      { q: 'What is the SI base unit of amount of substance?', options: ['Gram','Kilogram','Atom','Mole'], answer: 3 },
      { q: 'What does the prefix "mega" (M) represent?', options: ['10³','10⁶','10⁹','10¹²'], answer: 1 },
      { q: 'What does the prefix "nano" (n) represent?', options: ['10⁻³','10⁻⁶','10⁻⁹','10⁻¹²'], answer: 2 },
      { q: 'What does the prefix "micro" (μ) represent?', options: ['10⁻²','10⁻³','10⁻⁶','10⁻⁹'], answer: 2 },
      { q: 'Which of these is a scalar quantity?', options: ['Velocity','Force','Displacement','Speed'], answer: 3 },
      { q: 'Which of these is a vector quantity?', options: ['Mass','Temperature','Energy','Acceleration'], answer: 3 },
      { q: 'What is the difference between a scalar and a vector?', options: ['Scalars are always larger','Vectors have both magnitude and direction; scalars have magnitude only','Scalars have direction; vectors do not','There is no difference'], answer: 1 },
      { q: 'What is 5.0 km in metres?', options: ['50 m','500 m','5000 m','50000 m'], answer: 2 },
      { q: 'What is 3.2 μm in metres?', options: ['3.2 × 10⁻³ m','3.2 × 10⁻⁶ m','3.2 × 10⁻⁹ m','3.2 × 10⁻² m'], answer: 1 },
      { q: 'Express 1 newton in SI base units.', options: ['kg m s⁻¹','kg m s⁻²','kg m² s⁻²','kg m² s⁻¹'], answer: 1 },
      { q: 'Express 1 joule in SI base units.', options: ['kg m s⁻²','kg m² s⁻²','kg m² s⁻³','kg m s⁻¹'], answer: 1 },
      { q: 'What is the prefix for 10⁻³?', options: ['centi','milli','micro','nano'], answer: 1 },
      { q: 'What is the prefix for 10⁹?', options: ['Mega','Giga','Tera','Kilo'], answer: 1 },
      { q: 'Which of these is a derived unit?', options: ['Kilogram','Metre','Second','Newton'], answer: 3 },
      { q: 'What is meant by estimation in physics?', options: ['Guessing randomly','Making an approximate calculation using reasonable assumptions','Measuring with high precision','Ignoring significant figures'], answer: 1 },
      { q: 'What does "homogeneity of an equation" mean?', options: ['The equation is balanced numerically','Both sides of the equation have the same units','The equation uses only SI units','The equation has no constants'], answer: 1 },
    ],
    amber: [
      { q: 'Check the homogeneity of E = mc². If E has units kg m² s⁻², what are the units of mc²?', options: ['kg m s⁻²','kg m² s⁻²','kg² m² s⁻²','kg m² s⁻¹'], answer: 1 },
      { q: 'The equation for pressure is P = F/A. Express the pascal in SI base units.', options: ['kg m⁻¹ s⁻²','kg m s⁻²','kg m² s⁻²','kg m⁻² s⁻¹'], answer: 0 },
      { q: 'A force of 5.0 N acts at 30° to the horizontal. What is the horizontal component?', options: ['2.5 N','4.3 N','5.0 N','10 N'], answer: 1 },
      { q: 'A force of 5.0 N acts at 30° to the horizontal. What is the vertical component?', options: ['2.5 N','4.3 N','5.0 N','1.0 N'], answer: 0 },
      { q: 'Two vectors of 3 N and 4 N act at right angles. What is the magnitude of the resultant?', options: ['1 N','5 N','7 N','12 N'], answer: 1 },
      { q: 'Which of these equations is NOT homogeneous? (v = velocity, a = acceleration, t = time, s = displacement)', options: ['v = u + at','s = ut + ½at²','v² = u² + 2as','v = u + ½at²'], answer: 3 },
      { q: 'A vector of magnitude 10 N acts at 60° above the horizontal. What is its vertical component?', options: ['5.0 N','7.1 N','8.7 N','10 N'], answer: 2 },
      { q: 'What is the resultant of two forces of 6 N and 8 N acting at right angles?', options: ['2 N','10 N','14 N','48 N'], answer: 1 },
      { q: 'Convert 2.5 GHz to Hz.', options: ['2.5 × 10³ Hz','2.5 × 10⁶ Hz','2.5 × 10⁹ Hz','2.5 × 10¹² Hz'], answer: 2 },
      { q: 'Express the watt in SI base units.', options: ['kg m² s⁻²','kg m² s⁻³','kg m s⁻²','kg m s⁻³'], answer: 1 },
      { q: 'Estimate the order of magnitude of the height of a person in metres.', options: ['10⁻¹ m','10⁰ m','10¹ m','10² m'], answer: 1 },
      { q: 'Two perpendicular forces of 5 N and 12 N act on an object. What angle does the resultant make with the 12 N force?', options: ['22.6°','67.4°','45°','90°'], answer: 0 },
      { q: 'A student checks whether v = √(2gh) is homogeneous. What are the units of √(2gh)?', options: ['m s⁻¹','m s⁻²','m² s⁻²','m'], answer: 0 },
      { q: 'Express the unit of electrical resistance (ohm) in SI base units.', options: ['kg m² s⁻³ A⁻²','kg m s⁻² A⁻¹','kg m² s⁻² A⁻²','kg m² s⁻¹ A⁻²'], answer: 0 },
      { q: 'What is the order of magnitude of the mass of the Earth (approximately 6 × 10²⁴ kg)?', options: ['10²³ kg','10²⁴ kg','10²⁵ kg','10⁶ kg'], answer: 2 },
      { q: 'Resolve a velocity of 20 m s⁻¹ at 45° to the horizontal into horizontal and vertical components.', options: ['14.1 m s⁻¹ each','10 m s⁻¹ each','20 m s⁻¹ each','17.3 m s⁻¹ and 10 m s⁻¹'], answer: 0 },
      { q: 'Express the volt in SI base units.', options: ['kg m² s⁻³ A⁻¹','kg m s⁻² A⁻¹','kg m² s⁻² A⁻¹','kg m² s⁻³ A⁻²'], answer: 0 },
      { q: 'A boat travels 3 km north then 4 km east. What is the magnitude of the displacement?', options: ['7 km','5 km','1 km','12 km'], answer: 1 },
      { q: 'Is kinetic energy a scalar or a vector quantity?', options: ['Vector because it depends on velocity','Scalar because it has magnitude but no direction','Neither','It depends on the reference frame'], answer: 1 },
      { q: 'What is the resultant of two 10 N forces acting at 60° to each other?', options: ['10 N','17.3 N','20 N','14.1 N'], answer: 1 },
    ],
    red: [
      { q: 'The equation F = Aρv² relates force F to area A, density ρ and speed v. Show this is homogeneous by checking units. Which units does the right-hand side give?', options: ['kg m s⁻²','kg m⁻¹ s⁻²','kg m² s⁻²','kg m⁻² s⁻¹'], answer: 0 },
      { q: 'An equation is given as v = 2πr/T. A student claims this proves the equation must be correct. Why is this claim invalid?', options: ['Homogeneity checks can show an equation is wrong','The equation is actually incorrect','The equation has the wrong units','The student has not checked the dimensions'], answer: 0 },
      { q: 'Estimate the number of atoms in a human body (mass ~70 kg, average atomic mass ~10⁻²⁶ kg). Which order of magnitude is closest?', options: ['10²⁰','10²⁵','10²⁸','10³⁵'], answer: 2 },
      { q: 'Three coplanar forces of 5 N, 8 N, and 10 N act on a point. The 5 N and 8 N forces are perpendicular. The 10 N force acts at 180° to the resultant of the other two. What is the net force?', options: ['0.6 N away from the 10 N direction','0.6 N in the direction of the resultant of 5 N and 8 N','9.4 N in the direction of the 10 N force','23 N'], answer: 0 },
      { q: 'The drag force on a sphere is given by F = kηrv, where η is viscosity (Pa s), r is radius, and v is speed. What are the units of the dimensionless constant k?', options: ['m⁻¹ s','No units — k is dimensionless','Pa s m','kg m s⁻¹'], answer: 1 },
      { q: 'Estimate the pressure exerted on the floor by a person standing on one foot. Use reasonable estimates for mass (~70 kg) and foot area (~200 cm²).', options: ['~35000 Pa','~350 Pa','~3500 Pa','~350000 Pa'], answer: 0 },
      { q: 'A student derives an expression for the period of a pendulum as T = 2π√(l/g). By checking dimensions, which side has units of seconds?', options: ['Only the left side','Only the right side','Both sides — the equation is dimensionally consistent','Neither side'], answer: 2 },
      { q: 'A vector A has magnitude 15 N at 30° to the x-axis, and vector B has magnitude 10 N at 120° to the x-axis. What is the x-component of A + B?', options: ['18.0 N','25 N','3.0 N','8.0 N'], answer: 3 },
      { q: 'The equation for energy stored in a spring is E = ½kx². Using base units, express the unit of k (the spring constant).', options: ['kg m² s⁻²','kg s⁻²','kg m s⁻²','kg m⁻¹ s⁻²'], answer: 1 },
      { q: 'A student estimates the power output of a human climbing stairs. If a 70 kg person climbs 3 m in 5 s, which order of magnitude is the power?', options: ['10¹ W','10² W','10³ W','10⁴ W'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── M3 */
  'M3': {
    name: 'Forces and Motion',
    green: [
      { q: 'What does the gradient of a displacement-time graph represent?', options: ['Acceleration','Velocity','Force','Distance'], answer: 1 },
      { q: 'What does the gradient of a velocity-time graph represent?', options: ['Velocity','Displacement','Acceleration','Force'], answer: 2 },
      { q: 'What does the area under a velocity-time graph represent?', options: ['Acceleration','Velocity','Displacement','Force'], answer: 2 },
      { q: 'State Newton\'s first law of motion.', options: ['F = ma','An object remains at rest or in uniform motion unless acted on by a resultant force','Every action has an equal and opposite reaction','Force equals rate of change of momentum'], answer: 1 },
      { q: 'State Newton\'s second law of motion.', options: ['Objects at rest stay at rest','The resultant force on an object equals the product of its mass and acceleration','Every action has an equal and opposite reaction','Momentum is always conserved'], answer: 1 },
      { q: 'State Newton\'s third law of motion.', options: ['F = ma','Objects at rest stay at rest','When body A exerts a force on body B, body B exerts an equal and opposite force on body A','Force equals rate of change of momentum'], answer: 2 },
      { q: 'What is the unit of momentum?', options: ['N','kg m s⁻¹','J','kg m s⁻²'], answer: 1 },
      { q: 'What is meant by terminal velocity?', options: ['The maximum velocity an object can ever reach','The velocity at which drag equals the driving force, so acceleration is zero','The velocity at which an object stops','The initial velocity of a falling object'], answer: 1 },
      { q: 'What is the equation for work done?', options: ['W = Fs cos θ','W = Fv','W = ½mv²','W = mgh/t'], answer: 0 },
      { q: 'What is the equation for kinetic energy?', options: ['E = mgh','E = ½mv²','E = Fs','E = Pt'], answer: 1 },
      { q: 'What is the equation for gravitational potential energy (near Earth\'s surface)?', options: ['E = ½mv²','E = mgh','E = mc²','E = Fs'], answer: 1 },
      { q: 'Define power.', options: ['The total energy of a system','The rate of doing work or transferring energy','The force applied over a distance','The momentum per unit time'], answer: 1 },
      { q: 'What is the unit of power?', options: ['Joule','Newton','Watt','Pascal'], answer: 2 },
      { q: 'What is efficiency defined as?', options: ['Total energy input','(Useful output energy / Total input energy) × 100%','Power × time','Work done × velocity'], answer: 1 },
      { q: 'What is the equation for momentum?', options: ['p = Ft','p = mv','p = ½mv²','p = ma'], answer: 1 },
      { q: 'In a closed system with no external forces, what happens to total momentum?', options: ['It increases','It decreases','It is conserved','It doubles'], answer: 2 },
      { q: 'Which SUVAT equation links v, u, a, and t?', options: ['s = ut + ½at²','v = u + at','v² = u² + 2as','s = ½(u+v)t'], answer: 1 },
      { q: 'What is impulse?', options: ['Force × velocity','Force × time = change in momentum','Mass × acceleration','Energy per unit time'], answer: 1 },
      { q: 'A car accelerates from rest at 2 m s⁻². What is its velocity after 5 s?', options: ['2.5 m s⁻¹','7 m s⁻¹','10 m s⁻¹','25 m s⁻¹'], answer: 2 },
      { q: 'What is the acceleration due to gravity near Earth\'s surface?', options: ['8.9 m s⁻²','9.81 m s⁻²','10.8 m s⁻²','6.67 m s⁻²'], answer: 1 },
    ],
    amber: [
      { q: 'A ball is thrown horizontally at 15 m s⁻¹ from a cliff. What is its horizontal velocity after 2 s (ignoring air resistance)?', options: ['5 m s⁻¹','10 m s⁻¹','15 m s⁻¹','19.6 m s⁻¹'], answer: 2 },
      { q: 'A projectile is launched at 30° to the horizontal at 20 m s⁻¹. What is the initial vertical component of velocity?', options: ['10 m s⁻¹','17.3 m s⁻¹','20 m s⁻¹','14.1 m s⁻¹'], answer: 0 },
      { q: 'A 1200 kg car decelerates from 30 m s⁻¹ to rest in 6 s. What is the braking force?', options: ['200 N','3600 N','6000 N','36000 N'], answer: 2 },
      { q: 'A 0.5 kg ball hits a wall at 8 m s⁻¹ and bounces back at 6 m s⁻¹. What is the change in momentum?', options: ['1 kg m s⁻¹','7 kg m s⁻¹','-7 kg m s⁻¹','14 kg m s⁻¹'], answer: 2 },
      { q: 'A force of 50 N acts on a 10 kg object on a frictionless surface. What is the acceleration?', options: ['0.2 m s⁻²','5 m s⁻²','50 m s⁻²','500 m s⁻²'], answer: 1 },
      { q: 'An object falls from rest. How far does it fall in 3 s? (g = 9.81 m s⁻²)', options: ['14.7 m','29.4 m','44.1 m','88.3 m'], answer: 2 },
      { q: 'A 2 kg object moves at 3 m s⁻¹. What is its kinetic energy?', options: ['3 J','6 J','9 J','18 J'], answer: 2 },
      { q: 'A 60 kg person climbs a 10 m ladder. What is the gain in GPE? (g = 9.81 m s⁻²)', options: ['600 J','5886 J','60 J','588.6 J'], answer: 1 },
      { q: 'A force of 200 N is applied at 60° to the direction of motion over 5 m. What is the work done?', options: ['1000 J','866 J','500 J','250 J'], answer: 2 },
      { q: 'A machine has an input power of 500 W and an efficiency of 80%. What is the useful output power?', options: ['100 W','400 W','625 W','500 W'], answer: 1 },
      { q: 'A car of mass 1000 kg travels at 20 m s⁻¹. What is its kinetic energy?', options: ['10 000 J','20 000 J','200 000 J','400 000 J'], answer: 2 },
      { q: 'Two objects undergo a perfectly elastic collision. Which quantity is conserved in addition to momentum?', options: ['Force','Kinetic energy','Potential energy','Impulse'], answer: 1 },
      { q: 'A 5 kg trolley moving at 4 m s⁻¹ collides with a stationary 3 kg trolley and they stick together. What is their common velocity?', options: ['1.5 m s⁻¹','2.5 m s⁻¹','4 m s⁻¹','20 m s⁻¹'], answer: 1 },
      { q: 'A car engine provides a driving force of 2000 N while travelling at a constant 30 m s⁻¹. What is the power output?', options: ['66.7 W','6000 W','60 000 W','600 W'], answer: 2 },
      { q: 'A ball is dropped from 20 m. What is its speed just before hitting the ground? (g = 9.81 m s⁻²)', options: ['14 m s⁻¹','19.8 m s⁻¹','20 m s⁻¹','39.2 m s⁻¹'], answer: 1 },
      { q: 'What happens to the vertical component of velocity of a projectile during flight (no air resistance)?', options: ['It remains constant','It increases at 9.81 m s⁻² downward','It decreases at 9.81 m s⁻² then increases','It depends on the horizontal component'], answer: 1 },
      { q: 'A force acts on a 4 kg object for 0.5 s, changing its velocity from 2 m s⁻¹ to 8 m s⁻¹. What is the force?', options: ['12 N','24 N','48 N','6 N'], answer: 2 },
      { q: 'A horizontal force of 40 N pushes a 5 kg box across a floor with friction force 10 N. What is the acceleration?', options: ['2 m s⁻²','6 m s⁻²','8 m s⁻²','10 m s⁻²'], answer: 1 },
      { q: 'A stone is projected horizontally from a 45 m cliff. How long does it take to reach the ground? (g = 9.81 m s⁻²)', options: ['1.5 s','2.1 s','3.0 s','4.5 s'], answer: 2 },
      { q: 'An object of mass 2 kg is lifted 5 m in 10 s. What is the power? (g = 9.81 m s⁻²)', options: ['1 W','9.81 W','49 W','98.1 W'], answer: 1 },
    ],
    red: [
      { q: 'A 0.15 kg cricket ball is bowled at 40 m s⁻¹ and hit back at 25 m s⁻¹. The contact time is 0.002 s. What is the average force on the ball?', options: ['1125 N','7500 N','3000 N','4875 N'], answer: 3 },
      { q: 'A bullet of mass 10 g is fired at 400 m s⁻¹ into a 2 kg block of wood at rest on a smooth surface. The bullet embeds in the block. What is the velocity of the block and bullet?', options: ['0.5 m s⁻¹','4.0 m s⁻¹','1.0 m s⁻¹','2.0 m s⁻¹'], answer: 3 },
      { q: 'A projectile is launched at 50 m s⁻¹ at 45° to the horizontal. What is the maximum height reached? (g = 9.81 m s⁻²)', options: ['255.1 m','127.6 m','63.8 m','31.9 m'], answer: 2 },
      { q: 'A skydiver of mass 80 kg reaches terminal velocity. What is the drag force acting on them?', options: ['0 N','80 N','392 N','784.8 N'], answer: 3 },
      { q: 'A car of mass 1200 kg travelling at 25 m s⁻¹ brakes to a stop. What is the minimum braking distance if the maximum braking force is 7500 N?', options: ['50 m','25 m','200 m','100 m'], answer: 0 },
      { q: 'Two ice skaters push off from rest. Skater A (60 kg) moves at 2 m s⁻¹. What is the velocity of skater B (80 kg)?', options: ['1.0 m s⁻¹','1.5 m s⁻¹ in opposite direction','2.0 m s⁻¹','2.5 m s⁻¹ in opposite direction'], answer: 1 },
      { q: 'A 500 kg roller coaster car starts from rest at the top of a 30 m hill. What is its speed at the bottom, assuming no friction? (g = 9.81 m s⁻²)', options: ['34.3 m s⁻¹','30 m s⁻¹','24.3 m s⁻¹','17.2 m s⁻¹'], answer: 2 },
      { q: 'A ball is thrown upward at 20 m s⁻¹. After what time does it return to the thrower? (g = 9.81 m s⁻²)', options: ['4.08 s','1.02 s','2.04 s','3.06 s'], answer: 0 },
      { q: 'A 0.1 kg ball bounces and the force-time graph shows a triangular peak of height 200 N lasting 0.01 s. What is the change in velocity?', options: ['1 m s⁻¹','10 m s⁻¹','20 m s⁻¹','100 m s⁻¹'], answer: 1 },
      { q: 'A rocket of mass 5000 kg ejects 50 kg of exhaust per second at 3000 m s⁻¹ relative to the rocket. What is the initial thrust?', options: ['150 000 N','3 000 000 N','15 000 N','60 000 N'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── M4 */
  'M4': {
    name: 'Electrons, Waves and Photons',
    green: [
      { q: 'What is the charge on one electron?', options: ['1.6 × 10⁻¹⁹ C','-1.6 × 10⁻¹⁹ C','1.6 × 10¹⁹ C','-1.6 × 10¹⁹ C'], answer: 1 },
      { q: 'Define electric current.', options: ['The rate of flow of charge','The force on a charge','The energy per unit charge','The resistance of a wire'], answer: 0 },
      { q: 'Define potential difference.', options: ['The rate of flow of charge','The work done per unit charge between two points','The charge per unit time','The current times resistance'], answer: 1 },
      { q: 'State Ohm\'s law.', options: ['V = IR for all components','V is directly proportional to I at constant temperature for an ohmic conductor','P = IV','R = ρL/A'], answer: 1 },
      { q: 'What is the unit of resistance?', options: ['Volt','Ampere','Ohm','Coulomb'], answer: 2 },
      { q: 'What is the equation relating charge, current, and time?', options: ['Q = It','Q = Vt','Q = IR','Q = Pt'], answer: 0 },
      { q: 'What is the equation for electrical power?', options: ['P = IV','P = mgh','P = ½mv²','P = Fs/t'], answer: 0 },
      { q: 'State Kirchhoff\'s first law.', options: ['The sum of EMFs equals the sum of PDs','The total current entering a junction equals the total current leaving it','V = IR','Power is conserved in a circuit'], answer: 1 },
      { q: 'State Kirchhoff\'s second law.', options: ['Current is conserved at a junction','The sum of EMFs in a loop equals the sum of PDs in that loop','P = IV','Charge is conserved'], answer: 1 },
      { q: 'What is the equation for resistivity?', options: ['R = V/I','ρ = RA/L','ρ = RL/A','R = ρA/L'], answer: 1 },
      { q: 'What is a progressive wave?', options: ['A wave that stays in one place','A wave that transfers energy from one place to another','A wave that has nodes and antinodes','A wave that requires no medium'], answer: 1 },
      { q: 'What is the speed of electromagnetic waves in a vacuum?', options: ['340 m s⁻¹','3 × 10⁶ m s⁻¹','3 × 10⁸ m s⁻¹','3 × 10¹⁰ m s⁻¹'], answer: 2 },
      { q: 'What is the equation linking wave speed, frequency, and wavelength?', options: ['v = fλ','v = f/λ','v = λ/f','f = vλ'], answer: 0 },
      { q: 'Define wavelength.', options: ['The time for one complete oscillation','The minimum distance between two points in phase','The maximum displacement from equilibrium','The number of waves per second'], answer: 1 },
      { q: 'Define frequency.', options: ['The number of complete oscillations per unit time','The distance between two crests','The maximum displacement','The speed of the wave'], answer: 0 },
      { q: 'What is the photoelectric effect?', options: ['Light being refracted','Emission of electrons from a metal surface when illuminated by light of sufficient frequency','Light interfering with itself','Electrons emitting light'], answer: 1 },
      { q: 'What is the equation for the energy of a photon?', options: ['E = hf','E = ½mv²','E = mc²','E = kT'], answer: 0 },
      { q: 'What is the de Broglie wavelength equation?', options: ['λ = h/p','λ = hf','λ = p/h','λ = E/h'], answer: 0 },
      { q: 'What is EMF?', options: ['The potential difference across the external circuit only','The total energy transferred per unit charge by the source','The voltage drop across the internal resistance','The current times resistance'], answer: 1 },
      { q: 'What is internal resistance?', options: ['The resistance of the external circuit','The resistance of the wires','The resistance within the power source itself','The total resistance of the circuit'], answer: 2 },
    ],
    amber: [
      { q: 'A 6 V battery with internal resistance 0.5 Ω is connected to a 2.5 Ω resistor. What is the current?', options: ['2 A','2.4 A','3 A','12 A'], answer: 0 },
      { q: 'In the circuit above, what is the terminal PD across the battery?', options: ['5 V','6 V','1 V','2.5 V'], answer: 0 },
      { q: 'Two resistors of 4 Ω and 6 Ω are connected in parallel. What is the combined resistance?', options: ['2.4 Ω','10 Ω','24 Ω','1.5 Ω'], answer: 0 },
      { q: 'Two resistors of 4 Ω and 6 Ω are connected in series. What is the total resistance?', options: ['2.4 Ω','10 Ω','24 Ω','1.5 Ω'], answer: 1 },
      { q: 'A wire of length L and area A has resistance R. If the length is doubled and the area halved, what is the new resistance?', options: ['R','2R','4R','R/2'], answer: 2 },
      { q: 'In a potential divider with R₁ = 3 kΩ and R₂ = 6 kΩ connected to 9 V, what is the voltage across R₂?', options: ['3 V','6 V','4.5 V','9 V'], answer: 1 },
      { q: 'What is the condition for a stationary wave to form?', options: ['Two waves of different frequency travelling in the same direction','Two waves of the same frequency and amplitude travelling in opposite directions','One wave reflecting off a fixed boundary with energy loss','A single wave with increasing amplitude'], answer: 1 },
      { q: 'Light passes from air (n = 1.0) into glass (n = 1.5) at an angle of incidence of 45°. What is the angle of refraction?', options: ['28.1°','30°','45°','67.5°'], answer: 0 },
      { q: 'In a double-slit experiment, what happens to the fringe spacing if the wavelength is increased?', options: ['Fringe spacing decreases','Fringe spacing increases','Fringe spacing stays the same','Fringes disappear'], answer: 1 },
      { q: 'The work function of a metal is 2.0 eV. What is the threshold frequency? (h = 6.63 × 10⁻³⁴ J s, 1 eV = 1.6 × 10⁻¹⁹ J)', options: ['3.0 × 10¹⁴ Hz','4.8 × 10¹⁴ Hz','5.0 × 10¹⁴ Hz','7.5 × 10¹⁴ Hz'], answer: 1 },
      { q: 'An electron is accelerated through a PD of 100 V. What kinetic energy does it gain?', options: ['100 J','1.6 × 10⁻¹⁷ J','1.6 × 10⁻¹⁹ J','100 eV'], answer: 1 },
      { q: 'In a potential divider, an LDR is used in place of R₁. As light intensity increases, what happens to V₂?', options: ['V₂ increases','V₂ decreases','V₂ stays the same','V₂ becomes zero'], answer: 0 },
      { q: 'What is the first harmonic (fundamental) frequency of a string of length L, wave speed v?', options: ['f = v/L','f = v/2L','f = 2v/L','f = v/4L'], answer: 1 },
      { q: 'A diffraction grating has 500 lines per mm. What is the slit spacing?', options: ['2 × 10⁻⁶ m','5 × 10⁻⁴ m','2 × 10⁻³ m','0.5 × 10⁻⁶ m'], answer: 0 },
      { q: 'For a diffraction grating, the equation d sin θ = nλ applies. What does n represent?', options: ['The number of slits','The order of the maximum','The refractive index','The number of wavelengths'], answer: 1 },
      { q: 'An atom transitions from energy level -1.5 eV to -3.4 eV. What is the energy of the emitted photon?', options: ['1.9 eV','3.4 eV','4.9 eV','1.5 eV'], answer: 0 },
      { q: 'What is the I-V characteristic of a filament lamp?', options: ['A straight line through the origin','A curve that levels off as V increases — resistance increases with temperature','A curve that steepens — resistance decreases','A horizontal line'], answer: 1 },
      { q: 'What is the I-V characteristic of a diode?', options: ['Linear in both directions','No current below threshold PD; rapidly increasing current above it in forward bias','Current proportional to voltage squared','Constant current regardless of voltage'], answer: 1 },
      { q: 'An electron has a de Broglie wavelength of 1.2 × 10⁻¹⁰ m. What is its momentum? (h = 6.63 × 10⁻³⁴ J s)', options: ['5.5 × 10⁻²⁴ kg m s⁻¹','7.96 × 10⁻⁴⁴ kg m s⁻¹','5.5 × 10⁻²⁰ kg m s⁻¹','6.63 × 10⁻³⁴ kg m s⁻¹'], answer: 0 },
      { q: 'When white light passes through a diffraction grating, the central maximum is white. Why are the other maxima spread into spectra?', options: ['Different colours have different intensities','Different wavelengths are diffracted by different amounts','The grating absorbs some colours','Only one colour can pass through at a time'], answer: 1 },
    ],
    red: [
      { q: 'A battery of EMF 12 V and internal resistance 2 Ω is connected to two resistors in parallel (6 Ω and 3 Ω). What is the current drawn from the battery?', options: ['4 A','1.5 A','3 A','2 A'], answer: 2 },
      { q: 'Light of wavelength 600 nm is incident on a diffraction grating with 3.0 × 10⁵ lines per metre. What is the maximum order of diffraction observed?', options: ['3','5','7','9'], answer: 1 },
      { q: 'A photon of wavelength 200 nm strikes a metal with work function 3.5 eV. What is the maximum kinetic energy of the emitted electron? (h = 6.63 × 10⁻³⁴ J s, c = 3 × 10⁸ m s⁻¹)', options: ['3.5 eV','9.9 eV','6.2 eV','2.7 eV'], answer: 3 },
      { q: 'In a Wheatstone bridge circuit, R₁ = 100 Ω, R₂ = 200 Ω, R₃ = 150 Ω. For balance, what must R₄ be?', options: ['100 Ω','250 Ω','75 Ω','300 Ω'], answer: 3 },
      { q: 'A stationary wave on a string has 4 nodes (including both ends). If the string length is 1.5 m, what is the wavelength?', options: ['1.5 m','0.5 m','1.0 m','0.75 m'], answer: 2 },
      { q: 'An electron is accelerated through 5 kV. What is its de Broglie wavelength? (m = 9.11 × 10⁻³¹ kg, h = 6.63 × 10⁻³⁴ J s, e = 1.6 × 10⁻¹⁹ C)', options: ['1.7 × 10⁻¹¹ m','5.5 × 10⁻¹² m','1.2 × 10⁻¹⁰ m','3.9 × 10⁻¹⁰ m'], answer: 0 },
      { q: 'The intensity of a wave is proportional to the square of its amplitude. If the amplitude is halved, what happens to the intensity?', options: ['It quarters','It stays the same','It doubles','It halves'], answer: 0 },
      { q: 'Two coherent sources separated by 0.5 mm produce an interference pattern on a screen 2.0 m away. If the fringe spacing is 2.4 mm, what is the wavelength?', options: ['300 nm','600 nm','480 nm','750 nm'], answer: 1 },
      { q: 'A potential divider consists of a 10 kΩ resistor and a thermistor. At a certain temperature the thermistor has resistance 5 kΩ. The supply is 12 V. What is the voltage across the thermistor?', options: ['4 V','8 V','6 V','3 V'], answer: 0 },
      { q: 'An LED has a threshold PD of 1.8 V. Estimate the wavelength of light emitted. (h = 6.63 × 10⁻³⁴ J s, c = 3 × 10⁸ m s⁻¹, e = 1.6 × 10⁻¹⁹ C)', options: ['690 nm','550 nm','900 nm','450 nm'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── M5 */
  'M5': {
    name: 'Newtonian World and Astrophysics',
    green: [
      { q: 'What is specific heat capacity?', options: ['The energy needed to change the state of 1 kg of substance','The energy needed to raise the temperature of 1 kg of substance by 1 K','The total internal energy of a substance','The temperature at which a substance melts'], answer: 1 },
      { q: 'What is specific latent heat?', options: ['The energy needed to raise the temperature of 1 kg by 1 K','The energy needed to change the state of 1 kg of substance at constant temperature','The energy stored as kinetic energy in particles','The total heat capacity of an object'], answer: 1 },
      { q: 'State the ideal gas equation.', options: ['PV = nRT','PV = mc²','P = ρgh','F = ma'], answer: 0 },
      { q: 'What is absolute zero?', options: ['0 °C','The temperature at which particles have minimum kinetic energy (0 K = -273.15 °C)','The temperature at which all substances are solid','The coldest temperature ever recorded on Earth'], answer: 1 },
      { q: 'Define angular velocity (ω).', options: ['The rate of change of displacement','The rate of change of angle, ω = 2πf','The speed along the circumference','The angular displacement'], answer: 1 },
      { q: 'What provides the centripetal force for a satellite orbiting Earth?', options: ['The satellite\'s engines','Air resistance','Gravitational attraction','Electromagnetic force'], answer: 2 },
      { q: 'What is simple harmonic motion (SHM)?', options: ['Motion at constant velocity in a circle','Motion where acceleration is proportional to displacement and directed towards equilibrium','Motion under constant acceleration','Motion where velocity is proportional to displacement'], answer: 1 },
      { q: 'State Newton\'s law of gravitation.', options: ['F = mg','Every particle attracts every other particle with a force proportional to the product of their masses and inversely proportional to the square of the distance between them','F = ma','Gravitational field strength is constant'], answer: 1 },
      { q: 'What is gravitational field strength g?', options: ['The force on a 1 kg mass at that point in the field','The total gravitational force','The mass of the planet','The gravitational potential'], answer: 0 },
      { q: 'What is a Hertzsprung-Russell diagram?', options: ['A graph of distance against time for stars','A graph plotting stellar luminosity against surface temperature','A graph of wavelength against intensity','A map of star positions in the sky'], answer: 1 },
      { q: 'What is Hubble\'s law?', options: ['Stars are born in nebulae','The recessional velocity of a galaxy is proportional to its distance from us','All galaxies are the same size','Light is always red-shifted'], answer: 1 },
      { q: 'What is cosmological redshift?', options: ['Light appearing blue due to the Doppler effect','The stretching of light wavelengths due to the expansion of space','A decrease in frequency due to gravity','Light bending around a massive object'], answer: 1 },
      { q: 'What does Wien\'s displacement law relate?', options: ['Temperature and luminosity','Peak wavelength and surface temperature of a black body','Pressure and volume','Mass and radius of a star'], answer: 1 },
      { q: 'What is the Stefan-Boltzmann law?', options: ['P = σAT⁴ — the total power radiated by a black body','E = hf','PV = nRT','F = GMm/r²'], answer: 0 },
      { q: 'Define gravitational potential.', options: ['The force per unit mass','The work done per unit mass in bringing a small test mass from infinity to that point','The kinetic energy of a mass in orbit','The acceleration due to gravity'], answer: 1 },
      { q: 'What is meant by damping in oscillations?', options: ['An increase in amplitude over time','The gradual loss of energy and decrease in amplitude','The change in frequency','The addition of a driving force'], answer: 1 },
      { q: 'What is resonance?', options: ['When an oscillating system is at rest','When the driving frequency equals the natural frequency, causing maximum amplitude','When damping is maximum','When frequency is zero'], answer: 1 },
      { q: 'State Kepler\'s third law.', options: ['Planets move in circular orbits','T² is proportional to r³ for orbits around the same central body','Equal areas are swept in equal times','Orbits are always elliptical'], answer: 1 },
      { q: 'What is internal energy?', options: ['The kinetic energy of the whole object','The sum of the randomly distributed kinetic and potential energies of all the particles in a system','The gravitational potential energy','The heat energy absorbed'], answer: 1 },
      { q: 'What is the Boltzmann constant?', options: ['The gas constant divided by Avogadro\'s number, k = R/Nₐ = 1.38 × 10⁻²³ J K⁻¹','The gravitational constant','Planck\'s constant','The speed of light'], answer: 0 },
    ],
    amber: [
      { q: 'How much energy is needed to raise the temperature of 2 kg of water (c = 4200 J kg⁻¹ K⁻¹) by 25 K?', options: ['105 000 J','210 000 J','420 000 J','8400 J'], answer: 1 },
      { q: 'A car goes around a circular bend of radius 50 m at 20 m s⁻¹. What is the centripetal acceleration?', options: ['0.4 m s⁻²','2.5 m s⁻²','8 m s⁻²','400 m s⁻²'], answer: 2 },
      { q: 'An ideal gas at 300 K has pressure 100 kPa. If the temperature rises to 600 K at constant volume, what is the new pressure?', options: ['50 kPa','100 kPa','200 kPa','400 kPa'], answer: 2 },
      { q: 'A mass on a spring oscillates with SHM of amplitude 0.1 m and frequency 2 Hz. What is the maximum speed?', options: ['0.2 m s⁻¹','0.4π m s⁻¹','0.63 m s⁻¹','1.26 m s⁻¹'], answer: 3 },
      { q: 'Calculate the gravitational field strength at a distance of 2R from the centre of a planet of mass M and radius R.', options: ['GM/R²','GM/4R²','GM/2R²','4GM/R²'], answer: 1 },
      { q: 'A satellite orbits Earth at radius r. If the orbital radius is doubled, by what factor does the orbital period change?', options: ['2','√2','2√2','4'], answer: 2 },
      { q: 'The mean kinetic energy of a gas molecule is given by ½m⟨c²⟩ = (3/2)kT. At 300 K, what is the mean KE? (k = 1.38 × 10⁻²³ J K⁻¹)', options: ['6.21 × 10⁻²¹ J','4.14 × 10⁻²¹ J','2.07 × 10⁻²¹ J','1.38 × 10⁻²³ J'], answer: 0 },
      { q: 'A star has peak wavelength 500 nm. Using Wien\'s law (λₘₐₓT = 2.9 × 10⁻³ m K), what is its surface temperature?', options: ['2900 K','5800 K','11600 K','1450 K'], answer: 1 },
      { q: 'A black body at 6000 K has luminosity L. If the temperature doubles to 12000 K (same radius), what is the new luminosity?', options: ['2L','4L','8L','16L'], answer: 3 },
      { q: 'A galaxy is receding at 15000 km s⁻¹. Using H₀ = 70 km s⁻¹ Mpc⁻¹, what is its distance?', options: ['214 Mpc','1050 Mpc','2.1 Mpc','150 Mpc'], answer: 0 },
      { q: 'An object performs SHM with period 0.5 s and amplitude 0.08 m. What is the maximum acceleration?', options: ['2.0 m s⁻²','6.3 m s⁻²','12.6 m s⁻²','126 m s⁻²'], answer: 2 },
      { q: 'What mass of ice (Lf = 3.3 × 10⁵ J kg⁻¹) can be melted by 66 000 J of energy?', options: ['0.1 kg','0.2 kg','0.5 kg','2.0 kg'], answer: 1 },
      { q: 'A 0.2 kg mass on a spring (k = 50 N m⁻¹) oscillates. What is the period?', options: ['0.2 s','0.4 s','0.6 s','1.3 s'], answer: 1 },
      { q: 'Two masses of 100 kg and 200 kg are separated by 0.5 m. What is the gravitational force between them? (G = 6.67 × 10⁻¹¹ N m² kg⁻²)', options: ['5.3 × 10⁻⁶ N','2.7 × 10⁻⁶ N','1.1 × 10⁻⁵ N','5.3 × 10⁻⁸ N'], answer: 0 },
      { q: 'A simple pendulum has length 1.0 m. What is its period? (g = 9.81 m s⁻²)', options: ['1.0 s','2.0 s','3.1 s','6.3 s'], answer: 1 },
      { q: 'At what point in SHM is the kinetic energy maximum?', options: ['At maximum displacement','At the equilibrium position','Halfway between equilibrium and maximum displacement','At the turning points'], answer: 1 },
      { q: 'A gas contains 3 × 10²³ molecules at 400 K. What is the total translational kinetic energy? (k = 1.38 × 10⁻²³ J K⁻¹)', options: ['2.48 J','1.66 J','8.28 J','0.83 J'], answer: 0 },
      { q: 'What type of star is found on the main sequence of the HR diagram?', options: ['A star that is fusing helium','A star that is fusing hydrogen in its core','A white dwarf','A red giant'], answer: 1 },
      { q: 'The escape velocity from a planet\'s surface is v = √(2GM/R). If the planet\'s mass is doubled and radius stays the same, by what factor does escape velocity change?', options: ['2','√2','4','½'], answer: 1 },
      { q: 'A damped oscillator loses 10% of its energy each cycle. After 3 cycles, approximately what fraction of the original energy remains?', options: ['70%','72.9%','90%','30%'], answer: 1 },
    ],
    red: [
      { q: 'A geostationary satellite orbits Earth at approximately 42 000 km from Earth\'s centre. What is its orbital speed? (Use T = 24 hours)', options: ['7.9 km s⁻¹','3.07 km s⁻¹','30 km s⁻¹','11.2 km s⁻¹'], answer: 1 },
      { q: 'A star has twice the radius and twice the surface temperature of the Sun. By what factor is its luminosity greater than the Sun\'s?', options: ['4','8','16','64'], answer: 3 },
      { q: 'An oscillator is driven at frequency f near its natural frequency f₀. Heavy damping is applied. What happens to the resonance peak?', options: ['It becomes taller and sharper','It disappears entirely','It shifts above f₀','It becomes shorter and broader, shifting slightly below f₀'], answer: 3 },
      { q: 'The gravitational potential at the surface of a planet (mass M, radius R) is V = -GM/R. What is the potential at height R above the surface?', options: ['-GM/R','-GM/2R','-GM/4R','0'], answer: 1 },
      { q: 'A container holds 0.1 mol of ideal gas at 300 K. The gas expands at constant temperature to double its volume. What is the new pressure if the initial pressure was 200 kPa?', options: ['100 kPa','200 kPa','400 kPa','50 kPa'], answer: 0 },
      { q: 'Calculate the rms speed of nitrogen molecules (M = 28 × 10⁻³ kg mol⁻¹) at 300 K. (R = 8.31 J mol⁻¹ K⁻¹)', options: ['517 m s⁻¹','300 m s⁻¹','730 m s⁻¹','1460 m s⁻¹'], answer: 0 },
      { q: 'A mass-spring system has natural frequency 5 Hz and is lightly damped. It is driven at 5 Hz. What happens?', options: ['The amplitude grows to a maximum — resonance occurs','The amplitude stays small','The frequency shifts to 10 Hz','The system stops oscillating'], answer: 0 },
      { q: 'The Doppler equation for recession is Δλ/λ ≈ v/c. A spectral line normally at 500 nm is observed at 505 nm. What is the recession speed?', options: ['3 × 10⁶ m s⁻¹','1 × 10⁶ m s⁻¹','1.5 × 10⁷ m s⁻¹','5 × 10⁶ m s⁻¹'], answer: 0 },
      { q: 'A planet has mass 4M and radius 2R compared to Earth. What is the gravitational field strength at its surface relative to Earth\'s g?', options: ['4g','g/2','g','2g'], answer: 2 },
      { q: 'In SHM, the displacement is x = A cos(ωt). At time t = T/4 (quarter period), what is the displacement?', options: ['A','0','-A','A/2'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── M6 */
  'M6': {
    name: 'Particles and Medical Physics',
    green: [
      { q: 'What is the equation for capacitance?', options: ['C = Q/V','C = V/Q','C = QV','C = Q²/V'], answer: 0 },
      { q: 'What is the unit of capacitance?', options: ['Coulomb','Volt','Farad','Ohm'], answer: 2 },
      { q: 'What is the energy stored in a capacitor?', options: ['E = ½QV','E = QV','E = Q/V','E = V/Q'], answer: 0 },
      { q: 'What is Coulomb\'s law?', options: ['F = kQq/r²','F = mg','F = BIL','F = ma'], answer: 0 },
      { q: 'What is the unit of electric field strength?', options: ['V m⁻¹ or N C⁻¹','J C⁻¹','C m⁻¹','N m⁻¹'], answer: 0 },
      { q: 'State Faraday\'s law of electromagnetic induction.', options: ['A current creates a magnetic field','The induced EMF is proportional to the rate of change of magnetic flux linkage','F = BIL','Flux is constant in a closed loop'], answer: 1 },
      { q: 'State Lenz\'s law.', options: ['The induced current flows in the same direction as the change','The induced EMF acts in a direction to oppose the change producing it','Current always flows from positive to negative','Magnetic flux is always conserved'], answer: 1 },
      { q: 'What is the force on a current-carrying wire in a magnetic field?', options: ['F = BQv','F = BIL','F = EQ','F = kQq/r²'], answer: 1 },
      { q: 'What is the force on a moving charge in a magnetic field?', options: ['F = BIL','F = BQv','F = EQ','F = mg'], answer: 1 },
      { q: 'What is the time constant of an RC circuit?', options: ['τ = R/C','τ = RC','τ = C/R','τ = R²C'], answer: 1 },
      { q: 'What is an alpha particle?', options: ['An electron','A helium nucleus (2 protons + 2 neutrons)','A photon','A neutron'], answer: 1 },
      { q: 'What is a beta-minus particle?', options: ['A helium nucleus','A positron','A high-speed electron emitted from a nucleus','A proton'], answer: 2 },
      { q: 'What is gamma radiation?', options: ['A stream of alpha particles','High-energy electromagnetic radiation emitted from a nucleus','A stream of electrons','A type of sound wave'], answer: 1 },
      { q: 'What is half-life?', options: ['The time for all atoms to decay','The time for the activity or number of undecayed nuclei to halve','The time for a substance to become safe','Half the decay constant'], answer: 1 },
      { q: 'What is E = mc² used for in nuclear physics?', options: ['Calculating electrical energy','Relating mass difference (mass defect) to energy released in nuclear reactions','Calculating kinetic energy','Calculating gravitational potential energy'], answer: 1 },
      { q: 'What is nuclear fission?', options: ['Small nuclei joining together','A heavy nucleus splitting into two smaller nuclei, releasing energy','The emission of an alpha particle','The absorption of a neutron with no energy release'], answer: 1 },
      { q: 'What is nuclear fusion?', options: ['A heavy nucleus splitting apart','Light nuclei joining together to form a heavier nucleus, releasing energy','Radioactive decay','Nuclear fission in reverse'], answer: 1 },
      { q: 'What is the Standard Model in particle physics?', options: ['A model of the atom with electrons in fixed orbits','The classification of all known fundamental particles and the forces between them','A model of nuclear fission','A model of stellar evolution'], answer: 1 },
      { q: 'Name the three generations of quarks.', options: ['Up/down, charm/strange, top/bottom','Electron, muon, tau','Proton, neutron, electron','Alpha, beta, gamma'], answer: 0 },
      { q: 'What type of imaging uses high-frequency sound waves reflected off internal structures?', options: ['X-ray','CT scan','Ultrasound','PET scan'], answer: 2 },
    ],
    amber: [
      { q: 'A 100 μF capacitor is charged to 12 V. How much charge is stored?', options: ['1.2 × 10⁻³ C','1.2 × 10⁻⁴ C','1.2 C','0.12 C'], answer: 0 },
      { q: 'What is the energy stored in a 47 μF capacitor charged to 9 V?', options: ['1.9 × 10⁻³ J','4.2 × 10⁻⁴ J','2.1 × 10⁻³ J','1.9 × 10⁻² J'], answer: 0 },
      { q: 'A capacitor discharges through a 10 kΩ resistor. If C = 200 μF, what is the time constant?', options: ['0.2 s','2 s','20 s','200 s'], answer: 1 },
      { q: 'During capacitor discharge, after how many time constants has the charge fallen to approximately 37% of its initial value?', options: ['0.5','1','2','5'], answer: 1 },
      { q: 'Two point charges of +2 μC and -3 μC are separated by 0.1 m. Is the force attractive or repulsive, and what is its magnitude? (k = 8.99 × 10⁹ N m² C⁻²)', options: ['Attractive, 5.4 N','Repulsive, 5.4 N','Attractive, 0.54 N','Repulsive, 0.54 N'], answer: 0 },
      { q: 'A straight wire of length 0.3 m carries a current of 4 A perpendicular to a magnetic field of 0.5 T. What is the force?', options: ['0.15 N','0.6 N','1.2 N','6 N'], answer: 1 },
      { q: 'An electron moves at 2 × 10⁶ m s⁻¹ perpendicular to a magnetic field of 0.01 T. What is the force on it? (e = 1.6 × 10⁻¹⁹ C)', options: ['3.2 × 10⁻¹⁵ N','3.2 × 10⁻¹³ N','1.6 × 10⁻¹⁵ N','3.2 × 10⁻¹² N'], answer: 0 },
      { q: 'A coil of 200 turns has flux changing from 0.05 Wb to 0.02 Wb in 0.1 s. What is the induced EMF?', options: ['6 V','60 V','0.6 V','600 V'], answer: 1 },
      { q: 'A radioactive sample has a half-life of 8 days. What fraction remains after 24 days?', options: ['1/2','1/4','1/8','1/16'], answer: 2 },
      { q: 'The binding energy per nucleon is highest for which element?', options: ['Hydrogen','Helium','Iron (Fe-56)','Uranium'], answer: 2 },
      { q: 'In beta-minus decay, a neutron transforms into:', options: ['A proton, an electron, and an antineutrino','A proton, a positron, and a neutrino','An alpha particle and a gamma ray','Two protons'], answer: 0 },
      { q: 'What is the quark composition of a proton?', options: ['uud','udd','uuu','ddd'], answer: 0 },
      { q: 'What is the quark composition of a neutron?', options: ['uud','udd','uuu','ddd'], answer: 1 },
      { q: 'A PET scan uses which type of radiation?', options: ['Alpha particles','Beta-minus particles','Gamma rays from positron-electron annihilation','X-rays'], answer: 2 },
      { q: 'In a uniform electric field between parallel plates separated by distance d with PD V, what is the field strength?', options: ['E = V/d','E = Vd','E = V²/d','E = d/V'], answer: 0 },
      { q: 'The decay constant λ and half-life t½ are related by:', options: ['λ = ln 2 / t½','λ = t½ / ln 2','λ = 2t½','λ = t½²'], answer: 0 },
      { q: 'A mass defect of 0.02 u corresponds to how much energy? (1 u = 931.5 MeV)', options: ['18.63 MeV','9.315 MeV','0.02 MeV','1863 MeV'], answer: 0 },
      { q: 'Which conservation law is violated if a proton were to decay into a neutron and a positron?', options: ['Conservation of charge','Conservation of baryon number','Conservation of lepton number','Conservation of energy'], answer: 2 },
      { q: 'X-rays are produced when high-speed electrons are decelerated by a metal target. This is called:', options: ['Photoelectric emission','Bremsstrahlung radiation','Compton scattering','Pair production'], answer: 1 },
      { q: 'What is the acoustic impedance of a material?', options: ['The speed of sound in it','The product of density and speed of sound (Z = ρc)','The frequency of sound in it','The wavelength of sound in it'], answer: 1 },
    ],
    red: [
      { q: 'A 500 μF capacitor is charged to 20 V and then discharged through a 4 kΩ resistor. What is the current after 4 s?', options: ['1.35 mA','0.68 mA','5 mA','2.71 mA'], answer: 1 },
      { q: 'An electron enters a uniform electric field of 5000 V m⁻¹. What is the force on the electron and its acceleration? (e = 1.6 × 10⁻¹⁹ C, m = 9.11 × 10⁻³¹ kg)', options: ['8 × 10⁻¹⁶ N, 8.8 × 10¹⁴ m s⁻²','8 × 10⁻¹⁶ N, 8.8 × 10¹⁰ m s⁻²','5 × 10⁻¹⁶ N, 5.5 × 10¹⁴ m s⁻²','1.6 × 10⁻¹⁶ N, 1.76 × 10¹⁴ m s⁻²'], answer: 0 },
      { q: 'A sample contains 10⁶ radioactive nuclei with λ = 0.01 s⁻¹. What is the activity?', options: ['10⁸ Bq','10⁶ Bq','10⁴ Bq','100 Bq'], answer: 2 },
      { q: 'In the reaction ²³⁵U + ¹n → ¹⁴¹Ba + ⁹²Kr + x¹n, what is x?', options: ['3','4','1','2'], answer: 0 },
      { q: 'Two parallel plates are separated by 2 cm with a PD of 1000 V. An electron is released from rest at the negative plate. What is its speed when it reaches the positive plate? (e = 1.6 × 10⁻¹⁹ C, m = 9.11 × 10⁻³¹ kg)', options: ['1.87 × 10⁷ m s⁻¹','5.93 × 10⁶ m s⁻¹','1.33 × 10⁷ m s⁻¹','3.0 × 10⁸ m s⁻¹'], answer: 0 },
      { q: 'The total binding energy of He-4 is 28.3 MeV. What is the binding energy per nucleon?', options: ['7.1 MeV','14.15 MeV','28.3 MeV','3.5 MeV'], answer: 0 },
      { q: 'A transformer has 500 primary turns and 50 secondary turns. If the input voltage is 230 V, what is the output voltage?', options: ['2.3 V','2300 V','115 V','23 V'], answer: 3 },
      { q: 'In ultrasound imaging, the percentage of intensity reflected at a boundary depends on the acoustic impedances Z₁ and Z₂. If Z₁ ≈ Z₂, what happens?', options: ['Almost all energy is reflected','The frequency changes','Almost all energy is transmitted — very little reflection','No sound can pass'], answer: 2 },
      { q: 'A charged particle moves in a circle in a magnetic field. If the speed is doubled, what happens to the radius of the circular path?', options: ['It halves','It stays the same','It doubles','It quadruples'], answer: 2 },
      { q: 'Which particles are leptons?', options: ['Protons, neutrons, pions','Electrons, muons, taus and their neutrinos','Up quarks, down quarks, strange quarks','Photons, W bosons, Z bosons'], answer: 1 },
    ],
  },

};
