/*
 * OCR B A-Level Physics (Advancing Physics, H557) — MCQ Diagnostic Question Bank
 * B1, B2: 25 questions each (10 green, 10 amber, 5 red) — smaller practical/data topics
 * B3–B6: 50 questions each (20 green, 20 amber, 10 red)
 * Diagnostic picks 2 green + 2 amber + 1 red = 5 questions per topic.
 * answer: 0-based index of correct option.
 */

const PHYSICS_OCR_B_QUESTIONS = {

  /* ─────────────────────────────────────────────────────────── B1 */
  'B1': {
    name: 'Development of Practical Skills',
    green: [
      { q: 'What is the independent variable in an experiment?', options: ['The variable that is measured','The variable that is deliberately changed','The variable kept constant','A variable that cannot be controlled'], answer: 1 },
      { q: 'What is meant by the resolution of a measuring instrument?', options: ['The largest value it can read','The smallest change in the quantity it can detect','Its accuracy','Its calibration range'], answer: 1 },
      { q: 'What is a systematic error?', options: ['A random fluctuation in readings','A consistent error in the same direction for every reading','An error that averages out over many readings','An error caused by parallax only'], answer: 1 },
      { q: 'What is meant by the precision of a set of measurements?', options: ['How close the mean is to the true value','How close repeat readings are to each other','Whether the instrument is calibrated','The number of significant figures used'], answer: 1 },
      { q: 'How is the percentage uncertainty in a single reading calculated?', options: ['(absolute uncertainty / reading) × 100','(reading / absolute uncertainty) × 100','absolute uncertainty × reading','reading − absolute uncertainty'], answer: 0 },
      { q: 'What does the area under a velocity–time graph represent?', options: ['Acceleration','Displacement','Speed','Force'], answer: 1 },
      { q: 'What is the purpose of repeating measurements in an experiment?', options: ['To eliminate systematic errors','To reduce the effect of random errors','To increase the range','To change the independent variable'], answer: 1 },
      { q: 'What type of error is caused by a zero error on a balance?', options: ['Random error','Systematic error','Parallax error','Human error only'], answer: 1 },
      { q: 'What does a line of best fit on a scatter graph represent?', options: ['The exact data points','The general trend of the data','Only the anomalous results','The random errors'], answer: 1 },
      { q: 'Which instrument has the best resolution for measuring the diameter of a thin wire?', options: ['A metre rule','A 30 cm ruler','A vernier calliper','A micrometer screw gauge'], answer: 3 },
    ],
    amber: [
      { q: 'A student measures a length as 25.0 ± 0.5 cm. What is the percentage uncertainty?', options: ['0.5%','2.0%','5.0%','20%'], answer: 1 },
      { q: 'If percentage uncertainties in length and time are 3% and 2% respectively, what is the percentage uncertainty in speed?', options: ['1%','5%','6%','9%'], answer: 1 },
      { q: 'A student plots ln(N) against time t and gets a straight line with gradient −0.02 s⁻¹. What does this indicate?', options: ['N increases linearly with t','N is proportional to t²','N decays exponentially with a decay constant of 0.02 s⁻¹','N is constant'], answer: 2 },
      { q: 'When a quantity is raised to a power n, its percentage uncertainty is:', options: ['Unchanged','Multiplied by n','Divided by n','Raised to the power n'], answer: 1 },
      { q: 'Error bars on a graph data point represent:', options: ['The range of the independent variable','The absolute uncertainty in the plotted quantity','The percentage uncertainty only','The systematic error'], answer: 1 },
      { q: 'To find the uncertainty in a gradient, a student should draw:', options: ['Only the best-fit line','The steepest and shallowest lines through the error bars','A curved line through all points','A horizontal line'], answer: 1 },
      { q: 'A vernier calliper reads 3.42 cm. Its resolution is 0.01 cm. What is the absolute uncertainty?', options: ['0.005 cm','0.01 cm','0.02 cm','0.1 cm'], answer: 1 },
      { q: 'To verify that y ∝ x², a student should plot:', options: ['y against x','y against x²','ln y against ln x','y² against x'], answer: 1 },
      { q: 'A student obtains a value of g = 9.65 ± 0.20 m s⁻². The accepted value is 9.81 m s⁻². Is the result accurate?', options: ['No, because 9.81 is outside the uncertainty range','Yes, because 9.81 lies within 9.45 to 9.85','No, because the precision is too low','Yes, because the percentage difference is small'], answer: 1 },
      { q: 'Which technique best reduces systematic error?', options: ['Repeating measurements','Calibrating the instrument against a known standard','Plotting a graph','Using a larger range'], answer: 1 },
    ],
    red: [
      { q: 'The percentage uncertainty in the radius r is 2%. If the calculated quantity is V = (4/3)πr³, what is the percentage uncertainty in V?', options: ['6%','2%','4%','8%'], answer: 0 },
      { q: 'A log–log graph of T against l for a pendulum gives a straight line with gradient 0.5. What does this confirm?', options: ['T ∝ l','T ∝ l²','T ∝ √l','T ∝ 1/l'], answer: 2 },
      { q: 'A student measures the speed of sound as 335 ± 8 m s⁻¹. The accepted value is 343 m s⁻¹. The percentage difference is 2.3% and total percentage uncertainty is 2.4%. What should they conclude?', options: ['The result proves the speed of sound is 335 m s⁻¹','The random errors are too large to draw any conclusion','The experiment is invalid due to systematic error','The result is consistent with the accepted value as the percentage difference is within the total uncertainty'], answer: 3 },
      { q: 'In a capacitor discharge experiment, a graph of ln(V) against t is plotted. The best-fit gradient is −0.050 s⁻¹ and the worst acceptable gradient is −0.045 s⁻¹. What is the percentage uncertainty in the time constant?', options: ['11%','20%','5%','10%'], answer: 0 },
      { q: 'A student claims their experiment validates a model because the R² value of the line of best fit is 0.98. Which criticism is most valid?', options: ['A high R² does not prove causation or that the model is physically correct','R² should always be exactly 1.0','The value should be compared with the number of data points using a chi-squared test only','R² values above 0.95 always prove the model'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B2 */
  'B2': {
    name: 'Fundamental Data Analysis',
    green: [
      { q: 'What is the SI unit of mass?', options: ['gram','kilogram','tonne','pound'], answer: 1 },
      { q: 'What prefix represents 10⁻³?', options: ['micro','milli','centi','kilo'], answer: 1 },
      { q: 'How many metres are in 1 km?', options: ['100','1 000','10 000','1 000 000'], answer: 1 },
      { q: 'What is the SI unit of time?', options: ['minute','hour','second','millisecond'], answer: 2 },
      { q: 'What does the prefix "mega" represent?', options: ['10³','10⁶','10⁹','10¹²'], answer: 1 },
      { q: 'Express 0.0035 m in millimetres.', options: ['0.35 mm','3.5 mm','35 mm','350 mm'], answer: 1 },
      { q: 'What is a derived SI unit?', options: ['A unit that is one of the seven base units','A unit expressed as a combination of base units','A unit used only in engineering','A non-standard unit'], answer: 1 },
      { q: 'Which of the following is a vector quantity?', options: ['Speed','Mass','Temperature','Velocity'], answer: 3 },
      { q: 'What is the SI unit of force?', options: ['Joule','Watt','Newton','Pascal'], answer: 2 },
      { q: 'How is the mean of a data set calculated?', options: ['Sum of values divided by the number of values','The most common value','The middle value when ordered','The range divided by two'], answer: 0 },
    ],
    amber: [
      { q: 'Express the unit of energy (joule) in SI base units.', options: ['kg m s⁻¹','kg m² s⁻²','kg m² s⁻³','kg m s⁻²'], answer: 1 },
      { q: 'A car travels 150 km in 2.5 hours. What is its average speed in m s⁻¹?', options: ['16.7','60','600','1 667'], answer: 0 },
      { q: 'The equation v² = u² + 2as is to be checked for homogeneity. What are the units of the right-hand side?', options: ['m s⁻¹','m² s⁻²','m s⁻²','m²'], answer: 1 },
      { q: 'A quantity Q = kAΔT/d. If the units of Q are watts, A is m², ΔT is K, and d is m, what are the units of k?', options: ['W m⁻¹ K⁻¹','W m K','W m⁻² K⁻¹','W K⁻¹'], answer: 0 },
      { q: 'Which graph would confirm a relationship y = ax^n most efficiently?', options: ['y against x','ln y against ln x','y against ln x','ln y against x'], answer: 1 },
      { q: 'A student obtains: 4.5, 4.7, 4.6, 4.4, 9.2. Which value is most likely anomalous?', options: ['4.4','4.5','4.7','9.2'], answer: 3 },
      { q: 'What are the SI base units of pressure?', options: ['kg m⁻¹ s⁻²','kg m s⁻²','kg m² s⁻²','kg m⁻² s⁻¹'], answer: 0 },
      { q: 'A force of 20 N acts at 30° to the horizontal. What is the horizontal component?', options: ['10.0 N','17.3 N','20.0 N','11.5 N'], answer: 1 },
      { q: 'On a ln y vs ln x graph, the gradient is 2 and the y-intercept is ln 5. What is the relationship?', options: ['y = 2x + 5','y = 5x²','y = 5e²ˣ','y = 2 ln x + 5'], answer: 1 },
      { q: 'An order-of-magnitude estimate of the number of atoms in a human body (mass ~70 kg, average atomic mass ~10⁻²⁶ kg) is:', options: ['10²⁵','10²⁷','10²⁸','10³⁰'], answer: 1 },
    ],
    red: [
      { q: 'The equation for the period of a mass–spring system is T = 2π√(m/k). A student measures m = 0.500 ± 0.005 kg and T = 1.40 ± 0.02 s. What is the percentage uncertainty in k?', options: ['1%','2.9%','3.9%','5.9%'], answer: 2 },
      { q: 'A student plots ln(I) against V for a filament lamp and obtains a curve rather than a straight line. What does this indicate?', options: ['The data should be replotted as I against V²','There is a systematic error in the ammeter','The resistance changes with temperature so the relationship is not exponential','The relationship is I = I₀ e^(V)'], answer: 2 },
      { q: 'An equation is proposed: F = 6πηrv, where F is force (N), r is radius (m), and v is velocity (m s⁻¹). What must the units of η be for the equation to be homogeneous?', options: ['kg m⁻¹ s⁻¹','kg m s⁻¹','kg m⁻² s⁻¹','N m⁻² s'], answer: 0 },
      { q: 'Two vectors of magnitude 5 N and 12 N act on a point. Which of the following is NOT a possible magnitude of their resultant?', options: ['18 N','17 N','13 N','7 N'], answer: 0 },
      { q: 'A student uses dimensional analysis to check E = ½mv² + mgh. Both terms have dimensions of:', options: ['kg m s⁻²','kg m² s⁻²','kg m s⁻¹','kg m² s⁻¹'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B3 */
  'B3': {
    name: 'Physics in Action',
    green: [
      { q: 'What is the equation for refractive index n in terms of wave speeds?', options: ['n = v₁/v₂','n = c/v','n = v/c','n = λ/f'], answer: 1 },
      { q: 'What happens to light when it enters a more optically dense medium?', options: ['It speeds up','It slows down','Its frequency changes','Its colour changes'], answer: 1 },
      { q: 'What is meant by total internal reflection?', options: ['All light is absorbed at a boundary','All light is refracted at a boundary','All light is reflected back into the denser medium at a boundary','Light is diffracted at a boundary'], answer: 2 },
      { q: 'What is the critical angle?', options: ['The angle of incidence at which the refracted ray travels along the boundary','The angle of refraction when light enters glass','The angle at which diffraction is maximum','The angle at which interference is constructive'], answer: 0 },
      { q: 'What is meant by the focal length of a converging lens?', options: ['The distance from the lens to the image','The distance from the lens to the focal point for parallel rays','The radius of curvature of the lens','The thickness of the lens at its centre'], answer: 1 },
      { q: 'What quantity does a potential divider circuit divide?', options: ['Current','Resistance','Voltage','Power'], answer: 2 },
      { q: 'What is the Young modulus a measure of?', options: ['The strength of a material','The stiffness of a material','The hardness of a material','The density of a material'], answer: 1 },
      { q: 'Stress is defined as:', options: ['Force × area','Force / area','Extension / original length','Force × extension'], answer: 1 },
      { q: 'Strain is defined as:', options: ['Force per unit area','Extension divided by original length','Stress divided by Young modulus','Energy per unit volume'], answer: 1 },
      { q: 'What is the unit of the Young modulus?', options: ['N','N m','Pa','J'], answer: 2 },
      { q: 'In a digital signal, the number of bits per sample determines the:', options: ['Sampling rate','Resolution of the signal','Frequency of the signal','Bandwidth'], answer: 1 },
      { q: 'What is meant by the resolution of a digital image?', options: ['The brightness of the image','The number of pixels in the image','The colour depth only','The file size'], answer: 1 },
      { q: 'What type of lens produces a virtual, upright, magnified image when the object is within the focal length?', options: ['Diverging lens','Converging lens','Cylindrical lens','Flat lens'], answer: 1 },
      { q: 'What is Snell\'s law?', options: ['n₁ sin θ₁ = n₂ sin θ₂','n₁ cos θ₁ = n₂ cos θ₂','n₁ tan θ₁ = n₂ tan θ₂','n₁/sin θ₁ = n₂/sin θ₂'], answer: 0 },
      { q: 'What is an analogue signal?', options: ['A signal that can only take discrete values','A signal that varies continuously','A signal transmitted as binary','A signal with only two levels'], answer: 1 },
      { q: 'What does a sensor do?', options: ['It stores data','It converts a physical quantity into an electrical signal','It amplifies signals only','It displays information'], answer: 1 },
      { q: 'What is the Rayleigh criterion related to?', options: ['The maximum stress a material can withstand','The minimum resolvable angular separation of two sources','The critical angle for total internal reflection','The sampling frequency for digital signals'], answer: 1 },
      { q: 'What is a pixel?', options: ['A unit of frequency','The smallest addressable element of a digital image','A type of lens','A unit of resolution in optics'], answer: 1 },
      { q: 'In a potential divider with two resistors R₁ and R₂ in series, V_out across R₂ is given by:', options: ['V_in × R₁/(R₁+R₂)','V_in × R₂/(R₁+R₂)','V_in × (R₁+R₂)/R₂','V_in × R₂/R₁'], answer: 1 },
      { q: 'What is diffraction?', options: ['The splitting of white light into colours','The bending/spreading of waves as they pass through a gap or around an obstacle','The change in wave speed at a boundary','The combination of two or more waves'], answer: 1 },
    ],
    amber: [
      { q: 'Light travels from glass (n = 1.50) into air (n = 1.00). What is the critical angle?', options: ['30.0°','41.8°','48.6°','90.0°'], answer: 1 },
      { q: 'A wire of length 2.0 m and cross-sectional area 1.0 × 10⁻⁶ m² extends by 0.5 mm under a force of 50 N. What is the Young modulus?', options: ['2.0 × 10⁸ Pa','2.0 × 10¹¹ Pa','1.0 × 10⁸ Pa','1.0 × 10¹¹ Pa'], answer: 1 },
      { q: 'A potential divider has R₁ = 3 kΩ and R₂ = 7 kΩ with V_in = 10 V. What is V_out across R₂?', options: ['3 V','5 V','7 V','10 V'], answer: 2 },
      { q: 'A converging lens has focal length 15 cm. An object is placed 30 cm from the lens. Where is the image formed?', options: ['10 cm','15 cm','30 cm','60 cm'], answer: 2 },
      { q: 'The Rayleigh criterion states that two sources are just resolved when the angular separation θ ≈:', options: ['λ/D','λD','D/λ','λ²/D'], answer: 0 },
      { q: 'A material has a stress–strain graph that is linear up to point A, then curves. Point A is the:', options: ['Breaking point','Yield point','Limit of proportionality','Elastic limit'], answer: 2 },
      { q: 'The area under a force–extension graph represents:', options: ['The Young modulus','The strain energy stored','The stress','The spring constant'], answer: 1 },
      { q: 'A digital signal is sampled at 44 100 Hz with 16-bit depth. How many signal levels are available?', options: ['44 100','16','65 536','2¹⁶ − 1'], answer: 2 },
      { q: 'An image sensor has 4000 × 3000 pixels. How many megapixels does it have?', options: ['7','12','16','24'], answer: 1 },
      { q: 'According to the Nyquist theorem, the sampling frequency must be at least:', options: ['Equal to the signal frequency','Twice the highest signal frequency','Half the signal frequency','Ten times the signal frequency'], answer: 1 },
      { q: 'A thermistor is used in a potential divider. As temperature increases, the resistance of an NTC thermistor:', options: ['Increases','Decreases','Stays the same','First increases then decreases'], answer: 1 },
      { q: 'Light passes through a single slit of width a. The angular position of the first minimum is given by sin θ =', options: ['λ/a','a/λ','2λ/a','λ/(2a)'], answer: 0 },
      { q: 'A copper wire has a Young modulus of 1.2 × 10¹¹ Pa. If the stress on the wire is 6.0 × 10⁷ Pa, what is the strain?', options: ['5.0 × 10⁻⁴','2.0 × 10⁻³','5.0 × 10⁻³','7.2 × 10³'], answer: 0 },
      { q: 'An LDR is placed in a potential divider circuit. In bright light, the output voltage across the LDR will be:', options: ['High, because its resistance is high','Low, because its resistance is low','Zero','Equal to the supply voltage'], answer: 1 },
      { q: 'A lens produces a magnification of −2. What does the negative sign indicate?', options: ['The image is diminished','The image is virtual','The image is inverted','The image is the same size as the object'], answer: 2 },
      { q: 'The resolving power of a telescope can be improved by:', options: ['Using a smaller objective lens','Using a larger objective lens','Using a longer focal length eyepiece','Reducing the light intensity'], answer: 1 },
      { q: 'A rubber band is stretched and released. The force–extension graph shows a hysteresis loop. The area of the loop represents:', options: ['The elastic potential energy stored','The energy dissipated as heat','The Young modulus','The breaking stress'], answer: 1 },
      { q: 'What advantage does digital signalling have over analogue signalling?', options: ['Higher bandwidth requirement','Signals can be regenerated without degradation','No sampling is needed','Simpler circuitry always'], answer: 1 },
      { q: 'A wire obeys Hooke\'s law up to a force of 40 N, at which point the extension is 2.0 mm. What is the spring constant?', options: ['20 N m⁻¹','80 N m⁻¹','2.0 × 10⁴ N m⁻¹','20 000 N m⁻¹'], answer: 2 },
      { q: 'A converging lens is used as a magnifying glass. For the image to be virtual, the object must be placed:', options: ['At the focal point','Beyond 2f','Between f and 2f','Between the lens and f'], answer: 3 },
    ],
    red: [
      { q: 'A telescope has an objective lens of diameter 0.10 m and observes light of wavelength 550 nm. What is the minimum angular resolution?', options: ['6.7 × 10⁻⁶ rad','5.5 × 10⁻⁶ rad','6.7 × 10⁻³ rad','5.5 × 10⁻³ rad'], answer: 0 },
      { q: 'A material undergoes plastic deformation. Which statement is correct?', options: ['The material has exceeded its elastic limit and is permanently deformed','The material returns to its original length when the force is removed','The strain energy is fully recoverable','The stress is still within the limit of proportionality'], answer: 0 },
      { q: 'Two thin wires A and B are made of the same material. Wire A has twice the length and half the diameter of wire B. The ratio of their extensions under the same force is:', options: ['16:1','8:1','4:1','2:1'], answer: 1 },
      { q: 'A student claims that increasing the number of bits per sample in a digital system always improves the quality of a reconstructed signal. Which statement best evaluates this claim?', options: ['Incorrect — bit depth only affects file size','Partially correct — more bits improve resolution but the sampling rate must also satisfy the Nyquist criterion','Incorrect — only sampling rate affects quality','Correct — more bits always means a perfect signal'], answer: 1 },
      { q: 'A converging lens of focal length 20 cm forms a real image. The object is moved from 60 cm to 40 cm from the lens. How does the image change?', options: ['It moves from 40 cm to 30 cm and gets smaller','It moves from 30 cm to 40 cm from the lens and gets larger','It becomes virtual','It moves from 30 cm to 40 cm and remains the same size'], answer: 1 },
      { q: 'A sensor has a sensitivity of 20 mV/°C and is connected in a potential divider. If the signal is digitised with an 8-bit ADC over a range of 0–5 V, what is the smallest temperature change that can be detected?', options: ['0.05 °C','0.98 °C','1.0 °C','5.0 °C'], answer: 1 },
      { q: 'Two point sources are observed through a circular aperture. According to the Rayleigh criterion, they are just resolved when:', options: ['The patterns do not overlap at all','The central maxima of both patterns overlap completely','The central maximum of one diffraction pattern falls on the first minimum of the other','The second maxima overlap'], answer: 2 },
      { q: 'A stress–strain graph for a ductile metal shows a large area under the curve beyond the elastic limit. This indicates the material has high:', options: ['Toughness','Elastic strain energy','Stiffness','Brittleness'], answer: 0 },
      { q: 'A fibre optic cable uses total internal reflection to transmit signals. Multipath dispersion can be reduced by:', options: ['Increasing the core diameter','Using a graded-index fibre or single-mode fibre','Increasing the refractive index of the cladding above that of the core','Using analogue rather than digital signals'], answer: 1 },
      { q: 'A strain gauge is attached to a beam under load. The gauge factor is 2.0 and the fractional change in resistance is 0.001. What is the strain?', options: ['0.0005','0.001','0.002','0.02'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B4 */
  'B4': {
    name: 'Understanding Processes',
    green: [
      { q: 'What is superposition of waves?', options: ['Waves always cancel each other out','The resultant displacement is the vector sum of individual displacements','Waves cannot pass through each other','The frequency of waves doubles when they meet'], answer: 1 },
      { q: 'What is constructive interference?', options: ['When waves cancel out','When the resultant amplitude is greater than either individual amplitude due to waves being in phase','When waves are reflected','When waves change frequency'], answer: 1 },
      { q: 'What is destructive interference?', options: ['When waves combine to give a larger amplitude','When waves arrive in antiphase and cancel each other out','When waves are absorbed','When the wavelength decreases'], answer: 1 },
      { q: 'What is a standing (stationary) wave?', options: ['A wave travelling in one direction','A wave that results from the superposition of two waves of the same frequency travelling in opposite directions','A wave with zero frequency','A longitudinal wave only'], answer: 1 },
      { q: 'At a node on a standing wave, the displacement is always:', options: ['Maximum','Zero','Varying sinusoidally','Equal to the wavelength'], answer: 1 },
      { q: 'At an antinode on a standing wave, the displacement is:', options: ['Always zero','Maximum','Constant','Equal to the wavelength'], answer: 1 },
      { q: 'What is the path difference for constructive interference?', options: ['nλ (a whole number of wavelengths)','(n+½)λ','λ/4','Any value'], answer: 0 },
      { q: 'What is meant by coherent sources?', options: ['Sources with the same amplitude','Sources with a constant phase difference and the same frequency','Sources that are very bright','Sources that are monochromatic only'], answer: 1 },
      { q: 'What is the de Broglie wavelength?', options: ['The wavelength of light emitted by an atom','The wavelength associated with a moving particle, given by λ = h/p','The wavelength of an electron in orbit','The wavelength of a photon only'], answer: 1 },
      { q: 'What is a photon?', options: ['A particle of matter','A quantum of electromagnetic radiation','An electron','A proton'], answer: 1 },
      { q: 'The energy of a photon is given by:', options: ['E = mc²','E = hf','E = ½mv²','E = mgh'], answer: 1 },
      { q: 'What is wave–particle duality?', options: ['Waves and particles are the same thing','Light and matter can exhibit both wave-like and particle-like behaviour','Only light shows duality','Only electrons show duality'], answer: 1 },
      { q: 'In Young\'s double-slit experiment, what pattern is observed on the screen?', options: ['A single bright line','A series of equally spaced bright and dark fringes','A continuous spectrum','A single dark region'], answer: 1 },
      { q: 'What does the photoelectric effect demonstrate?', options: ['The wave nature of light','The particle nature of light','That light travels in straight lines','That light can be polarised'], answer: 1 },
      { q: 'What is the threshold frequency in the photoelectric effect?', options: ['The highest frequency that causes emission','The minimum frequency below which no photoelectrons are emitted','The frequency of the emitted electrons','The frequency at which maximum current flows'], answer: 1 },
      { q: 'What is the work function of a metal?', options: ['The total energy of the metal','The maximum kinetic energy of emitted electrons','The minimum energy needed to release an electron from the surface','The energy of the photon'], answer: 2 },
      { q: 'What is meant by time dilation in special relativity?', options: ['Time runs faster for a moving observer','Time runs slower for a moving observer relative to a stationary observer','Time stops completely','Time is not affected by motion'], answer: 1 },
      { q: 'In Young\'s experiment, the fringe spacing depends on:', options: ['The slit width only','The wavelength, slit separation, and distance to the screen','The amplitude of the light','The intensity only'], answer: 1 },
      { q: 'A diffraction grating has many equally spaced slits. The condition for a bright maximum is:', options: ['d sin θ = nλ','d cos θ = nλ','d = nλ sin θ','sin θ = nd/λ'], answer: 0 },
      { q: 'What is the Planck constant?', options: ['A constant relating mass and energy','A constant relating photon energy and frequency (E = hf)','A constant in Newton\'s law of gravitation','A constant in Coulomb\'s law'], answer: 1 },
    ],
    amber: [
      { q: 'In a double-slit experiment, the slit separation is 0.5 mm, the screen is 1.5 m away, and the wavelength is 600 nm. What is the fringe spacing?', options: ['0.9 mm','1.8 mm','3.6 mm','0.45 mm'], answer: 1 },
      { q: 'A diffraction grating has 500 lines per mm. What is the slit spacing?', options: ['2 × 10⁻⁶ m','5 × 10⁻⁴ m','2 × 10⁻³ m','5 × 10⁻⁶ m'], answer: 0 },
      { q: 'For a standing wave on a string fixed at both ends, the fundamental frequency has:', options: ['One node and one antinode','Two nodes and one antinode','Two antinodes and one node','Three nodes and two antinodes'], answer: 1 },
      { q: 'An electron is accelerated through a potential difference of 100 V. Its de Broglie wavelength is approximately:', options: ['0.12 nm','1.2 nm','12 nm','0.012 nm'], answer: 0 },
      { q: 'Light of frequency 6.0 × 10¹⁴ Hz hits a metal surface with work function 2.0 eV. What is the maximum kinetic energy of the emitted electrons?', options: ['0.48 eV','0.50 eV','2.0 eV','4.5 eV'], answer: 1 },
      { q: 'A guitar string vibrates at its third harmonic. How many antinodes are present?', options: ['1','2','3','4'], answer: 2 },
      { q: 'In single-slit diffraction, the central maximum is:', options: ['The same width as the other maxima','Twice the width of the other maxima','Half the width of the other maxima','Narrower than the secondary maxima'], answer: 1 },
      { q: 'A diffraction grating with slit spacing 2.0 × 10⁻⁶ m is used with light of wavelength 600 nm. What is the maximum order of diffraction visible?', options: ['1','2','3','4'], answer: 2 },
      { q: 'The path difference between two coherent sources at a point is 1.5λ. The interference at this point is:', options: ['Constructive','Destructive','Neither — it depends on amplitude','Zero path difference'], answer: 1 },
      { q: 'An electron has momentum 1.5 × 10⁻²⁴ kg m s⁻¹. Its de Broglie wavelength is:', options: ['4.4 × 10⁻¹⁰ m','6.6 × 10⁻¹⁰ m','4.4 × 10⁻⁸ m','6.6 × 10⁻³⁴ m'], answer: 0 },
      { q: 'In the photoelectric effect, increasing the intensity of light above the threshold frequency causes:', options: ['An increase in the maximum kinetic energy of electrons','An increase in the number of emitted electrons per second','A decrease in the threshold frequency','No change'], answer: 1 },
      { q: 'A microwave oven produces standing waves. The distance between adjacent antinodes is 6.1 cm. What is the wavelength of the microwaves?', options: ['3.05 cm','6.1 cm','12.2 cm','24.4 cm'], answer: 2 },
      { q: 'Einstein\'s photoelectric equation is:', options: ['E = hf − φ','hf = φ + ½mv²_max','hf = ½mv²','φ = hf + ½mv²'], answer: 1 },
      { q: 'A standing wave in a pipe open at both ends has a fundamental frequency of 200 Hz. The frequency of the third harmonic is:', options: ['400 Hz','600 Hz','800 Hz','1000 Hz'], answer: 1 },
      { q: 'Two waves with the same frequency and amplitude, but a phase difference of π, produce:', options: ['Complete constructive interference','Complete destructive interference','Partial interference','No interference'], answer: 1 },
      { q: 'The de Broglie wavelength of a particle decreases when:', options: ['Its speed decreases','Its momentum increases','Its mass decreases','Its kinetic energy decreases'], answer: 1 },
      { q: 'White light passes through a diffraction grating. The first-order spectrum is observed. Which colour is diffracted through the largest angle?', options: ['Red','Green','Blue','Violet'], answer: 3 },
      { q: 'In the electron diffraction experiment, decreasing the accelerating voltage causes the diffraction rings to:', options: ['Become smaller','Become larger','Disappear','Remain the same'], answer: 1 },
      { q: 'In special relativity, the Lorentz factor γ = 1/√(1 − v²/c²). At v = 0.6c, γ equals:', options: ['1.00','1.25','1.50','2.00'], answer: 1 },
      { q: 'A standing wave on a string fixed at both ends has length 1.2 m and vibrates at the second harmonic. The wavelength is:', options: ['0.6 m','1.2 m','2.4 m','0.3 m'], answer: 1 },
    ],
    red: [
      { q: 'In a double-slit experiment with white light, the central fringe is white. Why do the fringes become coloured further from the centre?', options: ['Different wavelengths have different fringe spacings so colours separate','The slits act as a prism','Different colours have different intensities','Only red and blue are diffracted'], answer: 0 },
      { q: 'A photon has the same de Broglie wavelength as an electron. Which has greater energy?', options: ['The photon','The electron','They have the same energy','It depends on the wavelength'], answer: 0 },
      { q: 'In quantum physics, the probability of detecting a photon at a location is proportional to:', options: ['The square of the amplitude of the probability amplitude','The wavelength','The frequency','The amplitude of the wave function'], answer: 0 },
      { q: 'A diffraction grating is used to observe sodium doublet lines at 589.0 nm and 589.6 nm. To resolve them in the first order, the minimum number of slits illuminated must be approximately:', options: ['100','500','1000','5000'], answer: 2 },
      { q: 'The photoelectric effect cannot be explained by the wave model of light because:', options: ['Waves cannot transfer energy','The wave model predicts a time delay before emission and that any frequency should cause emission given enough intensity, which is not observed','The wave model predicts too many electrons','Waves cannot interact with electrons'], answer: 1 },
      { q: 'A standing wave has nodes separated by 0.30 m. The wave speed is 12 m s⁻¹. The frequency is:', options: ['10 Hz','20 Hz','40 Hz','60 Hz'], answer: 1 },
      { q: 'An electron and a proton are both accelerated from rest through the same potential difference. The ratio of their de Broglie wavelengths (λ_e/λ_p) is:', options: ['m_p/m_e','√(m_e/m_p)','m_e/m_p','√(m_p/m_e)'], answer: 3 },
      { q: 'In special relativity, a muon has a mean lifetime of 2.2 μs in its rest frame. If it travels at 0.995c, its observed lifetime is approximately:', options: ['11 μs','2.2 μs','44 μs','22 μs'], answer: 3 },
      { q: 'In the OCR B "many paths" approach to quantum physics, the probability of a photon arriving at a point is determined by:', options: ['Only the straight-line path','The sum of the amplitude arrows for all possible paths, then squaring the resultant','The product of all possible paths','The average of all path lengths'], answer: 1 },
      { q: 'A student argues that since electrons can be diffracted, they must be waves and cannot be particles. Which response best evaluates this claim?', options: ['Incorrect — electron diffraction is caused by particle collisions','Correct — the de Broglie hypothesis proves electrons are waves','Correct — electrons are purely waves','Incorrect — electrons show both wave and particle behaviour depending on the experiment'], answer: 3 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B5 */
  'B5': {
    name: 'Rise and Fall of the Clockwork Universe',
    green: [
      { q: 'What is the equation for displacement in uniform acceleration: s = ?', options: ['vt','ut + ½at²','v/t','at'], answer: 1 },
      { q: 'Newton\'s first law states that an object remains at rest or in uniform motion unless:', options: ['It has mass','It is in a vacuum','An external resultant force acts on it','It is moving in a circle'], answer: 2 },
      { q: 'Newton\'s second law is expressed as:', options: ['F = ma','F = mv','F = mg only','F = mv²/r'], answer: 0 },
      { q: 'What is the SI unit of momentum?', options: ['N','kg m s⁻¹','J','Pa'], answer: 1 },
      { q: 'What is the principle of conservation of momentum?', options: ['Momentum is always zero','Total momentum before a collision equals total momentum after, in a closed system','Momentum increases in every collision','Only kinetic energy is conserved'], answer: 1 },
      { q: 'What is the equation for kinetic energy?', options: ['½mv²','mgh','½kx²','Fv'], answer: 0 },
      { q: 'What provides the centripetal force for a car going around a bend?', options: ['The engine force','Gravity','Friction between tyres and road','Air resistance'], answer: 2 },
      { q: 'What is the condition for simple harmonic motion (SHM)?', options: ['Constant velocity','Acceleration proportional to displacement and directed towards the equilibrium position','Constant acceleration','Zero net force'], answer: 1 },
      { q: 'What is the ideal gas equation?', options: ['PV = nRT','PV = mRT','P = nRT/m','PV = NkT only'], answer: 0 },
      { q: 'What is the Boltzmann constant?', options: ['The gas constant per mole','The gas constant per molecule (k = R/Nₐ)','The Planck constant divided by 2π','The gravitational constant per unit mass'], answer: 1 },
      { q: 'Newton\'s third law states:', options: ['Forces always cancel out','Every action has an equal and opposite reaction on a different body','Force equals mass times acceleration','Objects at rest stay at rest'], answer: 1 },
      { q: 'What is gravitational potential energy near Earth\'s surface?', options: ['½mv²','mgh','GMm/r','½kx²'], answer: 1 },
      { q: 'The period of an oscillation is:', options: ['The number of cycles per second','The time for one complete oscillation','The maximum displacement','The speed of the wave'], answer: 1 },
      { q: 'What is the angular velocity ω of an object moving in a circle?', options: ['v/r','2πf','Both v/r and 2πf','Neither v/r nor 2πf'], answer: 2 },
      { q: 'Centripetal acceleration is directed:', options: ['Tangentially','Towards the centre of the circle','Away from the centre','Along the velocity'], answer: 1 },
      { q: 'The equation F = −kx describes:', options: ['Newton\'s second law','Hooke\'s law / the restoring force in SHM','Coulomb\'s law','The gravitational force'], answer: 1 },
      { q: 'In an ideal gas, the molecules are assumed to have:', options: ['Significant volume compared to the container','No intermolecular forces except during collisions','Constant speed','Attractive forces at all distances'], answer: 1 },
      { q: 'The mean kinetic energy of a gas molecule is given by:', options: ['½kT','(3/2)kT','kT','2kT'], answer: 1 },
      { q: 'What is Newton\'s law of gravitation?', options: ['F = mg','F = GMm/r²','F = Gm/r','F = GM/r²'], answer: 1 },
      { q: 'What is the unit of gravitational field strength?', options: ['N','N kg⁻¹','N m⁻²','J kg⁻¹'], answer: 1 },
    ],
    amber: [
      { q: 'A 2 kg object accelerates from rest to 10 m s⁻¹ in 4 s. What is the resultant force?', options: ['2.5 N','5 N','10 N','20 N'], answer: 1 },
      { q: 'A ball is thrown upward at 20 m s⁻¹. Ignoring air resistance, what is its maximum height? (g = 9.8 m s⁻²)', options: ['10.2 m','20.4 m','40.8 m','2.04 m'], answer: 1 },
      { q: 'Two objects of mass 3 kg and 5 kg approach each other at 4 m s⁻¹ and 2 m s⁻¹ respectively. They stick together. What is their velocity after collision?', options: ['0.25 m s⁻¹ in the direction of the 3 kg object','0.25 m s⁻¹ in the direction of the 5 kg object','1.5 m s⁻¹','0 m s⁻¹'], answer: 0 },
      { q: 'A car of mass 1200 kg travels at 15 m s⁻¹ around a bend of radius 50 m. What centripetal force is needed?', options: ['3600 N','5400 N','360 N','540 N'], answer: 1 },
      { q: 'The period of a simple pendulum is T = 2π√(l/g). If the length is doubled, the new period is:', options: ['T','√2 × T','2T','4T'], answer: 1 },
      { q: 'In SHM, at the equilibrium position the:', options: ['Displacement and velocity are both maximum','Displacement is zero and velocity is maximum','Velocity is zero and displacement is maximum','Acceleration is maximum'], answer: 1 },
      { q: 'An ideal gas at 300 K has a pressure of 100 kPa. If the temperature is raised to 600 K at constant volume, the new pressure is:', options: ['50 kPa','100 kPa','200 kPa','400 kPa'], answer: 2 },
      { q: 'A mass on a spring oscillates with amplitude 0.05 m and angular frequency 10 rad s⁻¹. What is the maximum speed?', options: ['0.05 m s⁻¹','0.5 m s⁻¹','5 m s⁻¹','50 m s⁻¹'], answer: 1 },
      { q: 'The gravitational field strength at the surface of a planet of mass M and radius R is:', options: ['GM/R','GM/R²','GMR','G/MR²'], answer: 1 },
      { q: 'A satellite orbits Earth in a circular orbit. The centripetal force is provided by:', options: ['The satellite\'s engines','Air resistance','Gravitational attraction','Electromagnetic force'], answer: 2 },
      { q: 'In SHM, the displacement x = A cos(ωt). The acceleration is:', options: ['−ω²A cos(ωt)','ω²A cos(ωt)','−ωA sin(ωt)','ωA cos(ωt)'], answer: 0 },
      { q: 'A gas occupies 0.02 m³ at 200 kPa and 400 K. How many moles are present? (R = 8.31 J mol⁻¹ K⁻¹)', options: ['0.6','1.2','2.4','4.8'], answer: 1 },
      { q: 'A projectile is launched at 30° to the horizontal at 40 m s⁻¹. Its initial vertical component of velocity is:', options: ['20 m s⁻¹','34.6 m s⁻¹','40 m s⁻¹','10 m s⁻¹'], answer: 0 },
      { q: 'The total energy in SHM is:', options: ['½kA²','½kx²','½mv²','½kA² only at the equilibrium position'], answer: 0 },
      { q: 'The root-mean-square speed of gas molecules at temperature T and molar mass M is:', options: ['√(3RT/M)','√(RT/M)','3RT/M','RT/(3M)'], answer: 0 },
      { q: 'A geostationary satellite has an orbital period of:', options: ['90 minutes','12 hours','24 hours','365 days'], answer: 2 },
      { q: 'A 0.5 kg mass on a spring (k = 200 N m⁻¹) oscillates in SHM. What is the period?', options: ['0.10 s','0.31 s','0.50 s','1.00 s'], answer: 1 },
      { q: 'The gravitational potential at a distance r from a point mass M is:', options: ['−GM/r','GM/r','−GM/r²','GM/r²'], answer: 0 },
      { q: 'An elastic collision conserves:', options: ['Kinetic energy only','Momentum only','Both kinetic energy and momentum','Neither kinetic energy nor momentum'], answer: 2 },
      { q: 'A force of 10 N acts for 0.5 s on a 2 kg object initially at rest. What is the final speed?', options: ['1.0 m s⁻¹','2.5 m s⁻¹','5.0 m s⁻¹','10 m s⁻¹'], answer: 1 },
    ],
    red: [
      { q: 'A ball bounces off a wall. Its velocity changes from +5 m s⁻¹ to −4 m s⁻¹ in 0.1 s. If its mass is 0.2 kg, the average force exerted by the wall is:', options: ['10 N','18 N','9 N','2 N'], answer: 1 },
      { q: 'In a damped oscillation, the amplitude decreases exponentially. This means the total energy of the system:', options: ['Decreases linearly','Decreases exponentially with time','Remains constant','Increases linearly'], answer: 1 },
      { q: 'A planet orbits a star. By equating gravitational force to centripetal force, the orbital period T is related to orbital radius r by:', options: ['T³ ∝ r²','T² ∝ r³','T ∝ r²','T ∝ r'], answer: 1 },
      { q: 'Two identical gas samples are at the same temperature. Sample A is helium (M = 4) and sample B is oxygen (M = 32). The ratio of their rms speeds (v_He/v_O₂) is:', options: ['1/√8','1/8','8','√8'], answer: 3 },
      { q: 'A mass on a spring undergoes forced oscillations. Resonance occurs when:', options: ['The damping is maximum','The amplitude is zero','The driving frequency is much higher than the natural frequency','The driving frequency equals the natural frequency of the system'], answer: 3 },
      { q: 'A rocket ejects gas at a rate of dm/dt = 50 kg s⁻¹ at an exhaust velocity of 3000 m s⁻¹. The thrust produced is:', options: ['1500 N','60 N','15 000 N','150 000 N'], answer: 3 },
      { q: 'The second law of thermodynamics implies that:', options: ['Heat cannot spontaneously flow from a cold body to a hot body without work being done','Temperature is always uniform','Entropy always decreases','Energy is always conserved'], answer: 0 },
      { q: 'A body moves in a vertical circle on the end of a string. At the top of the circle, the minimum speed to maintain a taut string is:', options: ['gr','√(gr/2)','√(2gr)','√(gr)'], answer: 3 },
      { q: 'In SHM, the velocity as a function of displacement is v = ±ω√(A² − x²). At what displacement is the speed half the maximum speed?', options: ['A/2','A/√2','3A/4','A√3/2'], answer: 3 },
      { q: 'The gravitational potential energy of a mass m at distance r from a planet of mass M is −GMm/r. The escape velocity from the surface (radius R) is:', options: ['√(GM/R)','√(2GM/R)','2GM/R','GM/R²'], answer: 1 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── B6 */
  'B6': {
    name: 'Field and Particle Physics',
    green: [
      { q: 'Coulomb\'s law gives the force between two point charges as:', options: ['F = kQq/r','F = kQq/r²','F = kQ/r²','F = Qq/r'], answer: 1 },
      { q: 'What is the SI unit of electric field strength?', options: ['N','N C⁻¹ or V m⁻¹','C','J'], answer: 1 },
      { q: 'Electric field lines point:', options: ['From negative to positive','From positive to negative','In circles around charges','Perpendicular to the force'], answer: 1 },
      { q: 'What is a capacitor?', options: ['A device that stores charge on two separated conductors','A device that stores current','A type of resistor','A type of inductor'], answer: 0 },
      { q: 'The capacitance of a capacitor is defined as:', options: ['C = Q/V','C = V/Q','C = QV','C = Q²/V'], answer: 0 },
      { q: 'The SI unit of capacitance is the:', options: ['Coulomb','Volt','Farad','Ohm'], answer: 2 },
      { q: 'A magnetic field exerts a force on a current-carrying conductor. The force is given by:', options: ['F = BIl (when field is perpendicular to current)','F = BI/l','F = Bl/I','F = B/Il'], answer: 0 },
      { q: 'What is magnetic flux?', options: ['The magnetic field strength','The product of magnetic flux density and the area perpendicular to the field (Φ = BA)','The force on a wire','The current in a solenoid'], answer: 1 },
      { q: 'Faraday\'s law of electromagnetic induction states that the induced EMF is equal to:', options: ['The magnetic flux','The rate of change of magnetic flux linkage','The magnetic field strength','The current in the coil'], answer: 1 },
      { q: 'Lenz\'s law states that the direction of an induced EMF is such that it:', options: ['Increases the change producing it','Opposes the change producing it','Is always clockwise','Is always zero'], answer: 1 },
      { q: 'What are quarks?', options: ['Fundamental particles that make up leptons','Fundamental particles that make up hadrons (baryons and mesons)','A type of lepton','A type of boson'], answer: 1 },
      { q: 'How many quarks make up a baryon?', options: ['1','2','3','4'], answer: 2 },
      { q: 'How many quarks make up a meson?', options: ['1','2 (a quark and an antiquark)','3','4'], answer: 1 },
      { q: 'A proton consists of which combination of quarks?', options: ['uud','udd','uuu','ddd'], answer: 0 },
      { q: 'A neutron consists of which combination of quarks?', options: ['uud','udd','uuu','ddd'], answer: 1 },
      { q: 'What is the charge of an up quark?', options: ['+1','−1','+2/3','−1/3'], answer: 2 },
      { q: 'What is the charge of a down quark?', options: ['+1','−1','+2/3','−1/3'], answer: 3 },
      { q: 'What is an electron classified as in the Standard Model?', options: ['A baryon','A meson','A lepton','A quark'], answer: 2 },
      { q: 'What is nuclear binding energy?', options: ['The energy needed to separate a nucleus into its individual nucleons','The energy released when a nucleus is formed','Both of these descriptions','The kinetic energy of nucleons'], answer: 2 },
      { q: 'What is radioactive decay?', options: ['A chemical reaction','The spontaneous and random emission of radiation from an unstable nucleus','A process that can be sped up by heating','A process that only occurs in heavy elements'], answer: 1 },
    ],
    amber: [
      { q: 'Two charges of +3 μC and −5 μC are separated by 0.2 m. The force between them is (k = 8.99 × 10⁹ N m² C⁻²):', options: ['3.37 N (attractive)','3.37 N (repulsive)','0.337 N (attractive)','33.7 N (attractive)'], answer: 0 },
      { q: 'The electric field strength at a distance r from a point charge Q is:', options: ['E = kQ/r','E = kQ/r²','E = kQr','E = Q/(4πε₀r)'], answer: 1 },
      { q: 'A 100 μF capacitor is charged to 12 V. The energy stored is:', options: ['0.72 mJ','7.2 mJ','1.2 mJ','72 mJ'], answer: 1 },
      { q: 'A wire of length 0.3 m carrying a current of 5 A is in a magnetic field of 0.2 T perpendicular to the wire. The force on the wire is:', options: ['0.03 N','0.3 N','3 N','30 N'], answer: 1 },
      { q: 'The magnetic flux through a coil of 200 turns changes by 0.05 Wb in 0.1 s. The induced EMF is:', options: ['1 V','10 V','100 V','1000 V'], answer: 2 },
      { q: 'In a capacitor discharge circuit (C = 100 μF, R = 10 kΩ), the time constant is:', options: ['0.1 s','1.0 s','10 s','100 s'], answer: 1 },
      { q: 'The force on a charge q moving at velocity v perpendicular to a magnetic field B is:', options: ['F = qvB','F = qv/B','F = qB/v','F = qv²B'], answer: 0 },
      { q: 'A charged particle moves in a circle in a uniform magnetic field. The radius of the circle is:', options: ['mv/(qB)','qvB/m','mv²/(qB)','m/(qvB)'], answer: 0 },
      { q: 'The electric potential at a distance r from a point charge Q is:', options: ['V = kQ/r','V = kQ/r²','V = kQr','V = kQ²/r'], answer: 0 },
      { q: 'Capacitors of 4 μF and 6 μF are connected in parallel. The total capacitance is:', options: ['2.4 μF','5 μF','10 μF','24 μF'], answer: 2 },
      { q: 'Capacitors of 4 μF and 6 μF are connected in series. The total capacitance is:', options: ['2.4 μF','5 μF','10 μF','24 μF'], answer: 0 },
      { q: 'In beta-minus decay, a neutron changes into:', options: ['A proton, an electron, and an antineutrino','A proton and a positron','Two protons','A proton and a neutrino'], answer: 0 },
      { q: 'The binding energy per nucleon curve peaks around which element?', options: ['Hydrogen','Helium','Iron (Fe-56)','Uranium'], answer: 2 },
      { q: 'A radioactive isotope has a half-life of 6 hours. After 18 hours, the fraction of the original sample remaining is:', options: ['1/2','1/4','1/8','1/16'], answer: 2 },
      { q: 'The strong nuclear force:', options: ['Acts over infinite range','Is repulsive at all distances','Is attractive at short range (~1 fm) and has a very short range','Only acts on leptons'], answer: 2 },
      { q: 'The decay constant λ is related to half-life t₁/₂ by:', options: ['λ = ln 2 / t₁/₂','λ = t₁/₂ / ln 2','λ = 2 / t₁/₂','λ = t₁/₂ × ln 2'], answer: 0 },
      { q: 'An electron moves at 2.0 × 10⁶ m s⁻¹ perpendicular to a magnetic field of 0.5 T. The force on the electron is:', options: ['1.6 × 10⁻¹³ N','3.2 × 10⁻¹³ N','1.0 × 10⁻¹³ N','8.0 × 10⁻¹⁴ N'], answer: 0 },
      { q: 'In a uniform electric field between parallel plates separated by distance d with potential difference V, the field strength E is:', options: ['V × d','V / d','d / V','V² / d'], answer: 1 },
      { q: 'Which interaction is responsible for beta decay?', options: ['Strong nuclear force','Electromagnetic force','Weak nuclear force','Gravitational force'], answer: 2 },
      { q: 'A nucleus of ²³⁸U undergoes alpha decay. The daughter nucleus is:', options: ['²³⁴Th','²³⁴Pa','²³⁶U','²³⁸Np'], answer: 0 },
    ],
    red: [
      { q: 'The electric field between two parallel plates is uniform. A proton enters parallel to the plates midway between them. The path of the proton is:', options: ['A straight line','A circular arc','A parabola towards the negative plate','A hyperbola'], answer: 2 },
      { q: 'A capacitor discharges through a resistor. The charge Q on the capacitor at time t is Q = Q₀e^(−t/RC). After how many time constants has the charge fallen to about 5% of its initial value?', options: ['3','5','1','2'], answer: 0 },
      { q: 'Two point charges +Q and −Q are separated by distance d. At the midpoint between them, the electric field strength is:', options: ['Zero','kQ/(d/2)² directed from +Q to −Q','2kQ/(d/2)² directed from +Q to −Q','4kQ/d² directed from −Q to +Q'], answer: 2 },
      { q: 'A rectangular coil of N turns, area A, rotates at angular velocity ω in a uniform magnetic field B. The maximum EMF induced is:', options: ['NBAω','NBA/ω','NBA','NB/Aω'], answer: 0 },
      { q: 'In the Standard Model, the exchange particle for the electromagnetic interaction is the:', options: ['W boson','Photon','Z boson','Gluon'], answer: 1 },
      { q: 'A cyclotron accelerates protons. The maximum kinetic energy depends on:', options: ['The voltage between the dees only','The frequency of the alternating voltage only','The radius of the dees, the magnetic field strength, and the charge-to-mass ratio','The number of revolutions only'], answer: 2 },
      { q: 'Nuclear fission releases energy because the binding energy per nucleon of the products is:', options: ['The same as the parent nucleus','Zero','Less than that of the parent nucleus','Greater than that of the parent nucleus'], answer: 3 },
      { q: 'A sample has an activity of 800 Bq. The decay constant is 0.02 s⁻¹. The number of undecayed nuclei is:', options: ['16','400','16 000','40 000'], answer: 3 },
      { q: 'In deep inelastic scattering experiments, high-energy electrons are fired at protons. The results provide evidence for:', options: ['The wave nature of electrons','The existence of quarks as point-like constituents of protons','The existence of the neutron','The photoelectric effect'], answer: 1 },
      { q: 'A positron and an electron annihilate. The minimum total energy of the photons produced is:', options: ['0.511 MeV','1.022 MeV','1.5 MeV','2.044 MeV'], answer: 1 },
    ],
  },

};
