const CHEMISTRY_OCR_A_QUESTIONS = {

'M1': {
  name: 'Development of Practical Skills',
  green: [
    { q: 'What is the purpose of a risk assessment in a chemistry practical?', options: ['To outline the step-by-step experimental procedure and equipment required', 'To systematically identify hazards and specify appropriate control measures', 'To record equipment calibration data and ensure measurement traceability', 'To predict the theoretical yield and determine an acceptable percentage error'], answer: 1 },
    { q: 'Which piece of glassware is most appropriate for measuring exactly 25.0 cm\u00B3 of a solution?', options: ['Beaker', 'Measuring cylinder', 'Pipette', 'Conical flask'], answer: 2 },
    { q: 'What does the term "precision" mean in practical chemistry?', options: ['How close a result is to the true value', 'How close repeated measurements are to each other', 'The number of decimal places used', 'Whether the experiment is fair'], answer: 1 },
    { q: 'What is the resolution of a measuring instrument?', options: ['Its maximum reading', 'The smallest change it can detect', 'Its percentage error', 'The number of readings taken'], answer: 1 },
    { q: 'Which of the following is a systematic error?', options: ['Random fluctuations in temperature', 'A balance that always reads 0.02 g too high', 'Slight variations in titre volumes', 'Human reaction time in timing'], answer: 1 },
    { q: 'What colour change indicates the end point when using phenolphthalein indicator?', options: ['Yellow to red', 'Colourless to pink', 'Blue to colourless', 'Orange to yellow'], answer: 1 },
    { q: 'What is meant by the term "accuracy"?', options: ['How close repeated results are to each other', 'How close a result is to the true value', 'The number of significant figures', 'The range of the data'], answer: 1 },
    { q: 'Which hazard symbol indicates a substance is corrosive?', options: ['Flame symbol', 'Skull and crossbones', 'Exclamation mark', 'Corroding surface symbol'], answer: 3 },
    { q: 'What is a burette used for in a titration?', options: ['Measuring fixed volumes of solution', 'Adding the titrant drop by drop', 'Heating the solution', 'Filtering the mixture'], answer: 1 },
    { q: 'What type of error can be reduced by repeating an experiment and calculating a mean?', options: ['Systematic error', 'Random error', 'Zero error', 'Parallax error'], answer: 1 },
  ],
  amber: [
    { q: 'A student measures 25.0 cm\u00B3 using a pipette with an uncertainty of \u00B10.06 cm\u00B3. What is the percentage uncertainty?', options: ['0.06%', '0.12%', '0.24%', '0.6%'], answer: 2, explanation: 'Percentage uncertainty = (uncertainty \u00F7 measurement) \u00D7 100 = (0.06 \u00F7 25.0) \u00D7 100 = 0.24%. A common mistake is to quote the uncertainty value directly (0.06%) without dividing by the measurement volume.' },
    { q: 'In a titration, concordant results are those that agree within:', options: ['0.50 cm\u00B3', '0.10 cm\u00B3', '1.00 cm\u00B3', '0.01 cm\u00B3'], answer: 1 },
    { q: 'A student obtains titre values of 24.10, 24.15, 24.10, and 25.80 cm\u00B3. Which value should be excluded?', options: ['24.10', '24.15', '25.80', 'None should be excluded'], answer: 2 },
    { q: 'When calculating percentage uncertainty in a titre, you should use:', options: ['The mean titre', 'The maximum titre', 'Half the range of concordant results', 'The first titre only'], answer: 2 },
    { q: 'A burette has an uncertainty of \u00B10.05 cm\u00B3. For a single titre reading, the total uncertainty is:', options: ['\u00B10.05 cm\u00B3', '\u00B10.10 cm\u00B3', '\u00B10.15 cm\u00B3', '\u00B10.50 cm\u00B3'], answer: 1 },
    { q: 'Which technique is most suitable for determining the concentration of an unknown acid?', options: ['Distillation', 'Titration', 'Filtration', 'Chromatography'], answer: 1 },
    { q: 'A student heats a crucible to constant mass. This means they heat until:', options: ['The crucible glows red', 'Two consecutive masses agree within 0.01 g', 'Exactly 10 minutes have passed', 'The substance has melted'], answer: 1 },
    { q: 'The percentage error in using a 250 cm\u00B3 volumetric flask (\u00B10.23 cm\u00B3) is:', options: ['0.092%', '0.23%', '0.046%', '2.3%'], answer: 0, explanation: 'Percentage error = (absolute uncertainty \u00F7 total volume) \u00D7 100 = (0.23 \u00F7 250) \u00D7 100 = 0.092%. A very common mistake is option B \u2014 quoting the uncertainty (0.23) as if it were already a percentage. Option C would be the answer if the uncertainty were \u00B10.115 cm\u00B3.' },
    { q: 'In a calorimetry experiment, a student measures the temperature rise as 8.5 \u00B0C using a thermometer with uncertainty \u00B10.5 \u00B0C. The percentage uncertainty is approximately:', options: ['5.0%', '5.9%', '11.8%', '0.59%'], answer: 1, explanation: 'Percentage uncertainty = (\u00B10.5 \u00F7 8.5) \u00D7 100 \u2248 5.9%. Option C (11.8%) would apply if both a start and end reading were taken separately (2 \u00D7 0.5 \u00F7 8.5 \u00D7 100), since the uncertainty doubles when subtracting two readings. Option A (5.0%) is a rounding error.' },
    { q: 'When using a water bath instead of a Bunsen burner, the main advantage is:', options: ['It heats faster', 'It provides more even and controlled heating', 'It reaches higher temperatures', 'It uses less energy'], answer: 1 },
  ],
  red: [
    { q: 'A student obtains a percentage yield of 105%. The most likely explanation is:', options: ['The reaction produced more product than expected', 'The product was not fully dried before weighing', 'The equation was balanced incorrectly', 'Catalysts increased the yield above 100%'], answer: 1 },
    { q: 'In an experiment with multiple measurements, the overall percentage uncertainty is found by:', options: ['Adding all percentage uncertainties', 'Multiplying all percentage uncertainties', 'Subtracting systematic from random errors', 'Taking the largest single uncertainty'], answer: 0 },
    { q: 'A student claims their experiment is both precise and accurate. Which statement best describes this?', options: ['Repeated results are clustered closely around the true value', 'Repeated results are spread widely but centred on the true value', 'Repeated results are clustered together but far from the true value', 'The experiment had no anomalous results'], answer: 0 },
    { q: 'A student finds their experimental enthalpy of combustion is significantly less exothermic than the literature value. The most likely reason for this difference is:', options: ['Using a balance with a precision of 0.01 g rather than 0.001 g', 'Heat energy being lost to the surroundings and the calorimeter during the experiment', 'Reading the burette to the nearest 0.05 cm\u00B3 rather than 0.02 cm\u00B3', 'Using deionised water rather than distilled water, which has a slightly different specific heat capacity'], answer: 1 },
    { q: 'To reduce the percentage uncertainty when using a balance (\u00B10.001 g), a student should:', options: ['Use a more sensitive balance', 'Weigh a larger mass of substance', 'Take fewer readings', 'Use a volumetric flask instead'], answer: 1 },
  ],
},

'M2': {
  name: 'Foundations in Chemistry',
  green: [
    { q: 'What is the relative charge of a proton?', options: ['+1', '-1', '0', '+2'], answer: 0 },
    { q: 'What is the mass number of an atom?', options: ['Number of protons only', 'Number of protons + neutrons', 'Number of electrons', 'Number of neutrons only'], answer: 1 },
    { q: 'Isotopes of an element have the same number of:', options: ['Neutrons', 'Protons', 'Nucleons', 'Mass number'], answer: 1 },
    { q: 'What is the Avogadro constant?', options: ['6.02 \u00D7 10\u00B2\u00B3 mol\u207B\u00B9', '6.02 \u00D7 10\u00B2\u00B2 mol\u207B\u00B9', '3.01 \u00D7 10\u00B2\u00B3 mol\u207B\u00B9', '6.02 \u00D7 10\u00B2\u2074 mol\u207B\u00B9'], answer: 0 },
    { q: 'What is the formula for calculating moles from mass?', options: ['moles = mass \u00D7 Mr', 'moles = mass / Mr', 'moles = Mr / mass', 'moles = mass + Mr'], answer: 1 },
    { q: 'An ionic bond is formed by:', options: ['Sharing electrons', 'Transfer of electrons from one atom to another', 'Delocalised electrons', 'Dipole-dipole interactions'], answer: 1 },
    { q: 'A covalent bond involves:', options: ['Transfer of electrons', 'Sharing of one or more pairs of electrons', 'Attraction between ions', 'Metallic bonding'], answer: 1 },
    { q: 'What is the oxidation state of oxygen in most compounds?', options: ['+2', '-1', '-2', '0'], answer: 2 },
    { q: 'In a redox reaction, reduction is defined as:', options: ['Gain of oxygen', 'Loss of electrons', 'Gain of electrons', 'Increase in oxidation state'], answer: 2 },
    { q: 'Which of the following is a strong acid?', options: ['CH\u2083COOH', 'HCl', 'H\u2082CO\u2083', 'HCN'], answer: 1 },
    { q: 'What shape does a molecule with two bonding pairs and two lone pairs have?', options: ['Linear', 'Tetrahedral', 'Bent/V-shaped', 'Trigonal planar'], answer: 2 },
    { q: 'What is an empirical formula?', options: ['The actual number of atoms in a molecule', 'The simplest whole number ratio of atoms', 'The formula showing all bonds', 'The structural formula'], answer: 1 },
    { q: 'What type of bonding is present in solid sodium chloride?', options: ['Covalent', 'Metallic', 'Ionic', 'Van der Waals'], answer: 2 },
    { q: 'What is the charge on a sulfate ion?', options: ['-1', '-2', '+2', '-3'], answer: 1 },
    { q: 'The first ionisation energy is the energy required to:', options: ['Add an electron to a gaseous atom', 'Remove one mole of electrons from one mole of gaseous atoms', 'Break a covalent bond', 'Melt an ionic compound'], answer: 1 },
    { q: 'What is the bond angle in a tetrahedral molecule?', options: ['90\u00B0', '104.5\u00B0', '109.5\u00B0', '120\u00B0'], answer: 2 },
    { q: 'Which sub-shell fills after 3p?', options: ['3d', '4s', '4p', '4d'], answer: 1 },
    { q: 'How many electrons can a d sub-shell hold?', options: ['2', '6', '10', '14'], answer: 2 },
    { q: 'What is the electron configuration of sodium (Z=11)?', options: ['1s\u00B2 2s\u00B2 2p\u2076 3s\u00B9', '1s\u00B2 2s\u00B2 2p\u2076 3p\u00B9', '1s\u00B2 2s\u00B2 2p\u2077', '1s\u00B2 2s\u00B3 2p\u2076'], answer: 0 },
    { q: 'A dative covalent bond is one where:', options: ['Electrons are transferred', 'Both electrons in the shared pair come from the same atom', 'Electrons are delocalised', 'The bond is between two metals'], answer: 1 },
  ],
  amber: [
    { q: 'Chlorine has two isotopes: \u00B3\u2075Cl (75.8%) and \u00B3\u2077Cl (24.2%). What is the relative atomic mass?', options: ['35.0', '35.5', '36.0', '35.2'], answer: 1 },
    { q: 'What mass of NaOH (Mr = 40.0) is needed to make 250 cm\u00B3 of a 0.10 mol dm\u207B\u00B3 solution?', options: ['0.50 g', '1.00 g', '2.50 g', '4.00 g'], answer: 1 },
    { q: 'In the reaction 2Na + 2H\u2082O \u2192 2NaOH + H\u2082, sodium is:', options: ['Reduced', 'Oxidised', 'Neither oxidised nor reduced', 'Acting as a catalyst'], answer: 1 },
    { q: 'What is the oxidation state of sulfur in SO\u2084\u00B2\u207B?', options: ['+4', '+6', '-2', '+2'], answer: 1 },
    { q: 'Which molecule has a trigonal pyramidal shape?', options: ['BF\u2083', 'NH\u2083', 'CH\u2084', 'CO\u2082'], answer: 1 },
    { q: 'The bond angle in water is approximately 104.5\u00B0 rather than 109.5\u00B0 because:', options: ['Water has double bonds', 'Lone pairs repel more than bonding pairs', 'Oxygen is very electronegative', 'Hydrogen atoms are small'], answer: 1 },
    { q: 'How many moles of HCl are needed to neutralise 0.05 mol of Na\u2082CO\u2083?', options: ['0.025 mol', '0.05 mol', '0.10 mol', '0.20 mol'], answer: 2 },
    { q: 'What volume of 0.20 mol dm\u207B\u00B3 HCl is needed to react with 25.0 cm\u00B3 of 0.10 mol dm\u207B\u00B3 NaOH?', options: ['12.5 cm\u00B3', '25.0 cm\u00B3', '50.0 cm\u00B3', '10.0 cm\u00B3'], answer: 0 },
    { q: 'Which of the following species acts as both an oxidising and reducing agent in disproportionation?', options: ['The reactant element', 'The product', 'The solvent', 'The catalyst'], answer: 0 },
    { q: 'The electron configuration of Fe\u00B2\u207A (Z=26) is:', options: ['1s\u00B2 2s\u00B2 2p\u2076 3s\u00B2 3p\u2076 3d\u2076', '1s\u00B2 2s\u00B2 2p\u2076 3s\u00B2 3p\u2076 3d\u2074 4s\u00B2', '1s\u00B2 2s\u00B2 2p\u2076 3s\u00B2 3p\u2076 3d\u2075 4s\u00B9', '1s\u00B2 2s\u00B2 2p\u2076 3s\u00B2 3p\u2076 4s\u00B2'], answer: 0 },
    { q: 'A compound has the composition 40.0% C, 6.7% H, and 53.3% O by mass. The empirical formula is:', options: ['CHO', 'CH\u2082O', 'C\u2082H\u2084O\u2082', 'CHO\u2082'], answer: 1 },
    { q: 'What is the concentration in mol dm\u207B\u00B3 of a solution containing 7.30 g of HCl (Mr = 36.5) in 500 cm\u00B3?', options: ['0.10', '0.20', '0.40', '1.00'], answer: 2 },
    { q: 'Metallic bonding involves:', options: ['Shared pairs of electrons between two atoms', 'Attraction between cations and a sea of delocalised electrons', 'Transfer of electrons to form ions', 'Intermolecular forces between molecules'], answer: 1 },
    { q: 'Which of these has the highest boiling point?', options: ['NaCl', 'Cl\u2082', 'CH\u2084', 'HCl'], answer: 0 },
    { q: 'London dispersion forces increase with:', options: ['Increasing polarity', 'Increasing number of electrons', 'Decreasing molecular mass', 'Increasing electronegativity'], answer: 1 },
    { q: 'Hydrogen bonding occurs between molecules that contain:', options: ['Any polar bond', 'H bonded to C only', 'H bonded to N, O, or F', 'H bonded to any halogen'], answer: 2 },
    { q: 'What is the oxidation state of Mn in KMnO\u2084?', options: ['+4', '+5', '+6', '+7'], answer: 3 },
    { q: '0.25 mol of a gas occupies what volume at RTP (24.0 dm\u00B3 mol\u207B\u00B9)?', options: ['2.4 dm\u00B3', '6.0 dm\u00B3', '12.0 dm\u00B3', '24.0 dm\u00B3'], answer: 1 },
    { q: 'In a titration, 25.0 cm\u00B3 of 0.10 mol dm\u207B\u00B3 NaOH reacted with 20.0 cm\u00B3 of H\u2082SO\u2084. The concentration of the acid is:', options: ['0.0625 mol dm\u207B\u00B3', '0.125 mol dm\u207B\u00B3', '0.0500 mol dm\u207B\u00B3', '0.250 mol dm\u207B\u00B3'], answer: 0 },
  ],
  red: [
    { q: 'Which statement explains why the second ionisation energy of sodium is much higher than the first?', options: ['The electron is removed from a full 2p sub-shell, which is closer to the nucleus and more shielded', 'The second electron is removed from a lower energy level with less shielding, so the nuclear attraction is much greater', 'Sodium has only one electron so the second cannot be removed', 'The electron-electron repulsion decreases after the first removal'], answer: 1 },
    { q: 'Which of the following best explains the trend in first ionisation energy across Period 3?', options: ['It decreases steadily due to increasing atomic radius', 'It generally increases but with dips at Al and S due to sub-shell and electron pairing effects', 'It increases steadily with no exceptions', 'It alternates due to changes in electron spin'], answer: 1 },
    { q: 'An oxide X reacts with both acids and bases. X is most likely:', options: ['Na\u2082O', 'MgO', 'Al\u2082O\u2083', 'SO\u2083'], answer: 2 },
    { q: 'In the reaction: MnO\u2084\u207B + 8H\u207A + 5Fe\u00B2\u207A \u2192 Mn\u00B2\u207A + 5Fe\u00B3\u207A + 4H\u2082O, the oxidation state of Mn changes from:', options: ['+7 to +4', '+7 to +2', '+4 to +2', '+6 to +2'], answer: 1 },
    { q: 'A gaseous compound has Mr = 60 and empirical formula CH\u2082O. Its molecular formula is:', options: ['CH\u2082O', 'C\u2082H\u2084O\u2082', 'C\u2083H\u2086O\u2083', 'C\u2084H\u2088O\u2084'], answer: 1 },
    { q: 'Ice has a lower density than liquid water because:', options: ['Hydrogen bonds break when ice melts', 'In ice, hydrogen bonds hold molecules in an open lattice with spaces', 'Ice molecules vibrate less than liquid water molecules', 'The O-H bonds are shorter in ice'], answer: 1 },
    { q: 'Which combination correctly describes diamond?', options: ['Giant covalent, high melting point, conducts electricity', 'Giant covalent, high melting point, does not conduct electricity', 'Simple molecular, low melting point, does not conduct electricity', 'Giant ionic, high melting point, conducts when molten'], answer: 1 },
    { q: 'The ideal gas equation is PV = nRT. What are the correct SI units for pressure and volume?', options: ['atm and cm\u00B3', 'Pa and dm\u00B3', 'Pa and m\u00B3', 'kPa and dm\u00B3'], answer: 2 },
    { q: 'SF\u2086 has no overall dipole moment because:', options: ['S-F bonds are non-polar', 'The octahedral shape means the polar bonds cancel out', 'Sulfur has no lone pairs and the molecule is linear', 'Fluorine atoms are too small to create a dipole'], answer: 1 },
    { q: 'Which of these species has the shortest bond length?', options: ['N\u2082 (triple bond)', 'O\u2082 (double bond)', 'F\u2082 (single bond)', 'Cl\u2082 (single bond)'], answer: 0 },
  ],
},

'M3': {
  name: 'Periodic Table and Energy',
  green: [
    { q: 'Periodicity refers to:', options: ['The mass of elements increasing', 'Repeating trends in properties across periods', 'Elements in the same group having different properties', 'Radioactive decay patterns'], answer: 1 },
    { q: 'Group 2 metals react with water to form:', options: ['An acidic solution and hydrogen', 'A metal oxide and water', 'An alkaline solution and hydrogen', 'A metal hydroxide and oxygen'], answer: 2 },
    { q: 'Which Group 7 element is a liquid at room temperature?', options: ['Fluorine', 'Chlorine', 'Bromine', 'Iodine'], answer: 2 },
    { q: 'Enthalpy of combustion is always:', options: ['Positive', 'Negative', 'Zero', 'It varies'], answer: 1 },
    { q: 'An exothermic reaction has:', options: ['A positive enthalpy change', 'A negative enthalpy change', 'No enthalpy change', 'An enthalpy change that depends on temperature'], answer: 1 },
    { q: 'A catalyst works by:', options: ['Increasing the enthalpy change', 'Providing an alternative reaction pathway with lower activation energy', 'Increasing the concentration of reactants', 'Raising the temperature of the reaction'], answer: 1 },
    { q: 'What is the unit of rate of reaction?', options: ['mol', 'mol dm\u207B\u00B3', 'mol dm\u207B\u00B3 s\u207B\u00B9', 'J mol\u207B\u00B9'], answer: 2 },
    { q: 'At equilibrium:', options: ['The forward reaction has stopped', 'Concentrations of reactants and products are equal', 'The rates of forward and reverse reactions are equal', 'Only the reverse reaction occurs'], answer: 2 },
    { q: 'Le Chatelier\'s principle states that a system at equilibrium will:', options: ['Always shift to the right', 'Oppose any change imposed on it', 'Increase the yield of products', 'Remain unchanged'], answer: 1 },
    { q: 'Down Group 2, the first ionisation energy:', options: ['Increases', 'Decreases', 'Stays the same', 'Alternates'], answer: 1 },
    { q: 'Which Group 2 carbonate is most thermally stable?', options: ['MgCO\u2083', 'CaCO\u2083', 'SrCO\u2083', 'BaCO\u2083'], answer: 3 },
    { q: 'The colour of chlorine gas is:', options: ['Brown', 'Yellow-green', 'Purple', 'Colourless'], answer: 1 },
    { q: 'A bond enthalpy is defined as the energy required to:', options: ['Form one mole of bonds in the gas phase', 'Break one mole of a specific covalent bond in the gas phase', 'Break an ionic lattice', 'Form a compound from its elements'], answer: 1 },
    { q: 'Increasing temperature increases rate of reaction because:', options: ['More particles have energy greater than the activation energy', 'The activation energy decreases', 'Molecules get larger', 'Pressure increases'], answer: 0 },
    { q: 'The Boltzmann distribution shows:', options: ['The arrangement of electrons in atoms', 'The distribution of molecular energies at a given temperature', 'How catalysts change enthalpy', 'The structure of the periodic table'], answer: 1 },
    { q: 'Hess\'s Law states that the enthalpy change for a reaction is:', options: ['Always negative', 'Independent of the route taken', 'Equal to the sum of bond enthalpies', 'Dependent on the catalyst used'], answer: 1 },
    { q: 'What happens to the position of equilibrium if pressure is increased in a gaseous reaction?', options: ['Shifts to the side with more moles of gas', 'Shifts to the side with fewer moles of gas', 'No effect', 'The equilibrium constant changes'], answer: 1 },
    { q: 'Down Group 7, the boiling points of the elements:', options: ['Decrease', 'Increase', 'Stay the same', 'Alternate'], answer: 1 },
    { q: 'Which halide ion is the strongest reducing agent?', options: ['F\u207B', 'Cl\u207B', 'Br\u207B', 'I\u207B'], answer: 3 },
    { q: 'The standard enthalpy of formation is measured under conditions of:', options: ['273 K and 1 atm', '298 K and 100 kPa', '298 K and 1 atm', '373 K and 100 kPa'], answer: 1 },
  ],
  amber: [
    { q: 'Using bond enthalpies: C-H = 412, O=O = 496, C=O = 743, O-H = 463 kJ mol\u207B\u00B9, estimate \u0394H for CH\u2084 + 2O\u2082 \u2192 CO\u2082 + 2H\u2082O.', options: ['-818 kJ mol\u207B\u00B9', '-890 kJ mol\u207B\u00B9', '-648 kJ mol\u207B\u00B9', '+818 kJ mol\u207B\u00B9'], answer: 0 },
    { q: 'If the equilibrium N\u2082 + 3H\u2082 \u21CC 2NH\u2083 is exothermic, increasing temperature will:', options: ['Increase yield of NH\u2083', 'Decrease yield of NH\u2083', 'Have no effect', 'Stop the reaction'], answer: 1 },
    { q: 'Chlorine reacts with NaOH(aq) to form NaCl, NaClO, and water. This is an example of:', options: ['Neutralisation', 'Disproportionation', 'Displacement', 'Decomposition'], answer: 1 },
    { q: 'Which Group 2 hydroxide is the least soluble?', options: ['Mg(OH)\u2082', 'Ca(OH)\u2082', 'Sr(OH)\u2082', 'Ba(OH)\u2082'], answer: 0 },
    { q: 'Adding a catalyst to a system at equilibrium:', options: ['Shifts equilibrium to the right', 'Shifts equilibrium to the left', 'Increases the equilibrium constant', 'Does not change the position of equilibrium'], answer: 3 },
    { q: 'Using Hess\'s Law and the enthalpies of formation: \u0394Hf[CO\u2082] = -394, \u0394Hf[H\u2082O] = -286, \u0394Hf[CH\u2084] = -75 kJ mol\u207B\u00B9, calculate \u0394H for CH\u2084 + 2O\u2082 \u2192 CO\u2082 + 2H\u2082O.', options: ['-605 kJ mol\u207B\u00B9', '-891 kJ mol\u207B\u00B9', '-755 kJ mol\u207B\u00B9', '+891 kJ mol\u207B\u00B9'], answer: 1 },
    { q: 'Chlorine displaces bromine from KBr solution because:', options: ['Chlorine is less reactive than bromine', 'Chlorine is a stronger oxidising agent than bromine', 'Bromine is a gas', 'Potassium reacts with chlorine'], answer: 1 },
    { q: 'The thermal decomposition temperature of Group 2 carbonates increases down the group because:', options: ['The cation size increases, so the carbonate ion is less polarised and harder to decompose', 'Larger cations have higher charge density', 'The bonding becomes more covalent', 'The mass of the carbonate increases'], answer: 0 },
    { q: 'An increase in concentration of reactants increases rate because:', options: ['Activation energy decreases', 'There are more frequent collisions between reactant particles', 'The temperature increases', 'The enthalpy change becomes more negative'], answer: 1 },
    { q: 'In the equilibrium 2SO\u2082(g) + O\u2082(g) \u21CC 2SO\u2083(g), the total moles of gas on the left is:', options: ['2', '3', '4', '1'], answer: 1 },
    { q: 'Silver nitrate solution is used to test for halide ions. AgCl precipitate is:', options: ['Yellow', 'White', 'Cream', 'No precipitate forms'], answer: 1 },
    { q: 'Barium chloride is used to test for:', options: ['Halide ions', 'Sulfate ions', 'Carbonate ions', 'Ammonium ions'], answer: 1 },
    { q: 'Down Group 2, reactivity with water:', options: ['Decreases', 'Increases', 'Stays the same', 'Only Mg reacts'], answer: 1 },
    { q: 'The enthalpy profile for an endothermic reaction shows:', options: ['Products lower than reactants', 'Products higher than reactants', 'Products at the same level as reactants', 'No activation energy hump'], answer: 1 },
    { q: 'On a Boltzmann distribution, increasing temperature:', options: ['Shifts the peak to the left and lowers it', 'Shifts the peak to the right and lowers it', 'Raises the peak but does not shift it', 'Narrows the distribution'], answer: 1 },
    { q: 'The equilibrium constant Kc for A \u21CC B is 0.01. This means:', options: ['The reaction goes almost to completion', 'The equilibrium lies to the left (favouring reactants)', 'The equilibrium lies to the right (favouring products)', 'The reaction is at equilibrium only at high temperature'], answer: 1 },
    { q: 'Mg burns in air to form:', options: ['MgO only', 'MgO and Mg\u2083N\u2082', 'Mg(OH)\u2082', 'MgCO\u2083'], answer: 1 },
    { q: 'The test for chloride ions using AgNO\u2083 and then NH\u2083(aq) shows that AgCl:', options: ['Is insoluble in both dilute and concentrated NH\u2083', 'Dissolves in dilute NH\u2083(aq)', 'Dissolves only in concentrated NH\u2083(aq)', 'Does not form a precipitate'], answer: 1 },
    { q: 'AgBr precipitate is what colour?', options: ['White', 'Cream', 'Yellow', 'Brown'], answer: 1 },
    { q: 'Which of the following best describes what happens to Kc when temperature is increased for an exothermic reaction?', options: ['Kc increases', 'Kc decreases', 'Kc stays the same', 'Kc becomes zero'], answer: 1 },
  ],
  red: [
    { q: 'Chlorine reacts with cold dilute NaOH: Cl\u2082 + 2NaOH \u2192 NaCl + NaClO + H\u2082O. The oxidation states of Cl change from:', options: ['0 to -1 and +1', '0 to -1 and +3', '-1 to 0 and +1', '+1 to -1 and +3'], answer: 0 },
    { q: 'A student mixes 50 cm\u00B3 of 1.0 mol dm\u207B\u00B3 HCl with 50 cm\u00B3 of 1.0 mol dm\u207B\u00B3 NaOH. The temperature rises by 6.8 \u00B0C. Given c = 4.18 J g\u207B\u00B9 K\u207B\u00B9, the enthalpy of neutralisation is approximately:', options: ['-28.4 kJ mol\u207B\u00B9', '-56.9 kJ mol\u207B\u00B9', '-114 kJ mol\u207B\u00B9', '-5.69 kJ mol\u207B\u00B9'], answer: 1 },
    { q: 'For the equilibrium PCl\u2085(g) \u21CC PCl\u2083(g) + Cl\u2082(g), which change increases both the rate of reaction and the yield of products?', options: ['Adding a catalyst', 'Increasing temperature', 'Increasing pressure', 'Decreasing temperature'], answer: 1 },
    { q: 'Concentrated sulfuric acid reacts with NaBr to produce HBr and also Br\u2082, SO\u2082, and H\u2082O. This occurs because:', options: ['NaBr is thermally unstable', 'HBr is a strong enough reducing agent to reduce H\u2082SO\u2084', 'Br\u207B is too small to reduce sulfuric acid', 'H\u2082SO\u2084 is a weak acid'], answer: 1 },
    { q: 'Concentrated H\u2082SO\u2084 with NaI produces I\u2082, H\u2082S, and S among other products. This shows that I\u207B is:', options: ['A weaker reducing agent than Br\u207B', 'A stronger reducing agent than Br\u207B and Cl\u207B', 'An oxidising agent', 'Not reactive with H\u2082SO\u2084'], answer: 1 },
    { q: 'A Born-Haber cycle for NaCl includes lattice enthalpy, which is:', options: ['The enthalpy change when gaseous ions form one mole of an ionic solid', 'The enthalpy change when a solid ionic compound dissolves in water', 'The enthalpy change when one mole of covalent bonds are broken', 'The enthalpy change for the formation of atoms from elements'], answer: 0 },
    { q: 'In the Contact process (2SO\u2082 + O\u2082 \u21CC 2SO\u2083), a compromise temperature of 450\u00B0C is used because:', options: ['The reaction is endothermic, so high temperature favours products', 'Lower temperature gives higher yield but the rate is too slow without a higher temperature', 'Higher pressure is impossible to achieve', 'V\u2082O\u2085 catalyst only works at this temperature'], answer: 1 },
    { q: 'The enthalpy change calculated from bond enthalpies often differs from the experimental value because:', options: ['Bond enthalpies are exact values', 'Mean bond enthalpies are averages and actual bond strengths vary with molecular environment', 'Hess\'s Law does not apply', 'Bond enthalpies include intermolecular forces'], answer: 1 },
    { q: 'For the reaction N\u2082O\u2084(g) \u21CC 2NO\u2082(g) \u0394H = +57 kJ mol\u207B\u00B9, a sealed flask at equilibrium is placed in warm water. Which row is correct?', options: ['Colour darkens, Kc increases', 'Colour lightens, Kc increases', 'Colour darkens, Kc decreases', 'Colour lightens, Kc decreases'], answer: 0 },
    { q: 'In a Hess\'s Law calculation, given: C(s) + O\u2082(g) \u2192 CO\u2082(g) \u0394H = -394 kJ; H\u2082(g) + \u00BDO\u2082(g) \u2192 H\u2082O(l) \u0394H = -286 kJ; 2C(s) + 3H\u2082(g) + \u00BDO\u2082(g) \u2192 C\u2082H\u2085OH(l) \u0394H = -277 kJ, the enthalpy of combustion of C\u2082H\u2085OH is:', options: ['-1367 kJ mol\u207B\u00B9', '-1269 kJ mol\u207B\u00B9', '-957 kJ mol\u207B\u00B9', '-1646 kJ mol\u207B\u00B9'], answer: 0 },
  ],
},

'M4': {
  name: 'Core Organic Chemistry',
  green: [
    { q: 'What is a functional group?', options: ['The carbon skeleton of a molecule', 'An atom or group of atoms responsible for the characteristic reactions of a compound', 'A type of isomer', 'The molecular formula of an organic compound'], answer: 1 },
    { q: 'The general formula for alkanes is:', options: ['CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnH2n+1'], answer: 1 },
    { q: 'What type of bond is present between carbon atoms in an alkene?', options: ['Single bond only', 'Double bond (C=C)', 'Triple bond', 'Ionic bond'], answer: 1 },
    { q: 'Homologous series members differ by:', options: ['One carbon atom', 'CH\u2082', 'Two carbon atoms', 'An oxygen atom'], answer: 1 },
    { q: 'What is structural isomerism?', options: ['Molecules with the same molecular formula but different structural formulae', 'Molecules with different molecular formulae', 'Molecules that are mirror images', 'Molecules with the same boiling point'], answer: 0 },
    { q: 'What is the IUPAC name for CH\u2083CH\u2082CH\u2082OH?', options: ['Methanol', 'Ethanol', 'Propan-1-ol', 'Propan-2-ol'], answer: 2 },
    { q: 'Alkanes undergo combustion. Complete combustion produces:', options: ['CO and H\u2082O', 'CO\u2082 and H\u2082O', 'C and H\u2082O', 'CO\u2082 and H\u2082'], answer: 1 },
    { q: 'The mechanism for the reaction of methane with chlorine is:', options: ['Electrophilic addition', 'Nucleophilic substitution', 'Free radical substitution', 'Elimination'], answer: 2 },
    { q: 'A primary alcohol has the OH group attached to a carbon bonded to:', options: ['No other carbon atoms', 'One other carbon atom (or no other carbons)', 'Two other carbon atoms', 'Three other carbon atoms'], answer: 1 },
    { q: 'The functional group of a haloalkane is:', options: ['-OH', '-COOH', '-C-X (where X is a halogen)', '-C=C-'], answer: 2 },
    { q: 'Which type of reaction do alkenes typically undergo?', options: ['Substitution', 'Addition', 'Elimination', 'Condensation'], answer: 1 },
    { q: 'What is the name of CH\u2083COCH\u2083?', options: ['Propanal', 'Propanone', 'Propanoic acid', 'Propan-1-ol'], answer: 1 },
    { q: 'E/Z isomerism is a type of:', options: ['Structural isomerism', 'Stereoisomerism', 'Optical isomerism', 'Chain isomerism'], answer: 1 },
    { q: 'Bromine water is decolourised by:', options: ['Alkanes', 'Alkenes', 'Both alkanes and alkenes', 'Neither'], answer: 1 },
    { q: 'In mass spectrometry, the molecular ion peak gives:', options: ['The number of atoms', 'The relative molecular mass', 'The number of isotopes', 'The boiling point'], answer: 1 },
    { q: 'Infrared spectroscopy can identify:', options: ['The mass of a molecule', 'Functional groups present in a molecule', 'The number of protons', 'The colour of a substance'], answer: 1 },
    { q: 'What is a nucleophile?', options: ['A species that accepts an electron pair', 'A species that donates an electron pair', 'A free radical', 'A catalyst'], answer: 1 },
    { q: 'What is an electrophile?', options: ['An electron pair donor', 'An electron pair acceptor', 'A free radical', 'A reducing agent'], answer: 1 },
    { q: 'The mechanism for the reaction of ethene with HBr is:', options: ['Free radical substitution', 'Electrophilic addition', 'Nucleophilic substitution', 'Elimination'], answer: 1 },
    { q: 'Fractional distillation separates crude oil fractions based on:', options: ['Density', 'Colour', 'Boiling point', 'Viscosity'], answer: 2 },
  ],
  amber: [
    { q: 'In free radical substitution, the initiation step for Cl\u2082 involves:', options: ['Heterolytic fission of Cl-Cl', 'Homolytic fission of Cl-Cl by UV light', 'Nucleophilic attack on Cl\u2082', 'Electrophilic addition to Cl\u2082'], answer: 1 },
    { q: 'When ethanol is heated with concentrated H\u2082SO\u2084 at 170\u00B0C, the product is:', options: ['Ethanoic acid', 'Ethane', 'Ethene', 'Ethoxyethane'], answer: 2 },
    { q: 'The hydrolysis of a primary haloalkane with aqueous NaOH follows which mechanism?', options: ['SN1', 'SN2', 'E1', 'Free radical'], answer: 1 },
    { q: 'Which alcohol, when oxidised with acidified K\u2082Cr\u2082O\u2087, produces a ketone?', options: ['Propan-1-ol', 'Propan-2-ol', 'Methanol', '2-methylpropan-2-ol'], answer: 1 },
    { q: 'E/Z isomerism requires:', options: ['A C=C double bond with two different groups on each carbon', 'A chiral centre', 'A ring structure', 'A triple bond'], answer: 0 },
    { q: 'A broad absorption at 2500-3300 cm\u207B\u00B9 in an IR spectrum suggests:', options: ['O-H in an alcohol', 'O-H in a carboxylic acid', 'C=O', 'N-H'], answer: 1 },
    { q: 'The reaction of propene with HBr gives mainly:', options: ['1-bromopropane', '2-bromopropane', 'Equal amounts of 1- and 2-bromopropane', '1,2-dibromopropane'], answer: 1 },
    { q: 'A tertiary haloalkane undergoes hydrolysis by which mechanism?', options: ['SN2', 'SN1', 'Free radical substitution', 'Electrophilic addition'], answer: 1 },
    { q: 'Refluxing a primary alcohol with acidified potassium dichromate produces:', options: ['A ketone', 'An aldehyde then a carboxylic acid', 'An alkene', 'No reaction'], answer: 1 },
    { q: 'To convert an aldehyde to a carboxylic acid, you would:', options: ['Reduce it with NaBH\u2084', 'Oxidise it with acidified K\u2082Cr\u2082O\u2087 under reflux', 'Heat it with concentrated H\u2082SO\u2084', 'React it with bromine water'], answer: 1 },
    { q: 'Curly arrows in organic mechanisms represent:', options: ['The movement of atoms', 'The movement of electron pairs', 'Bond rotation', 'The direction of heat flow'], answer: 1 },
    { q: 'In electrophilic addition of HBr to ethene, the electrophile is:', options: ['Br\u207B', 'H\u207A (or H\u03B4+ of HBr)', 'HBr molecule', 'Br\u2082'], answer: 1 },
    { q: 'Which reagent converts an alcohol to a haloalkane?', options: ['NaOH(aq)', 'HBr or PCl\u2083/PCl\u2085', 'K\u2082Cr\u2082O\u2087/H\u207A', 'KMnO\u2084'], answer: 1 },
    { q: 'Catalytic cracking of long-chain alkanes produces:', options: ['Only shorter alkanes', 'Shorter alkanes and alkenes', 'Only alkenes', 'Alcohols and carboxylic acids'], answer: 1 },
    { q: 'Ethanol produced by fermentation of glucose uses:', options: ['H\u2082SO\u2084 catalyst at 300\u00B0C', 'Yeast enzymes under anaerobic conditions', 'Steam at high pressure', 'UV light'], answer: 1 },
    { q: 'In the SN2 mechanism, the rate depends on:', options: ['Concentration of the haloalkane only', 'Concentration of both the haloalkane and the nucleophile', 'Temperature only', 'The solvent used'], answer: 1 },
    { q: 'Dehydration of butan-2-ol can produce:', options: ['Only but-1-ene', 'Only but-2-ene', 'A mixture of but-1-ene and but-2-ene', 'Butane'], answer: 2 },
    { q: 'Which test distinguishes an aldehyde from a ketone?', options: ['Bromine water', 'Tollens\' reagent (silver mirror test)', 'Sodium carbonate solution', 'Universal indicator'], answer: 1 },
    { q: 'The mass spectrum of a compound shows M+ at m/z = 46 and a peak at m/z = 31 (loss of 15). The compound is likely:', options: ['Ethanol (loss of CH\u2083)', 'Dimethyl ether', 'Methanal', 'Propane'], answer: 0 },
    { q: 'Bond polarity in C-X bonds decreases in the order:', options: ['C-F > C-Cl > C-Br > C-I', 'C-I > C-Br > C-Cl > C-F', 'C-Cl > C-F > C-Br > C-I', 'All C-X bonds have equal polarity'], answer: 0 },
  ],
  red: [
    { q: 'A compound C\u2083H\u2086O has two structural isomers: one is an alcohol and one is an ether. The alcohol is:', options: ['Propan-1-ol only', 'Propan-1-ol or propan-2-ol', 'Methoxyethane', 'Propanal'], answer: 1 },
    { q: 'In the SN1 mechanism of 2-bromo-2-methylpropane, the rate-determining step is:', options: ['Attack of the nucleophile on the carbon', 'Formation of the carbocation by loss of Br\u207B', 'Proton transfer', 'Formation of the C-Br bond'], answer: 1 },
    { q: 'The reaction of propene with HBr mainly forms 2-bromopropane. This is explained by:', options: ['The secondary carbocation intermediate is more stable than the primary', 'Anti-Markovnikov addition', 'The Br\u207B attacks the terminal carbon', 'Steric effects only'], answer: 0 },
    { q: 'CFCs are harmful to the ozone layer because:', options: ['They are acidic gases', 'UV radiation causes homolytic fission of C-Cl bonds, producing Cl radicals that catalytically destroy O\u2083', 'They react with water to form HCl', 'They absorb all UV radiation'], answer: 1 },
    { q: 'A primary alcohol can be oxidised to an aldehyde (not further to carboxylic acid) by using:', options: ['Reflux with K\u2082Cr\u2082O\u2087/H\u207A', 'Distillation with K\u2082Cr\u2082O\u2087/H\u207A as the aldehyde is formed', 'Tollens\' reagent', 'NaBH\u2084'], answer: 1 },
    { q: 'Rate of hydrolysis of haloalkanes follows the order C-I > C-Br > C-Cl > C-F because:', options: ['Bond polarity increases from C-F to C-I', 'Bond enthalpy decreases from C-F to C-I, so C-I is easiest to break', 'Iodine is the most electronegative halogen', 'Fluoroalkanes are the most reactive'], answer: 1 },
    { q: 'In the propagation steps of free radical substitution of methane with Cl\u2082, which pair is correct?', options: ['Cl\u2022 + CH\u2084 \u2192 CH\u2083\u2022 + HCl; then CH\u2083\u2022 + Cl\u2082 \u2192 CH\u2083Cl + Cl\u2022', 'Cl\u2082 \u2192 2Cl\u2022; then Cl\u2022 + CH\u2084 \u2192 CH\u2083Cl + H\u2022', 'CH\u2084 \u2192 CH\u2083\u2022 + H\u2022; then H\u2022 + Cl\u2082 \u2192 HCl + Cl\u2022', 'CH\u2083\u2022 + Cl\u2022 \u2192 CH\u2083Cl; then Cl\u2082 \u2192 2Cl\u2022'], answer: 0 },
    { q: 'A compound has molecular formula C\u2084H\u2088O, reacts with Na to produce H\u2082, and can be oxidised to a ketone. It is:', options: ['Butan-1-ol', 'Butan-2-ol', '2-methylpropan-1-ol', '2-methylpropan-2-ol'], answer: 1 },
    { q: 'The IR spectrum of a compound shows a strong absorption at 1710 cm\u207B\u00B9 and a broad absorption at 2500-3300 cm\u207B\u00B9. The compound contains:', options: ['An alcohol group', 'A carboxylic acid group', 'An aldehyde group', 'An amine group'], answer: 1 },
    { q: 'When comparing ethanol production by fermentation versus hydration of ethene, fermentation:', options: ['Gives a purer product', 'Is a continuous process', 'Uses renewable resources and lower temperatures but produces a dilute solution', 'Requires a catalyst of H\u2083PO\u2084'], answer: 2 },
  ],
},

'M5': {
  name: 'Physical Chemistry and Transition Elements',
  green: [
    { q: 'The rate equation expresses rate in terms of:', options: ['Temperature and pressure', 'Concentrations of reactants raised to powers', 'Enthalpy changes', 'Equilibrium constants'], answer: 1 },
    { q: 'The order of a reaction with respect to a reactant is:', options: ['Always equal to its stoichiometric coefficient', 'Determined experimentally', 'Always 1', 'The same as the overall order'], answer: 1 },
    { q: 'What is the expression for Kc?', options: ['Products divided by reactants, using concentrations at equilibrium', 'Reactants divided by products', 'Sum of all concentrations', 'Rate of forward reaction divided by rate of reverse'], answer: 0 },
    { q: 'A buffer solution resists changes in:', options: ['Volume', 'Temperature', 'pH', 'Concentration'], answer: 2 },
    { q: 'Entropy is a measure of:', options: ['Energy stored in bonds', 'The disorder or number of ways particles can be arranged', 'The rate of a reaction', 'The equilibrium position'], answer: 1 },
    { q: 'A reaction is feasible when:', options: ['\u0394G is positive', '\u0394G is negative', '\u0394H is negative', '\u0394S is positive'], answer: 1 },
    { q: 'The Gibbs free energy equation is:', options: ['\u0394G = \u0394H + T\u0394S', '\u0394G = \u0394H - T\u0394S', '\u0394G = T\u0394S - \u0394H', '\u0394G = \u0394H / T\u0394S'], answer: 1 },
    { q: 'Transition metals are defined as d-block elements that:', options: ['Have a full d sub-shell', 'Form at least one stable ion with a partially filled d sub-shell', 'Are all in Period 4', 'Only form +2 ions'], answer: 1 },
    { q: 'A common property of transition metals is:', options: ['They are all gases at room temperature', 'They form coloured compounds', 'They have low melting points', 'They only form one oxidation state'], answer: 1 },
    { q: 'What is a ligand?', options: ['A positively charged ion', 'A molecule or ion that donates a lone pair to a central metal ion', 'A free radical', 'An oxidising agent'], answer: 1 },
    { q: 'The formula for pH is:', options: ['pH = log[H\u207A]', 'pH = -log[H\u207A]', 'pH = ln[H\u207A]', 'pH = [H\u207A] \u00D7 10'], answer: 1 },
    { q: 'A strong acid is one that:', options: ['Has a high concentration', 'Fully dissociates in aqueous solution', 'Has a pH of exactly 0', 'Reacts quickly'], answer: 1 },
    { q: 'Standard electrode potential is measured against:', options: ['A copper electrode', 'A zinc electrode', 'The standard hydrogen electrode (SHE)', 'A silver electrode'], answer: 2 },
    { q: 'In an electrochemical cell, the more negative electrode is:', options: ['The cathode', 'The anode', 'The salt bridge', 'Neither'], answer: 1 },
    { q: 'Kp is the equilibrium constant expressed in terms of:', options: ['Concentrations', 'Partial pressures', 'Mole fractions', 'Volumes'], answer: 1 },
    { q: 'The coordination number of a complex ion is:', options: ['The charge on the central metal ion', 'The total number of coordinate bonds from ligands to the metal ion', 'The number of d electrons', 'The oxidation state'], answer: 1 },
    { q: 'Which of the following is NOT a characteristic property of transition metals?', options: ['Variable oxidation states', 'Catalytic activity', 'Forming coloured ions', 'Low density'], answer: 3 },
    { q: 'Ka is the:', options: ['Equilibrium constant for the dissociation of water', 'Acid dissociation constant', 'Base dissociation constant', 'Solubility product'], answer: 1 },
    { q: 'An acidic buffer is made from:', options: ['A strong acid and its salt', 'A weak acid and its conjugate base (salt)', 'A strong acid and a strong base', 'Two weak acids'], answer: 1 },
    { q: 'The units of the rate constant k depend on:', options: ['The temperature only', 'The overall order of the reaction', 'The mechanism', 'The activation energy'], answer: 1 },
  ],
  amber: [
    { q: 'For the rate equation rate = k[A][B]\u00B2, the overall order is:', options: ['1', '2', '3', '4'], answer: 2 },
    { q: 'If doubling [A] doubles the rate, and doubling [B] quadruples the rate, the rate equation is:', options: ['rate = k[A][B]', 'rate = k[A][B]\u00B2', 'rate = k[A]\u00B2[B]', 'rate = k[A]\u00B2[B]\u00B2'], answer: 1 },
    { q: 'The pH of 0.010 mol dm\u207B\u00B3 HCl is:', options: ['1.0', '2.0', '3.0', '0.01'], answer: 1 },
    { q: 'The pH of 0.10 mol dm\u207B\u00B3 NaOH (Kw = 1.0 \u00D7 10\u207B\u00B9\u2074) is:', options: ['1.0', '12.0', '13.0', '14.0'], answer: 2 },
    { q: 'For an endothermic reaction, increasing temperature makes the reaction more feasible because:', options: ['\u0394H becomes negative', 'T\u0394S term increases, making \u0394G more negative', '\u0394S decreases', 'The activation energy decreases'], answer: 1 },
    { q: 'The complex [Cu(H\u2082O)\u2086]\u00B2\u207A is:', options: ['Tetrahedral and blue', 'Octahedral and blue', 'Square planar and green', 'Linear and colourless'], answer: 1 },
    { q: 'When excess NaOH is added to [Cu(H\u2082O)\u2086]\u00B2\u207A, the observation is:', options: ['A blue solution forms', 'A pale blue precipitate forms (Cu(OH)\u2082) which does not dissolve', 'A deep blue solution forms', 'A green precipitate forms'], answer: 1 },
    { q: 'The half-life of a first-order reaction:', options: ['Depends on initial concentration', 'Is constant regardless of concentration', 'Doubles when concentration doubles', 'Is always 1 second'], answer: 1 },
    { q: '[Fe(H\u2082O)\u2086]\u00B3\u207A is yellow. When SCN\u207B is added, the solution turns blood red because:', options: ['Fe\u00B3\u207A is reduced to Fe\u00B2\u207A', 'A ligand substitution occurs forming [Fe(SCN)(H\u2082O)\u2085]\u00B2\u207A', 'A precipitation reaction occurs', 'SCN\u207B is a coloured ion'], answer: 1 },
    { q: 'The EMF of a cell is calculated by:', options: ['E\u00B0(cathode) - E\u00B0(anode)', 'E\u00B0(anode) - E\u00B0(cathode)', 'E\u00B0(cathode) + E\u00B0(anode)', 'E\u00B0(cathode) \u00D7 E\u00B0(anode)'], answer: 0 },
    { q: 'Kp for the equilibrium N\u2082O\u2084(g) \u21CC 2NO\u2082(g) has units of:', options: ['No units', 'kPa', 'kPa\u207B\u00B9', 'kPa\u00B2'], answer: 1 },
    { q: 'Adding water to a buffer solution:', options: ['Changes the pH significantly', 'Does not significantly change the pH because the ratio of acid to salt stays approximately the same', 'Makes the buffer acidic', 'Destroys the buffer'], answer: 1 },
    { q: 'The colour of transition metal complexes arises from:', options: ['Electron transitions between s and p orbitals', 'd-d electron transitions when d orbitals are split by ligands', 'Nuclear transitions', 'Emission of X-rays'], answer: 1 },
    { q: 'Cisplatin [PtCl\u2082(NH\u2083)\u2082] has which geometry?', options: ['Tetrahedral', 'Octahedral', 'Square planar', 'Linear'], answer: 2 },
    { q: 'In a pH titration of a weak acid with a strong base, the buffer region is:', options: ['At the equivalence point', 'Before the equivalence point where the weak acid and its salt coexist', 'After the equivalence point', 'At pH 7'], answer: 1 },
    { q: 'The entropy change for a reaction in which a gas is produced from a solid is:', options: ['Negative', 'Positive', 'Zero', 'Cannot be determined'], answer: 1 },
    { q: 'Vanadium can exist in oxidation states +5, +4, +3, and +2. The colours (in order) in aqueous solution are:', options: ['Yellow, blue, green, violet', 'Blue, green, yellow, violet', 'Violet, green, blue, yellow', 'Green, yellow, blue, violet'], answer: 0 },
    { q: 'A bidentate ligand:', options: ['Donates one lone pair to the metal ion', 'Donates two lone pairs from two different atoms to the metal ion', 'Has two central metal ions', 'Is always negatively charged'], answer: 1 },
    { q: 'EDTA is a hexadentate ligand. It forms very stable complexes because:', options: ['It is a strong acid', 'The chelate effect gives a large positive entropy change', 'It has a very high molecular mass', 'It contains transition metal atoms'], answer: 1 },
    { q: 'For a second-order reaction, the units of k are:', options: ['s\u207B\u00B9', 'mol dm\u207B\u00B3 s\u207B\u00B9', 'mol\u207B\u00B9 dm\u00B3 s\u207B\u00B9', 'mol\u207B\u00B2 dm\u2076 s\u207B\u00B9'], answer: 2 },
  ],
  red: [
    { q: 'A reaction has rate = k[A]\u00B2[B]. Experiment data: when [A] and [B] are both doubled, the rate increases by a factor of:', options: ['4', '8', '6', '16'], answer: 1 },
    { q: 'The standard electrode potential for Cu\u00B2\u207A/Cu is +0.34 V and for Zn\u00B2\u207A/Zn is -0.76 V. The EMF of the Daniell cell is:', options: ['0.42 V', '1.10 V', '-1.10 V', '-0.42 V'], answer: 1 },
    { q: 'A weak acid HA has Ka = 1.8 \u00D7 10\u207B\u2075. The pH of a 0.10 mol dm\u207B\u00B3 solution is approximately:', options: ['2.87', '4.74', '5.00', '1.00'], answer: 0 },
    { q: 'For the reaction A + B \u2192 C, the rate-determining step is: A + A \u2192 X (slow), then X + B \u2192 C (fast). The rate equation is:', options: ['rate = k[A][B]', 'rate = k[A]\u00B2', 'rate = k[A]\u00B2[B]', 'rate = k[B]'], answer: 1 },
    { q: 'A buffer contains 0.10 mol dm\u207B\u00B3 CH\u2083COOH and 0.20 mol dm\u207B\u00B3 CH\u2083COONa. If Ka = 1.8 \u00D7 10\u207B\u2075, the pH is approximately:', options: ['4.44', '4.74', '5.05', '5.35'], answer: 2 },
    { q: 'The ligand substitution of [Co(H\u2082O)\u2086]\u00B2\u207A with concentrated HCl forms [CoCl\u2084]\u00B2\u207B. The change in coordination number is:', options: ['6 to 4', '4 to 6', '6 to 2', '4 to 4'], answer: 0 },
    { q: 'A reaction has \u0394H = +100 kJ mol\u207B\u00B9 and \u0394S = +200 J K\u207B\u00B9 mol\u207B\u00B9. The minimum temperature for feasibility is:', options: ['200 K', '500 K', '0.5 K', '2000 K'], answer: 1 },
    { q: 'The electrode potential of a half-cell becomes more positive when:', options: ['The concentration of the metal ion in solution increases', 'The concentration of the metal ion decreases', 'The temperature decreases', 'The electrode is made larger'], answer: 0 },
    { q: 'In the reaction: Cr\u2082O\u2087\u00B2\u207B + 14H\u207A + 6e\u207B \u2192 2Cr\u00B3\u207A + 7H\u2082O, Cr changes oxidation state from:', options: ['+6 to +3', '+7 to +3', '+3 to +6', '+6 to 0'], answer: 0 },
    { q: 'When NH\u2083 is added to [Cu(H\u2082O)\u2086]\u00B2\u207A in excess, the deep blue complex formed is:', options: ['[Cu(NH\u2083)\u2084(H\u2082O)\u2082]\u00B2\u207A', '[Cu(NH\u2083)\u2086]\u00B2\u207A', '[Cu(OH)\u2082(H\u2082O)\u2084]', 'Cu(NH\u2083)\u2082'], answer: 0 },
  ],
},

'M6': {
  name: 'Organic Chemistry and Analysis',
  green: [
    { q: 'Benzene has the molecular formula:', options: ['C\u2086H\u2086', 'C\u2086H\u2081\u2082', 'C\u2086H\u2081\u2080', 'C\u2085H\u2086'], answer: 0 },
    { q: 'The bonding in benzene is best described as:', options: ['Alternating single and double bonds', 'A delocalised ring of electrons above and below the plane', 'All single bonds', 'All double bonds'], answer: 1 },
    { q: 'An aldehyde has the functional group:', options: ['-COOH', '-CHO', '-CO- (between two carbons)', '-OH'], answer: 1 },
    { q: 'A carboxylic acid contains the functional group:', options: ['-CHO', '-CO-', '-COOH', '-COO-'], answer: 2 },
    { q: 'An amine contains which functional group?', options: ['-COOH', '-NH\u2082 (or -NHR, -NR\u2082)', '-NO\u2082', '-OH'], answer: 1 },
    { q: 'A condensation polymer is formed when:', options: ['Monomers join with no other product', 'Monomers join with loss of a small molecule (e.g. H\u2082O)', 'Only alkenes polymerise', 'Only addition reactions occur'], answer: 1 },
    { q: 'NMR spectroscopy detects:', options: ['Bond vibrations', 'The mass of fragments', 'The chemical environment of \u00B9H or \u00B9\u00B3C nuclei', 'UV absorption'], answer: 2 },
    { q: 'In \u00B9H NMR, the number of peaks indicates:', options: ['The total number of hydrogen atoms', 'The number of different chemical environments of hydrogen', 'The molecular mass', 'The number of carbon atoms'], answer: 1 },
    { q: 'TMS (tetramethylsilane) is used as a reference in NMR because:', options: ['It is radioactive', 'It gives a single peak at chemical shift 0', 'It absorbs UV light', 'It is a strong acid'], answer: 1 },
    { q: 'Chromatography separates mixtures based on:', options: ['Boiling point only', 'Different affinities for the stationary and mobile phases', 'Colour only', 'Molecular mass only'], answer: 1 },
    { q: 'What type of reaction does benzene typically undergo?', options: ['Addition', 'Electrophilic substitution', 'Nucleophilic addition', 'Free radical addition'], answer: 1 },
    { q: 'A ketone has the general structure:', options: ['RCHO', 'RCOR\'', 'RCOOH', 'RCOOR\''], answer: 1 },
    { q: 'An acyl chloride has the functional group:', options: ['-COCl', '-COO-', '-COOH', '-Cl'], answer: 0 },
    { q: 'An ester is formed from:', options: ['An acid and a base', 'A carboxylic acid and an alcohol', 'Two alcohols', 'An amine and an acid'], answer: 1 },
    { q: 'Polyesters are formed from the reaction between:', options: ['Dicarboxylic acids and diols', 'Amino acids', 'Alkenes', 'Haloalkanes and amines'], answer: 0 },
    { q: 'Which reagent reduces a carbonyl group to an alcohol?', options: ['K\u2082Cr\u2082O\u2087/H\u207A', 'NaBH\u2084', 'Br\u2082/AlBr\u2083', 'HCN'], answer: 1 },
    { q: 'The splitting pattern in \u00B9H NMR follows the:', options: ['n rule', 'n+1 rule', '2n rule', '2n+1 rule'], answer: 1 },
    { q: 'An amide bond links amino acids together in:', options: ['Polyesters', 'Proteins (peptides)', 'Addition polymers', 'Nucleic acids'], answer: 1 },
    { q: 'Nylon is an example of a:', options: ['Addition polymer', 'Polyester', 'Polyamide', 'Polysaccharide'], answer: 2 },
    { q: 'Rf value in chromatography is calculated as:', options: ['Distance moved by solvent / distance moved by spot', 'Distance moved by spot / distance moved by solvent front', 'Mass of spot / mass of solvent', 'Time for spot to travel / total time'], answer: 1 },
  ],
  amber: [
    { q: 'Benzene undergoes nitration using a mixture of:', options: ['HNO\u2083 and HCl', 'Concentrated HNO\u2083 and concentrated H\u2082SO\u2084', 'Dilute HNO\u2083 and NaOH', 'HNO\u2083 and AlCl\u2083'], answer: 1 },
    { q: 'The electrophile in the nitration of benzene is:', options: ['NO\u2082', 'NO\u2083\u207B', 'NO\u2082\u207A (nitronium ion)', 'HNO\u2083'], answer: 2 },
    { q: 'Friedel-Crafts acylation of benzene uses:', options: ['An acyl chloride and an AlCl\u2083 catalyst', 'An alcohol and H\u2082SO\u2084', 'Br\u2082 and UV light', 'KMnO\u2084 and NaOH'], answer: 0 },
    { q: 'Phenol is more reactive than benzene towards electrophilic substitution because:', options: ['The OH group is electron-withdrawing', 'The lone pair on oxygen is donated into the ring, increasing electron density', 'Phenol is an acid', 'The O-H bond is weaker than C-H'], answer: 1 },
    { q: 'The reaction of an aldehyde with HCN produces:', options: ['A primary amine, formed by nucleophilic substitution at the carbonyl carbon', 'A hydroxynitrile, formed by nucleophilic addition to the carbonyl group', 'A carboxylic acid, formed by oxidation of the carbonyl with the CN\u207B ion', 'A hemiacetal, formed by addition of H to the carbonyl oxygen and CN to the carbon'], answer: 1 },
    { q: 'Brady\'s reagent (2,4-DNP) is used to test for:', options: ['Alcohols', 'Carboxylic acids', 'Aldehydes and ketones (carbonyl compounds)', 'Amines'], answer: 2 },
    { q: 'Tollens\' reagent gives a silver mirror with:', options: ['Ketones only', 'Aldehydes only', 'Both aldehydes and ketones', 'Carboxylic acids'], answer: 1 },
    { q: 'The nucleophilic addition mechanism for the reaction of a carbonyl with HCN involves:', options: ['CN\u207B attacking the \u03B4+ carbon of C=O', 'H\u207A attacking the \u03B4- oxygen', 'A free radical chain', 'Electrophilic attack on the oxygen'], answer: 0 },
    { q: 'An amino acid at its isoelectric point exists mainly as:', options: ['A cation', 'An anion', 'A zwitterion', 'A neutral molecule with no charges'], answer: 2 },
    { q: 'In \u00B9H NMR, a triplet peak indicates the hydrogen is adjacent to:', options: ['1 hydrogen on neighbouring carbons', '2 hydrogens on neighbouring carbons', '3 hydrogens on neighbouring carbons', '4 hydrogens on neighbouring carbons'], answer: 1 },
    { q: 'Hydrolysis of a nitrile (R-CN) with dilute acid produces:', options: ['An amine', 'A carboxylic acid', 'An alcohol', 'An aldehyde'], answer: 1 },
    { q: 'The reaction of an acyl chloride with an amine produces:', options: ['An ester and HCl', 'An amide and HCl', 'A carboxylic acid and NH\u2083', 'An alcohol and HCl'], answer: 1 },
    { q: 'Optical isomerism occurs when a carbon atom has:', options: ['A double bond', 'Four different groups attached (chiral centre)', 'Two identical groups', 'No hydrogen atoms'], answer: 1 },
    { q: 'A racemic mixture contains:', options: ['Only one enantiomer', 'Equal amounts of both enantiomers', 'Only the R isomer', 'A mixture of structural isomers'], answer: 1 },
    { q: 'In \u00B9\u00B3C NMR, the number of peaks indicates:', options: ['The total number of carbon atoms', 'The number of different carbon environments', 'The molecular mass', 'The number of hydrogen atoms'], answer: 1 },
    { q: 'PET (polyethylene terephthalate) is a:', options: ['Polyamide', 'Polyester', 'Addition polymer', 'Polypeptide'], answer: 1 },
    { q: 'Kevlar is a polyamide made from:', options: ['Diols and dicarboxylic acids', 'A diamine and a dicarboxylic acid (aromatic monomers)', 'Ethene monomers', 'Amino acids only'], answer: 1 },
    { q: 'Gas chromatography-mass spectrometry (GC-MS) combines:', options: ['Separation by boiling point with identification by fragmentation pattern', 'Separation by colour with UV detection', 'NMR with IR spectroscopy', 'Electrophoresis with X-ray diffraction'], answer: 0 },
    { q: 'The reaction of a carboxylic acid with an alcohol in the presence of an acid catalyst produces:', options: ['An amide and water', 'An ester and water', 'An aldehyde and water', 'A ketone and water'], answer: 1 },
    { q: 'Benzene reacts with Br\u2082 in the presence of AlBr\u2083 catalyst. The organic product is:', options: ['Cyclohexane', '1,2-dibromocyclohexane', 'Bromobenzene', 'Phenol'], answer: 2 },
  ],
  red: [
    { q: 'The Kekule model of benzene is incorrect because:', options: ['Benzene has alternating bond lengths', 'Benzene does not decolourise bromine water, and its enthalpy of hydrogenation is less exothermic than predicted for 3 C=C bonds', 'Benzene is a gas at room temperature', 'Benzene reacts by addition'], answer: 1 },
    { q: 'In the nucleophilic addition of HCN to propanone, the product has a chiral centre. The product is:', options: ['Optically active', 'A racemic mixture because the CN\u207B can attack from either side of the planar carbonyl', 'Only the R enantiomer', 'Not chiral'], answer: 1 },
    { q: 'The directing effect of an -NH\u2082 group on a benzene ring means further substitution occurs mainly at:', options: ['The meta position', 'The 2,4 (ortho and para) positions', 'Only the para position', 'All positions equally'], answer: 1 },
    { q: 'A compound C\u2084H\u2088O\u2082 shows two peaks in its \u00B9\u00B3C NMR spectrum. The compound is most likely:', options: ['Butanoic acid', 'Ethyl ethanoate', 'Methyl propanoate', '1,4-butanediol'], answer: 1 },
    { q: 'Condensation polymers can be broken down by hydrolysis. This is a problem for:', options: ['Addition polymers in landfill', 'Polyester clothing exposed to strongly acidic or basic conditions', 'PVC pipes', 'Polythene bags'], answer: 1 },
    { q: 'In \u00B9H NMR, a peak at \u03B4 9-10 ppm is characteristic of:', options: ['R-OH', 'R-CHO (aldehyde proton)', 'R-COOH', 'Aromatic H'], answer: 1 },
    { q: 'A compound gives a positive iodoform test. It could be:', options: ['Propanal', 'Pentan-3-one', 'Ethanol', 'Propan-1-ol'], answer: 2 },
    { q: 'The mechanism for electrophilic substitution of benzene involves:', options: ['A carbocation intermediate formed when the electrophile attacks the delocalised ring', 'A carbanion intermediate', 'A free radical chain', 'Nucleophilic attack on the ring'], answer: 0 },
    { q: 'Azo dyes are formed by coupling a diazonium salt with:', options: ['An alkane', 'A phenol or aromatic amine in alkaline conditions', 'Concentrated HCl', 'An aldehyde'], answer: 1 },
    { q: 'A compound has molecular formula C\u2083H\u2087NO. Its IR shows N-H and C=O absorptions. Its \u00B9H NMR shows a singlet (3H), a singlet (3H), and a broad signal (1H). The compound is:', options: ['Propanamide', 'N-methylacetamide (N-methylethanamide)', 'Propylamine', '3-aminopropanal'], answer: 1 },
  ],
},

};
