const CHEMISTRY_OCR_A_QUESTIONS = {

'M1': {
  name: 'Development of Practical Skills',
  green: [
    { q: 'What is the purpose of a risk assessment in a chemistry practical?', options: ['To systematically identify hazards and specify appropriate control measures', 'To record equipment calibration data and ensure measurement traceability', 'To predict the theoretical yield and determine an acceptable percentage error', 'To outline the step-by-step experimental procedure and equipment required'], answer: 0 },
    { q: 'Which piece of glassware is most appropriate for measuring exactly 25.0 cm³ of a solution?', options: ['Measuring cylinder', 'Pipette', 'Conical flask', 'Beaker'], answer: 1 },
    { q: 'What does the term "precision" mean in practical chemistry?', options: ['Whether the experiment is fair', 'How close a result is to the true value', 'How close repeated measurements are to each other', 'The number of decimal places used'], answer: 2 },
    { q: 'What is the resolution of a measuring instrument?', options: ['Its percentage error', 'The number of readings taken', 'Its maximum reading', 'The smallest change it can detect'], answer: 3 },
    { q: 'Which of the following is a systematic error?', options: ['A balance that always reads 0.02 g too high', 'Slight variations in titre volumes', 'Human reaction time in timing', 'Random fluctuations in temperature'], answer: 0 },
    { q: 'What colour change indicates the end point when using phenolphthalein indicator?', options: ['Yellow to red', 'Colourless to pink', 'Blue to colourless', 'Orange to yellow'], answer: 1 },
    { q: 'What is meant by the term "accuracy"?', options: ['The range of the data', 'How close repeated results are to each other', 'How close a result is to the true value', 'The number of significant figures'], answer: 2 },
    { q: 'Which hazard symbol indicates a substance is corrosive?', options: ['Flame symbol', 'Skull and crossbones (toxic)', 'Exclamation mark', 'Corroding surface symbol'], answer: 3 },
    { q: 'What is a burette used for in a titration?', options: ['Adding the titrant drop by drop', 'Heating the solution', 'Filtering the mixture', 'Measuring fixed volumes of solution'], answer: 0 },
    { q: 'What type of error can be reduced by repeating an experiment and calculating a mean?', options: ['Systematic error', 'Random error', 'Zero error', 'Parallax error'], answer: 1 },
  ],
  amber: [
    { q: 'A student measures 25.0 cm³ using a pipette with an uncertainty of ±0.06 cm³. What is the percentage uncertainty?', options: ['0.06%', '0.12%', '0.24%', '0.6%'], answer: 2, explanation: 'Percentage uncertainty = (uncertainty ÷ measurement) × 100 = (0.06 ÷ 25.0) × 100 = 0.24%. A common mistake is to quote the uncertainty value directly (0.06%) without dividing by the measurement volume.' },
    { q: 'In a titration, concordant results are those that agree within:', options: ['1.00 cm³', '0.01 cm³', '0.50 cm³', '0.10 cm³'], answer: 3 },
    { q: 'A student obtains titre values of 24.10, 24.15, 24.10, and 25.80 cm³. Which value should be excluded?', options: ['25.80', 'None should be excluded', '24.10', '24.15'], answer: 0 },
    { q: "When calculating the percentage uncertainty in a burette titre, you should use:", options: ["The titre divided by the uncertainty of two readings, × 100","The uncertainty of two readings (2 × ±0.05 cm³) divided by the titre, × 100","The uncertainty of one reading (±0.05 cm³) divided by the titre, × 100","The uncertainty of two readings divided by the burette capacity (50 cm³), × 100"], answer: 1 },
    { q: 'A burette has an uncertainty of ±0.05 cm³. The total uncertainty in a single titre (initial and final readings) is:', options: ['±0.50 cm³', '±0.05 cm³', '±0.10 cm³', '±0.15 cm³'], answer: 2 },
    { q: 'Which technique is most suitable for determining the concentration of an unknown acid?', options: ['Filtration', 'Chromatography', 'Distillation', 'Titration'], answer: 3 },
    { q: 'A student heats a crucible to constant mass. This means they heat until:', options: ['Two consecutive masses agree within 0.01 g', 'Exactly 10 minutes have passed', 'The substance has melted', 'The crucible glows red'], answer: 0 },
    { q: 'The percentage error in using a 250 cm³ volumetric flask (±0.23 cm³) is:', options: ['2.3%', '0.092%', '0.23%', '0.046%'], answer: 1, explanation: 'Percentage error = (absolute uncertainty ÷ total volume) × 100 = (0.23 ÷ 250) × 100 = 0.092%. A very common mistake is option B — quoting the uncertainty (0.23) as if it were already a percentage. Option C would be the answer if the uncertainty were ±0.115 cm³.' },
    { q: "In a calorimetry experiment, a student measures the temperature rise as 8.5 °C. The uncertainty in this temperature rise is ±0.5 °C. The percentage uncertainty is approximately:", options: ["0.59%","5.0%","5.9%","11.8%"], answer: 2, explanation: 'Percentage uncertainty = (0.5 ÷ 8.5) × 100 ≈ 5.9%. The stated ±0.5 °C is already the uncertainty in the rise, so it is not doubled. 11.8% is what you get by doubling it; 0.59% forgets to multiply by 100.' },
    { q: 'When using a water bath instead of a Bunsen burner, the main advantage is:', options: ['It reaches higher temperatures', 'It uses less energy', 'It heats faster', 'It provides more even and controlled heating'], answer: 3 },
  ],
  red: [
    { q: 'A student obtains a percentage yield of 105%. The most likely explanation is:', options: ['The product was not fully dried before weighing','The equation was balanced incorrectly','Catalysts increased the yield above 100%','The reaction produced more product than expected'], answer: 0 },
    { q: 'In an experiment with multiple measurements, the overall percentage uncertainty is found by:', options: ['Taking the largest single uncertainty','Adding all percentage uncertainties','Subtracting systematic from random errors','Multiplying all percentage uncertainties'], answer: 1 },
    { q: 'A student claims their experiment is both precise and accurate. Which statement best describes this?', options: ['Repeated results are clustered together but far from the true value','The experiment had no anomalous results','Repeated results are clustered closely around the true value','Repeated results are spread widely but centred on the true value'], answer: 2 },
    { q: 'A student finds their experimental enthalpy of combustion is significantly less exothermic than the literature value. The most likely reason for this difference is:', options: ['Using deionised water rather than distilled water, which has a slightly different specific heat capacity','Reading the burette to the nearest 0.05 cm³ rather than 0.02 cm³','Using a balance with a precision of 0.01 g rather than 0.001 g','Heat energy being lost to the surroundings and the calorimeter during the experiment'], answer: 3 },
    { q: 'To reduce the percentage uncertainty when using a balance (±0.001 g), a student should:', options: ['Weigh a larger mass of substance','Take fewer readings','Use a volumetric flask instead','Use a more sensitive balance'], answer: 0 },
  ],
},

'M2': {
  name: 'Foundations in Chemistry',
  green: [
    { q: 'What is the relative charge of a proton?', options: ['+2', '+1', '-1', '0'], answer: 1 },
    { q: 'What is the mass number of an atom?', options: ['Number of neutrons only', 'Number of protons only', 'Number of protons + neutrons', 'Number of electrons'], answer: 2 },
    { q: 'Isotopes of an element have the same number of:', options: ['Nucleons', 'Mass number', 'Neutrons', 'Protons'], answer: 3 },
    { q: 'What is the Avogadro constant?', options: ['6.02 × 10²³ mol⁻¹', '6.02 × 10²² mol⁻¹', '3.01 × 10²³ mol⁻¹', '6.02 × 10²⁴ mol⁻¹'], answer: 0 },
    { q: 'What is the formula for calculating moles from mass?', options: ['moles = mass × Mr', 'moles = mass / Mr', 'moles = Mr / mass', 'moles = mass + Mr'], answer: 1 },
    { q: 'An ionic bond is formed by:', options: ['Dipole-dipole interactions', 'Sharing electrons', 'Transfer of electrons from one atom to another', 'Delocalised electrons'], answer: 2 },
    { q: 'A covalent bond involves:', options: ['Attraction between ions', 'Metallic bonding', 'Transfer of electrons', 'Sharing of one or more pairs of electrons'], answer: 3 },
    { q: 'What is the oxidation state of oxygen in most compounds?', options: ['-2', '0', '+2', '-1'], answer: 0 },
    { q: 'In a redox reaction, reduction is defined as:', options: ['Loss of electrons', 'Gain of electrons', 'Increase in oxidation state', 'Gain of oxygen'], answer: 1 },
    { q: 'Which of the following is a strong acid?', options: ['HCN', 'CH₃COOH', 'HCl', 'H₂CO₃'], answer: 2 },
    { q: 'What shape does a molecule with two bonding pairs and two lone pairs have?', options: ['Trigonal planar', 'Linear', 'Tetrahedral', 'Bent/V-shaped'], answer: 3 },
    { q: 'What is an empirical formula?', options: ['The simplest whole number ratio of atoms', 'The formula showing all bonds', 'The structural formula', 'The actual number of atoms in a molecule'], answer: 0 },
    { q: 'What type of bonding is present in solid sodium chloride?', options: ['Metallic', 'Ionic', 'Van der Waals', 'Covalent'], answer: 1 },
    { q: 'What is the charge on a sulfate ion?', options: ['-3', '-1', '-2', '+2'], answer: 2 },
    { q: 'The first ionisation energy is the energy required to:', options: ['Break a covalent bond', 'Melt an ionic compound', 'Add an electron to a gaseous atom', 'Remove one mole of electrons from one mole of gaseous atoms'], answer: 3 },
    { q: 'What is the bond angle in a tetrahedral molecule?', options: ['109.5°', '120°', '90°', '104.5°'], answer: 0 },
    { q: 'Which sub-shell fills after 3p?', options: ['3d', '4s', '4p', '4d'], answer: 1 },
    { q: 'How many electrons can a d sub-shell hold?', options: ['2', '6', '10', '14'], answer: 2 },
    { q: 'What is the electron configuration of sodium (Z=11)?', options: ['1s² 2s² 2p⁶ 3p¹', '1s² 2s² 2p⁷', '1s² 2s³ 2p⁶', '1s² 2s² 2p⁶ 3s¹'], answer: 3 },
    { q: 'A dative covalent bond is one where:', options: ['Both electrons in the shared pair come from the same atom', 'Electrons are delocalised', 'The bond is between two metals', 'Electrons are transferred'], answer: 0 },
  ],
  amber: [
    { q: 'Chlorine has two isotopes: ³⁵Cl (75.8%) and ³⁷Cl (24.2%). What is the relative atomic mass?', options: ['35.0', '35.5', '36.0', '35.2'], answer: 1, explanation: 'Ar = (35×75.8 + 37×24.2) ÷ 100 = (2653 + 895.4) ÷ 100 = 3548.4 ÷ 100 = 35.5.' },
    { q: 'What mass of NaOH (Mr = 40.0) is needed to make 250 cm³ of a 0.10 mol dm⁻³ solution?', options: ['4.00 g', '0.50 g', '1.00 g', '2.50 g'], answer: 2, explanation: 'moles NaOH = c×V = 0.10×0.250 = 0.025 mol; mass = 0.025×40 = 1.00 g.' },
    { q: 'In the reaction 2Na + 2H₂O → 2NaOH + H₂, sodium is:', options: ['Neither oxidised nor reduced', 'Acting as a catalyst', 'Reduced', 'Oxidised'], answer: 3 },
    { q: 'What is the oxidation state of sulfur in SO₄²⁻?', options: ['+6', '-2', '+2', '+4'], answer: 0, explanation: 'In SO₄²⁻: O is −2 (×4 = −8); total charge = −2. S + (−8) = −2 → S = +6.' },
    { q: 'Which molecule has a trigonal pyramidal shape?', options: ['BF₃', 'NH₃', 'CH₄', 'CO₂'], answer: 1 },
    { q: 'The bond angle in water is approximately 104.5° rather than 109.5° because:', options: ['Hydrogen atoms are small', 'Water has double bonds', 'Lone pairs repel more than bonding pairs', 'Oxygen is very electronegative'], answer: 2 },
    { q: 'How many moles of HCl are needed to neutralise 0.05 mol of Na₂CO₃?', options: ['0.20 mol', '0.025 mol', '0.05 mol', '0.10 mol'], answer: 3, explanation: 'Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂; ratio 1:2. moles HCl = 2 × 0.05 = 0.10 mol.' },
    { q: 'What volume of 0.20 mol dm⁻³ HCl is needed to react with 25.0 cm³ of 0.10 mol dm⁻³ NaOH?', options: ['12.5 cm³', '25.0 cm³', '50.0 cm³', '10.0 cm³'], answer: 0, explanation: 'moles NaOH = 0.025 dm³ × 0.10 mol dm⁻³ = 0.0025 mol; moles HCl = 0.0025 (1:1 ratio); V = 0.0025 ÷ 0.20 = 0.0125 dm³ = 12.5 cm³.' },
    { q: 'Which of the following species acts as both an oxidising and reducing agent in disproportionation?', options: ['The catalyst', 'The reactant element', 'The product', 'The solvent'], answer: 1 },
    { q: 'The electron configuration of Fe²⁺ (Z=26) is:', options: ['1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁵ 4s¹', '1s² 2s² 2p⁶ 3s² 3p⁶ 4s²', '1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁶', '1s² 2s² 2p⁶ 3s² 3p⁶ 3d⁴ 4s²'], answer: 2 },
    { q: 'A compound has the composition 40.0% C, 6.7% H, and 53.3% O by mass. The empirical formula is:', options: ['C₂H₄O₂', 'CHO₂', 'CHO', 'CH₂O'], answer: 3, explanation: 'Divide each % by atomic mass: C: 40.0÷12=3.33; H: 6.7÷1=6.7; O: 53.3÷16=3.33. Ratio = 1:2:1, giving empirical formula CH₂O.' },
    { q: 'What is the concentration in mol dm⁻³ of a solution containing 7.30 g of HCl (Mr = 36.5) in 500 cm³?', options: ['0.40', '1.00', '0.10', '0.20'], answer: 0, explanation: 'moles HCl = 7.30÷36.5 = 0.200 mol; V = 500 cm³ = 0.500 dm³; c = 0.200÷0.500 = 0.40 mol dm⁻³.' },
    { q: 'Metallic bonding involves:', options: ['Shared pairs of electrons between two atoms', 'Attraction between cations and a sea of delocalised electrons', 'Transfer of electrons to form ions', 'Intermolecular forces between molecules'], answer: 1 },
    { q: 'Which of these has the highest boiling point?', options: ['CH₄', 'HCl', 'NaCl', 'Cl₂'], answer: 2 },
    { q: 'London dispersion forces increase with:', options: ['Decreasing molecular mass', 'Increasing electronegativity', 'Increasing polarity', 'Increasing number of electrons'], answer: 3 },
    { q: 'Hydrogen bonding occurs between molecules that contain:', options: ['H bonded to N, O, or F', 'H bonded to any halogen', 'Any polar bond', 'H bonded to C only'], answer: 0 },
    { q: 'What is the oxidation state of Mn in KMnO₄?', options: ['+6', '+7', '+4', '+5'], answer: 1, explanation: 'In KMnO₄: K is +1, O is −2 (×4 = −8). Sum = 0: (+1) + Mn + (−8) = 0 → Mn = +7.' },
    { q: '0.25 mol of a gas occupies what volume at RTP (24.0 dm³ mol⁻¹)?', options: ['24.0 dm³', '2.4 dm³', '6.0 dm³', '12.0 dm³'], answer: 2, explanation: 'V = n × molar volume = 0.25 mol × 24.0 dm³ mol⁻¹ = 6.0 dm³.' },
    { q: 'In a titration, 25.0 cm³ of 0.10 mol dm⁻³ NaOH reacted with 20.0 cm³ of H₂SO₄. The concentration of the acid is:', options: ['0.125 mol dm⁻³', '0.0500 mol dm⁻³', '0.250 mol dm⁻³', '0.0625 mol dm⁻³'], answer: 3 },
  ],
  red: [
    { q: 'Which statement explains why the second ionisation energy of sodium is much higher than the first?', options: ['The second electron is removed from a lower energy level with less shielding, so the nuclear attraction is much greater','Sodium has only one electron so the second cannot be removed','The electron-electron repulsion decreases after the first removal','The electron is removed from a full 2p sub-shell, which is closer to the nucleus and more shielded'], answer: 0 },
    { q: 'Which of the following best explains the trend in first ionisation energy across Period 3?', options: ['It increases steadily with no exceptions','It generally increases but with dips at Al and S due to sub-shell and electron pairing effects','It alternates due to changes in electron spin','It decreases steadily due to increasing atomic radius'], answer: 1 },
    { q: 'An oxide X reacts with both acids and bases. X is most likely:', options: ['MgO','Na₂O(s)','Al₂O₃','SO₃'], answer: 2 },
    { q: 'In the reaction: MnO₄⁻ + 8H⁺ + 5Fe²⁺ → Mn²⁺ + 5Fe³⁺ + 4H₂O, the oxidation state of Mn changes from:', options: ['+4 to +2','+6 to +2','+7 to +4','+7 to +2'], answer: 3 },
    { q: 'A gaseous compound has Mr = 60 and empirical formula CH₂O. Its molecular formula is:', options: ['C₂H₄O₂','C₃H₆O₃','C₄H₈O₄','CH₂O'], answer: 0 },
    { q: 'Ice has a lower density than liquid water because:', options: ['Hydrogen bonds break when ice melts','In ice, hydrogen bonds hold molecules in an open lattice with spaces','Ice molecules vibrate less than liquid water molecules','The O-H bonds are shorter in ice'], answer: 1 },
    { q: 'Which combination correctly describes diamond?', options: ['Simple molecular, low melting point, does not conduct electricity','Giant ionic, high melting point, conducts when molten','Giant covalent, high melting point, does not conduct electricity','Giant covalent, high melting point, conducts electricity'], answer: 2 },
    { q: 'The ideal gas equation is PV = nRT. What are the correct SI units for pressure and volume?', options: ['Pa and dm³','atm and cm³','kPa and dm³','Pa and m³'], answer: 3 },
    { q: 'SF₆ has no overall dipole moment because:', options: ['The octahedral shape means the polar bonds cancel out','Sulfur has no lone pairs and the molecule is linear, so the dipoles cancel','Fluorine atoms are too small to create a dipole','S-F bonds are non-polar'], answer: 0 },
    { q: 'Which of these species has the shortest bond length?', options: ['Cl₂ (single bond)','N₂ (triple bond)','F₂ (single bond)','O₂ (double bond)'], answer: 1 },
  ],
},

'M3': {
  name: 'Periodic Table and Energy',
  green: [
    { q: 'Periodicity refers to:', options: ['Radioactive decay patterns', 'The mass of elements increasing', 'Repeating trends in properties across periods', 'Elements in the same group having different properties'], answer: 2 },
    { q: 'Group 2 metals react with water to form:', options: ['A metal hydroxide and oxygen', 'An acidic solution and hydrogen gas bubbles', 'A metal oxide and water', 'An alkaline solution and hydrogen'], answer: 3 },
    { q: 'Which Group 7 element is a liquid at room temperature?', options: ['Bromine', 'Iodine', 'Fluorine', 'Chlorine'], answer: 0 },
    { q: 'Enthalpy of combustion is always:', options: ['Positive', 'Negative', 'Zero', 'It varies'], answer: 1 },
    { q: 'An exothermic reaction has:', options: ['An enthalpy change that depends on temperature', 'A positive enthalpy change', 'A negative enthalpy change', 'No enthalpy change'], answer: 2 },
    { q: 'A catalyst works by:', options: ['Increasing the concentration of reactants', 'Raising the temperature of the reaction', 'Increasing the enthalpy change', 'Providing an alternative reaction pathway with lower activation energy'], answer: 3 },
    { q: 'What is the unit of rate of reaction?', options: ['mol dm⁻³ s⁻¹', 'J mol⁻¹', 'mol', 'mol dm⁻³'], answer: 0 },
    { q: 'At equilibrium:', options: ['The concentrations of reactants and products are exactly equal', 'The rates of forward and reverse reactions are equal', 'Only the reverse reaction occurs', 'The forward reaction has stopped'], answer: 1 },
    { q: 'Le Chatelier\'s principle states that a system at equilibrium will:', options: ['Remain unchanged', 'Always shift to the right', 'Oppose any change imposed on it', 'Increase the yield of products at all times'], answer: 2 },
    { q: 'Down Group 2, the first ionisation energy:', options: ['Stays the same', 'Alternates', 'Increases', 'Decreases'], answer: 3 },
    { q: 'Which Group 2 carbonate is most thermally stable?', options: ['BaCO₃', 'MgCO₃', 'CaCO₃', 'SrCO₃'], answer: 0 },
    { q: 'The colour of chlorine gas is:', options: ['Brown', 'Yellow-green', 'Purple', 'Colourless'], answer: 1 },
    { q: 'A bond enthalpy is defined as the energy required to:', options: ['Form a compound from its elements', 'Form one mole of bonds in the gas phase', 'Break one mole of a specific covalent bond in the gas phase', 'Break an ionic lattice'], answer: 2 },
    { q: 'Increasing temperature increases rate of reaction because:', options: ['The activation energy decreases', 'Molecules get larger', 'Pressure increases', 'More particles have energy greater than the activation energy'], answer: 3 },
    { q: 'The Boltzmann distribution shows:', options: ['The distribution of molecular energies at a given temperature', 'How catalysts change enthalpy', 'The structure of the periodic table', 'The arrangement of electrons in atoms'], answer: 0 },
    { q: 'Hess\'s Law states that the enthalpy change for a reaction is:', options: ['Always negative', 'Independent of the route taken', 'Equal to the sum of bond enthalpies', 'Dependent on the catalyst used'], answer: 1 },
    { q: 'What happens to the position of equilibrium if pressure is increased in a gaseous reaction?', options: ['The equilibrium constant changes', 'Shifts to the side with more moles of gas present', 'Shifts to the side with fewer moles of gas', 'No effect'], answer: 2 },
    { q: 'Down Group 7, the boiling points of the elements:', options: ['Stay the same', 'Alternate', 'Decrease', 'Increase'], answer: 3 },
    { q: 'Which halide ion is the strongest reducing agent?', options: ['I⁻', 'F⁻', 'Cl⁻', 'Br⁻'], answer: 0 },
    { q: 'The standard enthalpy of formation is measured under conditions of:', options: ['273 K and 1 atm', '298 K and 100 kPa', '298 K and 1 atm', '373 K and 100 kPa'], answer: 1 },
  ],
  amber: [
    { q: "Using bond enthalpies: C-H = 412, O=O = 496, C=O = 743, O-H = 463 kJ mol⁻¹, estimate ΔH for CH₄ + 2O₂ → CO₂ + 2H₂O.", options: ["-648 kJ mol⁻¹","+698 kJ mol⁻¹","-698 kJ mol⁻¹","-890 kJ mol⁻¹"], answer: 2 },
    { q: 'If the equilibrium N₂ + 3H₂ ⇌ 2NH₃ is exothermic, increasing temperature will:', options: ['Have no effect', 'Stop the reaction', 'Increase yield of NH₃', 'Decrease yield of NH₃'], answer: 3 },
    { q: 'Chlorine reacts with NaOH(aq) to form NaCl, NaClO, and water. This is an example of:', options: ['Disproportionation', 'Displacement', 'Decomposition', 'Neutralisation'], answer: 0 },
    { q: 'Which Group 2 hydroxide is the least soluble?', options: ['Ba(OH)₂', 'Mg(OH)₂', 'Ca(OH)₂', 'Sr(OH)₂'], answer: 1 },
    { q: 'Adding a catalyst to a system at equilibrium:', options: ['Shifts equilibrium to the left', 'Increases the equilibrium constant', 'Does not change the position of equilibrium', 'Shifts equilibrium to the right'], answer: 2 },
    { q: 'Using Hess\'s Law and the enthalpies of formation: ΔHf[CO₂] = -394, ΔHf[H₂O] = -286, ΔHf[CH₄] = -75 kJ mol⁻¹, calculate ΔH for CH₄ + 2O₂ → CO₂ + 2H₂O.', options: ['-755 kJ mol⁻¹', '+891 kJ mol⁻¹', '-605 kJ mol⁻¹', '-891 kJ mol⁻¹'], answer: 3 },
    { q: 'Chlorine displaces bromine from KBr solution because:', options: ['Chlorine is a stronger oxidising agent than bromine', 'Bromine is a gas', 'Potassium reacts with chlorine', 'Chlorine is less reactive than bromine'], answer: 0 },
    { q: 'The thermal decomposition temperature of Group 2 carbonates increases down the group because:', options: ['The mass of the carbonate increases', 'The cation size increases, so the carbonate ion is less polarised and harder to decompose', 'Larger cations have higher charge density', 'The bonding becomes more covalent'], answer: 1 },
    { q: 'An increase in concentration of reactants increases rate because:', options: ['The enthalpy change becomes more negative', 'Activation energy decreases', 'There are more frequent collisions between reactant particles', 'The temperature increases'], answer: 2 },
    { q: 'In the equilibrium 2SO₂(g) + O₂(g) ⇌ 2SO₃(g), the total moles of gas on the left is:', options: ['4', '1', '2', '3'], answer: 3 },
    { q: 'Silver nitrate solution is used to test for halide ions. AgCl precipitate is:', options: ['White', 'Cream', 'No precipitate forms', 'Yellow'], answer: 0 },
    { q: 'Barium chloride is used to test for:', options: ['Halide ions', 'Sulfate ions', 'Carbonate ions', 'Ammonium ions'], answer: 1 },
    { q: 'Down Group 2, reactivity with water:', options: ['Only Mg reacts', 'Decreases', 'Increases', 'Stays the same'], answer: 2 },
    { q: 'The enthalpy profile for an endothermic reaction shows:', options: ['Products at the same level as reactants', 'No activation energy hump', 'Products lower than reactants', 'Products higher than reactants'], answer: 3 },
    { q: 'On a Boltzmann distribution, increasing temperature:', options: ['Shifts the peak to the right and lowers it', 'Raises the peak but does not shift it', 'Narrows the distribution', 'Shifts the peak to the left and makes it taller'], answer: 0 },
    { q: 'The equilibrium constant Kc for A ⇌ B is 0.01. This means:', options: ['The reaction goes almost to completion', 'The equilibrium lies to the left (favouring reactants)', 'The equilibrium lies to the right (favouring products)', 'The reaction is at equilibrium only at high temperature'], answer: 1 },
    { q: 'Mg burns in air to form:', options: ['MgCO₃', 'MgO only', 'MgO and Mg₃N₂', 'Mg(OH)₂'], answer: 2 },
    { q: 'The test for chloride ions using AgNO₃ and then NH₃(aq) shows that AgCl:', options: ['Dissolves only in concentrated NH₃(aq)', 'Does not form a precipitate', 'Is insoluble in both dilute and concentrated NH₃', 'Dissolves in dilute NH₃(aq)'], answer: 3 },
    { q: 'AgBr precipitate is what colour?', options: ['Cream', 'Yellow', 'Brown', 'White'], answer: 0 },
    { q: 'Which of the following best describes what happens to Kc when temperature is increased for an exothermic reaction?', options: ['Kc increases', 'Kc decreases', 'Kc stays the same', 'Kc becomes zero'], answer: 1 },
  ],
  red: [
    { q: 'Chlorine reacts with cold dilute NaOH: Cl₂ + 2NaOH → NaCl + NaClO + H₂O. The oxidation states of Cl change from:', options: ['-1 to 0 and +1','+1 to -1 and +3','0 to -1 and +1','0 to -1 and +3'], answer: 2 },
    { q: 'A student mixes 50 cm³ of 1.0 mol dm⁻³ HCl with 50 cm³ of 1.0 mol dm⁻³ NaOH. The temperature rises by 6.8 °C. Given c = 4.18 J g⁻¹ K⁻¹, the enthalpy of neutralisation is approximately:', options: ['-114 kJ mol⁻¹','-28.4 kJ mol⁻¹','-5.69 kJ mol⁻¹','-56.8 kJ mol⁻¹'], answer: 3 },
    { q: 'For the equilibrium PCl₅(g) ⇌ PCl₃(g) + Cl₂(g), which change increases both the rate of reaction and the yield of products?', options: ['Increasing temperature','Decreasing temperature','Adding a catalyst','Increasing pressure'], answer: 0 },
    { q: 'Concentrated sulfuric acid reacts with NaBr to produce HBr and also Br₂, SO₂, and H₂O. This occurs because:', options: ['Br⁻ is too small to reduce sulfuric acid','HBr is a strong enough reducing agent to reduce H₂SO₄','NaBr is thermally unstable','H₂SO₄ is a weak acid'], answer: 1 },
    { q: 'Concentrated H₂SO₄ with NaI produces I₂, H₂S, and S among other products. This shows that I⁻ is:', options: ['A weaker reducing agent than Br⁻, so it reduces H₂SO₄ less','An oxidising agent','A stronger reducing agent than Br⁻ and Cl⁻','Not reactive with H₂SO₄'], answer: 2 },
    { q: 'A Born-Haber cycle for NaCl includes lattice enthalpy, which is:', options: ['The enthalpy change when one mole of a solid ionic compound dissolves in water','The enthalpy change when one mole of covalent bonds are broken','The enthalpy change for the formation of atoms from elements','The enthalpy change when gaseous ions form one mole of an ionic solid'], answer: 3 },
    { q: 'In the Contact process (2SO₂ + O₂ ⇌ 2SO₃), a compromise temperature of 450°C is used because:', options: ['Lower temperature gives higher yield but the rate is too slow without a higher temperature','V₂O₅ catalyst only works at this temperature','The reaction is endothermic, so high temperature favours products','Higher pressure is impossible to achieve'], answer: 0 },
    { q: 'The enthalpy change calculated from bond enthalpies often differs from the experimental value because:', options: ['Bond enthalpies are exact values','Mean bond enthalpies are averages over many compounds, and actual bond strengths vary with the molecular environment','Hess\'s Law does not apply','Bond enthalpies include intermolecular forces'], answer: 1 },
    { q: 'For the reaction N₂O₄(g) ⇌ 2NO₂(g) ΔH = +57 kJ mol⁻¹, a sealed flask at equilibrium is placed in warm water. Which row is correct?', options: ['Colour darkens, Kc decreases','Colour lightens, Kc decreases','Colour darkens, Kc increases','Colour lightens, Kc increases'], answer: 2 },
    { q: 'In a Hess\'s Law calculation, given: C(s) + O₂(g) → CO₂(g) ΔH = -394 kJ; H₂(g) + ½O₂(g) → H₂O(l) ΔH = -286 kJ; 2C(s) + 3H₂(g) + ½O₂(g) → C₂H₅OH(l) ΔH = -277 kJ, the enthalpy of combustion of C₂H₅OH is:', options: ['-957 kJ mol⁻¹','-1269 kJ mol⁻¹','-1646 kJ mol⁻¹','-1369 kJ mol⁻¹'], answer: 3 },
  ],
},

'M4': {
  name: 'Core Organic Chemistry',
  green: [
    { q: 'What is a functional group?', options: ['An atom or group of atoms responsible for the characteristic reactions of a compound', 'A type of isomer', 'The molecular formula of an organic compound', 'The carbon skeleton of a molecule'], answer: 0 },
    { q: 'The general formula for alkanes is:', options: ['CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnH2n+1'], answer: 1 },
    { q: 'What type of bond is present between carbon atoms in an alkene?', options: ['Ionic bond', 'Single bond only (C-C)', 'Double bond (C=C)', 'Triple bond'], answer: 2 },
    { q: 'Homologous series members differ by:', options: ['Two carbon atoms', 'An oxygen atom', 'One carbon atom', 'CH₂'], answer: 3 },
    { q: 'What is structural isomerism?', options: ['Molecules with the same molecular formula but different structural formulae', 'Molecules with different molecular formulae', 'Molecules that are mirror images', 'Molecules with the same boiling point'], answer: 0 },
    { q: 'What is the IUPAC name for CH₃CH₂CH₂OH?', options: ['Ethanol', 'Propan-1-ol', 'Propan-2-ol', 'Methanol'], answer: 1 },
    { q: 'Alkanes undergo combustion. Complete combustion produces:', options: ['CO₂ and H₂', 'CO and H₂O only', 'CO₂ and H₂O', 'C and H₂O'], answer: 2 },
    { q: 'The mechanism for the reaction of methane with chlorine is:', options: ['Elimination', 'Electrophilic addition', 'Nucleophilic substitution', 'Free radical substitution'], answer: 3 },
    { q: 'A primary alcohol has the OH group attached to a carbon bonded to:', options: ['One other carbon atom (or no other carbons)', 'Two other carbon atoms', 'Three other carbon atoms', 'No other carbon atoms'], answer: 0 },
    { q: 'The functional group of a haloalkane is:', options: ['-COOH', '-C-X (where X is a halogen)', '-C=C-', '-OH'], answer: 1 },
    { q: 'Which type of reaction do alkenes typically undergo?', options: ['Condensation', 'Substitution', 'Addition', 'Elimination'], answer: 2 },
    { q: 'What is the name of CH₃COCH₃?', options: ['Propanoic acid', 'Propan-1-ol', 'Propanal', 'Propanone'], answer: 3 },
    { q: 'E/Z isomerism is a type of:', options: ['Stereoisomerism', 'Optical isomerism', 'Chain isomerism', 'Structural isomerism'], answer: 0 },
    { q: 'Bromine water is decolourised by:', options: ['Alkanes', 'Alkenes', 'Both alkanes and alkenes', 'Neither'], answer: 1 },
    { q: 'In mass spectrometry, the molecular ion peak gives:', options: ['The boiling point', 'The number of atoms', 'The relative molecular mass', 'The number of isotopes'], answer: 2 },
    { q: 'Infrared spectroscopy can identify:', options: ['The number of protons', 'The colour of a substance', 'The mass of a molecule', 'Functional groups present in a molecule'], answer: 3 },
    { q: 'What is a nucleophile?', options: ['A species that donates an electron pair', 'A free radical', 'A catalyst', 'A species that accepts an electron pair'], answer: 0 },
    { q: 'What is an electrophile?', options: ['An electron pair donor (Lewis base)', 'An electron pair acceptor', 'A free radical', 'A reducing agent'], answer: 1 },
    { q: 'The mechanism for the reaction of ethene with HBr is:', options: ['Elimination', 'Free radical substitution', 'Electrophilic addition', 'Nucleophilic substitution'], answer: 2 },
    { q: 'Fractional distillation separates crude oil fractions based on:', options: ['Viscosity', 'Density of the fraction', 'Colour', 'Boiling point'], answer: 3 },
  ],
  amber: [
    { q: 'In free radical substitution, the initiation step for Cl₂ involves:', options: ['Homolytic fission of Cl-Cl by UV light', 'Nucleophilic attack on Cl₂', 'Electrophilic addition to Cl₂', 'Heterolytic fission of Cl-Cl by heating strongly'], answer: 0 },
    { q: 'When ethanol is heated with concentrated H₂SO₄ at 170°C, the product is:', options: ['Ethane', 'Ethene', 'Ethoxyethane', 'Ethanoic acid'], answer: 1 },
    { q: 'The hydrolysis of a primary haloalkane with aqueous NaOH follows which mechanism?', options: ['Free radical', 'SN1', 'SN2', 'E1'], answer: 2 },
    { q: 'Which alcohol, when oxidised with acidified K₂Cr₂O₇, produces a ketone?', options: ['Methanol', '2-methylpropan-2-ol', 'Propan-1-ol', 'Propan-2-ol'], answer: 3 },
    { q: 'E/Z isomerism requires:', options: ['A C=C double bond with two different groups on each carbon', 'A chiral centre', 'A ring structure', 'A triple bond'], answer: 0 },
    { q: 'A broad absorption at 2500-3300 cm⁻¹ in an IR spectrum suggests:', options: ['O-H in an alcohol (H-bonded)', 'O-H in a carboxylic acid', 'C=O', 'N-H'], answer: 1 },
    { q: 'The reaction of propene with HBr gives mainly:', options: ['1,2-dibromopropane', '1-bromopropane', '2-bromopropane', 'Equal amounts of 1- and 2-bromopropane'], answer: 2 },
    { q: 'A tertiary haloalkane undergoes hydrolysis by which mechanism?', options: ['Free radical substitution', 'Electrophilic addition', 'SN2', 'SN1'], answer: 3 },
    { q: 'Refluxing a primary alcohol with acidified potassium dichromate produces:', options: ['An aldehyde then a carboxylic acid', 'An alkene', 'No reaction', 'A ketone'], answer: 0 },
    { q: 'To convert an aldehyde to a carboxylic acid, you would:', options: ['Reduce it with NaBH₄', 'Oxidise it with acidified K₂Cr₂O₇ under reflux', 'Heat it with concentrated H₂SO₄', 'React it with bromine water'], answer: 1 },
    { q: 'Curly arrows in organic mechanisms represent:', options: ['The direction of heat flow in the reaction', 'The movement of atoms', 'The movement of electron pairs', 'Bond rotation'], answer: 2 },
    { q: 'In electrophilic addition of HBr to ethene, the electrophile is:', options: ['HBr molecule (as a whole)', 'Br₂', 'Br⁻', 'H⁺ (or Hδ+ of HBr)'], answer: 3 },
    { q: 'Which reagent converts an alcohol to a haloalkane?', options: ['HBr or PCl₃/PCl₅', 'K₂Cr₂O₇/H⁺ (under reflux)', 'KMnO₄', 'NaOH(aq)'], answer: 0 },
    { q: 'Catalytic cracking of long-chain alkanes produces:', options: ['Only shorter alkanes', 'Shorter alkanes and alkenes', 'Only alkenes', 'Alcohols and carboxylic acids'], answer: 1 },
    { q: 'Ethanol produced by fermentation of glucose uses:', options: ['UV light', 'H₂SO₄ catalyst at 300°C', 'Yeast enzymes under anaerobic conditions', 'Steam at high pressure'], answer: 2 },
    { q: 'In the SN2 mechanism, the rate depends on:', options: ['Temperature only', 'The solvent used', 'Concentration of the haloalkane only', 'Concentration of both the haloalkane and the nucleophile'], answer: 3 },
    { q: 'Dehydration of butan-2-ol can produce:', options: ['A mixture of but-1-ene and but-2-ene', 'Butane', 'Only but-1-ene', 'Only but-2-ene'], answer: 0 },
    { q: 'Which test distinguishes an aldehyde from a ketone?', options: ['Bromine water', 'Tollens\' reagent (silver mirror test)', 'Sodium carbonate solution (fizzing with aldehydes)', 'Universal indicator'], answer: 1 },
    { q: 'The mass spectrum of a compound shows M+ at m/z = 46 and a peak at m/z = 31 (loss of 15). Its IR spectrum shows a broad absorption at 3200–3600 cm⁻¹. The compound is likely:', options: ['Methanal', 'Propane', 'Ethanol (loss of CH₃)', 'Dimethyl ether (CH₃OCH₃)'], answer: 2 },
    { q: 'Bond polarity in C-X bonds decreases in the order:', options: ['C-I > C-Br > C-Cl > C-F', 'C-Cl > C-F > C-Br > C-I', 'All C-X bonds have equal polarity', 'C-F > C-Cl > C-Br > C-I'], answer: 3 },
  ],
  red: [
    { q: 'A compound C₃H₈O has structural isomers that are alcohols and one that is an ether. The alcohol is:', options: ['Propan-1-ol or propan-2-ol','Propanal','Methoxyethane','Propan-1-ol only (not propan-2-ol)'], answer: 0 },
    { q: 'In the SN1 mechanism of 2-bromo-2-methylpropane, the rate-determining step is:', options: ['Formation of the C-Br bond','Formation of the carbocation by loss of Br⁻','Proton transfer','Attack of the nucleophile on the carbon bonded to the bromine'], answer: 1 },
    { q: 'The reaction of propene with HBr mainly forms 2-bromopropane. This is explained by:', options: ['Steric effects only','Anti-Markovnikov addition','The secondary carbocation intermediate is more stable than the primary','The Br⁻ attacks the terminal carbon'], answer: 2 },
    { q: 'CFCs are harmful to the ozone layer because:', options: ['They absorb all UV radiation','They react with water in the stratosphere to form HCl, which breaks down O₃','They are acidic gases','UV radiation causes homolytic fission of C-Cl bonds'], answer: 3 },
    { q: 'A primary alcohol can be oxidised to an aldehyde (not further to carboxylic acid) by using:', options: ['Distillation with K₂Cr₂O₇/H⁺ as the aldehyde is formed','Tollens\' reagent','NaBH₄','Reflux with K₂Cr₂O₇/H⁺'], answer: 0 },
    { q: 'Rate of hydrolysis of haloalkanes follows the order C-I > C-Br > C-Cl > C-F because:', options: ['Fluoroalkanes are the most reactive','Bond enthalpy decreases from C-F to C-I, so C-I is easiest to break','Bond polarity increases from C-F to C-I','Iodine is the most electronegative halogen, so the C-I bond is the most polar of all'], answer: 1 },
    { q: 'In the propagation steps of free radical substitution of methane with Cl₂, which pair is correct?', options: ['CH₄ → CH₃• + H•; then H• + Cl₂ → HCl + Cl• and CH₃• + Cl• → CH₃Cl','CH₃• + Cl• → CH₃Cl; then Cl₂ → 2Cl•','Cl• + CH₄ → CH₃• + HCl; then CH₃• + Cl₂ → CH₃Cl + Cl•','Cl₂ → 2Cl•; then Cl• + CH₄ → CH₃Cl + H•'], answer: 2 },
    { q: "A compound has molecular formula C₄H₁₀O, reacts with Na to produce H₂, and can be oxidised to a ketone. It is:", options: ["Butan-1-ol","2-methylpropan-1-ol","2-methylpropan-2-ol","Butan-2-ol"], answer: 3 },
    { q: 'The IR spectrum of a compound shows a strong absorption at 1710 cm⁻¹ and a broad absorption at 2500-3300 cm⁻¹. The compound contains:', options: ['A carboxylic acid group','An aldehyde group (CHO) and an ester','An amine group','An alcohol group'], answer: 0 },
    { q: 'When comparing ethanol production by fermentation versus hydration of ethene, fermentation:', options: ['Gives a purer product','Uses renewable resources and lower temperatures but produces impure ethanol slowly in a batch process','Requires a catalyst of H₃PO₄','Is a continuous process'], answer: 1 },
  ],
},

'M5': {
  name: 'Physical Chemistry and Transition Elements',
  green: [
    { q: 'The rate equation expresses rate in terms of:', options: ['Equilibrium constants', 'Temperature and pressure', 'Concentrations of reactants raised to powers', 'Enthalpy changes'], answer: 2 },
    { q: 'The order of a reaction with respect to a reactant is:', options: ['Always 1', 'The same as the overall order', 'Always equal to its stoichiometric coefficient', 'Determined experimentally'], answer: 3 },
    { q: 'What is the expression for Kc?', options: ['Products divided by reactants, using concentrations at equilibrium', 'Reactants divided by products', 'Sum of all concentrations', 'The rate of the forward reaction divided by the rate of the reverse reaction'], answer: 0 },
    { q: 'A buffer solution resists changes in:', options: ['Temperature', 'pH', 'Concentration', 'Volume'], answer: 1 },
    { q: 'Entropy is a measure of:', options: ['The equilibrium position', 'Energy stored in bonds', 'The disorder or number of ways particles can be arranged', 'The rate of a reaction'], answer: 2 },
    { q: 'A reaction is feasible when:', options: ['ΔH is negative', 'ΔS is positive', 'ΔG is positive', 'ΔG is negative'], answer: 3 },
    { q: 'The Gibbs free energy equation is:', options: ['ΔG = ΔH - TΔS', 'ΔG = TΔS - ΔH', 'ΔG = ΔH / TΔS', 'ΔG = ΔH + TΔS'], answer: 0 },
    { q: 'Transition metals are defined as d-block elements that:', options: ['Have a full d sub-shell', 'Form at least one stable ion with a partially filled d sub-shell', 'Are all in Period 4', 'Only form +2 ions'], answer: 1 },
    { q: 'A common property of transition metals is:', options: ['They only form one oxidation state', 'They are all gases at room temperature', 'They form coloured compounds', 'They have low melting points'], answer: 2 },
    { q: 'What is a ligand?', options: ['A free radical', 'An oxidising agent', 'A positively charged ion', 'A molecule or ion that donates a lone pair to a central metal ion'], answer: 3 },
    { q: 'The formula for pH is:', options: ['pH = -log[H⁺]', 'pH = ln[H⁺]', 'pH = [H⁺] × 10', 'pH = log[H⁺]'], answer: 0 },
    { q: 'A strong acid is one that:', options: ['Has a high concentration of acid molecules', 'Fully dissociates in aqueous solution', 'Has a pH of exactly 0', 'Reacts quickly'], answer: 1 },
    { q: 'Standard electrode potential is measured against:', options: ['A copper electrode', 'A zinc electrode', 'The standard hydrogen electrode (SHE)', 'A silver electrode'], answer: 2 },
    { q: 'In an electrochemical cell, the more negative electrode is:', options: ['The salt bridge', 'Neither', 'The cathode', 'The anode'], answer: 3 },
    { q: 'Kp is the equilibrium constant expressed in terms of:', options: ['Partial pressures', 'Mole fractions', 'Volumes', 'Concentrations in mol dm⁻³'], answer: 0 },
    { q: 'The coordination number of a complex ion is:', options: ['The charge on the central metal ion', 'The total number of coordinate bonds from ligands to the metal ion', 'The number of d electrons', 'The oxidation state'], answer: 1 },
    { q: 'Which of the following is NOT a characteristic property of transition metals?', options: ['Catalytic activity', 'Forming coloured ions', 'Low density', 'Variable oxidation states'], answer: 2 },
    { q: 'Ka is the:', options: ['Base dissociation constant', 'Solubility product', 'Equilibrium constant for the dissociation of water', 'Acid dissociation constant'], answer: 3 },
    { q: 'An acidic buffer is made from:', options: ['A weak acid and its conjugate base (salt)', 'A strong acid and a strong base', 'Two weak acids', 'A strong acid and its salt, in equal amounts'], answer: 0 },
    { q: 'The units of the rate constant k depend on:', options: ['The temperature only, as k increases with T', 'The overall order of the reaction', 'The mechanism', 'The activation energy'], answer: 1 },
  ],
  amber: [
    { q: 'For the rate equation rate = k[A][B]², the overall order is:', options: ['1', '2', '3', '4'], answer: 2 },
    { q: 'If doubling [A] doubles the rate, and doubling [B] quadruples the rate, the rate equation is:', options: ['rate = k[A]²[B]', 'rate = k[A]²[B]²', 'rate = k[A][B]', 'rate = k[A][B]²'], answer: 3 },
    { q: 'The pH of 0.010 mol dm⁻³ HCl is:', options: ['2.0', '3.0', '0.01', '1.0'], answer: 0 },
    { q: 'The pH of 0.10 mol dm⁻³ NaOH (Kw = 1.0 × 10⁻¹⁴) is:', options: ['12.0', '13.0', '14.0', '1.0'], answer: 1 },
    { q: 'For an endothermic reaction, increasing temperature makes the reaction more feasible because:', options: ['The activation energy decreases, so the reaction goes faster', 'ΔH becomes negative', 'TΔS term increases, making ΔG more negative', 'ΔS decreases'], answer: 2 },
    { q: 'The complex [Cu(H₂O)₆]²⁺ is:', options: ['Square planar and green', 'Linear and colourless', 'Tetrahedral and blue', 'Octahedral and blue'], answer: 3 },
    { q: 'When excess NaOH is added to [Cu(H₂O)₆]²⁺, the observation is:', options: ['A pale blue precipitate forms (Cu(OH)₂) which does not dissolve', 'A deep blue solution forms', 'A green precipitate forms', 'A blue solution forms'], answer: 0 },
    { q: 'The half-life of a first-order reaction:', options: ['Depends on the initial concentration of the reactant', 'Is constant regardless of concentration', 'Doubles when concentration doubles', 'Is always 1 second'], answer: 1 },
    { q: '[Fe(H₂O)₆]³⁺ is yellow. When SCN⁻ is added, the solution turns blood red because:', options: ['SCN⁻ is a coloured ion', 'Fe³⁺ is reduced to Fe²⁺', 'A ligand substitution occurs forming [Fe(SCN)(H₂O)₅]²⁺', 'A precipitation reaction occurs'], answer: 2 },
    { q: 'The EMF of a cell is calculated by:', options: ['E°(anode) - E°(cathode)', 'E°(cathode) + E°(anode)', 'E°(cathode) × E°(anode)', 'E°(cathode) - E°(anode)'], answer: 3 },
    { q: 'Kp for the equilibrium N₂O₄(g) ⇌ 2NO₂(g) has units of:', options: ['kPa', 'kPa⁻¹', 'kPa²', 'No units'], answer: 0 },
    { q: 'Adding water to a buffer solution:', options: ['Changes the pH significantly', 'Does not significantly change the pH because the ratio of acid to salt stays approximately the same', 'Makes the buffer acidic', 'Destroys the buffer'], answer: 1 },
    { q: 'The colour of transition metal complexes arises from:', options: ['Emission of X-rays', 'Electron transitions between s and p orbitals of the metal, emitting visible light', 'd-d electron transitions when d orbitals are split by ligands', 'Nuclear transitions'], answer: 2 },
    { q: 'Cisplatin [PtCl₂(NH₃)₂] has which geometry?', options: ['Linear', 'Tetrahedral (sp³)', 'Octahedral', 'Square planar'], answer: 3 },
    { q: 'In a pH titration of a weak acid with a strong base, the buffer region is:', options: ['Before the equivalence point where the weak acid and its salt coexist', 'After the equivalence point', 'At pH 7', 'At the equivalence point'], answer: 0 },
    { q: 'The entropy change for a reaction in which a gas is produced from a solid is:', options: ['Negative', 'Positive', 'Zero', 'Cannot be determined'], answer: 1 },
    { q: 'Vanadium can exist in oxidation states +5, +4, +3, and +2. The colours (in order) in aqueous solution are:', options: ['Violet, green, blue, yellow', 'Green, yellow, blue, violet', 'Yellow, blue, green, violet', 'Blue, green, yellow, violet'], answer: 2 },
    { q: 'A bidentate ligand:', options: ['Has two central metal ions', 'Is always negatively charged', 'Donates one lone pair to the metal ion', 'Donates two lone pairs from two different atoms to the metal ion'], answer: 3 },
    { q: 'EDTA is a hexadentate ligand. It forms very stable complexes because:', options: ['The chelate effect gives a large positive entropy change', 'It has a very high molecular mass', 'It contains transition metal atoms', 'It is a strong acid'], answer: 0 },
    { q: 'For a second-order reaction, the units of k are:', options: ['mol dm⁻³ s⁻¹', 'mol⁻¹ dm³ s⁻¹', 'mol⁻² dm⁶ s⁻¹', 's⁻¹'], answer: 1 },
  ],
  red: [
    { q: 'A reaction has rate = k[A]²[B]. Experiment data: when [A] and [B] are both doubled, the rate increases by a factor of:', options: ['16','4','8','6'], answer: 2 },
    { q: 'The standard electrode potential for Cu²⁺/Cu is +0.34 V and for Zn²⁺/Zn is -0.76 V. The EMF of the Daniell cell is:', options: ['0.42 V','-0.42 V','-1.10 V','1.10 V'], answer: 3 },
    { q: 'A weak acid HA has Ka = 1.8 × 10⁻⁵. The pH of a 0.10 mol dm⁻³ solution is approximately:', options: ['2.87','4.74','5.00','1.00'], answer: 0 },
    { q: 'For the reaction A + B → C, the rate-determining step is: A + A → X (slow), then X + B → C (fast). The rate equation is:', options: ['rate = k[A]²[B]','rate = k[A]²','rate = k[A][B]','rate = k[B]'], answer: 1 },
    { q: 'A buffer contains 0.10 mol dm⁻³ CH₃COOH and 0.20 mol dm⁻³ CH₃COONa. If Ka = 1.8 × 10⁻⁵, the pH is approximately:', options: ['4.44','4.74','5.05','5.35'], answer: 2 },
    { q: 'The ligand substitution of [Co(H₂O)₆]²⁺ with concentrated HCl forms [CoCl₄]²⁻. The change in coordination number is:', options: ['4 to 6','6 to 2','4 to 4','6 to 4'], answer: 3 },
    { q: 'A reaction has ΔH = +100 kJ mol⁻¹ and ΔS = +200 J K⁻¹ mol⁻¹. The minimum temperature for feasibility is:', options: ['500 K','0.5 K','2000 K','200 K'], answer: 0 },
    { q: 'The electrode potential of a half-cell becomes more positive when:', options: ['The electrode is made larger','The concentration of the metal ion in solution increases','The concentration of the metal ion decreases','The temperature decreases'], answer: 1 },
    { q: 'In the reaction: Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O, Cr changes oxidation state from:', options: ['+3 to +6','+6 to 0','+6 to +3','+7 to +3'], answer: 2 },
    { q: 'When NH₃ is added to [Cu(H₂O)₆]²⁺ in excess, the deep blue complex formed is:', options: ['Cu(NH₃)₂','[Cu(NH₃)₆]²⁺','[Cu(OH)₂(H₂O)₄]','[Cu(NH₃)₄(H₂O)₂]²⁺'], answer: 3 },
  ],
},

'M6': {
  name: 'Organic Chemistry and Analysis',
  green: [
    { q: 'Benzene has the molecular formula:', options: ['C₆H₆', 'C₆H₁₂', 'C₆H₁₀', 'C₅H₆'], answer: 0 },
    { q: 'The bonding in benzene is best described as:', options: ['Alternating single and double bonds', 'A delocalised ring of electrons above and below the plane', 'All single bonds', 'All double bonds'], answer: 1 },
    { q: 'An aldehyde has the functional group:', options: ['-OH', '-COOH', '-CHO', '-CO- (between two carbons)'], answer: 2 },
    { q: 'A carboxylic acid contains the functional group:', options: ['-COO-', '-CHO', '-CO-', '-COOH'], answer: 3 },
    { q: 'An amine contains which functional group?', options: ['-NH₂ (or -NHR, -NR₂)', '-NO₂', '-OH', '-COOH (carboxyl group)'], answer: 0 },
    { q: 'A condensation polymer is formed when:', options: ['Monomers join with no other product', 'Monomers join with loss of a small molecule (e.g. H₂O)', 'Only alkenes polymerise', 'Only addition reactions occur'], answer: 1 },
    { q: 'NMR spectroscopy detects:', options: ['Bond vibrations', 'The mass of fragments', 'The chemical environment of ¹H or ¹³C nuclei', 'UV absorption'], answer: 2 },
    { q: 'In ¹H NMR, the number of peaks indicates:', options: ['The molecular mass', 'The number of carbon atoms', 'The total number of hydrogen atoms', 'The number of different chemical environments of hydrogen'], answer: 3 },
    { q: 'TMS (tetramethylsilane) is used as a reference in NMR because:', options: ['It gives a single peak at chemical shift 0', 'It absorbs UV light', 'It is a strong acid', 'It is radioactive'], answer: 0 },
    { q: 'Chromatography separates mixtures based on:', options: ['Boiling point only', 'Different affinities for the stationary and mobile phases', 'Colour only', 'Molecular mass only'], answer: 1 },
    { q: 'What type of reaction does benzene typically undergo?', options: ['Free radical addition', 'Addition', 'Electrophilic substitution', 'Nucleophilic addition to the ring'], answer: 2 },
    { q: 'A ketone has the general structure:', options: ['RCOOH', 'RCOOR\'', 'RCHO', 'RCOR\''], answer: 3 },
    { q: 'An acyl chloride has the functional group:', options: ['-COCl', '-COO-', '-COOH', '-Cl'], answer: 0 },
    { q: 'An ester is formed from:', options: ['An acid and a base', 'A carboxylic acid and an alcohol', 'Two alcohols', 'An amine and a carboxylic acid (as a salt)'], answer: 1 },
    { q: 'Polyesters are formed from the reaction between:', options: ['Alkenes', 'Haloalkanes and amines, releasing HCl', 'Dicarboxylic acids and diols', 'Amino acids'], answer: 2 },
    { q: 'Which reagent reduces a carbonyl group to an alcohol?', options: ['Br₂/AlBr₃', 'HCN', 'K₂Cr₂O₇/H⁺', 'NaBH₄'], answer: 3 },
    { q: 'The splitting pattern in ¹H NMR follows the:', options: ['n+1 rule', '2n rule', '2n+1 rule', 'n rule'], answer: 0 },
    { q: 'An amide bond links amino acids together in:', options: ['Polyesters', 'Proteins (peptides)', 'Addition polymers (poly(alkenes))', 'Nucleic acids'], answer: 1 },
    { q: 'Nylon is an example of a:', options: ['Addition polymer', 'Polyester', 'Polyamide', 'Polysaccharide'], answer: 2 },
    { q: 'Rf value in chromatography is calculated as:', options: ['Mass of spot / mass of solvent', 'Time for spot to travel / total time', 'Distance moved by the solvent front / distance moved by the spot', 'Distance moved by spot / distance moved by solvent front'], answer: 3 },
  ],
  amber: [
    { q: 'Benzene undergoes nitration using a mixture of:', options: ['Concentrated HNO₃ and concentrated H₂SO₄', 'Dilute HNO₃ and NaOH', 'HNO₃ and AlCl₃', 'HNO₃ and HCl'], answer: 0 },
    { q: 'The electrophile in the nitration of benzene is:', options: ['NO₃⁻', 'NO₂⁺ (nitronium ion)', 'HNO₃ (the nitric acid)', 'NO₂'], answer: 1 },
    { q: 'Friedel-Crafts acylation of benzene uses:', options: ['Br₂ and UV light', 'KMnO₄ and NaOH', 'An acyl chloride and an AlCl₃ catalyst', 'An alcohol and concentrated H₂SO₄ as a catalyst'], answer: 2 },
    { q: 'Phenol is more reactive than benzene towards electrophilic substitution because:', options: ['Phenol is an acid', 'The O-H bond is weaker than C-H', 'The OH group is electron-withdrawing', 'The lone pair on oxygen is donated into the ring, increasing electron density'], answer: 3 },
    { q: 'The reaction of an aldehyde with HCN produces:', options: ['A hydroxynitrile, formed by nucleophilic addition to the carbonyl group', 'A carboxylic acid, formed by oxidation of the carbonyl with the CN⁻ ion', 'A hemiacetal, formed by addition of H to the carbonyl oxygen and CN to the carbon', 'A primary amine, formed by nucleophilic substitution at the carbonyl carbon'], answer: 0 },
    { q: 'Brady\'s reagent (2,4-DNP) is used to test for:', options: ['Carboxylic acids', 'Aldehydes and ketones (carbonyl compounds)', 'Amines', 'Alcohols'], answer: 1 },
    { q: 'Tollens\' reagent gives a silver mirror with:', options: ['Carboxylic acids', 'Ketones only', 'Aldehydes only', 'Both aldehydes and ketones'], answer: 2 },
    { q: 'The nucleophilic addition mechanism for the reaction of a carbonyl with HCN involves:', options: ['H⁺ attacking the δ- oxygen', 'A free radical chain', 'Electrophilic attack on the oxygen', 'CN⁻ attacking the δ+ carbon of C=O'], answer: 3 },
    { q: 'An amino acid at its isoelectric point exists mainly as:', options: ['A zwitterion', 'A neutral molecule with no charges', 'A cation', 'An anion'], answer: 0 },
    { q: 'In ¹H NMR, a triplet peak indicates the hydrogen is adjacent to:', options: ['1 hydrogen on neighbouring carbons', '2 hydrogens on neighbouring carbons', '3 hydrogens on neighbouring carbons', '4 hydrogens on neighbouring carbons'], answer: 1 },
    { q: 'Hydrolysis of a nitrile (R-CN) with dilute acid produces:', options: ['An aldehyde', 'An amine (R-CH₂NH₂)', 'A carboxylic acid', 'An alcohol'], answer: 2 },
    { q: 'The reaction of an acyl chloride with an amine produces:', options: ['A carboxylic acid and NH₃', 'An alcohol and HCl', 'An ester and HCl', 'An amide and HCl'], answer: 3 },
    { q: 'Optical isomerism occurs when a carbon atom has:', options: ['Four different groups attached (chiral centre)', 'Two identical groups', 'No hydrogen atoms', 'A double bond'], answer: 0 },
    { q: 'A racemic mixture contains:', options: ['Only one enantiomer', 'Equal amounts of both enantiomers', 'Only the R isomer', 'A mixture of structural isomers in any ratio'], answer: 1 },
    { q: 'In ¹³C NMR, the number of peaks indicates:', options: ['The number of hydrogen atoms', 'The total number of carbon atoms in the molecule', 'The number of different carbon environments', 'The molecular mass'], answer: 2 },
    { q: 'PET (polyethylene terephthalate) is a:', options: ['Addition polymer', 'Polypeptide', 'Polyamide', 'Polyester'], answer: 3 },
    { q: 'Kevlar is a polyamide made from:', options: ['A diamine and a dicarboxylic acid (aromatic monomers)', 'Ethene monomers', 'Amino acids only', 'Diols and dicarboxylic acids'], answer: 0 },
    { q: 'Gas chromatography-mass spectrometry (GC-MS) combines:', options: ['Electrophoresis with X-ray diffraction', 'Separation by boiling point with identification by fragmentation pattern', 'Separation by colour with UV detection', 'NMR with IR spectroscopy'], answer: 1 },
    { q: 'The reaction of a carboxylic acid with an alcohol in the presence of an acid catalyst produces:', options: ['A ketone and water', 'An amide and water', 'An ester and water', 'An aldehyde and water'], answer: 2 },
    { q: 'Benzene reacts with Br₂ in the presence of AlBr₃ catalyst. The organic product is:', options: ['Phenol', 'Cyclohexane', '1,2-dibromocyclohexane', 'Bromobenzene'], answer: 3 },
  ],
  red: [
    { q: 'The Kekule model of benzene is incorrect because:', options: ['Benzene does not decolourise bromine water','Benzene has alternating bond lengths','Benzene reacts by addition','Benzene is a gas at room temperature, so it cannot be a ring'], answer: 0 },
    { q: "In the nucleophilic addition of HCN to propanal, the product has a chiral centre. The product is:", options: ["Optically active","A racemic mixture because the CN⁻ can attack the planar carbonyl carbon from either side equally","Only the R enantiomer","Not chiral"], answer: 1 },
    { q: 'The directing effect of an -NH₂ group on a benzene ring means further substitution occurs mainly at:', options: ['Only the para (4) position, as the NH₂ group is bulky','The meta position','The 2,4 (ortho and para) positions','All positions equally'], answer: 2 },
    { q: "A compound C₄H₈O₂ shows three peaks in its ¹³C NMR spectrum. The compound is most likely:", options: ["Butanoic acid","Ethyl ethanoate","Methyl propanoate","2-methylpropanoic acid"], answer: 3 },
    { q: 'Condensation polymers can be broken down by hydrolysis. This is a problem for:', options: ['Polyester clothing exposed to strongly acidic or basic conditions','PVC pipes','Polythene bags','Addition polymers in landfill'], answer: 0 },
    { q: 'In ¹H NMR, a peak at δ 9-10 ppm is characteristic of:', options: ['R-OH','R-CHO (aldehyde proton)','R-COOH (carboxylic acid proton)','Aromatic H'], answer: 1 },
    { q: 'A compound gives a positive iodoform test. It could be:', options: ['Propanal','Pentan-3-one','Ethanol','Propan-1-ol'], answer: 2 },
    { q: 'The mechanism for electrophilic substitution of benzene involves:', options: ['Nucleophilic attack on the ring','A carbanion intermediate','A free radical chain','A carbocation intermediate formed when the electrophile accepts a pair of electrons from the delocalised ring'], answer: 3 },
    { q: 'Azo dyes are formed by coupling a diazonium salt with:', options: ['A phenol or aromatic amine in alkaline conditions','Concentrated HCl at room temperature, which releases the dye','An alkane','An aldehyde'], answer: 0 },
    { q: 'A compound has molecular formula C₃H₇NO. Its IR shows N-H and C=O absorptions. Its ¹H NMR shows a singlet (3H), a singlet (3H), and a broad signal (1H). The compound is:', options: ['Propanamide (CH₃CH₂CONH₂), with a triplet and quartet','N-methylacetamide (N-methylethanamide)','Propylamine','3-aminopropanal'], answer: 1 },
  ],
},

};
