const CHEMISTRY_AQA_QUESTIONS = {

  'P1': {
    name: 'Physical Chemistry I',
    green: [
      { q: 'What is the relative charge of a proton?', options: ['+1', '-1', '0', '+2'], answer: 0 },
      { q: 'How many electrons can the first electron shell hold?', options: ['2', '8', '18', '32'], answer: 0 },
      { q: 'What is the mass number of an atom?', options: ['Number of protons + neutrons', 'Number of protons only', 'Number of electrons only', 'Number of neutrons only'], answer: 0 },
      { q: 'Isotopes have the same number of which particle?', options: ['Protons', 'Neutrons', 'Electrons and neutrons', 'Neutrons only'], answer: 0 },
      { q: 'What is the Avogadro constant?', options: ['6.022 x 10^23', '6.022 x 10^22', '3.01 x 10^23', '6.022 x 10^24'], answer: 0 },
      { q: 'What is the formula for calculating moles from mass?', options: ['mass / molar mass', 'mass x molar mass', 'molar mass / mass', 'mass x volume'], answer: 0 },
      { q: 'What type of bonding occurs in sodium chloride?', options: ['Ionic', 'Covalent', 'Metallic', 'Van der Waals'], answer: 0 },
      { q: 'A covalent bond involves the sharing of what?', options: ['Electron pairs', 'Protons', 'Neutrons', 'Ions'], answer: 0 },
      { q: 'What shape does a molecule with two bonding pairs and no lone pairs have?', options: ['Linear', 'Bent', 'Trigonal planar', 'Tetrahedral'], answer: 0 },
      { q: 'What is the bond angle in a tetrahedral molecule?', options: ['109.5 degrees', '120 degrees', '90 degrees', '180 degrees'], answer: 0 },
      { q: 'Metallic bonding involves a lattice of positive ions surrounded by what?', options: ['Delocalised electrons', 'Anions', 'Neutrons', 'Covalent bonds'], answer: 0 },
      { q: 'Which of these is an endothermic process?', options: ['Bond breaking', 'Bond making', 'Combustion', 'Neutralisation'], answer: 0 },
      { q: 'What is the standard enthalpy of formation measured relative to?', options: ['Elements in their standard states', 'Compounds in solution', 'Gases at STP', 'Pure liquids'], answer: 0 },
      { q: 'In a mass spectrum, what does the peak with the highest m/z value represent?', options: ['Molecular ion peak', 'Base peak', 'Fragment ion', 'Isotope peak'], answer: 0 },
      { q: 'What is the relative mass of an electron?', options: ['1/1836', '1', '0', '2'], answer: 0 },
      { q: 'The empirical formula represents what?', options: ['Simplest whole number ratio of atoms', 'Actual number of atoms', 'Number of moles', 'Molecular structure'], answer: 0 },
      { q: 'What is a coordinate (dative covalent) bond?', options: ['Both electrons in the shared pair come from one atom', 'Electrons are transferred', 'Electrons are delocalised', 'Bonds formed between ions'], answer: 0 },
      { q: 'London dispersion forces arise from what?', options: ['Temporary induced dipoles', 'Permanent dipoles', 'Ionic interactions', 'Hydrogen bonds'], answer: 0 },
      { q: 'Which state symbol represents aqueous solution?', options: ['(aq)', '(l)', '(s)', '(g)'], answer: 0 },
      { q: 'What is the unit of enthalpy change?', options: ['kJ mol^-1', 'J', 'kJ kg^-1', 'mol L^-1'], answer: 0 }
    ],
    amber: [
      { q: 'An atom has 11 protons, 12 neutrons and 11 electrons. What is its mass number?', options: ['23', '11', '12', '34'], answer: 0 },
      { q: 'Which electron configuration is correct for a chlorine atom?', options: ['1s2 2s2 2p6 3s2 3p5', '1s2 2s2 2p6 3s2 3p6', '1s2 2s2 2p6 3s1 3p5', '1s2 2s2 2p5 3s2 3p6'], answer: 0 },
      { q: 'What mass of NaOH (Mr = 40) is needed to make 250 cm3 of a 0.1 mol dm^-3 solution?', options: ['1.0 g', '4.0 g', '0.4 g', '10.0 g'], answer: 0, explanation: 'moles = concentration × volume(dm³) = 0.1 × 0.25 = 0.025 mol; mass = moles × Mr = 0.025 × 40 = 1.0 g.' },
      { q: 'In the reaction 2Mg + O2 -> 2MgO, what mass of MgO is formed from 2.4 g of Mg?', options: ['4.0 g', '2.0 g', '8.0 g', '6.0 g'], answer: 0, explanation: 'moles Mg = 2.4÷24 = 0.1 mol; 2Mg:2MgO ratio is 1:1, so moles MgO = 0.1; mass = 0.1×40 = 4.0 g.' },
      { q: 'Which molecule has a trigonal pyramidal shape?', options: ['NH3', 'BF3', 'CH4', 'CO2'], answer: 0 },
      { q: 'What is the bond angle in a molecule with three bonding pairs and one lone pair?', options: ['107 degrees', '109.5 degrees', '120 degrees', '104.5 degrees'], answer: 0 },
      { q: 'Why does diamond have a very high melting point?', options: ['Strong covalent bonds throughout the giant structure', 'Strong ionic bonds', 'Strong metallic bonds', 'Strong hydrogen bonds'], answer: 0 },
      { q: 'Calculate the enthalpy change when 100 cm3 of water rises by 15 K. (c = 4.18 J g^-1 K^-1)', options: ['-6.27 kJ', '-6270 kJ', '-62.7 kJ', '-0.627 kJ'], answer: 0, explanation: 'q = mcΔT = 100 g × 4.18 J g⁻¹K⁻¹ × 15 K = 6270 J = 6.27 kJ (negative: heat released by reaction).' },
      { q: 'Using Hess\'s law, if A->B is +50 kJ and B->C is -80 kJ, what is A->C?', options: ['-30 kJ', '+130 kJ', '-130 kJ', '+30 kJ'], answer: 0, explanation: 'ΔH(A→C) = ΔH(A→B) + ΔH(B→C) = (+50) + (−80) = −30 kJ.' },
      { q: 'Which species acts as the reducing agent in the reaction Zn + CuSO4 -> ZnSO4 + Cu?', options: ['Zn', 'Cu', 'SO4^2-', 'Cu^2+'], answer: 0 },
      { q: 'A gaseous compound has Mr = 44 and empirical formula CH2O. What is its molecular formula?', options: ['C2H4O2', 'CH2O', 'C3H6O3', 'C4H8O4'], answer: 0 },
      { q: 'Hydrogen bonding occurs between molecules containing H bonded to which atoms?', options: ['N, O, or F', 'Any non-metal', 'C, N, or O', 'S, O, or F'], answer: 0 },
      { q: 'What volume of 0.5 mol dm^-3 HCl neutralises 25 cm3 of 0.2 mol dm^-3 NaOH?', options: ['10 cm3', '25 cm3', '50 cm3', '5 cm3'], answer: 0, explanation: 'moles NaOH = 0.025 × 0.2 = 0.005 mol; HCl:NaOH = 1:1, so moles HCl = 0.005; V = 0.005÷0.5 = 0.01 dm³ = 10 cm³.' },
      { q: 'Which substance has the lowest boiling point?', options: ['He', 'H2O', 'NaCl', 'SiO2'], answer: 0 },
      { q: 'What is the oxidation state of sulfur in SO4^2-?', options: ['+6', '+4', '-2', '+2'], answer: 0 },
      { q: 'Which of these molecules is polar?', options: ['HCl', 'CO2', 'CCl4', 'BF3'], answer: 0 },
      { q: 'In a first ionisation energy trend, which element has the highest value in Period 2?', options: ['Ne', 'Li', 'Be', 'N'], answer: 0 },
      { q: 'How many moles of gas occupy 24 dm3 at RTP?', options: ['1', '2', '0.5', '24'], answer: 0, explanation: 'n = volume ÷ molar volume = 24 ÷ 24.0 = 1 mol (at RTP, 1 mol gas occupies 24.0 dm³).' },
      { q: 'What is the percentage atom economy for CaO from CaCO3 -> CaO + CO2?', options: ['56%', '44%', '100%', '28%'], answer: 0, explanation: '% atom economy = (Mr desired product ÷ total Mr all products) × 100 = (56 ÷ (56+44)) × 100 = 56%.' },
      { q: 'Which intermolecular force is strongest?', options: ['Hydrogen bonding', 'Permanent dipole-dipole', 'London dispersion forces', 'They are all equal'], answer: 0 }
    ],
    red: [
      { q: 'The successive ionisation energies of an element are: 578, 1817, 2745, 11578, 14831. How many electrons are in the outer shell?', options: ['3','2','4','1'], answer: 0 },
      { q: 'Why is the first ionisation energy of oxygen lower than that of nitrogen?', options: ['Electron pairing in the 2p orbital causes repulsion in oxygen','Oxygen has a larger atomic radius','Nitrogen has more protons','Oxygen has a higher nuclear charge'], answer: 0 },
      { q: 'A compound contains 40.0% C, 6.7% H and 53.3% O by mass. Its Mr is 180. What is the molecular formula?', options: ['C2H4O2','C3H6O3','C6H12O6','CH2O'], answer: 2, explanation: 'C: 40÷12=3.33; H: 6.7÷1=6.7; O: 53.3÷16=3.33 → ratio 1:2:1 → empirical CH₂O (Mr=30); 180÷30=6 → C₆H₁₂O₆.' },
      { q: 'Using mean bond enthalpies: C-H = 412, O=O = 496, C=O = 743, O-H = 463. Calculate the enthalpy of combustion of CH4.', options: ['-412 kJ mol^-1','-1646 kJ mol^-1','+818 kJ mol^-1','-818 kJ mol^-1'], answer: 3 },
      { q: 'Why does the boiling point of water deviate significantly from the trend in Group 16 hydrides?', options: ['Water has ionic character','Extensive hydrogen bonding between water molecules','Water has stronger London forces','Water has a lower molar mass'], answer: 1 },
      { q: 'Explain why BF3 can act as a Lewis acid.', options: ['It has an incomplete octet and can accept a lone pair','It has lone pairs to donate','It can lose a proton','It has a high electronegativity'], answer: 0 },
      { q: 'In a Born-Haber cycle for NaCl, which step has the largest endothermic value?', options: ['Lattice enthalpy','Electron affinity of chlorine','Atomisation of chlorine','Atomisation and ionisation of sodium combined'], answer: 3 },
      { q: 'A titration requires 23.50 cm3 of 0.100 mol dm^-3 Na2CO3 to neutralise 25.00 cm3 of HCl. What is the concentration of HCl?', options: ['0.188 mol dm^-3','0.235 mol dm^-3','0.100 mol dm^-3','0.094 mol dm^-3'], answer: 0, explanation: 'moles Na₂CO₃ = 0.0235 × 0.100 = 0.00235 mol; Na₂CO₃:2HCl ratio → moles HCl = 0.00470; [HCl] = 0.00470÷0.025 = 0.188 mol dm⁻³.' },
      { q: 'Why do real gases deviate from ideal behaviour at high pressures?', options: ['Temperature increases','Molecular volume becomes significant and intermolecular forces act','Molecules move faster','Molecules become smaller'], answer: 1 },
      { q: 'The electron configuration [Ar] 3d5 4s1 corresponds to which element, and why is it anomalous?', options: ['Chromium; half-filled 3d subshell is more stable','Manganese; it needs extra stability','Vanadium; electron repulsion is minimised','Iron; 3d orbitals are filled'], answer: 0 }
    ]
  },

  'P2': {
    name: 'Physical Chemistry II',
    green: [
      { q: 'What does the rate of a reaction measure?', options: ['Change in concentration per unit time', 'Total amount of product', 'Activation energy', 'Enthalpy change'], answer: 0 },
      { q: 'What is a catalyst?', options: ['A substance that increases reaction rate without being consumed', 'A substance that is used up', 'A reactant', 'An inhibitor'], answer: 0 },
      { q: 'What is the equilibrium constant Kc for a reaction at equilibrium?', options: ['Products over reactants raised to stoichiometric powers', 'Reactants over products', 'Rate of forward reaction', 'Total concentration'], answer: 0 },
      { q: 'Le Chatelier\'s principle states that a system at equilibrium will do what when disturbed?', options: ['Shift to counteract the change', 'Stop reacting', 'Shift in the same direction as the change', 'Reach a new equilibrium instantly'], answer: 0 },
      { q: 'What is the pH of a neutral solution at 25 degrees C?', options: ['7', '0', '14', '1'], answer: 0 },
      { q: 'What is a strong acid?', options: ['One that fully dissociates in solution', 'One with a high concentration', 'One that partially dissociates', 'One with a high pH'], answer: 0 },
      { q: 'What does a negative standard electrode potential indicate?', options: ['The species is a stronger reducing agent than hydrogen', 'The species is a strong oxidising agent', 'The reaction is exothermic', 'The cell potential is negative'], answer: 0 },
      { q: 'In an electrochemical cell, oxidation occurs at which electrode?', options: ['Anode', 'Cathode', 'Both', 'Neither'], answer: 0 },
      { q: 'What is the formula for calculating pH from hydrogen ion concentration?', options: ['pH = -log[H+]', 'pH = log[H+]', 'pH = [H+] / 10', 'pH = 1 / [H+]'], answer: 0 },
      { q: 'What is entropy a measure of?', options: ['Disorder in a system', 'Energy in a system', 'Temperature change', 'Pressure'], answer: 0 },
      { q: 'Which of these increases the rate of reaction?', options: ['Increasing temperature', 'Decreasing concentration', 'Removing a catalyst', 'Decreasing surface area'], answer: 0 },
      { q: 'What is the standard hydrogen electrode potential defined as?', options: ['0.00 V', '+1.00 V', '-1.00 V', '+0.50 V'], answer: 0 },
      { q: 'A buffer solution resists changes in what?', options: ['pH', 'Temperature', 'Volume', 'Concentration'], answer: 0 },
      { q: 'What is Kw at 25 degrees C?', options: ['1.00 x 10^-14 mol2 dm^-6', '1.00 x 10^-7 mol dm^-3', '7', '1.00 x 10^-12 mol2 dm^-6'], answer: 0 },
      { q: 'In a dynamic equilibrium, what is true?', options: ['Rate of forward reaction equals rate of backward reaction', 'All reactions have stopped', 'Only products are present', 'Only reactants are present'], answer: 0 },
      { q: 'What is the sign of delta G for a spontaneous reaction?', options: ['Negative', 'Positive', 'Zero', 'Cannot determine'], answer: 0 },
      { q: 'Increasing pressure shifts equilibrium towards the side with what?', options: ['Fewer moles of gas', 'More moles of gas', 'Higher temperature', 'Lower energy'], answer: 0 },
      { q: 'What is the conjugate base of HCl?', options: ['Cl^-', 'H+', 'OH-', 'HCl2-'], answer: 0 },
      { q: 'What are the units of Kc if all species are in mol dm^-3 and the equation is A -> B?', options: ['No units', 'mol dm^-3', 'mol^-1 dm^3', 'mol^2 dm^-6'], answer: 0 },
      { q: 'Which factor does NOT affect the value of Kc?', options: ['Catalyst', 'Temperature', 'Neither — both affect Kc', 'Both affect Kc'], answer: 0 }
    ],
    amber: [
      { q: 'The rate equation is rate = k[A]^2[B]. What is the overall order?', options: ['3', '2', '1', '4'], answer: 0 },
      { q: 'If the concentration of A is doubled and the rate quadruples, what is the order with respect to A?', options: ['2', '1', '3', '0'], answer: 0 },
      { q: 'Calculate the pH of 0.01 mol dm^-3 HCl.', options: ['2', '1', '0.01', '12'], answer: 0, explanation: 'HCl fully dissociates: [H⁺] = 0.01 = 10⁻² mol dm⁻³. pH = −log(10⁻²) = 2.' },
      { q: 'What is the pH of 0.1 mol dm^-3 NaOH at 25 degrees C?', options: ['13', '1', '7', '14'], answer: 0, explanation: '[OH⁻] = 0.1; pOH = −log(0.1) = 1; at 25°C: pH = 14 − 1 = 13.' },
      { q: 'For the reaction N2 + 3H2 <=> 2NH3, what is the Kp expression?', options: ['p(NH3)^2 / (p(N2) x p(H2)^3)', 'p(N2) x p(H2)^3 / p(NH3)^2', 'p(NH3) / p(N2) x p(H2)', '2p(NH3) / p(N2) + 3p(H2)'], answer: 0 },
      { q: 'An endothermic reaction is at equilibrium. What happens if temperature increases?', options: ['Equilibrium shifts to the right, Kc increases', 'Equilibrium shifts to the left, Kc decreases', 'No change', 'Kc stays the same but position shifts right'], answer: 0 },
      { q: 'What is the cell EMF if E(cathode) = +0.34 V and E(anode) = -0.76 V?', options: ['+1.10 V', '-0.42 V', '+0.42 V', '-1.10 V'], answer: 0, explanation: 'E_cell = E(cathode) − E(anode) = +0.34 − (−0.76) = +0.34 + 0.76 = +1.10 V.' },
      { q: 'A reaction has delta H = -100 kJ and delta S = +50 J K^-1. At 298 K, what is delta G?', options: ['-114.9 kJ', '-85.1 kJ', '+114.9 kJ', '-50 kJ'], answer: 0, explanation: 'ΔG = ΔH − TΔS. Convert ΔS: 50 J K⁻¹ = 0.050 kJ K⁻¹. ΔG = −100 − (298×0.050) = −114.9 kJ.' },
      { q: 'Which of these is a buffer solution?', options: ['CH3COOH and CH3COONa', 'HCl and NaCl', 'NaOH and NaCl', 'H2SO4 and Na2SO4'], answer: 0 },
      { q: 'What happens to the rate constant k when temperature increases?', options: ['It increases', 'It decreases', 'It stays the same', 'It becomes zero'], answer: 0 },
      { q: 'The Arrhenius equation is k = Ae^(-Ea/RT). What does Ea represent?', options: ['Activation energy', 'Enthalpy change', 'Entropy', 'Free energy'], answer: 0 },
      { q: 'Calculate Ka for a weak acid with pH 2.87 and initial concentration 0.1 mol dm^-3.', options: ['1.82 x 10^-5 mol dm^-3', '1.35 x 10^-3 mol dm^-3', '1.82 x 10^-3 mol dm^-3', '1.35 x 10^-5 mol dm^-3'], answer: 0, explanation: '[H⁺] = 10^⁻²·⁸⁷ = 1.35×10⁻³. Ka = [H⁺]²÷[HA] = (1.35×10⁻³)²÷0.1 = 1.82×10⁻⁵ mol dm⁻³.' },
      { q: 'What is the half-life of a first-order reaction?', options: ['Constant regardless of concentration', 'Proportional to initial concentration', 'Inversely proportional to concentration', 'Variable and unpredictable'], answer: 0 },
      { q: 'For the equilibrium PCl5 <=> PCl3 + Cl2, how does adding an inert gas at constant volume affect the position?', options: ['No effect', 'Shifts right', 'Shifts left', 'Depends on temperature'], answer: 0 },
      { q: 'A reaction is second order overall. What are the units of the rate constant k?', options: ['mol^-1 dm^3 s^-1', 'mol dm^-3 s^-1', 's^-1', 'mol^-2 dm^6 s^-1'], answer: 0 },
      { q: 'Which indicator is suitable for a strong acid-weak base titration?', options: ['Methyl orange', 'Phenolphthalein', 'Universal indicator', 'Litmus'], answer: 0 },
      { q: 'What is the relationship between Kc and Kp?', options: ['Kp = Kc(RT)^delta_n', 'Kp = Kc / RT', 'Kp = Kc x R', 'Kp = Kc + delta_n'], answer: 0 },
      { q: 'At the equivalence point of a strong acid-strong base titration, the pH is?', options: ['7', 'Less than 7', 'Greater than 7', 'Depends on concentration'], answer: 0 },
      { q: 'What is the order of a reaction if its rate-concentration graph is a straight line through the origin?', options: ['First order', 'Zero order', 'Second order', 'Third order'], answer: 0 },
      { q: 'In an electrochemical cell, which half-cell has the more negative electrode potential?', options: ['The anode', 'The cathode', 'Both are equal', 'It depends on concentration'], answer: 0 }
    ],
    red: [
      { q: 'A reaction has rate = k[A][B]^2. Experiments show doubling [A] doubles the rate and doubling [B] quadruples it. The mechanism has a slow step of A + B2 -> AB2. Is this consistent?', options: ['No, the orders do not match','Yes, the rate equation matches the slow step','Cannot determine from this data','Only if a catalyst is present'], answer: 1 },
      { q: 'For the equilibrium 2SO2 + O2 <=> 2SO3, delta H = -197 kJ. The system is at equilibrium at 700 K. Which change increases the yield of SO3 AND increases the rate?', options: ['Decreasing temperature only','Adding a catalyst and increasing pressure','Removing SO3 only','Increasing temperature only'], answer: 1 },
      { q: 'The pH of a buffer solution made from 0.1 mol dm^-3 CH3COOH and 0.15 mol dm^-3 CH3COONa is? (Ka = 1.74 x 10^-5)', options: ['4.94','4.76','4.58','5.12'], answer: 0, explanation: 'pH = pKa + log([A⁻]/[HA]) = −log(1.74×10⁻⁵) + log(0.15/0.1) = 4.76 + 0.176 = 4.94.' },
      { q: 'A fuel cell converts chemical energy directly to electrical energy. Why is a hydrogen fuel cell more efficient than burning hydrogen in a combustion engine?', options: ['It operates at higher temperature','It produces more water','It uses a catalyst','It bypasses the Carnot efficiency limit by not using a heat engine'], answer: 3 },
      { q: 'The Gibbs free energy equation is delta G = delta H - T delta S. At what temperature does a reaction with delta H = +50 kJ and delta S = +100 J K^-1 become spontaneous?', options: ['Above 500 K','Below 500 K','At all temperatures','Never spontaneous'], answer: 0, explanation: 'Spontaneous when ΔG<0, i.e. T>ΔH/ΔS = 50,000 J÷100 J K⁻¹ = 500 K.' },
      { q: 'Explain why the lattice enthalpy calculated from a Born-Haber cycle for AgI is significantly different from the theoretical value.', options: ['AgI has significant covalent character due to polarisation','AgI is purely ionic','The Born-Haber value is always more accurate','There is no difference'], answer: 0 },
      { q: 'A clock reaction experiment gives these results: [A]=0.1, t=40s; [A]=0.2, t=10s; [A]=0.3, t=4.4s. What is the likely order with respect to A?', options: ['Second order','First order','Zero order','Third order'], answer: 0, explanation: 'Rate∝1/t. [A] doubles (0.1→0.2) → rate ratio = 40/10 = 4 (quadrupled). Rate ∝ [A]² → second order.' },
      { q: 'Why does the entropy of the system decrease when water freezes, yet it can still occur spontaneously at temperatures below 0 degrees C?', options: ['Entropy of the universe decreases','Enthalpy has no role','Delta G is positive','The entropy of the surroundings increases more than the system entropy decreases'], answer: 3 },
      { q: 'For the titration of a diprotic acid H2A with NaOH, how many equivalence points are observed if Ka1 >> Ka2?', options: ['Two distinct equivalence points','One equivalence point','Three equivalence points','No equivalence points'], answer: 0 },
      { q: 'In a concentration cell where both half-cells contain Cu/Cu^2+ but at different concentrations, what determines the cell EMF?', options: ['The ratio of ion concentrations via the Nernst equation','The standard electrode potential alone','The temperature only','The volume of solution'], answer: 0 }
    ]
  },

  'I1': {
    name: 'Inorganic Chemistry I',
    green: [
      { q: 'What is periodicity?', options: ['Repeating trends in properties across periods', 'Random variation in properties', 'Properties unique to one group', 'Trends down a group only'], answer: 0 },
      { q: 'Group 2 elements are also known as what?', options: ['Alkaline earth metals', 'Alkali metals', 'Halogens', 'Noble gases'], answer: 0 },
      { q: 'What is the trend in atomic radius going down Group 2?', options: ['Increases', 'Decreases', 'Stays the same', 'Increases then decreases'], answer: 0 },
      { q: 'Group 7 elements are known as what?', options: ['Halogens', 'Alkali metals', 'Noble gases', 'Transition metals'], answer: 0 },
      { q: 'What colour is chlorine gas?', options: ['Pale green', 'Brown', 'Purple', 'Colourless'], answer: 0 },
      { q: 'What is the trend in electronegativity across a period?', options: ['Increases', 'Decreases', 'Stays the same', 'Decreases then increases'], answer: 0 },
      { q: 'What product forms when Group 2 metals react with water?', options: ['Metal hydroxide and hydrogen', 'Metal oxide and water', 'Metal chloride and oxygen', 'No reaction'], answer: 0 },
      { q: 'What colour is bromine at room temperature?', options: ['Red-brown liquid', 'Pale green gas', 'Purple solid', 'Colourless gas'], answer: 0 },
      { q: 'What happens to first ionisation energy across Period 3?', options: ['Generally increases', 'Generally decreases', 'Stays constant', 'Halves each time'], answer: 0 },
      { q: 'What is the electron configuration of Mg?', options: ['1s2 2s2 2p6 3s2', '1s2 2s2 2p6 3s1', '1s2 2s2 2p6 3s2 3p1', '1s2 2s2 2p6'], answer: 0 },
      { q: 'Which Group 2 metal reacts most vigorously with water?', options: ['Barium', 'Magnesium', 'Calcium', 'Beryllium'], answer: 0 },
      { q: 'Halogens exist as what type of molecules?', options: ['Diatomic', 'Monatomic', 'Triatomic', 'Polyatomic'], answer: 0 },
      { q: 'What type of bonding exists in NaCl?', options: ['Ionic', 'Covalent', 'Metallic', 'Hydrogen bonding'], answer: 0 },
      { q: 'What is the state of iodine at room temperature?', options: ['Grey-black solid', 'Brown liquid', 'Green gas', 'Colourless gas'], answer: 0 },
      { q: 'What is the trend in boiling point of halogens going down the group?', options: ['Increases', 'Decreases', 'Stays the same', 'Alternates'], answer: 0 },
      { q: 'Which Group 2 compound is used as an antacid?', options: ['Mg(OH)2', 'BaCl2', 'CaF2', 'SrSO4'], answer: 0 },
      { q: 'What is the charge on a halide ion?', options: ['-1', '+1', '-2', '+2'], answer: 0 },
      { q: 'Which element has the highest first ionisation energy in Period 3?', options: ['Argon', 'Sodium', 'Chlorine', 'Silicon'], answer: 0 },
      { q: 'What happens to reactivity going down Group 2?', options: ['Increases', 'Decreases', 'Stays the same', 'Decreases then increases'], answer: 0 },
      { q: 'What happens to reactivity going down Group 7?', options: ['Decreases', 'Increases', 'Stays the same', 'Increases then decreases'], answer: 0 }
    ],
    amber: [
      { q: 'Why does sodium have a lower first ionisation energy than magnesium?', options: ['Sodium has one fewer proton and the outer electron is easier to remove', 'Sodium has a larger nuclear charge', 'Magnesium has more shielding', 'Sodium has a full outer shell'], answer: 0 },
      { q: 'When chlorine water is added to potassium bromide solution, what is observed?', options: ['Solution turns orange-brown', 'Solution turns purple', 'No change', 'Solution turns green'], answer: 0 },
      { q: 'What is the product when barium reacts with dilute sulfuric acid?', options: ['BaSO4 and H2 (reaction slows due to insoluble BaSO4)', 'BaCl2 and H2O', 'BaO and H2', 'Ba(OH)2 and SO3'], answer: 0 },
      { q: 'Why is there a drop in ionisation energy between beryllium and boron?', options: ['Boron removes a 2p electron which is higher in energy and easier to remove', 'Boron has fewer protons', 'Beryllium has more shielding', 'Boron has a full 2s orbital'], answer: 0 },
      { q: 'Silver nitrate solution is added to a solution containing chloride ions. What is seen?', options: ['White precipitate', 'Cream precipitate', 'Yellow precipitate', 'No precipitate'], answer: 0 },
      { q: 'What is the trend in solubility of Group 2 sulfates?', options: ['Decreases down the group', 'Increases down the group', 'All are soluble', 'All are insoluble'], answer: 0 },
      { q: 'Why does fluorine not follow the expected trend in halogen reactivity?', options: ['F-F bond is weak due to lone pair repulsion in the small atom', 'Fluorine is less electronegative', 'Fluorine has a large atomic radius', 'Fluorine has low electron affinity'], answer: 0 },
      { q: 'What is the test for sulfate ions?', options: ['Add barium chloride solution; white precipitate forms', 'Add silver nitrate; yellow precipitate forms', 'Add sodium hydroxide; gas produced', 'Add hydrochloric acid; fizzing occurs'], answer: 0 },
      { q: 'Why does silicon have a very high melting point among Period 3 elements?', options: ['Silicon has a giant covalent structure with strong covalent bonds', 'Silicon is metallic', 'Silicon has ionic bonding', 'Silicon has weak intermolecular forces'], answer: 0 },
      { q: 'Concentrated sulfuric acid reacts differently with different halide salts. What happens with NaBr?', options: ['HBr is produced initially, then some is oxidised to Br2', 'Only HBr is produced with no oxidation', 'SO2 and S are produced', 'No reaction occurs'], answer: 0 },
      { q: 'What is the trend in thermal stability of Group 2 carbonates?', options: ['Increases down the group', 'Decreases down the group', 'All decompose at the same temperature', 'None decompose'], answer: 0 },
      { q: 'Which halide ion is the strongest reducing agent?', options: ['I^-', 'Br^-', 'Cl^-', 'F^-'], answer: 0 },
      { q: 'When chlorine is dissolved in water, what reaction occurs?', options: ['Cl2 + H2O -> HCl + HClO (disproportionation)', 'Cl2 + H2O -> 2HCl', 'No reaction', 'Cl2 + 2H2O -> 2HCl + O2'], answer: 0 },
      { q: 'Why does MgCO3 decompose at a lower temperature than BaCO3?', options: ['Mg^2+ is smaller and more polarising, weakening the carbonate ion', 'BaCO3 has weaker bonds', 'MgCO3 has stronger ionic bonding', 'BaCO3 is more covalent'], answer: 0 },
      { q: 'What is the flame colour of calcium compounds?', options: ['Orange-red', 'Green', 'Red', 'Yellow'], answer: 0 },
      { q: 'How is chlorine used in water treatment?', options: ['It kills bacteria by oxidation', 'It removes dissolved metals', 'It adjusts pH', 'It removes sediment'], answer: 0 },
      { q: 'What precipitate colour forms when silver nitrate is added to iodide ions?', options: ['Yellow', 'White', 'Cream', 'No precipitate'], answer: 0 },
      { q: 'Why is the first ionisation energy of neon much higher than sodium?', options: ['Neon has a higher nuclear charge with the same number of electron shells', 'Neon has more electron shells', 'Sodium has a higher nuclear charge', 'Neon has less shielding'], answer: 0 },
      { q: 'Group 2 hydroxides show what trend in solubility?', options: ['Increase down the group', 'Decrease down the group', 'All are equally soluble', 'All are insoluble'], answer: 0 },
      { q: 'What is the test for a carbonate? Adding dilute HCl produces...', options: ['CO2 gas which turns limewater milky', 'H2 gas which pops', 'O2 gas which relights a splint', 'Cl2 gas which bleaches litmus'], answer: 0 }
    ],
    red: [
      { q: 'Explain why the trend in first ionisation energy across Period 3 is not a smooth increase, referencing the dips at Al and S.', options: ['Al loses a 2p electron (less stable than 2s) and S has paired 2p electron repulsion','Al and S have anomalous nuclear charges','Shielding increases suddenly at Al and S','The 3d orbitals begin to fill at Al'], answer: 0 },
      { q: 'Concentrated H2SO4 is added to NaI. Multiple products form. Which set is correct?', options: ['HI and I2 only','NaI does not react with H2SO4','HI, I2, H2S, S, SO2 (H2SO4 is reduced in multiple steps)','Only HI'], answer: 2 },
      { q: 'Why can the thermal stability of Group 2 carbonates be explained using polarisation?', options: ['Smaller cations polarise the large carbonate anion more, weakening C-O bonds','Larger cations create stronger ionic bonds','Polarisation only affects covalent compounds','All carbonates have the same stability'], answer: 0 },
      { q: 'The disproportionation of Cl2 in NaOH depends on temperature. At room temperature Cl2 + 2NaOH -> NaCl + NaClO + H2O. At 70 degrees C, what forms?', options: ['NaCl and NaClO3 (chlorate(V))','NaCl and NaClO2','Only NaClO','NaCl and NaClO4'], answer: 0 },
      { q: 'Why does beryllium chloride have significant covalent character unlike other Group 2 chlorides?', options: ['Be^2+ is very small with high charge density, strongly polarising Cl^-','Beryllium has a low electronegativity','Chlorine is not electronegative enough','All Group 2 chlorides are covalent'], answer: 0 },
      { q: 'Using electrode potentials, predict whether iodide ions can reduce Fe^3+ to Fe^2+. E(Fe3+/Fe2+) = +0.77 V, E(I2/I-) = +0.54 V.', options: ['Only at high temperatures','Cannot be determined from electrode potentials','Yes; E_cell = +0.23 V which is positive so feasible','No; E_cell is negative'], answer: 2 },
      { q: 'Why does aluminium oxide have a very high melting point while P4O10 has a relatively low melting point, despite both being Period 3 oxides?', options: ['Both have giant structures but P4O10 is less dense','Al2O3 is molecular','Al2O3 has a giant ionic lattice; P4O10 is simple molecular with weak intermolecular forces','P4O10 has stronger bonds than Al2O3'], answer: 2 },
      { q: 'A student adds excess NaOH to a solution of aluminium sulfate. What happens and why?', options: ['White precipitate forms then dissolves as Al(OH)3 is amphoteric, forming [Al(OH)4]^-','White precipitate forms and remains','No precipitate forms','A green precipitate forms'], answer: 0 },
      { q: 'Explain why the electron affinity of chlorine is more exothermic than that of fluorine.', options: ['Fluorine is very small so electron repulsion in the 2p subshell is significant','Chlorine has a higher nuclear charge','Fluorine has a larger atomic radius','Chlorine has less shielding'], answer: 0 },
      { q: 'Why is barium sulfate used in medical imaging despite barium ions being toxic?', options: ['BaSO4 decomposes in the stomach','BaSO4 is absorbed safely','Ba^2+ ions are not actually toxic','BaSO4 is extremely insoluble so Ba^2+ ions are not released into the body'], answer: 3 }
    ]
  },

  'I2': {
    name: 'Inorganic Chemistry II',
    green: [
      { q: 'Where are transition metals located in the periodic table?', options: ['d-block, between Groups 2 and 3', 'p-block', 's-block', 'f-block'], answer: 0 },
      { q: 'What is a key property of transition metals related to oxidation states?', options: ['They can form multiple stable oxidation states', 'They only exist in the +2 oxidation state', 'They have no variable oxidation states', 'They only form +1 ions'], answer: 0 },
      { q: 'What colour are Cu^2+ compounds typically?', options: ['Blue', 'Green', 'Yellow', 'Colourless'], answer: 0 },
      { q: 'What is a ligand?', options: ['A species that donates a lone pair to a central metal ion', 'A metal ion', 'An anion only', 'A neutral atom with no lone pairs'], answer: 0 },
      { q: 'What is the coordination number?', options: ['Number of coordinate bonds to the central metal ion', 'Number of ligands in solution', 'Charge on the metal ion', 'Number of d electrons'], answer: 0 },
      { q: 'What is the shape of [Cu(H2O)6]^2+?', options: ['Octahedral', 'Tetrahedral', 'Linear', 'Square planar'], answer: 0 },
      { q: 'Which ion is responsible for the colour of potassium manganate(VII)?', options: ['MnO4^-', 'K+', 'Mn^2+', 'O^2-'], answer: 0 },
      { q: 'What colour precipitate forms when NaOH is added to Fe^2+ ions?', options: ['Green', 'Brown', 'White', 'Blue'], answer: 0 },
      { q: 'What colour precipitate forms when NaOH is added to Fe^3+ ions?', options: ['Brown', 'Green', 'White', 'Blue'], answer: 0 },
      { q: 'Period 3 elements Na to Ar show what trend in atomic radius?', options: ['Decrease across the period', 'Increase across the period', 'Stay the same', 'Increase then decrease'], answer: 0 },
      { q: 'What is the electron configuration of Fe?', options: ['[Ar] 3d6 4s2', '[Ar] 3d8', '[Ar] 3d5 4s2', '[Ar] 3d7 4s1'], answer: 0 },
      { q: 'Na2O is what type of oxide?', options: ['Basic', 'Acidic', 'Amphoteric', 'Neutral'], answer: 0 },
      { q: 'What type of oxide is SiO2?', options: ['Acidic (weakly)', 'Basic', 'Amphoteric', 'Neutral'], answer: 0 },
      { q: 'Transition metals can act as catalysts because of what property?', options: ['Variable oxidation states', 'High melting points', 'Coloured compounds', 'Large atomic radii'], answer: 0 },
      { q: 'What is the formula of the hexaaquairon(III) ion?', options: ['[Fe(H2O)6]^3+', '[Fe(H2O)4]^2+', '[Fe(OH)6]^3-', '[FeO6]^3+'], answer: 0 },
      { q: 'What is the charge on the chromate ion?', options: ['-2 (CrO4^2-)', '-1', '-3', '0'], answer: 0 },
      { q: 'Which Period 3 oxide reacts with both acids and bases?', options: ['Al2O3', 'Na2O', 'SiO2', 'P4O10'], answer: 0 },
      { q: 'Water is what type of ligand?', options: ['Monodentate', 'Bidentate', 'Polydentate', 'Non-ligand'], answer: 0 },
      { q: 'What is a complex ion?', options: ['A metal ion surrounded by ligands', 'A simple ionic compound', 'A covalent molecule', 'An acid'], answer: 0 },
      { q: 'What colour are Cr^3+ ions in solution?', options: ['Green', 'Yellow', 'Blue', 'Colourless'], answer: 0 }
    ],
    amber: [
      { q: 'Why do transition metal ions form coloured compounds?', options: ['d-d electron transitions absorb specific wavelengths of visible light', 'They reflect all light', 'Ligands are coloured', 'The metal itself is coloured'], answer: 0 },
      { q: 'What is the electron configuration of Cu^2+?', options: ['[Ar] 3d9', '[Ar] 3d8 4s1', '[Ar] 3d10', '[Ar] 3d7 4s2'], answer: 0 },
      { q: 'EDTA is a hexadentate ligand. What does this mean?', options: ['It forms 6 coordinate bonds with the metal ion', 'It has 6 atoms total', 'It bonds to 6 different metals', 'It has 6 lone pairs total'], answer: 0 },
      { q: 'When excess NaOH is added to Cr^3+ ions, what happens?', options: ['Green precipitate dissolves to form [Cr(OH)6]^3- (dark green solution)', 'Green precipitate remains', 'No precipitate forms', 'Brown precipitate forms'], answer: 0 },
      { q: 'Which transition metal compound catalyses the decomposition of hydrogen peroxide?', options: ['MnO2', 'CuO', 'Fe2O3', 'ZnO'], answer: 0 },
      { q: 'The reaction of [Cu(H2O)6]^2+ with excess NH3 produces what?', options: ['[Cu(NH3)4(H2O)2]^2+ (deep blue solution)', '[Cu(NH3)6]^2+', 'Cu(OH)2 precipitate only', 'No reaction'], answer: 0 },
      { q: 'Why is Sc^3+ colourless?', options: ['It has no d electrons so no d-d transitions are possible', 'It absorbs UV light', 'It has a full d subshell', 'Its d electrons are paired'], answer: 0 },
      { q: 'What is the oxidation state of Cr in Cr2O7^2-?', options: ['+6', '+3', '+7', '+2'], answer: 0 },
      { q: 'Period 3 chlorides: NaCl, MgCl2 are ionic. What about AlCl3?', options: ['Ionic when solid but covalent when vapour due to polarisation', 'Purely ionic', 'Purely covalent', 'Metallic'], answer: 0 },
      { q: 'What type of isomerism occurs when the same formula complex has different spatial arrangements?', options: ['Geometric (cis-trans) isomerism', 'Structural isomerism', 'Optical isomerism', 'Chain isomerism'], answer: 0 },
      { q: 'What is the role of vanadium(V) oxide in the Contact Process?', options: ['Catalyst for the oxidation of SO2 to SO3', 'Reactant consumed in the process', 'It provides sulfur', 'It absorbs SO3'], answer: 0 },
      { q: 'When [Fe(H2O)6]^3+ reacts with Na2CO3 solution, what happens?', options: ['CO2 gas is evolved and Fe(OH)3 precipitate forms (carbonate is too basic)', 'Fe2(CO3)3 precipitate forms', 'No reaction', 'A blue solution forms'], answer: 0 },
      { q: 'What change is observed when potassium dichromate(VI) is reduced?', options: ['Orange to green (Cr^6+ to Cr^3+)', 'Green to orange', 'Yellow to orange', 'Purple to colourless'], answer: 0 },
      { q: 'Which Period 3 oxide produces an acidic solution when dissolved in water?', options: ['P4O10', 'MgO', 'Na2O', 'Al2O3'], answer: 0 },
      { q: 'Why is zinc not considered a transition metal by the strict definition?', options: ['Zn^2+ has a full 3d10 configuration; it does not form an ion with a partially filled d subshell', 'Zinc is in the s-block', 'Zinc does not form coloured compounds', 'Zinc has no d electrons'], answer: 0 },
      { q: 'What is the shape of [CuCl4]^2-?', options: ['Tetrahedral', 'Octahedral', 'Square planar', 'Linear'], answer: 0 },
      { q: 'How does the reaction of Na and Mg with water compare?', options: ['Na reacts vigorously; Mg reacts very slowly with cold water but faster with steam', 'Both react equally', 'Mg reacts faster than Na', 'Neither reacts with water'], answer: 0 },
      { q: 'What is a bidentate ligand? Give an example.', options: ['A ligand that forms two coordinate bonds, e.g. ethane-1,2-diamine', 'A ligand that forms one bond, e.g. water', 'A ligand with two atoms', 'A negatively charged ligand'], answer: 0 },
      { q: 'SiCl4 reacts with water but CCl4 does not. Why?', options: ['Si has available 3d orbitals to accept lone pairs from water; C does not', 'CCl4 has stronger bonds', 'SiCl4 is ionic', 'CCl4 is more polar'], answer: 0 },
      { q: 'What colour change occurs when iron(II) is oxidised to iron(III) in solution?', options: ['Pale green to yellow/orange', 'Yellow to green', 'Brown to green', 'Blue to green'], answer: 0 }
    ],
    red: [
      { q: 'Why does [Cu(NH3)4(H2O)2]^2+ form rather than [Cu(NH3)6]^2+ when excess ammonia is added to [Cu(H2O)6]^2+?', options: ['Copper can only bond to 4 nitrogen atoms','NH3 is a weaker ligand than water','The complex would be unstable with 6 NH3','Steric effects prevent full substitution; NH3 is slightly larger than H2O'], answer: 3 },
      { q: 'Cis-platin [PtCl2(NH3)2] is used as an anticancer drug but trans-platin is not effective. Why does geometry matter?', options: ['Cis form can bind to adjacent bases on DNA causing cross-linking; trans form cannot','Trans form is more soluble','Cis form is colourless','Trans form decomposes in the body'], answer: 0 },
      { q: 'The compound [Co(en)2Cl2]+ shows optical isomerism. What structural feature allows this?', options: ['The complex is octahedral with no plane of symmetry in the cis form','The en ligands are identical','It is tetrahedral','It has only monodentate ligands'], answer: 0 },
      { q: 'Why does the addition of chloride ions to [Co(H2O)6]^2+ produce a colour change from pink to blue?', options: ['Cl^- causes a ligand substitution changing octahedral to tetrahedral, altering d-orbital splitting','Chloride is reduced','Cobalt is oxidised','Water molecules are coloured'], answer: 0 },
      { q: 'In a titration with acidified potassium manganate(VII), why must the solution be acidified with sulfuric acid and not hydrochloric acid?', options: ['HCl is too dilute','HCl would reduce the MnO4^-','H2SO4 is a stronger acid','Cl^- ions would be oxidised by MnO4^-, giving a false end point'], answer: 3 },
      { q: 'Explain why the reaction of aluminium chloride with water is vigorous and produces fumes, while sodium chloride simply dissolves.', options: ['AlCl3 is covalent and undergoes hydrolysis releasing HCl; NaCl is ionic and dissociates','NaCl is covalent','AlCl3 has ionic bonding that breaks','Both react the same way'], answer: 0 },
      { q: 'Haemoglobin contains Fe^2+ in a complex. Carbon monoxide poisoning occurs because CO binds to Fe^2+ more strongly than O2. Why?', options: ['CO oxidises Fe^2+ to Fe^3+','CO breaks down haemoglobin','CO is a stronger ligand than O2 forming a more stable complex, preventing oxygen transport','CO is more soluble in blood'], answer: 2 },
      { q: 'The theoretical lattice energy of AgCl differs significantly from its Born-Haber value. What does this suggest about the bonding?', options: ['AgCl has significant covalent character; Ag+ polarises Cl^-','AgCl is purely ionic','The Born-Haber calculation is wrong','AgCl has metallic character'], answer: 0 },
      { q: 'Why can transition metals form complexes with a wide variety of coordination numbers (2, 4, 6)?', options: ['They have only one oxidation state','The energy of 3d, 4s, and 4p orbitals are close enough to form various hybrid orbitals','Transition metals are very large atoms','Ligands are all the same size'], answer: 1 },
      { q: 'In the chromium(III)-EDTA complex, the stability constant is very large. Explain why chelate complexes are more stable than those with monodentate ligands.', options: ['The enthalpy change is more negative','The chelate effect: entropy increases as one polydentate ligand displaces several monodentate ligands','Monodentate ligands are weaker','EDTA forms stronger individual bonds'], answer: 1 }
    ]
  },

  'O1': {
    name: 'Organic Chemistry I',
    green: [
      { q: 'What is the general formula of alkanes?', options: ['CnH2n+2', 'CnH2n', 'CnH2n-2', 'CnHn'], answer: 0 },
      { q: 'What type of reaction do alkanes undergo with halogens in UV light?', options: ['Free radical substitution', 'Electrophilic addition', 'Nucleophilic substitution', 'Elimination'], answer: 0 },
      { q: 'What is the general formula of alkenes?', options: ['CnH2n', 'CnH2n+2', 'CnH2n-2', 'CnHn+2'], answer: 0 },
      { q: 'What type of reaction do alkenes undergo with bromine?', options: ['Electrophilic addition', 'Free radical substitution', 'Nucleophilic addition', 'Condensation'], answer: 0 },
      { q: 'What is a halogenoalkane?', options: ['An alkane with one or more hydrogen atoms replaced by a halogen', 'An alkene with a halogen', 'A carboxylic acid with a halogen', 'An aromatic compound with a halogen'], answer: 0 },
      { q: 'What functional group do alcohols contain?', options: ['-OH (hydroxyl)', '-COOH', '-CHO', '-NH2'], answer: 0 },
      { q: 'What is a primary alcohol?', options: ['The OH is bonded to a carbon attached to one other carbon', 'The OH is bonded to a carbon with two other carbons', 'The OH is bonded to a carbon with three other carbons', 'Any alcohol'], answer: 0 },
      { q: 'What is the test for an alkene?', options: ['Decolourises bromine water', 'Burns with a smoky flame', 'Turns litmus red', 'Dissolves in water'], answer: 0 },
      { q: 'What does IR spectroscopy detect?', options: ['Functional groups via bond vibrations', 'Mass of molecules', 'Number of hydrogen environments', 'Colour of compounds'], answer: 0 },
      { q: 'What is a homologous series?', options: ['A series of compounds with the same functional group differing by CH2', 'A group of isomers', 'Compounds with the same formula', 'A set of allotropes'], answer: 0 },
      { q: 'Combustion of alkanes produces what in excess oxygen?', options: ['CO2 and H2O', 'CO and H2O', 'C and H2O', 'CO2 and H2'], answer: 0 },
      { q: 'What is the name of CH3CH2OH?', options: ['Ethanol', 'Methanol', 'Propanol', 'Butanol'], answer: 0 },
      { q: 'What type of bond is C=C in alkenes?', options: ['One sigma and one pi bond', 'Two sigma bonds', 'Two pi bonds', 'One ionic and one covalent bond'], answer: 0 },
      { q: 'What reagent is used to oxidise a primary alcohol to an aldehyde?', options: ['Acidified potassium dichromate (distill product)', 'Concentrated sulfuric acid', 'Sodium hydroxide', 'Bromine water'], answer: 0 },
      { q: 'Structural isomers have the same what?', options: ['Molecular formula but different structural formula', 'Structural formula', 'Functional group', 'Name'], answer: 0 },
      { q: 'What is the IUPAC name of CH3CHBrCH3?', options: ['2-bromopropane', '1-bromopropane', 'Bromopropane', '3-bromopropane'], answer: 0 },
      { q: 'In mass spectrometry, what causes the molecular ion peak?', options: ['Removal of one electron from the molecule', 'Breaking bonds in the molecule', 'Addition of a proton', 'Removal of a neutron'], answer: 0 },
      { q: 'What is the product of the reaction of ethene with HBr?', options: ['Bromoethane', 'Ethanol', '1,2-dibromoethane', 'Ethane'], answer: 0 },
      { q: 'What is the purpose of fractional distillation of crude oil?', options: ['Separate hydrocarbons by boiling point', 'Crack long-chain hydrocarbons', 'Polymerise alkenes', 'Remove sulfur'], answer: 0 },
      { q: 'What type of reaction is the formation of poly(ethene) from ethene?', options: ['Addition polymerisation', 'Condensation polymerisation', 'Substitution', 'Elimination'], answer: 0 }
    ],
    amber: [
      { q: 'In free radical substitution of methane with chlorine, what is the propagation step?', options: ['CH4 + Cl* -> CH3* + HCl, then CH3* + Cl2 -> CH3Cl + Cl*', 'Cl2 -> 2Cl*', 'CH3* + Cl* -> CH3Cl', 'CH4 -> CH3* + H*'], answer: 0 },
      { q: 'Markownikoff\'s rule predicts that HBr added to propene forms mainly which product?', options: ['2-bromopropane', '1-bromopropane', '1,2-dibromopropane', 'Propane'], answer: 0 },
      { q: 'Why do tertiary halogenoalkanes undergo nucleophilic substitution by an SN1 mechanism?', options: ['The tertiary carbocation intermediate is stabilised by three alkyl groups', 'The carbon is less sterically hindered', 'Primary halogenoalkanes are more stable', 'SN2 is impossible for all halogenoalkanes'], answer: 0 },
      { q: 'What is the product when propan-1-ol is heated under reflux with acidified K2Cr2O7?', options: ['Propanoic acid', 'Propanal', 'Propanone', 'No reaction'], answer: 0 },
      { q: 'Which type of alcohol cannot be oxidised by acidified dichromate?', options: ['Tertiary', 'Primary', 'Secondary', 'All alcohols can be oxidised'], answer: 0 },
      { q: 'E/Z isomerism requires what structural features?', options: ['Restricted rotation (C=C) and two different groups on each carbon of the double bond', 'A chiral centre', 'A ring structure only', 'Single bonds only'], answer: 0 },
      { q: 'What reagent converts a halogenoalkane to an alcohol?', options: ['Aqueous NaOH (reflux)', 'Concentrated H2SO4', 'KMnO4', 'HBr'], answer: 0 },
      { q: 'What reagent and conditions convert a halogenoalkane to an amine?', options: ['Excess ethanolic ammonia, heat in sealed tube', 'Aqueous NaOH', 'Concentrated H2SO4', 'LiAlH4'], answer: 0 },
      { q: 'The broad O-H absorption in an IR spectrum around 2500-3300 cm^-1 indicates what?', options: ['Carboxylic acid', 'Alcohol', 'Aldehyde', 'Amine'], answer: 0 },
      { q: 'In the dehydration of ethanol, what reagent and conditions are used?', options: ['Concentrated H2SO4 or Al2O3, heat', 'NaOH, reflux', 'K2Cr2O7, reflux', 'Br2, room temperature'], answer: 0 },
      { q: 'Why does 1-bromobutane react faster with NaOH than 1-chlorobutane?', options: ['C-Br bond is weaker than C-Cl bond', 'Bromine is more electronegative', 'Chlorine is a better leaving group', 'C-Br bond is shorter'], answer: 0 },
      { q: 'Tollens\' reagent (ammoniacal silver nitrate) gives a silver mirror with which functional group?', options: ['Aldehyde', 'Ketone', 'Carboxylic acid', 'Alcohol'], answer: 0 },
      { q: 'What is the mechanism for the reaction of ethene with HBr?', options: ['Electrophilic addition', 'Nucleophilic addition', 'Free radical addition', 'SN2'], answer: 0 },
      { q: 'What product forms when propan-2-ol is oxidised?', options: ['Propanone', 'Propanal', 'Propanoic acid', 'No reaction'], answer: 0 },
      { q: 'In the halogenation of alkanes, why are multiple substitution products formed?', options: ['Further substitution of hydrogen atoms on the product continues', 'Only one product forms', 'The reaction stops after one substitution', 'Halogens do not react with alkanes'], answer: 0 },
      { q: 'What is the test to distinguish between a primary and tertiary halogenoalkane?', options: ['Rate of reaction with aqueous silver nitrate (AgNO3/ethanol) - tertiary reacts fastest', 'Flame test', 'Bromine water test', 'pH measurement'], answer: 0 },
      { q: 'Ethanol can be produced by fermentation. What conditions are required?', options: ['Yeast, warm temperature (30-40 degrees C), anaerobic conditions', 'High pressure and a catalyst', 'UV light', 'Strong acid catalyst'], answer: 0 },
      { q: 'What is the product of hydration of propene using steam and an acid catalyst?', options: ['Propan-2-ol (major product by Markownikoff\'s rule)', 'Propan-1-ol', 'Propanoic acid', 'Propanal'], answer: 0 },
      { q: 'Why does an elimination reaction occur with ethanolic NaOH but substitution with aqueous NaOH?', options: ['In ethanol, OH^- acts as a base; in water, it acts as a nucleophile', 'Ethanol is a stronger nucleophile', 'Water promotes elimination', 'There is no difference'], answer: 0 },
      { q: 'What is the purpose of cracking in the oil industry?', options: ['Break long-chain alkanes into shorter, more useful hydrocarbons and alkenes', 'Combine small molecules', 'Remove sulfur impurities', 'Separate crude oil fractions'], answer: 0 }
    ],
    red: [
      { q: 'Draw the mechanism for the reaction of 2-bromopropane with OH^- via SN1. Why is the product racemic?', options: ['The planar carbocation can be attacked equally from either side','The halogen blocks one side','Only one enantiomer forms','SN1 always gives one product'], answer: 0 },
      { q: 'Explain why the elimination product is favoured over substitution when a tertiary halogenoalkane reacts with a strong base at high temperature.', options: ['Substitution is always favoured','The base is consumed before substitution can occur','Elimination never occurs with tertiary substrates','Steric hindrance around the tertiary carbon hinders nucleophilic attack; high temp favours elimination kinetically'], answer: 3 },
      { q: 'In the free radical substitution of methane, why is a mixture of CH3Cl, CH2Cl2, CHCl3, and CCl4 obtained?', options: ['Termination prevents further substitution','The reaction is highly selective','Only CH3Cl forms','Each chlorinated product can undergo further substitution; statistical control is not possible'], answer: 3 },
      { q: 'Compare the environmental impact of producing ethanol by fermentation versus hydration of ethene.', options: ['Both have identical environmental impact','Fermentation is carbon neutral and uses renewable resources; hydration uses non-renewable fossil fuels','Hydration is more sustainable','Fermentation produces more CO2 overall'], answer: 1 },
      { q: 'An unknown compound C4H8O2 shows a broad absorption at 2500-3300 cm^-1 and a peak at 1710 cm^-1 in its IR spectrum. It reacts with Na2CO3 to produce CO2. Suggest its identity.', options: ['Butanal (aldehyde)','Butanone (ketone)','Butanoic acid (carboxylic acid)','Ethyl ethanoate (ester)'], answer: 2 },
      { q: 'Why does the C-H bond in an aldehyde absorb at a different wavenumber in IR compared to alkane C-H?', options: ['The carbonyl group affects the electron density of the adjacent C-H bond, changing its vibrational frequency','They absorb at the same frequency','Aldehydes have no C-H bonds','IR cannot distinguish between them'], answer: 0 },
      { q: 'Explain why the rate of hydrolysis of halogenoalkanes follows the order: C-I > C-Br > C-Cl > C-F.', options: ['All react at the same rate','C-F is the weakest bond','Electronegativity determines rate','Bond enthalpy decreases from C-F to C-I so C-I is broken most easily'], answer: 3 },
      { q: 'Predict the major product of the reaction of but-1-ene with HBr and explain using Markownikoff\'s rule and carbocation stability.', options: ['1,2-dibromobutane; addition occurs twice','Butane; reduction occurs','2-bromobutane; the secondary carbocation intermediate is more stable than primary','1-bromobutane; the primary carbocation is more stable'], answer: 2 },
      { q: 'Why does the mass spectrum of chloroethane show peaks at m/z = 64, 66, 49, 29, and 27?', options: ['All peaks represent the same fragment','The isotope pattern is not relevant','There is only one peak in the spectrum','64 and 66 are M+ (35Cl and 37Cl); 49 is CH2Cl+; 29 is CHO+/C2H5+; 27 is C2H3+'], answer: 3 },
      { q: 'Compare SN1 and SN2 mechanisms for halogenoalkanes, explaining how substrate type, nucleophile strength, and solvent polarity affect which pathway is favoured.', options: ['SN2 favoured by primary substrates, strong nucleophiles, polar aprotic solvents; SN1 by tertiary substrates, weak nucleophiles, polar protic solvents','SN1 is always favoured','SN2 is always faster','Solvent has no effect on mechanism'], answer: 0 }
    ]
  },

  'O2': {
    name: 'Organic Chemistry II',
    green: [
      { q: 'What functional group do carboxylic acids contain?', options: ['-COOH', '-CHO', '-OH', '-CO-'], answer: 0 },
      { q: 'What is the general structure of an ester?', options: ['RCOOR\'', 'RCOOH', 'RCHO', 'RCOR\''], answer: 0 },
      { q: 'What is the functional group in an aldehyde?', options: ['-CHO', '-COOH', '-CO-', '-OH'], answer: 0 },
      { q: 'What is the functional group in a ketone?', options: ['-CO- (carbonyl between two carbons)', '-CHO', '-COOH', '-OH'], answer: 0 },
      { q: 'Benzene has the molecular formula C6H6. What is its structure?', options: ['A planar ring with delocalised electrons', 'Three alternating double bonds (Kekule)', 'A chain of 6 carbons', 'A tetrahedral arrangement'], answer: 0 },
      { q: 'What is an amine?', options: ['A compound derived from ammonia where H is replaced by an alkyl/aryl group', 'A carboxylic acid derivative', 'An alcohol with nitrogen', 'A type of ketone'], answer: 0 },
      { q: 'What type of polymerisation produces a condensation polymer?', options: ['Condensation polymerisation (with loss of small molecule)', 'Addition polymerisation', 'Free radical polymerisation', 'Ring-opening polymerisation'], answer: 0 },
      { q: 'NMR spectroscopy is used to determine what?', options: ['The number and environment of hydrogen (or carbon) atoms', 'The mass of a molecule', 'Functional groups', 'Colour of a compound'], answer: 0 },
      { q: 'What does the term "aromatic" refer to in chemistry?', options: ['Compounds containing a benzene ring', 'Compounds with a pleasant smell', 'Compounds with double bonds', 'Compounds that are volatile'], answer: 0 },
      { q: 'What is a peptide bond?', options: ['A bond formed between amino acids by condensation', 'A bond in DNA only', 'An ionic bond in proteins', 'A hydrogen bond'], answer: 0 },
      { q: 'What small molecule is lost during ester formation?', options: ['Water', 'Carbon dioxide', 'Hydrogen', 'Ammonia'], answer: 0 },
      { q: 'Acyl chlorides have which functional group?', options: ['-COCl', '-COOH', '-CHO', '-Cl'], answer: 0 },
      { q: 'What is the product of reducing a ketone?', options: ['Secondary alcohol', 'Primary alcohol', 'Aldehyde', 'Carboxylic acid'], answer: 0 },
      { q: 'What reagent reduces a carbonyl compound to an alcohol?', options: ['NaBH4 (sodium borohydride)', 'K2Cr2O7', 'KMnO4', 'H2SO4'], answer: 0 },
      { q: 'What type of reaction does benzene typically undergo?', options: ['Electrophilic substitution', 'Electrophilic addition', 'Nucleophilic substitution', 'Free radical addition'], answer: 0 },
      { q: 'In 1H NMR, what does chemical shift (delta) depend on?', options: ['The electron environment of the hydrogen atom', 'The mass of the atom', 'The number of bonds in the molecule', 'The temperature of the sample'], answer: 0 },
      { q: 'What is a polyamide?', options: ['A polymer formed by condensation of dicarboxylic acids and diamines', 'A polymer of alkenes', 'A polymer of esters', 'A polymer of ethers'], answer: 0 },
      { q: 'Which reagent is used to test for a carbonyl group (aldehyde or ketone)?', options: ['2,4-dinitrophenylhydrazine (2,4-DNPH)', 'Bromine water', 'Silver nitrate', 'Sodium hydroxide'], answer: 0 },
      { q: 'What is the monomer of nylon 6,6?', options: ['Hexanedioic acid and 1,6-diaminohexane', 'Ethene', 'Styrene', 'Caprolactam only'], answer: 0 },
      { q: 'What does TMS stand for in NMR spectroscopy?', options: ['Tetramethylsilane', 'Trimethylsulfide', 'Tetraethylsilane', 'Trimethylsilane'], answer: 0 }
    ],
    amber: [
      { q: 'Why does benzene undergo electrophilic substitution rather than addition?', options: ['To preserve the delocalised pi system and its stabilisation energy', 'Benzene cannot undergo addition', 'Substitution is always faster', 'Benzene has no pi electrons'], answer: 0 },
      { q: 'What are the conditions for the nitration of benzene?', options: ['Concentrated HNO3 and H2SO4 at 50 degrees C', 'Dilute HNO3 only', 'HNO3 and AlCl3', 'HNO3 and UV light'], answer: 0 },
      { q: 'What is the electrophile in the nitration of benzene?', options: ['NO2+ (nitronium ion)', 'NO3^-', 'HNO3', 'H+'], answer: 0 },
      { q: 'The Friedel-Crafts acylation of benzene requires what catalyst?', options: ['AlCl3 (Lewis acid catalyst)', 'H2SO4', 'Ni', 'Pt'], answer: 0 },
      { q: 'What is the product when ethanoyl chloride reacts with water?', options: ['Ethanoic acid and HCl', 'Ethanol and HCl', 'Ethyl ethanoate and HCl', 'Ethane and HCl'], answer: 0 },
      { q: 'How can you distinguish between an aldehyde and a ketone?', options: ['Tollens\' reagent or Fehling\'s solution — aldehyde gives positive result, ketone does not', 'Both react with 2,4-DNPH', 'Ketones are more reactive', 'IR spectroscopy cannot distinguish them'], answer: 0 },
      { q: 'What is an optical isomer?', options: ['Non-superimposable mirror image molecules (enantiomers)', 'Molecules with different functional groups', 'Cis-trans isomers', 'Molecules with different molecular formulae'], answer: 0 },
      { q: 'A chiral centre requires what?', options: ['A carbon bonded to four different groups', 'A carbon with a double bond', 'A nitrogen atom', 'Two identical substituents'], answer: 0 },
      { q: 'In 1H NMR, what does the splitting pattern (n+1 rule) tell you?', options: ['The number of hydrogen atoms on adjacent carbons', 'The chemical shift', 'The molecular formula', 'The type of functional group'], answer: 0 },
      { q: 'What is the mechanism for nucleophilic addition to a carbonyl group?', options: ['Nucleophile attacks the delta+ carbon, followed by protonation of the oxygen', 'Electrophile attacks the oxygen', 'Free radical attacks the carbon', 'Elimination of water'], answer: 0 },
      { q: 'Phenol is more reactive than benzene towards electrophilic substitution. Why?', options: ['The lone pair on oxygen is donated into the ring, increasing electron density', 'Phenol has fewer electrons', 'Benzene has more electron density', 'Phenol is less stable'], answer: 0 },
      { q: 'What is the product of the reaction between an acyl chloride and an amine?', options: ['An amide and HCl', 'An ester and HCl', 'A carboxylic acid and NH3', 'An alcohol and NH4Cl'], answer: 0 },
      { q: 'In 13C NMR, what does the number of peaks tell you?', options: ['The number of different carbon environments', 'The number of carbon atoms', 'The molecular mass', 'The number of bonds'], answer: 0 },
      { q: 'What is the hydrolysis product of a polyester in acidic conditions?', options: ['Dicarboxylic acid and diol', 'Amino acids', 'Alkene monomers', 'Diamine and diacid'], answer: 0 },
      { q: 'Amines act as bases. Why?', options: ['The lone pair on nitrogen can accept a proton', 'They donate protons', 'They are neutral', 'They have no lone pairs'], answer: 0 },
      { q: 'What is the product of Friedel-Crafts acylation of benzene with ethanoyl chloride?', options: ['Phenylethanone', 'Ethylbenzene', 'Chlorobenzene', 'Benzaldehyde'], answer: 0 },
      { q: 'How does a racemic mixture affect plane-polarised light?', options: ['No overall rotation — equal and opposite rotations cancel', 'Rotates it clockwise', 'Rotates it anticlockwise', 'Absorbs all light'], answer: 0 },
      { q: 'What is the difference between addition and condensation polymerisation?', options: ['Addition: no by-product, unsaturated monomers. Condensation: small molecule lost, bifunctional monomers', 'There is no difference', 'Addition always uses heat', 'Condensation uses catalysts only'], answer: 0 },
      { q: 'What happens when an amino acid is in a zwitterionic form?', options: ['It has both a positive NH3+ and negative COO^- group', 'It is fully protonated', 'It is fully deprotonated', 'It has no charge at all'], answer: 0 },
      { q: 'What is the approximate chemical shift of an -OH proton bonded to an aromatic ring in 1H NMR?', options: ['4-12 ppm (variable, often broad)', '0-1 ppm', '9-10 ppm (only for CHO)', '1-2 ppm'], answer: 0 }
    ],
    red: [
      { q: 'Explain why benzene\'s enthalpy of hydrogenation is less exothermic than three times the enthalpy of hydrogenation of cyclohexene.', options: ['Hydrogenation does not occur for benzene','Delocalisation energy stabilises benzene so less energy is released than expected for three isolated double bonds','Cyclohexene is more stable','Benzene has three true double bonds'], answer: 1 },
      { q: 'In the nitration of methylbenzene, the methyl group directs substitution to the 2- and 4- positions. Explain why.', options: ['The methyl group is electron-donating by induction, increasing electron density at the 2,4 positions','Substitution occurs randomly','The 3-position is more electron-rich','Methyl group withdraws electrons'], answer: 0 },
      { q: 'A compound C8H8O2 shows the following 1H NMR: singlet at 2.3 ppm (3H), singlet at 3.9 ppm (3H), two doublets at 7.0 and 7.9 ppm (2H each). Suggest a structure.', options: ['Methyl 4-methylbenzoate (para-substituted aromatic ester)','4-methoxyacetophenone','Phenylacetic acid methyl ester','2-methylbenzoic acid methyl ester'], answer: 0 },
      { q: 'Why is the Friedel-Crafts acylation preferred over alkylation for introducing a side chain onto benzene?', options: ['Alkylation gives a single product','Alkylation is faster','Acylation avoids polysubstitution (the product is deactivated) and carbocation rearrangements','Acylation requires no catalyst'], answer: 2 },
      { q: 'Explain how you would synthesise the painkiller paracetamol (4-hydroxyacetanilide) from 4-aminophenol.', options: ['React 4-aminophenol with ethanoyl chloride (or ethanoic anhydride) to form the amide bond','Nitrate benzene then reduce','Oxidise 4-aminophenol','React phenol with ammonia'], answer: 0 },
      { q: 'Biodegradable polyesters like PLA break down by hydrolysis. Why are addition polymers like polyethene not biodegradable?', options: ['Addition polymers dissolve in water','All polymers are biodegradable','Addition polymers have no hydrolysable functional groups in the backbone; only C-C bonds','Polyethene contains ester links'], answer: 2 },
      { q: 'A drug molecule has a chiral centre. One enantiomer is therapeutic and the other causes side effects. Explain how this is possible.', options: ['Enantiomers interact differently with chiral receptor sites in the body due to their 3D shape','Both enantiomers have the same effect','Chirality does not affect biological activity','Only one enantiomer exists in nature'], answer: 0 },
      { q: 'Explain the retrosynthetic approach to making 1-phenylethanone from benzene, identifying the reagents for each step.', options: ['Friedel-Crafts acylation: benzene + CH3COCl with AlCl3 catalyst in one step','Benzene + ethanol + H2SO4','Benzene + ethanal + NaBH4','Benzene + ethanoic acid directly'], answer: 0 },
      { q: 'Interpret the following 13C NMR: 4 peaks at approximately 14, 22, 34, and 178 ppm for a compound with formula C4H8O2.', options: ['Butanoic acid — 3 CH2/CH3 carbons at low shift and COOH at 178 ppm','Methyl propanoate','Ethyl ethanoate','Butanal'], answer: 0 },
      { q: 'Explain why 2,4,6-trinitrophenol (picric acid) is a stronger acid than phenol, despite both containing an -OH group on a benzene ring.', options: ['Picric acid has more -OH groups','Three nitro groups are electron-withdrawing, stabilising the conjugate base by delocalisation of the negative charge','Both have the same acidity','Phenol has electron-withdrawing groups'], answer: 1 }
    ]
  }

};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { CHEMISTRY_AQA_QUESTIONS };
}
