/*
 * OCR A-Level Economics (H460) — MCQ Diagnostic Question Bank
 * 8 granular topics: 1.1-1.4 (Microeconomics), 2.1-2.4 (Macroeconomics)
 * Per topic: 20 green (recall), 20 amber (application/analysis), 10 red (evaluation/synoptic)
 * answer: 0-based index of correct option.
 */
const ECONOMICS_OCR_QUESTIONS = {
  '1.1': {
    name: 'Economic Problem & Market Systems',
    green: [
      { q: 'What is the basic economic problem?', options: ['Inflation', 'Scarcity', 'Unemployment', 'Poverty'], answer: 1 },
      { q: 'Which of the following is a factor of production?', options: ['Money', 'Shares', 'Land', 'Profit'], answer: 2 },
      { q: 'Opportunity cost is best defined as:', options: ['The monetary cost of a decision', 'The next best alternative forgone', 'The total cost of production', 'The price paid by consumers'], answer: 1 },
      { q: 'A production possibility frontier (PPF) shows:', options: ['The maximum output with given resources', 'The minimum cost of production', 'The equilibrium price', 'Consumer preferences'], answer: 0 },
      { q: 'Which type of economy relies on the price mechanism to allocate resources?', options: ['Command economy', 'Mixed economy', 'Free market economy', 'Traditional economy'], answer: 2 },
      { q: 'A movement along the demand curve is caused by:', options: ['A change in income', 'A change in price of the good', 'A change in tastes', 'A change in population'], answer: 1 },
      { q: 'The law of demand states that:', options: ['As price rises, quantity demanded rises', 'As price falls, quantity demanded falls', 'As price rises, quantity demanded falls', 'Price and demand are unrelated'], answer: 2 },
      { q: 'A shift of the supply curve to the right indicates:', options: ['A decrease in supply', 'An increase in supply', 'An increase in price', 'A decrease in demand'], answer: 1 },
      { q: 'Consumer surplus is the difference between:', options: ['Price and cost', 'What consumers are willing to pay and what they actually pay', 'Revenue and cost', 'Supply and demand'], answer: 1 },
      { q: 'If price elasticity of demand (PED) equals -0.5, demand is:', options: ['Elastic', 'Inelastic', 'Unit elastic', 'Perfectly elastic'], answer: 1 },
      { q: 'What does a PED value greater than 1 (in absolute terms) indicate?', options: ['Inelastic demand', 'Elastic demand', 'Unit elastic demand', 'Perfectly inelastic demand'], answer: 1 },
      { q: 'Cross elasticity of demand (XED) between substitutes is:', options: ['Negative', 'Positive', 'Zero', 'Infinite'], answer: 1 },
      { q: 'Income elasticity of demand (YED) for an inferior good is:', options: ['Positive', 'Negative', 'Zero', 'Greater than 1'], answer: 1 },
      { q: 'Producer surplus is:', options: ['The difference between price received and the minimum price a firm is willing to accept', 'Total revenue minus variable costs', 'Profit earned by firms', 'The area above the supply curve'], answer: 0 },
      { q: 'Which of these would shift the demand curve for cars to the right?', options: ['An increase in the price of cars', 'A decrease in consumer income', 'A fall in the price of petrol', 'An increase in interest rates'], answer: 2 },
      { q: 'The equilibrium price is where:', options: ['Demand is at its highest', 'Supply is at its lowest', 'Quantity demanded equals quantity supplied', 'Government sets the price'], answer: 2 },
      { q: 'Price elasticity of supply (PES) is likely to be higher when:', options: ['Firms have excess capacity', 'Raw materials are scarce', 'Production takes a long time', 'Firms are at full capacity'], answer: 0 },
      { q: 'A normal good has a YED that is:', options: ['Negative', 'Zero', 'Positive', 'Undefined'], answer: 2 },
      { q: 'The price mechanism performs which three functions?', options: ['Rationing, incentive, signalling', 'Production, distribution, consumption', 'Demand, supply, equilibrium', 'Saving, investment, growth'], answer: 0 },
      { q: 'If supply is perfectly inelastic, the supply curve is:', options: ['Horizontal', 'Vertical', 'Upward sloping', 'Downward sloping'], answer: 1 }
    ],
    amber: [
      { q: 'A government imposes a minimum price above equilibrium in an agricultural market. What is the most likely outcome?', options: ['Shortage', 'Surplus', 'No change in quantity', 'Increased demand'], answer: 1 },
      { q: 'If the XED between goods A and B is -1.5, the goods are likely to be:', options: ['Substitutes', 'Complements', 'Unrelated', 'Inferior goods'], answer: 1 },
      { q: 'A firm produces luxury handbags with YED of +2.5. A recession reduces national income by 5%. What happens to quantity demanded?', options: ['Falls by 2.5%', 'Falls by 12.5%', 'Rises by 12.5%', 'Falls by 5%'], answer: 1 },
      { q: 'When a per-unit tax is imposed, the burden falls more on consumers when:', options: ['Demand is elastic', 'Supply is elastic', 'Demand is inelastic', 'Supply is inelastic'], answer: 2 },
      { q: 'A PPF bowed outward from the origin indicates:', options: ['Constant opportunity cost', 'Increasing opportunity cost', 'Decreasing opportunity cost', 'Zero opportunity cost'], answer: 1 },
      { q: 'If PED for cigarettes is -0.3, a 20% price increase would reduce quantity demanded by:', options: ['6%', '3%', '20%', '60%'], answer: 0 },
      { q: 'A subsidy granted to producers will:', options: ['Shift supply left', 'Shift supply right', 'Shift demand right', 'Shift demand left'], answer: 1 },
      { q: 'In a market where demand is perfectly elastic, the incidence of an indirect tax falls entirely on:', options: ['Consumers', 'Producers', 'Government', 'Both equally'], answer: 1 },
      { q: 'Which factor would make PES more elastic in the short run?', options: ['High spare capacity', 'Long production time', 'Highly specialised labour', 'Limited raw materials'], answer: 0 },
      { q: 'A price ceiling below equilibrium causes:', options: ['Excess supply', 'Excess demand', 'Market clearing', 'Reduced consumer surplus'], answer: 1 },
      { q: 'The deadweight loss from an indirect tax is greater when:', options: ['Both demand and supply are inelastic', 'Both demand and supply are elastic', 'Only supply is elastic', 'The tax rate is low'], answer: 1 },
      { q: 'A firm faces PED of -2 and is currently maximising revenue. It should:', options: ['Raise price', 'Lower price', 'Keep price unchanged', 'Increase output'], answer: 2 },
      { q: 'Composite demand for oil means that:', options: ['Oil has many substitutes', 'Oil is demanded for multiple uses', 'Oil supply is limited', 'Oil demand is elastic'], answer: 1 },
      { q: 'If the government removes a subsidy on renewable energy, what happens to the market for solar panels?', options: ['Supply shifts left, price rises', 'Supply shifts right, price falls', 'Demand shifts left, price falls', 'Demand shifts right, price rises'], answer: 0 },
      { q: 'Joint supply means that:', options: ['Two goods are produced together', 'Two goods are consumed together', 'Two firms merge', 'Two goods are substitutes'], answer: 0 },
      { q: 'A positive externality in consumption leads to:', options: ['Overproduction relative to social optimum', 'Underproduction relative to social optimum', 'Allocative efficiency', 'Productive efficiency'], answer: 1 },
      { q: 'Total revenue increases when price falls if:', options: ['PED < 1', 'PED > 1', 'PED = 1', 'PED = 0'], answer: 1 },
      { q: 'The signalling function of prices means:', options: ['Prices tell producers what consumers want', 'Prices prevent inflation', 'Prices reduce inequality', 'Prices ensure full employment'], answer: 0 },
      { q: 'Derived demand refers to:', options: ['Demand that changes with income', 'Demand for a factor because of demand for the final good', 'Demand that is perfectly elastic', 'Demand from overseas markets'], answer: 1 },
      { q: 'If a market is in disequilibrium with excess supply, the price mechanism will:', options: ['Raise price to clear the market', 'Lower price to clear the market', 'Increase supply further', 'Shift the demand curve'], answer: 1 }
    ],
    red: [
      { q: 'A government introduces a maximum price on rental housing. Which combination of effects is most likely?', options: ['Reduced supply, excess demand, potential black markets','Increased supply, lower quality, excess supply','Higher rents, increased investment, gentrification','Reduced demand, falling prices, improved quality'], answer: 0 },
      { q: 'Evaluate: "The free market always allocates resources efficiently." Which statement best challenges this?', options: ['Government intervention always improves outcomes','Consumers are always rational','Markets always achieve productive efficiency','Market failure means the price mechanism can lead to misallocation'], answer: 3 },
      { q: 'A luxury good has YED of +3.0 and PED of -1.8. During a boom with rising incomes, which pricing strategy maximises revenue?', options: ['Keep prices stable as demand will rise with incomes','Raise prices significantly as demand is inelastic','Raise prices as both elasticities support it','Cut prices to exploit elastic demand and income growth'], answer: 3 },
      { q: 'Which statement best evaluates the use of indirect taxes to correct market failure?', options: ['They have no deadweight loss','They always achieve the socially optimal output','They only work for positive externalities','They are effective but may be regressive and cause government failure'], answer: 3 },
      { q: 'In evaluating the price mechanism, which limitation is most significant for healthcare markets?', options: ['Prices may not reflect social costs and benefits due to information asymmetry','Prices always reflect true value','Healthcare has perfectly elastic demand','The market always provides the optimal quantity'], answer: 0 },
      { q: 'A developing country removes price controls on food. The most likely short-run and long-run outcomes are:', options: ['Short run: surplus; Long run: deficit','Short run: lower prices; Long run: food shortages','Short run: higher prices and hardship; Long run: increased supply and','Short run: no change; Long run: inflation'], answer: 2 },
      { q: 'Which argument most effectively evaluates the claim that opportunity cost makes all choices rational?', options: ['All consumers have perfect information','The economic problem does not exist in developed nations','Opportunity cost is always measurable','Behavioural economics shows bounded rationality and cognitive biases affect decisions'], answer: 3 },
      { q: 'A market experiences both a negative externality in production and an indirect tax. Which outcome requires the most careful evaluation?', options: ['Whether demand becomes more elastic','Whether consumer surplus rises','Whether the tax exactly corrects the externality or','Whether supply increases'], answer: 2 },
      { q: 'Evaluate the effectiveness of buffer stock schemes in agricultural markets:', options: ['They eliminate all price volatility permanently','They always stabilise prices without cost','They only work for industrial goods','They can stabilise prices but involve storage costs'], answer: 3 },
      { q: 'Which evaluation point is strongest when assessing whether the price mechanism or government planning best allocates healthcare?', options: ['Healthcare has characteristics of both market and government failure, requiring mixed approaches','The free market always provides the optimal amount of healthcare','The price mechanism ensures equity','Government planning avoids all inefficiency'], answer: 0 }
    ]
  },
  '1.2': {
    name: 'Market Failure & Government Intervention',
    green: [
      { q: 'Market failure occurs when:', options: ['Firms make losses', 'Resources are not allocated efficiently', 'Government intervenes', 'Prices are too high'], answer: 1 },
      { q: 'A public good is characterised by:', options: ['Rivalry and excludability', 'Non-rivalry and non-excludability', 'High prices', 'Government ownership'], answer: 1 },
      { q: 'A negative externality is:', options: ['A cost to the producer', 'A cost imposed on third parties', 'A benefit to society', 'A tax on goods'], answer: 1 },
      { q: 'The free rider problem is associated with:', options: ['Private goods', 'Public goods', 'Merit goods', 'Demerit goods'], answer: 1 },
      { q: 'A merit good is one that is:', options: ['Overconsumed in a free market', 'Underconsumed in a free market', 'Not produced at all', 'Only produced by government'], answer: 1 },
      { q: 'A demerit good is one that:', options: ['Has positive externalities', 'Is underconsumed', 'Has negative externalities and is overconsumed', 'Is non-rivalrous'], answer: 2 },
      { q: 'Information failure means:', options: ['The internet is unavailable', 'Economic agents lack perfect information to make rational decisions', 'Prices are incorrect', 'Markets are competitive'], answer: 1 },
      { q: 'Which is an example of a positive externality?', options: ['Factory pollution', 'Vaccination', 'Smoking', 'Traffic congestion'], answer: 1 },
      { q: 'Government failure occurs when:', options: ['Government intervention leads to a worse allocation of resources', 'Markets fail', 'Taxes are collected', 'Subsidies are given'], answer: 0 },
      { q: 'An indirect tax is used to correct:', options: ['Positive externalities', 'Negative externalities', 'Public goods', 'Income inequality'], answer: 1 },
      { q: 'A subsidy on education is justified because education is a:', options: ['Public good', 'Demerit good', 'Merit good', 'Free good'], answer: 2 },
      { q: 'Which is an example of a public good?', options: ['Healthcare', 'Street lighting', 'Education', 'Housing'], answer: 1 },
      { q: 'Asymmetric information means:', options: ['Both parties have the same information', 'One party has more information than another', 'Information is freely available', 'Markets are efficient'], answer: 1 },
      { q: 'A Pigouvian tax aims to:', options: ['Raise government revenue', 'Internalise an external cost', 'Reduce supply', 'Increase demand'], answer: 1 },
      { q: 'Property rights help solve externalities because:', options: ['They increase government spending', 'They allow bargaining to reach an efficient outcome', 'They eliminate all pollution', 'They reduce taxes'], answer: 1 },
      { q: 'Moral hazard refers to:', options: ['Consumers buying merit goods', 'People taking greater risks because they are insured', 'Firms competing fairly', 'Government providing subsidies'], answer: 1 },
      { q: 'Adverse selection occurs in:', options: ['Perfect competition', 'Insurance markets where high-risk individuals are more likely to buy cover', 'Public goods provision', 'Command economies'], answer: 1 },
      { q: 'Tradeable pollution permits aim to:', options: ['Increase pollution', 'Set a cap on total pollution and allow trading of rights', 'Eliminate all industrial output', 'Raise tax revenue'], answer: 1 },
      { q: 'Regulation is a form of:', options: ['Market-based intervention', 'Direct government intervention', 'Voluntary agreement', 'Price mechanism'], answer: 1 },
      { q: 'The social cost of production equals:', options: ['Private cost plus external cost', 'Private cost minus external cost', 'External cost only', 'Total revenue minus total cost'], answer: 0 }
    ],
    amber: [
      { q: 'A factory emits pollution affecting local residents. The socially optimal output is where:', options: ['Marginal private cost equals marginal private benefit', 'Marginal social cost equals marginal social benefit', 'Total revenue is maximised', 'Output is zero'], answer: 1 },
      { q: 'A government bans smoking in public places. This is most likely to:', options: ['Eliminate all negative externalities from smoking', 'Reduce external costs imposed on non-smokers in public spaces', 'Increase consumption of cigarettes', 'Create a black market for public smoking'], answer: 1 },
      { q: 'The introduction of congestion charging in a city is designed to:', options: ['Increase traffic flow by raising revenue', 'Internalise the external cost of congestion', 'Subsidise public transport', 'Eliminate car ownership'], answer: 1 },
      { q: 'If a merit good is provided free at the point of use, this may lead to:', options: ['Underconsumption', 'Overconsumption and excess demand', 'Productive efficiency', 'No change in consumption'], answer: 1 },
      { q: 'Government failure is more likely when:', options: ['Markets are competitive', 'Politicians have perfect information', 'There are unintended consequences and bureaucratic inefficiency', 'Externalities are absent'], answer: 2 },
      { q: 'A carbon tax set too low will:', options: ['Overcorrect the externality', 'Fail to reduce emissions to the socially optimal level', 'Eliminate all pollution', 'Have no effect on prices'], answer: 1 },
      { q: 'The Coase theorem suggests externalities can be resolved without government intervention when:', options: ['Property rights are well defined and transaction costs are low', 'There are many affected parties', 'The externality is large', 'Government sets the price'], answer: 0 },
      { q: 'Minimum unit pricing on alcohol aims to:', options: ['Increase government revenue', 'Reduce consumption by targeting the heaviest drinkers', 'Make all alcohol unaffordable', 'Subsidise moderate drinkers'], answer: 1 },
      { q: 'A sugar tax is likely to be more effective in reducing consumption if:', options: ['Demand for sugary drinks is elastic', 'Demand for sugary drinks is inelastic', 'Supply is perfectly inelastic', 'There are no substitutes'], answer: 0 },
      { q: 'State provision of healthcare may lead to government failure because:', options: ['It eliminates waiting lists', 'It may lead to over-bureaucracy and inefficient resource allocation', 'It always achieves allocative efficiency', 'It reduces information failure'], answer: 1 },
      { q: 'Quasi-public goods differ from pure public goods because:', options: ['They are fully non-rival and non-excludable', 'They may become rival or excludable at some point', 'They cannot be provided by the private sector', 'They have no externalities'], answer: 1 },
      { q: 'Behavioural economics suggests that nudges can address market failure by:', options: ['Forcing consumers to change behaviour', 'Altering the choice architecture without restricting freedom', 'Increasing taxes on all goods', 'Removing all government intervention'], answer: 1 },
      { q: 'If a subsidy on electric vehicles is too generous, this could lead to:', options: ['Underconsumption of electric vehicles', 'Government failure through overcorrection and fiscal cost', 'A reduction in positive externalities', 'Perfectly competitive markets'], answer: 1 },
      { q: 'Regulatory capture is when:', options: ['Regulations improve market efficiency', 'The regulated industry influences the regulator in its own interest', 'Consumers benefit from regulation', 'Government achieves its policy objectives'], answer: 1 },
      { q: 'The principal-agent problem in healthcare means:', options: ['Patients always choose the cheapest treatment', 'Doctors (agents) may not always act in the best interest of patients (principals)', 'Healthcare is a public good', 'There are no information failures'], answer: 1 },
      { q: 'A pollution permit system is more efficient than a flat regulation because:', options: ['It ensures zero pollution', 'It allows firms with lowest abatement costs to reduce pollution first', 'It costs the government less to administer', 'It does not require monitoring'], answer: 1 },
      { q: 'Common pool resources suffer from market failure because:', options: ['They are excludable', 'They are rivalrous but non-excludable, leading to overuse', 'They are non-rivalrous', 'The government provides them efficiently'], answer: 1 },
      { q: 'Information provision as a policy to reduce obesity is limited because:', options: ['It restricts consumer choice', 'It may not change behaviour due to bounded rationality and addiction', 'It is very expensive', 'It eliminates all market failure'], answer: 1 },
      { q: 'A subsidy on vaccinations is justified because:', options: ['Vaccinations have negative externalities', 'The free market overproduces vaccinations', 'Vaccinations generate positive externalities that are not reflected in market demand', 'Vaccinations are demerit goods'], answer: 2 },
      { q: 'The social benefit of consumption equals:', options: ['Private benefit plus external benefit', 'Private benefit minus external benefit', 'External benefit only', 'Total revenue'], answer: 0 }
    ],
    red: [
      { q: 'Evaluate: "A carbon tax is always superior to tradeable permits in reducing emissions." Which response is most balanced?', options: ['Carbon taxes are always better because they raise revenue','Neither policy has any effect on emissions','Tradeable permits always work better because they use market forces','Carbon taxes provide price certainty but not quantity certainty; permits provide quantity certainty but price volatility'], answer: 3 },
      { q: 'Which evaluation of government intervention in markets with information failure is most complete?', options: ['Government always has better information than consumers','Intervention may address information gaps but government also faces information failure','Markets always self-correct information problems','Regulation never works in practice'], answer: 1 },
      { q: 'Assess the claim: "Public goods must always be provided by the government."', options: ['The private sector always provides public goods efficiently','Public goods do not exist in reality','While the free rider problem makes private provision difficult','This is always true as the private sector never provides public goods'], answer: 2 },
      { q: 'Which statement best evaluates the use of minimum prices to reduce alcohol consumption?', options: ['They may reduce consumption but are regressive','They always work perfectly','They have no deadweight loss','They only affect wealthy consumers'], answer: 0 },
      { q: 'Evaluate the effectiveness of subsidies on renewable energy:', options: ['They only benefit producers','They never work because of government failure','They can correct market failure but may cause government failure through cost','They always achieve the socially optimal level of output'], answer: 2 },
      { q: 'To what extent does the free rider problem prevent private provision of public goods?', options: ['It has no effect on provision','It only applies to merit goods','It completely prevents any private provision in all cases','It makes private provision difficult but technological solutions, advertising revenue'], answer: 3 },
      { q: 'Which statement best evaluates whether government failure is worse than market failure?', options: ['Government failure is always worse','Market failure is always worse','It depends on the magnitude of each, the reversibility of intervention','They are always equal in magnitude'], answer: 2 },
      { q: 'Assess the use of behavioural nudges versus taxation to address obesity:', options: ['Taxes are always superior','Nudges are always superior','Neither has any effect','Nudges preserve choice but may be weak; taxes change'], answer: 3 },
      { q: 'Evaluate: "Tradeable pollution permits always achieve economic efficiency."', options: ['True, they always work perfectly','They can achieve efficiency if the cap is set correctly','They never achieve efficiency','Only taxes can achieve efficiency'], answer: 1 },
      { q: 'Which argument best evaluates the privatisation of previously state-provided merit goods?', options: ['Privatisation always improves efficiency','Privatisation may improve productive efficiency through','State provision is always superior','Merit goods cannot be privatised'], answer: 1 }
    ]
  },
  '1.3': {
    name: 'Firm Objectives, Costs & Revenue',
    green: [
      { q: 'Total revenue is calculated as:', options: ['Price minus cost', 'Price multiplied by quantity', 'Total cost plus profit', 'Average revenue times average cost'], answer: 1 },
      { q: 'Average revenue equals:', options: ['Total revenue divided by quantity sold', 'Marginal revenue', 'Total cost divided by output', 'Price minus average cost'], answer: 0 },
      { q: 'Marginal revenue is:', options: ['Total revenue divided by total output', 'The additional revenue from selling one more unit', 'Average revenue minus marginal cost', 'Revenue per worker'], answer: 1 },
      { q: 'In the short run, at least one factor of production is:', options: ['Variable', 'Fixed', 'Free', 'Increasing'], answer: 1 },
      { q: 'Fixed costs are costs that:', options: ['Change with output', 'Do not change with output in the short run', 'Are always zero', 'Only exist in the long run'], answer: 1 },
      { q: 'Variable costs:', options: ['Remain constant as output changes', 'Change as output changes', 'Include rent and salaries', 'Are zero at all output levels'], answer: 1 },
      { q: 'Profit is calculated as:', options: ['Total revenue minus total cost', 'Total revenue plus total cost', 'Average cost minus average revenue', 'Marginal revenue minus marginal cost'], answer: 0 },
      { q: 'Normal profit is:', options: ['The same as supernormal profit', 'The minimum profit needed to keep a firm in the industry', 'Zero economic profit', 'Both B and C'], answer: 3 },
      { q: 'Supernormal profit occurs when:', options: ['Total revenue equals total cost', 'Total revenue exceeds total cost (including normal profit)', 'Average cost exceeds average revenue', 'The firm is making a loss'], answer: 1 },
      { q: 'The law of diminishing marginal returns states that:', options: ['Output always falls', 'Adding more of a variable factor eventually leads to smaller increases in output', 'Fixed costs rise in the long run', 'Marginal cost always falls'], answer: 1 },
      { q: 'Economies of scale occur when:', options: ['Average costs rise as output increases', 'Average costs fall as output increases', 'Marginal costs rise', 'Total costs fall'], answer: 1 },
      { q: 'Diseconomies of scale occur when:', options: ['Average costs fall', 'Average costs rise as output increases beyond a certain point', 'Total revenue rises', 'Fixed costs fall'], answer: 1 },
      { q: 'A profit-maximising firm produces where:', options: ['MC = AC', 'MR = MC', 'AR = AC', 'TR is minimised'], answer: 1 },
      { q: 'The long run is defined as:', options: ['More than one year', 'The period when all factors are variable', 'The period when at least one factor is fixed', 'The planning horizon for investment'], answer: 1 },
      { q: 'Which is an example of an internal economy of scale?', options: ['Better transport infrastructure in the area', 'Bulk buying discounts', 'Skilled labour pool in the region', 'University research nearby'], answer: 1 },
      { q: 'Revenue maximisation occurs where:', options: ['MR = MC', 'MR = 0', 'AR = AC', 'MC = AC'], answer: 1 },
      { q: 'The shutdown point for a firm in the short run is where:', options: ['AR = ATC', 'AR < AVC', 'AR = MC', 'MR = MC'], answer: 1 },
      { q: 'Total cost equals:', options: ['Fixed cost plus variable cost', 'Fixed cost minus variable cost', 'Average cost times price', 'Marginal cost times output'], answer: 0 },
      { q: 'The marginal cost curve intersects the average cost curve at:', options: ['The maximum of the AC curve', 'The minimum of the AC curve', 'Zero output', 'Maximum output'], answer: 1 },
      { q: 'An external economy of scale is:', options: ['A cost saving within the firm from increasing output', 'A cost saving arising from the growth of the industry', 'A type of diseconomy', 'Government subsidy'], answer: 1 }
    ],
    amber: [
      { q: 'A firm currently produces where MR > MC. To maximise profit it should:', options: ['Reduce output', 'Increase output', 'Raise price', 'Shut down'], answer: 1 },
      { q: 'If a firm experiences increasing returns to scale, this means:', options: ['Doubling inputs less than doubles output', 'Doubling inputs more than doubles output', 'Average costs are rising', 'The firm has diseconomies of scale'], answer: 1 },
      { q: 'A firm pursuing sales maximisation will produce where:', options: ['MR = MC', 'AR = ATC (normal profit constraint)', 'MR = 0', 'MC is minimised'], answer: 2 },
      { q: 'Managerial economies of scale arise because:', options: ['Larger firms can employ specialist managers', 'All managers are equally productive', 'Small firms have better management', 'Management costs rise proportionally'], answer: 0 },
      { q: 'The minimum efficient scale (MES) is:', options: ['The lowest possible output', 'The smallest output at which long-run average cost is minimised', 'The maximum profitable output', 'Where marginal cost is zero'], answer: 1 },
      { q: 'A natural monopoly has cost characteristics where:', options: ['Average costs always rise', 'One firm can supply the whole market at lower average cost than two or more firms', 'There are constant returns to scale', 'Fixed costs are zero'], answer: 1 },
      { q: 'If average cost is falling, marginal cost must be:', options: ['Rising', 'Below average cost', 'Above average cost', 'Equal to average cost'], answer: 1 },
      { q: 'Satisficing behaviour means a firm:', options: ['Maximises profit at all times', 'Aims for a satisfactory level of profit rather than maximum', 'Always minimises costs', 'Shuts down in the short run'], answer: 1 },
      { q: 'Technical economies of scale include:', options: ['Bulk buying', 'Use of larger, more efficient machinery', 'Access to cheaper finance', 'Division of labour in management'], answer: 1 },
      { q: 'A firm earns normal profit when:', options: ['AR > ATC', 'AR = ATC', 'AR < ATC', 'MR > MC'], answer: 1 },
      { q: 'The principal-agent problem in firms arises because:', options: ['Owners and managers have identical objectives', 'Managers may pursue their own objectives rather than profit maximisation', 'All firms are profit maximisers', 'Shareholders have perfect information'], answer: 1 },
      { q: 'X-inefficiency occurs when:', options: ['A firm produces at minimum average cost', 'A firm produces above its minimum average cost curve due to lack of competitive pressure', 'Marginal cost equals marginal revenue', 'The firm is allocatively efficient'], answer: 1 },
      { q: 'Financial economies of scale mean that larger firms:', options: ['Pay higher interest rates', 'Can borrow at lower interest rates due to lower risk', 'Cannot access capital markets', 'Have higher variable costs'], answer: 1 },
      { q: 'In the long run, a firm making subnormal profit will:', options: ['Continue producing', 'Exit the industry', 'Expand output', 'Increase fixed costs'], answer: 1 },
      { q: 'The relationship between marginal product and marginal cost is:', options: ['Direct - they move together', 'Inverse - as MP rises, MC falls', 'Unrelated', 'Both always rise'], answer: 1 },
      { q: 'A firm with market power faces a demand curve that is:', options: ['Perfectly elastic (horizontal)', 'Downward sloping', 'Vertical', 'Upward sloping'], answer: 1 },
      { q: 'Risk-bearing economies of scale mean that:', options: ['Large firms face more risk', 'Large firms can diversify to spread risk across products and markets', 'Small firms take fewer risks', 'Risk decreases with output automatically'], answer: 1 },
      { q: 'The long-run average cost curve is an envelope of:', options: ['Marginal cost curves', 'Short-run average cost curves', 'Total cost curves', 'Revenue curves'], answer: 1 },
      { q: 'Divorce of ownership and control may lead to:', options: ['Perfect profit maximisation', 'Managerial objectives diverging from shareholder objectives', 'Lower agency costs', 'Perfect information'], answer: 1 },
      { q: 'A firm pursues profit maximisation in the long run but predatory pricing in the short run. This strategy aims to:', options: ['Maximise short-run revenue', 'Drive out competitors then raise prices', 'Achieve allocative efficiency', 'Satisfy all stakeholders'], answer: 1 }
    ],
    red: [
      { q: 'Evaluate: "Profit maximisation is the only realistic objective for firms." Which response is most balanced?', options: ['Only public companies maximise profit','True, all firms maximise profit','False, firms have multiple possible objectives including satisficing','Objectives never change over time'], answer: 2 },
      { q: 'Assess the significance of economies of scale as a barrier to entry:', options: ['They can deter entry if MES is large relative to market size','They always prevent entry','They only matter in perfect competition','They never affect entry decisions'], answer: 0 },
      { q: 'Which evaluation of the principal-agent problem is most complete?', options: ['It never occurs in practice','It can lead to X-inefficiency and non-profit-maximising behaviour','It only affects small firms','It is always resolved by performance-related pay'], answer: 1 },
      { q: 'Evaluate the claim: "Diseconomies of scale are inevitable for large firms."', options: ['True, all large firms experience them','Only occur in manufacturing','They are a risk but can be mitigated through decentralisation','They never occur in modern firms'], answer: 2 },
      { q: 'To what extent is the concept of normal profit useful in economic analysis?', options: ['It is perfectly measurable and always useful','It is a theoretical construct that helps explain long-run','It has no practical relevance','It only applies to monopolies'], answer: 1 },
      { q: 'Assess whether natural monopolies should always be nationalised:', options: ['Nationalisation may prevent abuse of monopoly power but may lead to X-inefficiency','Natural monopolies do not exist','Yes, private ownership always leads to exploitation','Privatisation always improves efficiency'], answer: 0 },
      { q: 'Evaluate: "Revenue maximisation is a more realistic short-run objective than profit maximisation."', options: ['It is never observed in practice','Revenue maximisation ignores costs entirely','It may be realistic for firms seeking market share or where','It always leads to higher long-run profits'], answer: 2 },
      { q: 'Which answer best evaluates whether the short run / long run distinction is useful?', options: ['It has no analytical value','The short run is always exactly one year','It perfectly describes reality','It provides a useful analytical framework but the boundary'], answer: 3 },
      { q: 'Assess the impact of digital technology on the cost structure of firms:', options: ['It only affects variable costs','It eliminates all economies of scale','It has no effect on costs','It tends to increase fixed costs but reduce marginal costs'], answer: 3 },
      { q: 'Evaluate whether predatory pricing is a rational long-run strategy:', options: ['It is always rational and always works','It can be rational if the predator has deep pockets and re-entry barriers exist','It never works because markets are efficient','It is only used by small firms'], answer: 1 }
    ]
  },
  '1.4': {
    name: 'Market Structures',
    green: [
      { q: 'Perfect competition is characterised by:', options: ['Few firms and differentiated products', 'Many firms, homogeneous products, and perfect information', 'One firm dominating the market', 'High barriers to entry'], answer: 1 },
      { q: 'In perfect competition, the demand curve facing an individual firm is:', options: ['Downward sloping', 'Upward sloping', 'Perfectly elastic (horizontal)', 'Perfectly inelastic (vertical)'], answer: 2 },
      { q: 'A monopoly is defined as:', options: ['A firm with more than 50% market share', 'A single seller in a market with high barriers to entry', 'Any large firm', 'A firm making supernormal profit'], answer: 1 },
      { q: 'Barriers to entry include:', options: ['Low start-up costs', 'Perfect information', 'Patents and legal barriers', 'Many substitute products'], answer: 2 },
      { q: 'Allocative efficiency occurs where:', options: ['MC = AC', 'P = MC', 'MR = MC', 'AR = ATC'], answer: 1 },
      { q: 'Productive efficiency occurs where:', options: ['P = MC', 'Production is at the minimum point of the AC curve', 'MR = MC', 'AR > AC'], answer: 1 },
      { q: 'An oligopoly is characterised by:', options: ['Many small firms', 'A few large firms dominating the market', 'Perfect competition', 'No barriers to entry'], answer: 1 },
      { q: 'Price discrimination requires:', options: ['Perfect competition', 'Market power, ability to separate markets, and different PED', 'Homogeneous products', 'No barriers to entry'], answer: 1 },
      { q: 'In monopolistic competition, firms:', options: ['Sell homogeneous products', 'Have high barriers to entry', 'Differentiate their products', 'Are price takers'], answer: 2 },
      { q: 'A contestable market is one where:', options: ['There are many firms', 'There are low barriers to entry and exit', 'The government regulates prices', 'Firms always make normal profit'], answer: 1 },
      { q: 'Supernormal profit in perfect competition is:', options: ['Sustained in the long run', 'Competed away in the long run', 'Impossible at any time', 'The normal outcome'], answer: 1 },
      { q: 'Dynamic efficiency refers to:', options: ['Producing at minimum AC', 'Innovation and investment over time improving products and processes', 'Setting P = MC', 'Short-run profit maximisation'], answer: 1 },
      { q: 'Concentration ratio measures:', options: ['The number of firms in a market', 'The market share of the largest firms', 'Profit margins', 'Barriers to entry'], answer: 1 },
      { q: 'Interdependence in oligopoly means:', options: ['Firms ignore each other', 'Each firm considers rivals\' reactions when making decisions', 'Firms always cooperate', 'There is no competition'], answer: 1 },
      { q: 'A cartel is:', options: ['A type of perfect competition', 'A formal agreement between firms to fix prices or output', 'A government regulator', 'A single firm monopoly'], answer: 1 },
      { q: 'Third-degree price discrimination involves:', options: ['Charging different prices for identical products to different consumer groups', 'Charging each consumer their maximum willingness to pay', 'Charging different prices for different quantities', 'Charging the same price to all consumers'], answer: 0 },
      { q: 'The kinked demand curve model explains:', options: ['Why oligopolists frequently change prices', 'Price rigidity in oligopoly', 'Perfect competition', 'Monopoly pricing'], answer: 1 },
      { q: 'Sunk costs are:', options: ['Variable costs', 'Costs that can be recovered on exit', 'Costs that cannot be recovered on exit', 'Future expected costs'], answer: 2 },
      { q: 'In the long run in perfect competition, firms earn:', options: ['Supernormal profit', 'Normal profit', 'Subnormal profit', 'Zero revenue'], answer: 1 },
      { q: 'Monopoly power can be measured by:', options: ['The number of employees', 'The Lerner index', 'Total output', 'Variable costs'], answer: 1 }
    ],
    amber: [
      { q: 'A perfectly competitive firm is both allocatively and productively efficient in the long run because:', options: ['P > MC and AC is minimised', 'P = MC and production occurs at minimum AC', 'MR > MC and AR > AC', 'The firm earns supernormal profit'], answer: 1 },
      { q: 'A monopolist can sustain supernormal profit in the long run because:', options: ['It is productively efficient', 'High barriers to entry prevent new firms entering', 'It produces at minimum AC', 'Demand is perfectly elastic'], answer: 1 },
      { q: 'The deadweight loss of monopoly arises because:', options: ['Price is set above MC, reducing output below the allocatively efficient level', 'The monopolist is productively efficient', 'Consumers gain surplus', 'Barriers to entry are low'], answer: 0 },
      { q: 'Game theory is used in oligopoly to analyse:', options: ['Perfect competition outcomes', 'Strategic decision-making and interdependence', 'Cost minimisation', 'Demand elasticity'], answer: 1 },
      { q: 'In a contestable market, even a monopolist may earn only normal profit because:', options: ['There are many firms', 'The threat of entry disciplines pricing behaviour', 'Government sets prices', 'Products are homogeneous'], answer: 1 },
      { q: 'First-degree price discrimination allows a monopolist to:', options: ['Charge one price to all consumers', 'Extract all consumer surplus', 'Achieve productive efficiency', 'Reduce output'], answer: 1 },
      { q: 'Non-price competition in oligopoly includes:', options: ['Price wars', 'Advertising, branding, and quality improvements', 'Reducing output', 'Setting P = MC'], answer: 1 },
      { q: 'The Competition and Markets Authority (CMA) aims to:', options: ['Increase monopoly power', 'Promote competition and prevent abuse of market power', 'Set prices for all firms', 'Nationalise industries'], answer: 1 },
      { q: 'A natural monopoly is most efficiently regulated by:', options: ['Breaking it into smaller firms', 'Setting price equal to AC to allow normal profit while preventing exploitation', 'Allowing unregulated monopoly pricing', 'Removing all barriers to entry'], answer: 1 },
      { q: 'In the Prisoner\'s Dilemma, the Nash equilibrium often results in:', options: ['The best outcome for both players', 'Both players cooperating', 'A sub-optimal outcome where both players defect', 'Maximum joint profit'], answer: 2 },
      { q: 'Limit pricing is when:', options: ['A firm charges the profit-maximising price', 'An incumbent sets price low enough to deter entry', 'Prices are set by government', 'A firm exits the market'], answer: 1 },
      { q: 'Hit-and-run competition is associated with:', options: ['Monopoly', 'Contestable markets with low sunk costs', 'Perfect competition', 'Cartels'], answer: 1 },
      { q: 'A monopoly may achieve dynamic efficiency because:', options: ['It has no incentive to innovate', 'Supernormal profits can fund research and development', 'It always produces at minimum AC', 'Competition drives innovation'], answer: 1 },
      { q: 'In monopolistic competition, long-run equilibrium results in:', options: ['Productive and allocative efficiency', 'Excess capacity and normal profit', 'Supernormal profit', 'Price equal to marginal cost'], answer: 1 },
      { q: 'The conditions for successful price discrimination are:', options: ['Perfect competition and homogeneous goods', 'Market power, market separation, and different PED between groups', 'Identical elasticities across groups', 'Zero barriers to entry'], answer: 1 },
      { q: 'Tacit collusion in oligopoly occurs when:', options: ['Firms sign a formal agreement', 'Firms independently follow a price leader without explicit agreement', 'Firms compete aggressively on price', 'The government coordinates pricing'], answer: 1 },
      { q: 'X-inefficiency is more likely under monopoly than perfect competition because:', options: ['Monopolists face intense competitive pressure', 'Lack of competition reduces the incentive to minimise costs', 'Monopolists always produce at minimum AC', 'Perfect competition has higher barriers to entry'], answer: 1 },
      { q: 'The welfare effects of third-degree price discrimination are:', options: ['Always positive for society', 'Ambiguous - consumer surplus is redistributed and output may rise or fall', 'Always negative for producers', 'Identical to perfect competition'], answer: 1 },
      { q: 'Deregulation aims to make markets more contestable by:', options: ['Increasing barriers to entry', 'Removing legal and regulatory barriers to entry', 'Nationalising firms', 'Fixing prices'], answer: 1 },
      { q: 'A firm with a monopoly in one market uses profits to subsidise low prices in another. This is called:', options: ['Predatory pricing', 'Cross-subsidisation', 'Limit pricing', 'Peak-load pricing'], answer: 1 }
    ],
    red: [
      { q: 'Evaluate: "Monopoly is always against the public interest."', options: ['False, monopoly may enable economies of scale, dynamic efficiency through R&D','True, monopoly always harms consumers','The public interest is not relevant to market structure','Monopoly is always efficient'], answer: 0 },
      { q: 'Assess the extent to which contestability theory challenges the traditional structure-conduct-performance model:', options: ['It adds nuance by showing that the threat of entry','It has no relevance to real markets','It completely replaces it','Only perfectly contestable markets exist'], answer: 0 },
      { q: 'Evaluate whether oligopoly or perfect competition delivers better outcomes for consumers:', options: ['Perfect competition ensures allocative efficiency but','Market structure does not affect consumers','Perfect competition is always better','Oligopoly is always better'], answer: 0 },
      { q: 'To what extent can competition policy effectively address the problems of oligopoly?', options: ['It never works','Oligopoly has no problems to address','It always succeeds','It can prevent overt collusion and mergers but tacit'], answer: 3 },
      { q: 'Evaluate the claim: "Price discrimination always reduces consumer welfare."', options: ['Price discrimination never occurs','True, it always harms all consumers','False, it can increase output, serve price-sensitive consumers','It only affects producers'], answer: 2 },
      { q: 'Assess whether breaking up a monopoly always improves market outcomes:', options: ['It always improves outcomes','Monopolies cannot be broken up','Breaking up may improve allocative efficiency but could','It never improves outcomes'], answer: 2 },
      { q: 'Evaluate the usefulness of the kinked demand curve model for explaining oligopoly behaviour:', options: ['It explains price rigidity but does not explain how the initial price is set','It perfectly explains all oligopoly behaviour','It only applies to monopoly','It has no validity'], answer: 0 },
      { q: 'To what extent does the profit motive ensure efficient outcomes in competitive markets?', options: ['It always ensures efficiency','It drives productive efficiency through cost minimisation but','The profit motive is irrelevant to efficiency','Only in monopoly does profit motive matter'], answer: 1 },
      { q: 'Assess whether digital markets are more or less likely to tend towards monopoly:', options: ['Network effects, data advantages, and low marginal costs create tendencies towards monopoly','Digital markets are always competitive','They always become monopolies','Market structure theory does not apply to digital markets'], answer: 0 },
      { q: 'Evaluate: "Regulation is a better response to monopoly than competition."', options: ['Regulation is always better','Competition is always better','Regulation can address natural monopoly and protect','Neither works in practice'], answer: 2 }
    ]
  },
  '2.1': {
    name: 'National & International Economy',
    green: [
      { q: 'GDP stands for:', options: ['General Domestic Product', 'Gross Domestic Product', 'Gross Demand Price', 'General Development Plan'], answer: 1 },
      { q: 'Real GDP adjusts nominal GDP for:', options: ['Population change', 'Inflation', 'Exchange rates', 'Government spending'], answer: 1 },
      { q: 'The consumer price index (CPI) measures:', options: ['GDP growth', 'Changes in the general price level', 'Unemployment', 'Balance of payments'], answer: 1 },
      { q: 'Demand-pull inflation is caused by:', options: ['Rising costs of production', 'Excess aggregate demand', 'Supply-side shocks', 'Falling wages'], answer: 1 },
      { q: 'Cost-push inflation is caused by:', options: ['Excess demand', 'Rising costs of production', 'Increased consumer spending', 'Lower interest rates'], answer: 1 },
      { q: 'The claimant count measures unemployment by:', options: ['Surveying households', 'Counting those claiming unemployment benefits', 'Measuring job vacancies', 'GDP per capita'], answer: 1 },
      { q: 'Cyclical unemployment is caused by:', options: ['Structural changes in the economy', 'A downturn in the economic cycle', 'Seasonal factors', 'Frictional factors'], answer: 1 },
      { q: 'The current account of the balance of payments includes:', options: ['Foreign direct investment', 'Trade in goods and services, investment income, and transfers', 'Capital flows', 'Gold reserves'], answer: 1 },
      { q: 'A current account deficit means:', options: ['Exports exceed imports', 'Imports and outflows exceed exports and inflows', 'GDP is falling', 'Inflation is rising'], answer: 1 },
      { q: 'The economic cycle consists of:', options: ['Only boom and recession', 'Boom, recession, slump, and recovery', 'Inflation and deflation only', 'Growth and decline'], answer: 1 },
      { q: 'GDP per capita is calculated by dividing:', options: ['GDP by population', 'GDP by land area', 'GDP by number of firms', 'GDP by government spending'], answer: 0 },
      { q: 'Frictional unemployment occurs when:', options: ['Industries decline permanently', 'Workers are between jobs', 'The economy is in recession', 'Technology replaces workers'], answer: 1 },
      { q: 'Structural unemployment is caused by:', options: ['Temporary job search', 'Long-term changes in the structure of the economy', 'Short-term demand fluctuations', 'Seasonal patterns'], answer: 1 },
      { q: 'Inflation is defined as:', options: ['A fall in the price level', 'A sustained increase in the general price level', 'Rising GDP', 'A one-off price increase'], answer: 1 },
      { q: 'The main macroeconomic objectives include:', options: ['Only low inflation', 'Economic growth, low unemployment, low inflation, and balance of payments equilibrium', 'Maximum government spending', 'Zero taxation'], answer: 1 },
      { q: 'An output gap occurs when:', options: ['Actual GDP equals potential GDP', 'Actual GDP differs from potential GDP', 'The economy is at full employment', 'There is no inflation'], answer: 1 },
      { q: 'A negative output gap indicates:', options: ['The economy is overheating', 'Actual output is below potential output', 'Inflation is high', 'Unemployment is at its natural rate'], answer: 1 },
      { q: 'The Human Development Index (HDI) measures:', options: ['Only GDP', 'Life expectancy, education, and income', 'Only literacy rates', 'Trade volumes'], answer: 1 },
      { q: 'Deflation is:', options: ['A reduction in the rate of inflation', 'A sustained fall in the general price level', 'Rising prices', 'An increase in GDP'], answer: 1 },
      { q: 'The Labour Force Survey (LFS) measures unemployment using the definition of people who are:', options: ['Claiming benefits', 'Without work, available for work, and actively seeking work (ILO definition)', 'Part-time workers', 'Economically inactive'], answer: 1 }
    ],
    amber: [
      { q: 'A positive output gap is likely to be associated with:', options: ['Rising unemployment and falling inflation', 'Demand-pull inflation and falling unemployment', 'Deflation and excess capacity', 'A current account surplus'], answer: 1 },
      { q: 'The Phillips curve suggests a trade-off between:', options: ['Growth and inflation', 'Unemployment and inflation', 'Interest rates and exchange rates', 'Exports and imports'], answer: 1 },
      { q: 'GDP may not be a good measure of living standards because:', options: ['It includes all unpaid work', 'It does not account for income distribution, leisure, or the informal economy', 'It measures inflation accurately', 'It perfectly captures wellbeing'], answer: 1 },
      { q: 'A depreciation of the exchange rate is likely to improve the current account if:', options: ['The Marshall-Lerner condition is met (PED for exports + PED for imports > 1)', 'Import demand is inelastic', 'Export demand is inelastic', 'Both demands are perfectly inelastic'], answer: 0 },
      { q: 'The J-curve effect shows that after a depreciation:', options: ['The current account improves immediately', 'The current account worsens initially before improving', 'Inflation falls immediately', 'GDP always rises'], answer: 1 },
      { q: 'Supply-side causes of a current account deficit include:', options: ['Excess consumer spending', 'Poor productivity and lack of international competitiveness', 'Low exchange rate', 'High savings ratio'], answer: 1 },
      { q: 'Hysteresis in the labour market means:', options: ['Unemployment always returns to its natural rate', 'Prolonged unemployment causes permanent damage to skills and employability', 'The economy always grows', 'Wages are perfectly flexible'], answer: 1 },
      { q: 'The natural rate of unemployment is:', options: ['Zero unemployment', 'The rate consistent with stable inflation (structural + frictional)', 'Only cyclical unemployment', 'Set by the government'], answer: 1 },
      { q: 'A rise in oil prices is likely to cause:', options: ['Only demand-pull inflation', 'Cost-push inflation and possibly stagflation', 'Only economic growth', 'A fall in unemployment'], answer: 1 },
      { q: 'Comparing GDP across countries requires adjustment for:', options: ['Only exchange rates', 'Purchasing power parity (PPP) and population size', 'Only inflation', 'Government size'], answer: 1 },
      { q: 'Seasonal unemployment:', options: ['Is a major policy concern', 'Occurs predictably at certain times of year in specific industries', 'Indicates structural decline', 'Cannot be measured'], answer: 1 },
      { q: 'A current account surplus may indicate:', options: ['Low domestic demand or high international competitiveness', 'Excessive consumer spending', 'A weak currency causing inflation', 'Government budget deficit'], answer: 0 },
      { q: 'The limitations of CPI as a measure of inflation include:', options: ['It is perfectly accurate', 'It may not reflect individual household spending patterns and has a substitution bias', 'It measures unemployment', 'It includes asset prices'], answer: 1 },
      { q: 'An economy at full employment can still have unemployment because:', options: ['Full employment means zero unemployment', 'Frictional and structural unemployment always exist at the natural rate', 'All workers are employed', 'The government employs everyone'], answer: 1 },
      { q: 'The costs of inflation include:', options: ['Only higher prices', 'Menu costs, shoe-leather costs, reduced international competitiveness, and redistribution effects', 'Higher economic growth', 'Lower unemployment'], answer: 1 },
      { q: 'If UK inflation is higher than its trading partners, this is likely to:', options: ['Improve the current account', 'Worsen the current account as exports become less competitive', 'Have no effect on trade', 'Increase the value of the pound'], answer: 1 },
      { q: 'Technological unemployment is a type of:', options: ['Cyclical unemployment', 'Structural unemployment', 'Frictional unemployment', 'Seasonal unemployment'], answer: 1 },
      { q: 'The accelerator effect suggests that:', options: ['Growth causes inflation', 'Changes in GDP growth lead to larger proportional changes in investment', 'Interest rates affect consumption', 'Exports drive growth'], answer: 1 },
      { q: 'A deflationary spiral occurs when:', options: ['Prices rise continuously', 'Falling prices lead to postponed spending, lower demand, and further price falls', 'GDP grows rapidly', 'The economy overheats'], answer: 1 },
      { q: 'The terms of trade measure:', options: ['The volume of trade', 'The ratio of export prices to import prices', 'Total trade value', 'Trade in services only'], answer: 1 }
    ],
    red: [
      { q: 'Evaluate: "Economic growth always improves living standards."', options: ['True, GDP growth always benefits everyone','Growth may improve material standards but distributional effects','GDP is a perfect measure of welfare','Growth never benefits anyone'], answer: 1 },
      { q: 'Assess the extent to which a current account deficit is a macroeconomic problem:', options: ['It depends on the cause, financing method, size, and sustainability','It is always a serious problem','It only matters for developing countries','It is never a problem'], answer: 0 },
      { q: 'Evaluate the usefulness of the Phillips curve in modern macroeconomic policy:', options: ['The short-run trade-off may exist but expectations, supply shocks','It applies only to command economies','It has been completely disproved','It perfectly describes the inflation-unemployment relationship'], answer: 0 },
      { q: 'To what extent is low unemployment always desirable?', options: ['Low unemployment always causes deflation','Very low unemployment may cause labour shortages, wage-push inflation','It is always desirable with no trade-offs','Unemployment is never a problem'], answer: 1 },
      { q: 'Evaluate whether deflation is always worse than inflation:', options: ['Deflation is always worse','Moderate inflation is generally considered less harmful than','Inflation is always worse','Both are always equally harmful'], answer: 1 },
      { q: 'Assess the conflict between achieving low unemployment and maintaining a stable current account:', options: ['There is never a conflict','Lower unemployment may boost consumer spending on imports','The current account is irrelevant to employment','Only fiscal policy affects both'], answer: 1 },
      { q: 'Evaluate GDP per capita as an indicator of development:', options: ['It is the best possible indicator','It captures average income but ignores distribution','It is completely useless','It only matters for rich countries'], answer: 1 },
      { q: 'To what extent do macroeconomic objectives inevitably conflict?', options: ['They never conflict','They always conflict','Trade-offs often exist (e.g., growth vs. inflation vs.','Only fiscal and monetary policy conflict'], answer: 2 },
      { q: 'Evaluate: "Technological change will inevitably cause mass permanent unemployment."', options: ['True, technology always destroys jobs permanently','Technology displaces some jobs but historically creates new ones','Technology never affects employment','Only manufacturing jobs are affected'], answer: 1 },
      { q: 'Assess whether the economic cycle can be effectively managed by government policy:', options: ['It can always be perfectly managed','Policy can moderate fluctuations but faces time lags','Government has no effect on the cycle','Only monetary policy matters'], answer: 1 }
    ]
  },
  '2.2': {
    name: 'AD/AS & Equilibrium',
    green: [
      { q: 'Aggregate demand (AD) consists of:', options: ['C + I + G + (X-M)', 'C + I + G', 'C + I', 'Only consumer spending'], answer: 0 },
      { q: 'The AD curve slopes downward because:', options: ['Of the law of demand', 'Higher price levels reduce real wealth, increase interest rates, and make exports less competitive', 'Firms produce less at higher prices', 'Government spending falls with prices'], answer: 1 },
      { q: 'A rightward shift of the AD curve could be caused by:', options: ['An increase in interest rates', 'A fall in consumer confidence', 'An increase in government spending', 'An increase in income tax'], answer: 2 },
      { q: 'The short-run aggregate supply (SRAS) curve slopes upward because:', options: ['Firms expand output as price levels rise with sticky wages', 'Wages adjust instantly', 'The economy is always at full capacity', 'Government fixes output'], answer: 0 },
      { q: 'The long-run aggregate supply (LRAS) curve is:', options: ['Upward sloping', 'Downward sloping', 'Vertical at the full employment level of output', 'Horizontal'], answer: 2 },
      { q: 'A shift in LRAS to the right indicates:', options: ['A rise in the price level', 'An increase in the productive capacity of the economy', 'A fall in aggregate demand', 'Short-run inflation'], answer: 1 },
      { q: 'Which would shift SRAS to the left?', options: ['A fall in oil prices', 'A rise in raw material costs', 'An increase in productivity', 'A reduction in indirect taxes'], answer: 1 },
      { q: 'Macroeconomic equilibrium occurs where:', options: ['AD = AS', 'AD > AS', 'AD < AS', 'LRAS = SRAS'], answer: 0 },
      { q: 'Consumer spending is the largest component of AD in the UK. It is influenced by:', options: ['Only wages', 'Interest rates, confidence, wealth, and income', 'Only government policy', 'Only inflation'], answer: 1 },
      { q: 'Investment (I) in the AD equation refers to:', options: ['Buying shares', 'Spending by firms on capital goods', 'Saving by households', 'Government infrastructure'], answer: 1 },
      { q: 'Net exports (X-M) will increase if:', options: ['The exchange rate appreciates', 'Domestic income rises', 'Foreign income rises', 'Import prices fall'], answer: 2 },
      { q: 'The multiplier effect means:', options: ['Government spending always crowds out private spending', 'An initial injection leads to a larger final increase in national income', 'Savings always equal investment', 'Taxes reduce income by the same amount'], answer: 1 },
      { q: 'The multiplier formula is:', options: ['1 / (1 - MPT)', '1 / (1 - MPC) or 1/MPW', 'MPC / MPS', 'AD / AS'], answer: 1 },
      { q: 'The marginal propensity to consume (MPC) is:', options: ['Total consumption divided by income', 'The proportion of additional income that is spent', 'The proportion of income saved', 'Average spending per person'], answer: 1 },
      { q: 'If the MPC is 0.8, the multiplier is:', options: ['0.8', '4', '5', '8'], answer: 2 },
      { q: 'Withdrawals (leakages) from the circular flow include:', options: ['Investment, government spending, exports', 'Savings, taxation, imports', 'Consumption, investment, exports', 'Only savings'], answer: 1 },
      { q: 'Injections into the circular flow include:', options: ['Savings, taxation, imports', 'Investment, government spending, exports', 'Only consumption', 'Only government spending'], answer: 1 },
      { q: 'In the Keynesian model, the economy can be in equilibrium:', options: ['Only at full employment', 'Below full employment', 'Only above full employment', 'Never'], answer: 1 },
      { q: 'An increase in interest rates is likely to:', options: ['Shift AD to the right', 'Shift AD to the left', 'Shift LRAS to the right', 'Have no effect on AD'], answer: 1 },
      { q: 'The wealth effect in the AD model means:', options: ['Higher prices increase real wealth', 'Higher prices reduce real wealth, reducing consumption', 'Wealth always increases with inflation', 'Only the rich are affected by price changes'], answer: 1 }
    ],
    amber: [
      { q: 'In a Keynesian model with spare capacity, an increase in AD leads to:', options: ['Only inflation', 'An increase in real output with little inflation', 'No change in output', 'Only a rise in the price level'], answer: 1 },
      { q: 'When the economy operates close to full capacity, an increase in AD primarily causes:', options: ['Higher real output', 'Demand-pull inflation with little increase in real output', 'Deflation', 'A fall in unemployment'], answer: 1 },
      { q: 'The Keynesian AS curve is shaped differently from the classical LRAS because:', options: ['Keynesians believe prices and wages are flexible', 'Keynesians believe the economy can have spare capacity with sticky wages', 'Classical economists believe in unemployment equilibrium', 'There is no difference'], answer: 1 },
      { q: 'A negative multiplier effect from a tax increase is smaller when:', options: ['MPC is high', 'MPC is low', 'There are no leakages', 'The economy is at full employment'], answer: 1 },
      { q: 'Crowding out occurs when:', options: ['Government spending reduces private sector spending through higher interest rates', 'Government spending always increases private investment', 'The multiplier is infinite', 'AD shifts left'], answer: 0 },
      { q: 'An improvement in technology would:', options: ['Only shift AD right', 'Shift LRAS right and potentially SRAS right', 'Shift LRAS left', 'Only increase the price level'], answer: 1 },
      { q: 'If there is a negative output gap, appropriate policy might be:', options: ['Contractionary fiscal policy', 'Expansionary fiscal or monetary policy to boost AD', 'Higher interest rates', 'Reducing government spending'], answer: 1 },
      { q: 'The paradox of thrift suggests that:', options: ['Saving is always good for the economy', 'If all households increase saving simultaneously, total income and output may fall', 'Investment always rises with savings', 'The multiplier is always positive'], answer: 1 },
      { q: 'A supply-side shock (e.g., oil price rise) on the AD/AS diagram is shown as:', options: ['AD shifting right', 'SRAS shifting left', 'LRAS shifting right', 'AD shifting left'], answer: 1 },
      { q: 'The size of the multiplier is smaller in an open economy because:', options: ['There are no leakages', 'A larger proportion of additional income leaks out through imports', 'Exports are zero', 'The MPC is always high'], answer: 1 },
      { q: 'Quantitative easing aims to shift AD by:', options: ['Raising interest rates', 'Increasing the money supply to lower long-term interest rates and boost lending', 'Reducing government spending', 'Increasing taxation'], answer: 1 },
      { q: 'In the classical model, a fall in AD leads to:', options: ['A fall in output and rise in unemployment', 'Only a fall in the price level with output returning to the full employment level', 'Permanent recession', 'Higher inflation'], answer: 1 },
      { q: 'Animal spirits (Keynes) refer to:', options: ['Rational calculation by firms', 'Waves of business optimism and pessimism affecting investment decisions', 'Government policy', 'Consumer price expectations'], answer: 1 },
      { q: 'A leftward shift of AD combined with a leftward shift of SRAS would:', options: ['Definitely increase output', 'Lead to a fall in output with an ambiguous effect on the price level', 'Always reduce prices', 'Increase employment'], answer: 1 },
      { q: 'The marginal propensity to withdraw (MPW) equals:', options: ['1 - MPC', 'MPC + MPS', 'MPS + MPT + MPM', 'Only the savings rate'], answer: 2 },
      { q: 'If the economy is in a deflationary gap, this means:', options: ['AD exceeds the full employment level', 'AD is insufficient to achieve full employment output', 'The economy is overheating', 'Inflation is high'], answer: 1 },
      { q: 'An inflationary gap occurs when:', options: ['Actual output is below potential', 'AD exceeds the full employment level of output', 'There is unemployment', 'Prices are falling'], answer: 1 },
      { q: 'Net trade deteriorates (X-M falls). On the AD/AS diagram this:', options: ['Shifts AD right', 'Shifts AD left', 'Shifts LRAS right', 'Has no effect on AD'], answer: 1 },
      { q: 'The accelerator model suggests investment depends on:', options: ['The level of GDP', 'Changes in the rate of GDP growth', 'Only interest rates', 'Only business confidence'], answer: 1 },
      { q: 'In practice, the multiplier may be smaller than theory suggests because:', options: ['There are no time lags', 'Leakages, time lags, spare capacity constraints, and crowding out reduce it', 'The MPC is always 1', 'Government never spends money'], answer: 1 }
    ],
    red: [
      { q: 'Evaluate the Keynesian vs classical views on the shape of the AS curve and their policy implications:', options: ['Only the classical view is correct','Only the Keynesian view is correct','They are identical','Keynesians argue for active demand management in recessions'], answer: 3 },
      { q: 'Assess the effectiveness of the multiplier in practice:', options: ['It always works perfectly as theory predicts','Its effectiveness depends on spare capacity, openness of the economy','It is always zero','It only works in command economies'], answer: 1 },
      { q: 'Evaluate: "Expansionary fiscal policy is always the best response to a recession."', options: ['True, it always works','It can boost AD but may be limited by time lags, crowding out','Fiscal policy never works','Only monetary policy can address recessions'], answer: 1 },
      { q: 'To what extent does the AD/AS model accurately represent the real economy?', options: ['It is a perfect representation','It has no analytical value','It only works for small economies','It provides a useful simplified framework but abstracts from'], answer: 3 },
      { q: 'Assess the significance of crowding out as a limitation of fiscal policy:', options: ['It only affects monetary policy','It never occurs','Its significance depends on the state of the economy','It always completely offsets fiscal policy'], answer: 2 },
      { q: 'Evaluate whether demand-side or supply-side policies are more effective for long-term growth:', options: ['Supply-side policies increase productive capacity for sustained growth','Neither type of policy affects growth','Only demand-side policies matter','Only supply-side policies matter'], answer: 0 },
      { q: 'Assess the risks of relying on quantitative easing to boost aggregate demand:', options: ['It only affects the supply side','It always works perfectly','It may inflate asset prices, increase inequality','There are no risks'], answer: 2 },
      { q: 'Evaluate the paradox of thrift and its policy implications:', options: ['Saving is always bad for the economy','Individual rationality (saving more) can be collectively','The paradox does not exist','It only applies in hyperinflation'], answer: 1 },
      { q: 'To what extent can monetary policy alone achieve macroeconomic stability?', options: ['Monetary policy has no effect','Only fiscal policy matters','It can always achieve stability alone','It is effective at controlling inflation but may be limited'], answer: 3 },
      { q: 'Evaluate: "A large negative output gap always justifies aggressive fiscal stimulus."', options: ['Output gaps cannot be measured','While a negative output gap suggests spare capacity','True, stimulus is always appropriate','Stimulus never works with output gaps'], answer: 1 }
    ]
  },
  '2.3': {
    name: 'Economic Policy',
    green: [
      { q: 'Fiscal policy involves:', options: ['Changing interest rates', 'Government spending and taxation decisions', 'Controlling the money supply', 'Setting exchange rates'], answer: 1 },
      { q: 'Monetary policy primarily involves:', options: ['Taxation changes', 'Interest rate decisions and money supply management', 'Government spending changes', 'Trade policy'], answer: 1 },
      { q: 'Supply-side policies aim to:', options: ['Increase aggregate demand', 'Increase the productive potential of the economy', 'Reduce government spending', 'Only reduce inflation'], answer: 1 },
      { q: 'An expansionary fiscal policy involves:', options: ['Raising taxes and cutting spending', 'Cutting taxes and/or raising government spending', 'Raising interest rates', 'Reducing the money supply'], answer: 1 },
      { q: 'The Bank of England sets interest rates to achieve:', options: ['Full employment', 'The government\'s inflation target', 'Maximum GDP growth', 'A balanced budget'], answer: 1 },
      { q: 'Which is an example of a supply-side policy?', options: ['Cutting interest rates', 'Increasing government spending', 'Investment in education and training', 'Raising income tax'], answer: 2 },
      { q: 'A contractionary monetary policy involves:', options: ['Lowering interest rates', 'Raising interest rates to reduce AD', 'Increasing government spending', 'Cutting taxes'], answer: 1 },
      { q: 'Progressive taxation means:', options: ['Everyone pays the same rate', 'Higher earners pay a higher proportion of their income', 'Lower earners pay a higher proportion', 'Tax rates never change'], answer: 1 },
      { q: 'Automatic stabilisers include:', options: ['Discretionary tax cuts', 'Transfer payments and progressive taxation that change automatically with the cycle', 'Interest rate changes', 'Supply-side reforms'], answer: 1 },
      { q: 'The government budget deficit is:', options: ['Total government debt', 'Government spending exceeding tax revenue in a given year', 'Tax revenue exceeding spending', 'The trade deficit'], answer: 1 },
      { q: 'Which is a market-based supply-side policy?', options: ['Government spending on infrastructure', 'Deregulation and privatisation', 'State funding of education', 'NHS spending increases'], answer: 1 },
      { q: 'Which is an interventionist supply-side policy?', options: ['Tax cuts for business', 'Deregulation', 'Government investment in infrastructure and education', 'Reducing trade union power'], answer: 2 },
      { q: 'The national debt is:', options: ['This year\'s budget deficit', 'The accumulation of past budget deficits', 'Government spending', 'Annual tax revenue'], answer: 1 },
      { q: 'Quantitative easing involves:', options: ['Raising interest rates', 'The central bank buying bonds to increase the money supply', 'Cutting government spending', 'Increasing taxes'], answer: 1 },
      { q: 'A direct tax is levied on:', options: ['Spending on goods', 'Income, profits, or wealth', 'Exports only', 'Imports only'], answer: 1 },
      { q: 'An indirect tax is levied on:', options: ['Income', 'Expenditure on goods and services', 'Property', 'Savings'], answer: 1 },
      { q: 'The transmission mechanism of monetary policy describes:', options: ['How fiscal policy works', 'How interest rate changes affect the real economy through various channels', 'How supply-side policies work', 'How trade policy operates'], answer: 1 },
      { q: 'Labour market flexibility can be increased by:', options: ['Stronger trade unions', 'Higher minimum wages', 'Reducing employment protection legislation', 'Increasing welfare benefits'], answer: 2 },
      { q: 'The Laffer curve suggests that:', options: ['Higher tax rates always raise more revenue', 'Beyond a certain point, higher tax rates reduce tax revenue', 'Tax cuts always increase revenue', 'There is no relationship between tax rates and revenue'], answer: 1 },
      { q: 'A balanced budget occurs when:', options: ['Government spending equals tax revenue', 'The national debt is zero', 'There is no trade deficit', 'GDP growth equals inflation'], answer: 0 }
    ],
    amber: [
      { q: 'Time lags in fiscal policy mean that:', options: ['Policy takes effect immediately', 'There is a delay between implementing policy and its effect on the economy', 'Policy never works', 'Only monetary policy has time lags'], answer: 1 },
      { q: 'A cut in corporation tax is a supply-side policy because:', options: ['It directly increases AD', 'It aims to incentivise investment and increase productive capacity', 'It reduces government revenue only', 'It is a demand-side measure'], answer: 1 },
      { q: 'The conflict between low inflation and low unemployment suggests that:', options: ['Both can always be achieved simultaneously', 'Policies to reduce unemployment may increase inflation and vice versa in the short run', 'There is never a trade-off', 'Only supply-side policies face trade-offs'], answer: 1 },
      { q: 'Fiscal policy may be limited in a recession because:', options: ['Government always has unlimited resources', 'High debt levels may constrain borrowing, and there may be crowding out effects', 'Interest rates cannot fall', 'The multiplier is always large'], answer: 1 },
      { q: 'Forward guidance by central banks aims to:', options: ['Confuse markets', 'Manage expectations about future interest rates to influence current behaviour', 'Raise inflation expectations', 'Only affect the exchange rate'], answer: 1 },
      { q: 'Supply-side policies to reduce the natural rate of unemployment include:', options: ['Higher unemployment benefits', 'Education, training, and reducing labour market rigidities', 'Raising interest rates', 'Increasing government spending'], answer: 1 },
      { q: 'The effectiveness of monetary policy may be limited when:', options: ['Interest rates are high', 'Interest rates are at or near zero (the liquidity trap)', 'Inflation is high', 'The exchange rate is floating'], answer: 1 },
      { q: 'Austerity policies during a recession are controversial because:', options: ['They always boost growth', 'Cutting spending may worsen the recession through the multiplier, even though they aim to reduce the deficit', 'They have no effect on AD', 'They always eliminate the deficit quickly'], answer: 1 },
      { q: 'The conflict between economic growth and the current account arises because:', options: ['Growth always improves the current account', 'Faster growth tends to increase imports, worsening the current account', 'There is never a conflict', 'Only exchange rate policy affects the current account'], answer: 1 },
      { q: 'Privatisation as a supply-side policy aims to:', options: ['Increase government revenue only', 'Improve efficiency through competition and the profit motive', 'Always lower prices for consumers', 'Increase public ownership'], answer: 1 },
      { q: 'The UK\'s inflation targeting framework gives the Bank of England:', options: ['Complete control over fiscal policy', 'Operational independence to set interest rates to meet the government\'s inflation target', 'Power to change tax rates', 'Control over government spending'], answer: 1 },
      { q: 'Expansionary fiscal policy financed by borrowing may lead to:', options: ['Lower interest rates', 'Higher interest rates, crowding out, and increased national debt', 'An immediate fall in inflation', 'Reduced government debt'], answer: 1 },
      { q: 'A trade-off between environmental protection and economic growth exists because:', options: ['Environmental regulations are costless', 'Regulations may increase costs and reduce short-run output, though green investment may boost long-run growth', 'There is never a conflict', 'Only developing countries face this trade-off'], answer: 1 },
      { q: 'The government spending multiplier is typically larger than the tax multiplier because:', options: ['Government spending is more efficient', 'Government spending directly enters AD, while tax cuts are partly saved', 'Tax cuts always work better', 'They are always equal'], answer: 1 },
      { q: 'Negative interest rates aim to:', options: ['Encourage saving', 'Discourage banks from holding reserves and encourage lending', 'Raise the exchange rate', 'Reduce the money supply'], answer: 1 },
      { q: 'The effectiveness of supply-side policies is limited because:', options: ['They work instantly', 'They take time to have effect, may increase inequality, and benefits are uncertain', 'They never increase capacity', 'They always reduce unemployment immediately'], answer: 1 },
      { q: 'Counter-cyclical fiscal policy means:', options: ['Always running a deficit', 'Running deficits in recessions and surpluses in booms', 'Keeping spending constant', 'Always cutting taxes'], answer: 1 },
      { q: 'If the Bank of England raises interest rates, the likely effects include:', options: ['Higher AD and inflation', 'Lower consumer spending, investment, and potentially an appreciation of sterling', 'Higher government spending', 'Lower unemployment'], answer: 1 },
      { q: 'Rules-based fiscal policy (e.g., fiscal rules) aims to:', options: ['Allow unlimited government borrowing', 'Provide credibility and discipline to fiscal policy while constraining discretion', 'Eliminate all government debt immediately', 'Replace monetary policy'], answer: 1 },
      { q: 'The distributional effects of monetary policy are important because:', options: ['Everyone is affected equally', 'Low interest rates may benefit borrowers and asset owners more than savers, potentially increasing inequality', 'Only firms are affected', 'Interest rates do not affect distribution'], answer: 1 }
    ],
    red: [
      { q: 'Evaluate: "Monetary policy is always more effective than fiscal policy in managing the economy."', options: ['True, monetary policy is always superior','Effectiveness depends on economic conditions','Fiscal policy is always superior','Neither policy ever works'], answer: 1 },
      { q: 'Assess the trade-offs of using austerity to reduce a budget deficit during a recession:', options: ['There are no trade-offs','Austerity may worsen the recession through lower AD and','Austerity always works immediately','Budget deficits never matter'], answer: 1 },
      { q: 'To what extent can supply-side policies alone solve unemployment?', options: ['They never reduce unemployment','Only demand-side policies affect unemployment','They always solve all unemployment','They can address structural and frictional unemployment but'], answer: 3 },
      { q: 'Evaluate the conflict between reducing inequality and promoting economic growth:', options: ['Equality always promotes growth','Redistribution may reduce incentives but extreme inequality','There is never a conflict','Inequality always promotes growth'], answer: 1 },
      { q: 'Assess the effectiveness of quantitative easing as a policy tool:', options: ['It is always effective with no side effects','It can lower long-term rates and boost asset prices but may','It never works','It only affects the supply side'], answer: 1 },
      { q: 'Evaluate: "Independent central banks always produce better economic outcomes."', options: ['Independence makes no difference','Political control is always better','True, independence guarantees good outcomes','Independence can improve inflation credibility and reduce'], answer: 3 },
      { q: 'To what extent can a government achieve all four macroeconomic objectives simultaneously?', options: ['It can always achieve all four','Trade-offs make simultaneous achievement very difficult','It can never achieve any objectives','Only two can ever be achieved'], answer: 1 },
      { q: 'Assess whether market-based or interventionist supply-side policies are more effective:', options: ['Market-based are always superior','Market-based policies improve incentives but may increase inequality','Interventionist are always superior','Neither type works'], answer: 1 },
      { q: 'Evaluate the risks of sustained low interest rates for the economy:', options: ['There are no risks','Low rates always benefit everyone','Only savers are affected','They may create asset price bubbles, encourage excessive borrowing'], answer: 3 },
      { q: 'Assess: "The government should always aim for a balanced budget."', options: ['True, deficits are always harmful','A balanced budget rule may provide fiscal discipline but','Deficits never matter','Only surpluses are acceptable'], answer: 1 }
    ]
  },
  '2.4': {
    name: 'International Economics & Development',
    green: [
      { q: 'Absolute advantage means:', options: ['A country can produce a good at lower opportunity cost', 'A country can produce more of a good with the same resources', 'A country has more resources', 'A country has higher GDP'], answer: 1 },
      { q: 'Comparative advantage means:', options: ['A country can produce all goods more efficiently', 'A country can produce a good at a lower opportunity cost than another', 'A country has more workers', 'A country has better technology'], answer: 1 },
      { q: 'A tariff is:', options: ['A subsidy on exports', 'A tax on imports', 'A quota on production', 'A ban on trade'], answer: 1 },
      { q: 'A quota is:', options: ['A tax on imports', 'A physical limit on the quantity of imports', 'An export subsidy', 'A type of tariff'], answer: 1 },
      { q: 'A floating exchange rate is determined by:', options: ['The government', 'The central bank', 'Market forces of supply and demand', 'International agreement'], answer: 2 },
      { q: 'An appreciation of a currency means:', options: ['Its value falls against other currencies', 'Its value rises against other currencies', 'Inflation rises', 'Interest rates fall'], answer: 1 },
      { q: 'A depreciation of a currency:', options: ['Makes exports more expensive', 'Makes exports cheaper and imports more expensive', 'Has no effect on trade', 'Always improves the current account'], answer: 1 },
      { q: 'Free trade means:', options: ['Trade without any restrictions', 'Trade with high tariffs', 'Trade only between rich countries', 'Government-controlled trade'], answer: 0 },
      { q: 'The World Trade Organisation (WTO) aims to:', options: ['Increase protectionism', 'Promote free trade and resolve trade disputes', 'Set exchange rates', 'Control inflation globally'], answer: 1 },
      { q: 'Globalisation refers to:', options: ['Increased protectionism', 'Growing interdependence of world economies through trade, capital, and labour flows', 'Reduced international trade', 'National self-sufficiency'], answer: 1 },
      { q: 'Economic development differs from economic growth because:', options: ['They are the same thing', 'Development includes improvements in living standards, health, education, and inequality reduction', 'Development only means higher GDP', 'Growth includes social indicators'], answer: 1 },
      { q: 'Foreign direct investment (FDI) is:', options: ['Buying government bonds', 'Investment by a multinational in physical capital in another country', 'Short-term capital flows', 'Overseas aid'], answer: 1 },
      { q: 'Protectionism is the policy of:', options: ['Promoting free trade', 'Restricting imports to protect domestic industries', 'Reducing tariffs', 'Joining trade blocs'], answer: 1 },
      { q: 'A trade bloc is:', options: ['A barrier to trade', 'A group of countries with preferential trade agreements', 'A type of tariff', 'An international bank'], answer: 1 },
      { q: 'The infant industry argument for protection states that:', options: ['All industries need permanent protection', 'New industries may need temporary protection to achieve economies of scale', 'Protection always helps growth', 'Tariffs have no cost'], answer: 1 },
      { q: 'The terms of trade are measured as:', options: ['Export volume / Import volume', '(Index of export prices / Index of import prices) x 100', 'Total trade value', 'Current account balance'], answer: 1 },
      { q: 'Multinational corporations (MNCs) are firms that:', options: ['Only operate domestically', 'Operate in more than one country', 'Are owned by governments', 'Only export goods'], answer: 1 },
      { q: 'Absolute poverty is defined as:', options: ['Being poorer than average', 'Living below a minimum income needed for basic necessities', 'Earning below median income', 'Having no savings'], answer: 1 },
      { q: 'Relative poverty is defined as:', options: ['Having no income', 'Having income below a proportion (e.g., 60%) of median income', 'Living on less than $1.90 per day', 'Having no access to healthcare'], answer: 1 },
      { q: 'The Gini coefficient measures:', options: ['GDP growth', 'Income or wealth inequality (0 = perfect equality, 1 = perfect inequality)', 'Inflation', 'Unemployment'], answer: 1 }
    ],
    amber: [
      { q: 'The theory of comparative advantage assumes:', options: ['Perfect factor mobility between countries', 'Constant costs, two countries, two goods, and no transport costs', 'Increasing returns to scale', 'Trade barriers exist'], answer: 1 },
      { q: 'A depreciation of sterling benefits UK exporters because:', options: ['UK goods become relatively cheaper in foreign currency terms', 'Import prices fall', 'Domestic inflation falls', 'Interest rates rise'], answer: 0 },
      { q: 'Hot money flows are attracted by:', options: ['Low interest rates', 'Higher relative interest rates and expected appreciation', 'Trade surpluses', 'Low GDP growth'], answer: 1 },
      { q: 'The impact of a tariff on a diagram shows:', options: ['Only a price increase', 'Higher price, reduced imports, domestic supply increase, government revenue, and deadweight loss', 'Lower prices for consumers', 'No welfare loss'], answer: 1 },
      { q: 'Trade creation in a customs union occurs when:', options: ['Trade is diverted from efficient to inefficient producers', 'Members switch from higher-cost domestic production to lower-cost production within the union', 'All trade is eliminated', 'Tariffs increase within the bloc'], answer: 1 },
      { q: 'Trade diversion occurs when:', options: ['Trade shifts to more efficient producers', 'A customs union diverts trade from more efficient non-members to less efficient members', 'Free trade increases', 'Tariffs are removed globally'], answer: 1 },
      { q: 'The Prebisch-Singer hypothesis suggests that:', options: ['Terms of trade for primary commodities improve over time', 'Terms of trade for primary commodity exporters tend to deteriorate over time', 'All countries benefit equally from trade', 'Manufactured goods decline in value'], answer: 1 },
      { q: 'Structural adjustment programmes imposed by the IMF have been criticised because:', options: ['They always work perfectly', 'They may impose austerity and market liberalisation that harms the poor in the short run', 'They increase aid dependency', 'They only help rich countries'], answer: 1 },
      { q: 'FDI can benefit developing countries by:', options: ['Always exploiting workers', 'Providing capital, technology transfer, employment, and tax revenue', 'Reducing all domestic production', 'Only benefiting multinational shareholders'], answer: 1 },
      { q: 'The impact of globalisation on inequality is:', options: ['It always reduces inequality', 'It may reduce between-country inequality but increase within-country inequality', 'It always increases inequality', 'It has no effect on inequality'], answer: 1 },
      { q: 'Barriers to development in low-income countries include:', options: ['Only lack of capital', 'Corruption, poor institutions, lack of infrastructure, conflict, and commodity dependency', 'Only geographical factors', 'Only cultural factors'], answer: 1 },
      { q: 'A managed float exchange rate system involves:', options: ['Purely market-determined rates', 'The central bank intervening occasionally to influence the rate while allowing market forces to operate', 'A fixed exchange rate', 'No foreign exchange market'], answer: 1 },
      { q: 'The advantages of a fixed exchange rate include:', options: ['Automatic adjustment to shocks', 'Certainty for international trade, reduced speculation, and policy discipline', 'Flexible monetary policy', 'No need for reserves'], answer: 1 },
      { q: 'Aid dependency may hinder development because:', options: ['Aid is always beneficial', 'It may reduce incentives for domestic reform, fund corruption, and create reliance on external support', 'It always increases growth', 'It improves governance automatically'], answer: 1 },
      { q: 'Microfinance aims to promote development by:', options: ['Providing large loans to governments', 'Giving small loans to entrepreneurs who lack access to conventional banking', 'Reducing tariffs', 'Increasing FDI'], answer: 1 },
      { q: 'The impact of MNCs on developing countries may include:', options: ['Only positive effects', 'Job creation and technology transfer but also potential exploitation, profit repatriation, and environmental damage', 'Only negative effects', 'No significant impact'], answer: 1 },
      { q: 'Purchasing power parity (PPP) adjustments are important because:', options: ['They are unnecessary', 'They account for differences in price levels across countries, giving a better comparison of living standards', 'They measure exchange rate speculation', 'They only apply to developed countries'], answer: 1 },
      { q: 'The Kuznets curve suggests that:', options: ['Inequality always rises with growth', 'Inequality initially rises then falls as an economy develops', 'Inequality always falls with growth', 'There is no relationship between growth and inequality'], answer: 1 },
      { q: 'Dumping in international trade refers to:', options: ['Selling exports at normal prices', 'Selling exports below cost in foreign markets to gain market share', 'Imposing tariffs', 'Subsidising all domestic firms'], answer: 1 },
      { q: 'Intellectual property protection in trade agreements may:', options: ['Always benefit developing countries', 'Benefit innovators but restrict access to medicines and technology for developing countries', 'Have no effect on development', 'Only benefit consumers'], answer: 1 }
    ],
    red: [
      { q: 'Evaluate: "Free trade always benefits all countries."', options: ['True, all countries always gain','Comparative advantage suggests mutual gains but adjustment costs','Free trade never benefits anyone','Only large countries benefit'], answer: 1 },
      { q: 'Assess the extent to which globalisation has benefited developing countries:', options: ['It has never benefited them','It has always benefited them','It has provided growth opportunities and poverty reduction for some','Only China has benefited'], answer: 2 },
      { q: 'Evaluate whether a floating or fixed exchange rate system is better for a developing country:', options: ['Fixed is always better','Floating is always better','Fixed provides stability but limits monetary policy flexibility','Exchange rate systems do not matter'], answer: 2 },
      { q: 'To what extent can aid effectively promote economic development?', options: ['Aid never works','Only trade promotes development','Aid always works','Aid can fill savings and foreign exchange gaps but'], answer: 3 },
      { q: 'Evaluate the infant industry argument for protectionism:', options: ['It is never valid','It always justifies permanent protection','It has theoretical validity but risks include perpetual protection','It only applies to agriculture'], answer: 2 },
      { q: 'Assess: "Multinational corporations are the most important driver of development in poor countries."', options: ['MNCs can bring capital, jobs, and technology but may also','True, they are always beneficial','Only domestic firms matter for development','MNCs always harm development'], answer: 0 },
      { q: 'Evaluate the impact of trade liberalisation on income inequality within countries:', options: ['It always reduces inequality','It may increase inequality as mobile capital gains while','It always increases inequality','It has no distributional effects'], answer: 1 },
      { q: 'Assess whether the WTO effectively promotes fair global trade:', options: ['It only benefits developing countries','It is completely ineffective','It has reduced tariffs and provided a dispute mechanism but','It always achieves fair trade'], answer: 2 },
      { q: 'Evaluate: "Economic growth is a necessary and sufficient condition for economic development."', options: ['Growth is irrelevant to development','Growth is likely necessary but not sufficient','Only equality matters for development','True, growth always leads to development'], answer: 1 },
      { q: 'Assess the sustainability of export-led growth as a development strategy:', options: ['It can drive growth through specialisation and FDI but may','It is always sustainable','Only import substitution works','It never works'], answer: 0 }
    ]
  }
};
