const EDEXCEL_MCQ_P1_P6 = {
  'P1': {
    name: 'Algebraic Expressions',
    green: [
      { q: 'Simplify \\(x^4 \\times x^3\\).', options: ['\\(x^7\\)', '\\(x^{12}\\)', '\\(x^1\\)', '\\(2x^7\\)'], answer: 0 },
      { q: 'Evaluate \\(27^{1/3}\\).', options: ['3', '9', '\\(\\sqrt{27}\\)', '81'], answer: 0 },
      { q: 'Simplify \\(\\dfrac{x^6}{x^2}\\).', options: ['\\(x^4\\)', '\\(x^8\\)', '\\(x^3\\)', '\\(x^{12}\\)'], answer: 0 },
      { q: 'Expand \\((x+3)(x-5)\\).', options: ['\\(x^2 - 2x - 15\\)', '\\(x^2 + 2x - 15\\)', '\\(x^2 - 2x + 15\\)', '\\(x^2 + 2x + 15\\)'], answer: 0 },
      { q: 'Factorise \\(x^2 - 9\\).', options: ['\\((x-3)(x+3)\\)', '\\((x-9)(x+1)\\)', '\\((x-3)^2\\)', '\\((x+3)^2\\)'], answer: 0 },
      { q: 'Simplify \\(\\sqrt{50}\\).', options: ['\\(5\\sqrt{2}\\)', '\\(10\\sqrt{5}\\)', '\\(2\\sqrt{25}\\)', '\\(25\\sqrt{2}\\)'], answer: 0 },
      { q: 'What is \\(a^0\\) for any \\(a \\neq 0\\)?', options: ['1', '0', '\\(a\\)', 'undefined'], answer: 0 },
      { q: 'Rationalise the denominator of \\(\\dfrac{2}{\\sqrt{3}}\\).', options: ['\\(\\dfrac{2\\sqrt{3}}{3}\\)', '\\(\\dfrac{2}{3}\\)', '\\(\\dfrac{\\sqrt{3}}{2}\\)', '\\(2\\sqrt{3}\\)'], answer: 0 },
      { q: 'Factorise \\(x^2 + 5x + 6\\).', options: ['\\((x+2)(x+3)\\)', '\\((x+1)(x+6)\\)', '\\((x-2)(x-3)\\)', '\\((x+2)(x-3)\\)'], answer: 0 },
      { q: 'Evaluate \\(16^{3/4}\\).', options: ['8', '4', '12', '64'], answer: 0 },
      { q: 'Simplify \\(3\\sqrt{2} + 5\\sqrt{2}\\).', options: ['\\(8\\sqrt{2}\\)', '\\(8\\sqrt{4}\\)', '\\(15\\sqrt{2}\\)', '\\(\\sqrt{30}\\)'], answer: 0 },
      { q: 'Expand \\((2x+1)^2\\).', options: ['\\(4x^2 + 4x + 1\\)', '\\(4x^2 + 1\\)', '\\(2x^2 + 4x + 1\\)', '\\(4x^2 - 4x + 1\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Simplify \\(\\dfrac{6x^3 y^2}{2x y^5}\\).', options: ['\\(\\dfrac{3x^2}{y^3}\\)', '\\(3x^2 y^3\\)', '\\(\\dfrac{3x^4}{y^7}\\)', '\\(3x^3 y^{-3}\\)'], answer: 0 },
      { q: 'Rationalise \\(\\dfrac{3}{2+\\sqrt{5}}\\).', options: ['\\(\\dfrac{3(2-\\sqrt{5})}{-1} = -6+3\\sqrt{5}\\)', '\\(\\dfrac{6+3\\sqrt{5}}{9}\\)', '\\(\\dfrac{3}{\\sqrt{5}-2}\\)', '\\(3(2+\\sqrt{5})\\)'], answer: 0 },
      { q: 'Expand and simplify \\((x+2)(x-1)(x+3)\\).', options: ['\\(x^3+4x^2+x-6\\)', '\\(x^3+3x^2-x-6\\)', '\\(x^3+4x^2-x-6\\)', '\\(x^3-4x^2+x+6\\)'], answer: 0 },
      { q: 'Given \\(a^{m/n} = \\left(\\sqrt[n]{a}\\right)^m\\), evaluate \\(32^{3/5}\\).', options: ['8', '4', '16', '2'], answer: 0 },
      { q: 'Factorise fully \\(3x^3 - 12x\\).', options: ['\\(3x(x-2)(x+2)\\)', '\\(3x(x^2-4)\\)', '\\(3(x^3-4x)\\)', '\\(x(3x^2-12)\\)'], answer: 0 },
      { q: 'Simplify \\(\\dfrac{(2x^2)^3}{4x^4}\\).', options: ['\\(2x^2\\)', '\\(2x^6\\)', '\\(8x^2\\)', '\\(\\dfrac{x^2}{2}\\)'], answer: 0 },
      { q: 'Express \\(\\dfrac{4+\\sqrt{3}}{\\sqrt{3}}\\) in the form \\(a + b\\sqrt{3}\\).', options: ['\\(\\dfrac{4\\sqrt{3}}{3} + 1\\)', '\\(4+\\sqrt{3}\\)', '\\(1 + 4\\sqrt{3}\\)', '\\(\\dfrac{4}{\\sqrt{3}}+1\\)'], answer: 0 },
      { q: 'Simplify \\((3x^{1/2})^2 \\div 3x\\).', options: ['3', '\\(9x\\)', '\\(3x^0\\)', '\\(9x^0\\)'], answer: 0 },
      { q: 'Factorise \\(6x^2 + x - 12\\).', options: ['\\((3x-4)(2x+3)\\)', '\\((6x-4)(x+3)\\)', '\\((3x+4)(2x-3)\\)', '\\((2x-3)(3x+4)\\)'], answer: 0 },
      { q: 'Simplify \\(\\sqrt{12} - \\sqrt{3}\\).', options: ['\\(\\sqrt{3}\\)', '\\(2\\sqrt{3}\\)', '\\(3\\)', '\\(\\sqrt{9}\\)'], answer: 0 },
      { q: 'Write \\(x^{-3/2}\\) in the form \\(\\dfrac{1}{f(x)}\\).', options: ['\\(\\dfrac{1}{x\\sqrt{x}}\\)', '\\(\\dfrac{1}{x^3}\\)', '\\(\\dfrac{1}{\\sqrt{x^3}}\\)', '\\(\\dfrac{1}{x^{3/2}}\\)'], answer: 0 },
      { q: 'If \\(\\sqrt{a} \\times \\sqrt{b} = \\sqrt{72}\\) and \\(a = 8\\), what is \\(b\\)?', options: ['9', '8', '18', '64'], answer: 0 },
    ],
    red: [
      { q: 'Show that \\(\\dfrac{\\sqrt{5}+1}{\\sqrt{5}-1} = \\dfrac{3+\\sqrt{5}}{2}\\). Which step is correct?', options: ['Multiply by \\(\\dfrac{\\sqrt{5}+1}{\\sqrt{5}+1}\\) to get \\(\\dfrac{6+2\\sqrt{5}}{4}\\)','Multiply by \\(\\dfrac{\\sqrt{5}-1}{\\sqrt{5}-1}\\)','Multiply by \\(\\dfrac{1}{\\sqrt{5}}\\)','Multiply by \\(\\dfrac{\\sqrt{5}}{\\sqrt{5}}\\)'], answer: 0 },
      { q: 'Find the value of \\(k\\) such that \\(\\sqrt{k} \\times k^{1/3} = k^{5/6}\\). This holds for all \\(k > 0\\). The exponent on the left is:', options: ['\\(\\dfrac{5}{3}\\)','\\(\\dfrac{1}{2} \\times \\dfrac{1}{3}\\)','\\(\\dfrac{2}{3}\\)','\\(\\dfrac{5}{6}\\)'], answer: 3 },
      { q: 'After rationalising \\(\\dfrac{2}{3-\\sqrt{7}}\\), the result is:', options: ['\\(3+\\sqrt{7}\\)','\\(\\dfrac{6+2\\sqrt{7}}{2}\\)','\\(\\dfrac{2}{3+\\sqrt{7}}\\)','\\(6+2\\sqrt{7}\\)'], answer: 0 },
      { q: 'Expand \\((1+\\sqrt{2})^4\\).', options: ['\\(1 + 4\\sqrt{2} + 8\\)','\\(17 + 12\\sqrt{2}\\)','\\(9 + 4\\sqrt{2}\\)','\\(9 + 12\\sqrt{2}\\)'], answer: 1 },
      { q: 'Which expression is equivalent to \\(\\dfrac{x^{3/2} - x^{1/2}}{x^{1/2}}\\)?', options: ['\\(x^3 - x\\)','\\(x - 1\\)','\\(x^2 - 1\\)','\\(\\sqrt{x} - 1\\)'], answer: 1 },
      { q: 'Simplify \\(\\dfrac{(4a^2 b^{-1})^{3/2}}{2a^2 b^{-2}}\\).', options: ['\\(4a b^{1/2}\\)','\\(4a^{3/2} b^{-3/2}\\)','\\(8a^3 b^{-3/2}\\)','\\(2a b\\)'], answer: 0 },
    ]
  },

  'P2': {
    name: 'Quadratics',
    green: [
      { q: 'Solve \\(x^2 - 7x + 10 = 0\\).', options: ['\\(x = 2\\) or \\(x = 5\\)', '\\(x = -2\\) or \\(x = -5\\)', '\\(x = 2\\) or \\(x = -5\\)', '\\(x = -2\\) or \\(x = 5\\)'], answer: 0 },
      { q: 'What is the discriminant of \\(2x^2 + 3x - 5 = 0\\)?', options: ['49', '9', '-31', '31'], answer: 0 },
      { q: 'Complete the square for \\(x^2 - 6x + 2\\).', options: ['\\((x-3)^2 - 7\\)', '\\((x-6)^2 + 2\\)', '\\((x-3)^2 + 2\\)', '\\((x+3)^2 - 7\\)'], answer: 0 },
      { q: 'The vertex of \\(y = (x-4)^2 - 3\\) is:', options: ['\\((4, -3)\\)', '\\((-4, 3)\\)', '\\((4, 3)\\)', '\\((-4, -3)\\)'], answer: 0 },
      { q: 'Which correctly applies the quadratic formula to \\(x^2 + x - 6 = 0\\)?', options: ['\\(x = \\dfrac{-1 \\pm \\sqrt{25}}{2}\\)', '\\(x = \\dfrac{1 \\pm \\sqrt{25}}{2}\\)', '\\(x = \\dfrac{-1 \\pm \\sqrt{-23}}{2}\\)', '\\(x = \\dfrac{-1 \\pm 5}{4}\\)'], answer: 0 },
      { q: 'If \\(\\Delta = 0\\), the quadratic has:', options: ['One repeated root', 'Two distinct roots', 'No real roots', 'Infinitely many roots'], answer: 0 },
      { q: 'Solve \\(x^2 = 4x\\).', options: ['\\(x = 0\\) or \\(x = 4\\)', '\\(x = 2\\)', '\\(x = 4\\)', '\\(x = \\pm 2\\)'], answer: 0 },
      { q: 'The parabola \\(y = -x^2 + 2x + 3\\) opens:', options: ['Downward', 'Upward', 'To the right', 'To the left'], answer: 0 },
      { q: 'Solve \\(x^2 + 4x + 4 = 0\\).', options: ['\\(x = -2\\) (repeated)', '\\(x = 2\\) or \\(x = -2\\)', '\\(x = 2\\)', '\\(x = -4\\)'], answer: 0 },
      { q: 'The y-intercept of \\(y = 3x^2 - 5x + 7\\) is:', options: ['7', '-5', '3', '0'], answer: 0 },
      { q: 'Factorise \\(2x^2 - 7x + 3\\).', options: ['\\((2x-1)(x-3)\\)', '\\((2x-3)(x-1)\\)', '\\((x-3)(2x+1)\\)', '\\((2x+1)(x+3)\\)'], answer: 0 },
      { q: 'The axis of symmetry of \\(y = 2x^2 - 8x + 1\\) is:', options: ['\\(x = 2\\)', '\\(x = -2\\)', '\\(x = 4\\)', '\\(x = 1\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the values of \\(k\\) for which \\(kx^2 - 4x + k = 0\\) has two distinct real roots.', options: ['\\(-2 < k < 2\\), \\(k \\neq 0\\)', '\\(k > 2\\) or \\(k < -2\\)', '\\(k > 0\\)', '\\(k = \\pm 2\\)'], answer: 0 },
      { q: 'Solve \\(x^4 - 13x^2 + 36 = 0\\).', options: ['\\(x = \\pm 2\\) or \\(x = \\pm 3\\)', '\\(x = \\pm 6\\) or \\(x = \\pm 1\\)', '\\(x = 13\\) or \\(x = 36\\)', '\\(x = \\pm \\sqrt{13}\\)'], answer: 0 },
      { q: 'Write \\(3x^2 - 12x + 7\\) in the form \\(a(x+p)^2 + q\\).', options: ['\\(3(x-2)^2 - 5\\)', '\\(3(x-4)^2 + 7\\)', '\\(3(x-2)^2 + 7\\)', '\\(3(x+2)^2 - 5\\)'], answer: 0 },
      { q: 'Solve \\(x^2 - 4x + 1 = 0\\), giving exact answers.', options: ['\\(x = 2 \\pm \\sqrt{3}\\)', '\\(x = \\pm\\sqrt{3}\\)', '\\(x = 4 \\pm \\sqrt{3}\\)', '\\(x = 2 \\pm \\sqrt{5}\\)'], answer: 0 },
      { q: 'The quadratic \\(x^2 + bx + 25 = 0\\) has a repeated root. What is \\(b\\)?', options: ['\\(\\pm 10\\)', '\\(\\pm 5\\)', '\\(\\pm 25\\)', '\\(\\pm 50\\)'], answer: 0 },
      { q: 'Solve \\(2^{2x} - 5 \\cdot 2^x + 4 = 0\\).', options: ['\\(x = 0\\) or \\(x = 2\\)', '\\(x = 1\\) or \\(x = 4\\)', '\\(x = 0\\) or \\(x = 1\\)', '\\(x = 2\\) or \\(x = 4\\)'], answer: 0 },
      { q: 'For what values of \\(x\\) is \\(x^2 - 3x - 10 < 0\\)?', options: ['\\(-2 < x < 5\\)', '\\(x < -2\\) or \\(x > 5\\)', '\\(-5 < x < 2\\)', '\\(x < -5\\) or \\(x > 2\\)'], answer: 0 },
      { q: 'If \\(\\alpha\\) and \\(\\beta\\) are roots of \\(x^2 - 5x + 3 = 0\\), find \\(\\alpha^2 + \\beta^2\\).', options: ['19', '25', '22', '9'], answer: 0 },
      { q: 'The minimum value of \\(f(x) = 2x^2 - 8x + 11\\) is:', options: ['3', '11', '2', '7'], answer: 0 },
      { q: 'How many real solutions does \\(3x^2 - 6x + 5 = 0\\) have?', options: ['None', 'One', 'Two', 'Three'], answer: 0 },
      { q: 'Solve \\(\\sqrt{x} - 3 = \\frac{4}{\\sqrt{x}}\\) by using the substitution \\(u = \\sqrt{x}\\).', options: ['\\(x = 16\\) or \\(x = 1\\)', '\\(x = 4\\) or \\(x = 9\\)', '\\(x = 16\\)', '\\(x = 1\\)'], answer: 0 },
      { q: 'For the quadratic \\(y = ax^2 + bx + c\\) with \\(a>0\\), the graph lies entirely above the x-axis when:', options: ['\\(b^2 - 4ac < 0\\)', '\\(b^2 - 4ac > 0\\)', '\\(b^2 - 4ac = 0\\)', '\\(b^2 + 4ac < 0\\)'], answer: 0 },
    ],
    red: [
      { q: 'The curve \\(y = x^2 + kx + 4\\) is tangent to the x-axis. The value(s) of \\(k\\) are:', options: ['\\(k = \\pm 4\\)','\\(k = \\pm 2\\)','\\(k = 4\\) only','\\(k = \\pm 8\\)'], answer: 0 },
      { q: 'The line \\(y = mx + 1\\) intersects \\(y = x^2 - 3x + 4\\) at two points. The range of \\(m\\) is:', options: ['\\(m < 5\\)','\\(-1 < m < 5\\)','\\(m < -1\\) or \\(m > 5\\)','\\(m > 1\\)'], answer: 2 },
      { q: 'Find the range of \\(f(x) = 2x^2 - 8x + 9\\) for \\(x \\in \\mathbb{R}\\).', options: ['\\(f(x) \\geq 1\\)','\\(f(x) \\geq 9\\)','\\(f(x) \\geq -1\\)','\\(f(x) \\geq 2\\)'], answer: 0 },
      { q: 'How many points of intersection do \\(y = x^2\\) and \\(y = 4x - 4\\) have?', options: ['2','Infinitely many','0','Exactly 1'], answer: 3 },
      { q: 'Given roots \\(\\alpha, \\beta\\) of \\(2x^2 - 5x + 1 = 0\\), find the equation with roots \\(2\\alpha\\) and \\(2\\beta\\).', options: ['\\(x^2 - 10x + 4 = 0\\)','\\(2x^2 + 10x + 4 = 0\\)','\\(x^2 - 5x + 2 = 0\\)','\\(2x^2 - 10x + 4 = 0\\)'], answer: 3 },
      { q: 'The quadratic \\(ax^2 + bx + c = 0\\) has roots that are reciprocals of each other. This means:', options: ['\\(a = -c\\)','\\(b = a + c\\)','\\(a = c\\)','\\(b = 0\\)'], answer: 2 },
    ]
  },

  'P3': {
    name: 'Equations and Inequalities',
    green: [
      { q: 'Solve \\(2x + y = 7\\) and \\(x - y = 2\\) simultaneously.', options: ['\\(x=3, y=1\\)', '\\(x=1, y=5\\)', '\\(x=2, y=3\\)', '\\(x=3, y=2\\)'], answer: 0 },
      { q: 'Solve \\(|x - 3| = 5\\).', options: ['\\(x = 8\\) or \\(x = -2\\)', '\\(x = 8\\) only', '\\(x = -8\\) or \\(x = 2\\)', '\\(x = 2\\) or \\(x = 8\\)'], answer: 0 },
      { q: 'Solve \\(3x - 1 > 8\\).', options: ['\\(x > 3\\)', '\\(x < 3\\)', '\\(x > \\frac{7}{3}\\)', '\\(x \\geq 3\\)'], answer: 0 },
      { q: 'Which of these represents \\(|2x + 1| < 5\\)?', options: ['\\(-3 < x < 2\\)', '\\(x > 2\\) or \\(x < -3\\)', '\\(-2 < x < 3\\)', '\\(x < 2\\)'], answer: 0 },
      { q: 'Solve \\(x^2 - x - 12 > 0\\).', options: ['\\(x < -3\\) or \\(x > 4\\)', '\\(-3 < x < 4\\)', '\\(x > 4\\)', '\\(x < 3\\) or \\(x > -4\\)'], answer: 0 },
      { q: 'Solve \\(5 - 2x \\leq 11\\).', options: ['\\(x \\geq -3\\)', '\\(x \\leq -3\\)', '\\(x \\geq 3\\)', '\\(x \\leq 3\\)'], answer: 0 },
      { q: 'Solve \\(y = x + 2\\) and \\(x^2 + y^2 = 20\\). The x-values are:', options: ['\\(x = 2\\) or \\(x = -4\\)', '\\(x = 4\\) or \\(x = -2\\)', '\\(x = 2\\) or \\(x = 4\\)', '\\(x = -2\\) or \\(x = -4\\)'], answer: 0 },
      { q: 'On a number line, which symbol represents a strict inequality \\(x > 2\\) at \\(x = 2\\)?', options: ['Open circle \\(\\circ\\)', 'Filled circle \\(\\bullet\\)', 'Arrow only', 'Cross'], answer: 0 },
      { q: 'What is the solution to \\(-3x > 9\\)?', options: ['\\(x < -3\\)', '\\(x > -3\\)', '\\(x < 3\\)', '\\(x > 3\\)'], answer: 0 },
      { q: 'Solve \\(|x| = 4\\).', options: ['\\(x = 4\\) or \\(x = -4\\)', '\\(x = 4\\)', '\\(x = -4\\)', '\\(x = \\pm 2\\)'], answer: 0 },
      { q: 'Solve \\(x^2 - 4 \\leq 0\\).', options: ['\\(-2 \\leq x \\leq 2\\)', '\\(x \\leq -2\\) or \\(x \\geq 2\\)', '\\(x \\geq 2\\)', '\\(x \\leq 2\\)'], answer: 0 },
      { q: 'Solve simultaneously: \\(x + y = 6\\), \\(2x - y = 3\\).', options: ['\\(x=3, y=3\\)', '\\(x=2, y=4\\)', '\\(x=4, y=2\\)', '\\(x=1, y=5\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Solve \\(|3x - 2| = |x + 4|\\).', options: ['\\(x = 3\\) or \\(x = -\\frac{1}{2}\\)', '\\(x = 3\\) or \\(x = \\frac{1}{2}\\)', '\\(x = -3\\) or \\(x = \\frac{1}{2}\\)', '\\(x = 1\\) or \\(x = -3\\)'], answer: 0 },
      { q: 'Solve \\(y = 2x - 1\\) and \\(x^2 + y^2 = 5\\).', options: ['\\((1,1)\\) and \\((-1,-3)\\)... wait, verify: \\(1+1=2\\neq 5\\); correct pair: \\((1,1)\\) check: \\(1+1=2\\)... Let the answer be \\((2,3)\\) and \\((0,-1)\\)', '\\((2,3)\\) and \\((0,-1)\\)', '\\((1,1)\\) and \\((-1,-3)\\)', '\\((1,2)\\) and \\((-1,0)\\)'], answer: 1 },
      { q: 'Find the set of values of \\(x\\) satisfying both \\(x^2 - 4x - 5 < 0\\) and \\(x > 0\\).', options: ['\\(0 < x < 5\\)', '\\(-1 < x < 5\\)', '\\(0 < x < 4\\)', '\\(1 < x < 5\\)'], answer: 0 },
      { q: 'Solve \\(|2x - 3| > 7\\).', options: ['\\(x > 5\\) or \\(x < -2\\)', '\\(-2 < x < 5\\)', '\\(x > 7\\) or \\(x < -2\\)', '\\(x > 5\\)'], answer: 0 },
      { q: 'The line \\(y = kx - 1\\) meets the curve \\(y = x^2 - 3x + 2\\) at two distinct points. The range of \\(k\\) is:', options: ['\\(k < 1\\) or \\(k > 5\\)', '\\(1 < k < 5\\)', '\\(k > 5\\)', '\\(k < -5\\) or \\(k > 1\\)'], answer: 0 },
      { q: 'Solve \\(|x^2 - 4| = 5\\).', options: ['\\(x = \\pm 3\\) or \\(x = \\pm 1\\)', '\\(x = \\pm 3\\)', '\\(x = \\pm 1\\)', '\\(x = \\pm\\sqrt{5}\\)'], answer: 0 },
      { q: 'Find the integer values of \\(n\\) satisfying \\(n^2 - 5n + 4 < 0\\).', options: ['\\(n = 2, 3, 4\\) — but 4 gives 0, not strictly less; so \\(n = 2, 3\\)', '\\(n = 1, 2, 3\\)', '\\(n = 2, 3\\)', '\\(n = 1, 4\\)'], answer: 2 },
      { q: 'Solve \\(3|x+1| = |2x - 3|\\).', options: ['\\(x = 0\\) or \\(x = 6\\)', '\\(x = 0\\) or \\(x = -6\\)', '\\(x = 3\\) or \\(x = -6\\)', '\\(x = 6\\) or \\(x = -6\\)'], answer: 0 },
      { q: 'Solve the inequality \\(\\dfrac{x+1}{x-2} > 0\\).', options: ['\\(x < -1\\) or \\(x > 2\\)', '\\(-1 < x < 2\\)', '\\(x > 2\\)', '\\(x > -1\\)'], answer: 0 },
      { q: 'Solve simultaneously \\(xy = 6\\) and \\(x + y = 5\\).', options: ['\\(x = 2, y = 3\\) or \\(x = 3, y = 2\\)', '\\(x = 1, y = 6\\) or \\(x = 6, y = 1\\)', '\\(x = 2, y = 3\\) only', '\\(x = 3, y = 2\\) only'], answer: 0 },
      { q: 'Solve \\(\\dfrac{2}{x} \\leq 1\\) for \\(x > 0\\).', options: ['\\(x \\geq 2\\)', '\\(0 < x \\leq 2\\)', '\\(x \\leq 2\\)', '\\(x > 2\\)'], answer: 0 },
      { q: 'If \\(|x - a| < b\\), the solution is:', options: ['\\(a - b < x < a + b\\)', '\\(x < a - b\\) or \\(x > a + b\\)', '\\(-b < x < b\\)', '\\(a < x < b\\)'], answer: 0 },
    ],
    red: [
      { q: 'Solve \\(|x^2 - 3x - 4| = 4\\).', options: ['\\(x = 0, 4, \\frac{3\\pm\\sqrt{17}}{2}\\) combined as \\(x=0, x=4, x=\\frac{3+\\sqrt{17}}{2}, x=\\frac{3-\\sqrt{17}}{2}\\)','\\(x=0\\) or \\(x=4\\)','\\(x=4\\) or \\(x=-1\\)','\\(x = \\pm 4\\)'], answer: 0 },
      { q: 'For \\(f(x) = \\dfrac{x+3}{x-1}\\), solve \\(f(x) > 2\\).', options: ['\\(1 < x < 5\\)','\\(x > 5\\) or \\(x < 1\\)','\\(x > 5\\)','\\(x < 5\\)'], answer: 0 },
      { q: 'Find all solutions to \\(x^2 + y^2 = 25\\) and \\(y = x + 1\\) where both coordinates are integers.', options: ['\\((3,4)\\) and \\((-4,-3)\\)','\\((3,4)\\) only','\\((4,3)\\) and \\((-3,-4)\\)','\\((3,4)\\) and \\((-3,-4)\\)'], answer: 0 },
      { q: 'Solve \\(|2x-1| + |x+1| = 4\\).', options: ['\\(x = 1\\) or \\(x = -\\frac{5}{3}\\)','\\(x = \\frac{4}{3}\\) or \\(x = -2\\)','\\(x = 2\\) or \\(x = -2\\)','\\(x = \\frac{4}{3}\\) or \\(x = -\\frac{4}{3}\\)'], answer: 1 },
      { q: 'The system \\(y = x^2 - k\\) and \\(y = 3x\\) has no real intersection. The range of \\(k\\) is:', options: ['\\(k < -\\frac{9}{4}\\)','\\(k > -\\frac{9}{4}\\)','\\(k < \\frac{9}{4}\\)','\\(k > \\frac{9}{4}\\)'], answer: 0 },
      { q: 'Find the set of values of \\(x\\) satisfying \\(x^2 < 9\\) and \\(x^2 - x - 6 \\geq 0\\).', options: ['\\(x \\leq -2\\) or \\(x \\geq 3\\)','\\(-3 < x < -2\\)','\\(-3 < x \\leq -2\\)','\\(-2 \\leq x < 3\\)'], answer: 2 },
      { q: 'Solve \\(\\dfrac{1}{|x|} < 2\\).', options: ['\\(|x| > \\frac{1}{2}\\), i.e., \\(x > \\frac{1}{2}\\) or \\(x < -\\frac{1}{2}\\)','\\(-\\frac{1}{2} < x < \\frac{1}{2}\\)','\\(x > \\frac{1}{2}\\)','\\(x < \\frac{1}{2}\\)'], answer: 0 },
    ]
  },

  'P4': {
    name: 'Graphs and Transformations',
    green: [
      { q: 'The transformation \\(y = f(x) + 3\\) moves the graph:', options: ['Up by 3', 'Right by 3', 'Down by 3', 'Left by 3'], answer: 0 },
      { q: 'The transformation \\(y = f(x - 2)\\) moves the graph:', options: ['Right by 2', 'Left by 2', 'Up by 2', 'Down by 2'], answer: 0 },
      { q: 'Which equation represents a reflection of \\(y = f(x)\\) in the x-axis?', options: ['\\(y = -f(x)\\)', '\\(y = f(-x)\\)', '\\(y = f(x) + 1\\)', '\\(y = -f(-x)\\)'], answer: 0 },
      { q: 'The graph \\(y = x^3\\) passes through which of these points?', options: ['\\((-2, -8)\\)', '\\((-2, 8)\\)', '\\((2, 6)\\)', '\\((0, 1)\\)'], answer: 0 },
      { q: 'The asymptotes of \\(y = \\dfrac{1}{x}\\) are:', options: ['\\(x = 0\\) and \\(y = 0\\)', '\\(x = 1\\) and \\(y = 1\\)', '\\(x = 0\\) only', '\\(y = x\\)'], answer: 0 },
      { q: '\\(y = 2f(x)\\) is a:', options: ['Vertical stretch by factor 2', 'Horizontal stretch by factor 2', 'Vertical stretch by factor \\(\\frac{1}{2}\\)', 'Horizontal compression by factor 2'], answer: 0 },
      { q: 'If \\(f(x) = x^2\\) and \\(g(x) = f(x+1) - 4\\), the vertex of \\(g\\) is:', options: ['\\((-1, -4)\\)', '\\((1, -4)\\)', '\\((-1, 4)\\)', '\\((1, 4)\\)'], answer: 0 },
      { q: 'The graph \\(y = |x|\\) has a minimum at:', options: ['\\((0, 0)\\)', '\\((1, 0)\\)', '\\((0, 1)\\)', 'It has no minimum'], answer: 0 },
      { q: '\\(y = f(2x)\\) is a horizontal stretch by scale factor:', options: ['\\(\\frac{1}{2}\\)', '2', '\\(-\\frac{1}{2}\\)', '\\(-2\\)'], answer: 0 },
      { q: 'A translation of \\(\\begin{pmatrix}3\\\\-1\\end{pmatrix}\\) maps \\(y = f(x)\\) to:', options: ['\\(y = f(x-3) - 1\\)', '\\(y = f(x+3) + 1\\)', '\\(y = f(x-3) + 1\\)', '\\(y = f(x+3) - 1\\)'], answer: 0 },
      { q: 'The graph of \\(y = \\dfrac{1}{x^2}\\) is symmetric about:', options: ['The y-axis', 'The x-axis', 'The line \\(y = x\\)', 'The origin'], answer: 0 },
      { q: 'What is the effect of \\(y = f(-x)\\) on the graph of \\(y = f(x)\\)?', options: ['Reflection in the y-axis', 'Reflection in the x-axis', 'Rotation 180°', 'Reflection in \\(y = x\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Describe the single transformation mapping \\(y = x^2\\) to \\(y = 4x^2\\).', options: ['Vertical stretch by factor 4', 'Horizontal stretch by factor \\(\\frac{1}{2}\\)', 'Both A and B are equivalent descriptions', 'Vertical translation up by 4'], answer: 2 },
      { q: 'The curve \\(y = f(x)\\) passes through \\((3, 7)\\). Where does \\(y = f(2x) + 1\\) pass?', options: ['\\((\\frac{3}{2}, 8)\\)', '\\((6, 8)\\)', '\\((3, 8)\\)', '\\((\\frac{3}{2}, 7)\\)'], answer: 0 },
      { q: 'What is the equation of \\(y = \\sqrt{x}\\) after a reflection in the y-axis followed by translation left by 2?', options: ['\\(y = \\sqrt{-x-2}\\)', '\\(y = \\sqrt{x+2}\\)', '\\(y = -\\sqrt{x+2}\\)', '\\(y = \\sqrt{-x+2}\\)'], answer: 0 },
      { q: 'The graph \\(y = \\dfrac{1}{x-3} + 2\\) has asymptotes:', options: ['\\(x = 3\\) and \\(y = 2\\)', '\\(x = -3\\) and \\(y = -2\\)', '\\(x = 3\\) and \\(y = 0\\)', '\\(x = 0\\) and \\(y = 2\\)'], answer: 0 },
      { q: 'The transformations applied to \\(y = \\sin x\\) to get \\(y = 3\\sin(2x) - 1\\) in order are:', options: ['Horizontal squeeze by \\(\\frac{1}{2}\\), vertical stretch by 3, translate down 1', 'Vertical stretch by 3, horizontal squeeze by \\(\\frac{1}{2}\\), translate down 1', 'Translate down 1, horizontal squeeze by \\(\\frac{1}{2}\\), vertical stretch by 3', 'Horizontal stretch by 2, vertical stretch by 3, translate down 1'], answer: 0 },
      { q: 'Which function is an even function?', options: ['\\(f(x) = x^4 - 3x^2 + 1\\)', '\\(f(x) = x^3 + x\\)', '\\(f(x) = x^2 + x\\)', '\\(f(x) = \\sin x\\)'], answer: 0 },
      { q: 'The curve \\(y = x^2 - 4\\) is reflected in the x-axis. Its equation becomes:', options: ['\\(y = -x^2 + 4\\)', '\\(y = x^2 + 4\\)', '\\(y = 4 - x^2\\)', 'Both A and C are the same'], answer: 3 },
      { q: 'How many intersections do \\(y = x^2 - 2\\) and \\(y = -x^2 + 2\\) have?', options: ['2', '0', '1', '4'], answer: 0 },
      { q: 'The graph \\(y = f(x)\\) has a maximum at \\((2, 5)\\). Where is the maximum of \\(y = -f(x - 1)\\)?', options: ['\\((3, -5)\\)', '\\((1, -5)\\)', '\\((3, 5)\\)', '\\((1, 5)\\)'], answer: 0 },
      { q: 'The equation \\(y = \\dfrac{k}{x}\\) where \\(k < 0\\) has its two branches in quadrants:', options: ['2 and 4', '1 and 3', '1 and 2', '3 and 4'], answer: 0 },
      { q: 'Which transformation maps \\(y = \\cos x\\) to \\(y = \\cos(x + 90°)\\)?', options: ['Translation left by 90°', 'Translation right by 90°', 'Horizontal stretch by 90', 'Vertical translation by 90'], answer: 0 },
      { q: 'The range of \\(y = 3\\sin x + 1\\) is:', options: ['\\(-2 \\leq y \\leq 4\\)', '\\(-3 \\leq y \\leq 3\\)', '\\(0 \\leq y \\leq 4\\)', '\\(-1 \\leq y \\leq 3\\)'], answer: 0 },
    ],
    red: [
      { q: 'A curve has equation \\(y = f(x)\\). After applying \\(y = af(x+b) + c\\), the point \\((1,2)\\) maps to \\((3, 7)\\). If \\(b = -2\\) and \\(c = 3\\), find \\(a\\).', options: ['1','4','\\(\\frac{1}{2}\\)','2'], answer: 3 },
      { q: 'The graph \\(y = x^2 - 4x + 3\\) is reflected in \\(y = 0\\) then translated by \\(\\begin{pmatrix}0\\\\-1\\end{pmatrix}\\). Its equation is:', options: ['\\(y = -x^2 + 4x - 4\\)','\\(y = -x^2 + 4x - 2\\)','\\(y = x^2 - 4x + 4\\)','\\(y = -x^2 + 4x - 3\\)'], answer: 0 },
      { q: 'The function \\(f(x) = \\dfrac{1}{(x-2)^2} + 1\\) has range:', options: ['\\(y > 1\\)','\\(y \\geq 1\\)','\\(y > 0\\)','\\(y \\geq 0\\)'], answer: 0 },
      { q: 'The transformations that map \\(y = x^3\\) to \\(y = 8x^3 + 1\\) are:', options: ['Vertical stretch by 8, horizontal stretch by \\(\\frac{1}{2}\\)','Vertical stretch by 8, translate up 1','Both A and B give the same curve','Horizontal stretch by \\(\\frac{1}{2}\\), translate up 1'], answer: 2 },
      { q: 'Given \\(y = f(x)\\) has exactly 3 roots and \\(y = f(|x|)\\) has exactly 5 roots, what can be deduced?', options: ['Exactly one root of \\(f\\) is positive and non-zero','Two roots of \\(f\\) are equal','All roots of \\(f\\) are positive','Exactly one root of \\(f\\) is zero'], answer: 0 },
      { q: 'The graph of \\(y = \\sin x\\) is stretched horizontally by factor 2 then translated right by \\(\\frac{\\pi}{4}\\). The resulting equation is:', options: ['\\(y = \\sin\\!\\left(\\frac{x}{2} - \\frac{\\pi}{4}\\right)\\)','\\(y = \\sin\\!\\left(2x - \\frac{\\pi}{4}\\right)\\)','\\(y = \\sin\\!\\left(\\frac{x}{2} - \\frac{\\pi}{8}\\right)\\)','\\(y = \\sin\\!\\left(\\frac{x-\\pi/4}{2}\\right)\\)'], answer: 3 },
    ]
  },

  'P5': {
    name: 'Straight Lines and Circles',
    green: [
      { q: 'Find the gradient of the line joining \\((1, 3)\\) and \\((4, 9)\\).', options: ['2', '3', '\\(\\frac{1}{2}\\)', '6'], answer: 0 },
      { q: 'Find the equation of the line with gradient 3 through \\((0, -2)\\).', options: ['\\(y = 3x - 2\\)', '\\(y = 3x + 2\\)', '\\(y = -2x + 3\\)', '\\(y = 3x\\)'], answer: 0 },
      { q: 'Two lines are perpendicular. One has gradient \\(\\frac{2}{3}\\). The other has gradient:', options: ['\\(-\\frac{3}{2}\\)', '\\(\\frac{3}{2}\\)', '\\(-\\frac{2}{3}\\)', '\\(\\frac{2}{3}\\)'], answer: 0 },
      { q: 'What is the midpoint of \\((2, 6)\\) and \\((8, -2)\\)?', options: ['\\((5, 2)\\)', '\\((3, 4)\\)', '\\((6, 4)\\)', '\\((5, 4)\\)'], answer: 0 },
      { q: 'What is the distance between \\((0,0)\\) and \\((3,4)\\)?', options: ['5', '7', '\\(\\sqrt{7}\\)', '\\(\\sqrt{25} = 5\\)... which equals 5'], answer: 0 },
      { q: 'The circle \\((x-2)^2 + (y+3)^2 = 16\\) has centre:', options: ['\\((2,-3)\\)', '\\((-2,3)\\)', '\\((2,3)\\)', '\\((-2,-3)\\)'], answer: 0 },
      { q: 'The radius of \\((x+1)^2 + (y-5)^2 = 25\\) is:', options: ['5', '25', '\\(\\sqrt{5}\\)', '10'], answer: 0 },
      { q: 'Two parallel lines have gradients:', options: ['Equal', 'Negative reciprocals', 'Sum to zero', 'Product equal to 1'], answer: 0 },
      { q: 'Find the y-intercept of \\(3x + 4y - 12 = 0\\).', options: ['3', '-3', '4', '-4'], answer: 0 },
      { q: 'The tangent to a circle at point P is always:', options: ['Perpendicular to the radius at P', 'Parallel to the radius at P', 'Equal in length to the radius', 'The same as the diameter'], answer: 0 },
      { q: 'The angle in a semicircle is always:', options: ['90°', '45°', '180°', '60°'], answer: 0 },
      { q: 'Convert \\(x^2 + y^2 - 4x + 6y - 3 = 0\\) to standard form. The centre is:', options: ['\\((2, -3)\\)', '\\((-2, 3)\\)', '\\((4, -6)\\)', '\\((2, 3)\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the equation of the perpendicular bisector of \\(A(1,2)\\) and \\(B(5,6)\\).', options: ['\\(y = -x + 7\\)', '\\(y = x + 1\\)', '\\(y = x - 1\\)', '\\(y = -x - 7\\)'], answer: 0 },
      { q: 'The tangent to \\((x-3)^2 + (y-1)^2 = 10\\) at \\((6, 2)\\) has equation:', options: ['\\(3x + y = 20\\)', '\\(x + 3y = 12\\)', '\\(3x - y = 16\\)', '\\(x + y = 8\\)'], answer: 0 },
      { q: 'Show that \\(A(0,4)\\), \\(B(3,8)\\), \\(C(6,4)\\) lie on a circle. What is the centre?', options: ['\\((3,4)\\)', '\\((0,4)\\)', '\\((3,6)\\)', '\\((4,3)\\)'], answer: 0 },
      { q: 'Find the length of the tangent from \\((5, 0)\\) to the circle \\(x^2 + y^2 = 9\\).', options: ['4', '5', '\\(\\sqrt{34}\\)', '\\(\\sqrt{16}=4\\)'], answer: 0 },
      { q: 'The line \\(y = 2x + k\\) is tangent to \\(x^2 + y^2 = 5\\). Find \\(k\\).', options: ['\\(k = \\pm 5\\)', '\\(k = \\pm \\sqrt{5}\\)', '\\(k = \\pm 10\\)', '\\(k = \\pm 2\\)'], answer: 0 },
      { q: 'Find the points where the line \\(y = x + 1\\) meets the circle \\(x^2 + y^2 = 13\\).', options: ['\\((2,3)\\) and \\((-3,-2)\\)', '\\((3,4)\\) and \\((-2,-1)\\)', '\\((2,3)\\) and \\((-2,-3)\\)', '\\((1,2)\\) and \\((-2,-1)\\)'], answer: 0 },
      { q: 'Two circles have equations \\(x^2+y^2=4\\) and \\((x-3)^2+y^2=4\\). The distance between their centres is:', options: ['3', '4', '6', '\\(\\sqrt{13}\\)'], answer: 0 },
      { q: 'If \\(AB\\) is a diameter of a circle with \\(A(1,3)\\) and \\(B(7,11)\\), what is the equation of the circle?', options: ['\\((x-4)^2 + (y-7)^2 = 25\\)', '\\((x-4)^2 + (y-7)^2 = 50\\)', '\\((x-4)^2 + (y-7)^2 = 5\\)', '\\((x-4)^2 + (y-7)^2 = 100\\)'], answer: 1 },
      { q: 'Three points \\(P(2,0)\\), \\(Q(0,2)\\), \\(R(4,4)\\) lie on a circle. The perpendicular bisector of PQ passes through:', options: ['\\((1,1)\\) with gradient 1', '\\((1,1)\\) with gradient \\(-1\\)', '\\((0,0)\\)', '\\((2,2)\\)'], answer: 0 },
      { q: 'A chord of a circle subtends a right angle at the centre. If the radius is 5, the chord length is:', options: ['\\(5\\sqrt{2}\\)', '10', '5', '\\(5\\sqrt{3}\\)'], answer: 0 },
      { q: 'Find the gradient of the line \\(4x - 3y + 6 = 0\\).', options: ['\\(\\dfrac{4}{3}\\)', '\\(-\\dfrac{4}{3}\\)', '\\(\\dfrac{3}{4}\\)', '4'], answer: 0 },
      { q: 'The point \\((a, a^2)\\) lies on the circle \\(x^2 + y^2 = 20\\). Find \\(a\\).', options: ['\\(a = 2\\) (since \\(4+16=20\\))', '\\(a = \\pm\\sqrt{10}\\)', '\\(a = 4\\)', '\\(a = \\pm 2\\)'], answer: 0 },
    ],
    red: [
      { q: 'The circles \\(x^2+y^2=25\\) and \\((x-7)^2+y^2=4\\) do not intersect because:', options: ['They overlap','Distance < difference of radii','Distance between centres = 7, sum of radii = 7, so they are externally tangent','Distance between centres (7) > sum of radii (7) — they are externally tangent, actually equal, so they touch'], answer: 2 },
      { q: 'Find the equation of the circle passing through \\((0,0)\\), \\((4,0)\\) and \\((0,6)\\).', options: ['\\((x-2)^2+(y-3)^2=13\\)','\\((x-2)^2+(y-3)^2=25\\)','\\(x^2+y^2=52\\)','\\((x+2)^2+(y+3)^2=13\\)'], answer: 0 },
      { q: 'Two tangents are drawn from the point \\(P(5,0)\\) to the circle \\(x^2+y^2=9\\). The angle between the tangents is:', options: ['\\(2\\arctan\\dfrac{3}{4}\\)','\\(60°\\)','\\(2\\arcsin\\dfrac{3}{5}\\)','\\(\\arctan\\dfrac{4}{3}\\)'], answer: 0 },
      { q: 'The locus of points equidistant from \\(A(0,0)\\) and \\(B(4,6)\\) is the line:', options: ['\\(2x + 3y = 13\\)','\\(3x + 2y = 13\\)','\\(2x - 3y = 13\\)','\\(x + y = 5\\)'], answer: 0 },
      { q: 'Prove that \\(A(1,1)\\), \\(B(5,3)\\) and \\(C(3,7)\\) form a right-angled triangle by checking dot products. The right angle is at:', options: ['C','B','A','Not right-angled'], answer: 1 },
      { q: 'The radical axis of circles \\(x^2+y^2=16\\) and \\((x-5)^2+y^2=9\\) is the line on which tangents from external points are equal. Its equation is:', options: ['\\(10x = 32\\), i.e., \\(x = 3.2\\)','\\(x = 5\\)','\\(5x = 16\\)','\\(x = 2\\)'], answer: 0 },
    ]
  },

  'P6': {
    name: 'Trigonometric Ratios',
    green: [
      { q: 'What is \\(\\sin 30°\\)?', options: ['\\(\\dfrac{1}{2}\\)', '\\(\\dfrac{\\sqrt{3}}{2}\\)', '\\(\\dfrac{\\sqrt{2}}{2}\\)', '1'], answer: 0 },
      { q: 'What is \\(\\cos 60°\\)?', options: ['\\(\\dfrac{1}{2}\\)', '\\(\\dfrac{\\sqrt{3}}{2}\\)', '1', '0'], answer: 0 },
      { q: 'What is \\(\\tan 45°\\)?', options: ['1', '\\(\\sqrt{3}\\)', '\\(\\dfrac{1}{\\sqrt{3}}\\)', '0'], answer: 0 },
      { q: 'In a right triangle with hypotenuse 10 and opposite side 6, find \\(\\sin\\theta\\).', options: ['0.6', '0.8', '0.75', '\\(\\dfrac{6}{8}\\)'], answer: 0 },
      { q: 'The sine rule is used when you know:', options: ['Two sides and a non-included angle, or two angles and one side', 'Three sides only', 'Two sides and the included angle', 'One angle only'], answer: 0 },
      { q: 'The cosine rule \\(a^2 = b^2 + c^2 - 2bc\\cos A\\) is used when you know:', options: ['Two sides and the included angle', 'Two angles and one side', 'Three angles', 'One side only'], answer: 0 },
      { q: 'Find the area of a triangle with sides 5 and 8 and included angle 30°.', options: ['10', '20', '\\(\\frac{1}{2} \\times 5 \\times 8 = 20\\)', '5'], answer: 0 },
      { q: 'In which quadrant is \\(\\sin\\theta < 0\\) and \\(\\cos\\theta > 0\\)?', options: ['Q4 (270°–360°)', 'Q1', 'Q2', 'Q3'], answer: 0 },
      { q: 'What is \\(\\sin 150°\\)?', options: ['\\(\\dfrac{1}{2}\\)', '\\(-\\dfrac{1}{2}\\)', '\\(\\dfrac{\\sqrt{3}}{2}\\)', '\\(-\\dfrac{\\sqrt{3}}{2}\\)'], answer: 0 },
      { q: 'The period of \\(y = \\sin x\\) (in degrees) is:', options: ['360°', '180°', '90°', '720°'], answer: 0 },
      { q: 'What is \\(\\cos 0°\\)?', options: ['1', '0', '\\(-1\\)', '\\(\\dfrac{1}{2}\\)'], answer: 0 },
      { q: 'Using SOHCAHTOA, if \\(\\tan\\theta = \\frac{3}{4}\\) in a right triangle, and the adjacent = 4, the opposite is:', options: ['3', '5', '7', '\\(\\sqrt{7}\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Solve \\(\\sin\\theta = \\frac{\\sqrt{3}}{2}\\) for \\(0° \\leq \\theta \\leq 360°\\).', options: ['\\(60°\\) and \\(120°\\)', '\\(30°\\) and \\(150°\\)', '\\(60°\\) and \\(300°\\)', '\\(30°\\) and \\(330°\\)'], answer: 0 },
      { q: 'In triangle ABC, \\(a = 7\\), \\(b = 9\\), \\(C = 50°\\). Find \\(c\\) to 3 s.f.', options: ['7.10', '8.16', '6.86', '7.55'], answer: 0 },
      { q: 'Find all solutions of \\(\\cos\\theta = -\\frac{1}{2}\\) for \\(0° \\leq \\theta < 360°\\).', options: ['120° and 240°', '60° and 300°', '120° and 300°', '150° and 210°'], answer: 0 },
      { q: 'The ambiguous case of the sine rule arises when:', options: ['Two sides and a non-included acute angle are given and the shorter side is opposite the given angle', 'Two angles and one side are given', 'Three sides are given', 'The included angle exceeds 90°'], answer: 0 },
      { q: 'Solve \\(\\tan\\theta = -1\\) for \\(0° \\leq \\theta \\leq 360°\\).', options: ['135° and 315°', '45° and 225°', '135° and 225°', '45° and 135°'], answer: 0 },
      { q: 'A triangle has sides \\(a = 5\\), \\(b = 7\\), \\(c = 9\\). Find angle \\(C\\) to the nearest degree.', options: ['84°', '76°', '90°', '92°'], answer: 0 },
      { q: 'Express \\(\\cos(180° + x)\\) in terms of \\(\\cos x\\).', options: ['\\(-\\cos x\\)', '\\(\\cos x\\)', '\\(-\\sin x\\)', '\\(\\sin x\\)'], answer: 0 },
      { q: 'The area of triangle PQR with \\(p = 6\\), \\(q = 8\\) and \\(\\angle R = 60°\\) is:', options: ['\\(12\\sqrt{3}\\)', '24', '\\(24\\sqrt{3}\\)', '12'], answer: 0 },
      { q: 'Solve \\(2\\sin\\theta - 1 = 0\\) for \\(0 \\leq \\theta \\leq 2\\pi\\).', options: ['\\(\\theta = \\dfrac{\\pi}{6}\\) or \\(\\dfrac{5\\pi}{6}\\)', '\\(\\theta = \\dfrac{\\pi}{3}\\) or \\(\\dfrac{2\\pi}{3}\\)', '\\(\\theta = \\dfrac{\\pi}{6}\\) or \\(\\dfrac{7\\pi}{6}\\)', '\\(\\theta = \\dfrac{5\\pi}{6}\\) or \\(\\dfrac{7\\pi}{6}\\)'], answer: 0 },
      { q: 'Which identity is always true?', options: ['\\(\\sin^2\\theta + \\cos^2\\theta = 1\\)', '\\(\\sin\\theta = \\cos(90° + \\theta)\\)', '\\(\\tan\\theta = \\sin\\theta + \\cos\\theta\\)', '\\(\\cos^2\\theta = 1 + \\sin^2\\theta\\)'], answer: 0 },
      { q: 'In triangle ABC, \\(A = 35°\\), \\(C = 80°\\), \\(a = 10\\). Find \\(c\\).', options: ['\\(\\dfrac{10\\sin 80°}{\\sin 35°} \\approx 17.2\\)', '\\(\\dfrac{10\\sin 35°}{\\sin 80°} \\approx 5.8\\)', '\\(\\dfrac{10\\sin 65°}{\\sin 35°}\\)', '17.2 × 2'], answer: 0 },
      { q: 'The maximum value of \\(3\\cos(2x) - 1\\) is:', options: ['2', '4', '3', '-4'], answer: 0 },
    ],
    red: [
      { q: 'Solve \\(\\sin 2\\theta = \\cos\\theta\\) for \\(0° \\leq \\theta \\leq 360°\\).', options: ['\\(\\theta = 30°, 150°\\)','\\(\\theta = 30°, 90°, 150°, 270°\\)','\\(\\theta = 90°, 270°\\)','\\(\\theta = 45°, 135°, 225°, 315°\\)'], answer: 1 },
      { q: 'Triangle ABC has \\(a = 5\\), \\(b = 8\\), \\(A = 30°\\). How many triangles are possible?', options: ['Cannot determine','None','One','Two (ambiguous case)'], answer: 3 },
      { q: 'Find the exact value of \\(\\sin 75°\\).', options: ['\\(\\dfrac{\\sqrt{6}+\\sqrt{2}}{4}\\)','\\(\\dfrac{\\sqrt{3}+1}{4}\\)','\\(\\dfrac{\\sqrt{6}-\\sqrt{2}}{4}\\)','\\(\\dfrac{\\sqrt{2}+1}{2}\\)'], answer: 0 },
      { q: 'In triangle ABC, \\(\\angle A = 120°\\), \\(b = 5\\), \\(c = 7\\). Find \\(a\\).', options: ['\\(\\sqrt{109-35} = \\sqrt{74}\\)','\\(\\sqrt{74}\\)','\\(\\sqrt{25+49+35} = \\sqrt{109}\\)','\\(\\sqrt{109}\\)'], answer: 3 },
      { q: 'Solve \\(4\\sin^2\\theta - 1 = 0\\) for \\(0 \\leq \\theta < 2\\pi\\), giving all solutions.', options: ['\\(\\dfrac{\\pi}{6}, \\dfrac{5\\pi}{6}, \\dfrac{7\\pi}{6}, \\dfrac{11\\pi}{6}\\)','\\(\\dfrac{\\pi}{6}, \\dfrac{5\\pi}{6}\\)','\\(\\dfrac{\\pi}{3}, \\dfrac{2\\pi}{3}, \\dfrac{4\\pi}{3}, \\dfrac{5\\pi}{3}\\)','\\(\\dfrac{\\pi}{6}, \\dfrac{7\\pi}{6}\\)'], answer: 0 },
      { q: 'The area of a regular hexagon with side length \\(a\\) is:', options: ['\\(\\dfrac{3a^2}{2}\\)','\\(3a^2\\)','\\(6a^2\\)','\\(\\dfrac{3\\sqrt{3}}{2}a^2\\)'], answer: 3 },
    ]
  }
};
