const EDEXCEL_MCQ_P7_P11 = {

  'P7': {
    name: 'Trigonometric Identities and Equations',
    green: [
      { q: 'Which identity is correct?', options: ['\\(\\sin^2\\theta + \\cos^2\\theta \\equiv 1\\)', '\\(\\sin^2\\theta - \\cos^2\\theta \\equiv 1\\)', '\\(\\sin\\theta \\cdot \\cos\\theta \\equiv 1\\)', '\\(\\sin^2\\theta + \\cos^2\\theta \\equiv 0\\)'], answer: 0 },
      { q: 'What is \\(\\tan\\theta\\) in terms of \\(\\sin\\theta\\) and \\(\\cos\\theta\\)?', options: ['\\(\\dfrac{\\sin\\theta}{\\cos\\theta}\\)', '\\(\\dfrac{\\cos\\theta}{\\sin\\theta}\\)', '\\(\\sin\\theta \\cdot \\cos\\theta\\)', '\\(\\dfrac{1}{\\sin\\theta}\\)'], answer: 0 },
      { q: 'In which quadrants is \\(\\sin\\theta\\) positive?', options: ['1st and 2nd', '1st and 4th', '2nd and 3rd', '3rd and 4th'], answer: 0 },
      { q: 'The principal value of \\(\\sin^{-1}(0.5)\\) in degrees is:', options: ['30°', '60°', '150°', '45°'], answer: 0 },
      { q: 'Solve \\(\\cos x = 0\\) for \\(0° \\leq x \\leq 360°\\). The solutions are:', options: ['90° and 270°', '0° and 180°', '45° and 315°', '60° and 300°'], answer: 0 },
      { q: 'Which expression equals \\(1 - \\sin^2\\theta\\)?', options: ['\\(\\cos^2\\theta\\)', '\\(\\cos\\theta\\)', '\\(\\tan^2\\theta\\)', '\\(-\\cos^2\\theta\\)'], answer: 0 },
      { q: 'In the CAST diagram, which letter occupies the 4th quadrant (270° to 360°)?', options: ['C', 'A', 'S', 'T'], answer: 0 },
      { q: 'Solve \\(\\tan x = 1\\) for \\(0° \\leq x \\leq 360°\\). One solution is 45°. The other is:', options: ['225°', '135°', '315°', '180°'], answer: 0 },
      { q: 'For the equation \\(2\\sin x - 1 = 0\\), the value of \\(\\sin x\\) is:', options: ['\\(\\dfrac{1}{2}\\)', '\\(2\\)', '\\(-\\dfrac{1}{2}\\)', '\\(1\\)'], answer: 0 },
      { q: '\\(\\cos(360° - x)\\) is equal to:', options: ['\\(\\cos x\\)', '\\(-\\cos x\\)', '\\(\\sin x\\)', '\\(-\\sin x\\)'], answer: 0 },
      { q: 'If \\(\\sin\\theta = -\\frac{\\sqrt{3}}{2}\\), which quadrants could \\(\\theta\\) lie in (for \\(0° \\leq \\theta \\leq 360°\\))?', options: ['3rd and 4th', '1st and 2nd', '2nd and 3rd', '1st and 4th'], answer: 0 },
      { q: 'What is \\(\\sin(180° - x)\\) equal to?', options: ['\\(\\sin x\\)', '\\(-\\sin x\\)', '\\(\\cos x\\)', '\\(-\\cos x\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Solve \\(2\\sin^2 x - \\sin x - 1 = 0\\) for \\(0° \\leq x \\leq 360°\\). The solutions are:', options: ['90°, 210°, 330°', '30°, 150°, 270°', '60°, 120°, 240°', '45°, 135°, 225°'], answer: 0 },
      { q: 'Which identity follows from dividing \\(\\sin^2\\theta + \\cos^2\\theta = 1\\) by \\(\\cos^2\\theta\\)?', options: ['\\(\\tan^2\\theta + 1 = \\sec^2\\theta\\)', '\\(1 + \\tan^2\\theta = \\csc^2\\theta\\)', '\\(\\sec^2\\theta - 1 = \\cos^2\\theta\\)', '\\(\\tan^2\\theta = \\sec^2\\theta + 1\\)'], answer: 0 },
      { q: 'Solve \\(\\sin(2x) = \\frac{1}{2}\\) for \\(0° \\leq x \\leq 180°\\). The solutions are:', options: ['15° and 75°', '30° and 60°', '15° and 165°', '30° and 150°'], answer: 0 },
      { q: 'Show that \\(\\frac{1 - \\cos^2\\theta}{\\sin\\theta}\\) simplifies to:', options: ['\\(\\sin\\theta\\)', '\\(\\cos\\theta\\)', '\\(\\tan\\theta\\)', '\\(1\\)'], answer: 0 },
      { q: 'How many solutions does \\(\\cos x = -0.5\\) have in \\(0° \\leq x \\leq 360°\\)?', options: ['2', '1', '3', '4'], answer: 0 },
      { q: 'The expression \\(3\\sin x + 4\\cos x\\) can be written as \\(R\\sin(x+\\alpha)\\). What is \\(R\\)?', options: ['5', '7', '\\(\\sqrt{7}\\)', '\\(\\sqrt{5}\\)'], answer: 0 },
      { q: 'Solve \\(\\cos^2 x = \\frac{3}{4}\\) for \\(0° \\leq x \\leq 360°\\). The number of solutions is:', options: ['4', '2', '1', '3'], answer: 0 },
      { q: 'If \\(\\sin x = \\frac{3}{5}\\) and \\(x\\) is in the first quadrant, what is \\(\\cos x\\)?', options: ['\\(\\dfrac{4}{5}\\)', '\\(\\dfrac{3}{4}\\)', '\\(\\dfrac{4}{3}\\)', '\\(\\dfrac{5}{4}\\)'], answer: 0 },
      { q: 'Which equation is equivalent to \\(2\\cos^2\\theta + \\sin\\theta - 1 = 0\\) after using \\(\\cos^2\\theta = 1 - \\sin^2\\theta\\)?', options: ['\\(2\\sin^2\\theta - \\sin\\theta - 1 = 0\\)', '\\(2\\sin^2\\theta + \\sin\\theta - 1 = 0\\)', '\\(-2\\sin^2\\theta + \\sin\\theta + 1 = 0\\)', '\\(2\\sin^2\\theta + \\sin\\theta + 1 = 0\\)'], answer: 0 },
      { q: 'Solve \\(\\tan^2 x = 3\\) for \\(0° \\leq x \\leq 360°\\). The solutions include:', options: ['60°, 120°, 240°, 300°', '30°, 150°, 210°, 330°', '45°, 135°, 225°, 315°', '60°, 240°'], answer: 0 },
      { q: 'In solving \\(\\sin(x + 30°) = 0.8\\) for \\(0° \\leq x \\leq 360°\\), the substitution should set the interval for \\((x+30°)\\) as:', options: ['30° to 390°', '0° to 360°', '30° to 360°', '0° to 330°'], answer: 0 },
      { q: 'Prove: which step correctly starts \\(\\dfrac{\\cos^2\\theta}{1 + \\sin\\theta}\\)?', options: ['\\(\\dfrac{1-\\sin^2\\theta}{1+\\sin\\theta}\\)', '\\(\\dfrac{\\sin^2\\theta-1}{1+\\sin\\theta}\\)', '\\(\\dfrac{1-\\cos^2\\theta}{1+\\sin\\theta}\\)', '\\(\\dfrac{1+\\sin^2\\theta}{1+\\sin\\theta}\\)'], answer: 0 },
    ],
    red: [
      { q: 'The general solution of \\(\\sin\\theta = k\\) (in degrees) is:', options: ['\\(\\theta = \\pm \\sin^{-1}(k) + 360n\\)','\\(\\theta = \\sin^{-1}(k) + 180n\\)','\\(\\theta = \\sin^{-1}(k) + 360n\\) or \\(\\theta = 180 -','\\(\\theta = \\sin^{-1}(k) + 90n\\)'], answer: 2 },
      { q: 'Express \\(5\\sin x - 12\\cos x\\) in the form \\(R\\sin(x - \\alpha)\\). What is \\(R\\)?', options: ['13','17','\\(\\sqrt{119}\\)','7'], answer: 0 },
      { q: 'Solve \\(2\\sin^2 x + 3\\cos x - 3 = 0\\) for \\(0 \\leq x \\leq 2\\pi\\). The number of solutions is:', options: ['2','3','1','4'], answer: 1 },
      { q: 'If \\(\\cos 2x = 1 - 2\\sin^2 x\\), which quadratic in \\(\\sin x\\) is equivalent to \\(\\cos 2x + \\sin x = 0\\)?', options: ['\\(2\\sin^2 x - \\sin x - 1 = 0\\)','\\(2\\sin^2 x + \\sin x - 1 = 0\\)','\\(2\\sin^2 x - \\sin x + 1 = 0\\)','\\(\\sin^2 x - \\sin x - 1 = 0\\)'], answer: 0 },
      { q: 'The maximum value of \\(3\\sin x - 4\\cos x\\) is:', options: ['1','5','7','\\(\\sqrt{7}\\)'], answer: 1 },
      { q: 'Solve \\(\\sin\\theta = \\cos\\theta\\) for \\(0° \\leq \\theta \\leq 360°\\). The solutions are:', options: ['45° and 225°','45° and 135°','0° and 180°','135° and 315°'], answer: 0 },
    ]
  },

  'P8': {
    name: 'Exponentials and Logarithms',
    green: [
      { q: 'What is \\(\\log_2 8\\)?', options: ['3', '4', '2', '6'], answer: 0 },
      { q: '\\(\\log_a 1\\) equals:', options: ['0', '1', '\\(a\\)', 'undefined'], answer: 0 },
      { q: 'Which of the following is the definition of \\(\\log_a x = y\\)?', options: ['\\(a^y = x\\)', '\\(x^a = y\\)', '\\(y^a = x\\)', '\\(a^x = y\\)'], answer: 0 },
      { q: '\\(e^{\\ln 5}\\) equals:', options: ['5', '\\(\\ln 5\\)', '\\(e^5\\)', '1'], answer: 0 },
      { q: '\\(\\ln(e^3)\\) equals:', options: ['3', '\\(e^3\\)', '\\(3e\\)', '1'], answer: 0 },
      { q: '\\(\\log_a(xy)\\) equals:', options: ['\\(\\log_a x + \\log_a y\\)', '\\(\\log_a x \\cdot \\log_a y\\)', '\\(\\log_a x - \\log_a y\\)', '\\(\\log_a(x+y)\\)'], answer: 0 },
      { q: 'The graph of \\(y = e^x\\) always passes through:', options: ['\\((0, 1)\\)', '\\((1, 0)\\)', '\\((0, e)\\)', '\\((1, e^2)\\)'], answer: 0 },
      { q: 'What is the horizontal asymptote of \\(y = e^x\\)?', options: ['\\(y = 0\\)', '\\(x = 0\\)', '\\(y = 1\\)', 'None'], answer: 0 },
      { q: 'Using log laws: \\(\\log_3 9 + \\log_3 3\\) equals:', options: ['3', '2', '4', '\\(\\log_3 12\\)'], answer: 0 },
      { q: 'The graph of \\(y = \\ln x\\) is a reflection of \\(y = e^x\\) in:', options: ['\\(y = x\\)', '\\(y = 0\\)', '\\(x = 0\\)', '\\(y = -x\\)'], answer: 0 },
      { q: 'Solve \\(e^x = 1\\). The solution is:', options: ['\\(x = 0\\)', '\\(x = 1\\)', '\\(x = e\\)', '\\(x = -1\\)'], answer: 0 },
      { q: '\\(\\log_a(x^n)\\) equals:', options: ['\\(n\\log_a x\\)', '\\(\\log_a(nx)\\)', '\\((\\log_a x)^n\\)', '\\(\\log_a x + n\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Solve \\(3^x = 7\\). The exact answer is:', options: ['\\(x = \\dfrac{\\ln 7}{\\ln 3}\\)', '\\(x = \\dfrac{\\ln 3}{\\ln 7}\\)', '\\(x = \\ln\\!\\left(\\dfrac{7}{3}\\right)\\)', '\\(x = 7\\ln 3\\)'], answer: 0 },
      { q: 'Solve \\(e^{2x} - 5e^x + 6 = 0\\). The solutions are:', options: ['\\(x = \\ln 2\\) and \\(x = \\ln 3\\)', '\\(x = 2\\) and \\(x = 3\\)', '\\(x = \\ln 2\\) only', '\\(x = e^2\\) and \\(x = e^3\\)'], answer: 0 },
      { q: 'Solve \\(\\log_2(x+1) + \\log_2(x+3) = 3\\). The valid solution is:', options: ['\\(x = 1\\)', '\\(x = -5\\) and \\(x = 1\\)', '\\(x = -5\\)', '\\(x = 3\\)'], answer: 0 },
      { q: 'The change of base formula gives \\(\\log_5 20\\) as:', options: ['\\(\\dfrac{\\ln 20}{\\ln 5}\\)', '\\(\\dfrac{\\ln 5}{\\ln 20}\\)', '\\(\\ln 4\\)', '\\(\\dfrac{20}{5}\\)'], answer: 0 },
      { q: 'A model is \\(N = 200e^{0.05t}\\). The initial value (\\(t=0\\)) is:', options: ['200', '0.05', '\\(200e\\)', '\\(e^{200}\\)'], answer: 0 },
      { q: 'Which of the following is NOT a valid log law?', options: ['\\(\\log(x+y) = \\log x + \\log y\\)', '\\(\\log(xy) = \\log x + \\log y\\)', '\\(\\log(x^n) = n\\log x\\)', '\\(\\log\\left(\\frac{x}{y}\\right) = \\log x - \\log y\\)'], answer: 0 },
      { q: 'Solve \\(2\\ln x - \\ln(x-1) = \\ln 4\\). The solution is:', options: ['\\(x = 2\\)', '\\(x = 4\\)', '\\(x = 1\\)', '\\(x = 2\\) and \\(x = -2\\)'], answer: 0 },
      { q: 'If \\(y = Ab^x\\), plotting \\(\\ln y\\) against \\(x\\) gives a straight line with gradient:', options: ['\\(\\ln b\\)', '\\(b\\)', '\\(\\ln A\\)', '\\(A\\)'], answer: 0 },
      { q: 'The domain of \\(y = \\ln(2x - 3)\\) is:', options: ['\\(x > \\dfrac{3}{2}\\)', '\\(x > 3\\)', '\\(x > 0\\)', '\\(x \\geq \\dfrac{3}{2}\\)'], answer: 0 },
      { q: 'Solve \\(5e^{x-1} = 15\\). The solution is:', options: ['\\(x = 1 + \\ln 3\\)', '\\(x = \\ln 3 + e\\)', '\\(x = \\ln 15 - 1\\)', '\\(x = 3\\)'], answer: 0 },
      { q: 'If \\(P = P_0 e^{kt}\\) and \\(P = 2P_0\\) when \\(t = 10\\), then \\(k =\\)', options: ['\\(\\dfrac{\\ln 2}{10}\\)', '\\(\\dfrac{2}{10}\\)', '\\(10\\ln 2\\)', '\\(\\dfrac{1}{10\\ln 2}\\)'], answer: 0 },
      { q: 'Solve \\(\\ln(3x+1) = 2\\). The solution is:', options: ['\\(x = \\dfrac{e^2-1}{3}\\)', '\\(x = \\dfrac{e^2}{3}\\)', '\\(x = \\dfrac{e-1}{3}\\)', '\\(x = e^2 - 1\\)'], answer: 0 },
    ],
    red: [
      { q: 'A population satisfies \\(P = 500e^{kt}\\). After 20 years, \\(P = 1500\\). Find \\(k\\) exactly:', options: ['\\(k = \\dfrac{\\ln 3}{20}\\)','\\(k = \\dfrac{3}{20}\\)','\\(k = \\dfrac{\\ln 1500}{20}\\)','\\(k = \\dfrac{20}{\\ln 3}\\)'], answer: 0 },
      { q: 'Solve \\(e^{2x} - 3e^x - 4 = 0\\) exactly. The only valid solution is:', options: ['\\(x = \\ln(-1)\\)','\\(x = \\ln 4\\) and \\(x = \\ln(-1)\\)','\\(x = \\ln 4\\)','\\(x = 4\\)'], answer: 2 },
      { q: 'The curve \\(y = 3 + 2e^{-x}\\) has which asymptote?', options: ['\\(y = 3\\)','\\(y = 0\\)','\\(x = 0\\)','\\(y = 2\\)'], answer: 0 },
      { q: 'Solve \\(2^{x+1} = 3^{x-1}\\) exactly for \\(x\\):', options: ['\\(x = \\dfrac{\\ln 3 + \\ln 2}{\\ln 2 - \\ln 3}\\)','\\(x = \\dfrac{\\ln 3 - \\ln 2}{\\ln 2 + \\ln 3}\\)','\\(x = \\dfrac{\\ln 6}{\\ln(2/3)}\\)','\\(x = \\ln\\!\\left(\\dfrac{3}{2}\\right)\\)'], answer: 0 },
      { q: 'The graph of \\(y = e^x + e^{-x}\\) is symmetric about:', options: ['the \\(x\\)-axis','the origin','the line \\(y=x\\)','the \\(y\\)-axis'], answer: 3 },
      { q: 'If \\(\\log_a b = p\\) and \\(\\log_a c = q\\), then \\(\\log_a\\!\\left(\\dfrac{a^2 b}{c^3}\\right)\\) equals:', options: ['\\(2p - 3q\\)','\\(2 + p + 3q\\)','\\(2 + p - 3q\\)','\\(p - 3q + a^2\\)'], answer: 2 },
    ]
  },

  'P9': {
    name: 'Differentiation (Year 1)',
    green: [
      { q: 'Differentiate \\(y = x^5\\). The result is:', options: ['\\(5x^4\\)', '\\(x^6\\)', '\\(5x^6\\)', '\\(\\dfrac{x^6}{6}\\)'], answer: 0 },
      { q: 'Differentiate \\(y = 7\\). The result is:', options: ['0', '7', '1', '\\(7x\\)'], answer: 0 },
      { q: 'Differentiate \\(y = x^{-2}\\). The result is:', options: ['\\(-2x^{-3}\\)', '\\(-\\dfrac{x^{-1}}{1}\\)', '\\(2x^{-3}\\)', '\\(-2x^{-1}\\)'], answer: 0 },
      { q: 'If \\(f(x) = 3x^2 - 4x + 1\\), then \\(f\'(x) =\\)', options: ['\\(6x - 4\\)', '\\(3x - 4\\)', '\\(6x^2 - 4\\)', '\\(6x + 4\\)'], answer: 0 },
      { q: 'What does \\(\\dfrac{d}{dx}(e^x)\\) equal?', options: ['\\(e^x\\)', '\\(xe^{x-1}\\)', '\\(e^{x-1}\\)', '\\(e\\)'], answer: 0 },
      { q: 'What does \\(\\dfrac{d}{dx}(\\ln x)\\) equal?', options: ['\\(\\dfrac{1}{x}\\)', '\\(\\ln x\\)', '\\(x\\ln x\\)', '\\(-\\dfrac{1}{x^2}\\)'], answer: 0 },
      { q: 'The gradient of \\(y = x^3\\) at \\(x = 2\\) is:', options: ['12', '8', '6', '24'], answer: 0 },
      { q: 'What does \\(\\dfrac{d}{dx}(\\sin x)\\) equal?', options: ['\\(\\cos x\\)', '\\(-\\cos x\\)', '\\(-\\sin x\\)', '\\(\\sin x\\)'], answer: 0 },
      { q: 'A stationary point occurs when:', options: ['\\(f\'(x) = 0\\)', '\\(f(x) = 0\\)', '\\(f\'\'(x) = 0\\)', '\\(f\'(x) = 1\\)'], answer: 0 },
      { q: 'If \\(f\'\'(a) < 0\\) at a stationary point, it is a:', options: ['Local maximum', 'Local minimum', 'Point of inflection', 'Cannot tell'], answer: 0 },
      { q: 'Rewrite \\(\\dfrac{1}{\\sqrt{x}}\\) as a power of \\(x\\):', options: ['\\(x^{-1/2}\\)', '\\(x^{1/2}\\)', '\\(x^{-2}\\)', '\\(x^2\\)'], answer: 0 },
      { q: 'A function is increasing where:', options: ['\\(f\'(x) > 0\\)', '\\(f\'(x) < 0\\)', '\\(f(x) > 0\\)', '\\(f\'(x) = 0\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Differentiate \\(y = \\dfrac{3}{x^2} + 2\\sqrt{x}\\). The result is:', options: ['\\(-\\dfrac{6}{x^3} + \\dfrac{1}{\\sqrt{x}}\\)', '\\(-\\dfrac{6}{x} + \\dfrac{1}{\\sqrt{x}}\\)', '\\(\\dfrac{6}{x^3} + \\dfrac{1}{\\sqrt{x}}\\)', '\\(-\\dfrac{3}{x^3} + x^{-1/2}\\)'], answer: 0 },
      { q: 'The equation of the tangent to \\(y = x^2\\) at \\((3, 9)\\) is:', options: ['\\(y = 6x - 9\\)', '\\(y = 3x\\)', '\\(y = 6x + 9\\)', '\\(y = 9x - 6\\)'], answer: 0 },
      { q: 'Find the \\(x\\)-coordinates of the stationary points of \\(y = x^3 - 6x\\):', options: ['\\(x = \\pm\\sqrt{2}\\)', '\\(x = 0\\) and \\(x = 6\\)', '\\(x = \\pm 2\\)', '\\(x = \\pm \\sqrt{6}\\)'], answer: 0 },
      { q: 'Using first principles, the derivative of \\(f(x) = x^2\\) at \\(x = a\\) is found by:', options: ['\\(\\lim_{h\\to 0}\\dfrac{(a+h)^2 - a^2}{h}\\)', '\\(\\lim_{h\\to 0}\\dfrac{a^2 - (a+h)^2}{h}\\)', '\\(\\dfrac{(a+1)^2 - a^2}{1}\\)', '\\(\\lim_{a\\to 0}\\dfrac{(a+h)^2 - h^2}{a}\\)'], answer: 0 },
      { q: 'The gradient of the normal to \\(y = x^3\\) at \\(x = 1\\) is:', options: ['\\(-\\dfrac{1}{3}\\)', '\\(3\\)', '\\(-3\\)', '\\(\\dfrac{1}{3}\\)'], answer: 0 },
      { q: 'Find the interval where \\(f(x) = 2x^3 - 3x^2 - 12x\\) is decreasing:', options: ['\\(-1 < x < 2\\)', '\\(x < -1\\) and \\(x > 2\\)', '\\(-2 < x < 1\\)', '\\(0 < x < 4\\)'], answer: 0 },
      { q: 'If \\(y = x^4 - 8x^2\\), then \\(\\dfrac{d^2y}{dx^2}\\) equals:', options: ['\\(12x^2 - 16\\)', '\\(4x^3 - 16x\\)', '\\(12x^2 + 16\\)', '\\(4x^2 - 16\\)'], answer: 0 },
      { q: 'A curve has \\(\\dfrac{dy}{dx} = 3x^2 - k\\). If \\(x = 2\\) is a stationary point, then \\(k =\\)', options: ['12', '6', '\\(-12\\)', '4'], answer: 0 },
      { q: 'Differentiate \\(y = (2x+1)(x-3)\\) after expanding. The result is:', options: ['\\(4x - 5\\)', '\\(2x - 3\\)', '\\(4x + 1\\)', '\\(2x - 5\\)'], answer: 0 },
      { q: 'The second derivative \\(f\'\'(x)\\) of \\(f(x) = x^4\\) is:', options: ['\\(12x^2\\)', '\\(4x^3\\)', '\\(24x\\)', '\\(12x^3\\)'], answer: 0 },
      { q: 'A rectangle has perimeter 20 cm. If one side is \\(x\\), the area \\(A\\) equals:', options: ['\\(A = x(10-x)\\)', '\\(A = x(20-x)\\)', '\\(A = x(5-x)\\)', '\\(A = x^2\\)'], answer: 0 },
      { q: 'The point \\((2, 5)\\) lies on \\(y = x^2 + 1\\). The equation of the normal at this point is:', options: ['\\(y = -\\frac{1}{4}x + \\frac{11}{2}\\)', '\\(y = 4x - 3\\)', '\\(y = -4x + 13\\)', '\\(y = \\frac{1}{4}x + \\frac{11}{2}\\)'], answer: 0 },
    ],
    red: [
      { q: 'Using first principles, differentiate \\(f(x) = \\dfrac{1}{x}\\). The answer is:', options: ['\\(-\\dfrac{1}{x^2}\\)','\\(\\dfrac{1}{x^2}\\)','\\(\\ln x\\)','\\(-x^{-1}\\)'], answer: 0 },
      { q: 'A cylinder has volume \\(V = 500\\) cm³. Express the total surface area \\(S\\) in terms of radius \\(r\\) only, then find \\(r\\) for minimum \\(S\\):', options: ['\\(r = \\left(\\dfrac{250}{\\pi}\\right)^{1/3}\\)','\\(r = 5\\)','\\(r = \\left(\\dfrac{500}{\\pi}\\right)^{1/3}\\)','\\(r = \\dfrac{250}{\\pi}\\)'], answer: 0 },
      { q: 'A curve \\(C\\) has equation \\(y = x^3 - 3x + 2\\). The tangent at \\((-1, 4)\\) has equation:', options: ['\\(y = 0\\cdot x + 4\\)','\\(y = -3x + 1\\)','\\(y = 4\\)','\\(y = 3x + 7\\)'], answer: 0 },
      { q: 'A function has \\(f\'\'(a) = 0\\) at a stationary point. What additional test is needed?', options: ['Check the sign of \\(f\'(x)\\) either side of \\(x = a\\)','Check \\(f(a)\\)','Compute \\(f\'\'\'(a)\\)','No further test needed — it is a point of inflection'], answer: 0 },
      { q: 'The curve \\(y = ax^3 + bx\\) passes through \\((1, -2)\\) and has gradient 0 at \\(x = 1\\). Find \\(a\\) and \\(b\\):', options: ['\\(a = 2, b = -4\\)','\\(a = -2, b = 0\\)','\\(a = 1, b = -3\\)','\\(a = 2, b = 4\\)'], answer: 0 },
      { q: 'The rate of change of \\(y = x^3 - 5x^2 + 6x\\) is equal to 2 when:', options: ['\\(x = 1\\) only','\\(x = 2\\) or \\(x = 4\\)','\\(x = 0\\) or \\(x = 2\\)','\\(x = 1\\) or \\(x = 3\\)'], answer: 3 },
    ]
  },

  'P10': {
    name: 'Integration (Year 1)',
    green: [
      { q: '\\(\\displaystyle\\int x^3 \\, dx =\\)', options: ['\\(\\dfrac{x^4}{4} + C\\)', '\\(3x^2 + C\\)', '\\(x^4 + C\\)', '\\(\\dfrac{x^4}{3} + C\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int 5 \\, dx =\\)', options: ['\\(5x + C\\)', '\\(5 + C\\)', '\\(0\\)', '\\(\\dfrac{5}{x} + C\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int e^x \\, dx =\\)', options: ['\\(e^x + C\\)', '\\(xe^{x-1} + C\\)', '\\(e^{x+1} + C\\)', '\\(\\dfrac{e^x}{x} + C\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int \\dfrac{1}{x} \\, dx =\\)', options: ['\\(\\ln|x| + C\\)', '\\(-\\dfrac{1}{x^2} + C\\)', '\\(\\dfrac{1}{x^2} + C\\)', '\\(x^{-2} + C\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_1^3 2x \\, dx\\):', options: ['8', '4', '6', '10'], answer: 0 },
      { q: 'The area under \\(y = x^2\\) from \\(x = 0\\) to \\(x = 3\\) is:', options: ['9', '27', '3', '6'], answer: 0 },
      { q: 'If \\(\\dfrac{dy}{dx} = 4x\\) and \\(y = 7\\) when \\(x = 0\\), then \\(y =\\)', options: ['\\(2x^2 + 7\\)', '\\(4x^2 + 7\\)', '\\(2x + 7\\)', '\\(2x^2\\)'], answer: 0 },
      { q: 'Which is correct? \\(\\displaystyle\\int x^{-1/2} \\, dx =\\)', options: ['\\(2\\sqrt{x} + C\\)', '\\(-\\dfrac{1}{2}x^{-3/2} + C\\)', '\\(\\dfrac{x^{1/2}}{2} + C\\)', '\\(2x^{3/2} + C\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^2 (3x^2 - 2x) \\, dx\\):', options: ['4', '8', '0', '6'], answer: 0 },
      { q: 'The constant of integration \\(C\\) is needed in:', options: ['Indefinite integrals only', 'Definite integrals only', 'All integrals', 'Neither'], answer: 0 },
      { q: 'If the area below the x-axis gives a negative definite integral, the actual area is:', options: ['The absolute value of the integral', 'The negative of the integral', 'Zero', 'The integral squared'], answer: 0 },
      { q: '\\(\\displaystyle\\int \\cos x \\, dx =\\)', options: ['\\(\\sin x + C\\)', '\\(-\\sin x + C\\)', '\\(-\\cos x + C\\)', '\\(\\cos x + C\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Evaluate \\(\\displaystyle\\int_1^4 \\left(\\sqrt{x} + \\dfrac{1}{x^2}\\right)dx\\):', options: ['\\(\\dfrac{40}{12} + \\dfrac{3}{4}\\)', '\\(\\dfrac{14}{3} + \\dfrac{3}{4}\\)', '\\(\\dfrac{14}{3}\\)', '\\(\\dfrac{14}{3} - \\dfrac{3}{4}\\)'], answer: 0 },
      { q: 'Find the area between \\(y = x^2\\) and \\(y = x + 2\\):', options: ['\\(\\dfrac{9}{2}\\)', '\\(\\dfrac{3}{2}\\)', '\\(\\dfrac{7}{2}\\)', '\\(\\dfrac{5}{2}\\)'], answer: 0 },
      { q: 'Using the trapezium rule with 2 strips on \\(\\displaystyle\\int_0^2 e^x \\, dx\\), the estimate is:', options: ['\\(\\dfrac{1}{2}(1 + 2e + e^2)\\)', '\\(e^2 - 1\\)', '\\(1 + e^2\\)', '\\(\\dfrac{e^2 + 1}{2}\\)'], answer: 0 },
      { q: 'The trapezium rule gives an overestimate when the curve is:', options: ['Concave up (\\(f\'\'(x) > 0\\))', 'Concave down (\\(f\'\'(x) < 0\\))', 'Decreasing', 'A straight line'], answer: 0 },
      { q: 'Find \\(y\\) given \\(\\dfrac{dy}{dx} = 3x^2 - 2\\) and \\(y = 4\\) when \\(x = 1\\):', options: ['\\(y = x^3 - 2x + 5\\)', '\\(y = x^3 - 2x + 4\\)', '\\(y = 3x^3 - 2x + 3\\)', '\\(y = x^3 - 2x\\)'], answer: 0 },
      { q: 'The area enclosed between \\(y = \\sin x\\) and the x-axis from \\(0\\) to \\(2\\pi\\) is:', options: ['4', '0', '2', '\\(\\pi\\)'], answer: 0 },
      { q: 'In the trapezium rule with \\(n\\) strips, how many \\(y\\)-values are there?', options: ['\\(n+1\\)', '\\(n\\)', '\\(n-1\\)', '\\(2n\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int_2^5 \\dfrac{1}{x} \\, dx\\) in exact form:', options: ['\\(\\ln 5 - \\ln 2\\)', '\\(\\ln 3\\)', '\\(\\dfrac{3}{2}\\)', '\\(\\ln 10 - \\ln 4\\)'], answer: 0 },
      { q: 'A curve passes through \\((2, 3)\\) and \\(\\dfrac{dy}{dx} = kx\\). If the gradient at \\(x=2\\) is 6, find \\(k\\):', options: ['3', '6', '\\(\\dfrac{3}{2}\\)', '12'], answer: 0 },
      { q: 'Find the area between \\(y = x^2 - 4\\) and the x-axis (total area including below x-axis):', options: ['\\(\\dfrac{32}{3}\\)', '0', '\\(\\dfrac{16}{3}\\)', '\\(-\\dfrac{32}{3}\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_1^e \\dfrac{3}{x} \\, dx\\):', options: ['3', '\\(3e\\)', '\\(3\\ln e = 3\\)', '\\(3e - 3\\)'], answer: 0 },
      { q: 'The area between \\(y = x^2\\) and \\(y = 2x\\) is:', options: ['\\(\\dfrac{4}{3}\\)', '2', '\\(\\dfrac{8}{3}\\)', '\\(\\dfrac{2}{3}\\)'], answer: 0 },
    ],
    red: [
      { q: 'Find the total area bounded by \\(y = x^3 - x\\) and the x-axis:', options: ['\\(\\dfrac{1}{2}\\)','\\(\\dfrac{1}{4}\\)','\\(\\dfrac{1}{6}\\)','0'], answer: 0 },
      { q: 'Using the trapezium rule with 4 strips to estimate \\(\\displaystyle\\int_0^1 x^2 \\, dx\\), the estimate minus the exact value is:', options: ['Positive (overestimate)','Negative (underestimate)','Zero (exact)','Cannot determine'], answer: 0 },
      { q: 'Find the area between \\(y = x^3 - 3x^2\\) and \\(y = 0\\) from \\(x = 0\\) to \\(x = 3\\):', options: ['\\(\\dfrac{27}{4}\\)','0','\\(-\\dfrac{27}{4}\\)','27'], answer: 0 },
      { q: 'The area enclosed between \\(y = x^3\\) and \\(y = x\\) is:', options: ['\\(\\dfrac{1}{2}\\)','\\(\\dfrac{1}{4}\\)','1','0'], answer: 0 },
      { q: 'Find the value of \\(k\\) such that \\(\\displaystyle\\int_0^k (2x - 3) \\, dx = 4\\):', options: ['\\(k = 1 + \\sqrt{5}\\)','\\(k = 4\\)','\\(k = \\dfrac{7}{2}\\)','\\(k = 2\\)'], answer: 0 },
      { q: 'The region R is bounded by \\(y = e^x\\), \\(y = 1\\), and \\(x = 2\\). The area of R is:', options: ['\\(e^2 - 2\\)','\\(e^2 - 1\\)','\\(e^2 + 1\\)','\\(e^2 - 3\\)'], answer: 0 },
    ]
  },

  'P11': {
    name: 'Vectors (Year 1)',
    green: [
      { q: 'The magnitude of \\(\\mathbf{a} = 3\\mathbf{i} + 4\\mathbf{j}\\) is:', options: ['5', '7', '\\(\\sqrt{7}\\)', '12'], answer: 0 },
      { q: 'If \\(\\mathbf{a} = \\binom{2}{-1}\\) and \\(\\mathbf{b} = \\binom{3}{4}\\), then \\(\\mathbf{a} + \\mathbf{b} =\\)', options: ['\\(\\binom{5}{3}\\)', '\\(\\binom{1}{5}\\)', '\\(\\binom{5}{5}\\)', '\\(\\binom{-1}{5}\\)'], answer: 0 },
      { q: '\\(\\vec{AB}\\) equals:', options: ['\\(\\mathbf{b} - \\mathbf{a}\\)', '\\(\\mathbf{a} - \\mathbf{b}\\)', '\\(\\mathbf{a} + \\mathbf{b}\\)', '\\(-\\mathbf{b}\\)'], answer: 0 },
      { q: 'The unit vector in the direction of \\(\\binom{0}{5}\\) is:', options: ['\\(\\binom{0}{1}\\)', '\\(\\binom{0}{5}\\)', '\\(\\binom{0}{1/5}\\)', '\\(\\binom{1}{0}\\)'], answer: 0 },
      { q: 'Scalar multiplication: \\(3\\binom{2}{-1} =\\)', options: ['\\(\\binom{6}{-3}\\)', '\\(\\binom{5}{2}\\)', '\\(\\binom{6}{3}\\)', '\\(\\binom{3}{-3}\\)'], answer: 0 },
      { q: 'The midpoint of A(2,6) and B(8,2) has position vector:', options: ['\\(5\\mathbf{i} + 4\\mathbf{j}\\)', '\\(3\\mathbf{i} + 2\\mathbf{j}\\)', '\\(6\\mathbf{i} + 8\\mathbf{j}\\)', '\\(5\\mathbf{i} - 4\\mathbf{j}\\)'], answer: 0 },
      { q: 'Two vectors are parallel if:', options: ['One is a scalar multiple of the other', 'They have equal magnitudes', 'They point in the same direction only', 'Their sum is zero'], answer: 0 },
      { q: '\\(|\\mathbf{a} - \\mathbf{b}|\\) represents:', options: ['The distance between the tips of \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) from origin', 'The sum of magnitudes', 'Always zero', 'The angle between vectors'], answer: 0 },
      { q: 'If \\(\\mathbf{a} = 2\\mathbf{i} - 3\\mathbf{j}\\), then \\(-\\mathbf{a} =\\)', options: ['\\(-2\\mathbf{i} + 3\\mathbf{j}\\)', '\\(2\\mathbf{i} + 3\\mathbf{j}\\)', '\\(-2\\mathbf{i} - 3\\mathbf{j}\\)', '\\(3\\mathbf{i} - 2\\mathbf{j}\\)'], answer: 0 },
      { q: '\\(|\\mathbf{i}|\\) (magnitude of unit vector \\(\\mathbf{i}\\)) equals:', options: ['1', '0', '\\(\\sqrt{2}\\)', '2'], answer: 0 },
      { q: 'A has position vector \\(\\binom{1}{3}\\), B has position vector \\(\\binom{5}{7}\\). \\(\\vec{AB} =\\)', options: ['\\(\\binom{4}{4}\\)', '\\(\\binom{-4}{-4}\\)', '\\(\\binom{6}{10}\\)', '\\(\\binom{4}{-4}\\)'], answer: 0 },
      { q: 'The vector \\(\\binom{6}{8}\\) has magnitude:', options: ['10', '14', '2', '\\(\\sqrt{100}\\) (= 10)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the unit vector in the direction of \\(5\\mathbf{i} - 12\\mathbf{j}\\):', options: ['\\(\\dfrac{5}{13}\\mathbf{i} - \\dfrac{12}{13}\\mathbf{j}\\)', '\\(\\dfrac{5}{17}\\mathbf{i} - \\dfrac{12}{17}\\mathbf{j}\\)', '\\(5\\mathbf{i} - 12\\mathbf{j}\\)', '\\(\\dfrac{1}{13}(5\\mathbf{i} + 12\\mathbf{j})\\)'], answer: 0 },
      { q: 'Show that A(1,1), B(3,5), C(5,9) are collinear. Which statement is correct?', options: ['\\(\\vec{AB} = \\binom{2}{4}\\) and \\(\\vec{AC} = \\binom{4}{8} = 2\\vec{AB}\\)', '\\(\\vec{AB} = \\vec{BC}\\)', '\\(|AB| = |BC|\\)', '\\(\\vec{AB} + \\vec{BC} = 0\\)'], answer: 0 },
      { q: 'P divides AB in the ratio 3:1 where \\(\\mathbf{a} = \\binom{1}{2}\\), \\(\\mathbf{b} = \\binom{5}{6}\\). Find \\(\\vec{OP}\\):', options: ['\\(\\binom{4}{5}\\)', '\\(\\binom{3}{4}\\)', '\\(\\binom{2}{3}\\)', '\\(\\binom{4}{4}\\)'], answer: 0 },
      { q: 'If \\(\\vec{OA} = 2\\mathbf{i} + \\mathbf{j}\\) and \\(\\vec{OB} = 5\\mathbf{i} - 2\\mathbf{j}\\), then \\(|\\vec{AB}|\\) equals:', options: ['\\(\\sqrt{18} = 3\\sqrt{2}\\)', '\\(\\sqrt{9} = 3\\)', '\\(\\sqrt{25}\\)', '\\(\\sqrt{13}\\)'], answer: 0 },
      { q: 'OABC is a parallelogram with \\(\\vec{OA} = \\mathbf{a}\\) and \\(\\vec{OC} = \\mathbf{c}\\). The diagonal \\(\\vec{OB} =\\)', options: ['\\(\\mathbf{a} + \\mathbf{c}\\)', '\\(\\mathbf{a} - \\mathbf{c}\\)', '\\(\\mathbf{c} - \\mathbf{a}\\)', '\\(2\\mathbf{a} + \\mathbf{c}\\)'], answer: 0 },
      { q: 'Which pair of vectors is parallel?', options: ['\\(2\\mathbf{i}+6\\mathbf{j}\\) and \\(\\mathbf{i}+3\\mathbf{j}\\)', '\\(\\mathbf{i}+2\\mathbf{j}\\) and \\(2\\mathbf{i}+\\mathbf{j}\\)', '\\(3\\mathbf{i}-\\mathbf{j}\\) and \\(-\\mathbf{i}+3\\mathbf{j}\\)', '\\(\\mathbf{i}+\\mathbf{j}\\) and \\(\\mathbf{i}-\\mathbf{j}\\)'], answer: 0 },
      { q: '\\(\\vec{OA} = \\mathbf{a}\\), \\(\\vec{OB} = \\mathbf{b}\\), M is the midpoint of OA. Find \\(\\vec{BM}\\):', options: ['\\(\\dfrac{1}{2}\\mathbf{a} - \\mathbf{b}\\)', '\\(\\mathbf{a} - \\mathbf{b}\\)', '\\(\\dfrac{1}{2}(\\mathbf{a} + \\mathbf{b})\\)', '\\(\\mathbf{b} - \\dfrac{1}{2}\\mathbf{a}\\)'], answer: 0 },
      { q: 'Given \\(\\vec{PQ} = 3\\mathbf{a} - \\mathbf{b}\\) and \\(\\vec{PR} = 6\\mathbf{a} - 2\\mathbf{b}\\), which is true?', options: ['P, Q, R are collinear', 'PQ is perpendicular to PR', '|PQ| = |PR|', 'PQ and PR have equal directions only'], answer: 0 },
      { q: 'If \\(2\\mathbf{a} - 3\\mathbf{b} = \\binom{4}{6}\\) and \\(\\mathbf{b} = \\binom{2}{0}\\), find \\(\\mathbf{a}\\):', options: ['\\(\\binom{5}{3}\\)', '\\(\\binom{2}{3}\\)', '\\(\\binom{4}{3}\\)', '\\(\\binom{1}{3}\\)'], answer: 0 },
      { q: 'The vector from \\((3, -1)\\) to \\((-2, 4)\\) is:', options: ['\\(-5\\mathbf{i} + 5\\mathbf{j}\\)', '\\(5\\mathbf{i} - 5\\mathbf{j}\\)', '\\(\\mathbf{i} + 3\\mathbf{j}\\)', '\\(-5\\mathbf{i} - 5\\mathbf{j}\\)'], answer: 0 },
      { q: 'In triangle OAB, M is the midpoint of AB. Express \\(\\vec{OM}\\) in terms of \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\):', options: ['\\(\\dfrac{1}{2}(\\mathbf{a}+\\mathbf{b})\\)', '\\(\\dfrac{1}{2}(\\mathbf{b}-\\mathbf{a})\\)', '\\(\\mathbf{a}+\\mathbf{b}\\)', '\\(\\dfrac{1}{2}\\mathbf{b}\\)'], answer: 0 },
      { q: 'Point X divides AB in ratio 1:2 from A. \\(\\vec{OX} =\\)', options: ['\\(\\dfrac{2\\mathbf{a}+\\mathbf{b}}{3}\\)', '\\(\\dfrac{\\mathbf{a}+2\\mathbf{b}}{3}\\)', '\\(\\dfrac{\\mathbf{a}+\\mathbf{b}}{2}\\)', '\\(\\dfrac{\\mathbf{a}-\\mathbf{b}}{3}\\)'], answer: 0 },
    ],
    red: [
      { q: 'Triangle OAB has \\(\\vec{OA} = \\mathbf{a}\\) and \\(\\vec{OB} = \\mathbf{b}\\). P is on OA with OP:PA = 1:2. Q is the midpoint of AB. Show PQ is parallel to OB. \\(\\vec{PQ} =\\)', options: ['\\(\\dfrac{1}{2}\\mathbf{b}\\)','\\(\\mathbf{b} - \\dfrac{1}{3}\\mathbf{a}\\)','\\(\\dfrac{2}{3}\\mathbf{b}\\)','\\(\\dfrac{1}{2}\\mathbf{b} - \\dfrac{1}{6}\\mathbf{a}\\)'], answer: 3 },
      { q: 'Prove: \\(\\vec{OA} = 3\\mathbf{i} + 2\\mathbf{j}\\), \\(\\vec{OB} = 7\\mathbf{i} + 6\\mathbf{j}\\), \\(\\vec{OC} = 11\\mathbf{i} + 10\\mathbf{j}\\) — are A, B, C collinear?', options: ['Yes: \\(\\vec{AC} = 2\\vec{AB}\\)','No: \\(\\vec{AB} \\neq \\vec{BC}\\)','Yes: \\(|AC| = |AB| + |BC|\\)','Cannot determine from given information'], answer: 0 },
      { q: 'In quadrilateral OABC, \\(\\vec{OA} = \\mathbf{a}\\), \\(\\vec{OC} = \\mathbf{c}\\), \\(\\vec{CB} = \\mathbf{a}\\). The midpoint M of OB has position vector:', options: ['\\(\\dfrac{1}{2}(2\\mathbf{a}+\\mathbf{c})\\)','\\(\\dfrac{1}{2}\\mathbf{c}\\)','\\(\\mathbf{a}+\\mathbf{c}\\)','\\(\\dfrac{1}{2}(\\mathbf{a}+\\mathbf{c})\\)'], answer: 3 },
      { q: 'If \\(\\mathbf{p} = \\lambda\\mathbf{a} + \\mu\\mathbf{b}\\) and P lies on the line through A parallel to OB, then:', options: ['\\(\\lambda = 0\\)','\\(\\lambda = 1\\)','\\(\\lambda = \\mu\\)','\\(\\mu = 1\\)'], answer: 1 },
      { q: 'A ship sails from port with velocity \\(\\mathbf{v} = 3\\mathbf{i} + 4\\mathbf{j}\\) km/h. Its speed is 5 km/h. After 2 hours, its displacement from port is:', options: ['\\(6\\mathbf{i} + 8\\mathbf{j}\\) km','\\(3\\mathbf{i} + 4\\mathbf{j}\\) km','10 km in direction \\(\\mathbf{v}\\)','\\(9\\mathbf{i} + 16\\mathbf{j}\\) km'], answer: 0 },
      { q: 'G is the centroid of triangle OAB (where \\(\\vec{OA}=\\mathbf{a}\\), \\(\\vec{OB}=\\mathbf{b}\\)). \\(\\vec{OG} =\\)', options: ['\\(\\dfrac{1}{3}(\\mathbf{a}+\\mathbf{b})\\)','\\(\\dfrac{1}{2}(\\mathbf{a}+\\mathbf{b})\\)','\\(\\mathbf{a}+\\mathbf{b}\\)','\\(\\dfrac{2}{3}(\\mathbf{a}+\\mathbf{b})\\)'], answer: 0 },
    ]
  }

};
