/*
 * AQA GCSE Computer Science (8525) — Diagnostic MCQ Question Bank
 * 50 questions per topic: 20 green (recall/basic), 20 amber (application), 10 red (analysis/evaluate)
 * Diagnostic picks 2 green + 2 amber + 1 red = 5 questions at random.
 * answer: 0-based index of correct option.
 */

const CS_AQA_QUESTIONS = {

  '3.1': {
    name: 'Fundamentals of Algorithms',
    green: [
      { q: 'What is an algorithm?', options: ['A programming language','A step-by-step set of instructions to solve a problem','A type of computer','A storage device'], answer: 1 },
      { q: 'Which of the following is the BEST description of the difference between an algorithm and a program?', options: ['There is no difference','An algorithm is the set of logical steps; a program is an algorithm written in a specific programming language','A program is always faster than an algorithm','An algorithm uses hardware; a program uses software'], answer: 1 },
      { q: 'Which flowchart symbol represents a decision?', options: ['Rectangle','Parallelogram','Diamond','Rounded rectangle'], answer: 2 },
      { q: 'Which flowchart symbol represents a process (e.g. an assignment)?', options: ['Rectangle','Diamond','Parallelogram','Oval'], answer: 0 },
      { q: 'Which flowchart symbol represents input or output?', options: ['Rectangle','Parallelogram','Diamond','Triangle'], answer: 1 },
      { q: 'Which flowchart symbol represents the start or end of an algorithm?', options: ['Diamond','Rectangle','Rounded rectangle (terminator)','Circle'], answer: 2 },
      { q: 'What is pseudo-code?', options: ['Code written in machine language','A structured, language-like way of writing an algorithm in plain English','A secret code used by programmers','Compiled source code'], answer: 1 },
      { q: 'What is the purpose of a trace table?', options: ['To design a graphical user interface','To record how variables change as an algorithm runs','To store program output','To compile source code'], answer: 1 },
      { q: 'What does a linear search do?', options: ['Splits the list in half repeatedly','Checks every item in a list one at a time from start to end','Sorts the list first then searches','Searches only even-indexed items'], answer: 1 },
      { q: 'What is required for binary search to work correctly?', options: ['The list must be empty','The list must be sorted','The list must contain only integers','The list must be short'], answer: 1 },
      { q: 'How does binary search narrow down the search space?', options: ['By removing the first item each time','By halving the remaining search space each step','By sorting the list again each pass','By doubling the list length'], answer: 1 },
      { q: 'What is a "pass" in bubble sort?', options: ['A single swap of two items','A single traversal through the list comparing adjacent pairs','A function call','A recursive step'], answer: 1 },
      { q: 'Which of the following does bubble sort do on each pair of adjacent items?', options: ['Adds them together','Compares them and swaps if in the wrong order','Removes them both','Copies the pair to a new list'], answer: 1 },
      { q: 'Merge sort is an example of which design technique?', options: ['Brute force','Trial and error','Divide and conquer','Greedy search'], answer: 2 },
      { q: 'What is decomposition in computational thinking?', options: ['Deleting unnecessary variables','Breaking a big problem down into smaller sub-problems','Removing detail from a model','Sorting a list'], answer: 1 },
      { q: 'What is abstraction in computational thinking?', options: ['Writing code in assembly language','Removing unnecessary detail so you can focus on what matters','Breaking a problem into sub-problems','Tracing through an algorithm'], answer: 1 },
      { q: 'Which algorithm only works on a sorted list?', options: ['Linear search','Bubble sort','Binary search','Merge sort'], answer: 2 },
      { q: 'Which sorting algorithm works by recursively splitting the list and merging sorted halves?', options: ['Bubble sort','Linear sort','Merge sort','Insertion sort'], answer: 2 },
      { q: 'In pseudo-code, what does the symbol \u2190 usually mean?', options: ['Equal to','Greater than','Assignment','Return'], answer: 2 },
      { q: 'Which of the following is NOT a property an algorithm must have?', options: ['It must terminate','Each step must be precise','It must be written in Python','It must produce the correct output for the same input'], answer: 2 },
    ],
    amber: [
      { q: 'A flowchart has: INPUT x, then decision "x > 5?". If yes OUTPUT "big", else OUTPUT "small". What does it output when x = 3?', options: ['big','small','nothing','x'], answer: 1 },
      { q: 'Consider: total \u2190 0; FOR i \u2190 1 TO 4: total \u2190 total + i. What is total after the loop?', options: ['4','6','10','16'], answer: 2 },
      { q: 'Linear search on the list [4, 9, 2, 7, 5] for value 7 takes how many comparisons?', options: ['1','2','3','4'], answer: 3 },
      { q: 'Binary search on the sorted list [2, 4, 6, 8, 10, 12, 14] looking for 10: which element is compared first?', options: ['2','8','10','14'], answer: 1 },
      { q: 'A bubble sort is run on [4, 1, 3, 2]. How many swaps happen in the FIRST pass?', options: ['0','1','2','3'], answer: 2 },
      { q: 'For a list of 16 sorted items, how many comparisons does binary search need at most?', options: ['2','4','8','16'], answer: 1 },
      { q: 'For a list of 16 items, how many comparisons does linear search need in the worst case?', options: ['4','8','16','256'], answer: 2 },
      { q: 'Which statement about a trace table is correct?', options: ['A new row is added each time a variable changes','A new row is added for every line of code','Trace tables only record output, not variables','Trace tables are used only for sorting algorithms'], answer: 0 },
      { q: 'Which of these is a valid reason to use a linear search rather than a binary search?', options: ['The list is very large','The list is unsorted','Fewer comparisons are needed','It always takes fewer steps'], answer: 1 },
      { q: 'Doubling the size of a list affects the worst-case comparisons of linear search by:', options: ['No change','Doubling them','Halving them','Squaring them'], answer: 1 },
      { q: 'Doubling the size of a list affects binary search worst-case comparisons by:', options: ['Adding 1 comparison','Doubling them','Halving them','Squaring them'], answer: 0 },
      { q: 'Bubble sort on [5, 4, 3, 2, 1] will take approximately how many comparisons in total?', options: ['4','10','25','100'], answer: 1 },
      { q: 'What is the OUTPUT? x \u2190 10; WHILE x > 0: x \u2190 x - 3; ENDWHILE; OUTPUT x', options: ['0','-1','-2','1'], answer: 2 },
      { q: 'Merging the two sorted lists [1, 4, 7] and [2, 3, 8] produces:', options: ['[1, 2, 3, 4, 7, 8]','[1, 4, 7, 2, 3, 8]','[8, 7, 4, 3, 2, 1]','[2, 3, 8, 1, 4, 7]'], answer: 0 },
      { q: 'You apply merge sort to [3, 1, 4, 1, 5]. After the final merge, what is the list?', options: ['[1, 1, 3, 4, 5]','[1, 3, 4, 1, 5]','[5, 4, 3, 1, 1]','[3, 1, 1, 4, 5]'], answer: 0 },
      { q: 'Which of the following BEST shows abstraction?', options: ['Writing a register program that stores only names and presence flags','Splitting a game into input, logic and render modules','Using a nested loop','Adding more RAM'], answer: 0 },
      { q: 'Which of the following BEST shows decomposition?', options: ['Ignoring a student\'s hair colour when writing a register','Splitting a shopping website into login, cart and payment modules','Reducing the size of integers used','Removing comments from code'], answer: 1 },
      { q: 'A linear search on a list of 1,000,000 items takes at most how many comparisons?', options: ['20','1000','1,000,000','1,000,000,000'], answer: 2 },
      { q: 'A binary search on 1,000,000 sorted items takes at most approximately how many comparisons?', options: ['20','1000','100,000','500,000'], answer: 0 },
      { q: 'Which of the following is true about bubble sort?', options: ['It is recursive','After each pass the largest remaining unsorted item is in its correct final position','It always needs a sorted list','It uses divide and conquer'], answer: 1 },
    ],
    red: [
      { q: 'Why does binary search take roughly log\u2082(n) comparisons?', options: ['Because it compares every pair of items','Because each step halves the remaining search space, and log\u2082(n) is the number of times n can be halved to reach 1','Because it uses recursion','Because sorted lists are faster to read'], answer: 1 },
      { q: 'For a list of 10 items, approximately how many comparisons does bubble sort make in the worst case?', options: ['10','20','45','100'], answer: 2 },
      { q: 'A company stores 2 million customer records that are updated constantly and searched many times per second. Which search approach is best overall?', options: ['Linear search on the unsorted list','Keep the list sorted and use binary search','Bubble sort then linear search each time','Use merge sort each time before searching'], answer: 1 },
      { q: 'A teacher is sorting a class list of 20 nearly-sorted names once a year. Which sort is a sensible choice?', options: ['Merge sort, because it is always fastest','Bubble sort, because it is simple and fast on small or nearly-sorted lists','Binary sort, because it needs fewer comparisons','None, sorting is never needed'], answer: 1 },
      { q: 'Which statement about merge sort is MOST accurate?', options: ['It is faster than bubble sort for large lists because its work grows like n log n rather than n\u00B2','It is simpler to implement than bubble sort','It does not require any extra memory','It only works on lists that are already sorted'], answer: 0 },
      { q: 'Why must binary search have a sorted list?', options: ['To make the code easier to write','Because it decides which half to discard by comparing against the middle item, which only works if items are in order','Because it is recursive','To save memory'], answer: 1 },
      { q: 'Which statement BEST captures the difference between decomposition and abstraction?', options: ['They are the same','Decomposition breaks a problem into sub-problems; abstraction removes unnecessary detail','Decomposition is faster; abstraction is slower','Abstraction only applies to sorting'], answer: 1 },
      { q: 'Comparing the efficiency of two algorithms on input size n, which pair grows MOST slowly as n increases?', options: ['n\u00B2 (bubble sort)','n (linear search)','log n (binary search)','n log n (merge sort)'], answer: 2 },
      { q: 'Which scenario is the best case for bubble sort?', options: ['An already-sorted list, which can be detected in one pass with no swaps','A reverse-sorted list','A list of equal items','A random list'], answer: 0 },
      { q: 'Evaluate: "Merge sort is always the best choice." Which response is MOST correct?', options: ['True, it is always fastest','Partly true: merge sort scales well for large lists but uses more memory and is more complex than bubble sort, which may be preferable for small or nearly-sorted data','False, merge sort never works','True, because it uses recursion'], answer: 1 },
    ],
  },
  '3.2': {
    name: 'Programming',
    green: [
      { q: 'Which data type stores a whole number only?', options: ['Real','Integer','Boolean','String'], answer: 1 },
      { q: 'Which data type stores only the values True or False?', options: ['Integer','Character','Boolean','String'], answer: 2 },
      { q: 'Which data type is most appropriate for a price in pounds and pence (e.g. 9.99)?', options: ['Integer','Real (float)','Boolean','Character'], answer: 1 },
      { q: 'Which data type is a sequence of characters such as "Hello"?', options: ['Character','String','Integer','Boolean'], answer: 1 },
      { q: 'What is casting in programming?', options: ['Writing a loop','Converting a value from one data type to another','Running a subroutine','Saving a file'], answer: 1 },
      { q: 'Which pseudo-code construct chooses between different blocks of code based on a condition?', options: ['Iteration','Selection','Sequence','Concatenation'], answer: 1 },
      { q: 'Which type of loop repeats a known number of times?', options: ['WHILE loop','FOR loop','REPEAT loop','DO loop'], answer: 1 },
      { q: 'Which type of loop is "condition-controlled"?', options: ['FOR','WHILE','Count-controlled','Sequential'], answer: 1 },
      { q: 'Which symbol represents integer division in AQA pseudo-code?', options: ['/','DIV','MOD','\\'], answer: 1 },
      { q: 'Which operator returns the remainder after division?', options: ['DIV','MOD','/','REM'], answer: 1 },
      { q: 'Which operator raises a number to a power?', options: ['*','^','/','%'], answer: 1 },
      { q: 'Which symbol in AQA pseudo-code means "not equal to"?', options: ['=','!','\u2260','~'], answer: 2 },
      { q: 'What is the result of the Boolean expression True AND False?', options: ['True','False','Error','Both'], answer: 1 },
      { q: 'What is the result of the Boolean expression True OR False?', options: ['True','False','Error','None'], answer: 0 },
      { q: 'What is the result of NOT True?', options: ['True','False','Null','Error'], answer: 1 },
      { q: 'What is the index of the first item in an AQA pseudo-code array?', options: ['-1','0','1','2'], answer: 1 },
      { q: 'A 2D array cell is accessed using how many indices?', options: ['One','Two','Three','Four'], answer: 1 },
      { q: 'Which function returns the number of characters in a string?', options: ['size()','length()','count()','chars()'], answer: 1 },
      { q: 'A subroutine that returns a value is called a:', options: ['Procedure','Function','Module','Class'], answer: 1 },
      { q: 'Which of these is an advantage of using subroutines?', options: ['Code cannot be reused','Programs become longer','Code can be reused without rewriting it','Variables are always global'], answer: 2 },
    ],
    amber: [
      { q: 'What is the value of 17 MOD 5?', options: ['2','3','4','12'], answer: 0 },
      { q: 'What is the value of 17 DIV 5?', options: ['2','3','4','12'], answer: 1 },
      { q: 'What is the value of 2 + 3 * 4?', options: ['20','14','24','11'], answer: 1 },
      { q: 'What is the value of (10 - 4) / 2?', options: ['3','8','6','1'], answer: 0 },
      { q: 'What is the value of 2 ^ 5?', options: ['10','25','32','16'], answer: 2 },
      { q: 'What does int("42") + 3 evaluate to?', options: ['"423"','45','"45"','Error'], answer: 1 },
      { q: 'Given x \u2190 5 and y \u2190 3, what is the value of x &gt; y AND y &gt; 0?', options: ['True','False','Error','Unknown'], answer: 0 },
      { q: 'What does (7 &lt; 3) OR (4 = 4) evaluate to?', options: ['True','False','Error','Null'], answer: 0 },
      { q: 'What is the OUTPUT of: total \u2190 0; FOR i \u2190 1 TO 3: total \u2190 total + i; ENDFOR; OUTPUT total', options: ['3','6','9','12'], answer: 1 },
      { q: 'What is the OUTPUT of: x \u2190 0; WHILE x &lt; 5: x \u2190 x + 2; ENDWHILE; OUTPUT x', options: ['4','5','6','10'], answer: 2 },
      { q: 'Given name \u2190 "Hello", what is name[1]?', options: ['"H"','"e"','"l"','"o"'], answer: 1 },
      { q: 'Given word \u2190 "Computer", what is subString(word, 3, 4) (start 3, length 4)?', options: ['"ompu"','"mpute"','"pute"','"puter"'], answer: 2 },
      { q: 'Given scores \u2190 [10, 20, 30, 40, 50], what is scores[2]?', options: ['10','20','30','40'], answer: 2 },
      { q: 'Given grid \u2190 [[1,2,3],[4,5,6],[7,8,9]], what is grid[1][2]?', options: ['2','4','6','8'], answer: 2 },
      { q: 'What does "Hello " + "world" evaluate to?', options: ['"Hello world"','"Helloworld"','Error','"Hello+world"'], answer: 0 },
      { q: 'Which of the following is TRUE for the condition age \u2265 13 AND age \u2264 19 when age = 19?', options: ['True','False','Error','Undefined'], answer: 0 },
      { q: 'What is the value of length("AQA GCSE")?', options: ['6','7','8','9'], answer: 2 },
      { q: 'If n MOD 2 = 0 then n is:', options: ['Odd','Even','Negative','Prime'], answer: 1 },
      { q: 'What does random(1, 6) simulate?', options: ['Any integer','A dice roll','A coin flip','A letter'], answer: 1 },
      { q: 'Which pseudo-code line correctly opens a file for reading?', options: ['f \u2190 openRead("data.txt")','f \u2190 openWrite("data.txt")','f \u2190 read("data.txt")','f \u2190 open(data.txt)'], answer: 0 },
    ],
    red: [
      { q: 'A programmer needs to keep asking the user for input until they enter a valid number between 1 and 10. Which loop is MOST appropriate?', options: ['FOR loop, because it is simpler','WHILE loop, because the number of iterations is not known in advance','Neither &mdash; use an IF statement','A nested FOR loop'], answer: 1 },
      { q: 'Which statement BEST explains why local variables are generally preferred over global variables?', options: ['Local variables run faster','Local variables keep each subroutine self-contained, reducing the risk of unintended interference from other parts of the program','Global variables cannot store numbers','Local variables use more memory and are therefore safer'], answer: 1 },
      { q: 'Consider: FOR i \u2190 0 TO 10: IF i MOD 2 = 0: OUTPUT i. What does this code output?', options: ['All numbers 0 to 10','Only odd numbers 1, 3, 5, 7, 9','Only even numbers 0, 2, 4, 6, 8, 10','Nothing'], answer: 2 },
      { q: 'A student writes: IF grade = "A" OR "B". Why is this incorrect?', options: ['It should use AND instead of OR','"B" alone is not a Boolean condition &mdash; it must be written as grade = "B"','Quotes should be single','OR does not exist in AQA pseudo-code'], answer: 1 },
      { q: 'A program needs to simulate rolling TWO six-sided dice and sum the result. Which approach is correct?', options: ['random(2, 12) once','random(1, 6) + random(1, 6)','random(1, 12)','random(1, 6) * 2'], answer: 1 },
      { q: 'Which of the following is the BEST reason to use a function rather than a procedure?', options: ['Functions are always faster','Functions return a value, so they can be used inside larger expressions such as total = a + area(r)','Procedures cannot take parameters','Only functions can be called more than once'], answer: 1 },
      { q: 'Which of these represents the STRONGEST argument for structured programming?', options: ['It uses less memory','It produces small, self-contained blocks (sequence, selection, iteration, subroutines) that are easier to test, maintain and understand','It runs faster because there are no loops','It avoids variables'], answer: 1 },
      { q: 'A student writes a FOR loop: FOR i \u2190 0 TO length(list). On running, they get an out-of-range error on the last iteration. What is the fix?', options: ['Change 0 to 1','Change to length(list) - 1, because indices run from 0 to length-1','Use a WHILE loop instead','Make the list global'], answer: 1 },
      { q: 'Consider this code for finding the maximum of an array: max \u2190 0; FOR i \u2190 0 TO length(list) - 1: IF list[i] &gt; max THEN max \u2190 list[i]. Why might it fail?', options: ['It will always work correctly','If every element is negative, max stays at 0 which is wrong. max should be initialised to list[0] instead','FOR loops cannot be used on arrays','The comparison should be \u2265, not &gt;'], answer: 1 },
      { q: 'Which statement about casting int("3.9") is MOST accurate?', options: ['Always returns 4','Depends on language &mdash; many languages error on non-integer text, and int(3.9) truncates to 3','Always returns 3.9','int() cannot take a string'], answer: 1 },
    ],
  },
  '3.3': { name: 'Fundamentals of Data Representation', green: [], amber: [], red: [] },
  '3.4': { name: 'Computer Systems', green: [], amber: [], red: [] },
  '3.5': { name: 'Fundamentals of Computer Networks', green: [], amber: [], red: [] },
  '3.6': { name: 'Cyber Security', green: [], amber: [], red: [] },
  '3.7': { name: 'Relational Databases and SQL', green: [], amber: [], red: [] },
  '3.8': { name: 'Ethical, Legal and Environmental Impacts', green: [], amber: [], red: [] },

};
