/*
 * AQA A-Level Further Mathematics — MCQ Question Bank
 * 50 questions per topic: 20 green (recall/procedure), 20 amber (application), 10 red (analysis/proof)
 * Diagnostic picks 2 green + 2 amber + 1 red = 5 questions at random (always one written).
 * answer: 0-based index of correct option in the options array.
 */

const FM_AQA_MCQ = {

  '1.1': {
    name: 'Complex Numbers',
    green: [
      { q: 'What is \\(i^2\\)?', options: ['\\(-1\\)','\\(1\\)','\\(i\\)','\\(-i\\)'], answer: 0 },
      { q: 'What is \\(|3+4i|\\)?', options: ['5','7','\\(\\sqrt{7}\\)','25'], answer: 0 },
      { q: 'What is the conjugate of \\(2-5i\\)?', options: ['\\(2+5i\\)','\\(-2+5i\\)','\\(-2-5i\\)','\\(5-2i\\)'], answer: 0 },
      { q: 'What is \\((2+3i)+(4-i)\\)?', options: ['\\(6+2i\\)','\\(6+4i\\)','\\(6-2i\\)','\\(8+2i\\)'], answer: 0 },
      { q: 'What is \\(i^3\\)?', options: ['\\(-i\\)','\\(i\\)','\\(-1\\)','1'], answer: 0 },
      { q: 'What is the real part of \\(7-3i\\)?', options: ['7','\\(-3\\)','\\(\\sqrt{58}\\)','3'], answer: 0 },
      { q: 'What is the imaginary part of \\(4+9i\\)?', options: ['9','4','\\(9i\\)','\\(\\sqrt{97}\\)'], answer: 0 },
      { q: 'What is \\((2+i)(2-i)\\)?', options: ['5','3','\\(4+1\\)','\\(4-i^2\\)'], answer: 0 },
      { q: 'What is \\(i^4\\)?', options: ['1','\\(-1\\)','\\(i\\)','\\(-i\\)'], answer: 0 },
      { q: 'If \\(z = a+bi\\), then \\(z + z^*\\) equals:', options: ['\\(2a\\)','\\(2bi\\)','\\(2b\\)','0'], answer: 0 },
      { q: 'If \\(z = a+bi\\), then \\(z\\cdot z^*\\) equals:', options: ['\\(a^2+b^2\\)','\\(a^2-b^2\\)','\\(2ab\\)','\\((a+b)^2\\)'], answer: 0 },
      { q: 'What is the argument of \\(1+i\\) in radians?', options: ['\\(\\pi/4\\)','\\(\\pi/2\\)','\\(\\pi/3\\)','\\(3\\pi/4\\)'], answer: 0 },
      { q: 'What is \\(|{-3+4i}|\\)?', options: ['5','1','7','\\(\\sqrt{7}\\)'], answer: 0 },
      { q: 'What is \\(\\arg(-1)\\)?', options: ['\\(\\pi\\)','0','\\(-\\pi/2\\)','\\(\\pi/2\\)'], answer: 0 },
      { q: 'The principal argument satisfies:', options: ['\\(-\\pi < \\arg(z) \\leq \\pi\\)','\\(0 \\leq \\arg(z) < 2\\pi\\)','\\(0 \\leq \\arg(z) \\leq \\pi\\)','\\(-\\pi \\leq \\arg(z) \\leq \\pi\\)'], answer: 0 },
      { q: 'What is \\(\\arg(i)\\)?', options: ['\\(\\pi/2\\)','\\(\\pi\\)','0','\\(-\\pi/2\\)'], answer: 0 },
      { q: 'Which of these has modulus 1?', options: ['\\(\\cos\\theta+i\\sin\\theta\\)','\\(1+i\\)','\\(2i\\)','\\(\\frac{1}{2}+i\\)'], answer: 0 },
      { q: 'What is \\(\\frac{1}{i}\\)?', options: ['\\(-i\\)','\\(i\\)','1','\\(-1\\)'], answer: 0 },
      { q: 'Euler\'s formula states:', options: ['\\(e^{i\\theta}=\\cos\\theta+i\\sin\\theta\\)','\\(e^{i\\theta}=\\cos\\theta-i\\sin\\theta\\)','\\(e^{i\\theta}=i(\\cos\\theta+\\sin\\theta)\\)','\\(e^{i\\theta}=\\cosh\\theta+i\\sinh\\theta\\)'], answer: 0 },
      { q: 'What are the square roots of \\(-1\\)?', options: ['\\(i\\) and \\(-i\\)','\\(1\\) and \\(-1\\)','\\(i\\) only','\\(\\pm\\sqrt{i}\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Simplify \\(\\dfrac{3+5i}{1+2i}\\).', options: ['\\(\\dfrac{13}{5}-\\dfrac{1}{5}i\\)','\\(\\dfrac{13}{5}+\\dfrac{1}{5}i\\)','\\(\\dfrac{3-5i}{1-4}\\)','\\(3-5i\\)'], answer: 0 },
      { q: 'Given \\(z=1+\\sqrt{3}i\\), what is \\(\\arg(z)\\)?', options: ['\\(\\pi/3\\)','\\(\\pi/6\\)','\\(2\\pi/3\\)','\\(\\pi/4\\)'], answer: 0 },
      { q: 'Solve \\(z^2+4z+13=0\\).', options: ['\\(-2\\pm 3i\\)','\\(2\\pm 3i\\)','\\(-4\\pm 3i\\)','\\(-2\\pm 13i\\)'], answer: 0 },
      { q: 'Write \\(2(\\cos(\\pi/6)+i\\sin(\\pi/6))\\) in \\(a+bi\\) form.', options: ['\\(\\sqrt{3}+i\\)','\\(1+\\sqrt{3}i\\)','\\(\\sqrt{3}+\\sqrt{3}i\\)','\\(2+2i\\)'], answer: 0 },
      { q: 'Find \\(|(2+3i)(1-2i)|\\).', options: ['\\(\\sqrt{65}\\)','\\(\\sqrt{13}\\)','\\(\\sqrt{5}\\)','\\(5\\sqrt{13}\\)'], answer: 0 },
      { q: 'By de Moivre\'s theorem, \\((\\cos\\theta+i\\sin\\theta)^5\\) equals:', options: ['\\(\\cos5\\theta+i\\sin5\\theta\\)','\\(5\\cos\\theta+5i\\sin\\theta\\)','\\(\\cos^5\\theta+i\\sin^5\\theta\\)','\\(\\cos5\\theta-i\\sin5\\theta\\)'], answer: 0 },
      { q: 'If one root of a real-coefficient equation is \\(3+2i\\), another root must be:', options: ['\\(3-2i\\)','\\(-3+2i\\)','\\(-3-2i\\)','\\(2+3i\\)'], answer: 0 },
      { q: 'The cube roots of unity include which pair of complex roots?', options: ['\\(-\\frac{1}{2}\\pm\\frac{\\sqrt{3}}{2}i\\)','\\(\\pm i\\)','\\(\\frac{1}{2}\\pm\\frac{\\sqrt{3}}{2}i\\)','\\(-1\\pm i\\)'], answer: 0 },
      { q: 'Express \\(-1+i\\) in modulus-argument form.', options: ['\\(\\sqrt{2}(\\cos\\frac{3\\pi}{4}+i\\sin\\frac{3\\pi}{4})\\)','\\(\\sqrt{2}(\\cos\\frac{\\pi}{4}+i\\sin\\frac{\\pi}{4})\\)','\\(2(\\cos\\frac{3\\pi}{4}+i\\sin\\frac{3\\pi}{4})\\)','\\(\\sqrt{2}(\\cos(-\\frac{\\pi}{4})+i\\sin(-\\frac{\\pi}{4}))\\)'], answer: 0 },
      { q: 'What is \\(\\arg(z_1 z_2)\\) in terms of \\(\\arg z_1\\) and \\(\\arg z_2\\)?', options: ['\\(\\arg z_1+\\arg z_2\\)','\\(\\arg z_1 \\cdot \\arg z_2\\)','\\(\\arg z_1-\\arg z_2\\)','\\(\\arg z_1/\\arg z_2\\)'], answer: 0 },
      { q: 'If \\(z = r e^{i\\theta}\\), what is \\(z^4\\)?', options: ['\\(r^4 e^{4i\\theta}\\)','\\(4r e^{4i\\theta}\\)','\\(r^4 e^{i\\theta/4}\\)','\\(4r^4 e^{i\\theta}\\)'], answer: 0 },
      { q: 'How many distinct roots does \\(z^5 = 1\\) have in \\(\\mathbb{C}\\)?', options: ['5','1','2','10'], answer: 0 },
      { q: 'The locus \\(|z-2|=3\\) is:', options: ['A circle centre \\((2,0)\\) radius 3','A circle centre \\((3,0)\\) radius 2','A perpendicular bisector','A half-line'], answer: 0 },
      { q: 'What is the Cartesian equation of \\(|z-i|=|z+i|\\)?', options: ['\\(y=0\\) (the real axis)','\\(x=0\\)','\\(y=x\\)','\\(x^2+y^2=1\\)'], answer: 0 },
      { q: 'The locus \\(\\arg(z-1)=\\pi/4\\) is:', options: ['A half-line from \\((1,0)\\) at angle \\(\\pi/4\\)','A full line through \\((1,0)\\)','A circle','A perpendicular bisector'], answer: 0 },
      { q: 'Use de Moivre to find \\(\\cos 3\\theta\\) in terms of \\(\\cos\\theta\\). The answer is:', options: ['\\(4\\cos^3\\theta-3\\cos\\theta\\)','\\(3\\cos\\theta-4\\cos^3\\theta\\)','\\(\\cos^3\\theta-3\\cos\\theta\\)','\\(4\\cos^3\\theta+3\\cos\\theta\\)'], answer: 0 },
      { q: 'The roots of \\(z^n=1\\) lie on a circle of radius:', options: ['1','\\(n\\)','\\(1/n\\)','\\(\\sqrt{n}\\)'], answer: 0 },
      { q: 'If \\(z = \\sqrt{2}e^{i\\pi/4}\\), then \\(z^2\\) equals:', options: ['\\(2i\\)','\\(2e^{i\\pi/2}\\)','\\(2\\)','\\(2e^{i\\pi/4}\\)'], answer: 0 },
      { q: 'Simplify \\((1+i)^4\\).', options: ['\\(-4\\)','4','\\(4i\\)','\\(-4i\\)'], answer: 0 },
      { q: 'The modulus of \\(\\dfrac{z_1}{z_2}\\) equals:', options: ['\\(\\dfrac{|z_1|}{|z_2|}\\)','\\(|z_1|-|z_2|\\)','\\(|z_1|+|z_2|\\)','\\(|z_1|\\cdot|z_2|\\)'], answer: 0 },
    ],
    red: [
      { q: 'For non-zero \\(z\\), \\(z + \\frac{1}{z}\\) is real if and only if:', options: ['\\(z\\) is real or \\(|z|=1\\)','\\(z\\) is real only','\\(|z|=1\\) only','\\(z\\) is purely imaginary'], answer: 0 },
      { q: 'If \\(z = re^{i\\theta}\\), then \\(\\bar{z}\\) equals:', options: ['\\(re^{-i\\theta}\\)','\\(re^{i\\theta}\\)','\\(-re^{i\\theta}\\)','\\(\\frac{1}{r}e^{-i\\theta}\\)'], answer: 0 },
      { q: 'A cubic with real coefficients has one root \\(2+3i\\). What is the product of all three roots if the leading coefficient is 1 and the real root is 4?', options: ['\\(-52\\)','52','\\(-4\\)','4'], answer: 0 },
      { q: 'Using \\(z+z^{-1}=2\\cos\\theta\\) with \\(z=e^{i\\theta}\\), \\(\\cos^3\\theta\\) equals:', options: ['\\(\\frac{1}{4}(\\cos 3\\theta+3\\cos\\theta)\\)','\\(\\frac{1}{4}(\\cos 3\\theta-3\\cos\\theta)\\)','\\(\\frac{3}{4}\\cos\\theta+\\frac{1}{4}\\cos 3\\theta\\)','\\(\\cos^3\\theta\\) (cannot simplify)'], answer: 0 },
      { q: 'The argument of the product of all \\(n\\)-th roots of unity is:', options: ['\\(0\\) (or \\(\\pi\\) if \\(n\\) even)', '\\(\\pi\\)', '\\(2\\pi\\)','\\((n-1)\\pi/n\\)'], answer: 0 },
      { q: 'Which of the following is NOT a property of complex conjugates?', options: ['\\(\\overline{z_1/z_2}=\\bar{z}_1/|z_2|\\)','\\(\\overline{z_1+z_2}=\\bar{z}_1+\\bar{z}_2\\)','\\(\\overline{z_1 z_2}=\\bar{z}_1\\bar{z}_2\\)','\\(|\\bar{z}|=|z|\\)'], answer: 0 },
      { q: 'How many distinct complex numbers \\(z\\) satisfy \\(z^6=64\\)?', options: ['6','3','2','12'], answer: 0 },
      { q: 'The locus \\(|z-3|=2|z|\\) is a circle. Its centre is:', options: ['\\((4,0)\\)','\\((3,0)\\)','\\((1,0)\\)','\\((-4,0)\\)'], answer: 0 },
      { q: 'If \\(\\omega = e^{2\\pi i/3}\\), then \\(1+\\omega+\\omega^2\\) equals:', options: ['0','1','3','\\(\\omega\\)'], answer: 0 },
      { q: 'A student says \\(\\arg(z_1 z_2)=\\arg(z_1)\\cdot\\arg(z_2)\\). This is:', options: ['False; a counterexample is \\(z_1=z_2=i\\)','True always','True only when \\(|z_1|=|z_2|=1\\)','True when both arguments are positive'], answer: 0 },
    ],
  },

  '1.2': {
    name: 'Matrices',
    green: [
      { q: 'What is the determinant of \\(\\begin{pmatrix}2&3\\\\1&4\\end{pmatrix}\\)?', options: ['5','11','8','\\(-5\\)'], answer: 0 },
      { q: 'The identity matrix \\(I\\) satisfies:', options: ['\\(AI=IA=A\\)','\\(AI=O\\)','\\(AI=A^2\\)','\\(AI=I\\)'], answer: 0 },
      { q: 'Matrix multiplication is:', options: ['Associative but not commutative','Commutative and associative','Commutative but not associative','Neither'], answer: 0 },
      { q: 'If \\(A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}\\), what is \\(2A\\)?', options: ['\\(\\begin{pmatrix}2&4\\\\6&8\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&2\\\\3&8\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&4\\\\6&4\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&4\\\\3&8\\end{pmatrix}\\)'], answer: 0 },
      { q: 'The area scale factor of a 2D transformation is:', options: ['\\(|\\det A|\\)','\\(\\det A\\)','\\(\\det A^2\\)','\\(|\\text{tr} A|\\)'], answer: 0 },
      { q: 'The rotation matrix for angle \\(\\theta\\) anticlockwise is:', options: ['\\(\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}\\)','\\(\\begin{pmatrix}\\cos\\theta&\\sin\\theta\\\\-\\sin\\theta&\\cos\\theta\\end{pmatrix}\\)','\\(\\begin{pmatrix}\\sin\\theta&\\cos\\theta\\\\\\cos\\theta&-\\sin\\theta\\end{pmatrix}\\)','\\(\\begin{pmatrix}\\cos\\theta&-\\cos\\theta\\\\\\sin\\theta&\\sin\\theta\\end{pmatrix}\\)'], answer: 0 },
      { q: 'The reflection matrix in \\(y=x\\) is:', options: ['\\(\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&-1\\\\-1&0\\end{pmatrix}\\)'], answer: 0 },
      { q: 'A matrix is singular when:', options: ['Its determinant is 0','Its trace is 0','It has no eigenvalues','It is not square'], answer: 0 },
      { q: 'If \\(A\\mathbf{v} = \\lambda\\mathbf{v}\\) for non-zero \\(\\mathbf{v}\\), then \\(\\lambda\\) is called:', options: ['An eigenvalue','A determinant','A norm','A cofactor'], answer: 0 },
      { q: 'The characteristic equation of \\(A\\) is obtained from:', options: ['\\(\\det(A-\\lambda I)=0\\)','\\(\\det(A+\\lambda I)=0\\)','\\(A\\mathbf{v}=\\mathbf{0}\\)','\\(\\text{tr}(A)-\\lambda=0\\)'], answer: 0 },
      { q: 'What does \\((AB)^T\\) equal?', options: ['\\(B^T A^T\\)','\\(A^T B^T\\)','\\((AB)^{-1}\\)','\\(A B^T\\)'], answer: 0 },
      { q: 'For a \\(2\\times2\\) matrix \\(A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}\\), the inverse is:', options: ['\\(\\frac{1}{ad-bc}\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}\\)','\\(\\frac{1}{ad-bc}\\begin{pmatrix}a&-b\\\\-c&d\\end{pmatrix}\\)','\\(\\frac{1}{ad-bc}\\begin{pmatrix}d&b\\\\c&a\\end{pmatrix}\\)','\\(\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}\\)'], answer: 0 },
      { q: 'What is \\(\\det(AB)\\)?', options: ['\\(\\det A \\cdot \\det B\\)','\\(\\det A + \\det B\\)','\\(\\det(A+B)\\)','\\(\\det A - \\det B\\)'], answer: 0 },
      { q: 'An \\(m\\times n\\) matrix multiplied by an \\(n\\times p\\) matrix gives a matrix of size:', options: ['\\(m\\times p\\)','\\(n\\times n\\)','\\(m\\times n\\)','\\(p\\times m\\)'], answer: 0 },
      { q: 'The reflection in the \\(x\\)-axis has matrix:', options: ['\\(\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'If \\(\\det A = 0\\), the matrix is called:', options: ['Singular','Invertible','Diagonal','Orthogonal'], answer: 0 },
      { q: 'The Cayley-Hamilton theorem states that every matrix satisfies:', options: ['Its own characteristic equation','\\(A^2=I\\)','\\(A^n=O\\) for some \\(n\\)','\\(A=A^T\\)'], answer: 0 },
      { q: 'The trace of \\(A=\\begin{pmatrix}3&1\\\\2&5\\end{pmatrix}\\) is:', options: ['8','15','\\(-7\\)','13'], answer: 0 },
      { q: 'Which matrix represents an enlargement by scale factor 3?', options: ['\\(3I\\)','\\(\\begin{pmatrix}3&0\\\\0&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&3\\\\3&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&3\\\\3&1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'If \\(A\\) has eigenvalue \\(\\lambda\\), then \\(A^2\\) has eigenvalue:', options: ['\\(\\lambda^2\\)','\\(2\\lambda\\)','\\(\\lambda\\)','\\(1/\\lambda\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the eigenvalues of \\(\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}\\).', options: ['2 and 5','1 and 6','3 and 4','\\(-1\\) and 8'], answer: 0 },
      { q: 'What is \\(\\det\\begin{pmatrix}1&2&0\\\\3&-1&4\\\\2&0&1\\end{pmatrix}\\)?', options: ['\\(-3\\)','3','\\(-15\\)','15'], answer: 0 },
      { q: 'The system \\(Ax=b\\) has a unique solution when:', options: ['\\(\\det A \\neq 0\\)','\\(\\det A = 0\\)','\\(A=I\\)','\\(b=0\\)'], answer: 0 },
      { q: 'The eigenvector of \\(\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}\\) for \\(\\lambda=5\\) is:', options: ['\\(\\begin{pmatrix}1\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\-2\\end{pmatrix}\\)','\\(\\begin{pmatrix}2\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}0\\\\1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'Using Cayley-Hamilton for \\(A\\) with characteristic equation \\(\\lambda^2-5\\lambda+6=0\\), \\(A^2\\) equals:', options: ['\\(5A-6I\\)','\\(5A+6I\\)','\\(6A-5I\\)','\\(-5A+6I\\)'], answer: 0 },
      { q: 'A transformation maps the unit square to a parallelogram with area 6. The determinant of the transformation matrix has absolute value:', options: ['6','3','\\(\\sqrt{6}\\)','36'], answer: 0 },
      { q: 'The matrix for rotation by \\(90°\\) anticlockwise is:', options: ['\\(\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-1&0\\\\0&-1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'Three simultaneous equations with \\(\\det A = 0\\) and inconsistent right-hand sides have:', options: ['No solution','A unique solution','Infinitely many solutions','Two solutions'], answer: 0 },
      { q: 'Which product gives \\(A^{-1}\\) for \\(A=\\begin{pmatrix}3&1\\\\5&2\\end{pmatrix}\\)?', options: ['\\(\\begin{pmatrix}2&-1\\\\-5&3\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}\\)','\\(\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}\\)','\\(\\begin{pmatrix}-2&1\\\\5&-3\\end{pmatrix}\\)'], answer: 0 },
      { q: 'For \\(2\\times 2\\) matrix \\(A\\), the sum of eigenvalues equals:', options: ['\\(\\text{tr}(A)\\)','\\(\\det(A)\\)','\\(|A|^2\\)','\\(\\text{tr}(A^2)\\)'], answer: 0 },
      { q: 'The composition "first reflect in \\(x\\)-axis, then rotate \\(90°\\) anticlockwise" has matrix (read right to left):', options: ['\\(\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'If \\(A\\) is \\(3\\times 3\\) and \\(\\det A = 2\\), then \\(\\det(3A)=\\)', options: ['54','6','18','\\(2\\)'], answer: 0 },
      { q: 'The eigenvalues of \\(\\begin{pmatrix}5&0\\\\0&3\\end{pmatrix}\\) are:', options: ['5 and 3','15 and 0','8 and 0','4 and 4'], answer: 0 },
      { q: 'If \\(\\det A = 3\\), then \\(\\det(A^{-1}) =\\)', options: ['\\(1/3\\)','\\(3\\)','\\(-3\\)','\\(9\\)'], answer: 0 },
      { q: 'A transformation has matrix with \\(\\det = -2\\). Its effect on orientation is:', options: ['Reversed (reflection component)','Preserved','No change to area','Scaling by 2'], answer: 0 },
      { q: 'The product of eigenvalues of \\(A\\) equals:', options: ['\\(\\det A\\)','\\(\\text{tr}(A)\\)','\\(|A|^2\\)','\\(\\text{tr}(A^2)\\)'], answer: 0 },
      { q: 'To find the inverse of a \\(3\\times 3\\) matrix using cofactors, you compute \\(A^{-1}=\\)', options: ['\\(\\frac{1}{\\det A}\\,\\text{adj}\\,A\\)','\\(\\frac{1}{\\det A}\\,A\\)','\\(\\det A \\cdot \\text{adj}\\,A\\)','\\((\\text{adj}\\,A)^T\\)'], answer: 0 },
      { q: 'A system \\(Ax=b\\) where \\(\\det A = 0\\) and \\(b \\neq 0\\) may have:', options: ['No solution or infinitely many','Always exactly one solution','Always no solution','Always infinitely many'], answer: 0 },
      { q: 'The sign pattern of cofactors for a \\(3\\times 3\\) matrix starts:', options: ['\\(+,-,+\\)','\\(-,+,-\\)','\\(+,+,+\\)','\\(-,-,-\\)'], answer: 0 },
      { q: 'If \\(Av = \\lambda v\\) and \\(Aw = \\mu w\\) with \\(\\lambda \\neq \\mu\\), then \\(v\\) and \\(w\\) are:', options: ['Linearly independent','Parallel','Orthogonal','Equal up to a scalar'], answer: 0 },
    ],
    red: [
      { q: 'The characteristic polynomial of \\(A=\\begin{pmatrix}2&1\\\\4&2\\end{pmatrix}\\) is \\(\\lambda^2-4\\lambda\\). By Cayley-Hamilton, \\(A^3\\) equals:', options: ['\\(4A^2=16A\\)','\\(4A\\)','\\(A^2\\)','\\(16I\\)'], answer: 0 },
      { q: 'A \\(3\\times 3\\) matrix \\(A\\) has \\(\\det A = 0\\). The system \\(Ax=b\\) is consistent. This means:', options: ['Infinitely many solutions (line or plane of solutions)','Exactly one solution','No solutions','Two solutions'], answer: 0 },
      { q: 'For a rotation matrix \\(R_\\theta\\), \\(\\det(R_\\theta)\\) always equals:', options: ['1','\\(-1\\)','\\(\\cos\\theta\\)','\\(\\sin\\theta\\)'], answer: 0 },
      { q: 'If both eigenvalues of a \\(2\\times 2\\) matrix are 0, the matrix is:', options: ['Either the zero matrix or nilpotent','Always the zero matrix','Always invertible','Always symmetric'], answer: 0 },
      { q: 'For \\(A=\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}\\), what is \\(A^4\\)?', options: ['\\(I\\)','\\(-I\\)','\\(A\\)','\\(O\\)'], answer: 0 },
      { q: 'Three planes given by \\(Ax=b\\) form a "triangular prism" (no common point, two pairs intersecting in parallel lines). This means:', options: ['\\(\\det A = 0\\) and the system is inconsistent','\\(\\det A \\neq 0\\)','\\(\\det A = 0\\) and the system has a line of solutions','All three planes are parallel'], answer: 0 },
      { q: 'If \\(A\\) and \\(B\\) are similar matrices (\\(B=P^{-1}AP\\)), they have:', options: ['The same eigenvalues','The same eigenvectors','\\(A=B\\)','The same determinant but different traces'], answer: 0 },
      { q: 'The image of the unit circle under a linear transformation \\(A\\) is generally:', options: ['An ellipse','A circle','A square','A parabola'], answer: 0 },
      { q: 'For \\(2\\times 2\\) matrix with eigenvalues \\(\\lambda_1, \\lambda_2\\), the characteristic equation is:', options: ['\\(\\lambda^2-(\\lambda_1+\\lambda_2)\\lambda+\\lambda_1\\lambda_2=0\\)','\\(\\lambda^2+\\lambda_1\\lambda_2=0\\)','\\((\\lambda-\\lambda_1)(\\lambda+\\lambda_2)=0\\)','\\(\\lambda^2-(\\lambda_1-\\lambda_2)^2=0\\)'], answer: 0 },
      { q: 'A student claims that if \\(AB=O\\) then \\(A=O\\) or \\(B=O\\). This is:', options: ['False; e.g. \\(A=\\begin{pmatrix}1&1\\\\1&1\\end{pmatrix}\\), \\(B=\\begin{pmatrix}1&-1\\\\-1&1\\end{pmatrix}\\)','True always','True only for \\(2\\times 2\\) matrices','True when \\(\\det A\\neq 0\\)'], answer: 0 },
    ],
  },

  '1.3': {
    name: 'Further Algebra and Functions',
    green: [
      { q: 'For the quadratic \\(ax^2+bx+c=0\\) with roots \\(\\alpha,\\beta\\): \\(\\alpha+\\beta=\\)', options: ['\\(-b/a\\)','\\(b/a\\)','\\(c/a\\)','\\(-c/a\\)'], answer: 0 },
      { q: 'For the quadratic \\(ax^2+bx+c=0\\): \\(\\alpha\\beta=\\)', options: ['\\(c/a\\)','\\(-b/a\\)','\\(b/a\\)','\\(-c/a\\)'], answer: 0 },
      { q: 'For the cubic \\(ax^3+bx^2+cx+d=0\\) with roots \\(\\alpha,\\beta,\\gamma\\): \\(\\alpha\\beta\\gamma=\\)', options: ['\\(-d/a\\)','\\(d/a\\)','\\(c/a\\)','\\(-c/a\\)'], answer: 0 },
      { q: '\\(\\alpha^2+\\beta^2\\) can be written as:', options: ['\\((\\alpha+\\beta)^2-2\\alpha\\beta\\)','\\((\\alpha+\\beta)^2+2\\alpha\\beta\\)','\\((\\alpha-\\beta)^2\\)','\\(\\alpha\\beta(\\alpha+\\beta)\\)'], answer: 0 },
      { q: 'For the cubic \\(ax^3+bx^2+cx+d=0\\): \\(\\alpha+\\beta+\\gamma=\\)', options: ['\\(-b/a\\)','\\(b/a\\)','\\(c/a\\)','\\(d/a\\)'], answer: 0 },
      { q: 'The partial fraction form of \\(\\dfrac{f(x)}{(ax+b)(cx+d)}\\) with \\(\\deg f < 2\\) is:', options: ['\\(\\dfrac{A}{ax+b}+\\dfrac{B}{cx+d}\\)','\\(\\dfrac{Ax+B}{ax+b}+C\\)','\\(\\dfrac{A}{ax+b}+\\dfrac{Bx}{cx+d}\\)','\\(\\dfrac{A}{(ax+b)^2}+\\dfrac{B}{cx+d}\\)'], answer: 0 },
      { q: 'An improper rational function has:', options: ['Degree of numerator \\(\\geq\\) degree of denominator','Negative coefficients','Complex roots','No real roots'], answer: 0 },
      { q: '\\(|f(x)| < a\\) (where \\(a>0\\)) means:', options: ['\\(-a < f(x) < a\\)','\\(f(x) < a\\)','\\(f(x) > -a\\)','\\(f(x)^2 < a\\)'], answer: 0 },
      { q: 'The solutions to \\(|x-2| < 5\\) are:', options: ['\\(-3 < x < 7\\)','\\(x < 7\\) only','\\(x > -3\\) only','\\(-7 < x < 3\\)'], answer: 0 },
      { q: 'To solve a rational inequality, you should NOT:', options: ['Multiply both sides by a variable expression (unknown sign)','Rearrange to one side','Use a sign table','Test values in each interval'], answer: 0 },
      { q: 'For partial fractions with a repeated linear factor \\((ax+b)^2\\):', options: ['Use \\(\\frac{A}{ax+b}+\\frac{B}{(ax+b)^2}\\)','Use \\(\\frac{A}{(ax+b)^2}\\) only','Use \\(\\frac{Ax+B}{(ax+b)^2}\\)','Divide the numerator first'], answer: 0 },
      { q: 'If \\(\\alpha, \\beta\\) are roots of \\(x^2-5x+3=0\\), then \\(\\alpha+\\beta=\\)', options: ['5','\\(-5\\)','3','\\(-3\\)'], answer: 0 },
      { q: 'If \\(\\alpha, \\beta\\) are roots of \\(x^2-5x+3=0\\), then \\(\\alpha\\beta=\\)', options: ['3','5','\\(-3\\)','\\(-5\\)'], answer: 0 },
      { q: 'For the cubic \\(x^3-3x^2+5x-2=0\\) with roots \\(\\alpha,\\beta,\\gamma\\): \\(\\alpha\\beta+\\beta\\gamma+\\gamma\\alpha=\\)', options: ['5','3','\\(-3\\)','2'], answer: 0 },
      { q: 'The modulus function satisfies \\(|ab|=\\)', options: ['\\(|a||b|\\)','\\(|a|+|b|\\)','\\(|a-b|\\)','\\(a^2 b^2\\)'], answer: 0 },
      { q: 'An oblique asymptote occurs when:', options: ['Degree of numerator is exactly 1 more than denominator','Denominator has degree 2','Numerator has complex roots','The function is periodic'], answer: 0 },
      { q: '\\(|f(x)| > a\\) (where \\(a > 0\\)) means:', options: ['\\(f(x) > a\\) or \\(f(x) < -a\\)','\\(-a < f(x) < a\\)','\\(f(x)^2 > 0\\)','\\(f(x) > 0\\)'], answer: 0 },
      { q: 'For roots of \\(x^3+px^2+qx+r=0\\): \\(\\sum\\alpha\\beta=\\)', options: ['\\(q\\)','\\(-q\\)','\\(p\\)','\\(r\\)'], answer: 0 },
      { q: 'To convert \\(|f(x)|=|g(x)|\\) to a solvable equation, you:', options: ['Solve \\(f(x)=g(x)\\) and \\(f(x)=-g(x)\\)','Only solve \\(f(x)=g(x)\\)','Square to get \\(f^2=g^2\\) — that alone suffices','Set \\(f(x)-g(x)=0\\)'], answer: 0 },
      { q: 'For the partial fraction of \\(\\frac{f(x)}{(x^2+1)(x+2)}\\) where \\(x^2+1\\) is irreducible:', options: ['\\(\\frac{Ax+B}{x^2+1}+\\frac{C}{x+2}\\)','\\(\\frac{A}{x^2+1}+\\frac{B}{x+2}\\)','\\(\\frac{A}{(x+i)(x-i)}+\\frac{B}{x+2}\\)','\\(\\frac{Ax+B}{(x^2+1)^2}+\\frac{C}{x+2}\\)'], answer: 0 },
    ],
    amber: [
      { q: 'If \\(\\alpha,\\beta\\) are roots of \\(2x^2-3x+1=0\\), find \\(\\alpha^2+\\beta^2\\).', options: ['\\(5/4\\)','\\(9/4\\)','\\(1/2\\)','\\(5/2\\)'], answer: 0 },
      { q: 'If \\(\\alpha,\\beta,\\gamma\\) are roots of \\(x^3-2x^2+x-3=0\\), find \\(\\alpha^2+\\beta^2+\\gamma^2\\).', options: ['2','1','\\(-1\\)','4'], answer: 0 },
      { q: 'The equation \\(x^3-4x+1=0\\) has roots \\(\\alpha,\\beta,\\gamma\\). Find an equation with roots \\(2\\alpha,2\\beta,2\\gamma\\).', options: ['\\(x^3-16x+8=0\\)','\\(x^3-8x+2=0\\)','\\(x^3-8x+1=0\\)','\\(8x^3-16x+1=0\\)'], answer: 0 },
      { q: 'Decompose \\(\\dfrac{5x+1}{(x+1)(2x-1)}\\).', options: ['\\(\\dfrac{4/3}{x+1}+\\dfrac{7/3}{2x-1}\\)','\\(\\dfrac{2}{x+1}+\\dfrac{3}{2x-1}\\)','\\(\\dfrac{1}{x+1}+\\dfrac{2}{2x-1}\\)','\\(\\dfrac{5}{x+1}-\\dfrac{1}{2x-1}\\)'], answer: 0 },
      { q: 'Solve \\(\\dfrac{x-1}{x+2}>2\\).', options: ['\\(x<-5\\) or \\(x>-2\\) — wait, let me check: rearranging gives \\(\\frac{x-1-2(x+2)}{x+2}>0\\) i.e. \\(\\frac{-x-5}{x+2}>0\\)','\\(-5<x<-2\\)','\\(x>-2\\)','\\(x<-5\\)'], answer: 1 },
      { q: 'Solve \\(|3x-1|<|x+3|\\).', options: ['\\(-\\frac{1}{2}<x<2\\)','\\(x<-\\frac{1}{2}\\) or \\(x>2\\)','\\(-2<x<\\frac{1}{2}\\)','All real \\(x\\)'], answer: 0 },
      { q: 'For roots \\(\\alpha,\\beta\\) of \\(x^2-5x+6=0\\), find \\(\\frac{1}{\\alpha}+\\frac{1}{\\beta}\\).', options: ['\\(5/6\\)','\\(6/5\\)','\\(5\\)','\\(1\\)'], answer: 0 },
      { q: 'Express \\(\\dfrac{x^2+3x+5}{(x+1)(x+2)}\\) in partial fractions after appropriate preparation.', options: ['\\(1+\\dfrac{3}{x+1}-\\dfrac{1}{x+2}\\)','\\(\\dfrac{3}{x+1}+\\dfrac{1}{x+2}\\)','\\(1+\\dfrac{1}{x+1}+\\dfrac{3}{x+2}\\)','\\(x+\\dfrac{1}{x+1}\\)'], answer: 0 },
      { q: 'If \\(\\alpha,\\beta,\\gamma\\) are roots of \\(x^3+x-2=0\\), find \\(\\alpha\\beta\\gamma\\).', options: ['2','\\(-2\\)','1','0'], answer: 0 },
      { q: 'Solve \\(|2x+1|\\geq 5\\).', options: ['\\(x\\leq-3\\) or \\(x\\geq2\\)','\\(-3\\leq x\\leq 2\\)','\\(x\\geq2\\) only','\\(x\\leq-3\\) only'], answer: 0 },
      { q: 'The oblique asymptote of \\(y=\\dfrac{x^2+2x+3}{x+1}\\) is:', options: ['\\(y=x+1\\)','\\(y=x+2\\)','\\(y=x\\)','\\(y=x+3\\)'], answer: 0 },
      { q: 'If the roots of \\(x^3-6x^2+11x-6=0\\) are \\(1,2,3\\), what is the sum of squares of roots?', options: ['14','36','11','6'], answer: 0 },
      { q: 'Solve the inequality \\(\\dfrac{1}{x-2}>3\\).', options: ['\\(2<x<\\dfrac{7}{3}\\)','\\(x>\\dfrac{7}{3}\\)','\\(x<2\\) or \\(x>\\dfrac{7}{3}\\)','\\(x>2\\)'], answer: 0 },
      { q: 'Find the partial fraction decomposition of \\(\\dfrac{3}{x(x^2+3)}\\).', options: ['\\(\\dfrac{1}{x}-\\dfrac{x}{x^2+3}\\)','\\(\\dfrac{3}{x}-\\dfrac{3}{x^2+3}\\)','\\(\\dfrac{1}{x^2}+\\dfrac{1}{x^2+3}\\)','\\(\\dfrac{1}{x}+\\dfrac{x+1}{x^2+3}\\)'], answer: 0 },
      { q: 'For the equation \\(x^3-px^2+qx-r=0\\) (\\(p,q,r>0\\)) with roots \\(\\alpha,\\beta,\\gamma\\), \\(\\alpha^2\\beta^2+\\beta^2\\gamma^2+\\gamma^2\\alpha^2=\\)', options: ['\\(q^2-2pr\\)','\\(p^2-2q\\)','\\(q^2+2pr\\)','\\(p^2+2q\\)'], answer: 0 },
      { q: 'To find an equation with roots \\(\\alpha^2,\\beta^2,\\gamma^2\\) from \\(f(x)=0\\), you substitute:', options: ['\\(x=\\sqrt{w}\\) (i.e. \\(w=x^2\\) in the original)','\\(x=w^2\\)','\\(x=1/w\\)','\\(x=w+1\\)'], answer: 0 },
      { q: 'The solution set of \\(\\dfrac{x^2-1}{x^2+1}>0\\) is:', options: ['\\(x<-1\\) or \\(x>1\\)','\\(-1<x<1\\)','All \\(x\\neq 0\\)','No solutions'], answer: 0 },
      { q: 'If \\(\\alpha,\\beta\\) are roots of \\(x^2-4x+1=0\\), then \\(\\alpha^3+\\beta^3=\\)', options: ['52','64','\\(-52\\)','28'], answer: 0 },
      { q: 'Decompose \\(\\dfrac{4}{(x-1)^2(x+3)}\\).', options: ['\\(\\dfrac{1}{x-1}+\\dfrac{1}{(x-1)^2}-\\dfrac{1}{x+3}\\)','\\(\\dfrac{2}{x-1}+\\dfrac{4}{x+3}\\)','\\(\\dfrac{1}{(x-1)^2}+\\dfrac{1}{x+3}\\)','\\(\\dfrac{4}{(x-1)^2}-\\dfrac{4}{x+3}\\)'], answer: 0 },
      { q: 'For roots \\(\\alpha,\\beta,\\gamma,\\delta\\) of \\(x^4-5x^3+ax^2+bx+c=0\\): \\(\\alpha+\\beta+\\gamma+\\delta=\\)', options: ['5','\\(-5\\)','\\(a\\)','\\(c\\)'], answer: 0 },
    ],
    red: [
      { q: 'Given \\(\\alpha,\\beta\\) are roots of \\(x^2-3x+k=0\\) and \\(\\alpha^2+\\beta^2=5\\), find \\(k\\).', options: ['2','\\(-2\\)','4','\\(-4\\)'], answer: 0 },
      { q: 'The equation with roots \\(1/\\alpha^2, 1/\\beta^2\\) where \\(\\alpha,\\beta\\) satisfy \\(x^2-4x+2=0\\) is:', options: ['\\(2x^2-6x+1=0\\)','\\(2x^2+6x-1=0\\)','\\(x^2-6x+2=0\\)','\\(4x^2-6x+1=0\\)'], answer: 0 },
      { q: 'Solve \\(\\dfrac{2x-1}{x+1}\\leq\\dfrac{x}{x-2}\\).', options: ['\\(x\\leq\\frac{1}{2}\\) or \\(1<x<2\\) or... requires sign table','\\(x<-1\\)','\\(-1<x<2\\)','All real \\(x\\)'], answer: 0 },
      { q: 'For \\(\\alpha,\\beta,\\gamma\\) roots of \\(x^3-x+1=0\\), find \\(\\alpha^3+\\beta^3+\\gamma^3\\).', options: ['\\(-3\\)','3','0','1'], answer: 0 },
      { q: 'A student writes \\(\\dfrac{2}{x^2-1}=\\dfrac{A}{x-1}+\\dfrac{B}{x+1}\\) and finds \\(A=1,B=-1\\). Check: \\(A+B=\\)', options: ['0','2','\\(-2\\)','1'], answer: 0 },
      { q: 'Solve \\(|x^2-4|<3\\).', options: ['\\(-\\sqrt{7}<x<-1\\) or \\(1<x<\\sqrt{7}\\)','\\(-1<x<1\\)','\\(1<x<\\sqrt{7}\\)','\\(-\\sqrt{7}<x<\\sqrt{7}\\)'], answer: 0 },
      { q: 'If \\(f(x)=\\dfrac{x^3+1}{x^2-x}\\), the oblique asymptote is:', options: ['\\(y=x+1\\)','\\(y=x\\)','\\(y=x-1\\)','\\(y=x+2\\)'], answer: 0 },
      { q: 'For roots of \\(x^4-1=0\\): the sum of cubes of all roots equals:', options: ['0','\\(-1\\)','4','1'], answer: 0 },
      { q: 'If all roots of \\(p(x)=0\\) are doubled to get \\(q(x)=0\\), and \\(p(x)=x^3-6x^2+11x-6\\), then \\(q(x)=\\)', options: ['\\(x^3-12x^2+44x-48\\)','\\(x^3-3x^2+\\frac{11}{2}x-\\frac{3}{4}\\)','\\(8x^3-12x^2+11x-6\\)','\\(x^3-6x^2+22x-48\\)'], answer: 0 },
      { q: 'The inequality \\(\\dfrac{(x-1)^2}{x+2}>0\\) has solution:', options: ['\\(x>-2,\\ x\\neq 1\\)','\\(x<-2\\)','\\(x>1\\)','\\(x\\neq 1\\)'], answer: 0 },
    ],
  },

  '1.4': {
    name: 'Series',
    green: [
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}r =\\)', options: ['\\(\\frac{n(n+1)}{2}\\)','\\(\\frac{n(n-1)}{2}\\)','\\(n^2\\)','\\(\\frac{n(2n+1)}{2}\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}r^2 =\\)', options: ['\\(\\frac{n(n+1)(2n+1)}{6}\\)','\\(\\frac{n^2(n+1)^2}{4}\\)','\\(\\frac{n(n+1)}{2}\\)','\\(\\frac{n(2n+1)(2n-1)}{6}\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}r^3 =\\)', options: ['\\(\\left[\\frac{n(n+1)}{2}\\right]^2\\)','\\(\\frac{n^2(n+1)}{4}\\)','\\(\\frac{n(n+1)(2n+1)}{6}\\)','\\(\\frac{n^4}{4}\\)'], answer: 0 },
      { q: 'What is \\(\\displaystyle\\sum_{r=1}^{4}r^2\\)?', options: ['30','20','55','100'], answer: 0 },
      { q: 'In a proof by induction for a sum formula, the base case is checked at:', options: ['\\(n=1\\)','\\(n=0\\)','\\(n=k\\)','\\(n=k+1\\)'], answer: 0 },
      { q: 'The Maclaurin series for \\(e^x\\) is:', options: ['\\(1+x+\\frac{x^2}{2!}+\\frac{x^3}{3!}+\\cdots\\)','\\(1-x+\\frac{x^2}{2!}-\\cdots\\)','\\(x-\\frac{x^3}{3!}+\\cdots\\)','\\(1+x+x^2+x^3+\\cdots\\)'], answer: 0 },
      { q: 'The Maclaurin series for \\(\\sin x\\) is:', options: ['\\(x-\\frac{x^3}{3!}+\\frac{x^5}{5!}-\\cdots\\)','\\(1-\\frac{x^2}{2!}+\\frac{x^4}{4!}-\\cdots\\)','\\(x+\\frac{x^3}{3!}+\\cdots\\)','\\(1+x-\\frac{x^2}{2}+\\cdots\\)'], answer: 0 },
      { q: 'The Maclaurin series for \\(\\cos x\\) is:', options: ['\\(1-\\frac{x^2}{2!}+\\frac{x^4}{4!}-\\cdots\\)','\\(x-\\frac{x^3}{3!}+\\cdots\\)','\\(1+x^2/2+\\cdots\\)','\\(-\\sin x\\) series'], answer: 0 },
      { q: 'The Maclaurin series for \\(\\ln(1+x)\\) is valid for:', options: ['\\(-1<x\\leq 1\\)','All real \\(x\\)','\\(0<x<1\\)','\\(|x|<2\\)'], answer: 0 },
      { q: 'In method of differences, \\(\\displaystyle\\sum_{r=1}^{n}[f(r)-f(r+1)]=\\)', options: ['\\(f(1)-f(n+1)\\)','\\(f(n)-f(1)\\)','\\(f(n+1)-f(1)\\)','\\(nf(1)\\)'], answer: 0 },
      { q: 'What is the first term of the Maclaurin series for \\(\\ln(1+x)\\)?', options: ['\\(x\\)','0','1','\\(-x\\)'], answer: 0 },
      { q: 'The inductive step in a proof by induction shows:', options: ['If true for \\(n=k\\), it is true for \\(n=k+1\\)','The base case','The formula is true for all \\(n\\)','An explicit formula for \\(n=k+1\\)'], answer: 0 },
      { q: 'The Taylor series of \\(f(x)\\) about \\(x=a\\) begins:', options: ['\\(f(a)+f\'(a)(x-a)+\\cdots\\)','\\(f(0)+f\'(0)x+\\cdots\\)','\\(f(x)+f\'(x)+\\cdots\\)','\\(f(a)(x-a)+\\cdots\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}1 =\\)', options: ['\\(n\\)','1','\\(n^2\\)','\\(n(n+1)/2\\)'], answer: 0 },
      { q: 'What is \\(\\displaystyle\\sum_{r=1}^{3}r^3\\)?', options: ['36','9','100','16'], answer: 0 },
      { q: 'The Maclaurin series for \\((1+x)^{1/2}\\) valid for \\(|x|<1\\) starts:', options: ['\\(1+\\frac{1}{2}x-\\frac{1}{8}x^2+\\cdots\\)','\\(1+\\frac{1}{2}x+\\frac{1}{2}x^2+\\cdots\\)','\\(1-\\frac{1}{2}x+\\cdots\\)','\\(1+x-x^2+\\cdots\\)'], answer: 0 },
      { q: 'The range of validity of the Maclaurin series for \\(e^x\\) is:', options: ['All real \\(x\\)','\\(|x|<1\\)','\\(x>0\\)','\\(-1<x<1\\)'], answer: 0 },
      { q: 'Which of these is needed to complete an induction proof?', options: ['A conclusion sentence stating the result holds for all \\(n\\geq1\\)','Finding the general formula','Checking \\(n=2\\)','Differentiation'], answer: 0 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}c\\) (constant) equals:', options: ['\\(cn\\)','\\(c\\)','\\(cn^2\\)','\\(c/n\\)'], answer: 0 },
      { q: 'To find the Maclaurin series for \\(f(x)\\), you need:', options: ['\\(f(0), f\'(0), f\'\'(0), \\ldots\\)','\\(f(1), f\'(1), \\ldots\\)','\\(\\lim_{x\\to0} f(x)\\)','The antiderivative of \\(f\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find \\(\\displaystyle\\sum_{r=1}^{n}(2r-1)\\).', options: ['\\(n^2\\)','\\(n(n+1)\\)','\\(n(2n-1)\\)','\\(2n^2-n\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\sum_{r=n+1}^{2n}r\\).', options: ['\\(\\frac{n(3n+1)}{2}\\)','\\(\\frac{n(n+1)}{2}\\)','\\(n(2n+1)\\)','\\(\\frac{3n^2}{2}\\)'], answer: 0 },
      { q: 'Using partial fractions, \\(\\dfrac{1}{r(r+1)}=\\dfrac{1}{r}-\\dfrac{1}{r+1}\\). Hence \\(\\displaystyle\\sum_{r=1}^{n}\\dfrac{1}{r(r+1)}=\\)', options: ['\\(\\dfrac{n}{n+1}\\)','\\(1\\)','\\(\\dfrac{1}{n+1}\\)','\\(\\dfrac{n+1}{n}\\)'], answer: 0 },
      { q: 'Prove by induction that \\(4^n-1\\) is divisible by 3. In the inductive step you show:', options: ['\\(4^{k+1}-1=4(4^k-1)+3\\) which is divisible by 3','\\(4^{k+1}=4^k+4\\)','\\(4^{k+1}-1=(k+1)\\cdot 3\\)','\\(4^{k+1}=3m+1\\) for integer \\(m\\)'], answer: 0 },
      { q: 'Find the first three non-zero terms of the Maclaurin series for \\(\\sin^2 x\\).', options: ['\\(x^2-\\frac{x^4}{3}+\\frac{2x^6}{45}-\\cdots\\)','\\(x^2-x^4+x^6-\\cdots\\)','\\(1-\\cos 2x\\)','\\(x^2+\\frac{x^4}{3}+\\cdots\\)'], answer: 0 },
      { q: 'What is the Maclaurin series for \\(\\ln(1-x)\\)?', options: ['\\(-x-\\frac{x^2}{2}-\\frac{x^3}{3}-\\cdots\\)','\\(x+\\frac{x^2}{2}+\\frac{x^3}{3}+\\cdots\\)','\\(-x+\\frac{x^2}{2}-\\frac{x^3}{3}+\\cdots\\)','\\(1-x+x^2-\\cdots\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\sum_{r=1}^{n}r(r+1)\\).', options: ['\\(\\frac{n(n+1)(n+2)}{3}\\)','\\(\\frac{n(n+1)(2n+1)}{6}+\\frac{n(n+1)}{2}\\)','\\(\\frac{n^2(n+1)}{2}\\)','\\(\\frac{n(n+2)(2n+1)}{6}\\)'], answer: 0 },
      { q: 'By induction, prove \\(\\sum_{r=1}^n r^2=\\frac{n(n+1)(2n+1)}{6}\\). The key manipulation in the inductive step is:', options: ['\\(\\frac{k(k+1)(2k+1)}{6}+(k+1)^2=\\frac{(k+1)(k+2)(2k+3)}{6}\\)','\\(k^2+(k+1)^2=\\frac{(k+1)(2k+1)}{6}\\)','Subtract \\(k\\) from each side','Use the quadratic formula'], answer: 0 },
      { q: 'Using the series for \\(e^x\\), find \\(e^{0.1}\\) to 4 decimal places.', options: ['1.1052','1.1000','1.1051','1.0952'], answer: 0 },
      { q: 'The first three non-zero terms of the series for \\(e^x\\cos x\\) are:', options: ['\\(1+x-\\frac{x^3}{3}-\\cdots\\)','\\(1+x+x^2-\\cdots\\)','\\(1+x-x^2-\\cdots\\)','\\(1-x+\\frac{x^2}{2}-\\cdots\\)'], answer: 0 },
      { q: 'Using \\(\\frac{1}{r(r+2)}=\\frac{1}{2}\\left(\\frac{1}{r}-\\frac{1}{r+2}\\right)\\), \\(\\sum_{r=1}^n\\frac{1}{r(r+2)}\\) simplifies to:', options: ['\\(\\frac{3}{4}-\\frac{1}{2(n+1)}-\\frac{1}{2(n+2)}\\)','\\(\\frac{1}{2}\\left(1-\\frac{1}{n+2}\\right)\\)','\\(\\frac{1}{n+1}+\\frac{1}{n+2}\\)','\\(\\frac{1}{4}\\)'], answer: 0 },
      { q: 'Find the Taylor series of \\(\\ln x\\) about \\(x=1\\) up to \\((x-1)^2\\).', options: ['\\((x-1)-\\frac{(x-1)^2}{2}+\\cdots\\)','\\(\\ln 1+(x-1)+\\cdots\\)','\\((x-1)^2-\\cdots\\)','\\(1+(x-1)+\\cdots\\)'], answer: 0 },
      { q: 'Show \\(n^3+2n\\) is divisible by 3 by induction. The inductive step uses:', options: ['\\((k+1)^3+2(k+1)=k^3+3k^2+3k+1+2k+2=(k^3+2k)+3(k^2+k+1)\\)','\\(k^3+2k+3k+3\\)','Factoring \\(n(n^2+2)\\) as \\(n(n+1)(n-1)+3n\\)','The base case \\(n=0\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\sum_{r=1}^{n}\\frac{3}{(3r-2)(3r+1)}\\) by differences.', options: ['\\(\\dfrac{n}{3n+1}\\)','\\(\\dfrac{1}{n}\\)','\\(\\dfrac{3n}{3n+1}\\)','\\(1-\\dfrac{1}{3n+1}\\)'], answer: 0 },
      { q: 'What is the \\(x^3\\) term in the Maclaurin series for \\(\\sin x\\cdot e^x\\)?', options: ['\\(\\frac{x^3}{3}\\)','\\(-\\frac{x^3}{3}\\)','\\(x^3\\)','0'], answer: 0 },
      { q: 'In a proof by induction for divisibility, the inductive step must show:', options: ['The \\(k+1\\) case is also divisible (not just quote the \\(k\\) case)','The base case again','The general term','The closed form'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\sum_{r=1}^{n}(r^3-r)\\).', options: ['\\(\\frac{n^2(n+1)^2}{4}-\\frac{n(n+1)}{2}\\)','\\(\\frac{n(n+1)(n+2)}{6}\\)','\\(\\frac{n^2(n^2-1)}{4}\\)','\\(\\frac{n(n+1)^2(n-1)}{4}\\)'], answer: 0 },
      { q: 'What are the first three terms of the Maclaurin expansion of \\((1-x)^{-1}\\) for \\(|x|<1\\)?', options: ['\\(1+x+x^2+\\cdots\\)','\\(1-x+x^2-\\cdots\\)','\\(1+\\frac{x}{2}+\\frac{3x^2}{8}+\\cdots\\)','\\(1-\\frac{x}{2}+\\cdots\\)'], answer: 0 },
      { q: 'Prove by induction that \\(A^n=\\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}\\) for \\(A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\). The key multiplication in the inductive step is:', options: ['\\(\\begin{pmatrix}1&k\\\\0&1\\end{pmatrix}\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}=\\begin{pmatrix}1&k+1\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}^k=kA\\)','\\(A^{k+1}=A^k+A\\)','The base case'], answer: 0 },
      { q: 'What is \\(\\displaystyle\\sum_{r=1}^{\\infty}\\dfrac{1}{r(r+1)}\\)?', options: ['1','\\(1/2\\)','\\(\\infty\\)','\\(\\ln 2\\)'], answer: 0 },
      { q: 'The Taylor expansion of \\(f(x+h)\\) about \\(h=0\\) gives:', options: ['\\(f(x)+hf\'(x)+\\frac{h^2}{2!}f\'\'(x)+\\cdots\\)','\\(f(x+h)=f(h)+\\cdots\\)','\\(f(x)f(h)\\)','\\(\\sum hf\'(n)\\)'], answer: 0 },
    ],
    red: [
      { q: 'Prove \\(\\displaystyle\\sum_{r=1}^n r^3 = \\left[\\frac{n(n+1)}{2}\\right]^2\\) by induction. The key simplification is:', options: ['\\(\\left[\\frac{k(k+1)}{2}\\right]^2+(k+1)^3=\\left[\\frac{(k+1)(k+2)}{2}\\right]^2\\)','Showing the sum telescopes','Using the formula for \\(\\sum r^2\\)','Differentiating the formula'], answer: 0 },
      { q: 'The method of differences requires partial fractions. Which is the correct decomposition to evaluate \\(\\sum\\frac{r+1}{r(r+2)}\\)?', options: ['\\(\\frac{1/2}{r}+\\frac{3/2}{r+2}\\) — no wait, check: \\(r+1=A(r+2)+Br\\)','\\(\\frac{1}{r}-\\frac{1}{r+2}\\)','\\(\\frac{r+1}{r(r+2)}\\) does not telescope','\\(\\frac{2}{r(r+2)}\\)'], answer: 1 },
      { q: 'Use the Maclaurin series to estimate \\(\\displaystyle\\int_0^{0.1}\\frac{\\sin x}{x}\\,dx\\) to 4 decimal places.', options: ['0.0999','0.1000','0.0998','0.1001'], answer: 0 },
      { q: 'The range of validity of \\(\\ln(1+2x)\\) expanded as a Maclaurin series is:', options: ['\\(-\\frac{1}{2}<x\\leq\\frac{1}{2}\\)','\\(-1<x\\leq 1\\)','\\(|x|<\\frac{1}{2}\\)','All \\(x\\)'], answer: 0 },
      { q: 'By induction, prove \\(2^n>n^2\\) for \\(n\\geq 5\\). Which base case is used?', options: ['\\(n=5\\)','\\(n=1\\)','\\(n=2\\)','\\(n=4\\)'], answer: 0 },
      { q: 'Find the exact sum \\(\\displaystyle\\sum_{r=1}^{\\infty}\\dfrac{1}{4r^2-1}\\) using partial fractions.', options: ['\\(1/2\\)','1','\\(1/4\\)','\\(\\infty\\)'], answer: 0 },
      { q: 'The error in approximating \\(e\\) by \\(1+1+\\frac{1}{2!}+\\frac{1}{3!}+\\frac{1}{4!}\\) is less than:', options: ['\\(1/5!\\)','\\(1/4!\\)','\\(1/3!\\)','\\(1/6!\\)'], answer: 0 },
      { q: 'For the series \\(\\sum_{r=0}^{\\infty} ar^n=\\frac{a}{1-r}\\) (\\(|r|<1\\)): if \\(r=0.5\\) and \\(a=1\\), which Maclaurin series does this relate to?', options: ['\\((1-x)^{-1}\\) evaluated at \\(x=1/2\\)','\\(\\ln(1+x)\\) at \\(x=1/2\\)','\\(e^x\\) at \\(x=1/2\\)','\\(\\sin x\\) at \\(x=1/2\\)'], answer: 0 },
      { q: 'Using \\(\\cos^2\\theta = \\frac{1+\\cos2\\theta}{2}\\) and the Maclaurin series for \\(\\cos u\\), the series for \\(\\cos^2 x\\) up to \\(x^4\\) is:', options: ['\\(1-x^2+\\frac{x^4}{3}-\\cdots\\)','\\(1-x^2+x^4-\\cdots\\)','\\(1+x^2-x^4+\\cdots\\)','\\(\\frac{1}{2}+\\frac{1}{2}\\cos 2x\\) (not a power series form)'], answer: 0 },
      { q: 'A telescoping sum \\(\\sum_{r=1}^n f(r)\\) where \\(f(r)=g(r)-g(r+2)\\) (gap 2) gives:', options: ['\\(g(1)+g(2)-g(n+1)-g(n+2)\\)','\\(g(1)-g(n+2)\\)','\\(g(1)-g(n+1)\\)','\\(2g(1)-g(n+2)\\)'], answer: 0 },
    ],
  },

  '1.5': {
    name: 'Further Calculus',
    green: [
      { q: 'The arc length of \\(y=f(x)\\) from \\(a\\) to \\(b\\) is:', options: ['\\(\\displaystyle\\int_a^b\\sqrt{1+(dy/dx)^2}\\,dx\\)','\\(\\displaystyle\\int_a^b(dy/dx)\\,dx\\)','\\(\\displaystyle\\int_a^b\\sqrt{(dy/dx)^2}\\,dx\\)','\\(\\displaystyle\\int_a^b(1+dy/dx)\\,dx\\)'], answer: 0 },
      { q: 'The surface area when \\(y=f(x)\\) is rotated about the \\(x\\)-axis is:', options: ['\\(2\\pi\\displaystyle\\int y\\sqrt{1+(dy/dx)^2}\\,dx\\)','\\(\\pi\\displaystyle\\int y^2\\,dx\\)','\\(2\\pi\\displaystyle\\int y\\,dx\\)','\\(4\\pi\\displaystyle\\int y\\,dx\\)'], answer: 0 },
      { q: 'The mean value of \\(f(x)\\) over \\([a,b]\\) is:', options: ['\\(\\frac{1}{b-a}\\displaystyle\\int_a^b f(x)\\,dx\\)','\\(\\displaystyle\\int_a^b f(x)\\,dx\\)','\\(\\frac{f(a)+f(b)}{2}\\)','\\(\\frac{1}{2}\\displaystyle\\int_a^b f(x)\\,dx\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int\\frac{1}{\\sqrt{a^2-x^2}}\\,dx =\\)', options: ['\\(\\arcsin(x/a)+C\\)','\\(\\arctan(x/a)+C\\)','\\(-\\arcsin(x/a)+C\\)','\\(\\text{arccosh}(x/a)+C\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int\\frac{1}{a^2+x^2}\\,dx =\\)', options: ['\\(\\frac{1}{a}\\arctan(x/a)+C\\)','\\(\\arctan(x/a)+C\\)','\\(\\frac{1}{a}\\arcsin(x/a)+C\\)','\\(\\frac{x}{a^2}+C\\)'], answer: 0 },
      { q: 'An improper integral \\(\\displaystyle\\int_1^{\\infty}x^{-2}\\,dx\\):', options: ['Converges to 1','Diverges','Converges to \\(1/2\\)','Converges to \\(\\infty\\)'], answer: 0 },
      { q: 'An improper integral \\(\\displaystyle\\int_1^{\\infty}x^{-1}\\,dx\\):', options: ['Diverges','Converges to 1','Converges to \\(\\ln 2\\)','Converges to 0'], answer: 0 },
      { q: 'A reduction formula for \\(I_n\\) expresses it in terms of:', options: ['\\(I_{n-1}\\) or \\(I_{n-2}\\)','\\(I_{2n}\\)','\\(nI_1\\)','\\(I_0\\) only'], answer: 0 },
      { q: 'For \\(I_n=\\displaystyle\\int_0^{\\pi/2}\\sin^n x\\,dx\\), the reduction formula is \\(I_n=\\)', options: ['\\(\\frac{n-1}{n}I_{n-2}\\)','\\(\\frac{n}{n+1}I_{n-1}\\)','\\(\\frac{n-1}{n}I_{n-1}\\)','\\((n-1)I_{n-2}\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int_0^{\\pi/2}\\sin^2 x\\,dx=\\)', options: ['\\(\\pi/4\\)','\\(\\pi/2\\)','1','\\(1/2\\)'], answer: 0 },
      { q: 'Completing the square: \\(x^2+4x+13=\\)', options: ['\\((x+2)^2+9\\)','\\((x+4)^2+9\\)','\\((x+2)^2-9\\)','\\((x+2)^2+4\\)'], answer: 0 },
      { q: 'The \\(p\\)-test: \\(\\displaystyle\\int_1^{\\infty}x^{-p}\\,dx\\) converges iff:', options: ['\\(p>1\\)','\\(p<1\\)','\\(p>0\\)','\\(p\\neq 1\\)'], answer: 0 },
      { q: 'For the arc length in parametric form, the integrand is:', options: ['\\(\\sqrt{(dx/dt)^2+(dy/dt)^2}\\)','\\(\\sqrt{1+(dy/dt)^2}\\)','\\((dx/dt)^2+(dy/dt)^2\\)','\\(|dy/dx|\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int\\frac{dx}{\\sqrt{x^2+1}}=\\)', options: ['\\(\\text{arcsinh}\\,x+C\\)','\\(\\text{arccosh}\\,x+C\\)','\\(\\arctan x+C\\)','\\(\\ln(x+1)+C\\)'], answer: 0 },
      { q: 'The mean value of \\(f(x)=x^2\\) over \\([0,3]\\) is:', options: ['3','4','9','\\(9/4\\)'], answer: 0 },
      { q: 'Integration by parts reduces \\(\\displaystyle\\int x^n e^x\\,dx\\) using \\(I_n=\\)', options: ['\\(x^n e^x-nI_{n-1}\\)','\\(nx^{n-1}e^x\\)','\\(x^{n+1}e^x/(n+1)\\)','\\(e^x(x^n+n)\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int_0^1\\frac{1}{\\sqrt{1-x^2}}\\,dx=\\)', options: ['\\(\\pi/2\\)','\\(\\pi\\)','1','\\(\\pi/4\\)'], answer: 0 },
      { q: 'To evaluate \\(\\displaystyle\\int\\frac{dx}{(x+1)^2+4}\\):', options: ['Use \\(u=x+1\\) then \\(\\frac{1}{2}\\arctan\\frac{u}{2}+C\\)','Use \\(u=x^2+4\\)','Partial fractions','Integration by parts'], answer: 0 },
      { q: 'The surface area formula uses \\(y\\) because:', options: ['The radius of each circular strip is \\(y\\)','The length element is \\(y\\,dx\\)','\\(y\\) cancels out','It comes from the chain rule'], answer: 0 },
      { q: 'For \\(I_0=\\displaystyle\\int_0^{\\pi/2}\\sin^0 x\\,dx\\), \\(I_0=\\)', options: ['\\(\\pi/2\\)','0','1','\\(\\pi\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the arc length of \\(y=x^{3/2}\\) from \\(x=0\\) to \\(x=4\\) (simplify \\(1+(3\\sqrt{x}/2)^2\\)).', options: ['\\(\\frac{8}{27}(10\\sqrt{10}-1)\\)','\\(\\frac{2}{3}\\cdot 4^{3/2}\\)','\\(\\frac{8}{27}(5\\sqrt{5}-1)\\)','\\(\\frac{4}{3}(10^{3/2}-1)\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^2\\frac{1}{4+x^2}\\,dx\\).', options: ['\\(\\pi/8\\)','\\(\\pi/4\\)','\\(1/2\\)','\\(\\pi/2\\)'], answer: 0 },
      { q: 'Using the reduction formula \\(I_n=\\frac{n-1}{n}I_{n-2}\\), find \\(I_4=\\displaystyle\\int_0^{\\pi/2}\\sin^4 x\\,dx\\).', options: ['\\(3\\pi/16\\)','\\(\\pi/4\\)','\\(3/8\\)','\\(\\pi/8\\)'], answer: 0 },
      { q: 'Determine whether \\(\\displaystyle\\int_0^1 x^{-1/2}\\,dx\\) converges.', options: ['Converges to 2','Diverges','Converges to 1','Converges to \\(1/2\\)'], answer: 0 },
      { q: 'Find the mean value of \\(\\sin x\\) over \\([0,\\pi]\\).', options: ['\\(2/\\pi\\)','\\(1/\\pi\\)','\\(\\pi/2\\)','0'], answer: 0 },
      { q: 'Using \\(I_n = x^n e^x - nI_{n-1}\\), find \\(\\displaystyle\\int x^2 e^x\\,dx\\).', options: ['\\(e^x(x^2-2x+2)+C\\)','\\(e^x(x^2+2x+2)+C\\)','\\(x^2e^x-2xe^x+C\\)','\\(e^x(x^2-2)+C\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{2}{9+x^2}\\,dx\\).', options: ['\\(\\frac{2}{3}\\arctan(x/3)+C\\)','\\(\\frac{1}{3}\\arctan(x/3)+C\\)','\\(2\\arctan(x/9)+C\\)','\\(\\frac{2}{9}\\arctan x+C\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{1}{\\sqrt{9-x^2}}\\,dx\\).', options: ['\\(\\arcsin(x/3)+C\\)','\\(\\arctan(x/3)+C\\)','\\(\\frac{1}{3}\\arcsin x+C\\)','\\(-\\arccos(x/3)+C\\)'], answer: 0 },
      { q: 'Use completing the square to evaluate \\(\\displaystyle\\int\\frac{dx}{x^2+6x+13}\\).', options: ['\\(\\frac{1}{2}\\arctan\\frac{x+3}{2}+C\\)','\\(\\arctan(x+3)+C\\)','\\(\\frac{1}{4}\\arctan\\frac{x+3}{4}+C\\)','\\(\\ln(x^2+6x+13)+C\\)'], answer: 0 },
      { q: 'The surface area when \\(y=2\\sqrt{x}\\) (\\(0\\leq x\\leq 3\\)) is rotated about the \\(x\\)-axis is:', options: ['\\(2\\pi\\displaystyle\\int_0^3 2\\sqrt{x}\\sqrt{1+1/x}\\,dx\\)','\\(\\pi\\displaystyle\\int_0^3 4x\\,dx\\)','\\(2\\pi\\displaystyle\\int_0^3 \\sqrt{x}\\,dx\\)','\\(4\\pi\\displaystyle\\int_0^3 \\sqrt{x+1}\\,dx\\)'], answer: 0 },
      { q: 'Derive the reduction formula for \\(\\displaystyle\\int\\cos^n x\\,dx\\). It is \\(I_n=\\)', options: ['\\(\\frac{\\cos^{n-1}x\\sin x}{n}+\\frac{n-1}{n}I_{n-2}\\)','\\(\\frac{n-1}{n}I_{n-2}\\) (definite over \\([0,\\pi/2]\\))','\\(\\sin x\\cos^{n-1}x+(n-1)I_{n-2}\\)','\\(\\frac{1}{n}I_{n-1}\\)'], answer: 0 },
      { q: 'Find the arc length of the parametric curve \\(x=3t^2\\), \\(y=2t^3\\) from \\(t=0\\) to \\(t=1\\).', options: ['\\(2(2\\sqrt{2}-1)\\)','\\(\\sqrt{13}\\)','\\(2\\sqrt{2}\\)','3'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_1^{\\infty}\\frac{1}{x^3}\\,dx\\).', options: ['\\(1/2\\)','1','\\(\\infty\\)','\\(1/3\\)'], answer: 0 },
      { q: 'Use partial fractions to find \\(\\displaystyle\\int\\frac{1}{(x-1)(x+3)}\\,dx\\).', options: ['\\(\\frac{1}{4}\\ln\\left|\\frac{x-1}{x+3}\\right|+C\\)','\\(\\frac{1}{4}\\ln|x-1|+\\ln|x+3|+C\\)','\\(\\ln|x^2+2x-3|+C\\)','\\(\\frac{1}{4}\\ln|(x-1)(x+3)|+C\\)'], answer: 0 },
      { q: 'The reduction formula \\(I_n=\\frac{n-1}{n}I_{n-2}\\) gives \\(I_5=\\displaystyle\\int_0^{\\pi/2}\\sin^5 x\\,dx=\\)', options: ['\\(8/15\\)','\\(3\\pi/16\\)','\\(4/15\\)','\\(16/15\\)'], answer: 0 },
      { q: 'For the mean value of \\(f(x)=e^x\\) over \\([0,2]\\):', options: ['\\(\\frac{e^2-1}{2}\\)','\\(e^2-1\\)','\\(e^2/2\\)','\\(e-1\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^{\\infty} e^{-x}\\,dx\\).', options: ['1','0','\\(\\infty\\)','\\(e\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{x}{x^2+4}\\,dx\\).', options: ['\\(\\frac{1}{2}\\ln(x^2+4)+C\\)','\\(\\ln(x^2+4)+C\\)','\\(\\frac{1}{2}\\arctan(x/2)+C\\)','\\(\\frac{x^2}{2(x^2+4)}+C\\)'], answer: 0 },
      { q: 'The surface area formula \\(2\\pi\\int y\\,ds\\) requires \\(ds\\) to be:', options: ['\\(\\sqrt{1+(dy/dx)^2}\\,dx\\)','\\(dy\\)','\\(dx\\)','\\(\\sqrt{dx^2+dy^2}\\)'], answer: 0 },
    ],
    red: [
      { q: 'Find the arc length of \\(y=\\cosh x\\) from \\(x=0\\) to \\(x=1\\).', options: ['\\(\\sinh 1\\)','\\(\\cosh 1-1\\)','\\(\\cosh 1\\)','1'], answer: 0 },
      { q: 'Use the reduction formula to find \\(\\displaystyle\\int_0^{\\pi/2}\\sin^6 x\\,dx\\).', options: ['\\(5\\pi/32\\)','\\(3\\pi/16\\)','\\(5/16\\)','\\(\\pi/4\\)'], answer: 0 },
      { q: 'The improper integral \\(\\displaystyle\\int_0^1\\ln x\\,dx\\) equals:', options: ['\\(-1\\)','0','\\(-\\ln 1\\)','1'], answer: 0 },
      { q: 'For large \\(n\\), \\(\\displaystyle\\int_0^{\\pi/2}\\sin^n x\\,dx\\) behaves like:', options: ['\\(\\sqrt{\\pi/(2n)}\\) (Stirling)','\\(1/n\\)','\\(\\pi/n\\)','\\(2/n\\)'], answer: 0 },
      { q: 'The value of \\(\\displaystyle\\int_0^{\\infty}\\frac{1}{1+x^2}\\,dx\\) is:', options: ['\\(\\pi/2\\)','\\(\\pi\\)','1','\\(\\pi/4\\)'], answer: 0 },
      { q: 'Show the mean value of \\(\\cos^2 x\\) over \\([0,\\pi]\\) is:', options: ['\\(1/2\\)','\\(\\pi/2\\)','0','1'], answer: 0 },
      { q: 'Derive the reduction formula for \\(\\displaystyle\\int_0^{\\pi/2}\\cos^n x\\,dx\\): it equals the same formula as for \\(\\sin^n x\\) because:', options: ['By the substitution \\(x=\\pi/2-u\\), which swaps \\(\\sin\\) and \\(\\cos\\)','The functions are equal','The limits force equality','Integration by parts gives the same result'], answer: 0 },
      { q: 'Determine whether \\(\\displaystyle\\int_1^{\\infty}\\frac{x}{x^2+1}\\,dx\\) converges.', options: ['Diverges (behaves like \\(1/x\\))', 'Converges to \\(\\pi/2\\)','Converges to 1','Converges to \\(\\ln 2\\)'], answer: 0 },
      { q: 'The arc length formula can be derived from:', options: ['Summing \\(\\sqrt{(\\Delta x)^2+(\\Delta y)^2}\\) and taking the limit','\\(\\int y\\,dx\\)','\\(\\int (1+y^2)\\,dx\\)','The surface area formula divided by \\(2\\pi\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^{\\infty} x e^{-x}\\,dx\\) using the reduction formula \\(I_n = n\\cdot I_{n-1}\\) (where \\(I_n=\\int_0^{\\infty}x^n e^{-x}\\,dx=n!\\)).', options: ['1','\\(e\\)','\\(1/e\\)','\\(\\infty\\)'], answer: 0 },
    ],
  },

  '1.6': {
    name: 'Further Vectors',
    green: [
      { q: 'The dot product \\(\\mathbf{a}\\cdot\\mathbf{b}=\\)', options: ['\\(|\\mathbf{a}||\\mathbf{b}|\\cos\\theta\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\sin\\theta\\)','\\(|\\mathbf{a}|+|\\mathbf{b}|\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\tan\\theta\\)'], answer: 0 },
      { q: '\\(\\mathbf{a}\\cdot\\mathbf{b}=0\\) implies:', options: ['\\(\\mathbf{a}\\perp\\mathbf{b}\\)','\\(\\mathbf{a}\\parallel\\mathbf{b}\\)','\\(|\\mathbf{a}|=|\\mathbf{b}|\\)','\\(\\mathbf{a}=-\\mathbf{b}\\)'], answer: 0 },
      { q: 'The magnitude of the cross product \\(|\\mathbf{a}\\times\\mathbf{b}|=\\)', options: ['\\(|\\mathbf{a}||\\mathbf{b}|\\sin\\theta\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\cos\\theta\\)','\\(|\\mathbf{a}|\\cdot|\\mathbf{b}|\\)','\\(|\\mathbf{a}|+|\\mathbf{b}|\\)'], answer: 0 },
      { q: '\\(\\mathbf{a}\\times\\mathbf{b}=\\mathbf{0}\\) implies:', options: ['\\(\\mathbf{a}\\parallel\\mathbf{b}\\) (or one is zero)','\\(\\mathbf{a}\\perp\\mathbf{b}\\)','\\(\\mathbf{a}=\\mathbf{b}\\)','\\(\\mathbf{a}=-\\mathbf{b}\\)'], answer: 0 },
      { q: '\\(\\mathbf{a}\\times\\mathbf{b}=\\)', options: ['\\(-\\mathbf{b}\\times\\mathbf{a}\\)','\\(\\mathbf{b}\\times\\mathbf{a}\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\)','\\(\\mathbf{a}\\cdot\\mathbf{b}\\)'], answer: 0 },
      { q: 'The area of a parallelogram with sides \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) is:', options: ['\\(|\\mathbf{a}\\times\\mathbf{b}|\\)','\\(\\mathbf{a}\\cdot\\mathbf{b}\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\)','\\(\\frac{1}{2}|\\mathbf{a}||\\mathbf{b}|\\)'], answer: 0 },
      { q: 'The area of a triangle with sides \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) is:', options: ['\\(\\frac{1}{2}|\\mathbf{a}\\times\\mathbf{b}|\\)','\\(|\\mathbf{a}\\times\\mathbf{b}|\\)','\\(\\frac{1}{2}\\mathbf{a}\\cdot\\mathbf{b}\\)','\\(|\\mathbf{a}|\\cdot|\\mathbf{b}|\\)'], answer: 0 },
      { q: 'The equation of a line in vector form is:', options: ['\\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}\\)','\\(\\mathbf{r}\\cdot\\mathbf{n}=d\\)','\\(\\mathbf{r}=\\lambda\\mathbf{n}\\)','\\(\\mathbf{r}=\\mathbf{a}+\\mathbf{b}\\)'], answer: 0 },
      { q: 'The equation of a plane in vector form is:', options: ['\\(\\mathbf{r}\\cdot\\mathbf{n}=d\\)','\\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}\\)','\\(\\mathbf{r}=\\lambda\\mathbf{a}+\\mu\\mathbf{b}\\)','\\(\\mathbf{r}\\times\\mathbf{n}=0\\)'], answer: 0 },
      { q: 'The scalar triple product \\(\\mathbf{a}\\cdot(\\mathbf{b}\\times\\mathbf{c})\\) gives:', options: ['The volume of a parallelepiped','The area of a face','The length of \\(\\mathbf{a}\\)','\\(|\\mathbf{a}||\\mathbf{b}||\\mathbf{c}|\\)'], answer: 0 },
      { q: 'Vectors \\(\\mathbf{a},\\mathbf{b},\\mathbf{c}\\) are coplanar iff:', options: ['\\(\\mathbf{a}\\cdot(\\mathbf{b}\\times\\mathbf{c})=0\\)','\\(\\mathbf{a}\\times\\mathbf{b}=\\mathbf{c}\\)','\\(\\mathbf{a}=\\mathbf{b}+\\mathbf{c}\\)','Their magnitudes are equal'], answer: 0 },
      { q: 'The angle \\(\\theta\\) between lines with directions \\(\\mathbf{d}_1\\), \\(\\mathbf{d}_2\\) satisfies:', options: ['\\(\\cos\\theta=\\frac{|\\mathbf{d}_1\\cdot\\mathbf{d}_2|}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(\\sin\\theta=\\frac{\\mathbf{d}_1\\cdot\\mathbf{d}_2}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(\\tan\\theta=\\frac{|\\mathbf{d}_1\\times\\mathbf{d}_2|}{\\mathbf{d}_1\\cdot\\mathbf{d}_2}\\)','\\(\\cos\\theta=\\frac{\\mathbf{d}_1\\times\\mathbf{d}_2}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)'], answer: 0 },
      { q: '\\(\\mathbf{i}\\times\\mathbf{j}=\\)', options: ['\\(\\mathbf{k}\\)','\\(-\\mathbf{k}\\)','\\(\\mathbf{i}\\)','\\(\\mathbf{0}\\)'], answer: 0 },
      { q: 'The distance from point \\(P\\) to plane \\(ax+by+cz=d\\) is:', options: ['\\(\\frac{|ax_0+by_0+cz_0-d|}{\\sqrt{a^2+b^2+c^2}}\\)','\\(|ax_0+by_0+cz_0-d|\\)','\\(\\frac{d}{\\sqrt{a^2+b^2+c^2}}\\)','\\(|\\mathbf{OP}|\\)'], answer: 0 },
      { q: 'Two lines in 3D that neither intersect nor are parallel are called:', options: ['Skew','Perpendicular','Coplanar','Tangent'], answer: 0 },
      { q: 'The normal to the plane \\(2x+3y-z=5\\) is:', options: ['\\(\\begin{pmatrix}2\\\\3\\\\-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}5\\\\0\\\\0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-2\\\\-3\\\\1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'To find the angle between a line and a plane, use:', options: ['\\(\\sin\\phi=\\frac{|\\mathbf{d}\\cdot\\mathbf{n}|}{|\\mathbf{d}||\\mathbf{n}|}\\)','\\(\\cos\\phi=\\frac{\\mathbf{d}\\cdot\\mathbf{n}}{|\\mathbf{d}||\\mathbf{n}|}\\)','\\(\\cos\\phi=\\frac{|\\mathbf{d}\\times\\mathbf{n}|}{|\\mathbf{d}||\\mathbf{n}|}\\)','\\(\\tan\\phi=\\frac{|\\mathbf{d}|}{|\\mathbf{n}|}\\)'], answer: 0 },
      { q: '\\(\\mathbf{a}\\times\\mathbf{a}=\\)', options: ['\\(\\mathbf{0}\\)','\\(|\\mathbf{a}|^2\\)','\\(\\mathbf{a}\\)','1'], answer: 0 },
      { q: 'The Cartesian symmetric form of the line through \\((1,2,3)\\) with direction \\(\\begin{pmatrix}4\\\\5\\\\6\\end{pmatrix}\\) is:', options: ['\\(\\frac{x-1}{4}=\\frac{y-2}{5}=\\frac{z-3}{6}\\)','\\(\\frac{x}{1}=\\frac{y}{2}=\\frac{z}{3}\\)','\\(\\frac{x+1}{4}=\\frac{y+2}{5}=\\frac{z+3}{6}\\)','\\(4x+5y+6z=1\\)'], answer: 0 },
      { q: 'The scalar triple product equals the \\(3\\times 3\\) determinant with:', options: ['Rows \\(\\mathbf{a},\\mathbf{b},\\mathbf{c}\\)','Columns \\(\\mathbf{a}\\times\\mathbf{b},\\mathbf{b}\\times\\mathbf{c},\\mathbf{c}\\times\\mathbf{a}\\)','Diagonal entries only','The cross product on the diagonal'], answer: 0 },
    ],
    amber: [
      { q: 'Find \\(\\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}\\times\\begin{pmatrix}4\\\\5\\\\6\\end{pmatrix}\\).', options: ['\\(\\begin{pmatrix}-3\\\\6\\\\-3\\end{pmatrix}\\)','\\(\\begin{pmatrix}3\\\\-6\\\\3\\end{pmatrix}\\)','\\(\\begin{pmatrix}12\\\\10\\\\18\\end{pmatrix}\\)','\\(\\begin{pmatrix}-3\\\\-6\\\\-3\\end{pmatrix}\\)'], answer: 0 },
      { q: 'Find the distance from \\((1,2,3)\\) to the plane \\(2x+y-2z=5\\).', options: ['\\(2/3\\)','\\(2\\)','\\(1/3\\)','\\(4/3\\)'], answer: 0 },
      { q: 'Find the angle between the planes \\(x+y+z=1\\) and \\(x-y+z=2\\).', options: ['\\(\\arccos(1/3)\\)','\\(\\arccos(2/3)\\)','\\(60°\\)','\\(90°\\)'], answer: 0 },
      { q: 'Lines \\(\\ell_1:\\mathbf{r}=\\begin{pmatrix}1\\\\0\\\\0\\end{pmatrix}+\\lambda\\begin{pmatrix}1\\\\1\\\\0\\end{pmatrix}\\) and \\(\\ell_2:\\mathbf{r}=\\begin{pmatrix}0\\\\1\\\\0\\end{pmatrix}+\\mu\\begin{pmatrix}0\\\\1\\\\1\\end{pmatrix}\\) — do they intersect?', options: ['Yes, at \\((1,1,0)\\) when \\(\\lambda=0,\\mu=0\\)','No, they are skew','No, they are parallel','Yes, at the origin'], answer: 0 },
      { q: 'Find the equation of the plane through \\((1,0,0)\\), \\((0,1,0)\\), \\((0,0,1)\\).', options: ['\\(x+y+z=1\\)','\\(x+y+z=0\\)','\\(x-y+z=1\\)','\\(x+y-z=1\\)'], answer: 0 },
      { q: 'The volume of the parallelepiped with edges \\(\\mathbf{i}+\\mathbf{j}\\), \\(\\mathbf{j}+\\mathbf{k}\\), \\(\\mathbf{i}+\\mathbf{k}\\) is:', options: ['2','1','\\(\\sqrt{2}\\)','4'], answer: 0 },
      { q: 'Find the shortest distance between skew lines \\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}_1\\) and \\(\\mathbf{r}=\\mathbf{b}+\\mu\\mathbf{d}_2\\) using:', options: ['\\(\\frac{|(\\mathbf{b}-\\mathbf{a})\\cdot(\\mathbf{d}_1\\times\\mathbf{d}_2)|}{|\\mathbf{d}_1\\times\\mathbf{d}_2|}\\)','\\(|\\mathbf{b}-\\mathbf{a}|\\)','\\(\\frac{|\\mathbf{d}_1\\cdot\\mathbf{d}_2|}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(|(\\mathbf{b}-\\mathbf{a})\\times\\mathbf{d}_1|\\)'], answer: 0 },
      { q: 'The intersection of the plane \\(\\mathbf{r}\\cdot\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}=3\\) with the line \\(\\mathbf{r}=\\begin{pmatrix}0\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}\\) occurs at \\(t=\\)', options: ['1','3','\\(1/3\\)','0'], answer: 0 },
      { q: 'If \\(\\mathbf{a}=(1,2,3)\\) and \\(\\mathbf{b}=(2,0,1)\\), find \\(\\mathbf{a}\\cdot\\mathbf{b}\\).', options: ['5','4','7','\\(-5\\)'], answer: 0 },
      { q: 'Three planes meet in a unique point iff:', options: ['\\(\\det(A)\\neq 0\\) where \\(A\\) is the coefficient matrix','\\(\\det(A)=0\\)','All normals are parallel','Any two planes are parallel'], answer: 0 },
      { q: 'The angle between the line \\(\\mathbf{r}=\\begin{pmatrix}0\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\0\\\\1\\end{pmatrix}\\) and the plane \\(z=0\\) is:', options: ['\\(45°\\)','\\(90°\\)','\\(30°\\)','\\(60°\\)'], answer: 0 },
      { q: 'The cross product \\(\\mathbf{a}\\times\\mathbf{b}\\) is perpendicular to:', options: ['Both \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\)','\\(\\mathbf{a}\\) only','\\(\\mathbf{b}\\) only','Neither'], answer: 0 },
      { q: 'The area of the triangle with vertices \\(A(1,0,0)\\), \\(B(0,1,0)\\), \\(C(0,0,1)\\) is:', options: ['\\(\\frac{\\sqrt{3}}{2}\\)','\\(\\frac{1}{2}\\)','\\(\\sqrt{3}\\)','1'], answer: 0 },
      { q: 'A plane contains the line \\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}\\) iff the normal \\(\\mathbf{n}\\) satisfies:', options: ['\\(\\mathbf{n}\\cdot\\mathbf{d}=0\\) and \\(\\mathbf{n}\\cdot\\mathbf{a}=d\\)','\\(\\mathbf{n}=\\mathbf{d}\\)','\\(\\mathbf{n}\\cdot\\mathbf{a}=0\\)','\\(\\mathbf{n}\\times\\mathbf{d}=\\mathbf{0}\\)'], answer: 0 },
      { q: 'To find the line of intersection of two planes, compute:', options: ['The cross product of their normals (direction) and a point on both','Their dot product','The sum of their normal equations','The difference of their equations'], answer: 0 },
      { q: 'For the line \\(\\frac{x-1}{2}=\\frac{y+1}{3}=\\frac{z}{1}\\), the direction vector is:', options: ['\\(\\begin{pmatrix}2\\\\3\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\-1\\\\0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}\\)','\\(\\begin{pmatrix}2\\\\-3\\\\0\\end{pmatrix}\\)'], answer: 0 },
      { q: 'Find \\(\\begin{pmatrix}2\\\\1\\\\0\\end{pmatrix}\\cdot\\left(\\begin{pmatrix}1\\\\0\\\\1\\end{pmatrix}\\times\\begin{pmatrix}0\\\\1\\\\1\\end{pmatrix}\\right)\\).', options: ['1','\\(-1\\)','0','2'], answer: 0 },
      { q: 'The distance between the parallel planes \\(x+y+z=1\\) and \\(x+y+z=4\\) is:', options: ['\\(\\sqrt{3}\\)','3','1','\\(3/\\sqrt{3}=\\sqrt{3}\\)'], answer: 0 },
      { q: 'Two lines intersect if and only if they are:', options: ['Coplanar and not parallel','Parallel','Skew','Perpendicular'], answer: 0 },
    ],
    red: [
      { q: 'Show that the lines \\(\\mathbf{r}=(1+t,2+t,t)\\) and \\(\\mathbf{r}=(2+s,3+2s,1+s)\\) are skew. The key test is:', options: ['\\(\\det(\\mathbf{b}-\\mathbf{a},\\mathbf{d}_1,\\mathbf{d}_2)\\neq 0\\)','\\(\\mathbf{d}_1=\\mathbf{d}_2\\)','Their dot product equals zero','The normals are perpendicular'], answer: 0 },
      { q: 'For three planes with \\(\\det A=0\\) and consistent equations, the solution is:', options: ['A line or plane (infinitely many solutions)','A unique point','No solution','Two discrete points'], answer: 0 },
      { q: 'The distance from \\((0,0,0)\\) to the plane \\(3x+4y+0z=10\\) is:', options: ['2','10','\\(10/5=2\\)','\\(10/\\sqrt{25}=2\\)'], answer: 0 },
      { q: 'If \\(\\mathbf{a}\\times\\mathbf{b}=\\mathbf{c}\\) and \\(\\mathbf{a}\\times\\mathbf{d}=\\mathbf{c}\\), then:', options: ['\\(\\mathbf{b}-\\mathbf{d}\\) is parallel to \\(\\mathbf{a}\\)','\\(\\mathbf{b}=\\mathbf{d}\\)','\\(\\mathbf{b}+\\mathbf{d}=2\\mathbf{c}\\)','\\(\\mathbf{c}=\\mathbf{0}\\)'], answer: 0 },
      { q: 'The foot of the perpendicular from \\(P=(1,2,3)\\) to the plane \\(x+y+z=0\\) is:', options: ['\\((-1,0,1)\\)','\\((1,2,3)/3\\)','\\((0,0,0)\\)','\\((-2,-1,0)\\)'], answer: 0 },
      { q: 'Three planes \\(x+y=1\\), \\(y+z=1\\), \\(x+z=1\\) intersect in:', options: ['The unique point \\((\\frac{1}{2},\\frac{1}{2},\\frac{1}{2})\\)','A line','No solution','Two points'], answer: 0 },
      { q: 'If \\(|\\mathbf{a}\\times\\mathbf{b}|=|\\mathbf{a}\\cdot\\mathbf{b}|\\), then the angle between \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) satisfies:', options: ['\\(\\sin\\theta=\\cos\\theta\\), so \\(\\theta=\\pi/4\\)','\\(\\theta=\\pi/2\\)','\\(\\theta=0\\)','\\(\\sin\\theta=1\\)'], answer: 0 },
      { q: 'A student finds the line of intersection of two planes and gets \\(\\mathbf{r}=\\begin{pmatrix}1\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\1\\\\0\\end{pmatrix}\\). To verify, they should:', options: ['Substitute into both plane equations and confirm they hold for all \\(t\\)','Find the determinant','Compute the cross product of the normals','Check the point \\((1,0,0)\\) only'], answer: 0 },
      { q: 'For a tetrahedron with one vertex at \\(O\\) and adjacent vertices at \\(A\\), \\(B\\), \\(C\\), its volume is:', options: ['\\(\\frac{1}{6}|\\overrightarrow{OA}\\cdot(\\overrightarrow{OB}\\times\\overrightarrow{OC})|\\)','\\(|\\overrightarrow{OA}\\times\\overrightarrow{OB}|\\)','\\(\\frac{1}{3}|\\overrightarrow{OA}||\\overrightarrow{OB}||\\overrightarrow{OC}|\\)','\\(\\frac{1}{2}|\\overrightarrow{OA}\\cdot(\\overrightarrow{OB}\\times\\overrightarrow{OC})|\\)'], answer: 0 },
      { q: 'Two planes with normals \\(\\mathbf{n}_1\\) and \\(\\mathbf{n}_2\\) are perpendicular iff:', options: ['\\(\\mathbf{n}_1\\cdot\\mathbf{n}_2=0\\)','\\(\\mathbf{n}_1=\\mathbf{n}_2\\)','\\(\\mathbf{n}_1\\times\\mathbf{n}_2=\\mathbf{0}\\)','\\(|\\mathbf{n}_1|=|\\mathbf{n}_2|\\)'], answer: 0 },
    ],
  },

  '1.7': {
    name: 'Polar Coordinates',
    green: [
      { q: 'The conversion \\(x=\\)', options: ['\\(r\\cos\\theta\\)','\\(r\\sin\\theta\\)','\\(r/\\cos\\theta\\)','\\(r\\tan\\theta\\)'], answer: 0 },
      { q: 'The conversion \\(y=\\)', options: ['\\(r\\sin\\theta\\)','\\(r\\cos\\theta\\)','\\(r/\\sin\\theta\\)','\\(r\\cot\\theta\\)'], answer: 0 },
      { q: '\\(r^2=\\)', options: ['\\(x^2+y^2\\)','\\(x^2-y^2\\)','\\(xy\\)','\\((x+y)^2\\)'], answer: 0 },
      { q: 'The polar equation \\(r=a\\) represents:', options: ['A circle centre \\(O\\) radius \\(a\\)','A straight line','A parabola','A spiral'], answer: 0 },
      { q: 'The polar area formula is:', options: ['\\(\\frac{1}{2}\\displaystyle\\int r^2\\,d\\theta\\)','\\(\\displaystyle\\int r\\,d\\theta\\)','\\(\\frac{1}{2}\\displaystyle\\int r\\,d\\theta\\)','\\(\\displaystyle\\int r^2\\,d\\theta\\)'], answer: 0 },
      { q: 'The cardioid \\(r=a(1+\\cos\\theta)\\) passes through the origin at \\(\\theta=\\)', options: ['\\(\\pi\\)','0','\\(\\pi/2\\)','\\(2\\pi\\)'], answer: 0 },
      { q: 'The maximum value of \\(r\\) for \\(r=3(1+\\cos\\theta)\\) is:', options: ['6','3','9','\\(3\\sqrt{2}\\)'], answer: 0 },
      { q: 'A curve with equation \\(r=\\cos(2\\theta)\\) (rose curve) has how many petals?', options: ['4','2','8','1'], answer: 0 },
      { q: 'The lemniscate \\(r^2=a^2\\cos(2\\theta)\\) exists only when:', options: ['\\(\\cos(2\\theta)\\geq 0\\)','\\(r\\geq 0\\)','\\(\\theta\\in[0,\\pi]\\)','\\(r=a\\)'], answer: 0 },
      { q: 'To find \\(dy/dx\\) for a polar curve, use:', options: ['\\(\\frac{dy/d\\theta}{dx/d\\theta}\\)','\\(dr/d\\theta\\)','\\(r/\\theta\\)','\\(dr/dx\\)'], answer: 0 },
      { q: 'The Archimedean spiral \\(r=a\\theta\\) has what kind of spacing?', options: ['Uniform spacing between turns','Exponentially increasing spacing','Decreasing spacing','Random spacing'], answer: 0 },
      { q: '\\(\\tan\\theta = \\)', options: ['\\(y/x\\)','\\(x/y\\)','\\(r/x\\)','\\(x/r\\)'], answer: 0 },
      { q: 'The polar curve \\(r=a\\cos\\theta\\) is a:', options: ['Circle with diameter on initial line','Cardioid','Spiral','Rose curve'], answer: 0 },
      { q: 'When computing the area enclosed by \\(r=f(\\theta)\\) for \\(\\alpha\\leq\\theta\\leq\\beta\\), we integrate:', options: ['\\(\\frac{1}{2}\\int_\\alpha^\\beta r^2\\,d\\theta\\)','\\(\\int_\\alpha^\\beta r\\,d\\theta\\)','\\(\\pi\\int_\\alpha^\\beta r^2\\,d\\theta\\)','\\(\\int_\\alpha^\\beta r^2\\,d\\theta\\)'], answer: 0 },
      { q: 'For a rose curve \\(r=a\\cos(n\\theta)\\), if \\(n=3\\) there are:', options: ['3 petals','6 petals','9 petals','1 petal'], answer: 0 },
      { q: 'The Cartesian equation of \\(r=2\\sin\\theta\\) is:', options: ['\\(x^2+(y-1)^2=1\\)','\\(x^2+y^2=4\\)','\\((x-1)^2+y^2=1\\)','\\(y=2x\\)'], answer: 0 },
      { q: 'The curve \\(r=a(1-\\cos\\theta)\\) is symmetric about:', options: ['The initial line (\\(x\\)-axis)','The \\(y\\)-axis','The origin','No axis'], answer: 0 },
      { q: 'The area enclosed by the curve \\(r^2=a^2\\cos 2\\theta\\) (one loop) requires limits:', options: ['\\(-\\pi/4\\) to \\(\\pi/4\\)','\\(0\\) to \\(\\pi/2\\)','\\(0\\) to \\(2\\pi\\)','\\(-\\pi/2\\) to \\(\\pi/2\\)'], answer: 0 },
      { q: 'For \\(r=f(\\theta)\\), \\(dx/d\\theta=\\)', options: ['\\(\\frac{dr}{d\\theta}\\cos\\theta - r\\sin\\theta\\)','\\(\\frac{dr}{d\\theta}\\sin\\theta + r\\cos\\theta\\)','\\(-r\\sin\\theta\\)','\\(r\\cos\\theta\\)'], answer: 0 },
      { q: 'The polar curve \\(r=a\\sec\\theta\\) in Cartesian form is:', options: ['\\(x=a\\)','\\(y=a\\)','\\(x^2+y^2=a^2\\)','\\(y=ax\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the total area enclosed by \\(r=2a\\cos\\theta\\).', options: ['\\(\\pi a^2\\)','\\(2\\pi a^2\\)','\\(4\\pi a^2\\)','\\(\\pi a^2/2\\)'], answer: 0 },
      { q: 'Find the total area enclosed by the cardioid \\(r=2(1+\\cos\\theta)\\).', options: ['\\(6\\pi\\)','\\(4\\pi\\)','\\(8\\pi\\)','\\(3\\pi\\)'], answer: 0 },
      { q: 'Find the area of one loop of \\(r=a\\cos(2\\theta)\\).', options: ['\\(\\pi a^2/8\\)','\\(\\pi a^2/4\\)','\\(\\pi a^2/2\\)','\\(\\pi a^2\\)'], answer: 0 },
      { q: 'Convert \\(r=\\frac{4}{1+\\cos\\theta}\\) to Cartesian form.', options: ['\\(y^2=8(x-2)\\) — (parabola)', '\\(x^2+y^2=16\\)','\\(y=4/(x+1)\\)','\\(x^2+y^2=4x\\)'], answer: 0 },
      { q: 'Find the gradient \\(dy/dx\\) at \\(\\theta=\\pi/2\\) for \\(r=a(1+\\cos\\theta)\\).', options: ['0 (horizontal tangent)','\\(\\infty\\) (vertical tangent)','1','\\(-1\\)'], answer: 0 },
      { q: 'The area between the circles \\(r=2\\) and \\(r=4\\sin\\theta\\) for \\(\\pi/6\\leq\\theta\\leq 5\\pi/6\\) requires:', options: ['\\(\\frac{1}{2}\\int(16\\sin^2\\theta-4)\\,d\\theta\\)','\\(\\frac{1}{2}\\int(4-16\\sin^2\\theta)\\,d\\theta\\)','\\(\\int(4\\sin\\theta-2)\\,d\\theta\\)','\\(\\int(4\\sin^2\\theta-1)\\,d\\theta\\)'], answer: 0 },
      { q: 'Find the Cartesian equation of \\(r^2=4\\cos(2\\theta)\\).', options: ['\\(x^2-y^2=2\\) (wait: \\(r^2=4(\\cos^2\\theta-\\sin^2\\theta)\\Rightarrow x^2-y^2=4\\)','\\(x^2+y^2=4\\)','\\(r=2\\)','\\(xy=2\\)'], answer: 0 },
      { q: 'A curve is symmetric about the line \\(\\theta=\\pi/2\\) iff:', options: ['\\(f(\\pi-\\theta)=f(\\theta)\\)','\\(f(-\\theta)=f(\\theta)\\)','\\(f(\\theta+\\pi)=f(\\theta)\\)','\\(f(2\\pi-\\theta)=f(\\theta)\\)'], answer: 0 },
      { q: 'Find the area enclosed between \\(r=1\\) and \\(r=2\\sin\\theta\\) that is inside \\(r=2\\sin\\theta\\) and outside \\(r=1\\).', options: ['\\(\\frac{\\pi}{3}+\\frac{\\sqrt{3}}{2}\\) (approximately, using limits \\(\\pi/6\\) to \\(5\\pi/6\\))','\\(\\pi-\\sqrt{3}\\)','\\(\\pi/2\\)','\\(4\\pi/3\\)'], answer: 0 },
      { q: 'The tangent to \\(r=a\\theta\\) at \\(\\theta=\\pi\\) has gradient:', options: ['\\(\\frac{-\\pi\\cos\\pi-\\sin\\pi}{\\pi(-\\sin\\pi)+\\cos\\pi}=\\frac{\\pi}{-1}=-\\pi\\) (approximately)','\\(\\pi\\)','\\(1\\)','0'], answer: 0 },
      { q: 'For the lemniscate \\(r^2=4\\cos(2\\theta)\\), the maximum value of \\(r\\) is:', options: ['2','4','\\(\\sqrt{4}=2\\)','\\(2\\sqrt{2}\\)'], answer: 0 },
      { q: 'Identify the polar curve \\(r=3+2\\cos\\theta\\): it is a:', options: ['Limaçon without inner loop (\\(a>b\\))','Cardioid','Lemniscate','Circle'], answer: 0 },
      { q: 'Find the area of the region inside \\(r=3\\cos\\theta\\) and outside \\(r=1+\\cos\\theta\\).', options: ['\\(\\pi\\)','\\(2\\pi\\)','\\(4\\pi\\)','\\(\\pi/2\\)'], answer: 0 },
      { q: 'For \\(r=1+2\\cos\\theta\\) (limaçon with inner loop), the inner loop exists where \\(r<0\\), i.e.:', options: ['\\(2\\pi/3<\\theta<4\\pi/3\\)','\\(0<\\theta<\\pi/3\\)','\\(\\pi/2<\\theta<\\pi\\)','Never'], answer: 0 },
      { q: 'To find where two polar curves intersect, you solve \\(r_1(\\theta)=r_2(\\theta)\\) AND check:', options: ['For intersections at the pole and \\(r=0\\) separately','Only the algebraic solutions','All \\(\\theta\\in[0,2\\pi)\\)','Only \\(\\theta\\in[0,\\pi]\\)'], answer: 0 },
      { q: 'The length of the polar curve \\(r=f(\\theta)\\) from \\(\\alpha\\) to \\(\\beta\\) is:', options: ['\\(\\displaystyle\\int_\\alpha^\\beta\\sqrt{r^2+(dr/d\\theta)^2}\\,d\\theta\\)','\\(\\displaystyle\\int_\\alpha^\\beta r\\,d\\theta\\)','\\(\\displaystyle\\int_\\alpha^\\beta\\sqrt{r}\\,d\\theta\\)','\\(\\displaystyle\\int_\\alpha^\\beta r^2\\,d\\theta\\)'], answer: 0 },
      { q: 'Find \\(dy/dx\\) for \\(r=2\\) at any \\(\\theta\\).', options: ['\\(-\\cot\\theta\\)','\\(\\tan\\theta\\)','\\(-\\tan\\theta\\)','\\(\\cot\\theta\\)'], answer: 0 },
      { q: 'The area of the cardioid \\(r=a(1-\\cos\\theta)\\) is:', options: ['\\(3\\pi a^2/2\\)','\\(2\\pi a^2\\)','\\(\\pi a^2\\)','\\(3\\pi a^2\\)'], answer: 0 },
      { q: 'The points where the tangent to \\(r=a(1+\\cos\\theta)\\) is vertical occur when \\(dx/d\\theta=0\\):', options: ['At \\(\\theta=0,\\pi/2,2\\pi/3\\) and related angles','Only at \\(\\theta=\\pi/2\\)','Only at \\(\\theta=0\\)','At \\(\\theta=\\pi\\) only'], answer: 0 },
    ],
    red: [
      { q: 'Find the total area enclosed by the three-petal rose \\(r=a\\cos(3\\theta)\\).', options: ['\\(\\pi a^2/4\\)','\\(\\pi a^2/2\\)','\\(3\\pi a^2/4\\)','\\(\\pi a^2\\)'], answer: 0 },
      { q: 'The limaçon \\(r=1+2\\cos\\theta\\) has an inner loop. Find its area.', options: ['\\(\\pi-3\\sqrt{3}/2\\) (approximately 0.544)','\\(\\pi\\)','\\(2\\pi-3\\sqrt{3}\\)','\\(\\pi/4\\)'], answer: 0 },
      { q: 'Show that \\(r=2\\cos\\theta\\) and \\(r=2\\sin\\theta\\) intersect where \\(\\theta=\\pi/4\\). The intersection point in Cartesian coordinates is:', options: ['\\((1,1)\\)','\\((\\sqrt{2},\\sqrt{2})\\)','\\((0,0)\\)','\\((2,2)\\)'], answer: 0 },
      { q: 'The Cartesian equation of the spiral \\(r=e^\\theta\\) cannot be expressed as a standard function because:', options: ['\\(\\theta=\\ln r\\) and \\(x=r\\cos(\\ln r)\\) — transcendental, cannot simplify','\\(r\\) is unbounded','\\(e^\\theta\\) is not periodic','The curve self-intersects'], answer: 0 },
      { q: 'Find the arc length of \\(r=a\\) (circle) for \\(\\theta\\in[0,2\\pi]\\).', options: ['\\(2\\pi a\\)','\\(\\pi a^2\\)','\\(a\\)','\\(4\\pi a\\)'], answer: 0 },
      { q: 'The area swept between \\(\\theta=0\\) and \\(\\theta=\\pi\\) by the lemniscate \\(r^2=4\\cos 2\\theta\\) is:', options: ['2 (each lobe)','4','\\(\\pi\\)','\\(2\\pi\\)'], answer: 0 },
      { q: 'For the polar curve \\(r=2+\\cos\\theta\\), the minimum value of \\(r\\) is:', options: ['1','0','2','3'], answer: 0 },
      { q: 'A student integrates \\(\\frac{1}{2}\\int_0^{2\\pi}r^2\\,d\\theta\\) for \\(r=a\\cos\\theta\\). They get \\(\\pi a^2/2\\). But the circle has area \\(\\pi(a/2)^2=\\pi a^2/4\\). The error is:', options: ['The curve traces the circle twice (\\(0\\) to \\(2\\pi\\)), so divide by 2','The formula is wrong','\\(r\\) should be squared differently','The limits should be \\([0,\\pi/2]\\)'], answer: 0 },
      { q: 'Find the equation of the tangent to \\(r=2(1+\\cos\\theta)\\) at \\(\\theta=\\pi/2\\).', options: ['\\(y=-x+2\\) (checking: at \\(\\theta=\\pi/2\\), \\(x=0,y=2\\); gradient\\(=-1\\))','\\(y=x+2\\)','\\(y=2\\)','\\(x=0\\)'], answer: 0 },
      { q: 'The area between the two loops of \\(r=1+2\\cos\\theta\\) (outer minus inner) is:', options: ['\\(2\\pi+3\\sqrt{3}/2\\) (approximately 8.83)','\\(3\\pi\\)','\\(\\pi\\)','\\(4\\pi-3\\sqrt{3}\\)'], answer: 0 },
    ],
  },

  '1.8': {
    name: 'Hyperbolic Functions',
    green: [
      { q: '\\(\\sinh x =\\)', options: ['\\(\\frac{e^x-e^{-x}}{2}\\)','\\(\\frac{e^x+e^{-x}}{2}\\)','\\(\\frac{e^x}{2}\\)','\\(e^x-e^{-x}\\)'], answer: 0 },
      { q: '\\(\\cosh x =\\)', options: ['\\(\\frac{e^x+e^{-x}}{2}\\)','\\(\\frac{e^x-e^{-x}}{2}\\)','\\(e^x\\)','\\(\\frac{e^x}{e^{-x}}\\)'], answer: 0 },
      { q: 'The fundamental identity of hyperbolic functions is:', options: ['\\(\\cosh^2 x-\\sinh^2 x=1\\)','\\(\\cosh^2 x+\\sinh^2 x=1\\)','\\(\\sinh^2 x-\\cosh^2 x=1\\)','\\(\\tanh^2 x+\\text{sech}^2 x=2\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\sinh x)=\\)', options: ['\\(\\cosh x\\)','\\(-\\cosh x\\)','\\(\\sinh x\\)','\\(-\\sinh x\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\cosh x)=\\)', options: ['\\(\\sinh x\\)','\\(-\\sinh x\\)','\\(\\cosh x\\)','\\(-\\cosh x\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\tanh x)=\\)', options: ['\\(\\text{sech}^2 x\\)','\\(\\sec^2 x\\)','\\(-\\text{sech}^2 x\\)','\\(\\coth x\\)'], answer: 0 },
      { q: '\\(\\sinh 0=\\)', options: ['0','1','\\(-1\\)','\\(e\\)'], answer: 0 },
      { q: '\\(\\cosh 0=\\)', options: ['1','0','\\(-1\\)','\\(e\\)'], answer: 0 },
      { q: 'The range of \\(\\tanh x\\) is:', options: ['\\((-1,1)\\)','\\(\\mathbb{R}\\)','\\([1,\\infty)\\)','\\((0,\\infty)\\)'], answer: 0 },
      { q: '\\(\\text{arcsinh}\\,x=\\)', options: ['\\(\\ln(x+\\sqrt{x^2+1})\\)','\\(\\ln(x+\\sqrt{x^2-1})\\)','\\(\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\)','\\(\\ln(x-\\sqrt{x^2+1})\\)'], answer: 0 },
      { q: '\\(\\text{arccosh}\\,x=\\)', options: ['\\(\\ln(x+\\sqrt{x^2-1})\\)','\\(\\ln(x+\\sqrt{x^2+1})\\)','\\(\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\)','\\(-\\ln(x-\\sqrt{x^2-1})\\)'], answer: 0 },
      { q: '\\(\\text{arctanh}\\,x=\\)', options: ['\\(\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\)','\\(\\ln(x+\\sqrt{x^2+1})\\)','\\(\\ln(1+x)\\)','\\(\\frac{1}{x}\\)'], answer: 0 },
      { q: '\\(\\int\\sinh x\\,dx=\\)', options: ['\\(\\cosh x+C\\)','\\(-\\cosh x+C\\)','\\(\\sinh x+C\\)','\\(e^x+C\\)'], answer: 0 },
      { q: '\\(\\int\\cosh x\\,dx=\\)', options: ['\\(\\sinh x+C\\)','\\(-\\sinh x+C\\)','\\(\\cosh x+C\\)','\\(\\tanh x+C\\)'], answer: 0 },
      { q: 'The graph of \\(\\cosh x\\) is:', options: ['U-shaped, minimum 1 at \\(x=0\\)','S-shaped','A straight line','Bounded between \\(-1\\) and \\(1\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\text{arcsinh}\\,x)=\\)', options: ['\\(\\frac{1}{\\sqrt{x^2+1}}\\)','\\(\\frac{1}{\\sqrt{x^2-1}}\\)','\\(\\frac{1}{1-x^2}\\)','\\(\\frac{1}{\\sqrt{1-x^2}}\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\text{arccosh}\\,x)=\\)', options: ['\\(\\frac{1}{\\sqrt{x^2-1}}\\)','\\(\\frac{1}{\\sqrt{x^2+1}}\\)','\\(\\frac{1}{1-x^2}\\)','\\(-\\frac{1}{\\sqrt{x^2-1}}\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\text{arctanh}\\,x)=\\)', options: ['\\(\\frac{1}{1-x^2}\\)','\\(\\frac{1}{\\sqrt{x^2+1}}\\)','\\(\\frac{1}{x^2-1}\\)','\\(\\frac{1}{\\sqrt{1-x^2}}\\)'], answer: 0 },
      { q: 'Osborne\'s rule states: replace \\(\\sin^2\\theta\\) with:', options: ['\\(-\\sinh^2 x\\)','\\(\\sinh^2 x\\)','\\(\\cosh^2 x\\)','\\(-\\cosh^2 x\\)'], answer: 0 },
      { q: 'The domain of \\(\\text{arccosh}\\,x\\) is:', options: ['\\(x\\geq 1\\)','All real \\(x\\)','\\(|x|<1\\)','\\(x>0\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Show that \\(\\cosh^2 x-\\sinh^2 x=1\\) using definitions. The calculation gives:', options: ['\\(\\frac{(e^x+e^{-x})^2-(e^x-e^{-x})^2}{4}=\\frac{4}{4}=1\\)','\\(\\cosh^2-\\sinh^2=0\\)','\\(\\frac{e^{2x}-e^{-2x}}{4}=1\\)','\\(e^{2x}\\cdot e^{-2x}=1\\)'], answer: 0 },
      { q: 'Solve \\(5\\cosh x-3\\sinh x=7\\) for \\(x\\).', options: ['\\(x=\\ln\\frac{7+\\sqrt{33}}{2}\\) or \\(x=\\ln\\frac{7-\\sqrt{33}}{2}\\)','\\(x=0\\)','\\(x=\\ln 7\\)','\\(x=\\pm1\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\sinh^2 x\\,dx\\).', options: ['\\(\\frac{\\sinh 2x}{4}-\\frac{x}{2}+C\\)','\\(\\frac{\\cosh^2 x}{2}+C\\)','\\(\\sinh x\\cosh x+C\\)','\\(\\frac{\\sinh 2x}{2}+C\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int_0^1\\cosh x\\,dx\\).', options: ['\\(\\sinh 1\\)','\\(\\cosh 1-1\\)','\\(\\cosh 1\\)','1'], answer: 0 },
      { q: 'Using Osborne\'s rule, what is the hyperbolic form of \\(\\cos(2A)=1-2\\sin^2 A\\)?', options: ['\\(\\cosh(2A)=1+2\\sinh^2 A\\)','\\(\\cosh(2A)=1-2\\sinh^2 A\\)','\\(\\cosh(2A)=2\\cosh^2 A-1\\)','\\(\\sinh(2A)=1+2\\cosh^2 A\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{1}{\\sqrt{x^2+4}}\\,dx\\).', options: ['\\(\\text{arcsinh}(x/2)+C\\)','\\(\\text{arccosh}(x/2)+C\\)','\\(\\frac{1}{2}\\arctan(x/2)+C\\)','\\(\\ln(x+\\sqrt{x^2+4})+C\\) — same as arcsinh'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{1}{\\sqrt{x^2-9}}\\,dx\\) for \\(x>3\\).', options: ['\\(\\text{arccosh}(x/3)+C\\)','\\(\\text{arcsinh}(x/3)+C\\)','\\(\\frac{1}{3}\\arctan(x/3)+C\\)','\\(\\ln(x-3)+C\\)'], answer: 0 },
      { q: 'Express \\(\\sinh(2x)\\) in terms of \\(\\sinh x\\) and \\(\\cosh x\\).', options: ['\\(2\\sinh x\\cosh x\\)','\\(\\cosh^2 x-\\sinh^2 x\\)','\\(2\\sinh^2 x+1\\)','\\(\\sinh^2 x+\\cosh^2 x\\)'], answer: 0 },
      { q: 'Solve \\(\\cosh x = 2\\).', options: ['\\(x=\\ln(2+\\sqrt{3})\\) or \\(x=-\\ln(2+\\sqrt{3})\\)','\\(x=\\text{arccosh}\\,2>0\\) only','\\(x=\\pm\\ln 2\\)','\\(x=2\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{1}{1-x^2}\\,dx\\) for \\(|x|<1\\).', options: ['\\(\\text{arctanh}\\,x+C=\\frac{1}{2}\\ln\\frac{1+x}{1-x}+C\\)','\\(\\arctan x+C\\)','\\(\\frac{1}{2}\\ln|1-x^2|+C\\)','\\(-\\text{arctanh}\\,x+C\\)'], answer: 0 },
      { q: 'Express \\(\\cosh(2x)\\) using \\(\\cosh x\\) only.', options: ['\\(2\\cosh^2 x-1\\)','\\(\\cosh^2 x+\\sinh^2 x\\)','\\(1+2\\sinh^2 x\\)','\\(2\\cosh x\\sinh x\\)'], answer: 0 },
      { q: 'Find the derivative of \\(\\sinh(3x)\\).', options: ['\\(3\\cosh(3x)\\)','\\(\\cosh(3x)\\)','\\(3\\sinh(3x)\\)','\\(-3\\cosh(3x)\\)'], answer: 0 },
      { q: 'Integrate \\(\\displaystyle\\int x\\cosh x\\,dx\\) by parts.', options: ['\\(x\\sinh x-\\cosh x+C\\)','\\(x\\cosh x-\\sinh x+C\\)','\\(x\\cosh x+\\sinh x+C\\)','\\(\\sinh x-x\\cosh x+C\\)'], answer: 0 },
      { q: 'Using the definition, show \\(\\tanh x\\to 1\\) as \\(x\\to\\infty\\). This is because:', options: ['\\(e^{-x}\\to 0\\) so \\(\\tanh x=\\frac{e^x-e^{-x}}{e^x+e^{-x}}\\to\\frac{1-0}{1+0}=1\\)','\\(\\sinh x\\to\\infty\\)','\\(\\cosh x\\to 0\\)','\\(e^x\\to 1\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\cosh^2 x\\,dx\\).', options: ['\\(\\frac{\\sinh 2x}{4}+\\frac{x}{2}+C\\)','\\(\\frac{\\cosh^2 x}{2}+C\\)','\\(\\frac{\\sinh 2x}{2}+C\\)','\\(\\frac{x\\cosh^2 x}{2}+C\\)'], answer: 0 },
      { q: 'Using Osborne\'s rule, convert \\(\\cos^2 A + \\sin^2 A=1\\):', options: ['\\(\\cosh^2 A - \\sinh^2 A = 1\\)','\\(\\cosh^2 A + \\sinh^2 A = 1\\)','\\(\\sinh^2 A - \\cosh^2 A = 1\\)','\\(\\cosh^2 A + \\sinh^2 A = 2\\)'], answer: 0 },
      { q: 'Prove \\(\\text{arctanh}\\,x=\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\). The key step is:', options: ['Setting \\(y=\\tanh x\\) then \\(e^{2x}=\\frac{1+y}{1-y}\\)','Using integration','Completing the square','The chain rule'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\tanh x\\,dx\\).', options: ['\\(\\ln(\\cosh x)+C\\)','\\(\\ln(\\sinh x)+C\\)','\\(\\text{sech}^2 x+C\\)','\\(-\\ln(\\cosh x)+C\\)'], answer: 0 },
      { q: 'The curve \\(y=\\cosh x\\) is known as a:', options: ['Catenary','Parabola','Cycloid','Lemniscate'], answer: 0 },
    ],
    red: [
      { q: 'Derive \\(\\text{arcsinh}\\,x=\\ln(x+\\sqrt{x^2+1})\\) from first principles.', options: ['Set \\(\\sinh y=x\\), form quadratic in \\(e^y\\), solve taking positive root','Use the chain rule on \\(\\sinh^{-1}\\)','Integrate \\(1/\\sqrt{x^2+1}\\)','Use Osborne\'s rule'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\sqrt{x^2+1}\\,dx\\) using the substitution \\(x=\\sinh t\\).', options: ['\\(\\frac{x\\sqrt{x^2+1}}{2}+\\frac{1}{2}\\text{arcsinh}\\,x+C\\)','\\(\\frac{x^2}{2}\\sqrt{x^2+1}+C\\)','\\(\\cosh x+C\\)','\\(\\frac{2}{3}(x^2+1)^{3/2}+C\\)'], answer: 0 },
      { q: 'Prove that \\(\\frac{d}{dx}(\\text{arccosh}\\,x)=\\frac{1}{\\sqrt{x^2-1}}\\) using implicit differentiation.', options: ['Set \\(y=\\text{arccosh}\\,x\\), so \\(\\cosh y=x\\), differentiate: \\(\\sinh y \\frac{dy}{dx}=1\\), use \\(\\sinh y=\\sqrt{\\cosh^2 y-1}=\\sqrt{x^2-1}\\)','Use Osborne\'s rule from \\(\\arccos\\)','Use the quotient rule','Use the product rule on \\(e^y\\)'], answer: 0 },
      { q: 'A catenary has equation \\(y=a\\cosh(x/a)\\). Its arc length from \\(x=-a\\) to \\(x=a\\) is:', options: ['\\(2a\\sinh 1\\)','\\(2a\\)','\\(2a\\cosh 1\\)','\\(a\\sinh 2\\)'], answer: 0 },
      { q: 'Solve \\(\\sinh^2 x-5\\cosh x+5=0\\).', options: ['\\(x=\\ln(2+\\sqrt{3})\\) or \\(x=0\\) (check with \\(\\cosh^2-\\sinh^2=1\\))','\\(x=\\ln 2\\) only','\\(x=0\\) only','No real solutions'], answer: 0 },
      { q: 'The integral \\(\\displaystyle\\int_1^2\\frac{1}{\\sqrt{x^2-1}}\\,dx\\) equals:', options: ['\\(\\text{arccosh}\\,2\\)','\\(\\ln(2+\\sqrt{3})\\)','\\(\\pi/4\\)','\\(\\arctan\\sqrt{3}\\)'], answer: 0 },
      { q: 'Express \\(\\sinh^3 x\\) in terms of multiple arguments using \\(3\\sinh x=\\sinh(3x)-4\\sinh^3 x\\) ... wait, the identity gives \\(\\sinh(3x)=3\\sinh x+4\\sinh^3 x\\). So \\(\\sinh^3 x=\\)', options: ['\\(\\frac{\\sinh 3x-3\\sinh x}{4}\\)','\\(\\frac{\\sinh 3x+3\\sinh x}{4}\\)','\\(\\frac{3\\sinh x-\\sinh 3x}{4}\\)','\\(\\sinh 3x/4\\)'], answer: 0 },
      { q: 'Show \\(1-\\tanh^2 x=\\text{sech}^2 x\\). This follows from:', options: ['Dividing \\(\\cosh^2 x-\\sinh^2 x=1\\) by \\(\\cosh^2 x\\)','The definition of \\(\\tanh\\)','Adding the squares','Osborne\'s rule'], answer: 0 },
      { q: 'The relationship between \\(\\text{arctanh}\\,x\\) and partial fractions gives \\(\\displaystyle\\int\\frac{1}{a^2-x^2}\\,dx=\\)', options: ['\\(\\frac{1}{a}\\text{arctanh}\\frac{x}{a}+C=\\frac{1}{2a}\\ln\\left|\\frac{a+x}{a-x}\\right|+C\\)','\\(\\frac{1}{a}\\arctan\\frac{x}{a}+C\\)','\\(\\frac{1}{a^2}\\ln|a^2-x^2|+C\\)','\\(\\text{arccosh}(x/a)+C\\)'], answer: 0 },
      { q: 'The surface area of a catenary \\(y=\\cosh x\\) rotated about the \\(x\\)-axis from \\(-a\\) to \\(a\\) requires:', options: ['\\(2\\pi\\int_{-a}^{a}\\cosh^2 x\\,dx\\) (since \\(\\sqrt{1+\\sinh^2 x}=\\cosh x\\))','\\(\\pi\\int_{-a}^a\\cosh^2 x\\,dx\\)','\\(2\\pi\\int_{-a}^a x\\,dx\\)','\\(4\\pi a^2\\)'], answer: 0 },
    ],
  },

  '1.9': {
    name: 'Differential Equations',
    green: [
      { q: 'A separable ODE has the form:', options: ['\\(dy/dx=f(x)g(y)\\)','\\(dy/dx+P(x)y=Q(x)\\)','\\(ay\\'\\'+by\\'+cy=0\\)','\\(y=f(x)\\)'], answer: 0 },
      { q: 'The integrating factor for \\(dy/dx+P(x)y=Q(x)\\) is:', options: ['\\(e^{\\int P\\,dx}\\)','\\(e^{P}\\)','\\(P(x)\\)','\\(\\int P\\,dx\\)'], answer: 0 },
      { q: 'The auxiliary equation for \\(ay\\'\\'+by\\'+cy=0\\) is:', options: ['\\(am^2+bm+c=0\\)','\\(a\\lambda^2+b\\lambda+c=0\\)','\\(am+b=0\\)','\\(m^2=ac/b^2\\)'], answer: 0 },
      { q: 'If the auxiliary equation has a repeated root \\(m\\), the complementary function is:', options: ['\\((A+Bx)e^{mx}\\)','\\(Ae^{mx}+Be^{mx}\\)','\\(e^{mx}(A\\cos x+B\\sin x)\\)','\\(Ae^{mx}\\)'], answer: 0 },
      { q: 'If the auxiliary equation has complex roots \\(\\alpha\\pm\\beta i\\), the CF is:', options: ['\\(e^{\\alpha x}(A\\cos\\beta x+B\\sin\\beta x)\\)','\\(e^{\\alpha x}+e^{\\beta x}\\)','\\(A\\cos\\alpha x+B\\sin\\beta x\\)','\\(e^{i\\alpha x}(A+B)\\)'], answer: 0 },
      { q: 'The general solution of a non-homogeneous ODE is:', options: ['\\(y_{CF}+y_{PI}\\)','\\(y_{CF}\\cdot y_{PI}\\)','\\(y_{CF}-y_{PI}\\)','\\(y_{PI}\\) only'], answer: 0 },
      { q: 'For \\(f(x)=ke^{px}\\) (not in CF), the trial particular integral is:', options: ['\\(\\lambda e^{px}\\)','\\(\\lambda xe^{px}\\)','\\(\\lambda x^2 e^{px}\\)','\\(\\lambda+\\mu x\\)'], answer: 0 },
      { q: 'For \\(f(x)=k\\sin(px)\\), the trial PI is:', options: ['\\(\\lambda\\cos(px)+\\mu\\sin(px)\\)','\\(\\lambda\\sin(px)\\)','\\(\\lambda\\cos(px)\\)','\\(\\lambda e^{px}\\)'], answer: 0 },
      { q: 'Solve \\(dy/dx=y\\). The general solution is:', options: ['\\(y=Ae^x\\)','\\(y=A\\ln x\\)','\\(y=Ax\\)','\\(y=e^{Ax}\\)'], answer: 0 },
      { q: 'Solve \\(dy/dx=2x\\). The general solution is:', options: ['\\(y=x^2+C\\)','\\(y=2+C\\)','\\(y=2x^2+C\\)','\\(y=x^2\\)'], answer: 0 },
      { q: 'If the auxiliary equation has roots \\(m=2\\) and \\(m=-3\\), the CF is:', options: ['\\(Ae^{2x}+Be^{-3x}\\)','\\(e^{2x}(A\\cos3x+B\\sin3x)\\)','\\((A+Bx)e^{-x}\\)','\\(Ae^{-x}+Be^{-6x}\\)'], answer: 0 },
      { q: 'The particular integral for \\(y\\'\\'+y=3\\) is:', options: ['\\(y=3\\)','\\(y=3x\\)','\\(y=3e^x\\)','\\(y=0\\)'], answer: 0 },
      { q: 'Multiplying a first-order linear ODE by \\(\\mu\\) converts the LHS to:', options: ['\\(\\frac{d}{dx}(\\mu y)\\)','\\(\\mu^2 y\\)','\\(\\mu y+\\mu P y\\)','\\(d\\mu/dx\\)'], answer: 0 },
      { q: 'The equation \\(y\\'\\'-3y\\'+2y=0\\) has auxiliary equation with roots:', options: ['\\(m=1,2\\)','\\(m=3,2\\)','\\(m=-1,-2\\)','\\(m=1,-1\\)'], answer: 0 },
      { q: 'For initial conditions to find a particular solution, you need:', options: ['Values of \\(y\\) (and possibly \\(y\'\\)) at specific points','The complementary function only','The particular integral only','The auxiliary equation roots'], answer: 0 },
      { q: 'What is the degree of an ODE?', options: ['The power of the highest derivative when the equation is written in polynomial form','The order of the highest derivative','The number of terms','The number of solutions'], answer: 0 },
      { q: 'A first-order ODE is separable if you can write it as:', options: ['Separate terms in \\(x\\) on one side, terms in \\(y\\) on the other','\\(y=f(x)+g(y)\\)','\\(dy/dx=f(x)+g(y)\\)','\\(y+y\'=f(x)\\)'], answer: 0 },
      { q: 'For the trial PI to fail (and need multiplying by \\(x\\)), you need:', options: ['The trial function is part of the complementary function','The coefficient is zero','The equation is non-linear','The RHS is a polynomial'], answer: 0 },
      { q: 'The order of a differential equation is determined by:', options: ['The highest derivative present','The degree of \\(y\\)','The number of constants in the general solution','The number of terms'], answer: 0 },
      { q: 'Coupled DEs \\(\\dot{x}=ax+by\\), \\(\\dot{y}=cx+dy\\) are reduced to a single ODE by:', options: ['Differentiating one equation and substituting the other to eliminate one variable','Adding the two equations','Subtracting the two equations','Using matrices directly'], answer: 0 },
    ],
    amber: [
      { q: 'Solve \\(dy/dx=xy\\) with \\(y(0)=1\\).', options: ['\\(y=e^{x^2/2}\\)','\\(y=e^x\\)','\\(y=xe^x\\)','\\(y=1+x^2/2\\)'], answer: 0 },
      { q: 'Find the general solution of \\(dy/dx+y/x=x^2\\).', options: ['\\(y=x^3/4+C/x\\)','\\(y=x^3/3+Cx\\)','\\(y=x^3/4+C\\)','\\(y=x^2+C/x\\)'], answer: 0 },
      { q: 'Find the general solution of \\(y\\'\\'-5y\\'+6y=0\\).', options: ['\\(y=Ae^{2x}+Be^{3x}\\)','\\(y=(A+Bx)e^{3x}\\)','\\(y=e^{5x/2}(A\\cos x+B\\sin x)\\)','\\(y=Ae^{-2x}+Be^{-3x}\\)'], answer: 0 },
      { q: 'Find the particular integral for \\(y\\'\\'-3y\\'+2y=4e^{3x}\\).', options: ['\\(y_{PI}=2e^{3x}\\)','\\(y_{PI}=4e^{3x}\\)','\\(y_{PI}=2xe^{3x}\\)','\\(y_{PI}=e^{3x}/2\\)'], answer: 0 },
      { q: 'Solve \\(y\\'\\'+4y=8\\) with \\(y(0)=3\\), \\(y\'(0)=0\\).', options: ['\\(y=\\cos 2x+2\\)','\\(y=3\\cos 2x\\)','\\(y=2+\\cos 2x+\\sin 2x\\)','\\(y=3e^{-4x}+2\\)'], answer: 0 },
      { q: 'Find the integrating factor for \\(dy/dx+2y/x=x^2\\).', options: ['\\(x^2\\)','\\(e^{2x}\\)','\\(x\\)','\\(e^{2/x}\\)'], answer: 0 },
      { q: 'For \\(y\\'\\'-4y\\'+4y=e^{2x}\\), the trial PI is:', options: ['\\(\\lambda x^2 e^{2x}\\)','\\(\\lambda e^{2x}\\)','\\(\\lambda x e^{2x}\\)','\\(\\lambda x^3 e^{2x}\\)'], answer: 0 },
      { q: 'Solve \\(y\\'\\'-y=\\sin x\\) for the particular integral.', options: ['\\(y_{PI}=-\\frac{1}{2}\\sin x\\)','\\(y_{PI}=\\frac{1}{2}\\sin x\\)','\\(y_{PI}=-\\sin x\\)','\\(y_{PI}=\\cos x\\)'], answer: 0 },
      { q: 'The equation \\(y\\'\\'+9y=\\cos 3x\\) — the trial PI \\(\\lambda\\cos3x+\\mu\\sin3x\\) fails because:', options: ['\\(\\cos 3x\\) is part of the CF (roots \\(\\pm3i\\))','The equation is non-linear','The coefficient of \\(y\\'\\'' is 1','\\(\\mu=0\\)'], answer: 0 },
      { q: 'Solve \\(\\frac{dy}{dx}+y\\cot x=\\cos x\\). The integrating factor is:', options: ['\\(\\sin x\\)','\\(\\cot x\\)','\\(\\cos x\\)','\\(e^x\\)'], answer: 0 },
      { q: 'Find the general solution of \\(y\\'\\'+2y\\'+5y=0\\).', options: ['\\(y=e^{-x}(A\\cos2x+B\\sin2x)\\)','\\(y=Ae^{-2x}+Be^{-5x}\\)','\\(y=(A+Bx)e^{-x}\\)','\\(y=e^x(A\\cos2x+B\\sin2x)\\)'], answer: 0 },
      { q: 'Find the particular integral for \\(y\\'\\'+y=x^2\\).', options: ['\\(x^2-2\\)','\\(x^2\\)','\\(x^2+2x\\)','\\(x^2-2x+2\\)'], answer: 0 },
      { q: 'Solve the coupled system \\(\\dot{x}=y\\), \\(\\dot{y}=-x\\). The solution has:', options: ['\\(x=A\\cos t+B\\sin t\\), \\(y=-A\\sin t+B\\cos t\\)','\\(x=Ae^t\\), \\(y=Be^t\\)','\\(x=x_0e^{-t}\\), \\(y=y_0e^{-t}\\)','\\(x=A\\cosh t\\), \\(y=B\\sinh t\\)'], answer: 0 },
      { q: 'The general solution of \\(y\\'\\'-4y=0\\) is:', options: ['\\(Ae^{2x}+Be^{-2x}\\)','\\(e^{2x}(A+B)\\)','\\(A\\cos2x+B\\sin2x\\)','\\((A+Bx)e^{2x}\\)'], answer: 0 },
      { q: 'Use separation of variables to solve \\(\\frac{dy}{dx}=\\frac{x}{y}\\). The general solution is:', options: ['\\(y^2=x^2+C\\)','\\(y=x+C\\)','\\(y^2-x^2=C\\)','\\(y=\\frac{x^2}{2}+C\\)'], answer: 0 },
      { q: 'To solve \\(y\\'\\'+y=e^x\\), the PI trial is:', options: ['\\(\\lambda e^x\\) (since \\(e^x\\) is not in CF)','\\(\\lambda x e^x\\)','\\(\\lambda x^2 e^x\\)','\\(\\lambda\\)'], answer: 0 },
      { q: 'Apply \\(y(0)=1\\), \\(y\'(0)=2\\) to \\(y=Ae^{2x}+Be^{3x}\\). Then:', options: ['\\(A+B=1\\), \\(2A+3B=2\\), so \\(A=1,B=0\\)','\\(A=2,B=-1\\)','\\(A=0,B=1\\)','\\(A=B=1\\)'], answer: 0 },
      { q: 'For the equation \\(y\\frac{dy}{dx}=x\\), the general solution (separating variables) is:', options: ['\\(y^2=x^2+C\\)','\\(y=x+C\\)','\\(y=\\sqrt{x}+C\\)','\\(y^2=2x^2+C\\)'], answer: 0 },
      { q: 'For the non-homogeneous equation \\(y\\'\\'-y=x\\), the PI is:', options: ['\\(-x\\)','\\(x\\)','\\(-x-1\\) — wait, try \\(y=ax+b\\): \\(-a-(ax+b)=x\\), so \\(-a=1,\\ -b-0=0\\)','\\(x+1\\)'], answer: 2 },
      { q: 'The coupled system \\(\\dot{x}=2x+y\\), \\(\\dot{y}=x+2y\\) has eigenvalues (of the matrix):', options: ['1 and 3','2 and 2','0 and 4','\\(-1\\) and 3'], answer: 0 },
    ],
    red: [
      { q: 'Solve \\(\\frac{dy}{dx}=\\frac{y^2-1}{x}\\) by separating variables.', options: ['\\(\\frac{y-1}{y+1}=Ax^2\\)','\\(y=\\frac{1+Ax^2}{1-Ax^2}\\)','\\(y^2=1+Cx^2\\)','\\(y=x+C\\)'], answer: 1 },
      { q: 'Find the general solution of \\(y\\'\\'-2y\\'+y=e^x\\) (note \\(e^x\\) is in the CF twice).', options: ['\\(y=(A+Bx)e^x+\\frac{x^2}{2}e^x\\)','\\(y=(A+Bx)e^x+xe^x\\)','\\(y=(A+Bx)e^x+e^x\\)','\\(y=Ae^x+\\frac{x^2}{2}e^x\\)'], answer: 0 },
      { q: 'For the Bernoulli equation \\(\\frac{dy}{dx}+y=y^3\\), the substitution \\(v=y^{-2}\\) gives:', options: ['\\(\\frac{dv}{dx}-2v=-2\\) (a linear ODE)','\\(\\frac{dv}{dx}+2v=2\\)','\\(\\frac{dv}{dx}=v^3\\)','\\(\\frac{dv}{dx}+v=1\\)'], answer: 0 },
      { q: 'For the system \\(\\dot{x}=4x+y\\), \\(\\dot{y}=2x+3y\\), eliminating \\(y\\) gives:', options: ['\\(\\ddot{x}-7\\dot{x}+10x=0\\)','\\(\\ddot{x}-4\\dot{x}+3x=0\\)','\\(\\ddot{x}-7x=0\\)','\\(\\ddot{x}+7\\dot{x}-10x=0\\)'], answer: 0 },
      { q: 'The particular integral of \\(y\\'\\'+y=\\cos x\\) requires which trial?', options: ['\\(x(\\lambda\\cos x+\\mu\\sin x)\\) (since \\(\\pm i\\) are CF roots)','\\(\\lambda\\cos x+\\mu\\sin x\\)','\\(x^2\\lambda\\cos x\\)','\\(\\lambda e^{ix}\\)'], answer: 0 },
      { q: 'Solve \\(y\\'\\'-2y\\'+2y=e^x\\sin x\\). The CF is \\(e^x(A\\cos x+B\\sin x)\\); the PI trial is:', options: ['\\(xe^x(\\lambda\\cos x+\\mu\\sin x)\\) (since \\(e^x(\\cos x+i\\sin x)\\) is in CF)','\\(e^x(\\lambda\\cos x+\\mu\\sin x)\\)','\\(\\lambda e^x\\sin x\\)','\\(\\lambda e^{2x}\\)'], answer: 0 },
      { q: 'For large \\(t\\), the solution \\(y=Ae^{-2t}+Be^{3t}\\) behaves like:', options: ['\\(Be^{3t}\\) (dominates as \\(e^{3t}\\to\\infty\\))','\\(Ae^{-2t}\\)','\\(A+B\\)','0'], answer: 0 },
      { q: 'A second-order ODE requires \\(\\square\\) arbitrary constants in its general solution:', options: ['2','1','0','3'], answer: 0 },
      { q: 'To test whether two solutions \\(y_1\\) and \\(y_2\\) are linearly independent, compute the Wronskian \\(W=y_1y_2\\'-y_2y_1\'\\). For \\(y_1=e^{2x}\\), \\(y_2=e^{3x}\\): \\(W=\\)', options: ['\\(e^{5x}\\neq0\\)','0','\\(5e^{5x}\\)','\\(6e^{5x}\\)'], answer: 0 },
      { q: 'The equation \\(x^2y\\'\\'+xy\\'-y=0\\) is a Cauchy-Euler equation. The substitution \\(x=e^t\\) converts it to:', options: ['A second-order ODE with constant coefficients','A separable equation','An exact equation','A Bernoulli equation'], answer: 0 },
      { q: 'For \\(y\\'\\'+4y=\\delta(t)\\) (impulse input), the response involves:', options: ['A sine wave of amplitude \\(1/2\\) starting at \\(t=0\\): \\(y=\\frac{1}{2}\\sin 2t\\) for \\(t>0\\)','\\(y=e^{-4t}\\)','A constant response','A growing exponential'], answer: 0 },
    ],
  },

};
