/*
 * AQA A-Level Further Mathematics — MCQ Question Bank
 * 50 questions per topic: 20 green (recall/procedure), 20 amber (application), 10 red (analysis/proof)
 * Diagnostic picks 2 green + 2 amber + 1 red = 5 questions at random (always one written).
 * answer: 0-based index of correct option in the options array.
 */

const FM_AQA_MCQ = {

  '1.1': {
    name: 'Complex Numbers',
    green: [
      { q: 'What is \\(i^2\\)?', options: ['\\(-1\\)','\\(1\\)','\\(i\\)','\\(-i\\)'], answer: 0 },
      { q: 'What is \\(|3+4i|\\)?', options: ['25','5','7','\\(\\sqrt{7}\\)'], answer: 1 },
      { q: 'What is the conjugate of \\(2-5i\\)?', options: ['\\(-2-5i\\)','\\(5-2i\\)','\\(2+5i\\)','\\(-2+5i\\)'], answer: 2 },
      { q: 'What is \\((2+3i)+(4-i)\\)?', options: ['\\(6+4i\\)','\\(6-2i\\)','\\(8+2i\\)','\\(6+2i\\)'], answer: 3 },
      { q: 'What is \\(i^3\\)?', options: ['\\(-i\\)','\\(i\\)','\\(-1\\)','1'], answer: 0 },
      { q: 'What is the real part of \\(7-3i\\)?', options: ['3','7','\\(-3\\)','\\(\\sqrt{58}\\)'], answer: 1 },
      { q: 'What is the imaginary part of \\(4+9i\\)?', options: ['\\(9i\\)','\\(\\sqrt{97}\\)','9','4'], answer: 2 },
      { q: "What is \\((2+i)(2-i)\\)?", options: ["3","4","\\(3+4i\\)","5"], answer: 3 },
      { q: 'What is \\(i^4\\)?', options: ['1','\\(-1\\)','\\(i\\)','\\(-i\\)'], answer: 0 },
      { q: 'If \\(z = a+bi\\), then \\(z + z^*\\) equals:', options: ['0','\\(2a\\)','\\(2bi\\)','\\(2b\\)'], answer: 1 },
      { q: 'If \\(z = a+bi\\), then \\(z\\cdot z^*\\) equals:', options: ['\\(2ab\\)','\\((a+b)^2\\)','\\(a^2+b^2\\)','\\(a^2-b^2\\)'], answer: 2 },
      { q: 'What is the argument of \\(1+i\\) in radians?', options: ['\\(\\pi/2\\)','\\(\\pi/3\\)','\\(3\\pi/4\\)','\\(\\pi/4\\)'], answer: 3 },
      { q: 'What is \\(|{-3+4i}|\\)?', options: ['5','1','7','\\(\\sqrt{7}\\)'], answer: 0 },
      { q: 'What is \\(\\arg(-1)\\)?', options: ['\\(\\pi/2\\)','\\(\\pi\\)','0','\\(-\\pi/2\\)'], answer: 1 },
      { q: 'The principal argument satisfies:', options: ['\\(0 \\leq \\arg(z) \\leq \\pi\\)','\\(-\\pi \\leq \\arg(z) \\leq \\pi\\)','\\(-\\pi < \\arg(z) \\leq \\pi\\)','\\(0 \\leq \\arg(z) < 2\\pi\\)'], answer: 2 },
      { q: 'What is \\(\\arg(i)\\)?', options: ['\\(\\pi\\)','0','\\(-\\pi/2\\)','\\(\\pi/2\\)'], answer: 3 },
      { q: 'Which of these has modulus 1?', options: ['\\(\\cos\\theta+i\\sin\\theta\\)','\\(1+i\\)','\\(2i\\)','\\(\\frac{1}{2}+i\\)'], answer: 0 },
      { q: 'What is \\(\\frac{1}{i}\\)?', options: ['\\(-1\\)','\\(-i\\)','\\(i\\)','1'], answer: 1 },
      { q: 'Euler\'s formula states:', options: ['\\(e^{i\\theta}=i(\\cos\\theta+\\sin\\theta)\\)','\\(e^{i\\theta}=\\cosh\\theta+i\\sinh\\theta\\)','\\(e^{i\\theta}=\\cos\\theta+i\\sin\\theta\\)','\\(e^{i\\theta}=\\cos\\theta-i\\sin\\theta\\)'], answer: 2 },
      { q: 'What are the square roots of \\(-1\\)?', options: ['\\(1\\) and \\(-1\\)','\\(i\\) only','\\(\\pm\\sqrt{i}\\)','\\(i\\) and \\(-i\\)'], answer: 3 },
    ],
    amber: [
      { q: 'Simplify \\(\\dfrac{3+5i}{1+2i}\\).', options: ['\\(\\dfrac{13}{5}-\\dfrac{1}{5}i\\)','\\(\\dfrac{13}{5}+\\dfrac{1}{5}i\\)','\\(\\dfrac{3-5i}{1-4}\\)','\\(3-5i\\)'], answer: 0 },
      { q: 'Given \\(z=1+\\sqrt{3}i\\), what is \\(\\arg(z)\\)?', options: ['\\(\\pi/4\\)','\\(\\pi/3\\)','\\(\\pi/6\\)','\\(2\\pi/3\\)'], answer: 1 },
      { q: 'Solve \\(z^2+4z+13=0\\).', options: ['\\(-4\\pm 3i\\)','\\(-2\\pm 13i\\)','\\(-2\\pm 3i\\)','\\(2\\pm 3i\\)'], answer: 2 },
      { q: 'Write \\(2(\\cos(\\pi/6)+i\\sin(\\pi/6))\\) in \\(a+bi\\) form.', options: ['\\(1+\\sqrt{3}i\\)','\\(\\sqrt{3}+\\sqrt{3}i\\)','\\(2+2i\\)','\\(\\sqrt{3}+i\\)'], answer: 3 },
      { q: 'Find \\(|(2+3i)(1-2i)|\\).', options: ['\\(\\sqrt{65}\\)','\\(\\sqrt{13}\\)','\\(\\sqrt{5}\\)','\\(5\\sqrt{13}\\)'], answer: 0 },
      { q: 'By de Moivre\'s theorem, \\((\\cos\\theta+i\\sin\\theta)^5\\) equals:', options: ['\\(\\cos5\\theta-i\\sin5\\theta\\)','\\(\\cos5\\theta+i\\sin5\\theta\\)','\\(5\\cos\\theta+5i\\sin\\theta\\)','\\(\\cos^5\\theta+i\\sin^5\\theta\\)'], answer: 1 },
      { q: 'If one root of a real-coefficient equation is \\(3+2i\\), another root must be:', options: ['\\(-3-2i\\)','\\(2+3i\\)','\\(3-2i\\)','\\(-3+2i\\)'], answer: 2 },
      { q: 'The cube roots of unity include which pair of complex roots?', options: ['\\(\\pm i\\)','\\(\\frac{1}{2}\\pm\\frac{\\sqrt{3}}{2}i\\)','\\(-1\\pm i\\)','\\(-\\frac{1}{2}\\pm\\frac{\\sqrt{3}}{2}i\\)'], answer: 3 },
      { q: 'Express \\(-1+i\\) in modulus-argument form.', options: ['\\(\\sqrt{2}(\\cos\\frac{3\\pi}{4}+i\\sin\\frac{3\\pi}{4})\\)','\\(\\sqrt{2}(\\cos\\frac{\\pi}{4}+i\\sin\\frac{\\pi}{4})\\)','\\(2(\\cos\\frac{3\\pi}{4}+i\\sin\\frac{3\\pi}{4})\\)','\\(\\sqrt{2}(\\cos(-\\frac{\\pi}{4})+i\\sin(-\\frac{\\pi}{4}))\\)'], answer: 0 },
      { q: 'What is \\(\\arg(z_1 z_2)\\) in terms of \\(\\arg z_1\\) and \\(\\arg z_2\\)?', options: ['\\(\\arg z_1/\\arg z_2\\)','\\(\\arg z_1+\\arg z_2\\)','\\(\\arg z_1 \\cdot \\arg z_2\\)','\\(\\arg z_1-\\arg z_2\\)'], answer: 1 },
      { q: 'If \\(z = r e^{i\\theta}\\), what is \\(z^4\\)?', options: ['\\(r^4 e^{i\\theta/4}\\)','\\(4r^4 e^{i\\theta}\\)','\\(r^4 e^{4i\\theta}\\)','\\(4r e^{4i\\theta}\\)'], answer: 2 },
      { q: 'How many distinct roots does \\(z^5 = 1\\) have in \\(\\mathbb{C}\\)?', options: ['1','2','10','5'], answer: 3 },
      { q: 'The locus \\(|z-2|=3\\) is:', options: ['A circle centre \\((2,0)\\) radius 3','A circle centre \\((3,0)\\) radius 2','A perpendicular bisector','A half-line'], answer: 0 },
      { q: 'What is the Cartesian equation of \\(|z-i|=|z+i|\\)?', options: ['\\(x^2+y^2=1\\)','\\(y=0\\) (the real axis)','\\(x=0\\)','\\(y=x\\)'], answer: 1 },
      { q: 'The locus \\(\\arg(z-1)=\\pi/4\\) is:', options: ['A circle','A perpendicular bisector','A half-line from \\((1,0)\\) at angle \\(\\pi/4\\)','A full line through \\((1,0)\\)'], answer: 2 },
      { q: 'Use de Moivre to find \\(\\cos 3\\theta\\) in terms of \\(\\cos\\theta\\). The answer is:', options: ['\\(3\\cos\\theta-4\\cos^3\\theta\\)','\\(\\cos^3\\theta-3\\cos\\theta\\)','\\(4\\cos^3\\theta+3\\cos\\theta\\)','\\(4\\cos^3\\theta-3\\cos\\theta\\)'], answer: 3 },
      { q: 'The roots of \\(z^n=1\\) lie on a circle of radius:', options: ['1','\\(n\\)','\\(1/n\\)','\\(\\sqrt{n}\\)'], answer: 0 },
      { q: "If \\(z = \\sqrt{2}e^{i\\pi/4}\\), then \\(z^2\\) equals:", options: ["\\(2e^{i\\pi/4}\\)","\\(2i\\)","\\(\\sqrt{2}\\,i\\)","\\(2\\)"], answer: 1 },
      { q: 'Simplify \\((1+i)^4\\).', options: ['\\(4i\\)','\\(-4i\\)','\\(-4\\)','4'], answer: 2 },
      { q: 'The modulus of \\(\\dfrac{z_1}{z_2}\\) equals:', options: ['\\(|z_1|-|z_2|\\)','\\(|z_1|+|z_2|\\)','\\(|z_1|\\cdot|z_2|\\)','\\(\\dfrac{|z_1|}{|z_2|}\\)'], answer: 3 },
    ],
    red: [
      { q: 'For non-zero \\(z\\), \\(z + \\frac{1}{z}\\) is real if and only if:', options: ['\\(z\\) is real or \\(|z|=1\\)','\\(z\\) is real only (not \\(|z|=1\\))','\\(|z|=1\\) only','\\(z\\) is purely imaginary'], answer: 0 },
      { q: 'If \\(z = re^{i\\theta}\\), then \\(\\bar{z}\\) equals:', options: ['\\(\\frac{1}{r}e^{-i\\theta}\\)','\\(re^{-i\\theta}\\)','\\(-re^{i\\theta}\\)','\\(re^{i\\theta}\\)'], answer: 1 },
      { q: 'A cubic with real coefficients has one root \\(2+3i\\). What is the product of all three roots if the leading coefficient is 1 and the real root is 4?', options: ['4','\\(-4\\)','52','\\(-52\\)'], answer: 2 },
      { q: "Using \\(z+z^{-1}=2\\cos\\theta\\) with \\(z=e^{i\\theta}\\), \\(\\cos^3\\theta\\) equals:", options: ["\\(\\frac{1}{4}(\\cos 3\\theta-3\\cos\\theta)\\)","\\(\\frac{1}{8}(\\cos 3\\theta+3\\cos\\theta)\\)","\\(\\cos^3\\theta\\) (cannot simplify)","\\(\\frac{1}{4}(\\cos 3\\theta+3\\cos\\theta)\\)"], answer: 3 },
      { q: 'The argument of the product of all \\(n\\)-th roots of unity is:', options: ['\\(0\\) (or \\(\\pi\\) if \\(n\\) even)','\\((n-1)\\pi/n\\)','\\(\\pi\\)','\\(2\\pi\\)'], answer: 0 },
      { q: 'Which of the following is NOT a property of complex conjugates?', options: ['\\(\\overline{z_1 z_2}=\\bar{z}_1\\bar{z}_2\\)','\\(\\overline{z_1/z_2}=\\bar{z}_1/|z_2|\\)','\\(|\\bar{z}|=|z|\\)','\\(\\overline{z_1+z_2}=\\bar{z}_1+\\bar{z}_2\\)'], answer: 1 },
      { q: 'How many distinct complex numbers \\(z\\) satisfy \\(z^6=64\\)?', options: ['2','12','6','3'], answer: 2 },
      { q: "The locus \\(|z-3|=2|z|\\) is a circle. Its centre is:", options: ["\\((3,0)\\)","\\((1,0)\\)","\\((4,0)\\)","\\((-1,0)\\)"], answer: 3 },
      { q: 'If \\(\\omega = e^{2\\pi i/3}\\), then \\(1+\\omega+\\omega^2\\) equals:', options: ['0','1','\\(\\omega\\)','3'], answer: 0 },
      { q: 'A student says \\(\\arg(z_1 z_2)=\\arg(z_1)\\cdot\\arg(z_2)\\). This is:', options: ['True always','False; a counterexample is \\(z_1=z_2=i\\)','True only when \\(|z_1|=|z_2|=1\\)','True when both arguments are positive'], answer: 1 },
    ],
  },

  '1.2': {
    name: 'Matrices',
    green: [
      { q: 'What is the determinant of \\(\\begin{pmatrix}2&3\\\\1&4\\end{pmatrix}\\)?', options: ['8','\\(-5\\)','5','11'], answer: 2 },
      { q: 'The identity matrix \\(I\\) satisfies:', options: ['\\(AI=O\\)','\\(AI=A^2\\)','\\(AI=I\\)','\\(AI=IA=A\\)'], answer: 3 },
      { q: 'Matrix multiplication is:', options: ['Associative but not commutative','Commutative and associative','Commutative but not associative','Neither'], answer: 0 },
      { q: 'If \\(A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}\\), what is \\(2A\\)?', options: ['\\(\\begin{pmatrix}2&4\\\\3&8\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&4\\\\6&8\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&2\\\\3&8\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&4\\\\6&4\\end{pmatrix}\\)'], answer: 1 },
      { q: 'The area scale factor of a 2D transformation is:', options: ['\\(\\det A^2\\)','\\(|\\text{tr} A|\\)','\\(|\\det A|\\)','\\(\\det A\\)'], answer: 2 },
      { q: 'The rotation matrix for angle \\(\\theta\\) anticlockwise is:', options: ['\\(\\begin{pmatrix}\\cos\\theta&\\sin\\theta\\\\-\\sin\\theta&\\cos\\theta\\end{pmatrix}\\)','\\(\\begin{pmatrix}\\sin\\theta&\\cos\\theta\\\\\\cos\\theta&-\\sin\\theta\\end{pmatrix}\\)','\\(\\begin{pmatrix}\\cos\\theta&-\\cos\\theta\\\\\\sin\\theta&\\sin\\theta\\end{pmatrix}\\)','\\(\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\\\sin\\theta&\\cos\\theta\\end{pmatrix}\\)'], answer: 3 },
      { q: 'The reflection matrix in \\(y=x\\) is:', options: ['\\(\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&-1\\\\-1&0\\end{pmatrix}\\)'], answer: 0 },
      { q: 'A matrix is singular when:', options: ['It is not square','Its determinant is 0','Its trace is 0','It has no eigenvalues'], answer: 1 },
      { q: 'If \\(A\\mathbf{v} = \\lambda\\mathbf{v}\\) for non-zero \\(\\mathbf{v}\\), then \\(\\lambda\\) is called:', options: ['A norm','A cofactor','An eigenvalue','A determinant'], answer: 2 },
      { q: 'The characteristic equation of \\(A\\) is obtained from:', options: ['\\(\\det(A+\\lambda I)=0\\)','\\(A\\mathbf{v}=\\mathbf{0}\\)','\\(\\text{tr}(A)-\\lambda=0\\)','\\(\\det(A-\\lambda I)=0\\)'], answer: 3 },
      { q: 'What does \\((AB)^T\\) equal?', options: ['\\(B^T A^T\\)','\\(A^T B^T\\)','\\((AB)^{-1}\\)','\\(A B^T\\)'], answer: 0 },
      { q: 'For a \\(2\\times2\\) matrix \\(A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}\\), the inverse is:', options: ['\\(\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}\\)','\\(\\frac{1}{ad-bc}\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}\\)','\\(\\frac{1}{ad-bc}\\begin{pmatrix}a&-b\\\\-c&d\\end{pmatrix}\\)','\\(\\frac{1}{ad-bc}\\begin{pmatrix}d&b\\\\c&a\\end{pmatrix}\\)'], answer: 1 },
      { q: 'What is \\(\\det(AB)\\)?', options: ['\\(\\det(A+B)\\)','\\(\\det A - \\det B\\)','\\(\\det A \\cdot \\det B\\)','\\(\\det A + \\det B\\)'], answer: 2 },
      { q: 'An \\(m\\times n\\) matrix multiplied by an \\(n\\times p\\) matrix gives a matrix of size:', options: ['\\(n\\times n\\)','\\(m\\times n\\)','\\(p\\times m\\)','\\(m\\times p\\)'], answer: 3 },
      { q: 'The reflection in the \\(x\\)-axis has matrix:', options: ['\\(\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'If \\(\\det A = 0\\), the matrix is called:', options: ['Orthogonal','Singular','Invertible','Diagonal'], answer: 1 },
      { q: 'The Cayley-Hamilton theorem states that every matrix satisfies:', options: ['\\(A^n=O\\) for some \\(n\\)','\\(A=A^T\\)','Its own characteristic equation','\\(A^2=I\\)'], answer: 2 },
      { q: 'The trace of \\(A=\\begin{pmatrix}3&1\\\\2&5\\end{pmatrix}\\) is:', options: ['15','\\(-7\\)','13','8'], answer: 3 },
      { q: 'Which matrix represents an enlargement by scale factor 3?', options: ['\\(3I\\)','\\(\\begin{pmatrix}3&0\\\\0&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&3\\\\3&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&3\\\\3&1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'If \\(A\\) has eigenvalue \\(\\lambda\\), then \\(A^2\\) has eigenvalue:', options: ['\\(1/\\lambda\\)','\\(\\lambda^2\\)','\\(2\\lambda\\)','\\(\\lambda\\)'], answer: 1 },
    ],
    amber: [
      { q: 'Find the eigenvalues of \\(\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}\\).', options: ['3 and 4','\\(-1\\) and 8','2 and 5','1 and 6'], answer: 2 },
      { q: "What is \\(\\det\\begin{pmatrix}1&2&0\\\\3&-1&4\\\\2&0&1\\end{pmatrix}\\)?", options: ["\\(-11\\)","15","\\(-3\\)","9"], answer: 3 },
      { q: 'The system \\(Ax=b\\) has a unique solution when:', options: ['\\(\\det A \\neq 0\\)','\\(\\det A = 0\\)','\\(A=I\\)','\\(b=0\\)'], answer: 0 },
      { q: 'The eigenvector of \\(\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}\\) for \\(\\lambda=5\\) is:', options: ['\\(\\begin{pmatrix}0\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\-2\\end{pmatrix}\\)','\\(\\begin{pmatrix}2\\\\1\\end{pmatrix}\\)'], answer: 1 },
      { q: 'Using Cayley-Hamilton for \\(A\\) with characteristic equation \\(\\lambda^2-5\\lambda+6=0\\), \\(A^2\\) equals:', options: ['\\(6A-5I\\)','\\(-5A+6I\\)','\\(5A-6I\\)','\\(5A+6I\\)'], answer: 2 },
      { q: 'A transformation maps the unit square to a parallelogram with area 6. The determinant of the transformation matrix has absolute value:', options: ['3','\\(\\sqrt{6}\\)','36','6'], answer: 3 },
      { q: 'The matrix for rotation by \\(90°\\) anticlockwise is:', options: ['\\(\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}-1&0\\\\0&-1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'Three simultaneous equations with \\(\\det A = 0\\) and inconsistent right-hand sides have:', options: ['Two solutions','No solution','A unique solution','Infinitely many solutions'], answer: 1 },
      { q: 'Which product gives \\(A^{-1}\\) for \\(A=\\begin{pmatrix}3&1\\\\5&2\\end{pmatrix}\\)?', options: ['\\(\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}\\)','\\(\\begin{pmatrix}-2&1\\\\5&-3\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&-1\\\\-5&3\\end{pmatrix}\\)','\\(\\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}\\)'], answer: 2 },
      { q: 'For \\(2\\times 2\\) matrix \\(A\\), the sum of eigenvalues equals:', options: ['\\(\\det(A)\\)','\\(|A|^2\\)','\\(\\text{tr}(A^2)\\)','\\(\\text{tr}(A)\\)'], answer: 3 },
      { q: 'The composition "first reflect in \\(x\\)-axis, then rotate \\(90°\\) anticlockwise" has matrix (read right to left):', options: ['\\(\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&-1\\end{pmatrix}\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}\\)'], answer: 0 },
      { q: 'If \\(A\\) is \\(3\\times 3\\) and \\(\\det A = 2\\), then \\(\\det(3A)=\\)', options: ['\\(2\\)','54','6','18'], answer: 1 },
      { q: 'The eigenvalues of \\(\\begin{pmatrix}5&0\\\\0&3\\end{pmatrix}\\) are:', options: ['8 and 0','4 and 4','5 and 3','15 and 0'], answer: 2 },
      { q: 'If \\(\\det A = 3\\), then \\(\\det(A^{-1}) =\\)', options: ['\\(3\\)','\\(-3\\)','\\(9\\)','\\(1/3\\)'], answer: 3 },
      { q: 'A transformation has matrix with \\(\\det = -2\\). Its effect on orientation is:', options: ['Reversed (reflection component)','Preserved','No change to area','Scaling by 2'], answer: 0 },
      { q: 'The product of eigenvalues of \\(A\\) equals:', options: ['\\(\\text{tr}(A^2)\\)','\\(\\det A\\)','\\(\\text{tr}(A)\\)','\\(|A|^2\\)'], answer: 1 },
      { q: 'To find the inverse of a \\(3\\times 3\\) matrix using cofactors, you compute \\(A^{-1}=\\)', options: ['\\(\\det A \\cdot \\text{adj}\\,A\\)','\\((\\text{adj}\\,A)^T\\)','\\(\\frac{1}{\\det A}\\,\\text{adj}\\,A\\)','\\(\\frac{1}{\\det A}\\,A\\)'], answer: 2 },
      { q: 'A system \\(Ax=b\\) where \\(\\det A = 0\\) and \\(b \\neq 0\\) may have:', options: ['Always exactly one solution','Always no solution','Always infinitely many','No solution or infinitely many'], answer: 3 },
      { q: 'The sign pattern of cofactors for a \\(3\\times 3\\) matrix starts:', options: ['\\(+,-,+\\)','\\(-,+,-\\)','\\(+,+,+\\)','\\(-,-,-\\)'], answer: 0 },
      { q: 'If \\(Av = \\lambda v\\) and \\(Aw = \\mu w\\) with \\(\\lambda \\neq \\mu\\), then \\(v\\) and \\(w\\) are:', options: ['Equal up to a scalar','Linearly independent','Parallel','Orthogonal'], answer: 1 },
    ],
    red: [
      { q: 'The characteristic polynomial of \\(A=\\begin{pmatrix}2&1\\\\4&2\\end{pmatrix}\\) is \\(\\lambda^2-4\\lambda\\). By Cayley-Hamilton, \\(A^3\\) equals:', options: ['\\(A^2 = 4A\\) only','\\(16I\\)','\\(4A^2=16A\\)','\\(4A\\)'], answer: 2 },
      { q: 'A \\(3\\times 3\\) matrix \\(A\\) has \\(\\det A = 0\\). The system \\(Ax=b\\) is consistent. This means:', options: ['No solutions','Two solutions','Exactly one solution','Infinitely many solutions (line or plane of solutions)'], answer: 3 },
      { q: 'For a rotation matrix \\(R_\\theta\\), \\(\\det(R_\\theta)\\) always equals:', options: ['1','\\(\\sin\\theta\\)','\\(\\cos\\theta\\)','\\(-1\\)'], answer: 0 },
      { q: 'If both eigenvalues of a \\(2\\times 2\\) matrix are 0, the matrix is:', options: ['Always the zero matrix, with no exceptions','Either the zero matrix or nilpotent','Always invertible','Always symmetric'], answer: 1 },
      { q: 'For \\(A=\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}\\), what is \\(A^4\\)?', options: ['\\(-I\\)','\\(O\\)','\\(I\\)','\\(A\\)'], answer: 2 },
      { q: 'Three planes given by \\(Ax=b\\) form a "triangular prism" (no common point, two pairs intersecting in parallel lines). This means:', options: ['All three planes are parallel','\\(\\det A \\neq 0\\)','\\(\\det A = 0\\) and the system has a line of solutions','\\(\\det A = 0\\) and the system is inconsistent'], answer: 3 },
      { q: 'If \\(A\\) and \\(B\\) are similar matrices (\\(B=P^{-1}AP\\)), they have:', options: ['The same eigenvalues','\\(A=B\\)','The same eigenvectors','The same determinant but different traces'], answer: 0 },
      { q: 'The image of the unit circle under a linear transformation \\(A\\) is generally:', options: ['A circle','An ellipse','A square','A parabola'], answer: 1 },
      { q: 'For \\(2\\times 2\\) matrix with eigenvalues \\(\\lambda_1, \\lambda_2\\), the characteristic equation is:', options: ['\\(\\lambda^2+\\lambda_1\\lambda_2=0\\)','\\((\\lambda-\\lambda_1)(\\lambda+\\lambda_2)=0\\)','\\(\\lambda^2-(\\lambda_1+\\lambda_2)\\lambda+\\lambda_1\\lambda_2=0\\)','\\(\\lambda^2-(\\lambda_1-\\lambda_2)^2=0\\)'], answer: 2 },
      { q: 'A student claims that if \\(AB=O\\) then \\(A=O\\) or \\(B=O\\). This is:', options: ['True always','True only for \\(2\\times 2\\) matrices','True when \\(\\det A\\neq 0\\)','False; e.g. \\(A=\\begin{pmatrix}1&1\\\\1&1\\end{pmatrix}\\)'], answer: 3 },
    ],
  },

  '1.3': {
    name: 'Further Algebra and Functions',
    green: [
      { q: 'For the quadratic \\(ax^2+bx+c=0\\) with roots \\(\\alpha,\\beta\\): \\(\\alpha+\\beta=\\)', options: ['\\(-b/a\\)','\\(b/a\\)','\\(c/a\\)','\\(-c/a\\)'], answer: 0 },
      { q: 'For the quadratic \\(ax^2+bx+c=0\\): \\(\\alpha\\beta=\\)', options: ['\\(-c/a\\)','\\(c/a\\)','\\(-b/a\\)','\\(b/a\\)'], answer: 1 },
      { q: 'For the cubic \\(ax^3+bx^2+cx+d=0\\) with roots \\(\\alpha,\\beta,\\gamma\\): \\(\\alpha\\beta\\gamma=\\)', options: ['\\(c/a\\)','\\(-c/a\\)','\\(-d/a\\)','\\(d/a\\)'], answer: 2 },
      { q: '\\(\\alpha^2+\\beta^2\\) can be written as:', options: ['\\((\\alpha+\\beta)^2+2\\alpha\\beta\\)','\\((\\alpha-\\beta)^2\\)','\\(\\alpha\\beta(\\alpha+\\beta)\\)','\\((\\alpha+\\beta)^2-2\\alpha\\beta\\)'], answer: 3 },
      { q: 'For the cubic \\(ax^3+bx^2+cx+d=0\\): \\(\\alpha+\\beta+\\gamma=\\)', options: ['\\(-b/a\\)','\\(b/a\\) (sign)','\\(c/a\\)','\\(d/a\\)'], answer: 0 },
      { q: 'The partial fraction form of \\(\\dfrac{f(x)}{(ax+b)(cx+d)}\\) with \\(\\deg f < 2\\) is:', options: ['\\(\\dfrac{A}{(ax+b)^2}+\\dfrac{B}{cx+d}\\)','\\(\\dfrac{A}{ax+b}+\\dfrac{B}{cx+d}\\)','\\(\\dfrac{Ax+B}{ax+b}+C\\)','\\(\\dfrac{A}{ax+b}+\\dfrac{Bx}{cx+d}\\)'], answer: 1 },
      { q: 'An improper rational function has:', options: ['Complex roots','No real roots','Degree of numerator \\(\\geq\\) degree of denominator','Negative coefficients'], answer: 2 },
      { q: '\\(|f(x)| < a\\) (where \\(a>0\\)) means:', options: ['\\(f(x) < a\\)','\\(f(x) > -a\\)','\\(f(x)^2 < a\\)','\\(-a < f(x) < a\\)'], answer: 3 },
      { q: 'The solutions to \\(|x-2| < 5\\) are:', options: ['\\(-3 < x < 7\\)','\\(x < 7\\) only','\\(x > -3\\) only','\\(-7 < x < 3\\)'], answer: 0 },
      { q: 'To solve a rational inequality, you should NOT:', options: ['Test values in each interval','Multiply both sides by a variable expression (unknown sign)','Rearrange to one side','Use a sign table'], answer: 1 },
      { q: 'For partial fractions with a repeated linear factor \\((ax+b)^2\\):', options: ['Use \\(\\frac{Ax+B}{(ax+b)^2}\\)','Divide the numerator first','Use \\(\\frac{A}{ax+b}+\\frac{B}{(ax+b)^2}\\)','Use \\(\\frac{A}{(ax+b)^2}\\) only'], answer: 2 },
      { q: 'If \\(\\alpha, \\beta\\) are roots of \\(x^2-5x+3=0\\), then \\(\\alpha+\\beta=\\)', options: ['\\(-5\\)','3','\\(-3\\)','5'], answer: 3 },
      { q: 'If \\(\\alpha, \\beta\\) are roots of \\(x^2-5x+3=0\\), then \\(\\alpha\\beta=\\)', options: ['3','5','\\(-3\\)','\\(-5\\)'], answer: 0 },
      { q: 'For the cubic \\(x^3-3x^2+5x-2=0\\) with roots \\(\\alpha,\\beta,\\gamma\\): \\(\\alpha\\beta+\\beta\\gamma+\\gamma\\alpha=\\)', options: ['2','5','3','\\(-3\\)'], answer: 1 },
      { q: 'The modulus function satisfies \\(|ab|=\\)', options: ['\\(|a-b|\\)','\\(a^2 b^2\\)','\\(|a||b|\\)','\\(|a|+|b|\\)'], answer: 2 },
      { q: 'An oblique asymptote occurs when:', options: ['Denominator has degree 2','Numerator has complex roots','The function is periodic','Degree of numerator is exactly 1 more than denominator'], answer: 3 },
      { q: '\\(|f(x)| > a\\) (where \\(a > 0\\)) means:', options: ['\\(f(x) > a\\) or \\(f(x) < -a\\)','\\(-a < f(x) < a\\)','\\(f(x)^2 > 0\\)','\\(f(x) > 0\\)'], answer: 0 },
      { q: 'For roots of \\(x^3+px^2+qx+r=0\\): \\(\\sum\\alpha\\beta=\\)', options: ['\\(r\\)','\\(q\\)','\\(-q\\)','\\(p\\)'], answer: 1 },
      { q: 'To convert \\(|f(x)|=|g(x)|\\) to a solvable equation, you:', options: ['Square to get \\(f^2=g^2\\) — that alone suffices','Set \\(f(x)-g(x)=0\\)','Solve \\(f(x)=g(x)\\) and \\(f(x)=-g(x)\\)','Only solve \\(f(x)=g(x)\\)'], answer: 2 },
      { q: 'For the partial fraction of \\(\\frac{f(x)}{(x^2+1)(x+2)}\\) where \\(x^2+1\\) is irreducible:', options: ['\\(\\frac{A}{x^2+1}+\\frac{B}{x+2}\\)','\\(\\frac{A}{(x+i)(x-i)}+\\frac{B}{x+2}\\)','\\(\\frac{Ax+B}{(x^2+1)^2}+\\frac{C}{x+2}\\)','\\(\\frac{Ax+B}{x^2+1}+\\frac{C}{x+2}\\)'], answer: 3 },
    ],
    amber: [
      { q: 'If \\(\\alpha,\\beta\\) are roots of \\(2x^2-3x+1=0\\), find \\(\\alpha^2+\\beta^2\\).', options: ['\\(5/4\\)','\\(9/4\\)','\\(1/2\\)','\\(5/2\\)'], answer: 0 },
      { q: 'If \\(\\alpha,\\beta,\\gamma\\) are roots of \\(x^3-2x^2+x-3=0\\), find \\(\\alpha^2+\\beta^2+\\gamma^2\\).', options: ['4','2','1','\\(-1\\)'], answer: 1 },
      { q: 'The equation \\(x^3-4x+1=0\\) has roots \\(\\alpha,\\beta,\\gamma\\). Find an equation with roots \\(2\\alpha,2\\beta,2\\gamma\\).', options: ['\\(x^3-8x+1=0\\)','\\(8x^3-16x+1=0\\)','\\(x^3-16x+8=0\\)','\\(x^3-8x+2=0\\)'], answer: 2 },
      { q: 'Decompose \\(\\dfrac{5x+1}{(x+1)(2x-1)}\\).', options: ['\\(\\dfrac{2}{x+1}+\\dfrac{3}{2x-1}\\)','\\(\\dfrac{1}{x+1}+\\dfrac{2}{2x-1}\\)','\\(\\dfrac{5}{x+1}-\\dfrac{1}{2x-1}\\)','\\(\\dfrac{4/3}{x+1}+\\dfrac{7/3}{2x-1}\\)'], answer: 3 },
      { q: 'Solve \\(\\dfrac{x-1}{x+2}>2\\).', options: ['\\(-5<x<-2\\)','\\(x>-2\\)','\\(x<-5\\)','\\(x<-5\\) or \\(x>-2\\)'], answer: 0 },
      { q: 'Solve \\(|3x-1|<|x+3|\\).', options: ['All real \\(x\\)','\\(-\\frac{1}{2}<x<2\\)','\\(x<-\\frac{1}{2}\\) or \\(x>2\\)','\\(-2<x<\\frac{1}{2}\\)'], answer: 1 },
      { q: 'For roots \\(\\alpha,\\beta\\) of \\(x^2-5x+6=0\\), find \\(\\frac{1}{\\alpha}+\\frac{1}{\\beta}\\).', options: ['\\(5\\)','\\(1\\)','\\(5/6\\)','\\(6/5\\)'], answer: 2 },
      { q: "Express \\(\\dfrac{x^2+3x+5}{(x+1)(x+2)}\\) in partial fractions after appropriate preparation.", options: ["\\(\\dfrac{3}{x+1}+\\dfrac{1}{x+2}\\)","\\(1+\\dfrac{1}{x+1}+\\dfrac{3}{x+2}\\)","\\(x+\\dfrac{1}{x+1}\\)","\\(1+\\dfrac{3}{x+1}-\\dfrac{3}{x+2}\\)"], answer: 3 },
      { q: 'If \\(\\alpha,\\beta,\\gamma\\) are roots of \\(x^3+x-2=0\\), find \\(\\alpha\\beta\\gamma\\).', options: ['2','\\(-2\\)','1','0'], answer: 0 },
      { q: 'Solve \\(|2x+1|\\geq 5\\).', options: ['\\(x\\leq-3\\) only','\\(x\\leq-3\\) or \\(x\\geq2\\)','\\(-3\\leq x\\leq 2\\)','\\(x\\geq2\\) only'], answer: 1 },
      { q: 'The oblique asymptote of \\(y=\\dfrac{x^2+2x+3}{x+1}\\) is:', options: ['\\(y=x\\)','\\(y=x+3\\)','\\(y=x+1\\)','\\(y=x+2\\)'], answer: 2 },
      { q: 'If the roots of \\(x^3-6x^2+11x-6=0\\) are \\(1,2,3\\), what is the sum of squares of roots?', options: ['36','11','6','14'], answer: 3 },
      { q: 'Solve the inequality \\(\\dfrac{1}{x-2}>3\\).', options: ['\\(2<x<\\dfrac{7}{3}\\)','\\(x>\\dfrac{7}{3}\\)','\\(x<2\\) or \\(x>\\dfrac{7}{3}\\)','\\(x>2\\)'], answer: 0 },
      { q: 'Find the partial fraction decomposition of \\(\\dfrac{3}{x(x^2+3)}\\).', options: ['\\(\\dfrac{1}{x}+\\dfrac{x+1}{x^2+3}\\)','\\(\\dfrac{1}{x}-\\dfrac{x}{x^2+3}\\)','\\(\\dfrac{3}{x}-\\dfrac{3}{x^2+3}\\)','\\(\\dfrac{1}{x^2}+\\dfrac{1}{x^2+3}\\)'], answer: 1 },
      { q: 'For the equation \\(x^3-px^2+qx-r=0\\) (\\(p,q,r>0\\)) with roots \\(\\alpha,\\beta,\\gamma\\), \\(\\alpha^2\\beta^2+\\beta^2\\gamma^2+\\gamma^2\\alpha^2=\\)', options: ['\\(q^2+2pr\\)','\\(p^2+2q\\)','\\(q^2-2pr\\)','\\(p^2-2q\\)'], answer: 2 },
      { q: 'To find an equation with roots \\(\\alpha^2,\\beta^2,\\gamma^2\\) from \\(f(x)=0\\), you substitute:', options: ['\\(x=w^2\\)','\\(x=1/w\\)','\\(x=w+1\\)','\\(x=\\sqrt{w}\\) (i.e. \\(w=x^2\\) in the original)'], answer: 3 },
      { q: 'The solution set of \\(\\dfrac{x^2-1}{x^2+1}>0\\) is:', options: ['\\(x<-1\\) or \\(x>1\\)','\\(-1<x<1\\)','All \\(x\\neq 0\\)','No solutions'], answer: 0 },
      { q: 'If \\(\\alpha,\\beta\\) are roots of \\(x^2-4x+1=0\\), then \\(\\alpha^3+\\beta^3=\\)', options: ['28','52','64','\\(-52\\)'], answer: 1 },
      { q: "Decompose \\(\\dfrac{4}{(x-1)^2(x+3)}\\).", options: ["\\(\\dfrac{1}{(x-1)^2}+\\dfrac{1}{x+3}\\)","\\(\\dfrac{4}{(x-1)^2}-\\dfrac{4}{x+3}\\)","\\(-\\dfrac{1}{4(x-1)}+\\dfrac{1}{(x-1)^2}+\\dfrac{1}{4(x+3)}\\)","\\(\\dfrac{2}{x-1}+\\dfrac{4}{x+3}\\)"], answer: 2 },
      { q: 'For roots \\(\\alpha,\\beta,\\gamma,\\delta\\) of \\(x^4-5x^3+ax^2+bx+c=0\\): \\(\\alpha+\\beta+\\gamma+\\delta=\\)', options: ['\\(-5\\)','\\(a\\)','\\(c\\)','5'], answer: 3 },
    ],
    red: [
      { q: 'Given \\(\\alpha,\\beta\\) are roots of \\(x^2-3x+k=0\\) and \\(\\alpha^2+\\beta^2=5\\), find \\(k\\).', options: ['2','4','\\(-2\\)','\\(-4\\)'], answer: 0 },
      { q: "The equation with roots \\(1/\\alpha^2, 1/\\beta^2\\) where \\(\\alpha,\\beta\\) satisfy \\(x^2-4x+2=0\\) is:", options: ["\\(2x^2-6x+1=0\\)","\\(4x^2-12x+1=0\\)","\\(2x^2+6x-1=0\\)","\\(4x^2-6x+1=0\\)"], answer: 1 },
      { q: "Solve \\(\\dfrac{2x-1}{x+1}\\leq\\dfrac{x}{x-2}\\).", options: ["\\(-1<x<2\\)","All real \\(x\\)","\\(-1<x\\leq 3-\\sqrt{7}\\) or \\(2<x\\leq 3+\\sqrt{7}\\)","\\(x<-1\\)"], answer: 2 },
      { q: 'For \\(\\alpha,\\beta,\\gamma\\) roots of \\(x^3-x+1=0\\), find \\(\\alpha^3+\\beta^3+\\gamma^3\\).', options: ['3 (from \\(3\\alpha\\beta\\gamma\\))','1','0','\\(-3\\)'], answer: 3 },
      { q: 'A student writes \\(\\dfrac{2}{x^2-1}=\\dfrac{A}{x-1}+\\dfrac{B}{x+1}\\) and finds \\(A=1,B=-1\\). Check: \\(A+B=\\)', options: ['0','\\(-2\\)','1','2'], answer: 0 },
      { q: 'Solve \\(|x^2-4|<3\\).', options: ['\\(-\\sqrt{7}<x<\\sqrt{7}\\)','\\(-\\sqrt{7}<x<-1\\) or \\(1<x<\\sqrt{7}\\)','\\(1<x<\\sqrt{7}\\)','\\(-1<x<1\\)'], answer: 1 },
      { q: 'If \\(f(x)=\\dfrac{x^3+1}{x^2-x}\\), the oblique asymptote is:', options: ['\\(y=x+2\\)','\\(y=x-1\\)','\\(y=x+1\\)','\\(y=x\\)'], answer: 2 },
      { q: 'For roots of \\(x^4-1=0\\): the sum of cubes of all roots equals:', options: ['1','4','\\(-1\\)','0'], answer: 3 },
      { q: 'If all roots of \\(p(x)=0\\) are doubled to get \\(q(x)=0\\), and \\(p(x)=x^3-6x^2+11x-6\\), then \\(q(x)=\\)', options: ['\\(x^3-12x^2+44x-48\\)','\\(x^3-3x^2+\\frac{11}{2}x-\\frac{3}{4}\\)','\\(8x^3-12x^2+11x-6\\)','\\(x^3-6x^2+22x-48\\)'], answer: 0 },
      { q: 'The inequality \\(\\dfrac{(x-1)^2}{x+2}>0\\) has solution:', options: ['\\(x>1\\)','\\(x>-2,\\ x\\neq 1\\)','\\(x\\neq 1\\)','\\(x<-2\\)'], answer: 1 },
    ],
  },

  '1.4': {
    name: 'Series',
    green: [
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}r =\\)', options: ['\\(n^2\\)','\\(\\frac{n(2n+1)}{2}\\)','\\(\\frac{n(n+1)}{2}\\)','\\(\\frac{n(n-1)}{2}\\)'], answer: 2 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}r^2 =\\)', options: ['\\(\\frac{n^2(n+1)^2}{4}\\)','\\(\\frac{n(n+1)}{2}\\)','\\(\\frac{n(2n+1)(2n-1)}{6}\\)','\\(\\frac{n(n+1)(2n+1)}{6}\\)'], answer: 3 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}r^3 =\\)', options: ['\\(\\left[\\frac{n(n+1)}{2}\\right]^2\\)','\\(\\frac{n^2(n+1)}{4}\\)','\\(\\frac{n(n+1)(2n+1)}{6}\\)','\\(\\frac{n^4}{4}\\)'], answer: 0 },
      { q: 'What is \\(\\displaystyle\\sum_{r=1}^{4}r^2\\)?', options: ['100','30','20','55'], answer: 1 },
      { q: 'In a proof by induction for a sum formula, the base case is checked at:', options: ['\\(n=k\\)','\\(n=k+1\\)','\\(n=1\\)','\\(n=0\\)'], answer: 2 },
      { q: 'The Maclaurin series for \\(e^x\\) is:', options: ['\\(1-x+\\frac{x^2}{2!}-\\cdots\\)','\\(x-\\frac{x^3}{3!}+\\cdots\\)','\\(1+x+x^2+x^3+\\cdots\\)','\\(1+x+\\frac{x^2}{2!}+\\frac{x^3}{3!}+\\cdots\\)'], answer: 3 },
      { q: 'The Maclaurin series for \\(\\sin x\\) is:', options: ['\\(x-\\frac{x^3}{3!}+\\frac{x^5}{5!}-\\cdots\\)','\\(1-\\frac{x^2}{2!}+\\frac{x^4}{4!}-\\cdots\\)','\\(x+\\frac{x^3}{3!}+\\cdots\\)','\\(1+x-\\frac{x^2}{2}+\\cdots\\)'], answer: 0 },
      { q: 'The Maclaurin series for \\(\\cos x\\) is:', options: ['\\(-\\sin x\\) series','\\(1-\\frac{x^2}{2!}+\\frac{x^4}{4!}-\\cdots\\)','\\(x-\\frac{x^3}{3!}+\\cdots\\)','\\(1+x^2/2+\\cdots\\)'], answer: 1 },
      { q: 'The Maclaurin series for \\(\\ln(1+x)\\) is valid for:', options: ['\\(0<x<1\\)','\\(|x|<2\\)','\\(-1<x\\leq 1\\)','All real \\(x\\)'], answer: 2 },
      { q: 'In method of differences, \\(\\displaystyle\\sum_{r=1}^{n}[f(r)-f(r+1)]=\\)', options: ['\\(f(n)-f(1)\\)','\\(f(n+1)-f(1)\\)','\\(nf(1)\\)','\\(f(1)-f(n+1)\\)'], answer: 3 },
      { q: 'What is the first term of the Maclaurin series for \\(\\ln(1+x)\\)?', options: ['\\(x\\)','0','1','\\(-x\\)'], answer: 0 },
      { q: 'The inductive step in a proof by induction shows:', options: ['An explicit formula for \\(n=k+1\\)','If true for \\(n=k\\), it is true for \\(n=k+1\\)','The base case','The formula is true for all \\(n\\)'], answer: 1 },
      { q: 'The Taylor series of \\(f(x)\\) about \\(x=a\\) begins:', options: ['\\(f(x)+f\'(x)+\\cdots\\)','\\(f(a)(x-a)+\\cdots\\)','\\(f(a)+f\'(a)(x-a)+\\cdots\\)','\\(f(0)+f^{\\prime}(0)x+\\cdots\\) (Maclaurin)'], answer: 2 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}1 =\\)', options: ['1','\\(n^2\\)','\\(n(n+1)/2\\)','\\(n\\)'], answer: 3 },
      { q: 'What is \\(\\displaystyle\\sum_{r=1}^{3}r^3\\)?', options: ['36','9','100','16'], answer: 0 },
      { q: 'The Maclaurin series for \\((1+x)^{1/2}\\) valid for \\(|x|<1\\) starts:', options: ['\\(1+x-x^2+\\cdots\\)','\\(1+\\frac{1}{2}x-\\frac{1}{8}x^2+\\cdots\\)','\\(1+\\frac{1}{2}x+\\frac{1}{2}x^2+\\cdots\\)','\\(1-\\frac{1}{2}x+\\cdots\\)'], answer: 1 },
      { q: 'The range of validity of the Maclaurin series for \\(e^x\\) is:', options: ['\\(x>0\\)','\\(-1<x<1\\)','All real \\(x\\)','\\(|x|<1\\) only (radius)'], answer: 2 },
      { q: 'Which of these is needed to complete an induction proof?', options: ['Finding the general formula','Checking \\(n=2\\)','Differentiation','A conclusion sentence stating the result holds for all \\(n\\geq1\\)'], answer: 3 },
      { q: '\\(\\displaystyle\\sum_{r=1}^{n}c\\) (constant) equals:', options: ['\\(cn\\)','\\(c\\)','\\(cn^2\\)','\\(c/n\\)'], answer: 0 },
      { q: 'To find the Maclaurin series for \\(f(x)\\), you need:', options: ['The antiderivative of \\(f\\)','\\(f(0), f\'(0), f\'\'(0), \\ldots\\)','\\(f(1), f\'(1), \\ldots\\)','\\(\\lim_{x\\to0} f(x)\\)'], answer: 1 },
    ],
    amber: [
      { q: 'Find \\(\\displaystyle\\sum_{r=1}^{n}(2r-1)\\).', options: ['\\(n(2n-1)\\)','\\(2n^2-n\\)','\\(n^2\\)','\\(n(n+1)\\)'], answer: 2 },
      { q: 'Find \\(\\displaystyle\\sum_{r=n+1}^{2n}r\\).', options: ['\\(\\frac{n(n+1)}{2}\\) (the first n)','\\(n(2n+1)\\)','\\(\\frac{3n^2}{2}\\)','\\(\\frac{n(3n+1)}{2}\\)'], answer: 3 },
      { q: 'Using partial fractions, \\(\\dfrac{1}{r(r+1)}=\\dfrac{1}{r}-\\dfrac{1}{r+1}\\). Hence \\(\\displaystyle\\sum_{r=1}^{n}\\dfrac{1}{r(r+1)}=\\)', options: ['\\(\\dfrac{n}{n+1}\\)','\\(1\\)','\\(\\dfrac{1}{n+1}\\)','\\(\\dfrac{n+1}{n}\\)'], answer: 0 },
      { q: 'Prove by induction that \\(4^n-1\\) is divisible by 3. In the inductive step you show:', options: ['\\(4^{k+1}=3m+1\\) for some integer \\(m\\), so it is odd','\\(4^{k+1}-1=4(4^k-1)+3\\) which is divisible by 3','\\(4^{k+1}=4^k+4\\)','\\(4^{k+1}-1=(k+1)\\cdot 3\\)'], answer: 1 },
      { q: 'Find the first three non-zero terms of the Maclaurin series for \\(\\sin^2 x\\).', options: ['\\(1-\\cos 2x\\)','\\(x^2+\\frac{x^4}{3}+\\cdots\\)','\\(x^2-\\frac{x^4}{3}+\\frac{2x^6}{45}-\\cdots\\)','\\(x^2-x^4+x^6-\\cdots\\)'], answer: 2 },
      { q: 'What is the Maclaurin series for \\(\\ln(1-x)\\)?', options: ['\\(x+\\frac{x^2}{2}+\\frac{x^3}{3}+\\cdots\\)','\\(-x+\\frac{x^2}{2}-\\frac{x^3}{3}+\\cdots\\)','\\(1-x+x^2-\\cdots\\)','\\(-x-\\frac{x^2}{2}-\\frac{x^3}{3}-\\cdots\\)'], answer: 3 },
      { q: "Find \\(\\displaystyle\\sum_{r=1}^{n}r(r+1)\\).", options: ["\\(\\frac{n(n+1)(n+2)}{3}\\)","\\(\\frac{n(n+1)(2n+1)}{6}+n\\)","\\(\\frac{n^2(n+1)}{2}\\)","\\(\\frac{n(n+2)(2n+1)}{6}\\)"], answer: 0 },
      { q: 'By induction, prove \\(\\sum_{r=1}^n r^2=\\frac{n(n+1)(2n+1)}{6}\\). The key manipulation in the inductive step is:', options: ['Use the quadratic formula','\\(\\frac{k(k+1)(2k+1)}{6}+(k+1)^2=\\frac{(k+1)(k+2)(2k+3)}{6}\\)','\\(k^2+(k+1)^2=\\frac{(k+1)(2k+1)}{6}\\)','Subtract \\(k\\) from each side'], answer: 1 },
      { q: 'Using the series for \\(e^x\\), find \\(e^{0.1}\\) to 4 decimal places.', options: ['1.1051','1.0952','1.1052','1.1000'], answer: 2 },
      { q: 'The first three non-zero terms of the series for \\(e^x\\cos x\\) are:', options: ['\\(1+x+x^2-\\cdots\\)','\\(1+x-x^2-\\cdots\\)','\\(1-x+\\frac{x^2}{2}-\\cdots\\)','\\(1+x-\\frac{x^3}{3}-\\cdots\\)'], answer: 3 },
      { q: 'Using \\(\\frac{1}{r(r+2)}=\\frac{1}{2}\\left(\\frac{1}{r}-\\frac{1}{r+2}\\right)\\), \\(\\sum_{r=1}^n\\frac{1}{r(r+2)}\\) simplifies to:', options: ['\\(\\frac{3}{4}-\\frac{1}{2(n+1)}-\\frac{1}{2(n+2)}\\)','\\(\\frac{1}{2}\\left(1-\\frac{1}{n+2}\\right)\\) (one term only)','\\(\\frac{1}{n+1}+\\frac{1}{n+2}\\)','\\(\\frac{1}{4}\\)'], answer: 0 },
      { q: 'Find the Taylor series of \\(\\ln x\\) about \\(x=1\\) up to \\((x-1)^2\\).', options: ['\\(1+(x-1)+\\cdots\\)','\\((x-1)-\\frac{(x-1)^2}{2}+\\cdots\\)','\\(\\ln 1+(x-1)+\\frac{(x-1)^2}{2}+\\cdots\\)','\\((x-1)^2-\\cdots\\)'], answer: 1 },
      { q: 'Show \\(n^3+2n\\) is divisible by 3 by induction. The inductive step uses:', options: ['Factoring \\(n(n^2+2)\\) as \\(n(n+1)(n-1)+3n\\) without using induction','The base case \\(n=0\\)','\\((k+1)^3+2(k+1)=k^3+3k^2+3k+1+2k+2=(k^3+2k)+3(k^2+k+1)\\)','\\(k^3+2k+3k+3\\)'], answer: 2 },
      { q: "Find \\(\\displaystyle\\sum_{r=1}^{n}\\frac{3}{(3r-2)(3r+1)}\\) by differences.", options: ["\\(1-\\dfrac{1}{3n-2}\\)","\\(\\dfrac{n}{3n+1}\\)","\\(\\dfrac{1}{n}\\)","\\(\\dfrac{3n}{3n+1}\\)"], answer: 3 },
      { q: 'What is the \\(x^3\\) term in the Maclaurin series for \\(\\sin x\\cdot e^x\\)?', options: ['\\(\\frac{x^3}{3}\\)','\\(-\\frac{x^3}{3}\\)','\\(x^3\\)','0'], answer: 0 },
      { q: 'In a proof by induction for divisibility, the inductive step must show:', options: ['The closed form','The \\(k+1\\) case is also divisible (not just quote the \\(k\\) case)','The base case again','The general term'], answer: 1 },
      { q: 'Find \\(\\displaystyle\\sum_{r=1}^{n}(r^3-r)\\).', options: ['\\(\\frac{n^2(n^2-1)}{4}\\)','\\(\\frac{n(n+1)^2(n-1)}{4}\\)','\\(\\frac{n^2(n+1)^2}{4}-\\frac{n(n+1)}{2}\\)','\\(\\frac{n(n+1)(n+2)}{6}\\)'], answer: 2 },
      { q: 'What are the first three terms of the Maclaurin expansion of \\((1-x)^{-1}\\) for \\(|x|<1\\)?', options: ['\\(1-x+x^2-\\cdots\\)','\\(1+\\frac{x}{2}+\\frac{3x^2}{8}+\\cdots\\)','\\(1-\\frac{x}{2}+\\cdots\\)','\\(1+x+x^2+\\cdots\\)'], answer: 3 },
      { q: 'Prove by induction that \\(A^n=\\begin{pmatrix}1&n\\\\0&1\\end{pmatrix}\\) for \\(A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\). The key multiplication in the inductive step is:', options: ['\\(\\begin{pmatrix}1&k\\\\0&1\\end{pmatrix}\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}=\\begin{pmatrix}1&k+1\\\\0&1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}^k=kA\\)','\\(A^{k+1}=A^k+A\\)','The base case'], answer: 0 },
      { q: 'What is \\(\\displaystyle\\sum_{r=1}^{\\infty}\\dfrac{1}{r(r+1)}\\)?', options: ['\\(\\ln 2\\)','1','\\(1/2\\)','\\(\\infty\\)'], answer: 1 },
      { q: 'The Taylor expansion of \\(f(x+h)\\) about \\(h=0\\) gives:', options: ['\\(f(x)f(h)\\)','\\(\\sum hf\'(n)\\)','\\(f(x)+hf\'(x)+\\frac{h^2}{2!}f\'\'(x)+\\cdots\\)','\\(f(x+h)=f(h)+\\cdots\\)'], answer: 2 },
    ],
    red: [
      { q: 'Prove \\(\\displaystyle\\sum_{r=1}^n r^3 = \\left[\\frac{n(n+1)}{2}\\right]^2\\) by induction. The key simplification is:', options: ['Using the formula for \\(\\sum r^2\\)','Showing the sum telescopes','Differentiating the formula','\\(\\left[\\frac{k(k+1)}{2}\\right]^2+(k+1)^3=\\left[\\frac{(k+1)(k+2)}{2}\\right]^2\\)'], answer: 3 },
      { q: "Which is the correct partial-fraction decomposition of \\(\\frac{r+1}{r(r+2)}\\)?", options: ["\\(\\frac{1}{2r}+\\frac{1}{2(r+2)}\\)","\\(\\frac{1}{2r}-\\frac{1}{2(r+2)}\\)","\\(\\frac{1}{r}-\\frac{1}{r+2}\\)","\\(\\frac{1}{r}+\\frac{1}{r+2}\\)"], answer: 0 },
      { q: 'Use the Maclaurin series to estimate \\(\\displaystyle\\int_0^{0.1}\\frac{\\sin x}{x}\\,dx\\) to 4 decimal places.', options: ['0.1000','0.0999','0.1001','0.0998'], answer: 1 },
      { q: 'The range of validity of \\(\\ln(1+2x)\\) expanded as a Maclaurin series is:', options: ['\\(-1<x\\leq 1\\)','\\(|x|<\\frac{1}{2}\\)','\\(-\\frac{1}{2}<x\\leq\\frac{1}{2}\\)','All \\(x\\)'], answer: 2 },
      { q: 'By induction, prove \\(2^n>n^2\\) for \\(n\\geq 5\\). Which base case is used?', options: ['\\(n=1\\)','\\(n=4\\)','\\(n=2\\)','\\(n=5\\)'], answer: 3 },
      { q: 'Find the exact sum \\(\\displaystyle\\sum_{r=1}^{\\infty}\\dfrac{1}{4r^2-1}\\) using partial fractions.', options: ['\\(1/2\\)','1','\\(\\infty\\)','\\(1/4\\)'], answer: 0 },
      { q: "The error in approximating \\(e\\) by \\(1+1+\\frac{1}{2!}+\\frac{1}{3!}+\\frac{1}{4!}\\) is less than:", options: ["\\(1/6!\\)","\\(1/4!\\)","\\(1/5!\\)","\\(1/7!\\)"], answer: 1 },
      { q: 'For the series \\(\\sum_{r=0}^{\\infty} ar^n=\\frac{a}{1-r}\\) (\\(|r|<1\\)): if \\(r=0.5\\) and \\(a=1\\), which Maclaurin series does this relate to?', options: ['\\(\\ln(1+x)\\) at \\(x=1/2\\)','\\(\\sin x\\) at \\(x=1/2\\)','\\((1-x)^{-1}\\) evaluated at \\(x=1/2\\)','\\(e^x\\) at \\(x=1/2\\)'], answer: 2 },
      { q: 'Using \\(\\cos^2\\theta = \\frac{1+\\cos2\\theta}{2}\\) and the Maclaurin series for \\(\\cos u\\), the series for \\(\\cos^2 x\\) up to \\(x^4\\) is:', options: ['\\(1+x^2-x^4+\\cdots\\)','\\(1-x^2+x^4-\\cdots\\)','\\(\\frac{1}{2}+\\frac{1}{2}\\cos 2x\\) (not a power series form)','\\(1-x^2+\\frac{x^4}{3}-\\cdots\\)'], answer: 3 },
      { q: 'A telescoping sum \\(\\sum_{r=1}^n f(r)\\) where \\(f(r)=g(r)-g(r+2)\\) (gap 2) gives:', options: ['\\(g(1)+g(2)-g(n+1)-g(n+2)\\)','\\(2g(1)-g(n+1)-g(n+2)\\) (twice)','\\(g(1)-g(n+1)\\)','\\(g(1)-g(n+2)\\)'], answer: 0 },
    ],
  },

  '1.5': {
    name: 'Further Calculus',
    green: [
      { q: 'The arc length of \\(y=f(x)\\) from \\(a\\) to \\(b\\) is:', options: ['\\(\\displaystyle\\int_a^b(1+dy/dx)\\,dx\\)','\\(\\displaystyle\\int_a^b\\sqrt{1+(dy/dx)^2}\\,dx\\)','\\(\\displaystyle\\int_a^b(dy/dx)\\,dx\\)','\\(\\displaystyle\\int_a^b\\sqrt{(dy/dx)^2+x^2}\\,dx\\)'], answer: 1 },
      { q: 'The surface area when \\(y=f(x)\\) is rotated about the \\(x\\)-axis is:', options: ['\\(2\\pi\\displaystyle\\int y\\,dx\\)','\\(4\\pi\\displaystyle\\int y\\,dx\\)','\\(2\\pi\\displaystyle\\int y\\sqrt{1+(dy/dx)^2}\\,dx\\)','\\(\\pi\\displaystyle\\int y^2\\,dx\\)'], answer: 2 },
      { q: 'The mean value of \\(f(x)\\) over \\([a,b]\\) is:', options: ['\\(\\displaystyle\\int_a^b f(x)\\,dx\\)','\\(\\frac{f(a)+f(b)}{2}\\)','\\(\\frac{1}{2}\\displaystyle\\int_a^b f(x)\\,dx\\) (halved)','\\(\\frac{1}{b-a}\\displaystyle\\int_a^b f(x)\\,dx\\)'], answer: 3 },
      { q: '\\(\\displaystyle\\int\\frac{1}{\\sqrt{a^2-x^2}}\\,dx =\\)', options: ['\\(\\arcsin(x/a)+C\\)','\\(\\arctan(x/a)+C\\)','\\(-\\arcsin(x/a)+C\\)','\\(\\text{arccosh}(x/a)+C\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int\\frac{1}{a^2+x^2}\\,dx =\\)', options: ['\\(\\frac{x}{a^2}+C\\)','\\(\\frac{1}{a}\\arctan(x/a)+C\\)','\\(\\arctan(x/a)+C\\)','\\(\\frac{1}{a}\\arcsin(x/a)+C\\)'], answer: 1 },
      { q: 'An improper integral \\(\\displaystyle\\int_1^{\\infty}x^{-2}\\,dx\\):', options: ['Converges to \\(1/2\\)','Converges to \\(\\infty\\)','Converges to 1','Diverges'], answer: 2 },
      { q: 'An improper integral \\(\\displaystyle\\int_1^{\\infty}x^{-1}\\,dx\\):', options: ['Converges to 1','Converges to \\(\\ln 2\\)','Converges to 0','Diverges'], answer: 3 },
      { q: 'A reduction formula for \\(I_n\\) expresses it in terms of:', options: ['\\(I_{n-1}\\) or \\(I_{n-2}\\)','\\(I_{2n}\\)','\\(nI_1\\)','\\(I_0\\) only'], answer: 0 },
      { q: 'For \\(I_n=\\displaystyle\\int_0^{\\pi/2}\\sin^n x\\,dx\\), the reduction formula is \\(I_n=\\)', options: ['\\((n-1)I_{n-2}\\)','\\(\\frac{n-1}{n}I_{n-2}\\)','\\(\\frac{n}{n+1}I_{n-1}\\)','\\(\\frac{n-1}{n}I_{n-1}\\)'], answer: 1 },
      { q: '\\(\\displaystyle\\int_0^{\\pi/2}\\sin^2 x\\,dx=\\)', options: ['1','\\(1/2\\)','\\(\\pi/4\\)','\\(\\pi/2\\)'], answer: 2 },
      { q: 'Completing the square: \\(x^2+4x+13=\\)', options: ['\\((x+4)^2+9\\)','\\((x+2)^2-9\\)','\\((x+2)^2+4\\)','\\((x+2)^2+9\\)'], answer: 3 },
      { q: 'The \\(p\\)-test: \\(\\displaystyle\\int_1^{\\infty}x^{-p}\\,dx\\) converges iff:', options: ['\\(p>1\\)','\\(p<1\\)','\\(p>0\\)','\\(p\\neq 1\\)'], answer: 0 },
      { q: 'For the arc length in parametric form, the integrand is:', options: ['\\(|dy/dx|\\)','\\(\\sqrt{(dx/dt)^2+(dy/dt)^2}\\)','\\(\\sqrt{1+(dy/dt)^2}\\)','\\((dx/dt)^2+(dy/dt)^2\\)'], answer: 1 },
      { q: '\\(\\displaystyle\\int\\frac{dx}{\\sqrt{x^2+1}}=\\)', options: ['\\(\\arctan x+C\\)','\\(\\ln(x+1)+C\\)','\\(\\text{arcsinh}\\,x+C\\)','\\(\\text{arccosh}\\,x+C\\)'], answer: 2 },
      { q: 'The mean value of \\(f(x)=x^2\\) over \\([0,3]\\) is:', options: ['4','9','\\(9/4\\)','3'], answer: 3 },
      { q: 'Integration by parts reduces \\(\\displaystyle\\int x^n e^x\\,dx\\) using \\(I_n=\\)', options: ['\\(x^n e^x-nI_{n-1}\\)','\\(nx^{n-1}e^x\\)','\\(x^{n+1}e^x/(n+1)\\)','\\(e^x(x^n+n)\\)'], answer: 0 },
      { q: '\\(\\displaystyle\\int_0^1\\frac{1}{\\sqrt{1-x^2}}\\,dx=\\)', options: ['\\(\\pi/4\\)','\\(\\pi/2\\)','\\(\\pi\\)','1'], answer: 1 },
      { q: 'To evaluate \\(\\displaystyle\\int\\frac{dx}{(x+1)^2+4}\\):', options: ['Partial fractions','Integration by parts','Use \\(u=x+1\\) then \\(\\frac{1}{2}\\arctan\\frac{u}{2}+C\\)','Use \\(u=x^2+4\\)'], answer: 2 },
      { q: 'The surface area formula uses \\(y\\) because:', options: ['The length element is \\(y\\,dx\\)','\\(y\\) cancels out','It comes from the chain rule','The radius of each circular strip is \\(y\\)'], answer: 3 },
      { q: 'For \\(I_0=\\displaystyle\\int_0^{\\pi/2}\\sin^0 x\\,dx\\), \\(I_0=\\)', options: ['\\(\\pi/2\\)','0','1','\\(\\pi\\)'], answer: 0 },
    ],
    amber: [
      { q: 'Find the arc length of \\(y=x^{3/2}\\) from \\(x=0\\) to \\(x=4\\) (simplify \\(1+(3\\sqrt{x}/2)^2\\)).', options: ['\\(\\frac{4}{3}(10^{3/2}-1)\\) (no 8/27)','\\(\\frac{8}{27}(10\\sqrt{10}-1)\\)','\\(\\frac{2}{3}\\cdot 4^{3/2}\\)','\\(\\frac{8}{27}(5\\sqrt{5}-1)\\)'], answer: 1 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^2\\frac{1}{4+x^2}\\,dx\\).', options: ['\\(1/2\\)','\\(\\pi/2\\)','\\(\\pi/8\\)','\\(\\pi/4\\)'], answer: 2 },
      { q: 'Using the reduction formula \\(I_n=\\frac{n-1}{n}I_{n-2}\\), find \\(I_4=\\displaystyle\\int_0^{\\pi/2}\\sin^4 x\\,dx\\).', options: ['\\(\\pi/4\\) (half)','\\(3/8\\)','\\(\\pi/8\\)','\\(3\\pi/16\\)'], answer: 3 },
      { q: 'Determine whether \\(\\displaystyle\\int_0^1 x^{-1/2}\\,dx\\) converges.', options: ['Converges to 2','Diverges','Converges to 1','Converges to \\(1/2\\)'], answer: 0 },
      { q: 'Find the mean value of \\(\\sin x\\) over \\([0,\\pi]\\).', options: ['0','\\(2/\\pi\\)','\\(1/\\pi\\)','\\(\\pi/2\\)'], answer: 1 },
      { q: 'Using \\(I_n = x^n e^x - nI_{n-1}\\), find \\(\\displaystyle\\int x^2 e^x\\,dx\\).', options: ['\\(x^2e^x-2xe^x+C\\)','\\(e^x(x^2-2)+C\\)','\\(e^x(x^2-2x+2)+C\\)','\\(e^x(x^2+2x+2)+C\\)'], answer: 2 },
      { q: 'Find \\(\\displaystyle\\int\\frac{2}{9+x^2}\\,dx\\).', options: ['\\(\\frac{1}{3}\\arctan(x/3)+C\\)','\\(2\\arctan(x/9)+C\\)','\\(\\frac{2}{9}\\arctan x+C\\)','\\(\\frac{2}{3}\\arctan(x/3)+C\\)'], answer: 3 },
      { q: "Find \\(\\displaystyle\\int\\frac{1}{\\sqrt{9-x^2}}\\,dx\\).", options: ["\\(\\arcsin(x/3)+C\\)","\\(\\arctan(x/3)+C\\)","\\(\\frac{1}{3}\\arcsin x+C\\)","\\(\\arccos(x/3)+C\\)"], answer: 0 },
      { q: 'Use completing the square to evaluate \\(\\displaystyle\\int\\frac{dx}{x^2+6x+13}\\).', options: ['\\(\\ln(x^2+6x+13)+C\\)','\\(\\frac{1}{2}\\arctan\\frac{x+3}{2}+C\\)','\\(\\arctan(x+3)+C\\)','\\(\\frac{1}{4}\\arctan\\frac{x+3}{4}+C\\)'], answer: 1 },
      { q: "The surface area when \\(y=2\\sqrt{x}\\) (\\(0\\leq x\\leq 3\\)) is rotated about the \\(x\\)-axis is:", options: ["\\(2\\pi\\displaystyle\\int_0^3 \\sqrt{x}\\,dx\\)","\\(2\\pi\\displaystyle\\int_0^3 \\sqrt{x+1}\\,dx\\)","\\(2\\pi\\displaystyle\\int_0^3 2\\sqrt{x}\\sqrt{1+1/x}\\,dx\\)","\\(\\pi\\displaystyle\\int_0^3 4x\\,dx\\)"], answer: 2 },
      { q: 'Derive the reduction formula for \\(\\displaystyle\\int\\cos^n x\\,dx\\). It is \\(I_n=\\)', options: ['\\(\\frac{n-1}{n}I_{n-2}\\) (definite over \\([0,\\pi/2]\\))','\\(\\sin x\\cos^{n-1}x+(n-1)I_{n-2}\\)','\\(\\frac{1}{n}I_{n-1}\\)','\\(\\frac{\\cos^{n-1}x\\sin x}{n}+\\frac{n-1}{n}I_{n-2}\\)'], answer: 3 },
      { q: 'Find the arc length of the parametric curve \\(x=3t^2\\), \\(y=2t^3\\) from \\(t=0\\) to \\(t=1\\).', options: ['\\(2(2\\sqrt{2}-1)\\)','\\(\\sqrt{13}\\)','\\(2\\sqrt{2}\\)','3'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_1^{\\infty}\\frac{1}{x^3}\\,dx\\).', options: ['\\(1/3\\)','\\(1/2\\)','1','\\(\\infty\\)'], answer: 1 },
      { q: 'Use partial fractions to find \\(\\displaystyle\\int\\frac{1}{(x-1)(x+3)}\\,dx\\).', options: ['\\(\\ln|x^2+2x-3|+C\\)','\\(\\frac{1}{4}\\ln|(x-1)(x+3)|+C\\)','\\(\\frac{1}{4}\\ln\\left|\\frac{x-1}{x+3}\\right|+C\\)','\\(\\frac{1}{4}\\ln|x-1|+\\ln|x+3|+C\\)'], answer: 2 },
      { q: 'The reduction formula \\(I_n=\\frac{n-1}{n}I_{n-2}\\) gives \\(I_5=\\displaystyle\\int_0^{\\pi/2}\\sin^5 x\\,dx=\\)', options: ['\\(3\\pi/16\\)','\\(4/15\\)','\\(16/15\\)','\\(8/15\\)'], answer: 3 },
      { q: 'For the mean value of \\(f(x)=e^x\\) over \\([0,2]\\):', options: ['\\(\\frac{e^2-1}{2}\\)','\\(e^2-1\\)','\\(e^2/2\\)','\\(e-1\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^{\\infty} e^{-x}\\,dx\\).', options: ['\\(e\\)','1','0','\\(\\infty\\)'], answer: 1 },
      { q: 'Find \\(\\displaystyle\\int\\frac{x}{x^2+4}\\,dx\\).', options: ['\\(\\frac{1}{2}\\arctan(x/2)+C\\)','\\(\\frac{x^2}{2(x^2+4)}+C\\)','\\(\\frac{1}{2}\\ln(x^2+4)+C\\)','\\(\\ln(x^2+4)+C\\)'], answer: 2 },
      { q: 'The surface area formula \\(2\\pi\\int y\\,ds\\) requires \\(ds\\) to be:', options: ['\\(dy\\)','\\(dx\\)','\\(\\sqrt{dx^2+dy^2}\\)','\\(\\sqrt{1+(dy/dx)^2}\\,dx\\)'], answer: 3 },
    ],
    red: [
      { q: 'Find the arc length of \\(y=\\cosh x\\) from \\(x=0\\) to \\(x=1\\).', options: ['\\(\\sinh 1\\)','1','\\(\\cosh 1\\)','\\(\\cosh 1-1\\)'], answer: 0 },
      { q: 'Use the reduction formula to find \\(\\displaystyle\\int_0^{\\pi/2}\\sin^6 x\\,dx\\).', options: ['\\(5/16\\)','\\(5\\pi/32\\)','\\(\\pi/4\\)','\\(3\\pi/16\\)'], answer: 1 },
      { q: 'The improper integral \\(\\displaystyle\\int_0^1\\ln x\\,dx\\) equals:', options: ['\\(-\\ln 1\\)','1','\\(-1\\)','0'], answer: 2 },
      { q: 'For large \\(n\\), \\(\\displaystyle\\int_0^{\\pi/2}\\sin^n x\\,dx\\) behaves like:', options: ['\\(1/n\\)','\\(2/n\\)','\\(\\pi/n\\)','\\(\\sqrt{\\pi/(2n)}\\) (Stirling)'], answer: 3 },
      { q: 'The value of \\(\\displaystyle\\int_0^{\\infty}\\frac{1}{1+x^2}\\,dx\\) is:', options: ['\\(\\pi/2\\)','\\(\\pi/4\\)','1','\\(\\pi\\)'], answer: 0 },
      { q: 'Show the mean value of \\(\\cos^2 x\\) over \\([0,\\pi]\\) is:', options: ['1','\\(1/2\\)','0','\\(\\pi/2\\)'], answer: 1 },
      { q: 'Derive the reduction formula for \\(\\displaystyle\\int_0^{\\pi/2}\\cos^n x\\,dx\\): it equals the same formula as for \\(\\sin^n x\\) because:', options: ['The limits force equality','The functions are equal','By the substitution \\(x=\\pi/2-u\\), which swaps \\(\\sin\\) and \\(\\cos\\)','Integration by parts gives the same result'], answer: 2 },
      { q: 'Determine whether \\(\\displaystyle\\int_1^{\\infty}\\frac{x}{x^2+1}\\,dx\\) converges.', options: ['Converges to \\(\\pi/2\\)','Converges to \\(\\frac{1}{2}\\ln 2\\)','Converges to 1','Diverges (behaves like \\(1/x\\))'], answer: 3 },
      { q: 'The arc length formula can be derived from:', options: ['Summing \\(\\sqrt{(\\Delta x)^2+(\\Delta y)^2}\\) and taking the limit','The surface area formula divided by \\(2\\pi\\)','\\(\\int y\\,dx\\)','\\(\\int (1+y^2)\\,dx\\)'], answer: 0 },
      { q: 'Evaluate \\(\\displaystyle\\int_0^{\\infty} x e^{-x}\\,dx\\) using the reduction formula \\(I_n = n\\cdot I_{n-1}\\) (where \\(I_n=\\int_0^{\\infty}x^n e^{-x}\\,dx=n!\\)).', options: ['\\(1/e\\)','1','\\(e\\)','\\(\\infty\\)'], answer: 1 },
    ],
  },

  '1.6': {
    name: 'Further Vectors',
    green: [
      { q: 'The dot product \\(\\mathbf{a}\\cdot\\mathbf{b}=\\)', options: ['\\(|\\mathbf{a}|+|\\mathbf{b}|\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\tan\\theta\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\cos\\theta\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\sin\\theta\\)'], answer: 2 },
      { q: '\\(\\mathbf{a}\\cdot\\mathbf{b}=0\\) implies:', options: ['\\(\\mathbf{a}\\parallel\\mathbf{b}\\)','\\(|\\mathbf{a}|=|\\mathbf{b}|\\)','\\(\\mathbf{a}=-\\mathbf{b}\\)','\\(\\mathbf{a}\\perp\\mathbf{b}\\)'], answer: 3 },
      { q: 'The magnitude of the cross product \\(|\\mathbf{a}\\times\\mathbf{b}|=\\)', options: ['\\(|\\mathbf{a}||\\mathbf{b}|\\sin\\theta\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\cos\\theta\\)','\\(|\\mathbf{a}|\\cdot|\\mathbf{b}|\\)','\\(|\\mathbf{a}|+|\\mathbf{b}|\\)'], answer: 0 },
      { q: '\\(\\mathbf{a}\\times\\mathbf{b}=\\mathbf{0}\\) implies:', options: ['\\(\\mathbf{a}=-\\mathbf{b}\\)','\\(\\mathbf{a}\\parallel\\mathbf{b}\\) (or one is zero)','\\(\\mathbf{a}\\perp\\mathbf{b}\\)','\\(\\mathbf{a}=\\mathbf{b}\\)'], answer: 1 },
      { q: '\\(\\mathbf{a}\\times\\mathbf{b}=\\)', options: ['\\(|\\mathbf{a}||\\mathbf{b}|\\)','\\(\\mathbf{a}\\cdot\\mathbf{b}\\)','\\(-\\mathbf{b}\\times\\mathbf{a}\\)','\\(\\mathbf{b}\\times\\mathbf{a}\\)'], answer: 2 },
      { q: 'The area of a parallelogram with sides \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) is:', options: ['\\(\\mathbf{a}\\cdot\\mathbf{b}\\)','\\(|\\mathbf{a}||\\mathbf{b}|\\)','\\(\\frac{1}{2}|\\mathbf{a}||\\mathbf{b}|\\)','\\(|\\mathbf{a}\\times\\mathbf{b}|\\)'], answer: 3 },
      { q: 'The area of a triangle with sides \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) is:', options: ['\\(\\frac{1}{2}|\\mathbf{a}\\times\\mathbf{b}|\\)','\\(|\\mathbf{a}\\times\\mathbf{b}|\\)','\\(\\frac{1}{2}\\mathbf{a}\\cdot\\mathbf{b}\\)','\\(|\\mathbf{a}|\\cdot|\\mathbf{b}|\\)'], answer: 0 },
      { q: 'The equation of a line in vector form is:', options: ['\\(\\mathbf{r}=\\mathbf{a}+\\mathbf{b}\\)','\\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}\\)','\\(\\mathbf{r}\\cdot\\mathbf{n}=d\\)','\\(\\mathbf{r}=\\lambda\\mathbf{n}\\)'], answer: 1 },
      { q: 'The equation of a plane in vector form is:', options: ['\\(\\mathbf{r}=\\lambda\\mathbf{a}+\\mu\\mathbf{b}\\)','\\(\\mathbf{r}\\times\\mathbf{n}=0\\)','\\(\\mathbf{r}\\cdot\\mathbf{n}=d\\)','\\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}\\)'], answer: 2 },
      { q: 'The scalar triple product \\(\\mathbf{a}\\cdot(\\mathbf{b}\\times\\mathbf{c})\\) gives:', options: ['The area of a face','The length of \\(\\mathbf{a}\\)','\\(|\\mathbf{a}||\\mathbf{b}||\\mathbf{c}|\\)','The volume of a parallelepiped'], answer: 3 },
      { q: 'Vectors \\(\\mathbf{a},\\mathbf{b},\\mathbf{c}\\) are coplanar iff:', options: ['\\(\\mathbf{a}\\cdot(\\mathbf{b}\\times\\mathbf{c})=0\\)','\\(\\mathbf{a}\\times\\mathbf{b}=\\mathbf{c}\\)','\\(\\mathbf{a}=\\mathbf{b}+\\mathbf{c}\\)','Their magnitudes are equal'], answer: 0 },
      { q: 'The angle \\(\\theta\\) between lines with directions \\(\\mathbf{d}_1\\), \\(\\mathbf{d}_2\\) satisfies:', options: ['\\(\\cos\\theta=\\frac{\\mathbf{d}_1\\times\\mathbf{d}_2}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(\\cos\\theta=\\frac{|\\mathbf{d}_1\\cdot\\mathbf{d}_2|}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(\\sin\\theta=\\frac{\\mathbf{d}_1\\cdot\\mathbf{d}_2}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(\\tan\\theta=\\frac{|\\mathbf{d}_1\\times\\mathbf{d}_2|}{\\mathbf{d}_1\\cdot\\mathbf{d}_2}\\)'], answer: 1 },
      { q: '\\(\\mathbf{i}\\times\\mathbf{j}=\\)', options: ['\\(\\mathbf{i}\\)','\\(\\mathbf{0}\\)','\\(\\mathbf{k}\\)','\\(-\\mathbf{k}\\)'], answer: 2 },
      { q: 'The distance from point \\(P\\) to plane \\(ax+by+cz=d\\) is:', options: ['\\(|ax_0+by_0+cz_0-d|\\)','\\(\\frac{d}{\\sqrt{a^2+b^2+c^2}}\\)','\\(|\\mathbf{OP}|\\)','\\(\\frac{|ax_0+by_0+cz_0-d|}{\\sqrt{a^2+b^2+c^2}}\\)'], answer: 3 },
      { q: 'Two lines in 3D that neither intersect nor are parallel are called:', options: ['Skew','Perpendicular','Coplanar','Tangent'], answer: 0 },
      { q: 'The normal to the plane \\(2x+3y-z=5\\) is:', options: ['\\(\\begin{pmatrix}-2\\\\-3\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}2\\\\3\\\\-1\\end{pmatrix}\\)','\\(\\begin{pmatrix}5\\\\0\\\\0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}\\)'], answer: 1 },
      { q: 'To find the angle between a line and a plane, use:', options: ['\\(\\cos\\phi=\\frac{|\\mathbf{d}\\times\\mathbf{n}|}{|\\mathbf{d}||\\mathbf{n}|}\\)','\\(\\tan\\phi=\\frac{|\\mathbf{d}|}{|\\mathbf{n}|}\\)','\\(\\sin\\phi=\\frac{|\\mathbf{d}\\cdot\\mathbf{n}|}{|\\mathbf{d}||\\mathbf{n}|}\\)','\\(\\cos\\phi=\\frac{\\mathbf{d}\\cdot\\mathbf{n}}{|\\mathbf{d}||\\mathbf{n}|}\\)'], answer: 2 },
      { q: '\\(\\mathbf{a}\\times\\mathbf{a}=\\)', options: ['\\(|\\mathbf{a}|^2\\)','\\(\\mathbf{a}\\)','1','\\(\\mathbf{0}\\)'], answer: 3 },
      { q: 'The Cartesian symmetric form of the line through \\((1,2,3)\\) with direction \\(\\begin{pmatrix}4\\\\5\\\\6\\end{pmatrix}\\) is:', options: ['\\(\\frac{x-1}{4}=\\frac{y-2}{5}=\\frac{z-3}{6}\\)','\\(\\frac{x}{1}=\\frac{y}{2}=\\frac{z}{3}\\)','\\(\\frac{x+1}{4}=\\frac{y+2}{5}=\\frac{z+3}{6}\\)','\\(4x+5y+6z=1\\)'], answer: 0 },
      { q: 'The scalar triple product equals the \\(3\\times 3\\) determinant with:', options: ['The cross product on the diagonal','Rows \\(\\mathbf{a},\\mathbf{b},\\mathbf{c}\\)','Columns \\(\\mathbf{a}\\times\\mathbf{b},\\mathbf{b}\\times\\mathbf{c},\\mathbf{c}\\times\\mathbf{a}\\)','Diagonal entries only'], answer: 1 },
    ],
    amber: [
      { q: 'Find \\(\\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}\\times\\begin{pmatrix}4\\\\5\\\\6\\end{pmatrix}\\).', options: ['\\(\\begin{pmatrix}12\\\\10\\\\18\\end{pmatrix}\\)','\\(\\begin{pmatrix}-3\\\\-6\\\\-3\\end{pmatrix}\\)','\\(\\begin{pmatrix}-3\\\\6\\\\-3\\end{pmatrix}\\)','\\(\\begin{pmatrix}3\\\\-6\\\\3\\end{pmatrix}\\)'], answer: 2 },
      { q: "Find the distance from \\((1,2,3)\\) to the plane \\(2x+y-2z=5\\).", options: ["\\(7/9\\)","\\(4/3\\)","\\(2/3\\)","\\(7/3\\)"], answer: 3 },
      { q: 'Find the angle between the planes \\(x+y+z=1\\) and \\(x-y+z=2\\).', options: ['\\(\\arccos(1/3)\\)','\\(\\arccos(2/3)\\)','\\(60°\\)','\\(90°\\)'], answer: 0 },
      { q: 'Lines \\(\\ell_1:\\mathbf{r}=\\begin{pmatrix}1\\\\0\\\\0\\end{pmatrix}+\\lambda\\begin{pmatrix}1\\\\1\\\\0\\end{pmatrix}\\) and \\(\\ell_2:\\mathbf{r}=\\begin{pmatrix}0\\\\1\\\\0\\end{pmatrix}+\\mu\\begin{pmatrix}0\\\\1\\\\1\\end{pmatrix}\\) — do they intersect?', options: ['Yes, at \\((1,1,0)\\) when \\(\\lambda=0,\\mu=0\\)','No, they are skew','No, they are parallel','Yes, at the origin'], answer: 1 },
      { q: 'Find the equation of the plane through \\((1,0,0)\\), \\((0,1,0)\\), \\((0,0,1)\\).', options: ['\\(x-y+z=1\\)','\\(x+y-z=1\\)','\\(x+y+z=1\\)','\\(x+y+z=0\\)'], answer: 2 },
      { q: 'The volume of the parallelepiped with edges \\(\\mathbf{i}+\\mathbf{j}\\), \\(\\mathbf{j}+\\mathbf{k}\\), \\(\\mathbf{i}+\\mathbf{k}\\) is:', options: ['1','\\(\\sqrt{2}\\)','4','2'], answer: 3 },
      { q: 'Find the shortest distance between skew lines \\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}_1\\) and \\(\\mathbf{r}=\\mathbf{b}+\\mu\\mathbf{d}_2\\) using:', options: ['\\(\\frac{|(\\mathbf{b}-\\mathbf{a})\\cdot(\\mathbf{d}_1\\times\\mathbf{d}_2)|}{|\\mathbf{d}_1\\times\\mathbf{d}_2|}\\)','\\(|\\mathbf{b}-\\mathbf{a}|\\)','\\(\\frac{|\\mathbf{d}_1\\cdot\\mathbf{d}_2|}{|\\mathbf{d}_1||\\mathbf{d}_2|}\\)','\\(|(\\mathbf{b}-\\mathbf{a})\\times\\mathbf{d}_1|\\)'], answer: 0 },
      { q: 'The intersection of the plane \\(\\mathbf{r}\\cdot\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}=3\\) with the line \\(\\mathbf{r}=\\begin{pmatrix}0\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}\\) occurs at \\(t=\\)', options: ['0','1','3','\\(1/3\\)'], answer: 1 },
      { q: 'If \\(\\mathbf{a}=(1,2,3)\\) and \\(\\mathbf{b}=(2,0,1)\\), find \\(\\mathbf{a}\\cdot\\mathbf{b}\\).', options: ['7','\\(-5\\)','5','4'], answer: 2 },
      { q: 'Three planes meet in a unique point iff:', options: ['\\(\\det(A)=0\\)','All normals are parallel','Any two planes are parallel','\\(\\det(A)\\neq 0\\) where \\(A\\) is the coefficient matrix'], answer: 3 },
      { q: 'The angle between the line \\(\\mathbf{r}=\\begin{pmatrix}0\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\0\\\\1\\end{pmatrix}\\) and the plane \\(z=0\\) is:', options: ['\\(45°\\)','\\(90°\\)','\\(30°\\)','\\(60°\\)'], answer: 0 },
      { q: 'The cross product \\(\\mathbf{a}\\times\\mathbf{b}\\) is perpendicular to:', options: ['Neither','Both \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\)','\\(\\mathbf{a}\\) only, not \\(\\mathbf{b}\\)','\\(\\mathbf{b}\\) only'], answer: 1 },
      { q: 'The area of the triangle with vertices \\(A(1,0,0)\\), \\(B(0,1,0)\\), \\(C(0,0,1)\\) is:', options: ['\\(\\sqrt{3}\\)','1','\\(\\frac{\\sqrt{3}}{2}\\)','\\(\\frac{1}{2}\\) (half base)'], answer: 2 },
      { q: 'A plane contains the line \\(\\mathbf{r}=\\mathbf{a}+\\lambda\\mathbf{d}\\) iff the normal \\(\\mathbf{n}\\) satisfies:', options: ['\\(\\mathbf{n}=\\mathbf{d}\\)','\\(\\mathbf{n}\\cdot\\mathbf{a}=0\\)','\\(\\mathbf{n}\\times\\mathbf{d}=\\mathbf{0}\\)','\\(\\mathbf{n}\\cdot\\mathbf{d}=0\\) and \\(\\mathbf{n}\\cdot\\mathbf{a}=d\\)'], answer: 3 },
      { q: 'To find the line of intersection of two planes, compute:', options: ['The cross product of their normals (direction) and a point on both','Their dot product','The sum of their normal equations','The difference of their equations'], answer: 0 },
      { q: 'For the line \\(\\frac{x-1}{2}=\\frac{y+1}{3}=\\frac{z}{1}\\), the direction vector is:', options: ['\\(\\begin{pmatrix}2\\\\-3\\\\0\\end{pmatrix}\\)','\\(\\begin{pmatrix}2\\\\3\\\\1\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\-1\\\\0\\end{pmatrix}\\)','\\(\\begin{pmatrix}1\\\\2\\\\3\\end{pmatrix}\\)'], answer: 1 },
      { q: "Find \\(\\begin{pmatrix}2\\\\1\\\\0\\end{pmatrix}\\cdot\\left(\\begin{pmatrix}1\\\\0\\\\1\\end{pmatrix}\\times\\begin{pmatrix}0\\\\1\\\\1\\end{pmatrix}\\right)\\).", options: ["\\(-1\\)","0","\\(-3\\)","3"], answer: 2 },
      { q: "The distance between the parallel planes \\(x+y+z=1\\) and \\(x+y+z=4\\) is:", options: ["3","1","\\(5/\\sqrt{3}\\)","\\(\\sqrt{3}\\)"], answer: 3 },
      { q: 'Two lines intersect if and only if they are:', options: ['Coplanar and not parallel','Parallel','Skew','Perpendicular to each other'], answer: 0 },
    ],
    red: [
      { q: "Show that the lines \\(\\mathbf{r}=(1+t,2+t,t)\\) and \\(\\mathbf{r}=(2+s,3+2s,2+s)\\) are skew. The key test is:", options: ["Their dot product equals zero","\\(\\det(\\mathbf{b}-\\mathbf{a},\\mathbf{d}_1,\\mathbf{d}_2)\\neq 0\\)","\\(\\mathbf{d}_1=\\mathbf{d}_2\\)","The normals are perpendicular"], answer: 1 },
      { q: 'For three planes with \\(\\det A=0\\) and consistent equations, the solution is:', options: ['A unique point','Two discrete points where the three planes cross','A line or plane (infinitely many solutions)','No solution'], answer: 2 },
      { q: "The distance from \\((0,0,0)\\) to the plane \\(3x+4y+0z=10\\) is:", options: ["10","\\(10/7\\)","\\(2/5\\)","2"], answer: 3 },
      { q: 'If \\(\\mathbf{a}\\times\\mathbf{b}=\\mathbf{c}\\) and \\(\\mathbf{a}\\times\\mathbf{d}=\\mathbf{c}\\), then:', options: ['\\(\\mathbf{b}-\\mathbf{d}\\) is parallel to \\(\\mathbf{a}\\)','\\(\\mathbf{b}+\\mathbf{d}=2\\mathbf{c}\\), so \\(\\mathbf{b}=\\mathbf{d}\\)','\\(\\mathbf{c}=\\mathbf{0}\\)','\\(\\mathbf{b}=\\mathbf{d}\\)'], answer: 0 },
      { q: 'The foot of the perpendicular from \\(P=(1,2,3)\\) to the plane \\(x+y+z=0\\) is:', options: ['\\((-2,-1,0)\\)','\\((-1,0,1)\\)','\\((1,2,3)/3\\)','\\((0,0,0)\\)'], answer: 1 },
      { q: 'Three planes \\(x+y=1\\), \\(y+z=1\\), \\(x+z=1\\) intersect in:', options: ['No solution','A line','The unique point \\((\\frac{1}{2},\\frac{1}{2},\\frac{1}{2})\\)','Two points'], answer: 2 },
      { q: 'If \\(|\\mathbf{a}\\times\\mathbf{b}|=|\\mathbf{a}\\cdot\\mathbf{b}|\\), then the angle between \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) satisfies:', options: ['\\(\\theta=0\\)','\\(\\theta=\\pi/2\\)','\\(\\sin\\theta=1\\), so \\(\\theta=\\pi/2\\) exactly here','\\(\\sin\\theta=\\cos\\theta\\), so \\(\\theta=\\pi/4\\)'], answer: 3 },
      { q: 'A student finds the line of intersection of two planes and gets \\(\\mathbf{r}=\\begin{pmatrix}1\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\1\\\\0\\end{pmatrix}\\). To verify, they should:', options: ['Substitute into both plane equations and confirm they hold for all \\(t\\)','Check the point \\((1,0,0)\\) only','Compute the cross product of the normals','Find the determinant'], answer: 0 },
      { q: 'For a tetrahedron with one vertex at \\(O\\) and adjacent vertices at \\(A\\), \\(B\\), \\(C\\), its volume is:', options: ['\\(|\\overrightarrow{OA}\\times\\overrightarrow{OB}|\\)','\\(\\frac{1}{6}|\\overrightarrow{OA}\\cdot(\\overrightarrow{OB}\\times\\overrightarrow{OC})|\\)','\\(\\frac{1}{2}|\\overrightarrow{OA}\\cdot(\\overrightarrow{OB}\\times\\overrightarrow{OC})|\\)','\\(\\frac{1}{3}|\\overrightarrow{OA}||\\overrightarrow{OB}||\\overrightarrow{OC}|\\)'], answer: 1 },
      { q: 'Two planes with normals \\(\\mathbf{n}_1\\) and \\(\\mathbf{n}_2\\) are perpendicular iff:', options: ['\\(|\\mathbf{n}_1|=|\\mathbf{n}_2|\\)','\\(\\mathbf{n}_1=\\mathbf{n}_2\\)','\\(\\mathbf{n}_1\\cdot\\mathbf{n}_2=0\\)','\\(\\mathbf{n}_1\\times\\mathbf{n}_2=\\mathbf{0}\\)'], answer: 2 },
    ],
  },

  '1.7': {
    name: 'Polar Coordinates',
    green: [
      { q: 'The conversion \\(x=\\)', options: ['\\(r\\sin\\theta\\)','\\(r/\\cos\\theta\\)','\\(r\\tan\\theta\\)','\\(r\\cos\\theta\\)'], answer: 3 },
      { q: 'The conversion \\(y=\\)', options: ['\\(r\\sin\\theta\\)','\\(r\\cos\\theta\\)','\\(r/\\sin\\theta\\)','\\(r\\cot\\theta\\)'], answer: 0 },
      { q: '\\(r^2=\\)', options: ['\\((x+y)^2\\)','\\(x^2+y^2\\)','\\(x^2-y^2\\)','\\(xy\\)'], answer: 1 },
      { q: 'The polar equation \\(r=a\\) represents:', options: ['A parabola','A spiral','A circle centre \\(O\\) radius \\(a\\)','A straight line'], answer: 2 },
      { q: 'The polar area formula is:', options: ['\\(\\displaystyle\\int r\\,d\\theta\\)','\\(\\frac{1}{2}\\displaystyle\\int r\\,d\\theta\\) (radians)','\\(\\displaystyle\\int r^2\\,d\\theta\\)','\\(\\frac{1}{2}\\displaystyle\\int r^2\\,d\\theta\\)'], answer: 3 },
      { q: 'The cardioid \\(r=a(1+\\cos\\theta)\\) passes through the origin at \\(\\theta=\\)', options: ['\\(\\pi\\)','0','\\(\\pi/2\\)','\\(2\\pi\\)'], answer: 0 },
      { q: 'The maximum value of \\(r\\) for \\(r=3(1+\\cos\\theta)\\) is:', options: ['\\(3\\sqrt{2}\\)','6','3','9'], answer: 1 },
      { q: 'A curve with equation \\(r=\\cos(2\\theta)\\) (rose curve) has how many petals?', options: ['8','1','4','2'], answer: 2 },
      { q: 'The lemniscate \\(r^2=a^2\\cos(2\\theta)\\) exists only when:', options: ['\\(r\\geq 0\\)','\\(\\theta\\in[0,\\pi]\\)','\\(r=a\\)','\\(\\cos(2\\theta)\\geq 0\\)'], answer: 3 },
      { q: 'To find \\(dy/dx\\) for a polar curve, use:', options: ['\\(\\frac{dy/d\\theta}{dx/d\\theta}\\)','\\(dr/d\\theta\\)','\\(r/\\theta\\)','\\(dr/dx\\)'], answer: 0 },
      { q: 'The Archimedean spiral \\(r=a\\theta\\) has what kind of spacing?', options: ['Random spacing','Uniform spacing between turns','Exponentially increasing spacing','Decreasing spacing'], answer: 1 },
      { q: '\\(\\tan\\theta = \\)', options: ['\\(r/x\\)','\\(x/r\\)','\\(y/x\\)','\\(x/y\\)'], answer: 2 },
      { q: 'The polar curve \\(r=a\\cos\\theta\\) is a:', options: ['Cardioid','Spiral','Rose curve','Circle with diameter on initial line'], answer: 3 },
      { q: 'When computing the area enclosed by \\(r=f(\\theta)\\) for \\(\\alpha\\leq\\theta\\leq\\beta\\), we integrate:', options: ['\\(\\frac{1}{2}\\int_\\alpha^\\beta r^2\\,d\\theta\\)','\\(\\int_\\alpha^\\beta r\\,d\\theta\\)','\\(\\pi\\int_\\alpha^\\beta r^2\\,d\\theta\\)','\\(\\int_\\alpha^\\beta r^2\\,d\\theta\\)'], answer: 0 },
      { q: 'For a rose curve \\(r=a\\cos(n\\theta)\\), if \\(n=3\\) there are:', options: ['1 petal','3 petals','6 petals','9 petals'], answer: 1 },
      { q: 'The Cartesian equation of \\(r=2\\sin\\theta\\) is:', options: ['\\((x-1)^2+y^2=1\\)','\\(y=2x\\)','\\(x^2+(y-1)^2=1\\)','\\(x^2+y^2=4\\)'], answer: 2 },
      { q: 'The curve \\(r=a(1-\\cos\\theta)\\) is symmetric about:', options: ['The \\(y\\)-axis','The origin','No axis','The initial line (\\(x\\)-axis)'], answer: 3 },
      { q: 'The area enclosed by the curve \\(r^2=a^2\\cos 2\\theta\\) (one loop) requires limits:', options: ['\\(-\\pi/4\\) to \\(\\pi/4\\)','\\(0\\) to \\(\\pi/2\\)','\\(0\\) to \\(2\\pi\\)','\\(-\\pi/2\\) to \\(\\pi/2\\)'], answer: 0 },
      { q: 'For \\(r=f(\\theta)\\), \\(dx/d\\theta=\\)', options: ['\\(r\\cos\\theta\\)','\\(\\frac{dr}{d\\theta}\\cos\\theta - r\\sin\\theta\\)','\\(\\frac{dr}{d\\theta}\\sin\\theta + r\\cos\\theta\\)','\\(-r\\sin\\theta\\)'], answer: 1 },
      { q: 'The polar curve \\(r=a\\sec\\theta\\) in Cartesian form is:', options: ['\\(x^2+y^2=a^2\\)','\\(y=ax\\)','\\(x=a\\)','\\(y=a\\)'], answer: 2 },
    ],
    amber: [
      { q: 'Find the total area enclosed by \\(r=2a\\cos\\theta\\).', options: ['\\(2\\pi a^2\\)','\\(4\\pi a^2\\)','\\(\\pi a^2/2\\)','\\(\\pi a^2\\)'], answer: 3 },
      { q: 'Find the total area enclosed by the cardioid \\(r=2(1+\\cos\\theta)\\).', options: ['\\(6\\pi\\)','\\(4\\pi\\)','\\(8\\pi\\)','\\(3\\pi\\)'], answer: 0 },
      { q: 'Find the area of one loop of \\(r=a\\cos(2\\theta)\\).', options: ['\\(\\pi a^2\\)','\\(\\pi a^2/8\\)','\\(\\pi a^2/4\\)','\\(\\pi a^2/2\\)'], answer: 1 },
      { q: 'Convert \\(r=\\frac{4}{1+\\cos\\theta}\\) to Cartesian form.', options: ['\\(y=4/(x+1)\\)', '\\(x^2+y^2=4x\\), a circle through the pole','\\(y^2=-8(x-2)\\), a parabola','\\(x^2+y^2=16\\)'], answer: 2 },
      { q: 'Find the gradient \\(dy/dx\\) at \\(\\theta=\\pi/2\\) for \\(r=a(1+\\cos\\theta)\\).', options: ['\\(-1\\)','0 (horizontal tangent)','\\(\\infty\\) (vertical tangent)','1'], answer: 3 },
      { q: 'The area between the circles \\(r=2\\) and \\(r=4\\sin\\theta\\) for \\(\\pi/6\\leq\\theta\\leq 5\\pi/6\\) requires:', options: ['\\(\\frac{1}{2}\\int(16\\sin^2\\theta-4)\\,d\\theta\\)','\\(\\frac{1}{2}\\int(4-16\\sin^2\\theta)\\,d\\theta\\)','\\(\\int(4\\sin\\theta-2)\\,d\\theta\\)','\\(\\int(4\\sin^2\\theta-1)\\,d\\theta\\)'], answer: 0 },
      { q: "Find the Cartesian equation of \\(r^2=4\\cos(2\\theta)\\).", options: ["\\(xy=2\\)","\\((x^2+y^2)^2=4(x^2-y^2)\\)","\\(x^2+y^2=4\\)","\\(x^2-y^2=4\\)"], answer: 1 },
      { q: 'A curve is symmetric about the line \\(\\theta=\\pi/2\\) iff:', options: ['\\(f(\\theta+\\pi)=f(\\theta)\\)','\\(f(2\\pi-\\theta)=f(\\theta)\\)','\\(f(\\pi-\\theta)=f(\\theta)\\)','\\(f(-\\theta)=f(\\theta)\\)'], answer: 2 },
      { q: 'Find the area enclosed between \\(r=1\\) and \\(r=2\\sin\\theta\\) that is inside \\(r=2\\sin\\theta\\) and outside \\(r=1\\).', options: ['\\(\\pi-\\sqrt{3}\\)','\\(\\pi/2\\)','\\(4\\pi/3\\)','\\(\\frac{\\pi}{3}+\\frac{\\sqrt{3}}{2}\\) (approximately, using limits \\(\\pi/6\\) to \\(5\\pi/6\\))'], answer: 3 },
      { q: 'The tangent to \\(r=a\\theta\\) at \\(\\theta=\\pi\\) has gradient:', options: ['\\(\\pi\\)','\\(1\\)','0','\\(\\frac{-\\pi\\cos\\pi-\\sin\\pi}{\\pi(-\\sin\\pi)+\\cos\\pi}=\\frac{\\pi}{-1}=-\\pi\\) (approximately)'], answer: 0 },
      { q: "For the lemniscate \\(r^2=4\\cos(2\\theta)\\), the maximum value of \\(r\\) is:", options: ["\\(2\\sqrt{2}\\)","2","4","\\(\\sqrt{2}\\)"], answer: 1 },
      { q: 'Identify the polar curve \\(r=3+2\\cos\\theta\\): it is a:', options: ['Lemniscate','Circle','Limaçon without inner loop (\\(a>b\\))','Cardioid'], answer: 2 },
      { q: 'Find the area of the region inside \\(r=3\\cos\\theta\\) and outside \\(r=1+\\cos\\theta\\).', options: ['\\(2\\pi\\)','\\(4\\pi\\)','\\(\\pi/2\\)','\\(\\pi\\)'], answer: 3 },
      { q: 'For \\(r=1+2\\cos\\theta\\) (limaçon with inner loop), the inner loop exists where \\(r<0\\), i.e.:', options: ['\\(2\\pi/3<\\theta<4\\pi/3\\)','\\(0<\\theta<\\pi/3\\) and \\(5\\pi/3<\\theta<2\\pi\\)','\\(\\pi/2<\\theta<\\pi\\)','Never'], answer: 0 },
      { q: 'To find where two polar curves intersect, you solve \\(r_1(\\theta)=r_2(\\theta)\\) AND check:', options: ['Only \\(\\theta\\in[0,\\pi]\\)','For intersections at the pole and \\(r=0\\) separately','Only the algebraic solutions of the equation in \\(\\theta\\)','All \\(\\theta\\in[0,2\\pi)\\)'], answer: 1 },
      { q: 'The length of the polar curve \\(r=f(\\theta)\\) from \\(\\alpha\\) to \\(\\beta\\) is:', options: ['\\(\\displaystyle\\int_\\alpha^\\beta\\sqrt{r+(dr/d\\theta)^2}\\,d\\theta\\) (no square)','\\(\\displaystyle\\int_\\alpha^\\beta r^2\\,d\\theta\\)','\\(\\displaystyle\\int_\\alpha^\\beta\\sqrt{r^2+(dr/d\\theta)^2}\\,d\\theta\\)','\\(\\displaystyle\\int_\\alpha^\\beta r\\,d\\theta\\)'], answer: 2 },
      { q: 'Find \\(dy/dx\\) for \\(r=2\\) at any \\(\\theta\\).', options: ['\\(\\tan\\theta\\)','\\(-\\tan\\theta\\)','\\(\\cot\\theta\\)','\\(-\\cot\\theta\\)'], answer: 3 },
      { q: 'The area of the cardioid \\(r=a(1-\\cos\\theta)\\) is:', options: ['\\(3\\pi a^2/2\\)','\\(2\\pi a^2\\)','\\(\\pi a^2\\)','\\(3\\pi a^2\\) (full)'], answer: 0 },
      { q: 'The points where the tangent to \\(r=a(1+\\cos\\theta)\\) is vertical occur when \\(dx/d\\theta=0\\):', options: ['At \\(\\theta=\\pi\\) only','At \\(\\theta=0,\\ 2\\pi/3,\\ 4\\pi/3\\) (and the cusp at \\(\\theta=\\pi\\))','Only at \\(\\theta=\\pi/2\\)','Only at \\(\\theta=0\\)'], answer: 1 },
    ],
    red: [
      { q: 'Find the total area enclosed by the three-petal rose \\(r=a\\cos(3\\theta)\\).', options: ['\\(3\\pi a^2/4\\)','\\(\\pi a^2\\)','\\(\\pi a^2/4\\)','\\(\\pi a^2/2\\)'], answer: 2 },
      { q: 'The limaçon \\(r=1+2\\cos\\theta\\) has an inner loop. Find its area.', options: ['\\(\\pi/4\\)','\\(2\\pi-3\\sqrt{3}\\) (twice the loop, about 1.09)','\\(\\pi\\)','\\(\\pi-3\\sqrt{3}/2\\) (approximately 0.544)'], answer: 3 },
      { q: 'Show that \\(r=2\\cos\\theta\\) and \\(r=2\\sin\\theta\\) intersect where \\(\\theta=\\pi/4\\). The intersection point in Cartesian coordinates is:', options: ['\\((1,1)\\)','\\((2,2)\\)','\\((\\sqrt{2},\\sqrt{2})\\)','\\((0,0)\\)'], answer: 0 },
      { q: 'The Cartesian equation of the spiral \\(r=e^\\theta\\) cannot be expressed as a standard function because:', options: ['\\(r\\) is unbounded','\\(\\theta=\\ln r\\) and \\(x=r\\cos(\\ln r)\\) — transcendental','\\(e^\\theta\\) is not periodic','The curve self-intersects'], answer: 1 },
      { q: 'Find the arc length of \\(r=a\\) (circle) for \\(\\theta\\in[0,2\\pi]\\).', options: ['\\(\\pi a^2\\)','\\(4\\pi a\\)','\\(2\\pi a\\)','\\(a\\)'], answer: 2 },
      { q: 'The area swept between \\(\\theta=0\\) and \\(\\theta=\\pi\\) by the lemniscate \\(r^2=4\\cos 2\\theta\\) is:', options: ['4','\\(2\\pi\\) (the full sweep)','\\(\\pi\\)','2 (half of each lobe)'], answer: 3 },
      { q: 'For the polar curve \\(r=2+\\cos\\theta\\), the minimum value of \\(r\\) is:', options: ['1','2','3','0'], answer: 0 },
      { q: 'A student integrates \\(\\frac{1}{2}\\int_0^{2\\pi}r^2\\,d\\theta\\) for \\(r=a\\cos\\theta\\). They get \\(\\pi a^2/2\\). But the circle has area \\(\\pi(a/2)^2=\\pi a^2/4\\). The error is:', options: ['\\(r\\) should be squared differently','The curve traces the circle twice (\\(0\\) to \\(2\\pi\\)), so divide by 2','The formula is wrong','The limits should be \\([0,\\pi/2]\\)'], answer: 1 },
      { q: 'Find the equation of the tangent to \\(r=2(1+\\cos\\theta)\\) at \\(\\theta=\\pi/2\\).', options: ['\\(x=0\\)','\\(y=2\\)','\\(y=x+2\\)','\\(y=-x+2\\) (checking: at \\(\\theta=\\pi/2\\), \\(x=0,y=2\\)'], answer: 2 },
      { q: 'The area between the two loops of \\(r=1+2\\cos\\theta\\) (outer minus inner) is:', options: ['\\(\\pi\\)','\\(4\\pi-3\\sqrt{3}\\) (approximately 7.37)','\\(3\\pi\\)','\\(\\pi+3\\sqrt{3}\\) (approximately 8.34)'], answer: 3 },
    ],
  },

  '1.8': {
    name: 'Hyperbolic Functions',
    green: [
      { q: '\\(\\sinh x =\\)', options: ['\\(\\frac{e^x-e^{-x}}{2}\\)','\\(\\frac{e^x+e^{-x}}{2}\\)','\\(\\frac{e^x}{2}\\)','\\(e^x-e^{-x}\\)'], answer: 0 },
      { q: '\\(\\cosh x =\\)', options: ['\\(\\frac{e^x}{e^{-x}}\\)','\\(\\frac{e^x+e^{-x}}{2}\\)','\\(\\frac{e^x-e^{-x}}{2}\\)','\\(e^x\\)'], answer: 1 },
      { q: 'The fundamental identity of hyperbolic functions is:', options: ['\\(\\sinh^2 x-\\cosh^2 x=1\\)','\\(\\tanh^2 x+\\text{sech}^2 x=2\\)','\\(\\cosh^2 x-\\sinh^2 x=1\\)','\\(\\cosh^2 x+\\sinh^2 x=1\\)'], answer: 2 },
      { q: '\\(\\frac{d}{dx}(\\sinh x)=\\)', options: ['\\(-\\cosh x\\)','\\(\\sinh x\\)','\\(-\\sinh x\\)','\\(\\cosh x\\)'], answer: 3 },
      { q: '\\(\\frac{d}{dx}(\\cosh x)=\\)', options: ['\\(\\sinh x\\)','\\(-\\sinh x\\)','\\(\\cosh x\\)','\\(-\\cosh x\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\tanh x)=\\)', options: ['\\(\\coth x\\)','\\(\\text{sech}^2 x\\)','\\(\\sec^2 x\\)','\\(-\\text{sech}^2 x\\)'], answer: 1 },
      { q: '\\(\\sinh 0=\\)', options: ['\\(-1\\)','\\(e\\)','0','1'], answer: 2 },
      { q: '\\(\\cosh 0=\\)', options: ['0','\\(-1\\)','\\(e\\)','1'], answer: 3 },
      { q: 'The range of \\(\\tanh x\\) is:', options: ['\\((-1,1)\\)','\\(\\mathbb{R}\\)','\\([1,\\infty)\\)','\\((0,\\infty)\\)'], answer: 0 },
      { q: '\\(\\text{arcsinh}\\,x=\\)', options: ['\\(\\ln(x-\\sqrt{x^2+1})\\)','\\(\\ln(x+\\sqrt{x^2+1})\\)','\\(\\ln(x+\\sqrt{x^2-1})\\)','\\(\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\)'], answer: 1 },
      { q: "\\(\\text{arccosh}\\,x=\\)", options: ["\\(\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\)","\\(\\ln(x-\\sqrt{x^2-1})\\)","\\(\\ln(x+\\sqrt{x^2-1})\\)","\\(\\ln(x+\\sqrt{x^2+1})\\)"], answer: 2 },
      { q: '\\(\\text{arctanh}\\,x=\\)', options: ['\\(\\ln(x+\\sqrt{x^2+1})\\)','\\(\\ln(1+x)\\)','\\(\\frac{1}{x}\\)','\\(\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\)'], answer: 3 },
      { q: '\\(\\int\\sinh x\\,dx=\\)', options: ['\\(\\cosh x+C\\)','\\(-\\cosh x+C\\)','\\(\\sinh x+C\\)','\\(e^x+C\\)'], answer: 0 },
      { q: '\\(\\int\\cosh x\\,dx=\\)', options: ['\\(\\tanh x+C\\)','\\(\\sinh x+C\\)','\\(-\\sinh x+C\\)','\\(\\cosh x+C\\)'], answer: 1 },
      { q: 'The graph of \\(\\cosh x\\) is:', options: ['A straight line','Bounded between \\(-1\\) and \\(1\\)','U-shaped, minimum 1 at \\(x=0\\)','S-shaped'], answer: 2 },
      { q: '\\(\\frac{d}{dx}(\\text{arcsinh}\\,x)=\\)', options: ['\\(\\frac{1}{\\sqrt{x^2-1}}\\)','\\(\\frac{1}{1-x^2}\\)','\\(\\frac{1}{\\sqrt{1-x^2}}\\)','\\(\\frac{1}{\\sqrt{x^2+1}}\\)'], answer: 3 },
      { q: '\\(\\frac{d}{dx}(\\text{arccosh}\\,x)=\\)', options: ['\\(\\frac{1}{\\sqrt{x^2-1}}\\)','\\(\\frac{1}{\\sqrt{x^2+1}}\\)','\\(\\frac{1}{1-x^2}\\)','\\(-\\frac{1}{\\sqrt{x^2-1}}\\)'], answer: 0 },
      { q: '\\(\\frac{d}{dx}(\\text{arctanh}\\,x)=\\)', options: ['\\(\\frac{1}{\\sqrt{1-x^2}}\\)','\\(\\frac{1}{1-x^2}\\)','\\(\\frac{1}{\\sqrt{x^2+1}}\\)','\\(\\frac{1}{x^2-1}\\)'], answer: 1 },
      { q: 'Osborne\'s rule states: replace \\(\\sin^2\\theta\\) with:', options: ['\\(\\cosh^2 x\\)','\\(-\\cosh^2 x\\)','\\(-\\sinh^2 x\\)','\\(\\sinh^2 x\\)'], answer: 2 },
      { q: 'The domain of \\(\\text{arccosh}\\,x\\) is:', options: ['All real \\(x\\)','\\(|x|<1\\)','\\(x>0\\)','\\(x\\geq 1\\)'], answer: 3 },
    ],
    amber: [
      { q: 'Show that \\(\\cosh^2 x-\\sinh^2 x=1\\) using definitions. The calculation gives:', options: ['\\(\\frac{(e^x+e^{-x})^2-(e^x-e^{-x})^2}{4}=\\frac{4}{4}=1\\)','\\(\\cosh^2-\\sinh^2=0\\)','\\(\\frac{e^{2x}-e^{-2x}}{4}=1\\)','\\(e^{2x}\\cdot e^{-2x}=1\\)'], answer: 0 },
      { q: 'Solve \\(5\\cosh x-3\\sinh x=7\\) for \\(x\\).', options: ['\\(x=\\pm1\\)','\\(x=\\ln\\frac{7+\\sqrt{33}}{2}\\) or \\(x=\\ln\\frac{7-\\sqrt{33}}{2}\\)','\\(x=0\\)','\\(x=\\ln 7\\)'], answer: 1 },
      { q: 'Find \\(\\displaystyle\\int\\sinh^2 x\\,dx\\).', options: ['\\(\\sinh x\\cosh x-\\frac{x}{2}+C\\) (halved)','\\(\\frac{\\sinh 2x}{2}+C\\)','\\(\\frac{\\sinh 2x}{4}-\\frac{x}{2}+C\\)','\\(\\frac{\\cosh^2 x}{2}+C\\)'], answer: 2 },
      { q: 'Find \\(\\displaystyle\\int_0^1\\cosh x\\,dx\\).', options: ['\\(\\cosh 1-1\\)','\\(\\cosh 1\\)','1','\\(\\sinh 1\\)'], answer: 3 },
      { q: 'Using Osborne\'s rule, what is the hyperbolic form of \\(\\cos(2A)=1-2\\sin^2 A\\)?', options: ['\\(\\cosh(2A)=1+2\\sinh^2 A\\)','\\(\\cosh(2A)=1-2\\sinh^2 A\\)','\\(\\cosh(2A)=2\\cosh^2 A-1\\)','\\(\\sinh(2A)=1+2\\cosh^2 A\\)'], answer: 0 },
      { q: "Find \\(\\displaystyle\\int\\frac{1}{\\sqrt{x^2+4}}\\,dx\\).", options: ["\\(\\frac{1}{2}\\text{arcsinh}(x/2)+C\\)","\\(\\text{arcsinh}(x/2)+C\\)","\\(\\text{arccosh}(x/2)+C\\)","\\(\\frac{1}{2}\\arctan(x/2)+C\\)"], answer: 1 },
      { q: 'Find \\(\\displaystyle\\int\\frac{1}{\\sqrt{x^2-9}}\\,dx\\) for \\(x>3\\).', options: ['\\(\\frac{1}{3}\\arctan(x/3)+C\\)','\\(\\ln(x-3)+C\\)','\\(\\text{arccosh}(x/3)+C\\)','\\(\\text{arcsinh}(x/3)+C\\)'], answer: 2 },
      { q: 'Express \\(\\sinh(2x)\\) in terms of \\(\\sinh x\\) and \\(\\cosh x\\).', options: ['\\(\\cosh^2 x-\\sinh^2 x\\)','\\(2\\sinh^2 x+1\\)','\\(\\sinh^2 x+\\cosh^2 x\\)','\\(2\\sinh x\\cosh x\\)'], answer: 3 },
      { q: 'Solve \\(\\cosh x = 2\\).', options: ['\\(x=\\ln(2+\\sqrt{3})\\) or \\(x=-\\ln(2+\\sqrt{3})\\)','\\(x=\\text{arccosh}\\,2=\\ln(2+\\sqrt{3})\\) only (positive)','\\(x=\\pm\\ln 2\\)','\\(x=2\\)'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\frac{1}{1-x^2}\\,dx\\) for \\(|x|<1\\).', options: ['\\(-\\text{arctanh}\\,x+C\\)','\\(\\text{arctanh}\\,x+C=\\frac{1}{2}\\ln\\frac{1+x}{1-x}+C\\)','\\(\\arctan x+C\\)','\\(\\frac{1}{2}\\ln|1-x^2|+C\\)'], answer: 1 },
      { q: 'Express \\(\\cosh(2x)\\) using \\(\\cosh x\\) only.', options: ['\\(1+2\\sinh^2 x\\)','\\(2\\cosh x\\sinh x\\)','\\(2\\cosh^2 x-1\\)','\\(\\cosh^2 x+\\sinh^2 x\\)'], answer: 2 },
      { q: 'Find the derivative of \\(\\sinh(3x)\\).', options: ['\\(\\cosh(3x)\\)','\\(3\\sinh(3x)\\)','\\(-3\\cosh(3x)\\)','\\(3\\cosh(3x)\\)'], answer: 3 },
      { q: 'Integrate \\(\\displaystyle\\int x\\cosh x\\,dx\\) by parts.', options: ['\\(x\\sinh x-\\cosh x+C\\)','\\(x\\cosh x-\\sinh x+C\\)','\\(x\\cosh x+\\sinh x+C\\)','\\(\\sinh x-x\\cosh x+C\\)'], answer: 0 },
      { q: 'Using the definition, show \\(\\tanh x\\to 1\\) as \\(x\\to\\infty\\). This is because:', options: ['\\(e^x\\to 1\\)','\\(e^{-x}\\to 0\\) so \\(\\tanh x=\\frac{e^x-e^{-x}}{e^x+e^{-x}}\\to\\frac{1-0}{1+0}=1\\)','\\(\\sinh x\\to\\infty\\)','\\(\\cosh x\\to 0\\)'], answer: 1 },
      { q: 'Find \\(\\displaystyle\\int\\cosh^2 x\\,dx\\).', options: ['\\(\\frac{\\sinh 2x}{2}+C\\)','\\(\\frac{x\\cosh^2 x}{2}+\\frac{x}{2}+C\\)','\\(\\frac{\\sinh 2x}{4}+\\frac{x}{2}+C\\)','\\(\\frac{\\cosh^2 x}{2}+C\\)'], answer: 2 },
      { q: 'Using Osborne\'s rule, convert \\(\\cos^2 A + \\sin^2 A=1\\):', options: ['\\(\\cosh^2 A + \\sinh^2 A = 1\\)','\\(\\sinh^2 A - \\cosh^2 A = 1\\)','\\(\\cosh^2 A + \\sinh^2 A = 2\\)','\\(\\cosh^2 A - \\sinh^2 A = 1\\)'], answer: 3 },
      { q: 'Prove \\(\\text{arctanh}\\,x=\\frac{1}{2}\\ln\\frac{1+x}{1-x}\\). The key step is:', options: ['Setting \\(y=\\tanh x\\) then \\(e^{2x}=\\frac{1+y}{1-y}\\)','Using integration','Completing the square','The chain rule'], answer: 0 },
      { q: 'Find \\(\\displaystyle\\int\\tanh x\\,dx\\).', options: ['\\(-\\ln(\\cosh x)+C\\)','\\(\\ln(\\cosh x)+C\\)','\\(\\ln(\\sinh x)+C\\)','\\(\\text{sech}^2 x+C\\)'], answer: 1 },
      { q: 'The curve \\(y=\\cosh x\\) is known as a:', options: ['Cycloid','Lemniscate','Catenary','Parabola'], answer: 2 },
    ],
    red: [
      { q: 'Derive \\(\\text{arcsinh}\\,x=\\ln(x+\\sqrt{x^2+1})\\) from first principles.', options: ['Use the chain rule on \\(\\sinh^{-1}\\) and integrate the result','Integrate \\(1/\\sqrt{x^2+1}\\)','Use Osborne\'s rule','Set \\(\\sinh y=x\\), form quadratic in \\(e^y\\)'], answer: 3 },
      { q: 'Find \\(\\displaystyle\\int\\sqrt{x^2+1}\\,dx\\) using the substitution \\(x=\\sinh t\\).', options: ['\\(\\frac{x\\sqrt{x^2+1}}{2}+\\frac{1}{2}\\text{arcsinh}\\,x+C\\)','\\(\\frac{2}{3}(x^2+1)^{3/2}+C\\)','\\(\\frac{x^2}{2}\\sqrt{x^2+1}+C\\)','\\(\\cosh x+C\\)'], answer: 0 },
      { q: 'Prove that \\(\\frac{d}{dx}(\\text{arccosh}\\,x)=\\frac{1}{\\sqrt{x^2-1}}\\) using implicit differentiation.', options: ['Use the product rule on \\(e^y\\)','Set \\(y=\\text{arccosh}\\,x\\), so \\(\\cosh y=x\\)','Use the quotient rule','Use Osborne’s rule, replacing \\(\\arccos\\) by \\(\\text{arccosh}\\)'], answer: 1 },
      { q: 'A catenary has equation \\(y=a\\cosh(x/a)\\). Its arc length from \\(x=-a\\) to \\(x=a\\) is:', options: ['\\(2a\\)','\\(2a\\cosh 1\\)','\\(2a\\sinh 1\\)','\\(a\\sinh 2\\)'], answer: 2 },
      { q: "Solve \\(\\sinh^2 x-5\\cosh x+5=0\\).", options: ["No real solutions","\\(x=0\\) only","\\(x=0\\) or \\(x=\\pm\\ln(2+\\sqrt{3})\\)","\\(x=0\\) or \\(x=\\pm\\ln(4+\\sqrt{15})\\)"], answer: 3 },
      { q: 'The integral \\(\\displaystyle\\int_1^2\\frac{1}{\\sqrt{x^2-1}}\\,dx\\) equals:', options: ['\\(\\text{arccosh}\\,2\\)','\\(\\ln(2+\\sqrt{5})\\) (arcsinh)','\\(\\arctan\\sqrt{3}\\)','\\(\\pi/4\\)'], answer: 0 },
      { q: 'Using the identity \\(\\sinh(3x)=3\\sinh x+4\\sinh^3 x\\), express \\(\\sinh^3 x\\) in terms of multiple arguments: \\(\\sinh^3 x=\\)', options: ['\\(\\frac{\\sinh 3x+3\\sinh x}{4}\\)','\\(\\frac{\\sinh 3x-3\\sinh x}{4}\\)','\\(\\sinh 3x/4\\)','\\(\\frac{3\\sinh x-\\sinh 3x}{4}\\)'], answer: 1 },
      { q: 'Show \\(1-\\tanh^2 x=\\text{sech}^2 x\\). This follows from:', options: ['The definition of \\(\\tanh\\) as \\(\\sinh x/\\cosh x\\) alone','Osborne\'s rule','Dividing \\(\\cosh^2 x-\\sinh^2 x=1\\) by \\(\\cosh^2 x\\)','Adding the squares'], answer: 2 },
      { q: 'The relationship between \\(\\text{arctanh}\\,x\\) and partial fractions gives \\(\\displaystyle\\int\\frac{1}{a^2-x^2}\\,dx=\\)', options: ['\\(\\text{arccosh}(x/a)+C\\)','\\(\\frac{1}{a}\\arctan\\frac{x}{a}+C\\) for all real values of \\(x\\)','\\(\\frac{1}{a^2}\\ln|a^2-x^2|+C\\)','\\(\\frac{1}{a}\\text{arctanh}\\frac{x}{a}+C\\) for \\(|x|<a\\)'], answer: 3 },
      { q: 'The surface area of a catenary \\(y=\\cosh x\\) rotated about the \\(x\\)-axis from \\(-a\\) to \\(a\\) requires:', options: ['\\(2\\pi\\int_{-a}^{a}\\cosh^2 x\\,dx\\) (since \\(\\sqrt{1+\\sinh^2 x}=\\cosh x\\))','\\(\\pi\\int_{-a}^a\\cosh^2 x\\,dx\\)','\\(4\\pi a^2\\)','\\(2\\pi\\int_{-a}^a x\\,dx\\)'], answer: 0 },
    ],
  },

  '1.9': {
    name: 'Differential Equations',
    green: [
      { q: 'A separable ODE has the form:', options: ['\\(y=f(x)\\)','\\(dy/dx=f(x)g(y)\\)','\\(dy/dx+P(x)y=Q(x)\\)','\\(ay\'\'+by\'+cy=0\\)'], answer: 1 },
      { q: 'The integrating factor for \\(dy/dx+P(x)y=Q(x)\\) is:', options: ['\\(P(x)\\)','\\(\\int P\\,dx\\) (no exp)','\\(e^{\\int P\\,dx}\\)','\\(e^{P}\\)'], answer: 2 },
      { q: "The auxiliary equation for \\(ay''+by'+cy=0\\) is:", options: ["\\(am^2-bm+c=0\\)","\\(am+b=0\\)","\\(m^2=ac/b^2\\)","\\(am^2+bm+c=0\\)"], answer: 3 },
      { q: 'If the auxiliary equation has a repeated root \\(m\\), the complementary function is:', options: ['\\((A+Bx)e^{mx}\\)','\\(Ae^{mx}+Be^{mx}\\)','\\(e^{mx}(A\\cos x+B\\sin x)\\)','\\(Ae^{mx}\\)'], answer: 0 },
      { q: 'If the auxiliary equation has complex roots \\(\\alpha\\pm\\beta i\\), the CF is:', options: ['\\(e^{i\\alpha x}(A+B)\\)','\\(e^{\\alpha x}(A\\cos\\beta x+B\\sin\\beta x)\\)','\\(e^{\\alpha x}+e^{\\beta x}\\)','\\(A\\cos\\alpha x+B\\sin\\beta x\\)'], answer: 1 },
      { q: 'The general solution of a non-homogeneous ODE is:', options: ['\\(y_{CF}-y_{PI}\\)','\\(y_{PI}\\) only','\\(y_{CF}+y_{PI}\\)','\\(y_{CF}\\cdot y_{PI}\\)'], answer: 2 },
      { q: 'For \\(f(x)=ke^{px}\\) (not in CF), the trial particular integral is:', options: ['\\(\\lambda xe^{px}\\)','\\(\\lambda x^2 e^{px}\\)','\\(\\lambda+\\mu x\\)','\\(\\lambda e^{px}\\)'], answer: 3 },
      { q: 'For \\(f(x)=k\\sin(px)\\), the trial PI is:', options: ['\\(\\lambda\\cos(px)+\\mu\\sin(px)\\)','\\(\\lambda\\sin(px)+\\mu x\\sin(px)\\)','\\(\\lambda\\cos(px)\\)','\\(\\lambda e^{px}\\)'], answer: 0 },
      { q: 'Solve \\(dy/dx=y\\). The general solution is:', options: ['\\(y=e^{Ax}\\)','\\(y=Ae^x\\)','\\(y=A\\ln x\\)','\\(y=Ax\\)'], answer: 1 },
      { q: 'Solve \\(dy/dx=2x\\). The general solution is:', options: ['\\(y=2x^2+C\\)','\\(y=x^2\\)','\\(y=x^2+C\\)','\\(y=2+C\\)'], answer: 2 },
      { q: 'If the auxiliary equation has roots \\(m=2\\) and \\(m=-3\\), the CF is:', options: ['\\(e^{2x}(A\\cos3x+B\\sin3x)\\)','\\((A+Bx)e^{-x}\\)','\\(Ae^{-x}+Be^{-6x}\\)','\\(Ae^{2x}+Be^{-3x}\\)'], answer: 3 },
      { q: 'The particular integral for \\(y\'\'+y=3\\) is:', options: ['\\(y=3\\)','\\(y=3x\\)','\\(y=3e^x\\)','\\(y=0\\)'], answer: 0 },
      { q: 'Multiplying a first-order linear ODE by \\(\\mu\\) converts the LHS to:', options: ['\\(d\\mu/dx\\)','\\(\\frac{d}{dx}(\\mu y)\\)','\\(\\mu^2 y\\)','\\(\\mu y+\\mu P y\\) (unchanged)'], answer: 1 },
      { q: 'The equation \\(y\'\'-3y\'+2y=0\\) has auxiliary equation with roots:', options: ['\\(m=-1,-2\\)','\\(m=1,-1\\)','\\(m=1,2\\)','\\(m=3,2\\)'], answer: 2 },
      { q: 'For initial conditions to find a particular solution, you need:', options: ['The complementary function only','The particular integral only','The auxiliary equation roots','Values of \\(y\\) (and possibly \\(y\'\\)) at specific points'], answer: 3 },
      { q: 'What is the degree of an ODE?', options: ['The power of the highest derivative when the equation is written in polynomial form','The order of the highest derivative','The number of terms','The number of solutions'], answer: 0 },
      { q: 'A first-order ODE is separable if you can write it as:', options: ['\\(y+y\'=f(x)\\)','Separate terms in \\(x\\) on one side, terms in \\(y\\) on the other','\\(y=f(x)+g(y)\\)','\\(dy/dx=f(x)+g(y)\\)'], answer: 1 },
      { q: 'For the trial PI to fail (and need multiplying by \\(x\\)), you need:', options: ['The equation is non-linear','The RHS is a polynomial','The trial function is part of the complementary function','The coefficient is zero'], answer: 2 },
      { q: 'The order of a differential equation is determined by:', options: ['The degree of \\(y\\)','The number of constants in the general solution','The number of terms','The highest derivative present'], answer: 3 },
      { q: 'Coupled DEs \\(\\dot{x}=ax+by\\), \\(\\dot{y}=cx+dy\\) are reduced to a single ODE by:', options: ['Differentiating one equation and substituting the other to eliminate one variable','Adding the two equations','Subtracting the two equations','Using matrices directly'], answer: 0 },
    ],
    amber: [
      { q: 'Solve \\(dy/dx=xy\\) with \\(y(0)=1\\).', options: ['\\(y=1+x^2/2\\) (Euler step)','\\(y=e^{x^2/2}\\)','\\(y=e^x\\)','\\(y=xe^x\\)'], answer: 1 },
      { q: 'Find the general solution of \\(dy/dx+y/x=x^2\\).', options: ['\\(y=x^3/4+C\\)','\\(y=x^2+C/x\\)','\\(y=x^3/4+C/x\\)','\\(y=x^3/3+Cx\\) (IF \\(x^{-1}\\))'], answer: 2 },
      { q: 'Find the general solution of \\(y\'\'-5y\'+6y=0\\).', options: ['\\(y=(A+Bx)e^{3x}\\)','\\(y=e^{5x/2}(A\\cos x+B\\sin x)\\)','\\(y=Ae^{-2x}+Be^{-3x}\\)','\\(y=Ae^{2x}+Be^{3x}\\)'], answer: 3 },
      { q: 'Find the particular integral for \\(y\'\'-3y\'+2y=4e^{3x}\\).', options: ['\\(y_{PI}=2e^{3x}\\)','\\(y_{PI}=4e^{3x}\\)','\\(y_{PI}=2xe^{3x}\\)','\\(y_{PI}=e^{3x}/2\\)'], answer: 0 },
      { q: 'Solve \\(y\'\'+4y=8\\) with \\(y(0)=3\\), \\(y\'(0)=0\\).', options: ['\\(y=3e^{-4x}+2\\)','\\(y=\\cos 2x+2\\)','\\(y=3\\cos 2x\\)','\\(y=2+\\cos 2x+\\sin 2x\\)'], answer: 1 },
      { q: 'Find the integrating factor for \\(dy/dx+2y/x=x^2\\).', options: ['\\(x\\)','\\(e^{2/x}\\)','\\(x^2\\)','\\(e^{2x}\\)'], answer: 2 },
      { q: 'For \\(y\'\'-4y\'+4y=e^{2x}\\), the trial PI is:', options: ['\\(\\lambda e^{2x}\\)','\\(\\lambda x e^{2x}\\)','\\(\\lambda x^3 e^{2x}\\)','\\(\\lambda x^2 e^{2x}\\)'], answer: 3 },
      { q: 'Solve \\(y\'\'-y=\\sin x\\) for the particular integral.', options: ['\\(y_{PI}=-\\frac{1}{2}\\sin x\\)','\\(y_{PI}=\\frac{1}{2}\\sin x\\) (sign)','\\(y_{PI}=-\\sin x\\)','\\(y_{PI}=\\cos x\\)'], answer: 0 },
      { q: 'The equation \\(y\'\'+9y=\\cos 3x\\) — the trial PI \\(\\lambda\\cos3x+\\mu\\sin3x\\) fails because:', options: ['\\(\\mu=0\\)','\\(\\cos 3x\\) is part of the CF (roots \\(\\pm3i\\))','The equation is non-linear','The coefficient of \\(y\'\'\\) is 1'], answer: 1 },
      { q: 'Solve \\(\\frac{dy}{dx}+y\\cot x=\\cos x\\). The integrating factor is:', options: ['\\(\\cos x\\)','\\(e^x\\)','\\(\\sin x\\)','\\(\\cot x\\)'], answer: 2 },
      { q: 'Find the general solution of \\(y\'\'+2y\'+5y=0\\).', options: ['\\(y=Ae^{-2x}+Be^{-5x}\\)','\\(y=(A+Bx)e^{-x}\\)','\\(y=e^x(A\\cos2x+B\\sin2x)\\)','\\(y=e^{-x}(A\\cos2x+B\\sin2x)\\)'], answer: 3 },
      { q: 'Find the particular integral for \\(y\'\'+y=x^2\\).', options: ['\\(x^2-2\\)','\\(x^2\\)','\\(x^2+2x\\)','\\(x^2-2x+2\\)'], answer: 0 },
      { q: 'Solve the coupled system \\(\\dot{x}=y\\), \\(\\dot{y}=-x\\). The solution has:', options: ['\\(x=A\\cosh t\\), \\(y=B\\sinh t\\)','\\(x=A\\cos t+B\\sin t\\), \\(y=-A\\sin t+B\\cos t\\)','\\(x=Ae^t\\), \\(y=Be^t\\)','\\(x=x_0e^{-t}\\), \\(y=y_0e^{-t}\\)'], answer: 1 },
      { q: 'The general solution of \\(y\'\'-4y=0\\) is:', options: ['\\(A\\cos 2x+B\\sin 2x\\) (for \\(+4y\\))','\\((A+Bx)e^{2x}\\)','\\(Ae^{2x}+Be^{-2x}\\)','\\(e^{2x}(A+B)\\)'], answer: 2 },
      { q: "Use separation of variables to solve \\(\\frac{dy}{dx}=\\frac{x}{y}\\). The general solution is:", options: ["\\(y=x+C\\)","\\(y^2+x^2=C\\)","\\(y=\\frac{x^2}{2}+C\\)","\\(y^2=x^2+C\\)"], answer: 3 },
      { q: 'To solve \\(y\'\'+y=e^x\\), the PI trial is:', options: ['\\(\\lambda e^x\\) (since \\(e^x\\) is not in CF)','\\(\\lambda x e^x\\)','\\(\\lambda x^2 e^x\\)','\\(\\lambda\\)'], answer: 0 },
      { q: 'Apply \\(y(0)=1\\), \\(y\'(0)=2\\) to \\(y=Ae^{2x}+Be^{3x}\\). Then:', options: ['\\(A=B=1\\)','\\(A+B=1\\), \\(2A+3B=2\\), so \\(A=1,B=0\\)','\\(A=2,B=-1\\)','\\(A=0,B=1\\)'], answer: 1 },
      { q: 'For the equation \\(y\\frac{dy}{dx}=x\\), the general solution (separating variables) is:', options: ['\\(y=\\sqrt{x}+C\\)','\\(y^2=2x^2+C\\)','\\(y^2=x^2+C\\)','\\(y=x+C\\)'], answer: 2 },
      { q: 'For the non-homogeneous equation \\(y\'\'-y=x\\), the PI is:', options: ['\\(x\\)','\\(-x-1\\)','\\(x+1\\)','\\(-x\\)'], answer: 3 },
      { q: 'The coupled system \\(\\dot{x}=2x+y\\), \\(\\dot{y}=x+2y\\) has eigenvalues (of the matrix):', options: ['1 and 3','2 and 2','0 and 4','\\(-1\\) and 3'], answer: 0 },
    ],
    red: [
      { q: 'Solve \\(\\frac{dy}{dx}=\\frac{y^2-1}{x}\\) by separating variables.', options: ['\\(\\frac{y+1}{y-1}=Ax^2\\) (inverted)','\\(y=\\frac{1+Ax^2}{1-Ax^2}\\)','\\(y^2=1+Cx^2\\)','\\(y=x+C\\)'], answer: 1 },
      { q: 'Find the general solution of \\(y\'\'-2y\'+y=e^x\\) (note \\(e^x\\) is in the CF twice).', options: ['\\(y=(A+Bx)e^x+e^x\\)','\\(y=Ae^x+\\frac{x^2}{2}e^x\\) (single root)','\\(y=(A+Bx)e^x+\\frac{x^2}{2}e^x\\)','\\(y=(A+Bx)e^x+xe^x\\)'], answer: 2 },
      { q: 'For the Bernoulli equation \\(\\frac{dy}{dx}+y=y^3\\), the substitution \\(v=y^{-2}\\) gives:', options: ['\\(\\frac{dv}{dx}+2v=2\\) (the sign of v flipped)','\\(\\frac{dv}{dx}=v^3\\)','\\(\\frac{dv}{dx}+v=1\\)','\\(\\frac{dv}{dx}-2v=-2\\) (a linear ODE)'], answer: 3 },
      { q: 'For the system \\(\\dot{x}=4x+y\\), \\(\\dot{y}=2x+3y\\), eliminating \\(y\\) gives:', options: ['\\(\\ddot{x}-7\\dot{x}+10x=0\\)','\\(\\ddot{x}-4\\dot{x}+3x=0\\)','\\(\\ddot{x}-7x=0\\)','\\(\\ddot{x}+7\\dot{x}-10x=0\\)'], answer: 0 },
      { q: 'The particular integral of \\(y\'\'+y=\\cos x\\) requires which trial?', options: ['\\(\\lambda e^{ix}\\)','\\(x(\\lambda\\cos x+\\mu\\sin x)\\) (since \\(\\pm i\\) are CF roots)','\\(\\lambda\\cos x+\\mu\\sin x\\) (no factor of \\(x\\) is needed here)','\\(x^2\\lambda\\cos x\\)'], answer: 1 },
      { q: 'Solve \\(y\'\'-2y\'+2y=e^x\\sin x\\). The CF is \\(e^x(A\\cos x+B\\sin x)\\); the PI trial is:', options: ['\\(\\lambda e^x\\sin x\\)','\\(\\lambda e^{2x}\\)','\\(xe^x(\\lambda\\cos x+\\mu\\sin x)\\) (since \\(e^x\\sin x\\) already appears in the CF)','\\(e^x(\\lambda\\cos x+\\mu\\sin x)\\)'], answer: 2 },
      { q: 'For large \\(t\\), the solution \\(y=Ae^{-2t}+Be^{3t}\\) behaves like:', options: ['\\(Ae^{-2t}\\)','\\(A+B\\)','0','\\(Be^{3t}\\) (dominates as \\(e^{3t}\\to\\infty\\))'], answer: 3 },
      { q: 'A second-order ODE requires \\(\\square\\) arbitrary constants in its general solution:', options: ['2','1','0','3'], answer: 0 },
      { q: 'To test whether two solutions \\(y_1\\) and \\(y_2\\) are linearly independent, compute the Wronskian \\(W=y_1y_2\'-y_2y_1\'\\). For \\(y_1=e^{2x}\\), \\(y_2=e^{3x}\\): \\(W=\\)', options: ['\\(6e^{5x}\\)','\\(e^{5x}\\neq0\\)','0','\\(5e^{5x}\\) (added powers)'], answer: 1 },
      { q: 'The equation \\(x^2y\'\'+xy\'-y=0\\) is a Cauchy-Euler equation. The substitution \\(x=e^t\\) converts it to:', options: ['An exact equation','A Bernoulli equation','A second-order ODE with constant coefficients','A separable first-order equation in the variable \\(t\\)'], answer: 2 },
      { q: 'For \\(y\'\'+4y=\\delta(t)\\) (impulse input), the response involves:', options: ['\\(y=e^{-4t}\\)','A constant response','A growing exponential','A sine wave of amplitude \\(1/2\\) starting at \\(t=0\\): \\(y=\\tfrac{1}{2}\\sin 2t\\)'], answer: 3 },
    ],
  },

};
