/*
 * Edexcel A-Level English Language (9EN0) — Diagnostic MCQ Bank
 * 50 questions per topic: 20 green (recall/basic), 20 amber (application), 10 red (analysis/evaluate)
 * Diagnostic picks 2 green + 2 amber + 1 red = 5 questions at random, one of which is a written Q pulled from english-edexcel-written.js
 * answer: 0-based index of correct option.
 */

const ENGLISH_EDEXCEL_QUESTIONS = {

  /* ─────────────────────────────────────────────────────────── 1.1 */
  '1.1': {
    name: 'Individual and Social Variation',
    green: [
      { q: 'What is an "idiolect"?', options: ['A regional accent','The unique linguistic profile of an individual speaker','An official language','A type of slang'], answer: 1 },
      { q: 'What is a "sociolect"?', options: ['A language variety associated with a particular social group','An accent only','A regional dialect','An individual\'s speech'], answer: 0 },
      { q: 'What is a "dialect"?', options: ['Only pronunciation patterns','A variety of a language with distinctive lexis, grammar and often pronunciation','A second language','A type of slang'], answer: 1 },
      { q: 'What is an "accent"?', options: ['Vocabulary differences','Pronunciation patterns of a speaker or group','Grammatical rules','A type of punctuation'], answer: 1 },
      { q: 'What does "RP" stand for?', options: ['Regional Pronunciation','Received Pronunciation','Rapid Pronunciation','Reading Paper'], answer: 1 },
      { q: 'RP is traditionally associated with…', options: ['Only Liverpool','High social prestige and BBC broadcasting','Only Wales','Children'], answer: 1 },
      { q: 'What is "Standard English"?', options: ['A regional dialect','The variety of English recognised for formal, educational and official use','An accent','A slang form'], answer: 1 },
      { q: 'Standard English and RP are…', options: ['The same thing','Different: Standard English is a dialect; RP is an accent','Only written','Only spoken'], answer: 1 },
      { q: 'What is meant by "register"?', options: ['A type of accent','The level of formality and appropriateness to context','An individual\'s speech','A grammar book'], answer: 1 },
      { q: 'Which of these is a UK regional dialect?', options: ['Geordie','Spanglish','Creole','AAVE'], answer: 0 },
      { q: 'Who carried out the Norwich study of language variation?', options: ['Labov','Peter Trudgill','Milroy','Cheshire'], answer: 1 },
      { q: 'Who studied language variation in Belfast through social networks?', options: ['Labov','Trudgill','Lesley Milroy','Cheshire'], answer: 2 },
      { q: 'Who conducted the New York department store study of /r/?', options: ['William Labov','Trudgill','Milroy','Petyt'], answer: 0 },
      { q: 'What is "overt prestige"?', options: ['Hidden prestige','Prestige attached to publicly valued standard forms','A type of accent','A form of slang'], answer: 1 },
      { q: 'What is "covert prestige"?', options: ['Official prestige','Hidden prestige attached to non-standard forms within a group','Only for writing','Only for RP'], answer: 1 },
      { q: 'What is a "sociolinguistic variable"?', options: ['A linguistic feature that varies systematically with social factors','A grammar rule','A formal register','A dictionary definition'], answer: 0 },
      { q: 'Which of these is a UK accent feature?', options: ['H-dropping in Cockney','Japanese tone marks','Mandarin tones','Greek letters'], answer: 0 },
      { q: 'Which of these is typical of Cockney?', options: ['T-glottalisation ("be\'er" for "better")','Use of French grammar','Use of Latin','Only RP vowels'], answer: 0 },
      { q: 'A North/South divide in UK English is often shown by which vowel split?', options: ['The "bath" / "trap" split','The German /ch/','Mandarin tones','Arabic script'], answer: 0 },
      { q: 'Who proposed the concept of "community of practice" for language variation?', options: ['Eckert and McConnell-Ginet','Lakoff','Skinner','Piaget'], answer: 0 },
    ],
    amber: [
      { q: 'Labov\'s New York department store study (1966) measured the frequency of which variable?', options: ['Post-vocalic /r/ across stores of different social prestige','Greek loanwords','Tone in Chinese','Mandarin particles'], answer: 0 },
      { q: 'What did Trudgill find about men and non-standard forms in Norwich?', options: ['Men under-reported standard usage','Men tended to use more non-standard forms and over-reported this use — covert prestige','Men always used RP','No difference'], answer: 1 },
      { q: 'Milroy\'s Belfast study argued that…', options: ['Network density predicts use of local vernacular forms','Only class matters','Only media matters','Only accent matters'], answer: 0 },
      { q: 'Howard Giles is associated with which theory?', options: ['Communication Accommodation Theory','Universal Grammar','Generative syntax','The deficit model'], answer: 0 },
      { q: 'Which term describes a speaker adjusting style TOWARDS the listener?', options: ['Convergence','Divergence','Diglossia','Creolisation'], answer: 0 },
      { q: 'Which term describes a speaker deliberately distancing their style FROM the listener?', options: ['Convergence','Divergence','Accommodation','Levelling'], answer: 1 },
      { q: 'Paul Kerswill is associated with research on…', options: ['Dialect levelling and MLE','Old English','Formal grammar only','Latin'], answer: 0 },
      { q: 'MLE stands for…', options: ['Modern Literary English','Multicultural London English','Mixed Latin English','Model Language Example'], answer: 1 },
      { q: 'Which of these is a feature of MLE?', options: ['Fronted GOOSE vowel; lexis from Caribbean, South Asian sources; "man" as indefinite pronoun','Only Latin lexis','Only French grammar','Only Old English forms'], answer: 0 },
      { q: 'Which of these is an example of "hypercorrection" (Labov)?', options: ['Lower-middle-class speakers over-producing a prestige form in careful speech','Dropping aspirates','Refusing standard forms','Using only local slang'], answer: 0 },
      { q: 'Bernstein proposed which controversial distinction?', options: ['Restricted and elaborated code','Active and passive voice','Phonemes and morphemes','Formal and informal'], answer: 0 },
      { q: 'Why is Bernstein\'s theory considered controversial?', options: ['It has been criticised for implying working-class speech is inherently deficient','It is universally accepted','It is about French','It is about spelling'], answer: 0 },
      { q: 'Jenny Cheshire\'s Reading study linked non-standard grammatical features to…', options: ['Age only','Peer-group membership in adolescent vernacular cultures','Only class','Only gender'], answer: 1 },
      { q: 'A "basilect" is…', options: ['A variety furthest from the prestige standard','An accent of the upper class','A formal register','A grammatical rule'], answer: 0 },
      { q: 'An "acrolect" is…', options: ['The variety closest to the prestige standard','A type of slang','A child variety','A regional dialect'], answer: 0 },
      { q: 'Which of these is an occupational lect?', options: ['Legal English with specialist jargon','Welsh','Cockney','Geordie'], answer: 0 },
      { q: 'What is "style-shifting"?', options: ['Writing in different fonts','A speaker adjusting their register / variety depending on context and audience','A morphological process','A cataloguing system'], answer: 1 },
      { q: 'Which term refers to the language of a particular profession or specialist group?', options: ['Jargon','Pidgin','Dialect','Patois'], answer: 0 },
      { q: 'Petyt\'s Bradford study found that…', options: ['H-dropping correlated with social class','Only accent mattered','No patterns were found','Accent has no social link'], answer: 0 },
      { q: 'Cheshire\'s research on adolescents showed that non-standard features served as markers of…', options: ['Covert prestige within peer groups','Overt prestige','Formality','Latinate register'], answer: 0 },
    ],
    red: [
      { q: 'Evaluate: "Standard English is objectively better than dialects." Which response is MOST linguistically accurate?', options: ['Yes — dialects have errors','No — all varieties are rule-governed; Standard English\'s status is social, not structural','Yes — Standard English is unchanging','No — Standard English is just a regional dialect'], answer: 1 },
      { q: 'Labov\'s finding that lower-middle-class speakers produced MORE prestige /r/ than upper-middle-class speakers in careful speech is known as…', options: ['Hypercorrection','Levelling','Divergence','Anti-language'], answer: 0 },
      { q: 'A top-band answer on UK regional variation integrates…', options: ['Multiple named studies (Labov, Trudgill, Milroy, Cheshire) with concepts of prestige, network and identity','Only one theorist','Only an accent description','Only one example'], answer: 0 },
      { q: 'Evaluate the claim: "Dialect levelling is destroying UK regional diversity."', options: ['Fully agree','Mixed: levelling is real (Kerswill) but new varieties (MLE) emerge; regional identity persists in other ways','Fully disagree','Dialects never change'], answer: 1 },
      { q: 'Why is network density (Milroy) considered a stronger predictor than class in some studies?', options: ['It identifies who actually talks with whom — explaining why close-knit groups retain vernacular features even across class','Class is irrelevant','Networks only apply to children','It cannot be measured'], answer: 0 },
      { q: 'A 30-year-old professional from Yorkshire uses /ʊ/ (the Northern short vowel) in "bath" at home but /ɑː/ (the Southern vowel) in meetings. What is happening?', options: ['Style-shifting / accommodation — register-sensitive variation','Random noise','Loss of identity','Only Labov'], answer: 0 },
      { q: 'Eckert and McConnell-Ginet\'s "community of practice" approach shifts the field from…', options: ['Static class/gender categories to shared practice and repertoires','Social class to biological sex','Identity to neurology','Meaning to grammar alone'], answer: 0 },
      { q: 'Labov\'s Martha\'s Vineyard study (1963) linked centralised diphthongs to…', options: ['Identity: islanders who wanted to distance themselves from mainland visitors centralised more','Class only','Age only','Ethnicity only'], answer: 0 },
      { q: 'Why does the "deficit" reading of Bernstein\'s codes face criticism?', options: ['Because Labov\'s work shows vernacular varieties are rule-governed; treating working-class speech as deficient conflates social judgement with linguistic fact','Because Bernstein invented nothing','Because codes are fixed','Because only AAVE matters'], answer: 0 },
      { q: 'What distinguishes a SOPHISTICATED treatment of "Standard English" in an A-level answer?', options: ['Recognition that Standard English is a DIALECT (lexis + grammar) distinct from RP (accent), and that its status is sociohistorical rather than natural','Treating it as the only correct form','Treating it as an accent','Treating it as universal'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── 1.2 */
  '1.2': {
    name: 'Historical Language Change',
    green: [
      { q: 'Which period is known as Early Modern English?', options: ['c. 450–1066','1066–1500','c. 1500–1700','1900–present'], answer: 2 },
      { q: 'The printing press was introduced to England in which year?', options: ['1066','1476','1611','1755'], answer: 1 },
      { q: 'Who introduced the printing press to England?', options: ['William Caxton','Samuel Johnson','Geoffrey Chaucer','William Shakespeare'], answer: 0 },
      { q: 'Samuel Johnson\'s "A Dictionary of the English Language" was published in…', options: ['1611','1755','1800','1900'], answer: 1 },
      { q: 'The Great Vowel Shift occurred approximately…', options: ['Before 1066','c. 1400–1700','1800–1900','2000–present'], answer: 1 },
      { q: 'What is a "neologism"?', options: ['An old word','A newly coined word or expression','A type of grammar','A spelling convention'], answer: 1 },
      { q: 'Which process creates "brunch" from "breakfast + lunch"?', options: ['Affixation','Blending','Compounding','Clipping'], answer: 1 },
      { q: '"Laptop" is formed by which process?', options: ['Blending','Compounding','Clipping','Borrowing'], answer: 1 },
      { q: '"Exam" from "examination" is an example of…', options: ['Blending','Clipping','Compounding','Affixation'], answer: 1 },
      { q: '"NATO" and "DIY" are examples of…', options: ['Acronyms / initialisms','Clippings','Blends','Eponyms'], answer: 0 },
      { q: '"Sandwich" (from the Earl of Sandwich) is an example of…', options: ['Eponym','Blend','Acronym','Clipping'], answer: 0 },
      { q: 'What is "semantic broadening"?', options: ['Narrower meaning','A word gaining wider meaning over time','A positive shift','A negative shift'], answer: 1 },
      { q: 'What is "semantic narrowing"?', options: ['Wider meaning','A word gaining a narrower meaning over time','Only for verbs','Only for adjectives'], answer: 1 },
      { q: 'What is "amelioration"?', options: ['A negative shift','A positive shift in meaning (e.g. "nice" once meant "foolish")','Narrowing','Broadening'], answer: 1 },
      { q: 'What is "pejoration"?', options: ['A positive shift','A negative shift in meaning (e.g. "silly" once meant "blessed")','Broadening','Narrowing'], answer: 1 },
      { q: 'Which theorist proposed three critical metaphors for language change?', options: ['Jean Aitchison','Noam Chomsky','William Labov','David Crystal'], answer: 0 },
      { q: 'Aitchison\'s metaphors include which of the following?', options: ['"Damp spoon", "crumbling castle", "infectious disease"','"Dry lake"','"Sunny meadow"','"Empty vessel"'], answer: 0 },
      { q: 'David Crystal is typically seen as a…', options: ['Descriptivist','Prescriptivist','Behaviourist','Formalist'], answer: 0 },
      { q: 'An "S-curve" describes the typical…', options: ['Shape of sound change diffusion — slow start, rapid spread, plateau','Shape of sentences','Vowel quality','Length of words'], answer: 0 },
      { q: 'Which of these is a driver of recent language change?', options: ['Digital technology and social media','Silence','Decline of reading','Only grammar lessons'], answer: 0 },
    ],
    amber: [
      { q: 'The Norman Conquest (1066) introduced large amounts of which lexis?', options: ['French/Anglo-Norman','Chinese','Russian','Swahili'], answer: 0 },
      { q: 'The King James Bible was published in…', options: ['1611','1476','1755','1900'], answer: 0 },
      { q: 'Which theorist used the metaphor "crumbling castle" to CRITIQUE prescriptivist views?', options: ['Jean Aitchison','Noam Chomsky','William Labov','Lynne Truss'], answer: 0 },
      { q: 'Halliday\'s functional view of change argues…', options: ['Language changes to meet changing communicative needs','Language never changes','Change is purely random','Only grammar changes'], answer: 0 },
      { q: 'Hockett suggested that some change is due to…', options: ['Random fluctuation','Only prescriptive rules','Only lexis','Only grammar'], answer: 0 },
      { q: 'The wave theory of language change describes…', options: ['Change spreading from an epicentre outward, weakening with distance','Change starting everywhere at once','Change stopping suddenly','Change only in writing'], answer: 0 },
      { q: 'The shift in "awful" from "awe-inspiring" to "very bad" illustrates…', options: ['Pejoration','Amelioration','Broadening','Narrowing'], answer: 0 },
      { q: 'The shift in "nice" from "foolish" to "pleasant" illustrates…', options: ['Amelioration','Pejoration','Narrowing','Broadening'], answer: 0 },
      { q: '"Meat" (once any food, now specifically flesh) illustrates…', options: ['Narrowing','Broadening','Amelioration','Pejoration'], answer: 0 },
      { q: '"Dog" (originally a specific breed, now any canine) illustrates…', options: ['Broadening','Narrowing','Amelioration','Pejoration'], answer: 0 },
      { q: 'Which process produces "edit" from "editor"?', options: ['Backformation','Blending','Acronym','Eponym'], answer: 0 },
      { q: '"Text" (verb) from "text" (noun) is an example of…', options: ['Conversion','Blending','Acronym','Eponym'], answer: 0 },
      { q: '"Tsunami" in English is an example of…', options: ['Borrowing from Japanese','Acronym','Eponym','Clipping'], answer: 0 },
      { q: 'The disappearance of "thou/thee/thine" in Early Modern English reflects…', options: ['Simplification of the pronoun system','Only phonological change','Prescriptive rules','Random noise'], answer: 0 },
      { q: 'Singular "they" has been used in English since…', options: ['The 14th century','Only 2020 onwards','Only in America','Only in writing'], answer: 0 },
      { q: 'Which 18th-century grammarians tried to model English on Latin rules?', options: ['Lindley Murray and others','Only Chomsky','Only Johnson','Only Crystal'], answer: 0 },
      { q: 'Which of these is typical of Early Modern English (c.1500–1700)?', options: ['Coexistence of "thou" and "you"; variable spelling','Only Old English runes','No standard at all','Only Middle English'], answer: 0 },
      { q: 'Which is an example of political/inclusive lexical change?', options: ['"Handicapped" → "disabled" → "person with a disability"','"Sun" → "sun"','"Dog" → "dog"','"Cup" → "cup"'], answer: 0 },
      { q: 'A "calque" is…', options: ['A loan translation (e.g. "skyscraper" translated literally into other languages)','An acronym','A blend','A clipping'], answer: 0 },
      { q: '"Google" used as a verb illustrates…', options: ['Conversion + brand to generic','Only acronym','Only eponym','Only clipping'], answer: 0 },
    ],
    red: [
      { q: 'Evaluate: "English is in decline." Which response is MOST linguistically informed?', options: ['Agree fully','Disagree — change is continuous, natural and not decay; "decline" is usually social anxiety dressed as linguistic claim','Partially agree','Only in spelling'], answer: 1 },
      { q: 'Which of Aitchison\'s metaphors critiques the idea that change is caused by older forms crumbling?', options: ['Crumbling castle — Aitchison rejects this as nostalgia','Damp spoon — wrong target','Infectious disease — wrong target','No such metaphor'], answer: 0 },
      { q: 'A descriptivist would likely say "literally" as an intensifier is…', options: ['An error','A case of semantic shift with precedents going back to the 18th century','A spelling mistake','Random'], answer: 1 },
      { q: 'Why is the "golden age" idea of English historically incorrect?', options: ['English has always been varied and changing; no era has been stable or pure','English was once pure','It is correct','Only for Old English'], answer: 0 },
      { q: 'Why does technology only PARTIALLY explain recent language change?', options: ['Social movements, migration and globalisation also drive change','Technology is irrelevant','Only technology matters','Change is random'], answer: 0 },
      { q: 'Top-band exam answers on language change often include…', options: ['Examples from both historical AND contemporary English','Only modern examples','Only old examples','Only spelling'], answer: 0 },
      { q: 'A prescriptivist piece complains about teenagers "ruining" English. An informed descriptivist response would…', options: ['Agree','Provide corpus evidence that shows variation exists but literacy and communicative competence are not eroded; cite Crystal, Tagg, Wood','Ignore data','Silence teenagers'], answer: 1 },
      { q: 'Why is "standardisation" considered sociopolitical as well as linguistic?', options: ['Because which dialect becomes "standard" reflects the power of the region and class whose speech became codified','Because English has no standards','Because it is scientific','Because dialects do not exist'], answer: 0 },
      { q: 'Crystal\'s view on the influence of digital modes is that they…', options: ['Destroy English','Add new registers and orthographic resources; texters draw on creative phonological awareness','Only affect spelling','Freeze English'], answer: 1 },
      { q: 'Which of these is a SOPHISTICATED formulation for Paper 1?', options: ['"The text shows modals of obligation that have become less frequent in informal digital registers, evidencing grammatical change in deontic modality."','"The text has some modals."','"Language is changing."','"Modals are old."'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── 1.3 */
  '1.3': {
    name: 'Global and Regional Variation',
    green: [
      { q: 'Who proposed the "Three Circles" model of World Englishes?', options: ['Braj Kachru','Noam Chomsky','David Crystal','Jennifer Jenkins'], answer: 0 },
      { q: 'Kachru\'s Inner Circle includes countries where English is…', options: ['A native language (UK, US, Australia)','A foreign language','Banned','Only written'], answer: 0 },
      { q: 'Kachru\'s Outer Circle includes countries where English is…', options: ['An institutionalised second language (India, Nigeria, Singapore)','Only Chinese','Only Spanish','Only German'], answer: 0 },
      { q: 'Kachru\'s Expanding Circle includes countries where English is…', options: ['A foreign/international language (China, Brazil, Russia)','A native language','Banned','Dead'], answer: 0 },
      { q: 'What does ELF stand for?', options: ['English as a Lingua Franca','English Literary Form','Early Learning Framework','English Language Foundation'], answer: 0 },
      { q: 'Who is associated with ELF research and the "Lingua Franca Core"?', options: ['Jennifer Jenkins','Lakoff','Chomsky','Skinner'], answer: 0 },
      { q: 'What does MLE stand for?', options: ['Multicultural London English','Modern Literary English','Mixed Latin English','Model Language Example'], answer: 0 },
      { q: 'Which researchers studied MLE in London?', options: ['Jenny Cheshire and Paul Kerswill','Chomsky','Butler','Trudgill'], answer: 0 },
      { q: 'Which of these is a feature of MLE?', options: ['Fronted GOOSE vowel; use of "man" as pronoun; lexis from Caribbean sources','Only RP vowels','Only French lexis','Only Old English forms'], answer: 0 },
      { q: 'What does AAVE stand for?', options: ['African American Vernacular English','All-American Verbal English','Academic American Verbal English','Australian American Variety'], answer: 0 },
      { q: 'Labov argued that AAVE is…', options: ['A rule-governed variety with its own grammar','"Broken English"','A kind of slang','A dead language'], answer: 0 },
      { q: 'A "pidgin" is…', options: ['A simplified contact language with no native speakers','A regional dialect','Only a slang form','Only a formal register'], answer: 0 },
      { q: 'A "creole" is…', options: ['A language that has developed from a pidgin and is now a native language','A type of accent','Only written','A formal register'], answer: 0 },
      { q: 'Jamaican Patois is an example of a…', options: ['Creole','Pidgin','Official academic language','RP accent'], answer: 0 },
      { q: 'Singlish is associated with which country?', options: ['Singapore','Sweden','Switzerland','Spain'], answer: 0 },
      { q: 'Which is a typical feature of Geordie (Tyneside)?', options: ['Use of "pet", "howay"','Use of French grammar','Use of Latin','Only RP vowels'], answer: 0 },
      { q: 'Which is typical of Scouse (Liverpool)?', options: ['Distinctive velar fricatives','Latin forms only','RP vowels only','Only French grammar'], answer: 0 },
      { q: 'Which is typical of Welsh English?', options: ['Sing-song intonation; invariant tag "isn\'t it"','Only French grammar','Only Latin','Only Old English'], answer: 0 },
      { q: 'Which of these is a common US variety?', options: ['Southern American English','Geordie','Cockney','Scouse'], answer: 0 },
      { q: 'David Crystal\'s view on the global spread of English is…', options: ['It has produced multiple "new Englishes" with legitimate norms','English is dying','Only British English is correct','English should be banned'], answer: 0 },
    ],
    amber: [
      { q: 'A criticism of Kachru\'s Three Circles model is that…', options: ['It implies a hierarchy with the Inner Circle as the norm; reality is more fluid','It has no theoretical basis','It ignores English entirely','It is only about Latin'], answer: 0 },
      { q: 'Jennifer Jenkins\' "Lingua Franca Core" argues that…', options: ['Only certain phonological features are essential for intelligibility in ELF','RP is the only acceptable model','Grammar is irrelevant','Writing is key'], answer: 0 },
      { q: 'Cheshire et al. (2011) argued MLE emerged primarily through…', options: ['Dense multiethnic peer networks in inner London','TV alone','Government policy','Parental correction'], answer: 0 },
      { q: 'Which Caribbean feature contributed to MLE lexis?', options: ['"Mandem", "ting" — borrowings from Jamaican Patois','Only Latin','Only Old English','Only French'], answer: 0 },
      { q: 'Which of these is a feature of Indian English?', options: ['"Prepone" (opposite of postpone); invariant tag "isn\'t it"','Old English grammar','Only RP vowels','Hebrew lexis'], answer: 0 },
      { q: 'Singlish often shows influence from which languages?', options: ['Malay, Hokkien, Tamil, Cantonese','Only English','Only Latin','Only Arabic'], answer: 0 },
      { q: 'Which term describes the study of how groups use multiple languages as a single repertoire?', options: ['Translanguaging (García)','Only code-switching','Only borrowing','Only standardisation'], answer: 0 },
      { q: 'A "lectal continuum" ranges from which to which?', options: ['Basilect (furthest from standard) through mesolect to acrolect (closest)','Old English to Modern English','Latin to French','Dialect to accent'], answer: 0 },
      { q: 'Labov\'s work on AAVE was influential in which 1979 US court decision?', options: ['The Ann Arbor decision','Brown v. Board','Roe v. Wade','None'], answer: 0 },
      { q: 'Which of these is a feature of AAVE?', options: ['Habitual "be" ("she be working"); copula deletion','Only Latin forms','Only RP vowels','Only Old English'], answer: 0 },
      { q: 'Giles\'s ethnolinguistic vitality depends on…', options: ['Demographic strength, institutional support, and status','Only spelling','Only grammar','Only accent'], answer: 0 },
      { q: 'Code-switching differs from code-mixing in that it…', options: ['Typically occurs at clause boundaries, not within words/phrases','Is random','Is only in writing','Does not exist'], answer: 0 },
      { q: 'A tabloid labelling MLE "jafaican" is an example of…', options: ['Standard-language ideology dressed as linguistic claim','A linguistic fact','A corpus study','A formal definition'], answer: 0 },
      { q: 'Which of these features characterise Nigerian English?', options: ['"Go-slow" = traffic jam; distinctive modal use','Only French grammar','Only Latin','Only RP'], answer: 0 },
      { q: 'Which is typical of Scottish English?', options: ['Rolled /r/, "wee", "bairn"','Only French grammar','Only Old English','Hebrew lexis'], answer: 0 },
      { q: 'The "bath/trap" split in UK English distinguishes…', options: ['Northern short /a/ from Southern long /ɑː/','French from Latin','Writing from speech','Only children from adults'], answer: 0 },
      { q: 'Paul Kerswill\'s work shows that new varieties can emerge in…', options: ['New towns (Milton Keynes) and ethnically diverse urban areas','Isolated rural areas only','Only in classrooms','Only in the South'], answer: 0 },
      { q: 'Which of these is a feature of Caribbean English / Jamaican Creole?', options: ['"Mi" for "I"; copula deletion; aspectual markers','Only Old English forms','Only RP vowels','Only Latin'], answer: 0 },
      { q: 'Translanguaging (García) challenges the idea that…', options: ['Languages are discrete bounded systems','Only children learn languages','Only adults code-switch','Grammar exists'], answer: 0 },
      { q: 'The representation of AAVE as "broken" is a case of…', options: ['Racialised standard-language ideology, not linguistic fact','A grammatical error','A scientific finding','A phonological study'], answer: 0 },
    ],
    red: [
      { q: 'Evaluate: "The global spread of English threatens other languages." Which answer is MOST balanced?', options: ['Agree fully','Mixed — English\'s role has contributed to endangerment in some contexts, but local languages adapt and hybridise; outcomes depend on specific sociopolitical conditions','Disagree fully','No effect'], answer: 1 },
      { q: 'Why does treating AAVE as "broken English" fail as linguistics?', options: ['AAVE follows systematic rules (Labov); calling it broken confuses social judgement with linguistic fact','It is broken','Only Old English is a language','It does not have a grammar'], answer: 0 },
      { q: 'A top-band answer on MLE typically integrates…', options: ['Features + theorists (Cheshire, Kerswill) + social context (peer networks) + identity analysis + reflection on media panics','Only slang','Only history','Only RP'], answer: 0 },
      { q: 'Why might Inner-Circle norms be inappropriate targets for ELF speakers?', options: ['Most global English communication happens between non-native speakers, and Inner-Circle accents are not intrinsically more intelligible (Jenkins)','Inner-Circle is always best','Grammar does not exist','Accents are fixed'], answer: 0 },
      { q: 'Why is "dialect levelling" not the same as "dialect death" in the UK?', options: ['Local identities persist; new varieties (MLE) emerge; levelling reshapes but does not erase variation','They are the same','No dialects remain','The UK has no dialects'], answer: 0 },
      { q: 'Which framework helps analyse gendered labels such as "jafaican"?', options: ['Standard-language ideology + verbal hygiene (Milroy, Cameron)','Only phonology','Only grammar','Only lexis'], answer: 0 },
      { q: 'How should an analysis of a text sample from World Englishes best proceed?', options: ['Identify features at phonology/lexis/grammar/discourse levels; engage with historical and social context; avoid deficit framing','Only translate','Only count words','Ignore context'], answer: 0 },
      { q: 'Kachru\'s framework is most useful when…', options: ['Combined with attention to fluid, real-world usage and the legitimacy of local norms','Applied rigidly','Used only for Latin','Used only for Middle English'], answer: 0 },
      { q: 'The Ebonics debate (1996) illustrates…', options: ['How linguistic facts about AAVE were filtered through racialised ideologies in policy','Only grammar','Only spelling','Only phonology'], answer: 0 },
      { q: 'Why are "new Englishes" (Crystal) linguistically legitimate?', options: ['They are rule-governed, community-used, and serve communicative and identity functions in their contexts','They are random','They are accidental','They are dead'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── 2.1 */
  '2.1': {
    name: "Children's Spoken Language Development",
    green: [
      { q: 'At approximately what age do most children produce their first recognisable words?', options: ['3 months','6 months','12 months','24 months'], answer: 2 },
      { q: 'What is the "holophrastic" stage?', options: ['The stage where one word represents a whole idea (12–18 months)','Complex sentences only','Silent reading','Writing paragraphs'], answer: 0 },
      { q: 'The two-word stage typically occurs around…', options: ['6 months','18–24 months','3 years','5 years'], answer: 1 },
      { q: 'The telegraphic stage is characterised by…', options: ['Short utterances missing function words','Full grammatical sentences','Only verbs','Complex subordination'], answer: 0 },
      { q: 'Who proposed the Language Acquisition Device (LAD)?', options: ['Noam Chomsky','Skinner','Piaget','Bruner'], answer: 0 },
      { q: 'Who is associated with the behaviourist theory of language acquisition?', options: ['B.F. Skinner','Chomsky','Piaget','Halliday'], answer: 0 },
      { q: 'Piaget\'s theory links language to…', options: ['Cognitive development','Positive reinforcement alone','Imitation only','Nothing'], answer: 0 },
      { q: 'Who proposed the Language Acquisition Support System (LASS)?', options: ['Jerome Bruner','Chomsky','Skinner','Halliday'], answer: 0 },
      { q: 'Vygotsky is associated with which concept?', options: ['Zone of Proximal Development (ZPD) and social interaction','Only grammar','Only phonology','Only writing'], answer: 0 },
      { q: 'What are Halliday\'s "functions of language"?', options: ['Categories describing why children use language','Grammar rules','Punctuation','Spelling rules'], answer: 0 },
      { q: 'Halliday\'s "instrumental" function means children use language to…', options: ['Express needs (e.g. "want milk")','Greet others','Tell stories','Ask questions'], answer: 0 },
      { q: 'Child-directed speech (CDS) is also known as…', options: ['Motherese / parentese','Telegraphic speech','Academic English','Old English'], answer: 0 },
      { q: 'Which is a feature of child-directed speech?', options: ['Higher pitch, exaggerated intonation, slower tempo','Only complex subordination','Only Latinate lexis','Only passive voice'], answer: 0 },
      { q: 'A "virtuous error" is…', options: ['A grammatical overgeneralisation showing rule learning (e.g. "goed")','A deliberate mistake','A pronunciation error only','A spelling mistake'], answer: 0 },
      { q: 'At approximately what age is most core grammar mastered?', options: ['18 months','3–5 years','10 years','16 years'], answer: 1 },
      { q: 'Who conducted the "wug test" (1958)?', options: ['Jean Berko','Chomsky','Skinner','Piaget'], answer: 0 },
      { q: 'The wug test shows that children…', options: ['Apply grammatical rules to novel words','Cannot learn plurals','Only imitate adults','Speak randomly'], answer: 0 },
      { q: 'The critical period hypothesis is associated with…', options: ['Eric Lenneberg','Chomsky','Halliday','Butler'], answer: 0 },
      { q: 'The case of Genie supports…', options: ['The critical period hypothesis','Behaviourism only','Prescriptivism','Nothing'], answer: 0 },
      { q: 'An "overextension" occurs when a child…', options: ['Uses a word more broadly than in adult speech','Uses too many pronouns','Speaks too quickly','Stops speaking'], answer: 0 },
    ],
    amber: [
      { q: 'Skinner\'s behaviourism explains acquisition via…', options: ['Imitation, reinforcement and conditioning','Innate structures','Only phonology','Only writing'], answer: 0 },
      { q: 'A common criticism of behaviourism is that it cannot explain…', options: ['Virtuous errors — children produce forms they have never heard','Spelling','Writing','Reading'], answer: 0 },
      { q: 'Chomsky\'s evidence for the LAD includes…', options: ['Speed of acquisition, virtuous errors, poverty of the stimulus, universal features across languages','Only phonology','Only writing','Only pronunciation'], answer: 0 },
      { q: 'Vygotsky\'s ZPD is the gap between…', options: ['What a child can do alone and with guidance from a more competent partner','Infancy and adolescence','Reading and writing','Native and foreign language'], answer: 0 },
      { q: 'Bruner\'s LASS emphasises the role of…', options: ['Caregivers scaffolding language through joint attention and routines','Innate structures alone','Only punishment','Only grammar lessons'], answer: 0 },
      { q: 'The Halliday function where a child explores and classifies the world is…', options: ['Representational / heuristic','Regulatory','Phatic','Instrumental'], answer: 0 },
      { q: 'The "imaginative" function in Halliday\'s framework refers to…', options: ['Play and fantasy language','Stating facts','Asking for things','Social greetings'], answer: 0 },
      { q: 'Which is a feature of child-directed speech supporting acquisition according to Bruner?', options: ['Repetition, simplified syntax, exaggerated prosody to invite turns','Complex subordination','Latin lexis','Legal jargon'], answer: 0 },
      { q: 'Katherine Nelson (1973) categorised toddlers\' first 50 words, finding the most common category was…', options: ['Specific nominals (mummy, doggy)','Verbs','Prepositions','Conjunctions'], answer: 0 },
      { q: 'A child saying "fis" for "fish" but rejecting an adult saying "fis" illustrates…', options: ['The fis phenomenon — perception precedes production','Random noise','Only phonology','Only lexis'], answer: 0 },
      { q: 'An "underextension" occurs when a child…', options: ['Uses a word more narrowly than in adult speech','Uses too many synonyms','Speaks too quickly','Uses adult grammar'], answer: 0 },
      { q: 'Which milestone is typical of the post-telegraphic stage (3+ years)?', options: ['Function words + emerging complex sentences','Only babbling','Only one-word utterances','Only telegraphic utterances'], answer: 0 },
      { q: 'Colwyn Trevarthen\'s work on "proto-conversations" suggests…', options: ['Infants and caregivers engage in turn-taking even pre-verbally','Infants do not interact','Only adults turn-take','Babies are silent'], answer: 0 },
      { q: 'Michael Tomasello\'s "usage-based" theory argues…', options: ['Grammar is learned from patterns in input; joint attention is central','Only genetics matters','Only imitation','Nothing innate'], answer: 0 },
      { q: 'The "poverty of the stimulus" argument supports…', options: ['Nativism (Chomsky)','Behaviourism','Only interactionism','Only Halliday'], answer: 0 },
      { q: 'The case of "Jim" (hearing child of deaf parents exposed to language via TV) showed that…', options: ['Input alone is insufficient — interactional input is needed','TV teaches grammar perfectly','Only Old English matters','Input does not matter'], answer: 0 },
      { q: 'At what age are most children typically in the telegraphic stage?', options: ['2–3 years','6 months','10 years','16 years'], answer: 0 },
      { q: 'Which of these is often an early PHONOLOGICAL feature?', options: ['Cluster reduction ("poon" for "spoon")','Only long sentences','Only RP vowels','Only writing'], answer: 0 },
      { q: 'A child who says "mouses" has shown…', options: ['A virtuous error overgeneralising regular plural "-s"','Imitation of an adult','A spelling mistake','An unrelated phoneme'], answer: 0 },
      { q: 'Which of these is a key feature of Bruner\'s LASS?', options: ['Joint attention, recasting, expansion, routines','Only grammar lessons','Only formal reading','Only writing'], answer: 0 },
    ],
    red: [
      { q: 'Evaluate: "Language acquisition is purely innate — input plays no role." Is this correct?', options: ['Yes','No — interactionists (Bruner, Vygotsky) show rich, scaffolded input is essential; nativist and social views complement each other','Yes — Skinner proved it','No — input is all'], answer: 1 },
      { q: 'Why is behaviourism alone insufficient as an explanation?', options: ['Children produce novel utterances and virtuous errors that pure imitation cannot explain','It explains everything','It covers only grammar','There is no criticism'], answer: 0 },
      { q: 'Compare Chomsky and Bruner. The main difference is that…', options: ['Chomsky emphasises innate LAD; Bruner emphasises socially-scaffolded LASS — they are complementary','They are identical','Chomsky studied writing only','Bruner rejected input'], answer: 0 },
      { q: 'Why is child-directed speech (CDS) considered supportive of acquisition?', options: ['Exaggerated prosody foregrounds sound; simplified syntax makes structure learnable; repetition consolidates; pauses invite turns','It has no effect','Formal register is best','Silence is best'], answer: 0 },
      { q: 'A child says "Daddy gone shop". How would a linguist analyse this?', options: ['Telegraphic stage — content words kept, function words/inflections omitted; correct word order shows basic syntactic knowledge','It is ungrammatical','Only post-telegraphic','Babbling'], answer: 0 },
      { q: 'Evaluate the case of Genie as evidence for the critical period.', options: ['Strong evidence — isolated past puberty, she never achieved adult grammar despite some lexis','No evidence','Evidence only for phonology','Against the hypothesis'], answer: 0 },
      { q: 'Why do top-band A-level answers integrate multiple theorists?', options: ['No single theory explains acquisition; Chomsky + Bruner + Halliday + Tomasello jointly cover innate, social, functional and usage dimensions','Only one theory is correct','Only Skinner matters','Only Halliday'], answer: 0 },
      { q: 'Why is the observer\'s paradox important in child-language research?', options: ['Children may behave differently when recorded — researchers must acknowledge and mitigate this','It is irrelevant','It only applies to adults','It helps research'], answer: 0 },
      { q: 'Which of these is the BEST interpretation of "I goed"?', options: ['Virtuous error — the child has mastered the regular rule and is overgeneralising to an irregular verb','A random mistake','An imitation','A spelling issue'], answer: 0 },
      { q: 'A strong Paper 2 transcript answer typically…', options: ['Identifies stage, applies frameworks at multiple linguistic levels, names 2+ theorists, discusses the caregiver\'s scaffolding, and evaluates cautiously','Only names the stage','Only lists features','Only counts words'], answer: 0 },
    ],
  },

  /* ─────────────────────────────────────────────────────────── 2.2 */
  '2.2': {
    name: "Children's Written Language Development",
    green: [
      { q: 'What is "emergent writing"?', options: ['Early mark-making / scribbling that shows awareness of writing as symbols','Only typing','Formal handwriting lessons','Dictation'], answer: 0 },
      { q: 'Kroll proposed how many stages of writing development?', options: ['Two','Three','Four','Five'], answer: 2 },
      { q: 'Kroll\'s stages are (in order)…', options: ['Preparation → consolidation → differentiation → integration','Imitation → creation → editing → publishing','Scribble → copying','Random → ordered'], answer: 0 },
      { q: 'Kroll\'s "preparation" stage is roughly…', options: ['Up to age 6 — motor skills + letter-sound links','Teenage years','Only university','Adulthood'], answer: 0 },
      { q: 'Kroll\'s "consolidation" stage involves…', options: ['Writing resembling speech — coordination with "and"','Formal legal prose','Academic essays','Formal letters'], answer: 0 },
      { q: 'Kroll\'s "differentiation" stage is when children…', options: ['Begin separating written and spoken styles','Only use one style','Stop writing','Write identical to speech'], answer: 0 },
      { q: 'Kroll\'s "integration" stage refers to…', options: ['Mastery of multiple styles / genres adapted to audience','Only narrative','Only editing','Only copying'], answer: 0 },
      { q: 'Britton proposed three functions of writing. The first is…', options: ['Expressive','Scientific','Legal','Numerical'], answer: 0 },
      { q: 'Britton\'s "expressive" function is writing that…', options: ['Is close to personal voice / speech','Is purely formal','Is only for academic essays','Is only argumentative'], answer: 0 },
      { q: 'Britton\'s "transactional" function is writing that…', options: ['Conveys information or persuades','Is only poetic','Is only literary','Is only scribble'], answer: 0 },
      { q: 'Britton\'s "poetic" function refers to…', options: ['Crafted writing attending to form and pattern','Only poetry','Only adverts','Only recipes'], answer: 0 },
      { q: 'Rothery classified children\'s narrative writing into categories including…', options: ['Recount, report, narrative, observation/comment','Only fiction','Only letter','Only report'], answer: 0 },
      { q: 'A "recount" in Rothery\'s framework…', options: ['Retells a past experience chronologically','Argues a position','Gives a scientific report','Reviews a film'], answer: 0 },
      { q: 'A "narrative" in Rothery\'s framework typically has…', options: ['Orientation, complication, resolution','Only a greeting','Only facts','Only statistics'], answer: 0 },
      { q: 'Gentry\'s "phonetic" spelling stage involves…', options: ['Spelling words as they sound ("kum" for "come")','Copying exactly','Random letters','Adult spelling'], answer: 0 },
      { q: 'Which writing skill typically develops LATER than letter formation?', options: ['Punctuation and paragraphing','Holding a pencil','Recognising one\'s own name','Making marks'], answer: 0 },
      { q: 'Early writers tend to omit which grammatical feature?', options: ['Function words (articles, auxiliaries)','Nouns only','Verbs only','Adjectives only'], answer: 0 },
      { q: 'Early fictional writing by children typically shows…', options: ['Heavy coordination with "and", "then"','Complex subordination','Legal register','Academic prose'], answer: 0 },
      { q: 'Which genre is typically easier for children to acquire first?', options: ['Recount','Analytical essay','Legal text','Scientific paper'], answer: 0 },
      { q: 'An "observation/comment" genre includes…', options: ['Observation of an event plus an evaluative comment','Only instructions','Only narrative','Only recount'], answer: 0 },
    ],
    amber: [
      { q: 'A 7-year-old\'s writing with repeated "and then" is MOST likely at which Kroll stage?', options: ['Consolidation — writing reflects speech patterns','Integration','Differentiation','Preparation'], answer: 0 },
      { q: 'Why might a child at the differentiation stage use passive constructions?', options: ['Imitation of adult formal registers — awareness that written style differs from speech','They are confused','They are underdeveloped','They cannot use active'], answer: 0 },
      { q: 'Punctuation in early writing is often…', options: ['Used to mark prosody (pauses) rather than syntactic boundaries','Mastered by age 5','Never used','Only commas'], answer: 0 },
      { q: 'Frequent "and then" as a connector reflects…', options: ['Temporal coordination typical of early narrative writing','Mature writing','Academic prose','Formal writing'], answer: 0 },
      { q: 'A teacher scaffolding a recount by asking "who was there? what happened first?" applies which theorist?', options: ['Bruner — explicit scaffolding','Skinner — reinforcement only','Chomsky — LAD','None'], answer: 0 },
      { q: 'A child\'s story with orientation + complication + resolution demonstrates…', options: ['Rothery\'s narrative genre structure','Only grammar','Pre-communicative stage','Scribble'], answer: 0 },
      { q: 'Frequent letter reversals (b/d) in early writing suggest…', options: ['Normal early development — reversals decrease with experience','Disability','Refusal to learn','Intentional style'], answer: 0 },
      { q: 'Which is a feature of INTEGRATION-stage writing?', options: ['Variety of sentence types, appropriate register for audience, consistent paragraphing','Only simple sentences','Speech-like coordination only','Scribble'], answer: 0 },
      { q: 'Britton\'s "expressive" function is typical of…', options: ['Early writing — close to speech','Legal writing','Academic essay','Only adult writing'], answer: 0 },
      { q: 'A child writing a formal letter deliberately shifts register. Which Kroll stage is this?', options: ['Differentiation or integration','Only consolidation','Only preparation','Not Kroll\'s'], answer: 0 },
      { q: 'Teacher feedback often moves from spelling → cohesion → paragraphing because…', options: ['Once basic orthography is stable, textual metafunction (Halliday) becomes the next priority','Spelling is irrelevant','It is random','Only spelling matters'], answer: 0 },
      { q: 'Rothery\'s genre framework is associated with…', options: ['The Sydney School — explicit genre pedagogy','Only Chomsky','Only Halliday','Only Labov'], answer: 0 },
      { q: 'Early writing typically lacks which feature of mature prose?', options: ['Signalling of stance and evaluation (modality, hedges)','Nouns','Letters','Word spacing'], answer: 0 },
      { q: 'A student who consciously adjusts style between a diary entry and a news report has reached…', options: ['Kroll\'s differentiation stage','Only consolidation','Only preparation','Pre-phonetic'], answer: 0 },
      { q: 'An emergent writer producing strings of letter-like shapes with spaces shows…', options: ['Awareness that writing consists of discrete symbols arranged spatially','Imitation only','Pre-communicative random noise','Adult writing'], answer: 0 },
      { q: 'Vygotsky\'s ZPD for a child writer means…', options: ['Tasks just beyond independent competence, achievable with modelling','Tasks already mastered','Tasks at university level','No support needed'], answer: 0 },
      { q: 'Digital communication affects children\'s writing by…', options: ['Introducing new orthographic features (abbreviations, emoji) and additional registers — research shows no collapse in standard writing','Destroying it','Replacing it','Freezing it'], answer: 0 },
      { q: 'A Year 6 child using past perfect ("had been waiting") in a story demonstrates…', options: ['Integration-stage tense variation for narrative time','Consolidation only','Pre-communicative','Only preparation'], answer: 0 },
      { q: 'Britton\'s transactional function is typical of…', options: ['Planned reader-focused writing — informative or persuasive','Only diaries','Only poems','Only dialogue'], answer: 0 },
      { q: 'Rothery\'s genre pedagogy is seen as important for equity because…', options: ['Explicit teaching of school-valued genres reduces disadvantage for children from less literacy-rich homes','It bans creativity','It focuses only on spelling','It is irrelevant'], answer: 0 },
    ],
    red: [
      { q: 'Evaluate: "Children\'s writing follows fixed stages." Discuss.', options: ['Yes — stages are rigid','Partially — Kroll\'s stages describe tendencies; individual variation and cultural factors affect trajectories','No — stages do not exist','Stages are random'], answer: 1 },
      { q: 'Why do Kroll\'s stages still matter for teaching?', options: ['They help teachers match scaffolding to the learner\'s stage (e.g. consolidation vs integration)','They replace all feedback','They are irrelevant','Only the last stage matters'], answer: 0 },
      { q: 'Compare Britton\'s and Rothery\'s models.', options: ['Britton focuses on writer purpose (expressive/transactional/poetic); Rothery on schematic genre structures; combining them gives both intention and cultural form','They are identical','They contradict','They are about speech'], answer: 0 },
      { q: 'Why is genre pedagogy considered influential?', options: ['Explicit teaching of genre gives learners access to valued forms, reducing the disadvantage of home backgrounds less aligned with school literacies','It bans creativity','It focuses only on spelling','It is historical only'], answer: 0 },
      { q: 'Evaluate: "Digital communication harms children\'s writing development." What is the most linguistically informed response?', options: ['Mixed — new orthographic features are added registers; research (Crystal, Tagg) shows no widespread literacy decline in educated users','Strongly agree','Digital is irrelevant','Only in spelling'], answer: 0 },
      { q: 'A child produces a beautiful poem but struggles with an analytical essay. What insight is useful?', options: ['Britton shows development can differ across functions; pedagogy should target transactional writing specifically','They have failed','They should only write poems','They need more phonology'], answer: 0 },
      { q: 'What are the LIMITS of stage models (Kroll) for describing writing?', options: ['Individual variation; cultural/SES factors; stages overlap in practice','There are no limits','They are perfect','They do not exist'], answer: 0 },
      { q: 'How does Vygotsky\'s ZPD apply to writing pedagogy?', options: ['Tasks set just beyond independent competence with explicit modelling, shared writing, peer collaboration; support fades with growth','It does not apply','Only applies to speech','Only applies to phonology'], answer: 0 },
      { q: 'Top-band Year 6 narrative writing typically shows…', options: ['Fronted adverbials, complex noun phrases, tense variation, deliberate minor sentences for rhythm','Only simple coordination','Only random words','Only capital letters'], answer: 0 },
      { q: 'An integrated A-level answer on a child\'s writing piece typically applies…', options: ['Kroll (stage) + Britton (function) + Rothery (genre) + Halliday (metafunction) + named linguistic features','Only Kroll','Only Rothery','Only spelling'], answer: 0 },
    ],
  },

};
